SplitReturn Class Reference
STL include.
#include <split_return.hpp>
Public Member Functions
SplitReturn (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~SplitReturn () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
STL include.
Structure the original short circuit
Definition at line 72 of file split_return.hpp.
Constructor & Destructor Documentation
SplitReturn()
SplitReturn::SplitReturn (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Behavior include Parameter include HLS include parser/treegcc include STD include STL include tree includes
Definition at line 86 of file split_return.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~SplitReturn().
 SplitReturn()
SplitReturn::~SplitReturn () [override], [default]
Destructor.
Referenced by SplitReturn().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > SplitReturn::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 94 of file split_return.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SWITCH_FIX, THROW_UNREACHABLE, USE_COUNTING, and FrontendFlowStep::WHOLE_APPLICATION.
HasToBeExecuted()
bool SplitReturn::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 128 of file split_return.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), and DesignFlowStep::parameters.
InternalExec()
DesignFlowStep_Status SplitReturn::InternalExec () [override], [virtual]
Restructures the unstructured code.
Implements FunctionFrontendFlowStep.
Definition at line 190 of file split_return.cpp.
References FrontendFlowStep::AppM, create_return_and_fix_cfg(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, statement_list::list_of_bloc, STR, SUCCESS, TOK, TOK_MEMUSE, TOK_OP, TOK_SCPE, TOK_SRCP, and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/split_return.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/split_return.cpp