CallGraphBuiltinCall Class Reference
Pass to add function called through pointers to the call graph.
#include <call_graph_builtin_call.hpp>
Public Member Functions
CallGraphBuiltinCall (const application_managerRef AM, unsigned int functionId, const DesignFlowManagerConstRef DFM, const ParameterConstRef P)
Ctor.
~CallGraphBuiltinCall () override
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (DesignFlowStep::RelationshipType RT) const override
State relationship with other design step.
Private Types
typedef std::map< std::string, CustomOrderedSet< unsigned int > > TypeDeclarationMap
Private Member Functions
void lookForBuiltinCall (const tree_nodeRef TN)
void ExtendCallGraph (unsigned int callerIdx, tree_nodeRef funType, unsigned int stmtIdx)
Private Attributes
bool modified
TypeDeclarationMap typeToDeclaration
Map function types to matching declarations.
Additional Inherited Members
Detailed Description
Pass to add function called through pointers to the call graph.
Definition at line 49 of file call_graph_builtin_call.hpp.
Member Typedef Documentation
TypeDeclarationMap
typedef std::map<std::string, CustomOrderedSet<unsigned int> > CallGraphBuiltinCall::TypeDeclarationMap [private]
Definition at line 52 of file call_graph_builtin_call.hpp.
Constructor & Destructor Documentation
CallGraphBuiltinCall()
CallGraphBuiltinCall::CallGraphBuiltinCall (const application_managerRef AM, unsigned int functionId, const DesignFlowManagerConstRef DFM, const ParameterConstRef P)
Ctor.
Parameters
AM Application Manager
functionId Function id of the analyzed function.
DFM Design Flow Manager
P Set of parameters
Definition at line 272 of file call_graph_builtin_call.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~CallGraphBuiltinCall().
 CallGraphBuiltinCall()
CallGraphBuiltinCall::~CallGraphBuiltinCall () [override], [default]
Referenced by CallGraphBuiltinCall().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, CallGraphBuiltinCall::FunctionRelationship > > CallGraphBuiltinCall::ComputeFrontendRelationships (DesignFlowStep::RelationshipType RT) const [override], [protected], [virtual]
State relationship with other design step.
Parameters
RT Type of the relationship to be considered
Implements FrontendFlowStep.
Definition at line 247 of file call_graph_builtin_call.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, FUNCTION_ANALYSIS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
ExtendCallGraph()
void CallGraphBuiltinCall::ExtendCallGraph (unsigned int callerIdx, tree_nodeRef funType, unsigned int stmtIdx) [private]
Definition at line 237 of file call_graph_builtin_call.cpp.
References FrontendFlowStep::AppM, tree_node::index, FunctionEdgeInfo::indirect_call, modified, tree_helper::print_type(), test_panda::type, and typeToDeclaration.
Referenced by lookForBuiltinCall().
Initialize()
void CallGraphBuiltinCall::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 280 of file call_graph_builtin_call.cpp.
References modified, and typeToDeclaration.
InternalExec()
DesignFlowStep_Status CallGraphBuiltinCall::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 286 of file call_graph_builtin_call.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeNode(), INDENT_DBG_MEX, lookForBuiltinCall(), modified, tree_helper::name_function(), DesignFlowStep::parameters, tree_helper::print_type(), STR, SUCCESS, test_panda::type, typeToDeclaration, UNCHANGED, and tree_node::visit().
lookForBuiltinCall()
void CallGraphBuiltinCall::lookForBuiltinCall (const tree_nodeRef TN) [private]
Definition at line 57 of file call_graph_builtin_call.cpp.
References FrontendFlowStep::AppM, test_panda::args, call_expr::args, gimple_call::args, BUILTIN_WAIT_CALL, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, ExtendCallGraph(), call_expr::fn, gimple_call::fn, FunctionEdgeInfo::function_address, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, getFunctionPointerType(), INDENT_DBG_MEX, tree_node::index, FunctionEdgeInfo::indirect_call, modified, tree_helper::name_function(), STR, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by InternalExec().
Field Documentation
modified
bool CallGraphBuiltinCall::modified [private]
Definition at line 53 of file call_graph_builtin_call.hpp.
Referenced by ExtendCallGraph(), Initialize(), InternalExec(), and lookForBuiltinCall().
typeToDeclaration
TypeDeclarationMap CallGraphBuiltinCall::typeToDeclaration [private]
Map function types to matching declarations.
Definition at line 58 of file call_graph_builtin_call.hpp.
Referenced by ExtendCallGraph(), Initialize(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/call_graph_builtin_call.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/call_graph_builtin_call.cpp