HLSInstructionWriter Class Reference
#include <hls_instruction_writer.hpp>
Public Member Functions
HLSInstructionWriter (const application_managerConstRef app_man, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters)
Constructor.
~HLSInstructionWriter () override
Destructor.
void declareFunction (const unsigned int function_id) override
Write the declaration of a function.
Additional Inherited Members
Detailed Description
Definition at line 56 of file hls_instruction_writer.hpp.
Constructor & Destructor Documentation
HLSInstructionWriter()
HLSInstructionWriter::HLSInstructionWriter (const application_managerConstRef _app_man, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
app_man is the application manager
indented_output_stream is the output stream on which source code has to be written
parameters is the set of input parameters
behavior include tree include utility include Backend include Parameter include
Definition at line 70 of file hls_instruction_writer.cpp.
References ~HLSInstructionWriter().
 HLSInstructionWriter()
HLSInstructionWriter::~HLSInstructionWriter () [override], [default]
Destructor.
Referenced by HLSInstructionWriter().
Member Function Documentation
declareFunction()
void HLSInstructionWriter::declareFunction (const unsigned int function_id) [override], [virtual]
Write the declaration of a function.
Parameters
function_id is the index of the function
the assumption is strong but the code that prints the name of the function is under our control ;-)
Reimplemented from InstructionWriter.
Definition at line 76 of file hls_instruction_writer.cpp.
References IndentedOutputStream::Append(), InstructionWriter::AppM, tree_node::get_kind(), GET_NODE, InstructionWriter::indented_output_stream, InstructionWriter::parameters, string_demangle(), and THROW_ASSERT.
Referenced by discrepancy_instruction_writer::declareFunction().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/hls_instruction_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/hls_instruction_writer.cpp