NanoXploreBackendFlow Class Reference
#include <NanoXploreBackendFlow.hpp>
Public Member Functions
NanoXploreBackendFlow (const ParameterConstRef Param, const std::string &flow_name, const target_managerRef manager)
Constructor.
~NanoXploreBackendFlow () override
Destructor.
void InitDesignParameters () override
Initializes the parameters.
void ExecuteSynthesis () override
Checks if the execution can be performed and, in case, performs the synthesis.
Protected Member Functions
void WriteFlowConfiguration (std::ostream &script) override
Writes the proper flow configuration in the output script.
void xparse_utilization (const std::string &fn)
Parses device utilization.
void CheckSynthesisResults () override
Checks the synthesis results and fills the corresponding datastructures.
Protected Attributes
std::map< std::string, double > design_values
results from the synthesis
Additional Inherited Members
Detailed Description
Definition at line 55 of file NanoXploreBackendFlow.hpp.
Constructor & Destructor Documentation
NanoXploreBackendFlow()
NanoXploreBackendFlow::NanoXploreBackendFlow (const ParameterConstRef Param, const std::string & flow_name, const target_managerRef manager)
Constructor.
Definition at line 82 of file NanoXploreBackendFlow.cpp.
References BackendFlow::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, BackendFlow::default_data, GET_CLASS, target_device::get_parameter(), target_device::has_parameter(), INDENT_DBG_MEX, INDENT_OUT_MEX, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, BackendFlow::Param, BackendFlow::parse_flow(), test_panda::parser, BackendFlow::target, THROW_ERROR, and ~NanoXploreBackendFlow().
 NanoXploreBackendFlow()
NanoXploreBackendFlow::~NanoXploreBackendFlow () [override], [default]
Destructor.
Referenced by NanoXploreBackendFlow().
Member Function Documentation
CheckSynthesisResults()
void NanoXploreBackendFlow::CheckSynthesisResults () [override], [protected], [virtual]
Checks the synthesis results and fills the corresponding datastructures.
Implements BackendFlow.
Definition at line 201 of file NanoXploreBackendFlow.cpp.
References BackendFlow::actual_parameters, BackendFlow::area_m, clb_model::BRAM, LUT_model::COMBINATIONAL_DELAY, CopyStdout(), area_model::create_model(), time_model::create_model(), design_values, clb_model::DSP, ExistFile(), FPGA, clb_model::FUNCTIONAL_ELEMENTS, NANOXPLORE_DSP, NANOXPLORE_FE, NANOXPLORE_LUTS, NANOXPLORE_MEM, NANOXPLORE_REGISTERS, NANOXPLORE_SLACK, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, OUTPUT_LEVEL_VERY_PEDANTIC, BackendFlow::Param, PARAM_clk_period, PARAM_nxpython_report, PARAM_nxpython_timing_report, DesignParameters::parameter_values, PRINT_OUT_MEX, clb_model::REGISTERS, clb_model::SLICE_LUTS, THROW_ASSERT, THROW_ERROR, BackendFlow::time_m, and xparse_utilization().
ExecuteSynthesis()
void NanoXploreBackendFlow::ExecuteSynthesis () [override], [virtual]
Checks if the execution can be performed and, in case, performs the synthesis.
Reimplemented from BackendFlow.
Definition at line 267 of file NanoXploreBackendFlow.cpp.
References BackendFlow::ExecuteSynthesis(), and THROW_ERROR.
InitDesignParameters()
void NanoXploreBackendFlow::InitDesignParameters () [override], [virtual]
Initializes the parameters.
determine if power optimization has to be performed
Reimplemented from BackendFlow.
Definition at line 276 of file NanoXploreBackendFlow.cpp.
References BackendFlow::actual_parameters, BackendFlow::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, target_device::get_parameter(), INDENT_DBG_MEX, BackendFlow::Param, PARAM_HDL_files, PARAM_nxpython_sources_macro_list, PARAM_power_optimization, PARAM_target_device, DesignParameters::parameter_values, BackendFlow::steps, STR, and BackendFlow::target.
WriteFlowConfiguration()
void NanoXploreBackendFlow::WriteFlowConfiguration (std::ostream & script) [override], [protected], [virtual]
Writes the proper flow configuration in the output script.
Implements BackendFlow.
Definition at line 237 of file NanoXploreBackendFlow.cpp.
References BackendFlow::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, NANOXPLORE_BYPASS_SET, NANOXPLORE_LICENSE_SET, and STR.
xparse_utilization()
void NanoXploreBackendFlow::xparse_utilization (const std::string & fn) [protected]
Parses device utilization.
Definition at line 121 of file NanoXploreBackendFlow.cpp.
References CE_XVM, design_values, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), LOAD_XVM, test_panda::parser, THROW_ASSERT, and THROW_ERROR.
Referenced by CheckSynthesisResults().
Field Documentation
design_values
std::map<std::string, double> NanoXploreBackendFlow::design_values [protected]
results from the synthesis
Definition at line 59 of file NanoXploreBackendFlow.hpp.
Referenced by CheckSynthesisResults(), and xparse_utilization().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/nanoxplore/NanoXploreBackendFlow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/nanoxplore/NanoXploreBackendFlow.cpp