/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Introduction/fifth/top.c File Reference
#include `module_lib.h`
Functions
void my_ip (uint8_t command, uint32_t param1, uint32_t param2)
Function Documentation
my_ip()
void my_ip (uint8_t command, uint32_t param1, uint32_t param2)
Definition at line 3 of file top.c.
References module1(), module2(), module1_output_t::output1, module2_output_t::output1, module1_output_t::output2, module2_output_t::output2, module1_output_t::output3, module2_output_t::output3, module1_output_t::output4, printer1(), and printer2().
Referenced by main().