null_node Struct Reference
#include <ext_tree_node.hpp>
Public Types
enum { GETID =(tree_node) = 0
 }
visitor enum
Public Member Functions
null_node (unsigned int i)
constructor
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Additional Inherited Members
Detailed Description
Definition at line 56 of file ext_tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 76 of file ext_tree_node.hpp.
Constructor & Destructor Documentation
null_node()
null_node::null_node (unsigned int i) [inline], [explicit]
constructor
Definition at line 59 of file ext_tree_node.hpp.
References GET_KIND, GET_KIND_TEXT, and visit().
Member Function Documentation
visit()
void null_node::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from tree_node.
Definition at line 46 of file ext_tree_node.cpp.
References ALL_VISIT, and VISIT_SC.
Referenced by blackbox_pragma::blackbox_pragma(), issue_pragma::issue_pragma(), map_pragma::map_pragma(), null_node(), omp_atomic_pragma::omp_atomic_pragma(), omp_pragma::omp_pragma(), omp_section_pragma::omp_section_pragma(), profiling_pragma::profiling_pragma(), statistical_profiling::statistical_profiling(), gimple_pragma::visit(), profiling_pragma::visit(), statistical_profiling::visit(), call_hw_pragma::visit(), call_point_hw_pragma::visit(), omp_parallel_pragma::visit(), omp_sections_pragma::visit(), omp_parallel_sections_pragma::visit(), and omp_section_pragma::visit().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/ext_tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/ext_tree_node.cpp