CSE Class Reference
CSE analysis.
#include <CSE.hpp>
Public Member Functions
CSE (const ParameterConstRef Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~CSE () override
Destructor.
DesignFlowStep_Status InternalExec () override
perform CSE analysis
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec)
Private Types
typedef std::pair< enum kind, std::vector< unsigned int > > CSE_tuple_key_type
define the type of the unique table key
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
tree_nodeRef hash_check (tree_nodeRef tn, vertex bb)
check if the statement has an equivalent in the unique table
bool check_loads (const gimple_assign *ga, unsigned int right_part_index, tree_nodeRef right_part)
check if the gimple assignment is a load, store or a memcpy/memset
Private Attributes
ScheduleRef schedule
The scheduling solution.
const tree_managerRef TM
tree manager
statement_list * sl
The statement list.
bool restart_phi_opt
when true PHI_OPT step has to restart
std::map< vertex, CustomUnorderedMapStable< CSE_tuple_key_type, tree_nodeRef > > unique_table
define a map relating variables and columns
Additional Inherited Members
Detailed Description
CSE analysis.
Definition at line 89 of file CSE.hpp.
Member Typedef Documentation
CSE_tuple_key_type
typedef std::pair<enum kind, std::vector<unsigned int> > CSE::CSE_tuple_key_type [private]
define the type of the unique table key
Definition at line 107 of file CSE.hpp.
Constructor & Destructor Documentation
CSE()
CSE::CSE (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
_Param is the set of the parameters
_AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
. include boost include behavior includes algorithm/dominance include design_flows include frontend_analysis HLS include STD include tree include wrapper/treegcc include
Definition at line 96 of file CSE.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~CSE().
 CSE()
CSE::~CSE () [override], [default]
Destructor.
Referenced by CSE().
Member Function Documentation
check_loads()
bool CSE::check_loads (const gimple_assign * ga, unsigned int right_part_index, tree_nodeRef right_part) [private]
check if the gimple assignment is a load, store or a memcpy/memset
check for bit field ref of vector type
Definition at line 156 of file CSE.cpp.
References FunctionFrontendFlowStep::function_behavior, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_node(), tree_helper::is_a_pointer(), tree_helper::is_a_vector(), tree_helper::is_an_array(), gimple_assign::op0, and TM.
Referenced by hash_check().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > CSE::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 104 of file CSE.cpp.
References ABORTED, COMPLETE_BB_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, NONEXISTENT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, restart_phi_opt, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, UNNECESSARY, and USE_COUNTING.
hash_check()
tree_nodeRef CSE::hash_check (tree_nodeRef tn, vertex bb) [private]
check if the statement has an equivalent in the unique table
check for LOADs, STOREs, MEMSET, MEMCPY, etc. etc.
We add type of right part; load from same address with different types must be considered different
If there are virtual uses, not only they must be the same, but also the basic block must be the same
Check if the virtual is defined in the same basic block
For each vuse we insert def_stmt if it is before
Definition at line 208 of file CSE.cpp.
References test_panda::arg, gimple_node::bb_index, tree_helper::CGetType(), check_loads(), gimple_assign::clobber, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_CONST_NODE, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), INDENT_DBG_MEX, tree_node::index, gimple_assign::init_assignment, statement_list::list_of_bloc, max(), gimple_node::memdef, gimple_assign::op0, gimple_assign::op1, DesignFlowStep::parameters, tree_helper::Size(), sl, STR, THROW_ASSERT, tree_node::ToString(), unique_table, gimple_node::vdef, gimple_node::vovers, and gimple_node::vuses.
Referenced by InternalExec().
Initialize()
void CSE::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec)
Reimplemented from DesignFlowStep.
Definition at line 555 of file CSE.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, and schedule.
InternalExec()
DesignFlowStep_Status CSE::InternalExec () [override], [virtual]
perform CSE analysis
Returns
the exit status of this step
store the GCC BB graph ala boost::graph
add vertices
add edges
add a connection between entry and exit thus avoiding problems with non terminating code
CSE on basic blocks
Implements FunctionFrontendFlowStep.
Definition at line 389 of file CSE.cpp.
References FrontendFlowStep::AppM, CFG_SELECTOR, BBGraph::CGetBBNodeInfo(), tree_helper::CGetType(), D_SELECTOR, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeReindex(), hash_check(), INDENT_DBG_MEX, tree_node::index, DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), restart_phi_opt, schedule, sl, STR, SUCCESS, THROW_ASSERT, TM, ToString(), tree_node::ToString(), UNCHANGED, unique_table, and Schedule::UpdateTime().
Field Documentation
restart_phi_opt
bool CSE::restart_phi_opt [private]
when true PHI_OPT step has to restart
Definition at line 102 of file CSE.hpp.
Referenced by ComputeFrontendRelationships(), and InternalExec().
schedule
ScheduleRef CSE::schedule [private]
The scheduling solution.
Definition at line 93 of file CSE.hpp.
Referenced by Initialize(), and InternalExec().
sl
statement_list* CSE::sl [private]
The statement list.
Definition at line 99 of file CSE.hpp.
Referenced by hash_check(), and InternalExec().
TM
const tree_managerRef CSE::TM [private]
tree manager
Definition at line 96 of file CSE.hpp.
Referenced by check_loads(), and InternalExec().
unique_table
std::map<vertex, CustomUnorderedMapStable<CSE_tuple_key_type, tree_nodeRef> > CSE::unique_table [private]
define a map relating variables and columns
Definition at line 110 of file CSE.hpp.
Referenced by hash_check(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/CSE.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/CSE.cpp