interface_infer Class Reference
#include <interface_infer.hpp>
Public Member Functions
interface_infer (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~interface_infer () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void Computepar2ssa (statement_list *sl, std::map< unsigned, unsigned > &par2ssa)
void classifyArgRecurse (CustomOrderedSet< unsigned > &Visited, ssa_name *argSSA, unsigned int destBB, statement_list *sl, bool &canBeMovedToBB2, bool &isRead, bool &isWrite, bool &unkwown_pattern, std::list< tree_nodeRef > &writeStmt, std::list< tree_nodeRef > &readStmt)
void classifyArg (statement_list *sl, tree_nodeRef argSSANode, bool &canBeMovedToBB2, bool &isRead, bool &isWrite, bool &unkwown_pattern, std::list< tree_nodeRef > &writeStmt, std::list< tree_nodeRef > &readStmt)
void addGimpleNOPxVirtual (tree_nodeRef origStmt, const tree_managerRef TM)
void create_Read_function (tree_nodeRef refStmt, const std::string &argName_string, tree_nodeRef origStmt, unsigned int destBB, const std::string &fdName, tree_nodeRef argSSANode, tree_nodeRef aType, tree_nodeRef readType, const std::list< tree_nodeRef > &usedStmt_defs, const tree_manipulationRef tree_man, const tree_managerRef TM, bool commonRWSignature)
void create_Write_function (const std::string &argName_string, tree_nodeRef origStmt, const std::string &fdName, tree_nodeRef writeValue, tree_nodeRef aType, tree_nodeRef writeType, const tree_manipulationRef tree_man, const tree_managerRef TM, bool commonRWSignature)
void create_resource_Read_simple (const std::vector< std::string > &operations, const std::string &argName_string, const std::string &interfaceType, unsigned int inputBitWidth, bool IO_port, unsigned n_resources)
void create_resource_Write_simple (const std::vector< std::string > &operations, const std::string &argName_string, const std::string &interfaceType, unsigned int inputBitWidth, bool IO_port, bool isDiffSize, unsigned n_resources)
void create_resource_array (const std::vector< std::string > &operationsR, const std::vector< std::string > &operationsW, const std::string &argName_string, const std::string &interfaceType, unsigned int inputBitWidth, unsigned int arraySize, unsigned n_resources, unsigned alignment)
void create_resource (const std::vector< std::string > &operationsR, const std::vector< std::string > &operationsW, const std::string &argName_string, const std::string &interfaceType, unsigned int inputBitWidth, bool isDiffSize, const std::string &fname, unsigned n_resources, unsigned alignment)
void ComputeResourcesAlignment (unsigned &n_resources, unsigned &alignment, unsigned int inputBitWidth, bool is_acType, bool is_signed, bool is_fixed)
Private Attributes
CustomOrderedSet< unsigned > writeVdef
Additional Inherited Members
Detailed Description
Definition at line 60 of file interface_infer.hpp.
Constructor & Destructor Documentation
interface_infer()
interface_infer::interface_infer (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 155 of file interface_infer.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~interface_infer().
 interface_infer()
interface_infer::~interface_infer () [override], [default]
Destructor.
Referenced by interface_infer().
Member Function Documentation
addGimpleNOPxVirtual()
void interface_infer::addGimpleNOPxVirtual (tree_nodeRef origStmt, const tree_managerRef TM) [private]
Definition at line 996 of file interface_infer.cpp.
References tree_manager::create_tree_node(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), sl, THROW_ASSERT, TOK, TOK_SRCP, and writeVdef.
Referenced by create_Write_function(), and InternalExec().
classifyArg()
void interface_infer::classifyArg (statement_list * sl, tree_nodeRef argSSANode, bool & canBeMovedToBB2, bool & isRead, bool & isWrite, bool & unkwown_pattern, std::list< tree_nodeRef > & writeStmt, std::list< tree_nodeRef > & readStmt) [private]
Definition at line 362 of file interface_infer.cpp.
References classifyArgRecurse(), bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, GET_NODE, statement_list::list_of_bloc, THROW_ASSERT, and THROW_ERROR.
Referenced by InternalExec().
classifyArgRecurse()
void interface_infer::classifyArgRecurse (CustomOrderedSet< unsigned > & Visited, ssa_name * argSSA, unsigned int destBB, statement_list * sl, bool & canBeMovedToBB2, bool & isRead, bool & isWrite, bool & unkwown_pattern, std::list< tree_nodeRef > & writeStmt, std::list< tree_nodeRef > & readStmt) [private]
reading different objects
propagate design interfaces
Definition at line 189 of file interface_infer.cpp.
References FrontendFlowStep::AppM, test_panda::arg, ssa_name::CGetUseStmts(), Computepar2ssa(), GET_INDEX_NODE, tree_helper::get_mangled_fname(), GET_NODE, statement_list::list_of_bloc, STR, THROW_ASSERT, THROW_ERROR, THROW_WARNING, tree_node::ToString(), test_panda::type, and ssa_name::var.
Referenced by classifyArg().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > interface_infer::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 99 of file interface_infer.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and USE_COUNTING.
Computepar2ssa()
void interface_infer::Computepar2ssa (statement_list * sl, std::map< unsigned, unsigned > & par2ssa) [private]
Definition at line 163 of file interface_infer.cpp.
References tree_helper::ComputeSsaUses(), GET_INDEX_NODE, GET_NODE, statement_list::list_of_bloc, and THROW_ASSERT.
Referenced by classifyArgRecurse(), and InternalExec().
ComputeRelationships()
void interface_infer::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 126 of file interface_infer.cpp.
References FunctionFrontendFlowStep::ComputeRelationships(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
ComputeResourcesAlignment()
void interface_infer::ComputeResourcesAlignment (unsigned & n_resources, unsigned & alignment, unsigned int inputBitWidth, bool is_acType, bool is_signed, bool is_fixed) [private]
compute alignment
Definition at line 922 of file interface_infer.cpp.
Referenced by InternalExec().
create_Read_function()
void interface_infer::create_Read_function (tree_nodeRef refStmt, const std::string & argName_string, tree_nodeRef origStmt, unsigned int destBB, const std::string & fdName, tree_nodeRef argSSANode, tree_nodeRef aType, tree_nodeRef readType, const std::list< tree_nodeRef > & usedStmt_defs, const tree_manipulationRef tree_man, const tree_managerRef TM, bool commonRWSignature) [private]
create the function_decl
TO BE IMPROVED
Definition at line 381 of file interface_infer.cpp.
References FrontendFlowStep::AppM, test_panda::args, tree_manipulation::create_bit_size_type(), tree_manipulation::create_boolean_type(), tree_manipulation::create_function_decl(), tree_manipulation::CreateCallExpr(), tree_manipulation::CreateGimpleAssign(), tree_manipulation::CreateIntegerCst(), tree_manipulation::CreateRealCst(), FunctionEdgeInfo::direct_call, GET_INDEX_NODE, tree_helper::get_mangled_fname(), GET_NODE, srcp::include_name, tree_manager::new_tree_node_id(), DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), tree_helper::Size(), sl, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by InternalExec().
create_resource()
void interface_infer::create_resource (const std::vector< std::string > & operationsR, const std::vector< std::string > & operationsW, const std::string & argName_string, const std::string & interfaceType, unsigned int inputBitWidth, bool isDiffSize, const std::string & fname, unsigned n_resources, unsigned alignment) [private]
Definition at line 965 of file interface_infer.cpp.
References FrontendFlowStep::AppM, create_resource_array(), create_resource_Read_simple(), create_resource_Write_simple(), THROW_ASSERT, and THROW_ERROR.
Referenced by InternalExec().
create_resource_array()
void interface_infer::create_resource_array (const std::vector< std::string > & operationsR, const std::vector< std::string > & operationsW, const std::string & argName_string, const std::string & interfaceType, unsigned int inputBitWidth, unsigned int arraySize, unsigned n_resources, unsigned alignment) [private]
add description and license
required to activate the module generation
add constraint on resource
Definition at line 771 of file interface_infer.cpp.
References structural_manager::add_NP_functionality(), structural_manager::add_port(), structural_manager::add_port_vector(), FrontendFlowStep::AppM, ARRAY_1D_STD_BRAM_NN_SDS, ARRAY_1D_STD_BRAM_SDS, CLOCK_PORT_NAME, area_model::create_model(), time_model::create_model(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, ENCODE_FDNAME, FunctionFrontendFlowStep::function_id, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), port_o::IN, INDENT_DBG_MEX, INTERFACE_LIBRARY, NP_functionality::LIBRARY, LIBRARY_STD_FU, port_o::OUT, DesignFlowStep::parameters, RESET_PORT_NAME, area_model::set_area_value(), time_model::set_execution_time(), structural_manager::set_top_info(), START_PORT_NAME, and NP_functionality::VERILOG_GENERATOR.
Referenced by create_resource().
create_resource_Read_simple()
void interface_infer::create_resource_Read_simple (const std::vector< std::string > & operations, const std::string & argName_string, const std::string & interfaceType, unsigned int inputBitWidth, bool IO_port, unsigned n_resources) [private]
add description and license
required to activate the module generation
otherwise no constraints are required for this resource
Definition at line 535 of file interface_infer.cpp.
References structural_manager::add_NP_functionality(), structural_manager::add_port(), structural_manager::add_port_vector(), FrontendFlowStep::AppM, CLOCK_PORT_NAME, functional_unit::COMBINATIONAL, area_model::create_model(), time_model::create_model(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DONE_PORT_NAME, ENCODE_FDNAME, EPSILON, FunctionFrontendFlowStep::function_id, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), port_o::IN, INDENT_DBG_MEX, INTERFACE_LIBRARY, NP_functionality::LIBRARY, port_o::OUT, DesignFlowStep::parameters, RESET_PORT_NAME, area_model::set_area_value(), time_model::set_execution_time(), structural_manager::set_top_info(), START_PORT_NAME, and NP_functionality::VERILOG_GENERATOR.
Referenced by create_resource().
create_resource_Write_simple()
void interface_infer::create_resource_Write_simple (const std::vector< std::string > & operations, const std::string & argName_string, const std::string & interfaceType, unsigned int inputBitWidth, bool IO_port, bool isDiffSize, unsigned n_resources) [private]
add description and license
required to activate the module generation
add constraint on resource
Definition at line 644 of file interface_infer.cpp.
References structural_manager::add_NP_functionality(), structural_manager::add_port(), structural_manager::add_port_vector(), FrontendFlowStep::AppM, CLOCK_PORT_NAME, functional_unit::COMBINATIONAL, area_model::create_model(), time_model::create_model(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DONE_PORT_NAME, ENCODE_FDNAME, EPSILON, FunctionFrontendFlowStep::function_id, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), port_o::IN, INDENT_DBG_MEX, INTERFACE_LIBRARY, NP_functionality::LIBRARY, port_o::OUT, DesignFlowStep::parameters, RESET_PORT_NAME, area_model::set_area_value(), time_model::set_execution_time(), structural_manager::set_top_info(), START_PORT_NAME, NP_functionality::VERILOG_GENERATOR, VHDL, and NP_functionality::VHDL_GENERATOR.
Referenced by create_resource().
create_Write_function()
void interface_infer::create_Write_function (const std::string & argName_string, tree_nodeRef origStmt, const std::string & fdName, tree_nodeRef writeValue, tree_nodeRef aType, tree_nodeRef writeType, const tree_manipulationRef tree_man, const tree_managerRef TM, bool commonRWSignature) [private]
create the function_decl
Definition at line 466 of file interface_infer.cpp.
References addGimpleNOPxVirtual(), FrontendFlowStep::AppM, test_panda::args, tree_helper::CGetType(), tree_manipulation::create_bit_size_type(), tree_manipulation::create_boolean_type(), tree_manipulation::create_function_decl(), tree_manipulation::create_gimple_call(), tree_manipulation::create_void_type(), tree_manipulation::CreateIntegerCst(), tree_manipulation::CreateNopExpr(), tree_manipulation::CreateUnsigned(), FunctionEdgeInfo::direct_call, GET_INDEX_NODE, tree_helper::get_mangled_fname(), GET_NODE, srcp::include_name, tree_helper::is_int(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, tree_helper::Size(), sl, STR, and THROW_ASSERT.
Referenced by InternalExec().
HasToBeExecuted()
bool interface_infer::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 1485 of file interface_infer.cpp.
References FunctionFrontendFlowStep::bb_version.
Initialize()
void interface_infer::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 1480 of file interface_infer.cpp.
References DesignFlowStep::Initialize().
InternalExec()
DesignFlowStep_Status interface_infer::InternalExec () [override], [virtual]
Performs the loops analysis.
load xml interface specification file
pre-process the list of statements to bind parm_decl and ssa variables
TO BE FIXED
Implements FunctionFrontendFlowStep.
Definition at line 1037 of file interface_infer.cpp.
References ac_type_bitwidth(), addGimpleNOPxVirtual(), FrontendFlowStep::AppM, test_panda::arg, classifyArg(), Computepar2ssa(), ComputeResourcesAlignment(), xml_node::convert_escaped(), create_Read_function(), create_resource(), create_Write_function(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, ENCODE_FDNAME, bloc::ENTRY_BLOCK_ID, XMLDomParser::Exec(), bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, xml_child::get_children(), XMLDomParser::get_document(), GET_INDEX_NODE, tree_helper::get_mangled_fname(), GET_NODE, tree_helper::get_pointed_type(), GetLeafFileName(), INDENT_DBG_MEX, tree_helper::is_a_pointer(), DesignFlowStep::parameters, test_panda::parser, tree_helper::size(), tree_helper::Size(), sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, THROW_WARNING, test_panda::type, UNCHANGED, and writeVdef.
Field Documentation
writeVdef
CustomOrderedSet<unsigned> interface_infer::writeVdef [private]
Definition at line 63 of file interface_infer.hpp.
Referenced by addGimpleNOPxVirtual(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/interface_infer.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/interface_infer.cpp