/home/osboxes/bambu/PandA-bambu/src/utility/Statistics.hpp File Reference
This file collects some algebric statistical functions.
#include <boost/math/distributions/lognormal.hpp>
#include <boost/math/distributions/normal.hpp>
#include <boost/version.hpp>
#include <tuple>
#include <boost/math/distributions.hpp>
#include <vector>
Macros
#define BOOST_TR1_TUPLE_HPP_INCLUDED
Utility include.
Functions
boost::math::normal MultiplyVarForCoefficient (int coeff, boost::math::normal var)
boost::math::normal VarSum (boost::math::normal x, double c)
boost::math::normal VarSum (boost::math::normal x, boost::math::normal y)
boost::math::normal VarSum (boost::math::normal x, boost::math::normal y, double p)
boost::math::lognormal VarSum (std::vector< boost::math::lognormal > v)
boost::math::lognormal VarSum (boost::math::lognormal x, boost::math::lognormal y)
boost::math::lognormal VarSum (boost::math::lognormal x, boost::math::lognormal y, double p)
boost::math::normal VarMax (boost::math::normal x, boost::math::normal y, double p)
boost::math::normal VarMax (std::vector< boost::math::normal > v)
boost::math::normal ComputeStatisticalDelay (double d, int n)
boost::math::lognormal ComputeStatisticalPower (double p, int n)
boost::math::normal CreateStatisticalAttribute (double a, int n)
boost::math::normal CreateStatisticalAttribute (double a, std::vector< int > d, double mean, double st_dev, int d_rand, double mean_rand, double st_dev_rand)
Detailed Description
This file collects some algebric statistical functions.
Author
Carmine Galeone $Revision$ $Date$
Macro Definition Documentation
BOOST_TR1_TUPLE_HPP_INCLUDED
#define BOOST_TR1_TUPLE_HPP_INCLUDED
Utility include.
Definition at line 55 of file Statistics.hpp.
Function Documentation
ComputeStatisticalDelay()
boost::math::normal ComputeStatisticalDelay (double d, int n)
Returns
a boost::math::normal random variable representing the statististical delay of an operational vertex in the DFG.
Parameters
d is the nominal delay of the operational vertex.
n is the number of random variables used to generate the statistical representation.
Definition at line 143 of file Statistics.cpp.
References CreateStatisticalAttribute().
ComputeStatisticalPower()
boost::math::lognormal ComputeStatisticalPower (double p, int n)
Returns
a boost::math::normal random variable representing the statististical power consumption of an operational vertex in the DFG.
Parameters
p is the nominal power consumption of the operational vertex.
n is the number of random variables used to generate the statistical representation.
Definition at line 148 of file Statistics.cpp.
References CreateStatisticalAttribute().
CreateStatisticalAttribute() [1/2]
boost::math::normal CreateStatisticalAttribute (double a, int n)
Returns
a boost::math::normal random variable representing an attribute of one operational vertex in the DFG.
Parameters
a is the nominal attribute value of the operational vertex.
n is the number of random variables used to generate the statistical representation.
Definition at line 155 of file Statistics.cpp.
References CreateStatisticalAttribute().
Referenced by ComputeStatisticalDelay(), ComputeStatisticalPower(), and CreateStatisticalAttribute().
CreateStatisticalAttribute() [2/2]
boost::math::normal CreateStatisticalAttribute (double a, std::vector< int > d, double mean, double st_dev, int d_rand, double mean_rand, double st_dev_rand)
Returns
a boost::math::normal random variable representing an attribute of one operational vertex in the DFG.
Parameters
a is the nominal attribute value of the operational vertex.
d is the list of the weights of the boost::math::normal random variables.
mean is mean of the single boost::math::normal random variable.
st_dev is standard deviation of the single boost::math::normal random variable.
d_rand is weight of the boost::math::normal variable representing the random component.
mean_rand is mean of the boost::math::normal variable representing the random component.
st_dev_rand is standard deviation of the boost::math::normal variable representing the random component.
Definition at line 167 of file Statistics.cpp.
References MultiplyVarForCoefficient(), and VarSum().
MultiplyVarForCoefficient()
boost::math::normal MultiplyVarForCoefficient (int coeff, boost::math::normal var)
Returns
return a boost::math::normal random variable multiplied for a constant.
Parameters
coeff is the constant.
var is the boost::math::normal random variable.
Definition at line 48 of file Statistics.cpp.
Referenced by CreateStatisticalAttribute().
VarMax() [1/2]
boost::math::normal VarMax (boost::math::normal x, boost::math::normal y, double p)
Returns
return the max of two boost::math::normal random variables.
Parameters
x is the first random variable.
y is the second random variable.
p is the correlation between x and y.
Definition at line 113 of file Statistics.cpp.
Referenced by VarMax().
VarMax() [2/2]
boost::math::normal VarMax (std::vector< boost::math::normal > v)
Returns
return the max of all the independent boost::math::normal random variables contained in a vector.
Parameters
v is the list of random variables.
Definition at line 129 of file Statistics.cpp.
References VarMax().
VarSum() [1/6]
boost::math::normal VarSum (boost::math::normal x, double c)
Returns
return the sum of a boost::math::normal random variable and a constant.
Parameters
x is the random variable.
c is the constant.
Definition at line 57 of file Statistics.cpp.
Referenced by CreateStatisticalAttribute(), and VarSum().
VarSum() [2/6]
boost::math::normal VarSum (boost::math::normal x, boost::math::normal y)
Returns
return the sum of two independent boost::math::normal random variables.
Parameters
x is the first random variable.
y is the second random variable.
Definition at line 63 of file Statistics.cpp.
References VarSum().
VarSum() [3/6]
boost::math::normal VarSum (boost::math::normal x, boost::math::normal y, double p)
Returns
return the sum of two boost::math::normal random variables.
Parameters
x is the first random variable.
y is the second random variable.
p is the correlation between x and y.
Definition at line 68 of file Statistics.cpp.
VarSum() [4/6]
boost::math::lognormal VarSum (std::vector< boost::math::lognormal > v)
Returns
return the sum of all the independent boost::math::normal random variables contained in a vector.
Parameters
v is the list of random variables.
Definition at line 79 of file Statistics.cpp.
References VarSum().
VarSum() [5/6]
boost::math::lognormal VarSum (boost::math::lognormal x, boost::math::lognormal y)
Returns
return the sum of two independent lognormal random variables.
Parameters
x is the first random variable.
y is the second random variable.
Definition at line 93 of file Statistics.cpp.
References VarSum().
VarSum() [6/6]
boost::math::lognormal VarSum (boost::math::lognormal x, boost::math::lognormal y, double p)
Returns
return the sum of two lognormal random variables.
Parameters
x is the first random variable.
y is the second random variable.
p is the correlation between x and y.
Definition at line 98 of file Statistics.cpp.