/home/osboxes/bambu/PandA-bambu/src/utility/fileIO.hpp File Reference
utility function used to read files.
#include `Parameter.hpp`
#include `dbgPrintHelper.hpp`
#include `exceptions.hpp`
#include `file_IO_constants.hpp`
#include `gzstream.hpp`
#include `refcount.hpp`
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/system/error_code.hpp>
#include <boost/version.hpp>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
Macros
#define TIMEOUT 124
Return value of timeout signaling timeout has reached.
#define ULIMIT 153
Return value of an application which was signaled by ulimit.
#define EXEEXT std::string(``)
Typedefs
typedef refcount< std::istream > fileIO_istreamRef
RefCount type definition for the input stream object.
typedef refcount< const std::istream > fileIO_istreamConstRef
typedef refcount< std::ostream > fileIO_ostreamRef
RefCount type definition for the input stream object.
Functions
fileIO_istreamRef fileIO_istream_open (const std::string &name)
this function returns an istream compressed or not.
fileIO_istreamRef fileIO_istream_open_from_string (const std::string &input)
Create a fileIO_istreamRef starting from a string.
fileIO_ostreamRef fileIO_ostream_open (const std::string &name)
this function returns an ostream compressed or not.
void CopyStdout (const std::string &filename)
Copy a file to the standard output.
void rename_file (boost::filesystem::path from, boost::filesystem::path to)
std::string GetLeafFileName (boost::filesystem::path file)
Return the filename (base + extension) without the path.
std::string GetBaseName (boost::filesystem::path file)
Return the file without the extension.
std::string GetDirectory (const boost::filesystem::path file)
Return the directory given a file.
std::string GetExtension (const std::string &file)
Return the extension of the file.
std::string GetExtension (boost::filesystem::path file)
std::string GetExtension (const char *file)
std::string GetCurrentPath ()
bool ExistFile (const std::string &file)
void CopyFile (boost::filesystem::path file_source, boost::filesystem::path file_target)
Copy file; if target already exist, overwrite.
std::string BuildPath (const std::string &first_part, const std::string second_part)
Build a path by combining two relative paths.
int PandaSystem (const ParameterConstRef Param, const std::string &system_command, const std::string &output=``, const unsigned int type=3, const bool background=false, const size_t timeout=0)
System call forcing execution with bash.
Detailed Description
utility function used to read files.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Marco Lattuada lattuada@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Macro Definition Documentation
EXEEXT
#define EXEEXT std::string(``)
Definition at line 136 of file fileIO.hpp.
TIMEOUT
#define TIMEOUT 124
Return value of timeout signaling timeout has reached.
Definition at line 64 of file fileIO.hpp.
ULIMIT
#define ULIMIT 153
Return value of an application which was signaled by ulimit.
Definition at line 67 of file fileIO.hpp.
Typedef Documentation
fileIO_istreamConstRef
typedef refcount<const std::istream> fileIO_istreamConstRef
Definition at line 73 of file fileIO.hpp.
fileIO_istreamRef
typedef refcount<std::istream> fileIO_istreamRef
RefCount type definition for the input stream object.
Definition at line 72 of file fileIO.hpp.
fileIO_ostreamRef
typedef refcount<std::ostream> fileIO_ostreamRef
RefCount type definition for the input stream object.
Definition at line 78 of file fileIO.hpp.
Function Documentation
BuildPath()
std::string BuildPath (const std::string & first_part, const std::string second_part) [inline]
Build a path by combining two relative paths.
Parameters
first_part is the first part to be combined
second_part is the second part to be combined
Definition at line 286 of file fileIO.hpp.
Referenced by TestVectorParser::ParseXMLFile().
CopyFile()
void CopyFile (boost::filesystem::path file_source, boost::filesystem::path file_target) [inline]
Copy file; if target already exist, overwrite.
Parameters
file_source is the file to be copied
file_target is the destination
Definition at line 265 of file fileIO.hpp.
Referenced by AlteraBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), GccWrapper::CompileFile(), and XilinxBackendFlow::parse_timing().
CopyStdout()
void CopyStdout (const std::string & filename) [inline]
Copy a file to the standard output.
Definition at line 142 of file fileIO.hpp.
References test_panda::stdout.
Referenced by NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), GccWrapper::CompileFile(), GccWrapper::CreateExecutable(), SimulationTool::DetermineCycles(), ToolManager::execute_command(), GccWrapper::FillTreeManager(), IcarusWrapper::GenerateScript(), GccWrapper::QueryGccConfig(), and SimulationTool::Simulate().
ExistFile()
bool ExistFile (const std::string & file) [inline]
Definition at line 255 of file fileIO.hpp.
Referenced by NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), and GetFile().
fileIO_istream_open()
fileIO_istreamRef fileIO_istream_open (const std::string & name) [inline]
this function returns an istream compressed or not.
It first check for a compressed file, then search for the compressed version of the file and finally in case no compressed file is found it look for the plain text file. this function is mainly based on the gzstream wrapper and on zlib library.
Parameters
name is the file name.
Returns
the refcount to the istream
Definition at line 87 of file fileIO.hpp.
References THROW_ERROR.
Referenced by BackendFlow::create_xml_scripts(), AsnParser::Exec(), AadlParser::Exec(), Parameter::GetFileFormat(), TestVectorParser::ParseXMLFile(), and read_technology_library().
fileIO_istream_open_from_string()
fileIO_istreamRef fileIO_istream_open_from_string (const std::string & input) [inline]
Create a fileIO_istreamRef starting from a string.
Definition at line 113 of file fileIO.hpp.
Referenced by CInitializationParser::Parse().
fileIO_ostream_open()
fileIO_ostreamRef fileIO_ostream_open (const std::string & name) [inline]
this function returns an ostream compressed or not.
this function is mainly based on the gzstream wrapper and on zlib library.
Parameters
name is the file name.
Returns
the refcount to the ostream
Definition at line 126 of file fileIO.hpp.
Referenced by main().
GetBaseName()
std::string GetBaseName (boost::filesystem::path file) [inline]
Return the file without the extension.
Parameters
file is the starting file
Returns
the file without path and extension
Definition at line 202 of file fileIO.hpp.
Referenced by GccWrapper::CompileFile(), and GccWrapper::FillTreeManager().
GetCurrentPath()
std::string GetCurrentPath () [inline]
Definition at line 246 of file fileIO.hpp.
Referenced by Parameter::SetCommonDefaults(), and BambuParameter::SetDefaults().
GetDirectory()
std::string GetDirectory (const boost::filesystem::path file) [inline]
Return the directory given a file.
Parameters
file is the file
Returns
the directory
Definition at line 218 of file fileIO.hpp.
Referenced by AadlParser::Exec(), and TestVectorParser::ParseXMLFile().
GetExtension() [1/3]
std::string GetExtension (const std::string & file) [inline]
Return the extension of the file.
Parameters
file is the starting file
Returns
the extension of the file
Definition at line 232 of file fileIO.hpp.
Referenced by GccWrapper::CompileFile(), VIVADO_xsim_wrapper::create_project_script(), ISE_isim_wrapper::create_project_script(), tree_panda_gcc_parameter::Exec(), create_tree_manager::Exec(), xst_wrapper::GenerateProjectFile(), modelsimWrapper::GenerateScript(), GetExtension(), Parameter::GetFileFormat(), LatticeBackendFlow::InitDesignParameters(), and XilinxBackendFlow::InitDesignParameters().
GetExtension() [2/3]
std::string GetExtension (boost::filesystem::path file) [inline]
Definition at line 237 of file fileIO.hpp.
References GetExtension().
GetExtension() [3/3]
std::string GetExtension (const char * file) [inline]
Definition at line 241 of file fileIO.hpp.
References GetExtension().
GetLeafFileName()
std::string GetLeafFileName (boost::filesystem::path file) [inline]
Return the filename (base + extension) without the path.
Parameters
file is the starting file
Returns
the file without the path
Definition at line 188 of file fileIO.hpp.
Referenced by ToolManager::determine_paths(), GccWrapper::FillTreeManager(), Parameter::GetFileFormat(), DesignCompilerWrapper::import_input_design(), interface_infer::InternalExec(), read_technology_library(), and PragmaParser::substitutePragmas().
PandaSystem()
int PandaSystem (const ParameterConstRef Param, const std::string & system_command, const std::string & output = ``, const unsigned int type = 3, const bool background = false, const size_t timeout = 0) [inline]
System call forcing execution with bash.
Parameters
Param is the set of input parameters
system_command is the to be executed
output is the file where output has to be saved
type specifies which streams have to be saved; possible values are 0 (none), 1 (stdout), 2 (stderr), 3(stdout and stderr)
background specifies if the command has to be executed in background
timeout is the timeout for the command (in minutes)
Returns
the value returned by the shell
Definition at line 301 of file fileIO.hpp.
References test_panda::command, counter, OUTPUT_LEVEL_PEDANTIC, STR_CST_file_IO_shell_output_file, STR_CST_file_IO_shell_script, THROW_ASSERT, THROW_UNREACHABLE, and test_panda::type.
Referenced by BambuParameter::CheckParameters(), GccWrapper::CompileFile(), GccWrapper::CreateExecutable(), CTestbenchExecution::Exec(), BasicBlocksProfiling::Exec(), create_tree_manager::Exec(), TestbenchValuesCGeneration::Exec(), ToolManager::execute_command(), FindMaxCFGTransformations::ExecuteBambu(), NonDeterministicFlows::ExecuteTool(), GccWrapper::FillTreeManager(), moduleGenerator::GenerateHDL(), IcarusWrapper::GenerateScript(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), GccWrapper::GetSourceCodeLines(), GccWrapper::GetSystemIncludes(), main(), and GccWrapper::QueryGccConfig().
rename_file()
void rename_file (boost::filesystem::path from, boost::filesystem::path to) [inline]
Definition at line 157 of file fileIO.hpp.
Referenced by GccWrapper::FillTreeManager().