AadlInformation Class Reference
#include <aadl_information.hpp>
Data Structures
struct AadlParameter
Strucutre containing the characteristics of a parameter.
Public Member Functions
void AddAsnType (const std::string &name, const AsnTypeRef &asn_type)
Add an asn_type.
AsnTypeRef CGetAsnType (const std::string &name) const
Get an asn_type.
Data Fields
std::map< std::string, std::list< AadlParameter > > function_parameters
For each function the list of parameters.
std::list< std::string > top_functions_names
The top functions in the order in which they are specified in the aadl file.
CustomMap< std::string, unsigned int > internal_memory_sizes
For each function the size of internal memory.
CustomMap< std::string, unsigned int > exposed_memory_sizes
For each function the exposed size of internal memory.
Protected Member Functions
std::string Normalize (const std::string &name) const
Normalize asn_type name.
Protected Attributes
CustomMap< std::string, AsnTypeRef > asn_types
The asn types.
Detailed Description
Definition at line 56 of file aadl_information.hpp.
Member Function Documentation
AddAsnType()
void AadlInformation::AddAsnType (const std::string & name, const AsnTypeRef & asn_type)
Add an asn_type.
Parameters
name is the name of the type
type is the type
Definition at line 93 of file aadl_information.cpp.
References AadlInformation::AadlParameter::asn_type, asn_types, and Normalize().
CGetAsnType()
AsnTypeRef AadlInformation::CGetAsnType (const std::string & name) const
Get an asn_type.
Parameters
name is the name of the type
Definition at line 98 of file aadl_information.cpp.
References asn_types, AadlInformation::AadlParameter::name, Normalize(), and THROW_ASSERT.
Normalize()
std::string AadlInformation::Normalize (const std::string & name) const [protected]
Normalize asn_type name.
Parameters
name is the name
Returns
the normalized name
Definition at line 88 of file aadl_information.cpp.
Referenced by AddAsnType(), and CGetAsnType().
Field Documentation
asn_types
CustomMap<std::string, AsnTypeRef> AadlInformation::asn_types [protected]
The asn types.
Definition at line 60 of file aadl_information.hpp.
Referenced by AddAsnType(), and CGetAsnType().
exposed_memory_sizes
CustomMap<std::string, unsigned int> AadlInformation::exposed_memory_sizes
For each function the exposed size of internal memory.
Definition at line 134 of file aadl_information.hpp.
function_parameters
std::map<std::string, std::list<AadlParameter> > AadlInformation::function_parameters
For each function the list of parameters.
Definition at line 125 of file aadl_information.hpp.
internal_memory_sizes
CustomMap<std::string, unsigned int> AadlInformation::internal_memory_sizes
For each function the size of internal memory.
Definition at line 131 of file aadl_information.hpp.
top_functions_names
std::list<std::string> AadlInformation::top_functions_names
The top functions in the order in which they are specified in the aadl file.
Definition at line 128 of file aadl_information.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/aadl_asn/aadl_information.hpp
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/aadl_asn/aadl_information.cpp