CWriter Class Reference
Class used to write the C code representing a program, this class can't be directly instantiated since the backend is not specified yet.
#include <c_writer.hpp>
Public Member Functions
virtual ~CWriter ()
Destructor.
virtual void Initialize ()
Initialize data structure.
const InstructionWriterRef getInstructionWriter () const
Returns the instruction writer.
const CustomSet< unsigned int > GetLocalVariables (const unsigned int function_id) const
Compute the local variables of a function.
virtual void WriteFunctionImplementation (unsigned int function_index)
Write function implementation.
virtual void StartFunctionBody (const unsigned int funId)
Writes the body of the function to the specified stream.
virtual void WriteFunctionBody (const unsigned int function_id)
Writes the body of a function.
virtual void EndFunctionBody (unsigned int funId)
Writes the code necessary to close a function (this function was a function also present in the original specification)
virtual void writeRoutineInstructions (const unsigned int function_index, const OpVertexSet &instructions, var_pp_functorConstRef variableFunctor, vertex bb_start=NULL_VERTEX, CustomOrderedSet< vertex > bb_end=CustomOrderedSet< vertex >())
Writes the instructions of the current routine, being it a task or a function of the original program.
virtual void WriteFunctionDeclaration (const unsigned int funId)
Writes the declaration of the function whose id in the tree is funId.
virtual void WriteHeader ()
Writes the header of the file.
virtual void WriteGlobalDeclarations ()
Writes the global declarations.
virtual void writeInclude (const std::string &file_name)
Writes an include directive.
virtual void DeclareType (unsigned int varType, const BehavioralHelperConstRef BH, CustomSet< std::string > &locally_declared_type)
This method should be called only if the type associated with the variable is a non built_in type and, in case the non built_in type hasn't been declared yet, it declares it; this method is used to declared new types with scope limited to a routine (be it a function of a task)
virtual void DeclareVariable (unsigned int curVar, CustomSet< unsigned int > &already_declared_variables, CustomSet< std::string > &locally_declared_type, const BehavioralHelperConstRef behavioral_helper, const var_pp_functorConstRef varFunc)
Declares the local variable; in case the variable used in the intialization of curVar hasn't been declared yet it get declared.
virtual void declare_cast_types (unsigned int funId, CustomSet< std::string > &locally_declared_types)
Declare all the types used in conversions.
virtual void DeclareLocalVariables (const CustomSet< unsigned int > &to_be_declared, CustomSet< unsigned int > &already_declared_variables, CustomSet< std::string > &locally_declared_type, const BehavioralHelperConstRef BH, const var_pp_functorConstRef varFunc)
Declares the local variable; in case the variable used in the intialization of curVar hasn't been declared yet it get declared.
virtual void DeclareFunctionTypes (const unsigned int)
Declares the types of the parameters of a function.
virtual void WriteFile (const std::string &file_name)
Writes the final C file.
virtual void WriteBuiltinWaitCall ()
Writes implementation of __builtin_wait_call.
Static Public Member Functions
static CWriterRef CreateCWriter (const CBackend::Type type, const CBackendInformationConstRef c_backend_information, const application_managerConstRef app_man, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters, const bool verbose)
Factory method.
Protected Member Functions
void writeRoutineInstructions_rec (vertex current_vertex, bool bracket, const unsigned int function_index)
Write recursively instructions belonging to a basic block of task or of a function.
virtual void writePreInstructionInfo (const FunctionBehaviorConstRef, const vertex)
Write additional information on the given statement vertex, before the statement itself.
virtual void writePostInstructionInfo (const FunctionBehaviorConstRef, const vertex)
Write additional information on the given statement vertex, after the statements itself.
virtual void WriteBodyLoop (const unsigned int function_index, const unsigned int, vertex current_vertex, bool bracket)
Write the instructions belonging to a body loop.
void compute_phi_nodes (const FunctionBehaviorConstRef function_behavior, const OpVertexSet &instructions, var_pp_functorConstRef variableFunctor)
Determines the instructions coming out from phi-node splitting.
void insert_copies (vertex b, const BBGraphConstRef bb_domGraph, const BBGraphConstRef bb_fcfgGraph, var_pp_functorConstRef variableFunctor, const CustomSet< unsigned int > &phi_instructions, std::map< unsigned int, unsigned int > &created_variables, std::map< unsigned int, std::string > &symbol_table, std::map< unsigned int, std::deque< std::string >> &array_of_stacks)
Compute the copy assignments needed by the phi nodes destruction Further details can be found in:
void schedule_copies (vertex b, const BBGraphConstRef bb_domGraph, const BBGraphConstRef bb_fcfgGraph, var_pp_functorConstRef variableFunctor, const CustomSet< unsigned int > &phi_instructions, std::map< unsigned int, unsigned int > &created_variables, std::map< unsigned int, std::string > &symbol_table, std::list< unsigned int > &pushed, std::map< unsigned int, std::deque< std::string >> &array_of_stacks)
insert copies according the algorithm described in Briggs et.
unsigned int create_new_identifier (std::map< unsigned int, std::string > &symbol_table)
create an identifier for the temporaries created by phi node destruction
void push_stack (std::string symbol_name, unsigned int dest_i, std::list< unsigned int > &pushed, std::map< unsigned int, std::deque< std::string >> &array_of_stacks)
push on the stack of temporary variables that has to replaced
void pop_stack (std::list< unsigned int > &pushed, std::map< unsigned int, std::deque< std::string >> &array_of_stacks)
remove from the stack all the temporaries
void WriteHashTableImplementation ()
Write the implementation of a hash table with long long int as key and long long int as value.
virtual void WriteBBHeader (const unsigned int bb_number, const unsigned int function_index)
CWriter (const application_managerConstRef _AppM, const InstructionWriterRef instruction_writer, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef Param, bool verbose=true)
Constructor of the class.
Protected Attributes
const application_managerConstRef AppM
the manager of the application
const tree_managerConstRef TM
The tree manager.
const IndentedOutputStreamRef indented_output_stream
Represents the stream we are currently writing to.
CustomSet< std::string > globally_declared_types
This set contains the list of the non built_in types already declared in the global scope.
CustomSet< unsigned int > globallyDeclVars
const InstructionWriterRef instrWriter
Contains the class used to write instructions.
size_t bb_label_counter
Counter of the invocations of writeRoutineInstructions; this counter allows to print different labels in differnt tasks to avoid problem due to multiple tasks inlineing.
bool verbose
Verbosity means that a comment is printed for each line in the output file.
const ParameterConstRef Param
set of parameters
int debug_level
the debug level
int output_level
the output level
unsigned int fake_max_tree_node_id
std::map< unsigned int, std::string > basic_block_prefix
string to be printed at the beginning of a given basic block
std::map< unsigned int, std::string > basic_block_tail
string to be printed at the end of a given basic block
std::map< vertex, std::map< unsigned int, std::string > > renaming_table
renaming table used by phi node destruction procedure
CustomOrderedSet< vertex > bb_frontier
CustomOrderedSet< vertex > bb_analyzed
std::map< unsigned int, std::string > basic_blocks_labels
CustomOrderedSet< vertex > goto_list
var_pp_functorConstRef local_rec_variableFunctor
FunctionBehaviorConstRef local_rec_function_behavior
CustomOrderedSet< vertex > local_rec_instructions
const dominance< BBGraph > * dominators
const dominance< BBGraph > * post_dominators
BBGraphConstRef local_rec_bb_fcfgGraph
OpGraphConstRef local_rec_cfgGraph
BehavioralHelperConstRef local_rec_behavioral_helper
std::vector< std::string > additionalIncludes
CustomOrderedSet< std::string > writtenIncludes
Detailed Description
Class used to write the C code representing a program, this class can't be directly instantiated since the backend is not specified yet.
So a subclass must be created which redefines all the abstract methods of this class.
Definition at line 97 of file c_writer.hpp.
Constructor & Destructor Documentation
CWriter()
CWriter::CWriter (const application_managerConstRef _AppM, const InstructionWriterRef instruction_writer, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef Param, bool verbose = true) [protected]
Constructor of the class.
Parameters
AppM is the manager of the application
instruction_writer is the instruction writer to use to print the single instruction
indented_output_stream is the stream where code has to be printed
Param is the set of parameters
verbose tells if annotations
Definition at line 210 of file c_writer.cpp.
References ~CWriter().
Referenced by CreateCWriter().
 CWriter()
CWriter::~CWriter () [virtual], [default]
Destructor.
Referenced by CWriter().
Member Function Documentation
compute_phi_nodes()
void CWriter::compute_phi_nodes (const FunctionBehaviorConstRef function_behavior, const OpVertexSet & instructions, var_pp_functorConstRef variableFunctor) [protected]
Determines the instructions coming out from phi-node splitting.
compute the assignment introduced by the phi nodes destruction
in case we declare the variables introduced during the phi nodes destruction
Definition at line 1098 of file c_writer.cpp.
References IndentedOutputStream::Append(), FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBGraphInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), FunctionBehavior::DOM_TREE, FunctionBehavior::FBB, FunctionBehavior::FCFG, GET_TYPE, tree_helper::get_type_index(), indented_output_stream, insert_copies(), tree_helper::print_type(), THROW_ASSERT, TM, and TYPE_PHI.
Referenced by DeclareLocalVariables().
create_new_identifier()
unsigned int CWriter::create_new_identifier (std::map< unsigned int, std::string > & symbol_table) [protected]
create an identifier for the temporaries created by phi node destruction
Parameters
symbol_table is the symbol table where the new id is inserted return an id for the symbol created
Definition at line 1568 of file c_writer.cpp.
References counter, fake_max_tree_node_id, STR, and TM.
Referenced by schedule_copies().
CreateCWriter()
CWriterRef CWriter::CreateCWriter (const CBackend::Type type, const CBackendInformationConstRef c_backend_information, const application_managerConstRef app_man, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters, const bool verbose) [static]
Factory method.
Parameters
type is the type of backend we are creating
c_backend_information is the information about the backend we are creating
app_man is the application manager
indented_output_stream is the output stream
parameters is the set of input parameters
verbose tells if produced source code has to be commented
Definition at line 228 of file c_writer.cpp.
References BA_NONE, CBackend::CB_SEQUENTIAL, InstructionWriter::CreateInstructionWriter(), CWriter(), and THROW_UNREACHABLE.
declare_cast_types()
void CWriter::declare_cast_types (unsigned int funId, CustomSet< std::string > & locally_declared_types) [virtual]
Declare all the types used in conversions.
Parameters
function_id is the function to be condiered
locally_declared_types is the set of already declared types
Definition at line 322 of file c_writer.cpp.
References AppM, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), DeclareType(), FunctionBehavior::DFG, ENTRY_ID, EXIT_ID, BehavioralHelper::get_typecast(), and index.
Referenced by StartFunctionBody().
DeclareFunctionTypes()
void CWriter::DeclareFunctionTypes (const unsigned int funId) [virtual]
Declares the types of the parameters of a function.
Parameters
fun_id is the index of the function
Definition at line 433 of file c_writer.cpp.
References AppM, FunctionBehavior::CGetBehavioralHelper(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DeclareType(), BehavioralHelper::get_function_name(), BehavioralHelper::GetFunctionReturnType(), BehavioralHelper::GetParameterTypes(), globally_declared_types, INDENT_DBG_MEX, and STR.
DeclareLocalVariables()
void CWriter::DeclareLocalVariables (const CustomSet< unsigned int > & to_be_declared, CustomSet< unsigned int > & already_declared_variables, CustomSet< std::string > & locally_declared_type, const BehavioralHelperConstRef BH, const var_pp_functorConstRef varFunc) [virtual]
Declares the local variable; in case the variable used in the intialization of curVar hasn't been declared yet it get declared.
Parameters
to_be_declared is the set of variables which have to be declared
already_decl_variables is the set of already declared variables
locally_declared_type is the set of already declared types
helper is the behavioral helper associated with the function
varFunc is the printer functor
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 1354 of file c_writer.cpp.
References AppM, FunctionBehavior::CGetOpGraph(), compute_phi_nodes(), debug_level, DEBUG_LEVEL_PEDANTIC, DeclareVariable(), FunctionBehavior::DFG, BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), tree_node::get_kind(), GET_NODE, BehavioralHelper::get_parameters(), INDENT_DBG_MEX, STR, THROW_ASSERT, and TM.
Referenced by DiscrepancyAnalysisCWriter::DeclareLocalVariables(), and StartFunctionBody().
DeclareType()
void CWriter::DeclareType (unsigned int varType, const BehavioralHelperConstRef BH, CustomSet< std::string > & locally_declared_type) [virtual]
This method should be called only if the type associated with the variable is a non built_in type and, in case the non built_in type hasn't been declared yet, it declares it; this method is used to declared new types with scope limited to a routine (be it a function of a task)
Parameters
varType the index of the type to be declared
BH the behavioral helper associated to the function which declare type
locally_declared_type is the set of type already declared in this function
routine_name is the name of the routina (function or thread)
Definition at line 1246 of file c_writer.cpp.
References IndentedOutputStream::Append(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BehavioralHelper::get_definition(), BehavioralHelper::get_function_name(), tree_helper::GetRealType(), tree_helper::GetTypesToBeDeclaredAfter(), tree_helper::GetTypesToBeDeclaredBefore(), globally_declared_types, tree_helper::HasToBeDeclared(), INDENT_DBG_MEX, indented_output_stream, tree_helper::name_type(), Param, BehavioralHelper::print_type_declaration(), STR, TM, and verbose.
Referenced by declare_cast_types(), DeclareFunctionTypes(), and DeclareVariable().
DeclareVariable()
void CWriter::DeclareVariable (unsigned int curVar, CustomSet< unsigned int > & already_declared_variables, CustomSet< std::string > & locally_declared_type, const BehavioralHelperConstRef behavioral_helper, const var_pp_functorConstRef varFunc) [virtual]
Declares the local variable; in case the variable used in the intialization of curVar hasn't been declared yet it get declared.
Parameters
curVar is the variable to be declared
already_decl_variables is the set of already declared variables
locally_declared_type is the set of already declared types
behavioral_helper is the behavioral helper
varFunc is the printer functor
Definition at line 1296 of file c_writer.cpp.
References IndentedOutputStream::Append(), debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DeclareType(), BehavioralHelper::get_type(), tree_helper::get_type_index(), BehavioralHelper::GetInit(), globallyDeclVars, INDENT_DBG_MEX, indented_output_stream, instrWriter, tree_helper::is_system(), BehavioralHelper::PrintVarDeclaration(), BehavioralHelper::PrintVariable(), STR, TM, and verbose.
Referenced by DeclareLocalVariables(), and WriteGlobalDeclarations().
EndFunctionBody()
void CWriter::EndFunctionBody (unsigned int funId) [virtual]
Writes the code necessary to close a function (this function was a function also present in the original specification)
Definition at line 529 of file c_writer.cpp.
References IndentedOutputStream::Append(), basic_block_prefix, basic_block_tail, indented_output_stream, renaming_table, STR, and verbose.
Referenced by WriteFunctionImplementation().
getInstructionWriter()
const InstructionWriterRef CWriter::getInstructionWriter () const
Returns the instruction writer.
Returns
the instruction writer
Definition at line 1341 of file c_writer.cpp.
References instrWriter.
GetLocalVariables()
const CustomSet< unsigned int > CWriter::GetLocalVariables (const unsigned int function_id) const
Compute the local variables of a function.
Parameters
function_id is the index of a function
Returns
the local variables of a function
Definition at line 459 of file c_writer.cpp.
References AppM, OpGraph::CGetOpNodeInfo(), and FunctionBehavior::DFG.
Referenced by StartFunctionBody().
Initialize()
void CWriter::Initialize () [virtual]
Initialize data structure.
Reimplemented in EdgeCWriter.
Definition at line 345 of file c_writer.cpp.
References additionalIncludes, fake_max_tree_node_id, globally_declared_types, globallyDeclVars, instrWriter, TM, and writtenIncludes.
Referenced by EdgeCWriter::Initialize().
insert_copies()
void CWriter::insert_copies (vertex b, const BBGraphConstRef bb_domGraph, const BBGraphConstRef bb_fcfgGraph, var_pp_functorConstRef variableFunctor, const CustomSet< unsigned int > & phi_instructions, std::map< unsigned int, unsigned int > & created_variables, std::map< unsigned int, std::string > & symbol_table, std::map< unsigned int, std::deque< std::string >> & array_of_stacks) [protected]
Compute the copy assignments needed by the phi nodes destruction Further details can be found in:
Preston Briggs, Keith D. Cooper, Timothy J. Harvey and L. Taylor Simpson, `Practical Improvements to the Construction and Destruction of Static Single Assignment Form`, Software -- Practice and Experience 1998
fill the renaming table for basic block b
Definition at line 1388 of file c_writer.cpp.
References pop_stack(), renaming_table, and schedule_copies().
Referenced by compute_phi_nodes().
pop_stack()
void CWriter::pop_stack (std::list< unsigned int > & pushed, std::map< unsigned int, std::deque< std::string >> & array_of_stacks) [protected]
remove from the stack all the temporaries
Parameters
pushed is the list of variables to be renamed
array_of_stacks is the array of stacks used by the phi node destruction procedure
Definition at line 1592 of file c_writer.cpp.
References THROW_ASSERT.
Referenced by insert_copies().
push_stack()
void CWriter::push_stack (std::string symbol_name, unsigned int dest_i, std::list< unsigned int > & pushed, std::map< unsigned int, std::deque< std::string >> & array_of_stacks) [protected]
push on the stack of temporary variables that has to replaced
Parameters
symbol_name is the new identifier for dest_i
dest_i is the id of the variable to be renamed
pushed is the list of variables to be renamed
array_of_stacks is the array of stacks used by the phi node destruction procedure
Definition at line 1585 of file c_writer.cpp.
References THROW_ASSERT.
Referenced by schedule_copies().
schedule_copies()
void CWriter::schedule_copies (vertex b, const BBGraphConstRef bb_domGraph, const BBGraphConstRef bb_fcfgGraph, var_pp_functorConstRef variableFunctor, const CustomSet< unsigned int > & phi_instructions, std::map< unsigned int, unsigned int > & created_variables, std::map< unsigned int, std::string > & symbol_table, std::list< unsigned int > & pushed, std::map< unsigned int, std::deque< std::string >> & array_of_stacks) [protected]
insert copies according the algorithm described in Briggs et.
al. Pass One: initialize the data structures
Pass two: Set up the worklist of initial copies
Pass Three: Iterate over the worklist, inserting copies
if dest live_out(b) wrt the original algorithm an optimization has been added: in case b does not dominate any other node we can skip the creation of t
insert a copy from dest to a new temp t at phi-node defining dest
push(t, Stack[dest])
insert a copy operation from map[src] to dest at the end of b
check if dest_i is source of any other pair in copy_set this optimization is not described in the original algorithm
create a new symbol
insert a copy from dest to a new temp t at the end of b
Definition at line 1412 of file c_writer.cpp.
References basic_block_prefix, basic_block_tail, BBGraph::CGetBBNodeInfo(), create_new_identifier(), GET_INDEX_NODE, GET_NODE, push_stack(), and renaming_table.
Referenced by insert_copies().
StartFunctionBody()
void CWriter::StartFunctionBody (const unsigned int funId) [virtual]
Writes the body of the function to the specified stream.
Parameters
funId is the index of the function
Definition at line 500 of file c_writer.cpp.
References IndentedOutputStream::Append(), AppM, declare_cast_types(), DeclareLocalVariables(), BehavioralHelper::get_parameters(), GetLocalVariables(), indented_output_stream, and instrWriter.
Referenced by WriteFunctionImplementation().
WriteBBHeader()
void CWriter::WriteBBHeader (const unsigned int bb_number, const unsigned int function_index) [protected], [virtual]
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 1840 of file c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
WriteBodyLoop()
void CWriter::WriteBodyLoop (const unsigned int function_index, const unsigned int, vertex current_vertex, bool bracket) [protected], [virtual]
Write the instructions belonging to a body loop.
Parameters
function_index is the identifier of the function to which instructions belong
loop_id is the index of the loop to be printed
current_vertex is the first basic block of the loop
bracket tells if bracket should be added before and after this basic block
Definition at line 355 of file c_writer.cpp.
References writeRoutineInstructions_rec().
Referenced by writeRoutineInstructions_rec().
WriteBuiltinWaitCall()
void CWriter::WriteBuiltinWaitCall () [virtual]
Writes implementation of __builtin_wait_call.
Reimplemented in HLSCWriter, and DiscrepancyAnalysisCWriter.
Definition at line 1844 of file c_writer.cpp.
References IndentedOutputStream::Append(), AppM, BUILTIN_WAIT_CALL, BehavioralHelper::get_function_name(), BehavioralHelper::get_parameters(), BehavioralHelper::get_size(), BehavioralHelper::get_type(), BehavioralHelper::GetFunctionReturnType(), indented_output_stream, BehavioralHelper::is_int(), BehavioralHelper::is_real(), BehavioralHelper::is_unsigned(), BehavioralHelper::print_type(), BehavioralHelper::PrintVariable(), STR, and test_panda::type.
Referenced by DiscrepancyAnalysisCWriter::WriteBuiltinWaitCall().
WriteFile()
void CWriter::WriteFile (const std::string & file_name) [virtual]
Writes the final C file.
Parameters
file_name is the name of the file to be generated
Reimplemented in HLSCWriter.
Definition at line 1835 of file c_writer.cpp.
References indented_output_stream, and IndentedOutputStream::WriteFile().
Referenced by EdgeCWriter::writeRoutineInstructions().
WriteFunctionBody()
void CWriter::WriteFunctionBody (const unsigned int function_id) [virtual]
Writes the body of a function.
Parameters
function_id is the function whose body has to be printed
Definition at line 360 of file c_writer.cpp.
References AppM, FunctionBehavior::CFG, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), BehavioralHelper::get_function_name(), THROW_ASSERT, and writeRoutineInstructions().
Referenced by WriteFunctionImplementation().
WriteFunctionDeclaration()
void CWriter::WriteFunctionDeclaration (const unsigned int funId) [virtual]
Writes the declaration of the function whose id in the tree is funId.
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 476 of file c_writer.cpp.
References IndentedOutputStream::Append(), AppM, FunctionBehavior::CGetBehavioralHelper(), BehavioralHelper::get_function_name(), indented_output_stream, instrWriter, BehavioralHelper::is_var_args(), Param, THROW_ERROR_CODE, and VARARGS_EC.
Referenced by DiscrepancyAnalysisCWriter::WriteFunctionDeclaration().
WriteFunctionImplementation()
void CWriter::WriteFunctionImplementation (unsigned int function_index) [virtual]
Write function implementation.
Parameters
function_id is the index of the function to be written
Reimplemented in HLSCWriter, and DiscrepancyAnalysisCWriter.
Definition at line 375 of file c_writer.cpp.
References EndFunctionBody(), StartFunctionBody(), and WriteFunctionBody().
Referenced by DiscrepancyAnalysisCWriter::WriteFunctionImplementation().
WriteGlobalDeclarations()
void CWriter::WriteGlobalDeclarations () [virtual]
Writes the global declarations.
Writing auxiliary variables used by instruction writer
Writing declarations of global variables
Reimplemented in HLSCWriter, BasicBlocksProfilingCWriter, and DiscrepancyAnalysisCWriter.
Definition at line 406 of file c_writer.cpp.
References IndentedOutputStream::Append(), AppM, BUILTIN_WAIT_CALL, DeclareVariable(), globally_declared_types, globallyDeclVars, indented_output_stream, instrWriter, STR, and THROW_ASSERT.
Referenced by DiscrepancyAnalysisCWriter::WriteGlobalDeclarations(), and BasicBlocksProfilingCWriter::WriteGlobalDeclarations().
WriteHashTableImplementation()
void CWriter::WriteHashTableImplementation () [protected]
Write the implementation of a hash table with long long int as key and long long int as value.
Definition at line 1603 of file c_writer.cpp.
References IndentedOutputStream::Append(), and indented_output_stream.
WriteHeader()
void CWriter::WriteHeader () [virtual]
Writes the header of the file.
Reimplemented in HLSCWriter, and EdgeCWriter.
Definition at line 382 of file c_writer.cpp.
References IndentedOutputStream::Append(), AppM, BehavioralHelper::get_function_name(), and indented_output_stream.
writeInclude()
void CWriter::writeInclude (const std::string & file_name) [virtual]
Writes an include directive.
Parameters
file_name the name of the header file to be included
Definition at line 1346 of file c_writer.cpp.
References IndentedOutputStream::Append(), indented_output_stream, and writtenIncludes.
writePostInstructionInfo()
void CWriter::writePostInstructionInfo (const FunctionBehaviorConstRef , const vertex) [protected], [virtual]
Write additional information on the given statement vertex, after the statements itself.
The default for this function is to do nothing, but every derived class can specify its own additional information to print
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 544 of file c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
writePreInstructionInfo()
void CWriter::writePreInstructionInfo (const FunctionBehaviorConstRef , const vertex) [protected], [virtual]
Write additional information on the given statement vertex, before the statement itself.
The default for this function is to do nothing, but every derived class can specify its own additional information to print
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 540 of file c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
writeRoutineInstructions()
void CWriter::writeRoutineInstructions (const unsigned int function_index, const OpVertexSet & instructions, var_pp_functorConstRef variableFunctor, vertex bb_start = NULL_VERTEX, CustomOrderedSet< vertex > bb_end = CustomOrderedSet<vertex>()) [virtual]
Writes the instructions of the current routine, being it a task or a function of the original program.
Parameters
function_index is the index of the function
instructions is the instructions which have to be printed
variableFunctor is the variable functor
bb_start is the first basic block to be printed
bb_end is the set of first basic block not to be printed
Then I compute all the labels associated with a basic block with more than one entering edge.
set of basic block already analyzed
store for which basic block the goto has been used
basic block frontier over which writeRoutineInstructions_rec cannot go.
some statements can be in entry
Reimplemented in EdgeCWriter.
Definition at line 1134 of file c_writer.cpp.
References IndentedOutputStream::Append(), AppM, basic_blocks_labels, bb_analyzed, bb_frontier, bb_label_counter, FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, dominators, FunctionBehavior::dominators, bloc::EXIT_BLOCK_ID, FunctionBehavior::FBB, FunctionBehavior::FCFG, BehavioralHelper::get_label_name(), GET_TYPE, goto_list, INDENT_DBG_MEX, indented_output_stream, local_rec_bb_fcfgGraph, local_rec_behavioral_helper, local_rec_cfgGraph, local_rec_function_behavior, local_rec_instructions, local_rec_variableFunctor, post_dominators, FunctionBehavior::post_dominators, BehavioralHelper::start_with_a_label(), STR, TYPE_ENTRY, and writeRoutineInstructions_rec().
Referenced by WriteFunctionBody().
writeRoutineInstructions_rec()
void CWriter::writeRoutineInstructions_rec (vertex current_vertex, bool bracket, const unsigned int function_index) [protected]
Write recursively instructions belonging to a basic block of task or of a function.
Parameters
current_vertex is the basic block which is being printed
bracket tells if bracket should be added before and after this basic block
function_index is the identifier of the function to which instructions belong
compute the last statement
check the feasibility
print each instruction
in case we have phi nodes we check if some assignments should be printed
Feedback edge on the false path of an if
Target is not a while or a for
now we can analyze the following basic blocks
then adjust post dominator
now we can analyze the following basic blocks
in case we have phi nodes we check if some assignments should be printed
Last basic block of a while/for loop
added a fake indent
Definition at line 548 of file c_writer.cpp.
References IndentedOutputStream::Append(), basic_block_prefix, basic_block_tail, basic_blocks_labels, bb_analyzed, bb_frontier, CFG_SELECTOR, BBGraph::CGetBBEdgeInfo(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetLoops(), OpGraph::CGetOpNodeInfo(), BehavioralHelper::clear_renaming_table(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, DOALL_LOOP, dominators, BehavioralHelper::end_with_a_cond_or_goto(), FB_CFG_SELECTOR, BehavioralHelper::get_function_index(), dominance< GraphObj >::get_immediate_dominator(), GET_INDEX_NODE, tree_node::get_kind(), GET_NAME, GET_TYPE, graph::GetSelector(), goto_list, INDENT_DBG_MEX, indented_output_stream, instrWriter, local_rec_bb_fcfgGraph, local_rec_behavioral_helper, local_rec_cfgGraph, local_rec_function_behavior, local_rec_instructions, local_rec_variableFunctor, NULL_VERTEX, post_dominators, BehavioralHelper::print_constant(), BehavioralHelper::PrintVariable(), BehavioralHelper::rename_a_variable(), renaming_table, BehavioralHelper::start_with_a_label(), STR, THROW_ASSERT, THROW_ERROR, TM, TYPE_FOR, TYPE_IF, TYPE_INIT, TYPE_LABEL, TYPE_MULTIIF, TYPE_SWITCH, TYPE_VPHI, TYPE_WHILE, verbose, WriteBBHeader(), WriteBodyLoop(), writePostInstructionInfo(), and writePreInstructionInfo().
Referenced by WriteBodyLoop(), and writeRoutineInstructions().
Field Documentation
additionalIncludes
std::vector<std::string> CWriter::additionalIncludes [protected]
Definition at line 193 of file c_writer.hpp.
Referenced by Initialize().
AppM
const application_managerConstRef CWriter::AppM [protected]
the manager of the application
Definition at line 101 of file c_writer.hpp.
Referenced by declare_cast_types(), DeclareFunctionTypes(), DeclareLocalVariables(), GetLocalVariables(), EdgeCWriter::Initialize(), BasicBlocksProfilingCWriter::print_edge(), StartFunctionBody(), WriteBuiltinWaitCall(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), HLSCWriter::WriteFile(), WriteFunctionBody(), DiscrepancyAnalysisCWriter::WriteFunctionDeclaration(), WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteFunctionImplementation(), BasicBlocksProfilingCWriter::WriteGlobalDeclarations(), WriteGlobalDeclarations(), HLSCWriter::WriteHeader(), WriteHeader(), HLSCWriter::WriteMainTestbench(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), DiscrepancyAnalysisCWriter::writePreInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and HLSCWriter::WriteSimulatorInitMemory().
basic_block_prefix
std::map<unsigned int, std::string> CWriter::basic_block_prefix [protected]
string to be printed at the beginning of a given basic block
Definition at line 135 of file c_writer.hpp.
Referenced by EndFunctionBody(), schedule_copies(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
basic_block_tail
std::map<unsigned int, std::string> CWriter::basic_block_tail [protected]
string to be printed at the end of a given basic block
Definition at line 138 of file c_writer.hpp.
Referenced by EndFunctionBody(), schedule_copies(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
basic_blocks_labels
std::map<unsigned int, std::string> CWriter::basic_blocks_labels [protected]
Definition at line 145 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
bb_analyzed
CustomOrderedSet<vertex> CWriter::bb_analyzed [protected]
Definition at line 144 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
bb_frontier
CustomOrderedSet<vertex> CWriter::bb_frontier [protected]
Definition at line 143 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
bb_label_counter
size_t CWriter::bb_label_counter [protected]
Counter of the invocations of writeRoutineInstructions; this counter allows to print different labels in differnt tasks to avoid problem due to multiple tasks inlineing.
Definition at line 118 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), and writeRoutineInstructions().
debug_level
int CWriter::debug_level [protected]
the debug level
Definition at line 127 of file c_writer.hpp.
Referenced by BasicBlocksProfilingCWriter::BasicBlocksProfilingCWriter(), DeclareFunctionTypes(), DeclareLocalVariables(), DeclareType(), DeclareVariable(), EdgeCWriter::EdgeCWriter(), HLSCWriter::HLSCWriter(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteMainTestbench(), HLSCWriter::WriteParamInitialization(), EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), writeRoutineInstructions_rec(), and HLSCWriter::WriteSimulatorInitMemory().
dominators
const dominance<BBGraph>* CWriter::dominators [protected]
Definition at line 150 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
fake_max_tree_node_id
unsigned int CWriter::fake_max_tree_node_id [protected]
Definition at line 132 of file c_writer.hpp.
Referenced by create_new_identifier(), and Initialize().
globally_declared_types
CustomSet<std::string> CWriter::globally_declared_types [protected]
This set contains the list of the non built_in types already declared in the global scope.
Definition at line 110 of file c_writer.hpp.
Referenced by DeclareFunctionTypes(), DeclareType(), Initialize(), and WriteGlobalDeclarations().
globallyDeclVars
CustomSet<unsigned int> CWriter::globallyDeclVars [protected]
Definition at line 112 of file c_writer.hpp.
Referenced by DeclareVariable(), Initialize(), and WriteGlobalDeclarations().
goto_list
CustomOrderedSet<vertex> CWriter::goto_list [protected]
Definition at line 146 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
indented_output_stream
const IndentedOutputStreamRef CWriter::indented_output_stream [protected]
Represents the stream we are currently writing to.
Definition at line 107 of file c_writer.hpp.
Referenced by compute_phi_nodes(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), DeclareType(), DeclareVariable(), EndFunctionBody(), BasicBlocksProfilingCWriter::print_edge(), StartFunctionBody(), DiscrepancyAnalysisCWriter::WriteBBHeader(), HLSCWriter::WriteBinaryMemoryInit(), WriteBuiltinWaitCall(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraCodeBeforeEveryMainCall(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), HLSCWriter::WriteFile(), WriteFile(), WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteGlobalDeclarations(), BasicBlocksProfilingCWriter::WriteGlobalDeclarations(), WriteGlobalDeclarations(), WriteHashTableImplementation(), EdgeCWriter::WriteHeader(), HLSCWriter::WriteHeader(), WriteHeader(), writeInclude(), HLSCWriter::WriteMainTestbench(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteParamInMemory(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), DiscrepancyAnalysisCWriter::writePreInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), writeRoutineInstructions_rec(), HLSCWriter::WriteSimulatorInitMemory(), HLSCWriter::WriteTestbenchFunctionCall(), HLSCWriter::WriteTestbenchGlobalVars(), HLSCWriter::WriteTestbenchHelperFunctions(), and HLSCWriter::WriteZeroedBytes().
instrWriter
const InstructionWriterRef CWriter::instrWriter [protected]
Contains the class used to write instructions.
Definition at line 115 of file c_writer.hpp.
Referenced by DeclareVariable(), getInstructionWriter(), Initialize(), StartFunctionBody(), WriteFunctionDeclaration(), HLSCWriter::WriteGlobalDeclarations(), WriteGlobalDeclarations(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
local_rec_bb_fcfgGraph
BBGraphConstRef CWriter::local_rec_bb_fcfgGraph [protected]
Definition at line 152 of file c_writer.hpp.
Referenced by writeRoutineInstructions(), and writeRoutineInstructions_rec().
local_rec_behavioral_helper
BehavioralHelperConstRef CWriter::local_rec_behavioral_helper [protected]
Definition at line 154 of file c_writer.hpp.
Referenced by writeRoutineInstructions(), and writeRoutineInstructions_rec().
local_rec_cfgGraph
OpGraphConstRef CWriter::local_rec_cfgGraph [protected]
Definition at line 153 of file c_writer.hpp.
Referenced by writeRoutineInstructions(), and writeRoutineInstructions_rec().
local_rec_function_behavior
FunctionBehaviorConstRef CWriter::local_rec_function_behavior [protected]
Definition at line 148 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
local_rec_instructions
CustomOrderedSet<vertex> CWriter::local_rec_instructions [protected]
Definition at line 149 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
local_rec_variableFunctor
var_pp_functorConstRef CWriter::local_rec_variableFunctor [protected]
Definition at line 147 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
output_level
int CWriter::output_level [protected]
the output level
Definition at line 130 of file c_writer.hpp.
Referenced by HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteFile(), and HLSCWriter::WriteSimulatorInitMemory().
Param
const ParameterConstRef CWriter::Param [protected]
set of parameters
Definition at line 124 of file c_writer.hpp.
Referenced by DiscrepancyAnalysisCWriter::DeclareLocalVariables(), DeclareType(), DiscrepancyAnalysisCWriter::DiscrepancyAnalysisCWriter(), EdgeCWriter::EdgeCWriter(), HLSCWriter::HLSCWriter(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteGlobalDeclarations(), BasicBlocksProfilingCWriter::WriteGlobalDeclarations(), HLSCWriter::WriteHeader(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), HLSCWriter::WriteSimulatorInitMemory(), HLSCWriter::WriteTestbenchFunctionCall(), and HLSCWriter::WriteTestbenchHelperFunctions().
post_dominators
const dominance<BBGraph>* CWriter::post_dominators [protected]
Definition at line 151 of file c_writer.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
renaming_table
std::map<vertex, std::map<unsigned int, std::string> > CWriter::renaming_table [protected]
renaming table used by phi node destruction procedure
Definition at line 141 of file c_writer.hpp.
Referenced by EndFunctionBody(), insert_copies(), schedule_copies(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
TM
const tree_managerConstRef CWriter::TM [protected]
The tree manager.
Definition at line 104 of file c_writer.hpp.
Referenced by compute_phi_nodes(), create_new_identifier(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), DeclareLocalVariables(), DeclareType(), DeclareVariable(), HLSCWriter::HLSCWriter(), Initialize(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), DiscrepancyAnalysisCWriter::WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteFunctionImplementation(), BasicBlocksProfilingCWriter::WriteGlobalDeclarations(), HLSCWriter::WriteHeader(), HLSCWriter::WriteMainTestbench(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteParamInMemory(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), DiscrepancyAnalysisCWriter::writePreInstructionInfo(), EdgeCWriter::writeRoutineInstructions_rec(), writeRoutineInstructions_rec(), HLSCWriter::WriteSimulatorInitMemory(), and HLSCWriter::WriteTestbenchFunctionCall().
verbose
bool CWriter::verbose [protected]
Verbosity means that a comment is printed for each line in the output file.
Definition at line 121 of file c_writer.hpp.
Referenced by DeclareType(), DeclareVariable(), EndFunctionBody(), EdgeCWriter::writeRoutineInstructions_rec(), and writeRoutineInstructions_rec().
writtenIncludes
CustomOrderedSet<std::string> CWriter::writtenIncludes [protected]
Definition at line 194 of file c_writer.hpp.
Referenced by Initialize(), and writeInclude().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/c_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/c_writer.cpp