AddOpPhiFlowEdges Class Reference
Superclass include.
#include <add_op_phi_flow_edges.hpp>
Public Member Functions
AddOpPhiFlowEdges (const application_managerRef AppM, const unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~AddOpPhiFlowEdges () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Performs the adding of flow edges to operation graphs.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Utility include Class to perform adding of flow edges targeting phi to operation graph
Definition at line 53 of file add_op_phi_flow_edges.hpp.
Constructor & Destructor Documentation
AddOpPhiFlowEdges()
AddOpPhiFlowEdges::AddOpPhiFlowEdges (const application_managerRef _AppM, const unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the function index
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior includes tree includes
Definition at line 62 of file add_op_phi_flow_edges.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~AddOpPhiFlowEdges().
 AddOpPhiFlowEdges()
AddOpPhiFlowEdges::~AddOpPhiFlowEdges () [override], [default]
Destructor.
Referenced by AddOpPhiFlowEdges().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > AddOpPhiFlowEdges::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 70 of file add_op_phi_flow_edges.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DOM_POST_DOM_COMPUTATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, OPERATIONS_CFG_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void AddOpPhiFlowEdges::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 95 of file add_op_phi_flow_edges.cpp.
References FunctionFrontendFlowStep::bb_version, FunctionBehavior::FLG, FLG_SELECTOR, FunctionFrontendFlowStep::function_behavior, GET_TYPE, and TYPE_PHI.
InternalExec()
DesignFlowStep_Status AddOpPhiFlowEdges::InternalExec () [override], [virtual]
Performs the adding of flow edges to operation graphs.
Returns
the exit status of this step
The control flow graph of operation
The control flow graph of basic block
Check if the phi is not in the target of a feedback edge
Approximation: we consider all conditions
Implements FunctionFrontendFlowStep.
Definition at line 112 of file add_op_phi_flow_edges.cpp.
References OpGraph::CGetOpGraphInfo(), OpGraph::CGetOpNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::DOM_TREE, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionBehavior::FCFG, FLG_SELECTOR, FunctionFrontendFlowStep::function_behavior, GET_NAME, GET_NODE, GET_TYPE, INDENT_DBG_MEX, STR, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, and TYPE_PHI.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_op_phi_flow_edges.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_op_phi_flow_edges.cpp