refcount< T > Struct Template Reference
Template borrowed from the ANTLR library by Terence Parr (http://www.jGuru.com - Software rights: http://www.antlr.org/license.html).
#include <refcount.hpp>
Data Structures
struct Ref
Public Member Functions
refcount (T *p=0)
template<class null_deleter >
refcount (T *p, null_deleter &d)
refcount (const refcount< T > &other)
~refcount ()
refcount< T > & operator= (const refcount< T > &other)
bool operator== (const refcount< T > &other)
operator T* () const
operator Wrefcount< T > () const
T * operator-> () const
T * get () const
template<class newType >
operator refcount< newType > ()
Private Attributes
struct refcount::Ref * ref
Friends
class Wrefcount< T >
Detailed Description
template<typename T>
struct refcount< T >
Template borrowed from the ANTLR library by Terence Parr (http://www.jGuru.com - Software rights: http://www.antlr.org/license.html).
refcount is a simple template class useful for passing references to function templates (algorithms) that would usually take copies of their arguments and to get transparent to the programmer all the allocation and deallocation issues. The original class has been extended to support refcount object that does not deallocate the ptr object. This can be useful in case of circular references. In particular, this implementation works similarly to the smart_pointer object when a null deleter is passed to the contructor.
Definition at line 94 of file refcount.hpp.
Constructor & Destructor Documentation
refcount() [1/3]
template<typename T>
refcount< T >::refcount (T * p = 0) [inline], [explicit]
Definition at line 128 of file refcount.hpp.
refcount() [2/3]
template<typename T>
template<class null_deleter >
refcount< T >::refcount (T * p, null_deleter & d) [inline], [explicit]
Definition at line 132 of file refcount.hpp.
refcount() [3/3]
template<typename T>
refcount< T >::refcount (const refcount< T > & other) [inline]
Definition at line 136 of file refcount.hpp.
 refcount()
template<typename T>
refcount< T >::~refcount () [inline]
Definition at line 139 of file refcount.hpp.
Member Function Documentation
get()
template<typename T>
T* refcount< T >::get () const [inline]
Definition at line 169 of file refcount.hpp.
Referenced by module::add_event(), module::add_gen_port(), module::add_in_out_port(), module::add_in_port(), module::add_internal_object(), module::add_local_data(), port_o::add_n_ports(), signal_o::add_n_signals(), module::add_out_port(), module::add_process(), module::add_service(), CallGraphManager::AddFunction(), Scheduling::compute_b_tag(), Scheduling::compute_b_tag_size(), tree_node_index_factory::create_tree_node(), AsnParser::Exec(), AadlParser::Exec(), CreateAddressTranslation::Exec(), port_o::fix_port_properties(), GetPointer(), TestbenchGenerationBaseStep::initialize_input_signals(), tree_helper::op_symbol(), for_each_functor< T, visitor_obj >::operator()(), std::hash< refcount< T > >::operator()(), RefCountOrder< T >::operator()(), operator<<(), Wrefcount< const HLS_manager >::operator=(), refcount< structural_manager >::operator==(), CInitializationParser::Parse(), BehavioralHelper::print_node(), BehavioralHelper::PrintVariable(), read_technology_File(), read_technology_library(), SDCSorter::SDCSorter(), Loop::SetParent(), TestbenchMemoryAllocation::TestbenchMemoryAllocation(), TestbenchGenerationBaseStep::write_auxiliary_signal_declaration(), WishboneInterfaceTestbench::write_call(), WishboneInterfaceTestbench::write_file_reading_operations(), MinimalInterfaceTestbench::write_file_reading_operations(), HDL_manager::write_fsm(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), HDL_manager::write_module(), TestbenchGenerationBaseStep::write_module_instantiation(), TestbenchGenerationBaseStep::write_output_checks(), MinimalInterfaceTestbench::write_output_signal_declaration(), WishboneInterfaceTestbench::write_signals(), MinimalInterfaceTestbench::write_slave_initializations(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), WishboneInterfaceTestbench::write_wishbone_output_signal_declaration(), Schedule::WriteDot(), EdgeCWriter::writeRoutineInstructions(), and target_device::xload_device_parameters().
operator refcount< newType >()
template<typename T>
template<class newType >
refcount< T >::operator refcount< newType > () [inline]
Definition at line 174 of file refcount.hpp.
operator T*()
template<typename T>
refcount< T >::operator T* () const [inline]
Definition at line 157 of file refcount.hpp.
operator Wrefcount< T >()
template<typename T>
refcount< T >::operator Wrefcount< T > () const [inline]
Definition at line 161 of file refcount.hpp.
operator->()
template<typename T>
T* refcount< T >::operator-> () const [inline]
Definition at line 165 of file refcount.hpp.
operator=()
template<typename T>
refcount<T>& refcount< T >::operator= (const refcount< T > & other) [inline]
Definition at line 145 of file refcount.hpp.
operator==()
template<typename T>
bool refcount< T >::operator== (const refcount< T > & other) [inline]
Definition at line 153 of file refcount.hpp.
Friends And Related Function Documentation
Wrefcount< T >
template<typename T>
friend class Wrefcount< T > [friend]
Definition at line 97 of file refcount.hpp.
Field Documentation
ref
template<typename T>
struct refcount::Ref * refcount< T >::ref [private]
Referenced by refcount< structural_manager >::operator=().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/utility/refcount.hpp