GenerateSynthesisScripts Class Reference
superclass include
#include <generate_synthesis_scripts.hpp>
Public Member Functions
GenerateSynthesisScripts (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~GenerateSynthesisScripts () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
superclass include
Definition at line 46 of file generate_synthesis_scripts.hpp.
Constructor & Destructor Documentation
GenerateSynthesisScripts()
GenerateSynthesisScripts::GenerateSynthesisScripts (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
. include behavior include HLS include STL includes tree include wrapper/synthesis include
Definition at line 64 of file generate_synthesis_scripts.cpp.
References DesignFlowStep::debug_level, GENERATE_SYNTHESIS_SCRIPT, GET_CLASS, and ~GenerateSynthesisScripts().
 GenerateSynthesisScripts()
GenerateSynthesisScripts::~GenerateSynthesisScripts () [override], [default]
Destructor.
Referenced by GenerateSynthesisScripts().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > GenerateSynthesisScripts::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 72 of file generate_synthesis_scripts.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, GENERATE_HDL, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and TOP_FUNCTION.
Exec()
DesignFlowStep_Status GenerateSynthesisScripts::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 96 of file generate_synthesis_scripts.cpp.
References FunctionBehavior::CGetBehavioralHelper(), BehavioralHelper::get_function_name(), HLS_step::HLSMgr, SUCCESS, THROW_ASSERT, and hls::top.
HasToBeExecuted()
bool GenerateSynthesisScripts::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 108 of file generate_synthesis_scripts.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/backend/generate_synthesis_scripts.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/backend/generate_synthesis_scripts.cpp