PhiOpt Class Reference
Restructure the tree control flow graph.
#include <phi_opt.hpp>
Public Member Functions
PhiOpt (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~PhiOpt () override
Destructor.
DesignFlowStep_Status InternalExec () override
Updates the tree to have a more compliant CFG.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Member Functions
PhiOpt_PatternType IdentifyPattern (const unsigned int bb_index) const
Identify to which pattern an empty basic block belongs.
void ApplyDiffNothing (const unsigned int bb_index)
Remove an empty basic block with multiple input edges.
void ApplyGimpleNothing (const unsigned int bb_index)
Remove an empty basic block dominated by gimple assign.
void ApplyIfMerge (const unsigned int bb_index)
Transform the control flow graph by merging a gimple_phi dominated by a gimple_cond.
void ApplyIfNothing (const unsigned int bb_index)
Transform the control flow graph by eliminating an empty basic block dominated by gimple_cond without modifying phi.
void ApplyIfRemove (const unsigned int bb_index)
Transform the control flow graph by removing a gimple_phi dominated by a gimple_cond.
void ApplyMultiMerge (const unsigned int bb_index)
Transform the control flow graph by merging a gimple_phi dominated by a gimple_multi_way_if.
void ApplyMultiNothing (const unsigned int bb_index)
Transform the control flow graph by eliminating an empty basic block dominated by gimple_multi_way_if without modifying phi.
void ApplyMultiRemove (const unsigned int bb_index)
Transform the control flow graph by removing a gimple_phi dominated by a gimple_multi_way_if.
void SinglePhiOptimization (const unsigned int bb_index)
Transform single input phi in assignment.
void ChainOptimization (const unsigned int bb_index)
Remove chains of basic blocks.
void MergePhi (const unsigned int bb_index)
Remove a basic block composed only of phis my merging with the successor.
void RemoveCondExpr (const tree_nodeRef statement)
Remove a redundant cond expr.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
tree_managerRef TM
The tree manager.
tree_manipulationConstRef tree_man
The tree manipulation.
statement_list * sl {nullptr}
The basic block graph of the function.
bool bb_modified
flag used to restart code motion step
ScheduleRef schedule
The scheduling solution.
Static Private Attributes
static bool tree_dumped
flag to check if initial tree has been dumped
Friends
class short_circuit_taf
Additional Inherited Members
Detailed Description
Restructure the tree control flow graph.
Definition at line 86 of file phi_opt.hpp.
Constructor & Destructor Documentation
PhiOpt()
PhiOpt::PhiOpt (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
parameters is the set of input parameters
header include . include behavior includes design_flow_manager includes parser/treegcc include STD include design_flows/technology includes tree includes utility include
Definition at line 99 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~PhiOpt().
 PhiOpt()
PhiOpt::~PhiOpt () [override], [default]
Destructor.
Referenced by PhiOpt().
Member Function Documentation
ApplyDiffNothing()
void PhiOpt::ApplyDiffNothing (const unsigned int bb_index) [private]
Remove an empty basic block with multiple input edges.
Create empty basic block
Add predecessor as pred basic block
Add successor as succ basic block
Fix successor of predecessor
Fix predecessor of successor
Fix gimple_multi_way_if
Fix phis
Definition at line 618 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, THROW_ASSERT, and TM.
Referenced by InternalExec().
ApplyGimpleNothing()
void PhiOpt::ApplyGimpleNothing (const unsigned int bb_index) [private]
Remove an empty basic block dominated by gimple assign.
Parameters
bb_index is the index of the empty basic block
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 895 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, and TM.
Referenced by InternalExec().
ApplyIfMerge()
void PhiOpt::ApplyIfMerge (const unsigned int bb_index) [private]
Transform the control flow graph by merging a gimple_phi dominated by a gimple_cond.
Parameters
bb_index is the index of the empty basic block
True if bb_index is on the true edge
The condition
Remove gimple_cond from list of statement
Update all the phis
The value coming from true edge
The value coming from false edge
The type of the expression
Create the ssa with the new input of the phi
Create a nop with virtual operands
Create the cond expr
Create the assign
Updating the phi
Do nothing - this edge will be removed
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 712 of file phi_opt.cpp.
References tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manipulation::ExtractCondition(), tree_node::get_kind(), tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_helper::is_a_vector(), statement_list::list_of_bloc, tree_manager::new_tree_node_id(), phi, sl, STR, THROW_ASSERT, TM, TOK, TOK_BIT_VALUES, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, tree_node::ToString(), and tree_man.
Referenced by InternalExec().
ApplyIfNothing()
void PhiOpt::ApplyIfNothing (const unsigned int bb_index) [private]
Transform the control flow graph by eliminating an empty basic block dominated by gimple_cond without modifying phi.
Parameters
bb_index is the index of the empty basic block
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 851 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, THROW_UNREACHABLE, and TM.
Referenced by InternalExec().
ApplyIfRemove()
void PhiOpt::ApplyIfRemove (const unsigned int bb_index) [private]
Transform the control flow graph by removing a gimple_phi dominated by a gimple_cond.
Parameters
bb_index is the index of the empty basic block
True if bb_index is on the true edge
Remove gimple_cond from list of statement. New statements can be pushed at the end
The condition
Remove all the phis
The value coming from true edge
The value coming from false edge
The type of the expression
Create a nop with virtual operands
Replace all use of virtual defined in phi with res of phi
Create the cond expr
Create the assign
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 926 of file phi_opt.cpp.
References tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manipulation::ExtractCondition(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_helper::is_a_vector(), statement_list::list_of_bloc, tree_manager::new_tree_node_id(), phi, sl, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, tree_node::ToString(), and tree_man.
Referenced by InternalExec().
ApplyMultiMerge()
void PhiOpt::ApplyMultiMerge (const unsigned int bb_index) [private]
Transform the control flow graph by merging a gimple_phi dominated by a gimple_multi_way_if.
Parameters
bb_index is the index of the empty basic block
True if bb_index is on the first edge
The gimple multi way if
Temporary remove gimple multi way if
The first condition
The second condition
Update all the phis
The value coming from the first edge
The value coming from the second edge
The type of the expression
Create the ssa with the new input of the phi
Create a nop with virtual operands
Create the cond expr
Create the assign
Updating the phi
Do nothing - this edge will be removed
Readding gimple multi way if it has more than two exits
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 1079 of file phi_opt.cpp.
References tree_manager::create_tree_node(), tree_manipulation::CreateOrExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_node::get_kind(), tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, tree_helper::is_a_vector(), statement_list::list_of_bloc, tree_manager::new_tree_node_id(), phi, sl, STR, TM, TOK, TOK_BIT_VALUES, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, and tree_man.
Referenced by InternalExec().
ApplyMultiNothing()
void PhiOpt::ApplyMultiNothing (const unsigned int bb_index) [private]
Transform the control flow graph by eliminating an empty basic block dominated by gimple_multi_way_if without modifying phi.
Parameters
bb_index is the index of the empty basic block
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 1287 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, and TM.
Referenced by InternalExec().
ApplyMultiRemove()
void PhiOpt::ApplyMultiRemove (const unsigned int bb_index) [private]
Transform the control flow graph by removing a gimple_phi dominated by a gimple_multi_way_if.
Parameters
bb_index is the index of the empty basic block
True if bb_index is on the first edge
The gimple multi way if
Temporary remove gimple multi way if
The first condition
The second condition
Remove all the phis
The value coming from the first edge
The value coming from the second edge
The type of the expression
Create a nop with virtual operands
Replace all use of virtual defined in phi with res of phi
Create the cond expr
Create the assign
Readd multi way if
Refactoring of the cfg - updating the predecessor
Refactoring of the cfg - updating the successor
Remove the current basic block
Definition at line 1330 of file phi_opt.cpp.
References tree_manager::create_tree_node(), tree_manipulation::CreateOrExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, tree_helper::is_a_vector(), statement_list::list_of_bloc, tree_manager::new_tree_node_id(), phi, sl, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, tree_node::ToString(), and tree_man.
Referenced by InternalExec().
ChainOptimization()
void PhiOpt::ChainOptimization (const unsigned int bb_index) [private]
Remove chains of basic blocks.
Parameters
bb_index is the starting basic block index
The phis are taken from the first block
Move statement of second block in first one
Update successor of curr_bb
Fix successor of succ
Remove bb
Definition at line 1847 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, bloc::EXIT_BLOCK_ID, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, THROW_ASSERT, and TM.
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionFrontendFlowStep::FunctionRelationship > > PhiOpt::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 123 of file phi_opt.cpp.
References ABORTED, BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, FunctionFrontendFlowStep::function_id, tree_manager::get_tree_node_const(), DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, tree_helper::is_a_nop_function_decl(), NONEXISTENT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, SWITCH_FIX, THROW_UNREACHABLE, TM, UNCHANGED, UNEXECUTED, UNNECESSARY, and USE_COUNTING.
ComputeRelationships()
void PhiOpt::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 2051 of file phi_opt.cpp.
References FunctionFrontendFlowStep::ComputeRelationships(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
IdentifyPattern()
PhiOpt_PatternType PhiOpt::IdentifyPattern (const unsigned int bb_index) const [private]
Identify to which pattern an empty basic block belongs.
Parameters
bb_index is the index of the empty basic block
Returns
the identified pattern
The gimple multi way if
The conditions
Successor is ending if of the function
Simulate to add the cond expr and check if there are problems with timing
The gimple multi way if
The first condition
The value coming from the first edge
The value coming from the second edge
True if bb_index is on the first edge
The type of the expression
Create the cond expr
Create the assign
Workaround: we need to consider the overhead due to multiplexers associated with the phi; for this reason definition is one of the operands; this is not fully consistent, but it is a temporary assignment
Created statement is not added to the predecessor
Definition at line 1556 of file phi_opt.cpp.
References Schedule::CanBeMoved(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DIFF_NOTHING, bloc::ENTRY_BLOCK_ID, Schedule::EvaluateCondsMerging(), bloc::EXIT_BLOCK_ID, GET_CONST_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), GIMPLE_NOTHING, IF_MERGE, IF_NOTHING, IF_REMOVE, INDENT_DBG_MEX, tree_helper::is_a_vector(), statement_list::list_of_bloc, MULTI_MERGE, MULTI_NOTHING, MULTI_REMOVE, tree_manager::new_tree_node_id(), phi, schedule, sl, STR, THROW_ASSERT, TM, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, UNCHANGED, and UNKNOWN.
Referenced by InternalExec().
Initialize()
void PhiOpt::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 107 of file phi_opt.cpp.
References FrontendFlowStep::AppM, bb_modified, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), DesignFlowStep::parameters, schedule, sl, TM, and tree_man.
InternalExec()
DesignFlowStep_Status PhiOpt::InternalExec () [override], [virtual]
Updates the tree to have a more compliant CFG.
Removed blocks composed only of phi
Check that two basic block do not have any common predecessor
Check that ssa defined by phi are used only once
Transform single input phi
Transform chain of basic blocks
Workaround to avoid invalidation of pointer
Remove empty basic block
Remove nop
Transform chain of basic blocks
If there is only a single vuse replace vdef with vuse in all the uses of vdef
Check that all the uses are not in phi or not defining a self loop
Implements FunctionFrontendFlowStep.
Definition at line 178 of file phi_opt.cpp.
References ApplyDiffNothing(), ApplyGimpleNothing(), ApplyIfMerge(), ApplyIfNothing(), ApplyIfRemove(), ApplyMultiMerge(), ApplyMultiNothing(), ApplyMultiRemove(), FrontendFlowStep::AppM, bb_modified, ChainOptimization(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DIFF_NOTHING, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, GET_INDEX_NODE, GET_NODE, FunctionFrontendFlowStep::GetName(), GIMPLE_NOTHING, IdentifyPattern(), IF_MERGE, IF_NOTHING, IF_REMOVE, INDENT_DBG_MEX, statement_list::list_of_bloc, MergePhi(), MULTI_MERGE, MULTI_NOTHING, MULTI_REMOVE, DesignFlowStep::parameters, phi, RemoveCondExpr(), tree_manager::ReplaceTreeNode(), test_panda::restart, SinglePhiOptimization(), sl, STR, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, TM, ToString(), UNCHANGED, UNKNOWN, and FunctionFrontendFlowStep::WriteBBGraphDot().
MergePhi()
void PhiOpt::MergePhi (const unsigned int bb_index) [private]
Remove a basic block composed only of phis my merging with the successor.
Parameters
block is the index of the basic block
Fixing phis
Removing phi only if number of uses is 1
These are phis which were present only in the predecessor
Fixing predecessor
Fixing gimple phi of predecessor
Fixing successor
Erasing basic block
Definition at line 1898 of file phi_opt.cpp.
References bb_modified, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, THROW_ASSERT, and TM.
Referenced by InternalExec().
RemoveCondExpr()
void PhiOpt::RemoveCondExpr (const tree_nodeRef statement) [private]
Remove a redundant cond expr.
Parameters
statement is the statement containing
Definition at line 2035 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, tree_manager::ReplaceTreeNode(), sl, THROW_ASSERT, TM, and tree_node::ToString().
Referenced by InternalExec().
SinglePhiOptimization()
void PhiOpt::SinglePhiOptimization (const unsigned int bb_index) [private]
Transform single input phi in assignment.
Building temp set of use stmts (to avoid invalidation during loop execution and to skip phi)
Definition at line 1793 of file phi_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, tree_manager::ReplaceTreeNode(), sl, STR, THROW_ASSERT, and TM.
Referenced by InternalExec().
Friends And Related Function Documentation
short_circuit_taf
friend class short_circuit_taf [friend]
Definition at line 88 of file phi_opt.hpp.
Field Documentation
bb_modified
bool PhiOpt::bb_modified [private]
flag used to restart code motion step
Definition at line 104 of file phi_opt.hpp.
Referenced by Initialize(), InternalExec(), and MergePhi().
schedule
ScheduleRef PhiOpt::schedule [private]
The scheduling solution.
Definition at line 107 of file phi_opt.hpp.
Referenced by IdentifyPattern(), and Initialize().
sl
statement_list* PhiOpt::sl {nullptr} [private]
The basic block graph of the function.
Definition at line 98 of file phi_opt.hpp.
Referenced by ApplyDiffNothing(), ApplyGimpleNothing(), ApplyIfMerge(), ApplyIfNothing(), ApplyIfRemove(), ApplyMultiMerge(), ApplyMultiNothing(), ApplyMultiRemove(), ChainOptimization(), IdentifyPattern(), Initialize(), InternalExec(), MergePhi(), RemoveCondExpr(), and SinglePhiOptimization().
TM
tree_managerRef PhiOpt::TM [private]
The tree manager.
Definition at line 92 of file phi_opt.hpp.
Referenced by ApplyDiffNothing(), ApplyGimpleNothing(), ApplyIfMerge(), ApplyIfNothing(), ApplyIfRemove(), ApplyMultiMerge(), ApplyMultiNothing(), ApplyMultiRemove(), ChainOptimization(), ComputeFrontendRelationships(), IdentifyPattern(), Initialize(), InternalExec(), MergePhi(), RemoveCondExpr(), and SinglePhiOptimization().
tree_dumped
bool PhiOpt::tree_dumped [static], [private]
flag to check if initial tree has been dumped
Definition at line 101 of file phi_opt.hpp.
tree_man
tree_manipulationConstRef PhiOpt::tree_man [private]
The tree manipulation.
Definition at line 95 of file phi_opt.hpp.
Referenced by ApplyIfMerge(), ApplyIfRemove(), ApplyMultiMerge(), ApplyMultiRemove(), and Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/phi_opt.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/phi_opt.cpp