TimeStamp Struct Reference
The type used for timestamp.
#include <utility.hpp>
Public Member Functions
TimeStamp ()
Empty constructor: timestamp is set to 01-01-1970 00.00.
TimeStamp (const std::string &timestamp)
Constructor from string.
Static Public Member Functions
static std::string GetCurrentTimeStamp ()
Return a timestamp of the current time.
Data Fields
std::string timestamp
Friends
std::ostream & operator<< (std::ostream &os, const TimeStamp &timestamp)
Friend definition of the << operator.
bool operator<= (const TimeStamp &timestamp1, const TimeStamp &timestamp2)
Detailed Description
The type used for timestamp.
Definition at line 249 of file utility.hpp.
Constructor & Destructor Documentation
TimeStamp() [1/2]
TimeStamp::TimeStamp ()
Empty constructor: timestamp is set to 01-01-1970 00.00.
Definition at line 47 of file utility.cpp.
TimeStamp() [2/2]
TimeStamp::TimeStamp (const std::string & timestamp) [explicit]
Constructor from string.
Parameters
timestamp is the string containing the timestamp
Definition at line 51 of file utility.cpp.
Member Function Documentation
GetCurrentTimeStamp()
std::string TimeStamp::GetCurrentTimeStamp () [static]
Return a timestamp of the current time.
Definition at line 55 of file utility.cpp.
Referenced by Evaluation::Exec(), CBackend::Exec(), HDL_manager::write_components(), and RTLCharacterization::xwrite_characterization().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const TimeStamp & timestamp) [friend]
Friend definition of the << operator.
Parameters
os is the output stream
timestamp is the timestamp to be printed
Definition at line 70 of file utility.cpp.
operator<=
bool operator<= (const TimeStamp & timestamp1, const TimeStamp & timestamp2) [friend]
Definition at line 76 of file utility.cpp.
Field Documentation
timestamp
std::string TimeStamp::timestamp
Definition at line 251 of file utility.hpp.
Referenced by operator<<(), and operator<=().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/utility/utility.hpp
/home/osboxes/bambu/PandA-bambu/src/utility/utility.cpp