cs_interface Class Reference
#include <cs_interface.hpp>
Public Member Functions
cs_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::INTERFACE_CS_GENERATION)
Constructor.
void build_wrapper (structural_objectRef wrappedObj, structural_objectRef interfaceObj, structural_managerRef SM_minimal_interface)
virtual ~cs_interface ()
Destructor.
virtual DesignFlowStep_Status InternalExec ()
Execute the step.
Protected Member Functions
void resize_memory_ctrl_ports (structural_objectRef mem_ctrl_mod)
resize_memory_ctrl_ports
void resize_dimension_bus_port (unsigned int vector_size, structural_objectRef port)
resize_dimension_bus_port
void manage_extern_global_port_top (const structural_managerRef SM, const structural_objectRef memory_module, const structural_objectRef circuit)
manage_memory_ports_parallel_chained_parallel
void instantiate_component_parallel (const structural_managerRef SM, structural_objectRef clock_port, structural_objectRef reset_port)
instantiate_component_parallel
void add_parameter_port (const structural_managerRef SM, structural_objectRef circuit, structural_objectRef top_module)
add_parameter_port
Additional Inherited Members
Detailed Description
Definition at line 47 of file cs_interface.hpp.
Constructor & Destructor Documentation
cs_interface()
cs_interface::cs_interface (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::INTERFACE_CS_GENERATION)
Constructor.
STD include.
utility include
Definition at line 60 of file cs_interface.cpp.
References DesignFlowStep::debug_level, HLSFunctionStep::funId, GET_CLASS, DesignFlowStep::parameters, and THROW_ASSERT.
 cs_interface()
cs_interface::~cs_interface () [virtual]
Destructor.
Definition at line 67 of file cs_interface.cpp.
Member Function Documentation
add_parameter_port()
void cs_interface::add_parameter_port (const structural_managerRef SM, structural_objectRef circuit, structural_objectRef top_module) [protected]
add_parameter_port
Parameters
SM
circuit
top_module
Definition at line 115 of file cs_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), CLOCK_PORT_NAME, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, get_id(), structural_object::get_typeRef(), port_o::IN, port_o::OUT, PRINT_DBG_MEX, and RESET_PORT_NAME.
Referenced by InternalExec().
build_wrapper()
void cs_interface::build_wrapper (structural_objectRef wrappedObj, structural_objectRef interfaceObj, structural_managerRef SM_minimal_interface)
instantiate_component_parallel()
void cs_interface::instantiate_component_parallel (const structural_managerRef SM, structural_objectRef clock_port, structural_objectRef reset_port) [protected]
instantiate_component_parallel
Parameters
SM
clock_port
reset_port
Definition at line 143 of file cs_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), ceil_log2(), CLOCK_PORT_NAME, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, hls::HLS_T, DesignFlowStep::parameters, port_o_K, PRINT_DBG_MEX, RESET_PORT_NAME, resize_memory_ctrl_ports(), and STR.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status cs_interface::InternalExec () [virtual]
Execute the step.
Returns
the exit status of this step
Set some descriptions and legal stuff
Implements HLSFunctionStep.
Definition at line 71 of file cs_interface.cpp.
References structural_manager::add_connection(), add_parameter_port(), structural_manager::add_port(), CLOCK_PORT_NAME, structural_object::find_member(), GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), get_id(), structural_object::get_id(), structural_object::get_typeRef(), HLSFunctionStep::HLS, structural_type_descriptor::id_type, port_o::IN, instantiate_component_parallel(), manage_extern_global_port_top(), DesignFlowStep::parameters, port_o_K, memory::propagate_memory_parameters(), RESET_PORT_NAME, structural_object::set_id(), structural_object::set_owner(), structural_manager::set_top_info(), SUCCESS, THROW_ERROR, and hls::top.
manage_extern_global_port_top()
void cs_interface::manage_extern_global_port_top (const structural_managerRef SM, const structural_objectRef memory_module, const structural_objectRef circuit) [protected]
manage_memory_ports_parallel_chained_parallel
Parameters
SM
memory_module
circuit
Definition at line 233 of file cs_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_port_vector(), structural_manager::add_sign_vector(), component_o_K, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_kind_text(), structural_object::get_path(), structural_object::get_typeRef(), port_o::IN, INDENT_DBG_MEX, port_o::OUT, DesignFlowStep::parameters, port_vector_o_K, and THROW_ASSERT.
Referenced by InternalExec().
resize_dimension_bus_port()
void cs_interface::resize_dimension_bus_port (unsigned int vector_size, structural_objectRef port) [protected]
resize_dimension_bus_port
Parameters
vector_size
port
Definition at line 214 of file cs_interface.cpp.
References HLS_step::HLSMgr, and structural_object::type_resize().
Referenced by resize_memory_ctrl_ports().
resize_memory_ctrl_ports()
void cs_interface::resize_memory_ctrl_ports (structural_objectRef mem_ctrl_mod) [protected]
resize_memory_ctrl_ports
Parameters
mem_ctrl_mod
Definition at line 184 of file cs_interface.cpp.
References get_id(), DesignFlowStep::parameters, and resize_dimension_bus_port().
Referenced by instantiate_component_parallel().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/cs_interface.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/cs_interface.cpp