reg_binding Class Reference
Class managing the register binding.
#include <reg_binding.hpp>
Public Types
enum type_t { STG = 0,
CDFG
 }
Public Member Functions
reg_binding (const hlsRef &HLS, const HLS_managerRef HLSMgr_)
Constructor.
virtual ~reg_binding ()
Destructor.
void bind (unsigned int sv, unsigned int index)
virtual std::string CalculateRegisterName (unsigned int i)
return the name of register to be used
unsigned int get_used_regs () const
returns number of used register
void set_used_regs (unsigned int regs)
sets number of used register
unsigned int get_register (unsigned int sv) const
return the register index where the storage value is stored
bool is_all_regs_without_enable ()
return true when all registers are without write enable: pipelining comes for free
void print_el (const_iterator &it) const
Function that print the register binding associated with a storage value.
generic_objRef get (const unsigned int &r) const
Returns reference to register object associated to a given index.
const register_obj & operator[] (unsigned int v)
redefinition of the [] operator
virtual void add_to_SM (structural_objectRef clock_port, structural_objectRef reset_port)
Add the resulting registers to the structural description of the datapath.
unsigned int get_bitsize (unsigned int r) const
return bitsize
Static Public Member Functions
static reg_bindingRef create_reg_binding (const hlsRef &HLS, const HLS_managerRef HLSMgr_)
Protected Member Functions
void compute_is_without_enable ()
compute the is with out enable relation
virtual void specialise_reg (structural_objectRef &reg, unsigned int r)
Specialise a register according to the type of the variables crossing it.
Protected Attributes
int debug
level of the verbosity during the debugging
unsigned int used_regs
number of used register
std::map< unsigned int, generic_objRef > unique_table
map between register index and object
std::map< unsigned int, unsigned int > reverse_map
bind the storage value with the register instance
std::map< unsigned int, unsigned int > bitsize_map
relation between registers and their bitsize
hlsRef HLS
HLS datastructure.
const HLS_managerRef HLSMgr
information about all the HLS synthesis
std::map< unsigned int, CustomOrderedSet< unsigned int > > reg2storage_values
map between the register and the associated storage value
CustomOrderedSet< unsigned int > is_without_enable
store the set of register without enable
bool all_regs_without_enable
when true all registers do not require write enable: pipelining comes for free
Private Member Functions
CustomOrderedSet< unsigned int > get_vars (const unsigned int &r) const
Returns the set of variable associated with the register.
unsigned int compute_bitsize (unsigned int r)
return and set the bitsize associated with given register
Detailed Description
Class managing the register binding.
Store the register binding, that is, the mapping of operations in the behavioral description into the set of selected register elements.
Definition at line 67 of file reg_binding.hpp.
Member Enumeration Documentation
type_t
enum reg_binding::type_t
Enumerator
STG
CDFG
Definition at line 70 of file reg_binding.hpp.
Constructor & Destructor Documentation
reg_binding()
reg_binding::reg_binding (const hlsRef & HLS_, const HLS_managerRef HLSMgr_)
Constructor.
HLS/binding/storage_value_information.
STL includes technology/physical_library include
Definition at line 76 of file reg_binding.cpp.
References ~reg_binding().
Referenced by create_reg_binding().
 reg_binding()
reg_binding::~reg_binding () [virtual], [default]
Destructor.
Referenced by reg_binding().
Member Function Documentation
add_to_SM()
void reg_binding::add_to_SM (structural_objectRef clock_port, structural_objectRef reset_port) [virtual]
Add the resulting registers to the structural description of the datapath.
define boolean type for command signals
Definition at line 243 of file reg_binding.cpp.
References structural_manager::add_connection(), all_regs_without_enable, CalculateRegisterName(), CLOCK_PORT_NAME, compute_is_without_enable(), hls::datapath, debug, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), hls::functionId, get_bitsize(), structural_manager::get_circ(), get_used_regs(), HLS, hls::HLS_T, HLSMgr, INDENT_OUT_MEX, is_without_enable, hls::output_level, OUTPUT_LEVEL_MINIMUM, port_o_K, PRINT_DBG_MEX, RESET_PORT_NAME, specialise_reg(), and STR.
Referenced by get(), and classic_datapath::InternalExec().
bind()
void reg_binding::bind (unsigned int sv, unsigned int index)
Definition at line 225 of file reg_binding.cpp.
References index, insert(), reg2storage_values, reverse_map, and unique_table.
Referenced by vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), chordal_coloring_register::InternalExec(), and weighted_clique_register::InternalExec().
CalculateRegisterName()
std::string reg_binding::CalculateRegisterName (unsigned int i) [virtual]
return the name of register to be used
Reimplemented in reg_binding_cs.
Definition at line 291 of file reg_binding.cpp.
References HLS, is_without_enable, hls::Param, register_SARSE, register_SE, register_SRSE, and register_STD.
Referenced by add_to_SM().
compute_bitsize()
unsigned int reg_binding::compute_bitsize (unsigned int r) [private]
return and set the bitsize associated with given register
Parameters
r is the register
Returns
the bitsize of register r
Definition at line 121 of file reg_binding.cpp.
References bitsize_map, hls::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, hls::functionId, structural_type_descriptor::get_name(), get_vars(), HLS, HLSMgr, PRINT_DBG_MEX, structural_type_descriptor::size, STD_GET_SIZE, STR, and structural_type_descriptor::vector_size.
Referenced by get(), and specialise_reg().
compute_is_without_enable()
void reg_binding::compute_is_without_enable () [protected]
compute the is with out enable relation
Definition at line 171 of file reg_binding.cpp.
References liveness::get_live_in(), liveness::get_live_out(), liveness::get_support(), get_used_regs(), get_vars(), HLS, liveness::is_a_dummy_state(), is_without_enable, and hls::Rliv.
Referenced by add_to_SM().
create_reg_binding()
reg_bindingRef reg_binding::create_reg_binding (const hlsRef & HLS, const HLS_managerRef HLSMgr_) [static]
Definition at line 82 of file reg_binding.cpp.
References hls::functionId, hls::Param, and reg_binding().
Referenced by weighted_clique_register::Initialize(), and weighted_clique_register::InternalExec().
get()
generic_objRef reg_binding::get (const unsigned int & r) const [inline]
Returns reference to register object associated to a given index.
Parameters
r is the register index
Returns
the associated reference
Definition at line 186 of file reg_binding.hpp.
References add_to_SM(), compute_bitsize(), get_bitsize(), get_vars(), and operator[]().
Referenced by mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), and VcdSignalSelection::SelectInternalSignals().
get_bitsize()
unsigned int reg_binding::get_bitsize (unsigned int r) const
return bitsize
Definition at line 136 of file reg_binding.cpp.
References bitsize_map, and THROW_ASSERT.
Referenced by add_to_SM(), and get().
get_register()
unsigned int reg_binding::get_register (unsigned int sv) const [inline]
return the register index where the storage value is stored
Parameters
sv is the storage value
Returns
the index of the register assigned to the storage value.
Definition at line 165 of file reg_binding.hpp.
Referenced by mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), fsm_controller::create_state_machine(), port_swapping::InternalExec(), VcdSignalSelection::SelectInternalSignals(), and mux_connection_binding::swap_p().
get_used_regs()
unsigned int reg_binding::get_used_regs () const [inline]
returns number of used register
Returns
the number of used register
Definition at line 146 of file reg_binding.hpp.
References used_regs.
Referenced by add_to_SM(), compute_is_without_enable(), mux_connection_binding::create_connections(), and fsm_controller::create_state_machine().
get_vars()
CustomOrderedSet< unsigned int > reg_binding::get_vars (const unsigned int & r) const [private]
Returns the set of variable associated with the register.
Parameters
r is the register
Returns
the set of associated variables
Definition at line 110 of file reg_binding.cpp.
References StorageValueInformation::get_variable_index(), HLS, reg2storage_values, hls::storage_value_information, and THROW_ASSERT.
Referenced by compute_bitsize(), compute_is_without_enable(), and get().
is_all_regs_without_enable()
bool reg_binding::is_all_regs_without_enable () [inline]
return true when all registers are without write enable: pipelining comes for free
Definition at line 171 of file reg_binding.hpp.
References all_regs_without_enable, and print_el().
Referenced by fu_binding::add_to_SM().
operator[]()
const register_obj & reg_binding::operator[] (unsigned int v)
redefinition of the [] operator
Definition at line 238 of file reg_binding.cpp.
References THROW_ASSERT.
Referenced by get().
print_el()
void reg_binding::print_el (const_iterator & it) const
Function that print the register binding associated with a storage value.
Definition at line 103 of file reg_binding.cpp.
References hls::functionId, StorageValueInformation::get_variable_index(), HLS, HLSMgr, INDENT_OUT_MEX, hls::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, hls::storage_value_information, and STR.
Referenced by is_all_regs_without_enable().
set_used_regs()
void reg_binding::set_used_regs (unsigned int regs) [inline]
sets number of used register
Parameters
regs is new number of used register
Definition at line 155 of file reg_binding.hpp.
Referenced by vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), chordal_coloring_register::InternalExec(), and weighted_clique_register::InternalExec().
specialise_reg()
void reg_binding::specialise_reg (structural_objectRef & reg, unsigned int r) [protected], [virtual]
Specialise a register according to the type of the variables crossing it.
Parameters
reg is the register
reg is the id of the register
Reimplemented in reg_binding_cs.
Definition at line 142 of file reg_binding.cpp.
References CLOCK_PORT_NAME, compute_bitsize(), hls::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, get_id(), structural_type_descriptor::get_name(), structural_object::get_path(), HLS, PRINT_DBG_MEX, RESET_PORT_NAME, structural_type_descriptor::size, STD_GET_SIZE, STR, and structural_type_descriptor::vector_size.
Referenced by add_to_SM(), and reg_binding_cs::specialise_reg().
Field Documentation
all_regs_without_enable
bool reg_binding::all_regs_without_enable [protected]
when true all registers do not require write enable: pipelining comes for free
Definition at line 105 of file reg_binding.hpp.
Referenced by add_to_SM(), and is_all_regs_without_enable().
bitsize_map
std::map<unsigned int, unsigned int> reg_binding::bitsize_map [protected]
relation between registers and their bitsize
Definition at line 90 of file reg_binding.hpp.
Referenced by compute_bitsize(), and get_bitsize().
debug
int reg_binding::debug [protected]
level of the verbosity during the debugging
Definition at line 78 of file reg_binding.hpp.
Referenced by add_to_SM().
HLS
hlsRef reg_binding::HLS [protected]
HLS datastructure.
Definition at line 93 of file reg_binding.hpp.
Referenced by add_to_SM(), CalculateRegisterName(), compute_bitsize(), compute_is_without_enable(), get_vars(), print_el(), reg_binding_cs::specialise_reg(), and specialise_reg().
HLSMgr
const HLS_managerRef reg_binding::HLSMgr [protected]
information about all the HLS synthesis
Definition at line 96 of file reg_binding.hpp.
Referenced by add_to_SM(), compute_bitsize(), and print_el().
is_without_enable
CustomOrderedSet<unsigned int> reg_binding::is_without_enable [protected]
store the set of register without enable
Definition at line 102 of file reg_binding.hpp.
Referenced by add_to_SM(), CalculateRegisterName(), and compute_is_without_enable().
reg2storage_values
std::map<unsigned int, CustomOrderedSet<unsigned int> > reg_binding::reg2storage_values [protected]
map between the register and the associated storage value
Definition at line 99 of file reg_binding.hpp.
Referenced by bind(), and get_vars().
reverse_map
std::map<unsigned int, unsigned int> reg_binding::reverse_map [protected]
bind the storage value with the register instance
Definition at line 87 of file reg_binding.hpp.
Referenced by bind().
unique_table
std::map<unsigned int, generic_objRef> reg_binding::unique_table [protected]
map between register index and object
Definition at line 84 of file reg_binding.hpp.
Referenced by bind().
used_regs
unsigned int reg_binding::used_regs [protected]
number of used register
Definition at line 81 of file reg_binding.hpp.
Referenced by get_used_regs().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/reg_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/reg_binding.cpp