Loop Class Reference
#include <loop.hpp>
Public Member Functions
Loop (const BBGraphRef g)
Constructor for empty loop (used for irreducible)
Loop (const BBGraphRef g, vertex header)
Constructor for reducible loop.
unsigned int GetId () const
returns the loop id
bool is_innermost () const
tells if the loop is innermost
bool IsReducible () const
tells if the loop is reducible
vertex GetHeader () const
returns loop header
CustomOrderedSet< vertex > get_entries () const
return the alternative entries of a loop
void add_entry (vertex v)
add an entry of the loop
const LoopRef Parent () const
returns the parent loop
void add_block (vertex block)
adds a block to this loop
size_t num_blocks () const
returns the number of basic blocks belonging to this loop
const CustomUnorderedSet< vertex > & get_blocks () const
returns the blocks
size_t num_exits () const
std::list< vertex >::const_iterator exit_block_iter_begin () const
std::list< vertex >::const_iterator exit_block_iter_end () const
size_t num_landing_pads () const
const CustomUnorderedSet< vertex > GetLandingPadBlocks () const
Return the landing pads of the loops.
vertex primary_landing_pad () const
void SetParent (LoopRef parent)
Sets parent for this loop.
void AddChild (LoopRef child)
Adds a child loop.
const CustomOrderedSet< LoopConstRef > & GetChildren () const
Returns the children of this loop in the loop forest.
void get_recursively_bb (CustomUnorderedSet< vertex > &ret) const
Returns the basic blocks which belong to this loop and to loop nested in this loop.
OpVertexSet GetRecursivelyOps (const OpGraphConstRef op_graph) const
Returns the operation which belongs to this loop or to a nested loop.
const std::map< vertex, CustomUnorderedSet< vertex > > & get_exit_landing_association () const
Returns the map exit_landing_association.
void add_sp_back_edge (vertex vs, vertex vd)
add a spanning tree back edge
bool is_sp_back_edge (vertex vs, vertex vd) const
check if a pair of vertex is a spanning tree back edge for the loop
CustomOrderedSet< std::pair< vertex, vertex > > get_sp_back_edges () const
return the list of spanning tree back edges
Data Fields
unsigned int depth
Nesting depth of this loop.
int loop_type
loop type
long long footprint_size
loop memory footprint
long long instruction_size
loop instruction footprint
vertex body_start
body start basic block (at the moment defined only for SIMPLE_LOOP & WHILE_LOOP)
unsigned int main_iv
the main induction variable of countable loop;
unsigned int initialization_tree_node_id
The index of the tree node containing the value of the initialization of the induction variable.
unsigned int init_gimple_id
The index of the gimple tree node containing the initialization of the induction variable; right operand can be different from initialization_tree_node_id because of assignments chain.
unsigned int inc_id
The node id containing the increment statement.
long long int increment
Increment of induction variable.
tree_nodeRef increment_tn
Increment of induction variable.
long long int lower_bound
Initial value of induction variable.
long long int upper_bound
Final value of induction variable.
tree_nodeRef upper_bound_tn
Final value of induction variable.
bool close_interval
flag for induction variable close interval
Private Member Functions
void ComputeLandingPadExits ()
compute landing pad exits
Private Attributes
const BBGraphRef g
The basic block control flow graph.
bool is_innermost_loop
tells if there aren't loop nested in this
refcount< Loop > parent_loop
Parent loop.
CustomOrderedSet< LoopConstRef > children
Child loops.
CustomUnorderedSet< vertex > blocks
Blocks which belong to this loop.
std::list< vertex > exits
exit blocks for this loop
CustomUnorderedSet< vertex > landing_pads
landing_pads for this loop
vertex primary_landing_pad_block
???
vertex header_block
the header of the loop
CustomOrderedSet< vertex > alternative_entries
in case the loop is irreducible the loop has multiple entries while for reducible loops the entry is just one
unsigned int loop_id
the id of the loop
std::map< vertex, CustomUnorderedSet< vertex > > exit_landing_association
Map storing the association between an exit basic block and the corresponding landing pads.
CustomOrderedSet< std::pair< vertex, vertex > > sp_back_edges
set of vertex pairs describing a spanning tree back edge for the loop
Static Private Attributes
static unsigned int curr_unused_irreducible_id = std::numeric_limits<unsigned int>::max()
used to label irreducible loops
Friends
class Loops
Friend definition of loop.
class add_loop_nop
Definition of friend class add_loop_nop.
Detailed Description
Definition at line 151 of file loop.hpp.
Constructor & Destructor Documentation
Loop() [1/2]
Loop::Loop (const BBGraphRef g) [explicit]
Constructor for empty loop (used for irreducible)
Parameters
g is the basic block control flow grah
Definition at line 63 of file loop.cpp.
Loop() [2/2]
Loop::Loop (const BBGraphRef g, vertex header)
Constructor for reducible loop.
Parameters
g is the basic block control flow graph
header is the header basic block
Definition at line 95 of file loop.cpp.
References add_block(), alternative_entries, BBGraph::CGetBBNodeInfo(), g, and loop_id.
Member Function Documentation
add_block()
void Loop::add_block (vertex block)
adds a block to this loop
Parameters
block is the basic block to be added
Definition at line 272 of file loop.cpp.
References blocks.
Referenced by add_entry(), Loops::DetectReducibleLoop(), Loop(), and Loops::tarjan_scc().
add_entry()
void Loop::add_entry (vertex v) [inline]
add an entry of the loop
Definition at line 292 of file loop.hpp.
References add_block(), AddChild(), exit_block_iter_begin(), exit_block_iter_end(), get_blocks(), get_exit_landing_association(), get_recursively_bb(), GetChildren(), GetLandingPadBlocks(), GetRecursivelyOps(), num_blocks(), num_exits(), num_landing_pads(), Parent(), primary_landing_pad(), and SetParent().
add_sp_back_edge()
void Loop::add_sp_back_edge (vertex vs, vertex vd) [inline]
add a spanning tree back edge
Definition at line 377 of file loop.hpp.
AddChild()
void Loop::AddChild (LoopRef child)
Adds a child loop.
Parameters
child is the child loop
Definition at line 277 of file loop.cpp.
References children.
Referenced by add_entry(), Loops::DetectReducibleLoop(), and Loops::tarjan_scc().
ComputeLandingPadExits()
void Loop::ComputeLandingPadExits () [private]
compute landing pad exits
Definition at line 240 of file loop.cpp.
References exit_landing_association, exits, g, get_recursively_bb(), and landing_pads.
exit_block_iter_begin()
std::list< vertex >::const_iterator Loop::exit_block_iter_begin () const
Definition at line 166 of file loop.cpp.
References exits.
Referenced by add_entry(), and Vectorize::DuplicateIncrement().
exit_block_iter_end()
std::list< vertex >::const_iterator Loop::exit_block_iter_end () const
Definition at line 171 of file loop.cpp.
References exits.
Referenced by add_entry().
get_blocks()
const CustomUnorderedSet< vertex > & Loop::get_blocks () const
returns the blocks
Returns
the blocks
Definition at line 156 of file loop.cpp.
References blocks.
Referenced by add_entry().
get_entries()
CustomOrderedSet<vertex> Loop::get_entries () const [inline]
return the alternative entries of a loop
Definition at line 286 of file loop.hpp.
References alternative_entries.
get_exit_landing_association()
const std::map< vertex, CustomUnorderedSet< vertex > > & Loop::get_exit_landing_association () const
Returns the map exit_landing_association.
Returns
the map exit_landing_association
Definition at line 305 of file loop.cpp.
References exit_landing_association.
Referenced by add_entry().
get_recursively_bb()
void Loop::get_recursively_bb (CustomUnorderedSet< vertex > & ret) const
Returns the basic blocks which belong to this loop and to loop nested in this loop.
Parameters
ret is the returned set of basic block of this loop and of its children
Definition at line 282 of file loop.cpp.
References blocks, and children.
Referenced by add_entry(), ComputeLandingPadExits(), and GetRecursivelyOps().
get_sp_back_edges()
CustomOrderedSet<std::pair<vertex, vertex> > Loop::get_sp_back_edges () const [inline]
return the list of spanning tree back edges
Definition at line 391 of file loop.hpp.
References sp_back_edges.
GetChildren()
const CustomOrderedSet< LoopConstRef > & Loop::GetChildren () const
Returns the children of this loop in the loop forest.
Definition at line 310 of file loop.cpp.
References children.
Referenced by add_entry().
GetHeader()
vertex Loop::GetHeader () const
returns loop header
Returns
returns loop header
Definition at line 136 of file loop.cpp.
References header_block.
Referenced by Vectorize::DuplicateIncrement().
GetId()
unsigned int Loop::GetId () const
returns the loop id
Returns
the loop id
Definition at line 131 of file loop.cpp.
References loop_id.
Referenced by Loops::tarjan_scc().
GetLandingPadBlocks()
const CustomUnorderedSet< vertex > Loop::GetLandingPadBlocks () const
Return the landing pads of the loops.
Parameters
the basic block landing pads of the loop
Definition at line 181 of file loop.cpp.
References landing_pads.
Referenced by add_entry().
GetRecursivelyOps()
OpVertexSet Loop::GetRecursivelyOps (const OpGraphConstRef op_graph) const
Returns the operation which belongs to this loop or to a nested loop.
Parameters
op_graph is the operation graph
Returns
the contained operations
Definition at line 290 of file loop.cpp.
References BBGraph::CGetBBNodeInfo(), g, get_recursively_bb(), and THROW_ASSERT.
Referenced by add_entry().
is_innermost()
bool Loop::is_innermost () const
tells if the loop is innermost
Returns
true if the loop is innermost
Definition at line 141 of file loop.cpp.
References children.
is_sp_back_edge()
bool Loop::is_sp_back_edge (vertex vs, vertex vd) const [inline]
check if a pair of vertex is a spanning tree back edge for the loop
Definition at line 384 of file loop.hpp.
IsReducible()
bool Loop::IsReducible () const
tells if the loop is reducible
Returns
true if the loop is reducible
Definition at line 146 of file loop.cpp.
References header_block, and NULL_VERTEX.
Referenced by Vectorize::DuplicateIncrement().
num_blocks()
size_t Loop::num_blocks () const
returns the number of basic blocks belonging to this loop
Returns
the number of basic blocks
Definition at line 151 of file loop.cpp.
References blocks.
Referenced by add_entry().
num_exits()
size_t Loop::num_exits () const
Definition at line 161 of file loop.cpp.
References exits.
Referenced by add_entry(), and Vectorize::DuplicateIncrement().
num_landing_pads()
size_t Loop::num_landing_pads () const
Definition at line 176 of file loop.cpp.
References landing_pads.
Referenced by add_entry().
Parent()
const LoopRef Loop::Parent () const
returns the parent loop
Returns
the parent loop if this loop is nested, NULL otherwise
Definition at line 230 of file loop.cpp.
References parent_loop.
Referenced by add_entry(), and Loops::DetectReducibleLoop().
primary_landing_pad()
vertex Loop::primary_landing_pad () const
Definition at line 186 of file loop.cpp.
References g, landing_pads, and NULL_VERTEX.
Referenced by add_entry().
SetParent()
void Loop::SetParent (LoopRef parent)
Sets parent for this loop.
Parameters
parent is the parent loop
Definition at line 235 of file loop.cpp.
References refcount< T >::get(), and parent_loop.
Referenced by add_entry(), and Loops::DetectReducibleLoop().
Friends And Related Function Documentation
add_loop_nop
friend class add_loop_nop [friend]
Definition of friend class add_loop_nop.
Definition at line 397 of file loop.hpp.
Loops
friend class Loops [friend]
Friend definition of loop.
Definition at line 155 of file loop.hpp.
Field Documentation
alternative_entries
CustomOrderedSet<vertex> Loop::alternative_entries [private]
in case the loop is irreducible the loop has multiple entries while for reducible loops the entry is just one
Definition at line 188 of file loop.hpp.
Referenced by get_entries(), and Loop().
blocks
CustomUnorderedSet<vertex> Loop::blocks [private]
Blocks which belong to this loop.
Definition at line 173 of file loop.hpp.
Referenced by add_block(), Loops::BuildZeroLoop(), get_blocks(), get_recursively_bb(), and num_blocks().
body_start
vertex Loop::body_start
body start basic block (at the moment defined only for SIMPLE_LOOP & WHILE_LOOP)
Definition at line 216 of file loop.hpp.
children
CustomOrderedSet<LoopConstRef> Loop::children [private]
Child loops.
Definition at line 170 of file loop.hpp.
Referenced by AddChild(), Loops::BuildZeroLoop(), get_recursively_bb(), GetChildren(), and is_innermost().
close_interval
bool Loop::close_interval
flag for induction variable close interval
Definition at line 246 of file loop.hpp.
curr_unused_irreducible_id
unsigned int Loop::curr_unused_irreducible_id = std::numeric_limits<unsigned int>::max() [static], [private]
used to label irreducible loops
Header include.
Definition at line 197 of file loop.hpp.
depth
unsigned int Loop::depth
Nesting depth of this loop.
Definition at line 204 of file loop.hpp.
Referenced by Loops::computeDepth().
exit_landing_association
std::map<vertex, CustomUnorderedSet<vertex> > Loop::exit_landing_association [private]
Map storing the association between an exit basic block and the corresponding landing pads.
Definition at line 194 of file loop.hpp.
Referenced by ComputeLandingPadExits(), and get_exit_landing_association().
exits
std::list<vertex> Loop::exits [private]
exit blocks for this loop
Definition at line 176 of file loop.hpp.
Referenced by ComputeLandingPadExits(), exit_block_iter_begin(), exit_block_iter_end(), and num_exits().
footprint_size
long long Loop::footprint_size
loop memory footprint
Definition at line 210 of file loop.hpp.
g
const BBGraphRef Loop::g [private]
The basic block control flow graph.
Definition at line 161 of file loop.hpp.
Referenced by ComputeLandingPadExits(), GetRecursivelyOps(), Loop(), and primary_landing_pad().
header_block
vertex Loop::header_block [private]
the header of the loop
Definition at line 185 of file loop.hpp.
Referenced by GetHeader(), and IsReducible().
inc_id
unsigned int Loop::inc_id
The node id containing the increment statement.
Definition at line 228 of file loop.hpp.
increment
long long int Loop::increment
Increment of induction variable.
Definition at line 231 of file loop.hpp.
increment_tn
tree_nodeRef Loop::increment_tn
Increment of induction variable.
Definition at line 234 of file loop.hpp.
init_gimple_id
unsigned int Loop::init_gimple_id
The index of the gimple tree node containing the initialization of the induction variable; right operand can be different from initialization_tree_node_id because of assignments chain.
Definition at line 225 of file loop.hpp.
initialization_tree_node_id
unsigned int Loop::initialization_tree_node_id
The index of the tree node containing the value of the initialization of the induction variable.
Definition at line 222 of file loop.hpp.
instruction_size
long long Loop::instruction_size
loop instruction footprint
Definition at line 213 of file loop.hpp.
is_innermost_loop
bool Loop::is_innermost_loop [private]
tells if there aren't loop nested in this
Definition at line 164 of file loop.hpp.
Referenced by Loops::BuildZeroLoop().
landing_pads
CustomUnorderedSet<vertex> Loop::landing_pads [private]
landing_pads for this loop
Definition at line 179 of file loop.hpp.
Referenced by ComputeLandingPadExits(), GetLandingPadBlocks(), num_landing_pads(), and primary_landing_pad().
loop_id
unsigned int Loop::loop_id [private]
the id of the loop
Definition at line 191 of file loop.hpp.
Referenced by GetId(), and Loop().
loop_type
int Loop::loop_type
loop type
Definition at line 207 of file loop.hpp.
lower_bound
long long int Loop::lower_bound
Initial value of induction variable.
Definition at line 237 of file loop.hpp.
main_iv
unsigned int Loop::main_iv
the main induction variable of countable loop;
Definition at line 219 of file loop.hpp.
parent_loop
refcount<Loop> Loop::parent_loop [private]
Parent loop.
Definition at line 167 of file loop.hpp.
Referenced by Parent(), and SetParent().
primary_landing_pad_block
vertex Loop::primary_landing_pad_block [private]
???
Definition at line 182 of file loop.hpp.
sp_back_edges
CustomOrderedSet<std::pair<vertex, vertex> > Loop::sp_back_edges [private]
set of vertex pairs describing a spanning tree back edge for the loop
Definition at line 200 of file loop.hpp.
Referenced by get_sp_back_edges().
upper_bound
long long int Loop::upper_bound
Final value of induction variable.
Definition at line 240 of file loop.hpp.
upper_bound_tn
tree_nodeRef Loop::upper_bound_tn
Final value of induction variable.
Definition at line 243 of file loop.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/algorithms/loops_detection/loop.hpp
/home/osboxes/bambu/PandA-bambu/src/algorithms/loops_detection/loop.cpp