string_cst_fix Class Reference
Pre-analysis step.
#include <string_cst_fix.hpp>
Public Member Functions
string_cst_fix (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~string_cst_fix () override
Destructor.
DesignFlowStep_Status Exec () override
Fixes the var_decl duplication.
Protected Member Functions
void recursive_analysis (tree_nodeRef &tn, const std::string &srcp)
Recursive tree node analysis.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
CustomUnorderedSet< unsigned int > already_visited_ae
Already visited address expression (used to avoid infinite recursion)
CustomUnorderedMap< unsigned int, tree_nodeRef > string_cst_map
relation between constant string and read-only variable initialized with the string_cst.
Additional Inherited Members
Detailed Description
Pre-analysis step.
It transforms the raw intermediate representation by removing direct references to string_cst.
Definition at line 68 of file string_cst_fix.hpp.
Constructor & Destructor Documentation
string_cst_fix()
string_cst_fix::string_cst_fix (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
Behavior include Graph include Parameter include STD include STL include Tree include Utility include
Definition at line 78 of file string_cst_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~string_cst_fix().
 string_cst_fix()
string_cst_fix::~string_cst_fix () [override], [default]
Destructor.
Referenced by string_cst_fix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > string_cst_fix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 85 of file string_cst_fix.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, FUNCTION_ANALYSIS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status string_cst_fix::Exec () [override], [virtual]
Fixes the var_decl duplication.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 111 of file string_cst_fix.cpp.
References FrontendFlowStep::AppM, test_panda::arg, GET_NODE, tree_manager::GetTreeNode(), phi, recursive_analysis(), sl, STR, and SUCCESS.
recursive_analysis()
void string_cst_fix::recursive_analysis (tree_nodeRef & tn, const std::string & srcp) [protected]
Recursive tree node analysis.
Removing statements create more problems than what it may solve.
So the solution for bambu is to not synthesize them.
makes the var_decl visible
Definition at line 146 of file string_cst_fix.cpp.
References already_visited_ae, FrontendFlowStep::AppM, test_panda::arg, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, NODE_NOT_YET_SUPPORTED_EC, DesignFlowStep::parameters, STR, string_cst_map, THROW_ASSERT, THROW_ERROR_CODE, THROW_UNREACHABLE, and tree_node::ToString().
Referenced by Exec().
Field Documentation
already_visited_ae
CustomUnorderedSet<unsigned int> string_cst_fix::already_visited_ae [protected]
Already visited address expression (used to avoid infinite recursion)
Definition at line 72 of file string_cst_fix.hpp.
Referenced by recursive_analysis().
string_cst_map
CustomUnorderedMap<unsigned int, tree_nodeRef> string_cst_fix::string_cst_map [protected]
relation between constant string and read-only variable initialized with the string_cst.
Definition at line 75 of file string_cst_fix.hpp.
Referenced by recursive_analysis().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/string_cst_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/string_cst_fix.cpp