LoadFileTechnology Class Reference
Step which loads technology library from file.
#include <load_file_technology.hpp>
Public Member Functions
LoadFileTechnology (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~LoadFileTechnology () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Step which loads technology library from file.
Definition at line 56 of file load_file_technology.hpp.
Constructor & Destructor Documentation
LoadFileTechnology()
LoadFileTechnology::LoadFileTechnology (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
TM is the technology manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include technology include utility includes
Definition at line 55 of file load_file_technology.cpp.
References DesignFlowStep::debug_level, GET_CLASS, LOAD_FILE_TECHNOLOGY, DesignFlowStep::parameters, and ~LoadFileTechnology().
 LoadFileTechnology()
LoadFileTechnology::~LoadFileTechnology () [override], [default]
Destructor.
Referenced by LoadFileTechnology().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > LoadFileTechnology::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 74 of file load_file_technology.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_DEFAULT_TECHNOLOGY, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status LoadFileTechnology::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 63 of file load_file_technology.cpp.
References INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, read_technology_File(), SUCCESS, TechnologyFlowStep::target, and TechnologyFlowStep::TM.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_file_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_file_technology.cpp