Loops Class Reference
#include <loops.hpp>
Public Member Functions
Loops (const FunctionBehaviorRef FB, const ParameterConstRef parameter)
The constructor builds the loop forest for the given method.
size_t NumLoops () const
Returns the number of loops.
const std::list< LoopConstRef > & GetList () const
Returns the list of loops (const)
const std::list< LoopRef > & GetModifiableList () const
Return the list of loops.
const LoopConstRef CGetLoop (unsigned int id) const
Returns a loop given the id.
const LoopRef GetLoop (unsigned int id)
Returns a loop given the id.
void WriteDot (const std::string &file_name) const
Write dot files representing the loop forest.
Private Types
typedef std::pair< vertex, vertex > vertex_pair
Private Member Functions
bool is_edge_in_list (CustomUnorderedSet< vertex_pair > &l, vertex source, vertex target)
Loops ()=delete
void DetectLoops ()
Computes the loops of the control flow graph.
void DetectReducibleLoop (const BBGraphRef djg, CustomOrderedSet< vertex > &visited, LoopRef loop, vertex node, vertex header)
Reducible loop construction.
void DetectIrreducibleLoop (const BBGraphRef djg, unsigned int min_level, unsigned int max_level, std::vector< std::list< vertex >> &level_vertices_rel)
void tarjan_scc (const BBGraphRef djg, vertex v, CustomUnorderedMap< vertex, unsigned int > &dfs_order, CustomUnorderedMap< vertex, unsigned int > &lowlink, std::list< vertex > &s, CustomOrderedSet< vertex > &u, unsigned int &max_dfs)
bool stack_contains (std::list< vertex > stack, vertex v)
void BuildZeroLoop ()
Creates Loop zero data structure.
void computeDepth (const LoopConstRef loop)
Sets depth for each loop in the forest starting from loop.
Private Attributes
const FunctionBehaviorRef FB
The function behavior.
const ParameterConstRef Param
class containing all the parameters
int debug_level
Debug level.
CustomUnorderedMap< vertex, LoopRef > block_to_loop
Maps between basic block and loop to which it belongs.
std::list< LoopRef > modifiable_loops_list
List of found loops.
std::list< LoopConstRef > const_loops_list
Detailed Description
Definition at line 89 of file loops.hpp.
Member Typedef Documentation
vertex_pair
typedef std::pair<vertex, vertex> Loops::vertex_pair [private]
Definition at line 108 of file loops.hpp.
Constructor & Destructor Documentation
Loops() [1/2]
Loops::Loops () [private], [delete]
Loops() [2/2]
Loops::Loops (const FunctionBehaviorRef FB, const ParameterConstRef parameter)
The constructor builds the loop forest for the given method.
Parameters
FB is the function behavior of the control flow graph to be analyzed
parameter is the set of input parameters
Detect loops
Build Zero Loop
compute depth
compute landing pads
Definition at line 176 of file loops.cpp.
References BuildZeroLoop(), computeDepth(), DetectLoops(), GetLoop(), and modifiable_loops_list.
Member Function Documentation
BuildZeroLoop()
void Loops::BuildZeroLoop () [private]
Creates Loop zero data structure.
Putting all the basic blocks in blocks
Definition at line 671 of file loops.cpp.
References FunctionBehavior::BB, Loop::blocks, BBGraph::CGetBBGraphInfo(), Loop::children, const_loops_list, FB, Loop::is_innermost_loop, and modifiable_loops_list.
Referenced by Loops().
CGetLoop()
const LoopConstRef Loops::CGetLoop (unsigned int id) const
Returns a loop given the id.
Parameters
id is the id of the loop
Definition at line 575 of file loops.cpp.
References const_loops_list, and THROW_UNREACHABLE.
computeDepth()
void Loops::computeDepth (const LoopConstRef loop) [private]
Sets depth for each loop in the forest starting from loop.
Parameters
loop is the root of the loop forest
Definition at line 659 of file loops.cpp.
References test_panda::children, and Loop::depth.
Referenced by Loops().
DetectIrreducibleLoop()
void Loops::DetectIrreducibleLoop (const BBGraphRef djg, unsigned int min_level, unsigned int max_level, std::vector< std::list< vertex >> & level_vertices_rel) [private]
Populate u with all the non-visited node whose level is >= min_level
Definition at line 426 of file loops.cpp.
References FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB, INDENT_DBG_MEX, test_panda::level, PRINT_DBG_MEX, STR, tarjan_scc(), and THROW_ASSERT.
Referenced by DetectLoops().
DetectLoops()
void Loops::DetectLoops () [private]
Computes the loops of the control flow graph.
Retrieve dominator tree and dominance relation
Create the DJ graph. This is done in two steps: 1) build the dominator tree 2) add the `J` edges
Add J edges (and detect CJ ones) D edges are already there since we use boost filtered graphs
Check for CJ and BJ edges
This is a BJ edge, and we mark it as such
This is a CJ edge, and we mark it as such
Build the spanning tree and detect the sp-back edges
spanning tree ancestor data structure
initialization
spanning tree construction and vertex labeling
compute the level_vertices_rel
Detect the sp-back edges
This is a sp-back edge
Detect this Loop (n is the header)
Identify SCCs for the subgraphs induced by nodes at level greater or equal than lev
Definition at line 203 of file loops.cpp.
References block_to_loop, BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), check_ancestor(), const_loops_list, debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DetectIrreducibleLoop(), DetectReducibleLoop(), FunctionBehavior::DJ, FB, FunctionBehavior::FBB, BehavioralHelper::get_function_name(), dominance< GraphObj >::get_immediate_dominator(), dominance< GraphObj >::getAllDominated(), index, is_edge_in_list(), J_SELECTOR, modifiable_loops_list, Param, PRINT_DBG_MEX, THROW_ASSERT, and BBGraph::WriteDot().
Referenced by Loops().
DetectReducibleLoop()
void Loops::DetectReducibleLoop (const BBGraphRef djg, CustomOrderedSet< vertex > & visited, LoopRef loop, vertex node, vertex header) [private]
Reducible loop construction.
Parameters
djg is the DJ graph
visited is the set of vertex visited
loop is the current loop
node is current vertex
header is the entry of the reducible loop
Definition at line 388 of file loops.cpp.
References Loop::add_block(), Loop::AddChild(), block_to_loop, Loop::Parent(), and Loop::SetParent().
Referenced by DetectLoops().
GetList()
const std::list< LoopConstRef > & Loops::GetList () const
Returns the list of loops (const)
Parameters
return the const list of loops
Definition at line 565 of file loops.cpp.
References const_loops_list.
GetLoop()
const LoopRef Loops::GetLoop (unsigned int id)
Returns a loop given the id.
Parameters
id is the id of the loop
Definition at line 586 of file loops.cpp.
References modifiable_loops_list, and THROW_UNREACHABLE.
Referenced by Loops().
GetModifiableList()
const std::list< LoopRef > & Loops::GetModifiableList () const
Return the list of loops.
Parameters
return the const list of loops
Definition at line 570 of file loops.cpp.
References modifiable_loops_list.
is_edge_in_list()
bool Loops::is_edge_in_list (CustomUnorderedSet< vertex_pair > & l, vertex source, vertex target) [private]
Definition at line 192 of file loops.cpp.
Referenced by DetectLoops().
NumLoops()
size_t Loops::NumLoops () const
Returns the number of loops.
Definition at line 597 of file loops.cpp.
References const_loops_list.
stack_contains()
bool Loops::stack_contains (std::list< vertex > stack, vertex v) [private]
Definition at line 458 of file loops.cpp.
Referenced by tarjan_scc().
tarjan_scc()
void Loops::tarjan_scc (const BBGraphRef djg, vertex v, CustomUnorderedMap< vertex, unsigned int > & dfs_order, CustomUnorderedMap< vertex, unsigned int > & lowlink, std::list< vertex > & s, CustomOrderedSet< vertex > & u, unsigned int & max_dfs) [private]
Definition at line 472 of file loops.cpp.
References Loop::add_block(), Loop::AddChild(), block_to_loop, BBGraph::CGetBBNodeInfo(), const_loops_list, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, Loop::GetId(), INDENT_DBG_MEX, modifiable_loops_list, stack_contains(), and STR.
Referenced by DetectIrreducibleLoop().
WriteDot()
void Loops::WriteDot (const std::string & file_name) const
Write dot files representing the loop forest.
Parameters
file_name is the file name to be produced
profiling_information is the profiling information used to print data about loop iterations
Definition at line 602 of file loops.cpp.
References FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), const_loops_list, COUNTABLE_LOOP, DO_WHILE_LOOP, DOALL_LOOP, FB, FOR_LOOP, Param, PIPELINABLE_LOOP, SINGLE_EXIT_LOOP, STR, UNKNOWN_LOOP, and WHILE_LOOP.
Field Documentation
block_to_loop
CustomUnorderedMap<vertex, LoopRef> Loops::block_to_loop [private]
Maps between basic block and loop to which it belongs.
Definition at line 102 of file loops.hpp.
Referenced by DetectLoops(), DetectReducibleLoop(), and tarjan_scc().
const_loops_list
std::list<LoopConstRef> Loops::const_loops_list [private]
Definition at line 106 of file loops.hpp.
Referenced by BuildZeroLoop(), CGetLoop(), DetectLoops(), GetList(), NumLoops(), tarjan_scc(), and WriteDot().
debug_level
int Loops::debug_level [private]
Debug level.
Definition at line 99 of file loops.hpp.
Referenced by DetectIrreducibleLoop(), DetectLoops(), and tarjan_scc().
FB
const FunctionBehaviorRef Loops::FB [private]
The function behavior.
Definition at line 93 of file loops.hpp.
Referenced by BuildZeroLoop(), DetectIrreducibleLoop(), DetectLoops(), and WriteDot().
modifiable_loops_list
std::list<LoopRef> Loops::modifiable_loops_list [private]
List of found loops.
Definition at line 105 of file loops.hpp.
Referenced by BuildZeroLoop(), DetectLoops(), GetLoop(), GetModifiableList(), Loops(), and tarjan_scc().
Param
const ParameterConstRef Loops::Param [private]
class containing all the parameters
Definition at line 96 of file loops.hpp.
Referenced by DetectLoops(), and WriteDot().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/algorithms/loops_detection/loops.hpp
/home/osboxes/bambu/PandA-bambu/src/algorithms/loops_detection/loops.cpp