graphs_collection Struct Reference
bulk graph.
#include <graph.hpp>
Public Member Functions
graphs_collection (GraphInfoRef info, const ParameterConstRef _parameters)
Constructor of graph.
virtual ~graphs_collection ()
Destructor.
boost::graph_traits< graphs_collection >::edge_descriptor AddSelector (const boost::graph_traits< graphs_collection >::edge_descriptor edge, const int selector)
Add a selector to an existing edge.
boost::graph_traits< graphs_collection >::edge_descriptor AddSelector (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target, const int selector)
Add a selector to an existing edge.
void RemoveSelector (boost::graph_traits< graphs_collection >::edge_descriptor edge)
Remove all the selectors of an edge from this graph.
void RemoveSelector (boost::graph_traits< graphs_collection >::edge_descriptor edge, const int selector)
Remove an edge from this graph.
void RemoveSelector (boost::graph_traits< graphs_collection >::vertex_descriptor source, boost::graph_traits< graphs_collection >::vertex_descriptor target, const int selector)
Remove an edge from this graph.
int GetSelector (const edge_descriptor e) const
Return the selectors associated with an edge.
virtual boost::graph_traits< boost_graphs_collection >::vertex_descriptor AddVertex (const NodeInfoRef info)
Add a vertex to this graph with a property.
boost::graph_traits< graphs_collection >::edge_descriptor AddEdge (boost::graph_traits< graphs_collection >::vertex_descriptor, boost::graph_traits< graphs_collection >::vertex_descriptor, const int)
Add an edge to this graph FIXME: this should be pure virtual.
boost::graph_traits< graphs_collection >::edge_descriptor InternalAddEdge (boost::graph_traits< graphs_collection >::vertex_descriptor source, boost::graph_traits< graphs_collection >::vertex_descriptor target, const int selector, const EdgeInfoRef info)
Add an edge to this graph FIXME: this should be protected.
virtual void RemoveVertex (boost::graph_traits< boost_graphs_collection >::vertex_descriptor v)
Remove a vertex from this graph.
bool ExistsEdge (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const
Check if an edge exists.
void CompressEdges ()
Data Fields
const ParameterConstRef parameters
Set of input parameters.
Detailed Description
bulk graph.
All the edge of a graph are store in this object
Definition at line 261 of file graph.hpp.
Constructor & Destructor Documentation
graphs_collection()
graphs_collection::graphs_collection (GraphInfoRef info, const ParameterConstRef _parameters) [inline]
Constructor of graph.
Parameters
info is the property associated with the graph
Definition at line 271 of file graph.hpp.
References boost_CGetOpGraph_property.
 graphs_collection()
virtual graphs_collection::~graphs_collection () [inline], [virtual]
Destructor.
Definition at line 277 of file graph.hpp.
Member Function Documentation
AddEdge()
boost::graph_traits<graphs_collection>::edge_descriptor graphs_collection::AddEdge (boost::graph_traits< graphs_collection >::vertex_descriptor , boost::graph_traits< graphs_collection >::vertex_descriptor , const int) [inline]
Add an edge to this graph FIXME: this should be pure virtual.
Parameters
source is the source of the edge to be added
target is the target of the edge to be added
selector is the selector to be set on the edge
info is the info to be associated with the edge
Definition at line 363 of file graph.hpp.
References THROW_UNREACHABLE.
AddSelector() [1/2]
boost::graph_traits<graphs_collection>::edge_descriptor graphs_collection::AddSelector (const boost::graph_traits< graphs_collection >::edge_descriptor edge, const int selector) [inline]
Add a selector to an existing edge.
Parameters
edge is the edge to be considered
selector is the selector to be added
Definition at line 286 of file graph.hpp.
Referenced by weak_dominance::add_edge().
AddSelector() [2/2]
boost::graph_traits<graphs_collection>::edge_descriptor graphs_collection::AddSelector (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target, const int selector) [inline]
Add a selector to an existing edge.
Parameters
source is the source of the edge
target is the target of the edge
Definition at line 297 of file graph.hpp.
References THROW_ASSERT.
AddVertex()
boost::graph_traits< boost_graphs_collection >::vertex_descriptor graphs_collection::AddVertex (const NodeInfoRef info) [virtual]
Add a vertex to this graph with a property.
Parameters
info is the property to be associated with the new vertex
Returns
the added vertex
Reimplemented in OpGraphsCollection.
Definition at line 56 of file graph.cpp.
References index, and test_panda::type.
Referenced by DesignFlowGraphsCollection::AddDesignFlowStep(), OpGraphsCollection::AddVertex(), structural_manager::build_graph(), and weak_dominance::calculate_weak_dominance_info().
CompressEdges()
void graphs_collection::CompressEdges () [inline]
Definition at line 411 of file graph.hpp.
ExistsEdge()
bool graphs_collection::ExistsEdge (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const [inline]
Check if an edge exists.
Parameters
source is the source vertex
target is the target vertex
Returns
true if source-target exists
Definition at line 403 of file graph.hpp.
Referenced by weak_dominance::add_edge().
GetSelector()
int graphs_collection::GetSelector (const edge_descriptor e) const [inline]
Return the selectors associated with an edge.
Parameters
e is the edge
Returns
the associated selector
Definition at line 343 of file graph.hpp.
References RawGraph::AddVertex().
Referenced by graph::GetSelector().
InternalAddEdge()
boost::graph_traits<graphs_collection>::edge_descriptor graphs_collection::InternalAddEdge (boost::graph_traits< graphs_collection >::vertex_descriptor source, boost::graph_traits< graphs_collection >::vertex_descriptor target, const int selector, const EdgeInfoRef info) [inline]
Add an edge to this graph FIXME: this should be protected.
Parameters
souce is the source of the edge to be added
target is the target of the edge to be added
selector is the selector to be set on the edge
info is the info to be associated with the edge
Definition at line 377 of file graph.hpp.
References RawGraph::RemoveVertex(), and THROW_ASSERT.
Referenced by weak_dominance::add_edge().
RemoveSelector() [1/3]
void graphs_collection::RemoveSelector (boost::graph_traits< graphs_collection >::edge_descriptor edge) [inline]
Remove all the selectors of an edge from this graph.
Parameters
edge is the edge to be considered
Definition at line 311 of file graph.hpp.
RemoveSelector() [2/3]
void graphs_collection::RemoveSelector (boost::graph_traits< graphs_collection >::edge_descriptor edge, const int selector) [inline]
Remove an edge from this graph.
Parameters
edge is the edge to be considered
selector is the selector to remove
Definition at line 321 of file graph.hpp.
RemoveSelector() [3/3]
void graphs_collection::RemoveSelector (boost::graph_traits< graphs_collection >::vertex_descriptor source, boost::graph_traits< graphs_collection >::vertex_descriptor target, const int selector) [inline]
Remove an edge from this graph.
Definition at line 329 of file graph.hpp.
References THROW_ASSERT.
RemoveVertex()
void graphs_collection::RemoveVertex (boost::graph_traits< boost_graphs_collection >::vertex_descriptor v) [virtual]
Remove a vertex from this graph.
Header include.
Parameters
v is the vertex to be removed
Reimplemented in OpGraphsCollection.
Definition at line 44 of file graph.cpp.
References index, and test_panda::type.
Referenced by OpGraphsCollection::RemoveVertex().
Field Documentation
parameters
const ParameterConstRef graphs_collection::parameters
Set of input parameters.
Definition at line 265 of file graph.hpp.
Referenced by OpGraph::CGetOutEdges(), CallGraph::WriteDot(), DesignFlowGraph::WriteDot(), CdfcGraph::WriteDot(), BBGraph::WriteDot(), StateTransitionGraph::WriteDot(), and OpGraph::WriteDot().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/graph/graph.hpp
/home/osboxes/bambu/PandA-bambu/src/graph/graph.cpp