Scheduling Class Reference
Generic class managing scheduling algorithms.
#include <scheduling.hpp>
Public Member Functions
Scheduling (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization=HLSFlowStepSpecializationConstRef())
Constructor.
~Scheduling () override
Destructor.
const CustomUnorderedMap< vertex, bool > & get_spec () const
It returns speculation property map.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
unsigned int compute_b_tag (const EdgeDescriptor &e, const OpGraphConstRef cdg, CustomOrderedSet< unsigned int >::const_iterator &switch_it, CustomOrderedSet< unsigned int >::const_iterator &switch_it_end) const
compute the branch tag given the edge and the control data flow graph.
unsigned int compute_b_tag_size (const OpGraphConstRef cdg, vertex controlling_vertex) const
Return the number of branches associated with the controlling vertex.
unsigned int b_tag_normalize (vertex controlling_vertex, unsigned int b_tag_not_normalized) const
return an unsigned int from 0 to compute_b_tag_size(controlling_vertex)-1 given a branch tag not normalized.
void init_switch_maps (vertex controlling_vertex, const OpGraphConstRef cdg)
initialize the maps associated with the switch vertices.
ControlStep anticipate_operations (const OpGraphConstRef dependence_graph)
Move up zero time operations in the previous step when possible.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Protected Attributes
CustomUnorderedMap< vertex, bool > spec
Map for speculation property of each operation vertex.
const bool speculation
flag to check speculation
Private Attributes
 switch statements data structures and functions.
CustomUnorderedMap< vertex, unsigned int > switch_map_size
store for each switch the number of outgoing branches.
CustomUnorderedMap< vertex, CustomUnorderedMapUnstable< unsigned int, unsigned int > > switch_normalizing_map
for each controlling vertex, it defines a relation between switch tags and branch tags
Additional Inherited Members
Detailed Description
Generic class managing scheduling algorithms.
Definition at line 64 of file scheduling.hpp.
Constructor & Destructor Documentation
Scheduling()
Scheduling::Scheduling (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type, const HLSFlowStepSpecializationConstRef _hls_flow_step_specialization = HLSFlowStepSpecializationConstRef())
Constructor.
implemented algorithms
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the type of scheduling
HLS/module_allocation
Definition at line 79 of file scheduling.cpp.
References ~Scheduling().
 Scheduling()
Scheduling::~Scheduling () [override], [default]
Destructor.
Referenced by Scheduling().
Member Function Documentation
anticipate_operations()
ControlStep Scheduling::anticipate_operations (const OpGraphConstRef dependence_graph) [protected]
Move up zero time operations in the previous step when possible.
Parameters
HLS is the structure storing all the High level synthesis information
dependence_graph is the graph to be scheduled
Returns
the new last step in which an operation is scheduled
The clock cycle
Last control step
Checking vertex in topological order
Checking if operations is time zero
Operation can not be anticipated
Operation can be anticipated
Definition at line 208 of file scheduling.cpp.
References hls::allocation_information, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, AllocationInformation::execution_time, fu_binding::get_assign(), Schedule::get_cstep(), AllocationInformation::get_execution_time(), GET_NAME, GET_TYPE, HLSFunctionStep::HLS, hls::HLS_C, AllocationInformation::op_et_to_cycles(), PRINT_DBG_MEX, hls::Rfu, hls::Rsch, Schedule::set_execution(), TYPE_FOR, TYPE_IF, TYPE_SWITCH, and TYPE_WHILE.
b_tag_normalize()
unsigned int Scheduling::b_tag_normalize (vertex controlling_vertex, unsigned int b_tag_not_normalized) const [protected]
return an unsigned int from 0 to compute_b_tag_size(controlling_vertex)-1 given a branch tag not normalized.
Parameters
controlling_vertex is the controlling vertex (used only for switch vertex).
b_tag_not_normalized is the non normalized tag.
Definition at line 182 of file scheduling.cpp.
References switch_normalizing_map, and THROW_ASSERT.
compute_b_tag()
unsigned int Scheduling::compute_b_tag (const EdgeDescriptor & e, const OpGraphConstRef cdg, CustomOrderedSet< unsigned int >::const_iterator & switch_it, CustomOrderedSet< unsigned int >::const_iterator & switch_it_end) const [protected]
compute the branch tag given the edge and the control data flow graph.
Parameters
e is the edge.
cdg is the controlling dependency graph.
switch_set is filled with the switch tags in case the source of e is a switch vertex.
Definition at line 158 of file scheduling.cpp.
References CDG_SELECTOR, CDG_TRUE_CHECK, EDGE_GET_NODEID, refcount< T >::get(), GET_TYPE, THROW_ERROR, TYPE_ENTRY, TYPE_IF, and TYPE_SWITCH.
compute_b_tag_size()
unsigned int Scheduling::compute_b_tag_size (const OpGraphConstRef cdg, vertex controlling_vertex) const [protected]
Return the number of branches associated with the controlling vertex.
Parameters
cdg is the control dependency graph.
controlling_vertex is the controlling vertex.
Definition at line 142 of file scheduling.cpp.
References refcount< T >::get(), GET_TYPE, switch_map_size, THROW_ASSERT, THROW_ERROR, TYPE_ENTRY, TYPE_IF, and TYPE_SWITCH.
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > Scheduling::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Reimplemented in SDCScheduling.
Definition at line 109 of file scheduling.cpp.
References ALLOCATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Referenced by SDCScheduling::ComputeHLSRelationships(), and parametric_list_based::ComputeHLSRelationships().
get_spec()
const CustomUnorderedMap<vertex, bool>& Scheduling::get_spec () const [inline]
It returns speculation property map.
Returns
the map associated
Definition at line 148 of file scheduling.hpp.
References Initialize(), and spec.
Referenced by parametric_list_based::InternalExec().
init_switch_maps()
void Scheduling::init_switch_maps (vertex controlling_vertex, const OpGraphConstRef cdg) [protected]
initialize the maps associated with the switch vertices.
Parameters
controlling_vertex is a switch vertex.
cdg is the control dependency graph.
Definition at line 191 of file scheduling.cpp.
References CDG_SELECTOR, EDGE_GET_NODEID, switch_map_size, and switch_normalizing_map.
Initialize()
void Scheduling::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from HLSFunctionStep.
Reimplemented in SDCScheduling.
Definition at line 87 of file scheduling.cpp.
References FunctionBehavior::CGetOpGraph(), fu_binding::create_fu_binding(), FunctionBehavior::FLSAODG, HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), Schedule::Initialize(), DesignFlowStep::parameters, hls::Rfu, and hls::Rsch.
Referenced by get_spec(), SDCScheduling::Initialize(), and parametric_list_based::Initialize().
Field Documentation
spec
CustomUnorderedMap<vertex, bool> Scheduling::spec [protected]
Map for speculation property of each operation vertex.
If true, it means that vertex is speculative executed, false otherwise
Definition at line 81 of file scheduling.hpp.
Referenced by get_spec().
speculation
const bool Scheduling::speculation [protected]
flag to check speculation
Definition at line 84 of file scheduling.hpp.
Referenced by parametric_list_based::exec(), and SDCScheduling::InternalExec().
switch_map_size
CustomUnorderedMap<vertex, unsigned int> Scheduling::switch_map_size [private]
store for each switch the number of outgoing branches.
Definition at line 72 of file scheduling.hpp.
Referenced by compute_b_tag_size(), and init_switch_maps().
switch_normalizing_map
CustomUnorderedMap<vertex, CustomUnorderedMapUnstable<unsigned int, unsigned int> > Scheduling::switch_normalizing_map [private]
for each controlling vertex, it defines a relation between switch tags and branch tags
Definition at line 75 of file scheduling.hpp.
Referenced by b_tag_normalize(), and init_switch_maps().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/scheduling.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/scheduling.cpp