/home/osboxes/bambu/PandA-bambu/src/HLS/hls_constraints.cpp File Reference
Data structure implementation for HLS constraints.
#include `hls_constraints.hpp`
#include `exceptions.hpp`
#include `technology_manager.hpp`
#include `utility.hpp`
#include `custom_map.hpp`
#include `polixml.hpp`
#include `xml_dom_parser.hpp`
#include `xml_helper.hpp`
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
#include `fileIO.hpp`
#include <boost/filesystem.hpp>
#include <iosfwd>
#include <string>
#include <utility>
#include <vector>
#include `string_manipulation.hpp`
#include `constraints_STD.data`
#include `constraints_STD_ALUs.data`
Functions
void DECODE_FU_LIB (std::string &fu_name, std::string &fu_library, const std::string &combined)
function used to extract the functional unit name and its library from a string.
Detailed Description
Data structure implementation for HLS constraints.
This file contains the implementation of all the methods used to constrain the synthesis
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Christian Pilato pilato@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
DECODE_FU_LIB()
void DECODE_FU_LIB (std::string & fu_name, std::string & fu_library, const std::string & combined)
function used to extract the functional unit name and its library from a string.
Definition at line 74 of file hls_constraints.cpp.
References SplitString().
Referenced by HLS_constraints::get_number_fu(), and HLS_constraints::xwrite().