xml_att_decl_node Struct Reference
#include <xml_att_decl_node.hpp>
Public Member Functions
xml_att_decl_node (const std::string &_name)
constructor
void print (std::ostream &os, bool, simple_indent *) const override
Print the class.
Additional Inherited Members
Detailed Description
Definition at line 53 of file xml_att_decl_node.hpp.
Constructor & Destructor Documentation
xml_att_decl_node()
xml_att_decl_node::xml_att_decl_node (const std::string & _name) [inline], [explicit]
constructor
Definition at line 56 of file xml_att_decl_node.hpp.
Member Function Documentation
print()
void xml_att_decl_node::print (std::ostream & os, bool , simple_indent *) const [inline], [override], [virtual]
Print the class.
Parameters
os is the stream.
formatted when true the xml is formatted in human readable way.
pp is the pretty print helper.
Implements xml_node.
Definition at line 66 of file xml_att_decl_node.hpp.
References xml_node::get_name(), attribute_sequence::has_attributes(), and attribute_sequence::print_attributes().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_att_decl_node.hpp