DesignFlowFactory Class Reference
#include <design_flow_factory.hpp>
Public Member Functions
DesignFlowFactory (const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~DesignFlowFactory () override
Destructor.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
DesignFlowStepRef CreateFlowStep (const std::string &signature) const override
Return a step given the signature.
const DesignFlowStepRef CreateDesignFlow (const DesignFlow_Type design_flow_type) const
Create a design flow.
Additional Inherited Members
Detailed Description
Definition at line 49 of file design_flow_factory.hpp.
Constructor & Destructor Documentation
DesignFlowFactory()
DesignFlowFactory::DesignFlowFactory (const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 46 of file design_flow_factory.cpp.
References ~DesignFlowFactory().
 DesignFlowFactory()
DesignFlowFactory::~DesignFlowFactory () [override], [default]
Destructor.
Referenced by DesignFlowFactory().
Member Function Documentation
CreateDesignFlow()
const DesignFlowStepRef DesignFlowFactory::CreateDesignFlow (const DesignFlow_Type design_flow_type) const
Create a design flow.
Parameters
design_flow_type is the type of design flow to be created
Returns
the step corresponding to the design flow
Definition at line 64 of file design_flow_factory.cpp.
References DesignFlowStepFactory::design_flow_manager, Wrefcount< T >::lock(), NON_DETERMINISTIC_FLOWS, DesignFlowStepFactory::parameters, and THROW_UNREACHABLE.
Referenced by CreateFlowStep().
CreateFlowStep()
DesignFlowStepRef DesignFlowFactory::CreateFlowStep (const std::string & signature) const [override], [virtual]
Return a step given the signature.
Parameters
signature is the signature of the step to be created
Returns
the created step
Reimplemented from DesignFlowStepFactory.
Definition at line 57 of file design_flow_factory.cpp.
References CreateDesignFlow(), GetPrefix(), DesignFlow::KindTextToEnum(), and THROW_ASSERT.
GetPrefix()
const std::string DesignFlowFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 52 of file design_flow_factory.cpp.
Referenced by CreateFlowStep().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow_factory.cpp