BehavioralHelper Class Reference
#include <behavioral_helper.hpp>
Public Member Functions
BehavioralHelper (const application_managerRef AppM, unsigned int index, bool body, const ParameterConstRef parameters)
Constructor.
virtual ~BehavioralHelper ()
Destructor.
virtual std::tuple< std::string, unsigned int, unsigned int > get_definition (unsigned int index, bool &is_system) const
Returns where the type index is defined.
std::string print_vertex (const OpGraphConstRef g, const vertex v, const var_pp_functorConstRef vppf, const bool dot=false) const
Print the operations corrisponding to the vertex.
virtual std::string print_init (unsigned int index, const var_pp_functorConstRef vppf) const
Print the initialization part.
virtual std::string print_attributes (unsigned int index, const var_pp_functorConstRef vppf, bool first=true) const
Print the attributes associated to a variable.
std::string PrintVariable (unsigned int index) const
Print the name of the variable associated to the index.
void InvaildateVariableName (const unsigned int index)
Invalidate cached variable name.
virtual std::string print_constant (unsigned int var, const var_pp_functorConstRef vppf=var_pp_functorConstRef()) const
Print the constant associated with index.
virtual std::string print_type (unsigned int type, bool global=false, bool print_qualifiers=false, bool print_storage=false, unsigned int var=0, const var_pp_functorConstRef vppf=var_pp_functorConstRef(), const std::string &prefix=``, const std::string &tail=``) const
Print a type and its variable in case var is not zero.
virtual std::string print_type_declaration (unsigned int type) const
Print the declaration of a non built-in type.
virtual unsigned int get_size (unsigned int index) const
Return the size in bit of a C object.
std::string get_function_name () const
Return the name of the function.
unsigned int get_function_index () const
Return the index of the function.
unsigned int GetFunctionReturnType (unsigned int function) const
Return the index associated with the type of the return of the function.
virtual bool is_bool (unsigned int index) const
Return true if index is a variable or a type of type bool.
virtual bool is_natural (unsigned int index) const
Return true if index is a variable grater than or equal to zero.
virtual bool is_int (unsigned int index) const
Return true if index is a variable or a type of type int.
virtual bool is_an_enum (unsigned int index) const
Return true if index is a variable or a type of type enum.
virtual bool is_unsigned (unsigned int index) const
Return true if index is a variable or a type of type unsigned int.
virtual bool is_real (unsigned int index) const
Return true if index is a variable or a type of type real.
virtual bool is_a_complex (unsigned int index) const
Return true if index is a variable or a type of type complex.
virtual bool is_a_struct (unsigned int index) const
Return true if index is a variable or a type of type struct.
virtual bool is_an_union (unsigned int index) const
Return true if index is a variable of a type of type union.
virtual bool is_an_array (unsigned int index) const
Return true if index is a variable or a type of type array.
bool is_a_vector (unsigned int variable) const
Return true if index is a variable or a type of type vector.
virtual bool is_a_pointer (unsigned int index) const
Return true if index is a variable or a type of type pointer.
virtual bool is_an_indirect_ref (unsigned int index) const
Return true if the index is an indirect ref.
virtual bool is_an_array_ref (unsigned int index) const
Return true if the index is an array ref.
virtual bool is_a_component_ref (unsigned int index) const
Return true if the index is a component ref.
virtual bool is_an_addr_expr (unsigned int index) const
Return true if the index is an addr_expr.
virtual bool is_a_mem_ref (unsigned int index) const
Return true if the index is a mem_ref.
virtual bool is_static (unsigned int decl) const
check if a given index is a static declaration
virtual bool is_extern (unsigned int decl) const
check if a given index is a extern declaration
virtual bool is_a_constant (unsigned int index) const
Return true if the index is a constant object.
virtual bool is_a_result_decl (unsigned int index) const
Return true if index is a result_decl.
virtual bool is_a_realpart_expr (unsigned int index) const
Return true if index is a realpart_expr.
virtual bool is_a_imagpart_expr (unsigned int index) const
Return true if index is a imagpart_expr.
virtual bool is_operating_system_function (const unsigned int obj) const
Return true if function is an operating system function.
virtual int unsigned start_with_a_label (const blocRef &block) const
Return the nodeID of the first statement of a basic block in case that statement is a label expression.
virtual unsigned int end_with_a_cond_or_goto (const blocRef &block) const
Return the nodeID of the last statement of a basic block in case that statement is a cond or a goto expression.
virtual unsigned int get_indirect_ref_var (unsigned int index) const
Return the variable of an indirect ref.
virtual unsigned int get_array_ref_array (unsigned int index) const
Return the array variable of an array ref.
virtual unsigned int get_array_ref_index (unsigned int index) const
Return the index variable of an array ref.
virtual unsigned int get_component_ref_record (unsigned int index) const
Return the record variable of a component ref.
virtual unsigned int get_component_ref_field (unsigned int index) const
Return the field index of a component ref.
virtual unsigned int get_mem_ref_base (unsigned int index) const
Return the base of a mem ref.
virtual unsigned int get_mem_ref_offset (unsigned int index) const
Return the offset of a mem ref.
virtual unsigned int get_operand_from_unary_expr (unsigned int index) const
Return the index of the operand if index is addr_expr, a realpart_expr or a imagpart_expr.
virtual unsigned int GetVarFromSsa (unsigned int index) const
Return the index of the variable base of a ssa var.
virtual unsigned int get_intermediate_var (unsigned int index) const
Return the intermediate variable of an operation.
virtual unsigned int get_type (const unsigned int var) const
Return the type of the variable.
virtual unsigned int get_pointed_type (const unsigned int type) const
Return the pointed type of a pointer.
unsigned int GetElements (const unsigned int index) const
Given an array or a vector return the element type.
virtual const CustomUnorderedSet< unsigned int > GetParameterTypes () const
Returns the types of the parameters.
const std::list< unsigned int > get_parameters () const
Return the list of index of original parameters of the function.
bool has_implementation () const
Return true if function has implementation.
virtual bool is_var_args () const
Returns true if this function is of var args type.
virtual bool is_va_start_call (unsigned int stm) const
return true in case stm is a va_start call_expr
virtual unsigned int GetInit (unsigned int var, CustomUnorderedSet< unsigned int > &list_of_variables) const
return the initialization object associated with the variable.
virtual unsigned int get_attributes (unsigned int var) const
return the attributes associated with the variable.
virtual unsigned int is_named_pointer (const unsigned int index) const
return the nodeid of the named pointer (pointer_type with a name different
unsigned int is_name_used (std::string var) const
Return if a variable with this name already exists.
void add_read_global_variable (unsigned int variable)
Add a read of a global variable.
void add_written_global_variable (unsigned int variable)
Add a writing of a global variables.
CustomOrderedSet< unsigned int > get_read_global_variables () const
Get the global variables read by the correspondent function.
CustomOrderedSet< unsigned int > get_written_global_variables () const
Get the global variables written by the correspondent function.
void add_initialization (unsigned int var, unsigned int init)
Add the initialization of a variables.
virtual std::string print_phinode_res (unsigned int phi_node_id, vertex v, const var_pp_functorConstRef vppf) const
void set_opaque ()
Set opaque flag to true.
void set_not_opaque ()
Set opaque flag to false.
bool get_opaque () const
Return the opaque flag.
virtual const std::string get_label_name (unsigned int label_expr_nid) const
return the label name associated with the label expression
virtual void create_gimple_modify_stmt (unsigned int function_decl_nid, blocRef &block, tree_nodeRef left_part, tree_nodeRef right_part)
create a gimple_assign
virtual std::string print_forward_declaration (unsigned int type) const
Print the declaration of a non built-in type.
virtual bool is_empty_return (unsigned int index) const
return true in case index is a return expr with an empty operand.
virtual unsigned int is_coming_from_phi_node (unsigned int nodeID) const
return the nodeID of the original gimple_phi in case the statement comes from a splitted phi node
virtual std::string print_node (unsigned int index, vertex v, const var_pp_functorConstRef vppf) const
Print the operations corresponding to the node.
virtual bool isCallExpression (unsigned int nodeID) const
This method returns true if the node specified in the parameters is a call expression.
virtual unsigned int getCallExpressionIndex (std::string launch_code) const
This method returns the index of the function whose launch code is given as a string parameter.
std::string PrintVarDeclaration (unsigned int var, const var_pp_functorConstRef vppf, bool init_has_to_be_printed) const
This function prints the declaration of a variable without the closing `;`.
unsigned int GetUnqualified (const unsigned int type) const
Return the unqualified version of a type.
virtual void get_typecast (unsigned int nodeid, CustomUnorderedSet< unsigned int > &types) const
return the types used in type casting by nodeid
bool IsDefaultSsaName (const unsigned int ssa_name_index) const
Return true if node is the default ssa_name.
bool function_has_to_be_printed (unsigned int f_id) const
returns true if the function body has to be printed by the C backend
std::string get_asm_string (const unsigned int node_index) const
return the string associated with the gimple_asm
bool IsStore (const unsigned int statement_index) const
Return if an operation is a store.
bool IsLoad (const unsigned int statement_index) const
Return if an operation is a load.
bool IsLut (const unsigned int statement_index) const
Return if an operation is a lut_expr.
Static Public Member Functions
static void rename_a_variable (unsigned int var, const std::string &new_name)
rename a variable
static void clear_renaming_table ()
remove all the entries from the renaming table
Protected Member Functions
bool has_bit_field (unsigned int variable) const
Return true if the variable is a field_decl and it has a bitfield.
Protected Attributes
const application_managerRef AppM
The application manager.
const tree_managerConstRef TM
The tree manager.
const ParameterConstRef Param
The set of input parameters.
int debug_level
the debug level
unsigned int function_index
Index of the function.
std::string function_name
Name of the function.
bool body
Flag to check if behavioral_graph_manager contains the function implementation.
bool opaque
Flag to check if a call to this function has to be treated as a TYPE_OPAQUE nodeID.
std::map< unsigned int, unsigned int > initializations
Structure which stores initializations.
Static Protected Attributes
static std::map< unsigned int, std::pair< std::string, int > > definitions
Maps between unqualified type and definition of a corresponding qualified type.
static std::map< std::string, unsigned int > used_name
Set of variables name already used.
static std::map< unsigned int, std::string > vars_symbol_table
The var symbol table.
static std::map< unsigned int, std::string > vars_renaming_table
Variable renaming table.
Detailed Description
Definition at line 81 of file behavioral_helper.hpp.
Constructor & Destructor Documentation
BehavioralHelper()
BehavioralHelper::BehavioralHelper (const application_managerRef AppM, unsigned int index, bool body, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
index is the index of the function_decl
body specifies if function body is available
parameters is the set of input parameters
Definition at line 119 of file behavioral_helper.cpp.
References ~BehavioralHelper().
 BehavioralHelper()
BehavioralHelper::~BehavioralHelper () [virtual], [default]
Destructor.
Referenced by BehavioralHelper().
Member Function Documentation
add_initialization()
void BehavioralHelper::add_initialization (unsigned int var, unsigned int init)
Add the initialization of a variables.
Parameters
var is the variable
init is the index of the initialization
Definition at line 1038 of file behavioral_helper.cpp.
References initializations.
add_read_global_variable()
void BehavioralHelper::add_read_global_variable (unsigned int variable)
Add a read of a global variable.
Parameters
variable is the global variable read
add_written_global_variable()
void BehavioralHelper::add_written_global_variable (unsigned int variable)
Add a writing of a global variables.
Parameters
variable is the global variable written
clear_renaming_table()
void BehavioralHelper::clear_renaming_table () [static]
remove all the entries from the renaming table
Definition at line 5438 of file behavioral_helper.cpp.
References vars_renaming_table.
Referenced by EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
create_gimple_modify_stmt()
void BehavioralHelper::create_gimple_modify_stmt (unsigned int function_decl_nid, blocRef & block, tree_nodeRef left_part, tree_nodeRef right_part) [virtual]
create a gimple_assign
Parameters
function_decl_nid is the node id of the function where the gimple_assign has to be inserted
block is the basic block where the gimple_assign has to be inserted
position is the statement after which gimple_assign has to be inserted
left_part is the tree_node of the left part
right_part is tree_node of the right part
Definition at line 5322 of file behavioral_helper.cpp.
References THROW_ERROR.
end_with_a_cond_or_goto()
unsigned int BehavioralHelper::end_with_a_cond_or_goto (const blocRef & block) const [virtual]
Return the nodeID of the last statement of a basic block in case that statement is a cond or a goto expression.
Parameters
block is basic block reference.
Definition at line 5302 of file behavioral_helper.cpp.
References GET_INDEX_NODE, and GET_NODE.
Referenced by EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
function_has_to_be_printed()
bool BehavioralHelper::function_has_to_be_printed (unsigned int f_id) const
returns true if the function body has to be printed by the C backend
Definition at line 5484 of file behavioral_helper.cpp.
References function_name, tree_helper::is_system(), and TM.
Referenced by VcdSignalSelection::CrossPropagateAddrSsa(), HWCallPathCalculator::discover_vertex(), VcdSignalSelection::SelectInternalSignals(), CBackend::WriteGlobalDeclarations(), CBackend::writeImplementations(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and DiscrepancyAnalysisCWriter::writePreInstructionInfo().
get_array_ref_array()
unsigned int BehavioralHelper::get_array_ref_array (unsigned int index) const [virtual]
Return the array variable of an array ref.
Parameters
index is an indirect_ref object.
Definition at line 4743 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_an_array_ref(), THROW_ASSERT, and TM.
Referenced by prettyPrintVertex::get_internal_vars(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_array_ref_index()
unsigned int BehavioralHelper::get_array_ref_index (unsigned int index) const [virtual]
Return the index variable of an array ref.
Parameters
index is an indirect_ref object.
Definition at line 4751 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_an_array_ref(), THROW_ASSERT, and TM.
Referenced by std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_asm_string()
std::string BehavioralHelper::get_asm_string (const unsigned int node_index) const
return the string associated with the gimple_asm
Parameters
node_index is the gimple_asm node id
Returns
the string associated with gimple_asm
Definition at line 5495 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, ENTRY_ID, EXIT_ID, tree_helper::get_asm_string(), GET_INDEX_NODE, GET_NODE, INDENT_DBG_MEX, IsLoad(), IsStore(), tree_helper::name_function(), STR, THROW_ASSERT, THROW_UNREACHABLE, and TM.
Referenced by moduleGenerator::specialize_fu().
get_attributes()
unsigned int BehavioralHelper::get_attributes (unsigned int var) const [virtual]
return the attributes associated with the variable.
Parameters
var is the index of variable
Returns
the attribute associated to the variable
Definition at line 5096 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), THROW_ASSERT, THROW_ERROR, and TM.
Referenced by PrintVarDeclaration().
get_component_ref_field()
unsigned int BehavioralHelper::get_component_ref_field (unsigned int index) const [virtual]
Return the field index of a component ref.
Parameters
index is an component_ref object.
Definition at line 4767 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_a_component_ref(), THROW_ASSERT, and TM.
Referenced by std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_component_ref_record()
unsigned int BehavioralHelper::get_component_ref_record (unsigned int index) const [virtual]
Return the record variable of a component ref.
Parameters
index is a component_ref object.
Definition at line 4759 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_a_component_ref(), THROW_ASSERT, and TM.
Referenced by prettyPrintVertex::get_internal_vars(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_definition()
std::tuple< std::string, unsigned int, unsigned int > BehavioralHelper::get_definition (unsigned int index, bool & is_system) const [virtual]
Returns where the type index is defined.
Parameters
index is the index typedef
bool tells if the type hype has been already recognized as system
Returns
a pair composed by the filename and the line:column of the definition
Definition at line 133 of file behavioral_helper.cpp.
References tree_helper::get_definition(), THROW_ASSERT, and TM.
Referenced by CBackend::AnalyzeInclude(), CWriter::DeclareType(), and HLSCWriter::WriteTestbenchFunctionCall().
get_function_index()
unsigned int BehavioralHelper::get_function_index () const
Return the index of the function.
Parameters
function_name is the name of the function
Definition at line 985 of file behavioral_helper.cpp.
References function_index.
Referenced by conn_binding_creator::add_parameter_ports(), top_entity::add_ports(), classic_datapath::add_ports(), TopEntityMemoryMapped::allocate_parameters(), memory_allocation::allocate_parameters(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), CWriter::DeclareLocalVariables(), memory_allocation::finalize_memory_allocation(), minimal_interface::InternalExec(), top_entity::InternalExec(), moduleGenerator::specialize_fu(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), CWriter::writeRoutineInstructions_rec(), and HLSCWriter::WriteTestbenchFunctionCall().
get_function_name()
std::string BehavioralHelper::get_function_name () const
Return the name of the function.
Definition at line 980 of file behavioral_helper.cpp.
References function_name.
Referenced by OpGraph::CGetOutEdges(), DataDependenceComputation::Computedependencies(), VcdSignalSelection::CrossPropagateAddrSsa(), discrepancy_instruction_writer::declareFunction(), CWriter::DeclareFunctionTypes(), CWriter::DeclareLocalVariables(), CWriter::DeclareType(), Loops::DetectLoops(), HWCallPathCalculator::examine_edge(), GenerateSynthesisScripts::Exec(), fun_dominator_allocation::Exec(), Evaluation::Exec(), memory_allocation::finalize_memory_allocation(), Bit_Value::initialize(), mem_cg_ext::InternalExec(), FSM_NI_SSA_liveness::InternalExec(), fsm_controller::InternalExec(), minimal_interface::InternalExec(), mem_dominator_allocation::InternalExec(), easy_module_binding::InternalExec(), TasteInterfaceGeneration::InternalExec(), top_entity_parallel_cs::InternalExec(), classic_datapath::InternalExec(), ControlFlowChecker::InternalExec(), weighted_clique_register::InternalExec(), AddBbEcfgEdges::InternalExec(), bb_feedback_edges_computation::InternalExec(), dom_post_dom_computation::InternalExec(), NI_SSA_liveness::InternalExec(), top_entity::InternalExec(), add_library::InternalExec(), datapath_parallel_cs::InternalExec(), operations_cfg_computation::InternalExec(), SDCScheduling::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), CWriter::WriteBuiltinWaitCall(), Schedule::WriteDot(), OpGraph::WriteDot(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), HLSCWriter::WriteFile(), CWriter::WriteFunctionBody(), DiscrepancyAnalysisCWriter::WriteFunctionDeclaration(), CWriter::WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteFunctionImplementation(), CBackend::WriteGlobalDeclarations(), CWriter::WriteHeader(), CBackend::writeIncludes(), HLSCWriter::WriteMainTestbench(), HLSCWriter::WriteParamDecl(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), and HLSCWriter::WriteTestbenchFunctionCall().
get_indirect_ref_var()
unsigned int BehavioralHelper::get_indirect_ref_var (unsigned int index) const [virtual]
Return the variable of an indirect ref.
Parameters
index is an indirect_ref object.
Definition at line 4732 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_an_indirect_ref(), THROW_ASSERT, and TM.
Referenced by prettyPrintVertex::get_internal_vars(), and pointer_var_pp_functor::operator()().
get_intermediate_var()
unsigned int BehavioralHelper::get_intermediate_var (unsigned int index) const [virtual]
Return the intermediate variable of an operation.
It returns 0 when there is not an intermediate variable.
Parameters
index is an operation.
check for type conversion
Definition at line 4809 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, and TM.
Referenced by prettyPrintVertex::get_internal_vars().
get_label_name()
const std::string BehavioralHelper::get_label_name (unsigned int label_expr_nid) const [virtual]
return the label name associated with the label expression
Definition at line 5291 of file behavioral_helper.cpp.
References GET_NODE, THROW_ASSERT, and TM.
Referenced by EdgeCWriter::writeRoutineInstructions(), and CWriter::writeRoutineInstructions().
get_mem_ref_base()
unsigned int BehavioralHelper::get_mem_ref_base (unsigned int index) const [virtual]
Return the base of a mem ref.
Parameters
index is a mem_ref object.
Definition at line 4775 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_a_mem_ref(), THROW_ASSERT, and TM.
Referenced by std_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_mem_ref_offset()
unsigned int BehavioralHelper::get_mem_ref_offset (unsigned int index) const [virtual]
Return the offset of a mem ref.
Parameters
index is a mem_ref object.
Definition at line 4783 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_a_mem_ref(), THROW_ASSERT, and TM.
Referenced by std_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_opaque()
bool BehavioralHelper::get_opaque () const
Return the opaque flag.
Returns
the opaque flag
Definition at line 1053 of file behavioral_helper.cpp.
References opaque.
get_operand_from_unary_expr()
unsigned int BehavioralHelper::get_operand_from_unary_expr (unsigned int index) const [virtual]
Return the index of the operand if index is addr_expr, a realpart_expr or a imagpart_expr.
Parameters
index is the index of the expression
Returns
the index of the operand
Definition at line 4791 of file behavioral_helper.cpp.
References GET_INDEX_NODE, is_a_imagpart_expr(), is_a_realpart_expr(), is_an_addr_expr(), THROW_ASSERT, and TM.
Referenced by prettyPrintVertex::get_internal_vars(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
get_parameters()
const std::list< unsigned int > BehavioralHelper::get_parameters () const
Return the list of index of original parameters of the function.
Definition at line 999 of file behavioral_helper.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, fun(), function_index, GET_INDEX_NODE, GET_NODE, INDENT_DBG_MEX, test_panda::parameters, STR, and TM.
Referenced by conn_binding_creator::add_parameter_ports(), top_entity::add_ports(), classic_datapath::add_ports(), fu_binding::add_to_SM(), TopEntityMemoryMapped::allocate_parameters(), memory_allocation::allocate_parameters(), TestbenchMemoryAllocation::AllocTestbenchMemory(), datapath_parallel_cs::connect_module_kernel(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), CWriter::DeclareLocalVariables(), memory_allocation::finalize_memory_allocation(), TopEntityMemoryMapped::InternalExec(), TestVectorParser::ParseXMLFile(), CWriter::StartFunctionBody(), CWriter::WriteBuiltinWaitCall(), HLSCWriter::WriteExpectedResults(), CBackend::writeIncludes(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteSimulatorInitMemory(), and HLSCWriter::WriteTestbenchFunctionCall().
get_pointed_type()
unsigned int BehavioralHelper::get_pointed_type (const unsigned int type) const [virtual]
Return the pointed type of a pointer.
Parameters
type is a pointer object
Definition at line 1063 of file behavioral_helper.cpp.
References tree_helper::get_pointed_type(), and TM.
Referenced by print_node().
get_read_global_variables()
CustomOrderedSet<unsigned int> BehavioralHelper::get_read_global_variables () const
Get the global variables read by the correspondent function.
get_size()
unsigned int BehavioralHelper::get_size (unsigned int index) const [virtual]
Return the size in bit of a C object.
Parameters
index is the index of a C object
Returns
the size in bit
Definition at line 975 of file behavioral_helper.cpp.
References tree_helper::size(), and TM.
Referenced by WB4_interface::get_data_bus_bitsize(), print_node(), structural_type_descriptor::structural_type_descriptor(), and CWriter::WriteBuiltinWaitCall().
get_type()
unsigned int BehavioralHelper::get_type (const unsigned int var) const [virtual]
Return the type of the variable.
Parameters
var is the index of variable
Definition at line 1058 of file behavioral_helper.cpp.
References tree_helper::get_type_index(), and TM.
Referenced by CWriter::DeclareVariable(), is_a_complex(), is_a_struct(), is_a_vector(), is_an_array(), is_an_enum(), is_an_union(), is_bool(), is_int(), is_named_pointer(), is_real(), is_unsigned(), std_var_pp_functor::operator()(), isolated_var_pp_functor::operator()(), print_node(), print_type_declaration(), PrintVarDeclaration(), structural_type_descriptor::structural_type_descriptor(), CWriter::WriteBuiltinWaitCall(), CBackend::writeIncludes(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), and HLSCWriter::WriteTestbenchFunctionCall().
get_typecast()
void BehavioralHelper::get_typecast (unsigned int nodeid, CustomUnorderedSet< unsigned int > & types) const [virtual]
return the types used in type casting by nodeid
Parameters
nodeid is the statement analyzed
types is the set of types type-casted by nodeid
Definition at line 5443 of file behavioral_helper.cpp.
References TM, and tree_node::visit().
Referenced by CWriter::declare_cast_types(), and CBackend::writeIncludes().
get_written_global_variables()
CustomOrderedSet<unsigned int> BehavioralHelper::get_written_global_variables () const
Get the global variables written by the correspondent function.
getCallExpressionIndex()
unsigned int BehavioralHelper::getCallExpressionIndex (std::string launch_code) const [virtual]
This method returns the index of the function whose launch code is given as a string parameter.
This information will be used to decide whether to insert or not the CUDA execution configuration launch code in the call expression.
Parameters
launch_code is the function launch code
Returns
the called-function identifier
Definition at line 1083 of file behavioral_helper.cpp.
References index, and TM.
GetElements()
unsigned int BehavioralHelper::GetElements (const unsigned int index) const
Given an array or a vector return the element type.
Parameters
index is the type of the array
Returns
the type of the element
Definition at line 1068 of file behavioral_helper.cpp.
References tree_helper::GetElements(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor(), HLSCWriter::WriteExpectedResults(), and HLSCWriter::WriteSimulatorInitMemory().
GetFunctionReturnType()
unsigned int BehavioralHelper::GetFunctionReturnType (unsigned int function) const
Return the index associated with the type of the return of the function.
Parameters
function_is is the index of the function
Returns
the index of the type
Definition at line 990 of file behavioral_helper.cpp.
References tree_helper::GetFunctionReturnType(), tree_node::index, and TM.
Referenced by conn_binding_creator::add_parameter_ports(), top_entity::add_ports(), classic_datapath::add_ports(), TopEntityMemoryMapped::allocate_parameters(), memory_allocation::allocate_parameters(), CWriter::DeclareFunctionTypes(), memory_allocation::finalize_memory_allocation(), TopEntityMemoryMapped::forwardPorts(), TopEntityMemoryMapped::insertMemoryMappedRegister(), TestVectorParser::ParseXMLFile(), VcdSignalSelection::SelectAddrSsa(), WishboneInterfaceTestbench::write_call(), WishboneInterfaceTestbench::write_file_reading_operations(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), CWriter::WriteBuiltinWaitCall(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteMainTestbench(), and HLSCWriter::WriteTestbenchFunctionCall().
GetInit()
unsigned int BehavioralHelper::GetInit (unsigned int var, CustomUnorderedSet< unsigned int > & list_of_variables) const [virtual]
return the initialization object associated with the variable.
Parameters
var is the index of variable
list_of_variables is used to return list of variables used during initialization
Returns
the index of the initialization object associated with the variable reference storing at the end true only if the variable has an initialization objetct. In case the variable does not have an initialization object this function returns 0.
Definition at line 5154 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), tree_helper::get_used_variables(), INDENT_DBG_MEX, initializations, PrintVariable(), THROW_UNREACHABLE, and TM.
Referenced by CWriter::DeclareVariable(), and PrintVarDeclaration().
GetParameterTypes()
const CustomUnorderedSet< unsigned int > BehavioralHelper::GetParameterTypes () const [virtual]
Returns the types of the parameters.
Returns
the types of the parameters
Definition at line 5003 of file behavioral_helper.cpp.
References function_index, GET_INDEX_NODE, GET_NODE, TM, and decl_node::type.
Referenced by CWriter::DeclareFunctionTypes().
GetUnqualified()
unsigned int BehavioralHelper::GetUnqualified (const unsigned int type) const
Return the unqualified version of a type.
Parameters
type is the type
Returns
the unqualified version of the type if it exists, 0 otherwise
Definition at line 5423 of file behavioral_helper.cpp.
References tree_helper::GetUnqualified(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor().
GetVarFromSsa()
unsigned int BehavioralHelper::GetVarFromSsa (unsigned int index) const [virtual]
Return the index of the variable base of a ssa var.
Parameters
index is the index of the ssa var
Returns
the index of the base variable
Definition at line 4799 of file behavioral_helper.cpp.
References GET_INDEX_NODE, index, and TM.
Referenced by pointer_var_pp_functor::operator()().
has_bit_field()
bool BehavioralHelper::has_bit_field (unsigned int variable) const [protected]
Return true if the variable is a field_decl and it has a bitfield.
Definition at line 5081 of file behavioral_helper.cpp.
References tree_node::get_kind(), TM, and TOK_BITFIELD.
Referenced by print_node(), and print_type_declaration().
has_implementation()
bool BehavioralHelper::has_implementation () const
Return true if function has implementation.
Definition at line 1033 of file behavioral_helper.cpp.
References body.
Referenced by VcdSignalSelection::CrossPropagateAddrSsa(), HWCallPathCalculator::discover_vertex(), VcdSignalSelection::SelectInternalSignals(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and DiscrepancyAnalysisCWriter::writePreInstructionInfo().
InvaildateVariableName()
void BehavioralHelper::InvaildateVariableName (const unsigned int index)
Invalidate cached variable name.
Parameters
index is the variable whose name must be invalidated
Definition at line 5768 of file behavioral_helper.cpp.
References vars_symbol_table.
is_a_complex()
bool BehavioralHelper::is_a_complex (unsigned int index) const [virtual]
Return true if index is a variable or a type of type complex.
Definition at line 4513 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_a_complex(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor(), and DiscrepancyAnalysisCWriter::writePostInstructionInfo().
is_a_component_ref()
bool BehavioralHelper::is_a_component_ref (unsigned int index) const [virtual]
Return true if the index is a component ref.
Parameters
index is the index
Definition at line 4561 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by get_component_ref_field(), get_component_ref_record(), prettyPrintVertex::get_internal_vars(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_a_constant()
bool BehavioralHelper::is_a_constant (unsigned int index) const [virtual]
Return true if the index is a constant object.
Parameters
index is a nodeID.
Returns
true if it's a constant object
Definition at line 4598 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, GET_INDEX_NODE, tree_node::get_kind(), and TM.
Referenced by mux_connection_binding::determine_connection(), prettyPrintVertex::get_internal_vars(), print_constant(), PrintVariable(), and mux_connection_binding::swap_p().
is_a_imagpart_expr()
bool BehavioralHelper::is_a_imagpart_expr (unsigned int index) const [virtual]
Return true if index is a imagpart_expr.
Parameters
index is the index of the node
Returns
true if index is a imagpart_expr
Definition at line 4714 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by get_operand_from_unary_expr(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_a_mem_ref()
bool BehavioralHelper::is_a_mem_ref (unsigned int index) const [virtual]
Return true if the index is a mem_ref.
Parameters
index is the index
Definition at line 4579 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by get_mem_ref_base(), get_mem_ref_offset(), std_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_a_pointer()
bool BehavioralHelper::is_a_pointer (unsigned int index) const [virtual]
Return true if index is a variable or a type of type pointer.
Definition at line 4538 of file behavioral_helper.cpp.
References tree_helper::is_a_pointer(), and TM.
Referenced by TestbenchMemoryAllocation::AllocTestbenchMemory(), TestVectorParser::ParseXMLFile(), print_node(), structural_type_descriptor::structural_type_descriptor(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteSimulatorInitMemory(), and HLSCWriter::WriteTestbenchFunctionCall().
is_a_realpart_expr()
bool BehavioralHelper::is_a_realpart_expr (unsigned int index) const [virtual]
Return true if index is a realpart_expr.
Parameters
index is the index of the node
Returns
true if index is a realpart_expr
Definition at line 4705 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by get_operand_from_unary_expr(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_a_result_decl()
bool BehavioralHelper::is_a_result_decl (unsigned int index) const [virtual]
Return true if index is a result_decl.
Definition at line 4696 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
is_a_struct()
bool BehavioralHelper::is_a_struct (unsigned int index) const [virtual]
Return true if index is a variable or a type of type struct.
Definition at line 4518 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_a_struct(), and TM.
Referenced by TestbenchMemoryAllocation::AllocTestbenchMemory(), print_node(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and HLSCWriter::WriteSimulatorInitMemory().
is_a_vector()
bool BehavioralHelper::is_a_vector (unsigned int variable) const
Return true if index is a variable or a type of type vector.
Definition at line 4533 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_a_vector(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor(), and DiscrepancyAnalysisCWriter::writePostInstructionInfo().
is_an_addr_expr()
bool BehavioralHelper::is_an_addr_expr (unsigned int index) const [virtual]
Return true if the index is an addr_expr.
Parameters
index is the index
Definition at line 4570 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by prettyPrintVertex::get_internal_vars(), get_operand_from_unary_expr(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_an_array()
bool BehavioralHelper::is_an_array (unsigned int index) const [virtual]
Return true if index is a variable or a type of type array.
Definition at line 4528 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_an_array(), and TM.
Referenced by TestbenchMemoryAllocation::AllocTestbenchMemory(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), address_var_pp_functor::operator()(), isolated_var_pp_functor::operator()(), print_node(), structural_type_descriptor::structural_type_descriptor(), HLSCWriter::WriteExpectedResults(), and HLSCWriter::WriteSimulatorInitMemory().
is_an_array_ref()
bool BehavioralHelper::is_an_array_ref (unsigned int index) const [virtual]
Return true if the index is an array ref.
Parameters
index is a variable.
Definition at line 4552 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by get_array_ref_array(), get_array_ref_index(), prettyPrintVertex::get_internal_vars(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_an_enum()
bool BehavioralHelper::is_an_enum (unsigned int index) const [virtual]
Return true if index is a variable or a type of type enum.
Definition at line 4499 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_an_enum(), and TM.
is_an_indirect_ref()
bool BehavioralHelper::is_an_indirect_ref (unsigned int index) const [virtual]
Return true if the index is an indirect ref.
Parameters
index is a variable.
Definition at line 4543 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
Referenced by get_indirect_ref_var(), prettyPrintVertex::get_internal_vars(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), and isolated_var_pp_functor::operator()().
is_an_union()
bool BehavioralHelper::is_an_union (unsigned int index) const [virtual]
Return true if index is a variable of a type of type union.
Parameters
index is the index of the variable or of the type
Returns
true if variable or type is of type union
Definition at line 4523 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_an_union(), and TM.
Referenced by print_node(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and HLSCWriter::WriteSimulatorInitMemory().
is_bool()
bool BehavioralHelper::is_bool (unsigned int index) const [virtual]
Return true if index is a variable or a type of type bool.
Definition at line 4484 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_bool(), and TM.
Referenced by TestVectorParser::ParseXMLFile(), and structural_type_descriptor::structural_type_descriptor().
is_coming_from_phi_node()
unsigned int BehavioralHelper::is_coming_from_phi_node (unsigned int nodeID) const [virtual]
return the nodeID of the original gimple_phi in case the statement comes from a splitted phi node
Parameters
nodeID is the statement nodeID
Definition at line 1128 of file behavioral_helper.cpp.
References GET_INDEX_NODE, and TM.
is_empty_return()
bool BehavioralHelper::is_empty_return (unsigned int index) const [virtual]
return true in case index is a return expr with an empty operand.
Definition at line 5415 of file behavioral_helper.cpp.
References THROW_ASSERT, and TM.
is_extern()
bool BehavioralHelper::is_extern (unsigned int decl) const [virtual]
check if a given index is a extern declaration
Parameters
decl is the decl index id
Returns
true whem decl is an extern function or variable declaration
Definition at line 4593 of file behavioral_helper.cpp.
References tree_helper::is_extern(), and TM.
is_int()
bool BehavioralHelper::is_int (unsigned int index) const [virtual]
Return true if index is a variable or a type of type int.
Definition at line 4494 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_int(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor(), and CWriter::WriteBuiltinWaitCall().
is_name_used()
unsigned int BehavioralHelper::is_name_used (std::string var) const
Return if a variable with this name already exists.
Parameters
var is the name of the variable
Returns
0 if is name hasn't been used, index of the existing variable with that name otherwise
is_named_pointer()
unsigned int BehavioralHelper::is_named_pointer (const unsigned int index) const [virtual]
return the nodeid of the named pointer (pointer_type with a name different
Parameters
index is the index of the variable or the index of the type
Definition at line 5032 of file behavioral_helper.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), get_type(), THROW_ASSERT, TM, and test_panda::type.
is_natural()
bool BehavioralHelper::is_natural (unsigned int index) const [virtual]
Return true if index is a variable grater than or equal to zero.
Definition at line 4489 of file behavioral_helper.cpp.
References tree_helper::is_natural(), and TM.
is_operating_system_function()
bool BehavioralHelper::is_operating_system_function (const unsigned int obj) const [virtual]
Return true if function is an operating system function.
Parameters
index is the index of the node
Returns
true if index is a library system function
Definition at line 4723 of file behavioral_helper.cpp.
References decl_node::operating_system_flag, and TM.
Referenced by VcdSignalSelection::CrossPropagateAddrSsa().
is_real()
bool BehavioralHelper::is_real (unsigned int index) const [virtual]
Return true if index is a variable or a type of type real.
Definition at line 4508 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_real(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor(), CWriter::WriteBuiltinWaitCall(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteParamInitialization(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), HLSCWriter::WriteSimulatorInitMemory(), and HLSCWriter::WriteTestbenchFunctionCall().
is_static()
bool BehavioralHelper::is_static (unsigned int decl) const [virtual]
check if a given index is a static declaration
Parameters
decl is the decl index id
Returns
true whem decl is a static function or variable declaration
Definition at line 4588 of file behavioral_helper.cpp.
References tree_helper::is_static(), and TM.
is_unsigned()
bool BehavioralHelper::is_unsigned (unsigned int index) const [virtual]
Return true if index is a variable or a type of type unsigned int.
Definition at line 4503 of file behavioral_helper.cpp.
References get_type(), tree_helper::is_unsigned(), and TM.
Referenced by structural_type_descriptor::structural_type_descriptor(), CWriter::WriteBuiltinWaitCall(), HLSCWriter::WriteParamInitialization(), and HLSCWriter::WriteSimulatorInitMemory().
is_va_start_call()
bool BehavioralHelper::is_va_start_call (unsigned int stm) const [virtual]
return true in case stm is a va_start call_expr
Parameters
stm is the statement
Definition at line 5051 of file behavioral_helper.cpp.
References tree_node::get_kind(), GET_NODE, is_var_args(), tree_helper::print_function_name(), and TM.
is_var_args()
bool BehavioralHelper::is_var_args () const [virtual]
Returns true if this function is of var args type.
Returns
true if this function is of var args type
Definition at line 1138 of file behavioral_helper.cpp.
References function_index, tree_node::get_kind(), GET_NODE, THROW_ASSERT, TM, and test_panda::type.
Referenced by VcdSignalSelection::CrossPropagateAddrSsa(), is_va_start_call(), and CWriter::WriteFunctionDeclaration().
isCallExpression()
bool BehavioralHelper::isCallExpression (unsigned int nodeID) const [virtual]
This method returns true if the node specified in the parameters is a call expression.
Parameters
node is the ID of the node to be analyzed
Returns
true if and only if the specified node is a call expression, false otherwise
Definition at line 1073 of file behavioral_helper.cpp.
References tree_node::get_kind(), and TM.
IsDefaultSsaName()
bool BehavioralHelper::IsDefaultSsaName (const unsigned int ssa_name_index) const
Return true if node is the default ssa_name.
Definition at line 5450 of file behavioral_helper.cpp.
References function_index, and TM.
Referenced by pointer_var_pp_functor::operator()().
IsLoad()
bool BehavioralHelper::IsLoad (const unsigned int statement_index) const
Return if an operation is a load.
Parameters
statement_index is the index of the tree node
Returns
true if statement is a load
Definition at line 5757 of file behavioral_helper.cpp.
References AppM, function_index, tree_helper::IsLoad(), and TM.
Referenced by get_asm_string().
IsLut()
bool BehavioralHelper::IsLut (const unsigned int statement_index) const
Return if an operation is a lut_expr.
Parameters
statement_index is the index of the tree node
Returns
true if statement is a lut_expr
Definition at line 5763 of file behavioral_helper.cpp.
References tree_helper::IsLut(), and TM.
IsStore()
bool BehavioralHelper::IsStore (const unsigned int statement_index) const
Return if an operation is a store.
Parameters
statement_index is the index of the tree node
Returns
true if statement is a store
Definition at line 5751 of file behavioral_helper.cpp.
References AppM, function_index, tree_helper::IsStore(), and TM.
Referenced by get_asm_string().
print_attributes()
std::string BehavioralHelper::print_attributes (unsigned int index, const var_pp_functorConstRef vppf, bool first = true) const [virtual]
Print the attributes associated to a variable.
Parameters
index is the attribute node
vppf is the functor used to dump the variable var.
Definition at line 514 of file behavioral_helper.cpp.
References GET_INDEX_NODE, GET_NODE, print_constant(), PrintVariable(), THROW_ERROR, and TM.
Referenced by PrintVarDeclaration().
print_constant()
std::string BehavioralHelper::print_constant (unsigned int var, const var_pp_functorConstRef vppf = var_pp_functorConstRef()) const [virtual]
Print the constant associated with index.
Parameters
index is the constant id.
vppf is the functor used to dump the variable var.
long double
double
float
FIXME: float can not be used for imaginary part of complex number
Definition at line 646 of file behavioral_helper.cpp.
References C_EC, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, is_a_constant(), tree_helper::is_system(), tree_helper::print_function_name(), tree_helper::print_type(), PrintVariable(), THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, TM, and test_panda::type.
Referenced by print_attributes(), print_init(), print_node(), print_type_declaration(), PrintVariable(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
print_forward_declaration()
std::string BehavioralHelper::print_forward_declaration (unsigned int type) const [virtual]
Print the declaration of a non built-in type.
Parameters
type is an object type.
Definition at line 5327 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), tree_helper::print_type(), THROW_ERROR, TM, and test_panda::type.
Referenced by prettyPrintVertex::print_forward_declaration().
print_init()
std::string BehavioralHelper::print_init (unsigned int index, const var_pp_functorConstRef vppf) const [virtual]
Print the initialization part.
Parameters
index is the initialization expression.
vppf is the functor used to dump the variable var.
check if designated initializers are really needed
Definition at line 238 of file behavioral_helper.cpp.
References CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, MAX_ROW_LENGTH, NULL_VERTEX, print_constant(), tree_helper::print_function_name(), print_node(), PrintVariable(), STR, THROW_ASSERT, THROW_ERROR, and TM.
Referenced by print_node(), and PrintVarDeclaration().
print_node()
std::string BehavioralHelper::print_node (unsigned int index, vertex v, const var_pp_functorConstRef vppf) const [virtual]
Print the operations corresponding to the node.
Parameters
index is the index of the node
v is the vertex of the operation
vppf is the functor used to dump the variable var. The stream on which string is printed is the one associate with the identer
Returns
the string corrisponding to the node
check possible pointer arithmetic reverse
&string[0]
&array is printed back as array
check for type conversion
check for type conversion
check for type conversion
__builtin_va_start should be ad-hoc managed
Print parameters.
This pattern is for gcc 4.5
This pattern is for gcc 4.6
__builtin_va_start should be ad-hoc managed
Print parameters.
now print clauses
now print clauses
now print clauses
now print clauses
Definition at line 1146 of file behavioral_helper.cpp.
References BITFIELD_EC, C_EC, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_NON_ADDR_UNARY_EXPRESSION, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_helper::CGetType(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_helper::find_obj_type_ref_function(), refcount< T >::get(), GET_CONST_NODE, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, get_pointed_type(), get_size(), get_type(), tree_helper::get_type_index(), tree_helper::get_type_node(), tree_helper::GetElements(), tree_helper::GetFunctionReturnType(), tree_helper::GetRealType(), has_bit_field(), INDENT_DBG_MEX, index, tree_node::index, is_a_pointer(), tree_helper::is_a_pointer(), is_a_struct(), tree_helper::is_a_struct(), tree_helper::is_a_vector(), is_an_array(), is_an_union(), tree_helper::is_an_union(), tree_helper::is_function_pointer_type(), integer_type::max, tree_helper::name_type(), tree_helper::op_symbol(), Param, print_constant(), tree_helper::print_function_name(), print_init(), print_type(), tree_helper::print_type(), PrintVariable(), tree_helper::size(), STR, STR_CST_pragma_keyword_call_hw, STR_CST_pragma_keyword_call_point_hw, STR_CST_pragma_keyword_map, STR_CST_pragma_keyword_recursive, STR_CST_string_sizeof, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, TM, and test_panda::type.
Referenced by TransitionInfo::print(), print_init(), print_phinode_res(), and print_vertex().
print_phinode_res()
std::string BehavioralHelper::print_phinode_res (unsigned int phi_node_id, vertex v, const var_pp_functorConstRef vppf) const [virtual]
Definition at line 5263 of file behavioral_helper.cpp.
References GET_INDEX_NODE, phi, print_node(), THROW_ASSERT, and TM.
print_type()
std::string BehavioralHelper::print_type (unsigned int type, bool global = false, bool print_qualifiers = false, bool print_storage = false, unsigned int var = 0, const var_pp_functorConstRef vppf = var_pp_functorConstRef(), const std::string & prefix = ``, const std::string & tail = ``) const [virtual]
Print a type and its variable in case var is not zero.
Parameters
type is the type of var.
global tells if the variable is global
print_qualifiers tells if the qualifiers (i.e. `const`) have to be printed
print_storage tells if the storage (i.e. `static`) has to be printed
var is the variable.
vppf is the pointer to the functor used to dump the possible variable var
prefix is the string to be appended at the begining of the printing
Returns
the printed string
Definition at line 5428 of file behavioral_helper.cpp.
References tree_helper::print_type(), and TM.
Referenced by conn_binding_creator::add_parameter_ports(), classic_datapath::add_ports(), InstructionWriter::declareFunction(), std_var_pp_functor::operator()(), isolated_var_pp_functor::operator()(), print_node(), structural_type_descriptor::structural_type_descriptor(), CWriter::WriteBuiltinWaitCall(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteMainTestbench(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), and HLSCWriter::WriteTestbenchFunctionCall().
print_type_declaration()
std::string BehavioralHelper::print_type_declaration (unsigned int type) const [virtual]
Print the declaration of a non built-in type.
Parameters
type is an object type.
Print the contents of the structure
Print the contents of the structure
Compute the dimensions
NOTE: this case cannot be moved because of break absence
Definition at line 4124 of file behavioral_helper.cpp.
References C_EC, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, enumeral_type::csts, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, array_type::elts, FIRST_TOKEN, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, get_type(), tree_helper::GetRealType(), has_bit_field(), INDENT_DBG_MEX, type_node::name, decl_node::packed_flag, type_node::packed_flag, Param, print_constant(), tree_helper::print_type(), pointer_type::ptd, type_node::qual, tree_helper::return_C_qualifiers(), type_node::size, field_decl::size, THROW_ASSERT, THROW_ERROR_CODE, THROW_UNREACHABLE, TM, test_panda::type, and type_node::unql.
Referenced by CWriter::DeclareType().
print_vertex()
std::string BehavioralHelper::print_vertex (const OpGraphConstRef g, const vertex v, const var_pp_functorConstRef vppf, const bool dot = false) const
Print the operations corrisponding to the vertex.
Parameters
g is the graph
v is the vertex
vppf is the functor used to dump the variable var.
dot tells if the output is a dot graph
Definition at line 139 of file behavioral_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, OpGraph::CGetOpNodeInfo(), ENTRY_ID, EXIT_ID, tree_node::get_kind(), print_node(), and TM.
Referenced by OpWriter::operator()(), StateInfo::print(), and InstructionWriter::write().
PrintVarDeclaration()
std::string BehavioralHelper::PrintVarDeclaration (unsigned int var, const var_pp_functorConstRef vppf, bool init_has_to_be_printed) const
This function prints the declaration of a variable without the closing `;`.
For example the function prints on the stream os the following piece of C code:
* MYINT a
* 
 when the variable var is equal to 4(a) and the vppf is an instance of std_var_pp_functor.
Parameters
var is the considered variable.
vppf is the functor used to dump the variable var.
print_init tells if the init has to be printed
If it is not a decl node (then it is an ssa-name) or it's a not system decl_node
Definition at line 1094 of file behavioral_helper.cpp.
References get_attributes(), tree_node::get_kind_text(), GET_NODE, get_type(), GetInit(), print_attributes(), print_init(), tree_helper::print_type(), THROW_ASSERT, and TM.
Referenced by CWriter::DeclareVariable().
PrintVariable()
std::string BehavioralHelper::PrintVariable (unsigned int index) const
Print the name of the variable associated to the index.
Parameters
index is the considered variable.
Returns
the name of the variable
Definition at line 543 of file behavioral_helper.cpp.
References default_COND, refcount< T >::get(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_node::index, INTERNAL, is_a_constant(), tree_helper::normalized_ID(), Param, print_constant(), tree_helper::print_function_name(), tree_helper::print_type(), THROW_ASSERT, TM, vars_renaming_table, and vars_symbol_table.
Referenced by conn_binding_creator::add_parameter_ports(), top_entity::add_ports(), classic_datapath::add_ports(), memory_allocation::allocate_parameters(), TestbenchMemoryAllocation::AllocTestbenchMemory(), top_entity_parallel_cs::connect_loop_iter(), datapath_parallel_cs::connect_module_kernel(), mux_connection_binding::create_connections(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), CWriter::DeclareVariable(), mux_connection_binding::determine_connection(), GetInit(), TopEntityMemoryMapped::insertMemoryMappedRegister(), allocation::IntegrateTechnologyLibraries(), FSM_NI_SSA_liveness::InternalExec(), mem_dominator_allocation::InternalExec(), TopEntityMemoryMapped::InternalExec(), NI_SSA_liveness::InternalExec(), port_swapping::InternalExec(), std_var_pp_functor::operator()(), pointer_var_pp_functor::operator()(), address_var_pp_functor::operator()(), isolated_var_pp_functor::operator()(), TestVectorParser::ParseXMLFile(), print_attributes(), Bit_Value::print_bitstring_map(), print_constant(), print_init(), print_node(), CdfgEdgeInfo::PrintLabels(), MemoryInitializationCWriter::Process(), MemoryInitializationWriter::Process(), WishboneInterfaceTestbench::write_call(), WishboneInterfaceTestbench::write_file_reading_operations(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), CWriter::WriteBuiltinWaitCall(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), CBackend::writeIncludes(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteParamInMemory(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), EdgeCWriter::writeRoutineInstructions_rec(), CWriter::writeRoutineInstructions_rec(), HLSCWriter::WriteSimulatorInitMemory(), and HLSCWriter::WriteTestbenchFunctionCall().
rename_a_variable()
void BehavioralHelper::rename_a_variable (unsigned int var, const std::string & new_name) [static]
rename a variable
Parameters
var is the index of the variable renamed
new_name is the new variable name
Definition at line 5433 of file behavioral_helper.cpp.
References vars_renaming_table.
Referenced by EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
set_not_opaque()
void BehavioralHelper::set_not_opaque ()
Set opaque flag to false.
Definition at line 1048 of file behavioral_helper.cpp.
References opaque.
set_opaque()
void BehavioralHelper::set_opaque ()
Set opaque flag to true.
Definition at line 1043 of file behavioral_helper.cpp.
References opaque.
start_with_a_label()
unsigned int BehavioralHelper::start_with_a_label (const blocRef & block) const [virtual]
Return the nodeID of the first statement of a basic block in case that statement is a label expression.
Parameters
block is basic block reference.
Definition at line 5273 of file behavioral_helper.cpp.
References GET_INDEX_NODE, and GET_NODE.
Referenced by EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
Field Documentation
AppM
const application_managerRef BehavioralHelper::AppM [protected]
The application manager.
Definition at line 85 of file behavioral_helper.hpp.
Referenced by IsLoad(), and IsStore().
body
bool BehavioralHelper::body [protected]
Flag to check if behavioral_graph_manager contains the function implementation.
Definition at line 115 of file behavioral_helper.hpp.
Referenced by has_implementation().
debug_level
int BehavioralHelper::debug_level [protected]
the debug level
Definition at line 94 of file behavioral_helper.hpp.
Referenced by get_asm_string(), get_parameters(), GetInit(), print_constant(), print_node(), and print_type_declaration().
definitions
std::map<unsigned int, std::pair<std::string, int> > BehavioralHelper::definitions [static], [protected]
Maps between unqualified type and definition of a corresponding qualified type.
Definition at line 97 of file behavioral_helper.hpp.
function_index
unsigned int BehavioralHelper::function_index [protected]
Index of the function.
Definition at line 109 of file behavioral_helper.hpp.
Referenced by get_function_index(), get_parameters(), GetParameterTypes(), is_var_args(), IsDefaultSsaName(), IsLoad(), and IsStore().
function_name
std::string BehavioralHelper::function_name [protected]
Name of the function.
Definition at line 112 of file behavioral_helper.hpp.
Referenced by function_has_to_be_printed(), and get_function_name().
initializations
std::map<unsigned int, unsigned int> BehavioralHelper::initializations [protected]
Structure which stores initializations.
Definition at line 121 of file behavioral_helper.hpp.
Referenced by add_initialization(), and GetInit().
opaque
bool BehavioralHelper::opaque [protected]
Flag to check if a call to this function has to be treated as a TYPE_OPAQUE nodeID.
Definition at line 118 of file behavioral_helper.hpp.
Referenced by get_opaque(), set_not_opaque(), and set_opaque().
Param
const ParameterConstRef BehavioralHelper::Param [protected]
The set of input parameters.
Definition at line 91 of file behavioral_helper.hpp.
Referenced by print_node(), print_type_declaration(), and PrintVariable().
TM
const tree_managerConstRef BehavioralHelper::TM [protected]
The tree manager.
Definition at line 88 of file behavioral_helper.hpp.
Referenced by function_has_to_be_printed(), get_array_ref_array(), get_array_ref_index(), get_asm_string(), get_attributes(), get_component_ref_field(), get_component_ref_record(), get_definition(), get_indirect_ref_var(), get_intermediate_var(), get_label_name(), get_mem_ref_base(), get_mem_ref_offset(), get_operand_from_unary_expr(), get_parameters(), get_pointed_type(), get_size(), get_type(), get_typecast(), getCallExpressionIndex(), GetElements(), GetFunctionReturnType(), GetInit(), GetParameterTypes(), GetUnqualified(), GetVarFromSsa(), has_bit_field(), is_a_complex(), is_a_component_ref(), is_a_constant(), is_a_imagpart_expr(), is_a_mem_ref(), is_a_pointer(), is_a_realpart_expr(), is_a_result_decl(), is_a_struct(), is_a_vector(), is_an_addr_expr(), is_an_array(), is_an_array_ref(), is_an_enum(), is_an_indirect_ref(), is_an_union(), is_bool(), is_coming_from_phi_node(), is_empty_return(), is_extern(), is_int(), is_named_pointer(), is_natural(), is_operating_system_function(), is_real(), is_static(), is_unsigned(), is_va_start_call(), is_var_args(), isCallExpression(), IsDefaultSsaName(), IsLoad(), IsLut(), IsStore(), print_attributes(), print_constant(), print_forward_declaration(), print_init(), print_node(), print_phinode_res(), print_type(), print_type_declaration(), print_vertex(), PrintVarDeclaration(), and PrintVariable().
used_name
std::map< std::string, unsigned int > BehavioralHelper::used_name [static], [protected]
Set of variables name already used.
Autoheader include.
Header include Behavior include Constant include Parameter include parser/treegcc include Tree include Utility include wrapper/treegcc include
Definition at line 100 of file behavioral_helper.hpp.
vars_renaming_table
std::map< unsigned int, std::string > BehavioralHelper::vars_renaming_table [static], [protected]
Variable renaming table.
Definition at line 106 of file behavioral_helper.hpp.
Referenced by clear_renaming_table(), PrintVariable(), and rename_a_variable().
vars_symbol_table
std::map< unsigned int, std::string > BehavioralHelper::vars_symbol_table [static], [protected]
The var symbol table.
Definition at line 103 of file behavioral_helper.hpp.
Referenced by InvaildateVariableName(), and PrintVariable().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/behavioral_helper.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/behavioral_helper.cpp