weak_dominance Class Reference
Class used to compute weak dominance.
#include <weak_dominance.hpp>
Public Member Functions
weak_dominance (const graph *_input, vertex _start, vertex _end, const ParameterConstRef param, int selector=WD_SELECTOR)
Constructor.
~weak_dominance ()=default
Destructor.
void calculate_weak_dominance_info (graphs_collection *output, CustomUnorderedMap< vertex, vertex > &i2o, CustomUnorderedMap< vertex, vertex > &o2i)
Compute weak dominance info.
Private Member Functions
void add_edge (vertex source, vertex target, graphs_collection *output)
Add a weak dominance edge between two nodes.
Private Attributes
const graph * input
the input graph (not const since node info are copied in the new graph
vertex start
the entry vertex
vertex end
the exit vertex
const int selector
the selector used in output graph
const ParameterConstRef param
The set of input parameters.
const int debug_level
the debug level
Detailed Description
Class used to compute weak dominance.
Definition at line 58 of file weak_dominance.hpp.
Constructor & Destructor Documentation
weak_dominance()
weak_dominance::weak_dominance (const graph * _input, vertex _start, vertex _end, const ParameterConstRef param, int selector = WD_SELECTOR)
Constructor.
Parameters
_input is the input graph
_start is the start vertex
_end is the end vertex
_param is the set of input parameters
_selector is the selctor of edges to be added
Definition at line 106 of file weak_dominance.cpp.
 weak_dominance()
weak_dominance::~weak_dominance () [default]
Destructor.
Member Function Documentation
add_edge()
void weak_dominance::add_edge (vertex source, vertex target, graphs_collection * output) [private]
Add a weak dominance edge between two nodes.
Parameters
source is the source vertex
target is the target vertex
output is the graph
Definition at line 111 of file weak_dominance.cpp.
References graphs_collection::AddSelector(), graphs_collection::ExistsEdge(), graphs_collection::InternalAddEdge(), and selector.
Referenced by calculate_weak_dominance_info().
calculate_weak_dominance_info()
void weak_dominance::calculate_weak_dominance_info (graphs_collection * output, CustomUnorderedMap< vertex, vertex > & i2o, CustomUnorderedMap< vertex, vertex > & o2i)
Compute weak dominance info.
Header include.
Parameters
output is the graph on which weak dominance edges have to be added;
i2o is the map from input vertex to output vertex
o2i is the map from output vertex to input vertex
Definition at line 57 of file weak_dominance.cpp.
References A, add_edge(), graphs_collection::AddVertex(), dominance< GraphObj >::calculate_dominance_info(), counter, end, dominance< GraphObj >::get_dominator_map(), input, test_panda::level, param, start, and THROW_ASSERT.
Field Documentation
debug_level
const int weak_dominance::debug_level [private]
the debug level
Definition at line 77 of file weak_dominance.hpp.
end
vertex weak_dominance::end [private]
the exit vertex
Definition at line 68 of file weak_dominance.hpp.
Referenced by calculate_weak_dominance_info().
input
const graph* weak_dominance::input [private]
the input graph (not const since node info are copied in the new graph
Definition at line 62 of file weak_dominance.hpp.
Referenced by calculate_weak_dominance_info().
param
const ParameterConstRef weak_dominance::param [private]
The set of input parameters.
Definition at line 74 of file weak_dominance.hpp.
Referenced by calculate_weak_dominance_info().
selector
const int weak_dominance::selector [private]
the selector used in output graph
Definition at line 71 of file weak_dominance.hpp.
Referenced by add_edge().
start
vertex weak_dominance::start [private]
the entry vertex
Definition at line 65 of file weak_dominance.hpp.
Referenced by calculate_weak_dominance_info().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/algorithms/dominance/weak_dominance.hpp
/home/osboxes/bambu/PandA-bambu/src/algorithms/dominance/weak_dominance.cpp