lut_transformation Class Reference
#include <lut_transformation.hpp>
Public Member Functions
lut_transformation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~lut_transformation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes the operations CFG graph data structure.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
tree_managerRef TM
The tree manager.
tree_manipulationRef tree_man
The lut manipulation.
size_t max_lut_size
The maximum number of inputs of a lut.
Additional Inherited Members
Detailed Description
Definition at line 72 of file lut_transformation.hpp.
Constructor & Destructor Documentation
lut_transformation()
lut_transformation::lut_transformation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Definition at line 1575 of file lut_transformation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, and GET_CLASS.
 lut_transformation()
lut_transformation::~lut_transformation () [override], [default]
Destructor.
Autoheader include.
. include behavior includes constants include design_flows includes design_flows/technology includes HLS includes STD include tree includes technology/physical_library include utility include tree includes
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > lut_transformation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 1608 of file lut_transformation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SUCCESS, and THROW_UNREACHABLE.
ComputeRelationships()
void lut_transformation::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 1548 of file lut_transformation.cpp.
References FunctionFrontendFlowStep::ComputeRelationships(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
HasToBeExecuted()
bool lut_transformation::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 1641 of file lut_transformation.cpp.
References FunctionFrontendFlowStep::HasToBeExecuted(), and DesignFlowStep::parameters.
Initialize()
void lut_transformation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 1538 of file lut_transformation.cpp.
References FrontendFlowStep::AppM, max_lut_size, DesignFlowStep::parameters, THROW_ASSERT, TM, and tree_man.
InternalExec()
DesignFlowStep_Status lut_transformation::InternalExec () [override], [virtual]
Computes the operations CFG graph data structure.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 1581 of file lut_transformation.cpp.
References FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), sl, SUCCESS, THROW_ASSERT, TM, and UNCHANGED.
Field Documentation
max_lut_size
size_t lut_transformation::max_lut_size [private]
The maximum number of inputs of a lut.
Definition at line 82 of file lut_transformation.hpp.
Referenced by Initialize().
TM
tree_managerRef lut_transformation::TM [private]
The tree manager.
Definition at line 76 of file lut_transformation.hpp.
Referenced by Initialize(), and InternalExec().
tree_man
tree_manipulationRef lut_transformation::tree_man [private]
The lut manipulation.
Definition at line 79 of file lut_transformation.hpp.
Referenced by Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/lut_transformation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/lut_transformation.cpp