QuartusPowerWrapper Class Reference
Main class for wrapping quartus_pow tool by Altera.
#include <quartus_power_wrapper.hpp>
Public Member Functions
QuartusPowerWrapper (const ParameterConstRef Param, const std::string &_output_dir, const target_deviceRef _device)
Constructor.
~QuartusPowerWrapper () override
Destructor.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
void generate_synthesis_script (const DesignParametersRef &dp, const std::string &file_name) override
Creates the proper configuration script.
Protected Member Functions
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
Additional Inherited Members
Detailed Description
Main class for wrapping quartus_pow tool by Altera.
Definition at line 49 of file quartus_power_wrapper.hpp.
Constructor & Destructor Documentation
QuartusPowerWrapper()
QuartusPowerWrapper::QuartusPowerWrapper (const ParameterConstRef _Param, const std::string & _output_dir, const target_deviceRef _device)
Constructor.
Parameters
Param is the set of parameters
Author
Pietro Fezzardi pietrofezzardi@gmail.comHeader include
Definition at line 48 of file quartus_power_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, and PRINT_DBG_MEX.
 QuartusPowerWrapper()
QuartusPowerWrapper::~QuartusPowerWrapper () [override]
Destructor.
Definition at line 54 of file quartus_power_wrapper.cpp.
Member Function Documentation
EvaluateVariables()
void QuartusPowerWrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 58 of file quartus_power_wrapper.cpp.
References DesignParameters::component_name, SynthesisTool::output_dir, PARAM_quartus_report, and DesignParameters::parameter_values.
generate_synthesis_script()
void QuartusPowerWrapper::generate_synthesis_script (const DesignParametersRef & dp, const std::string & file_name) [override], [virtual]
Creates the proper configuration script.
replace some of the escape sequences
Reimplemented from AlteraWrapper.
Definition at line 82 of file quartus_power_wrapper.cpp.
References DesignParameters::assign(), SynthesisTool::generate_bare_script(), AlteraWrapper::getStringValue(), remove_escaped(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, SynthesisTool::xml_reserved_vars, and SynthesisTool::xml_script_nodes.
get_command_line()
std::string QuartusPowerWrapper::get_command_line (const DesignParametersRef & dp) const [override], [virtual]
Returns the proper command line.
Implements AlteraWrapper.
Definition at line 64 of file quartus_power_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, AlteraWrapper::toString(), and SynthesisTool::xml_tool_options.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_power_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_power_wrapper.cpp