SynthesisTool Class Reference
#include <SynthesisTool.hpp>
Public Types
enum type_t {
UNKNOWN = 0,
DESIGN_COMPILER,
XST,
NGDBUILD,
MAP,
PAR,
TRCE,
VIVADO_FLOW,
QUARTUS_13_FLOW,
QUARTUS_13_SETUP,
QUARTUS_13_STA,
QUARTUS_SETUP,
QUARTUS_FLOW,
QUARTUS_POW,
QUARTUS_STA,
LATTICE_FLOW,
NXPYTHON_FLOW
 }
supported synthesis tools
Public Member Functions
SynthesisTool (const ParameterConstRef &Param, std::string tool_exec, const target_deviceRef &device, const std::string &output_dir, std::string default_output_dir)
Constructor.
virtual ~SynthesisTool ()
Destructor.
virtual void CheckExecution ()
Check if the tool can be really executed; i.e., it has been properly configured.
virtual void EvaluateVariables (const DesignParametersRef dp)
Evaluates the design variables.
virtual void generate_synthesis_script (const DesignParametersRef &dp, const std::string &file_name)=0
Creates the proper configuration script.
virtual std::string get_command_line (const DesignParametersRef &dp) const =0
virtual std::string toString (const xml_script_node_tRef node, const DesignParametersRef dp) const =0
Returns the string-based representation of the XML element.
virtual std::string getStringValue (const xml_script_node_tRef node, const DesignParametersRef &dp) const =0
Returns the string-based representation of the XML element.
std::string get_output_directory () const
Returns the path of the output directory.
std::string generate_bare_script (const std::vector< xml_script_node_tRef > &nodes, const DesignParametersRef &dp)
xml_set_variable_tRef get_reserved_parameter (const std::string &name)
Gets a reserved (tool) parameter by name.
void replace_parameters (const DesignParametersRef &dp, std::string &script) const
Replaces occurrences of parameters inside a script.
void xload_scripts (const xml_element *child)
Actual parsing of parameters and script nodes.
void xload (const xml_element *node, const std::string &tool_config)
Method parsing the configuration file directly from an XML node.
xml_nodeRef xwrite () const
Method writing the configuration file.
bool has_scripts () const
Checks if there is a configuration script loaded.
virtual std::string get_tool_exec () const
Returns the name of the tool executable.
Static Public Member Functions
static SynthesisToolRef create_synthesis_tool (type_t type, const ParameterConstRef &Param, const std::string &output_dir, const target_deviceRef &device)
Factory method.
Protected Member Functions
void create_output_directory (const std::string &sub_dir)
Creates the directory to store the output files.
virtual void init_reserved_vars ()
Initializes the reserved variables.
Protected Attributes
const target_deviceRef device
class containing information about the target device
const ParameterConstRef Param
class containing all the parameters
int debug_level
debug level of the class
unsigned int output_level
verbosity level of the class
ToolManagerRef tool
utility class to manage the executable
const std::string tool_exec
name of the tool executable
std::string output_dir
the output directory
std::string script_name
name of the script
std::map< unsigned int, std::string > script_map
map between the identifier of the script and the corresponding stream
std::vector< xml_parameter_tRef > xml_tool_options
std::vector< xml_script_node_tRef > xml_script_nodes
std::vector< xml_set_variable_tRef > xml_reserved_vars
Detailed Description
Definition at line 86 of file SynthesisTool.hpp.
Member Enumeration Documentation
type_t
enum SynthesisTool::type_t
supported synthesis tools
Enumerator
UNKNOWN
DESIGN_COMPILER
XST
NGDBUILD
MAP
PAR
TRCE
VIVADO_FLOW
QUARTUS_13_FLOW
QUARTUS_13_SETUP
QUARTUS_13_STA
QUARTUS_SETUP
QUARTUS_FLOW
QUARTUS_POW
QUARTUS_STA
LATTICE_FLOW
NXPYTHON_FLOW
Definition at line 90 of file SynthesisTool.hpp.
Constructor & Destructor Documentation
SynthesisTool()
SynthesisTool::SynthesisTool (const ParameterConstRef & _Param, std::string _tool_exec, const target_deviceRef & _device, const std::string & _flow_name, std::string _output_dir)
Constructor.
Autoheader include.
supported synthesis tools creating the output directory
Definition at line 91 of file SynthesisTool.cpp.
References create_output_directory(), init_reserved_vars(), and ~SynthesisTool().
 SynthesisTool()
SynthesisTool::~SynthesisTool () [virtual], [default]
Destructor.
Referenced by SynthesisTool().
Member Function Documentation
CheckExecution()
void SynthesisTool::CheckExecution () [virtual]
Check if the tool can be really executed; i.e., it has been properly configured.
Definition at line 202 of file SynthesisTool.cpp.
create_output_directory()
void SynthesisTool::create_output_directory (const std::string & sub_dir) [protected]
Creates the directory to store the output files.
Definition at line 215 of file SynthesisTool.cpp.
References output_dir, and Param.
Referenced by SynthesisTool().
create_synthesis_tool()
SynthesisToolRef SynthesisTool::create_synthesis_tool (type_t type, const ParameterConstRef & Param, const std::string & output_dir, const target_deviceRef & device) [static]
Factory method.
this point should never be reached
Definition at line 107 of file SynthesisTool.cpp.
References DESIGN_COMPILER, LATTICE_FLOW, MAP, NGDBUILD, NXPYTHON_FLOW, PAR, QUARTUS_13_FLOW, QUARTUS_13_SETUP, QUARTUS_13_STA, QUARTUS_FLOW, QUARTUS_POW, QUARTUS_SETUP, QUARTUS_STA, THROW_ERROR, TRCE, UNKNOWN, VIVADO_FLOW, and XST.
Referenced by BackendFlow::create_xml_scripts(), and BackendFlow::xload().
EvaluateVariables()
void SynthesisTool::EvaluateVariables (const DesignParametersRef dp) [virtual]
Evaluates the design variables.
Reimplemented in DesignCompilerWrapper, xst_wrapper, trce_wrapper, map_wrapper, ngdbuild_wrapper, par_wrapper, vivado_flow_wrapper, QuartusReportWrapper, lattice_flow_wrapper, Quartus13ReportWrapper, nxpython_flow_wrapper, and QuartusPowerWrapper.
Definition at line 360 of file SynthesisTool.cpp.
generate_bare_script()
std::string SynthesisTool::generate_bare_script (const std::vector< xml_script_node_tRef > & nodes, const DesignParametersRef & dp)
Returns
The bare script without any special string replacement
Definition at line 320 of file SynthesisTool.cpp.
References NODE_ITE_BLOCK, and toString().
Referenced by NanoXploreWrapper::generate_synthesis_script(), AlteraWrapper::generate_synthesis_script(), LatticeWrapper::generate_synthesis_script(), QuartusPowerWrapper::generate_synthesis_script(), SynopsysWrapper::generate_synthesis_script(), and XilinxWrapper::generate_synthesis_script().
generate_synthesis_script()
virtual void SynthesisTool::generate_synthesis_script (const DesignParametersRef & dp, const std::string & file_name) [pure virtual]
Creates the proper configuration script.
Implemented in XilinxWrapper, SynopsysWrapper, QuartusPowerWrapper, AlteraWrapper, LatticeWrapper, and NanoXploreWrapper.
get_command_line()
virtual std::string SynthesisTool::get_command_line (const DesignParametersRef & dp) const [pure virtual]
Returns
The tool command line
Implemented in xst_wrapper, AlteraWrapper, LatticeWrapper, SynopsysWrapper, NanoXploreWrapper, QuartusReportWrapper, Quartus13ReportWrapper, trce_wrapper, map_wrapper, ngdbuild_wrapper, par_wrapper, QuartusPowerWrapper, QuartusWrapper, Quartus13Wrapper, vivado_flow_wrapper, and nxpython_flow_wrapper.
get_output_directory()
std::string SynthesisTool::get_output_directory () const
Returns the path of the output directory.
Definition at line 210 of file SynthesisTool.cpp.
References output_dir.
get_reserved_parameter()
xml_set_variable_tRef SynthesisTool::get_reserved_parameter (const std::string & name)
Gets a reserved (tool) parameter by name.
Parameters
name Parameter name.
Returns
Reserved parameter reference.
Definition at line 334 of file SynthesisTool.cpp.
References THROW_ERROR, and xml_reserved_vars.
Referenced by DesignCompilerWrapper::EvaluateVariables(), DesignCompilerWrapper::import_input_design(), DesignCompilerWrapper::perform_optimization(), DesignCompilerWrapper::save_design(), DesignCompilerWrapper::set_constraints(), DesignCompilerWrapper::set_link_libraries(), DesignCompilerWrapper::set_search_path(), and DesignCompilerWrapper::set_target_libraries().
get_tool_exec()
std::string SynthesisTool::get_tool_exec () const [virtual]
Returns the name of the tool executable.
Definition at line 364 of file SynthesisTool.cpp.
References tool_exec.
Referenced by nxpython_flow_wrapper::get_command_line(), vivado_flow_wrapper::get_command_line(), Quartus13Wrapper::get_command_line(), QuartusWrapper::get_command_line(), QuartusPowerWrapper::get_command_line(), par_wrapper::get_command_line(), ngdbuild_wrapper::get_command_line(), map_wrapper::get_command_line(), trce_wrapper::get_command_line(), Quartus13ReportWrapper::get_command_line(), QuartusReportWrapper::get_command_line(), SynopsysWrapper::get_command_line(), LatticeWrapper::get_command_line(), xst_wrapper::get_command_line(), xload(), and xwrite().
getStringValue()
virtual std::string SynthesisTool::getStringValue (const xml_script_node_tRef node, const DesignParametersRef & dp) const [pure virtual]
Returns the string-based representation of the XML element.
Implemented in XilinxWrapper, SynopsysWrapper, AlteraWrapper, LatticeWrapper, and NanoXploreWrapper.
has_scripts()
bool SynthesisTool::has_scripts () const
Checks if there is a configuration script loaded.
Definition at line 102 of file SynthesisTool.cpp.
References script_map, and xml_script_nodes.
init_reserved_vars()
void SynthesisTool::init_reserved_vars () [protected], [virtual]
Initializes the reserved variables.
Reimplemented in DesignCompilerWrapper, xst_wrapper, trce_wrapper, map_wrapper, ngdbuild_wrapper, and par_wrapper.
Definition at line 206 of file SynthesisTool.cpp.
Referenced by ngdbuild_wrapper::init_reserved_vars(), par_wrapper::init_reserved_vars(), map_wrapper::init_reserved_vars(), trce_wrapper::init_reserved_vars(), xst_wrapper::init_reserved_vars(), DesignCompilerWrapper::init_reserved_vars(), and SynthesisTool().
replace_parameters()
void SynthesisTool::replace_parameters (const DesignParametersRef & dp, std::string & script) const
Replaces occurrences of parameters inside a script.
Parameters
dp Design parameters.
script Script whose parameters have to be replaced.
Definition at line 348 of file SynthesisTool.cpp.
References DesignParameters::parameter_values.
Referenced by DesignCompilerWrapper::EvaluateVariables(), NanoXploreWrapper::generate_synthesis_script(), AlteraWrapper::generate_synthesis_script(), LatticeWrapper::generate_synthesis_script(), QuartusPowerWrapper::generate_synthesis_script(), SynopsysWrapper::generate_synthesis_script(), XilinxWrapper::generate_synthesis_script(), nxpython_flow_wrapper::get_command_line(), vivado_flow_wrapper::get_command_line(), Quartus13Wrapper::get_command_line(), QuartusWrapper::get_command_line(), QuartusPowerWrapper::get_command_line(), par_wrapper::get_command_line(), ngdbuild_wrapper::get_command_line(), map_wrapper::get_command_line(), trce_wrapper::get_command_line(), Quartus13ReportWrapper::get_command_line(), QuartusReportWrapper::get_command_line(), LatticeWrapper::get_command_line(), and xst_wrapper::get_command_line().
toString()
virtual std::string SynthesisTool::toString (const xml_script_node_tRef node, const DesignParametersRef dp) const [pure virtual]
Returns the string-based representation of the XML element.
Implemented in XilinxWrapper, SynopsysWrapper, AlteraWrapper, LatticeWrapper, and NanoXploreWrapper.
Referenced by generate_bare_script().
xload()
void SynthesisTool::xload (const xml_element * node, const std::string & tool_config)
Method parsing the configuration file directly from an XML node.
Definition at line 271 of file SynthesisTool.cpp.
References CE_XVM, xml_child::get_children(), xml_node::get_name(), get_tool_exec(), LOAD_XVM, THROW_ERROR, and xload_scripts().
xload_scripts()
void SynthesisTool::xload_scripts (const xml_element * child)
Actual parsing of parameters and script nodes.
Definition at line 239 of file SynthesisTool.cpp.
References xml_script_node_t::create(), xml_script_node_t::find_type(), xml_child::get_children(), test_panda::lines, NODE_PARAMETER, THROW_ERROR, xml_script_nodes, and xml_tool_options.
Referenced by xload().
xwrite()
xml_nodeRef SynthesisTool::xwrite () const
Method writing the configuration file.
Definition at line 306 of file SynthesisTool.cpp.
References get_tool_exec(), xml_script_nodes, and xml_tool_options.
Field Documentation
debug_level
int SynthesisTool::debug_level [protected]
debug level of the class
Definition at line 128 of file SynthesisTool.hpp.
Referenced by DesignCompilerWrapper::DesignCompilerWrapper(), xst_wrapper::GenerateProjectFile(), lattice_flow_wrapper::lattice_flow_wrapper(), map_wrapper::map_wrapper(), ngdbuild_wrapper::ngdbuild_wrapper(), nxpython_flow_wrapper::nxpython_flow_wrapper(), par_wrapper::par_wrapper(), DesignCompilerWrapper::parse_area_reports(), DesignCompilerWrapper::parse_cell_reports(), DesignCompilerWrapper::parse_synthesis_reports(), DesignCompilerWrapper::parse_time_reports(), Quartus13ReportWrapper::Quartus13ReportWrapper(), QuartusPowerWrapper::QuartusPowerWrapper(), QuartusReportWrapper::QuartusReportWrapper(), trce_wrapper::trce_wrapper(), vivado_flow_wrapper::vivado_flow_wrapper(), and xst_wrapper::xst_wrapper().
device
const target_deviceRef SynthesisTool::device [protected]
class containing information about the target device
Definition at line 122 of file SynthesisTool.hpp.
Referenced by DesignCompilerWrapper::parse_area_reports(), DesignCompilerWrapper::parse_time_reports(), and DesignCompilerWrapper::set_target_libraries().
output_dir
std::string SynthesisTool::output_dir [protected]
the output directory
Definition at line 140 of file SynthesisTool.hpp.
Referenced by create_output_directory(), vivado_flow_wrapper::create_sdc(), QuartusPowerWrapper::EvaluateVariables(), nxpython_flow_wrapper::EvaluateVariables(), Quartus13ReportWrapper::EvaluateVariables(), lattice_flow_wrapper::EvaluateVariables(), QuartusReportWrapper::EvaluateVariables(), vivado_flow_wrapper::EvaluateVariables(), ngdbuild_wrapper::EvaluateVariables(), par_wrapper::EvaluateVariables(), map_wrapper::EvaluateVariables(), trce_wrapper::EvaluateVariables(), xst_wrapper::EvaluateVariables(), get_output_directory(), DesignCompilerWrapper::import_input_design(), and DesignCompilerWrapper::save_design().
output_level
unsigned int SynthesisTool::output_level [protected]
verbosity level of the class
Definition at line 131 of file SynthesisTool.hpp.
Referenced by ngdbuild_wrapper::get_command_line(), DesignCompilerWrapper::parse_area_reports(), DesignCompilerWrapper::parse_cell_reports(), DesignCompilerWrapper::parse_reports(), DesignCompilerWrapper::parse_synthesis_reports(), DesignCompilerWrapper::parse_time_reports(), and DesignCompilerWrapper::perform_optimization().
Param
const ParameterConstRef SynthesisTool::Param [protected]
class containing all the parameters
Definition at line 125 of file SynthesisTool.hpp.
Referenced by create_output_directory(), vivado_flow_wrapper::create_sdc(), DesignCompilerWrapper::DesignCompilerWrapper(), DesignCompilerWrapper::parse_area_reports(), DesignCompilerWrapper::parse_time_reports(), DesignCompilerWrapper::perform_optimization(), DesignCompilerWrapper::set_constraints(), and DesignCompilerWrapper::write_reports().
script_map
std::map<unsigned int, std::string> SynthesisTool::script_map [protected]
map between the identifier of the script and the corresponding stream
Definition at line 146 of file SynthesisTool.hpp.
Referenced by has_scripts().
script_name
std::string SynthesisTool::script_name [protected]
name of the script
Definition at line 143 of file SynthesisTool.hpp.
Referenced by NanoXploreWrapper::generate_synthesis_script(), AlteraWrapper::generate_synthesis_script(), LatticeWrapper::generate_synthesis_script(), QuartusPowerWrapper::generate_synthesis_script(), SynopsysWrapper::generate_synthesis_script(), XilinxWrapper::generate_synthesis_script(), nxpython_flow_wrapper::get_command_line(), vivado_flow_wrapper::get_command_line(), Quartus13Wrapper::get_command_line(), QuartusWrapper::get_command_line(), QuartusPowerWrapper::get_command_line(), Quartus13ReportWrapper::get_command_line(), QuartusReportWrapper::get_command_line(), SynopsysWrapper::get_command_line(), and LatticeWrapper::get_command_line().
tool
ToolManagerRef SynthesisTool::tool [protected]
utility class to manage the executable
Definition at line 134 of file SynthesisTool.hpp.
Referenced by DesignCompilerWrapper::set_constraints().
tool_exec
const std::string SynthesisTool::tool_exec [protected]
name of the tool executable
Definition at line 137 of file SynthesisTool.hpp.
Referenced by get_tool_exec().
xml_reserved_vars
std::vector<xml_set_variable_tRef> SynthesisTool::xml_reserved_vars [protected]
Definition at line 156 of file SynthesisTool.hpp.
Referenced by NanoXploreWrapper::generate_synthesis_script(), AlteraWrapper::generate_synthesis_script(), LatticeWrapper::generate_synthesis_script(), QuartusPowerWrapper::generate_synthesis_script(), SynopsysWrapper::generate_synthesis_script(), XilinxWrapper::generate_synthesis_script(), and get_reserved_parameter().
xml_script_nodes
std::vector<xml_script_node_tRef> SynthesisTool::xml_script_nodes [protected]
Definition at line 155 of file SynthesisTool.hpp.
Referenced by DesignCompilerWrapper::EvaluateVariables(), NanoXploreWrapper::generate_synthesis_script(), AlteraWrapper::generate_synthesis_script(), LatticeWrapper::generate_synthesis_script(), QuartusPowerWrapper::generate_synthesis_script(), SynopsysWrapper::generate_synthesis_script(), XilinxWrapper::generate_synthesis_script(), has_scripts(), xload_scripts(), and xwrite().
xml_tool_options
std::vector<xml_parameter_tRef> SynthesisTool::xml_tool_options [protected]
Definition at line 154 of file SynthesisTool.hpp.
Referenced by nxpython_flow_wrapper::get_command_line(), vivado_flow_wrapper::get_command_line(), Quartus13Wrapper::get_command_line(), QuartusWrapper::get_command_line(), QuartusPowerWrapper::get_command_line(), par_wrapper::get_command_line(), ngdbuild_wrapper::get_command_line(), map_wrapper::get_command_line(), trce_wrapper::get_command_line(), Quartus13ReportWrapper::get_command_line(), QuartusReportWrapper::get_command_line(), SynopsysWrapper::get_command_line(), LatticeWrapper::get_command_line(), xst_wrapper::get_command_line(), xload_scripts(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/SynthesisTool.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/SynthesisTool.cpp