fixed_scheduling Class Reference
#include <fixed_scheduling.hpp>
Public Member Functions
fixed_scheduling (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~fixed_scheduling () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Additional Inherited Members
Detailed Description
Definition at line 48 of file fixed_scheduling.hpp.
Constructor & Destructor Documentation
fixed_scheduling()
fixed_scheduling::fixed_scheduling (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
design_flow_manager is the design flow manager
Definition at line 65 of file fixed_scheduling.cpp.
References FIXED_SCHEDULING, and ~fixed_scheduling().
 fixed_scheduling()
fixed_scheduling::~fixed_scheduling () [override], [default]
Destructor.
Referenced by fixed_scheduling().
Member Function Documentation
InternalExec()
DesignFlowStep_Status fixed_scheduling::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 72 of file fixed_scheduling.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, XMLDomParser::Exec(), FunctionBehavior::FDFG, HLSFunctionStep::funId, XMLDomParser::get_document(), HLSFunctionStep::HLS, HLS_step::HLSMgr, DesignFlowStep::parameters, test_panda::parser, PRINT_DBG_MEX, SUCCESS, THROW_ERROR, and hls::xload().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/fixed_scheduling.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/fixed_scheduling.cpp