/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/TopEntityMemoryMapped.cpp File Reference
#include `TopEntityMemoryMapped.hpp`
#include `Parameter.hpp`
#include `call_graph_manager.hpp`
#include `structural_manager.hpp`
#include `structural_objects.hpp`
#include `hls.hpp`
#include `hls_manager.hpp`
#include `hls_target.hpp`
#include `fu_binding.hpp`
#include `functions.hpp`
#include `memory.hpp`
#include `memory_allocation.hpp`
#include `memory_cs.hpp`
#include `memory_symbol.hpp`
#include `custom_map.hpp`
#include `technology_manager.hpp`
#include `technology_node.hpp`
#include `behavioral_helper.hpp`
#include `tree_helper.hpp`
#include `copyrights_strings.hpp`
#include `dbgPrintHelper.hpp`
#include `string_manipulation.hpp`
Functions
static void propagateInterface (structural_managerRef SM, structural_objectRef wrappedObj, std::list< std::string > &ParametersName)
static void connect_with_signal_name (structural_managerRef SM, structural_objectRef portA, structural_objectRef portB, std::string signalName)
static void connectClockAndReset (structural_managerRef SM, structural_objectRef interfaceObj, structural_objectRef component)
static void setBusSizes (structural_objectRef component, const HLS_managerRef HLSMgr)
Function Documentation
connect_with_signal_name()
static void connect_with_signal_name (structural_managerRef SM, structural_objectRef portA, structural_objectRef portB, std::string signalName) [static]
Definition at line 489 of file TopEntityMemoryMapped.cpp.
References structural_object::get_typeRef().
Referenced by TopEntityMemoryMapped::allocate_parameters(), TopEntityMemoryMapped::insertMemoryMappedRegister(), and TopEntityMemoryMapped::insertStartDoneLogic().
connectClockAndReset()
static void connectClockAndReset (structural_managerRef SM, structural_objectRef interfaceObj, structural_objectRef component) [static]
Definition at line 517 of file TopEntityMemoryMapped.cpp.
References CLOCK_PORT_NAME, structural_object::find_member(), port_o_K, reset(), and RESET_PORT_NAME.
Referenced by TopEntityMemoryMapped::allocate_parameters(), TopEntityMemoryMapped::insertMemoryMappedRegister(), TopEntityMemoryMapped::insertStartDoneLogic(), TopEntityMemoryMapped::insertStatusRegister(), and propagateInterface().
propagateInterface()
static void propagateInterface (structural_managerRef SM, structural_objectRef wrappedObj, std::list< std::string > & ParametersName) [static]
Definition at line 468 of file TopEntityMemoryMapped.cpp.
References CLOCK_PORT_NAME, connectClockAndReset(), DONE_PORT_NAME, structural_object::get_id(), structural_object::get_typeRef(), RESET_PORT_NAME, RETURN_PORT_NAME, START_PORT_NAME, and THROW_ASSERT.
Referenced by TopEntityMemoryMapped::InternalExec(), and TopEntityMemoryMapped::resizing_IO().
setBusSizes()
static void setBusSizes (structural_objectRef component, const HLS_managerRef HLSMgr) [static]
Definition at line 529 of file TopEntityMemoryMapped.cpp.
References structural_object::type_resize().
Referenced by TopEntityMemoryMapped::allocate_parameters(), TopEntityMemoryMapped::insertMemoryMappedRegister(), TopEntityMemoryMapped::insertStartDoneLogic(), and TopEntityMemoryMapped::insertStatusRegister().