NonDeterministicFlows Class Reference
Class to test non deterministic flows.
#include <non_deterministic_flows.hpp>
Public Member Functions
NonDeterministicFlows (const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~NonDeterministicFlows () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the flow.
Private Member Functions
const std::string ComputeArgString (const size_t seed) const
Compute the arg list string of the tool.
bool ExecuteTool (const size_t seed) const
Execute tool with non deterministic flow.
Additional Inherited Members
Detailed Description
Class to test non deterministic flows.
Definition at line 51 of file non_deterministic_flows.hpp.
Constructor & Destructor Documentation
NonDeterministicFlows()
NonDeterministicFlows::NonDeterministicFlows (const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
design_flow_manager is the design flow manager
parameters is the set of the parameters
Definition at line 96 of file non_deterministic_flows.cpp.
References ~NonDeterministicFlows().
 NonDeterministicFlows()
NonDeterministicFlows::~NonDeterministicFlows () [override], [default]
Destructor.
Referenced by NonDeterministicFlows().
Member Function Documentation
ComputeArgString()
const std::string NonDeterministicFlows::ComputeArgString (const size_t seed) const [private]
Compute the arg list string of the tool.
Parameters
seed is the seed to be passed
Returns
the argument string
Executable
Definition at line 49 of file non_deterministic_flows.cpp.
References test_panda::arg, DesignFlowStep::parameters, STR, and THROW_ASSERT.
Referenced by ExecuteTool().
Exec()
DesignFlowStep_Status NonDeterministicFlows::Exec () [override], [virtual]
Execute the flow.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 102 of file non_deterministic_flows.cpp.
References ABORTED, ExecuteTool(), DesignFlowStep::parameters, and SUCCESS.
ExecuteTool()
bool NonDeterministicFlows::ExecuteTool (const size_t seed) const [private]
Execute tool with non deterministic flow.
Parameters
seed is the seed to be passed
Returns
true if the execution was successful, false otherwise
Definition at line 74 of file non_deterministic_flows.cpp.
References ComputeArgString(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, IsError(), PandaSystem(), DesignFlowStep::parameters, and STR.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/non_deterministic_flows.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/non_deterministic_flows.cpp