reg_binding_cs Class Reference
#include <reg_binding_cs.hpp>
Public Member Functions
reg_binding_cs (const hlsRef &HLS, const HLS_managerRef HLSMgr_)
Constructor.
virtual ~reg_binding_cs ()
Destructor.
Protected Member Functions
std::string CalculateRegisterName (unsigned int i)
CalculateRegisterName.
void specialise_reg (structural_objectRef &reg, unsigned int r)
specialise_reg add dimension selector
Additional Inherited Members
Detailed Description
Definition at line 46 of file reg_binding_cs.hpp.
Constructor & Destructor Documentation
reg_binding_cs()
reg_binding_cs::reg_binding_cs (const hlsRef & HLS, const HLS_managerRef HLSMgr_)
Constructor.
STD include.
Definition at line 53 of file reg_binding_cs.cpp.
 reg_binding_cs()
reg_binding_cs::~reg_binding_cs () [virtual]
Destructor.
Definition at line 57 of file reg_binding_cs.cpp.
Member Function Documentation
CalculateRegisterName()
std::string reg_binding_cs::CalculateRegisterName (unsigned int i) [protected], [virtual]
CalculateRegisterName.
Parameters
i
Returns
Reimplemented from reg_binding.
Definition at line 61 of file reg_binding_cs.cpp.
specialise_reg()
void reg_binding_cs::specialise_reg (structural_objectRef & reg, unsigned int r) [protected], [virtual]
specialise_reg add dimension selector
Parameters
reg
r
Reimplemented from reg_binding.
Definition at line 66 of file reg_binding_cs.cpp.
References ceil_log2(), structural_object::find_member(), get_id(), reg_binding::HLS, hls::Param, port_o_K, SELECTOR_REGISTER_FILE, reg_binding::specialise_reg(), STR, and structural_object::type_resize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/reg_binding_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/reg_binding_cs.cpp