variable2obj< data_obj > Struct Template Reference
Class managing map of the storage values on a generic object.
#include <Variable.hpp>
Public Member Functions
variable2obj ()=default
Constructor.
virtual ~variable2obj ()
Destructor.
virtual void print_el (typename variable2obj< data_obj >::const_iterator &it) const =0
Function that print the information associated with a variable.
virtual void print () const
Function that prints the class variable2obj.
const data_obj operator() (const unsigned int &__k) const
template<class Iterator >
void resize (Iterator left, Iterator right, int val)
Friends
std::ostream & operator<< (std::ostream &os, variable2obj &s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const variable2obj *s)
Friend definition of the << operator.
Detailed Description
template<class data_obj>
struct variable2obj< data_obj >
Class managing map of the storage values on a generic object.
Definition at line 60 of file Variable.hpp.
Constructor & Destructor Documentation
variable2obj()
template<class data_obj>
variable2obj< data_obj >::variable2obj () [default]
Constructor.
 variable2obj()
template<class data_obj>
virtual variable2obj< data_obj >::~variable2obj () [inline], [virtual]
Destructor.
Definition at line 70 of file Variable.hpp.
Member Function Documentation
operator()()
template<class data_obj>
const data_obj variable2obj< data_obj >::operator() (const unsigned int & __k) const [inline]
Definition at line 93 of file Variable.hpp.
print()
template<class data_obj>
virtual void variable2obj< data_obj >::print () const [inline], [virtual]
Function that prints the class variable2obj.
Parameters
os is the output stream
Definition at line 84 of file Variable.hpp.
Referenced by vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), chordal_coloring_register::InternalExec(), and weighted_clique_register::InternalExec().
print_el()
template<class data_obj>
virtual void variable2obj< data_obj >::print_el (typename variable2obj< data_obj >::const_iterator & it) const [pure virtual]
Function that print the information associated with a variable.
Parameters
os is the output stream
Referenced by variable2obj< generic_objRef >::print(), and variable2obj< generic_objRef >::~variable2obj().
resize()
template<class data_obj>
template<class Iterator >
void variable2obj< data_obj >::resize (Iterator left, Iterator right, int val) [inline]
Definition at line 100 of file Variable.hpp.
Friends And Related Function Documentation
operator<< [1/2]
template<class data_obj>
std::ostream& operator<< (std::ostream & os, variable2obj< data_obj > & s) [friend]
Friend definition of the << operator.
Parameters
os is the output stream
Definition at line 110 of file Variable.hpp.
operator<< [2/2]
template<class data_obj>
std::ostream& operator<< (std::ostream & os, const variable2obj< data_obj > * s) [friend]
Friend definition of the << operator.
Pointer version.
Parameters
os is the output stream
Definition at line 120 of file Variable.hpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/Variable.hpp