port_o Struct Reference
This class describes a port associated with a component or a channel.
#include <structural_objects.hpp>
Public Types
enum port_direction {
IN = 0,
OUT,
IO,
GEN,
UNKNOWN,
TLM_IN,
TLM_OUT,
TLM_INOUT
 }
Enumerative type describing the direction of a port.
enum port_endianess { LITTLE = 0,
BIG,
NONE
 }
Enumerative type describing the endianess of a port; NONE means that it has not been specified yet.
enum port_interface {
PI_DEFAULT = 0,
PI_RNONE,
PI_WNONE,
PI_RACK,
PI_WACK,
PI_RVALID,
PI_WVALID,
PI_EMPTY_N,
PI_READ,
PI_FULL_N,
PI_WRITE,
PI_ADDRESS,
PI_CHIPENABLE,
PI_WRITEENABLE,
PI_DIN,
PI_DOUT
 }
Enumerative type describing if the port is associated with a specific interface type.
Public Member Functions
port_o (int debug_level, const structural_objectRef o, port_direction dir, so_kind _port_type)
Constructor.
~port_o () override=default
Destructor.
void add_connection (structural_objectRef s)
Bind this port with a signal/port.
void remove_connection (structural_objectRef s)
remove a connection (signal/port) from this
bool is_connected (structural_objectRef s) const
void substitute_connection (structural_objectRef old_conn, structural_objectRef new_conn)
const structural_objectRef get_connection (unsigned int n) const
Return connection bounded to this port.
unsigned int get_connections_size () const
Return the number of connections bounded to this port.
port_direction get_port_direction () const
Return the direction of the port.
void set_port_direction (port_direction dir)
Set the direction of the port.
port_endianess get_port_endianess () const
Return the endianess of the port.
void set_port_endianess (port_endianess end)
Set the endianess of the port.
port_interface get_port_interface () const
Return the port interface type of the port.
void set_port_interface (port_interface pi)
Set the port interface type of the port.
unsigned get_port_alignment () const
Return the port interface alignment.
void set_port_alignment (unsigned algn)
Set the port interface alignment.
structural_objectRef get_connected_signal () const
Return the connected signal, if any.
void set_port_size (unsigned int dim)
Set port size.
unsigned int get_port_size () const
Get port size.
void set_is_var_args (bool c)
set the is var_args attribute.
bool get_is_var_args () const
return true if the port is a var_args
void set_is_clock (bool c)
set the is clock attribute.
bool get_is_clock () const
return true if the port is a clock
void set_is_extern (bool c)
set the is_extern attribute.
bool get_is_extern () const
return true if the port is extern
void set_bus_bundle (const std::string &name)
Sets the bus bundle identifier.
std::string get_bus_bundle () const
Returns the bus bundle identifier, if any.
void set_is_global (bool c)
set the is_global attribute.
bool get_is_global () const
return true if the port is global
void set_is_memory (bool c)
set the is_memory attribute.
bool get_is_memory () const
return true if the port is a memory port
void set_is_slave (bool c)
set the is_slave attribute.
bool get_is_slave () const
return true if the port works as slave memory port
void set_is_master (bool c)
set the is_master attribute.
bool get_is_master () const
return true if the port works as master memory port
void set_is_data_bus (bool c)
set the is_data attribute.
bool get_is_data_bus () const
return true if the port works as a data bus
void set_is_addr_bus (bool c)
set the is_addr_bus attribute.
bool get_is_addr_bus () const
return true if the port works as an address bus
void set_is_size_bus (bool c)
set the is_size_bus attribute.
bool get_is_size_bus () const
return true if the port works as a size bus
void set_is_tag_bus (bool c)
set the is_tag_bus attribute.
bool get_is_tag_bus () const
return true if the port works as an tag bus
void set_is_doubled (bool c)
set the is_doubled attribute.
bool get_is_doubled () const
return true if the port has a doubled size w.r.t the precision
void set_is_halved (bool c)
set the is_halved attribute.
bool get_is_halved () const
return true if the port has a halved size w.r.t the precision
structural_objectRef find_bounded_object (const structural_objectConstRef f_owner=structural_objectConstRef()) const
Find the object bounded to the port.
void set_critical ()
set the port as critical with respect to the timing path
bool get_critical () const
return if the component is critical or not
void set_reverse ()
Sets the port as reverse.
bool get_reverse () const
Returns if the port as to be printed in a reverse mode.
void copy (structural_objectRef dest) const override
Perform a copy of the port.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void add_n_ports (unsigned int n_ports, structural_objectRef owner)
Specify the number of ports of a generic port_vector object and add its corresponding ports.
const structural_objectRef get_port (unsigned int n) const
Return the ith port of the vector.
unsigned int get_ports_size () const
Return the number of ports.
unsigned int get_lsb () const
return the index of the least significant port
void print (std::ostream &os) const override
Print the port (for debug purpose)
std::string get_kind_text () const override
return the name of the class as a string.
enum so_kind get_kind () const override
return the type of the class
Static Public Member Functions
static port_direction to_port_direction (const std::string &val)
Convert a string into the corresponding port_direction enumerative type.
static port_interface to_port_interface (const std::string &val)
Convert a string into the corresponding port_interface enumerative type.
static void resize_busport (unsigned int bus_size_bitsize, unsigned int bus_addr_bitsize, unsigned int bus_data_bitsize, unsigned int bus_tag_bitsize, structural_objectRef port)
auxiliary function used to resize the bus ports with respect to their associated bus size
static void resize_std_port (unsigned int bitsize_variable, unsigned int n_elements, int debug_level, structural_objectRef port)
auxiliary function used to resize the standard ports
static void fix_port_properties (structural_objectRef port_i, structural_objectRef cir_port)
copy the port properties from port_i to cir_port
Data Fields
std::string size_parameter
custom size parameter
Static Public Attributes
static const unsigned int PARAMETRIC_PORT = static_cast<unsigned int>(-1)
Private Attributes
std::vector< Wrefcount< structural_object > > connected_objects
The list of connections associated with the port.
port_direction dir
direction of a port
port_endianess end
endianess of a port
port_interface pi
port interface type of a port
unsigned aligment
bool is_var_args
when true the port must be specialized at runtime depending on the number of input
bool is_clock
when true the port is a clock port and has to be attached to a clock object
bool is_extern
when true the port is an extern port
bool is_global
when true the port is a global port
bool is_reverse
when true the port is dumped as [0:msb-1] instead of [msb-1:0]
bool is_memory
when true the port is a memory port
bool is_slave
when true the port is a slave port
bool is_master
when true the port is a master port
bool is_data_bus
when true the port is a data bus
bool is_addr_bus
when true the port is an address bus
bool is_size_bus
when true the port is a size bus
bool is_tag_bus
when true the port is a tag bus
bool is_doubled
when true the port has a doubled size
bool is_halved
when true the port has a halfed size
bool is_critical
when true the port is involved into the critical path of the netlist
std::string bus_bundle
bus bundle
unsigned int lsb
least significant bit
std::vector< structural_objectRef > ports
The list of ports associated with the port.
so_kind port_type
port type
Static Private Attributes
static const char * port_directionNames [] = {`IN`, `OUT`, `IO`, `GEN`, `UNKNOWN`}
store the names of the enumerative port_direction.
static const char * port_interfaceNames [] = {`PI_DEFAULT`, `PI_RNONE`, `PI_WNONE`}
store the names of the enumerative port_interface.
 default values associated with the members of the port_o class.
static const bool is_clock_DEFAULT = false
static const bool is_extern_DEFAULT = false
static const bool is_global_DEFAULT = false
static const bool is_memory_DEFAULT = false
static const bool is_slave_DEFAULT = false
static const bool is_master_DEFAULT = false
static const bool is_data_bus_DEFAULT = false
static const bool is_addr_bus_DEFAULT = false
static const bool is_tag_bus_DEFAULT = false
static const bool is_size_bus_DEFAULT = false
static const bool is_doubled_DEFAULT = false
static const bool is_halved_DEFAULT = false
static const bool is_critical_DEFAULT = false
static const bool is_reverse_DEFAULT = false
static const bool is_var_args_DEFAULT = false
static const unsigned port_interface_alignment_DEFAULT = 0
Additional Inherited Members
Detailed Description
This class describes a port associated with a component or a channel.
A port can be in relation with:
another standard port (e.g., primary input/output connections);
a signal (e.g., standard internal connections):
a port of a channel (e.g, when a channel is used as a connection).
Definition at line 648 of file structural_objects.hpp.
Member Enumeration Documentation
port_direction
enum port_o::port_direction
Enumerative type describing the direction of a port.
Enumerator
IN
OUT
IO
GEN
UNKNOWN
TLM_IN
TLM_OUT
TLM_INOUT
Definition at line 652 of file structural_objects.hpp.
port_endianess
enum port_o::port_endianess
Enumerative type describing the endianess of a port; NONE means that it has not been specified yet.
Enumerator
LITTLE
BIG
NONE
Definition at line 665 of file structural_objects.hpp.
port_interface
enum port_o::port_interface
Enumerative type describing if the port is associated with a specific interface type.
Enumerator
PI_DEFAULT
PI_RNONE
PI_WNONE
PI_RACK
PI_WACK
PI_RVALID
PI_WVALID
PI_EMPTY_N
PI_READ
PI_FULL_N
PI_WRITE
PI_ADDRESS
PI_CHIPENABLE
PI_WRITEENABLE
PI_DIN
PI_DOUT
Definition at line 673 of file structural_objects.hpp.
Constructor & Destructor Documentation
port_o()
port_o::port_o (int debug_level, const structural_objectRef o, port_direction dir, so_kind _port_type)
Constructor.
Parameters
o is the owner of the port
dir defines the direction of the port.
Definition at line 894 of file structural_objects.cpp.
References IN, and attribute::STRING.
Referenced by copy(), and xload().
 port_o()
port_o::~port_o () [override], [default]
Destructor.
Member Function Documentation
add_connection()
void port_o::add_connection (structural_objectRef s)
Bind this port with a signal/port.
Parameters
s is the connection
Definition at line 929 of file structural_objects.cpp.
References connected_objects, constant_o_K, structural_object::get_kind(), get_kind(), structural_object::get_kind_text(), structural_object::get_owner(), structural_object::get_path(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, and THROW_ASSERT.
add_n_ports()
void port_o::add_n_ports (unsigned int n_ports, structural_objectRef owner)
Specify the number of ports of a generic port_vector object and add its corresponding ports.
It can be done only on port_vectors not yet specialized. The type of the port is equal to the type descriptor of the port_vector.
Parameters
n_ports is the number of the ports.
owner is the reference version of `this`.
Definition at line 4289 of file structural_objects.cpp.
References structural_object::debug_level, refcount< T >::get(), structural_object::get_path(), structural_object::get_typeRef(), port_o_K, port_vector_o_K, structural_object::set_id(), structural_object::set_type(), and THROW_ASSERT.
Referenced by StateTransitionGraphManager::specialise_mu().
copy()
void port_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the port.
Parameters
dest destination object.
connected_objects has to be updated outside!!!
Reimplemented from structural_object.
Definition at line 1352 of file structural_objects.cpp.
References aligment, bus_bundle, structural_object::copy(), structural_object::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, dir, end, structural_object::get_path(), get_port(), index, is_addr_bus, is_clock, is_critical, is_data_bus, is_doubled, is_extern, is_global, is_halved, is_master, is_memory, is_reverse, is_size_bus, is_slave, is_tag_bus, is_var_args, lsb, pi, port_o(), port_o_K, ports, PRINT_DBG_MEX, size_parameter, STR, and THROW_ERROR.
find_bounded_object()
structural_objectRef port_o::find_bounded_object (const structural_objectConstRef f_owner = structural_objectConstRef()) const
Find the object bounded to the port.
The object searched has the same owner of the port.
Returns
the object bounded to the port.
Definition at line 1210 of file structural_objects.cpp.
References connected_objects, constant_o_K, structural_object::get_id(), get_kind(), structural_object::get_owner(), structural_object::get_path(), INDENT_DBG_MEX, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by structural_manager::build_graph().
find_isomorphic()
structural_objectRef port_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Definition at line 1279 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, structural_object::find_isomorphic(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), port_o_K, port_vector_o_K, ports, signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_ERROR.
find_member()
structural_objectRef port_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 1319 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, connected_objects, constant_o_K, data_o_K, event_o_K, port_o_K, port_type, port_vector_o_K, ports, signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_ERROR.
fix_port_properties()
void port_o::fix_port_properties (structural_objectRef port_i, structural_objectRef cir_port) [static]
copy the port properties from port_i to cir_port
Parameters
port_i is the source port
cir_port is the created port
Definition at line 4389 of file structural_objects.cpp.
References NP_functionality::EQUATION, refcount< T >::get(), bus_connection_o::get_connection(), bus_connection_o::get_connections_size(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_kind_text(), NP_functionality::get_NP_functionality(), structural_object::get_owner(), structural_object::get_path(), structural_object::get_typeRef(), structural_type_descriptor::id_type, OUT, structural_object::owner, port_o_K, signal_o_K, SplitString(), THROW_ASSERT, THROW_ERROR, and test_panda::tokens.
Referenced by top_entity::add_ports(), minimal_interface::build_wrapper(), fu_binding::manage_extern_global_port(), datapath_parallel_cs::manage_extern_global_port_parallel(), cs_interface::manage_extern_global_port_top(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), fu_binding::manage_memory_ports_chained(), and fu_binding::manage_memory_ports_parallel_chained().
get_bus_bundle()
std::string port_o::get_bus_bundle () const
Returns the bus bundle identifier, if any.
Definition at line 1105 of file structural_objects.cpp.
References bus_bundle.
get_connected_signal()
structural_objectRef port_o::get_connected_signal () const
Return the connected signal, if any.
Null pointer otherwise.
Definition at line 974 of file structural_objects.cpp.
References connected_objects, structural_object::get_owner(), structural_object::get_path(), signal_o_K, signal_vector_o_K, and THROW_ASSERT.
get_connection()
const structural_objectRef port_o::get_connection (unsigned int n) const
Return connection bounded to this port.
Parameters
n is the index of the connection
Definition at line 1019 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
get_connections_size()
unsigned int port_o::get_connections_size () const
Return the number of connections bounded to this port.
Definition at line 1025 of file structural_objects.cpp.
References connected_objects.
get_critical()
bool port_o::get_critical () const
return if the component is critical or not
Definition at line 1407 of file structural_objects.cpp.
References is_critical.
Referenced by structural_manager::build_graph().
get_is_addr_bus()
bool port_o::get_is_addr_bus () const
return true if the port works as an address bus
Definition at line 1165 of file structural_objects.cpp.
References is_addr_bus.
get_is_clock()
bool port_o::get_is_clock () const
return true if the port is a clock
Definition at line 1085 of file structural_objects.cpp.
References is_clock.
get_is_data_bus()
bool port_o::get_is_data_bus () const
return true if the port works as a data bus
Definition at line 1155 of file structural_objects.cpp.
References is_data_bus.
get_is_doubled()
bool port_o::get_is_doubled () const
return true if the port has a doubled size w.r.t the precision
Definition at line 1195 of file structural_objects.cpp.
References is_doubled.
get_is_extern()
bool port_o::get_is_extern () const
return true if the port is extern
Definition at line 1095 of file structural_objects.cpp.
References is_extern.
get_is_global()
bool port_o::get_is_global () const
return true if the port is global
Definition at line 1115 of file structural_objects.cpp.
References is_global.
get_is_halved()
bool port_o::get_is_halved () const
return true if the port has a halved size w.r.t the precision
Definition at line 1205 of file structural_objects.cpp.
References is_halved.
get_is_master()
bool port_o::get_is_master () const
return true if the port works as master memory port
Definition at line 1145 of file structural_objects.cpp.
References is_master.
get_is_memory()
bool port_o::get_is_memory () const
return true if the port is a memory port
Definition at line 1125 of file structural_objects.cpp.
References is_memory.
get_is_size_bus()
bool port_o::get_is_size_bus () const
return true if the port works as a size bus
Definition at line 1175 of file structural_objects.cpp.
References is_size_bus.
get_is_slave()
bool port_o::get_is_slave () const
return true if the port works as slave memory port
Definition at line 1135 of file structural_objects.cpp.
References is_slave.
get_is_tag_bus()
bool port_o::get_is_tag_bus () const
return true if the port works as an tag bus
Definition at line 1185 of file structural_objects.cpp.
References is_tag_bus.
get_is_var_args()
bool port_o::get_is_var_args () const
return true if the port is a var_args
Definition at line 1075 of file structural_objects.cpp.
References is_var_args.
get_kind()
enum so_kind port_o::get_kind () const [inline], [override], [virtual]
return the type of the class
Implements structural_object.
Definition at line 1091 of file structural_objects.hpp.
Referenced by add_connection(), and find_bounded_object().
get_kind_text()
std::string port_o::get_kind_text () const [inline], [override], [virtual]
return the name of the class as a string.
Implements structural_object.
Definition at line 1081 of file structural_objects.hpp.
References port_vector_o_K.
Referenced by xwrite().
get_lsb()
unsigned int port_o::get_lsb () const [inline]
return the index of the least significant port
Definition at line 1041 of file structural_objects.hpp.
References structural_type_descriptor::print().
get_port()
const structural_objectRef port_o::get_port (unsigned int n) const
Return the ith port of the vector.
It checks that a port exists at position n.
Parameters
n is the index of the port
Definition at line 4307 of file structural_objects.cpp.
References structural_object::get_path(), port_vector_o_K, STR, and THROW_ASSERT.
Referenced by conn_binding::add_command_ports(), and copy().
get_port_alignment()
unsigned port_o::get_port_alignment () const
Return the port interface alignment.
Definition at line 1060 of file structural_objects.cpp.
References aligment.
get_port_direction()
port_o::port_direction port_o::get_port_direction () const
Return the direction of the port.
Definition at line 1030 of file structural_objects.cpp.
References dir.
get_port_endianess()
port_o::port_endianess port_o::get_port_endianess () const
Return the endianess of the port.
Definition at line 1040 of file structural_objects.cpp.
References end.
get_port_interface()
port_o::port_interface port_o::get_port_interface () const
Return the port interface type of the port.
Definition at line 1050 of file structural_objects.cpp.
References pi.
get_port_size()
unsigned int port_o::get_port_size () const
Get port size.
Returns
the dimension of the port
Definition at line 4325 of file structural_objects.cpp.
References structural_object::get_typeRef(), and structural_type_descriptor::size.
get_ports_size()
unsigned int port_o::get_ports_size () const
Return the number of ports.
When the port_vector has not yet specialized 0 is returned.
Definition at line 4314 of file structural_objects.cpp.
References structural_object::get_path(), port_vector_o_K, and THROW_ASSERT.
get_reverse()
bool port_o::get_reverse () const
Returns if the port as to be printed in a reverse mode.
Definition at line 1417 of file structural_objects.cpp.
References is_reverse.
is_connected()
bool port_o::is_connected (structural_objectRef s) const
Definition at line 960 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
print()
void port_o::print (std::ostream & os) const [override], [virtual]
Print the port (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Definition at line 1615 of file structural_objects.cpp.
References aligment, connected_objects, structural_object::convert_so_short(), dir, pi, port_directionNames, port_interface_alignment_DEFAULT, port_interfaceNames, ports, structural_object::PP, structural_object::print(), and STR.
remove_connection()
void port_o::remove_connection (structural_objectRef s)
remove a connection (signal/port) from this
Parameters
s is the connection to be removed
Definition at line 945 of file structural_objects.cpp.
References connected_objects, structural_object::get_path(), and THROW_ASSERT.
resize_busport()
void port_o::resize_busport (unsigned int bus_size_bitsize, unsigned int bus_addr_bitsize, unsigned int bus_data_bitsize, unsigned int bus_tag_bitsize, structural_objectRef port) [static]
auxiliary function used to resize the bus ports with respect to their associated bus size
Parameters
bus_size_bitsize bitsize of sizes
bus_addr_bitsize bitsize of addresses
bus_data_bitsize bitsize of data
bus_tag_bitsize bitsize of tag
port is the port to be resized
Definition at line 4330 of file structural_objects.cpp.
References structural_object::get_kind(), pi(), port_vector_o_K, and structural_object::type_resize().
Referenced by fu_binding::add_to_SM(), TasteInterfaceGeneration::InternalExec(), TopEntityMemoryMapped::resizing_IO(), fu_binding::specialise_fu(), and RTLCharacterization::specialize_fu().
resize_std_port()
void port_o::resize_std_port (unsigned int bitsize_variable, unsigned int n_elements, int debug_level, structural_objectRef port) [static]
auxiliary function used to resize the standard ports
Parameters
bitsize_variable is the bitsize
n_elements is the number of elements
debug_level is the debug level
port is the port to be resized
Definition at line 4357 of file structural_objects.cpp.
References structural_object::debug_level, DEBUG_LEVEL_PEDANTIC, structural_object::get_kind(), structural_object::get_path(), INDENT_DBG_MEX, pi(), port_vector_o_K, STR, THROW_ASSERT, and structural_object::type_resize().
Referenced by fu_binding::join_merge_split(), fu_binding::manage_extern_global_port(), RTLCharacterization::resize_port(), and fu_binding::specialise_fu().
set_bus_bundle()
void port_o::set_bus_bundle (const std::string & name)
Sets the bus bundle identifier.
Definition at line 1100 of file structural_objects.cpp.
References bus_bundle.
set_critical()
void port_o::set_critical ()
set the port as critical with respect to the timing path
Definition at line 1402 of file structural_objects.cpp.
References is_critical.
set_is_addr_bus()
void port_o::set_is_addr_bus (bool c)
set the is_addr_bus attribute.
Parameters
c when true the port is a port used as an address bus
Definition at line 1160 of file structural_objects.cpp.
References is_addr_bus.
set_is_clock()
void port_o::set_is_clock (bool c)
set the is clock attribute.
Parameters
c when true the port is a clock port and has to be attached to a clock object
Definition at line 1080 of file structural_objects.cpp.
References is_clock.
set_is_data_bus()
void port_o::set_is_data_bus (bool c)
set the is_data attribute.
Parameters
c when true the port is a port used as a data bus
Definition at line 1150 of file structural_objects.cpp.
References is_data_bus.
set_is_doubled()
void port_o::set_is_doubled (bool c)
set the is_doubled attribute.
Parameters
c when true the port has a doubled size w.r.t the precision
Definition at line 1190 of file structural_objects.cpp.
References is_doubled.
set_is_extern()
void port_o::set_is_extern (bool c)
set the is_extern attribute.
Parameters
c when true the port is a extern port and has to be attached to an extern object
Definition at line 1090 of file structural_objects.cpp.
References is_extern.
set_is_global()
void port_o::set_is_global (bool c)
set the is_global attribute.
Parameters
c when true the port is a global port and has to be attached to a global object
Definition at line 1110 of file structural_objects.cpp.
References is_global.
set_is_halved()
void port_o::set_is_halved (bool c)
set the is_halved attribute.
Parameters
c when true the port has a halved size w.r.t the precision
Definition at line 1200 of file structural_objects.cpp.
References is_halved.
set_is_master()
void port_o::set_is_master (bool c)
set the is_master attribute.
Parameters
c when true the port is a port used to interact with the onchip or offchip memory as master
Definition at line 1140 of file structural_objects.cpp.
References is_master.
set_is_memory()
void port_o::set_is_memory (bool c)
set the is_memory attribute.
Parameters
c when true the port is a port used to interact with the onchip or offchip memory
Definition at line 1120 of file structural_objects.cpp.
References is_memory.
set_is_size_bus()
void port_o::set_is_size_bus (bool c)
set the is_size_bus attribute.
Parameters
c when true the port is a port used as a size bus
Definition at line 1170 of file structural_objects.cpp.
References is_size_bus.
set_is_slave()
void port_o::set_is_slave (bool c)
set the is_slave attribute.
Parameters
c when true the port is a port used to interact with the onchip or offchip memory as slave
Definition at line 1130 of file structural_objects.cpp.
References is_slave.
set_is_tag_bus()
void port_o::set_is_tag_bus (bool c)
set the is_tag_bus attribute.
Parameters
c when true the port is a port used as an tag bus
Definition at line 1180 of file structural_objects.cpp.
References is_tag_bus.
set_is_var_args()
void port_o::set_is_var_args (bool c)
set the is var_args attribute.
Parameters
c when true the port has a variable numbers of inputs
Definition at line 1070 of file structural_objects.cpp.
References is_var_args.
set_port_alignment()
void port_o::set_port_alignment (unsigned algn)
Set the port interface alignment.
Definition at line 1065 of file structural_objects.cpp.
References aligment.
set_port_direction()
void port_o::set_port_direction (port_direction dir)
Set the direction of the port.
Definition at line 1035 of file structural_objects.cpp.
References dir.
set_port_endianess()
void port_o::set_port_endianess (port_endianess end)
Set the endianess of the port.
Definition at line 1045 of file structural_objects.cpp.
References end.
set_port_interface()
void port_o::set_port_interface (port_interface pi)
Set the port interface type of the port.
Definition at line 1055 of file structural_objects.cpp.
References pi.
set_port_size()
void port_o::set_port_size (unsigned int dim)
Set port size.
Parameters
dim is the new dimension of the port
Definition at line 4320 of file structural_objects.cpp.
References structural_object::get_typeRef(), and structural_type_descriptor::size.
set_reverse()
void port_o::set_reverse ()
Sets the port as reverse.
Definition at line 1412 of file structural_objects.cpp.
References is_reverse.
substitute_connection()
void port_o::substitute_connection (structural_objectRef old_conn, structural_objectRef new_conn)
Definition at line 988 of file structural_objects.cpp.
References connected_objects, structural_object::get_kind(), structural_object::get_path(), signal_o_K, and THROW_ERROR.
to_port_direction()
port_o::port_direction port_o::to_port_direction (const std::string & val) [static]
Convert a string into the corresponding port_direction enumerative type.
Parameters
val is the string version of the enum.
Definition at line 1502 of file structural_objects.cpp.
References port_directionNames, and UNKNOWN.
Referenced by xload(), and module::xload().
to_port_interface()
port_o::port_interface port_o::to_port_interface (const std::string & val) [static]
Convert a string into the corresponding port_interface enumerative type.
Parameters
val is the string version of the enum.
Definition at line 1511 of file structural_objects.cpp.
References port_interfaceNames, and UNKNOWN.
Referenced by xload().
xload()
void port_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
the field connected_objects has to be updated outside!!!
Reimplemented from structural_object.
Definition at line 1422 of file structural_objects.cpp.
References aligment, CE_XVM, dir, xml_child::get_children(), GET_CLASS_NAME, structural_manager::get_debug_level(), structural_object::get_id(), is_addr_bus, is_clock, is_critical, is_data_bus, is_doubled, is_extern, is_global, is_halved, is_master, is_memory, is_reverse, is_size_bus, is_slave, is_tag_bus, is_var_args, LOAD_XVFM, LOAD_XVM, lsb, min, pi, port_o(), port_o_K, port_type, port_vector_o_K, ports, size_parameter, THROW_ASSERT, to_port_direction(), to_port_interface(), and structural_object::xload().
xwrite()
void port_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Definition at line 1520 of file structural_objects.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), aligment, connected_objects, dir, structural_object::get_id(), get_kind_text(), structural_object::get_typeRef(), structural_type_descriptor::id_type, is_addr_bus, is_addr_bus_DEFAULT, is_clock, is_clock_DEFAULT, is_critical, is_critical_DEFAULT, is_data_bus, is_data_bus_DEFAULT, is_doubled, is_doubled_DEFAULT, is_extern, is_extern_DEFAULT, is_global, is_global_DEFAULT, is_halved, is_halved_DEFAULT, is_master, is_master_DEFAULT, is_memory, is_memory_DEFAULT, is_reverse, is_reverse_DEFAULT, is_size_bus, is_size_bus_DEFAULT, is_slave, is_slave_DEFAULT, is_tag_bus, is_tag_bus_DEFAULT, is_var_args, is_var_args_DEFAULT, pi, port_directionNames, port_interface_alignment_DEFAULT, port_interfaceNames, ports, WRITE_XNVM, WRITE_XNVM2, WRITE_XVM, and structural_object::xwrite().
Field Documentation
aligment
unsigned port_o::aligment [private]
Definition at line 1109 of file structural_objects.hpp.
Referenced by copy(), get_port_alignment(), print(), set_port_alignment(), xload(), and xwrite().
bus_bundle
std::string port_o::bus_bundle [private]
bus bundle
Definition at line 1157 of file structural_objects.hpp.
Referenced by copy(), get_bus_bundle(), and set_bus_bundle().
connected_objects
std::vector<Wrefcount<structural_object> > port_o::connected_objects [private]
The list of connections associated with the port.
Definition at line 1098 of file structural_objects.hpp.
Referenced by add_connection(), find_bounded_object(), find_member(), get_connected_signal(), get_connection(), get_connections_size(), is_connected(), print(), remove_connection(), substitute_connection(), and xwrite().
dir
port_direction port_o::dir [private]
direction of a port
Definition at line 1101 of file structural_objects.hpp.
Referenced by copy(), get_port_direction(), print(), set_port_direction(), xload(), and xwrite().
end
port_endianess port_o::end [private]
endianess of a port
Definition at line 1104 of file structural_objects.hpp.
Referenced by copy(), get_port_endianess(), and set_port_endianess().
is_addr_bus
bool port_o::is_addr_bus [private]
when true the port is an address bus
Definition at line 1139 of file structural_objects.hpp.
Referenced by copy(), get_is_addr_bus(), set_is_addr_bus(), xload(), and xwrite().
is_addr_bus_DEFAULT
const bool port_o::is_addr_bus_DEFAULT = false [static], [private]
Definition at line 1185 of file structural_objects.hpp.
Referenced by xwrite().
is_clock
bool port_o::is_clock [private]
when true the port is a clock port and has to be attached to a clock object
Definition at line 1115 of file structural_objects.hpp.
Referenced by copy(), get_is_clock(), set_is_clock(), xload(), and xwrite().
is_clock_DEFAULT
const bool port_o::is_clock_DEFAULT = false [static], [private]
Definition at line 1178 of file structural_objects.hpp.
Referenced by xwrite().
is_critical
bool port_o::is_critical [private]
when true the port is involved into the critical path of the netlist
Definition at line 1154 of file structural_objects.hpp.
Referenced by copy(), get_critical(), set_critical(), xload(), and xwrite().
is_critical_DEFAULT
const bool port_o::is_critical_DEFAULT = false [static], [private]
Definition at line 1190 of file structural_objects.hpp.
Referenced by xwrite().
is_data_bus
bool port_o::is_data_bus [private]
when true the port is a data bus
Definition at line 1136 of file structural_objects.hpp.
Referenced by copy(), get_is_data_bus(), set_is_data_bus(), xload(), and xwrite().
is_data_bus_DEFAULT
const bool port_o::is_data_bus_DEFAULT = false [static], [private]
Definition at line 1184 of file structural_objects.hpp.
Referenced by xwrite().
is_doubled
bool port_o::is_doubled [private]
when true the port has a doubled size
Definition at line 1148 of file structural_objects.hpp.
Referenced by copy(), get_is_doubled(), set_is_doubled(), xload(), and xwrite().
is_doubled_DEFAULT
const bool port_o::is_doubled_DEFAULT = false [static], [private]
Definition at line 1188 of file structural_objects.hpp.
Referenced by xwrite().
is_extern
bool port_o::is_extern [private]
when true the port is an extern port
Definition at line 1118 of file structural_objects.hpp.
Referenced by copy(), get_is_extern(), set_is_extern(), xload(), and xwrite().
is_extern_DEFAULT
const bool port_o::is_extern_DEFAULT = false [static], [private]
Definition at line 1179 of file structural_objects.hpp.
Referenced by xwrite().
is_global
bool port_o::is_global [private]
when true the port is a global port
Definition at line 1121 of file structural_objects.hpp.
Referenced by copy(), get_is_global(), set_is_global(), xload(), and xwrite().
is_global_DEFAULT
const bool port_o::is_global_DEFAULT = false [static], [private]
Definition at line 1180 of file structural_objects.hpp.
Referenced by xwrite().
is_halved
bool port_o::is_halved [private]
when true the port has a halfed size
Definition at line 1151 of file structural_objects.hpp.
Referenced by copy(), get_is_halved(), set_is_halved(), xload(), and xwrite().
is_halved_DEFAULT
const bool port_o::is_halved_DEFAULT = false [static], [private]
Definition at line 1189 of file structural_objects.hpp.
Referenced by xwrite().
is_master
bool port_o::is_master [private]
when true the port is a master port
Definition at line 1133 of file structural_objects.hpp.
Referenced by copy(), get_is_master(), set_is_master(), xload(), and xwrite().
is_master_DEFAULT
const bool port_o::is_master_DEFAULT = false [static], [private]
Definition at line 1183 of file structural_objects.hpp.
Referenced by xwrite().
is_memory
bool port_o::is_memory [private]
when true the port is a memory port
Definition at line 1127 of file structural_objects.hpp.
Referenced by copy(), get_is_memory(), set_is_memory(), xload(), and xwrite().
is_memory_DEFAULT
const bool port_o::is_memory_DEFAULT = false [static], [private]
Definition at line 1181 of file structural_objects.hpp.
Referenced by xwrite().
is_reverse
bool port_o::is_reverse [private]
when true the port is dumped as [0:msb-1] instead of [msb-1:0]
Definition at line 1124 of file structural_objects.hpp.
Referenced by copy(), get_reverse(), set_reverse(), xload(), and xwrite().
is_reverse_DEFAULT
const bool port_o::is_reverse_DEFAULT = false [static], [private]
Definition at line 1191 of file structural_objects.hpp.
Referenced by xwrite().
is_size_bus
bool port_o::is_size_bus [private]
when true the port is a size bus
Definition at line 1142 of file structural_objects.hpp.
Referenced by copy(), get_is_size_bus(), set_is_size_bus(), xload(), and xwrite().
is_size_bus_DEFAULT
const bool port_o::is_size_bus_DEFAULT = false [static], [private]
Definition at line 1187 of file structural_objects.hpp.
Referenced by xwrite().
is_slave
bool port_o::is_slave [private]
when true the port is a slave port
Definition at line 1130 of file structural_objects.hpp.
Referenced by copy(), get_is_slave(), set_is_slave(), xload(), and xwrite().
is_slave_DEFAULT
const bool port_o::is_slave_DEFAULT = false [static], [private]
Definition at line 1182 of file structural_objects.hpp.
Referenced by xwrite().
is_tag_bus
bool port_o::is_tag_bus [private]
when true the port is a tag bus
Definition at line 1145 of file structural_objects.hpp.
Referenced by copy(), get_is_tag_bus(), set_is_tag_bus(), xload(), and xwrite().
is_tag_bus_DEFAULT
const bool port_o::is_tag_bus_DEFAULT = false [static], [private]
Definition at line 1186 of file structural_objects.hpp.
Referenced by xwrite().
is_var_args
bool port_o::is_var_args [private]
when true the port must be specialized at runtime depending on the number of input
Definition at line 1112 of file structural_objects.hpp.
Referenced by copy(), get_is_var_args(), set_is_var_args(), xload(), and xwrite().
is_var_args_DEFAULT
const bool port_o::is_var_args_DEFAULT = false [static], [private]
Definition at line 1192 of file structural_objects.hpp.
Referenced by xwrite().
lsb
unsigned int port_o::lsb [private]
least significant bit
Definition at line 1160 of file structural_objects.hpp.
Referenced by copy(), and xload().
PARAMETRIC_PORT
const unsigned int port_o::PARAMETRIC_PORT = static_cast<unsigned int>(-1) [static]
Definition at line 693 of file structural_objects.hpp.
Referenced by structural_manager::add_port_vector(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), and LoadBuiltinTechnology::Exec().
pi
port_interface port_o::pi [private]
port interface type of a port
Definition at line 1107 of file structural_objects.hpp.
Referenced by copy(), get_port_interface(), print(), set_port_interface(), xload(), and xwrite().
port_directionNames
const char * port_o::port_directionNames = {`IN`, `OUT`, `IO`, `GEN`, `UNKNOWN`} [static], [private]
store the names of the enumerative port_direction.
Definition at line 1166 of file structural_objects.hpp.
Referenced by structural_object::get_path(), print(), to_port_direction(), and xwrite().
port_interface_alignment_DEFAULT
const unsigned port_o::port_interface_alignment_DEFAULT = 0 [static], [private]
Definition at line 1193 of file structural_objects.hpp.
Referenced by print(), and xwrite().
port_interfaceNames
const char * port_o::port_interfaceNames = {`PI_DEFAULT`, `PI_RNONE`, `PI_WNONE`} [static], [private]
store the names of the enumerative port_interface.
Definition at line 1169 of file structural_objects.hpp.
Referenced by structural_object::get_path(), print(), to_port_interface(), and xwrite().
port_type
so_kind port_o::port_type [private]
port type
Definition at line 1172 of file structural_objects.hpp.
Referenced by find_member(), and xload().
ports
std::vector<structural_objectRef> port_o::ports [private]
The list of ports associated with the port.
Definition at line 1163 of file structural_objects.hpp.
Referenced by copy(), find_isomorphic(), find_member(), print(), xload(), and xwrite().
size_parameter
std::string port_o::size_parameter
custom size parameter
Definition at line 718 of file structural_objects.hpp.
Referenced by copy(), and xload().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp