application_manager Class Reference
#include <application_manager.hpp>
Public Member Functions
application_manager (const FunctionExpanderConstRef function_expander, const bool single_root_function, const bool allow_recursive_functions, const ParameterConstRef _Param)
Constructor.
virtual ~application_manager ()
Destructor.
const tree_managerRef get_tree_manager () const
Returns the tree manager associated with the application.
CallGraphManagerRef GetCallGraphManager ()
Returns the call graph associated with the application.
const CallGraphManagerConstRef CGetCallGraphManager () const
Returns the call graph associated with the application.
bool hasToBeInterfaced (unsigned int funId) const
Check for interface generation.
FunctionBehaviorRef GetFunctionBehavior (unsigned int index)
Returns the data structure associated with the given identifier.
const FunctionBehaviorConstRef CGetFunctionBehavior (unsigned int index) const
Returns the datastructure associated with the given identifier.
CustomOrderedSet< unsigned int > get_functions_with_body () const
Returns the set of functions whose implementation is present in the parsed input specification (i.e.
CustomOrderedSet< unsigned int > get_functions_without_body () const
Returns the set of functions whose implementation is not present in the parsed input specification (i.e.
void add_global_variable (unsigned int var)
Adds a global variable.
const CustomSet< unsigned int > & get_global_variables () const
Returns the set of original global variables.
unsigned int get_produced_value (unsigned int fun_id, const vertex &v) const
Returns the value produced by a vertex.
const ParameterConstRef get_parameter () const
Returns the parameter datastructure.
void add_written_object (unsigned int node_id)
Add the node_id to the set of object modified by a store.
const CustomOrderedSet< unsigned int > & get_written_objects () const
Return the set of variables modified by a store.
void set_address_bitsize (unsigned int value)
set the value of the address bitsize
unsigned int & Rget_address_bitsize ()
return the address bitsize
unsigned int get_address_bitsize () const
bool ApplyNewTransformation () const
Return true if a new transformation can be applied.
void RegisterTransformation (const std::string &step, const tree_nodeConstRef new_tn)
Register a transformation.
bool isParmUsed (unsigned parm_index) const
isParmUsed return true in case the parameter is used
unsigned getSSAFromParm (unsigned parm_index) const
getSSAFromParm returns the ssa_name index associated with the parm_decl index, 0 in case there is not an associated index
void setSSAFromParm (unsigned int parm_index, unsigned ssa_index)
setSSAFromParm defines the parm_decl versus ssa_name relation
void clearParm2SSA ()
clearParm2SSA cleans the map putting into relation parm_decl and ssa_name
Data Fields
std::map< std::string, std::string > input_files
The original input file and the actual source code file to be elaborated.
Protected Member Functions
unsigned int get_produced_value (const tree_nodeRef &tn) const
Returns the values produced by a vertex (recursive version)
Protected Attributes
const tree_managerRef TM
class representing the application information at low level
const CallGraphManagerRef call_graph_manager
class representing the call graph of the application
const ParameterConstRef Param
class containing all the parameters
CustomSet< unsigned int > global_variables
set of global variables
unsigned int address_bitsize
const bool single_root_function
True if only one root function has to be considered.
CustomOrderedSet< unsigned int > written_objects
store memory objects which can be written
size_t cfg_transformations
The number of cfg transformations applied to this function.
const int debug_level
debugging level of the class
CustomMap< unsigned, unsigned > Parm2SSA_map
put into relation formal parameters and the associated ssa variables
Detailed Description
Definition at line 75 of file application_manager.hpp.
Constructor & Destructor Documentation
application_manager()
application_manager::application_manager (const FunctionExpanderConstRef function_expander, const bool single_root_function, const bool allow_recursive_functions, const ParameterConstRef _Param)
Constructor.
Parameters
function_expander is the expander used to determine if a called function has to be examinedi
single_root_function specifies if only one root function has to be considered
allow_recursive_functions specifies if recursive functions are allowed
_Param is the reference to the class containing all the parameters
Definition at line 74 of file application_manager.cpp.
References input_files, Param, and ~application_manager().
 application_manager()
application_manager::~application_manager () [virtual], [default]
Destructor.
Referenced by application_manager().
Member Function Documentation
add_global_variable()
void application_manager::add_global_variable (unsigned int var)
Adds a global variable.
Parameters
var is the global variable to be added
Definition at line 149 of file application_manager.cpp.
References global_variables.
add_written_object()
void application_manager::add_written_object (unsigned int node_id)
Add the node_id to the set of object modified by a store.
Parameters
node_id is the object stored in memory
Definition at line 328 of file application_manager.cpp.
References written_objects.
ApplyNewTransformation()
bool application_manager::ApplyNewTransformation () const
Return true if a new transformation can be applied.
Definition at line 335 of file application_manager.cpp.
References cfg_transformations, and Param.
Referenced by get_address_bitsize().
CGetCallGraphManager()
const CallGraphManagerConstRef application_manager::CGetCallGraphManager () const
Returns the call graph associated with the application.
Definition at line 117 of file application_manager.cpp.
References call_graph_manager.
Referenced by hasToBeInterfaced().
CGetFunctionBehavior()
const FunctionBehaviorConstRef application_manager::CGetFunctionBehavior (unsigned int index) const
Returns the datastructure associated with the given identifier.
This method returns an error if the function does not exist.
Parameters
index is the identified of the function to be returned
Returns
the FunctionBehavior associated with the given function
Definition at line 137 of file application_manager.cpp.
References call_graph_manager, STR, and THROW_ASSERT.
Referenced by pragma_manager::CheckAddOmpFor(), get_produced_value(), HLS_manager::get_required_values(), and HLS_manager::xwrite().
clearParm2SSA()
void application_manager::clearParm2SSA ()
clearParm2SSA cleans the map putting into relation parm_decl and ssa_name
Definition at line 374 of file application_manager.cpp.
References Parm2SSA_map.
Referenced by get_address_bitsize().
get_address_bitsize()
unsigned int application_manager::get_address_bitsize () const [inline]
Definition at line 259 of file application_manager.hpp.
References address_bitsize, ApplyNewTransformation(), clearParm2SSA(), getSSAFromParm(), isParmUsed(), RegisterTransformation(), and setSSAFromParm().
get_functions_with_body()
CustomOrderedSet< unsigned int > application_manager::get_functions_with_body () const
Returns the set of functions whose implementation is present in the parsed input specification (i.e.
which has a non empty graph)
Definition at line 154 of file application_manager.cpp.
References call_graph_manager.
get_functions_without_body()
CustomOrderedSet< unsigned int > application_manager::get_functions_without_body () const
Returns the set of functions whose implementation is not present in the parsed input specification (i.e.
the ones with an empty Control Flow Graph)
Definition at line 159 of file application_manager.cpp.
References call_graph_manager.
get_global_variables()
const CustomSet< unsigned int > & application_manager::get_global_variables () const
Returns the set of original global variables.
Returns
a set containing the identified of the global variables
Definition at line 144 of file application_manager.cpp.
References global_variables.
get_parameter()
const ParameterConstRef application_manager::get_parameter () const
Returns the parameter datastructure.
Definition at line 102 of file application_manager.cpp.
References Param.
get_produced_value() [1/2]
unsigned int application_manager::get_produced_value (const tree_nodeRef & tn) const [protected]
Returns the values produced by a vertex (recursive version)
only the first output and so only single output gimple_asm are supported
Definition at line 178 of file application_manager.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, THROW_ASSERT, THROW_ERROR, and THROW_UNREACHABLE.
Referenced by get_produced_value().
get_produced_value() [2/2]
unsigned int application_manager::get_produced_value (unsigned int fun_id, const vertex & v) const
Returns the value produced by a vertex.
Definition at line 171 of file application_manager.cpp.
References FunctionBehavior::CFG, CGetFunctionBehavior(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), ENTRY_ID, EXIT_ID, get_produced_value(), tree_manager::get_tree_node_const(), and TM.
get_tree_manager()
const tree_managerRef application_manager::get_tree_manager () const
Returns the tree manager associated with the application.
Definition at line 107 of file application_manager.cpp.
References TM.
get_written_objects()
const CustomOrderedSet< unsigned int > & application_manager::get_written_objects () const
Return the set of variables modified by a store.
Definition at line 323 of file application_manager.cpp.
References written_objects.
GetCallGraphManager()
CallGraphManagerRef application_manager::GetCallGraphManager ()
Returns the call graph associated with the application.
Definition at line 112 of file application_manager.cpp.
References call_graph_manager.
GetFunctionBehavior()
FunctionBehaviorRef application_manager::GetFunctionBehavior (unsigned int index)
Returns the data structure associated with the given identifier.
This method returns an error if the function does not exist.
Parameters
index is the identified of the function to be returned
Returns
the FunctionBehavior associated with the given function
Definition at line 130 of file application_manager.cpp.
References call_graph_manager, STR, and THROW_ASSERT.
Referenced by pragma_manager::CheckAddOmpFor(), and pragma_manager::CheckAddOmpSimd().
getSSAFromParm()
unsigned application_manager::getSSAFromParm (unsigned parm_index) const
getSSAFromParm returns the ssa_name index associated with the parm_decl index, 0 in case there is not an associated index
Parameters
parm_index is the parm_decl index for which we look for the associated ssa_name index
Definition at line 356 of file application_manager.cpp.
References Parm2SSA_map, and THROW_ASSERT.
Referenced by get_address_bitsize().
hasToBeInterfaced()
bool application_manager::hasToBeInterfaced (unsigned int funId) const
Check for interface generation.
The interface has to be created for the top function and any additional top that is called through the bus.
Parameters
funId tree index of a function.
Returns
true if is a top or is an additional top.
Definition at line 122 of file application_manager.cpp.
References CGetCallGraphManager().
isParmUsed()
bool application_manager::isParmUsed (unsigned parm_index) const
isParmUsed return true in case the parameter is used
Parameters
parm_index is the parm_decl index
Returns
true in case the parameter is used
Definition at line 351 of file application_manager.cpp.
References Parm2SSA_map.
Referenced by get_address_bitsize().
RegisterTransformation()
void application_manager::RegisterTransformation (const std::string & step, const tree_nodeConstRef new_tn)
Register a transformation.
Parameters
step is the name of the step in which the transformation is applied
new_tn is the tree node to be created
Definition at line 340 of file application_manager.cpp.
References cfg_transformations, INDENT_OUT_MEX, max(), Param, STR, and THROW_ASSERT.
Referenced by get_address_bitsize().
Rget_address_bitsize()
unsigned int& application_manager::Rget_address_bitsize () [inline]
return the address bitsize
Definition at line 255 of file application_manager.hpp.
References address_bitsize.
set_address_bitsize()
void application_manager::set_address_bitsize (unsigned int value) [inline]
set the value of the address bitsize
Parameters
value is the new value
Definition at line 247 of file application_manager.hpp.
setSSAFromParm()
void application_manager::setSSAFromParm (unsigned int parm_index, unsigned ssa_index)
setSSAFromParm defines the parm_decl versus ssa_name relation
Parameters
parm_index is the index of the parm_decl
ssa_index is the index of the ssa_name
Definition at line 363 of file application_manager.cpp.
References Parm2SSA_map, and THROW_ASSERT.
Referenced by get_address_bitsize().
Field Documentation
address_bitsize
unsigned int application_manager::address_bitsize [protected]
Definition at line 98 of file application_manager.hpp.
Referenced by get_address_bitsize(), and Rget_address_bitsize().
call_graph_manager
const CallGraphManagerRef application_manager::call_graph_manager [protected]
class representing the call graph of the application
Definition at line 82 of file application_manager.hpp.
Referenced by CGetCallGraphManager(), CGetFunctionBehavior(), get_functions_with_body(), get_functions_without_body(), GetCallGraphManager(), GetFunctionBehavior(), and HLS_manager::xwrite().
cfg_transformations
size_t application_manager::cfg_transformations [protected]
The number of cfg transformations applied to this function.
Definition at line 113 of file application_manager.hpp.
Referenced by ApplyNewTransformation(), and RegisterTransformation().
debug_level
const int application_manager::debug_level [protected]
debugging level of the class
Definition at line 117 of file application_manager.hpp.
global_variables
CustomSet<unsigned int> application_manager::global_variables [protected]
set of global variables
Definition at line 96 of file application_manager.hpp.
Referenced by add_global_variable(), and get_global_variables().
input_files
std::map<std::string, std::string> application_manager::input_files
The original input file and the actual source code file to be elaborated.
Definition at line 134 of file application_manager.hpp.
Referenced by application_manager().
Param
const ParameterConstRef application_manager::Param [protected]
class containing all the parameters
Definition at line 93 of file application_manager.hpp.
Referenced by application_manager(), ApplyNewTransformation(), HLS_manager::get_backend_flow(), get_parameter(), HLS_manager::HLS_manager(), HLS_manager::IsSingleWriteMemory(), and RegisterTransformation().
Parm2SSA_map
CustomMap<unsigned, unsigned> application_manager::Parm2SSA_map [protected]
put into relation formal parameters and the associated ssa variables
Definition at line 120 of file application_manager.hpp.
Referenced by clearParm2SSA(), getSSAFromParm(), isParmUsed(), and setSSAFromParm().
single_root_function
const bool application_manager::single_root_function [protected]
True if only one root function has to be considered.
Definition at line 101 of file application_manager.hpp.
TM
const tree_managerRef application_manager::TM [protected]
class representing the application information at low level
Definition at line 79 of file application_manager.hpp.
Referenced by HLS_manager::get_constant_string(), get_produced_value(), HLS_manager::get_required_values(), get_tree_manager(), HLS_manager::is_reading_writing_function(), and HLS_manager::is_register_compatible().
written_objects
CustomOrderedSet<unsigned int> application_manager::written_objects [protected]
store memory objects which can be written
Definition at line 104 of file application_manager.hpp.
Referenced by add_written_object(), and get_written_objects().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/application_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/application_manager.cpp