trce_wrapper Class Reference
Main class for wrapping ISE tools by Xilinx.
#include <trce_wrapper.hpp>
Public Member Functions
trce_wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~trce_wrapper () override
Destructor.
Protected Member Functions
void init_reserved_vars () override
Initializes the reserved variables.
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Additional Inherited Members
Detailed Description
Main class for wrapping ISE tools by Xilinx.
Definition at line 60 of file trce_wrapper.hpp.
Constructor & Destructor Documentation
trce_wrapper()
trce_wrapper::trce_wrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Header include.
Parameters
Param is the set of parameters
Definition at line 56 of file trce_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, and ~trce_wrapper().
 trce_wrapper()
trce_wrapper::~trce_wrapper () [override], [default]
Destructor.
Referenced by trce_wrapper().
Member Function Documentation
EvaluateVariables()
void trce_wrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 70 of file trce_wrapper.cpp.
References DesignParameters::assign(), SynthesisTool::output_dir, PARAM_top_id, PARAM_trce_report_post, PARAM_trce_report_pre, PARAM_trce_tmpdir, and DesignParameters::parameter_values.
get_command_line()
std::string trce_wrapper::get_command_line (const DesignParametersRef & dp) const [override], [protected], [virtual]
Returns the proper command line.
Implements SynthesisTool.
Definition at line 80 of file trce_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), XilinxWrapper::toString(), and SynthesisTool::xml_tool_options.
init_reserved_vars()
void trce_wrapper::init_reserved_vars () [override], [protected], [virtual]
Initializes the reserved variables.
Reimplemented from SynthesisTool.
Definition at line 64 of file trce_wrapper.cpp.
References ADD_RES_VAR, SynthesisTool::init_reserved_vars(), and PARAM_trce_tmpdir.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/ise/trce_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/ise/trce_wrapper.cpp