filter_clique< vertex_type > Struct Template Reference
Functor used to reduce the size of clique: the rationale of filtering is that too many sharing may create problem to the timing closure of the design.
#include <clique_covering.hpp>
Public Member Functions
virtual ~filter_clique ()
virtual bool select_candidate_to_remove (const CustomOrderedSet< C_vertex > &candidate_clique, C_vertex &v, const std::map< C_vertex, vertex_type > &converter, const cc_compatibility_graph &cg) const =0
Detailed Description
template<typename vertex_type>
struct filter_clique< vertex_type >
Functor used to reduce the size of clique: the rationale of filtering is that too many sharing may create problem to the timing closure of the design.
Definition at line 115 of file clique_covering.hpp.
Constructor & Destructor Documentation
 filter_clique()
template<typename vertex_type>
virtual filter_clique< vertex_type >::~filter_clique () [inline], [virtual]
Definition at line 50 of file filter_clique.hpp.
Member Function Documentation
select_candidate_to_remove()
template<typename vertex_type>
virtual bool filter_clique< vertex_type >::select_candidate_to_remove (const CustomOrderedSet< C_vertex > & candidate_clique, C_vertex & v, const std::map< C_vertex, vertex_type > & converter, const cc_compatibility_graph & cg) const [pure virtual]
Implemented in slack_based_filtering, and no_filter_clique< vertex_type >.
Referenced by TTT_based_clique_covering_fast< vertex_type >::do_clique_covering(), TTT_based_clique_covering< vertex_type >::do_clique_covering(), bipartite_matching_clique_covering< vertex_type >::exec(), TS_based_clique_covering< vertex_type >::is_non_compliant(), and filter_clique< vertex >::~filter_clique().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/clique_covering.hpp
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/filter_clique.hpp