loops_computation Class Reference
loops computation analysis step
#include <loops_computation.hpp>
Public Member Functions
loops_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~loops_computation () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Performs the loop computation step.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
loops computation analysis step
Definition at line 62 of file loops_computation.hpp.
Constructor & Destructor Documentation
loops_computation()
loops_computation::loops_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the reference to the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
Definition at line 63 of file loops_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~loops_computation().
 loops_computation()
loops_computation::~loops_computation () [override], [default]
Destructor.
Referenced by loops_computation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > loops_computation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 71 of file loops_computation.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DOM_POST_DOM_COMPUTATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void loops_computation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 95 of file loops_computation.cpp.
References FunctionFrontendFlowStep::bb_version, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status loops_computation::InternalExec () [override], [virtual]
Performs the loop computation step.
Returns
the exit status of this step
FIXME: zero loop
Implements FunctionFrontendFlowStep.
Definition at line 101 of file loops_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, BBGraph::GetBBNodeInfo(), DesignFlowStep::parameters, PRINT_DBG_MEX, SUCCESS, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/loops_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/loops_computation.cpp