HDL_manager Class Reference
#include <HDL_manager.hpp>
Public Member Functions
HDL_manager (const HLS_managerRef hls_manager, const target_deviceRef device, const ParameterConstRef parameters)
Constructor.
HDL_manager (const HLS_managerRef HLSMgr, const target_deviceRef device, const structural_managerRef SM, const ParameterConstRef parameters)
Constructor.
~HDL_manager ()
Destructor.
void hdl_gen (const std::string &file_name, const std::list< structural_objectRef > &cirs, bool equation, std::list< std::string > &hdl_files, std::list< std::string > &aux_files)
Generates HDL code.
Static Public Member Functions
static std::string convert_to_identifier (const language_writer *lan, const std::string &id)
Converts a generic string to a language compliant identifier.
static std::string convert_to_identifier (const std::string &id)
Converts a generic string to a language compliant identifier.
static std::string get_mod_typename (const language_writer *lan, const structural_objectRef &cir)
Returns the module typename taking into account even the flopoco customizations.
Private Member Functions
void get_post_order_structural_components (const structural_objectRef cir, std::list< structural_objectRef > &list_of_com) const
Returns the list of components that have a structural-based description.
std::string write_components (const std::string &filename, const HDLWriter_Language language, const std::list< structural_objectRef > &components, bool equation, std::list< std::string > &aux_files) const
Generates the HDL description for the given components in the specified language.
void write_components (const std::string &filename, const std::list< structural_objectRef > &components, bool equation, std::list< std::string > &hdl_files, std::list< std::string > &aux_files)
Determines the proper language for each component and generates the corresponding HDL descriptions.
void write_module (const language_writerRef writer, const structural_objectRef cir, bool equation, std::list< std::string > &aux_files) const
Writes the module description.
void write_flopoco_module (const structural_objectRef &cir, std::list< std::string > &aux_files) const
Writes the FloPoCo module description to a VHDL file.
void io_signal_fix_ith (const language_writerRef writer, const structural_objectRef po, bool &lspf) const
Writes signal port connection post fix.
bool is_fsm (const structural_objectRef &cir) const
Returns true if the module has a FSM description associated with, false otherwise.
void write_fsm (const language_writerRef writer, const structural_objectRef &cir, const std::string &fsm_desc) const
Writes a mealy/moore finite state machine behavioral description.
void write_behavioral (const language_writerRef writer, const structural_objectRef &cir, const std::string &behav) const
Writes the behavioral description associated with the component.
Private Attributes
const HLS_managerRef HLSMgr
The high level synthesis manager.
const target_deviceRef device
reference to the target device
const technology_managerConstRef TM
reference to the class containing all the technology information
const structural_managerRef SM
The structural manager containing top.
const ParameterConstRef parameters
The set of input parameters.
const int debug_level
The debug level.
Detailed Description
Definition at line 76 of file HDL_manager.hpp.
Constructor & Destructor Documentation
HDL_manager() [1/2]
HDL_manager::HDL_manager (const HLS_managerRef hls_manager, const target_deviceRef device, const ParameterConstRef parameters)
Constructor.
Parameters
hls_manager is the high level synthesis manager
device is the data structure containing information about the target device
parameters is the data structure containing all the parameters
Definition at line 111 of file HDL_manager.cpp.
References ~HDL_manager().
HDL_manager() [2/2]
HDL_manager::HDL_manager (const HLS_managerRef _HLSMgr, const target_deviceRef _device, const structural_managerRef _SM, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
HLS is the high level synthesis manager
device is the data structure containing information about the target device
SM is the structural manager containing the top component
parameters is the data structure containing all the parameters
Autoheader include boost include design_flows include design_flows/backend/ToHDL includes HLS include STL include technology includes
Definition at line 98 of file HDL_manager.cpp.
 HDL_manager()
HDL_manager::~HDL_manager () [default]
Destructor.
Referenced by HDL_manager().
Member Function Documentation
convert_to_identifier() [1/2]
std::string HDL_manager::convert_to_identifier (const language_writer * lan, const std::string & id) [static]
Converts a generic string to a language compliant identifier.
Definition at line 1061 of file HDL_manager.cpp.
References language_writer::check_keyword(), and THROW_UNREACHABLE.
Referenced by convert_to_identifier(), fix_identifier(), get_mod_typename(), TestbenchGenerationBaseStep::initialize_input_signals(), VHDL_writer::type_converter_size(), TestbenchGenerationBaseStep::write_auxiliary_signal_declaration(), WishboneInterfaceTestbench::write_call(), WishboneInterfaceTestbench::write_file_reading_operations(), MinimalInterfaceTestbench::write_file_reading_operations(), write_flopoco_module(), write_fsm(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), VHDL_writer::write_io_signal_post_fix(), verilog_writer::write_io_signal_post_fix(), write_module(), verilog_writer::write_module_declaration(), VHDL_writer::write_module_declaration(), VHDL_writer::write_module_definition_end(), verilog_writer::write_module_instance_begin(), VHDL_writer::write_module_instance_begin(), TestbenchGenerationBaseStep::write_module_instantiation(), VHDL_writer::write_module_internal_declaration(), VHDL_writer::write_module_parametrization(), VHDL_writer::write_module_parametrization_decl(), system_verilog_writer::write_NP_functionalities(), VHDL_writer::write_NP_functionalities(), verilog_writer::write_NP_functionalities(), TestbenchGenerationBaseStep::write_output_checks(), MinimalInterfaceTestbench::write_output_signal_declaration(), verilog_writer::write_port_binding(), VHDL_writer::write_port_binding(), verilog_writer::write_port_declaration(), VHDL_writer::write_port_declaration(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), WishboneInterfaceTestbench::write_signals(), MinimalInterfaceTestbench::write_slave_initializations(), verilog_writer::write_state_declaration(), VHDL_writer::write_transition_output_functions(), verilog_writer::write_transition_output_functions(), verilog_writer::write_vector_port_binding(), VHDL_writer::write_vector_port_binding(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), WishboneInterfaceTestbench::write_wishbone_output_signal_declaration(), VHDL_writer::WriteBuiltin(), and verilog_writer::WriteBuiltin().
convert_to_identifier() [2/2]
std::string HDL_manager::convert_to_identifier (const std::string & id) [static]
Converts a generic string to a language compliant identifier.
Definition at line 1094 of file HDL_manager.cpp.
References convert_to_identifier().
get_mod_typename()
std::string HDL_manager::get_mod_typename (const language_writer * lan, const structural_objectRef & cir) [static]
Returns the module typename taking into account even the flopoco customizations.
Parameters
lan is the chosen language writer object.
cir is the module.
Definition at line 1100 of file HDL_manager.cpp.
References convert_to_identifier(), NP_functionality::FLOPOCO_PROVIDED, NP_functionality::get_NP_functionality(), GET_TYPE_NAME, PIPE_PARAMETER, STD_GET_SIZE, and STR.
Referenced by find_eq_module::operator()(), VHDL_writer::write_component_declaration(), write_module(), and TestbenchGenerationBaseStep::write_module_instantiation().
get_post_order_structural_components()
void HDL_manager::get_post_order_structural_components (const structural_objectRef cir, std::list< structural_objectRef > & list_of_com) const [private]
Returns the list of components that have a structural-based description.
This list of components is relative sorted such that if a component C_i uses a component C_j then C_j is before C_i. To obtain this list the hierarchy is visited in a post-order fashion.
Parameters
lan is the chosen language writer object.
cir is the structural object under analysis.
list_of_com is the list of components.
no action for signals and bus
Definition at line 380 of file HDL_manager.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, NP_functionality::exist_NP_functionality(), functional_unit_K, functional_unit_template_K, technology_node::get_kind(), structural_object::get_kind(), NP_functionality::get_NP_functionality(), GET_TYPE_NAME, NP_functionality::IP_COMPONENT, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ERROR, and TM.
Referenced by hdl_gen().
hdl_gen()
void HDL_manager::hdl_gen (const std::string & file_name, const std::list< structural_objectRef > & cirs, bool equation, std::list< std::string > & hdl_files, std::list< std::string > & aux_files)
Generates HDL code.
Parameters
file_name is the name to be created
cirs are the structural objects representing the components to be generated
equation specifies if the equation-based version of the component has to be generated
the created files (file_name + other files)
the created aux files
compute the list of components for which a structural description exist.
generate the HDL descriptions for all the components
Definition at line 323 of file HDL_manager.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, get_post_order_structural_components(), PRINT_DBG_MEX, THROW_ASSERT, and write_components().
io_signal_fix_ith()
void HDL_manager::io_signal_fix_ith (const language_writerRef writer, const structural_objectRef po, bool & lspf) const [private]
Writes signal port connection post fix.
Parameters
lan is the chosen language writer object.
po is the primary port.
lspf is true when the first post is written
Definition at line 473 of file HDL_manager.cpp.
References constant_o_K, structural_object::get_kind(), structural_object::get_owner(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, and THROW_ASSERT.
Referenced by write_module().
is_fsm()
bool HDL_manager::is_fsm (const structural_objectRef & cir) const [private]
Returns true if the module has a FSM description associated with, false otherwise.
Parameters
cir is the module.
check for a fsm description
Definition at line 367 of file HDL_manager.cpp.
References NP_functionality::exist_NP_functionality(), NP_functionality::FSM, NP_functionality::FSM_CS, NP_functionality::get_NP_functionality(), and THROW_ASSERT.
Referenced by write_module().
write_behavioral()
void HDL_manager::write_behavioral (const language_writerRef writer, const structural_objectRef & cir, const std::string & behav) const [private]
Writes the behavioral description associated with the component.
Parameters
writer is the chosen language writer object.
cir is the module.
behav is the string-based behavioral description.
Definition at line 957 of file HDL_manager.cpp.
References SplitString(), and THROW_ASSERT.
Referenced by write_module().
write_components() [1/2]
std::string HDL_manager::write_components (const std::string & filename, const HDLWriter_Language language, const std::list< structural_objectRef > & components, bool equation, std::list< std::string > & aux_files) const [private]
Generates the HDL description for the given components in the specified language.
write the header of the file
write all modules
we write the definition of the object stored in library
write the tail of the file
Definition at line 125 of file HDL_manager.cpp.
References language_writer::create_writer(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, NP_functionality::FLOPOCO_PROVIDED, NP_functionality::get_NP_functionality(), TimeStamp::GetCurrentTimeStamp(), INDENT_DBG_MEX, parameters, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, TM, VERILOG, NP_functionality::VERILOG_FILE_PROVIDED, VHDL, NP_functionality::VHDL_FILE_PROVIDED, and write_module().
Referenced by hdl_gen(), and write_components().
write_components() [2/2]
void HDL_manager::write_components (const std::string & filename, const std::list< structural_objectRef > & components, bool equation, std::list< std::string > & hdl_files, std::list< std::string > & aux_files) [private]
Determines the proper language for each component and generates the corresponding HDL descriptions.
default language
determine the proper language for each component
generate the auxiliary files
add the generated file to the global list
Definition at line 212 of file HDL_manager.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, NP_functionality::exist_NP_functionality(), NP_functionality::FLOPOCO_PROVIDED, NP_functionality::FSM, NP_functionality::FSM_CS, NP_functionality::get_NP_functionality(), parameters, PRINT_DBG_MEX, SYSTEM_VERILOG, NP_functionality::SYSTEM_VERILOG_PROVIDED, THROW_ASSERT, THROW_ERROR, THROW_WARNING, TM, test_panda::type, NP_functionality::UNKNOWN, VERILOG, NP_functionality::VERILOG_FILE_PROVIDED, NP_functionality::VERILOG_PROVIDED, VHDL, NP_functionality::VHDL_FILE_PROVIDED, NP_functionality::VHDL_PROVIDED, and write_components().
write_flopoco_module()
void HDL_manager::write_flopoco_module (const structural_objectRef & cir, std::list< std::string > & aux_files) const [private]
Writes the FloPoCo module description to a VHDL file.
Parameters
cir is the module to be fixed.
Definition at line 919 of file HDL_manager.cpp.
References convert_to_identifier(), debug_level, DEBUG_LEVEL_PEDANTIC, NP_functionality::FLOPOCO_PROVIDED, GET_TYPE_NAME, PIPE_PARAMETER, PRINT_DBG_MEX, STD_GET_SIZE, STR, and THROW_ERROR.
Referenced by write_module().
write_fsm()
void HDL_manager::write_fsm (const language_writerRef writer, const structural_objectRef & cir, const std::string & fsm_desc) const [private]
Writes a mealy/moore finite state machine behavioral description.
Parameters
writer is the chosen language writer object.
cir is the module.
fsm_desc is the string-based FSM description.
write state declaration.
write the present_state update
write transition and output functions
Definition at line 970 of file HDL_manager.cpp.
References convert_to_identifier(), debug_level, DEBUG_LEVEL_VERBOSE, device, structural_object::find_member(), refcount< T >::get(), NEXT_STATE_PORT_NAME, parameters, port_o_K, PRESENT_STATE_PORT_NAME, PRINT_DBG_MEX, SplitString(), THROW_ASSERT, and test_panda::tokens.
Referenced by write_module().
write_module()
void HDL_manager::write_module (const language_writerRef writer, const structural_objectRef cir, bool equation, std::list< std::string > & aux_files) const [private]
Writes the module description.
Parameters
lan is the chosen language writer object.
cir is the module to be written. The analysis does not consider the inner objects but just one level of the hierarchy.
write module declaration
write library declaration component
write IO port declarations
close the interface declaration and start the implementation
specify the timing annotations to the components
specify timing characterization
write components declarations write signal declarations
write module_instantiation begin
write module instantiation & connection binding
write IO ports binding
First output and then input. Some backend could have benefits from this ordering. Some customization are possible, like direct translation of gates into built-in statements.
write loop signal post fix
for generic ports the post fix is not required. A generic port is never attached to a signal.
check if there is some behavior attached to the module
write module_instantiation end
Definition at line 503 of file HDL_manager.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, convert_to_identifier(), data_o_K, debug_level, DEBUG_LEVEL_PARANOIC, DEBUG_LEVEL_VERY_PEDANTIC, NP_functionality::EQUATION, event_o_K, NP_functionality::exist_NP_functionality(), NP_functionality::FLOPOCO_PROVIDED, NP_functionality::FSM, NP_functionality::FSM_CS, functional_unit_K, functional_unit_template_K, refcount< T >::get(), module::get_authors(), structural_object::get_black_box(), module::get_copyright(), module::get_description(), module::get_gen_port(), module::get_gen_port_size(), structural_object::get_id(), module::get_in_out_port(), module::get_in_out_port_size(), module::get_in_port(), module::get_in_port_size(), module::get_internal_object(), module::get_internal_objects_size(), technology_node::get_kind(), module::get_license(), get_mod_typename(), NP_functionality::get_NP_functionality(), module::get_NP_functionality(), module::get_out_port(), module::get_out_port_size(), structural_object::get_path(), GET_TYPE_NAME, INDENT_DBG_MEX, io_signal_fix_ith(), NP_functionality::IP_COMPONENT, is_fsm(), parameters, port_o_K, port_vector_o_K, PRINT_DBG_MEX, signal_o_K, signal_vector_o_K, THROW_ASSERT, THROW_ERROR, TM, write_behavioral(), write_flopoco_module(), and write_fsm().
Referenced by write_components().
Field Documentation
debug_level
const int HDL_manager::debug_level [private]
The debug level.
Definition at line 100 of file HDL_manager.hpp.
Referenced by hdl_gen(), write_components(), write_flopoco_module(), write_fsm(), and write_module().
device
const target_deviceRef HDL_manager::device [private]
reference to the target device
Definition at line 83 of file HDL_manager.hpp.
Referenced by write_fsm().
HLSMgr
const HLS_managerRef HDL_manager::HLSMgr [private]
The high level synthesis manager.
Definition at line 80 of file HDL_manager.hpp.
parameters
const ParameterConstRef HDL_manager::parameters [private]
The set of input parameters.
Definition at line 97 of file HDL_manager.hpp.
Referenced by write_components(), write_fsm(), and write_module().
SM
const structural_managerRef HDL_manager::SM [private]
The structural manager containing top.
Definition at line 94 of file HDL_manager.hpp.
TM
const technology_managerConstRef HDL_manager::TM [private]
reference to the class containing all the technology information
Definition at line 86 of file HDL_manager.hpp.
Referenced by get_post_order_structural_components(), write_components(), and write_module().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/HDL_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/HDL_manager.cpp