DiscrepancyAnalysisCWriter Class Reference
#include <discrepancy_analysis_c_writer.hpp>
Public Member Functions
DiscrepancyAnalysisCWriter (const HLSCBackendInformationConstRef _hls_c_backend_information, const application_managerConstRef _AppM, const InstructionWriterRef _instruction_writer, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _parameters, bool _verbose)
Constructor.
~DiscrepancyAnalysisCWriter () override
Destructor.
void DeclareLocalVariables (const CustomSet< unsigned int > &to_be_declared, CustomSet< unsigned int > &already_declared_variables, CustomSet< std::string > &locally_declared_type, const BehavioralHelperConstRef BH, const var_pp_functorConstRef varFunc) override
Declares the local variable; in case the variable used in the initialization of curVar hasn't been declared yet it get declared.
void WriteFunctionDeclaration (const unsigned int funId) override
Writes the declaration of the function whose id in the tree is funId.
void WriteBuiltinWaitCall () override
Writes implementation of __builtin_wait_call.
Protected Member Functions
void WriteGlobalDeclarations () override
Writes the global declarations.
void WriteExtraInitCode () override
Write additional initialization code needed by subclasses.
void WriteExtraCodeBeforeEveryMainCall () override
virtual void WriteBBHeader (const unsigned int bb_number, const unsigned int function_index) override
void writePreInstructionInfo (const FunctionBehaviorConstRef FB, const vertex v) override
Write extra information on the given statement vertex, before the statement itself.
void writePostInstructionInfo (const FunctionBehaviorConstRef fun_behavior, const vertex) override
Write extra information on the given statement vertex, after the statement itself.
void WriteFunctionImplementation (unsigned int function_index) override
Write function implementation.
Protected Attributes
const DiscrepancyRef Discrepancy
Additional Inherited Members
Detailed Description
Definition at line 47 of file discrepancy_analysis_c_writer.hpp.
Constructor & Destructor Documentation
DiscrepancyAnalysisCWriter()
DiscrepancyAnalysisCWriter::DiscrepancyAnalysisCWriter (const HLSCBackendInformationConstRef _hls_c_backend_information, const application_managerConstRef _AppM, const InstructionWriterRef _instruction_writer, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _parameters, bool _verbose)
Constructor.
Definition at line 112 of file discrepancy_analysis_c_writer.cpp.
References CWriter::Param, STR, THROW_ASSERT, and ~DiscrepancyAnalysisCWriter().
 DiscrepancyAnalysisCWriter()
DiscrepancyAnalysisCWriter::~DiscrepancyAnalysisCWriter () [override], [default]
Destructor.
Referenced by DiscrepancyAnalysisCWriter().
Member Function Documentation
DeclareLocalVariables()
void DiscrepancyAnalysisCWriter::DeclareLocalVariables (const CustomSet< unsigned int > & to_be_declared, CustomSet< unsigned int > & already_declared_variables, CustomSet< std::string > & locally_declared_type, const BehavioralHelperConstRef BH, const var_pp_functorConstRef varFunc) [override], [virtual]
Declares the local variable; in case the variable used in the initialization of curVar hasn't been declared yet it get declared.
Parameters
to_be_declared is the set of variables which have to be declared
already_decl_variables is the set of already declared variables
locally_declared_type is the set of already declared types
helper is the behavioral helper associated with the function
varFunc is the printer functor
Reimplemented from CWriter.
Definition at line 626 of file discrepancy_analysis_c_writer.cpp.
References IndentedOutputStream::Append(), compute_n_bytes(), CWriter::DeclareLocalVariables(), BehavioralHelper::get_function_index(), BehavioralHelper::get_parameters(), HLSCWriter::hls_c_backend_information, CWriter::indented_output_stream, FunctionBehavior::is_variable_mem(), CWriter::Param, BehavioralHelper::PrintVariable(), tree_helper::size(), STR, THROW_ASSERT, and CWriter::TM.
WriteBBHeader()
void DiscrepancyAnalysisCWriter::WriteBBHeader (const unsigned int bb_number, const unsigned int function_index) [override], [protected], [virtual]
Reimplemented from CWriter.
Definition at line 678 of file discrepancy_analysis_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::indented_output_stream, and STR.
WriteBuiltinWaitCall()
void DiscrepancyAnalysisCWriter::WriteBuiltinWaitCall () [override], [virtual]
Writes implementation of __builtin_wait_call.
Reimplemented from HLSCWriter.
Definition at line 698 of file discrepancy_analysis_c_writer.cpp.
References CWriter::WriteBuiltinWaitCall().
WriteExtraCodeBeforeEveryMainCall()
void DiscrepancyAnalysisCWriter::WriteExtraCodeBeforeEveryMainCall () [override], [protected], [virtual]
Reimplemented from HLSCWriter.
Definition at line 621 of file discrepancy_analysis_c_writer.cpp.
References IndentedOutputStream::Append(), and CWriter::indented_output_stream.
WriteExtraInitCode()
void DiscrepancyAnalysisCWriter::WriteExtraInitCode () [override], [protected], [virtual]
Write additional initialization code needed by subclasses.
Reimplemented from HLSCWriter.
Definition at line 583 of file discrepancy_analysis_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, Discrepancy::c_trace_filename, FunctionBehavior::CGetBehavioralHelper(), compute_n_bytes(), BehavioralHelper::get_function_name(), HLSCWriter::hls_c_backend_information, CWriter::indented_output_stream, tree_helper::is_system(), CWriter::Param, BehavioralHelper::PrintVariable(), tree_helper::size(), STR, THROW_ASSERT, and CWriter::TM.
WriteFunctionDeclaration()
void DiscrepancyAnalysisCWriter::WriteFunctionDeclaration (const unsigned int funId) [override], [virtual]
Writes the declaration of the function whose id in the tree is funId.
Reimplemented from CWriter.
Definition at line 683 of file discrepancy_analysis_c_writer.cpp.
References CWriter::AppM, FunctionBehavior::CGetBehavioralHelper(), BehavioralHelper::get_function_name(), tree_helper::is_extern(), tree_helper::is_static(), THROW_ASSERT, CWriter::TM, and CWriter::WriteFunctionDeclaration().
WriteFunctionImplementation()
void DiscrepancyAnalysisCWriter::WriteFunctionImplementation (unsigned int function_index) [override], [protected], [virtual]
Write function implementation.
Parameters
function_id is the index of the function to be written
Reimplemented from HLSCWriter.
Definition at line 663 of file discrepancy_analysis_c_writer.cpp.
References CWriter::AppM, FunctionBehavior::CGetBehavioralHelper(), BehavioralHelper::get_function_name(), tree_helper::is_extern(), tree_helper::is_static(), THROW_ASSERT, CWriter::TM, and CWriter::WriteFunctionImplementation().
WriteGlobalDeclarations()
void DiscrepancyAnalysisCWriter::WriteGlobalDeclarations () [override], [protected], [virtual]
Writes the global declarations.
Reimplemented from HLSCWriter.
Definition at line 510 of file discrepancy_analysis_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::indented_output_stream, CWriter::Param, CWriter::WriteGlobalDeclarations(), HLSCWriter::WriteTestbenchGlobalVars(), and HLSCWriter::WriteTestbenchHelperFunctions().
writePostInstructionInfo()
void DiscrepancyAnalysisCWriter::writePostInstructionInfo (const FunctionBehaviorConstRef fun_behavior, const vertex statement) [override], [protected], [virtual]
Write extra information on the given statement vertex, after the statement itself.
check if we need to add a check for floating operation correctness
Reimplemented from CWriter.
Definition at line 175 of file discrepancy_analysis_c_writer.cpp.
References Discrepancy::address_ssa, IndentedOutputStream::Append(), CWriter::AppM, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), ENTRY_ID, EXIT_ID, FunctionBehavior::FCFG, BehavioralHelper::function_has_to_be_printed(), time_model::get_cycles(), BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), GET_INDEX_NODE, tree_node::get_kind(), operation::get_name(), GET_NODE, tree_helper::get_type_index(), tree_helper::GetElements(), BehavioralHelper::has_implementation(), HLSCWriter::hls_c_backend_information, CWriter::indented_output_stream, BehavioralHelper::is_a_complex(), BehavioralHelper::is_a_struct(), BehavioralHelper::is_a_vector(), BehavioralHelper::is_an_union(), operation::is_bounded(), is_large_integer(), BehavioralHelper::is_real(), Discrepancy::n_checked_operations, tree_helper::normalized_ID(), CWriter::Param, BehavioralHelper::PrintVariable(), tree_helper::size(), tree_helper::Size(), Discrepancy::ssa_to_skip, Discrepancy::ssa_to_skip_if_address, STR, THROW_ASSERT, THROW_ERROR, operation::time_m, and CWriter::TM.
writePreInstructionInfo()
void DiscrepancyAnalysisCWriter::writePreInstructionInfo (const FunctionBehaviorConstRef FB, const vertex v) [override], [protected], [virtual]
Write extra information on the given statement vertex, before the statement itself.
Reimplemented from CWriter.
Definition at line 123 of file discrepancy_analysis_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, BUILTIN_WAIT_CALL, FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), ENTRY_ID, EXIT_ID, FunctionBehavior::FCFG, BehavioralHelper::function_has_to_be_printed(), GET_NODE, BehavioralHelper::has_implementation(), CWriter::indented_output_stream, STR, THROW_ASSERT, and CWriter::TM.
Field Documentation
Discrepancy
const DiscrepancyRef DiscrepancyAnalysisCWriter::Discrepancy [protected]
Definition at line 50 of file discrepancy_analysis_c_writer.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/discrepancy_analysis_c_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/discrepancy_analysis_c_writer.cpp