/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/control_flow_checker.cpp File Reference
#include `control_flow_checker.hpp`
#include `function_behavior.hpp`
#include `structural_manager.hpp`
#include `hls.hpp`
#include `hls_manager.hpp`
#include `hls_target.hpp`
#include `Discrepancy.hpp`
#include `language_writer.hpp`
#include `state_transition_graph.hpp`
#include `state_transition_graph_manager.hpp`
#include <algorithm>
#include <string>
#include <tuple>
#include `custom_map.hpp`
#include `custom_set.hpp`
#include `behavioral_helper.hpp`
#include `Parameter.hpp`
#include `copyrights_strings.hpp`
#include `string_manipulation.hpp`
#include <boost/algorithm/string/case_conv.hpp>
Functions
static bool is_one_hot (const HLS_managerRef HLSMgr, unsigned int function_id)
static unsigned int comp_state_bitsize (bool one_hot_encoding, const HLS_managerRef HLSMgr, const unsigned int f_id, unsigned max_value)
static std::string create_control_flow_checker (size_t epp_trace_bitsize, const unsigned int f_id, const StateTransitionGraphManagerRef &STG, const HLS_managerRef HLSMgr, const HWDiscrepancyInfoConstRef &discr_info, bool one_hot_encoding, unsigned max_value, unsigned int state_bitsize, int DEBUG_PARAMETER(debug_level))
Function Documentation
comp_state_bitsize()
static unsigned int comp_state_bitsize (bool one_hot_encoding, const HLS_managerRef HLSMgr, const unsigned int f_id, unsigned max_value) [static]
Definition at line 127 of file control_flow_checker.cpp.
References language_writer::bitnumber().
Referenced by ControlFlowChecker::InternalExec().
create_control_flow_checker()
static std::string create_control_flow_checker (size_t epp_trace_bitsize, const unsigned int f_id, const StateTransitionGraphManagerRef & STG, const HLS_managerRef HLSMgr, const HWDiscrepancyInfoConstRef & discr_info, bool one_hot_encoding, unsigned max_value, unsigned int state_bitsize, int DEBUG_PARAMETERdebug_level) [static]
adjust in case states are not consecutive
Definition at line 139 of file control_flow_checker.cpp.
References StateTransitionGraphManager::CGetAstg(), StateTransitionGraphManager::CGetEPPStg(), StateTransitionGraphManager::CGetStg(), CLOCK_PORT_NAME, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, NEXT_STATE_PORT_NAME, PRESENT_STATE_PORT_NAME, PRINT_DBG_MEX, RESET_PORT_NAME, result, START_PORT_NAME, STR, and THROW_ASSERT.
Referenced by ControlFlowChecker::InternalExec().
is_one_hot()
static bool is_one_hot (const HLS_managerRef HLSMgr, unsigned int function_id) [static]
Definition at line 109 of file control_flow_checker.cpp.
Referenced by ControlFlowChecker::InternalExec().