vertex2obj< data_obj > Struct Template Reference
Class managing map of the vertexes on a generic object.
#include <Vertex.hpp>
Public Member Functions
vertex2obj ()=default
Constructor.
virtual ~vertex2obj ()
Destructor.
virtual void print_el (std::ostream &os, const graph *, typename vertex2obj< data_obj >::const_iterator &it) const
Function that print the information associated with a vertex.
virtual void print_rowHead (std::ostream &os, const graph *data, typename vertex2obj< data_obj >::const_iterator &it) const
Function that print the name and the operation performed by the vertex.
virtual void print (std::ostream &os, const graph *data=nullptr) const
Function that prints the class vertex2obj.
const data_obj operator() (const vertex &__k) const
template<class Iterator , class data_type >
void resize (Iterator left, Iterator right, data_type val)
Friends
std::ostream & operator<< (std::ostream &os, vertex2obj &s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const vertex2obj *s)
Friend definition of the << operator.
Detailed Description
template<class data_obj>
struct vertex2obj< data_obj >
Class managing map of the vertexes on a generic object.
Definition at line 59 of file Vertex.hpp.
Constructor & Destructor Documentation
vertex2obj()
template<class data_obj>
vertex2obj< data_obj >::vertex2obj () [default]
Constructor.
 vertex2obj()
template<class data_obj>
virtual vertex2obj< data_obj >::~vertex2obj () [inline], [virtual]
Destructor.
Definition at line 69 of file Vertex.hpp.
Member Function Documentation
operator()()
template<class data_obj>
const data_obj vertex2obj< data_obj >::operator() (const vertex & __k) const [inline]
Definition at line 119 of file Vertex.hpp.
print()
template<class data_obj>
virtual void vertex2obj< data_obj >::print (std::ostream & os, const graph * data = nullptr) const [inline], [virtual]
Function that prints the class vertex2obj.
Parameters
os is the output stream
Definition at line 103 of file Vertex.hpp.
print_el()
template<class data_obj>
virtual void vertex2obj< data_obj >::print_el (std::ostream & os, const graph * , typename vertex2obj< data_obj >::const_iterator & it) const [inline], [virtual]
Function that print the information associated with a vertex.
Parameters
os is the output stream
Definition at line 77 of file Vertex.hpp.
Referenced by vertex2obj< dataType >::print().
print_rowHead()
template<class data_obj>
virtual void vertex2obj< data_obj >::print_rowHead (std::ostream & os, const graph * data, typename vertex2obj< data_obj >::const_iterator & it) const [inline], [virtual]
Function that print the name and the operation performed by the vertex.
Parameters
os is the output stream
os << GET_NAME(data, it->first) + `(` + GET_OP(data, it->first) + `)`;
Definition at line 86 of file Vertex.hpp.
Referenced by vertex2obj< dataType >::print().
resize()
template<class data_obj>
template<class Iterator , class data_type >
void vertex2obj< data_obj >::resize (Iterator left, Iterator right, data_type val) [inline]
Definition at line 125 of file Vertex.hpp.
Referenced by ASLAP::add_constraints_to_ALAP(), ASLAP::add_constraints_to_ASAP(), ASLAP::compute_ALAP_fast(), and ASLAP::compute_ASAP().
Friends And Related Function Documentation
operator<< [1/2]
template<class data_obj>
std::ostream& operator<< (std::ostream & os, vertex2obj< data_obj > & s) [friend]
Friend definition of the << operator.
Parameters
os is the output stream
Definition at line 135 of file Vertex.hpp.
operator<< [2/2]
template<class data_obj>
std::ostream& operator<< (std::ostream & os, const vertex2obj< data_obj > * s) [friend]
Friend definition of the << operator.
Pointer version.
Parameters
os is the output stream
Definition at line 145 of file Vertex.hpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/graph/Vertex.hpp