/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/progModels/actor_graph_backend.hpp File Reference
Abstract class to write an actor graphs.
#include `config_HAVE_GRAPH_PARTITIONING_BUILT.hpp`
#include `config_HAVE_MPPB.hpp`
#include `actor_graph_backend.hpp`
#include `refcount.hpp`
#include `custom_map.hpp`
Data Structures
class ActorGraphBackend
Typedefs
typedef refcount< ActorGraphBackend > ActorGraphBackendRef
Enumerations
enum ActorGraphBackend_Type { ActorGraphBackend_Type::BA_NONE
 }
C thread backend to be used.
Functions
REF_FORWARD_DECL (ActorGraphBackend)
Autoheader includes.
REF_FORWARD_DECL (ActorGraphWriter)
CONSTREF_FORWARD_DECL (ActorGraphManager)
REF_FORWARD_DECL (CWriter)
REF_FORWARD_DECL (IndentedOutputStream)
CONSTREF_FORWARD_DECL (Parameter)
CONSTREF_FORWARD_DECL (PartitioningManager)
std::string ToString (ActorGraphBackend_Type actor_graph_backend_type)
Header include.
Detailed Description
Abstract class to write an actor graphs.
Author
Marco Lattuada lattuada@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Typedef Documentation
ActorGraphBackendRef
typedef refcount<ActorGraphBackend> ActorGraphBackendRef
Definition at line 146 of file actor_graph_backend.hpp.
Enumeration Type Documentation
ActorGraphBackend_Type
enum ActorGraphBackend_Type [strong]
C thread backend to be used.
Enumerator
BA_NONE Plain backend.
Definition at line 72 of file actor_graph_backend.hpp.
Function Documentation
CONSTREF_FORWARD_DECL() [1/3]
CONSTREF_FORWARD_DECL (ActorGraphManager)
CONSTREF_FORWARD_DECL() [2/3]
CONSTREF_FORWARD_DECL (Parameter)
CONSTREF_FORWARD_DECL() [3/3]
CONSTREF_FORWARD_DECL (PartitioningManager)
REF_FORWARD_DECL() [1/4]
REF_FORWARD_DECL (ActorGraphBackend)
Autoheader includes.
intermediate_representations/actor_graphs include utility includes STL include
REF_FORWARD_DECL() [2/4]
REF_FORWARD_DECL (ActorGraphWriter)
REF_FORWARD_DECL() [3/4]
REF_FORWARD_DECL (CWriter)
REF_FORWARD_DECL() [4/4]
REF_FORWARD_DECL (IndentedOutputStream)
ToString()
std::string ToString (ActorGraphBackend_Type actor_graph_backend_type)
Header include.
. includes
Definition at line 52 of file actor_graph_backend.cpp.
References BA_NONE, and THROW_UNREACHABLE.
Referenced by dead_code_elimination::add_gimple_nop(), IR_lowering::array_ref_lowering(), mux_connection_binding::create_connections(), ipa_point_to_analysis::Exec(), IR_lowering::expand_target_mem_ref(), memory_allocation::finalize_memory_allocation(), parm_decl_taken_address_fix::InternalExec(), FixStructsPassedByValue::InternalExec(), FunctionCallTypeCleanup::InternalExec(), BasicBlocksCfgComputation::InternalExec(), SwitchFix::InternalExec(), call_expr_fix::InternalExec(), compute_implicit_calls::InternalExec(), fanout_opt::InternalExec(), BuildVirtualPhi::InternalExec(), hls_div_cg_ext::InternalExec(), CSE::InternalExec(), IR_lowering::InternalExec(), PhiOpt::InternalExec(), rebuild_initialization2::look_for_ROMs(), Bit_Value_opt::optimize(), hls_div_cg_ext::recursive_examinate(), fu_binding::specialise_fu(), and tree_node::~tree_node().