weighted_clique_register Class Reference
#include <weighted_clique_register.hpp>
Public Member Functions
weighted_clique_register (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
Constructor of the class.
~weighted_clique_register () override
Destructor of the class.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Additional Inherited Members
Detailed Description
Definition at line 72 of file weighted_clique_register.hpp.
Constructor & Destructor Documentation
weighted_clique_register()
weighted_clique_register::weighted_clique_register (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
Constructor of the class.
Parameters
design_flow_manager is the design flow manager
Definition at line 85 of file weighted_clique_register.cpp.
References ~weighted_clique_register().
 weighted_clique_register()
weighted_clique_register::~weighted_clique_register () [override], [default]
Destructor of the class.
Referenced by weighted_clique_register().
Member Function Documentation
Initialize()
void weighted_clique_register::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 95 of file weighted_clique_register.cpp.
References reg_binding::create_reg_binding(), HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), and hls::Rreg.
InternalExec()
DesignFlowStep_Status weighted_clique_register::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
performing clique covering
vertex to clique map
retrieve the solution
finalize
Implements HLSFunctionStep.
Definition at line 101 of file weighted_clique_register.cpp.
References reg_binding::bind(), compatibility_based_register::CG, FunctionBehavior::CGetBehavioralHelper(), compatibility_based_register::create_compatibility_graph(), reg_binding::create_reg_binding(), clique_covering< VertexType >::create_solver(), HLSFunctionStep::funId, BehavioralHelper::get_function_name(), liveness::get_live_in(), StorageValueInformation::get_storage_value_index(), liveness::get_support(), HLSFunctionStep::HLS, HLS_step::hls_flow_step_specialization, HLS_step::HLSMgr, INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, variable2obj< data_obj >::print(), print_cpu_time(), reg_binding_creator::register_lower_bound, hls::Rliv, hls::Rreg, reg_binding::set_used_regs(), START_TIME, STOP_TIME, hls::storage_value_information, STR, SUCCESS, and compatibility_based_register::verts.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/weighted_clique_register.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/weighted_clique_register.cpp