AsnType Class Reference
#include <asn_type.hpp>
Public Member Functions
AsnType (const AsnType_Kind kind)
Constructor.
virtual ~AsnType ()
Destructor.
AsnType_Kind GetKind ()
Return the type.
Protected Attributes
const AsnType_Kind kind
The actual kind.
Detailed Description
Definition at line 70 of file asn_type.hpp.
Constructor & Destructor Documentation
AsnType()
AsnType::AsnType (const AsnType_Kind _kind) [explicit]
Constructor.
Header include.
booost include utility includ
Definition at line 51 of file asn_type.cpp.
References ~AsnType().
 AsnType()
AsnType::~AsnType () [virtual], [default]
Destructor.
Referenced by AsnType().
Member Function Documentation
GetKind()
AsnType_Kind AsnType::GetKind ()
Return the type.
Definition at line 57 of file asn_type.cpp.
References kind.
Referenced by CreateAddressTranslation::ComputeAddress().
Field Documentation
kind
const AsnType_Kind AsnType::kind [protected]
The actual kind.
Definition at line 74 of file asn_type.hpp.
Referenced by GetKind().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/aadl_asn/asn_type.hpp
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/aadl_asn/asn_type.cpp