BBCdgComputation Class Reference
Superclass include.
#include <bb_cdg_computation.hpp>
Public Member Functions
BBCdgComputation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~BBCdgComputation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the computation of the CDG representation.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
loops computation analysis step
Definition at line 49 of file bb_cdg_computation.hpp.
Constructor & Destructor Documentation
BBCdgComputation()
BBCdgComputation::BBCdgComputation (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
. include algorithms/dominance include behavior include
Definition at line 56 of file bb_cdg_computation.cpp.
References ~BBCdgComputation().
 BBCdgComputation()
BBCdgComputation::~BBCdgComputation () [override], [default]
Destructor.
Referenced by BBCdgComputation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BBCdgComputation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 63 of file bb_cdg_computation.cpp.
References BB_FEEDBACK_EDGES_IDENTIFICATION, BB_ORDER_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DOM_POST_DOM_COMPUTATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void BBCdgComputation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 88 of file bb_cdg_computation.cpp.
References FunctionFrontendFlowStep::bb_version, FunctionBehavior::CDG_BB, CDG_SELECTOR, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status BBCdgComputation::InternalExec () [override], [virtual]
Performs the computation of the CDG representation.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 104 of file bb_cdg_computation.cpp.
References A, FunctionBehavior::BB, FunctionBehavior::CDG_BB, CDG_SELECTOR, CFG_SELECTOR, BBGraph::CGetBBEdgeInfo(), counter, FunctionFrontendFlowStep::function_behavior, dominance< GraphObj >::get_immediate_dominator(), BBGraph::GetBBNodeInfo(), DesignFlowStep::parameters, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/bb_cdg_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/bb_cdg_computation.cpp