OpOrderComputation Class Reference
Superclass include.
#include <op_order_computation.hpp>
Public Member Functions
OpOrderComputation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~OpOrderComputation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes a topological order of the operations according to the control flow graph.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Compute a topological order of the operations according to the control flow graph + flow edges
Definition at line 50 of file op_order_computation.hpp.
Constructor & Destructor Documentation
OpOrderComputation()
OpOrderComputation::OpOrderComputation (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
. include behavior include
Definition at line 57 of file op_order_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~OpOrderComputation().
 OpOrderComputation()
OpOrderComputation::~OpOrderComputation () [override], [default]
Destructor.
Referenced by OpOrderComputation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > OpOrderComputation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 65 of file op_order_computation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, OP_FEEDBACK_EDGES_IDENTIFICATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void OpOrderComputation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 88 of file op_order_computation.cpp.
References FunctionFrontendFlowStep::bb_version, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status OpOrderComputation::InternalExec () [override], [virtual]
Computes a topological order of the operations according to the control flow graph.
Returns
the exit status of this step
Mark for visit in different functions.
MARK initialization
Examining successors
Checking if all successor's predecessors have been examinated
Vertex can be added to list
Checking if EXIT has been added
Implements FunctionFrontendFlowStep.
Definition at line 97 of file op_order_computation.cpp.
References CFG_TRUE_CHECK, OpGraph::CGetOpGraphInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::ECFG, ENTRY, EXIT, FunctionFrontendFlowStep::function_behavior, GET_NAME, INDENT_DBG_MEX, index, NULL_VERTEX, SUCCESS, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/op_order_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/op_order_computation.cpp