functional_unit_template Struct Reference
This class describe a functional unit template.
#include <technology_node.hpp>
Public Member Functions
const std::string & get_name () const override
Return the name of the operation.
void xload (const xml_element *Enode, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) override
Load a functional unit starting from an xml file.
void xwrite (xml_element *rootnode, const technology_nodeRef tn, const ParameterConstRef Param, TargetDevice_Type type) override
Add a functional unit to an xml tree.
void lib_write (std::ofstream &os, const simple_indentRef PP) override
Append a technology_node to a liberty file.
void lef_write (std::ofstream &os, const simple_indentRef PP) override
Append a technology_node to a LEF file.
void print (std::ostream &os) const override
function that prints the class functional_unit.
functional_unit_template ()
Constructor.
functional_unit_template (const xml_nodeRef XML_description)
Data Fields
technology_nodeRef FU
Functional Unit.
std::string specialized
when non empty it defines with respect what the functional unit template has been specialized
std::string characterizing_constant_value
Value used during the characterization of templates.
std::string memory_type
Specify the type of memory the functional unit is compliant with.
std::string channels_type
Specify the type of the channel the functional unit is compliant with.
std::string memory_ctrl_type
Specify the type of memory controller the functional unit is compliant with.
std::string bram_load_latency
Specify the bram load latency the functional unit is compliant with.
bool no_constant_characterization
The template will not consider constants connected to the inputs during the module characterization.
Additional Inherited Members
Detailed Description
This class describe a functional unit template.
Definition at line 733 of file technology_node.hpp.
Constructor & Destructor Documentation
functional_unit_template() [1/2]
functional_unit_template::functional_unit_template ()
Constructor.
Definition at line 1306 of file technology_node.cpp.
functional_unit_template() [2/2]
functional_unit_template::functional_unit_template (const xml_nodeRef XML_description) [explicit]
Definition at line 1310 of file technology_node.cpp.
Member Function Documentation
get_name()
const std::string& functional_unit_template::get_name () const [inline], [override], [virtual]
Return the name of the operation.
Implements technology_node.
Definition at line 772 of file technology_node.hpp.
References technology_node::get_name(), GET_TEC_KIND, GET_TEC_KIND_TEXT, technology_node::lef_write(), technology_node::lib_write(), technology_node::PP, technology_node::print(), test_panda::type, technology_node::xload(), and technology_node::xwrite().
lef_write()
void functional_unit_template::lef_write (std::ofstream & os, const simple_indentRef PP) [override], [virtual]
Append a technology_node to a LEF file.
Implements technology_node.
Definition at line 1422 of file technology_node.cpp.
References THROW_UNREACHABLE.
lib_write()
void functional_unit_template::lib_write (std::ofstream & os, const simple_indentRef PP) [override], [virtual]
Append a technology_node to a liberty file.
Implements technology_node.
Definition at line 1417 of file technology_node.cpp.
References THROW_UNREACHABLE.
print()
void functional_unit_template::print (std::ostream & os) const [override], [virtual]
function that prints the class functional_unit.
Parameters
os is the output stream.
Implements technology_node.
Definition at line 1427 of file technology_node.cpp.
References FU, and technology_node::print().
xload()
void functional_unit_template::xload (const xml_element * Enode, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) [override], [virtual]
Load a functional unit starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
Implements technology_node.
Definition at line 1314 of file technology_node.cpp.
References bram_load_latency, channels_type, characterizing_constant_value, xml_node::convert_escaped(), FU, xml_child::get_children(), GET_CLASS_NAME, xml_text_node::get_content(), memory_ctrl_type, memory_type, no_constant_characterization, specialized, THROW_ERROR, and technology_node::xload().
xwrite()
void functional_unit_template::xwrite (xml_element * rootnode, const technology_nodeRef tn, const ParameterConstRef Param, TargetDevice_Type type) [override], [virtual]
Add a functional unit to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the functional unit is attached.
Implements technology_node.
Definition at line 1378 of file technology_node.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), bram_load_latency, channels_type, characterizing_constant_value, FU, GET_CLASS_NAME, memory_ctrl_type, memory_type, no_constant_characterization, specialized, and technology_node::xwrite().
Field Documentation
bram_load_latency
std::string functional_unit_template::bram_load_latency
Specify the bram load latency the functional unit is compliant with.
non-null only in case the functional unit is a memory or a memory controller.
Definition at line 757 of file technology_node.hpp.
Referenced by xload(), and xwrite().
channels_type
std::string functional_unit_template::channels_type
Specify the type of the channel the functional unit is compliant with.
Definition at line 749 of file technology_node.hpp.
Referenced by xload(), and xwrite().
characterizing_constant_value
std::string functional_unit_template::characterizing_constant_value
Value used during the characterization of templates.
Definition at line 742 of file technology_node.hpp.
Referenced by xload(), and xwrite().
FU
technology_nodeRef functional_unit_template::FU
Functional Unit.
Definition at line 736 of file technology_node.hpp.
Referenced by allocation::get_compliant_pipelined_unit(), print(), xload(), and xwrite().
memory_ctrl_type
std::string functional_unit_template::memory_ctrl_type
Specify the type of memory controller the functional unit is compliant with.
non-null only in case the functional unit is a memory controller.
Definition at line 753 of file technology_node.hpp.
Referenced by xload(), and xwrite().
memory_type
std::string functional_unit_template::memory_type
Specify the type of memory the functional unit is compliant with.
non-null only in case the functional unit is a memory.
Definition at line 746 of file technology_node.hpp.
Referenced by xload(), and xwrite().
no_constant_characterization
bool functional_unit_template::no_constant_characterization
The template will not consider constants connected to the inputs during the module characterization.
Definition at line 760 of file technology_node.hpp.
Referenced by xload(), and xwrite().
specialized
std::string functional_unit_template::specialized
when non empty it defines with respect what the functional unit template has been specialized
Definition at line 739 of file technology_node.hpp.
Referenced by xload(), and xwrite().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.cpp