ToDataFileStepFactory Class Reference
#include <to_data_file_step_factory.hpp>
Public Member Functions
ToDataFileStepFactory (const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~ToDataFileStepFactory () override
Destructor.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
const DesignFlowStepRef CreateStep (const std::string &signature) const
Creates a step.
Additional Inherited Members
Detailed Description
Definition at line 56 of file to_data_file_step_factory.hpp.
Constructor & Destructor Documentation
ToDataFileStepFactory()
ToDataFileStepFactory::ToDataFileStepFactory (const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
utility include
Parameters
target is the target device
design_flow_manager is the design flow manager
parameters is the set of input parameters
design_flows/ToDataFile include
Definition at line 52 of file to_data_file_step_factory.cpp.
References ~ToDataFileStepFactory().
 ToDataFileStepFactory()
ToDataFileStepFactory::~ToDataFileStepFactory () [override], [default]
Destructor.
Referenced by ToDataFileStepFactory().
Member Function Documentation
CreateStep()
const DesignFlowStepRef ToDataFileStepFactory::CreateStep (const std::string & signature) const
Creates a step.
Parameters
signature is the signature of the step to be created
Returns
the created step
Definition at line 72 of file to_data_file_step_factory.cpp.
References DesignFlowStepFactory::design_flow_manager, Wrefcount< T >::lock(), ToDataFileStep::NameToEnum(), DesignFlowStepFactory::parameters, THROW_ASSERT, THROW_UNREACHABLE, and UNKNOWN.
GetPrefix()
const std::string ToDataFileStepFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 67 of file to_data_file_step_factory.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/to_data_file_step_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/to_data_file_step_factory.cpp