extract_patterns Class Reference
Class extracting patterns extending the GCC IR.
#include <extract_patterns.hpp>
Public Member Functions
extract_patterns (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~extract_patterns () override
Destructor.
DesignFlowStep_Status InternalExec () override
Extract patterns from the GCC IR.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void ternary_plus_expr_extraction (statement_list *sl, tree_managerRef TM)
look for ternary plus expressions
Additional Inherited Members
Detailed Description
Class extracting patterns extending the GCC IR.
Definition at line 62 of file extract_patterns.hpp.
Constructor & Destructor Documentation
extract_patterns()
extract_patterns::extract_patterns (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
_Param is the set of the parameters
_AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
Definition at line 70 of file extract_patterns.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~extract_patterns().
 extract_patterns()
extract_patterns::~extract_patterns () [override], [default]
Destructor.
Referenced by extract_patterns().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > extract_patterns::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 78 of file extract_patterns.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and USE_COUNTING.
InternalExec()
DesignFlowStep_Status extract_patterns::InternalExec () [override], [virtual]
Extract patterns from the GCC IR.
Returns
the exit status of this step
for each basic block B in CFG do > Consider all blocks successively
Implements FunctionFrontendFlowStep.
Definition at line 213 of file extract_patterns.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), PRINT_DBG_MEX, sl, SUCCESS, ternary_plus_expr_extraction(), and THROW_ASSERT.
ternary_plus_expr_extraction()
void extract_patterns::ternary_plus_expr_extraction (statement_list * sl, tree_managerRef TM) [private]
look for ternary plus expressions
Parameters
sl is the statement list
TM is the tree manager
manage capacity
matched
Definition at line 129 of file extract_patterns.cpp.
References FrontendFlowStep::AppM, tree_manipulation::create_ternary_operation(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, tree_helper::get_type_node(), FunctionFrontendFlowStep::GetName(), INDENT_DBG_MEX, tree_helper::is_a_complex(), tree_helper::is_a_vector(), tree_helper::is_real(), statement_list::list_of_bloc, DesignFlowStep::parameters, tree_helper::Size(), STR, ternary_operation_type0(), and ternary_operation_type1().
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/extract_patterns.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/extract_patterns.cpp