FunctionEdgeWriter Class Reference
Functor used by write_graphviz to write the edges of a function graph.
#include <call_graph.hpp>
Public Member Functions
FunctionEdgeWriter (const CallGraph *call_graph)
constructor
~FunctionEdgeWriter () override
Destructor.
void operator() (std::ostream &out, const EdgeDescriptor &e) const override
operator function returning the edge description
Private Attributes
const std::map< unsigned int, FunctionBehaviorRef > & behaviors
reference to the behaviors
Additional Inherited Members
Detailed Description
Functor used by write_graphviz to write the edges of a function graph.
Definition at line 240 of file call_graph.hpp.
Constructor & Destructor Documentation
FunctionEdgeWriter()
FunctionEdgeWriter::FunctionEdgeWriter (const CallGraph * call_graph) [explicit]
constructor
Parameters
g is the graph to be printed
Definition at line 128 of file call_graph.cpp.
References ~FunctionEdgeWriter().
 FunctionEdgeWriter()
FunctionEdgeWriter::~FunctionEdgeWriter () [override], [default]
Destructor.
Referenced by FunctionEdgeWriter().
Member Function Documentation
operator()()
void FunctionEdgeWriter::operator() (std::ostream & out, const EdgeDescriptor & e) const [override], [virtual]
operator function returning the edge description
Parameters
out is the output stream
e is the edge
Implements EdgeWriter.
Definition at line 134 of file call_graph.cpp.
References FEEDBACK_SELECTOR, graph::GetSelector(), EdgeWriter::printing_graph, STD_SELECTOR, and THROW_ERROR.
Field Documentation
behaviors
const std::map<unsigned int, FunctionBehaviorRef>& FunctionEdgeWriter::behaviors [private]
reference to the behaviors
Definition at line 244 of file call_graph.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph.cpp