xml_set_entry_t Class Reference
String entry of a multiple values variable (set).
#include <xml_script_command.hpp>
Public Member Functions
xml_set_entry_t (std::string _value, const std::string *_condition)
xml_set_entry_t (const xml_element *element)
~xml_set_entry_t () override
std::string get_xml_name () const override
Gets the XML element name of this node type.
xml_nodeRef create_xml_node () const override
Creates an XML node for polixml data structures.
void clean () override
Cleans object attributes.
bool checkCondition (const DesignParametersRef &dp) const override
If the node has a compile-time condition, this method evaluates it.
Data Fields
std::string value
std::string * condition
Additional Inherited Members
Detailed Description
String entry of a multiple values variable (set).
Definition at line 152 of file xml_script_command.hpp.
Constructor & Destructor Documentation
xml_set_entry_t() [1/2]
xml_set_entry_t::xml_set_entry_t (std::string _value, const std::string * _condition)
Definition at line 238 of file xml_script_command.cpp.
References condition.
xml_set_entry_t() [2/2]
xml_set_entry_t::xml_set_entry_t (const xml_element * element) [explicit]
Definition at line 243 of file xml_script_command.cpp.
References condition, attribute_sequence::get_attribute(), xml_attribute::get_value(), THROW_ERROR, and value.
 xml_set_entry_t()
xml_set_entry_t::~xml_set_entry_t () [override]
Definition at line 266 of file xml_script_command.cpp.
References clean().
Member Function Documentation
checkCondition()
bool xml_set_entry_t::checkCondition (const DesignParametersRef & dp) const [override], [virtual]
If the node has a compile-time condition, this method evaluates it.
Parameters
dp Design parameters, used to check conditions at compile time.
Returns
The condition evaluation if any, otherwise is true by default.
Reimplemented from xml_script_node_t.
Definition at line 294 of file xml_script_command.cpp.
References condition, and xml_script_node_t::evaluate_condition().
clean()
void xml_set_entry_t::clean () [override], [virtual]
Cleans object attributes.
Implements xml_script_node_t.
Definition at line 271 of file xml_script_command.cpp.
References condition.
Referenced by ~xml_set_entry_t().
create_xml_node()
xml_nodeRef xml_set_entry_t::create_xml_node () const [override], [virtual]
Creates an XML node for polixml data structures.
Implements xml_script_node_t.
Definition at line 283 of file xml_script_command.cpp.
References condition, get_xml_name(), attribute_sequence::set_attribute(), and value.
get_xml_name()
std::string xml_set_entry_t::get_xml_name () const [override], [virtual]
Gets the XML element name of this node type.
Implements xml_script_node_t.
Definition at line 278 of file xml_script_command.cpp.
References TAG_ENTRY.
Referenced by create_xml_node().
Field Documentation
condition
std::string* xml_set_entry_t::condition
Definition at line 156 of file xml_script_command.hpp.
Referenced by checkCondition(), clean(), create_xml_node(), and xml_set_entry_t().
value
std::string xml_set_entry_t::value
Definition at line 155 of file xml_script_command.hpp.
Referenced by create_xml_node(), NanoXploreWrapper::toString(), LatticeWrapper::toString(), AlteraWrapper::toString(), SynopsysWrapper::toString(), XilinxWrapper::toString(), and xml_set_entry_t().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xml_script_command.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xml_script_command.cpp