sched_based_chaining_computation Class Reference
#include <sched_based_chaining_computation.hpp>
Public Member Functions
sched_based_chaining_computation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~sched_based_chaining_computation () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Execute the step.
Additional Inherited Members
Detailed Description
Definition at line 46 of file sched_based_chaining_computation.hpp.
Constructor & Destructor Documentation
sched_based_chaining_computation()
sched_based_chaining_computation::sched_based_chaining_computation (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
STD include.
Parameters
design_flow_manager is the design flow manager
HLS/chaining includes
Definition at line 58 of file sched_based_chaining_computation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~sched_based_chaining_computation().
 sched_based_chaining_computation()
sched_based_chaining_computation::~sched_based_chaining_computation () [override], [default]
Destructor.
Referenced by sched_based_chaining_computation().
Member Function Documentation
Initialize()
void sched_based_chaining_computation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from chaining.
Definition at line 66 of file sched_based_chaining_computation.cpp.
References hls::chaining_information, HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, ChainingInformation::Initialize(), and HLSFunctionStep::Initialize().
InternalExec()
DesignFlowStep_Status sched_based_chaining_computation::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 73 of file sched_based_chaining_computation.cpp.
References ChainingInformation::add_chained_vertices_in(), ChainingInformation::add_chained_vertices_out(), FunctionBehavior::CGetOpGraph(), hls::chaining_information, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FLSAODG, HLSFunctionStep::funId, Schedule::get_cstep(), Schedule::get_cstep_end(), GET_NAME, HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, ChainingInformation::is_chained_with, hls::Rsch, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/chaining/sched_based_chaining_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/chaining/sched_based_chaining_computation.cpp