BitLatticeManipulator Class Reference
#include <bit_lattice.hpp>
Public Member Functions
BitLatticeManipulator (const tree_managerConstRef TM, const int debug_level)
Constructor.
~BitLatticeManipulator ()
Destructor.
Protected Member Functions
bit_lattice bit_sup (const bit_lattice a, const bit_lattice b) const
std::deque< bit_lattice > sup (const std::deque< bit_lattice > &a, const std::deque< bit_lattice > &b, const unsigned int output_uid) const
Computes the sup between two bitstrings.
bit_lattice bit_inf (const bit_lattice a, const bit_lattice b) const
std::deque< bit_lattice > inf (const std::deque< bit_lattice > &a, const std::deque< bit_lattice > &b, const unsigned int output_uid) const
Computes the inf between two bitstrings.
std::deque< bit_lattice > sign_extend_bitstring (const std::deque< bit_lattice > &bitstring, bool bitstring_is_signed, size_t final_size) const
Extends a bitstring.
void sign_reduce_bitstring (std::deque< bit_lattice > &bitstring, bool bitstring_is_signed) const
Reduce the size of a bitstring erasing all but one most significant zeros in unsigned bitstring and all but one most significant values in signed bitstrings.
std::deque< bit_lattice > constructor_bitstring (const tree_nodeRef &ctor_tn, unsigned int ssa_node_id) const
auxiliary function used to build the bitstring lattice for read-only arrays
std::deque< bit_lattice > string_cst_bitstring (const tree_nodeRef &strcst_tn, unsigned int ssa_node_id) const
auxiliary function used to build the bitstring lattice for read-only string_cst
bool is_handled_by_bitvalue (unsigned int type_id) const
Returns true if the type identified by type_id is handled by bitvalue analysis.
bool mix ()
Mixes the content of current and best using the sup operation, storing the result in the best map.
bool update_current (std::deque< bit_lattice > res, unsigned int output_uid)
Given a bitstring res, and the id of a tree node ouput_uid, this functions checks if it is necessary to update the bistring stored in the current map used by the bitvalue analysis algorithm.
void clear ()
Clean up the internal data structures.
Protected Attributes
const tree_managerConstRef TM
CustomUnorderedMap< unsigned int, std::deque< bit_lattice > > current
Map of the current bit-values of each variable.
CustomUnorderedMap< unsigned int, std::deque< bit_lattice > > best
Map of the best bit-values of each variable.
CustomUnorderedSet< unsigned int > signed_var
Set storing the signed ssa.
const int bl_debug_level
The debug level of methods of this class - it cannot be named debug_level because of ambiguity of FrontendFlowStep::debug_level derived classes.
Detailed Description
Definition at line 69 of file bit_lattice.hpp.
Constructor & Destructor Documentation
BitLatticeManipulator()
BitLatticeManipulator::BitLatticeManipulator (const tree_managerConstRef _TM, const int _bl_debug_level) [explicit]
Constructor.
Header include.
. include STD include STL includes tree includes utility includes
Definition at line 65 of file bit_lattice.cpp.
References ~BitLatticeManipulator().
 BitLatticeManipulator()
BitLatticeManipulator::~BitLatticeManipulator () [default]
Destructor.
Referenced by BitLatticeManipulator().
Member Function Documentation
bit_inf()
bit_lattice BitLatticeManipulator::bit_inf (const bit_lattice a, const bit_lattice b) const [protected]
Definition at line 218 of file bit_lattice.cpp.
References U, and X.
Referenced by Bit_Value::backward_transfer(), and inf().
bit_sup()
bit_lattice BitLatticeManipulator::bit_sup (const bit_lattice a, const bit_lattice b) const [protected]
Definition at line 71 of file bit_lattice.cpp.
References U, and X.
Referenced by sup().
clear()
void BitLatticeManipulator::clear () [protected]
Clean up the internal data structures.
Definition at line 469 of file bit_lattice.cpp.
References best, current, and signed_var.
Referenced by BitValueIPA::Exec(), Bit_Value::initialize(), and Bit_Value::InternalExec().
constructor_bitstring()
std::deque< bit_lattice > BitLatticeManipulator::constructor_bitstring (const tree_nodeRef & ctor_tn, unsigned int ssa_node_id) const [protected]
auxiliary function used to build the bitstring lattice for read-only arrays
Parameters
ctor_tn is the tree reindex or a tree node of the contructor
ssa_node_id is the ssa node id of the lattice destination
Definition at line 364 of file bit_lattice.cpp.
References create_bitstring_from_constant(), create_u_bitstring(), el, tree_helper::get_array_dim_and_bitsize(), GET_CONST_NODE, GET_INDEX_CONST_NODE, tree_node::get_kind(), GET_NODE, inf(), tree_helper::is_int(), STR, THROW_ASSERT, TM, tree_node::ToString(), test_panda::type, and X.
Referenced by Bit_Value::initialize().
inf()
std::deque< bit_lattice > BitLatticeManipulator::inf (const std::deque< bit_lattice > & a, const std::deque< bit_lattice > & b, const unsigned int output_uid) const [protected]
Computes the inf between two bitstrings.
Parameters
a first bitstring
b second bitstring
output_uid is the id of the tree node for which the bitvalue is * computed
Returns
inf between the two bitstrings
Definition at line 242 of file bit_lattice.cpp.
References bit_inf(), tree_helper::CGetType(), GET_NODE, tree_helper::get_type_index(), tree_helper::is_bool(), tree_helper::is_int(), sign_extend_bitstring(), sign_reduce_bitstring(), signed_var, tree_helper::size(), tree_helper::Size(), STR, THROW_ASSERT, THROW_UNREACHABLE, TM, and X.
Referenced by Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), constructor_bitstring(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), Bit_Value::initialize(), and string_cst_bitstring().
is_handled_by_bitvalue()
bool BitLatticeManipulator::is_handled_by_bitvalue (unsigned int type_id) const [protected]
Returns true if the type identified by type_id is handled by bitvalue analysis.
Definition at line 420 of file bit_lattice.cpp.
References tree_helper::is_a_complex(), tree_helper::is_a_struct(), tree_helper::is_a_vector(), tree_helper::is_real(), and TM.
Referenced by Bit_Value::backward(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), Bit_Value::initialize(), and Bit_Value::manage_forward_binary_operands().
mix()
bool BitLatticeManipulator::mix () [protected]
Mixes the content of current and best using the sup operation, storing the result in the best map.
Returns true if the best map was updated, false otherwise.
Definition at line 425 of file bit_lattice.cpp.
References best, bitstring_to_string(), bl_debug_level, current, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, STR, and sup().
Referenced by BitValueIPA::Exec(), and Bit_Value::InternalExec().
sign_extend_bitstring()
std::deque< bit_lattice > BitLatticeManipulator::sign_extend_bitstring (const std::deque< bit_lattice > & bitstring, bool bitstring_is_signed, size_t final_size) const [protected]
Extends a bitstring.
Parameters
bitstring to extend
bitstring_is_signed must be true if bitstring is signed
final_size desired length of the bitstrign
Returns
the extended bitstring
Definition at line 347 of file bit_lattice.cpp.
References THROW_ASSERT, X, and ZERO.
Referenced by Bit_Value::backward_transfer(), Bit_Value::forward_transfer(), inf(), Bit_Value::initialize(), and sup().
sign_reduce_bitstring()
void BitLatticeManipulator::sign_reduce_bitstring (std::deque< bit_lattice > & bitstring, bool bitstring_is_signed) const [protected]
Reduce the size of a bitstring erasing all but one most significant zeros in unsigned bitstring and all but one most significant values in signed bitstrings.
Parameters
bitstring bitstring to reduce.
bitstring_is_signed must be true if bitstring is signed
Definition at line 317 of file bit_lattice.cpp.
References THROW_ASSERT, U, X, and ZERO.
Referenced by inf(), Bit_Value::initialize(), sup(), and update_current().
string_cst_bitstring()
std::deque< bit_lattice > BitLatticeManipulator::string_cst_bitstring (const tree_nodeRef & strcst_tn, unsigned int ssa_node_id) const [protected]
auxiliary function used to build the bitstring lattice for read-only string_cst
Parameters
strcst_tn is a tree reindex or a tree node of the string_cst
ssa_node_id is the ssa node id of the lattice destination
Definition at line 405 of file bit_lattice.cpp.
References create_bitstring_from_constant(), tree_node::get_kind(), inf(), tree_helper::is_int(), THROW_ASSERT, and TM.
Referenced by Bit_Value::initialize().
sup()
std::deque< bit_lattice > BitLatticeManipulator::sup (const std::deque< bit_lattice > & a, const std::deque< bit_lattice > & b, const unsigned int output_uid) const [protected]
Computes the sup between two bitstrings.
Parameters
a first bitstring variable
b second bitstring variable
output_uid is the id of the tree node for which the bitvalue is * computed
Returns
the sup of the two bitstrings.
Definition at line 95 of file bit_lattice.cpp.
References bit_sup(), tree_helper::CGetType(), GET_NODE, tree_helper::get_type_index(), tree_helper::is_bool(), tree_helper::is_int(), min, sign_extend_bitstring(), sign_reduce_bitstring(), signed_var, tree_helper::size(), tree_helper::Size(), STR, THROW_ASSERT, THROW_UNREACHABLE, TM, X, and ZERO.
Referenced by Bit_Value::initialize(), mix(), and update_current().
update_current()
bool BitLatticeManipulator::update_current (std::deque< bit_lattice > res, unsigned int output_uid) [protected]
Given a bitstring res, and the id of a tree node ouput_uid, this functions checks if it is necessary to update the bistring stored in the current map used by the bitvalue analysis algorithm.
Definition at line 448 of file bit_lattice.cpp.
References best, current, tree_helper::is_int(), sign_reduce_bitstring(), signed_var, sup(), and TM.
Referenced by Bit_Value::backward(), BitValueIPA::Exec(), and Bit_Value::forward().
Field Documentation
best
CustomUnorderedMap<unsigned int, std::deque<bit_lattice> > BitLatticeManipulator::best [protected]
Map of the best bit-values of each variable.
Map storing the best bit-values of the variables at the end of all the iterations of forward_transfer or backward_transfer.
Definition at line 84 of file bit_lattice.hpp.
Referenced by Bit_Value::backward(), Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), clear(), Bit_Value::clear_current(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), Bit_Value::initialize(), Bit_Value::InternalExec(), Bit_Value::manage_forward_binary_operands(), mix(), update_current(), and Bit_Value::update_IR().
bl_debug_level
const int BitLatticeManipulator::bl_debug_level [protected]
The debug level of methods of this class - it cannot be named debug_level because of ambiguity of FrontendFlowStep::debug_level derived classes.
Definition at line 92 of file bit_lattice.hpp.
Referenced by mix().
current
CustomUnorderedMap<unsigned int, std::deque<bit_lattice> > BitLatticeManipulator::current [protected]
Map of the current bit-values of each variable.
Map storing the current bit-values of the variables at the end of each iteration of forward_transfer or backward_transfer.
Definition at line 78 of file bit_lattice.hpp.
Referenced by Bit_Value::backward(), Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), clear(), Bit_Value::clear_current(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), Bit_Value::manage_forward_binary_operands(), mix(), and update_current().
signed_var
CustomUnorderedSet<unsigned int> BitLatticeManipulator::signed_var [protected]
Set storing the signed ssa.
Definition at line 89 of file bit_lattice.hpp.
Referenced by clear(), BitValueIPA::Exec(), inf(), Bit_Value::initialize(), sup(), and update_current().
TM
const tree_managerConstRef BitLatticeManipulator::TM [protected]
Definition at line 72 of file bit_lattice.hpp.
Referenced by Bit_Value::backward(), Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), constructor_bitstring(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), inf(), Bit_Value::initialize(), is_handled_by_bitvalue(), Bit_Value::pointer_resizing(), string_cst_bitstring(), sup(), update_current(), and Bit_Value::update_IR().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/bit_lattice.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/bit_lattice.cpp