AugmentedVector< T > Class Template Reference
#include <augmented_vector.hpp>
Public Member Functions
AugmentedVector ()=default
Empty Constructor.
AugmentedVector (const size_t _size, T element)
Construct a vector composed by size element.
AugmentedVector (const size_t _size)
Construct a vector of size size.
AugmentedVector (const std::vector< T > &vector)
Constructor from std::vector.
T & operator[] (size_t position)
Redefinition of [] operator.
const T & operator[] (size_t position) const
Redefinition of [] operator.
T operator* (const AugmentedVector< T > &other) const
Redefinition of * operator as scalar multiplication.
AugmentedVector< T > operator- (const AugmentedVector< T > &other) const
Redefinition of - operator as the difference of the single element.
size_t size () const
Return the size of the vector.
T Norm2 () const
Return the 2-norm of the vector.
void get_min (size_t &min) const
Return the index of mininum element of the vector.
void get_min_max (size_t &min, size_t &max) const
Return the index of the minimum and maximum element of the vector.
T get_sum () const
Return the sum of a row.
T get_mean () const
Return the mean of the vector.
void remove (const size_t index)
Remove an element.
void clear ()
Erase all the elements.
void push_back (const T &elem)
Inserts a new elment at the end.
void resize (size_t n, T t=T())
Inserts or erases elements at the end such that the size becomes n.
void normalize ()
Normalize the row.
void Clear ()
Erase all elements.
Private Attributes
std::vector< T > internal_vector
The class which it logical extended by this (inheritance from template is not allowed)
Detailed Description
template<class T>
class AugmentedVector< T >
Definition at line 55 of file augmented_vector.hpp.
Constructor & Destructor Documentation
AugmentedVector() [1/4]
template<class T>
AugmentedVector< T >::AugmentedVector () [default]
Empty Constructor.
AugmentedVector() [2/4]
template<class T>
AugmentedVector< T >::AugmentedVector (const size_t _size, T element) [inline]
Construct a vector composed by size element.
Parameters
size is the size of the vector
element is the element with which the vector is filled
Definition at line 72 of file augmented_vector.hpp.
AugmentedVector() [3/4]
template<class T>
AugmentedVector< T >::AugmentedVector (const size_t _size) [inline], [explicit]
Construct a vector of size size.
Parameters
size is the size of the vector
Definition at line 80 of file augmented_vector.hpp.
AugmentedVector() [4/4]
template<class T>
AugmentedVector< T >::AugmentedVector (const std::vector< T > & vector) [inline], [explicit]
Constructor from std::vector.
Parameters
vector is the starting vector
Definition at line 88 of file augmented_vector.hpp.
Member Function Documentation
clear()
template<class T>
void AugmentedVector< T >::clear () [inline]
Erase all the elements.
Definition at line 240 of file augmented_vector.hpp.
Clear()
template<class T>
void AugmentedVector< T >::Clear () [inline]
Erase all elements.
Definition at line 280 of file augmented_vector.hpp.
get_mean()
template<class T>
T AugmentedVector< T >::get_mean () const [inline]
Return the mean of the vector.
Returns
the mean
Definition at line 220 of file augmented_vector.hpp.
References AugmentedVector< T >::get_sum(), and AugmentedVector< T >::size().
get_min()
template<class T>
void AugmentedVector< T >::get_min (size_t & min) const [inline]
Return the index of mininum element of the vector.
Parameters
min is where the index of the mimimum element will be stored
Definition at line 171 of file augmented_vector.hpp.
References index, and AugmentedVector< T >::size().
get_min_max()
template<class T>
void AugmentedVector< T >::get_min_max (size_t & min, size_t & max) const [inline]
Return the index of the minimum and maximum element of the vector.
Parameters
min is where the index of the minimum element will be stored
max is where the index of the maximum element will be stored
Definition at line 187 of file augmented_vector.hpp.
References index, and AugmentedVector< T >::size().
get_sum()
template<class T>
T AugmentedVector< T >::get_sum () const [inline]
Return the sum of a row.
Returns
the sum of the row
Definition at line 205 of file augmented_vector.hpp.
References index, and AugmentedVector< T >::size().
Referenced by AugmentedVector< T >::get_mean(), and AugmentedVector< T >::normalize().
Norm2()
template<class T>
T AugmentedVector< T >::Norm2 () const [inline]
Return the 2-norm of the vector.
Returns
the 2-norm of the vector
Fixme this works only if exists conversion from 0 to T
Definition at line 156 of file augmented_vector.hpp.
normalize()
template<class T>
void AugmentedVector< T >::normalize () [inline]
Normalize the row.
Definition at line 267 of file augmented_vector.hpp.
References AugmentedVector< T >::get_sum(), index, and AugmentedVector< T >::size().
operator*()
template<class T>
T AugmentedVector< T >::operator* (const AugmentedVector< T > & other) const [inline]
Redefinition of * operator as scalar multiplication.
Parameters
other is the second operand
Returns
the scalar multiplication
Fixme this works only if exists conversion from 0 to T
Definition at line 115 of file augmented_vector.hpp.
References AugmentedVector< T >::size(), and THROW_ASSERT.
operator-()
template<class T>
AugmentedVector<T> AugmentedVector< T >::operator- (const AugmentedVector< T > & other) const [inline]
Redefinition of - operator as the difference of the single element.
Parameters
other is the second operand
Returns
a vector storing the difference of the corresponding elements
Definition at line 132 of file augmented_vector.hpp.
References AugmentedVector< T >::internal_vector, AugmentedVector< T >::size(), and THROW_ASSERT.
operator[]() [1/2]
template<class T>
T& AugmentedVector< T >::operator[] (size_t position) [inline]
Redefinition of [] operator.
Parameters
position is the position of the element to get
Definition at line 96 of file augmented_vector.hpp.
operator[]() [2/2]
template<class T>
const T& AugmentedVector< T >::operator[] (size_t position) const [inline]
Redefinition of [] operator.
Parameters
position is the position of the element to get
Definition at line 105 of file augmented_vector.hpp.
push_back()
template<class T>
void AugmentedVector< T >::push_back (const T & elem) [inline]
Inserts a new elment at the end.
Parameters
elem is the element to be inserted
Definition at line 249 of file augmented_vector.hpp.
remove()
template<class T>
void AugmentedVector< T >::remove (const size_t index) [inline]
Remove an element.
Parameters
index is the index of the element to be removed
To avoid the cast, we should use a for with ++
Definition at line 229 of file augmented_vector.hpp.
References index.
resize()
template<class T>
void AugmentedVector< T >::resize (size_t n, T t = T()) [inline]
Inserts or erases elements at the end such that the size becomes n.
Parameters
n is the new size of the vector
t is the element to be inserted
Definition at line 259 of file augmented_vector.hpp.
size()
template<class T>
size_t AugmentedVector< T >::size () const [inline]
Return the size of the vector.
Returns
the size of the vector
Definition at line 147 of file augmented_vector.hpp.
Referenced by AugmentedVector< T >::get_mean(), AugmentedVector< T >::get_min(), AugmentedVector< T >::get_min_max(), get_point_line_distance(), AugmentedVector< T >::get_sum(), AugmentedVector< T >::normalize(), AugmentedVector< T >::operator*(), and AugmentedVector< T >::operator-().
Field Documentation
internal_vector
template<class T>
std::vector<T> AugmentedVector< T >::internal_vector [private]
The class which it logical extended by this (inheritance from template is not allowed)
Definition at line 59 of file augmented_vector.hpp.
Referenced by AugmentedVector< T >::operator-().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/utility/augmented_vector.hpp