CBackend Class Reference
Class simply used to drive the backend in order to print C code.
#include <c_backend.hpp>
Public Types
enum Type { CB_SEQUENTIAL
 }
The types of backend.
Public Member Functions
~CBackend () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
const std::string GetSignature () const override
Return a unified identifier of this design step.
const std::string GetName () const override
Return the name of this design step.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
const CWriterRef GetCWriter () const
Static Public Member Functions
static const std::string ComputeSignature (const Type type)
Compute the signature for a c backend step.
Data Fields
const Type c_backend_type
The type of this instance.
Protected Member Functions
void compute_variables (const OpGraphConstRef inGraph, const CustomUnorderedSet< unsigned int > &gblVariables, std::list< unsigned int > &funParams, CustomUnorderedSet< unsigned int > &computed_variables)
Computes the variables which have to be declared for a function.
virtual void AnalyzeInclude (unsigned int index, const BehavioralHelperConstRef BH, CustomOrderedSet< std::string > &includes)
Analyze a variable or a type to identify the includes to be added.
virtual void writeIncludes ()
Writes the file header, i.e the comments at the beginning of the file.
virtual void WriteGlobalDeclarations ()
Write the global declarations.
virtual void writeImplementations ()
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Protected Attributes
CustomUnorderedSet< unsigned int > already_visited
The set of already analyzed nodes during search of header to include; it is used to avoid infinite recursion.
const IndentedOutputStreamRef indented_output_stream
The output stream.
const CWriterRef writer
the writer
const std::string file_name
The name of the file to be created.
const application_managerConstRef AppM
the manager of the application
const tree_managerConstRef TM
The tree_manager.
Private Member Functions
CBackend (const Type type, const CBackendInformationConstRef c_backend_information, const DesignFlowManagerConstRef design_flow_manager, const application_managerConstRef AppM, std::string file_name, const ParameterConstRef Param)
Constructor.
Private Attributes
CustomOrderedSet< unsigned int > functions_to_be_declared
This set usually is equal to the set of functions without a body.
CustomOrderedSet< unsigned int > functions_to_be_defined
Friends
class CBackendStepFactory
Detailed Description
Class simply used to drive the backend in order to print C code.
Definition at line 90 of file c_backend.hpp.
Member Enumeration Documentation
Type
enum CBackend::Type
The types of backend.
Enumerator
CB_SEQUENTIAL Sequential c without instrumentation.
Definition at line 149 of file c_backend.hpp.
Constructor & Destructor Documentation
CBackend()
CBackend::CBackend (const Type _c_backend_type, const CBackendInformationConstRef c_backend_information, const DesignFlowManagerConstRef _design_flow_manager, const application_managerConstRef _AppM, std::string _file_name, const ParameterConstRef _parameters) [private]
Constructor.
Header include.
Parameters
type is the type of c backend to be created
c_backend_information is the information about the backend to be created
design_flow_manager is the design flow graph manager
AppM is the manager of the application
file_name is the file to be created
Param is the set of input parameters
design_flows include design_flows/backend/ToC design_flows/backend/ToC/source_code_writers include frontend_analysis Behavior include Graph include Paramter include STD include STL include tree includes Utility include
Definition at line 123 of file c_backend.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~CBackend().
 CBackend()
CBackend::~CBackend () [override], [default]
Destructor.
Referenced by CBackend().
Member Function Documentation
AnalyzeInclude()
void CBackend::AnalyzeInclude (unsigned int index, const BehavioralHelperConstRef BH, CustomOrderedSet< std::string > & includes) [protected], [virtual]
Analyze a variable or a type to identify the includes to be added.
Parameters
index is the index of the variable or of the type
BH is the behavioral helper
includes is where include has to be inseted
Definition at line 310 of file c_backend.cpp.
References already_visited, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BehavioralHelper::get_definition(), tree_helper::get_type_index(), tree_helper::GetTypesToBeDeclaredAfter(), tree_helper::GetTypesToBeDeclaredBefore(), INDENT_DBG_MEX, DesignFlowStep::parameters, STR, TM, and test_panda::type.
Referenced by writeIncludes().
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef CBackend::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 372 of file c_backend.cpp.
References DesignFlowStep::design_flow_manager, and Wrefcount< T >::lock().
compute_variables()
void CBackend::compute_variables (const OpGraphConstRef inGraph, const CustomUnorderedSet< unsigned int > & gblVariables, std::list< unsigned int > & funParams, CustomUnorderedSet< unsigned int > & computed_variables) [protected]
Computes the variables which have to be declared for a function.
Parameters
inGraph is the data flow graph of the function
gblVariables is the set containing the node ids of the global variables
funParams is the list of function parameters
computed_variables is the set where the computed variables will be stored
Definition at line 347 of file c_backend.cpp.
References OpGraph::CGetOpNodeInfo().
ComputeRelationships()
void CBackend::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [protected], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 433 of file c_backend.cpp.
References FrontendFlowStep::ALL_FUNCTIONS, AppM, BASIC_BLOCKS_CFG_COMPUTATION, c_backend_type, CB_SEQUENTIAL, ApplicationFrontendFlowStep::ComputeSignature(), HLSFunctionStep::ComputeSignature(), ComputeSignature(), FrontendFlowStepFactory::CreateApplicationFrontendFlowStep(), HLSFlowStepFactory::CreateHLSFlowStep(), FrontendFlowStep::CreateSteps(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, FUNCTION_ANALYSIS, HLS_SYNTHESIS_FLOW, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), LOOP_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TEST_VECTOR_PARSER, TESTBENCH_MEMORY_ALLOCATION, THROW_ASSERT, THROW_UNREACHABLE, VAR_ANALYSIS, and FrontendFlowStep::WHOLE_APPLICATION.
ComputeSignature()
const std::string CBackend::ComputeSignature (const Type type) [static]
Compute the signature for a c backend step.
Definition at line 382 of file c_backend.cpp.
References CB_SEQUENTIAL, and THROW_UNREACHABLE.
Referenced by CTestbenchExecution::ComputeRelationships(), BasicBlocksProfiling::ComputeRelationships(), TestbenchValuesCGeneration::ComputeRelationships(), ComputeRelationships(), and GetSignature().
Exec()
DesignFlowStep_Status CBackend::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 143 of file c_backend.cpp.
References IndentedOutputStream::Append(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, file_name, TimeStamp::GetCurrentTimeStamp(), INDENT_DBG_MEX, indented_output_stream, DesignFlowStep::parameters, SUCCESS, WriteGlobalDeclarations(), writeImplementations(), writeIncludes(), and writer.
GetCWriter()
const CWriterRef CBackend::GetCWriter () const
Returns
the associated c writer
Definition at line 138 of file c_backend.cpp.
References writer.
GetName()
const std::string CBackend::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 428 of file c_backend.cpp.
References GetSignature().
GetSignature()
const std::string CBackend::GetSignature () const [override], [virtual]
Return a unified identifier of this design step.
Returns
the signature of the design step
Implements DesignFlowStep.
Definition at line 377 of file c_backend.cpp.
References c_backend_type, and ComputeSignature().
Referenced by GetName().
HasToBeExecuted()
bool CBackend::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 169 of file c_backend.cpp.
Initialize()
void CBackend::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 174 of file c_backend.cpp.
References already_visited, AppM, c_backend_type, file_name, functions_to_be_declared, functions_to_be_defined, and writer.
WriteGlobalDeclarations()
void CBackend::WriteGlobalDeclarations () [protected], [virtual]
Write the global declarations.
Definition at line 191 of file c_backend.cpp.
References IndentedOutputStream::Append(), AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BehavioralHelper::function_has_to_be_printed(), functions_to_be_declared, functions_to_be_defined, BehavioralHelper::get_function_name(), INDENT_DBG_MEX, indented_output_stream, DesignFlowStep::parameters, and writer.
Referenced by Exec().
writeImplementations()
void CBackend::writeImplementations () [protected], [virtual]
Definition at line 236 of file c_backend.cpp.
References AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BehavioralHelper::function_has_to_be_printed(), functions_to_be_defined, INDENT_DBG_MEX, and writer.
Referenced by Exec().
writeIncludes()
void CBackend::writeIncludes () [protected], [virtual]
Writes the file header, i.e the comments at the beginning of the file.
Definition at line 251 of file c_backend.cpp.
References AnalyzeInclude(), AppM, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::DFG, ENTRY_ID, EXIT_ID, functions_to_be_defined, BehavioralHelper::get_function_name(), BehavioralHelper::get_parameters(), BehavioralHelper::get_type(), BehavioralHelper::get_typecast(), INDENT_DBG_MEX, index, BehavioralHelper::PrintVariable(), STR, and writer.
Referenced by Exec().
Friends And Related Function Documentation
CBackendStepFactory
friend class CBackendStepFactory [friend]
Definition at line 187 of file c_backend.hpp.
Field Documentation
already_visited
CustomUnorderedSet<unsigned int> CBackend::already_visited [protected]
The set of already analyzed nodes during search of header to include; it is used to avoid infinite recursion.
Definition at line 94 of file c_backend.hpp.
Referenced by AnalyzeInclude(), and Initialize().
AppM
const application_managerConstRef CBackend::AppM [protected]
the manager of the application
Definition at line 106 of file c_backend.hpp.
Referenced by ComputeRelationships(), Initialize(), WriteGlobalDeclarations(), writeImplementations(), and writeIncludes().
c_backend_type
const Type CBackend::c_backend_type
The type of this instance.
Definition at line 183 of file c_backend.hpp.
Referenced by ComputeRelationships(), GetSignature(), and Initialize().
file_name
const std::string CBackend::file_name [protected]
The name of the file to be created.
Definition at line 103 of file c_backend.hpp.
Referenced by Exec(), and Initialize().
functions_to_be_declared
CustomOrderedSet<unsigned int> CBackend::functions_to_be_declared [private]
This set usually is equal to the set of functions without a body.
Definition at line 190 of file c_backend.hpp.
Referenced by Initialize(), and WriteGlobalDeclarations().
functions_to_be_defined
CustomOrderedSet<unsigned int> CBackend::functions_to_be_defined [private]
Definition at line 193 of file c_backend.hpp.
Referenced by Initialize(), WriteGlobalDeclarations(), writeImplementations(), and writeIncludes().
indented_output_stream
const IndentedOutputStreamRef CBackend::indented_output_stream [protected]
The output stream.
Definition at line 97 of file c_backend.hpp.
Referenced by Exec(), and WriteGlobalDeclarations().
TM
const tree_managerConstRef CBackend::TM [protected]
The tree_manager.
Definition at line 109 of file c_backend.hpp.
Referenced by AnalyzeInclude().
writer
const CWriterRef CBackend::writer [protected]
the writer
Definition at line 100 of file c_backend.hpp.
Referenced by Exec(), GetCWriter(), Initialize(), WriteGlobalDeclarations(), writeImplementations(), and writeIncludes().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/progModels/c_backend.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/progModels/c_backend.cpp