/home/osboxes/bambu/PandA-bambu/src/utility/exceptions.cpp File Reference
exceptions managed by PandA
#include <cstdlib>
Functions
bool IsError (const int error_value)
Utility include.
bool is_failure (const int error_value)
Return true if the return value corresponds to a failure (not to an error)
Detailed Description
exceptions managed by PandA
This structure is used to manage the exception arised by the Panda toolset.
Author
Marco Lattuada lattuada@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
is_failure()
bool is_failure (const int error_value)
Return true if the return value corresponds to a failure (not to an error)
Parameters
return_value is a return value of a system
Returns
true if return value corresponds to a failure
Definition at line 66 of file exceptions.cpp.
IsError()
bool IsError (const int error_value)
Utility include.
Return true if the return_value corresponds to an error.
Definition at line 60 of file exceptions.cpp.
Referenced by BambuParameter::CheckParameters(), GccWrapper::CompileFile(), GccWrapper::CreateExecutable(), CTestbenchExecution::Exec(), BasicBlocksProfiling::Exec(), create_tree_manager::Exec(), TestbenchValuesCGeneration::Exec(), ToolManager::execute_command(), FindMaxCFGTransformations::ExecuteBambu(), NonDeterministicFlows::ExecuteTool(), GccWrapper::FillTreeManager(), moduleGenerator::GenerateHDL(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), GccWrapper::GetSourceCodeLines(), GccWrapper::GetSystemIncludes(), main(), and GccWrapper::QueryGccConfig().