/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/allocation.cpp File Reference
Wrapper for technology used by the high-level synthesis flow.
#include `allocation.hpp`
#include `HDL_manager.hpp`
#include `NP_functionality.hpp`
#include `Parameter.hpp`
#include `allocation_information.hpp`
#include `behavioral_helper.hpp`
#include `call_graph_manager.hpp`
#include `clb_model.hpp`
#include `config_HAVE_EXPERIMENTAL.hpp`
#include `config_HAVE_FLOPOCO.hpp`
#include `cpu_time.hpp`
#include `dbgPrintHelper.hpp`
#include `design_flow_step_factory.hpp`
#include `exceptions.hpp`
#include `functions.hpp`
#include `hls.hpp`
#include `hls_constraints.hpp`
#include `hls_flow_step_factory.hpp`
#include `hls_target.hpp`
#include `language_writer.hpp`
#include `library_manager.hpp`
#include `memory.hpp`
#include `memory_allocation.hpp`
#include `moduleGenerator.hpp`
#include `op_graph.hpp`
#include `schedule.hpp`
#include `string_manipulation.hpp`
#include `structural_manager.hpp`
#include `structural_objects.hpp`
#include `target_device.hpp`
#include `technology_manager.hpp`
#include `technology_node.hpp`
#include `time_model.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
#include `typed_node_info.hpp`
#include `utility.hpp`
#include <cstddef>
#include <limits>
#include <algorithm>
#include <tuple>
#include <utility>
#include <vector>
#include `custom_map.hpp`
#include `custom_set.hpp`
Functions
static bool is_other_port (const structural_objectRef &port)
Header include.
static bool is_a_skip_operation (const std::string &op_name)
static std::string encode_op_type (const std::string &op_name, const std::string &fu_supported_types)
static std::string encode_op_type_prec (const std::string &op_name, const std::string &fu_supported_types, node_kind_prec_infoRef node_info)
static std::string fix_identifier (std::string port_name, language_writerRef writer)
static void connectClockAndReset (structural_managerRef &SM, structural_objectRef &interfaceObj, structural_objectRef &component)
Detailed Description
Wrapper for technology used by the high-level synthesis flow.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Function Documentation
connectClockAndReset()
static void connectClockAndReset (structural_managerRef & SM, structural_objectRef & interfaceObj, structural_objectRef & component) [static]
Definition at line 262 of file allocation.cpp.
References CLOCK_PORT_NAME, structural_object::find_member(), port_o_K, reset(), RESET_PORT_NAME, and THROW_UNREACHABLE.
Referenced by allocation::BuildProxyWrapper().
encode_op_type()
static std::string encode_op_type (const std::string & op_name, const std::string & fu_supported_types) [inline], [static]
Definition at line 107 of file allocation.cpp.
Referenced by encode_op_type_prec(), and allocation::InternalExec().
encode_op_type_prec()
static std::string encode_op_type_prec (const std::string & op_name, const std::string & fu_supported_types, node_kind_prec_infoRef node_info) [inline], [static]
Definition at line 112 of file allocation.cpp.
References encode_op_type(), and STR.
Referenced by allocation::InternalExec().
fix_identifier()
static std::string fix_identifier (std::string port_name, language_writerRef writer) [static]
Definition at line 256 of file allocation.cpp.
References HDL_manager::convert_to_identifier().
Referenced by allocation::BuildProxyFunctionVerilog(), and allocation::BuildProxyFunctionVHDL().
is_a_skip_operation()
static bool is_a_skip_operation (const std::string & op_name) [static]
Definition at line 99 of file allocation.cpp.
Referenced by allocation::get_compliant_pipelined_unit().
is_other_port()
static bool is_other_port (const structural_objectRef & port) [static]
Header include.
STL includes
Definition at line 93 of file allocation.cpp.
Referenced by allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), allocation::BuildProxyFunctionVerilog(), allocation::BuildProxyFunctionVHDL(), and allocation::BuildProxyWrapper().