gzstreambuf Class Reference
The big change with respect to the original code is a refactoring for a header based library.
#include <gzstream.hpp>
Public Member Functions
gzstreambuf ()
int is_open ()
gzstreambuf * open (const char *name, int open_mode)
gzstreambuf * close ()
~gzstreambuf () override
int overflow (int c=EOF) override
int underflow () override
int sync () override
Private Member Functions
int flush_buffer ()
Private Attributes
gzFile file
char buffer [bufferSize]
char opened
int mode
Static Private Attributes
static const int bufferSize = 47 + 256
Detailed Description
The big change with respect to the original code is a refactoring for a header based library.
Internal classes to implement gzstream. See below for user classes.
Definition at line 77 of file gzstream.hpp.
Constructor & Destructor Documentation
gzstreambuf()
gzstreambuf::gzstreambuf () [inline]
Definition at line 91 of file gzstream.hpp.
 gzstreambuf()
gzstreambuf::~gzstreambuf () [inline], [override]
Definition at line 105 of file gzstream.hpp.
References close(), overflow(), sync(), and underflow().
Member Function Documentation
close()
gzstreambuf * gzstreambuf::close () [inline]
Definition at line 203 of file gzstream.hpp.
References file, is_open(), opened, and sync().
Referenced by gzstreambase::gzstreambase(), is_open(), and ~gzstreambuf().
flush_buffer()
int gzstreambuf::flush_buffer () [inline], [private]
Definition at line 241 of file gzstream.hpp.
References file.
Referenced by overflow(), and sync().
is_open()
int gzstreambuf::is_open () [inline]
Definition at line 99 of file gzstream.hpp.
References close(), open(), and opened.
Referenced by close(), and open().
open()
gzstreambuf * gzstreambuf::open (const char * name, int open_mode) [inline]
Definition at line 180 of file gzstream.hpp.
References file, is_open(), mode, and opened.
Referenced by gzstreambase::gzstreambase(), and is_open().
overflow()
int gzstreambuf::overflow (int c = EOF) [inline], [override]
Definition at line 252 of file gzstream.hpp.
References flush_buffer(), mode, and opened.
Referenced by ~gzstreambuf().
sync()
int gzstreambuf::sync () [inline], [override]
Definition at line 266 of file gzstream.hpp.
References flush_buffer().
Referenced by close(), and ~gzstreambuf().
underflow()
int gzstreambuf::underflow () [inline], [override]
Definition at line 215 of file gzstream.hpp.
References buffer, bufferSize, file, mode, and opened.
Referenced by ~gzstreambuf().
Field Documentation
buffer
char gzstreambuf::buffer[bufferSize] [private]
Definition at line 84 of file gzstream.hpp.
Referenced by underflow().
bufferSize
const int gzstreambuf::bufferSize = 47 + 256 [static], [private]
Definition at line 80 of file gzstream.hpp.
Referenced by underflow().
file
gzFile gzstreambuf::file [private]
Definition at line 83 of file gzstream.hpp.
Referenced by close(), flush_buffer(), open(), and underflow().
mode
int gzstreambuf::mode [private]
Definition at line 86 of file gzstream.hpp.
Referenced by open(), overflow(), and underflow().
opened
char gzstreambuf::opened [private]
Definition at line 85 of file gzstream.hpp.
Referenced by close(), is_open(), open(), overflow(), and underflow().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/utility/gzstream.hpp