parametric_list_based Class Reference
Class managing list based scheduling algorithms.
#include <parametric_list_based.hpp>
Public Member Functions
parametric_list_based (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
This is the constructor of the list_based.
~parametric_list_based () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void exec (const OpVertexSet &operations, ControlStep current_cycle)
Function that computes the List-Based scheduling of the graph.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Member Functions
void compute_exec_stage_time (const unsigned int fu_type, double &stage_period, const ControlStep cs, const OpGraphConstRef op_graph, vertex v, double &op_execution_time, double &phi_extra_time, double current_starting_time, double setup_hold_time)
void compute_starting_ending_time_asap (const vertex v, const unsigned int fu_type, const ControlStep cs, double &current_starting_time, double &current_ending_time, double &stage_period, bool &cannot_be_chained, fu_bindingRef res_binding, const ScheduleConstRef schedule, double &phi_extra_time, double setup_hold_time, CustomMap< std::pair< unsigned int, unsigned int >, double > &local_fo_correction_map)
Given the control step in which an operation is scheduled, compute the exact starting and ending time of an operation.
void compute_starting_ending_time_alap (const vertex v, const unsigned int fu_type, const ControlStep cs, double &starting_time, double &ending_time, double &op_execution_time, double &stage_period, unsigned int &n_cycles, bool &has_a_store_unbounded_as_in, fu_bindingRef res_binding, const ScheduleConstRef schedule, double &phi_extra_time, double setup_hold_time, CustomMap< std::pair< unsigned int, unsigned int >, double > &local_connection_map)
void update_starting_ending_time (vertex candidate_v, fu_bindingRef res_binding, OpGraphConstRef op_dfg_graph, const ScheduleConstRef schedule)
update starting and ending time by moving candidate_v as late as possible without increasing the whole latency
void update_starting_ending_time_asap (vertex candidate_v, fu_bindingRef res_binding, OpGraphConstRef opDFG, const ScheduleConstRef schedule)
void update_vertices_timing (const ControlStep vertex_cstep, vertex current_v, const ScheduleConstRef schedule, std::list< vertex > &vertices_analyzed, fu_bindingRef res_binding, const OpGraphConstRef opDFG)
update the starting and ending time of the vertices scheduled in the same cs of current_v
bool BB_update_resources_use (unsigned int &used_resources, const unsigned int fu_type) const
Update the resource map.
void add_to_priority_queues (PriorityQueues &priority_queue, std::set< unsigned int, resource_ordering_functor > &ready_resources, const vertex v) const
Adds the vertex v to the priority queues.
double compute_slack (vertex current_op, const ControlStep current_vertex_cstep, double setup_hold_time)
compute the slack of a given operation and in case specify if is pipelined
void update_vertices_slack (vertex current_v, const ScheduleRef schedule, OpVertexSet &vertices_analyzed, double setup_hold_time, const OpGraphConstRef opDFG)
update the slack of vertices of current_v and of all the vertices in chaining with it
bool store_in_chaining_with_load_in (unsigned int current_vertex_cstep, vertex v)
store_in_chaining_with_load checks if a store is chained with a load operation or vice versa
bool store_in_chaining_with_load_out (unsigned int current_vertex_cstep, vertex v)
void do_balanced_scheduling (std::deque< vertex > &sub_levels, const ScheduleRef schedule, const fu_bindingRef res_binding, const double setup_hold_time, const double scheduling_mux_margins, const OpGraphConstRef opDFG)
perform balanced scheduling on an existing solution
void do_balanced_scheduling1 (std::deque< vertex > &sub_levels, const ScheduleRef schedule, const fu_bindingRef res_binding, const double setup_hold_time, const double scheduling_mux_margins, const OpGraphConstRef opDFG, bool seen_cstep_has_RET_conflict)
different version of balanced scheduling.
bool check_non_direct_operation_chaining (vertex current_v, unsigned int v_fu_type, const ControlStep cs, const ScheduleConstRef schedule, fu_bindingRef res_binding) const
bool check_direct_operation_chaining (vertex current_v, const ControlStep cs, const ScheduleConstRef schedule, fu_bindingRef res_binding) const
bool check_LOAD_chaining (vertex current_v, const ControlStep cs, const ScheduleConstRef schedule) const
void CheckSchedulabilityConditions (const vertex &current_vertex, ControlStep current_cycle, double &current_starting_time, double &current_ending_time, double &current_stage_period, CustomMap< std::pair< unsigned int, unsigned int >, double > &local_connection_map, double current_cycle_starting_time, double current_cycle_ending_time, double setup_hold_time, double &phi_extra_time, double scheduling_mux_margins, bool unbounded, bool cstep_has_RET_conflict, unsigned int fu_type, const vertex2obj< ControlStep > &current_ASAP, const fu_bindingRef res_binding, const ScheduleRef schedule, bool &predecessorsCond, bool &pipeliningCond, bool &cannotBeChained0, bool &chainingRetCond, bool &cannotBeChained1, bool &asyncCond, bool &cannotBeChained2, bool &MultiCond0, bool &MultiCond1, bool &nonDirectMemCond)
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Private Attributes
const ParametricListBased_Metric parametric_list_based_metric
The used metric.
OpGraphConstRef flow_graph
The dependence graph.
OpGraphConstRef flow_graph_with_feedbacks
The dependence graph with feedbacks.
vertex2float starting_time
The starting time given the scheduling (used for chaining)
OpVertexMap< double > ending_time
The ending time given the scheduling (used for chaining)
double clock_cycle
The clock cycle.
CustomUnorderedMapUnstable< std::pair< vertex, unsigned int >, bool > is_complex
memoization table used for connection estimation
size_t executions_number
Number of executions.
Static Private Attributes
static const double EPSILON = 0.000000001
Additional Inherited Members
Detailed Description
Class managing list based scheduling algorithms.
Definition at line 144 of file parametric_list_based.hpp.
Constructor & Destructor Documentation
parametric_list_based()
parametric_list_based::parametric_list_based (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
This is the constructor of the list_based.
Parameters
parameters is the set of input parameters
HLSmgr is the HLS manager
function_id is the function index of the function
design_flow_manager is the hls design flow
hls_flow_step_specialization specifies how specialize this step
Definition at line 298 of file parametric_list_based.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~parametric_list_based().
 parametric_list_based()
parametric_list_based::~parametric_list_based () [override], [default]
Destructor.
Referenced by parametric_list_based().
Member Function Documentation
add_to_priority_queues()
void parametric_list_based::add_to_priority_queues (PriorityQueues & priority_queue, std::set< unsigned int, resource_ordering_functor > & ready_resources, const vertex v) const [private]
Adds the vertex v to the priority queues.
Parameters
priority_trees are the priority_queues
ready_resources is the set of resources which have at least one ready operation
v is the vertex.
Definition at line 1465 of file parametric_list_based.cpp.
References hls::allocation_information, AllocationInformation::can_implement_set(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, flow_graph, AllocationInformation::get_fu_name(), GET_NAME, HLSFunctionStep::HLS, INDENT_DBG_MEX, and AllocationInformation::is_vertex_bounded_with().
Referenced by exec().
BB_update_resources_use()
bool parametric_list_based::BB_update_resources_use (unsigned int & used_resources, const unsigned int fu_type) const [private]
Update the resource map.
Parameters
used_resources_fu is the resource map.
fu_type is the functional unit type on which operation is scheduled
Returns
true if the assignment is feasible
Definition at line 1454 of file parametric_list_based.cpp.
References hls::allocation_information, AllocationInformation::get_number_fu(), and HLSFunctionStep::HLS.
Referenced by exec().
check_direct_operation_chaining()
bool parametric_list_based::check_direct_operation_chaining (vertex current_v, const ControlStep cs, const ScheduleConstRef schedule, fu_bindingRef res_binding) const [private]
compute the set of operations on the control step frontier
Definition at line 2384 of file parametric_list_based.cpp.
References hls::allocation_information, flow_graph, fu_binding::get_assign(), GET_TYPE, HLSFunctionStep::HLS, AllocationInformation::is_direct_access_memory_unit(), and TYPE_LOAD.
check_LOAD_chaining()
bool parametric_list_based::check_LOAD_chaining (vertex current_v, const ControlStep cs, const ScheduleConstRef schedule) const [private]
compute the set of operations on the control step frontier
Definition at line 2407 of file parametric_list_based.cpp.
References flow_graph, GET_TYPE, and TYPE_LOAD.
Referenced by compute_starting_ending_time_alap(), and compute_starting_ending_time_asap().
check_non_direct_operation_chaining()
bool parametric_list_based::check_non_direct_operation_chaining (vertex current_v, unsigned int v_fu_type, const ControlStep cs, const ScheduleConstRef schedule, fu_bindingRef res_binding) const [private]
Set of already analyzed operations
compute the set of operations on the control step frontier
Definition at line 2342 of file parametric_list_based.cpp.
References hls::allocation_information, flow_graph, fu_binding::get_assign(), AllocationInformation::get_memory_var(), AllocationInformation::get_number_channels(), AllocationInformation::get_proxy_memory_var(), GET_TYPE, HLSFunctionStep::HLS, HLS_step::HLSMgr, AllocationInformation::is_indirect_access_memory_unit(), AllocationInformation::is_memory_unit(), AllocationInformation::is_one_cycle_direct_access_memory_unit(), AllocationInformation::is_readonly_memory_unit(), hls::Param, DesignFlowStep::parameters, REMOVE_DIRECT_TO_INDIRECT, and TYPE_LOAD.
Referenced by compute_starting_ending_time_alap(), and compute_starting_ending_time_asap().
CheckSchedulabilityConditions()
void parametric_list_based::CheckSchedulabilityConditions (const vertex & current_vertex, ControlStep current_cycle, double & current_starting_time, double & current_ending_time, double & current_stage_period, CustomMap< std::pair< unsigned int, unsigned int >, double > & local_connection_map, double current_cycle_starting_time, double current_cycle_ending_time, double setup_hold_time, double & phi_extra_time, double scheduling_mux_margins, bool unbounded, bool cstep_has_RET_conflict, unsigned int fu_type, const vertex2obj< ControlStep > & current_ASAP, const fu_bindingRef res_binding, const ScheduleRef schedule, bool & predecessorsCond, bool & pipeliningCond, bool & cannotBeChained0, bool & chainingRetCond, bool & cannotBeChained1, bool & asyncCond, bool & cannotBeChained2, bool & MultiCond0, bool & MultiCond1, bool & nonDirectMemCond) [private]
Definition at line 334 of file parametric_list_based.cpp.
References hls::allocation_information, clock_cycle, compute_starting_ending_time_asap(), EPSILON, flow_graph, AllocationInformation::get_cycles(), AllocationInformation::get_initiation_time(), AllocationInformation::get_memory_var(), AllocationInformation::get_number_channels(), AllocationInformation::get_proxy_memory_var(), GET_TYPE, HLSFunctionStep::HLS, HLS_step::HLSMgr, AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_memory_unit(), AllocationInformation::is_one_cycle_direct_access_memory_unit(), AllocationInformation::is_readonly_memory_unit(), hls::Param, DesignFlowStep::parameters, TYPE_LOAD, TYPE_RET, and TYPE_STORE.
Referenced by exec().
compute_exec_stage_time()
void parametric_list_based::compute_exec_stage_time (const unsigned int fu_type, double & stage_period, const ControlStep cs, const OpGraphConstRef op_graph, vertex v, double & op_execution_time, double & phi_extra_time, double current_starting_time, double setup_hold_time) [private]
check for PHIs attached to the output. They may require one or more muxes.
corrections for the memory controllers
corrections in case the unit first fits in a clock period and then after all the additions does not fit anymore
recompute the execution time from scratch
Stage period has already been used for computing ending time of operation If the operation has registered inputs, the stage period of first stage is 0 (mux delay is described by connection time)
Definition at line 1329 of file parametric_list_based.cpp.
References hls::allocation_information, OpGraph::CGetOpNodeInfo(), clock_cycle, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, EPSILON, flow_graph, flow_graph_with_feedbacks, from_strongtype_cast(), AllocationInformation::get_correction_time(), AllocationInformation::get_cycles(), AllocationInformation::get_execution_time(), AllocationInformation::get_initiation_time(), GET_NAME, AllocationInformation::GetConnectionTime(), AllocationInformation::GetFuType(), AllocationInformation::GetTimeLatency(), HLSFunctionStep::HLS, INDENT_DBG_MEX, AllocationInformation::is_indirect_access_memory_unit(), AllocationInformation::is_operation_PI_registered(), max(), AllocationInformation::mux_time_unit(), DesignFlowStep::parameters, SCALAR, STR, THROW_ERROR, and USE.
Referenced by compute_starting_ending_time_alap(), and compute_starting_ending_time_asap().
compute_slack()
double parametric_list_based::compute_slack (vertex current_op, const ControlStep current_vertex_cstep, double setup_hold_time) [private]
compute the slack of a given operation and in case specify if is pipelined
Definition at line 1582 of file parametric_list_based.cpp.
References clock_cycle, EPSILON, from_strongtype_cast(), HLSFunctionStep::HLS, hls::HLS_C, and starting_time.
Referenced by update_vertices_slack().
compute_starting_ending_time_alap()
void parametric_list_based::compute_starting_ending_time_alap (const vertex v, const unsigned int fu_type, const ControlStep cs, double & starting_time, double & ending_time, double & op_execution_time, double & stage_period, unsigned int & n_cycles, bool & has_a_store_unbounded_as_in, fu_bindingRef res_binding, const ScheduleConstRef schedule, double & phi_extra_time, double setup_hold_time, CustomMap< std::pair< unsigned int, unsigned int >, double > & local_connection_map) [private]
ending time is equal to the connection time plus the maximum between the controller time and the operation ending time
Definition at line 1394 of file parametric_list_based.cpp.
References hls::allocation_information, OpGraph::CGetOpNodeInfo(), check_LOAD_chaining(), check_non_direct_operation_chaining(), clock_cycle, compute_exec_stage_time(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, ending_time, AllocationInformation::EstimateControllerDelay(), flow_graph, from_strongtype_cast(), fu_binding::get_assign(), AllocationInformation::get_cycles(), AllocationInformation::get_memory_var(), GET_NAME, AllocationInformation::get_number_channels(), AllocationInformation::get_proxy_memory_var(), GET_TYPE, AllocationInformation::GetConnectionTime(), HLSFunctionStep::HLS, HLS_step::HLSMgr, AllocationInformation::is_memory_unit(), AllocationInformation::is_one_cycle_direct_access_memory_unit(), AllocationInformation::is_operation_bounded(), AllocationInformation::is_operation_PI_registered(), AllocationInformation::is_readonly_memory_unit(), max(), min, hls::Param, DesignFlowStep::parameters, PRINT_DBG_MEX, starting_time, STR, TYPE_LOAD, and TYPE_STORE.
Referenced by do_balanced_scheduling(), and do_balanced_scheduling1().
compute_starting_ending_time_asap()
void parametric_list_based::compute_starting_ending_time_asap (const vertex v, const unsigned int fu_type, const ControlStep cs, double & current_starting_time, double & current_ending_time, double & stage_period, bool & cannot_be_chained, fu_bindingRef res_binding, const ScheduleConstRef schedule, double & phi_extra_time, double setup_hold_time, CustomMap< std::pair< unsigned int, unsigned int >, double > & local_fo_correction_map) [private]
Given the control step in which an operation is scheduled, compute the exact starting and ending time of an operation.
Parameters
v is the vertex of the operation
fu_type is the functional unit type
cs is the control step
current_starting_time is where starting_time will be stored
current_ending_time is where ending_time will be stored
stage_period is the minimum period of the pipelined unit fu_type
ending time is equal to the connection time plus the maximum between the controller time and the operation ending time
Check for chaining
Definition at line 1265 of file parametric_list_based.cpp.
References hls::allocation_information, AllocationInformation::CanBeChained(), OpGraph::CGetOpNodeInfo(), check_LOAD_chaining(), check_non_direct_operation_chaining(), clock_cycle, compute_exec_stage_time(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, ending_time, AllocationInformation::EstimateControllerDelay(), flow_graph, from_strongtype_cast(), fu_binding::get_assign(), AllocationInformation::get_memory_var(), GET_NAME, AllocationInformation::get_number_channels(), AllocationInformation::get_proxy_memory_var(), GET_TYPE, AllocationInformation::GetConnectionTime(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, AllocationInformation::is_memory_unit(), AllocationInformation::is_one_cycle_direct_access_memory_unit(), AllocationInformation::is_readonly_memory_unit(), max(), hls::Param, DesignFlowStep::parameters, PRINT_DBG_MEX, starting_time, STR, TYPE_LOAD, TYPE_PHI, TYPE_STORE, and TYPE_VPHI.
Referenced by CheckSchedulabilityConditions().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > parametric_list_based::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 2431 of file parametric_list_based.cpp.
References Scheduling::ComputeHLSRelationships(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
ComputeRelationships()
void parametric_list_based::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from HLSFunctionStep.
Definition at line 313 of file parametric_list_based.cpp.
References HLSFunctionStep::ComputeRelationships(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, executions_number, HLSFunctionStep::funId, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), NULL_VERTEX, and DesignFlowStep::parameters.
do_balanced_scheduling()
void parametric_list_based::do_balanced_scheduling (std::deque< vertex > & sub_levels, const ScheduleRef schedule, const fu_bindingRef res_binding, const double setup_hold_time, const double scheduling_mux_margins, const OpGraphConstRef opDFG) [private]
perform balanced scheduling on an existing solution
Parameters
sub_levels is the list of sorted vertices
schedule is the current scheduling
res_binding is the current resource binding
setup_hold_time is the delay for the setup and hold of registers
balanced scheduling step 1: dependencies computation
step 2: compute operation distribution
check if time has unbounded vertices or the return statement
only 1 unbounded operation is allowed in a control step
unbounded operations could not be moved
Chaining is possible but not allowed
Chaining with STOREs/LOADs is not possible
pipelined operation does not fit at the begin
pipelined operation does not fit at the end
Multi-cycles operations cannot be scheduled together with unbounded operations
operation does not fit at the end
operation does not fit in the cycle
try to keep the previous latency
Definition at line 1786 of file parametric_list_based.cpp.
References hls::allocation_information, OpGraph::CGetOpNodeInfo(), clock_cycle, compute_starting_ending_time_alap(), ending_time, Schedule::ending_times, flow_graph, from_strongtype_cast(), AllocationInformation::get_area(), fu_binding::get_assign(), Schedule::get_cstep(), AllocationInformation::get_DSPs(), AllocationInformation::get_initiation_time(), AllocationInformation::get_number_fu(), GET_TYPE, HLSFunctionStep::HLS, INFINITE_UINT, AllocationInformation::is_operation_bounded(), AllocationInformation::is_vertex_bounded(), max(), min, NULL_VERTEX, DesignFlowStep::parameters, Schedule::set_execution(), Schedule::set_execution_end(), starting_time, Schedule::starting_times, THROW_ASSERT, TYPE_INIT, TYPE_LABEL, TYPE_LOAD, TYPE_PHI, TYPE_RET, TYPE_STORE, TYPE_VPHI, update_starting_ending_time(), and update_vertices_slack().
do_balanced_scheduling1()
void parametric_list_based::do_balanced_scheduling1 (std::deque< vertex > & sub_levels, const ScheduleRef schedule, const fu_bindingRef res_binding, const double setup_hold_time, const double scheduling_mux_margins, const OpGraphConstRef opDFG, bool seen_cstep_has_RET_conflict) [private]
different version of balanced scheduling.
It re-schedules the operation trying to improve their slack.
Parameters
sub_levels is the list of sorted vertices
schedule is the current scheduling
res_binding is the current resource binding
setup_hold_time is the delay for the setup and hold of registers
balanced scheduling step 1: dependencies computation
step 2: compute operation distribution
check if time has unbounded vertices, the return or the IF/SWITCH statements
recompute the number of cycles removing the return cycle
only 1 unbounded operation is allowed in a control step
unbounded operations could not be moved
no room for fu_type at time time
Chaining is possible but not allowed
Chaining with STOREs/LOADs is not possible
pipelined operation does not fit at the begin
pipelined operation does not fit at the end
Multi-cycles operations cannot be scheduled together with unbounded operations
operation does not fit at the end
operation does not fit in the cycle
try to keep the previous latency
try to reduce as much as possible the chaining between operations
no room for fu_type at time time
Definition at line 1984 of file parametric_list_based.cpp.
References hls::allocation_information, OpGraph::CGetOpNodeInfo(), clock_cycle, AllocationInformation::compute_normalized_area(), compute_starting_ending_time_alap(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, ending_time, Schedule::ending_times, EPSILON, flow_graph, from_strongtype_cast(), fu_binding::get_assign(), Schedule::get_cstep(), AllocationInformation::get_fu_name(), AllocationInformation::get_initiation_time(), GET_NAME, AllocationInformation::get_number_fu(), Schedule::get_slack(), GET_TYPE, HLSFunctionStep::HLS, hls::HLS_C, INFINITE_UINT, AllocationInformation::is_operation_bounded(), AllocationInformation::is_vertex_bounded(), max(), min, NULL_VERTEX, DesignFlowStep::parameters, PRINT_DBG_MEX, Schedule::set_execution(), Schedule::set_execution_end(), starting_time, Schedule::starting_times, STR, THROW_ASSERT, TYPE_INIT, TYPE_LABEL, TYPE_LOAD, TYPE_PHI, TYPE_STORE, TYPE_VPHI, update_starting_ending_time(), update_vertices_slack(), and update_vertices_timing().
Referenced by exec().
exec()
void parametric_list_based::exec (const OpVertexSet & operations, ControlStep current_cycle)
Function that computes the List-Based scheduling of the graph.
The scheduling
Current ASAP
The binding
Number of predecessors of a vertex already scheduled
The clock cycle
The setup+hold time delay
The set of resources for which the list of ready operations is not empty
Set of ready operations (needed for update priority)
vertices still live at the beginning of the current control step
select the type of graph
Number of operation to be scheduled
compute asap and alap
compute the set of vertices without input edges. At least one vertex is expected
Updating structure for already scheduled operations
Check if all its predecessors have been scheduled. In this case the vertex is ready
Setting priority
priory queues set up
definition of the data structure used to check if a resource is available given a vertex in case a vertex is not included in a map this mean that the used resources are zero. First index is the functional unit type, second index is the controller node, third index is the condition
Operations which can be scheduled in this control step because precedences are satisfied, but they can't be scheduled in this control step for some reasons Index is the functional unit type
Adding information about operation still live
Ignore empty list
Ignore already scheduled operation
remove current_vertex from the queue
true if operation is schedulable check if there exist enough resources available
check compatibility
put these type of operations as last operation scheduled for the basic block
starting time of the operation
ending time of the operation
stage period for pipelined units
checking if predecessors have finished
scheduling is now possible
update resource usage
check if there exist enough resources available
update cstep_vuses
even if it is bounded we would like to prevent non-direct memory accesses running together with unbounded operations
set the schedule information
set the binding information
Check if some successors have become ready
check if to_v should be considered as ready
update priorities and possibly rehash the queues
clear the vises
move to the next cycle
update starting and ending time of operations by running them as late as possible
compute the vertices slack
Definition at line 381 of file parametric_list_based.cpp.
References add_to_priority_queues(), ASLAP::ALAP_fast, ASLAP::ALAP_with_partial_scheduling, hls::allocation_information, BB_update_resources_use(), fu_binding::bind(), FunctionBehavior::CFG, OpGraph::CGetOpGraphInfo(), OpGraph::CGetOpNodeInfo(), check_if_is_live_in_next_cycle(), CheckSchedulabilityConditions(), clock_cycle, CTRL_STEP_MULTIPLIER, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::DFG, do_balanced_scheduling1(), DYNAMIC_MOBILITY, ending_time, FunctionBehavior::FFLSAODG, flow_graph, flow_graph_with_feedbacks, FunctionBehavior::FLSAODG, from_strongtype_cast(), HLSFunctionStep::funId, fu_binding::get_assign(), AllocationInformation::get_execution_time(), AllocationInformation::get_fu_name(), AllocationInformation::get_initiation_time(), tree_helper::get_mangled_fname(), AllocationInformation::get_memory_var(), GET_NAME, AllocationInformation::get_number_fu(), AllocationInformation::get_number_fu_types(), AllocationInformation::get_proxy_memory_var(), AllocationInformation::get_setup_hold_time(), GET_TYPE, HLSFunctionStep::HLS, hls::HLS_C, HLS_step::HLSMgr, INDENT_DBG_MEX, AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_memory_unit(), AllocationInformation::is_operation_bounded(), max(), AllocationInformation::mux_time_unit(), Schedule::num_scheduled(), hls::Param, DesignFlowStep::parameters, parametric_list_based_metric, PRINT_DBG_MEX, hls::Rfu, hls::Rsch, FunctionBehavior::SG, Scheduling::speculation, starting_time, STATIC_FIXED, STATIC_MOBILITY, STR, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, THROW_WARNING, TYPE_FOR, TYPE_GOTO, TYPE_IF, TYPE_LOAD, TYPE_MULTIIF, TYPE_RET, TYPE_STORE, TYPE_SWITCH, TYPE_WHILE, update_starting_ending_time(), update_starting_ending_time_asap(), and update_vertices_slack().
Referenced by InternalExec().
Initialize()
void parametric_list_based::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from HLSFunctionStep.
Definition at line 327 of file parametric_list_based.cpp.
References FunctionBehavior::CFG, FunctionBehavior::CGetOpGraph(), ending_time, HLSFunctionStep::funId, HLS_step::HLSMgr, and Scheduling::Initialize().
InternalExec()
DesignFlowStep_Status parametric_list_based::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Find the minimum slack
Implements HLSFunctionStep.
Definition at line 1494 of file parametric_list_based.cpp.
References hls::allocation_information, FunctionBehavior::CFG, FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), clock_cycle, xml_document::create_root_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, ending_time, EPSILON, exec(), executions_number, FunctionBehavior::FDFG, flow_graph, from_strongtype_cast(), HLSFunctionStep::funId, Schedule::get_cstep_end(), Schedule::get_csteps(), BehavioralHelper::get_function_name(), GET_NAME, AllocationInformation::get_setup_hold_time(), Scheduling::get_spec(), AllocationInformation::getMinimumSlack(), HLSFunctionStep::HLS, hls::HLS_C, HLS_step::HLSMgr, INDENT_OUT_MEX, max(), min, hls::operations, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, Schedule::print(), print_cpu_time(), PRINT_DBG_MEX, hls::Rfu, hls::Rsch, Schedule::set_spec(), AllocationInformation::setMinimumSlack(), START_TIME, STOP_TIME, STR, SUCCESS, xml_document::write_to_file_formatted(), Schedule::WriteDot(), and hls::xwrite().
store_in_chaining_with_load_in()
bool parametric_list_based::store_in_chaining_with_load_in (unsigned int current_vertex_cstep, vertex v) [private]
store_in_chaining_with_load checks if a store is chained with a load operation or vice versa
Parameters
current_vertex_cstep control step of vertex v
v vertex considered
Returns
true in case vertex v is a store or a load operation and it is chained with a load or store operation
Definition at line 1736 of file parametric_list_based.cpp.
References OpGraph::CGetOpNodeInfo(), clock_cycle, ending_time, flow_graph, GET_TYPE, TYPE_LOAD, and TYPE_STORE.
store_in_chaining_with_load_out()
bool parametric_list_based::store_in_chaining_with_load_out (unsigned int current_vertex_cstep, vertex v) [private]
Definition at line 1761 of file parametric_list_based.cpp.
References OpGraph::CGetOpNodeInfo(), clock_cycle, flow_graph, GET_TYPE, starting_time, TYPE_LOAD, and TYPE_STORE.
update_starting_ending_time()
void parametric_list_based::update_starting_ending_time (vertex candidate_v, fu_bindingRef res_binding, OpGraphConstRef op_dfg_graph, const ScheduleConstRef schedule) [private]
update starting and ending time by moving candidate_v as late as possible without increasing the whole latency
non-pipelined operations move towards the control step border
Definition at line 1647 of file parametric_list_based.cpp.
References hls::allocation_information, clock_cycle, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, ending_time, EPSILON, from_strongtype_cast(), fu_binding::get_assign(), AllocationInformation::get_initiation_time(), GET_NAME, HLSFunctionStep::HLS, AllocationInformation::is_operation_bounded(), max(), min, PRINT_DBG_MEX, starting_time, STR, and THROW_ASSERT.
Referenced by do_balanced_scheduling(), do_balanced_scheduling1(), exec(), and update_vertices_timing().
update_starting_ending_time_asap()
void parametric_list_based::update_starting_ending_time_asap (vertex candidate_v, fu_bindingRef res_binding, OpGraphConstRef opDFG, const ScheduleConstRef schedule) [private]
non-pipelined operations move towards the control step border
Definition at line 1693 of file parametric_list_based.cpp.
References hls::allocation_information, clock_cycle, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, ending_time, from_strongtype_cast(), fu_binding::get_assign(), AllocationInformation::get_initiation_time(), GET_NAME, HLSFunctionStep::HLS, AllocationInformation::is_operation_bounded(), max(), PRINT_DBG_MEX, starting_time, STR, and THROW_ASSERT.
Referenced by exec().
update_vertices_slack()
void parametric_list_based::update_vertices_slack (vertex current_v, const ScheduleRef schedule, OpVertexSet & vertices_analyzed, double setup_hold_time, const OpGraphConstRef opDFG) [private]
update the slack of vertices of current_v and of all the vertices in chaining with it
Parameters
current_v is the considered vertex
schedule is the scheduling data structure
vertices_analyzed is the set of vertices having the slack updated
compute the set of operations on the clock frontier
Definition at line 1592 of file parametric_list_based.cpp.
References compute_slack(), Schedule::get_cstep(), min, and Schedule::set_slack().
Referenced by do_balanced_scheduling(), do_balanced_scheduling1(), and exec().
update_vertices_timing()
void parametric_list_based::update_vertices_timing (const ControlStep vertex_cstep, vertex current_v, const ScheduleConstRef schedule, std::list< vertex > & vertices_analyzed, fu_bindingRef res_binding, const OpGraphConstRef opDFG) [private]
update the starting and ending time of the vertices scheduled in the same cs of current_v
Parameters
vertex_cstep is the control step of vertex current_v before its rescheduling
current_v is the current vertex
schedule is the current scheduling
vertices_analyzed is the set of vertices updated
res_binding is the current resource binding
compute the set of operations on the clock frontier
Definition at line 1624 of file parametric_list_based.cpp.
References update_starting_ending_time().
Referenced by do_balanced_scheduling1().
Field Documentation
clock_cycle
double parametric_list_based::clock_cycle [private]
The clock cycle.
Definition at line 167 of file parametric_list_based.hpp.
Referenced by CheckSchedulabilityConditions(), compute_exec_stage_time(), compute_slack(), compute_starting_ending_time_alap(), compute_starting_ending_time_asap(), do_balanced_scheduling(), do_balanced_scheduling1(), exec(), InternalExec(), store_in_chaining_with_load_in(), store_in_chaining_with_load_out(), update_starting_ending_time(), and update_starting_ending_time_asap().
ending_time
OpVertexMap<double> parametric_list_based::ending_time [private]
The ending time given the scheduling (used for chaining)
Definition at line 164 of file parametric_list_based.hpp.
Referenced by compute_starting_ending_time_alap(), compute_starting_ending_time_asap(), do_balanced_scheduling(), do_balanced_scheduling1(), exec(), Initialize(), InternalExec(), store_in_chaining_with_load_in(), update_starting_ending_time(), and update_starting_ending_time_asap().
EPSILON
const double parametric_list_based::EPSILON = 0.000000001 [static], [private]
Definition at line 147 of file parametric_list_based.hpp.
Referenced by CheckSchedulabilityConditions(), compute_exec_stage_time(), compute_slack(), do_balanced_scheduling1(), InternalExec(), and update_starting_ending_time().
executions_number
size_t parametric_list_based::executions_number [private]
Number of executions.
Definition at line 173 of file parametric_list_based.hpp.
Referenced by ComputeRelationships(), and InternalExec().
flow_graph
OpGraphConstRef parametric_list_based::flow_graph [private]
The dependence graph.
Definition at line 155 of file parametric_list_based.hpp.
Referenced by add_to_priority_queues(), check_direct_operation_chaining(), check_LOAD_chaining(), check_non_direct_operation_chaining(), CheckSchedulabilityConditions(), compute_exec_stage_time(), compute_starting_ending_time_alap(), compute_starting_ending_time_asap(), do_balanced_scheduling(), do_balanced_scheduling1(), exec(), InternalExec(), store_in_chaining_with_load_in(), and store_in_chaining_with_load_out().
flow_graph_with_feedbacks
OpGraphConstRef parametric_list_based::flow_graph_with_feedbacks [private]
The dependence graph with feedbacks.
Definition at line 158 of file parametric_list_based.hpp.
Referenced by compute_exec_stage_time(), and exec().
is_complex
CustomUnorderedMapUnstable<std::pair<vertex, unsigned int>, bool> parametric_list_based::is_complex [private]
memoization table used for connection estimation
Definition at line 170 of file parametric_list_based.hpp.
parametric_list_based_metric
const ParametricListBased_Metric parametric_list_based::parametric_list_based_metric [private]
The used metric.
Definition at line 152 of file parametric_list_based.hpp.
Referenced by exec().
starting_time
vertex2float parametric_list_based::starting_time [private]
The starting time given the scheduling (used for chaining)
Definition at line 161 of file parametric_list_based.hpp.
Referenced by compute_slack(), compute_starting_ending_time_alap(), compute_starting_ending_time_asap(), do_balanced_scheduling(), do_balanced_scheduling1(), exec(), store_in_chaining_with_load_out(), update_starting_ending_time(), and update_starting_ending_time_asap().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/parametric_list_based.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/parametric_list_based.cpp