/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/FunctionCallTypeCleanup.cpp File Reference
#include `FunctionCallTypeCleanup.hpp`
#include `Parameter.hpp`
#include `call_graph_manager.hpp`
#include `tree_basic_block.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_manipulation.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
#include `application_manager.hpp`
#include `dbgPrintHelper.hpp`
#include `function_behavior.hpp`
#include `string_manipulation.hpp`
Functions
static bool conv_really_needed (const tree_managerConstRef TM, unsigned int op0, unsigned int op1)
Detailed Description
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Function Documentation
conv_really_needed()
static bool conv_really_needed (const tree_managerConstRef TM, unsigned int op0, unsigned int op1) [inline], [static]
Definition at line 59 of file FunctionCallTypeCleanup.cpp.
References tree_helper::is_a_complex(), tree_helper::is_real(), and tree_helper::size().
Referenced by FunctionCallTypeCleanup::InternalExec().