AddOpExitFlowEdges Class Reference
Class to perform adding of flow edges to operation graph.
#include <add_op_exit_flow_edges.hpp>
Public Member Functions
AddOpExitFlowEdges (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~AddOpExitFlowEdges () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Performs the adding of flow edges to operation graphs.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Class to perform adding of flow edges to operation graph.
Definition at line 62 of file add_op_exit_flow_edges.hpp.
Constructor & Destructor Documentation
AddOpExitFlowEdges()
AddOpExitFlowEdges::AddOpExitFlowEdges (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the node id of the function analyzed.
. include behavior include tree include
Definition at line 61 of file add_op_exit_flow_edges.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~AddOpExitFlowEdges().
 AddOpExitFlowEdges()
AddOpExitFlowEdges::~AddOpExitFlowEdges () [override], [default]
Destructor.
Referenced by AddOpExitFlowEdges().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > AddOpExitFlowEdges::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 69 of file add_op_exit_flow_edges.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, OP_REACHABILITY_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void AddOpExitFlowEdges::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 93 of file add_op_exit_flow_edges.cpp.
References FunctionFrontendFlowStep::bb_version, FunctionBehavior::FLG, FLG_SELECTOR, FunctionFrontendFlowStep::function_behavior, GET_TYPE, and TYPE_LAST_OP.
InternalExec()
DesignFlowStep_Status AddOpExitFlowEdges::InternalExec () [override], [virtual]
Performs the adding of flow edges to operation graphs.
Returns
the exit status of this step
The control flow graph of operation
The control flow graph of basic block
Adding operation to empty return
NOTE: the old version of this code added a flow edge from all the operations which reach last op and not only from the operations of the same basic block: was there any actual reason to do in this way?
Implements FunctionFrontendFlowStep.
Definition at line 110 of file add_op_exit_flow_edges.cpp.
References FunctionBehavior::BB, OpGraph::CGetOpNodeInfo(), FunctionBehavior::FCFG, FunctionBehavior::FFLSAODG, FunctionBehavior::FLG, FLG_SELECTOR, FunctionFrontendFlowStep::function_behavior, GET_TYPE, DesignFlowStep::parameters, SUCCESS, and TYPE_LAST_OP.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_op_exit_flow_edges.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_op_exit_flow_edges.cpp