tree_node Class Reference
Abstract pure class for the tree structure.
#include <tree_node.hpp>
Public Member Functions
tree_node (unsigned int i)
Constructor.
virtual ~tree_node ()
Destructor.
virtual enum kind get_kind () const =0
Virtual function returning the type of the actual class.
virtual std::string get_kind_text () const =0
Virtual function returning the name of the actual class.
virtual void visit (tree_node_visitor *const v) const
virtual function used to traverse the tree_node data structure.
std::string ToString () const
Print this node as string in gimple format.
Static Public Member Functions
static enum kind get_kind (const std::string &name)
Given a string, return the corresponding kind.
static std::string GetString (const enum kind k)
Given a kind, return the corresponding string.
Data Fields
const unsigned int index
Represent the index readed from the raw file and the index-1 of the vector of tree_node associated to the functions vector present in the tree_manager.
Static Private Attributes
static std::map< std::string, enum kind > string_to_kind
Map string to corresponding enum.
static std::map< enum kind, std::string > kind_to_string
Map kind to string.
Friends
std::ostream & operator<< (std::ostream &os, const tree_node *tn)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const tree_nodeRef &tn)
Friend definition of the << operator.
Detailed Description
Abstract pure class for the tree structure.
This node and in particular its refCount type will be used to describe all nodes readed from the tree gcc raw structure.
Definition at line 128 of file tree_node.hpp.
Constructor & Destructor Documentation
tree_node()
tree_node::tree_node (unsigned int i) [inline], [explicit]
Constructor.
Definition at line 147 of file tree_node.hpp.
Referenced by handler::visit().
 tree_node()
virtual tree_node::~tree_node () [inline], [virtual]
Destructor.
Definition at line 152 of file tree_node.hpp.
References operator<<(), and ToString().
Member Function Documentation
get_kind() [1/2]
virtual enum kind tree_node::get_kind () const [pure virtual]
Virtual function returning the type of the actual class.
Referenced by tree_helper::accessed_greatest_bitsize(), tree_helper::accessed_minimum_bitsize(), TestbenchMemoryAllocation::AllocTestbenchMemory(), determine_memory_accesses::analyze_node(), use_counting::analyze_node(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyMultiMerge(), IR_lowering::array_ref_lowering(), Bit_Value::backward(), Bit_Value::backward_compute_result_from_uses(), operations_cfg_computation::build_operation_recursive(), call_graph_computation::call_graph_computation_recursive(), tree_manager::check_for_decl(), tree_manager::check_for_type(), FunctionExpander::check_lib_type(), CSE::check_loads(), tree_manager::check_ssa_uses(), simple_code_motion::CheckMovable(), Vectorize::ClassifyTreeNode(), tree_manager::collapse_into(), tree_helper::compute_ssa_uses_rec_ptr(), tree_helper::ComputeSsaUses(), BitLatticeManipulator::constructor_bitstring(), tree_manipulation::create_binary_operation(), mux_connection_binding::create_connections(), tree_manipulation::create_extract_bit_expr(), tree_manipulation::create_gimple_cond(), tree_manipulation::create_gimple_modify_stmt(), tree_manipulation::create_gimple_return(), tree_manipulation::create_lut_expr(), tree_manipulation::create_parm_decl(), tree_manipulation::create_phi_node(), tree_manipulation::create_quaternary_operation(), tree_manipulation::create_result_decl(), tree_manipulation::create_ternary_operation(), tree_node_dup::create_tree_node(), tree_node_index_factory::create_tree_node(), tree_manipulation::create_unary_operation(), tree_manipulation::create_var_decl(), VcdSignalSelection::CrossPropagateAddrSsa(), HLSInstructionWriter::declareFunction(), CWriter::DeclareLocalVariables(), mux_connection_binding::determine_connection(), tree_manager::erase_usage_info(), BitValueIPA::Exec(), PragmaAnalysis::Exec(), tree_helper::extract_array_indexes(), rebuild_initialization2::extract_var_decl(), extractOp1(), memory_allocation::finalize_memory_allocation(), tree_helper::get_array_data_bitsize(), tree_helper::get_array_dim_and_bitsize(), tree_helper::get_array_dimensions(), BehavioralHelper::get_attributes(), tree_helper::get_base_index(), operations_cfg_computation::get_first_node(), tree_helper::get_formal_ith(), fsm_controller::get_guard_value(), tree_helper::get_integer_cst_value(), BehavioralHelper::get_intermediate_var(), tree_manager::get_next_vers(), tree_helper::get_parameter_types(), tree_helper::get_pointed_type(), application_manager::get_produced_value(), tree_helper::get_required_values(), tree_helper::get_type_index(), tree_helper::get_type_node(), tree_helper::get_used_variables(), getAssign(), tree_helper::GetFunctionReturnType(), BehavioralHelper::GetInit(), GimpleWriter::GimpleWriter(), BehavioralHelper::has_bit_field(), CSE::hash_check(), tree_helper::HasToBeDeclared(), Bit_Value::initialize(), tree_manager::insert_usage_info(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), LoopsAnalysisBambu::InternalExec(), compute_implicit_calls::InternalExec(), dead_code_elimination::InternalExec(), multi_way_if::InternalExec(), IR_lowering::InternalExec(), tree_helper::is_a_complex(), BehavioralHelper::is_a_component_ref(), BehavioralHelper::is_a_constant(), BehavioralHelper::is_a_imagpart_expr(), BehavioralHelper::is_a_mem_ref(), BehavioralHelper::is_a_realpart_expr(), BehavioralHelper::is_a_result_decl(), tree_helper::is_a_struct(), tree_helper::is_a_variable(), tree_helper::is_a_vector(), BehavioralHelper::is_an_addr_expr(), tree_helper::is_an_addr_expr(), tree_helper::is_an_array(), BehavioralHelper::is_an_array_ref(), tree_helper::is_an_enum(), BehavioralHelper::is_an_indirect_ref(), tree_helper::is_an_union(), tree_helper::is_concat_bit_ior_expr(), tree_helper::is_constant(), fanout_opt::is_dest_relevant(), tree_helper::is_fully_resolved(), is_large_integer(), BehavioralHelper::is_named_pointer(), tree_helper::is_natural(), tree_helper::is_packed(), tree_helper::is_packed_access(), tree_helper::is_SC_BIND_PROXY_NIL(), tree_helper::is_simple_pointer_plus_test(), tree_manager::is_top_function(), BehavioralHelper::is_va_start_call(), BehavioralHelper::is_var_args(), BehavioralHelper::isCallExpression(), HWCallInjection::isHardwareCall(), dead_code_elimination::kill_uses(), rebuild_initialization2::look_for_ROMs(), CallGraphBuiltinCall::lookForBuiltinCall(), tree_manager::merge_tree_managers(), tree_helper::name_function(), tree_helper::name_tmpl(), tree_helper::name_type(), tree_helper::op_symbol(), type_casting::operator()(), BBWriter::operator()(), FunctionExpander::operator()(), Bit_Value_opt::optimize(), BehavioralHelper::print_constant(), BehavioralHelper::print_forward_declaration(), tree_helper::print_function_name(), BehavioralHelper::print_init(), BehavioralHelper::print_node(), tree_helper::print_type(), BehavioralHelper::print_type_declaration(), BehavioralHelper::print_vertex(), BehavioralHelper::PrintVariable(), IR_lowering::reached_max_transformation_limit(), tree_helper::record_name(), parm2ssa::recursive_analysis(), string_cst_fix::recursive_analysis(), hls_div_cg_ext::recursive_examinate(), VarDeclFix::recursive_examinate(), CheckSystemType::recursive_examinate(), soft_float_cg_ext::RecursiveExaminate(), tree_helper::RecursiveGetTypesToBeDeclared(), tree_manager::RecursiveReplaceTreeNode(), VcdSignalSelection::SelectInitialSsa(), VcdSignalSelection::SelectInternalSignals(), VcdSignalSelection::SingleStepPropagateAddrSsa(), tree_helper::Size(), BitLatticeManipulator::string_cst_bitstring(), Vectorize::Transform(), Bit_Value::update_IR(), varFound(), fu_binding::write_init(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteParamDecl(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), EdgeCWriter::writeRoutineInstructions_rec(), CWriter::writeRoutineInstructions_rec(), HLSCWriter::WriteSimulatorInitMemory(), and HLSCWriter::WriteTestbenchFunctionCall().
get_kind() [2/2]
enum kind tree_node::get_kind (const std::string & name) [static]
Given a string, return the corresponding kind.
Parameters
name is the string
Returns
the corresponding kind
Definition at line 99 of file tree_node.cpp.
References BOOST_PP_SEQ_FOR_EACH(), NAME_KIND, string_to_kind, and TREE_NODE_LIST.
get_kind_text()
virtual std::string tree_node::get_kind_text () const [pure virtual]
Virtual function returning the name of the actual class.
Referenced by tree_helper::accessed_greatest_bitsize(), tree_helper::accessed_minimum_bitsize(), determine_memory_accesses::analyze_node(), Bit_Value::backward_compute_result_from_uses(), operations_cfg_computation::build_operation_recursive(), simple_code_motion::CheckMovable(), tree_manager::collapse_into(), tree_helper::compute_ssa_uses_rec_ptr(), mux_connection_binding::create_connections(), tree_node_dup::create_tree_node(), tree_node_factory::create_tree_node(), tree_node_index_factory::create_tree_node(), mux_connection_binding::determine_connection(), BitValueIPA::Exec(), fu_binding::fill_array_ref_memory(), BehavioralHelper::get_attributes(), tree_helper::get_base_index(), operations_cfg_computation::get_first_node(), tree_helper::get_integer_cst_value(), application_manager::get_produced_value(), tree_helper::get_required_values(), tree_helper::get_type_node(), BehavioralHelper::GetInit(), GimpleWriter::GimpleWriter(), CSE::hash_check(), tree_helper::HasToBeDeclared(), LoopsAnalysisBambu::InternalExec(), multi_way_if::InternalExec(), tree_helper::is_a_variable(), tree_helper::is_fully_resolved(), tree_helper::is_packed(), tree_helper::is_packed_access(), tree_helper::IsAligned(), CallGraphBuiltinCall::lookForBuiltinCall(), tree_manager::merge_tree_managers(), tree_helper::name_function(), tree_helper::name_type(), tree_helper::op_symbol(), BehavioralHelper::print_constant(), BehavioralHelper::print_forward_declaration(), tree_helper::print_function_name(), BehavioralHelper::print_node(), tree_helper::print_type(), BehavioralHelper::print_type_declaration(), BehavioralHelper::PrintVarDeclaration(), parm2ssa::recursive_analysis(), string_cst_fix::recursive_analysis(), hls_div_cg_ext::recursive_examinate(), VarDeclFix::recursive_examinate(), CheckSystemType::recursive_examinate(), soft_float_cg_ext::RecursiveExaminate(), Vectorize::Transform(), Bit_Value::update_IR(), fu_binding::write_init(), raw_writer::write_when_not_null_point_to(), and HLSCWriter::WriteSimulatorInitMemory().
GetString()
std::string tree_node::GetString (const enum kind k) [static]
Given a kind, return the corresponding string.
Parameters
k is the kind
Returns
the name of the kind
Definition at line 110 of file tree_node.cpp.
References BINARY_EXPRESSION_TREE_NODES, BOOST_PP_SEQ_FOR_EACH(), KIND_NAME, kind_to_string, QUATERNARY_EXPRESSION_TREE_NODES, TERNARY_EXPRESSION_TREE_NODES, TREE_NODE_LIST, UNARY_EXPRESSION_TREE_NODES, and VISIT_TREE_NODE_MACRO.
Referenced by tree_manager::find(), VcdSignalSelection::InitialPhiResIsAddress(), VcdSignalSelection::InitialSsaIsAddress(), dead_code_elimination::InternalExec(), VcdSignalSelection::PropagateAddrSsa(), VcdSignalSelection::SelectInitialAddrParam(), VcdSignalSelection::SingleStepPropagateAddrSsa(), and VcdSignalSelection::SingleStepPropagateParamToSsa().
ToString()
std::string tree_node::ToString () const
Print this node as string in gimple format.
Returns
the string containing the gimple representation of this node
Referenced by determine_memory_accesses::analyze_node(), use_counting::analyze_node(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiRemove(), Bit_Value::backward_transfer(), HWCallInjection::buildBuiltinCall(), AllocationInformation::can_implement_set(), Schedule::CanBeMoved(), ssa_name::CGetDefStmt(), simple_code_motion::CheckMovable(), interface_infer::classifyArgRecurse(), Vectorize::ClassifyTreeNode(), tree_manager::collapse_into(), tree_helper::compute_ssa_uses_rec_ptr(), BitLatticeManipulator::constructor_bitstring(), PragmaAnalysis::create_omp_pragma(), tree_manipulation::create_ssa_name(), Vectorize::DuplicateIncrement(), ipa_point_to_analysis::Exec(), IR_lowering::expand_mult_const(), tree_manipulation::ExtractCondition(), extractOp1(), memory_allocation::finalize_memory_allocation(), Vectorize::FixPhis(), liveness::get_op_where_defined(), AllocationInformation::GetNodeTypePrec(), CSE::hash_check(), mem_dominator_allocation::InternalExec(), LoopsAnalysisBambu::InternalExec(), compute_implicit_calls::InternalExec(), fanout_opt::InternalExec(), simple_code_motion::InternalExec(), CSE::InternalExec(), operations_cfg_computation::InternalExec(), allocation::InternalExec(), cdfc_module_binding::InternalExec(), rebuild_initialization2::look_for_ROMs(), Bit_Value_opt::optimize(), bloc::PushAfter(), bloc::PushBack(), bloc::PushBefore(), bloc::PushFront(), parm2ssa::recursive_analysis(), string_cst_fix::recursive_analysis(), VarDeclFix::recursive_examinate(), tree_manager::RecursiveReplaceTreeNode(), PhiOpt::RemoveCondExpr(), gimple_phi::RemoveDefEdge(), bloc::RemovePhi(), bloc::RemoveStmt(), ssa_name::RemoveUse(), tree_manager::ReplaceTreeNode(), VcdSignalSelection::SingleStepPropagateAddrSsa(), VcdSignalSelection::SingleStepPropagateParamToSsa(), Vectorize::Transform(), typename_type(), and fu_binding::write_init().
visit()
virtual void tree_node::visit (tree_node_visitor *const v) const [virtual]
virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented in lut_expr, vector_type, vector_cst, var_decl, union_type, type_decl, try_block, tree_vec, tree_list, nontype_argument_pack, type_argument_pack, template_parm_index, template_decl, target_mem_ref461, target_mem_ref, target_expr, gimple_switch, string_cst, statement_list, ssa_name, scope_ref, return_stmt, gimple_return, gimple_resx, result_decl, reference_type, record_type, real_type, real_cst, pointer_type, gimple_predict, gimple_phi, parm_decl, overload, namespace_decl, method_type, gimple_label, integer_type, integer_cst, identifier_node, handler, gimple_goto, gimple_nop, gimple_assign, function_type, function_decl, field_decl, expr_stmt, enumeral_type, constructor, const_decl, gimple_cond, complex_type, complex_cst, expr_pack_expansion, type_pack_expansion, cast_expr, case_label_expr, gimple_call, aggr_init_expr, call_expr, block, binfo, gimple_bind, baselink, gimple_asm, array_type, error_mark, cst_node, memory_tag, type_node, quaternary_expr, ternary_expr, binary_expr, unary_expr, gimple_node, expr_node, decl_node, gimple_multi_way_if, WeightedNode, gimple_for, gimple_while, omp_declare_simd_pragma, omp_simd_pragma, omp_for_pragma, omp_atomic_pragma, omp_critical_pragma, omp_task_pragma, omp_target_pragma, omp_section_pragma, omp_parallel_sections_pragma, omp_sections_pragma, omp_parallel_pragma, omp_pragma, blackbox_pragma, issue_pragma, call_point_hw_pragma, call_hw_pragma, map_pragma, statistical_profiling, profiling_pragma, gimple_pragma, tree_reindex, and null_node.
Referenced by BehavioralHelper::get_typecast(), GimpleWriter::GimpleWriter(), CallGraphBuiltinCall::InternalExec(), tree_manager::merge_tree_managers(), and typename_type().
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, const tree_node * tn) [friend]
Friend definition of the << operator.
Parameters
os is the output stream
tn is the tree_node to be printed
Referenced by typename_type().
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const tree_nodeRef & tn) [friend]
Friend definition of the << operator.
Parameters
os is the output stream
tn is the tree_node to be printed
Definition at line 158 of file tree_node.cpp.
Field Documentation
index
const unsigned int tree_node::index
Represent the index readed from the raw file and the index-1 of the vector of tree_node associated to the functions vector present in the tree_manager.
Definition at line 142 of file tree_node.hpp.
Referenced by tree_helper::accessed_greatest_bitsize(), gimple_phi::AddDefEdge(), bloc::AddPhi(), determine_memory_accesses::analyze_node(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), operations_cfg_computation::build_operation_recursive(), simple_code_motion::CheckMovable(), tree_manipulation::create_gimple_call(), short_circuit_taf::create_gimple_cond(), tree_manipulation::CreateGimpleAssign(), Vectorize::DuplicateIncrement(), IR_lowering::expand_sdiv_pow2(), IR_lowering::expand_smod_pow2(), CallGraphBuiltinCall::ExtendCallGraph(), tree_manipulation::ExtractCondition(), Bit_Value::forward_transfer(), tree_helper::get_base_index(), Schedule::GetBBEndingTime(), BehavioralHelper::GetFunctionReturnType(), OpNodeInfo::GetNodeId(), GimpleWriter::GimpleWriter(), CSE::hash_check(), Bit_Value::initialize(), LoopsAnalysisBambu::InternalExec(), constant_flop_wrapper::InternalExec(), hls_div_cg_ext::InternalExec(), CondExprRestructuring::InternalExec(), CSE::InternalExec(), MultipleEntryIfReduction::InternalExec(), IR_lowering::InternalExec(), CallGraphBuiltinCall::lookForBuiltinCall(), tree_helper::op_symbol(), type_casting::operator()(), Bit_Value_opt::optimize(), tree_reindex::print(), BehavioralHelper::print_node(), BehavioralHelper::PrintVariable(), bloc::PushAfter(), bloc::PushBack(), bloc::PushBefore(), bloc::PushFront(), hls_div_cg_ext::recursive_examinate(), soft_float_cg_ext::RecursiveExaminate(), tree_helper::RecursiveGetTypesToBeDeclared(), tree_manager::RecursiveReplaceTreeNode(), gimple_phi::RemoveDefEdge(), bloc::RemovePhi(), bloc::RemoveStmt(), bloc::Replace(), gimple_phi::ReplaceDefEdge(), Vectorize::Transform(), typename_type(), expr_pack_expansion::visit(), and fu_binding::write_init().
kind_to_string
std::map< enum kind, std::string > tree_node::kind_to_string [static], [private]
Map kind to string.
Definition at line 135 of file tree_node.hpp.
Referenced by GetString().
string_to_kind
std::map< std::string, enum kind > tree_node::string_to_kind [static], [private]
Map string to corresponding enum.
Definition at line 132 of file tree_node.hpp.
Referenced by get_kind().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp