HLSFlowStepFactory Class Reference
#include <hls_flow_step_factory.hpp>
Public Member Functions
HLSFlowStepFactory (const DesignFlowManagerConstRef design_flow_manager, const HLS_managerRef _HLS_manager, const ParameterConstRef parameters)
Constructor.
~HLSFlowStepFactory () override
Destructor.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
DesignFlowStepRef CreateHLSFlowStep (const HLSFlowStep_Type hls_flow_step_type, const unsigned int funId, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization=HLSFlowStepSpecializationConstRef()) const
Create a scheduling design flow step.
const DesignFlowStepSet CreateHLSFlowSteps (const CustomUnorderedSet< std::pair< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef >> &hls_flow_steps) const
Create the frontend design flow steps.
const DesignFlowStepSet CreateHLSFlowSteps (const std::pair< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef > &hls_flow_step) const
The same as CreateHLSFlowSteps, but just for one step.
const DesignFlowStepSet CreateHLSFlowSteps (const HLSFlowStep_Type type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization) const
The same as CreateHLSFlowSteps, but just for one step, with an even simpler syntax.
const DesignFlowStepRef CreateHLSFlowStep (const std::pair< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef > &hls_flow_step) const
const DesignFlowStepRef CreateHLSFlowStep (const HLSFlowStep_Type type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization) const
Protected Member Functions
bool checkNode (const xml_element *node, unsigned int funId, const std::string &ref_step) const
Verifies if the current node has to be added to the list of steps.
Protected Attributes
const HLS_managerRef HLS_mgr
The HLS manager.
Detailed Description
Definition at line 57 of file hls_flow_step_factory.hpp.
Constructor & Destructor Documentation
HLSFlowStepFactory()
HLSFlowStepFactory::HLSFlowStepFactory (const DesignFlowManagerConstRef _design_flow_manager, const HLS_managerRef _HLS_mgr, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
design_flow_manager is the design flow manager
HLS_manager is the HLS manager
parameters is the set of input parameters
. include Header include Behavior include design_flow includes HLS/architecture_creator HLS/architecture_creator/datapath_creation ///HLS/architecture_creator/controller_creation HLS backend include HLS/binding/interconnection includes HLS/binding/module include HLS/binding/register/algorithms includes HLS/binding/storage_value_insertion includes HLS/chaining HLS/evaluation HLS/evaluation/exact includes HLS/evaluation/linear includes HLS/function_allocation HLS/hls_flow includes HLS/hls_flow/synthesis includes HLS/interface/NPI include HLS/interface/WB4 includes HLS/liveness includes HLS/memory includes HLS/memory HLS/module_allocation includes HLS/scheduling include HLS/simulation includes HLS/stg polixml STD include STL includes tree include utility include
Definition at line 282 of file hls_flow_step_factory.cpp.
References DesignFlowStepFactory::debug_level, GET_CLASS, DesignFlowStepFactory::parameters, and ~HLSFlowStepFactory().
 HLSFlowStepFactory()
HLSFlowStepFactory::~HLSFlowStepFactory () [override], [default]
Destructor.
Referenced by HLSFlowStepFactory().
Member Function Documentation
checkNode()
bool HLSFlowStepFactory::checkNode (const xml_element * node, unsigned int funId, const std::string & ref_step) const [protected]
Verifies if the current node has to be added to the list of steps.
CreateHLSFlowStep() [1/3]
DesignFlowStepRef HLSFlowStepFactory::CreateHLSFlowStep (const HLSFlowStep_Type hls_flow_step_type, const unsigned int funId, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization = HLSFlowStepSpecializationConstRef()) const
Create a scheduling design flow step.
Parameters
hls_flow_step_type is the type of scheduling step to be created
funId is the index of the function to be scheduled
hls_flow_step_specialization contains information about how specialize the single step
Definition at line 294 of file hls_flow_step_factory.cpp.
References ADD_LIBRARY, ALLOCATION, BB_STG_CREATOR, C_TESTBENCH_EXECUTION, CALL_GRAPH_UNFOLDING, CDFC_MODULE_BINDING, CHORDAL_COLORING_REGISTER_BINDING, CLASSIC_DATAPATH_CREATOR, CLASSICAL_HLS_SYNTHESIS_FLOW, COLORING_REGISTER_BINDING, HLSFunctionStep::ComputeSignature(), HLS_step::ComputeSignature(), CONTROL_FLOW_CHECKER, DATAPATH_CS_CREATOR, DATAPATH_CS_PARALLEL_CREATOR, DesignFlowStepFactory::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStepFactory::design_flow_manager, DOMINATOR_FUNCTION_ALLOCATION, DOMINATOR_MEMORY_ALLOCATION, DOMINATOR_MEMORY_ALLOCATION_CS, DRY_RUN_EVALUATION, EASY_MODULE_BINDING, HLS_step::EnumToName(), EVALUATION, FIXED_SCHEDULING, FSM_CONTROLLER_CREATOR, FSM_CS_CONTROLLER_CREATOR, FSM_NI_SSA_LIVENESS, GENERATE_HDL, GENERATE_SIMULATION_SCRIPT, GENERATE_SYNTHESIS_SCRIPT, HLS_BIT_VALUE, HLS_FUNCTION_BIT_VALUE, HLS_mgr, HLS_SYNTHESIS_FLOW, HW_DISCREPANCY_ANALYSIS, HW_PATH_COMPUTATION, INDENT_DBG_MEX, INFERRED_INTERFACE_GENERATION, INITIALIZE_HLS, INTERFACE_CS_GENERATION, LIST_BASED_SCHEDULING, Wrefcount< T >::lock(), MINIMAL_INTERFACE_GENERATION, MINIMAL_TESTBENCH_GENERATION, MUX_INTERCONNECTION_BINDING, OMP_BODY_LOOP_SYNTHESIS_FLOW, DesignFlowStepFactory::parameters, PORT_SWAPPING, SCHED_CHAINING, STANDARD_HLS_FLOW, TEST_VECTOR_PARSER, TESTBENCH_GENERATION, TESTBENCH_MEMORY_ALLOCATION, TESTBENCH_VALUES_C_GENERATION, TESTBENCH_VALUES_XML_GENERATION, THROW_UNREACHABLE, TOP_ENTITY_CREATION, TOP_ENTITY_CS_CREATION, TOP_ENTITY_CS_PARALLEL_CREATION, TOP_ENTITY_MEMORY_MAPPED_CREATION, UNIQUE_MODULE_BINDING, UNIQUE_REGISTER_BINDING, UNKNOWN, VALUES_SCHEME_STORAGE_VALUE_INSERTION, VIRTUAL_DESIGN_FLOW, WB4_INTERCON_INTERFACE_GENERATION, WB4_INTERFACE_GENERATION, WB4_TESTBENCH_GENERATION, WEIGHTED_CLIQUE_REGISTER_BINDING, WRITE_HLS_SUMMARY, and XML_MEMORY_ALLOCATOR.
Referenced by CBackend::ComputeRelationships(), and CreateHLSFlowSteps().
CreateHLSFlowStep() [2/3]
const DesignFlowStepRef HLSFlowStepFactory::CreateHLSFlowStep (const std::pair< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef > & hls_flow_step) const
Definition at line 1064 of file hls_flow_step_factory.cpp.
References CreateHLSFlowSteps().
CreateHLSFlowStep() [3/3]
const DesignFlowStepRef HLSFlowStepFactory::CreateHLSFlowStep (const HLSFlowStep_Type type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization) const
Definition at line 1069 of file hls_flow_step_factory.cpp.
References CreateHLSFlowSteps().
CreateHLSFlowSteps() [1/3]
const DesignFlowStepSet HLSFlowStepFactory::CreateHLSFlowSteps (const CustomUnorderedSet< std::pair< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef >> & hls_flow_steps) const
Create the frontend design flow steps.
Parameters
hls_flow_steps is the set of steps to be created
Definition at line 865 of file hls_flow_step_factory.cpp.
References ADD_LIBRARY, ALLOCATION, BB_STG_CREATOR, C_TESTBENCH_EXECUTION, CALL_GRAPH_UNFOLDING, CDFC_MODULE_BINDING, CHORDAL_COLORING_REGISTER_BINDING, CLASSIC_DATAPATH_CREATOR, CLASSICAL_HLS_SYNTHESIS_FLOW, COLORING_REGISTER_BINDING, CONTROL_FLOW_CHECKER, CreateHLSFlowStep(), DATAPATH_CS_CREATOR, DATAPATH_CS_PARALLEL_CREATOR, DesignFlowStepFactory::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DOMINATOR_FUNCTION_ALLOCATION, DOMINATOR_MEMORY_ALLOCATION, DOMINATOR_MEMORY_ALLOCATION_CS, DRY_RUN_EVALUATION, EASY_MODULE_BINDING, HLS_step::EnumToName(), EVALUATION, FIXED_SCHEDULING, FSM_CONTROLLER_CREATOR, FSM_CS_CONTROLLER_CREATOR, FSM_NI_SSA_LIVENESS, GENERATE_HDL, GENERATE_SIMULATION_SCRIPT, GENERATE_SYNTHESIS_SCRIPT, HLS_BIT_VALUE, HLS_FUNCTION_BIT_VALUE, HLS_mgr, HLS_SYNTHESIS_FLOW, HW_DISCREPANCY_ANALYSIS, HW_PATH_COMPUTATION, INDENT_DBG_MEX, INFERRED_INTERFACE_GENERATION, INITIALIZE_HLS, INTERFACE_CS_GENERATION, LIST_BASED_SCHEDULING, MINIMAL_INTERFACE_GENERATION, MINIMAL_TESTBENCH_GENERATION, MUX_INTERCONNECTION_BINDING, OMP_BODY_LOOP_SYNTHESIS_FLOW, PORT_SWAPPING, SCHED_CHAINING, STANDARD_HLS_FLOW, TEST_VECTOR_PARSER, TESTBENCH_GENERATION, TESTBENCH_MEMORY_ALLOCATION, TESTBENCH_VALUES_C_GENERATION, TESTBENCH_VALUES_XML_GENERATION, THROW_UNREACHABLE, TOP_ENTITY_CREATION, TOP_ENTITY_CS_CREATION, TOP_ENTITY_CS_PARALLEL_CREATION, TOP_ENTITY_MEMORY_MAPPED_CREATION, UNIQUE_MODULE_BINDING, UNIQUE_REGISTER_BINDING, UNKNOWN, VALUES_SCHEME_STORAGE_VALUE_INSERTION, VIRTUAL_DESIGN_FLOW, WB4_INTERCON_INTERFACE_GENERATION, WB4_INTERFACE_GENERATION, WB4_TESTBENCH_GENERATION, WEIGHTED_CLIQUE_REGISTER_BINDING, WRITE_HLS_SUMMARY, and XML_MEMORY_ALLOCATOR.
Referenced by CreateHLSFlowStep(), and CreateHLSFlowSteps().
CreateHLSFlowSteps() [2/3]
const DesignFlowStepSet HLSFlowStepFactory::CreateHLSFlowSteps (const std::pair< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef > & hls_flow_step) const
The same as CreateHLSFlowSteps, but just for one step.
Definition at line 1051 of file hls_flow_step_factory.cpp.
References CreateHLSFlowSteps().
CreateHLSFlowSteps() [3/3]
const DesignFlowStepSet HLSFlowStepFactory::CreateHLSFlowSteps (const HLSFlowStep_Type type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization) const
The same as CreateHLSFlowSteps, but just for one step, with an even simpler syntax.
Definition at line 1058 of file hls_flow_step_factory.cpp.
References CreateHLSFlowSteps().
GetPrefix()
const std::string HLSFlowStepFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 289 of file hls_flow_step_factory.cpp.
Field Documentation
HLS_mgr
const HLS_managerRef HLSFlowStepFactory::HLS_mgr [protected]
The HLS manager.
Definition at line 61 of file hls_flow_step_factory.hpp.
Referenced by CreateHLSFlowStep(), and CreateHLSFlowSteps().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow_step_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow_step_factory.cpp