FixStructsPassedByValue Class Reference
#include <FixStructsPassedByValue.hpp>
Public Member Functions
FixStructsPassedByValue (const ParameterConstRef params, const application_managerRef AM, unsigned int fun_id, const DesignFlowManagerConstRef dfm)
Constructor.
~FixStructsPassedByValue () override
Destructor.
Protected Member Functions
DesignFlowStep_Status InternalExec () override
Execute the step.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 45 of file FixStructsPassedByValue.hpp.
Constructor & Destructor Documentation
FixStructsPassedByValue()
FixStructsPassedByValue::FixStructsPassedByValue (const ParameterConstRef params, const application_managerRef AM, unsigned int fun_id, const DesignFlowManagerConstRef dfm)
Constructor.
Definition at line 55 of file FixStructsPassedByValue.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~FixStructsPassedByValue().
 FixStructsPassedByValue()
FixStructsPassedByValue::~FixStructsPassedByValue () [override], [default]
Destructor.
Referenced by FixStructsPassedByValue().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > FixStructsPassedByValue::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 425 of file FixStructsPassedByValue.cpp.
References BLOCK_FIX, FrontendFlowStep::CALLING_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, STRING_CST_FIX, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
InternalExec()
DesignFlowStep_Status FixStructsPassedByValue::InternalExec () [override], [protected], [virtual]
Execute the step.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 111 of file FixStructsPassedByValue.cpp.
References ALGN_POINTER, FrontendFlowStep::AppM, test_panda::args, BB_ENTRY, BB_EXIT, cannot_have_struct_parameters(), tree_manager::CGetTreeReindex(), tree_helper::CGetType(), tree_manipulation::create_gimple_call(), tree_manipulation::create_identifier_node(), tree_manipulation::create_parm_decl(), tree_manipulation::create_pointer_type(), tree_manipulation::create_ssa_name(), tree_manipulation::create_var_decl(), tree_manipulation::CreateAddrExpr(), tree_manipulation::CreateGimpleAssignAddrExpr(), tree_manipulation::CreateIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_manager::function_index(), GET_CONST_NODE, tree_helper::get_formal_ith(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), srcp::include_name, INDENT_DBG_MEX, tree_helper::is_a_struct(), tree_helper::is_an_union(), tree_helper::name_function(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), tree_helper::Size(), sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, ToString(), and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/FixStructsPassedByValue.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/FixStructsPassedByValue.cpp