conn_binding_creator Class Reference
Generic class managing interconnection binding algorithms.
#include <conn_binding_creator.hpp>
Public Member Functions
conn_binding_creator (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
~conn_binding_creator () override
Destructor.
Protected Member Functions
void add_parameter_ports ()
Add ports representing parameter values.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Protected Attributes
std::map< unsigned int, generic_objRef > input_ports
map between input port variable and generic object
std::map< unsigned int, generic_objRef > output_ports
map between output port variable and generic object
Additional Inherited Members
Detailed Description
Generic class managing interconnection binding algorithms.
Definition at line 69 of file conn_binding_creator.hpp.
Constructor & Destructor Documentation
conn_binding_creator()
conn_binding_creator::conn_binding_creator (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
Constructor.
Autoheader include.
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the type of connection binding algorithm
HLS includes HLS/binding/interconnection HLS/binding/module includes HLS/binding/register/algorithms includes behavior include
Definition at line 74 of file conn_binding_creator.cpp.
References ~conn_binding_creator().
 conn_binding_creator()
conn_binding_creator::~conn_binding_creator () [override], [default]
Destructor.
Referenced by conn_binding_creator().
Member Function Documentation
add_parameter_ports()
void conn_binding_creator::add_parameter_ports () [protected]
Add ports representing parameter values.
list containing the parameters of the original function (representing input and output values)
Definition at line 119 of file conn_binding_creator.cpp.
References conn_binding::bind_port(), FunctionBehavior::CGetBehavioralHelper(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, HLSFunctionStep::funId, BehavioralHelper::get_function_index(), BehavioralHelper::get_parameters(), BehavioralHelper::GetFunctionReturnType(), HLSFunctionStep::HLS, HLS_step::HLSMgr, conn_binding::IN, input_ports, conn_binding::OUT, output_ports, PRINT_DBG_MEX, PRINT_DBG_STRING, BehavioralHelper::print_type(), BehavioralHelper::PrintVariable(), hls::Rconn, and STR.
Referenced by mux_connection_binding::create_connections().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > conn_binding_creator::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 81 of file conn_binding_creator.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, PORT_SWAPPING, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Field Documentation
input_ports
std::map<unsigned int, generic_objRef> conn_binding_creator::input_ports [protected]
map between input port variable and generic object
Definition at line 73 of file conn_binding_creator.hpp.
Referenced by add_parameter_ports(), and mux_connection_binding::connect_to_registers().
output_ports
std::map<unsigned int, generic_objRef> conn_binding_creator::output_ports [protected]
map between output port variable and generic object
Definition at line 76 of file conn_binding_creator.hpp.
Referenced by add_parameter_ports().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/conn_binding_creator.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/conn_binding_creator.cpp