CallGraph Class Reference
This class is the view of a call graph.
#include <call_graph.hpp>
Public Member Functions
CallGraph (const CallGraphsCollectionRef call_graphs_collection, const int selector)
Constructor.
CallGraph (const CallGraphsCollectionRef call_graphs_collection, const int selector, const CustomUnorderedSet< vertex > &vertices)
Constructor.
~CallGraph () override
Destructor.
const FunctionEdgeInfoConstRef CGetFunctionEdgeInfo (const EdgeDescriptor edge) const
Return the info associated with an edge.
const CallGraphInfoConstRef CGetCallGraphInfo () const
Return the info associated with the call graph.
CallGraphInfoRef GetCallGraphInfo ()
Return the info associated with the call graph.
void WriteDot (const std::string &file_name) const
Write the call graph in dot format.
Additional Inherited Members
Detailed Description
This class is the view of a call graph.
Definition at line 153 of file call_graph.hpp.
Constructor & Destructor Documentation
CallGraph() [1/2]
CallGraph::CallGraph (const CallGraphsCollectionRef call_graphs_collection, const int selector)
Constructor.
Parameters
call_graphs_collection is the starting call graphs collection
selector is the selector of the view
Definition at line 83 of file call_graph.cpp.
CallGraph() [2/2]
CallGraph::CallGraph (const CallGraphsCollectionRef call_graphs_collection, const int selector, const CustomUnorderedSet< vertex > & vertices)
Constructor.
Parameters
call_graphs_collection is the starting call graphs collection
selector is the selector of the view
vertices is the set of vertices to be considered
Definition at line 87 of file call_graph.cpp.
References ~CallGraph().
 CallGraph()
CallGraph::~CallGraph () [override], [default]
Destructor.
Referenced by CallGraph().
Member Function Documentation
CGetCallGraphInfo()
const CallGraphInfoConstRef CallGraph::CGetCallGraphInfo () const [inline]
Return the info associated with the call graph.
Returns
the info associated with the call graph
Definition at line 189 of file call_graph.hpp.
References graph::CGetGraphInfo().
Referenced by CalledFunctionsVisitor::back_edge(), and CalledFunctionsVisitor::finish_vertex().
CGetFunctionEdgeInfo()
const FunctionEdgeInfoConstRef CallGraph::CGetFunctionEdgeInfo (const EdgeDescriptor edge) const [inline]
Return the info associated with an edge.
Parameters
edge is the edge to be considered
Definition at line 180 of file call_graph.hpp.
References graph::CGetEdgeInfo().
Referenced by CallSitesCollectorVisitor::examine_edge().
GetCallGraphInfo()
CallGraphInfoRef CallGraph::GetCallGraphInfo () [inline]
Return the info associated with the call graph.
Returns
the info associated with the call graph
Definition at line 198 of file call_graph.hpp.
References graph::GetGraphInfo().
WriteDot()
void CallGraph::WriteDot (const std::string & file_name) const
Write the call graph in dot format.
Parameters
file_name is the name of the file to create
Definition at line 93 of file call_graph.cpp.
References graph::collection, test_panda::full_name, and graphs_collection::parameters.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph.cpp