graph Struct Reference
General class used to describe a graph in PandA.
#include <graph.hpp>
Public Member Functions
virtual ~graph ()
Destructor.
bool is_in_subset (const boost::graph_traits< graph >::vertex_descriptor v) const
return true in case the vertex is a vertex of the subgraph.
int GetSelector () const
Return the selector of this graph.
int GetSelector (const edge_descriptor e) const
Return the selectors associated with an edge.
int GetSelector (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const
Return the selectors associated with an edge.
void GetStronglyConnectedComponents (std::map< size_t, UnorderedSetStdStable< boost::graph_traits< graphs_collection >::vertex_descriptor >> &strongly_connected_components) const
Compute the strongly connected components of the graph.
void BreadthFirstSearch (const boost::graph_traits< graphs_collection >::vertex_descriptor node, boost::bfs_visitor<> *vis) const
Compute the breadth first search.
void ReverseTopologicalSort (std::deque< boost::graph_traits< graphs_collection >::vertex_descriptor > &sorted_vertices) const
Compute the reverse topological order of the graph.
void TopologicalSort (std::list< boost::graph_traits< graphs_collection >::vertex_descriptor > &sorted_vertices) const
Compute the topological order of the graph.
bool IsReachable (const boost::graph_traits< graphs_collection >::vertex_descriptor x, const boost::graph_traits< graphs_collection >::vertex_descriptor y) const
Compute if vertex y is reachable from x.
NodeInfoRef GetNodeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor node)
FIXME: this method should become protected and called by equivalent method in subclasses Get the node property.
GraphInfoRef GetGraphInfo ()
FIXME: this method should become protected and called by equivalent method in subclasses Get the graph property.
const GraphInfoConstRef CGetGraphInfo () const
FIXME: this method should become protected and called by equivalent method in subclasses Get the graph property.
template<typename VertexWriterTemplate , typename EdgeWriterTemplate >
void InternalWriteDot (const std::string &file_name, const VertexWriterConstRef vertex_writer, const EdgeWriterConstRef edge_writer) const
Print the graph in dot format FIXME: this method should become protected and called by WriteDot.
bool ExistsEdge (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const
Check if an edge exists.
boost::graph_traits< graphs_collection >::edge_descriptor CGetEdge (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const
Returns the edge connecting two vertices; throw error if it does not exist.
 graph constructors
graph (graphs_collection *g, const int _selector)
Standard constructor.
graph (graphs_collection *g, const int _selector, const CustomUnorderedSet< boost::graph_traits< graphs_collection >::vertex_descriptor > &vertices)
Sub-graph constructor.
Protected Member Functions
const NodeInfoConstRef CGetNodeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor node) const
Get the node property.
EdgeInfoRef GetEdgeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor source, typename boost::graph_traits< graphs_collection >::vertex_descriptor target)
Get the edge property.
const EdgeInfoConstRef CGetEdgeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor source, typename boost::graph_traits< graphs_collection >::vertex_descriptor target) const
Get the edge property.
EdgeInfoRef GetEdgeInfo (typename boost::graph_traits< graphs_collection >::edge_descriptor edge) const
Get the edge property.
EdgeInfoConstRef CGetEdgeInfo (typename boost::graph_traits< graphs_collection >::edge_descriptor edge) const
Get the edge property.
template<typename VertexWriterTemplate , typename EdgeWriterTemplate , typename GraphWriterTemplate >
void InternalWriteDot (const std::string &file_name, const VertexWriterConstRef vertex_writer, const EdgeWriterConstRef edge_writer, const GraphWriterConstRef graph_writer) const
Print the graph in dot format.
Protected Attributes
graphs_collection * collection
The graph collection.
const int selector
selector
Friends
boost::graph_traits< graph >::vertex_descriptor VERTEX (const boost::graph_traits< graph >::vertices_size_type, const graph &)
this function can access the bulk graph
Detailed Description
General class used to describe a graph in PandA.
Definition at line 707 of file graph.hpp.
Constructor & Destructor Documentation
graph() [1/2]
graph::graph (graphs_collection * g, const int _selector) [inline]
Standard constructor.
Parameters
g is the bulk graph.
_selector is the selector used to filter the bulk graph.
Definition at line 804 of file graph.hpp.
graph() [2/2]
graph::graph (graphs_collection * g, const int _selector, const CustomUnorderedSet< boost::graph_traits< graphs_collection >::vertex_descriptor > & vertices) [inline]
Sub-graph constructor.
Parameters
g is the bulk graph.
_selector is the selector used to filter the bulk graph.
vertices is the set of vertexes on which the graph is filtered.
Definition at line 817 of file graph.hpp.
References VERTEX().
 graph()
virtual graph::~graph () [inline], [virtual]
Destructor.
Definition at line 829 of file graph.hpp.
Member Function Documentation
BreadthFirstSearch()
void graph::BreadthFirstSearch (const boost::graph_traits< graphs_collection >::vertex_descriptor node, boost::bfs_visitor<> * vis) const [inline]
Compute the breadth first search.
Definition at line 895 of file graph.hpp.
CGetEdge()
boost::graph_traits<graphs_collection>::edge_descriptor graph::CGetEdge (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const [inline]
Returns the edge connecting two vertices; throw error if it does not exist.
Parameters
source is the source of the edge to be returned
target is the target of the edge to be returned
Returns
the edge connecting source with target
Definition at line 1016 of file graph.hpp.
References THROW_ASSERT, and test_panda::type.
CGetEdgeInfo() [1/2]
const EdgeInfoConstRef graph::CGetEdgeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor source, typename boost::graph_traits< graphs_collection >::vertex_descriptor target) const [inline], [protected]
Get the edge property.
Parameters
source is the source vertex of the edge
target is the target vertex of the edge
Returns
the associated property
Definition at line 743 of file graph.hpp.
References THROW_ASSERT.
Referenced by BBGraph::CGetBBEdgeInfo(), CdfcGraph::CGetCdfcEdgeInfo(), CallGraph::CGetFunctionEdgeInfo(), OpGraph::CGetOpEdgeInfo(), and StateTransitionGraph::CGetTransitionInfo().
CGetEdgeInfo() [2/2]
EdgeInfoConstRef graph::CGetEdgeInfo (typename boost::graph_traits< graphs_collection >::edge_descriptor edge) const [inline], [protected]
Get the edge property.
Parameters
edge is the edge whose property is asked
Returns
the associated property
Definition at line 769 of file graph.hpp.
References THROW_ASSERT.
CGetGraphInfo()
const GraphInfoConstRef graph::CGetGraphInfo () const [inline]
FIXME: this method should become protected and called by equivalent method in subclasses Get the graph property.
Returns
the property associated with the graph
Definition at line 976 of file graph.hpp.
References boost_CGetOpGraph_property.
Referenced by BBGraph::CGetBBGraphInfo(), CallGraph::CGetCallGraphInfo(), DesignFlowGraph::CGetDesignFlowGraphInfo(), StateTransitionGraph::CGetStateTransitionGraphInfo(), and CdfcGraph::WriteDot().
CGetNodeInfo()
const NodeInfoConstRef graph::CGetNodeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor node) const [inline], [protected]
Get the node property.
Parameters
node is the node whose property is asked
Returns
the associated property
Definition at line 715 of file graph.hpp.
References THROW_ASSERT.
Referenced by BBGraph::CGetBBNodeInfo(), DesignFlowGraph::CGetDesignFlowStepInfo(), OpGraph::CGetOpNodeInfo(), and StateTransitionGraph::CGetStateInfo().
ExistsEdge()
bool graph::ExistsEdge (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const [inline]
Check if an edge exists.
Parameters
source is the source vertex
target is the target vertex
Returns
true if source-target exists
Definition at line 1002 of file graph.hpp.
Referenced by SDCScheduling::AddDelayConstraints(), and SDCScheduling::InternalExec().
GetEdgeInfo() [1/2]
EdgeInfoRef graph::GetEdgeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor source, typename boost::graph_traits< graphs_collection >::vertex_descriptor target) [inline], [protected]
Get the edge property.
Parameters
source is the source vertex of the edge
target is the target vertex of the edge
Returns
the associated property
Definition at line 728 of file graph.hpp.
References THROW_ASSERT.
Referenced by BBGraph::GetBBEdgeInfo(), and StateTransitionGraph::GetTransitionInfo().
GetEdgeInfo() [2/2]
EdgeInfoRef graph::GetEdgeInfo (typename boost::graph_traits< graphs_collection >::edge_descriptor edge) const [inline], [protected]
Get the edge property.
Parameters
edge is the edge whose property is asked
Returns
the associated property
Definition at line 757 of file graph.hpp.
References THROW_ASSERT.
GetGraphInfo()
GraphInfoRef graph::GetGraphInfo () [inline]
FIXME: this method should become protected and called by equivalent method in subclasses Get the graph property.
Returns
the property associated with the graph
Definition at line 965 of file graph.hpp.
References boost_CGetOpGraph_property.
Referenced by structural_manager::build_graph(), structural_manager::get_PI(), BBGraph::GetBBGraphInfo(), CallGraph::GetCallGraphInfo(), DesignFlowGraph::GetDesignFlowGraphInfo(), and StateTransitionGraph::GetStateTransitionGraphInfo().
GetNodeInfo()
NodeInfoRef graph::GetNodeInfo (typename boost::graph_traits< graphs_collection >::vertex_descriptor node) [inline]
FIXME: this method should become protected and called by equivalent method in subclasses Get the node property.
Parameters
node is the vertex whose property is asked
Returns
the associated property
Definition at line 953 of file graph.hpp.
References THROW_ASSERT.
Referenced by BBGraph::GetBBNodeInfo(), DesignFlowGraph::GetDesignFlowStepInfo(), OpGraph::GetOpNodeInfo(), and StateTransitionGraph::GetStateInfo().
GetSelector() [1/3]
int graph::GetSelector () const [inline]
Return the selector of this graph.
Returns
the selector of the graph
Definition at line 845 of file graph.hpp.
Referenced by SDCScheduling::AddDelayConstraints(), OpGraph::GetSrcVertices(), BB_based_stg::InternalExec(), LoopsAnalysisBambu::InternalExec(), AddBbEcfgEdges::InternalExec(), BuildVirtualPhi::InternalExec(), MultipleEntryIfReduction::InternalExec(), SDCScheduling::InternalExec(), cdfc_module_binding::InternalExec(), OpEdgeWriter::operator()(), BBEdgeWriter::operator()(), cg_edge_writer::operator()(), FunctionEdgeWriter::operator()(), DesignFlowEdgeWriter::operator()(), TransitionWriter::operator()(), cdfc_module_binding::update_slack_starting_time(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
GetSelector() [2/3]
int graph::GetSelector (const edge_descriptor e) const [inline]
Return the selectors associated with an edge.
Parameters
e is the edge
Returns
the associated selector
Definition at line 855 of file graph.hpp.
References graphs_collection::GetSelector().
GetSelector() [3/3]
int graph::GetSelector (const boost::graph_traits< graphs_collection >::vertex_descriptor source, const boost::graph_traits< graphs_collection >::vertex_descriptor target) const [inline]
Return the selectors associated with an edge.
Parameters
source is the source of an edge
target is the target of an edge
Returns
the associated selector
Definition at line 866 of file graph.hpp.
References graphs_collection::GetSelector().
GetStronglyConnectedComponents()
void graph::GetStronglyConnectedComponents (std::map< size_t, UnorderedSetStdStable< boost::graph_traits< graphs_collection >::vertex_descriptor >> & strongly_connected_components) const [inline]
Compute the strongly connected components of the graph.
Parameters
strongly_connected_components is where the set of vertices which compose the different strongly connected components will be stored; key is the index of the strongly connected component
Definition at line 879 of file graph.hpp.
InternalWriteDot() [1/2]
template<typename VertexWriterTemplate , typename EdgeWriterTemplate , typename GraphWriterTemplate >
void graph::InternalWriteDot (const std::string & file_name, const VertexWriterConstRef vertex_writer, const EdgeWriterConstRef edge_writer, const GraphWriterConstRef graph_writer) const [inline], [protected]
Print the graph in dot format.
Parameters
file_name is the name of the file to be created
node_writer is the functor used to print the node labels
edge_writer is the functor used to print the edge labels
graph_writer is the functor used to print the graph properties
Definition at line 790 of file graph.hpp.
Referenced by Schedule::WriteDot().
InternalWriteDot() [2/2]
template<typename VertexWriterTemplate , typename EdgeWriterTemplate >
void graph::InternalWriteDot (const std::string & file_name, const VertexWriterConstRef vertex_writer, const EdgeWriterConstRef edge_writer) const [inline]
Print the graph in dot format FIXME: this method should become protected and called by WriteDot.
Parameters
file_name is the name of the file to be created
node_writer is the functor used to print the node labels
edge_writer is the functor used to print the edge labels
Definition at line 990 of file graph.hpp.
is_in_subset()
bool graph::is_in_subset (const boost::graph_traits< graph >::vertex_descriptor v) const [inline]
return true in case the vertex is a vertex of the subgraph.
Definition at line 836 of file graph.hpp.
Referenced by ASLAP::add_constraints_to_ALAP(), ASLAP::add_constraints_to_ASAP(), ASLAP::compute_ALAP_fast(), ASLAP::compute_ALAP_worst_case(), ASLAP::compute_ASAP(), and ASLAP::update_ALAP().
IsReachable()
bool graph::IsReachable (const boost::graph_traits< graphs_collection >::vertex_descriptor x, const boost::graph_traits< graphs_collection >::vertex_descriptor y) const [inline]
Compute if vertex y is reachable from x.
Definition at line 921 of file graph.hpp.
Referenced by liveness::are_in_conflict(), and rebuild_initialization2::look_for_ROMs().
ReverseTopologicalSort()
void graph::ReverseTopologicalSort (std::deque< boost::graph_traits< graphs_collection >::vertex_descriptor > & sorted_vertices) const [inline]
Compute the reverse topological order of the graph.
Parameters
sorted_vertices is where results will be store
Definition at line 904 of file graph.hpp.
Referenced by SDCScheduling::Initialize().
TopologicalSort()
void graph::TopologicalSort (std::list< boost::graph_traits< graphs_collection >::vertex_descriptor > & sorted_vertices) const [inline]
Compute the topological order of the graph.
Parameters
sorted_vertices is where results will be store
Definition at line 913 of file graph.hpp.
Referenced by CallGraphManager::AddCallPoint(), SDCScheduling::AddDelayConstraints(), AddBbEcfgEdges::InternalExec(), bb_feedback_edges_computation::InternalExec(), and cdfc_module_binding::InternalExec().
Friends And Related Function Documentation
VERTEX
boost::graph_traits<graph>::vertex_descriptor VERTEX (const boost::graph_traits< graph >::vertices_size_type i, const graph & g) [friend]
this function can access the bulk graph
Parameters
i is the index of the vertex.
g is the graph for which the vertex is asked.
Returns
the vertex with the index i of the graph g.
Definition at line 1261 of file graph.hpp.
Field Documentation
collection
graphs_collection* graph::collection [protected]
The graph collection.
Definition at line 777 of file graph.hpp.
Referenced by OpGraph::CGetOperations(), OpGraph::CGetOutEdges(), DesignFlowGraph::GetDesignFlowStep(), CallGraph::WriteDot(), DesignFlowGraph::WriteDot(), CdfcGraph::WriteDot(), BBGraph::WriteDot(), StateTransitionGraph::WriteDot(), and OpGraph::WriteDot().
selector
const int graph::selector [protected]
selector
Definition at line 780 of file graph.hpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/graph/graph.hpp