multi_way_if Class Reference
STL include.
#include <multi_way_if.hpp>
Public Member Functions
multi_way_if (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~multi_way_if () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
void MergeCondCond (unsigned int pred, unsigned int curr_bb)
Merge two basic blocks both ending with gimple_cond_K.
void MergeCondMulti (const unsigned int pred_bb, const unsigned int curr_bb)
Build the gimple_multi_way_if by mergin a gimple_cond with a gimple_multi_way_if.
void MergeMultiCond (const unsigned int pred_bb, const unsigned int curr_bb)
Merge a gimple_cond in a gimple_multi_way_if.
void MergeMultiMulti (const unsigned int pred_bb, const unsigned int curr_bb)
Merge two gimple_multi_way_if in a single one.
void UpdateCfg (unsigned int pred_bb, unsigned int curr_bb)
Update the basic block control flow graph data structure.
void FixCfg (const unsigned int pred_bb, const unsigned int succ_bb)
Insert a basic block on an edge.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
statement_list * sl
The statement list of the analyzed function.
tree_managerRef TM
The tree manager.
tree_manipulationRef tree_man
The tree manipulation.
bool bb_modified
Modified file.
Additional Inherited Members
Detailed Description
STL include.
Structure the original short circuit
Definition at line 72 of file multi_way_if.hpp.
Constructor & Destructor Documentation
multi_way_if()
multi_way_if::multi_way_if (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
. include src/algorithms/graph_helpers include behavior includes design_flows includes hls includes parser/treegcc include STD include STL include tree includes
Definition at line 98 of file multi_way_if.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~multi_way_if().
 multi_way_if()
multi_way_if::~multi_way_if () [override], [default]
Destructor.
Referenced by multi_way_if().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > multi_way_if::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 106 of file multi_way_if.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SWITCH_FIX, THROW_UNREACHABLE, and USE_COUNTING.
FixCfg()
void multi_way_if::FixCfg (const unsigned int pred_bb, const unsigned int succ_bb) [private]
Insert a basic block on an edge.
Parameters
pred_bb is the index of the first basic block
succ_bb is the index of the second basic block
The index of the basic block to be created
Create the new basic block and set all the fields
Fix the predecessor
Fix the last statement of the predecessor
Fix the successor
Fix the phi
Definition at line 668 of file multi_way_if.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, STR, THROW_ASSERT, and TM.
Referenced by InternalExec().
HasToBeExecuted()
bool multi_way_if::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Multi way if can be executed only after vectorization
Reimplemented from FunctionFrontendFlowStep.
Definition at line 729 of file multi_way_if.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), Wrefcount< T >::lock(), NULL_VERTEX, and DesignFlowStep::parameters.
Initialize()
void multi_way_if::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 144 of file multi_way_if.cpp.
References FrontendFlowStep::AppM, bb_modified, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), DesignFlowStep::parameters, sl, TM, and tree_man.
InternalExec()
DesignFlowStep_Status multi_way_if::InternalExec () [override], [virtual]
Restructures the unstructured code.
add edges
add a connection between entry and exit thus avoiding problems with non terminating code
sort basic block vertices from the entry till the exit
check for short circuit conditions: i.e., if they have at least a successor in common if so we add a basic block on the shortest path (e.g., predecessor --> common successor) In this way in the produced gimple_multi_way_if there cannot be multiple conditions with the same next bb phi_opt will remove the extra basic block
Fixed point since list of successor is changed by FixCfg
now the merging starts
Implements FunctionFrontendFlowStep.
Definition at line 205 of file multi_way_if.cpp.
References FrontendFlowStep::AppM, bb_modified, CFG_SELECTOR, cyclic_topological_sort(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, FixCfg(), FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, BBGraph::GetBBNodeInfo(), FunctionFrontendFlowStep::GetName(), INDENT_DBG_MEX, statement_list::list_of_bloc, MergeCondCond(), MergeCondMulti(), MergeMultiCond(), MergeMultiMulti(), DesignFlowStep::parameters, test_panda::restart, sl, STR, SUCCESS, UNCHANGED, UpdateCfg(), and FunctionFrontendFlowStep::WriteBBGraphDot().
MergeCondCond()
void multi_way_if::MergeCondCond (unsigned int pred, unsigned int curr_bb) [private]
Merge two basic blocks both ending with gimple_cond_K.
Parameters
pred is the first basic block
curr_bb is the second basic block
identify the first gimple_cond
identify the second gimple_cond
create the gimple_multi_way_if node
Definition at line 613 of file multi_way_if.cpp.
References tree_manager::create_tree_node(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateNotExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manipulation::ExtractCondition(), GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, statement_list::list_of_bloc, tree_manager::new_tree_node_id(), sl, THROW_ASSERT, TM, TOK, TOK_SRCP, and tree_man.
Referenced by InternalExec().
MergeCondMulti()
void multi_way_if::MergeCondMulti (const unsigned int pred_bb, const unsigned int curr_bb) [private]
Build the gimple_multi_way_if by mergin a gimple_cond with a gimple_multi_way_if.
Parameters
pred_bb is the basic block containing the gimple_cond
second_bb is the basic block containg the gimple_multi_way_if
create the gimple_multi_way_if node
Create ce_condition
Remove old gimple_cond
Remove old gimple multi way if
First case: second bb is on the true edge
Skipped default condition
Second case: second bb is on the false edge
Definition at line 373 of file multi_way_if.cpp.
References tree_manager::create_tree_node(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateNotExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manipulation::ExtractCondition(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, statement_list::list_of_bloc, tree_manager::new_tree_node_id(), sl, TM, TOK, TOK_SRCP, and tree_man.
Referenced by InternalExec().
MergeMultiCond()
void multi_way_if::MergeMultiCond (const unsigned int pred_bb, const unsigned int curr_bb) [private]
Merge a gimple_cond in a gimple_multi_way_if.
Parameters
pred_bb is the basic block containing the gimple_multi_way_if
curr_bb is the basic block containing the gimple_cond
create the gimple_multi_way_if node
Remove old gimple_multi_way_if
Remove old gimple_cond
Create condition
Non default and succ is on this edge
Non default and succ is not on this edge
Default and succ is is on this edge
Building the and of the not of other conditions of cond
Default and second is not on this edge
Definition at line 541 of file multi_way_if.cpp.
References tree_manager::create_tree_node(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateNotExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manipulation::ExtractCondition(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, statement_list::list_of_bloc, tree_manager::new_tree_node_id(), sl, TM, TOK, TOK_SRCP, and tree_man.
Referenced by InternalExec().
MergeMultiMulti()
void multi_way_if::MergeMultiMulti (const unsigned int pred_bb, const unsigned int curr_bb) [private]
Merge two gimple_multi_way_if in a single one.
Parameters
pred_bb is the basic block containing the first gimple_multi_way_if
curr_bb is the basic block containing the second gimple multi_way_if
create the gimple_multi_way_if node
Remove old gimple_cond
Remove old gimple multi way if
Non default and succ is on this edge
Non default and succ is not on this edge
Default and succ is on this edge
Building the and of the not of other conditions of cond1
Default and second is not on this edge
Definition at line 432 of file multi_way_if.cpp.
References tree_manager::create_tree_node(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateNotExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, statement_list::list_of_bloc, tree_manager::new_tree_node_id(), sl, TM, TOK, TOK_SRCP, and tree_man.
Referenced by InternalExec().
UpdateCfg()
void multi_way_if::UpdateCfg (unsigned int pred_bb, unsigned int curr_bb) [private]
Update the basic block control flow graph data structure.
Parameters
pred_bb is the predecessor basic block
curr_bb is the current basic block
Remove curr_bb from successor of pred_bb
For each successor succ of curr_bb
Remove curr_bb from its predecessor
Add pred_bb to its predecessor
Add succ to successor of pred_bb
Update phi information
Definition at line 164 of file multi_way_if.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, sl, and TM.
Referenced by InternalExec().
Field Documentation
bb_modified
bool multi_way_if::bb_modified [private]
Modified file.
Definition at line 85 of file multi_way_if.hpp.
Referenced by Initialize(), and InternalExec().
sl
statement_list* multi_way_if::sl [private]
The statement list of the analyzed function.
Definition at line 76 of file multi_way_if.hpp.
Referenced by FixCfg(), Initialize(), InternalExec(), MergeCondCond(), MergeCondMulti(), MergeMultiCond(), MergeMultiMulti(), and UpdateCfg().
TM
tree_managerRef multi_way_if::TM [private]
The tree manager.
Definition at line 79 of file multi_way_if.hpp.
Referenced by FixCfg(), Initialize(), MergeCondCond(), MergeCondMulti(), MergeMultiCond(), MergeMultiMulti(), and UpdateCfg().
tree_man
tree_manipulationRef multi_way_if::tree_man [private]
The tree manipulation.
Definition at line 82 of file multi_way_if.hpp.
Referenced by Initialize(), MergeCondCond(), MergeCondMulti(), MergeMultiCond(), and MergeMultiMulti().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/multi_way_if.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/multi_way_if.cpp