TypedNodeInfo Struct Reference
#include <typed_node_info.hpp>
Public Member Functions
TypedNodeInfo ()
Constructor.
~TypedNodeInfo () override
Destructor.
void print (std::ostream &, int detail_level=0) const override
Print the information associated with the node of the graph.
Data Fields
std::string node_operation
Custom vertex property: node_operation.
std::string vertex_name
Definition of the node name property.
unsigned int node_type
Custom vertex property: node_type.
Friends
std::ostream & operator<< (std::ostream &os, const TypedNodeInfo &s)
Friend definition of the << operator.
Detailed Description
Definition at line 114 of file typed_node_info.hpp.
Constructor & Destructor Documentation
TypedNodeInfo()
TypedNodeInfo::TypedNodeInfo ()
Constructor.
Header include.
Definition at line 48 of file typed_node_info.cpp.
References ~TypedNodeInfo().
 TypedNodeInfo()
TypedNodeInfo::~TypedNodeInfo () [override], [default]
Destructor.
Referenced by TypedNodeInfo().
Member Function Documentation
print()
void TypedNodeInfo::print (std::ostream & os, int detail_level = 0) const [override], [virtual]
Print the information associated with the node of the graph.
Parameters
os is the output stream.
Reimplemented from NodeInfo.
Definition at line 54 of file typed_node_info.cpp.
References node_operation, node_type, and vertex_name.
Referenced by cg_node_info::print().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const TypedNodeInfo & s) [friend]
Friend definition of the << operator.
Parameters
os is the output stream.
s is the node to print.
Definition at line 154 of file typed_node_info.hpp.
Field Documentation
node_operation
std::string TypedNodeInfo::node_operation
Custom vertex property: node_operation.
This property defines which operation is performed: assignment, addition, comparison, etc.
Definition at line 120 of file typed_node_info.hpp.
Referenced by print().
node_type
unsigned int TypedNodeInfo::node_type
Custom vertex property: node_type.
This property defines which type of node is: read and write a port, read a constant, if, case, wait and notify or generic operation.
Definition at line 131 of file typed_node_info.hpp.
Referenced by print().
vertex_name
std::string TypedNodeInfo::vertex_name
Definition of the node name property.
Definition at line 125 of file typed_node_info.hpp.
Referenced by OpNodeInfo::GetNodeId(), OpNodeInfo::GetVariables(), and print().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/graph/typed_node_info.hpp
/home/osboxes/bambu/PandA-bambu/src/graph/typed_node_info.cpp