create_tree_manager Class Reference
Class that creates the tree_manager starting from the source code files.
#include <create_tree_manager.hpp>
Public Member Functions
create_tree_manager (const ParameterConstRef Param, const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~create_tree_manager () override
Destructor.
DesignFlowStep_Status Exec () override
Creates the tree_manager data structure by invoking the GCC wrapper.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Attributes
const GccWrapperRef gcc_wrapper
The gcc wrapper.
Additional Inherited Members
Detailed Description
Class that creates the tree_manager starting from the source code files.
Definition at line 57 of file create_tree_manager.hpp.
Constructor & Destructor Documentation
create_tree_manager()
create_tree_manager::create_tree_manager (const ParameterConstRef _parameters, const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
Param is the set of the parameters
AppM is the reference to the application manager
design_flow_manager is the design flow manager
Header include behavior include design_flow includes Intermediate Representation at raw level Wrapper include Utility include
Definition at line 76 of file create_tree_manager.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~create_tree_manager().
 create_tree_manager()
create_tree_manager::~create_tree_manager () [override], [default]
Destructor.
Referenced by create_tree_manager().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > create_tree_manager::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 116 of file create_tree_manager.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
ComputeRelationships()
void create_tree_manager::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [private], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FrontendFlowStep.
Definition at line 85 of file create_tree_manager.cpp.
References FrontendFlowStep::AppM, FrontendFlowStep::ComputeRelationships(), ParserFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, Wrefcount< T >::lock(), NULL_VERTEX, and DesignFlowStep::parameters.
Exec()
DesignFlowStep_Status create_tree_manager::Exec () [override], [virtual]
Creates the tree_manager data structure by invoking the GCC wrapper.
Returns
the exit status of this step
parsing of archive files
Implements ApplicationFrontendFlowStep.
Definition at line 144 of file create_tree_manager.cpp.
References FrontendFlowStep::AppM, test_panda::command, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, gcc_wrapper, GetExtension(), INDENT_DBG_MEX, INDENT_OUT_MEX, IsError(), tree_manager::merge_tree_managers(), DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERBOSE, PandaSystem(), DesignFlowStep::parameters, ParseTreeFile(), SUCCESS, and THROW_ERROR.
HasToBeExecuted()
bool create_tree_manager::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from ApplicationFrontendFlowStep.
Definition at line 255 of file create_tree_manager.cpp.
Field Documentation
gcc_wrapper
const GccWrapperRef create_tree_manager::gcc_wrapper [private]
The gcc wrapper.
Definition at line 61 of file create_tree_manager.hpp.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/create_tree_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/create_tree_manager.cpp