/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Introduction/fifth/module_lib.h File Reference
#include <stdint.h>
Data Structures
struct module1_output_t
struct module2_output_t
Functions
void module1 (uint32_t input1, uint16_t input2, module1_output_t *outputs)
void module2 (uint32_t input1, module2_output_t *outputs)
void printer1 (uint64_t value1, uint64_t value2, uint16_t value3, uint32_t value4)
void printer2 (uint64_t value1, uint64_t value2, uint16_t value3)
void my_ip (uint8_t command, uint32_t param1, uint32_t param2)
Function Documentation
module1()
void module1 (uint32_t input1, uint16_t input2, module1_output_t * outputs)
Definition at line 2 of file module1.c.
References module1_output_t::output1, module1_output_t::output2, module1_output_t::output3, and module1_output_t::output4.
Referenced by my_ip().
module2()
void module2 (uint32_t input1, module2_output_t * outputs)
Definition at line 2 of file module2.c.
References module2_output_t::output1, module2_output_t::output2, and module2_output_t::output3.
Referenced by my_ip().
my_ip()
void my_ip (uint8_t command, uint32_t param1, uint32_t param2)
Definition at line 3 of file top.c.
References module1(), module2(), module1_output_t::output1, module2_output_t::output1, module1_output_t::output2, module2_output_t::output2, module1_output_t::output3, module2_output_t::output3, module1_output_t::output4, printer1(), and printer2().
printer1()
void printer1 (uint64_t value1, uint64_t value2, uint16_t value3, uint32_t value4)
Definition at line 3 of file printer1.c.
printer2()
void printer2 (uint64_t value1, uint64_t value2, uint16_t value3)
Definition at line 3 of file printer2.c.