determine_memory_accesses Class Reference
#include <determine_memory_accesses.hpp>
Public Member Functions
determine_memory_accesses (const ParameterConstRef parameters, const application_managerRef AppM, unsigned int function_idi, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~determine_memory_accesses () override
Destructor.
DesignFlowStep_Status InternalExec () override
Determines the variables that require a memory access.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
void analyze_node (unsigned int node_id, bool left_p, bool dynamic_address, bool no_dynamic_address)
Analyze the given node ID to determine which variables have to be referred in memory.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const BehavioralHelperConstRef behavioral_helper
The behavioral helper.
const tree_managerConstRef TM
The tree manager.
CustomUnorderedSet< unsigned int > already_visited_ae
Already visited address expression (used to avoid infinite recursion)
bool already_executed
True if already executed.
Additional Inherited Members
Detailed Description
Definition at line 61 of file determine_memory_accesses.hpp.
Constructor & Destructor Documentation
determine_memory_accesses()
determine_memory_accesses::determine_memory_accesses (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
parameters is the set of input parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
Behavior include Parameter include Tree include
Definition at line 71 of file determine_memory_accesses.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~determine_memory_accesses().
 determine_memory_accesses()
determine_memory_accesses::~determine_memory_accesses () [override], [default]
Destructor.
Referenced by determine_memory_accesses().
Member Function Documentation
analyze_node()
void determine_memory_accesses::analyze_node (unsigned int node_id, bool left_p, bool dynamic_address, bool no_dynamic_address) [private]
Analyze the given node ID to determine which variables have to be referred in memory.
check for implicit memcpy calls
manage temporary addresses
manage temporary addresses
an address of a parm decl may be used in writing so it has to be copied
check if the actual parameter has been allocated in memory
if the formal parameter has not been allocated in memory then it has to be initialized
check if the formal parameter has been allocated in memory.
If the actual has not been allocated in memory then the formal parameter storage has to be initialized with the actual value with a MEMSTORE_STD
check if the actual parameter has been allocated in memory
if the formal parameter has not been allocated in memory then it has to be initialized
check if the formal parameter has been allocated in memory.
If the actual has not been allocated in memory then the formal parameter storage has to be initialized with the actual value with a MEMSTORE_STD
skip the &
check for unaligned accesses
Definition at line 162 of file determine_memory_accesses.cpp.
References already_visited_ae, FrontendFlowStep::AppM, test_panda::arg, test_panda::args, behavioral_helper, BUILTIN_WAIT_CALL, C_EC, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, el, FunctionFrontendFlowStep::function_behavior, tree_helper::get_base_index(), GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_node(), INDENT_DBG_MEX, INDENT_OUT_MEX, tree_node::index, tree_helper::is_a_pointer(), tree_helper::is_a_vector(), tree_helper::is_volatile(), NODE_NOT_YET_SUPPORTED_EC, DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, PRINT_DBG_MEX, tree_helper::print_function_name(), STR, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, TM, and tree_node::ToString().
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > determine_memory_accesses::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 79 of file determine_memory_accesses.cpp.
References FrontendFlowStep::CALLED_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, PARM2SSA, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, VAR_DECL_FIX, and FrontendFlowStep::WHOLE_APPLICATION.
HasToBeExecuted()
bool determine_memory_accesses::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 1290 of file determine_memory_accesses.cpp.
References already_executed.
InternalExec()
DesignFlowStep_Status determine_memory_accesses::InternalExec () [override], [virtual]
Determines the variables that require a memory access.
analyze formal parameters
Implements FunctionFrontendFlowStep.
Definition at line 124 of file determine_memory_accesses.cpp.
References already_executed, analyze_node(), FrontendFlowStep::AppM, BB_ENTRY, BB_EXIT, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), DesignFlowStep::parameters, phi, PRINT_DBG_MEX, sl, SUCCESS, THROW_ASSERT, TM, and UNCHANGED.
Field Documentation
already_executed
bool determine_memory_accesses::already_executed [private]
True if already executed.
Definition at line 74 of file determine_memory_accesses.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
already_visited_ae
CustomUnorderedSet<unsigned int> determine_memory_accesses::already_visited_ae [private]
Already visited address expression (used to avoid infinite recursion)
Definition at line 71 of file determine_memory_accesses.hpp.
Referenced by analyze_node().
behavioral_helper
const BehavioralHelperConstRef determine_memory_accesses::behavioral_helper [private]
The behavioral helper.
Definition at line 65 of file determine_memory_accesses.hpp.
Referenced by analyze_node().
TM
const tree_managerConstRef determine_memory_accesses::TM [private]
The tree manager.
Definition at line 68 of file determine_memory_accesses.hpp.
Referenced by analyze_node(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/determine_memory_accesses.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/determine_memory_accesses.cpp