ISE_isim_wrapper Class Reference
Main class for wrapping ISE ISIM Xilinx.
#include <ISE_isim_wrapper.hpp>
Public Member Functions
ISE_isim_wrapper (const ParameterConstRef &Param, std::string suffix)
Constructor.
~ISE_isim_wrapper () override
Destructor.
void CheckExecution () override
Checks if the current specification can be executed or not.
Private Member Functions
std::string create_project_script (const std::string &top_filename, const std::list< std::string > &file_list)
Creates the project file for ISIM.
void GenerateScript (std::ostringstream &script, const std::string &top_filename, const std::list< std::string > &file_list) override
Generates the proper simulation script.
Private Attributes
std::string suffix
suffix added to the ISIM dir
Additional Inherited Members
Detailed Description
Main class for wrapping ISE ISIM Xilinx.
Definition at line 68 of file ISE_isim_wrapper.hpp.
Constructor & Destructor Documentation
ISE_isim_wrapper()
ISE_isim_wrapper::ISE_isim_wrapper (const ParameterConstRef & _Param, std::string _suffix)
Constructor.
Autoheader include.
Parameters
Param is the set of parameters
Includes the class definition
Definition at line 72 of file ISE_isim_wrapper.cpp.
References SimulationTool::debug_level, DEBUG_LEVEL_PEDANTIC, ISIM_SUBDIR, PRINT_DBG_MEX, suffix, and ~ISE_isim_wrapper().
 ISE_isim_wrapper()
ISE_isim_wrapper::~ISE_isim_wrapper () [override], [default]
Destructor.
Referenced by ISE_isim_wrapper().
Member Function Documentation
CheckExecution()
void ISE_isim_wrapper::CheckExecution () [override], [virtual]
Checks if the current specification can be executed or not.
Reimplemented from SimulationTool.
Definition at line 81 of file ISE_isim_wrapper.cpp.
References THROW_ERROR.
create_project_script()
std::string ISE_isim_wrapper::create_project_script (const std::string & top_filename, const std::list< std::string > & file_list) [private]
Creates the project file for ISIM.
Definition at line 88 of file ISE_isim_wrapper.cpp.
References flopoco::filename, GetExtension(), ISIM_SUBDIR, suffix, and THROW_ERROR.
Referenced by GenerateScript().
GenerateScript()
void ISE_isim_wrapper::GenerateScript (std::ostringstream & script, const std::string & top_filename, const std::list< std::string > & file_list) [override], [private], [virtual]
Generates the proper simulation script.
prepare tclbatch script
Implements SimulationTool.
Definition at line 128 of file ISE_isim_wrapper.cpp.
References create_project_script(), SimulationTool::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INTSTYLE_ISE, INTSTYLE_SILENT, ISIM_SUBDIR, SimulationTool::log_file, SimulationTool::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, SimulationTool::Param, PRINT_OUT_MEX, STR, and suffix.
Field Documentation
suffix
std::string ISE_isim_wrapper::suffix [private]
suffix added to the ISIM dir
Definition at line 72 of file ISE_isim_wrapper.hpp.
Referenced by create_project_script(), GenerateScript(), and ISE_isim_wrapper().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/isim/ISE_isim_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/isim/ISE_isim_wrapper.cpp