OmpAllocation Class Reference
Superclass include.
#include <omp_allocation.hpp>
Public Member Functions
OmpAllocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~OmpAllocation ()
Destructor.
Protected Member Functions
virtual void IntegrateTechnologyLibraries ()
Integrate technology libraries with special functional units.
void AddPandaPthreadMutex ()
Add the module implementing panda_pthread_mutex.
Additional Inherited Members
Detailed Description
Superclass include.
This wrapper collects all the methods used by the High-level synthesis classes to retrieve information about the functional units.
Definition at line 50 of file omp_allocation.hpp.
Constructor & Destructor Documentation
OmpAllocation()
OmpAllocation::OmpAllocation (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
. include behavior includes circuit include HLS includes technology include technology/physical_library include technology/physical_library/models includes tree includes utility include
Definition at line 75 of file omp_allocation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 OmpAllocation()
OmpAllocation::~OmpAllocation ()
Destructor.
Definition at line 81 of file omp_allocation.cpp.
Member Function Documentation
AddPandaPthreadMutex()
void OmpAllocation::AddPandaPthreadMutex () [protected]
Add the module implementing panda_pthread_mutex.
add description and license
Definition at line 105 of file omp_allocation.cpp.
References structural_manager::add_NP_functionality(), technology_manager::add_operation(), structural_manager::add_port(), area_model::create_model(), time_model::create_model(), DONE_PORT_NAME, FPGA, structural_manager::get_circ(), technology_manager::get_fu(), HLS_step::HLSMgr, port_o::IN, NP_functionality::LIBRARY, OPENMP_LIBRARY, port_o::OUT, DesignFlowStep::parameters, structural_manager::set_top_info(), START_PORT_NAME, STR, THROW_ASSERT, allocation::TM, top(), and NP_functionality::VERILOG_PROVIDED.
Referenced by IntegrateTechnologyLibraries().
IntegrateTechnologyLibraries()
void OmpAllocation::IntegrateTechnologyLibraries () [protected], [virtual]
Integrate technology libraries with special functional units.
Reimplemented from allocation.
Definition at line 85 of file omp_allocation.cpp.
References AddPandaPthreadMutex(), FunctionBehavior::CFG, FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), HLSFunctionStep::funId, technology_manager::get_fu(), HLS_step::HLSMgr, allocation::IntegrateTechnologyLibraries(), tree_helper::normalized_ID(), OPENMP_LIBRARY, and allocation::TM.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/omp_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/omp_allocation.cpp