resource_ordering_functor Struct Reference
Functor used to compare which of two resources has to be considered first in the scheduling.
Public Member Functions
bool operator() (const unsigned int &a, const unsigned int &b) const
functor function used to compare two resources with respect to their performances
resource_ordering_functor (const AllocationInformationConstRef _all)
Constructor.
~resource_ordering_functor ()=default
Destructor.
Private Attributes
const AllocationInformationConstRef all
copy of the order: control step associated with the vertices.
Detailed Description
Functor used to compare which of two resources has to be considered first in the scheduling.
Definition at line 146 of file parametric_list_based.cpp.
Constructor & Destructor Documentation
resource_ordering_functor()
resource_ordering_functor::resource_ordering_functor (const AllocationInformationConstRef _all) [inline], [explicit]
Constructor.
Parameters
o is the order.
Definition at line 183 of file parametric_list_based.cpp.
 resource_ordering_functor()
resource_ordering_functor::~resource_ordering_functor () [default]
Destructor.
Member Function Documentation
operator()()
bool resource_ordering_functor::operator() (const unsigned int & a, const unsigned int & b) const [inline]
functor function used to compare two resources with respect to their performances
Parameters
a is the first vertex
bis the second vertex
Returns
true when a is faster than b
Definition at line 159 of file parametric_list_based.cpp.
References AllocationInformation::get_area(), AllocationInformation::get_DSPs(), AllocationInformation::get_fu_name(), AllocationInformation::get_worst_execution_time(), AllocationInformation::is_indirect_access_memory_unit(), PROXY_PREFIX, and STR.
Field Documentation
all
const AllocationInformationConstRef resource_ordering_functor::all [private]
copy of the order: control step associated with the vertices.
Definition at line 150 of file parametric_list_based.cpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/parametric_list_based.cpp