/home/osboxes/bambu/PandA-bambu/src/circuit/structuralIO.hpp File Reference
Input and output functions used to read and write the structural data structures.
#include `refcount.hpp`
#include <string>
Functions
structural_managerRef read_structural_File (const std::string &f, const ParameterRef &Param)
Read an xml file describing the structural data structures.
void write_structural_File (const std::string &f, structural_managerRef const &CM)
Write an xml file describing the structural data structures.
 forward declarations
REF_FORWARD_DECL (structural_manager)
RefCount type definition of the structural_manager class structure.
REF_FORWARD_DECL (Parameter)
Detailed Description
Input and output functions used to read and write the structural data structures.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$
Warning
This file is still in a work in progress state
Last modified by $Author$
Function Documentation
read_structural_File()
structural_managerRef read_structural_File (const std::string & f, const ParameterRef & Param)
Read an xml file describing the structural data structures.
Parameters
f the input file name
Returns
the structural manager.
Definition at line 54 of file structuralIO.cpp.
References XMLDomParser::Exec(), XMLDomParser::get_document(), test_panda::parser, and structural_manager::xload().
REF_FORWARD_DECL() [1/2]
REF_FORWARD_DECL (structural_manager)
RefCount type definition of the structural_manager class structure.
REF_FORWARD_DECL() [2/2]
REF_FORWARD_DECL (Parameter)
write_structural_File()
void write_structural_File (const std::string & f, structural_managerRef const & CM)
Write an xml file describing the structural data structures.
Parameters
f the output file name
CM is the structural manager.
Definition at line 91 of file structuralIO.cpp.
References xml_document::create_root_node(), and xml_document::write_to_file_formatted().