HLSBitValue Class Reference
superclass include
#include <hls_bit_value.hpp>
Public Member Functions
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
 Constructors and Destructors.
HLSBitValue (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~HLSBitValue () override
Destructor.
Private Member Functions
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
superclass include
This class works as an aggregator of HLSFunctionBitValue
Definition at line 50 of file hls_bit_value.hpp.
Constructor & Destructor Documentation
HLSBitValue()
HLSBitValue::HLSBitValue (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
. include behavior includes design_flows includes frontend_flow includes HLS includes . utility includes STL includes
Definition at line 70 of file hls_bit_value.cpp.
References DesignFlowStep::debug_level, GET_CLASS, HLS_BIT_VALUE, and ~HLSBitValue().
 HLSBitValue()
HLSBitValue::~HLSBitValue () [override], [default]
Destructor.
Referenced by HLSBitValue().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > HLSBitValue::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 126 of file hls_bit_value.cpp.
References ALL_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLS_FUNCTION_BIT_VALUE, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
ComputeRelationships()
void HLSBitValue::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [private], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
check if __builtin_memcpy has to be synthesized
FIXME: temporary deactivated
Managed in HLSFunctionStep::ComputeRelationships
Root function cannot be computed at the beginning
Reimplemented from HLS_step.
Definition at line 78 of file hls_bit_value.cpp.
References HLS_step::ComputeRelationships(), ApplicationFrontendFlowStep::ComputeSignature(), HLSFunctionStep::ComputeSignature(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, HLS_FUNCTION_BIT_VALUE, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), NULL_VERTEX, DesignFlowStep::parameters, SUCCESS, THROW_ASSERT, and UNCHANGED.
Exec()
DesignFlowStep_Status HLSBitValue::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 150 of file hls_bit_value.cpp.
References EMPTY.
HasToBeExecuted()
bool HLSBitValue::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 155 of file hls_bit_value.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/hls_bit_value.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/hls_bit_value.cpp