commutative_expr_restructuring Class Reference
#include <commutative_expr_restructuring.hpp>
Public Member Functions
commutative_expr_restructuring (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~commutative_expr_restructuring () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
bool IsCommExprGimple (const tree_nodeConstRef tn) const
Return true if tree node is a gimple_assign with a mult_expr/plus_expr in the right part.
tree_nodeRef IsCommExprChain (const tree_nodeConstRef tn, const bool first) const
Given a gimple_assign with cond_expr in the right part and one of its operand it checks:
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
ScheduleRef schedule
The schedule.
AllocationInformationRef allocation_information
The allocation information.
tree_managerRef TM
The tree manager.
Additional Inherited Members
Detailed Description
Definition at line 55 of file commutative_expr_restructuring.hpp.
Constructor & Destructor Documentation
commutative_expr_restructuring()
commutative_expr_restructuring::commutative_expr_restructuring (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 130 of file commutative_expr_restructuring.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~commutative_expr_restructuring().
 commutative_expr_restructuring()
commutative_expr_restructuring::~commutative_expr_restructuring () [override], [default]
Destructor.
Referenced by commutative_expr_restructuring().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > commutative_expr_restructuring::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Not executed
If schedule is not update, do not execute this step and invalidate UpdateSchedule
Implements FrontendFlowStep.
Definition at line 83 of file commutative_expr_restructuring.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::CGetBBVersion(), COMPLETE_BB_GRAPH, FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SUCCESS, and THROW_UNREACHABLE.
HasToBeExecuted()
bool commutative_expr_restructuring::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 441 of file commutative_expr_restructuring.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), Wrefcount< T >::lock(), and DesignFlowStep::parameters.
Initialize()
void commutative_expr_restructuring::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 430 of file commutative_expr_restructuring.cpp.
References allocation_information, FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, DesignFlowStep::Initialize(), schedule, and TM.
InternalExec()
DesignFlowStep_Status commutative_expr_restructuring::InternalExec () [override], [virtual]
Performs the loops analysis.
Check if new ending time would not be larger The time in which last operand is ready
As commutative expression time we consider the worst among the existing operation in the chain
Inserting first commutative expression after the last one
Create the ssa in the left part
Create the assign
Set the bit value for the intermediate ssa to correctly update execution time
Inserting last commutative expression
Create the assign
Check that the second commutative expression is actually dead
Remove the intermediate commutative expression
Removing added statements
Adding old statements
Recomputing schedule
Setting pointer to the previous element
Restarting
Implements FunctionFrontendFlowStep.
Definition at line 177 of file commutative_expr_restructuring.cpp.
References allocation_information, FrontendFlowStep::AppM, tree_manager::CGetTreeNode(), counter, tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, EPSILON, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, Schedule::get_cstep(), tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), AllocationInformation::GetConnectionTime(), Schedule::GetEndingTime(), FunctionFrontendFlowStep::GetName(), AllocationInformation::GetTimeLatency(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, INDENT_OUT_MEX, IsCommExprChain(), IsCommExprGimple(), max(), tree_manager::new_tree_node_id(), DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, schedule, sl, STR, SUCCESS, THROW_ASSERT, TM, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, UNCHANGED, fu_binding::UNKNOWN, Schedule::UpdateTime(), and FunctionFrontendFlowStep::WriteBBGraphDot().
IsCommExprChain()
tree_nodeRef commutative_expr_restructuring::IsCommExprChain (const tree_nodeConstRef tn, const bool first) const [private]
Given a gimple_assign with cond_expr in the right part and one of its operand it checks:
if operand is a ssa_name
if operand is defined in the same basic block
if operand is defined in a gimple_assign whose right a part is another cond_expr
if operand is on the relative critical path (i.e., it delays execution of tn
Parameters
tn is the starting gimple_assign
first is true if first operand has to be considered, false if second oeprand has to be considered
Returns
the chained gimple_assignment if all conditions hold
Definition at line 151 of file commutative_expr_restructuring.cpp.
References GET_CONST_NODE, Schedule::get_cstep(), Schedule::get_cstep_end(), GET_NODE, Schedule::GetEndingTime(), Schedule::GetStartingTime(), tree_helper::is_constant(), schedule, and TM.
Referenced by InternalExec().
IsCommExprGimple()
bool commutative_expr_restructuring::IsCommExprGimple (const tree_nodeConstRef tn) const [private]
Return true if tree node is a gimple_assign with a mult_expr/plus_expr in the right part.
Parameters
tn is the tree reindex to be considered
Definition at line 138 of file commutative_expr_restructuring.cpp.
References GET_CONST_NODE, GET_NODE, and tree_helper::get_type_node().
Referenced by InternalExec().
Field Documentation
allocation_information
AllocationInformationRef commutative_expr_restructuring::allocation_information [private]
The allocation information.
Definition at line 62 of file commutative_expr_restructuring.hpp.
Referenced by Initialize(), and InternalExec().
schedule
ScheduleRef commutative_expr_restructuring::schedule [private]
The schedule.
Definition at line 59 of file commutative_expr_restructuring.hpp.
Referenced by Initialize(), InternalExec(), and IsCommExprChain().
TM
tree_managerRef commutative_expr_restructuring::TM [private]
The tree manager.
Definition at line 65 of file commutative_expr_restructuring.hpp.
Referenced by Initialize(), InternalExec(), and IsCommExprChain().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/commutative_expr_restructuring.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/commutative_expr_restructuring.cpp