CleanVirtualPhi Class Reference
Superclass include.
#include <clean_virtual_phi.hpp>
Public Member Functions
CleanVirtualPhi (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~CleanVirtualPhi () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
utility includes
Definition at line 48 of file clean_virtual_phi.hpp.
Constructor & Destructor Documentation
CleanVirtualPhi()
CleanVirtualPhi::CleanVirtualPhi (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 85 of file clean_virtual_phi.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~CleanVirtualPhi().
 CleanVirtualPhi()
CleanVirtualPhi::~CleanVirtualPhi () [override], [default]
Destructor.
Referenced by CleanVirtualPhi().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > CleanVirtualPhi::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Header include.
Parameters
relationship_type is the type of relationship to be considered
. include behavior include tree includes
Implements FrontendFlowStep.
Definition at line 60 of file clean_virtual_phi.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
HasToBeExecuted()
bool CleanVirtualPhi::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 138 of file clean_virtual_phi.cpp.
References FunctionFrontendFlowStep::bb_version.
Initialize()
void CleanVirtualPhi::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 133 of file clean_virtual_phi.cpp.
References DesignFlowStep::Initialize().
InternalExec()
DesignFlowStep_Status CleanVirtualPhi::InternalExec () [override], [virtual]
Performs the loops analysis.
Removing all the virtual phi The virtual phis refer to memory definitions and uses instead of virtual definitions and uses
Moving iterator to avoid its invalidation
Implements FunctionFrontendFlowStep.
Definition at line 93 of file clean_virtual_phi.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, INDENT_DBG_MEX, phi, sl, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/clean_virtual_phi.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/clean_virtual_phi.cpp