SynthesisEvaluation Class Reference
superclass include
#include <synthesis_evaluation.hpp>
Public Member Functions
SynthesisEvaluation (const ParameterConstRef Param, const HLS_managerRef hls_mgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor of the class.
~SynthesisEvaluation () override
Destructor of the class.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
superclass include
utility include
Class performing the actual simulation
utility include
Class performing the actual logic synthesis
Definition at line 56 of file synthesis_evaluation.hpp.
Constructor & Destructor Documentation
SynthesisEvaluation()
SynthesisEvaluation::SynthesisEvaluation (const ParameterConstRef _Param, const HLS_managerRef _hls_mgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor of the class.
Header include.
. include behavior include HLS include technology/physical_library/models technology/physical_library/models/area wrapper/synthesis include
Definition at line 68 of file synthesis_evaluation.cpp.
References ~SynthesisEvaluation().
 SynthesisEvaluation()
SynthesisEvaluation::~SynthesisEvaluation () [override], [default]
Destructor of the class.
Referenced by SynthesisEvaluation().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > SynthesisEvaluation::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 75 of file synthesis_evaluation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, GENERATE_HDL, GENERATE_SYNTHESIS_SCRIPT, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, TOP_FUNCTION, and WHOLE_APPLICATION.
InternalExec()
DesignFlowStep_Status SynthesisEvaluation::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
get the used resources from the wrapper
get the timing information after the synthesis
get the timing information after the synthesis
get the used resources from the wrapper
get the timing information after the synthesis
get the used resources from the wrapper
Implements HLSFunctionStep.
Definition at line 116 of file synthesis_evaluation.cpp.
References clb_model::ALMS, clb_model::BRAM, clb_model::DSP, clb_model::FUNCTIONAL_ELEMENTS, area_model::get_area_value(), time_model::get_execution_time(), HLS_step::HLSMgr, clb_model::LOGIC_ELEMENTS, clb_model::LUT_FF_PAIRS, DesignFlowStep::parameters, clb_model::REGISTERS, clb_model::SLICE, clb_model::SLICE_LUTS, STR, SUCCESS, and THROW_UNREACHABLE.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/evaluation/exact/synthesis_evaluation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/evaluation/exact/synthesis_evaluation.cpp