OpWriter Class Reference
#include <behavioral_writer_helper.hpp>
Public Member Functions
OpWriter (const OpGraph *operation_graph, const int detail_level)
Constructor.
void operator() (std::ostream &out, const vertex &v) const override
Functor to print the label of a vertex.
Protected Attributes
const BehavioralHelperConstRef helper
The behavioral helper.
Detailed Description
Definition at line 125 of file behavioral_writer_helper.hpp.
Constructor & Destructor Documentation
OpWriter()
OpWriter::OpWriter (const OpGraph * operation_graph, const int detail_level)
Constructor.
Parameters
op_graph is the operation graph
detail_level is the level of detail: 0 - print operation 1 - print operation and accessed variables
Definition at line 378 of file behavioral_writer_helper.cpp.
Referenced by operator()().
Member Function Documentation
operator()()
void OpWriter::operator() (std::ostream & out, const vertex & v) const [override], [virtual]
Functor to print the label of a vertex.
Parameters
out is the stream where label has to be printed
v is the vertex whose label has to be printed
Implements VertexWriter.
Definition at line 382 of file behavioral_writer_helper.cpp.
References OpGraph::CGetOpNodeInfo(), VertexWriter::detail_level, GET_NAME, GET_TYPE, helper, OpWriter(), BehavioralHelper::print_vertex(), VertexWriter::printing_graph, TYPE_ASSIGN, TYPE_ENTRY, TYPE_EXIT, TYPE_EXTERNAL, TYPE_GOTO, TYPE_IF, TYPE_LOAD, TYPE_MEMCPY, TYPE_STORE, TYPE_SWITCH, and AbsControlStep::UNKNOWN.
Field Documentation
helper
const BehavioralHelperConstRef OpWriter::helper [protected]
The behavioral helper.
Definition at line 129 of file behavioral_writer_helper.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/behavioral_writer_helper.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/behavioral_writer_helper.cpp