TTT_maximal_weighted_clique< Graph > Class Template Reference
Class computing the maximal weighted clique from a generic graph.
#include <clique_covering.hpp>
Public Member Functions
const CustomOrderedSet< vertex > get_weighted_maximal_cliques (const Graph &g, int upper_bound)
return the weighted maximal clique of a graph g
int get_last_W_Q_max ()
return the last weight of the maximum clique
TTT_maximal_weighted_clique (std::map< C_vertex, std::string > &_names)
Private Types
typedef boost::graph_traits< Graph >::vertex_iterator vertex_iterator
vertex iterator
typedef boost::graph_traits< Graph >::vertex_descriptor vertex
vertex object
typedef boost::graph_traits< Graph >::adjacency_iterator adjacency_iterator
adjacency iterator
typedef boost::graph_traits< Graph >::out_edge_iterator edge_iterator
out edge iterator
Private Member Functions
vertex get_max_weighted_adiacent_intersection (const CustomUnorderedSet< vertex > &subg, const CustomUnorderedSet< vertex > &cand, const Graph &g)
return the vertex of subg with the maximum intersection with cand
vertex get_max_weight_vertex (CustomUnorderedSet< vertex > &ext, const Graph &g)
return the vertex of ext having the maximum edge weight with respect to the graph g
int compute_delta_weight (vertex q_vertex, CustomUnorderedSet< vertex > Q_set, const Graph &g)
compute the delta of the weight by adding q_vertex to the clique
void expand (CustomUnorderedSet< vertex > &subg, CustomUnorderedSet< vertex > &cand, const Graph &g, int upper_bound)
recursive procedure expand defined in first cited paper
Private Attributes
CustomUnorderedSet< vertex > Q
set of vertices of the current clique
CustomOrderedSet< vertex > Q_max
set of vertices of the maximum clique found so far
int W_Q
weight of Q
int W_Q_max
weight of Q_max
std::map< C_vertex, std::string > & names
Detailed Description
template<typename Graph>
class TTT_maximal_weighted_clique< Graph >
Class computing the maximal weighted clique from a generic graph.
Definition at line 323 of file clique_covering.hpp.
Member Typedef Documentation
adjacency_iterator
template<typename Graph>
typedef boost::graph_traits<Graph>::adjacency_iterator TTT_maximal_weighted_clique< Graph >::adjacency_iterator [private]
adjacency iterator
Definition at line 330 of file clique_covering.hpp.
edge_iterator
template<typename Graph>
typedef boost::graph_traits<Graph>::out_edge_iterator TTT_maximal_weighted_clique< Graph >::edge_iterator [private]
out edge iterator
Definition at line 332 of file clique_covering.hpp.
vertex
template<typename Graph>
typedef boost::graph_traits<Graph>::vertex_descriptor TTT_maximal_weighted_clique< Graph >::vertex [private]
vertex object
Definition at line 328 of file clique_covering.hpp.
vertex_iterator
template<typename Graph>
typedef boost::graph_traits<Graph>::vertex_iterator TTT_maximal_weighted_clique< Graph >::vertex_iterator [private]
vertex iterator
Definition at line 326 of file clique_covering.hpp.
Constructor & Destructor Documentation
TTT_maximal_weighted_clique()
template<typename Graph>
TTT_maximal_weighted_clique< Graph >::TTT_maximal_weighted_clique (std::map< C_vertex, std::string > & _names) [inline], [explicit]
Definition at line 490 of file clique_covering.hpp.
Member Function Documentation
compute_delta_weight()
template<typename Graph>
int TTT_maximal_weighted_clique< Graph >::compute_delta_weight (vertex q_vertex, CustomUnorderedSet< vertex > Q_set, const Graph & g) [inline], [private]
compute the delta of the weight by adding q_vertex to the clique
Definition at line 399 of file clique_covering.hpp.
References result.
expand()
template<typename Graph>
void TTT_maximal_weighted_clique< Graph >::expand (CustomUnorderedSet< vertex > & subg, CustomUnorderedSet< vertex > & cand, const Graph & g, int upper_bound) [inline], [private]
recursive procedure expand defined in first cited paper
get the vertex in subg with the maximum of adjacent vertices in cand
get adjacent vertices of u
set of vertices adjacent to u
compute EXT_u = CAND - gamma_u
compute delta_weight
Definition at line 411 of file clique_covering.hpp.
References unordered_set_difference(), and unordered_set_intersection().
get_last_W_Q_max()
template<typename Graph>
int TTT_maximal_weighted_clique< Graph >::get_last_W_Q_max () [inline]
return the last weight of the maximum clique
Definition at line 486 of file clique_covering.hpp.
Referenced by TTT_based_clique_covering< vertex_type >::do_clique_covering().
get_max_weight_vertex()
template<typename Graph>
vertex TTT_maximal_weighted_clique< Graph >::get_max_weight_vertex (CustomUnorderedSet< vertex > & ext, const Graph & g) [inline], [private]
return the vertex of ext having the maximum edge weight with respect to the graph g
Definition at line 373 of file clique_covering.hpp.
References result, and THROW_ASSERT.
get_max_weighted_adiacent_intersection()
template<typename Graph>
vertex TTT_maximal_weighted_clique< Graph >::get_max_weighted_adiacent_intersection (const CustomUnorderedSet< vertex > & subg, const CustomUnorderedSet< vertex > & cand, const Graph & g) [inline], [private]
return the vertex of subg with the maximum intersection with cand
Definition at line 346 of file clique_covering.hpp.
References result, and THROW_ASSERT.
get_weighted_maximal_cliques()
template<typename Graph>
const CustomOrderedSet<vertex> TTT_maximal_weighted_clique< Graph >::get_weighted_maximal_cliques (const Graph & g, int upper_bound) [inline]
return the weighted maximal clique of a graph g
Definition at line 469 of file clique_covering.hpp.
References min.
Referenced by TTT_based_clique_covering< vertex_type >::do_clique_covering().
Field Documentation
names
template<typename Graph>
std::map<C_vertex, std::string>& TTT_maximal_weighted_clique< Graph >::names [private]
Definition at line 343 of file clique_covering.hpp.
Q
template<typename Graph>
CustomUnorderedSet<vertex> TTT_maximal_weighted_clique< Graph >::Q [private]
set of vertices of the current clique
Definition at line 335 of file clique_covering.hpp.
Q_max
template<typename Graph>
CustomOrderedSet<vertex> TTT_maximal_weighted_clique< Graph >::Q_max [private]
set of vertices of the maximum clique found so far
Definition at line 337 of file clique_covering.hpp.
W_Q
template<typename Graph>
int TTT_maximal_weighted_clique< Graph >::W_Q [private]
weight of Q
Definition at line 339 of file clique_covering.hpp.
W_Q_max
template<typename Graph>
int TTT_maximal_weighted_clique< Graph >::W_Q_max [private]
weight of Q_max
Definition at line 341 of file clique_covering.hpp.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/clique_covering.hpp