xml_child Class Reference
#include <xml_node.hpp>
Public Member Functions
xml_child (const std::string &_name)
constructor
void print (std::ostream &os, bool formatted, simple_indent *pp) const override
Print the class.
xml_element * add_child_element (const std::string &name)
Add a child element to this node.
xml_element * add_child_element (const xml_nodeRef &node)
Add a child element to this node starting from a given node.
xml_text_node * add_child_text (const std::string &content)
Append a new text node.
xml_text_node * get_child_text ()
Get the first child text content node.
const xml_text_node * get_child_text () const
Get the first child text content node.
xml_comment_node * add_child_comment (const std::string &content)
Append a new comment node.
xml_att_decl_node * add_child_attribute_declaration (const std::string &name)
Append a new attribute declaration node.
void remove_child (xml_node *el)
Remove the child node.
node_list const & get_children ()
Obtain the list of child nodes.
const node_list & get_children () const
Obtain the list of child nodes.
bool has_child () const
const CustomSet< xml_nodeRef > CGetDescendants (const std::string &path) const
Return the set of descendants with a specific path.
Private Attributes
node_list child_list
xml_text_node * first_text
Additional Inherited Members
Detailed Description
Definition at line 219 of file xml_node.hpp.
Constructor & Destructor Documentation
xml_child()
xml_child::xml_child (const std::string & _name) [inline], [explicit]
constructor
Definition at line 225 of file xml_node.hpp.
Member Function Documentation
add_child_attribute_declaration()
xml_att_decl_node * xml_child::add_child_attribute_declaration (const std::string & name)
Append a new attribute declaration node.
Parameters
name The name of the declaration.
Returns
The new attribute declaration node.
Definition at line 88 of file xml_node.cpp.
References child_list.
add_child_comment()
xml_comment_node * xml_child::add_child_comment (const std::string & content)
Append a new comment node.
Parameters
content The text. This should be unescaped - see xml_comment_node::set_content().
Returns
The new comment node.
Definition at line 80 of file xml_node.cpp.
References child_list.
add_child_element() [1/2]
xml_element * xml_child::add_child_element (const std::string & _name)
Add a child element to this node.
STL include.
Parameters
name The new node name
Returns
The newly-created element
utility include
Definition at line 54 of file xml_node.cpp.
References child_list.
Referenced by xml_document::create_root_node(), xml_set_variable_t::create_xml_node(), xml_parameter_t::create_xml_node(), xml_command_t::create_xml_node(), xml_shell_t::create_xml_node(), xml_ite_block_t::create_xml_node(), BackendFlow::create_xml_scripts(), WriteTechnology::Exec(), Evaluation::Exec(), TestVectorParser::ParseXMLFile(), Translator::Translator(), DesignCompilerWrapper::write_timing_paths(), Parameter::write_xml_configuration_file(), ProfilingInformation::WriteToXml(), GccWrapper::WriteXml(), FPGA_device::xwrite(), liberty_model::xwrite(), IC_device::xwrite(), attribute::xwrite(), NP_functionality::xwrite(), hls::xwrite(), library_manager::xwrite(), HLS_constraints::xwrite(), structural_type_descriptor::xwrite(), structural_manager::xwrite(), operation::xwrite(), structural_object::xwrite(), functional_unit::xwrite(), functional_unit_template::xwrite(), memory::xwrite(), port_o::xwrite(), event_o::xwrite(), data_o::xwrite(), action_o::xwrite(), constant_o::xwrite(), signal_o::xwrite(), module::xwrite(), component_o::xwrite(), channel_o::xwrite(), bus_connection_o::xwrite(), RTLCharacterization::xwrite_characterization(), HLS_constraints::xwriteBindingConstraints(), HLS_constraints::xwriteFUConstraints(), and HLS_constraints::xwriteSchedulingConstraints().
add_child_element() [2/2]
xml_element * xml_child::add_child_element (const xml_nodeRef & node)
Add a child element to this node starting from a given node.
Parameters
node is the given datastructure to be added
Returns
The newly-created element
Definition at line 62 of file xml_node.cpp.
References child_list.
add_child_text()
xml_text_node * xml_child::add_child_text (const std::string & content)
Append a new text node.
Parameters
content The text. This should be unescaped - see ContentNode::set_content().
Returns
The new text node.
Definition at line 68 of file xml_node.cpp.
References child_list, and first_text.
Referenced by attribute::xwrite(), library_manager::xwrite(), structural_object::xwrite(), functional_unit::xwrite(), functional_unit_template::xwrite(), port_o::xwrite(), module::xwrite(), and RTLCharacterization::xwrite_characterization().
CGetDescendants()
const CustomSet< xml_nodeRef > xml_child::CGetDescendants (const std::string & path) const
Return the set of descendants with a specific path.
Parameters
path is the / separated list of the tags to be crossed from the current node to the ancestor
Returns
the set of xml nodes
Definition at line 106 of file xml_node.cpp.
References get_children(), test_panda::level, and SplitString().
get_child_text() [1/2]
xml_text_node* xml_child::get_child_text () [inline]
Get the first child text content node.
This is a convenience method, meant as an alternative to iterating over all the child nodes to find the first suitable node then and getting the text directly.
Returns
The first text node, if any.
Definition at line 263 of file xml_node.hpp.
Referenced by BackendFlow::create_xml_scripts(), xml_element::print(), and attribute::xload().
get_child_text() [2/2]
const xml_text_node* xml_child::get_child_text () const [inline]
Get the first child text content node.
This is a convenience method, meant as an alternative to iterating over all the child nodes to find the first suitable node then and getting the text directly.
Returns
The first text node, if any.
Definition at line 272 of file xml_node.hpp.
get_children() [1/2]
node_list const& xml_child::get_children () [inline]
Obtain the list of child nodes.
Returns
The list of child nodes.
Definition at line 300 of file xml_node.hpp.
Referenced by HLS_constraints::add_builtin_constraints(), CGetDescendants(), HLS_target::create_target(), BackendFlow::create_xml_scripts(), get_connections(), Translator::get_normalization(), Parameter::GetFileFormat(), HLS_constraints::HLS_constraints(), interface_infer::InternalExec(), Parameter::load_xml_configuration_file(), Parameter::load_xml_configuration_file_rec(), DataXmlParser::Parse(), mem_xml_allocation::parse_external_allocation(), BackendFlow::parse_flow(), mem_xml_allocation::parse_internal_allocation(), mem_xml_allocation::parse_xml_allocation(), TestVectorParser::ParseXMLFile(), xml_element::print(), Translator::read_column_formats(), HLS_constraints::read_HLS_constraints_File(), GccWrapper::ReadXml(), XilinxBackendFlow::vivado_xparse_utilization(), Translator::write_to_latex(), target_technology::xload(), attribute::xload(), target_device::xload(), BackendFlow::xload(), hls::xload(), HLS_constraints::xload(), library_manager::xload(), SynthesisTool::xload(), technology_manager::xload(), structural_manager::xload(), operation::xload(), structural_object::xload(), functional_unit::xload(), functional_unit_template::xload(), port_o::xload(), action_o::xload(), signal_o::xload(), module::xload(), channel_o::xload(), target_device::xload_device_parameters(), SynthesisTool::xload_scripts(), target_technology::xload_technology_parameters(), time_model::xload_timing_path(), xml_command_t::xml_command_t(), xml_foreach_t::xml_foreach_t(), xml_ite_block_t::xml_ite_block_t(), xml_parameter_t::xml_parameter_t(), xml_set_variable_t::xml_set_variable_t(), xml_shell_t::xml_shell_t(), XilinxBackendFlow::xparse_timing(), AlteraBackendFlow::xparse_utilization(), LatticeBackendFlow::xparse_utilization(), NanoXploreBackendFlow::xparse_utilization(), and XilinxBackendFlow::xparse_xst_utilization().
get_children() [2/2]
const node_list& xml_child::get_children () const [inline]
Obtain the list of child nodes.
Returns
The list of child nodes.
Definition at line 308 of file xml_node.hpp.
has_child()
bool xml_child::has_child () const [inline]
Returns
Whether this node has children, or is empty.
Definition at line 316 of file xml_node.hpp.
Referenced by xml_element::print().
print()
void xml_child::print (std::ostream & os, bool formatted, simple_indent * pp) const [inline], [override], [virtual]
Print the class.
Implements xml_node.
Definition at line 232 of file xml_node.hpp.
References xml_node::name.
Referenced by xml_element::print(), and xml_document::print().
remove_child()
void xml_child::remove_child (xml_node * el) [inline]
Remove the child node.
Parameters
el The child node to remove. This Node will be deleted and therefore unusable after calling this method.
Definition at line 292 of file xml_node.hpp.
Field Documentation
child_list
node_list xml_child::child_list [private]
Definition at line 329 of file xml_node.hpp.
Referenced by add_child_attribute_declaration(), add_child_comment(), add_child_element(), and add_child_text().
first_text
xml_text_node* xml_child::first_text [private]
Definition at line 330 of file xml_node.hpp.
Referenced by add_child_text().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_node.hpp
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_node.cpp