top_entity Class Reference
#include <top_entity.hpp>
Public Member Functions
top_entity (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type=HLSFlowStep_Type::TOP_ENTITY_CREATION)
Constructor.
virtual ~top_entity ()
Destructor.
virtual DesignFlowStep_Status InternalExec ()
Execute the step.
Protected Member Functions
void add_ports (structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef reset_port)
Adds the input/output ports to the circuit.
void add_command_signals (structural_objectRef circuit)
Adds the command signals to the circuit.
virtual const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
virtual void add_input_register (structural_objectRef port_in, const std::string &port_prefix, structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef reset_port, structural_objectRef e_port)
Add the register to store input parameters.
Protected Attributes
structural_managerRef SM
reference to the resulting circuit
Additional Inherited Members
Detailed Description
Definition at line 50 of file top_entity.hpp.
Constructor & Destructor Documentation
top_entity()
top_entity::top_entity (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::TOP_ENTITY_CREATION)
Constructor.
STD include.
Parameters
design_flow_manager is the design flow manager
top_entity_type is the type of top entity to be created
STL includes technology/physical_library include
Definition at line 81 of file top_entity.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~top_entity().
 top_entity()
top_entity::~top_entity () [virtual], [default]
Destructor.
Referenced by top_entity().
Member Function Documentation
add_command_signals()
void top_entity::add_command_signals (structural_objectRef circuit) [protected]
Adds the command signals to the circuit.
Parameters
circuit is the reference to the datastructure representing the circuit
it means that the operation has not to be executed
Definition at line 554 of file top_entity.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), hls::controller, hls::datapath, structural_object::find_member(), structural_manager::get_circ(), structural_object::get_id(), structural_object::get_typeRef(), conn_binding::GetSelectors(), HLSFunctionStep::HLS, port_o_K, hls::Rconn, SM, and THROW_ASSERT.
Referenced by InternalExec().
add_input_register()
void top_entity::add_input_register (structural_objectRef port_in, const std::string & port_prefix, structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef reset_port, structural_objectRef e_port) [protected], [virtual]
Add the register to store input parameters.
Parameters
port_in is the input parameter port of the datapath
port_prefix is the prefix of the port name
circuit is the circuit of the top entity
clock_port is the port of the clock signal
reset_port is the port of the reset signal
e_port is the input parameter port of the top entity
Reimplemented in top_entity_cs.
Definition at line 311 of file top_entity.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), CLOCK_PORT_NAME, structural_object::find_member(), technology_manager::get_library(), GET_TYPE_SIZE, structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_T, port_o_K, register_STD, RESET_PORT_NAME, and SM.
Referenced by add_ports().
add_ports()
void top_entity::add_ports (structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef reset_port) [protected]
Adds the input/output ports to the circuit.
Parameters
circuit is the reference to the datastructure representing the circuit
creating extern IN port on top starting from extern ports on datapath and add connection
creating extern OUT port on top starting from extern ports on datapath and add connection
creating extern IO port on top starting from extern ports on datapath and add connection
Definition at line 335 of file top_entity.cpp.
References structural_manager::add_connection(), structural_manager::add_constant(), add_input_register(), structural_manager::add_port(), structural_manager::add_port_vector(), FunctionBehavior::CGetBehavioralHelper(), hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), port_o::fix_port_properties(), hls::functionId, HLSFunctionStep::funId, structural_manager::get_circ(), BehavioralHelper::get_function_index(), get_id(), structural_object::get_kind(), structural_object::get_kind_text(), BehavioralHelper::get_parameters(), generic_obj::get_structural_obj(), GET_TYPE_SIZE, structural_object::get_typeRef(), BehavioralHelper::GetFunctionReturnType(), HLSFunctionStep::HLS, HLS_step::HLSMgr, port_o::IN, INDENT_DBG_MEX, port_o::IO, conn_binding::OUT, port_o::OUT, port_o_K, port_vector_o_K, BehavioralHelper::PrintVariable(), hls::Rconn, hls::registered_inputs, RETURN_PORT_NAME, SM, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by top_entity_parallel_cs::InternalExec(), and InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > top_entity::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Reimplemented in top_entity_parallel_cs.
Definition at line 89 of file top_entity.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status top_entity::InternalExec () [virtual]
Execute the step.
Returns
the exit status of this step
function name to be synthesized
Test on previous steps. They checks if datapath and controller have been created. If they didn't, top circuit cannot be created.
top circuit creation
main circuit type
setting top circuit component
Set some descriptions and legal stuff
creating structural_manager
creating structural_manager
command signal type descriptor
add clock port
connect to datapath and controller clock
add reset port
connecting global reset port to the datapath one
connecting global reset port to the controller one
start port
check if datapath has a start signal
add done port
check if checker has to be added
add entry in in_port_map between port id and port index
Implements HLSFunctionStep.
Reimplemented in TopEntityMemoryMapped, top_entity_parallel_cs, and top_entity_cs.
Definition at line 117 of file top_entity.cpp.
References add_command_signals(), structural_manager::add_connection(), structural_manager::add_port(), add_ports(), structural_manager::add_sign(), FunctionBehavior::CGetBehavioralHelper(), CLOCK_PORT_NAME, hls::control_flow_checker, hls::controller, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, DONE_PORT_NAME_CFC, structural_object::find_member(), flipflop_AR, flipflop_SR, FSM_CONTROLLER_CREATOR, FSM_CS_CONTROLLER_CREATOR, HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, port_o::IN, LIBRARY_STD, NEXT_STATE_PORT_NAME, port_o::OUT, DesignFlowStep::parameters, port_o_K, PRESENT_STATE_PORT_NAME, PRINT_DBG_MEX, memory::propagate_memory_parameters(), hls::registered_done_port, RESET_PORT_NAME, structural_object::set_black_box(), structural_object::set_owner(), structural_manager::set_top_info(), SM, START_PORT_NAME, START_PORT_NAME_CFC, SUCCESS, THROW_ASSERT, and hls::top.
Referenced by top_entity_cs::InternalExec(), and TopEntityMemoryMapped::InternalExec().
Field Documentation
SM
structural_managerRef top_entity::SM [protected]
reference to the resulting circuit
Definition at line 54 of file top_entity.hpp.
Referenced by add_command_signals(), top_entity_cs::add_context_switch_port(), top_entity_cs::add_context_switch_port_kernel(), top_entity_cs::add_input_register(), add_input_register(), add_ports(), top_entity_parallel_cs::connect_loop_iter(), top_entity_parallel_cs::connect_port_parallel(), top_entity_parallel_cs::InternalExec(), InternalExec(), and TopEntityMemoryMapped::resizing_IO().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/top_entity.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/top_entity.cpp