ChainingInformation Class Reference
#include <chaining_information.hpp>
Public Member Functions
ChainingInformation (const HLS_managerConstRef HLS_mgr, const unsigned int function_id)
Constructor.
void Initialize ()
Initialize the object (i.e., like a constructor, but executed just before exec of a step)
size_t get_representative_in (vertex op1) const
Return the representative vertex associated with the chained vertices set in input.
size_t get_representative_out (vertex op1) const
Return the representative vertex associated with the chained vertices set in output.
bool is_chained_vertex (vertex v) const
return true in case the vertex is in chaining with something
bool may_be_chained_ops (vertex op1, vertex op2) const
check if two operations are chained in at least one state
void add_chained_vertices_in (vertex op1, vertex src)
put into relation the vertices whith respect the chained vertices connected with the input
void add_chained_vertices_out (vertex op1, vertex tgt)
put into relation the vertices whith respect the chained vertices connected with the output
Protected Attributes
std::map< vertex, unsigned int > actual_bb_index_map
relation between operation and basic block
ChainingSetRef chaining_relation
relation between vertices in terms of chaining in input or in output
CustomOrderedSet< vertex > is_chained_with
set of vertices chained with something
const Wrefcount< const HLS_manager > HLS_mgr
The HLS manager.
const unsigned int function_id
The index of the function.
Friends
class chaining
class epdg_sched_based_chaining_computation
class sched_based_chaining_computation
Detailed Description
Definition at line 56 of file chaining_information.hpp.
Constructor & Destructor Documentation
ChainingInformation()
ChainingInformation::ChainingInformation (const HLS_managerConstRef HLS_mgr, const unsigned int function_id)
Constructor.
Parameters
HLS_mgr is the HLS manager
function_id is the index of the function to which this data structure refers
Definition at line 88 of file chaining_information.cpp.
Member Function Documentation
add_chained_vertices_in()
void ChainingInformation::add_chained_vertices_in (vertex op1, vertex src)
put into relation the vertices whith respect the chained vertices connected with the input
Parameters
op1 is the considered vertex
src is the chained vertex chained in input
Definition at line 128 of file chaining_information.cpp.
References chaining_relation.
Referenced by sched_based_chaining_computation::InternalExec().
add_chained_vertices_out()
void ChainingInformation::add_chained_vertices_out (vertex op1, vertex tgt)
put into relation the vertices whith respect the chained vertices connected with the output
Parameters
op1 is the considered vertex
tgt is the chained vertex chained in output
Definition at line 133 of file chaining_information.cpp.
References chaining_relation.
Referenced by sched_based_chaining_computation::InternalExec().
get_representative_in()
size_t ChainingInformation::get_representative_in (vertex op1) const
Return the representative vertex associated with the chained vertices set in input.
It is assumed that chaining define an equivalent relation between vertices.
Parameters
op1 is the considered vertex
Returns
the representative vertex
Definition at line 92 of file chaining_information.cpp.
References chaining_relation.
Referenced by cdfc_module_binding::InternalExec(), and cdfc_module_binding::update_slack_starting_time().
get_representative_out()
size_t ChainingInformation::get_representative_out (vertex op1) const
Return the representative vertex associated with the chained vertices set in output.
It is assumed that chaining define an equivalent relation between vertices.
Parameters
op1 is the considered vertex
Returns
the representative vertex
Definition at line 97 of file chaining_information.cpp.
References chaining_relation.
Initialize()
void ChainingInformation::Initialize ()
Initialize the object (i.e., like a constructor, but executed just before exec of a step)
Definition at line 102 of file chaining_information.cpp.
References hls::chaining_information, chaining_relation, FunctionBehavior::FLSAODG, function_id, HLS_mgr, and Wrefcount< T >::lock().
Referenced by sched_based_chaining_computation::Initialize(), and chaining::Initialize().
is_chained_vertex()
bool ChainingInformation::is_chained_vertex (vertex v) const
return true in case the vertex is in chaining with something
Parameters
v is the operation
Definition at line 117 of file chaining_information.cpp.
References is_chained_with.
may_be_chained_ops()
bool ChainingInformation::may_be_chained_ops (vertex op1, vertex op2) const
check if two operations are chained in at least one state
Parameters
op1 is the first vertex
op2 is the second vertex
Definition at line 122 of file chaining_information.cpp.
References chaining_relation.
Referenced by cdfc_module_binding::InternalExec(), and cdfc_module_binding::update_slack_starting_time().
Friends And Related Function Documentation
chaining
friend class chaining [friend]
Definition at line 59 of file chaining_information.hpp.
epdg_sched_based_chaining_computation
friend class epdg_sched_based_chaining_computation [friend]
Definition at line 60 of file chaining_information.hpp.
sched_based_chaining_computation
friend class sched_based_chaining_computation [friend]
Definition at line 61 of file chaining_information.hpp.
Field Documentation
actual_bb_index_map
std::map<vertex, unsigned int> ChainingInformation::actual_bb_index_map [protected]
relation between operation and basic block
Definition at line 64 of file chaining_information.hpp.
chaining_relation
ChainingSetRef ChainingInformation::chaining_relation [protected]
relation between vertices in terms of chaining in input or in output
Definition at line 67 of file chaining_information.hpp.
Referenced by add_chained_vertices_in(), add_chained_vertices_out(), get_representative_in(), get_representative_out(), Initialize(), and may_be_chained_ops().
function_id
const unsigned int ChainingInformation::function_id [protected]
The index of the function.
Definition at line 76 of file chaining_information.hpp.
Referenced by Initialize().
HLS_mgr
const Wrefcount<const HLS_manager> ChainingInformation::HLS_mgr [protected]
The HLS manager.
Definition at line 73 of file chaining_information.hpp.
Referenced by Initialize().
is_chained_with
CustomOrderedSet<vertex> ChainingInformation::is_chained_with [protected]
set of vertices chained with something
Definition at line 70 of file chaining_information.hpp.
Referenced by sched_based_chaining_computation::InternalExec(), and is_chained_vertex().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/chaining/chaining_information.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/chaining/chaining_information.cpp