/home/osboxes/bambu/PandA-bambu/src/parser/discrepancy/parse_discrepancy.hpp File Reference
#include `refcount.hpp`
Functions
REF_FORWARD_DECL (Discrepancy)
void parse_discrepancy (const std::string &c_trace_filename, DiscrepancyRef Discrepancy)
Function Documentation
parse_discrepancy()
void parse_discrepancy (const std::string & c_trace_filename, DiscrepancyRef Discrepancy)
Definition at line 55 of file parse_discrepancy.cpp.
References discrepancy_parseY(), and THROW_ERROR.
Referenced by HWDiscrepancyAnalysis::Exec(), and vcd_utility::Exec().
REF_FORWARD_DECL()
REF_FORWARD_DECL (Discrepancy)
Author
Pietro Fezzardi pietrofezzardi@gmail.com