target_manager Class Reference
#include <target_manager.hpp>
Public Member Functions
target_manager (const ParameterConstRef &_Param, const technology_managerRef &_TM, const target_deviceRef &device)
Constructor.
virtual ~target_manager ()
Destructor.
void set_technology_manager (const technology_managerRef &_TM)
Sets the technology manager.
const technology_managerRef get_technology_manager () const
Returns the current technology manager.
void set_target_technology (const target_technologyRef &_target)
Sets the reference to the target technology manager class.
const target_technologyRef get_target_technology () const
Returns the reference to the class representing the target technology.
void set_target_device (const target_deviceRef &_device)
Sets the reference to the target device class.
const target_deviceRef get_target_device () const
Returns the reference to the class containing information about the target device.
Protected Attributes
const ParameterConstRef Param
class containing all the parameters
technology_managerRef TM
information about the technology library
target_deviceRef device
reference to the information about the target device
target_technologyRef target
reference to the target technology
Detailed Description
Definition at line 53 of file target_manager.hpp.
Constructor & Destructor Documentation
target_manager()
target_manager::target_manager (const ParameterConstRef & _Param, const technology_managerRef & _TM, const target_deviceRef & device)
Constructor.
Header include.
Parameters
_Param is the reference to the class containing all the parameters
creating the datastructure representing the target device
Definition at line 48 of file target_manager.cpp.
References set_target_device(), set_technology_manager(), and ~target_manager().
 target_manager()
target_manager::~target_manager () [virtual], [default]
Destructor.
Referenced by target_manager().
Member Function Documentation
get_target_device()
const target_deviceRef target_manager::get_target_device () const
Returns the reference to the class containing information about the target device.
Definition at line 84 of file target_manager.cpp.
References device.
Referenced by allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), memory_allocation::finalize_memory_allocation(), mem_dominator_allocation::InternalExec(), allocation::InternalExec(), HLS_manager::IsSingleWriteMemory(), and mem_xml_allocation::parse_xml_allocation().
get_target_technology()
const target_technologyRef target_manager::get_target_technology () const
Returns the reference to the class representing the target technology.
Definition at line 73 of file target_manager.cpp.
References target.
get_technology_manager()
const technology_managerRef target_manager::get_technology_manager () const
Returns the current technology manager.
Definition at line 63 of file target_manager.cpp.
References TM.
Referenced by HLSFunctionStep::ComputeRelationships(), HLS_step::ComputeRelationships(), fun_dominator_allocation::Exec(), IR_lowering::expand_MC(), allocation::get_compliant_pipelined_unit(), allocation::get_fu(), AllocationInformation::get_fu(), allocation::Initialize(), and mem_dominator_allocation::InternalExec().
set_target_device()
void target_manager::set_target_device (const target_deviceRef & _device)
Sets the reference to the target device class.
Definition at line 78 of file target_manager.cpp.
References device, target_device::get_target_technology(), and set_target_technology().
Referenced by target_manager().
set_target_technology()
void target_manager::set_target_technology (const target_technologyRef & _target)
Sets the reference to the target technology manager class.
Definition at line 68 of file target_manager.cpp.
References target.
Referenced by set_target_device().
set_technology_manager()
void target_manager::set_technology_manager (const technology_managerRef & _TM)
Sets the technology manager.
Definition at line 58 of file target_manager.cpp.
References TM.
Referenced by target_manager().
Field Documentation
device
target_deviceRef target_manager::device [protected]
reference to the information about the target device
Definition at line 63 of file target_manager.hpp.
Referenced by get_target_device(), HLS_target::HLS_target(), and set_target_device().
Param
const ParameterConstRef target_manager::Param [protected]
class containing all the parameters
Definition at line 57 of file target_manager.hpp.
Referenced by HLS_target::HLS_target().
target
target_technologyRef target_manager::target [protected]
reference to the target technology
Definition at line 66 of file target_manager.hpp.
Referenced by HLS_target::create_target(), get_target_technology(), HLS_target::HLS_target(), and set_target_technology().
TM
technology_managerRef target_manager::TM [protected]
information about the technology library
Definition at line 60 of file target_manager.hpp.
Referenced by HLS_target::create_target(), get_technology_manager(), and set_technology_manager().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/target_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/target_manager.cpp