call_graph_computation Class Reference
Build call graph structures starting from the tree_manager.
#include <call_graph_computation.hpp>
Public Member Functions
call_graph_computation (const ParameterConstRef Param, const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~call_graph_computation () override
Destructor.
DesignFlowStep_Status Exec () override
Computes the call graph data structure.
Private Member Functions
void call_graph_computation_recursive (const tree_managerRef &TM, const tree_nodeRef &tn, unsigned int node_stmt, enum FunctionEdgeInfo::CallType call_type)
Recursive analysis of the tree nodes looking for call expressions.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const CallGraphManagerRef CGM
The CallGraphManager used to modify the call graph.
unsigned int current
Index of current function.
CustomOrderedSet< tree_nodeRef > already_visited
set of already examined addr_expr used to avoid circular recursion
Additional Inherited Members
Detailed Description
Build call graph structures starting from the tree_manager.
Definition at line 71 of file call_graph_computation.hpp.
Constructor & Destructor Documentation
call_graph_computation()
call_graph_computation::call_graph_computation (const ParameterConstRef _parameters, const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
design_flow_manager is the design flow manager
Behavior include Parameter include Tree include Utility include
Definition at line 71 of file call_graph_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~call_graph_computation().
 call_graph_computation()
call_graph_computation::~call_graph_computation () [override], [default]
Destructor.
Referenced by call_graph_computation().
Member Function Documentation
call_graph_computation_recursive()
void call_graph_computation::call_graph_computation_recursive (const tree_managerRef & TM, const tree_nodeRef & tn, unsigned int node_stmt, enum FunctionEdgeInfo::CallType call_type) [private]
Recursive analysis of the tree nodes looking for call expressions.
Parameters
TM is the tree manager.
tn is current tree node.
node_stmt is the analyzed tree node
call_type is the type of call to be added
check for nested function
var decl performs an assignment when init is not null
Definition at line 188 of file call_graph_computation.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, CGM, current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionEdgeInfo::direct_call, tree_helper::find_obj_type_ref_function(), fun(), tree_manager::get_implementation_node(), GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, NESTED_FUNCTIONS_EC, STR, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, and THROW_UNREACHABLE.
Referenced by Exec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > call_graph_computation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 79 of file call_graph_computation.cpp.
References CREATE_TREE_MANAGER, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status call_graph_computation::Exec () [override], [virtual]
Computes the call graph data structure.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 114 of file call_graph_computation.cpp.
References FrontendFlowStep::AppM, call_graph_computation_recursive(), CGM, current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, fun(), FunctionEdgeInfo::function_address, tree_manager::get_implementation_node(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetAllFunctions(), INDENT_DBG_MEX, tree_helper::name_function(), NESTED_FUNCTIONS_EC, DesignFlowStep::parameters, sl, STR, SUCCESS, THROW_ERROR, and THROW_ERROR_CODE.
Field Documentation
already_visited
CustomOrderedSet<tree_nodeRef> call_graph_computation::already_visited [private]
set of already examined addr_expr used to avoid circular recursion
Definition at line 81 of file call_graph_computation.hpp.
CGM
const CallGraphManagerRef call_graph_computation::CGM [private]
The CallGraphManager used to modify the call graph.
Definition at line 75 of file call_graph_computation.hpp.
Referenced by call_graph_computation_recursive(), and Exec().
current
unsigned int call_graph_computation::current [private]
Index of current function.
Definition at line 78 of file call_graph_computation.hpp.
Referenced by call_graph_computation_recursive(), and Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/call_graph_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/call_graph_computation.cpp