CBackendStepFactory Class Reference
#include <c_backend_step_factory.hpp>
Public Member Functions
CBackendStepFactory (const DesignFlowManagerConstRef design_flow_manager, const application_managerConstRef application_manager, const ParameterConstRef param)
Constructor.
~CBackendStepFactory () override
Destructor.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
const DesignFlowStepRef CreateCBackendStep (const CBackend::Type c_backend_type, const std::string &file_name, const CBackendInformationConstRef c_backend_information) const
Create a backend c step.
Private Attributes
const application_managerConstRef application_manager
Additional Inherited Members
Detailed Description
Definition at line 67 of file c_backend_step_factory.hpp.
Constructor & Destructor Documentation
CBackendStepFactory()
CBackendStepFactory::CBackendStepFactory (const DesignFlowManagerConstRef _design_flow_manager, const application_managerConstRef _application_manager, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
design_flow_manager is the design flow manager
parameters is the set of input parameters
Header include . includes
Definition at line 55 of file c_backend_step_factory.cpp.
References DesignFlowStepFactory::debug_level, GET_CLASS, DesignFlowStepFactory::parameters, and ~CBackendStepFactory().
 CBackendStepFactory()
CBackendStepFactory::~CBackendStepFactory () [override], [default]
Destructor.
Referenced by CBackendStepFactory().
Member Function Documentation
CreateCBackendStep()
const DesignFlowStepRef CBackendStepFactory::CreateCBackendStep (const CBackend::Type c_backend_type, const std::string & file_name, const CBackendInformationConstRef c_backend_information) const
Create a backend c step.
Parameters
c_backend_type is the type of c backend to be created
file_name is the name of the file to be written
c_backend_information is the information about the frontend to be generated
Definition at line 68 of file c_backend_step_factory.cpp.
References application_manager, DesignFlowStepFactory::design_flow_manager, Wrefcount< T >::lock(), and DesignFlowStepFactory::parameters.
Referenced by CTestbenchExecution::ComputeRelationships(), and TestbenchValuesCGeneration::ComputeRelationships().
GetPrefix()
const std::string CBackendStepFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 63 of file c_backend_step_factory.cpp.
Field Documentation
application_manager
const application_managerConstRef CBackendStepFactory::application_manager [private]
Definition at line 70 of file c_backend_step_factory.hpp.
Referenced by CreateCBackendStep().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/c_backend_step_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/c_backend_step_factory.cpp