TestbenchMemoryAllocation Class Reference
#include <testbench_memory_allocation.hpp>
Public Member Functions
TestbenchMemoryAllocation (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
~TestbenchMemoryAllocation () override
Destructor.
DesignFlowStep_Status Exec () override
Executes the step.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the HLS relationships of this step.
Protected Member Functions
void AllocTestbenchMemory (void) const
Alloc the extra memory needed for the testbench input values.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Attributes
bool flag_cpp
True if the input code is c++.
Additional Inherited Members
Detailed Description
Definition at line 39 of file testbench_memory_allocation.hpp.
Constructor & Destructor Documentation
TestbenchMemoryAllocation()
TestbenchMemoryAllocation::TestbenchMemoryAllocation (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
. include
behavior include HLS include HLS/memory include HLS/simulation include STD include STL includes tree include utility include
Definition at line 79 of file testbench_memory_allocation.cpp.
References DesignFlowStep::debug_level, flag_cpp, refcount< T >::get(), GET_CLASS, DesignFlowStep::parameters, TESTBENCH_MEMORY_ALLOCATION, and ~TestbenchMemoryAllocation().
 TestbenchMemoryAllocation()
TestbenchMemoryAllocation::~TestbenchMemoryAllocation () [override], [default]
Destructor.
Referenced by TestbenchMemoryAllocation().
Member Function Documentation
AllocTestbenchMemory()
void TestbenchMemoryAllocation::AllocTestbenchMemory (void) const [protected]
Alloc the extra memory needed for the testbench input values.
check the next free aligned address
Definition at line 95 of file testbench_memory_allocation.cpp.
References tree_manager::CGetTreeNode(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, flag_cpp, tree_helper::get_array_data_bitsize(), GET_INDEX_NODE, tree_node::get_kind(), BehavioralHelper::get_parameters(), tree_manager::get_tree_node_const(), tree_helper::get_type_index(), HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, BehavioralHelper::is_a_pointer(), tree_helper::is_a_pointer(), BehavioralHelper::is_a_struct(), BehavioralHelper::is_an_array(), NODE_NOT_YET_SUPPORTED_EC, DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, TestbenchGenerationBaseStep::print_var_init(), BehavioralHelper::PrintVariable(), tree_helper::size(), SplitString(), STR, THROW_ASSERT, THROW_ERROR, and THROW_ERROR_CODE.
Referenced by Exec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > TestbenchMemoryAllocation::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [virtual]
Compute the HLS relationships of this step.
Reimplemented from HLS_step.
Definition at line 252 of file testbench_memory_allocation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TEST_VECTOR_PARSER, THROW_UNREACHABLE, and TOP_FUNCTION.
Exec()
DesignFlowStep_Status TestbenchMemoryAllocation::Exec () [override], [virtual]
Executes the step.
Implements DesignFlowStep.
Definition at line 89 of file testbench_memory_allocation.cpp.
References AllocTestbenchMemory(), and SUCCESS.
HasToBeExecuted()
bool TestbenchMemoryAllocation::HasToBeExecuted () const [override], [protected], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 276 of file testbench_memory_allocation.cpp.
Field Documentation
flag_cpp
bool TestbenchMemoryAllocation::flag_cpp [protected]
True if the input code is c++.
Definition at line 43 of file testbench_memory_allocation.hpp.
Referenced by AllocTestbenchMemory(), and TestbenchMemoryAllocation().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_memory_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_memory_allocation.cpp