/home/osboxes/bambu/PandA-bambu/src/HLS/memory/mem_xml_allocation.cpp File Reference
Parsing of memory allocation described in XML.
#include `mem_xml_allocation.hpp`
#include `hls_manager.hpp`
#include `hls_target.hpp`
#include `memory.hpp`
#include `memory_symbol.hpp`
#include `target_device.hpp`
#include `technology_manager.hpp`
#include `polixml.hpp`
#include `xml_dom_parser.hpp`
#include `xml_helper.hpp`
#include `Parameter.hpp`
#include `dbgPrintHelper.hpp`
#include `exceptions.hpp`
#include `fileIO.hpp`
Functions
unsigned int get_id (const std::string &var_string)
Detailed Description
Parsing of memory allocation described in XML.
Author
Christian Pilato pilato@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
get_id()
unsigned int get_id (const std::string & var_string)
Definition at line 157 of file mem_xml_allocation.cpp.
Referenced by cs_interface::add_parameter_port(), top_entity::add_ports(), conn_binding::add_to_SM(), RTLCharacterization::AnalyzeCell(), minimal_interface::build_wrapper(), conn_binding_cs::instantiate_suspension_component(), cs_interface::InternalExec(), TasteInterfaceGeneration::InternalExec(), fu_binding::manage_extern_global_port(), datapath_parallel_cs::manage_extern_global_port_parallel(), cs_interface::manage_extern_global_port_top(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), fu_binding::manage_memory_ports_chained(), fu_binding::manage_memory_ports_parallel_chained(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), mem_xml_allocation::parse_external_allocation(), mem_xml_allocation::parse_internal_allocation(), datapath_parallel_cs::resize_ctrl_parallel_ports(), cs_interface::resize_memory_ctrl_ports(), reg_binding_cs::specialise_reg(), reg_binding::specialise_reg(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_slave_initializations(), and structural_object::~structural_object().