field_decl Struct Reference
struct definition of the field_decl tree node.
#include <tree_node.hpp>
Public Types
enum {
GETID =(decl_node) = 0,
GETID =(decl_node) = 0,
GETID =(decl_node) = 0,
GETID =(decl_node) = 0,
GETID =(decl_node) = 0
 }
visitor enum
Public Member Functions
field_decl (unsigned int i)
constructor
long long int offset ()
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
tree_nodeRef init
init field holds the value to initialize a variable to.
tree_nodeRef size
size field holds the size of datum, in bits.
unsigned int algn
algn field holds the alignment required for the datum, in bits.
tree_nodeRef bpos
bpos field is the field position, counting in bytes, of the byte containing the bit closest to the beginning of the structure (tree-dump.c use the macro DECL_FIELD_OFFSET and the function bit_position)
tree_nodeRef smt_ann
symbol_memory_tag annotation
Additional Inherited Members
Detailed Description
struct definition of the field_decl tree node.
The tree walker structure of this node is: #(TOK_FIELD_DECL decl_node attr (init)? (size)? algn (bpos)?)
Definition at line 2646 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
GETID
GETID
GETID
GETID
Definition at line 2706 of file tree_node.hpp.
Constructor & Destructor Documentation
field_decl()
field_decl::field_decl (unsigned int i) [inline], [explicit]
constructor
Definition at line 2649 of file tree_node.hpp.
Member Function Documentation
offset()
long long int field_decl::offset ()
Compute the offset of this field in the struct or structure
Returns
the offset for this field
Definition at line 685 of file tree_node.cpp.
References tree_helper::get_integer_cst_value(), and GET_NODE.
Referenced by record_type::get_field().
visit()
void field_decl::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from attr.
Definition at line 695 of file tree_node.cpp.
References ALL_VISIT, gimple_call::visit(), VISIT_MEMBER, and VISIT_SC.
Field Documentation
algn
unsigned int field_decl::algn
algn field holds the alignment required for the datum, in bits.
(tree-dump.c use the macro DECL_ALIGN)
Definition at line 2672 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
bpos
tree_nodeRef field_decl::bpos
bpos field is the field position, counting in bytes, of the byte containing the bit closest to the beginning of the structure (tree-dump.c use the macro DECL_FIELD_OFFSET and the function bit_position)
Definition at line 2680 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
init
tree_nodeRef field_decl::init
init field holds the value to initialize a variable to.
(tree-dump.c use the macro DECL_INITIAL)
Definition at line 2660 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
size
tree_nodeRef field_decl::size
size field holds the size of datum, in bits.
(tree-dump.c use the macro DECL_SIZE)
Definition at line 2666 of file tree_node.hpp.
Referenced by BehavioralHelper::print_type_declaration(), and raw_writer::write_when_not_null_point_to().
smt_ann
tree_nodeRef field_decl::smt_ann
symbol_memory_tag annotation
Definition at line 2685 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp