/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/progModels/actor_graph_backend.cpp File Reference
#include `actor_graph_backend.hpp`
#include `Parameter.hpp`
#include `string_manipulation.hpp`
Functions
std::string ToString (ActorGraphBackend_Type actor_graph_backend_type)
Header include.
Function Documentation
ToString()
std::string ToString (ActorGraphBackend_Type actor_graph_backend_type)
Header include.
. includes
Definition at line 52 of file actor_graph_backend.cpp.
References BA_NONE, and THROW_UNREACHABLE.
Referenced by dead_code_elimination::add_gimple_nop(), IR_lowering::array_ref_lowering(), mux_connection_binding::create_connections(), ipa_point_to_analysis::Exec(), IR_lowering::expand_target_mem_ref(), memory_allocation::finalize_memory_allocation(), parm_decl_taken_address_fix::InternalExec(), FixStructsPassedByValue::InternalExec(), FunctionCallTypeCleanup::InternalExec(), BasicBlocksCfgComputation::InternalExec(), SwitchFix::InternalExec(), call_expr_fix::InternalExec(), compute_implicit_calls::InternalExec(), fanout_opt::InternalExec(), BuildVirtualPhi::InternalExec(), hls_div_cg_ext::InternalExec(), CSE::InternalExec(), IR_lowering::InternalExec(), PhiOpt::InternalExec(), rebuild_initialization2::look_for_ROMs(), Bit_Value_opt::optimize(), hls_div_cg_ext::recursive_examinate(), fu_binding::specialise_fu(), and tree_node::~tree_node().