AddOpLoopFlowEdges Class Reference
Class to perform adding of flow edges to operation graph.
#include <add_op_loop_flow_edges.hpp>
Public Member Functions
AddOpLoopFlowEdges (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~AddOpLoopFlowEdges () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the adding of flow edges to operation graphs.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Class to perform adding of flow edges to operation graph.
Definition at line 62 of file add_op_loop_flow_edges.hpp.
Constructor & Destructor Documentation
AddOpLoopFlowEdges()
AddOpLoopFlowEdges::AddOpLoopFlowEdges (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the node id of the function analyzed.
Algorithm include Behavior include Tree include Parameter include
Definition at line 68 of file add_op_loop_flow_edges.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~AddOpLoopFlowEdges().
 AddOpLoopFlowEdges()
AddOpLoopFlowEdges::~AddOpLoopFlowEdges () [override], [default]
Destructor.
Referenced by AddOpLoopFlowEdges().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > AddOpLoopFlowEdges::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 76 of file add_op_loop_flow_edges.cpp.
References AGGREGATE_DATA_FLOW_ANALYSIS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, OP_CONTROL_DEPENDENCE_COMPUTATION, OP_FEEDBACK_EDGES_IDENTIFICATION, OP_REACHABILITY_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SCALAR_SSA_DATA_FLOW_ANALYSIS, and THROW_UNREACHABLE.
Initialize()
void AddOpLoopFlowEdges::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 103 of file add_op_loop_flow_edges.cpp.
References FunctionFrontendFlowStep::bb_version, FunctionBehavior::FLG, FLG_SELECTOR, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status AddOpLoopFlowEdges::InternalExec () [override], [virtual]
Performs the adding of flow edges to operation graphs.
Returns
the exit status of this step
The control flow graph of operation
The graph used for the scheduling
The control flow graph of basic blocks
Operations of each loop
The loop structure
Adding edges from last operation of header to all operations of the loop
Operations which belong to the loop
Skip operation belonging to the header itself
Searching last operation of the header
add a flow edge from the last operation of the header and the operations of the loop useful only for the speculation graph
add a feedback flow edge from the operations of the loop to the first statement of the header
Implements FunctionFrontendFlowStep.
Definition at line 119 of file add_op_loop_flow_edges.cpp.
References BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB_FLG_SELECTOR, FunctionBehavior::FBB, FunctionBehavior::FCFG, FunctionBehavior::FFLSAODG, FunctionBehavior::FLG, FLG_SELECTOR, FunctionBehavior::FLSAODG, FunctionFrontendFlowStep::function_behavior, GET_NAME, IRREDUCIBLE_LOOPS_EC, DesignFlowStep::parameters, PRINT_DBG_MEX, SUCCESS, THROW_ASSERT, THROW_ERROR_CODE, and THROW_UNREACHABLE.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_op_loop_flow_edges.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_op_loop_flow_edges.cpp