IC_device Class Reference
#include <IC_device.hpp>
Public Member Functions
IC_device (const ParameterConstRef Param, const technology_managerRef TM)
Constructor of the class.
~IC_device () override
Destructor of the class.
void load_devices (const target_deviceRef device) override
Load all data specific for a given technology.
virtual void set_dimension (double area)
Set the proper dimension for the target device.
void xwrite (xml_element *node) override
Method to write an XML node.
Protected Member Functions
void initialize () override
Initialize the target device based on the given parameters.
Additional Inherited Members
Detailed Description
Definition at line 49 of file IC_device.hpp.
Constructor & Destructor Documentation
IC_device()
IC_device::IC_device (const ParameterConstRef _Param, const technology_managerRef _TM)
Constructor of the class.
technology includes
Parameters
Param is the reference to the class that contains all the parameters
design includes XML includes parameters' includes boost includes for file manipulations
Definition at line 63 of file IC_device.cpp.
References target_device::core_height, target_device::core_width, target_device::debug_level, GET_CLASS, target_device::has_parameter(), initialize(), target_device::Param, and ~IC_device().
 IC_device()
IC_device::~IC_device () [override], [default]
Destructor of the class.
Referenced by IC_device().
Member Function Documentation
initialize()
void IC_device::initialize () [override], [protected], [virtual]
Initialize the target device based on the given parameters.
Implements target_device.
Definition at line 123 of file IC_device.cpp.
References target_device::has_parameter(), OUTPUT_LEVEL_VERBOSE, target_device::Param, target_device::parameters, and PRINT_OUT_MEX.
Referenced by IC_device().
load_devices()
void IC_device::load_devices (const target_deviceRef device) [override], [virtual]
Load all data specific for a given technology.
Load default resources
creating the data structure representing the target technology
update with specified device information
Implements target_device.
Definition at line 133 of file IC_device.cpp.
References target_technology::create_technology(), XMLDomParser::Exec(), XMLDomParser::get_document(), OUTPUT_LEVEL_MINIMUM, target_device::Param, test_panda::parser, PRINT_OUT_MEX, target_device::target, THROW_ERROR, and target_device::xload().
set_dimension()
void IC_device::set_dimension (double area) [virtual]
Set the proper dimension for the target device.
Definition at line 86 of file IC_device.cpp.
References target_device::core_height, target_device::core_width, target_technology::get_parameter(), target_device::target, and THROW_ASSERT.
xwrite()
void IC_device::xwrite (xml_element * node) [override], [virtual]
Method to write an XML node.
Parameters
node is the node for writing the information
Implements target_device.
Definition at line 75 of file IC_device.cpp.
References xml_child::add_child_element(), target_device::parameters, and WRITE_XNVM2.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/target_device/IC/IC_device.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/target_device/IC/IC_device.cpp