CTestbenchExecution Class Reference
#include <CTestbenchExecution.hpp>
Public Member Functions
CTestbenchExecution (const ParameterConstRef Param, const HLS_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const std::string &testbench_basename=`values`)
constructor
void ComputeRelationships (DesignFlowStepSet &design_flow_step_set, const DesignFlowStep::RelationshipType relationship_type)
Compute the relationships of a step with other steps.
virtual DesignFlowStep_Status Exec ()
Execute the step.
virtual bool HasToBeExecuted () const
Check if this step has actually to be executed.
Protected Member Functions
virtual const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
Protected Attributes
const std::string output_directory
const std::string testbench_basename
Additional Inherited Members
Detailed Description
Definition at line 56 of file CTestbenchExecution.hpp.
Constructor & Destructor Documentation
CTestbenchExecution()
CTestbenchExecution::CTestbenchExecution (const ParameterConstRef Param, const HLS_managerRef AppM, const DesignFlowManagerConstRef _design_flow_manager, const std::string & _testbench_basename = `values`)
constructor
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Marco Minutoli mminutoli@gmail.com
Manuel Beniani manuel.beniani@gmail.com
Christian Pilato pilato@elet.polimi.it
Pietro Fezzardi pietrofezzardi@gmail.comSTD include STL includes
Definition at line 101 of file CTestbenchExecution.cpp.
References C_TESTBENCH_EXECUTION, DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > CTestbenchExecution::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 107 of file CTestbenchExecution.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TEST_VECTOR_PARSER, TESTBENCH_MEMORY_ALLOCATION, THROW_UNREACHABLE, and TOP_FUNCTION.
ComputeRelationships()
void CTestbenchExecution::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
check if __builtin_memcpy has to be synthesized
FIXME: temporary deactivated
Managed in HLSFunctionStep::ComputeRelationships
Root function cannot be computed at the beginning
Reimplemented from HLS_step.
Definition at line 374 of file CTestbenchExecution.cpp.
References HLS_step::ComputeRelationships(), ApplicationFrontendFlowStep::ComputeSignature(), CBackend::ComputeSignature(), FrontendFlowStepFactory::CreateApplicationFrontendFlowStep(), CBackendStepFactory::CreateCBackendStep(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, FUNCTION_ANALYSIS, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), output_directory, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, testbench_basename, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status CTestbenchExecution::Exec () [virtual]
Execute the step.
Returns
the exit status of this step
Nothing to do
Implements DesignFlowStep.
Definition at line 136 of file CTestbenchExecution.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_MINIMUM, HLS_step::HLSMgr, INDENT_DBG_MEX, IsError(), O0, output_directory, PandaSystem(), DesignFlowStep::parameters, SUCCESS, testbench_basename, THROW_ASSERT, and THROW_ERROR.
HasToBeExecuted()
bool CTestbenchExecution::HasToBeExecuted () const [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 369 of file CTestbenchExecution.cpp.
Field Documentation
output_directory
const std::string CTestbenchExecution::output_directory [protected]
Definition at line 59 of file CTestbenchExecution.hpp.
Referenced by ComputeRelationships(), and Exec().
testbench_basename
const std::string CTestbenchExecution::testbench_basename [protected]
Definition at line 61 of file CTestbenchExecution.hpp.
Referenced by ComputeRelationships(), and Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/CTestbenchExecution.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/CTestbenchExecution.cpp