HWDiscrepancyAnalysis Class Reference
#include <HWDiscrepancyAnalysis.hpp>
Public Member Functions
HWDiscrepancyAnalysis (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
DesignFlowStep_Status Exec ()
Execute the step.
bool HasToBeExecuted () const
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
Protected Attributes
const DiscrepancyRef Discr
const std::string present_state_name
Additional Inherited Members
Detailed Description
Definition at line 48 of file HWDiscrepancyAnalysis.hpp.
Constructor & Destructor Documentation
HWDiscrepancyAnalysis()
HWDiscrepancyAnalysis::HWDiscrepancyAnalysis (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Definition at line 96 of file HWDiscrepancyAnalysis.cpp.
References DesignFlowStep::debug_level, GET_CLASS, HW_DISCREPANCY_ANALYSIS, DesignFlowStep::parameters, and VERILOG.
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > HWDiscrepancyAnalysis::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 104 of file HWDiscrepancyAnalysis.cpp.
References C_TESTBENCH_EXECUTION, CALL_GRAPH_UNFOLDING, DesignFlowStep::DEPENDENCE_RELATIONSHIP, HW_PATH_COMPUTATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and TOP_FUNCTION.
Exec()
DesignFlowStep_Status HWDiscrepancyAnalysis::Exec () [virtual]
Execute the step.
Returns
the exit status of this step
adjust in case states are not consecutive
Implements DesignFlowStep.
Definition at line 130 of file HWDiscrepancyAnalysis.cpp.
References BB_ENTRY, language_writer::bitnumber(), component_o_K, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, Discr, structural_object::find_member(), FIXED_METADATA_SIZE, structural_object::get_id(), structural_object::get_path(), GET_TYPE_NAME, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, max(), MAX_METADATA_BITSIZE, min, tree_helper::name_function(), NULL_VERTEX, NumberToBinaryString(), DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, DesignFlowStep::parameters, parse_discrepancy(), STR, SUCCESS, THROW_ASSERT, and THROW_ERROR.
HasToBeExecuted()
bool HWDiscrepancyAnalysis::HasToBeExecuted () const [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 732 of file HWDiscrepancyAnalysis.cpp.
Field Documentation
Discr
const DiscrepancyRef HWDiscrepancyAnalysis::Discr [protected]
Definition at line 61 of file HWDiscrepancyAnalysis.hpp.
Referenced by Exec().
present_state_name
const std::string HWDiscrepancyAnalysis::present_state_name [protected]
Definition at line 63 of file HWDiscrepancyAnalysis.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/HWDiscrepancyAnalysis.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/HWDiscrepancyAnalysis.cpp