Translator::LatexColumnFormat Class Reference
Class describing the characteristic of a column of latex table.
Public Types
enum TextFormat
Text format.
enum ComparisonOperator
Comparison operator.
enum TotalFormat
Total format.
Public Member Functions
LatexColumnFormat ()
Constructor.
Static Public Member Functions
static TextFormat get_TF (const std::string &string)
Given a string return the corresponding enum.
static ComparisonOperator get_CO (const std::string &string)
Given a string return the corresponding enum.
static TotalFormat GetTotalFormat (const std::string &string)
Given a string return the corresponding enum.
static bool Compare (const long double A, const ComparisonOperator comparator, const long double B)
Return A operator B.
Data Fields
std::string column_name
The name of the column.
std::vector< std::string > columns_prefix
The prefix of the columns.
std::string source_name
The xml name of this column.
std::string column_alignment
The alignment of the column.
TextFormat text_format
The text format of the column.
std::streamsize precision
The precision of the number.
CustomUnorderedSet< std::string > compared_columns
The columns with which this has to be compared.
ComparisonOperator comparison_operator
The operator of the comparison.
TotalFormat total_format
The format of the total of this column.
Static Private Attributes
static CustomUnorderedMap< std::string, TextFormat > string_to_TF
Map string->enum for text format.
static CustomUnorderedMap< std::string, ComparisonOperator > string_to_CO
Map string->enum for comparison operator.
static CustomUnorderedMap< std::string, TotalFormat > string_to_TOF
Map string->enum for total format.
Detailed Description
Class describing the characteristic of a column of latex table.
Definition at line 101 of file translator.hpp.
Member Enumeration Documentation
ComparisonOperator
enum Translator::LatexColumnFormat::ComparisonOperator
Comparison operator.
Definition at line 111 of file translator.hpp.
TextFormat
enum Translator::LatexColumnFormat::TextFormat
Text format.
Definition at line 105 of file translator.hpp.
TotalFormat
enum Translator::LatexColumnFormat::TotalFormat
Total format.
Definition at line 117 of file translator.hpp.
Constructor & Destructor Documentation
LatexColumnFormat()
Translator::LatexColumnFormat::LatexColumnFormat ()
Constructor.
Definition at line 127 of file translator.cpp.
References BOOST_PP_SEQ_FOR_EACH, CO_NAME, COMPARISON_OPERATOR, string_to_CO, string_to_TF, string_to_TOF, TEXT_FORMAT, TF_NAME, THROW_ASSERT, TOF_NAME, and TOTAL_FORMAT.
Member Function Documentation
Compare()
bool Translator::LatexColumnFormat::Compare (const long double A, const ComparisonOperator comparator, const long double B) [static]
Return A operator B.
Parameters
A is the first operand
comparator is the operator to be applied
B is the second operand
Returns
true if A operator B
Definition at line 174 of file translator.cpp.
References STR, and THROW_UNREACHABLE.
Referenced by Translator::write_to_latex().
get_CO()
static ComparisonOperator Translator::LatexColumnFormat::get_CO (const std::string & string) [static]
Given a string return the corresponding enum.
Parameters
string is the string to be analyzed
Referenced by Translator::read_column_formats().
get_TF()
static TextFormat Translator::LatexColumnFormat::get_TF (const std::string & string) [static]
Given a string return the corresponding enum.
Parameters
string is the string to be analyzed
Referenced by Translator::read_column_formats().
GetTotalFormat()
static TotalFormat Translator::LatexColumnFormat::GetTotalFormat (const std::string & string) [static]
Given a string return the corresponding enum.
Parameters
string is the string to be analyzed
Referenced by Translator::read_column_formats().
Field Documentation
column_alignment
std::string Translator::LatexColumnFormat::column_alignment
The alignment of the column.
Definition at line 143 of file translator.hpp.
column_name
std::string Translator::LatexColumnFormat::column_name
The name of the column.
Definition at line 134 of file translator.hpp.
Referenced by Translator::read_column_formats().
columns_prefix
std::vector<std::string> Translator::LatexColumnFormat::columns_prefix
The prefix of the columns.
Definition at line 137 of file translator.hpp.
compared_columns
CustomUnorderedSet<std::string> Translator::LatexColumnFormat::compared_columns
The columns with which this has to be compared.
Definition at line 152 of file translator.hpp.
comparison_operator
ComparisonOperator Translator::LatexColumnFormat::comparison_operator
The operator of the comparison.
Definition at line 155 of file translator.hpp.
precision
std::streamsize Translator::LatexColumnFormat::precision
The precision of the number.
Definition at line 149 of file translator.hpp.
source_name
std::string Translator::LatexColumnFormat::source_name
The xml name of this column.
Definition at line 140 of file translator.hpp.
string_to_CO
CustomUnorderedMap< std::string, Translator::LatexColumnFormat::ComparisonOperator > Translator::LatexColumnFormat::string_to_CO [static], [private]
Map string->enum for comparison operator.
Definition at line 127 of file translator.hpp.
Referenced by LatexColumnFormat().
string_to_TF
CustomUnorderedMap< std::string, Translator::LatexColumnFormat::TextFormat > Translator::LatexColumnFormat::string_to_TF [static], [private]
Map string->enum for text format.
Definition at line 124 of file translator.hpp.
Referenced by LatexColumnFormat().
string_to_TOF
CustomUnorderedMap< std::string, Translator::LatexColumnFormat::TotalFormat > Translator::LatexColumnFormat::string_to_TOF [static], [private]
Map string->enum for total format.
Definition at line 130 of file translator.hpp.
Referenced by LatexColumnFormat().
text_format
TextFormat Translator::LatexColumnFormat::text_format
The text format of the column.
Definition at line 146 of file translator.hpp.
total_format
TotalFormat Translator::LatexColumnFormat::total_format
The format of the total of this column.
Definition at line 158 of file translator.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/translator.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/translator.cpp