tree_manipulation Class Reference
This class creates a layer to add nodes and to manipulate the tree_nodes manager.
#include <tree_manipulation.hpp>
Public Member Functions
tree_manipulation (const tree_managerRef &TreeM, const ParameterConstRef &parameters)
This is the constructor of the tree_manipulation.
tree_manipulation (const tree_managerRef &TreeM, const ParameterConstRef &parameters, bool _reuse)
~tree_manipulation ()
This is the destructor of the tree_manipulation.
tree_nodeRef create_unary_operation (const tree_nodeRef &type, const tree_nodeRef &op, const std::string &srcp, enum kind operation_kind) const
EXPRESSION_TREE_NODES.
tree_nodeRef create_binary_operation (const tree_nodeRef &type, const tree_nodeRef &op0, const tree_nodeRef &op1, const std::string &srcp, enum kind operation_kind) const
Function used to create a binary expression.
tree_nodeRef create_ternary_operation (const tree_nodeRef &type, const tree_nodeRef &op0, const tree_nodeRef &op1, const tree_nodeRef &op2, const std::string &srcp, enum kind operation_kind) const
Function used to create a ternary expression.
tree_nodeRef create_quaternary_operation (const tree_nodeRef &type, const tree_nodeRef &op0, const tree_nodeRef &op1, const tree_nodeRef &op2, const tree_nodeRef &op3, const std::string &srcp, enum kind operation_kind) const
Function used to create a quaternary expression.
tree_nodeRef create_lut_expr (const tree_nodeRef &type, const tree_nodeRef &op0, const tree_nodeRef &op1, const tree_nodeRef &op2, const tree_nodeRef &op3, const tree_nodeRef &op4, const tree_nodeRef &op5, const tree_nodeRef &op6, const tree_nodeRef &op7, const tree_nodeRef &op8, const std::string &srcp) const
create_lut_expr: function used to create a generic lut_expr operation
tree_nodeRef create_extract_bit_expr (const tree_nodeRef &op0, const tree_nodeRef &op1, const std::string &srcp) const
tree_nodeRef CreateIntegerCst (const tree_nodeConstRef &type, const long long int value, const unsigned int integer_cst_nid) const
CONST_OBJ_TREE_NODES.
tree_nodeRef CreateRealCst (const tree_nodeConstRef &type, const long double value, const unsigned int real_cst_nid) const
Function used to create a real_cst node.
tree_nodeRef create_identifier_node (const std::string &strg) const
IDENTIFIER_TREE_NODE.
tree_nodeRef create_parm_decl (const tree_nodeRef &name, const tree_nodeRef &type, const tree_nodeRef &scpe, const tree_nodeRef &size, const tree_nodeRef &argt, const tree_nodeRef &smt_ann, const tree_nodeRef &init, const std::string &srcp, unsigned int algn, int used, bool register_flag=false, bool readonly_flag=false) const
DECL_NODES.
tree_nodeRef create_translation_unit_decl () const
create or find a global scope
tree_nodeRef create_result_decl (const tree_nodeRef &name, const tree_nodeRef &type, const tree_nodeRef &scpe, const tree_nodeRef &size, const tree_nodeRef &smt_ann, const tree_nodeRef &init, const std::string &srcp, unsigned int algn, bool artificial_flag=false) const
Function used to create a result_decl.
tree_nodeRef create_var_decl (const tree_nodeRef &name, const tree_nodeConstRef &type, const tree_nodeRef &scpe, const tree_nodeRef &size, const tree_nodeRef &smt_ann, const tree_nodeRef &init, const std::string &srcp, unsigned int algn, int used, bool artificial_flag=false, int use_tmpl=-1, bool static_static_flag=false, bool extern_flag=false, bool static_flag=false, bool register_flag=false, bool readonly_flag=false, const std::string &bit_values=``, bool addr_taken=false, bool addr_not_taken=false) const
Function used to create a var_decl.
tree_nodeRef create_void_type () const
TYPE_OBJ.
tree_nodeRef create_boolean_type () const
Function that creates a boolean type if it is not already present, otherwise it returns the one that is already in the tree manager.
tree_nodeRef create_default_integer_type () const
Function that creates a integer type if it is not already present, otherwise it returns the one that is already in the tree manager.
tree_nodeRef create_default_unsigned_integer_type () const
Function that creates a unsigned integer type if it is not already present, otherwise it returns the one that is already in the tree manager.
tree_nodeRef CreateDefaultUnsignedLongLongInt () const
Function that creates a long long unsigned int type if it is not already present, otherwise return the existing type.
tree_nodeRef create_bit_size_type () const
Function that creates a bit_size type if it is not already present, otherwise it returns the one that is already in the tree manager.
tree_nodeRef create_size_type () const
create a sizetype builtin type in case it has not already been created, otherwise it returns the one found in the tree manager.
tree_nodeRef create_pointer_type (const tree_nodeConstRef &ptd, unsigned int algn) const
Function that creates a pointer type if it is not already present, otherwise it returns the one that is already in the tree manager.
tree_nodeRef create_integer_type_with_prec (unsigned int prec, bool unsigned_p) const
create an integer type starting from a given prec
tree_nodeRef create_ssa_name (const tree_nodeConstRef &var, const tree_nodeConstRef &type, const tree_nodeConstRef &min, const tree_nodeConstRef &max, bool volatile_flag=false, bool virtual_flag=false) const
MISCELLANEOUS_OBJ_TREE_NODES.
tree_nodeRef create_phi_node (tree_nodeRef &ssa_res, const std::vector< std::pair< tree_nodeRef, unsigned int >> &list_of_def_edge, const tree_nodeRef &scpe, unsigned int bb_index, bool virtual_flag=false) const
GIMPLE_PHI.
tree_nodeRef create_gimple_modify_stmt (const tree_nodeRef &op0, const tree_nodeRef &op1, const std::string &srcp, const unsigned int bb_index) const
GIMPLE_ASSIGN.
tree_nodeRef CreateGimpleAssign (const tree_nodeRef &type, const tree_nodeConstRef &min, const tree_nodeConstRef &max, const tree_nodeRef &op, unsigned int bb_index, const std::string &srcp) const
Create gimple assignment.
tree_nodeRef create_gimple_call (const tree_nodeConstRef &called_function, const std::vector< tree_nodeRef > &args, const std::string &srcp, const unsigned int bb_index) const
GIMPLE_CALL.
tree_nodeRef create_gimple_cond (const tree_nodeRef &expr, const std::string &srcp, unsigned int bb_index) const
GIMPLE_COND.
tree_nodeRef create_gimple_return (const tree_nodeRef &type, const tree_nodeRef &expr, const std::string &srcp, unsigned int bb_index) const
GIMPLE_RETURN.
void create_label (const blocRef &block, unsigned int function_decl_nid) const
create a label expression in a header of a loop.
void create_goto (const blocRef &block, unsigned int function_decl_nid, unsigned int label_expr_nid) const
create a goto expression.
tree_nodeRef create_function_decl (const std::string &function_name, const tree_nodeRef &scpe, const std::vector< tree_nodeRef > &argsT, const tree_nodeRef &returnType, const std::string &srcp, bool with_body) const
create the declaration of a function without its body
blocRef create_basic_block (std::map< unsigned int, blocRef > &list_of_bloc, std::vector< unsigned int > predecessors, std::vector< unsigned int > successors, std::vector< tree_nodeRef > stmt, unsigned int number, unsigned int true_edge=0, unsigned int false_edge=0, std::vector< tree_nodeRef > phi=std::vector< tree_nodeRef >()) const
BASIC BLOCK.
void bb_add_stmts (blocRef &bb, const std::vector< tree_nodeRef > &stmt) const
Function that adds in basic block bb the statements listed in vector stmt.
void bb_add_stmt (blocRef &bb, const tree_nodeRef &stmt) const
Function that adds in basic block bb the statement stmt.
void bb_add_successors (blocRef &bb, const std::vector< unsigned int > &successors) const
Function that adds a list of successors in basic block bb.
void bb_add_successor (blocRef &bb, const unsigned int &successor) const
Function that adds a successor in basic block bb.
void bb_add_predecessors (blocRef &bb, const std::vector< unsigned int > &predecessors) const
Function that adds a list of predecessors in basic block bb.
void bb_add_predecessor (blocRef &bb, const unsigned int &predecessor) const
Function that adds a predecessor in basic block bb.
void bb_remove_successors (blocRef &bb, const std::vector< unsigned int > &successors) const
Function that removes a list of successors in basic block bb.
void bb_remove_successor (blocRef &bb, const unsigned int &successor) const
Function that removes a successor in basic block bb.
void bb_remove_predecessors (blocRef &bb, const std::vector< unsigned int > &predecessors) const
Function that removes a list of predecessors in basic block bb.
void bb_remove_predecessor (blocRef &bb, const unsigned int &predecessor) const
Function that removes a predecessor in basic block bb.
void bb_remove_all_predecessors (blocRef &bb) const
Function that removes all the predecessors of basic block bb.
void bb_remove_all_successors (blocRef &bb) const
Function that removes all the successors of basic block bb.
void bb_set_false_edge (blocRef &bb, const unsigned int &false_edge_index) const
Function that sets in basic block bb the index of the then basic block in case the last statement is a gimple_cond.
void bb_set_true_edge (blocRef &bb, const unsigned int &true_edge_index) const
Function that sets in basic block bb the index of the if basic block in case the last statement is a gimple_cond.
tree_nodeRef CreateNotExpr (const tree_nodeConstRef &condition, const blocRef &block) const
UTILITY.
tree_nodeRef CreateAndExpr (const tree_nodeConstRef &first_condition, const tree_nodeConstRef &second_condition, const blocRef &block) const
Create an or expression.
tree_nodeRef CreateOrExpr (const tree_nodeConstRef &first_condition, const tree_nodeConstRef &second_condition, const blocRef &block) const
Create an or expression.
tree_nodeRef ExtractCondition (const tree_nodeRef &gc, const blocRef &block) const
Extract computation of condition from a gimple_cond.
tree_nodeRef CreateNopExpr (const tree_nodeConstRef &operand, const tree_nodeConstRef &type, const tree_nodeConstRef &min, const tree_nodeConstRef &max) const
Create a nop_expr to perform a conversion.
tree_nodeRef CreateUnsigned (const tree_nodeConstRef &signed_type) const
Create an unsigned integer type starting from signed type.
tree_nodeRef CreateEqExpr (const tree_nodeConstRef &first_operand, const tree_nodeConstRef &second_operand, const blocRef &block) const
Create an eq_expr.
tree_nodeRef CreateCallExpr (const tree_nodeConstRef &called_function, const std::vector< tree_nodeRef > &args, const std::string &srcp) const
Create a call_expr.
tree_nodeRef CreateAddrExpr (const tree_nodeConstRef &tn, const std::string &srcp) const
Create an addr_expr.
tree_nodeRef CreateGimpleAssignAddrExpr (const tree_nodeConstRef &tn, const unsigned int bb_index, const std::string &srcp) const
Create a gimple_assign with op0 a new ssa_name, and op1 an addr_expr which takes the address of the tree node tn.
tree_nodeRef CreateVectorBooleanType (const unsigned int number_of_elements) const
Create a vector bool type.
Private Attributes
tree_managerRef TreeM
Tree Manager.
const bool reuse
True if statements can be reused.
const ParameterConstRef parameters
The set of input parameters.
const int debug_level
debug level.
Static Private Attributes
static unsigned int goto_label_unique_id = 0
store a unique id used during the creation of the label_decl associated with a gimple_goto.
Detailed Description
This class creates a layer to add nodes and to manipulate the tree_nodes manager.
Definition at line 108 of file tree_manipulation.hpp.
Constructor & Destructor Documentation
tree_manipulation() [1/2]
tree_manipulation::tree_manipulation (const tree_managerRef & TreeM, const ParameterConstRef & parameters)
This is the constructor of the tree_manipulation.
Constructor.
Parameters
TreeM is the tree manager.
parameters is the set of input parameters
Definition at line 79 of file tree_manipulation.cpp.
tree_manipulation() [2/2]
tree_manipulation::tree_manipulation (const tree_managerRef & TreeM, const ParameterConstRef & parameters, bool _reuse)
Definition at line 83 of file tree_manipulation.cpp.
References ~tree_manipulation().
 tree_manipulation()
tree_manipulation::~tree_manipulation () [default]
This is the destructor of the tree_manipulation.
Destructor.
Referenced by tree_manipulation().
Member Function Documentation
bb_add_predecessor()
void tree_manipulation::bb_add_predecessor (blocRef & bb, const unsigned int & predecessor) const
Function that adds a predecessor in basic block bb.
Add a predecessor in basic block bb.
Parameters
bb is the basic block.
predecessor is the predecessor.
Definition at line 1770 of file tree_manipulation.cpp.
Referenced by bb_add_predecessors().
bb_add_predecessors()
void tree_manipulation::bb_add_predecessors (blocRef & bb, const std::vector< unsigned int > & predecessors) const
Function that adds a list of predecessors in basic block bb.
Add a list of predecessors in basic block bb.
Parameters
bb is the basic block.
predecessors is the vector of predecessors.
Definition at line 1761 of file tree_manipulation.cpp.
References bb_add_predecessor().
bb_add_stmt()
void tree_manipulation::bb_add_stmt (blocRef & bb, const tree_nodeRef & stmt) const
Function that adds in basic block bb the statement stmt.
Add a statement in basic block.
Parameters
bb is the basic block.
stmt is the statement.
Insert the list of statement
Definition at line 1738 of file tree_manipulation.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, PRINT_DBG_MEX, and STR.
Referenced by bb_add_stmts().
bb_add_stmts()
void tree_manipulation::bb_add_stmts (blocRef & bb, const std::vector< tree_nodeRef > & stmt) const
Function that adds in basic block bb the statements listed in vector stmt.
Add a list of statement in basic block bb.
Parameters
bb is the basic block.
stmt is the vector of statements.
Insert the list of statement
Definition at line 1728 of file tree_manipulation.cpp.
References bb_add_stmt().
bb_add_successor()
void tree_manipulation::bb_add_successor (blocRef & bb, const unsigned int & successor) const
Function that adds a successor in basic block bb.
Add a successor in basic block bb.
Parameters
bb is the basic block.
successor is the successor.
Definition at line 1755 of file tree_manipulation.cpp.
Referenced by bb_add_successors().
bb_add_successors()
void tree_manipulation::bb_add_successors (blocRef & bb, const std::vector< unsigned int > & successors) const
Function that adds a list of successors in basic block bb.
Add a list of successors in basic block bb.
Parameters
bb is the basic block.
successors is the vector of successors.
Definition at line 1746 of file tree_manipulation.cpp.
References bb_add_successor().
bb_remove_all_predecessors()
void tree_manipulation::bb_remove_all_predecessors (blocRef & bb) const
Function that removes all the predecessors of basic block bb.
Remove all the predecessors from basic block bb.
Parameters
bb is the basic block.
Definition at line 1814 of file tree_manipulation.cpp.
bb_remove_all_successors()
void tree_manipulation::bb_remove_all_successors (blocRef & bb) const
Function that removes all the successors of basic block bb.
Remove all the successors from basic block bb.
Parameters
bb is the basic block.
Definition at line 1820 of file tree_manipulation.cpp.
bb_remove_predecessor()
void tree_manipulation::bb_remove_predecessor (blocRef & bb, const unsigned int & predecessor) const
Function that removes a predecessor in basic block bb.
Remove a predecessors in basic block bb.
Parameters
bb is the basic block.
predecessor is the predecessor.
Definition at line 1804 of file tree_manipulation.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, PRINT_DBG_MEX, STR, and THROW_ASSERT.
Referenced by bb_remove_predecessors().
bb_remove_predecessors()
void tree_manipulation::bb_remove_predecessors (blocRef & bb, const std::vector< unsigned int > & predecessors) const
Function that removes a list of predecessors in basic block bb.
Remove a list of predecessors in basic block bb.
Parameters
bb is the basic block.
predecessors is the vector of predecessors.
Definition at line 1795 of file tree_manipulation.cpp.
References bb_remove_predecessor().
bb_remove_successor()
void tree_manipulation::bb_remove_successor (blocRef & bb, const unsigned int & successor) const
Function that removes a successor in basic block bb.
Remove a successor from basic block bb.
Parameters
bb is the basic block.
successor is the successor.
Definition at line 1785 of file tree_manipulation.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, PRINT_DBG_MEX, STR, and THROW_ASSERT.
Referenced by bb_remove_successors().
bb_remove_successors()
void tree_manipulation::bb_remove_successors (blocRef & bb, const std::vector< unsigned int > & successors) const
Function that removes a list of successors in basic block bb.
Remove a list of successors from basic block bb.
Parameters
bb is the basic block.
successors is the vector of successors.
Definition at line 1776 of file tree_manipulation.cpp.
References bb_remove_successor().
bb_set_false_edge()
void tree_manipulation::bb_set_false_edge (blocRef & bb, const unsigned int & false_edge_index) const
Function that sets in basic block bb the index of the then basic block in case the last statement is a gimple_cond.
Set the false edge of basic block bb.
Parameters
bb is the basic block.
false_edge_index is the index of the then basic block.
Definition at line 1826 of file tree_manipulation.cpp.
bb_set_true_edge()
void tree_manipulation::bb_set_true_edge (blocRef & bb, const unsigned int & true_edge_index) const
Function that sets in basic block bb the index of the if basic block in case the last statement is a gimple_cond.
Set the true edge of basic block bb.
Parameters
bb is the basic block.
true_edge_index is the index of the if basic block.
Definition at line 1832 of file tree_manipulation.cpp.
create_basic_block()
blocRef tree_manipulation::create_basic_block (std::map< unsigned int, blocRef > & list_of_bloc, std::vector< unsigned int > predecessors, std::vector< unsigned int > successors, std::vector< tree_nodeRef > stmt, unsigned int number, unsigned int true_edge = 0, unsigned int false_edge = 0, std::vector< tree_nodeRef > phi = std::vector<tree_nodeRef>()) const
BASIC BLOCK.
BASIC_BLOCK.
Function used to create a new basic block.
Parameters
list_of_bloc is the list of basic blocks.
predecessors is the list of predecessors of the basic block to be created (indexes of the blocks).
successors is the list of successors of the basic block to be created (indexes of the blocks).
stmt is the list of the stmt node to be inserted in the basic block (tree_reindex nodes).
number is the new basic block number
true_edge is the index of the basic block it goes if there is a jump expression and the condition is satisfied (default=0).
false_edge is the index of the basic block it goes if there is a jump expression and the condition is not satisfied (default=0).
phi is the list of the gimple_phi to be inserted (default empty).
Returns
basic block created.
Create a basic block Create new basic block
Set the true_edge
Set the false_edge
Insert the list of predecessors
Insert the list of successors
Insert the list of statement
Insert the list of phi node
Definition at line 1682 of file tree_manipulation.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, PRINT_DBG_MEX, and STR.
create_binary_operation()
tree_nodeRef tree_manipulation::create_binary_operation (const tree_nodeRef & type, const tree_nodeRef & op0, const tree_nodeRef & op1, const std::string & srcp, enum kind operation_kind) const
Function used to create a binary expression.
TODO weight_node to fix in tree_node_factory.cpp Create a binary expression.
Parameters
type is the type of the expression (tree_reindex).
op0 is the first operand of the binary expression (tree_reindex).
op1 is the second operand of the binary expression (tree_reindex).
srcp is the definition of the source position.
operation_kind is the kind of binary expression to create (bit_and_expr_K, plus_expr_K,...).
Returns
the tree_reindex node of the operation created.
Check if the tree_node given are tree_reindex
Check if the tree_node type is a binary expression
Check if it is a correct node type
Definition at line 215 of file tree_manipulation.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, THROW_ERROR, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by IR_lowering::array_ref_lowering(), IR_lowering::division_by_a_constant(), IR_lowering::expand_MC(), IR_lowering::expand_mult_const(), IR_lowering::expand_mult_highpart(), IR_lowering::expand_sdiv_pow2(), IR_lowering::expand_smod_pow2(), IR_lowering::expand_target_mem_ref(), parm_decl_taken_address_fix::InternalExec(), UnComparisonLowering::InternalExec(), IR_lowering::InternalExec(), and Bit_Value_opt::optimize().
create_bit_size_type()
tree_nodeRef tree_manipulation::create_bit_size_type () const
Function that creates a bit_size type if it is not already present, otherwise it returns the one that is already in the tree manager.
Create a bit_size type.
Returns
the tree_reindex node of the bit_size type.
@32 identifier_node strg: `bitsizetype` lngt: 13 @18 integer_type name: @32 size: @33 algn: 64 prec: 64 unsigned min : @34 max : @35 @33 integer_cst type: @18 low : 64 @34 integer_cst type: @18 low : 0 @35 integer_cst type: @18 low : -1
@32 identifier_node strg: `bitsizetype` lngt: 13
@18 integer_type name: @32 size: @33 algn: 64 prec: 64 unsigned min : @34 max : @35
@32
not_found decl
@18 integer_type name: @32 size: @33 algn: 64 prec: 64 unsigned min : @34 max : @35
@33 integer_cst type: @18 low : 64
@34 integer_cst type: @18 low : 0
@35 integer_cst type: @18 low : -1
Definition at line 975 of file tree_manipulation.cpp.
References ALGN_BIT_SIZE, create_identifier_node(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), MAX_VALUE_BIT_SIZE, MIN_VALUE_BIT_SIZE, tree_manager::new_tree_node_id(), PREC_BIT_SIZE, PRINT_DBG_MEX, SIZE_VALUE_BIT_SIZE, STR, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_NAME, TOK_PREC, TOK_SIZE, TOK_UNSIGNED, and TreeM.
Referenced by create_boolean_type(), create_default_integer_type(), create_default_unsigned_integer_type(), create_function_decl(), create_pointer_type(), interface_infer::create_Read_function(), interface_infer::create_Write_function(), and CreateDefaultUnsignedLongLongInt().
create_boolean_type()
tree_nodeRef tree_manipulation::create_boolean_type () const
Function that creates a boolean type if it is not already present, otherwise it returns the one that is already in the tree manager.
Create a boolean type.
Returns
the tree_reindex node of the boolean type.
@48 boolean_type name: @55 size: @7 algn: 8 @55 type_decl name: @58 type: @48 srcp: `<built-in>:0:0` @58 identifier_node strg: `_Bool` lngt: 5 @7 integer_cst type: @21 low: 8 @21 is bit_size
@58 identifier_node strg: `_Bool` lngt: 5
@58
@55 type_decl name: @58 type: @48 srcp: `<built-in>:0:0`
not_found decl
@55 type_decl name: @58 type: @48 srcp: `<built-in>:0:0`
@48 boolean_type name: @55 size: @7 algn: 8
@7 integer_cst type: @21 low: 8 @21 is bit_size
Definition at line 1095 of file tree_manipulation.cpp.
References ALGN_BOOLEAN, create_bit_size_type(), create_identifier_node(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, SIZE_VALUE_BOOL, STR, THROW_ERROR, TOK, TOK_ALGN, TOK_NAME, TOK_SIZE, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by Vectorize::AddGuards(), create_extract_bit_expr(), short_circuit_taf::create_gimple_cond(), interface_infer::create_Read_function(), interface_infer::create_Write_function(), CreateAndExpr(), CreateEqExpr(), CreateNotExpr(), CreateOrExpr(), CreateVectorBooleanType(), IR_lowering::expand_sdiv_pow2(), IR_lowering::expand_smod_pow2(), ExtractCondition(), UnComparisonLowering::InternalExec(), CondExprRestructuring::InternalExec(), IR_lowering::InternalExec(), and Bit_Value_opt::optimize().
create_default_integer_type()
tree_nodeRef tree_manipulation::create_default_integer_type () const
Function that creates a integer type if it is not already present, otherwise it returns the one that is already in the tree manager.
Create an integer type.
Returns
the tree_reindex node of the integer type.
@36 identifier_node strg: `int` lngt: 3 @19 type_decl name: @36 type: @8 srcp: `<built-in>:0:0` @8 integer_type name: @19 size: @11 algn: 32 prec: 32 min : @20 max : @21 @11 integer_cst type: @18 low : 32 @20 integer_cst type: @8 high: -1 low : -2147483648 @21 integer_cst type: @8 low : 2147483647
@36 identifier_node strg: `int` lngt: 3
@36
@19 type_decl name: @36 type: @8 srcp: `<built-in>:0:0`
not_found decl
@20 type_decl name: @41 type: @8 srcp: `<built-in>:0:0`
@8 integer_type name: @19 size: @11 algn: 32 prec: 32 min : @20 max : @21
@11 integer_cst type: @18 low : 32
@20 integer_cst type: @8 high: -1 low : -2147483648
@21 integer_cst type: @8 low : 2147483647
Definition at line 1303 of file tree_manipulation.cpp.
References ALGN_INT, create_bit_size_type(), create_identifier_node(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), MAX_VALUE_INT, MIN_VALUE_INT, tree_manager::new_tree_node_id(), PREC_INT, PRINT_DBG_MEX, SIZE_VALUE_INT, STR, THROW_ERROR, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_NAME, TOK_PREC, TOK_SIZE, TOK_SRCP, TOK_TYPE, TOK_UNSIGNED, and TreeM.
Referenced by HWCallInjection::buildBuiltinCall(), rebuild_initialization::InternalExec(), and rebuild_initialization2::look_for_ROMs().
create_default_unsigned_integer_type()
tree_nodeRef tree_manipulation::create_default_unsigned_integer_type () const
Function that creates a unsigned integer type if it is not already present, otherwise it returns the one that is already in the tree manager.
Create an unsigned integer type.
Returns
the tree_reindex node of the unsigned integer type.
@41 identifier_node strg: `unsigned int` lngt: 12 @8 integer_type name: @20 size: @12 algn: 32 prec: 32 unsigned min : @21 max : @22 @20 type_decl name: @41 type: @8 srcp: `<built-in>:0:0` @12 integer_cst type: @18 low : 32 @21 integer_cst type: @8 low : 0 @22 integer_cst type: @8 low : -1
@41 identifier_node strg: `unsigned int` lngt: 12
@41
@20 type_decl name: @41 type: @8 srcp: `<built-in>:0:0`
not_found decl
@20 type_decl name: @41 type: @8 srcp: `<built-in>:0:0`
@8 integer_type name: @20 size: @12 algn: 32 prec: 32 unsigned min : @21 max : @22
@12 integer_cst type: @18 low : 32
@21 integer_cst type: @8 low : 0
@22 integer_cst type: @8 low : -1
Definition at line 1161 of file tree_manipulation.cpp.
References ALGN_UNSIGNED_INT, create_bit_size_type(), create_identifier_node(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), MAX_VALUE_UNSIGNED_INT, MIN_VALUE_UNSIGNED_INT, tree_manager::new_tree_node_id(), PREC_UNSIGNED_INT, PRINT_DBG_MEX, SIZE_VALUE_UNSIGNED_INT, STR, THROW_ERROR, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_NAME, TOK_PREC, TOK_SIZE, TOK_SRCP, TOK_TYPE, TOK_UNSIGNED, and TreeM.
Referenced by dead_code_elimination::kill_uses(), and Vectorize::Transform().
create_extract_bit_expr()
tree_nodeRef tree_manipulation::create_extract_bit_expr (const tree_nodeRef & op0, const tree_nodeRef & op1, const std::string & srcp) const
Definition at line 627 of file tree_manipulation.cpp.
References create_boolean_type(), tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by Bit_Value_opt::optimize().
create_function_decl()
tree_nodeRef tree_manipulation::create_function_decl (const std::string & function_name, const tree_nodeRef & scpe, const std::vector< tree_nodeRef > & argsT, const tree_nodeRef & returnType, const std::string & srcp, bool with_body) const
create the declaration of a function without its body
Parameters
function_name is the function name
scpe is the function scope
args is the vector of argument types
srcp is the source references
with_body when true a stub of the body is created
Returns
is the the tree_reindex associated with the function_decl created.
add parm_decl to the function_decl
Definition at line 2041 of file tree_manipulation.cpp.
References create_bit_size_type(), create_identifier_node(), create_parm_decl(), tree_manager::create_tree_node(), CreateIntegerCst(), tree_manager::find(), tree_manager::function_index(), GET_INDEX_NODE, tree_manager::get_next_available_tree_node_id(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), SIZE_VALUE_FUNCTION, STR, THROW_ERROR, TOK, TOK_ALGN, TOK_BODY, TOK_CHAN, TOK_NAME, TOK_PRMS, TOK_RETN, TOK_SCPE, TOK_SIZE, TOK_SRCP, TOK_STRG, TOK_TYPE, TOK_VALU, and TreeM.
Referenced by interface_infer::create_Read_function(), and interface_infer::create_Write_function().
create_gimple_call()
tree_nodeRef tree_manipulation::create_gimple_call (const tree_nodeConstRef & called_function, const std::vector< tree_nodeRef > & args, const std::string & srcp, const unsigned int bb_index) const
GIMPLE_CALL.
Definition at line 1538 of file tree_manipulation.cpp.
References ALGN_POINTER, test_panda::arg, tree_helper::CGetType(), create_pointer_type(), tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_CONST_NODE, GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, index, tree_node::index, tree_manager::new_tree_node_id(), STR, THROW_ASSERT, TOK, TOK_ARG, TOK_FN, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by interface_infer::create_Write_function(), FixStructsPassedByValue::InternalExec(), and mem_cg_ext::InternalExec().
create_gimple_cond()
tree_nodeRef tree_manipulation::create_gimple_cond (const tree_nodeRef & expr, const std::string & srcp, unsigned int bb_index) const
GIMPLE_COND.
Function used to create a new gimple_cond with only one operand and of void type.
Parameters
expr is the condition and can be of any type.
srcp is the definition of the source position.
Returns
the tree_reindex node of the gimple_cond created.
Parameters
bb_index is the basic block index associated with the gimple statement
Returns
the tree_reindex node of the gimple_cond created.
Create a gimple_cond with one operand (type void) schema used to create the nodes
@116 gimple_cond type: @62 srcp: `array.c`:1 op: @115
Definition at line 1575 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), create_void_type(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_OP0, TOK_SRCP, TOK_TYPE, and TreeM.
create_gimple_modify_stmt()
tree_nodeRef tree_manipulation::create_gimple_modify_stmt (const tree_nodeRef & op0, const tree_nodeRef & op1, const std::string & srcp, const unsigned int bb_index) const
GIMPLE_ASSIGN.
Function used to create a gimple_assign.
Parameters
op0 is the first operand.
op1 is the second operand.
srcp is the definition of the source position.
bb_index is the basic block index associated with the gimple statement
Returns
the tree_reindex node of the gimple_assign.
Create a gimple_assign
Definition at line 1510 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_manager::new_tree_node_id(), STR, THROW_ASSERT, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, and TreeM.
Referenced by CreateGimpleAssign(), and parm_decl_taken_address_fix::InternalExec().
create_gimple_return()
tree_nodeRef tree_manipulation::create_gimple_return (const tree_nodeRef & type, const tree_nodeRef & expr, const std::string & srcp, unsigned int bb_index) const
GIMPLE_RETURN.
Create gimple_return.
Function used to create a new gimple_return.
Parameters
type is the type of the expression returned.
expr is the value to return.
srcp is the definition of the source position.
bb_index is the basic block index associated with the gimple statement
Returns
the tree_reindex node of the gimple_return created.
Add definition in ssa_name
Definition at line 1601 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
create_goto()
void tree_manipulation::create_goto (const blocRef & block, unsigned int function_decl_nid, unsigned int label_expr_nid) const
create a goto expression.
Parameters
block is the basic block where the goto expression has to be inserted.
function_decl_nid is the node id of the function where the goto expression is defined.
label_expr_nid is the node id of the label expression associated with the goto expression.
compute the label_decl_nid
create the gimple_goto tree node
Definition at line 1964 of file tree_manipulation.cpp.
References tree_manager::add_goto(), tree_manager::create_tree_node(), tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), THROW_ASSERT, TOK, TOK_ALGN, TOK_NAME, TOK_OP, TOK_SRCP, TOK_STRG, TOK_TYPE, and TreeM.
create_identifier_node()
tree_nodeRef tree_manipulation::create_identifier_node (const std::string & strg) const
IDENTIFIER_TREE_NODE.
Function used to create an identifier node if it is not already present, otherwise it returns the one that is already in the tree manager.
Parameters
strg is the identifier string associated with the identifier_node.
Returns
the tree_reindex node of the identifier_node created.
Create an identifier node @37 identifier_node strg: `int` lngt: 3
Definition at line 699 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_STRG, and TreeM.
Referenced by HWCallInjection::buildBuiltinCall(), create_bit_size_type(), create_boolean_type(), create_default_integer_type(), create_default_unsigned_integer_type(), create_function_decl(), create_size_type(), create_void_type(), CreateDefaultUnsignedLongLongInt(), parm_decl_taken_address_fix::InternalExec(), and FixStructsPassedByValue::InternalExec().
create_integer_type_with_prec()
tree_nodeRef tree_manipulation::create_integer_type_with_prec (unsigned int prec, bool unsigned_p) const
create an integer type starting from a given prec
Parameters
prec is the required integer_type precision
unsigned_p say if the integer_type required is unsigned or not
Returns
a new integer with a precision equal to prec
Definition at line 1429 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), tree_manager::CreateUniqueIntegerCst(), tree_manager::find(), GET_INDEX_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), STR, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_PREC, TOK_SIZE, TOK_UNSIGNED, and TreeM.
Referenced by IR_lowering::InternalExec().
create_label()
void tree_manipulation::create_label (const blocRef & block, unsigned int function_decl_nid) const
create a label expression in a header of a loop.
Parameters
block is the basic block where the label expression has to be inserted.
function_decl_nid is the node id of the function where the label expression is defined.
check if the first statement is a gimple_label but with a unnamed label_decl.
addd the name to the label_decl
Definition at line 1837 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), goto_label_unique_id, tree_manager::new_tree_node_id(), THROW_ASSERT, TOK, TOK_ALGN, TOK_NAME, TOK_OP, TOK_SCPE, TOK_SRCP, TOK_STRG, TOK_TYPE, and TreeM.
create_lut_expr()
tree_nodeRef tree_manipulation::create_lut_expr (const tree_nodeRef & type, const tree_nodeRef & op0, const tree_nodeRef & op1, const tree_nodeRef & op2, const tree_nodeRef & op3, const tree_nodeRef & op4, const tree_nodeRef & op5, const tree_nodeRef & op6, const tree_nodeRef & op7, const tree_nodeRef & op8, const std::string & srcp) const
create_lut_expr: function used to create a generic lut_expr operation
Parameters
type is the type of the expression (tree_reindex).
op0 describes the LUT functionality as a constant integer.
op1 is the first operand of the lut_expr expression (tree_reindex).
op2 is the second operand of the lut_expr expression (tree_reindex).
op3 is the third operand of the lut_expr expression (tree_reindex).
op4 is the fourth operand of the lut_expr expression (tree_reindex).
op5 is the fifth operand of the lut_expr expression (tree_reindex).
op6 is the sixth operand of the lut_expr expression (tree_reindex).
op7 is the seventh operand of the lut_expr expression (tree_reindex).
op8 is the eighth operand of the lut_expr expression (tree_reindex).
srcp is the definition of the source position.
Returns
the tree_reindex node of the operation created.
Definition at line 584 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_OP3, TOK_OP4, TOK_OP5, TOK_OP6, TOK_OP7, TOK_OP8, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by CondExprRestructuring::InternalExec(), and Bit_Value_opt::optimize().
create_parm_decl()
tree_nodeRef tree_manipulation::create_parm_decl (const tree_nodeRef & name, const tree_nodeRef & type, const tree_nodeRef & scpe, const tree_nodeRef & size, const tree_nodeRef & argt, const tree_nodeRef & smt_ann, const tree_nodeRef & init, const std::string & srcp, unsigned int algn, int used, bool register_flag = false, bool readonly_flag = false) const
DECL_NODES.
Create parm_decl.
Function used to create a parm_decl.
Parameters
name is the name field containing an identifier_node used to represent a name.
type is the type.
scpe is the scope declaration.
size is the size field holding the size of datum, in bits.
argt is the type in which the argument is actually passed.
smt_ann is the symbol_memory_tag annotation.
init is the init field holding the value to initialize a variable to.
srcp is the definition of the source position.
algn is the field holding the alignment required for the datum, in bits.
used is nonzero if the name is used in its scope
register_flag means declared 'register'
readonly_flag means declared 'readonly'
Returns
the tree_reindex node of the parm_decl created.
Check if the tree_node given are tree_reindex
Definition at line 870 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_ALGN, TOK_ARGT, TOK_INIT, TOK_NAME, TOK_READONLY, TOK_REGISTER, TOK_SCPE, TOK_SIZE, TOK_SMT_ANN, TOK_SRCP, TOK_TYPE, TOK_USED, and TreeM.
Referenced by create_function_decl(), and FixStructsPassedByValue::InternalExec().
create_phi_node()
tree_nodeRef tree_manipulation::create_phi_node (tree_nodeRef & ssa_res, const std::vector< std::pair< tree_nodeRef, unsigned int >> & list_of_def_edge, const tree_nodeRef & scpe, unsigned int bb_index, bool virtual_flag = false) const
GIMPLE_PHI.
Function used to create a gimple_phi.
Parameters
ssa_res is the new ssa_name node created by the phi node.
list_of_def_edge vector where each tuple contains the incoming reaching definition (ssa_name node) and the edge via which that definition is coming through.
bb_index is the basic block index associated with the gimple phi
virtual_flag flag to set if it is a virtual gimple_phi (default false).
Returns
the tree_reindex node of the gimple_phi.
Create a gimple_phi
Definition at line 1628 of file tree_manipulation.cpp.
References create_ssa_name(), tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_node(), tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_RES, TOK_SCPE, TOK_SRCP, and TreeM.
create_pointer_type()
tree_nodeRef tree_manipulation::create_pointer_type (const tree_nodeConstRef & ptd, unsigned int algn) const
Function that creates a pointer type if it is not already present, otherwise it returns the one that is already in the tree manager.
Create a pointer type.
Parameters
ptd type pointed by the pointer type (tree_reindex).
Returns
the tree_reindex node of the pointer type.
@15 pointer_type size: @12 algn: 32 ptd : @9 @9 type of the pointer @12 integer_cst type: @26 low : 32 @26 is bit_size_type
@12 integer_cst type: @26 low : 32 @26 is bit_size_type
@12 integer_cst type: @26 low : 32 @26 is bit_size_type
Definition at line 1391 of file tree_manipulation.cpp.
References create_bit_size_type(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, SIZE_VALUE_POINTER, STR, TOK, TOK_ALGN, TOK_PTD, TOK_SIZE, and TreeM.
Referenced by IR_lowering::array_ref_lowering(), HWCallInjection::buildBuiltinCall(), create_gimple_call(), CreateAddrExpr(), CreateCallExpr(), IR_lowering::expand_target_mem_ref(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), and IR_lowering::InternalExec().
create_quaternary_operation()
tree_nodeRef tree_manipulation::create_quaternary_operation (const tree_nodeRef & type, const tree_nodeRef & op0, const tree_nodeRef & op1, const tree_nodeRef & op2, const tree_nodeRef & op3, const std::string & srcp, enum kind operation_kind) const
Function used to create a quaternary expression.
TODO weight_node to fix in tree_node_factory.cpp Create a quaternary expression.
Parameters
type is the type of the expression (tree_reindex).
op0 is the first operand of the quaternary expression (tree_reindex).
op1 is the second operand of the quaternary expression (tree_reindex).
op2 is the third operand of the quaternary expression (tree_reindex).
op3 is the fourth operand of the quaternary expression (tree_reindex).
srcp is the definition of the source position.
operation_kind is the kind of quaternary expression to create (array_range_ref_K, array_ref_K).
Returns
the tree_reindex node of the operation created.
Check if the tree_node given are tree_reindex
Check if the tree_node type is a quaternary expression
Definition at line 461 of file tree_manipulation.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, THROW_ERROR, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_OP3, TOK_SRCP, TOK_TYPE, and TreeM.
create_result_decl()
tree_nodeRef tree_manipulation::create_result_decl (const tree_nodeRef & name, const tree_nodeRef & type, const tree_nodeRef & scpe, const tree_nodeRef & size, const tree_nodeRef & smt_ann, const tree_nodeRef & init, const std::string & srcp, unsigned int algn, bool artificial_flag = false) const
Function used to create a result_decl.
Create result_decl.
Parameters
name is the name field containing an identifier_node used to represent a name.
type is the type.
scpe is the scope declaration.
size is the size field holding the size of datum, in bits.
smt_ann is the symbol_memory_tag annotation (default empty).
init is the init field holding the value to initialize a variable to.
srcp is the definition of the source position.
algn is the field holding the alignment required for the datum, in bits.
artificial_flag used to indicate that this decl_node represents a compiler-generated entity (default false).
Returns
the tree_reindex node of the result_decl created.
Check if the tree_node given are tree_reindex
Definition at line 815 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_ALGN, TOK_ARTIFICIAL, TOK_INIT, TOK_NAME, TOK_SCPE, TOK_SIZE, TOK_SMT_ANN, TOK_SRCP, TOK_TYPE, and TreeM.
create_size_type()
tree_nodeRef tree_manipulation::create_size_type () const
create a sizetype builtin type in case it has not already been created, otherwise it returns the one found in the tree manager.
Create a size type. @32 identifier_node strg: `sizetype` lngt: 13 @18 integer_type name: @32 size: @33 algn: 64 prec: 64 unsigned min : @34 max : @35 @33 integer_cst type: @18 low : 64 @34 integer_cst type: @18 low : 0 @35 integer_cst type: @18 low : -1
sizetype will translated in unsigned long
@124
not_found decl
@18 integer_type name: @32 size: @33 algn: 64 prec: 64 unsigned min : @34 max : @35
@33 integer_cst type: @18 low : 64
@34 integer_cst type: @18 low : 0
@35 integer_cst type: @18 low : -1
Definition at line 1032 of file tree_manipulation.cpp.
References ALGN_BIT_SIZE, create_identifier_node(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), MAX_VALUE_BIT_SIZE, MIN_VALUE_BIT_SIZE, tree_manager::new_tree_node_id(), PREC_BIT_SIZE, PRINT_DBG_MEX, SIZE_VALUE_BIT_SIZE, STR, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_NAME, TOK_PREC, TOK_SIZE, TOK_UNSIGNED, and TreeM.
Referenced by IR_lowering::array_ref_lowering(), CreateVectorBooleanType(), IR_lowering::expand_target_mem_ref(), and IR_lowering::InternalExec().
create_ssa_name()
tree_nodeRef tree_manipulation::create_ssa_name (const tree_nodeConstRef & var, const tree_nodeConstRef & type, const tree_nodeConstRef & min, const tree_nodeConstRef & max, bool volatile_flag = false, bool virtual_flag = false) const
MISCELLANEOUS_OBJ_TREE_NODES.
SSA_NAME Function used to create a ssa_name node.
Parameters
var is the variable being referenced.
type is the type of the ssa_node
min is the minimum value of the ssa_var
max is the maximum value of the ssa_var
volatile_flag flag set to true in case a ssa_name is never defined (default false).
virtual_flag flag for virtual phi (default false).
Returns
the tree_reindex node of the ssa_name.
SSA_NAME Create a ssa_name node
Definition at line 1457 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_CONST_NODE, tree_manager::get_next_vers(), GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_manager::new_tree_node_id(), STR, THROW_ASSERT, TOK, TOK_MAX, TOK_MIN, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, tree_node::ToString(), and TreeM.
Referenced by create_phi_node(), CreateGimpleAssign(), parm_decl_taken_address_fix::InternalExec(), FixStructsPassedByValue::InternalExec(), FunctionCallTypeCleanup::InternalExec(), MultipleEntryIfReduction::InternalExec(), and Bit_Value_opt::optimize().
create_ternary_operation()
tree_nodeRef tree_manipulation::create_ternary_operation (const tree_nodeRef & type, const tree_nodeRef & op0, const tree_nodeRef & op1, const tree_nodeRef & op2, const std::string & srcp, enum kind operation_kind) const
Function used to create a ternary expression.
TODO weight_node to fix in tree_node_factory.cpp Create a ternary expression.
Parameters
type is the type of the expression (tree_reindex).
op0 is the first operand of the ternary expression (tree_reindex).
op1 is the second operand of the ternary expression (tree_reindex).
op2 is the third operand of the ternary expression (tree_reindex).
srcp is the definition of the source position.
operation_kind is the kind of ternary expression to create (component_ref_K, gimple_switch_K,...).
Returns
the tree_reindex node of the operation created.
Check if the tree_node given are tree_reindex
Check if the tree_node type is a ternary expression
Check if it is a correct node type
Definition at line 337 of file tree_manipulation.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, THROW_ERROR, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by IR_lowering::expand_sdiv_pow2(), Bit_Value_opt::optimize(), and extract_patterns::ternary_plus_expr_extraction().
create_translation_unit_decl()
tree_nodeRef tree_manipulation::create_translation_unit_decl () const
create or find a global scope
Definition at line 793 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, TOK, TOK_SRCP, and TreeM.
create_unary_operation()
tree_nodeRef tree_manipulation::create_unary_operation (const tree_nodeRef & type, const tree_nodeRef & op, const std::string & srcp, enum kind operation_kind) const
EXPRESSION_TREE_NODES.
Function used to create an unary expression.
Parameters
type is the type of the expression (tree_reindex).
op is the operand of the unary expression (tree_reindex).
srcp is the definition of the source position.
operation_kind is the kind of unary expression to create (bit_not_expr_K, nop_expr_K,...).
Returns
the tree_reindex node of the operation created.
TODO weight_node to fix in tree_node_factory.cpp Create an unary operation Check if the tree_node given are tree_reindex
Check if the tree_node type is a unary expression
Check if it is a correct node type
Definition at line 94 of file tree_manipulation.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, THROW_ERROR, TOK, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by IR_lowering::array_ref_lowering(), IR_lowering::division_by_a_constant(), IR_lowering::expand_MC(), IR_lowering::expand_mult_const(), IR_lowering::expand_target_mem_ref(), UnComparisonLowering::InternalExec(), FunctionCallTypeCleanup::InternalExec(), IR_lowering::InternalExec(), and Bit_Value_opt::optimize().
create_var_decl()
tree_nodeRef tree_manipulation::create_var_decl (const tree_nodeRef & name, const tree_nodeConstRef & type, const tree_nodeRef & scpe, const tree_nodeRef & size, const tree_nodeRef & smt_ann, const tree_nodeRef & init, const std::string & srcp, unsigned int algn, int used, bool artificial_flag = false, int use_tmpl = -1, bool static_static_flag = false, bool extern_flag = false, bool static_flag = false, bool register_flag = false, bool readonly_flag = false, const std::string & bit_values = ``, bool addr_taken = false, bool addr_not_taken = false) const
Function used to create a var_decl.
DECL_NODES.
Parameters
name is the name field containing an identifier_node used to represent a name.
type is the type.
scpe is the scope declaration.
size is the size field holding the size of datum, in bits.
smt_ann is the symbol_memory_tag annotation.
init is the init field holding the value to initialize a variable to.
srcp is the definition of the source position.
algn is the field holding the alignment required for the datum, in bits.
used is nonzero if the name is used in its scope
artificial_flag used to indicate that this decl_node represents a compiler-generated entity (default false).
use_tmpl indicates whether or not (and how) a template was expanded for this VAR_DECL (default -1).
static_static_flag to manage C++ code with static member (default false).
static_flag to manage standard static attribute (default false).
extern_flag a variable can be extern (default false).
init field holds the value to initialize a variable to (default false).
Returns
the tree_reindex node of the var_decl created.
Create a var_decl Check if the tree_node given are tree_reindex
Definition at line 728 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_CONST_NODE, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_ADDR_NOT_TAKEN, TOK_ADDR_TAKEN, TOK_ALGN, TOK_ARTIFICIAL, TOK_BIT_VALUES, TOK_EXTERN, TOK_INIT, TOK_NAME, TOK_READONLY, TOK_REGISTER, TOK_SCPE, TOK_SIZE, TOK_SMT_ANN, TOK_SRCP, TOK_STATIC, TOK_STATIC_STATIC, TOK_TYPE, TOK_USE_TMPL, TOK_USED, and TreeM.
Referenced by FixStructsPassedByValue::InternalExec(), and parm_decl_taken_address_fix::InternalExec().
create_void_type()
tree_nodeRef tree_manipulation::create_void_type () const
TYPE_OBJ.
Function that creates a void type if it is not already present, otherwise it returns the one that is already in the tree manager.
Returns
the tree_reindex node of the void type.
Create a void type @41 void_type name: @58 algn: 8 @58 type_decl name: @63 type: @41 srcp: `<built-in>:0:0` @63 identifier_node strg: `void` lngt: 4
Create the void_type @41 void_type name: @58 algn: 8
Create the type_decl @58 type_decl name: @63 type: @41 srcp: `<built-in>:0:0`
Definition at line 930 of file tree_manipulation.cpp.
References ALGN_VOID, create_identifier_node(), tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), PRINT_DBG_MEX, STR, TOK, TOK_ALGN, TOK_NAME, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by HWCallInjection::buildBuiltinCall(), create_gimple_cond(), and interface_infer::create_Write_function().
CreateAddrExpr()
tree_nodeRef tree_manipulation::CreateAddrExpr (const tree_nodeConstRef & tn, const std::string & srcp) const
Create an addr_expr.
Parameters
tn is the tree reindex of the object of which you want to take the address
srcp is the srcp to be associated with the call
Returns
the tree reindex of the created node
Definition at line 2487 of file tree_manipulation.cpp.
References tree_manager::CGetTreeReindex(), tree_helper::CGetType(), create_pointer_type(), tree_manager::create_tree_node(), tree_manager::new_tree_node_id(), STR, TOK, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by CreateGimpleAssignAddrExpr(), FixStructsPassedByValue::InternalExec(), and IR_lowering::InternalExec().
CreateAndExpr()
tree_nodeRef tree_manipulation::CreateAndExpr (const tree_nodeConstRef & first_condition, const tree_nodeConstRef & second_condition, const blocRef & block) const
Create an or expression.
Parameters
first_condition is the first condition
second_condition is the second condition
block is the basic block in which new statement has to be added
Returns
the ssa in the left part of the created statement
Create the and expr
Definition at line 2162 of file tree_manipulation.cpp.
References create_boolean_type(), tree_manager::create_tree_node(), CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), reuse, STR, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by Vectorize::AddGuards(), Schedule::EvaluateMultiWayIfsMerging(), multi_way_if::MergeCondCond(), multi_way_if::MergeCondMulti(), multi_way_if::MergeMultiCond(), and multi_way_if::MergeMultiMulti().
CreateCallExpr()
tree_nodeRef tree_manipulation::CreateCallExpr (const tree_nodeConstRef & called_function, const std::vector< tree_nodeRef > & args, const std::string & srcp) const
Create a call_expr.
Parameters
called_function is the tree reindex of the called function
args is the arguments of the call
srcp is the srcp to be associated with the call
Returns
the tree reindex of the created node
Definition at line 2459 of file tree_manipulation.cpp.
References ALGN_POINTER, test_panda::arg, tree_helper::CGetType(), create_pointer_type(), tree_manager::create_tree_node(), GET_CONST_NODE, GET_INDEX_CONST_NODE, tree_manager::GetTreeReindex(), index, tree_manager::new_tree_node_id(), STR, TOK, TOK_ARG, TOK_FN, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by interface_infer::create_Read_function(), constant_flop_wrapper::InternalExec(), hls_div_cg_ext::recursive_examinate(), and soft_float_cg_ext::RecursiveExaminate().
CreateDefaultUnsignedLongLongInt()
tree_nodeRef tree_manipulation::CreateDefaultUnsignedLongLongInt () const
Function that creates a long long unsigned int type if it is not already present, otherwise return the existing type.
@41
not_found decl
Definition at line 1243 of file tree_manipulation.cpp.
References ALGN_UNSIGNED_LONG_LONG_INT, create_bit_size_type(), create_identifier_node(), tree_manager::create_tree_node(), CreateIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::find(), GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, MAX_VALUE_UNSIGNED_LONG_LONG_INT, MIN_VALUE_UNSIGNED_LONG_LONG_INT, tree_manager::new_tree_node_id(), PREC_UNSIGNED_LONG_LONG_INT, PRINT_DBG_MEX, SIZE_VALUE_UNSIGNED_LONG_LONG_INT, STR, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_NAME, TOK_PREC, TOK_SIZE, TOK_SRCP, TOK_TYPE, TOK_UNSIGNED, and TreeM.
Referenced by CondExprRestructuring::InternalExec(), and Bit_Value_opt::optimize().
CreateEqExpr()
tree_nodeRef tree_manipulation::CreateEqExpr (const tree_nodeConstRef & first_operand, const tree_nodeConstRef & second_operand, const blocRef & block) const
Create an eq_expr.
Parameters
first_operand is the first operand
second_operand is the second operand
block is the basic block in which new statement has to be added
Returns
the ssa in the left part of the created statement
Create the eq expr
Definition at line 2422 of file tree_manipulation.cpp.
References create_boolean_type(), tree_manager::create_tree_node(), CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), reuse, STR, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, TOK_TYPE, and TreeM.
CreateGimpleAssign()
tree_nodeRef tree_manipulation::CreateGimpleAssign (const tree_nodeRef & type, const tree_nodeConstRef & min, const tree_nodeConstRef & max, const tree_nodeRef & op, unsigned int bb_index, const std::string & srcp) const
Create gimple assignment.
Parameters
type is the type the assignment
min is the minimum value of the assigned ssa_var
max is the maximum value of the assigned ssa_var
op is the right part
bb_index is the index of the basic block index
srcp is the srcp to be assigned
Definition at line 1529 of file tree_manipulation.cpp.
References create_gimple_modify_stmt(), create_ssa_name(), tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), tree_node::index, and TreeM.
Referenced by IR_lowering::array_ref_lowering(), interface_infer::create_Read_function(), CreateAndExpr(), CreateEqExpr(), CreateGimpleAssignAddrExpr(), CreateNopExpr(), CreateNotExpr(), CreateOrExpr(), IR_lowering::division_by_a_constant(), IR_lowering::expand_MC(), IR_lowering::expand_mult_const(), IR_lowering::expand_mult_highpart(), IR_lowering::expand_sdiv_pow2(), IR_lowering::expand_smod_pow2(), IR_lowering::expand_target_mem_ref(), ExtractCondition(), UnComparisonLowering::InternalExec(), FunctionCallTypeCleanup::InternalExec(), hls_div_cg_ext::InternalExec(), CondExprRestructuring::InternalExec(), IR_lowering::InternalExec(), and Bit_Value_opt::optimize().
CreateGimpleAssignAddrExpr()
tree_nodeRef tree_manipulation::CreateGimpleAssignAddrExpr (const tree_nodeConstRef & tn, const unsigned int bb_index, const std::string & srcp) const
Create a gimple_assign with op0 a new ssa_name, and op1 an addr_expr which takes the address of the tree node tn.
Parameters
tn is the tree reindex of the object of which you want to take the address
bb_index is the basic block index associated with the gimple_assign
srcp is the srcp to be associated with the call
Returns
the tree reindex of the created node
Definition at line 2506 of file tree_manipulation.cpp.
References tree_manager::CGetTreeReindex(), CreateAddrExpr(), CreateGimpleAssign(), GET_NODE, TreeM, and test_panda::type.
Referenced by FixStructsPassedByValue::InternalExec(), parm_decl_taken_address_fix::InternalExec(), and mem_cg_ext::InternalExec().
CreateIntegerCst()
tree_nodeRef tree_manipulation::CreateIntegerCst (const tree_nodeConstRef & type, const long long int value, const unsigned int integer_cst_nid) const
CONST_OBJ_TREE_NODES.
Function used to create a integer_cst node.
Parameters
type is the type of the node.
value is the value of the constant
integer_cst_nid is the index node of the object to be created
Returns
the tree_reindex node of the integer_cst created.
Create an integer_cst node
Definition at line 650 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_TYPE, TOK_VALUE, and TreeM.
Referenced by Vectorize::AddGuards(), create_bit_size_type(), create_boolean_type(), create_default_integer_type(), create_default_unsigned_integer_type(), create_function_decl(), create_pointer_type(), interface_infer::create_Read_function(), create_size_type(), interface_infer::create_Write_function(), CreateDefaultUnsignedLongLongInt(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), SerializeMutualExclusions::InternalExec(), rebuild_initialization::InternalExec(), rebuild_initialization2::look_for_ROMs(), and Vectorize::Transform().
CreateNopExpr()
tree_nodeRef tree_manipulation::CreateNopExpr (const tree_nodeConstRef & operand, const tree_nodeConstRef & type, const tree_nodeConstRef & min, const tree_nodeConstRef & max) const
Create a nop_expr to perform a conversion.
Parameters
operand is the operand to be converted
type is the destination type
min is the minimum value of the assigned ssa_var
max is the maximum value of the assigned ssa_var
Returns
the gimple assignment containing the nop expr as right part
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
Definition at line 2271 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), CreateGimpleAssign(), GET_CONST_NODE, GET_NODE, tree_manager::GetTreeReindex(), max(), min, tree_manager::new_tree_node_id(), STR, THROW_ASSERT, THROW_UNREACHABLE, TOK, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by interface_infer::create_Write_function(), FunctionCallTypeCleanup::InternalExec(), hls_div_cg_ext::InternalExec(), IR_lowering::InternalExec(), and Bit_Value_opt::optimize().
CreateNotExpr()
tree_nodeRef tree_manipulation::CreateNotExpr (const tree_nodeConstRef & condition, const blocRef & block) const
UTILITY.
Create a not expression if it does not exist in the basic block
Parameters
condition is the operand of the not
block is the basic block in which new statement has tobe added
Returns
the ssa in the left part of the created statement
Create the not expr
Definition at line 2198 of file tree_manipulation.cpp.
References create_boolean_type(), tree_manager::create_tree_node(), CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), reuse, STR, TOK, TOK_OP, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by Schedule::EvaluateMultiWayIfsMerging(), SerializeMutualExclusions::InternalExec(), multi_way_if::MergeCondCond(), multi_way_if::MergeCondMulti(), multi_way_if::MergeMultiCond(), multi_way_if::MergeMultiMulti(), and Bit_Value_opt::optimize().
CreateOrExpr()
tree_nodeRef tree_manipulation::CreateOrExpr (const tree_nodeConstRef & first_condition, const tree_nodeConstRef & second_condition, const blocRef & block) const
Create an or expression.
Parameters
first_condition is the first condition
second_condition is the second condition
block is the basic block in which new statement has to be added
Returns
the ssa in the left part of the created statement
Create the or expr
Definition at line 2125 of file tree_manipulation.cpp.
References create_boolean_type(), tree_manager::create_tree_node(), CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), reuse, STR, TOK, TOK_OP0, TOK_OP1, TOK_SRCP, TOK_TYPE, and TreeM.
Referenced by PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), Schedule::EvaluateCondsMerging(), and Vectorize::Transform().
CreateRealCst()
tree_nodeRef tree_manipulation::CreateRealCst (const tree_nodeConstRef & type, const long double value, const unsigned int real_cst_nid) const
Function used to create a real_cst node.
Parameters
type is the type of the node.
value is the value of the constant
real_cst_nid is the index node of the object to be created
Returns
the tree_reindex node of the real_cst created.
Definition at line 667 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_TYPE, TOK_VALR, TOK_VALX, and TreeM.
Referenced by interface_infer::create_Read_function(), dead_code_elimination::kill_uses(), and Bit_Value_opt::optimize().
CreateUnsigned()
tree_nodeRef tree_manipulation::CreateUnsigned (const tree_nodeConstRef & signed_type) const
Create an unsigned integer type starting from signed type.
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
THROW_ASSERT cannot be used since this function has to return an empty tree node in release
Definition at line 2301 of file tree_manipulation.cpp.
References tree_manager::create_tree_node(), tree_manager::find(), FIRST_TOKEN, GET_CONST_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_manager::GetTreeReindex(), max(), min, tree_manager::new_tree_node_id(), STR, THROW_ASSERT, THROW_UNREACHABLE, TOK, TOK_ALGN, TOK_MAX, TOK_MIN, TOK_NAME, TOK_PREC, TOK_QUAL, TOK_SIZE, TOK_STRG, TOK_UNSIGNED, TOK_VALUE, and TreeM.
Referenced by interface_infer::create_Write_function(), and IR_lowering::InternalExec().
CreateVectorBooleanType()
tree_nodeRef tree_manipulation::CreateVectorBooleanType (const unsigned int number_of_elements) const
Create a vector bool type.
Parameters
number_of_elements is the number of elements of a vector
Returns
the tree reindex of the created node
not_found decl
Definition at line 2518 of file tree_manipulation.cpp.
References create_boolean_type(), create_size_type(), tree_manager::create_tree_node(), tree_manager::CreateUniqueIntegerCst(), tree_manager::find(), tree_manager::GetTreeReindex(), index, tree_manager::new_tree_node_id(), STR, TOK, TOK_ELTS, TOK_SIZE, TOK_SRCP, and TreeM.
Referenced by IR_lowering::InternalExec().
ExtractCondition()
tree_nodeRef tree_manipulation::ExtractCondition (const tree_nodeRef & gc, const blocRef & block) const
Extract computation of condition from a gimple_cond.
Parameters
gc is the gimple_cond (already eliminated)
block is the basic block in which new statement has to be added
Returns
the ssa in the left part of the created statement
Definition at line 2233 of file tree_manipulation.cpp.
References create_boolean_type(), CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, reuse, THROW_ASSERT, tree_node::ToString(), and TreeM.
Referenced by PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), multi_way_if::MergeCondCond(), multi_way_if::MergeCondMulti(), and multi_way_if::MergeMultiCond().
Field Documentation
debug_level
const int tree_manipulation::debug_level [private]
debug level.
Definition at line 121 of file tree_manipulation.hpp.
Referenced by bb_add_stmt(), bb_remove_predecessor(), bb_remove_successor(), create_basic_block(), create_binary_operation(), create_bit_size_type(), create_boolean_type(), create_default_integer_type(), create_default_unsigned_integer_type(), create_extract_bit_expr(), create_gimple_call(), create_gimple_cond(), create_gimple_modify_stmt(), create_gimple_return(), create_identifier_node(), create_lut_expr(), create_parm_decl(), create_phi_node(), create_pointer_type(), create_quaternary_operation(), create_result_decl(), create_size_type(), create_ssa_name(), create_ternary_operation(), create_translation_unit_decl(), create_unary_operation(), create_var_decl(), create_void_type(), CreateDefaultUnsignedLongLongInt(), CreateIntegerCst(), CreateRealCst(), and ExtractCondition().
goto_label_unique_id
unsigned int tree_manipulation::goto_label_unique_id = 0 [static], [private]
store a unique id used during the creation of the label_decl associated with a gimple_goto.
Header include.
tree includes
Definition at line 124 of file tree_manipulation.hpp.
Referenced by create_label().
parameters
const ParameterConstRef tree_manipulation::parameters [private]
The set of input parameters.
Definition at line 118 of file tree_manipulation.hpp.
reuse
const bool tree_manipulation::reuse [private]
True if statements can be reused.
Definition at line 115 of file tree_manipulation.hpp.
Referenced by CreateAndExpr(), CreateEqExpr(), CreateNotExpr(), CreateOrExpr(), and ExtractCondition().
TreeM
tree_managerRef tree_manipulation::TreeM [private]
Tree Manager.
Definition at line 112 of file tree_manipulation.hpp.
Referenced by create_binary_operation(), create_bit_size_type(), create_boolean_type(), create_default_integer_type(), create_default_unsigned_integer_type(), create_extract_bit_expr(), create_function_decl(), create_gimple_call(), create_gimple_cond(), create_gimple_modify_stmt(), create_gimple_return(), create_goto(), create_identifier_node(), create_integer_type_with_prec(), create_label(), create_lut_expr(), create_parm_decl(), create_phi_node(), create_pointer_type(), create_quaternary_operation(), create_result_decl(), create_size_type(), create_ssa_name(), create_ternary_operation(), create_translation_unit_decl(), create_unary_operation(), create_var_decl(), create_void_type(), CreateAddrExpr(), CreateAndExpr(), CreateCallExpr(), CreateDefaultUnsignedLongLongInt(), CreateEqExpr(), CreateGimpleAssign(), CreateGimpleAssignAddrExpr(), CreateIntegerCst(), CreateNopExpr(), CreateNotExpr(), CreateOrExpr(), CreateRealCst(), CreateUnsigned(), CreateVectorBooleanType(), and ExtractCondition().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_manipulation.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_manipulation.cpp