OpNodeInfo Struct Reference
Information associated with a generic operation node.
#include <op_graph.hpp>
Public Member Functions
OpNodeInfo ()
Constructor.
~OpNodeInfo () override
Destructor.
void Initialize ()
Initialize variable maps.
const CustomSet< unsigned int > & GetVariables (const FunctionBehavior_VariableType variable_type, const FunctionBehavior_VariableAccessType access_type) const
Return a set of accessed scalar variables.
unsigned int GetNodeId () const
Return the node id of the operation associated with the vertex.
void Print (std::ostream &stream, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format) const
Print the content of this node.
Data Fields
CustomSet< unsigned int > cited_variables
set of cited variables (i.e., variables which are included in the c printing of this statement)
CustomMap< FunctionBehavior_VariableType, CustomMap< FunctionBehavior_VariableAccessType, CustomSet< unsigned int > > > variables
set of scalar ssa accessed in this node
std::list< unsigned int > actual_parameters
Set of actual parameters of called function (used in pthread backend.
tree_nodeRef node
The tree node associated with this vertex.
CustomUnorderedSet< unsigned int > called
Store the index of called functions.
unsigned int bb_index
Store the index of the basic block which this operation vertex belongs to.
unsigned int cer
Store the index of the control equivalent region.
Detailed Description
Information associated with a generic operation node.
Definition at line 361 of file op_graph.hpp.
Constructor & Destructor Documentation
OpNodeInfo()
OpNodeInfo::OpNodeInfo ()
Constructor.
Definition at line 78 of file op_graph.cpp.
References Initialize().
 OpNodeInfo()
OpNodeInfo::~OpNodeInfo () [override], [default]
Destructor.
Referenced by Initialize().
Member Function Documentation
GetNodeId()
unsigned int OpNodeInfo::GetNodeId () const
Return the node id of the operation associated with the vertex.
Definition at line 140 of file op_graph.cpp.
References ENTRY, ENTRY_ID, EXIT, EXIT_ID, tree_node::index, node, THROW_UNREACHABLE, and TypedNodeInfo::vertex_name.
GetVariables()
const CustomSet< unsigned int > & OpNodeInfo::GetVariables (const FunctionBehavior_VariableType variable_type, const FunctionBehavior_VariableAccessType access_type) const
Return a set of accessed scalar variables.
Parameters
variable_type is the type of variables to be considered
access_type is the type of accesses to be considered
Definition at line 111 of file op_graph.cpp.
References ENTRY, EXIT, GET_NODE, node, NOP, THROW_ASSERT, variables, and TypedNodeInfo::vertex_name.
Initialize()
void OpNodeInfo::Initialize ()
Initialize variable maps.
This is necessary to be sure that the set exists (even if empty)
Definition at line 83 of file op_graph.cpp.
References ADDRESS, DEFINITION, MEMORY, OVER, SCALAR, USE, variables, VIRTUAL, and ~OpNodeInfo().
Referenced by OpNodeInfo().
Print()
void OpNodeInfo::Print (std::ostream & stream, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format) const
Print the content of this node.
Parameters
stream is the stream on which this node has to be printed
behavioral_helper is the helper associated with the function
dotty_format specifies if the output has to be formatted for a dotty label
Definition at line 200 of file op_graph.cpp.
References cited_variables, MEMORY, PrintMemoriesLists(), PrintVariablesList(), PrintVariablesLists(), SCALAR, variables, and VIRTUAL.
Field Documentation
actual_parameters
std::list<unsigned int> OpNodeInfo::actual_parameters
Set of actual parameters of called function (used in pthread backend.
Definition at line 375 of file op_graph.hpp.
bb_index
unsigned int OpNodeInfo::bb_index
Store the index of the basic block which this operation vertex belongs to.
Definition at line 384 of file op_graph.hpp.
called
CustomUnorderedSet<unsigned int> OpNodeInfo::called
Store the index of called functions.
Definition at line 381 of file op_graph.hpp.
cer
unsigned int OpNodeInfo::cer
Store the index of the control equivalent region.
Definition at line 387 of file op_graph.hpp.
cited_variables
CustomSet<unsigned int> OpNodeInfo::cited_variables
set of cited variables (i.e., variables which are included in the c printing of this statement)
Definition at line 364 of file op_graph.hpp.
Referenced by Print().
node
tree_nodeRef OpNodeInfo::node
The tree node associated with this vertex.
Definition at line 378 of file op_graph.hpp.
Referenced by GetNodeId(), and GetVariables().
variables
CustomMap<FunctionBehavior_VariableType, CustomMap<FunctionBehavior_VariableAccessType, CustomSet<unsigned int> > > OpNodeInfo::variables
set of scalar ssa accessed in this node
Definition at line 367 of file op_graph.hpp.
Referenced by GetVariables(), Initialize(), Print(), PrintMemoriesLists(), and PrintVariablesLists().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.cpp