area_model Class Reference
#include <area_model.hpp>
Public Types
enum chacterization_t { PRE_TECHNOLOGY_MAPPING,
POST_TECHNOLOGY_MAPPING
 }
enum element_t {
COMBINATIONAL_AREA,
NONCOMBINATIONAL_AREA,
CELL_AREA,
INTERCONNECT_AREA,
TOTAL_AREA
 }
Public Member Functions
virtual void print (std::ostream &os) const =0
Print method.
virtual void set_area_value (const double &_area_)=0
Set the nominal value for the area of the component.
virtual double get_area_value () const =0
Return the nominal value for the area of the component.
virtual bool is_characterization (unsigned int characterization_type) const =0
Checks if there is a characterization value.
 Constructors and destructors.
area_model (const ParameterConstRef &_Param_)
Constructor.
virtual ~area_model ()
Destructor.
Static Public Member Functions
static area_modelRef create_model (const TargetDevice_Type type, const ParameterConstRef &Param)
Factory method.
Static Public Attributes
static const double area_DEFAULT = 1.0
default area value
Protected Attributes
const ParameterConstRef Param
class containing all the parameters
Detailed Description
Definition at line 55 of file area_model.hpp.
Member Enumeration Documentation
chacterization_t
enum area_model::chacterization_t
Enumerator
PRE_TECHNOLOGY_MAPPING
POST_TECHNOLOGY_MAPPING
Definition at line 58 of file area_model.hpp.
element_t
enum area_model::element_t
Enumerator
COMBINATIONAL_AREA
NONCOMBINATIONAL_AREA
CELL_AREA
INTERCONNECT_AREA
TOTAL_AREA
Definition at line 64 of file area_model.hpp.
Constructor & Destructor Documentation
area_model()
area_model::area_model (const ParameterConstRef & _Param_) [explicit]
Constructor.
Definition at line 61 of file area_model.cpp.
References ~area_model().
 area_model()
area_model::~area_model () [virtual], [default]
Destructor.
Referenced by area_model().
Member Function Documentation
create_model()
area_modelRef area_model::create_model (const TargetDevice_Type type, const ParameterConstRef & Param) [static]
Factory method.
Definition at line 67 of file area_model.cpp.
References FPGA, and THROW_UNREACHABLE.
Referenced by OmpAllocation::AddPandaPthreadMutex(), RTLCharacterization::AnalyzeCell(), AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), interface_infer::create_resource_array(), interface_infer::create_resource_Read_simple(), interface_infer::create_resource_Write_simple(), FunctionalUnitStep::create_template_instance(), add_library::InternalExec(), DesignCompilerWrapper::parse_area_reports(), moduleGenerator::specialize_fu(), functional_unit::xload(), XilinxBackendFlow::xparse_map_utilization(), XilinxBackendFlow::xparse_xst_utilization(), and RTLCharacterization::xwrite_characterization().
get_area_value()
virtual double area_model::get_area_value () const [pure virtual]
Return the nominal value for the area of the component.
Implemented in clb_model, and cell_model.
Referenced by AllocationInformation::get_area(), SynthesisEvaluation::InternalExec(), functional_unit::lib_write(), functional_unit::print(), and functional_unit::xwrite().
is_characterization()
virtual bool area_model::is_characterization (unsigned int characterization_type) const [pure virtual]
Checks if there is a characterization value.
Implemented in clb_model, and cell_model.
print()
virtual void area_model::print (std::ostream & os) const [pure virtual]
Print method.
Implemented in clb_model, and cell_model.
set_area_value()
virtual void area_model::set_area_value (const double & _area_) [pure virtual]
Set the nominal value for the area of the component.
Implemented in clb_model, and cell_model.
Referenced by XilinxBackendFlow::CheckSynthesisResults(), interface_infer::create_resource_array(), interface_infer::create_resource_Read_simple(), interface_infer::create_resource_Write_simple(), add_library::InternalExec(), DesignCompilerWrapper::parse_area_reports(), and functional_unit::xload().
Field Documentation
area_DEFAULT
const double area_model::area_DEFAULT = 1.0 [static]
default area value
Header include.
Autoheader include available models
Definition at line 115 of file area_model.hpp.
Param
const ParameterConstRef area_model::Param [protected]
class containing all the parameters
Definition at line 75 of file area_model.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/area_model.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/area_model.cpp