VIVADO_xsim_wrapper Class Reference
Main class for wrapping VIVADO XSIM Xilinx.
#include <VIVADO_xsim_wrapper.hpp>
Public Member Functions
VIVADO_xsim_wrapper (const ParameterConstRef &Param, std::string suffix)
Constructor.
~VIVADO_xsim_wrapper () override
Destructor.
void CheckExecution () override
Checks if the current specification can be executed or not.
void Clean () const override
Remove files created during simulation.
Private Member Functions
std::string create_project_script (const std::string &top_filename, const std::list< std::string > &file_list)
create the project file for VIVADO xelab
void GenerateScript (std::ostringstream &script, const std::string &top_filename, const std::list< std::string > &file_list) override
Generates the proper simulation script.
Private Attributes
std::string suffix
suffix added to the XSIM dir
Additional Inherited Members
Detailed Description
Main class for wrapping VIVADO XSIM Xilinx.
Definition at line 62 of file VIVADO_xsim_wrapper.hpp.
Constructor & Destructor Documentation
VIVADO_xsim_wrapper()
VIVADO_xsim_wrapper::VIVADO_xsim_wrapper (const ParameterConstRef & _Param, std::string _suffix)
Constructor.
Autoheader include.
Parameters
Param is the set of parameters
Includes the class definition
Definition at line 70 of file VIVADO_xsim_wrapper.cpp.
References SimulationTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, suffix, XSIM_SUBDIR, and ~VIVADO_xsim_wrapper().
 VIVADO_xsim_wrapper()
VIVADO_xsim_wrapper::~VIVADO_xsim_wrapper () [override], [default]
Destructor.
Referenced by VIVADO_xsim_wrapper().
Member Function Documentation
CheckExecution()
void VIVADO_xsim_wrapper::CheckExecution () [override], [virtual]
Checks if the current specification can be executed or not.
Reimplemented from SimulationTool.
Definition at line 79 of file VIVADO_xsim_wrapper.cpp.
References THROW_ERROR.
Clean()
void VIVADO_xsim_wrapper::Clean () const [override], [virtual]
Remove files created during simulation.
Reimplemented from SimulationTool.
Definition at line 154 of file VIVADO_xsim_wrapper.cpp.
create_project_script()
std::string VIVADO_xsim_wrapper::create_project_script (const std::string & top_filename, const std::list< std::string > & file_list) [private]
create the project file for VIVADO xelab
Parameters
top_filename top entity/filename
file_list list of files to be simulated
Returns
name of the project file
Definition at line 86 of file VIVADO_xsim_wrapper.cpp.
References flopoco::filename, GetExtension(), suffix, THROW_ERROR, and XSIM_SUBDIR.
Referenced by GenerateScript().
GenerateScript()
void VIVADO_xsim_wrapper::GenerateScript (std::ostringstream & script, const std::string & top_filename, const std::list< std::string > & file_list) [override], [private], [virtual]
Generates the proper simulation script.
Implements SimulationTool.
Definition at line 126 of file VIVADO_xsim_wrapper.cpp.
References create_project_script(), SimulationTool::log_file, SimulationTool::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, SimulationTool::Param, PRINT_OUT_MEX, STR, suffix, and XSIM_SUBDIR.
Field Documentation
suffix
std::string VIVADO_xsim_wrapper::suffix [private]
suffix added to the XSIM dir
Definition at line 66 of file VIVADO_xsim_wrapper.hpp.
Referenced by create_project_script(), GenerateScript(), and VIVADO_xsim_wrapper().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/xsim/VIVADO_xsim_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/xsim/VIVADO_xsim_wrapper.cpp