/home/osboxes/bambu/PandA-bambu/src/HLS/module_generator/moduleGenerator.cpp File Reference
#include `moduleGenerator.hpp`
#include `config_BOOST_INCLUDE_DIR.hpp`
#include `Parameter.hpp`
#include `function_behavior.hpp`
#include `op_graph.hpp`
#include `structural_manager.hpp`
#include `structural_objects.hpp`
#include `language_writer.hpp`
#include `hls_manager.hpp`
#include `memory.hpp`
#include `memory_cs.hpp`
#include <boost/filesystem/fstream.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <iosfwd>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include `technology_manager.hpp`
#include `library_manager.hpp`
#include `technology_node.hpp`
#include `area_model.hpp`
#include `behavioral_helper.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
#include `constant_strings.hpp`
#include `fileIO.hpp`
#include `math_function.hpp`
#include `string_manipulation.hpp`
Macros
#define NAMESEPARATOR `_`
Functions
static unsigned int resize_to_8_or_greater (unsigned int value)
Detailed Description
Author
Alessandro Nacci alenacci@gmail.com
Gianluca Durelli durellinux@gmail.com
Marco Lattuada marco.lattuada@polimi.it
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Macro Definition Documentation
NAMESEPARATOR
#define NAMESEPARATOR `_`
Definition at line 113 of file moduleGenerator.cpp.
Referenced by moduleGenerator::get_specialized_name().
Function Documentation
resize_to_8_or_greater()
static unsigned int resize_to_8_or_greater (unsigned int value) [static]
Definition at line 120 of file moduleGenerator.cpp.
References resize_to_1_8_16_32_64_128_256_512().
Referenced by moduleGenerator::GenerateHDL(), moduleGenerator::get_specialized_name(), and moduleGenerator::specialize_fu().