memory Class Reference
#include <memory.hpp>
Public Member Functions
memory (const tree_managerRef TreeM, unsigned int off_base_address, unsigned int max_bram, bool null_pointer_check, bool initial_internal_address_p, unsigned int initial_internal_address, const unsigned &_bus_addr_bitsize)
Constructor.
virtual ~memory ()
Destructor.
std::map< unsigned int, memory_symbolRef > get_ext_memory_variables () const
Return variables allocated out of the top module.
void add_external_variable (unsigned int var)
Allocates a variable to the set of variables allocated outside to outermost function.
void add_external_symbol (unsigned int var, const memory_symbolRef m_sym)
Allocates a variable to the set of variables allocated outside to outermost function.
void add_internal_variable (unsigned int funID_scope, unsigned int var)
Allocates a variable to the set of variables allocated internally to the given function.
void add_internal_variable_proxy (unsigned int funID_scope, unsigned int var)
allocate a proxy for the variable for the specified function
void compute_next_base_address (unsigned int &address, unsigned int var, unsigned int alignment)
Compute the new base address based on the size of the given variable and align the memory as needed.
const CustomOrderedSet< unsigned int > & get_proxied_internal_variables (unsigned int funID_scope) const
return the proxied internal variables associated with the function
bool has_proxied_internal_variables (unsigned int funID_scope) const
check if the function has proxied variables
bool is_a_proxied_variable (unsigned int var) const
return true if the variable is a proxied variable
void add_read_only_variable (unsigned var)
add a read only variable
bool is_read_only_variable (unsigned var) const
return true when the variable is only read
void add_internal_symbol (unsigned int funID_scope, unsigned int var, const memory_symbolRef m_sym)
Allocates a variable to the set of variables allocated internally to the given function.
void add_private_memory (unsigned int var)
add a var that safely cannot be attached to the bus
void set_sds_var (unsigned int var, bool value)
set if a variable is always accessed with the same data size or not
void add_source_value (unsigned int var, unsigned int value)
add a value to the set of values written in a given memory variable
const CustomOrderedSet< unsigned int > & get_source_values (unsigned int var)
return the set of values used to write a given memory variable
void add_parameter (unsigned int funID_scope, unsigned int var, bool is_last)
Allocates a parameter to the set of the interface registers.
void add_parameter_symbol (unsigned int funID_scope, unsigned int var, const memory_symbolRef m_sym)
Allocates a parameter to the set of the interface registers.
bool is_internal_variable (unsigned int funID_scope, unsigned int var) const
Test if a variable is allocated into the specified function.
bool is_external_variable (unsigned int var) const
Test if a variable is into the set of variables out of the top function.
bool is_private_memory (unsigned int var) const
Return true in case the variable is private.
bool is_sds_var (unsigned int var) const
check if the variable is always accessed with the same data size
bool has_sds_var (unsigned int var) const
return true if the var has been classified in term of same data size relation
bool is_parameter (unsigned int funID_scope, unsigned int var) const
Test if a variable is into the set of interface registers.
const std::map< unsigned int, memory_symbolRef > get_callSites () const
Get call sites map.
unsigned int get_callSite_base_address (unsigned int var) const
Get the current base address of the given call site.
unsigned int get_internal_base_address (unsigned int var) const
Get the current base address of the given variable.
unsigned int get_external_base_address (unsigned int var) const
Get the current base address of the given variable.
unsigned int get_parameter_base_address (unsigned int funId, unsigned int var) const
Get the current base address of the given variable.
unsigned int get_base_address (unsigned int var, unsigned int funId) const
Get the current base address of the given variable.
unsigned int get_first_address (unsigned int funId) const
Get the first address of the function address space.
unsigned int get_last_address (unsigned int funId, const application_managerRef AppM) const
Get the last address of the function address space.
memory_symbolRef get_symbol (unsigned int var, unsigned int funId) const
Return the symbol associated with the given variable.
unsigned int get_rangesize (unsigned int var) const
return the address space rangesize associated with the given var
bool has_callSite_base_address (unsigned int var) const
Check if there is a base address for the given call site.
bool has_internal_base_address (unsigned int var) const
Check if there is a base address for the given variable.
unsigned int get_n_mem_operations (unsigned int var) const
void increment_n_mem_operations (unsigned int var)
bool has_external_base_address (unsigned int var) const
Check if there is a base address for the given variable.
bool has_parameter_base_address (unsigned int var, unsigned int funId) const
Check if there is a base address for the given parameter.
bool has_base_address (unsigned int var) const
Check if there is a base address for the given variable.
bool is_parm_decl_copied (unsigned int var) const
return true in case the parm_decl parameter has to be copied from the caller
void add_parm_decl_copied (unsigned int var)
add a parm_decl to the set of parm_decl written
bool is_parm_decl_stored (unsigned int var) const
return true in case the parm_decl parameter has to be initialized from the formal value
void add_parm_decl_stored (unsigned int var)
add a parm_decl to the set of parm_decl that has to be initialized
bool is_actual_parm_loaded (unsigned int var) const
return true in case the actual parameter has to be initialized from a stored value
void add_actual_parm_loaded (unsigned int var)
add an actual parameter to the set of parameter that has to be initialized from a stored value
std::map< unsigned int, memory_symbolRef > get_function_vars (unsigned int funID_scope) const
Return the variables allocated within the space of a given function.
std::map< unsigned int, memory_symbolRef > get_function_parameters (unsigned int funID_scope) const
Return parameters allocated in register of the interface.
unsigned int get_memory_address () const
Return the first memory address not yet allocated.
void reserve_space (unsigned int space)
Explicitly allocate a certain space in the external memory.
unsigned int get_allocated_space () const
Returns the amount of memory allocated internally to the module.
unsigned int get_allocated_parameters_memory () const
Return the total amount of memory allocated for the memory mapped parameters.
unsigned int get_allocated_intern_memory () const
Returns the amount of memory allocated internally but not private.
unsigned int get_max_address () const
return the maximum address allocated
void set_bus_data_bitsize (unsigned int bitsize)
set the bus data bitsize
unsigned int get_bus_data_bitsize () const
return the bitsize of the data bus
void set_bus_size_bitsize (unsigned int bitsize)
set the bus size bitsize
unsigned int get_bus_size_bitsize () const
return the bitsize of the size bus
void set_bram_bitsize (unsigned int bitsize)
set the BRAM bitsize
unsigned int get_bram_bitsize () const
return the BRAM bitsize
void set_maxbram_bitsize (unsigned int bitsize)
set the maximum BRAM bitsize
unsigned int get_maxbram_bitsize () const
return the BRAM bitsize
void set_intern_shared_data (bool has_accesses)
define if the Spec has data that can be externally accessed
bool has_intern_shared_data () const
return true in case the specification has data that can be externally accessed
void set_maximum_references (unsigned int var, size_t n_refs)
define the maximum number of references for a given variable
size_t get_maximum_references (unsigned int var) const
return the maximum number of references for a given variable
void set_maximum_loads (unsigned int var, size_t n_refs)
define the maximum number of loads for a given variable
size_t get_maximum_loads (unsigned int var) const
return the maximum number of loads for a given variable
void add_need_bus (unsigned int var)
the variable is read or written through the bus
bool does_need_addr (unsigned int var) const
check if a load or a store of the variable is done trough the bus
void set_use_unknown_addresses (bool accesses)
define if there exist an object used by the Spec with an address not known at compile time
bool has_unknown_addresses () const
return true in case the specification use addresses not known at compile time
void set_pointer_conversion (bool accesses)
set if a pointer conversion happen
bool has_pointer_conversion () const
return true in case at least one pointer conversion happen
void set_unaligned_accesses (bool accesses)
set if LOADs or STOREs perform unaligned accesses
bool has_unaligned_accesses () const
return true in case of unaligned accesses
void set_all_pointers_resolved (bool resolved)
define if all pointers have statically resolved
bool has_all_pointers_resolved () const
return true in case all pointers have been statically resolved
void set_packed_vars (bool packed)
update the the packed variables status
bool has_packed_vars () const
void set_implicit_memcpy (bool cond)
define if there exist an implicit call of memcpy
bool has_implicit_memcpy () const
return true in case the specification has an implicit call of memcpy
unsigned int get_internal_base_address_alignment () const
return the internal base address alignment.
unsigned int get_parameter_alignment () const
return the parameter alignment
void set_internal_base_address_alignment (unsigned int _internal_base_address_alignment)
set the internal base address alignment
void xwrite (xml_element *node)
Writes the current memory allocation into an XML description.
unsigned int count_non_private_internal_symbols () const
bool notEQ (refcount< memory > ref) const
return true in case the current memory object and the passed one are different
Static Public Member Functions
static memoryRef create_memory (const ParameterConstRef _parameters, const tree_managerRef _TreeM, unsigned int _off_base_address, unsigned int max_bram, bool _null_pointer_check, bool initial_internal_address_p, unsigned int initial_internal_address, const unsigned int &_address_bitsize)
static void propagate_memory_parameters (const structural_objectRef src, const structural_managerRef tgt)
Propagates the memory parameters from the source (innermost) module to the target (outermost) one.
static void add_memory_parameter (const structural_managerRef SM, const std::string &name, const std::string &value)
Adds the given memory parameter to the corresponding object.
Private Member Functions
void align (unsigned int &address, unsigned int alignment)
Alignment utility function.
Private Attributes
const tree_managerRef TreeM
datastructure containing tree information
std::map< unsigned int, memory_symbolRef > external
set of variables allocated outside the top module
std::map< unsigned int, std::map< unsigned int, memory_symbolRef > > internal
set of variables allocated internally to the cores, classified by function id
std::map< unsigned int, CustomOrderedSet< unsigned int > > internal_variable_proxy
set of variable proxies accessed by a function
CustomOrderedSet< unsigned int > proxied_variables
is the set of proxied variables
CustomOrderedSet< unsigned int > read_only_vars
std::map< unsigned int, memory_symbolRef > in_vars
set of all the internal variables
std::map< unsigned int, unsigned int > rangesize
for each var store the address space rangesize associated with it
std::map< unsigned int, std::map< unsigned int, memory_symbolRef > > parameter
set of variables allocated in registers of the interface
std::map< unsigned int, memory_symbolRef > params
set of all the internal parameters
std::map< unsigned int, memory_symbolRef > callSites
set of call sites for __builtin_wait_call
CustomOrderedSet< unsigned int > private_memories
store the objects that does not need to be attached to the bus
std::map< unsigned int, unsigned int > same_data_size_accesses
store if a given variable is accessed always with the same data_size or not
std::map< unsigned int, CustomOrderedSet< unsigned int > > source_values
ssa_names assigned to a given memory variable
CustomOrderedSet< unsigned int > parm_decl_copied
parm_decl that has to be copied from the caller
CustomOrderedSet< unsigned int > parm_decl_stored
parm_decl storage has to be initialized from the formal parameter
CustomOrderedSet< unsigned int > actual_parm_loaded
actual parameter that has to be loaded from a stored value
unsigned int next_base_address
it represents the next address that is available for internal allocation
unsigned int internal_base_address_start
is the start internal address
unsigned int maximum_private_memory_size
is the maximum amount of private memory allocated
unsigned int total_amount_of_private_memory
total amount of internal memory allocated
unsigned int total_amount_of_parameter_memory
total amount of parameter memory
unsigned int off_base_address
it represents the base address of the external memory
unsigned int next_off_base_address
it represents the next address that is available to allocate a variable out of the top module
unsigned int bus_data_bitsize
bus data bitsize
unsigned int bus_size_bitsize
bus size bitsize
unsigned int bram_bitsize
bram bitsize
unsigned int maxbram_bitsize
maximum bram bitsize
bool intern_shared_data
define if the Spec has data that can be externally accessed
bool use_unknown_addresses
Spec accesses data having an address unknown at compile time.
bool pointer_conversion
true when at least one pointer conversion happen
bool unaligned_accesses
true when LOADs or STOREs perform unaligned accesses
bool all_pointers_resolved
is true when all pointers are resolved statically
bool implicit_memcpy
when true an implicit memcpy is called
unsigned int internal_base_address_alignment
internal address alignment
unsigned int external_base_address_alignment
external address alignment
const unsigned int parameter_alignment
parameter alignment
std::map< unsigned int, unsigned int > n_mem_operations_per_var
number of LOAD/STORE per var
bool null_pointer_check
when false object could be allocated starting from address 0
std::map< unsigned int, size_t > maximum_references
define for each variable the number of references whenever it is possible
std::map< unsigned int, size_t > maximum_loads
define for each variable the number of loads whenever it is possible
CustomOrderedSet< unsigned int > need_bus
define for each variable the number of loads whenever it is possible
bool packed_vars
true when packed vars are used
const unsigned & bus_addr_bitsize
Detailed Description
Definition at line 67 of file memory.hpp.
Constructor & Destructor Documentation
memory()
memory::memory (const tree_managerRef _TreeM, unsigned int _off_base_address, unsigned int max_bram, bool _null_pointer_check, bool initial_internal_address_p, unsigned int initial_internal_address, const unsigned & _bus_addr_bitsize)
Constructor.
STL includes.
tree include we start to allocate from internal_base_address_alignment byte to align address to internal_base_address_alignment bits we can use address 0 in some cases but it is not safe in general.
Definition at line 79 of file memory.cpp.
References align(), external_base_address_alignment, internal_base_address_alignment, internal_base_address_start, next_base_address, null_pointer_check, and ~memory().
Referenced by align(), and create_memory().
 memory()
memory::~memory () [virtual], [default]
Destructor.
Referenced by align(), and memory().
Member Function Documentation
add_actual_parm_loaded()
void memory::add_actual_parm_loaded (unsigned int var)
add an actual parameter to the set of parameter that has to be initialized from a stored value
Definition at line 556 of file memory.cpp.
References actual_parm_loaded.
Referenced by increment_n_mem_operations().
add_external_symbol()
void memory::add_external_symbol (unsigned int var, const memory_symbolRef m_sym)
Allocates a variable to the set of variables allocated outside to outermost function.
The corresponding symbol is already provided
Definition at line 258 of file memory.cpp.
References compute_next_base_address(), external, external_base_address_alignment, in_vars, max(), next_off_base_address, parameter, STR, and THROW_WARNING.
Referenced by add_external_variable(), and align().
add_external_variable()
void memory::add_external_variable (unsigned int var)
Allocates a variable to the set of variables allocated outside to outermost function.
Definition at line 251 of file memory.cpp.
References add_external_symbol(), align(), tree_helper::get_var_alignment(), next_off_base_address, and TreeM.
Referenced by align().
add_internal_symbol()
void memory::add_internal_symbol (unsigned int funID_scope, unsigned int var, const memory_symbolRef m_sym)
Allocates a variable to the set of variables allocated internally to the given function.
The corresponding symbol is already provided
Definition at line 210 of file memory.cpp.
References align(), callSites, compute_n_bytes(), compute_next_base_address(), external, tree_manager::get_tree_node_const(), in_vars, internal_base_address_alignment, is_private_memory(), max(), maximum_private_memory_size, next_base_address, parameter, rangesize, tree_helper::size(), STR, THROW_ASSERT, THROW_WARNING, total_amount_of_private_memory, and TreeM.
Referenced by add_internal_variable(), and align().
add_internal_variable()
void memory::add_internal_variable (unsigned int funID_scope, unsigned int var)
Allocates a variable to the set of variables allocated internally to the given function.
Definition at line 151 of file memory.cpp.
References add_internal_symbol(), align(), tree_helper::get_var_alignment(), in_vars, internal_base_address_start, is_private_memory(), next_base_address, null_pointer_check, and TreeM.
Referenced by align().
add_internal_variable_proxy()
void memory::add_internal_variable_proxy (unsigned int funID_scope, unsigned int var)
allocate a proxy for the variable for the specified function
Parameters
funID_scope is the function id
var is the variable
Definition at line 178 of file memory.cpp.
References internal_variable_proxy, and proxied_variables.
Referenced by align().
add_memory_parameter()
void memory::add_memory_parameter (const structural_managerRef SM, const std::string & name, const std::string & value) [static]
Adds the given memory parameter to the corresponding object.
Definition at line 628 of file memory.cpp.
References structural_object::AddParameter(), structural_object::ExistsParameter(), structural_manager::get_circ(), structural_object::GetParameter(), MEMORY_PARAMETER, structural_object::SetParameter(), THROW_ASSERT, and THROW_ERROR.
Referenced by classic_datapath::add_ports(), fu_binding::add_to_SM(), TopEntityMemoryMapped::allocate_parameters(), build_bus_interface(), WB4_interface::build_WB4_bus_interface(), get_parameter_alignment(), and fu_binding::specialize_memory_unit().
add_need_bus()
void memory::add_need_bus (unsigned int var) [inline]
the variable is read or written through the bus
Parameters
var is the variable
Definition at line 662 of file memory.hpp.
add_parameter()
void memory::add_parameter (unsigned int funID_scope, unsigned int var, bool is_last)
Allocates a parameter to the set of the interface registers.
align in case is not aligned
Definition at line 285 of file memory.cpp.
References add_parameter_symbol(), align(), internal_base_address_alignment, next_base_address, and total_amount_of_parameter_memory.
Referenced by get_source_values().
add_parameter_symbol()
void memory::add_parameter_symbol (unsigned int funID_scope, unsigned int var, const memory_symbolRef m_sym)
Allocates a parameter to the set of the interface registers.
allocation of the parameters
Definition at line 298 of file memory.cpp.
References compute_next_base_address(), external, in_vars, max(), next_base_address, parameter, parameter_alignment, params, STR, THROW_WARNING, and total_amount_of_parameter_memory.
Referenced by add_parameter(), and get_source_values().
add_parm_decl_copied()
void memory::add_parm_decl_copied (unsigned int var)
add a parm_decl to the set of parm_decl written
Definition at line 536 of file memory.cpp.
References parm_decl_copied.
Referenced by increment_n_mem_operations().
add_parm_decl_stored()
void memory::add_parm_decl_stored (unsigned int var)
add a parm_decl to the set of parm_decl that has to be initialized
Definition at line 546 of file memory.cpp.
References parm_decl_stored.
Referenced by increment_n_mem_operations().
add_private_memory()
void memory::add_private_memory (unsigned int var)
add a var that safely cannot be attached to the bus
Parameters
var is var index
Definition at line 270 of file memory.cpp.
References private_memories.
Referenced by align().
add_read_only_variable()
void memory::add_read_only_variable (unsigned var)
add a read only variable
Parameters
var is the variable id
Definition at line 200 of file memory.cpp.
References read_only_vars.
Referenced by align().
add_source_value()
void memory::add_source_value (unsigned int var, unsigned int value)
add a value to the set of values written in a given memory variable
Parameters
var is the memory variable
value is the source value
Definition at line 280 of file memory.cpp.
References source_values.
Referenced by align().
align()
void memory::align (unsigned int & address, unsigned int alignment) [inline], [private]
Alignment utility function.
Definition at line 200 of file memory.hpp.
References add_external_symbol(), add_external_variable(), add_internal_symbol(), add_internal_variable(), add_internal_variable_proxy(), add_private_memory(), add_read_only_variable(), add_source_value(), compute_next_base_address(), create_memory(), get_ext_memory_variables(), get_proxied_internal_variables(), has_proxied_internal_variables(), is_a_proxied_variable(), is_read_only_variable(), memory(), set_sds_var(), and ~memory().
Referenced by add_external_variable(), add_internal_symbol(), add_internal_variable(), add_parameter(), compute_next_base_address(), memory(), reserve_space(), and set_internal_base_address_alignment().
compute_next_base_address()
void memory::compute_next_base_address (unsigned int & address, unsigned int var, unsigned int alignment)
Compute the new base address based on the size of the given variable and align the memory as needed.
Parameters
address is the address to be evaluated
var is the variable that has to be reserved
alignment is the address alignment
compute the next base address
align the memory address
Definition at line 130 of file memory.cpp.
References align(), bus_addr_bitsize, compute_n_bytes(), tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_helper::size(), and TreeM.
Referenced by add_external_symbol(), add_internal_symbol(), add_parameter_symbol(), and align().
count_non_private_internal_symbols()
unsigned int memory::count_non_private_internal_symbols () const
Returns
return the number of internal symbols non private
Definition at line 242 of file memory.cpp.
References in_vars, and is_private_memory().
Referenced by get_parameter_alignment().
create_memory()
memoryRef memory::create_memory (const ParameterConstRef _parameters, const tree_managerRef _TreeM, unsigned int _off_base_address, unsigned int max_bram, bool _null_pointer_check, bool initial_internal_address_p, unsigned int initial_internal_address, const unsigned int & _address_bitsize) [static]
Definition at line 116 of file memory.cpp.
References memory().
Referenced by align(), mem_dominator_allocation::InternalExec(), and mem_xml_allocation::parse_xml_allocation().
does_need_addr()
bool memory::does_need_addr (unsigned int var) const [inline]
check if a load or a store of the variable is done trough the bus
Parameters
var is the variable
Returns
true in case var is loaded or stored through the bus
Definition at line 672 of file memory.hpp.
get_allocated_intern_memory()
unsigned int memory::get_allocated_intern_memory () const [inline]
Returns the amount of memory allocated internally but not private.
Definition at line 528 of file memory.hpp.
References get_max_address(), and internal_base_address_start.
get_allocated_parameters_memory()
unsigned int memory::get_allocated_parameters_memory () const
Return the total amount of memory allocated for the memory mapped parameters.
Definition at line 521 of file memory.cpp.
References total_amount_of_parameter_memory.
Referenced by increment_n_mem_operations().
get_allocated_space()
unsigned int memory::get_allocated_space () const
Returns the amount of memory allocated internally to the module.
Definition at line 516 of file memory.cpp.
References internal_base_address_start, next_base_address, and total_amount_of_private_memory.
Referenced by increment_n_mem_operations().
get_base_address()
unsigned int memory::get_base_address (unsigned int var, unsigned int funId) const
Get the current base address of the given variable.
Definition at line 415 of file memory.cpp.
References get_callSite_base_address(), get_external_base_address(), get_internal_base_address(), get_parameter_base_address(), has_base_address(), has_callSite_base_address(), has_internal_base_address(), has_parameter_base_address(), STR, and THROW_ASSERT.
Referenced by get_callSites(), and fu_binding::write_init().
get_bram_bitsize()
unsigned int memory::get_bram_bitsize () const [inline]
return the BRAM bitsize
Definition at line 581 of file memory.hpp.
References bram_bitsize.
Referenced by fu_binding::fill_array_ref_memory().
get_bus_data_bitsize()
unsigned int memory::get_bus_data_bitsize () const [inline]
return the bitsize of the data bus
Definition at line 549 of file memory.hpp.
References bus_data_bitsize.
Referenced by fu_binding::fill_array_ref_memory().
get_bus_size_bitsize()
unsigned int memory::get_bus_size_bitsize () const [inline]
return the bitsize of the size bus
Definition at line 565 of file memory.hpp.
References bus_size_bitsize.
get_callSite_base_address()
unsigned int memory::get_callSite_base_address (unsigned int var) const
Get the current base address of the given call site.
Definition at line 348 of file memory.cpp.
References callSites, and THROW_ASSERT.
Referenced by get_base_address(), and get_callSites().
get_callSites()
const std::map<unsigned int, memory_symbolRef> memory::get_callSites () const [inline]
Get call sites map.
Definition at line 373 of file memory.hpp.
References callSites, get_base_address(), get_callSite_base_address(), get_external_base_address(), get_first_address(), get_internal_base_address(), get_last_address(), get_parameter_base_address(), get_rangesize(), get_symbol(), has_callSite_base_address(), and has_internal_base_address().
get_ext_memory_variables()
std::map< unsigned int, memory_symbolRef > memory::get_ext_memory_variables () const
Return variables allocated out of the top module.
Definition at line 125 of file memory.cpp.
References external.
Referenced by align().
get_external_base_address()
unsigned int memory::get_external_base_address (unsigned int var) const
Get the current base address of the given variable.
Definition at line 360 of file memory.cpp.
References external, and THROW_ASSERT.
Referenced by get_base_address(), and get_callSites().
get_first_address()
unsigned int memory::get_first_address (unsigned int funId) const
Get the first address of the function address space.
Definition at line 433 of file memory.cpp.
References has_parameter_base_address(), is_private_memory(), min, and parameter.
Referenced by get_callSites().
get_function_parameters()
std::map< unsigned int, memory_symbolRef > memory::get_function_parameters (unsigned int funID_scope) const
Return parameters allocated in register of the interface.
Definition at line 380 of file memory.cpp.
References parameter.
Referenced by get_last_address(), increment_n_mem_operations(), WishboneInterfaceTestbench::write_call(), WishboneInterfaceTestbench::write_file_reading_operations(), TestbenchGenerationBaseStep::write_output_checks(), and WishboneInterfaceTestbench::write_signals().
get_function_vars()
std::map< unsigned int, memory_symbolRef > memory::get_function_vars (unsigned int funID_scope) const
Return the variables allocated within the space of a given function.
Definition at line 373 of file memory.cpp.
Referenced by increment_n_mem_operations().
get_internal_base_address()
unsigned int memory::get_internal_base_address (unsigned int var) const
Get the current base address of the given variable.
Definition at line 354 of file memory.cpp.
References in_vars, and THROW_ASSERT.
Referenced by get_base_address(), and get_callSites().
get_internal_base_address_alignment()
unsigned int memory::get_internal_base_address_alignment () const [inline]
return the internal base address alignment.
Definition at line 776 of file memory.hpp.
References internal_base_address_alignment.
get_last_address()
unsigned int memory::get_last_address (unsigned int funId, const application_managerRef AppM) const
Get the last address of the function address space.
Definition at line 456 of file memory.cpp.
References get_function_parameters(), has_base_address(), has_parameter_base_address(), is_private_memory(), max(), tree_helper::size(), and TreeM.
Referenced by get_callSites().
get_max_address()
unsigned int memory::get_max_address () const
return the maximum address allocated
Definition at line 526 of file memory.cpp.
References internal_base_address_start, max(), maximum_private_memory_size, and next_base_address.
Referenced by get_allocated_intern_memory().
get_maxbram_bitsize()
unsigned int memory::get_maxbram_bitsize () const [inline]
return the BRAM bitsize
Definition at line 597 of file memory.hpp.
References maxbram_bitsize.
get_maximum_loads()
size_t memory::get_maximum_loads (unsigned int var) const [inline]
return the maximum number of loads for a given variable
Parameters
var is the variable
Returns
the maximum number of loads for var
Definition at line 653 of file memory.hpp.
get_maximum_references()
size_t memory::get_maximum_references (unsigned int var) const [inline]
return the maximum number of references for a given variable
Parameters
var is the variable
Returns
the maximum number of references for var
Definition at line 633 of file memory.hpp.
get_memory_address()
unsigned int memory::get_memory_address () const
Return the first memory address not yet allocated.
Definition at line 312 of file memory.cpp.
References next_off_base_address.
Referenced by increment_n_mem_operations().
get_n_mem_operations()
unsigned int memory::get_n_mem_operations (unsigned int var) const [inline]
Returns
the numnber of LOAD/STORE operations per var
Definition at line 437 of file memory.hpp.
get_parameter_alignment()
unsigned int memory::get_parameter_alignment () const [inline]
return the parameter alignment
Definition at line 784 of file memory.hpp.
References add_memory_parameter(), count_non_private_internal_symbols(), notEQ(), parameter_alignment, propagate_memory_parameters(), set_internal_base_address_alignment(), and xwrite().
get_parameter_base_address()
unsigned int memory::get_parameter_base_address (unsigned int funId, unsigned int var) const
Get the current base address of the given variable.
Definition at line 366 of file memory.cpp.
References parameter, and THROW_ASSERT.
Referenced by get_base_address(), get_callSites(), and WishboneInterfaceTestbench::write_signals().
get_proxied_internal_variables()
const CustomOrderedSet< unsigned int > & memory::get_proxied_internal_variables (unsigned int funID_scope) const
return the proxied internal variables associated with the function
Parameters
funID_scope is the function id
Returns
the set of variables proxied in funID_scope
Definition at line 184 of file memory.cpp.
References has_proxied_internal_variables(), internal_variable_proxy, STR, and THROW_ASSERT.
Referenced by align().
get_rangesize()
unsigned int memory::get_rangesize (unsigned int var) const
return the address space rangesize associated with the given var
Parameters
var is the variable considered
Definition at line 504 of file memory.cpp.
References has_base_address(), rangesize, STR, and THROW_ASSERT.
Referenced by get_callSites().
get_source_values()
const CustomOrderedSet<unsigned int>& memory::get_source_values (unsigned int var) [inline]
return the set of values used to write a given memory variable
Parameters
var is the memory variable
Returns
the set of values associated with var
Definition at line 319 of file memory.hpp.
References add_parameter(), add_parameter_symbol(), has_sds_var(), is_external_variable(), is_internal_variable(), is_parameter(), is_private_memory(), and is_sds_var().
get_symbol()
memory_symbolRef memory::get_symbol (unsigned int var, unsigned int funId) const
Return the symbol associated with the given variable.
Definition at line 489 of file memory.cpp.
References callSites, external, has_base_address(), has_callSite_base_address(), has_internal_base_address(), has_parameter_base_address(), in_vars, parameter, STR, and THROW_ASSERT.
Referenced by get_callSites().
has_all_pointers_resolved()
bool memory::has_all_pointers_resolved () const [inline]
return true in case all pointers have been statically resolved
Definition at line 735 of file memory.hpp.
References all_pointers_resolved.
has_base_address()
bool memory::has_base_address (unsigned int var) const
Check if there is a base address for the given variable.
Definition at line 410 of file memory.cpp.
References callSites, external, in_vars, and params.
Referenced by get_base_address(), get_last_address(), get_rangesize(), get_symbol(), increment_n_mem_operations(), HLS_manager::is_register_compatible(), and fu_binding::write_init().
has_callSite_base_address()
bool memory::has_callSite_base_address (unsigned int var) const
Check if there is a base address for the given call site.
Definition at line 387 of file memory.cpp.
References callSites.
Referenced by get_base_address(), get_callSites(), and get_symbol().
has_external_base_address()
bool memory::has_external_base_address (unsigned int var) const
Check if there is a base address for the given variable.
Definition at line 397 of file memory.cpp.
References external.
Referenced by increment_n_mem_operations().
has_implicit_memcpy()
bool memory::has_implicit_memcpy () const [inline]
return true in case the specification has an implicit call of memcpy
Definition at line 768 of file memory.hpp.
References implicit_memcpy.
has_intern_shared_data()
bool memory::has_intern_shared_data () const [inline]
return true in case the specification has data that can be externally accessed
Definition at line 613 of file memory.hpp.
References intern_shared_data.
has_internal_base_address()
bool memory::has_internal_base_address (unsigned int var) const
Check if there is a base address for the given variable.
Definition at line 392 of file memory.cpp.
References in_vars.
Referenced by get_base_address(), get_callSites(), and get_symbol().
has_packed_vars()
bool memory::has_packed_vars () const [inline]
Returns
true in case packed vars are used
Definition at line 752 of file memory.hpp.
References packed_vars.
has_parameter_base_address()
bool memory::has_parameter_base_address (unsigned int var, unsigned int funId) const
Check if there is a base address for the given parameter.
Definition at line 402 of file memory.cpp.
References parameter.
Referenced by get_base_address(), get_first_address(), get_last_address(), get_symbol(), and increment_n_mem_operations().
has_pointer_conversion()
bool memory::has_pointer_conversion () const [inline]
return true in case at least one pointer conversion happen
Definition at line 703 of file memory.hpp.
References pointer_conversion.
has_proxied_internal_variables()
bool memory::has_proxied_internal_variables (unsigned int funID_scope) const
check if the function has proxied variables
Parameters
funID_scope is the function id
Returns
true when there are proxied variables, false otherwise
Definition at line 190 of file memory.cpp.
References internal_variable_proxy.
Referenced by align(), and get_proxied_internal_variables().
has_sds_var()
bool memory::has_sds_var (unsigned int var) const
return true if the var has been classified in term of same data size relation
Parameters
var is the variable id
Returns
true when var is in the sds relation, false otherwise
Definition at line 338 of file memory.cpp.
References same_data_size_accesses.
Referenced by get_source_values(), and is_sds_var().
has_unaligned_accesses()
bool memory::has_unaligned_accesses () const [inline]
return true in case of unaligned accesses
Definition at line 719 of file memory.hpp.
References unaligned_accesses.
has_unknown_addresses()
bool memory::has_unknown_addresses () const [inline]
return true in case the specification use addresses not known at compile time
Definition at line 687 of file memory.hpp.
References use_unknown_addresses.
increment_n_mem_operations()
void memory::increment_n_mem_operations (unsigned int var) [inline]
Definition at line 442 of file memory.hpp.
References add_actual_parm_loaded(), add_parm_decl_copied(), add_parm_decl_stored(), get_allocated_parameters_memory(), get_allocated_space(), get_function_parameters(), get_function_vars(), get_memory_address(), has_base_address(), has_external_base_address(), has_parameter_base_address(), is_actual_parm_loaded(), is_parm_decl_copied(), is_parm_decl_stored(), and reserve_space().
is_a_proxied_variable()
bool memory::is_a_proxied_variable (unsigned int var) const
return true if the variable is a proxied variable
Parameters
var is the id of the variable
Returns
true when var is a proxied variable
Definition at line 195 of file memory.cpp.
References proxied_variables.
Referenced by align().
is_actual_parm_loaded()
bool memory::is_actual_parm_loaded (unsigned int var) const
return true in case the actual parameter has to be initialized from a stored value
Definition at line 551 of file memory.cpp.
References actual_parm_loaded.
Referenced by increment_n_mem_operations().
is_external_variable()
bool memory::is_external_variable (unsigned int var) const
Test if a variable is into the set of variables out of the top function.
Definition at line 322 of file memory.cpp.
References external.
Referenced by get_source_values().
is_internal_variable()
bool memory::is_internal_variable (unsigned int funID_scope, unsigned int var) const
Test if a variable is allocated into the specified function.
Definition at line 317 of file memory.cpp.
Referenced by get_source_values().
is_parameter()
bool memory::is_parameter (unsigned int funID_scope, unsigned int var) const
Test if a variable is into the set of interface registers.
Definition at line 343 of file memory.cpp.
References parameter.
Referenced by get_source_values().
is_parm_decl_copied()
bool memory::is_parm_decl_copied (unsigned int var) const
return true in case the parm_decl parameter has to be copied from the caller
Definition at line 531 of file memory.cpp.
References parm_decl_copied.
Referenced by increment_n_mem_operations().
is_parm_decl_stored()
bool memory::is_parm_decl_stored (unsigned int var) const
return true in case the parm_decl parameter has to be initialized from the formal value
Definition at line 541 of file memory.cpp.
References parm_decl_stored.
Referenced by increment_n_mem_operations().
is_private_memory()
bool memory::is_private_memory (unsigned int var) const
Return true in case the variable is private.
Parameters
var is the index of the variable
Returns
true in case the variable is private
Definition at line 327 of file memory.cpp.
References private_memories.
Referenced by add_internal_symbol(), add_internal_variable(), count_non_private_internal_symbols(), fu_binding::fill_array_ref_memory(), get_first_address(), get_last_address(), and get_source_values().
is_read_only_variable()
bool memory::is_read_only_variable (unsigned var) const
return true when the variable is only read
Parameters
var is the variable id
Returns
true when variable is only read, false otherwise
Definition at line 205 of file memory.cpp.
References read_only_vars.
Referenced by align().
is_sds_var()
bool memory::is_sds_var (unsigned int var) const
check if the variable is always accessed with the same data size
Parameters
var is the variable id
Returns
true when the variable is always accessed with the same data size, false otherwise
Definition at line 332 of file memory.cpp.
References has_sds_var(), same_data_size_accesses, STR, and THROW_ASSERT.
Referenced by get_source_values().
notEQ()
bool memory::notEQ (refcount< memory > ref) const
return true in case the current memory object and the passed one are different
Definition at line 732 of file memory.cpp.
References actual_parm_loaded, all_pointers_resolved, bram_bitsize, bus_addr_bitsize, bus_data_bitsize, bus_size_bitsize, callSites, external, external_base_address_alignment, implicit_memcpy, in_vars, intern_shared_data, internal, internal_base_address_alignment, internal_base_address_start, internal_variable_proxy, maxbram_bitsize, maximum_loads, maximum_private_memory_size, maximum_references, need_bus, next_base_address, next_off_base_address, null_pointer_check, off_base_address, packed_vars, parameter, parameter_alignment, params, parm_decl_copied, parm_decl_stored, pointer_conversion, private_memories, proxied_variables, rangesize, read_only_vars, same_data_size_accesses, total_amount_of_parameter_memory, total_amount_of_private_memory, unaligned_accesses, and use_unknown_addresses.
Referenced by get_parameter_alignment().
propagate_memory_parameters()
void memory::propagate_memory_parameters (const structural_objectRef src, const structural_managerRef tgt) [static]
Propagates the memory parameters from the source (innermost) module to the target (outermost) one.
Definition at line 569 of file memory.cpp.
References structural_object::AddParameter(), structural_object::ExistsParameter(), structural_manager::get_circ(), structural_object::GetParameter(), MEMORY_PARAMETER, structural_object::SetParameter(), and THROW_ERROR.
Referenced by fu_binding::add_to_SM(), allocation::BuildProxyWrapper(), WB4Intercon_interface::exec(), get_parameter_alignment(), cs_interface::InternalExec(), minimal_interface::InternalExec(), top_entity_parallel_cs::InternalExec(), TopEntityMemoryMapped::InternalExec(), top_entity::InternalExec(), WB4_interface::InternalExec(), and datapath_parallel_cs::InternalExec().
reserve_space()
void memory::reserve_space (unsigned int space)
Explicitly allocate a certain space in the external memory.
Definition at line 510 of file memory.cpp.
References align(), internal_base_address_alignment, and next_off_base_address.
Referenced by increment_n_mem_operations().
set_all_pointers_resolved()
void memory::set_all_pointers_resolved (bool resolved) [inline]
define if all pointers have statically resolved
Definition at line 727 of file memory.hpp.
set_bram_bitsize()
void memory::set_bram_bitsize (unsigned int bitsize) [inline]
set the BRAM bitsize
Definition at line 573 of file memory.hpp.
set_bus_data_bitsize()
void memory::set_bus_data_bitsize (unsigned int bitsize) [inline]
set the bus data bitsize
Definition at line 541 of file memory.hpp.
set_bus_size_bitsize()
void memory::set_bus_size_bitsize (unsigned int bitsize) [inline]
set the bus size bitsize
Definition at line 557 of file memory.hpp.
set_implicit_memcpy()
void memory::set_implicit_memcpy (bool cond) [inline]
define if there exist an implicit call of memcpy
Definition at line 760 of file memory.hpp.
set_intern_shared_data()
void memory::set_intern_shared_data (bool has_accesses) [inline]
define if the Spec has data that can be externally accessed
Definition at line 605 of file memory.hpp.
set_internal_base_address_alignment()
void memory::set_internal_base_address_alignment (unsigned int _internal_base_address_alignment)
set the internal base address alignment
Parameters
_internal_base_address_alignment is the new alignment
Definition at line 561 of file memory.cpp.
References align(), internal_base_address_alignment, internal_base_address_start, next_base_address, and THROW_ASSERT.
Referenced by get_parameter_alignment().
set_maxbram_bitsize()
void memory::set_maxbram_bitsize (unsigned int bitsize) [inline]
set the maximum BRAM bitsize
Definition at line 589 of file memory.hpp.
set_maximum_loads()
void memory::set_maximum_loads (unsigned int var, size_t n_refs) [inline]
define the maximum number of loads for a given variable
Parameters
var is variable
n_refs is the number of loads
Definition at line 643 of file memory.hpp.
set_maximum_references()
void memory::set_maximum_references (unsigned int var, size_t n_refs) [inline]
define the maximum number of references for a given variable
Parameters
var is variable
n_refs is the number of references
Definition at line 623 of file memory.hpp.
set_packed_vars()
void memory::set_packed_vars (bool packed) [inline]
update the the packed variables status
Parameters
packed is true when there is at least one packed variables
Definition at line 744 of file memory.hpp.
set_pointer_conversion()
void memory::set_pointer_conversion (bool accesses) [inline]
set if a pointer conversion happen
Definition at line 695 of file memory.hpp.
set_sds_var()
void memory::set_sds_var (unsigned int var, bool value)
set if a variable is always accessed with the same data size or not
Parameters
var is the variable id
value is true when the variable is always accessed with the same data size or false otherwise
Definition at line 275 of file memory.cpp.
References same_data_size_accesses.
Referenced by align().
set_unaligned_accesses()
void memory::set_unaligned_accesses (bool accesses) [inline]
set if LOADs or STOREs perform unaligned accesses
Definition at line 711 of file memory.hpp.
set_use_unknown_addresses()
void memory::set_use_unknown_addresses (bool accesses) [inline]
define if there exist an object used by the Spec with an address not known at compile time
Definition at line 679 of file memory.hpp.
xwrite()
void memory::xwrite (xml_element * node)
Writes the current memory allocation into an XML description.
Definition at line 651 of file memory.cpp.
References xml_child::add_child_element(), external, tree_helper::name_function(), off_base_address, parameter, STR, TreeM, WRITE_XNVM, and WRITE_XVM.
Referenced by get_parameter_alignment(), and HLS_manager::xwrite().
Field Documentation
actual_parm_loaded
CustomOrderedSet<unsigned int> memory::actual_parm_loaded [private]
actual parameter that has to be loaded from a stored value
Definition at line 115 of file memory.hpp.
Referenced by add_actual_parm_loaded(), is_actual_parm_loaded(), and notEQ().
all_pointers_resolved
bool memory::all_pointers_resolved [private]
is true when all pointers are resolved statically
Definition at line 163 of file memory.hpp.
Referenced by has_all_pointers_resolved(), and notEQ().
bram_bitsize
unsigned int memory::bram_bitsize [private]
bram bitsize
Definition at line 145 of file memory.hpp.
Referenced by get_bram_bitsize(), and notEQ().
bus_addr_bitsize
const unsigned& memory::bus_addr_bitsize [private]
Definition at line 195 of file memory.hpp.
Referenced by compute_next_base_address(), and notEQ().
bus_data_bitsize
unsigned int memory::bus_data_bitsize [private]
bus data bitsize
Definition at line 139 of file memory.hpp.
Referenced by get_bus_data_bitsize(), and notEQ().
bus_size_bitsize
unsigned int memory::bus_size_bitsize [private]
bus size bitsize
Definition at line 142 of file memory.hpp.
Referenced by get_bus_size_bitsize(), and notEQ().
callSites
std::map<unsigned int, memory_symbolRef> memory::callSites [private]
set of call sites for __builtin_wait_call
Definition at line 97 of file memory.hpp.
Referenced by add_internal_symbol(), get_callSite_base_address(), get_callSites(), get_symbol(), has_base_address(), has_callSite_base_address(), and notEQ().
external
std::map<unsigned int, memory_symbolRef> memory::external [private]
set of variables allocated outside the top module
Definition at line 73 of file memory.hpp.
Referenced by add_external_symbol(), add_internal_symbol(), add_parameter_symbol(), get_ext_memory_variables(), get_external_base_address(), get_symbol(), has_base_address(), has_external_base_address(), is_external_variable(), notEQ(), and xwrite().
external_base_address_alignment
unsigned int memory::external_base_address_alignment [private]
external address alignment
Definition at line 172 of file memory.hpp.
Referenced by add_external_symbol(), memory(), and notEQ().
implicit_memcpy
bool memory::implicit_memcpy [private]
when true an implicit memcpy is called
Definition at line 166 of file memory.hpp.
Referenced by has_implicit_memcpy(), and notEQ().
in_vars
std::map<unsigned int, memory_symbolRef> memory::in_vars [private]
set of all the internal variables
Definition at line 87 of file memory.hpp.
Referenced by add_external_symbol(), add_internal_symbol(), add_internal_variable(), add_parameter_symbol(), count_non_private_internal_symbols(), get_internal_base_address(), get_symbol(), has_base_address(), has_internal_base_address(), and notEQ().
intern_shared_data
bool memory::intern_shared_data [private]
define if the Spec has data that can be externally accessed
Definition at line 151 of file memory.hpp.
Referenced by has_intern_shared_data(), and notEQ().
internal
std::map<unsigned int, std::map<unsigned int, memory_symbolRef> > memory::internal [private]
set of variables allocated internally to the cores, classified by function id
Definition at line 76 of file memory.hpp.
Referenced by notEQ().
internal_base_address_alignment
unsigned int memory::internal_base_address_alignment [private]
internal address alignment
Definition at line 169 of file memory.hpp.
Referenced by add_internal_symbol(), add_parameter(), get_internal_base_address_alignment(), memory(), notEQ(), reserve_space(), and set_internal_base_address_alignment().
internal_base_address_start
unsigned int memory::internal_base_address_start [private]
is the start internal address
Definition at line 121 of file memory.hpp.
Referenced by add_internal_variable(), get_allocated_intern_memory(), get_allocated_space(), get_max_address(), memory(), notEQ(), and set_internal_base_address_alignment().
internal_variable_proxy
std::map<unsigned int, CustomOrderedSet<unsigned int> > memory::internal_variable_proxy [private]
set of variable proxies accessed by a function
Definition at line 79 of file memory.hpp.
Referenced by add_internal_variable_proxy(), get_proxied_internal_variables(), has_proxied_internal_variables(), and notEQ().
maxbram_bitsize
unsigned int memory::maxbram_bitsize [private]
maximum bram bitsize
Definition at line 148 of file memory.hpp.
Referenced by get_maxbram_bitsize(), and notEQ().
maximum_loads
std::map<unsigned int, size_t> memory::maximum_loads [private]
define for each variable the number of loads whenever it is possible
Definition at line 187 of file memory.hpp.
Referenced by notEQ().
maximum_private_memory_size
unsigned int memory::maximum_private_memory_size [private]
is the maximum amount of private memory allocated
Definition at line 124 of file memory.hpp.
Referenced by add_internal_symbol(), get_max_address(), and notEQ().
maximum_references
std::map<unsigned int, size_t> memory::maximum_references [private]
define for each variable the number of references whenever it is possible
Definition at line 184 of file memory.hpp.
Referenced by notEQ().
n_mem_operations_per_var
std::map<unsigned int, unsigned int> memory::n_mem_operations_per_var [private]
number of LOAD/STORE per var
Definition at line 178 of file memory.hpp.
need_bus
CustomOrderedSet<unsigned int> memory::need_bus [private]
define for each variable the number of loads whenever it is possible
Definition at line 190 of file memory.hpp.
Referenced by notEQ().
next_base_address
unsigned int memory::next_base_address [private]
it represents the next address that is available for internal allocation
Definition at line 118 of file memory.hpp.
Referenced by add_internal_symbol(), add_internal_variable(), add_parameter(), add_parameter_symbol(), get_allocated_space(), get_max_address(), memory(), notEQ(), and set_internal_base_address_alignment().
next_off_base_address
unsigned int memory::next_off_base_address [private]
it represents the next address that is available to allocate a variable out of the top module
Definition at line 136 of file memory.hpp.
Referenced by add_external_symbol(), add_external_variable(), get_memory_address(), notEQ(), and reserve_space().
null_pointer_check
bool memory::null_pointer_check [private]
when false object could be allocated starting from address 0
Definition at line 181 of file memory.hpp.
Referenced by add_internal_variable(), memory(), and notEQ().
off_base_address
unsigned int memory::off_base_address [private]
it represents the base address of the external memory
Definition at line 133 of file memory.hpp.
Referenced by notEQ(), and xwrite().
packed_vars
bool memory::packed_vars [private]
true when packed vars are used
Definition at line 193 of file memory.hpp.
Referenced by has_packed_vars(), and notEQ().
parameter
std::map<unsigned int, std::map<unsigned int, memory_symbolRef> > memory::parameter [private]
set of variables allocated in registers of the interface
Definition at line 93 of file memory.hpp.
Referenced by add_external_symbol(), add_internal_symbol(), add_parameter_symbol(), get_first_address(), get_function_parameters(), get_parameter_base_address(), get_symbol(), has_parameter_base_address(), is_parameter(), notEQ(), and xwrite().
parameter_alignment
const unsigned int memory::parameter_alignment [private]
parameter alignment
Definition at line 175 of file memory.hpp.
Referenced by add_parameter_symbol(), get_parameter_alignment(), and notEQ().
params
std::map<unsigned int, memory_symbolRef> memory::params [private]
set of all the internal parameters
Definition at line 95 of file memory.hpp.
Referenced by add_parameter_symbol(), has_base_address(), and notEQ().
parm_decl_copied
CustomOrderedSet<unsigned int> memory::parm_decl_copied [private]
parm_decl that has to be copied from the caller
Definition at line 109 of file memory.hpp.
Referenced by add_parm_decl_copied(), is_parm_decl_copied(), and notEQ().
parm_decl_stored
CustomOrderedSet<unsigned int> memory::parm_decl_stored [private]
parm_decl storage has to be initialized from the formal parameter
Definition at line 112 of file memory.hpp.
Referenced by add_parm_decl_stored(), is_parm_decl_stored(), and notEQ().
pointer_conversion
bool memory::pointer_conversion [private]
true when at least one pointer conversion happen
Definition at line 157 of file memory.hpp.
Referenced by has_pointer_conversion(), and notEQ().
private_memories
CustomOrderedSet<unsigned int> memory::private_memories [private]
store the objects that does not need to be attached to the bus
Definition at line 100 of file memory.hpp.
Referenced by add_private_memory(), is_private_memory(), and notEQ().
proxied_variables
CustomOrderedSet<unsigned int> memory::proxied_variables [private]
is the set of proxied variables
Definition at line 82 of file memory.hpp.
Referenced by add_internal_variable_proxy(), is_a_proxied_variable(), and notEQ().
rangesize
std::map<unsigned int, unsigned int> memory::rangesize [private]
for each var store the address space rangesize associated with it
Definition at line 90 of file memory.hpp.
Referenced by add_internal_symbol(), get_rangesize(), and notEQ().
read_only_vars
CustomOrderedSet<unsigned int> memory::read_only_vars [private]
Definition at line 84 of file memory.hpp.
Referenced by add_read_only_variable(), is_read_only_variable(), and notEQ().
same_data_size_accesses
std::map<unsigned int, unsigned int> memory::same_data_size_accesses [private]
store if a given variable is accessed always with the same data_size or not
Definition at line 103 of file memory.hpp.
Referenced by has_sds_var(), is_sds_var(), notEQ(), and set_sds_var().
source_values
std::map<unsigned int, CustomOrderedSet<unsigned int> > memory::source_values [private]
ssa_names assigned to a given memory variable
Definition at line 106 of file memory.hpp.
Referenced by add_source_value().
total_amount_of_parameter_memory
unsigned int memory::total_amount_of_parameter_memory [private]
total amount of parameter memory
Definition at line 130 of file memory.hpp.
Referenced by add_parameter(), add_parameter_symbol(), get_allocated_parameters_memory(), and notEQ().
total_amount_of_private_memory
unsigned int memory::total_amount_of_private_memory [private]
total amount of internal memory allocated
Definition at line 127 of file memory.hpp.
Referenced by add_internal_symbol(), get_allocated_space(), and notEQ().
TreeM
const tree_managerRef memory::TreeM [private]
datastructure containing tree information
Definition at line 70 of file memory.hpp.
Referenced by add_external_variable(), add_internal_symbol(), add_internal_variable(), compute_next_base_address(), get_last_address(), and xwrite().
unaligned_accesses
bool memory::unaligned_accesses [private]
true when LOADs or STOREs perform unaligned accesses
Definition at line 160 of file memory.hpp.
Referenced by has_unaligned_accesses(), and notEQ().
use_unknown_addresses
bool memory::use_unknown_addresses [private]
Spec accesses data having an address unknown at compile time.
Definition at line 154 of file memory.hpp.
Referenced by has_unknown_addresses(), and notEQ().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/memory.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/memory.cpp