objective_function Class Reference
#include <objective_function.hpp>
Public Member Functions
virtual void print (std::ostream &) const
This method prints the class to the standard output stream.
virtual void set_objective_function (meilp_solverRef const &MS, problem_dimRef const &p_dimension)=0
objective_function ()
The class constructor.
virtual ~objective_function ()
The class Destructor.
Detailed Description
Definition at line 63 of file objective_function.hpp.
Constructor & Destructor Documentation
objective_function()
objective_function::objective_function () [default]
The class constructor.
Referenced by print().
 objective_function()
objective_function::~objective_function () [virtual], [default]
The class Destructor.
Referenced by print().
Member Function Documentation
print()
virtual void objective_function::print (std::ostream &) const [inline], [virtual]
This method prints the class to the standard output stream.
Parameters
os the output stream.
Definition at line 71 of file objective_function.hpp.
References objective_function(), set_objective_function(), and ~objective_function().
set_objective_function()
virtual void objective_function::set_objective_function (meilp_solverRef const & MS, problem_dimRef const & p_dimension) [pure virtual]
Referenced by print().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/ilp/objective_function.hpp
/home/osboxes/bambu/PandA-bambu/src/ilp/objective_function.cpp