event_o Class Reference
This class describes a generic event.
#include <structural_objects.hpp>
Public Member Functions
event_o (int debug_level, const structural_objectRef o)
Constructor.
~event_o () override=default
Destructor.
void copy (structural_objectRef dest) const override
Perform a copy of the event.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the event (for debug purpose)
Additional Inherited Members
Detailed Description
This class describes a generic event.
Definition at line 1200 of file structural_objects.hpp.
Constructor & Destructor Documentation
event_o()
event_o::event_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the event
Definition at line 1639 of file structural_objects.cpp.
 event_o()
event_o::~event_o () [override], [default]
Destructor.
Member Function Documentation
copy()
void event_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the event.
Parameters
dest destination object.
Reimplemented from structural_object.
Definition at line 1649 of file structural_objects.cpp.
References structural_object::copy().
find_isomorphic()
structural_objectRef event_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Definition at line 1654 of file structural_objects.cpp.
References THROW_ERROR.
find_member()
structural_objectRef event_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
This method throw and error since does not have associated any structural object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 1643 of file structural_objects.cpp.
References THROW_ERROR.
print()
void event_o::print (std::ostream & os) const [override], [virtual]
Print the event (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Definition at line 1671 of file structural_objects.cpp.
References structural_object::PP, and structural_object::print().
xload()
void event_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
Reimplemented from structural_object.
Definition at line 1660 of file structural_objects.cpp.
References structural_object::xload().
xwrite()
void event_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Definition at line 1665 of file structural_objects.cpp.
References xml_child::add_child_element(), structural_object::get_kind_text(), and structural_object::xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp