/home/osboxes/bambu/PandA-bambu/src/HLS/stg/BB_based_stg.cpp File Reference
#include `BB_based_stg.hpp`
#include `Parameter.hpp`
#include `loop.hpp`
#include `loops.hpp`
#include `basic_block.hpp`
#include `call_graph_manager.hpp`
#include `function_behavior.hpp`
#include `op_graph.hpp`
#include <boost/graph/depth_first_search.hpp>
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/incremental_components.hpp>
#include `hls.hpp`
#include `hls_constraints.hpp`
#include `fu_binding.hpp`
#include `functions.hpp`
#include `allocation_information.hpp`
#include `schedule.hpp`
#include `StateTransitionGraph_constructor.hpp`
#include `state_transition_graph.hpp`
#include `state_transition_graph_manager.hpp`
#include `Discrepancy.hpp`
#include <cmath>
#include `technology_manager.hpp`
#include `technology_node.hpp`
#include `time_model.hpp`
#include `behavioral_helper.hpp`
#include `call_graph.hpp`
#include `omp_functions.hpp`
#include `tree_basic_block.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `custom_map.hpp`
#include `custom_set.hpp`
#include <boost/foreach.hpp>
#include `cpu_time.hpp`
#include `dbgPrintHelper.hpp`
#include `string_manipulation.hpp`
Functions
static void add_in_sched_order (std::list< vertex > &statement_list, vertex stmt, const ScheduleConstRef sch, const OpGraphConstRef ASSERT_PARAMETER(dfg))
static void add_EPP_edges (const StateTransitionGraphManagerRef &STG)
static size_t compute_edge_increments (const StateTransitionGraphManagerRef &STG)
Function Documentation
add_EPP_edges()
static void add_EPP_edges (const StateTransitionGraphManagerRef & STG) [static]
Definition at line 752 of file BB_based_stg.cpp.
References StateTransitionGraphManager::get_entry_state(), StateTransitionGraphManager::get_exit_state(), StateTransitionGraphManager::GetStg(), StateTransitionGraphManager::STG_builder, and THROW_ASSERT.
Referenced by BB_based_stg::compute_EPP_edge_increments().
add_in_sched_order()
static void add_in_sched_order (std::list< vertex > & statement_list, vertex stmt, const ScheduleConstRef sch, const OpGraphConstRef ASSERT_PARAMETERdfg) [static]
Definition at line 144 of file BB_based_stg.cpp.
References GET_NAME, and THROW_ASSERT.
Referenced by BB_based_stg::InternalExec().
compute_edge_increments()
static size_t compute_edge_increments (const StateTransitionGraphManagerRef & STG) [static]
Definition at line 790 of file BB_based_stg.cpp.
References StateTransitionGraphManager::GetEPPStg(), max(), and THROW_UNREACHABLE.
Referenced by BB_based_stg::compute_EPP_edge_increments().