TestVectorParser Class Reference
#include <test_vector_parser.hpp>
Public Member Functions
TestVectorParser (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
~TestVectorParser () override
Destructor.
void Initialize () override
Initializes the data needed for execution.
DesignFlowStep_Status Exec () override
Executes the step.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the HLS relationships of this step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
void ParseUserString (std::vector< std::map< std::string, std::string >> &test_vectors) const
Parse a user defined string extracting the test vectors.
void ParseXMLFile (std::vector< std::map< std::string, std::string >> &test_vectors) const
Parse a user defined xml file extracting the test vectors.
size_t ParseTestVectors (std::vector< std::map< std::string, std::string >> &test_vectors) const
Parses the test vectors using one of ParseUserString() or ParseXMLFile(), depending on internal parameters set from Initialize()
Private Attributes
std::string input_xml_filename
std::string user_input_string
Additional Inherited Members
Detailed Description
Definition at line 48 of file test_vector_parser.hpp.
Constructor & Destructor Documentation
TestVectorParser()
TestVectorParser::TestVectorParser (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
behavior include
boost include design_flows include frontend_analysis HLS/ include include from HLS/simulation parser/polixml include polixml include STL include tree/ include utility includes wrapper/treegcc include
Definition at line 91 of file test_vector_parser.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, TEST_VECTOR_PARSER, and ~TestVectorParser().
 TestVectorParser()
TestVectorParser::~TestVectorParser () [override], [default]
Destructor.
Referenced by TestVectorParser().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > TestVectorParser::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [virtual]
Compute the HLS relationships of this step.
Reimplemented from HLS_step.
Definition at line 292 of file test_vector_parser.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLS_SYNTHESIS_FLOW, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and TOP_FUNCTION.
Exec()
DesignFlowStep_Status TestVectorParser::Exec () [override], [virtual]
Executes the step.
Implements DesignFlowStep.
Definition at line 282 of file test_vector_parser.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_MINIMUM, HLS_step::HLSMgr, INDENT_DBG_MEX, ParseTestVectors(), STR, and SUCCESS.
HasToBeExecuted()
bool TestVectorParser::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 316 of file test_vector_parser.cpp.
Initialize()
void TestVectorParser::Initialize () [override], [virtual]
Initializes the data needed for execution.
It's something similar to a constructor, but it runs just before execution. The reason is that some data needed for the execution may not be present when the step is created and they need to be retreived just before the execution
Reimplemented from DesignFlowStep.
Definition at line 260 of file test_vector_parser.cpp.
References HLS_step::HLSMgr, DesignFlowStep::Initialize(), input_xml_filename, DesignFlowStep::parameters, THROW_UNREACHABLE, and user_input_string.
ParseTestVectors()
size_t TestVectorParser::ParseTestVectors (std::vector< std::map< std::string, std::string >> & test_vectors) const [private]
Parses the test vectors using one of ParseUserString() or ParseXMLFile(), depending on internal parameters set from Initialize()
Parameters
out test_vectors Where the parsed test vectors are stored
Definition at line 243 of file test_vector_parser.cpp.
References input_xml_filename, ParseUserString(), ParseXMLFile(), THROW_UNREACHABLE, and user_input_string.
Referenced by Exec().
ParseUserString()
void TestVectorParser::ParseUserString (std::vector< std::map< std::string, std::string >> & test_vectors) const [private]
Parse a user defined string extracting the test vectors.
Parameters
out test_vectors Where the parsed test vectors are stored
pre-processing to support arrays
Definition at line 98 of file test_vector_parser.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, index, SplitString(), THROW_ERROR, and user_input_string.
Referenced by ParseTestVectors().
ParseXMLFile()
void TestVectorParser::ParseXMLFile (std::vector< std::map< std::string, std::string >> & test_vectors) const [private]
Parse a user defined xml file extracting the test vectors.
If discrepancy is enabled, then xml output is ignored
Definition at line 131 of file test_vector_parser.cpp.
References xml_child::add_child_element(), BuildPath(), xml_document::create_root_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, XMLDomParser::Exec(), fileIO_istream_open(), xml_child::get_children(), XMLDomParser::get_document(), BehavioralHelper::get_parameters(), GetDirectory(), BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, INDENT_DBG_MEX, input_xml_filename, BehavioralHelper::is_a_pointer(), BehavioralHelper::is_bool(), DesignFlowStep::parameters, test_panda::parser, BehavioralHelper::PrintVariable(), attribute_sequence::set_attribute(), STR, THROW_ASSERT, THROW_ERROR, THROW_WARNING, and xml_document::write_to_file_formatted().
Referenced by ParseTestVectors().
Field Documentation
input_xml_filename
std::string TestVectorParser::input_xml_filename [private]
Definition at line 51 of file test_vector_parser.hpp.
Referenced by Initialize(), ParseTestVectors(), and ParseXMLFile().
user_input_string
std::string TestVectorParser::user_input_string [private]
Definition at line 53 of file test_vector_parser.hpp.
Referenced by Initialize(), ParseTestVectors(), and ParseUserString().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/test_vector_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/test_vector_parser.cpp