QuartusWrapper Class Reference
#include <quartus_wrapper.hpp>
Public Member Functions
QuartusWrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~QuartusWrapper () override
Destructor.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Additional Inherited Members
Detailed Description
Definition at line 53 of file quartus_wrapper.hpp.
Constructor & Destructor Documentation
QuartusWrapper()
QuartusWrapper::QuartusWrapper (const ParameterConstRef & _Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Header include.
Parameters
Param is the set of parameters
output_dir is the directory where to save all the results
wrapper/synthesis include
Definition at line 49 of file quartus_wrapper.cpp.
References ~QuartusWrapper().
 QuartusWrapper()
QuartusWrapper::~QuartusWrapper () [override], [default]
Destructor.
Referenced by QuartusWrapper().
Member Function Documentation
get_command_line()
std::string QuartusWrapper::get_command_line (const DesignParametersRef & dp) const [override], [virtual]
Returns the proper command line.
Implements AlteraWrapper.
Definition at line 54 of file quartus_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, AlteraWrapper::toString(), and SynthesisTool::xml_tool_options.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_wrapper.cpp