GenerateSimulationScripts Class Reference
superclass include
#include <generate_simulation_scripts.hpp>
Public Member Functions
GenerateSimulationScripts (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~GenerateSimulationScripts () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
superclass include
Definition at line 46 of file generate_simulation_scripts.hpp.
Constructor & Destructor Documentation
GenerateSimulationScripts()
GenerateSimulationScripts::GenerateSimulationScripts (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
behavior include
circuit include STD include STL include utility include
Definition at line 90 of file generate_simulation_scripts.cpp.
References DesignFlowStep::debug_level, GENERATE_SIMULATION_SCRIPT, GET_CLASS, and ~GenerateSimulationScripts().
 GenerateSimulationScripts()
GenerateSimulationScripts::~GenerateSimulationScripts () [override], [default]
Destructor.
Referenced by GenerateSimulationScripts().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > GenerateSimulationScripts::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 98 of file generate_simulation_scripts.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, GENERATE_HDL, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TESTBENCH_GENERATION, THROW_UNREACHABLE, and TOP_FUNCTION.
Exec()
DesignFlowStep_Status GenerateSimulationScripts::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 123 of file generate_simulation_scripts.cpp.
References SimulationTool::CreateSimulationTool(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BackendFlow::DetermineBackendFlowType(), structural_manager::get_circ(), structural_object::get_id(), HLS_step::HLSMgr, SimulationTool::ICARUS, INDENT_DBG_MEX, SimulationTool::ISIM, BackendFlow::LATTICE_FPGA, SimulationTool::MODELSIM, DesignFlowStep::parameters, SUCCESS, THROW_ASSERT, THROW_ERROR, hls::top, SimulationTool::VERILATOR, and SimulationTool::XSIM.
HasToBeExecuted()
bool GenerateSimulationScripts::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 180 of file generate_simulation_scripts.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/backend/generate_simulation_scripts.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/backend/generate_simulation_scripts.cpp