bipartite_matching_clique_covering< vertex_type > Class Template Reference
clique covering based on bipartite matching procedure
#include <clique_covering.hpp>
Public Member Functions
bipartite_matching_clique_covering ()
constructor
C_vertex add_vertex (const vertex_type &element, const std::string &name) override
add a vertex
void add_edge (const vertex_type &src, const vertex_type &dest, int _weight) override
add an edge
size_t num_vertices () override
return the number of vertices of the clique
CustomOrderedSet< vertex_type > get_clique (unsigned int i) override
Returns a clique.
void extend_and_assign (boost::numeric::ublas::matrix< int > &cost_matrix, size_t &final_num_cols, size_t num_rows)
void exec (const filter_clique< vertex_type > &fc, check_clique< vertex_type > &) override
Abstract method that will execute clique covering algorithm.
void writeDot (const std::string &filename) const override
Writes a dotty representation of the actual graph.
void add_subpartitions (size_t id, vertex_type v) override
add subpartitions over which bipartite matching can start on
void suggest_min_resources (size_t n_resources) override
suggest that the problem have at least a given number of resources
void min_resources (size_t n_resources) override
specify the minimum number of resources
void suggest_max_resources (size_t) override
suggest that the problem have at worst no more than the given number of resources
void max_resources (size_t) override
specify the maximum number of resources
Private Member Functions
size_t color_the_cc_compatibility_graph (const boost_cc_compatibility_graph &CG)
partition the set of vertex in set where each element is in conflict with the others the maximum size of these sets is the number of the cliques used to cover the graph
Private Attributes
boost_cc_compatibility_graph clique_covering_graph_bulk
bulk undirected graph
std::vector< CustomUnorderedSet< C_vertex > > cliques
set of maximal clique computed
std::map< vertex_type, C_vertex > v2uv
map between vertex_type and C_vertex
std::map< C_vertex, vertex_type > uv2v
map between C_vertex and vertex_type
std::map< C_vertex, std::string > names
name map for the C_vertex vertices
int max_weight
maximum weight
std::map< size_t, CustomOrderedSet< boost::graph_traits< boost_cc_compatibility_graph >::vertex_descriptor > > partitions
size_t num_cols
Static Private Attributes
static const int COMPATIBILITY_EDGE = 1
edge selector
static const int COMPATIBILITY_ALL_EDGES = ~0
static const int BIG_NUMBER = 10000000
Additional Inherited Members
Detailed Description
template<typename vertex_type>
class bipartite_matching_clique_covering< vertex_type >
clique covering based on bipartite matching procedure
Definition at line 1433 of file clique_covering.hpp.
Constructor & Destructor Documentation
bipartite_matching_clique_covering()
template<typename vertex_type >
bipartite_matching_clique_covering< vertex_type >::bipartite_matching_clique_covering () [inline]
constructor
Definition at line 1496 of file clique_covering.hpp.
Member Function Documentation
add_edge()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::add_edge (const vertex_type & src, const vertex_type & dest, int _weight) [inline], [override], [virtual]
add an edge
Implements clique_covering< vertex_type >.
Definition at line 1513 of file clique_covering.hpp.
References max(), and THROW_ASSERT.
add_subpartitions()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::add_subpartitions (size_t id, vertex_type v) [inline], [override], [virtual]
add subpartitions over which bipartite matching can start on
Parameters
id is the subpartition id
vertex is the vertex of the given subpartition
Implements clique_covering< vertex_type >.
Definition at line 1716 of file clique_covering.hpp.
References max(), and THROW_ASSERT.
add_vertex()
template<typename vertex_type >
C_vertex bipartite_matching_clique_covering< vertex_type >::add_vertex (const vertex_type & element, const std::string & name) [inline], [override], [virtual]
add a vertex
vertex weight not considered
Implements clique_covering< vertex_type >.
Definition at line 1501 of file clique_covering.hpp.
References result, and THROW_ASSERT.
color_the_cc_compatibility_graph()
template<typename vertex_type >
size_t bipartite_matching_clique_covering< vertex_type >::color_the_cc_compatibility_graph (const boost_cc_compatibility_graph & CG) [inline], [private]
partition the set of vertex in set where each element is in conflict with the others the maximum size of these sets is the number of the cliques used to cover the graph
coloring based on DSATUR 2 heuristic
Definition at line 1455 of file clique_covering.hpp.
References boost::dsatur2_coloring(), and max().
exec()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::exec (const filter_clique< vertex_type > & fc, check_clique< vertex_type > & cq) [inline], [override], [virtual]
Abstract method that will execute clique covering algorithm.
If you want to specialize the implementation with your favourite algorithm, you have to implement this method.
Parameters
fc is the filtering clique functor used to reduce the proposed clique
now color the graph and then do the bipartite matching on the vertex having the same color
initializes the cliques with empty sets
compute the assignment for each element of a partition
already assigned to a clique
check if *v_it fit in the clique given the filtering predicate
consistency check
check if *v_it fit in the clique given the filtering predicate
undo the last step
Implements clique_covering< vertex_type >.
Definition at line 1557 of file clique_covering.hpp.
References bipartite_matching< CostFunctor >::get_solution(), filter_clique< vertex_type >::select_candidate_to_remove(), bipartite_matching< CostFunctor >::solve_bipartite_matching(), and THROW_ASSERT.
extend_and_assign()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::extend_and_assign (boost::numeric::ublas::matrix< int > & cost_matrix, size_t & final_num_cols, size_t num_rows) [inline]
Definition at line 1544 of file clique_covering.hpp.
get_clique()
template<typename vertex_type >
CustomOrderedSet<vertex_type> bipartite_matching_clique_covering< vertex_type >::get_clique (unsigned int i) [inline], [override], [virtual]
Returns a clique.
Parameters
i is the i-th clique into graph
Returns
set of elements into clique
Implements clique_covering< vertex_type >.
Definition at line 1531 of file clique_covering.hpp.
References result, and THROW_ASSERT.
max_resources()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::max_resources (size_t n_resources) [inline], [override], [virtual]
specify the maximum number of resources
Parameters
n_resources is the number of resources
Implements clique_covering< vertex_type >.
Definition at line 1738 of file clique_covering.hpp.
References flopoco::filename, check_clique< vertex_type >::initialize_structures(), max(), result, STR, THROW_ASSERT, and test_panda::type.
min_resources()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::min_resources (size_t n_resources) [inline], [override], [virtual]
specify the minimum number of resources
Parameters
n_resources is the number of resources
Implements clique_covering< vertex_type >.
Definition at line 1729 of file clique_covering.hpp.
References max().
num_vertices()
template<typename vertex_type >
size_t bipartite_matching_clique_covering< vertex_type >::num_vertices () [inline], [override], [virtual]
return the number of vertices of the clique
Implements clique_covering< vertex_type >.
Definition at line 1526 of file clique_covering.hpp.
suggest_max_resources()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::suggest_max_resources (size_t n_resources) [inline], [override], [virtual]
suggest that the problem have at worst no more than the given number of resources
Parameters
n_resources is the number of resources
Implements clique_covering< vertex_type >.
Definition at line 1734 of file clique_covering.hpp.
suggest_min_resources()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::suggest_min_resources (size_t n_resources) [inline], [override], [virtual]
suggest that the problem have at least a given number of resources
Parameters
n_resources is the number of resources available
Implements clique_covering< vertex_type >.
Definition at line 1724 of file clique_covering.hpp.
References min.
writeDot()
template<typename vertex_type >
void bipartite_matching_clique_covering< vertex_type >::writeDot (const std::string & filename) const [inline], [override], [virtual]
Writes a dotty representation of the actual graph.
Parameters
filename is the output filename
Implements clique_covering< vertex_type >.
Definition at line 1710 of file clique_covering.hpp.
Field Documentation
BIG_NUMBER
template<typename vertex_type >
const int bipartite_matching_clique_covering< vertex_type >::BIG_NUMBER = 10000000 [static], [private]
Definition at line 1451 of file clique_covering.hpp.
clique_covering_graph_bulk
template<typename vertex_type >
boost_cc_compatibility_graph bipartite_matching_clique_covering< vertex_type >::clique_covering_graph_bulk [private]
bulk undirected graph
Definition at line 1437 of file clique_covering.hpp.
cliques
template<typename vertex_type >
std::vector<CustomUnorderedSet<C_vertex> > bipartite_matching_clique_covering< vertex_type >::cliques [private]
set of maximal clique computed
Definition at line 1439 of file clique_covering.hpp.
COMPATIBILITY_ALL_EDGES
template<typename vertex_type >
const int bipartite_matching_clique_covering< vertex_type >::COMPATIBILITY_ALL_EDGES = ~0 [static], [private]
Definition at line 1450 of file clique_covering.hpp.
COMPATIBILITY_EDGE
template<typename vertex_type >
const int bipartite_matching_clique_covering< vertex_type >::COMPATIBILITY_EDGE = 1 [static], [private]
edge selector
Definition at line 1449 of file clique_covering.hpp.
max_weight
template<typename vertex_type >
int bipartite_matching_clique_covering< vertex_type >::max_weight [private]
maximum weight
Definition at line 1447 of file clique_covering.hpp.
names
template<typename vertex_type >
std::map<C_vertex, std::string> bipartite_matching_clique_covering< vertex_type >::names [private]
name map for the C_vertex vertices
Definition at line 1445 of file clique_covering.hpp.
num_cols
template<typename vertex_type >
size_t bipartite_matching_clique_covering< vertex_type >::num_cols [private]
Definition at line 1492 of file clique_covering.hpp.
partitions
template<typename vertex_type >
std::map<size_t, CustomOrderedSet<boost::graph_traits<boost_cc_compatibility_graph>::vertex_descriptor> > bipartite_matching_clique_covering< vertex_type >::partitions [private]
Definition at line 1490 of file clique_covering.hpp.
uv2v
template<typename vertex_type >
std::map<C_vertex, vertex_type> bipartite_matching_clique_covering< vertex_type >::uv2v [private]
map between C_vertex and vertex_type
Definition at line 1443 of file clique_covering.hpp.
v2uv
template<typename vertex_type >
std::map<vertex_type, C_vertex> bipartite_matching_clique_covering< vertex_type >::v2uv [private]
map between vertex_type and C_vertex
Definition at line 1441 of file clique_covering.hpp.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/clique_covering.hpp