TTT_based_clique_covering< vertex_type > Class Template Reference
#include <clique_covering.hpp>
Public Member Functions
TTT_based_clique_covering (bool _all_edges)
constructor
void do_clique_covering (const cc_compatibility_graphRef CG, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > &ds, CustomUnorderedSet< C_vertex > &support, const CustomUnorderedSet< C_vertex > &all_vertices, const filter_clique< vertex_type > &fc) override
Additional Inherited Members
Detailed Description
template<typename vertex_type>
class TTT_based_clique_covering< vertex_type >
Definition at line 1070 of file clique_covering.hpp.
Constructor & Destructor Documentation
TTT_based_clique_covering()
template<typename vertex_type >
TTT_based_clique_covering< vertex_type >::TTT_based_clique_covering (bool _all_edges) [inline], [explicit]
constructor
Definition at line 1074 of file clique_covering.hpp.
Member Function Documentation
do_clique_covering()
template<typename vertex_type >
void TTT_based_clique_covering< vertex_type >::do_clique_covering (const cc_compatibility_graphRef CG, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > & ds, CustomUnorderedSet< C_vertex > & support, const CustomUnorderedSet< C_vertex > & all_vertices, const filter_clique< vertex_type > & fc) [inline], [override], [virtual]
update the upper bound with the last weight
do some filtering
check trivial cases
Reimplemented from coloring_based_clique_covering< vertex_type >.
Definition at line 1078 of file clique_covering.hpp.
References TTT_maximal_weighted_clique< Graph >::get_last_W_Q_max(), TTT_maximal_weighted_clique< Graph >::get_weighted_maximal_cliques(), max(), filter_clique< vertex_type >::select_candidate_to_remove(), and THROW_ASSERT.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/clique_covering.hpp