ParserFlowStep Class Reference
#include <parser_flow_step.hpp>
Public Member Functions
ParserFlowStep (const DesignFlowManagerConstRef design_flow_manager, const ParserFlowStep_Type parser_step_type, const std::string &file_name, const ParameterConstRef parameters)
Constructor.
~ParserFlowStep () override
Destructor.
const std::string GetSignature () const override
Return the signature of this step.
const std::string GetName () const override
Return the name of this design step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
Static Public Member Functions
static const std::string ComputeSignature (const ParserFlowStep_Type parser_step_type, const std::string &file_name)
Compute the signature of a parser flow step.
Protected Member Functions
virtual const std::string GetKindText () const
Return the name of the type of this frontend flow step.
Static Protected Member Functions
static const std::string EnumToKindText (const ParserFlowStep_Type parser_step_type)
Given a parser step type, return the name of the type.
Protected Attributes
const ParserFlowStep_Type parser_step_type
The type of the parse.
const std::string file_name
The name of the file to be parsed.
Additional Inherited Members
Detailed Description
Definition at line 59 of file parser_flow_step.hpp.
Constructor & Destructor Documentation
ParserFlowStep()
ParserFlowStep::ParserFlowStep (const DesignFlowManagerConstRef _design_flow_manager, const ParserFlowStep_Type _parser_step_type, const std::string & _file_name, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
parser_step_type is the type of the parser
file_name is the name of the file
parameters is the set of input parameters
design_flows include
Definition at line 50 of file parser_flow_step.cpp.
References ~ParserFlowStep().
 ParserFlowStep()
ParserFlowStep::~ParserFlowStep () [override], [default]
Destructor.
Referenced by ParserFlowStep().
Member Function Documentation
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef ParserFlowStep::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 103 of file parser_flow_step.cpp.
References DesignFlowStep::design_flow_manager, and Wrefcount< T >::lock().
ComputeRelationships()
void ParserFlowStep::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 99 of file parser_flow_step.cpp.
ComputeSignature()
const std::string ParserFlowStep::ComputeSignature (const ParserFlowStep_Type parser_step_type, const std::string & file_name) [static]
Compute the signature of a parser flow step.
Parameters
parser_step_type is the type of parser
file_name is the file name
Returns
the corresponding signature
Definition at line 67 of file parser_flow_step.cpp.
References file_name, and STR.
Referenced by create_tree_manager::ComputeRelationships(), and GetSignature().
EnumToKindText()
const std::string ParserFlowStep::EnumToKindText (const ParserFlowStep_Type parser_step_type) [static], [protected]
Given a parser step type, return the name of the type.
Parameters
type is the type to be considered
Returns
the name of the type
Definition at line 77 of file parser_flow_step.cpp.
References THROW_UNREACHABLE.
Referenced by GetKindText().
GetKindText()
const std::string ParserFlowStep::GetKindText () const [protected], [virtual]
Return the name of the type of this frontend flow step.
Definition at line 72 of file parser_flow_step.cpp.
References EnumToKindText(), and parser_step_type.
Referenced by GetName().
GetName()
const std::string ParserFlowStep::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 62 of file parser_flow_step.cpp.
References file_name, and GetKindText().
GetSignature()
const std::string ParserFlowStep::GetSignature () const [override], [virtual]
Return the signature of this step.
Implements DesignFlowStep.
Definition at line 57 of file parser_flow_step.cpp.
References ComputeSignature(), file_name, and parser_step_type.
HasToBeExecuted()
bool ParserFlowStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 94 of file parser_flow_step.cpp.
Field Documentation
file_name
const std::string ParserFlowStep::file_name [protected]
The name of the file to be parsed.
Definition at line 66 of file parser_flow_step.hpp.
Referenced by ComputeSignature(), AsnParser::Exec(), AadlParser::Exec(), GetName(), and GetSignature().
parser_step_type
const ParserFlowStep_Type ParserFlowStep::parser_step_type [protected]
The type of the parse.
Definition at line 63 of file parser_flow_step.hpp.
Referenced by GetKindText(), and GetSignature().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/parser_flow_step.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/parser_flow_step.cpp