tree_reindex Class Reference
This class is used to perform the re-index of all tree nodes.
#include <tree_reindex.hpp>
Public Types
enum { GETID =(tree_node) = 0
 }
visitor enum
Public Member Functions
~tree_reindex () override
void print (std::ostream &os) const
function that prints the class tree_reindex.
void visit (tree_node_visitor *const v) const override
virtual function used to traverse the tree_node data structure.
Static Public Member Functions
static void enable_html ()
Redefinition of get_tree_node_kind_text.
static void enable_raw ()
Data Fields
const tree_nodeRef & actual_tree_node
Represent the actual reference to the tree_node.
Static Public Attributes
static bool html = false
Private Member Functions
tree_reindex (const unsigned int ind, const tree_nodeRef &tn)
Private constructor with index initialization It can be accesses only by tree_manager.
Friends
class tree_manager
Detailed Description
This class is used to perform the re-index of all tree nodes.
Each reference to a tree_node is implemented by this type of tree_node
Definition at line 55 of file tree_reindex.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 111 of file tree_reindex.hpp.
Constructor & Destructor Documentation
tree_reindex()
tree_reindex::tree_reindex (const unsigned int ind, const tree_nodeRef & tn) [private]
Private constructor with index initialization It can be accesses only by tree_manager.
Parameters
ind is the value of the index member.
tn is the actual reference to the tree_node. NOTE: this has to be a reference since tree_nodeRef at the moment of the construction of this can not ready
Definition at line 48 of file tree_reindex.cpp.
References ~tree_reindex().
 tree_reindex()
tree_reindex::~tree_reindex () [override], [default]
Referenced by tree_reindex().
Member Function Documentation
enable_html()
static void tree_reindex::enable_html () [inline], [static]
Redefinition of get_tree_node_kind_text.
Redefinition of get_tree_node_kind. Switch the print function to the html format
Definition at line 97 of file tree_reindex.hpp.
enable_raw()
static void tree_reindex::enable_raw () [inline], [static]
Definition at line 101 of file tree_reindex.hpp.
References visit().
print()
void tree_reindex::print (std::ostream & os) const
function that prints the class tree_reindex.
Definition at line 54 of file tree_reindex.cpp.
References html, and tree_node::index.
visit()
void tree_reindex::visit (tree_node_visitor *const v) const [override], [virtual]
virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from tree_node.
Definition at line 66 of file tree_reindex.cpp.
References actual_tree_node, ALL_VISIT, html, and VISIT_MEMBER.
Referenced by enable_raw().
Friends And Related Function Documentation
tree_manager
friend class tree_manager [friend]
Definition at line 58 of file tree_reindex.hpp.
Field Documentation
actual_tree_node
const tree_nodeRef& tree_reindex::actual_tree_node
Represent the actual reference to the tree_node.
NOTE: this has to be a reference since tree_nodeRef at the moment of the construction of this can not ready
Definition at line 74 of file tree_reindex.hpp.
Referenced by visit().
html
bool tree_reindex::html = false [static]
Definition at line 76 of file tree_reindex.hpp.
Referenced by print(), and visit().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_reindex.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_reindex.cpp