WB4_interface Class Reference
#include <WB4_interface.hpp>
Public Member Functions
WB4_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::WB4_INTERFACE_GENERATION)
Constructor.
~WB4_interface () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
unsigned int get_data_bus_bitsize ()
unsigned int get_addr_bus_bitsize ()
void build_WB4_bus_interface (structural_managerRef SM)
void connect_with_signal_name (structural_managerRef SM, structural_objectRef portA, structural_objectRef portB, std::string signalName)
void connect_with_signal_name (structural_managerRef SM, structural_objectRef APort, structural_objectRef B, std::string Bsignal, const std::string &signalName)
void connect_with_signal_name (structural_managerRef SM, structural_objectRef A, std::string Asignal, structural_objectRef B, std::string Bsignal, const std::string &signalName)
void connect_with_signal (structural_managerRef SM, structural_objectRef portA, structural_objectRef portB)
void connect_with_signal (structural_managerRef SM, structural_objectRef A, std::string Asignal, structural_objectRef B, std::string Bsignal)
void connect_with_signal (structural_managerRef SM, structural_objectRef APort, structural_objectRef B, std::string Bsignal)
void connect_with_signal (structural_managerRef SM, structural_objectRef A, std::string Asignal, structural_objectRef portB)
void build_WB4_complete_logic (structural_managerRef SM, structural_objectRef wrappedObj, structural_objectRef interfaceObj)
Additional Inherited Members
Detailed Description
Definition at line 64 of file WB4_interface.hpp.
Constructor & Destructor Documentation
WB4_interface()
WB4_interface::WB4_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type = HLSFlowStep_Type::WB4_INTERFACE_GENERATION)
Constructor.
technology/physical_library include
Definition at line 79 of file WB4_interface.cpp.
References ~WB4_interface().
 WB4_interface()
WB4_interface::~WB4_interface () [override], [default]
Destructor.
Referenced by WB4_interface().
Member Function Documentation
build_WB4_bus_interface()
void WB4_interface::build_WB4_bus_interface (structural_managerRef SM) [protected]
Definition at line 152 of file WB4_interface.cpp.
References memory::add_memory_parameter(), structural_manager::add_port(), CLOCK_PORT_NAME, hls::functionId, get_addr_bus_bitsize(), structural_manager::get_circ(), get_data_bus_bitsize(), HLSFunctionStep::HLS, HLS_step::HLSMgr, port_o::IN, tree_helper::name_function(), port_o::OUT, RESET_PORT_NAME, STR, WB_ACKIM_PORT_NAME, WB_ACKOS_PORT_NAME, WB_ADDRIS_PORT_NAME, WB_ADDROM_PORT_NAME, WB_BASE_ADDRESS, WB_CYCIS_PORT_NAME, WB_CYCOM_PORT_NAME, WB_DATIM_PORT_NAME, WB_DATIS_PORT_NAME, WB_DATOM_PORT_NAME, WB_DATOS_PORT_NAME, WB_IRQ_PORT_NAME, WB_SELIS_PORT_NAME, WB_SELOM_PORT_NAME, WB_STBIS_PORT_NAME, WB_STBOM_PORT_NAME, WB_WEIS_PORT_NAME, and WB_WEOM_PORT_NAME.
Referenced by InternalExec().
build_WB4_complete_logic()
void WB4_interface::build_WB4_complete_logic (structural_managerRef SM, structural_objectRef wrappedObj, structural_objectRef interfaceObj) [protected]
Definition at line 270 of file WB4_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), ADDRESS_FILTER_WB, ADDRESS_RANGE_CHECKER_WB, ALL_BRAM, AND_GATE_STD, structural_type_descriptor::check_type(), CLOCK_PORT_NAME, connect_with_signal(), connect_with_signal_name(), CONSTANT_STD, DATARAMSIZE_CONVERTER_WB, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEMUX_GATE_STD, DONE_PORT_NAME, EXT_PIPELINED_BRAM, structural_object::find_member(), hls::functionId, get_addr_bus_bitsize(), structural_manager::get_circ(), get_data_bus_bitsize(), structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, LIBRARY_STD, MUX_GATE_STD, tree_helper::name_function(), NOT_GATE_STD, NOT_INTERNAL_COMPONENT, OR_GATE_STD, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, port_o_K, PRINT_DBG_MEX, RESET_PORT_NAME, SEL_CONVERTER_WB, structural_object::SetParameter(), START_PORT_NAME, STR, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, WB_ACKIM_PORT_NAME, WB_ACKOS_PORT_NAME, WB_ADDRIS_PORT_NAME, WB_ADDROM_PORT_NAME, WB_BASE_ADDRESS, WB_CYCIS_PORT_NAME, WB_CYCOM_PORT_NAME, WB_DATIM_PORT_NAME, WB_DATIS_PORT_NAME, WB_DATOM_PORT_NAME, WB_DATOS_PORT_NAME, WB_IRQ_PORT_NAME, WB_SELIS_PORT_NAME, WB_SELOM_PORT_NAME, WB_STBIS_PORT_NAME, WB_STBOM_PORT_NAME, WB_WEIS_PORT_NAME, WB_WEOM_PORT_NAME, and WBLIBRARY.
Referenced by InternalExec().
connect_with_signal() [1/4]
void WB4_interface::connect_with_signal (structural_managerRef SM, structural_objectRef portA, structural_objectRef portB) [protected]
Definition at line 246 of file WB4_interface.cpp.
References connect_with_signal_name(), and structural_object::get_id().
Referenced by build_WB4_complete_logic(), and connect_with_signal().
connect_with_signal() [2/4]
void WB4_interface::connect_with_signal (structural_managerRef SM, structural_objectRef A, std::string Asignal, structural_objectRef B, std::string Bsignal) [protected]
Definition at line 251 of file WB4_interface.cpp.
References connect_with_signal(), structural_object::find_member(), and port_o_K.
connect_with_signal() [3/4]
void WB4_interface::connect_with_signal (structural_managerRef SM, structural_objectRef APort, structural_objectRef B, std::string Bsignal) [protected]
Definition at line 258 of file WB4_interface.cpp.
References connect_with_signal(), structural_object::find_member(), and port_o_K.
connect_with_signal() [4/4]
void WB4_interface::connect_with_signal (structural_managerRef SM, structural_objectRef A, std::string Asignal, structural_objectRef portB) [protected]
Definition at line 264 of file WB4_interface.cpp.
References connect_with_signal(), structural_object::find_member(), and port_o_K.
connect_with_signal_name() [1/3]
void WB4_interface::connect_with_signal_name (structural_managerRef SM, structural_objectRef portA, structural_objectRef portB, std::string signalName) [protected]
Definition at line 199 of file WB4_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), structural_manager::get_circ(), structural_object::get_kind(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), port_o_K, and THROW_ASSERT.
Referenced by build_WB4_complete_logic(), connect_with_signal(), and connect_with_signal_name().
connect_with_signal_name() [2/3]
void WB4_interface::connect_with_signal_name (structural_managerRef SM, structural_objectRef APort, structural_objectRef B, std::string Bsignal, const std::string & signalName) [protected]
Definition at line 240 of file WB4_interface.cpp.
References connect_with_signal_name(), structural_object::find_member(), and port_o_K.
connect_with_signal_name() [3/3]
void WB4_interface::connect_with_signal_name (structural_managerRef SM, structural_objectRef A, std::string Asignal, structural_objectRef B, std::string Bsignal, const std::string & signalName) [protected]
Definition at line 233 of file WB4_interface.cpp.
References connect_with_signal_name(), structural_object::find_member(), and port_o_K.
get_addr_bus_bitsize()
unsigned int WB4_interface::get_addr_bus_bitsize () [protected]
Definition at line 141 of file WB4_interface.cpp.
References HLS_step::HLSMgr, and max().
Referenced by build_bus_interface(), build_WB4_bus_interface(), and build_WB4_complete_logic().
get_data_bus_bitsize()
unsigned int WB4_interface::get_data_bus_bitsize () [protected]
Definition at line 124 of file WB4_interface.cpp.
References FunctionBehavior::CGetBehavioralHelper(), hls::functionId, BehavioralHelper::get_size(), HLSFunctionStep::HLS, HLS_step::HLSMgr, and max().
Referenced by build_bus_interface(), build_WB4_bus_interface(), and build_WB4_complete_logic().
InternalExec()
DesignFlowStep_Status WB4_interface::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Set some descriptions and legal stuff
Reimplemented from minimal_interface.
Definition at line 86 of file WB4_interface.cpp.
References build_WB4_bus_interface(), build_WB4_complete_logic(), GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), structural_object::get_id(), structural_object::get_typeRef(), HLSFunctionStep::HLS, structural_type_descriptor::id_type, minimal_interface::InternalExec(), DesignFlowStep::parameters, memory::propagate_memory_parameters(), structural_object::set_id(), structural_object::set_owner(), structural_manager::set_top_info(), SUCCESS, and hls::top.
Referenced by WB4Intercon_interface::exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/WB4/WB4_interface.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/WB4/WB4_interface.cpp