clb_model Class Reference
#include <clb_model.hpp>
Public Types
enum value_t {
REGISTERS,
SLICE,
SLICE_LUTS,
LUT_FF_PAIRS,
ALMS,
LOGIC_ELEMENTS,
FUNCTIONAL_ELEMENTS,
DSP,
BRAM
 }
type of resources
Public Member Functions
clb_model (const ParameterConstRef &Param)
Constructor.
clb_model (const ParameterConstRef &Param, const double &_area_)
Constructor with specified area value.
~clb_model () override
Destructor.
void print (std::ostream &os) const override
Prints the used resources into an output stream.
void set_area_value (const double &_area_) override
Sets the nominal value for the area of the component.
double get_area_value () const override
Returns the nominal value for the area of the component.
bool is_characterization (unsigned int characterization_type) const override
Checks if there is a characterization for the given type.
void set_resource_value (value_t val, double num)
Sets the number of resources used for the specified type.
bool is_used_resource (value_t val) const
Returns true if the specified resource is used, false otherwise.
double get_resource_value (value_t val) const
Returns the number of resources used for the given type.
Protected Attributes
double area
a double value representing the area of the component
std::map< value_t, double > used_resources
resources required for the component
Additional Inherited Members
Detailed Description
Definition at line 57 of file clb_model.hpp.
Member Enumeration Documentation
value_t
enum clb_model::value_t
type of resources
Enumerator
REGISTERS
SLICE
SLICE_LUTS
LUT_FF_PAIRS
ALMS
LOGIC_ELEMENTS
FUNCTIONAL_ELEMENTS
DSP
BRAM
Definition at line 61 of file clb_model.hpp.
Constructor & Destructor Documentation
clb_model() [1/2]
clb_model::clb_model (const ParameterConstRef & Param) [explicit]
Constructor.
Header include.
Definition at line 48 of file clb_model.cpp.
clb_model() [2/2]
clb_model::clb_model (const ParameterConstRef & Param, const double & _area_)
Constructor with specified area value.
Definition at line 53 of file clb_model.cpp.
References ~clb_model().
 clb_model()
clb_model::~clb_model () [override], [default]
Destructor.
Referenced by clb_model().
Member Function Documentation
get_area_value()
double clb_model::get_area_value () const [override], [virtual]
Returns the nominal value for the area of the component.
Implements area_model.
Definition at line 59 of file clb_model.cpp.
References area.
get_resource_value()
double clb_model::get_resource_value (value_t val) const
Returns the number of resources used for the given type.
Definition at line 84 of file clb_model.cpp.
References is_used_resource(), and used_resources.
is_characterization()
bool clb_model::is_characterization (unsigned int characterization_type) const [override], [virtual]
Checks if there is a characterization for the given type.
Implements area_model.
Definition at line 69 of file clb_model.cpp.
is_used_resource()
bool clb_model::is_used_resource (value_t val) const
Returns true if the specified resource is used, false otherwise.
Definition at line 79 of file clb_model.cpp.
References used_resources.
Referenced by get_resource_value().
print()
void clb_model::print (std::ostream & os) const [override], [virtual]
Prints the used resources into an output stream.
Implements area_model.
Definition at line 93 of file clb_model.cpp.
References LUT_FF_PAIRS, and used_resources.
set_area_value()
void clb_model::set_area_value (const double & _area_) [override], [virtual]
Sets the nominal value for the area of the component.
Implements area_model.
Definition at line 64 of file clb_model.cpp.
References area.
set_resource_value()
void clb_model::set_resource_value (value_t val, double num)
Sets the number of resources used for the specified type.
Definition at line 74 of file clb_model.cpp.
References used_resources.
Field Documentation
area
double clb_model::area [protected]
a double value representing the area of the component
Definition at line 76 of file clb_model.hpp.
Referenced by get_area_value(), and set_area_value().
used_resources
std::map<value_t, double> clb_model::used_resources [protected]
resources required for the component
Definition at line 79 of file clb_model.hpp.
Referenced by get_resource_value(), is_used_resource(), print(), and set_resource_value().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/area/clb_model.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/area/clb_model.cpp