short_circuit_taf Class Reference
STL include.
#include <short_circuit_taf.hpp>
Public Member Functions
short_circuit_taf (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~short_circuit_taf () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
bool check_merging_candidate (unsigned int &bb1, unsigned int &bb2, unsigned int merging_candidate, bool &bb1_true, bool &bb2_true, std::map< unsigned int, blocRef > &list_of_bloc)
Check if a basic block is a merging BB for a short circuit.
bool create_gimple_cond (unsigned int bb1, unsigned int bb2, bool bb1_true, std::map< unsigned int, blocRef > &list_of_bloc, bool or_type, unsigned int merging_candidate)
create the or/and expression required by short circuit collapsing
void restructure_CFG (unsigned int bb1, unsigned int bb2, unsigned int merging_candidate, std::map< unsigned int, blocRef > &list_of_bloc)
restructure the CFG eliminating all BBs not needed after short circuit collapsing
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
bool check_phis (unsigned int curr_bb, std::map< unsigned int, blocRef > &list_of_bloc)
check if phi could create problem to the short circuit collapsing
void fix_multi_way_if (unsigned int curr_bb, std::map< unsigned int, blocRef > &list_of_bloc, unsigned int succ)
Additional Inherited Members
Detailed Description
STL include.
Structure the original short circuit
Definition at line 71 of file short_circuit_taf.hpp.
Constructor & Destructor Documentation
short_circuit_taf()
short_circuit_taf::short_circuit_taf (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Behavior include Parameter include design flow manager include HLS includes parser/treegcc include STD include STL include design_flows/technology includes tree includes utility includes
Definition at line 98 of file short_circuit_taf.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~short_circuit_taf().
 short_circuit_taf()
short_circuit_taf::~short_circuit_taf () [override], [default]
Destructor.
Referenced by short_circuit_taf().
Member Function Documentation
check_merging_candidate()
bool short_circuit_taf::check_merging_candidate (unsigned int & bb1, unsigned int & bb2, unsigned int merging_candidate, bool & bb1_true, bool & bb2_true, std::map< unsigned int, blocRef > & list_of_bloc) [private]
Check if a basic block is a merging BB for a short circuit.
let bb1 the upper if
let search bb2, the lower if
Definition at line 290 of file short_circuit_taf.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, GET_NODE, INDENT_DBG_MEX, PRINT_DBG_MEX, STR, and THROW_ASSERT.
Referenced by InternalExec().
check_phis()
bool short_circuit_taf::check_phis (unsigned int curr_bb, std::map< unsigned int, blocRef > & list_of_bloc) [private]
check if phi could create problem to the short circuit collapsing
Parameters
curr_bb is the basic block that merge the two or more flows
list_of_bloc is the list of basic blocks
Returns
true in case the short circuit merging can be performed
Definition at line 176 of file short_circuit_taf.cpp.
References GET_NODE, and phi.
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > short_circuit_taf::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
We can check if single_write_memory is true only after technology was loaded
Implements FrontendFlowStep.
Definition at line 106 of file short_circuit_taf.cpp.
References ABORTED, FrontendFlowStep::AppM, BLOCK_FIX, CLEAN_VIRTUAL_PHI, TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), NONEXISTENT, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, SWITCH_FIX, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, UNNECESSARY, and USE_COUNTING.
create_gimple_cond()
bool short_circuit_taf::create_gimple_cond (unsigned int bb1, unsigned int bb2, bool bb1_true, std::map< unsigned int, blocRef > & list_of_bloc, bool or_type, unsigned int merging_candidate) [private]
create the or/and expression required by short circuit collapsing
If there are more than one statements in the basic block containing cond2, then do not merge conditions (in case speculation step should manage the code motion)
identify the first gimple_cond
create the ssa_var representing the condition for bb1
create the assignment between condition for bb1 and the new ssa var
and then add to the bb1 statement list
fix merging_candidate phis
create the ssa_var representing the result of the cond_expr
second, create the gimple assignment
and then add to the statement list
cond1 has to be negate create the ssa_var representing the negated condition
create !cond1
and then add to the bb1 statement list
identify the second gimple_cond
create the ssa_var representing the condition for bb2
create the assignment between condition for bb2 and the new ssa var
and then add to the bb1 statement list
create (!)cond1 or cond2
The expression contained in ce2 must now be the newly created expression, identified by expr_index Temporary remove statement to remove old uses
Readding the statement
add the statements of bb1 to bb2
add the phi of bb1 to bb2
Definition at line 364 of file short_circuit_taf.cpp.
References FrontendFlowStep::AppM, tree_helper::CGetType(), tree_manipulation::create_boolean_type(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_manager::get_next_vers(), GET_NODE, tree_helper::get_type_index(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, tree_helper::is_a_vector(), tree_helper::is_bool(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, phi, PRINT_DBG_MEX, STR, THROW_ASSERT, TOK, TOK_OP, TOK_OP0, TOK_OP1, TOK_OP2, TOK_ORIG, TOK_SRCP, TOK_TYPE, TOK_VERS, TOK_VIRTUAL, and TOK_VOLATILE.
Referenced by InternalExec().
fix_multi_way_if()
void short_circuit_taf::fix_multi_way_if (unsigned int curr_bb, std::map< unsigned int, blocRef > & list_of_bloc, unsigned int succ) [private]
Definition at line 617 of file short_circuit_taf.cpp.
References GET_NODE.
Referenced by restructure_CFG().
Initialize()
void short_circuit_taf::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 172 of file short_circuit_taf.cpp.
InternalExec()
DesignFlowStep_Status short_circuit_taf::InternalExec () [override], [virtual]
Restructures the unstructured code.
compute merging candidates
find the first to merge
cond expr not completely collapsed
Implements FunctionFrontendFlowStep.
Definition at line 187 of file short_circuit_taf.cpp.
References FrontendFlowStep::AppM, check_merging_candidate(), check_phis(), create_gimple_cond(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), INDENT_DBG_MEX, restructure_CFG(), sl, STR, SUCCESS, UNCHANGED, and FunctionFrontendFlowStep::WriteBBGraphDot().
restructure_CFG()
void short_circuit_taf::restructure_CFG (unsigned int bb1, unsigned int bb2, unsigned int merging_candidate, std::map< unsigned int, blocRef > & list_of_bloc) [private]
restructure the CFG eliminating all BBs not needed after short circuit collapsing
fix bb2 predecessor
fix bb1 empty block
check for BB with gimple_multi_way_if
Definition at line 591 of file short_circuit_taf.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, fix_multi_way_if(), and PRINT_DBG_MEX.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/short_circuit_taf.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/short_circuit_taf.cpp