omp_task_pragma Struct Reference
#include <ext_tree_node.hpp>
Public Types
enum { GETID =(omp_pragma) = 0
 }
visitor enum
Public Member Functions
omp_task_pragma (unsigned int i)
constructor
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
CustomUnorderedMapUnstable< std::string, std::string > clauses
Clauses associated with the directives.
Additional Inherited Members
Detailed Description
Definition at line 502 of file ext_tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 523 of file ext_tree_node.hpp.
Constructor & Destructor Documentation
omp_task_pragma()
omp_task_pragma::omp_task_pragma (unsigned int i) [explicit]
constructor
Definition at line 142 of file ext_tree_node.cpp.
Member Function Documentation
visit()
void omp_task_pragma::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from omp_pragma.
Definition at line 146 of file ext_tree_node.cpp.
References ALL_VISIT, and VISIT_SC.
Referenced by map_pragma::visit(), issue_pragma::visit(), blackbox_pragma::visit(), omp_pragma::visit(), omp_atomic_pragma::visit(), omp_for_pragma::visit(), omp_simd_pragma::visit(), omp_declare_simd_pragma::visit(), gimple_while::visit(), gimple_for::visit(), and gimple_multi_way_if::visit().
Field Documentation
clauses
CustomUnorderedMapUnstable<std::string, std::string> omp_task_pragma::clauses
Clauses associated with the directives.
Definition at line 505 of file ext_tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/ext_tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/ext_tree_node.cpp