HLSFunctionBitValue Class Reference
superclass include
#include <hls_function_bit_value.hpp>
Public Member Functions
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
 Constructors and Destructors.
HLSFunctionBitValue (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~HLSFunctionBitValue () override
Destructor.
Private Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
superclass include
STD includes
This class work as a proxy of the front end step performing the bit value analysis
Definition at line 55 of file hls_function_bit_value.hpp.
Constructor & Destructor Documentation
HLSFunctionBitValue()
HLSFunctionBitValue::HLSFunctionBitValue (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
design_flow includes
Parameters
design_flow_manager is the design flow manager
frontend_analysis includes HLS includes
Definition at line 76 of file hls_function_bit_value.cpp.
References DesignFlowStep::debug_level, GET_CLASS, HLS_FUNCTION_BIT_VALUE, and ~HLSFunctionBitValue().
 HLSFunctionBitValue()
HLSFunctionBitValue::~HLSFunctionBitValue () [override], [default]
Destructor.
Referenced by HLSFunctionBitValue().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > HLSFunctionBitValue::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 89 of file hls_function_bit_value.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, INITIALIZE_HLS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, THROW_UNREACHABLE, and WHOLE_APPLICATION.
Initialize()
void HLSFunctionBitValue::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from HLSFunctionStep.
Definition at line 84 of file hls_function_bit_value.cpp.
References HLSFunctionStep::Initialize().
InternalExec()
DesignFlowStep_Status HLSFunctionBitValue::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 114 of file hls_function_bit_value.cpp.
References DesignFlowStep::design_flow_manager, HLSFunctionStep::funId, HLS_step::HLSMgr, Wrefcount< T >::lock(), DesignFlowStep::parameters, and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/hls_function_bit_value.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/hls_function_bit_value.cpp