/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/rebuild_initializations.cpp File Reference
rebuild initialization where it is possible
#include `rebuild_initializations.hpp`
#include `Parameter.hpp`
#include `application_manager.hpp`
#include `basic_block.hpp`
#include `behavioral_helper.hpp`
#include `custom_map.hpp`
#include `custom_set.hpp`
#include `dbgPrintHelper.hpp`
#include `function_behavior.hpp`
#include `string_manipulation.hpp`
#include `token_interface.hpp`
#include `tree_basic_block.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_manipulation.hpp`
#include `tree_reindex.hpp`
#include <fstream>
#include <utility>
#include <vector>
Macros
#define REBUILD2_DEVEL 0
#define foundNonConstant(VD)
#define unexpetedPattern2(node, VD) foundNonConstant(VD)
Functions
static tree_nodeRef extractOp1 (tree_nodeRef opSSA)
static bool varFound (tree_nodeRef node, unsigned &vd_index, tree_nodeRef &vd_node)
static bool unexpetedPattern (tree_nodeRef)
tree_nodeRef getAssign (tree_nodeRef SSAop, unsigned vd_index, CustomOrderedSet< unsigned > &nonConstantVars, TreeNodeMap< std::map< long long int, tree_nodeRef >> &inits, tree_managerRef TM)
Detailed Description
rebuild initialization where it is possible
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$ Last modified by $Author$
Macro Definition Documentation
foundNonConstant
#define foundNonConstant(VD)
Value:
do \
   { \
      nonConstantVars.insert(VD); \
      auto key = TM->CGetTreeReindex(VD); \
      inits.erase(key); \
   } while(0)
Definition at line 515 of file rebuild_initializations.cpp.
Referenced by rebuild_initialization2::look_for_ROMs().
REBUILD2_DEVEL
#define REBUILD2_DEVEL 0
Definition at line 258 of file rebuild_initializations.cpp.
unexpetedPattern2
#define unexpetedPattern2(node, VD) foundNonConstant(VD)
Definition at line 526 of file rebuild_initializations.cpp.
Referenced by rebuild_initialization2::look_for_ROMs().
Function Documentation
extractOp1()
static tree_nodeRef extractOp1 (tree_nodeRef opSSA) [static]
Definition at line 231 of file rebuild_initializations.cpp.
References tree_node::get_kind(), GET_NODE, THROW_ASSERT, and tree_node::ToString().
Referenced by rebuild_initialization2::extract_var_decl(), and rebuild_initialization2::extract_var_decl_ppe().
getAssign()
tree_nodeRef getAssign (tree_nodeRef SSAop, unsigned vd_index, CustomOrderedSet< unsigned > & nonConstantVars, TreeNodeMap< std::map< long long int, tree_nodeRef >> & inits, tree_managerRef TM)
Definition at line 529 of file rebuild_initializations.cpp.
References tree_manager::CGetTreeReindex(), tree_node::get_kind(), GET_NODE, and THROW_ASSERT.
Referenced by rebuild_initialization2::look_for_ROMs().
unexpetedPattern()
static bool unexpetedPattern (tree_nodeRef) [static]
Definition at line 262 of file rebuild_initializations.cpp.
Referenced by rebuild_initialization2::extract_var_decl(), and rebuild_initialization2::extract_var_decl_ppe().
varFound()
static bool varFound (tree_nodeRef node, unsigned & vd_index, tree_nodeRef & vd_node) [static]
Definition at line 245 of file rebuild_initializations.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, and THROW_ASSERT.
Referenced by rebuild_initialization2::extract_var_decl(), and rebuild_initialization2::extract_var_decl_ppe().