modelsimWrapper Class Reference
STD include.
#include <modelsimWrapper.hpp>
Public Member Functions
modelsimWrapper (const ParameterConstRef &Param, std::string suffix)
Constructor.
~modelsimWrapper () override
Destructor.
void CheckExecution () override
Checks if the current specification can be executed or not.
void Clean () const override
Remove files created during simulation.
Private Member Functions
void GenerateScript (std::ostringstream &script, const std::string &top_filename, const std::list< std::string > &file_list) override
Generates the proper simulation script.
Private Attributes
std::string suffix
suffix added to the SIM dir
Additional Inherited Members
Detailed Description
STD include.
STL include
Main class for wrapping the modesilm compiler and simulator.
Definition at line 61 of file modelsimWrapper.hpp.
Constructor & Destructor Documentation
modelsimWrapper()
modelsimWrapper::modelsimWrapper (const ParameterConstRef & Param, std::string suffix)
Constructor.
Parameters
Param is the set of parameters
Definition at line 95 of file modelsimWrapper.cpp.
References SimulationTool::debug_level, DEBUG_LEVEL_VERBOSE, PRINT_DBG_MEX, SIM_SUBDIR, suffix, and ~modelsimWrapper().
 modelsimWrapper()
modelsimWrapper::~modelsimWrapper () [override], [default]
Destructor.
Referenced by modelsimWrapper().
Member Function Documentation
CheckExecution()
void modelsimWrapper::CheckExecution () [override], [virtual]
Checks if the current specification can be executed or not.
Reimplemented from SimulationTool.
Definition at line 104 of file modelsimWrapper.cpp.
References THROW_ERROR.
Clean()
void modelsimWrapper::Clean () const [override], [virtual]
Remove files created during simulation.
Reimplemented from SimulationTool.
Definition at line 244 of file modelsimWrapper.cpp.
References SIM_SUBDIR, and suffix.
GenerateScript()
void modelsimWrapper::GenerateScript (std::ostringstream & script, const std::string & top_filename, const std::list< std::string > & file_list) [override], [private], [virtual]
Generates the proper simulation script.
prepare input files
add modelsim license variable
Implements SimulationTool.
Definition at line 111 of file modelsimWrapper.cpp.
References SimulationTool::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GetExtension(), INDENT_DBG_MEX, SimulationTool::log_file, MENTOR_LICENSE_SET, MODELSIM_VCOM, MODELSIM_VDEL, MODELSIM_VLIB, MODELSIM_VLOG, MODELSIM_VMAP, MODELSIM_VSIM, SimulationTool::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, SimulationTool::Param, SIM_SUBDIR, STR, suffix, THROW_ASSERT, and THROW_UNREACHABLE.
Field Documentation
suffix
std::string modelsimWrapper::suffix [private]
suffix added to the SIM dir
Definition at line 64 of file modelsimWrapper.hpp.
Referenced by Clean(), GenerateScript(), and modelsimWrapper().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/modelsim/modelsimWrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/modelsim/modelsimWrapper.cpp