/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value_opt.cpp File Reference
#include `Bit_Value_opt.hpp`
#include `config_HAVE_FROM_DISCREPANCY_BUILT.hpp`
#include `config_HAVE_STDCXX_17.hpp`
#include `application_manager.hpp`
#include `behavioral_helper.hpp`
#include `call_graph.hpp`
#include `call_graph_manager.hpp`
#include `function_behavior.hpp`
#include `Discrepancy.hpp`
#include `Parameter.hpp`
#include <boost/range/adaptor/reversed.hpp>
#include <cmath>
#include <fstream>
#include <string>
#include `dbgPrintHelper.hpp`
#include `ext_tree_node.hpp`
#include `hls_manager.hpp`
#include `hls_target.hpp`
#include `math_function.hpp`
#include `string_manipulation.hpp`
#include `tree_basic_block.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_manipulation.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
#include `utility.hpp`
Functions
static void constrainSSA (ssa_name *op_ssa, tree_managerRef TM)
Detailed Description
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
constrainSSA()
static void constrainSSA (ssa_name * op_ssa, tree_managerRef TM) [static]
Definition at line 153 of file Bit_Value_opt.cpp.
References ssa_name::bit_values, tree_manager::CreateUniqueIntegerCst(), GET_INDEX_NODE, tree_helper::is_int(), ssa_name::max, ssa_name::min, tree_helper::size(), and ssa_name::type.
Referenced by Bit_Value_opt::optimize().