TasteInterfaceGeneration Class Reference
Class generating taste interfaces.
#include <taste_interface_generation.hpp>
Public Member Functions
TasteInterfaceGeneration (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~TasteInterfaceGeneration () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Class generating taste interfaces.
Definition at line 54 of file taste_interface_generation.hpp.
Constructor & Destructor Documentation
TasteInterfaceGeneration()
TasteInterfaceGeneration::TasteInterfaceGeneration (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
. include circuit includes constants include design_flows includes HLS includes HLS/memory include HLS/module_allocation include HLS/stg include intermediate_representation/aadl_asn include STD include STL includes technology include technology/physical_library include tree includes
Definition at line 98 of file taste_interface_generation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~TasteInterfaceGeneration().
 TasteInterfaceGeneration()
TasteInterfaceGeneration::~TasteInterfaceGeneration () [override], [default]
Destructor.
Referenced by TasteInterfaceGeneration().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > TasteInterfaceGeneration::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from module_interface.
Definition at line 106 of file taste_interface_generation.cpp.
References module_interface::ComputeHLSRelationships(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, MINIMAL_INTERFACE_GENERATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
ComputeRelationships()
void TasteInterfaceGeneration::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from HLSFunctionStep.
Definition at line 600 of file taste_interface_generation.cpp.
References ADD_LIBRARY, HLS_step::CGetDesignFlowStepFactory(), HLSFunctionStep::ComputeRelationships(), HLSFunctionStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, HLSFunctionStep::funId, HLS_step::HLSMgr, Wrefcount< T >::lock(), NULL_VERTEX, STR_CST_taste_address_translation, STR_CST_taste_data_size, STR_CST_taste_endianess_check, STR_CST_taste_endianess_inversion, STR_CST_taste_memory_enabling, STR_CST_taste_output_multiplexer, STR_CST_taste_reg_status, and THROW_ASSERT.
HasToBeExecuted()
bool TasteInterfaceGeneration::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from HLSFunctionStep.
Definition at line 686 of file taste_interface_generation.cpp.
References HLSFunctionStep::funId, HLSFunctionStep::HasToBeExecuted(), HLS_step::HLSMgr, STR_CST_taste_address_translation, STR_CST_taste_data_size, STR_CST_taste_endianess_check, STR_CST_taste_endianess_inversion, STR_CST_taste_memory_enabling, STR_CST_taste_output_multiplexer, and STR_CST_taste_reg_status.
InternalExec()
DesignFlowStep_Status TasteInterfaceGeneration::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
function name to be synthesized
auto taste_interface_module = GetPointer<const module>(taste_interface_circuit);
Set some descriptions and legal stuff
Adding minimal interface module to the taste interface
Checking if minimal interface has memory interface
Add ports
Connect minimal interface
Preparing and connecting reg_status
Preparing and connecting reg_status_update
Preparing and connecting reg_status
Computing the mask for addresses
Preparing masked version of address
Preparing and connecting endianess_check
Preparing and connecting endianess_inversion
Creating parameter registers
Resizing register size
Converting size to fit register
Connecting register
Resizing register size
Connects return port to register
Connects done port to register
Converting size to fit data bus
Connect and instantiate memory
component specialization
Preparing and connecting memory_translation
Preparing and connecting data_size
Preparing and connecting memory_enabling
Preparing and connecting actual_enabling of the memory
Prepearing and connecting load enable
Preparing and connecting sel_LOAD of the memory
Preparing and connecting sel_STORE of the memory
Connecting input of memory - in1
Connecting input of memory - in2
Connecting input of memory - in3
Connecting input of memory - sel_LOAD
Connecting input of memory - sel_STORE
Connecting input of memory - clock - reset
Preparing output
Output endianess conversion
Implements HLSFunctionStep.
Definition at line 131 of file taste_interface_generation.cpp.
References module_interface::add_sign_vector(), module_interface::AddConnection(), module_interface::AddConstant(), structural_object::AddParameter(), module_interface::AddSignal(), ARRAY_1D_STD_BRAM_NN, FunctionBehavior::CGetBehavioralHelper(), CLOCK_PORT_NAME, structural_manager::COMPLETE_G, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, structural_object::find_member(), HLSFunctionStep::funId, BehavioralHelper::get_function_name(), get_id(), structural_object::get_kind(), technology_manager::get_library(), structural_object::get_path(), GET_TYPE_SIZE, HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, port_o::IN, INDENT_DBG_MEX, index, NP_functionality::LIBRARY, LIBRARY_STD_FU, port_o::OUT, hls::Param, DesignFlowStep::parameters, port_o_K, port_vector_o_K, register_SE, RESET_PORT_NAME, port_o::resize_busport(), RETURN_PORT_NAME, structural_object::set_black_box(), structural_object::set_id(), structural_object::set_owner(), structural_object::SetParameter(), START_PORT_NAME, STR, STR_CST_taste_address_translation, STR_CST_taste_data_size, STR_CST_taste_endianess_check, STR_CST_taste_endianess_inversion, STR_CST_taste_memory_enabling, STR_CST_taste_output_multiplexer, STR_CST_taste_reg_status, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, hls::top, structural_object::type_resize(), UUDATA_CONVERTER_STD, and WORK_LIBRARY.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/taste_interface_generation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/taste_interface_generation.cpp