/home/osboxes/bambu/PandA-bambu/documentation/tutorial_fpl_2017/lab2/materials/2.1/hint.c File Reference
Functions
void max (int input[10], int *max)
Function Documentation
max()
void max (int input[10], int * max)
Definition at line 1 of file hint.c.
Referenced by AbsControlStep::AbsControlStep(), tree_helper::accessed_greatest_bitsize(), ASLAP::add_constraints_to_ALAP(), ASLAP::add_constraints_to_ASAP(), coloring_based_clique_covering< vertex_type >::add_edge(), bipartite_matching_clique_covering< vertex_type >::add_edge(), memory::add_external_symbol(), memory::add_internal_symbol(), memory::add_parameter_symbol(), bipartite_matching_clique_covering< vertex_type >::add_subpartitions(), fu_binding::add_to_SM(), module_interface::AddConstant(), RTLCharacterization::AnalyzeCell(), simple_code_motion::CheckMovable(), AllocationInformation::Clear(), bipartite_matching_clique_covering< vertex_type >::color_the_cc_compatibility_graph(), ASLAP::compute_ALAP_worst_case(), compute_edge_increments(), parametric_list_based::compute_exec_stage_time(), StateTransitionGraphManager::compute_min_max(), parametric_list_based::compute_starting_ending_time_alap(), parametric_list_based::compute_starting_ending_time_asap(), compatibility_based_register::create_compatibility_graph(), conflict_based_register::create_conflict_graph(), tree_manipulation::CreateNopExpr(), tree_manipulation::CreateUnsigned(), boost::degree_coloring(), vcd_utility::detect_fixed_address_mismatch(), IR_lowering::division_by_a_constant(), parametric_list_based::do_balanced_scheduling(), parametric_list_based::do_balanced_scheduling1(), coloring_based_clique_covering< vertex_type >::do_clique_covering(), TTT_based_clique_covering< vertex_type >::do_clique_covering(), AllocationInformation::estimate_call_delay(), estimate_muxes(), Schedule::EvaluateCondsMerging(), Schedule::EvaluateMultiWayIfsMerging(), HWDiscrepancyAnalysis::Exec(), vcd_utility::Exec(), parametric_list_based::exec(), RTS_based_clique_covering< vertex_type >::exec(), memory_allocation::finalize_memory_allocation(), port_swapping::find_max_degree(), Bit_Value::forward_transfer(), WB4_interface::get_addr_bus_bitsize(), get_addr_bus_bitsize(), tree_helper::get_array_data_bitsize(), tree_helper::get_array_dim_and_bitsize(), AllocationInformation::get_attribute_of_fu_per_op(), allocation::get_compliant_pipelined_unit(), WB4_interface::get_data_bus_bitsize(), get_data_bus_bitsize(), memory::get_last_address(), memory::get_max_address(), AllocationInformation::get_worst_execution_time(), AllocationInformation::get_worst_number_of_cycles(), AllocationInformation::get_worst_stage_period(), AllocationInformation::GetConnectionTime(), AllocationInformation::GetNodeTypePrec(), module_binding_check_no_filter< vertex_type >::getOpSlack(), AllocationInformation::GetPhiConnectionLatency(), CSE::hash_check(), AllocationInformation::Initialize(), mem_cg_ext::InternalExec(), mem_dominator_allocation::InternalExec(), chordal_coloring_register::InternalExec(), BB_based_stg::InternalExec(), ControlFlowChecker::InternalExec(), compute_implicit_calls::InternalExec(), CondExprRestructuring::InternalExec(), commutative_expr_restructuring::InternalExec(), RemoveEndingIf::InternalExec(), MultipleEntryIfReduction::InternalExec(), IR_lowering::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), bipartite_matching_clique_covering< vertex_type >::max_resources(), full_cost_matrix::max_row(), bipartite_matching_clique_covering< vertex_type >::min_resources(), Bit_Value_opt::optimize(), flopoco_wrapper::outputSignals(), port_swapping::p_swap(), mem_xml_allocation::parse_xml_allocation(), vcd_utility::print_discrepancy(), hls_div_cg_ext::recursive_examinate(), application_manager::RegisterTransformation(), slack_based_filtering::select_candidate_to_remove(), TS_based_clique_covering< vertex_type >::select_edge(), TS_based_clique_covering< vertex_type >::select_edge_start(), vcd_trace_head::set_consecutive_state_executions(), HLS_constraints::set_max_registers(), Parameter::SetCommonDefaults(), tree_helper::Size(), fu_binding::specialise_fu(), conn_binding::specialise_mux(), synth_mult(), boost::unsorted_coloring(), bipartite_matching< CostFunctor >::update_labels(), parametric_list_based::update_starting_ending_time(), parametric_list_based::update_starting_ending_time_asap(), vcd_parser::vcd_add_signal(), enumeral_type::visit(), integer_type::visit(), cdfc_module_binding::weight_computation(), fu_binding::write_init(), VHDL_writer::write_state_declaration(), verilog_writer::write_state_declaration(), verilog_writer::write_vector_port_binding(), and operation::xload().