vivado_flow_wrapper Class Reference
Main class for wrapping vivado_flow tool by XILINX.
#include <vivado_flow_wrapper.hpp>
Public Member Functions
vivado_flow_wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~vivado_flow_wrapper () override
Destructor.
Protected Member Functions
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Private Member Functions
void create_sdc (const DesignParametersRef &dp)
Additional Inherited Members
Detailed Description
Main class for wrapping vivado_flow tool by XILINX.
Definition at line 56 of file vivado_flow_wrapper.hpp.
Constructor & Destructor Documentation
vivado_flow_wrapper()
vivado_flow_wrapper::vivado_flow_wrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Parameters
Param is the set of parameters
Definition at line 57 of file vivado_flow_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, and ~vivado_flow_wrapper().
 vivado_flow_wrapper()
vivado_flow_wrapper::~vivado_flow_wrapper () [override], [default]
Destructor.
Referenced by vivado_flow_wrapper().
Member Function Documentation
create_sdc()
void vivado_flow_wrapper::create_sdc (const DesignParametersRef & dp) [private]
Definition at line 74 of file vivado_flow_wrapper.cpp.
References DesignParameters::component_name, SynthesisTool::output_dir, SynthesisTool::Param, PARAM_clk_name, PARAM_clk_period, PARAM_connect_iob, PARAM_is_combinational, PARAM_sdc_file, and DesignParameters::parameter_values.
Referenced by EvaluateVariables().
EvaluateVariables()
void vivado_flow_wrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 65 of file vivado_flow_wrapper.cpp.
References DesignParameters::assign(), DesignParameters::component_name, create_sdc(), SynthesisTool::output_dir, PARAM_vivado_outdir, PARAM_vivado_report, PARAM_vivado_timing_report, and DesignParameters::parameter_values.
get_command_line()
std::string vivado_flow_wrapper::get_command_line (const DesignParametersRef & dp) const [override], [protected], [virtual]
Returns the proper command line.
Implements SynthesisTool.
Definition at line 99 of file vivado_flow_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, XilinxWrapper::toString(), and SynthesisTool::xml_tool_options.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/vivado_flow_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/vivado_flow_wrapper.cpp