dom_info< GraphObj > Class Template Reference
Store the intermediate information used to compute dominator or post dominator information.
#include <Dominance.hpp>
Public Member Functions
dom_info (const GraphObj &_g, const Vertex &_en_block, const Vertex &_ex_block, const ParameterConstRef param)
Constructor.
void calc_dfs_tree (bool reverse)
The main entry for calculating the DFS tree or forest.
void calc_idoms (bool reverse)
This calculates the immediate dominators (or post-dominators if REVERSE is true).
void fill_dom_map (CustomUnorderedMapStable< Vertex, Vertex > &dom_map)
fill the dominator map after its computation
Private Types
typedef boost::graph_traits< const GraphObj >::vertex_descriptor Vertex
The algorithm uses two different indices for each Vertex: a generic index given by boost and the index in the dfs search.
typedef boost::graph_traits< const GraphObj >::in_edge_iterator in_edge_iterator
edge_iterator definition.
typedef boost::graph_traits< const GraphObj >::out_edge_iterator out_edge_iterator
edge_iterator definition.
typedef boost::graph_traits< const GraphObj >::edge_descriptor edge
edge definition.
typedef boost::graph_traits< const GraphObj >::vertex_iterator Vertex_iterator
Vertex iterator definition.
Private Member Functions
void calc_dfs_tree_rec (Vertex bb)
The recursive variant of creating a DFS tree.
void compress (TBB v)
Compress the path from V to the root of its set and update path_min at the same time.
TBB eval (TBB v)
Compress the path from V to the set root of V if needed (when the root has changed since the last call).
void link_roots (TBB v, TBB w)
This essentially merges the two sets of V and W, giving a single set with the new root V.
Private Attributes
std::vector< TBB > dfs_parent
The parent of a node in the DFS tree.
std::vector< TBB > key
For a node x key[x] is roughly the node nearest to the root from which exists a way to x only over nodes behind x.
std::vector< TBB > path_min
The value in path_min[x] is the node y on the path from x to the root of the tree x is in with the smallest key[y].
std::vector< TBB > bucket
bucket[x] points to the first node of the set of nodes having x as key.
std::vector< TBB > next_bucket
And next_bucket[x] points to the next node.
std::vector< TBB > set_chain
set_chain[x] is the next node on the path from x to the representant of the set containing x.
std::vector< unsigned int > set_size
set_size[x] is the number of elements in the set named by x.
std::vector< TBB > set_child
set_child[x] is used for balancing the tree representing a set.
unsigned int dfsnum
This is the next free DFS number when creating the DFS tree.
unsigned int nodes
The number of nodes in the DFS tree (==dfsnum-1).
CustomOrderedSet< TBB > fake_exit_edge
Blocks with bits set here have a fake edge to EXIT.
const unsigned long int last_basic_block
index of the last basic block
const Vertex & en_block
Start block (ENTRY_BLOCK_PTR for forward problem, EXIT_BLOCK for backward problem).
const Vertex & ex_block
Ending block.
const GraphObj & g
Flow graph reference.
std::vector< TBB > dom
After the algorithm is done, dom[x] contains the immediate dominator of x.
std::vector< TBB > dfs_order
If b is the number of a basic block (index_map[bb_Vertex]), dfs_order[b] is the number of that node in DFS order counted from 1.
std::vector< Vertex > dfs_to_bb
If x is the DFS-index of a node which corresponds with a basic block, dfs_to_bb[x] is that basic block.
std::map< Vertex, size_t > index_map
index map putting into relation vertices and arbitrary indexes.
int debug_level
debug_level
Detailed Description
template<typename GraphObj>
class dom_info< GraphObj >
Store the intermediate information used to compute dominator or post dominator information.
It holds various arrays reflecting the (sub)structure of the flowgraph. Most of them are of type TBB and are also indexed by TBB.
Definition at line 91 of file Dominance.hpp.
Member Typedef Documentation
edge
template<typename GraphObj>
typedef boost::graph_traits<const GraphObj>::edge_descriptor dom_info< GraphObj >::edge [private]
edge definition.
Definition at line 102 of file Dominance.hpp.
in_edge_iterator
template<typename GraphObj>
typedef boost::graph_traits<const GraphObj>::in_edge_iterator dom_info< GraphObj >::in_edge_iterator [private]
edge_iterator definition.
Definition at line 98 of file Dominance.hpp.
out_edge_iterator
template<typename GraphObj>
typedef boost::graph_traits<const GraphObj>::out_edge_iterator dom_info< GraphObj >::out_edge_iterator [private]
edge_iterator definition.
Definition at line 100 of file Dominance.hpp.
Vertex
template<typename GraphObj>
typedef boost::graph_traits<const GraphObj>::vertex_descriptor dom_info< GraphObj >::Vertex [private]
The algorithm uses two different indices for each Vertex: a generic index given by boost and the index in the dfs search.
Definition of Vertex
Definition at line 96 of file Dominance.hpp.
Vertex_iterator
template<typename GraphObj>
typedef boost::graph_traits<const GraphObj>::vertex_iterator dom_info< GraphObj >::Vertex_iterator [private]
Vertex iterator definition.
Definition at line 104 of file Dominance.hpp.
Constructor & Destructor Documentation
dom_info()
template<typename GraphObj>
dom_info< GraphObj >::dom_info (const GraphObj & _g, const Vertex & _en_block, const Vertex & _ex_block, const ParameterConstRef param) [inline]
Constructor.
Parameters
g is the starting graph
en_block is the entry block
ex_block is the exit_block,
param is the set of input parameters
Definition at line 326 of file Dominance.hpp.
Member Function Documentation
calc_dfs_tree()
template<typename GraphObj>
void dom_info< GraphObj >::calc_dfs_tree (bool reverse) [inline]
The main entry for calculating the DFS tree or forest.
Parameters
reverse is true, if we are interested in the reverse flow graph. In that case the result is not necessarily a tree but a forest, because there may be nodes from which the EXIT_BLOCK is unreachable.
source is the ENTRY_BLOCK when reverse is false while it is the EXIT_BLOCK if reverse is true
Definition at line 367 of file Dominance.hpp.
References dom_info< GraphObj >::calc_dfs_tree_rec(), counter, DEBUG_LEVEL_VERY_PEDANTIC, dom_info< GraphObj >::dfsnum, dom_info< GraphObj >::en_block, INDENT_DBG_MEX, index, dom_info< GraphObj >::last_basic_block, and THROW_ASSERT.
Referenced by dominance< BBGraph >::calculate_dominance_info().
calc_dfs_tree_rec()
template<typename GraphObj>
void dom_info< GraphObj >::calc_dfs_tree_rec (Vertex bb) [inline], [private]
The recursive variant of creating a DFS tree.
After this is done all nodes reachable from BB were visited, have assigned their dfs number and are linked together to form a tree.
Parameters
bb is the basic block Vertex BB.
Definition at line 193 of file Dominance.hpp.
References DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, and dom_info< GraphObj >::last_basic_block.
Referenced by dom_info< GraphObj >::calc_dfs_tree().
calc_idoms()
template<typename GraphObj>
void dom_info< GraphObj >::calc_idoms (bool reverse) [inline]
This calculates the immediate dominators (or post-dominators if REVERSE is true).
On return the immediate dominator to node V is in dom[V].
Definition at line 454 of file Dominance.hpp.
References DEBUG_LEVEL_VERY_PEDANTIC, dom_info< GraphObj >::eval(), INDENT_DBG_MEX, dom_info< GraphObj >::last_basic_block, dom_info< GraphObj >::link_roots(), and dom_info< GraphObj >::nodes.
Referenced by dominance< BBGraph >::calculate_dominance_info().
compress()
template<typename GraphObj>
void dom_info< GraphObj >::compress (TBB v) [inline], [private]
Compress the path from V to the root of its set and update path_min at the same time.
After compress(V) set_chain[V] is the root of the set V is in and path_min[V] is the node with the smallest key[] value on the path from V to that root.
Parameters
v is the basic block ID of V.
Definition at line 234 of file Dominance.hpp.
Referenced by dom_info< GraphObj >::eval().
eval()
template<typename GraphObj>
TBB dom_info< GraphObj >::eval (TBB v) [inline], [private]
Compress the path from V to the set root of V if needed (when the root has changed since the last call).
Returns the node with the smallest key[] value on the path from V to the root.
Parameters
v is the basic block ID of V.
Definition at line 255 of file Dominance.hpp.
References dom_info< GraphObj >::compress().
Referenced by dom_info< GraphObj >::calc_idoms().
fill_dom_map()
template<typename GraphObj>
void dom_info< GraphObj >::fill_dom_map (CustomUnorderedMapStable< Vertex, Vertex > & dom_map) [inline]
fill the dominator map after its computation
Parameters
dom_map is the dominator map.
Definition at line 566 of file Dominance.hpp.
References DEBUG_LEVEL_VERY_PEDANTIC, dom_info< GraphObj >::en_block, and INDENT_DBG_MEX.
Referenced by dominance< BBGraph >::calculate_dominance_info().
link_roots()
template<typename GraphObj>
void dom_info< GraphObj >::link_roots (TBB v, TBB w) [inline], [private]
This essentially merges the two sets of V and W, giving a single set with the new root V.
The internal representation of these disjoint sets is a balanced tree. Currently link(V,W) is only used with V being the parent of W.
Definition at line 285 of file Dominance.hpp.
Referenced by dom_info< GraphObj >::calc_idoms().
Field Documentation
bucket
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::bucket [private]
bucket[x] points to the first node of the set of nodes having x as key.
Definition at line 120 of file Dominance.hpp.
debug_level
template<typename GraphObj>
int dom_info< GraphObj >::debug_level [private]
debug_level
Definition at line 185 of file Dominance.hpp.
dfs_order
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::dfs_order [private]
If b is the number of a basic block (index_map[bb_Vertex]), dfs_order[b] is the number of that node in DFS order counted from 1.
This is an index into most of the other arrays in this structure.
Definition at line 172 of file Dominance.hpp.
dfs_parent
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::dfs_parent [private]
The parent of a node in the DFS tree.
Definition at line 107 of file Dominance.hpp.
dfs_to_bb
template<typename GraphObj>
std::vector<Vertex> dom_info< GraphObj >::dfs_to_bb [private]
If x is the DFS-index of a node which corresponds with a basic block, dfs_to_bb[x] is that basic block.
Note, that in our structure there are more nodes that basic blocks, so only dfs_to_bb[dfs_order[index_map[bb]]]==bb is true for every basic block bb, but not the opposite.
Definition at line 179 of file Dominance.hpp.
dfsnum
template<typename GraphObj>
unsigned int dom_info< GraphObj >::dfsnum [private]
This is the next free DFS number when creating the DFS tree.
Definition at line 141 of file Dominance.hpp.
Referenced by dom_info< GraphObj >::calc_dfs_tree().
dom
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::dom [private]
After the algorithm is done, dom[x] contains the immediate dominator of x.
Definition at line 165 of file Dominance.hpp.
Referenced by dominance< BBGraph >::get_dominator_map().
en_block
template<typename GraphObj>
const Vertex& dom_info< GraphObj >::en_block [private]
Start block (ENTRY_BLOCK_PTR for forward problem, EXIT_BLOCK for backward problem).
Definition at line 156 of file Dominance.hpp.
Referenced by dom_info< GraphObj >::calc_dfs_tree(), and dom_info< GraphObj >::fill_dom_map().
ex_block
template<typename GraphObj>
const Vertex& dom_info< GraphObj >::ex_block [private]
Ending block.
Definition at line 159 of file Dominance.hpp.
fake_exit_edge
template<typename GraphObj>
CustomOrderedSet<TBB> dom_info< GraphObj >::fake_exit_edge [private]
Blocks with bits set here have a fake edge to EXIT.
These are used to turn a DFS forest into a proper tree.
Definition at line 150 of file Dominance.hpp.
g
template<typename GraphObj>
const GraphObj& dom_info< GraphObj >::g [private]
Flow graph reference.
Definition at line 162 of file Dominance.hpp.
index_map
template<typename GraphObj>
std::map<Vertex, size_t> dom_info< GraphObj >::index_map [private]
index map putting into relation vertices and arbitrary indexes.
Definition at line 182 of file Dominance.hpp.
key
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::key [private]
For a node x key[x] is roughly the node nearest to the root from which exists a way to x only over nodes behind x.
Such a node is also called semidominator.
Definition at line 114 of file Dominance.hpp.
last_basic_block
template<typename GraphObj>
const unsigned long int dom_info< GraphObj >::last_basic_block [private]
index of the last basic block
Definition at line 153 of file Dominance.hpp.
Referenced by dom_info< GraphObj >::calc_dfs_tree(), dom_info< GraphObj >::calc_dfs_tree_rec(), and dom_info< GraphObj >::calc_idoms().
next_bucket
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::next_bucket [private]
And next_bucket[x] points to the next node.
Definition at line 123 of file Dominance.hpp.
nodes
template<typename GraphObj>
unsigned int dom_info< GraphObj >::nodes [private]
The number of nodes in the DFS tree (==dfsnum-1).
Definition at line 144 of file Dominance.hpp.
Referenced by dom_info< GraphObj >::calc_idoms().
path_min
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::path_min [private]
The value in path_min[x] is the node y on the path from x to the root of the tree x is in with the smallest key[y].
Definition at line 117 of file Dominance.hpp.
set_chain
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::set_chain [private]
set_chain[x] is the next node on the path from x to the representant of the set containing x.
If set_chain[x]==0 then x is a root. It's similar to a reversed link list
Definition at line 130 of file Dominance.hpp.
set_child
template<typename GraphObj>
std::vector<TBB> dom_info< GraphObj >::set_child [private]
set_child[x] is used for balancing the tree representing a set.
It can be understood as the next sibling of x.
Definition at line 138 of file Dominance.hpp.
set_size
template<typename GraphObj>
std::vector<unsigned int> dom_info< GraphObj >::set_size [private]
set_size[x] is the number of elements in the set named by x.
Definition at line 133 of file Dominance.hpp.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/dominance/Dominance.hpp