mem_dominator_allocation Class Reference
Superclass include.
#include <mem_dominator_allocation.hpp>
Public Member Functions
mem_dominator_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::DOMINATOR_MEMORY_ALLOCATION)
Constructor.
~mem_dominator_allocation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
std::vector< unsigned int > getFunctionAllocationOrder (CustomOrderedSet< unsigned int > top_functions)
Additional Inherited Members
Detailed Description
Superclass include.
STL includes
Definition at line 51 of file mem_dominator_allocation.hpp.
Constructor & Destructor Documentation
mem_dominator_allocation()
mem_dominator_allocation::mem_dominator_allocation (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStepSpecializationConstRef _hls_flow_step_specialization, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::DOMINATOR_MEMORY_ALLOCATION)
Constructor.
STD includes.
Parameters
design_flow_manager is the design flow manager
STL includes technology include tree includes
Definition at line 90 of file mem_dominator_allocation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and ~mem_dominator_allocation().
 mem_dominator_allocation()
mem_dominator_allocation::~mem_dominator_allocation () [override], [default]
Destructor.
Referenced by mem_dominator_allocation().
Member Function Documentation
getFunctionAllocationOrder()
std::vector< unsigned int > mem_dominator_allocation::getFunctionAllocationOrder (CustomOrderedSet< unsigned int > top_functions) [protected]
Definition at line 116 of file mem_dominator_allocation.cpp.
References buildAllocationOrderRecursively(), and HLS_step::HLSMgr.
Referenced by InternalExec().
Initialize()
void mem_dominator_allocation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 112 of file mem_dominator_allocation.cpp.
InternalExec()
DesignFlowStep_Status mem_dominator_allocation::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
TODO: to be fixed with information coming out from the target platform description
information about memory allocation to be shared across the functions
the analysis has to be performed only on the reachable functions
we do not need the exit vertex since the post-dominator graph is not used
custom function like printf may create problem to the pointer resolution
var referring vertex map
compute the number of instances for each function
find the common dominator and decide where to allocate
look for a single instance function in case the object is not a ROM and not a local var
find the common dominator between two candidates
classify variable
check dynamic address use
we never have &(var_index_object)
read only memory
we never have &(var_index_object)
used in a single place
we never have &(var_index_object)
change the alignment in case is requested
change the internal alignment to improve the decoding logic
Round up to the next highest power of 2
really allocate
check dynamic address use
we never have &(var_index_object)
read only memory
add proxies
clean proxy library
Implements memory_allocation.
Definition at line 145 of file mem_dominator_allocation.cpp.
References tree_helper::accessed_greatest_bitsize(), tree_helper::accessed_minimum_bitsize(), ALL_BRAM, memory_allocation::allocate_parameters(), BUILTIN_WAIT_CALL, FunctionBehavior::CFG, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), tree_manager::CGetTreeNode(), compute_n_bytes(), memory::create_memory(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, technology_manager::erase_library(), EXT_PIPELINED_BRAM, memory_allocation::finalize_memory_allocation(), memory_allocation::func_list, tree_helper::get_array_data_bitsize(), tree_helper::get_base_index(), FunctionBehavior::get_dynamic_address(), FunctionBehavior::get_function_mem(), BehavioralHelper::get_function_name(), FunctionBehavior::get_has_undefined_function_receiving_pointers(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NAME, GET_NODE, target_device::get_parameter(), get_remapped_vertex(), target_manager::get_target_device(), target_manager::get_technology_manager(), tree_manager::get_tree_node_const(), GET_TYPE, tree_helper::get_type_index(), getFunctionAllocationOrder(), GSS, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, INTERN_UNALIGNED, tree_helper::is_a_complex(), FunctionBehavior::is_a_state_variable(), tree_helper::is_a_struct(), tree_helper::is_an_array(), tree_helper::is_an_union(), tree_helper::is_fully_resolved(), tree_helper::is_packed(), FunctionBehavior::is_variable_mem(), LSS, max(), MEMCMP, MEMCPY, memory_allocation::memory_allocation_policy, MEMSET, NO_BRAM, NONE, NULL_VERTEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, print_cpu_time(), BehavioralHelper::PrintVariable(), PROXY_LIBRARY, memory_allocation::setup_memory_allocation(), tree_helper::size(), START_TIME, STOP_TIME, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, THROW_WARNING, tree_node::ToString(), TYPE_LOAD, TYPE_STORE, UNCHANGED, WB4_INTERFACE_GENERATION, and WORK_LIBRARY.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/mem_dominator_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/mem_dominator_allocation.cpp