LoadTechnology Class Reference
Step which loads device dependent technology information.
#include <load_technology.hpp>
Public Member Functions
LoadTechnology (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~LoadTechnology () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
void PrintFinalIR () const override
Dump the final intermediate representation.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Step which loads device dependent technology information.
Definition at line 56 of file load_technology.hpp.
Constructor & Destructor Documentation
LoadTechnology()
LoadTechnology::LoadTechnology (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
TM is the technology manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include STD include STL include technology includes technology/target_device include utility includes
Definition at line 64 of file load_technology.cpp.
References DesignFlowStep::composed, DesignFlowStep::debug_level, GET_CLASS, LOAD_TECHNOLOGY, DesignFlowStep::parameters, and ~LoadTechnology().
 LoadTechnology()
LoadTechnology::~LoadTechnology () [override], [default]
Destructor.
Referenced by LoadTechnology().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > LoadTechnology::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 73 of file load_technology.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_DEFAULT_TECHNOLOGY, LOAD_DEVICE_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and WRITE_TECHNOLOGY.
Exec()
DesignFlowStep_Status LoadTechnology::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 110 of file load_technology.cpp.
References EMPTY.
PrintFinalIR()
void LoadTechnology::PrintFinalIR () const [override], [virtual]
Dump the final intermediate representation.
Reimplemented from DesignFlowStep.
Definition at line 115 of file load_technology.cpp.
References TechnologyFlowStep::GetName(), DesignFlowStep::parameters, technology_manager::print(), and TechnologyFlowStep::TM.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_technology.cpp