XmlFlexLexer Struct Reference
#include <xmlLexer.hpp>
Public Member Functions
XmlFlexLexer (std::string _name, std::istream *argin=nullptr, std::ostream *argout=nullptr)
~XmlFlexLexer () override=default
void yyerror (const char *msg)
void LexerError (const char *msg) override
int yywrap () override
int yylex () override
Data Fields
const std::string name
The name of the parsed file/string.
int keep
To store start condition.
YYSTYPE * lvalp
Detailed Description
Definition at line 61 of file xmlLexer.hpp.
Constructor & Destructor Documentation
XmlFlexLexer()
XmlFlexLexer::XmlFlexLexer (std::string _name, std::istream * argin = nullptr, std::ostream * argout = nullptr) [inline]
Definition at line 66 of file xmlLexer.hpp.
References ~XmlFlexLexer().
 XmlFlexLexer()
XmlFlexLexer::~XmlFlexLexer () [override], [default]
Referenced by XmlFlexLexer().
Member Function Documentation
LexerError()
void XmlFlexLexer::LexerError (const char * msg) [inline], [override]
Definition at line 74 of file xmlLexer.hpp.
References exit_code, INDENT_OUT_MEX, STR, and THROW_ERROR.
Referenced by yyerror().
yyerror()
void XmlFlexLexer::yyerror (const char * msg) [inline]
Definition at line 70 of file xmlLexer.hpp.
References LexerError().
yylex()
int XmlFlexLexer::yylex () [override]
yywrap()
int XmlFlexLexer::yywrap () [inline], [override]
Definition at line 80 of file xmlLexer.hpp.
Field Documentation
keep
int XmlFlexLexer::keep
To store start condition.
Definition at line 85 of file xmlLexer.hpp.
lvalp
YYSTYPE* XmlFlexLexer::lvalp
Definition at line 86 of file xmlLexer.hpp.
name
const std::string XmlFlexLexer::name
The name of the parsed file/string.
Definition at line 64 of file xmlLexer.hpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/parser/polixml/xmlLexer.hpp