memory_allocation Class Reference
Allocation memory class.
#include <memory_allocation.hpp>
Public Member Functions
memory_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization=HLSFlowStepSpecializationConstRef())
Constructor.
~memory_allocation () override
Destructor.
void allocate_parameters (unsigned int functionId)
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
void setup_memory_allocation ()
Prepares the datastructures for the memory allocation.
void finalize_memory_allocation ()
Performs a final analysis of the memory allocation to finalize the datastructure.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
virtual DesignFlowStep_Status InternalExec ()=0
Execute the step.
Protected Attributes
CustomOrderedSet< unsigned int > func_list
list of functions to be analyzed
const MemoryAllocation_Policy memory_allocation_policy
The memory allocation policy.
unsigned int memory_version
The version of memory representation on which this step was applied.
std::map< unsigned int, unsigned int > last_bb_ver
The version of BB IR representation on which this step was applied.
std::map< unsigned int, unsigned int > last_bitvalue_ver
The version of bit value IR representation on which this step was applied.
Additional Inherited Members
Detailed Description
Allocation memory class.
Definition at line 111 of file memory_allocation.hpp.
Constructor & Destructor Documentation
memory_allocation()
memory_allocation::memory_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization = HLSFlowStepSpecializationConstRef())
Constructor.
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the algorithm to be used
Definition at line 144 of file memory_allocation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~memory_allocation().
 memory_allocation()
memory_allocation::~memory_allocation () [override], [default]
Destructor.
Referenced by memory_allocation().
Member Function Documentation
allocate_parameters()
void memory_allocation::allocate_parameters (unsigned int functionId)
Definition at line 553 of file memory_allocation.cpp.
References FunctionBehavior::CGetBehavioralHelper(), BehavioralHelper::get_function_index(), BehavioralHelper::get_parameters(), BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, INDENT_OUT_MEX, tree_helper::name_function(), DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, BehavioralHelper::PrintVariable(), tree_helper::size(), and STR.
Referenced by mem_dominator_allocation::InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > memory_allocation::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 159 of file memory_allocation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status memory_allocation::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 608 of file memory_allocation.cpp.
References FunctionBehavior::GetBBVersion(), FunctionBehavior::GetBitValueVersion(), HLS_step::HLSMgr, InternalExec(), last_bb_ver, last_bitvalue_ver, and memory_version.
Referenced by mem_dominator_allocation_cs::Exec().
finalize_memory_allocation()
void memory_allocation::finalize_memory_allocation () [protected]
Performs a final analysis of the memory allocation to finalize the datastructure.
looking for the maximum data bus size needed
check for packed struct/union accesses
check if a global variable may be accessed from an external component
an external component can access the var possibly (global and volatile vars)
Definition at line 212 of file memory_allocation.cpp.
References tree_helper::accessed_greatest_bitsize(), ALL_BRAM, FunctionBehavior::CFG, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, func_list, tree_helper::get_base_index(), FunctionBehavior::get_dereference_unknown_addr(), BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), FunctionBehavior::get_has_globals(), GET_INDEX_NODE, tree_node::get_kind(), tree_helper::get_mangled_fname(), GET_NAME, GET_NODE, target_device::get_parameter(), BehavioralHelper::get_parameters(), FunctionBehavior::get_parm_decl_stored(), FunctionBehavior::get_pointer_type_conversion(), target_manager::get_target_device(), GET_TYPE, tree_helper::get_type_index(), tree_helper::get_type_node(), FunctionBehavior::get_unaligned_accesses(), BehavioralHelper::GetFunctionReturnType(), FunctionBehavior::has_packed_vars(), HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, index, INFERRED_INTERFACE_GENERATION, tree_helper::is_a_complex(), tree_helper::is_a_misaligned_vector(), tree_helper::is_a_pointer(), tree_helper::is_a_struct(), tree_helper::is_an_union(), tree_helper::is_packed_access(), FunctionBehavior::is_variable_mem(), tree_helper::is_volatile(), max(), MEMCMP, MEMCPY, MEMSET, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, PRINT_DBG_MEX, resize_to_1_8_16_32_64_128_256_512(), tree_helper::size(), STR, THROW_ASSERT, THROW_ERROR, THROW_WARNING, ToString(), tree_node::ToString(), TYPE_LOAD, TYPE_STORE, and WB4_INTERFACE_GENERATION.
Referenced by mem_xml_allocation::finalize_memory_allocation(), and mem_dominator_allocation::InternalExec().
HasToBeExecuted()
bool memory_allocation::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 592 of file memory_allocation.cpp.
References FunctionBehavior::GetBBVersion(), HLS_step::HLSMgr, last_bb_ver, and memory_version.
InternalExec()
virtual DesignFlowStep_Status memory_allocation::InternalExec () [protected], [pure virtual]
Execute the step.
Returns
the exit status of this step
Implemented in mem_xml_allocation, and mem_dominator_allocation.
Referenced by Exec().
setup_memory_allocation()
void memory_allocation::setup_memory_allocation () [protected]
Prepares the datastructures for the memory allocation.
the analysis has to be performed only on the reachable functions
add parm_decls that have to be copied
add parm_decls that have to be stored
add actual parameters that have to be loaded
Definition at line 183 of file memory_allocation.cpp.
References func_list, FunctionBehavior::get_parm_decl_copied(), FunctionBehavior::get_parm_decl_loaded(), FunctionBehavior::get_parm_decl_stored(), and HLS_step::HLSMgr.
Referenced by mem_dominator_allocation::InternalExec(), and mem_xml_allocation::parse_xml_allocation().
Field Documentation
func_list
CustomOrderedSet<unsigned int> memory_allocation::func_list [protected]
list of functions to be analyzed
Definition at line 115 of file memory_allocation.hpp.
Referenced by finalize_memory_allocation(), mem_dominator_allocation::InternalExec(), and setup_memory_allocation().
last_bb_ver
std::map<unsigned int, unsigned int> memory_allocation::last_bb_ver [protected]
The version of BB IR representation on which this step was applied.
Definition at line 124 of file memory_allocation.hpp.
Referenced by Exec(), and HasToBeExecuted().
last_bitvalue_ver
std::map<unsigned int, unsigned int> memory_allocation::last_bitvalue_ver [protected]
The version of bit value IR representation on which this step was applied.
Definition at line 127 of file memory_allocation.hpp.
Referenced by Exec().
memory_allocation_policy
const MemoryAllocation_Policy memory_allocation::memory_allocation_policy [protected]
The memory allocation policy.
Definition at line 118 of file memory_allocation.hpp.
Referenced by mem_dominator_allocation::InternalExec().
memory_version
unsigned int memory_allocation::memory_version [protected]
The version of memory representation on which this step was applied.
Definition at line 121 of file memory_allocation.hpp.
Referenced by Exec(), and HasToBeExecuted().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/memory_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/memory_allocation.cpp