compute_implicit_calls Class Reference
#include <compute_implicit_calls.hpp>
Public Member Functions
compute_implicit_calls (const ParameterConstRef parameters, const application_managerRef AppM, unsigned int function_idi, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~compute_implicit_calls () override
Destructor.
DesignFlowStep_Status InternalExec () override
Determines the variables that require a memory access.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
tree_managerRef TM
The tree manager.
Additional Inherited Members
Detailed Description
Definition at line 60 of file compute_implicit_calls.hpp.
Constructor & Destructor Documentation
compute_implicit_calls()
compute_implicit_calls::compute_implicit_calls (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
This step do the lowering of two types of implicit memory operations: memset and memcpy implicit patterns.
Parameters
parameters is the set of input parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
Currently, only the memset implicit pattern is managed.
For the memset we look for this pattern: BB1: (xxxxa)* var = {}; (xxxxb)*
and we translate such code into this one: BB1: (xxxxa)* upperlimit=varsize+var; BBN1: i0=phi(var,i1) i1=i0+sizeof(item of var); i0* = 0; if(i1!= upperlimit) goto BBN1; BBN2: (xxxxb)* Note that implicit memory virtual definition has to be translated from `var = {};` into `var[i0] = 0;`.Header include Behavior include Parameter include Tree include
Definition at line 95 of file compute_implicit_calls.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~compute_implicit_calls().
 compute_implicit_calls()
compute_implicit_calls::~compute_implicit_calls () [override], [default]
Destructor.
Referenced by compute_implicit_calls().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > compute_implicit_calls::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 103 of file compute_implicit_calls.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status compute_implicit_calls::InternalExec () [override], [virtual]
Determines the variables that require a memory access.
check for implicit memset/memcpy calls
do the memset transformations
create BBN1
Add BBN1 predecessor as BB1_index basic block
create BBN2
Add BBN2 predecessor as BBN1 basic block
Add BBN2 successor as BB1 basic block
fix true and false edges
Add BBN1 successor as succ basic block
Fix BBN2 successors
Update all the phis
The tree manipulation
retrieve the starting variable
add a cast
Create phi for the induction variable of BBN1
The list of def edge which contains for the moment only the value coming from the forward edge
compute the size of memory to be set with memset
the comparison
the gimple cond
restructure of the implicit memset statement
We must use pointer since we are erasing elements in the list
move var = {}; to BBN1
Going one step step forward to avoid invalidation of the pointer
Moving statement
Going one step back since pointer is already increment in for loop
move (xxxxb)* to BBN2
Going one step step forward to avoid invalidation of the pointer
Moving statement
Going one step back since pointer is already increment in for loop
Implements FunctionFrontendFlowStep.
Definition at line 129 of file compute_implicit_calls.cpp.
References FrontendFlowStep::AppM, BB_ENTRY, BB_EXIT, tree_helper::CGetElements(), tree_manager::CGetTreeNode(), tree_helper::CGetType(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, FunctionFrontendFlowStep::function_id, tree_manager::function_index(), tree_helper::get_base_index(), GET_INDEX_CONST_NODE, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_helper::get_type_node(), FunctionFrontendFlowStep::GetSignature(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_helper::is_a_vector(), max(), DesignFlowStep::parameters, phi, PRINT_DBG_MEX, tree_helper::Size(), sl, STR, SUCCESS, THROW_ASSERT, TM, ToString(), tree_node::ToString(), UNCHANGED, and PointToSolution::variables.
Field Documentation
TM
tree_managerRef compute_implicit_calls::TM [private]
The tree manager.
Definition at line 64 of file compute_implicit_calls.hpp.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/compute_implicit_calls.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/compute_implicit_calls.cpp