component_o Class Reference
This class describes a generic component.
#include <structural_objects.hpp>
Public Member Functions
component_o (int debug_level, const structural_objectRef o)
Constructor.
~component_o () override=default
destructor
void copy (structural_objectRef dest) const override
Perform a copy of the component.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the component (for debug purpose)
Additional Inherited Members
Detailed Description
This class describes a generic component.
Definition at line 2271 of file structural_objects.hpp.
Constructor & Destructor Documentation
component_o()
component_o::component_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the component.
Definition at line 3990 of file structural_objects.cpp.
 component_o()
component_o::~component_o () [override], [default]
destructor
Member Function Documentation
copy()
void component_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the component.
Parameters
dest destination object.
Reimplemented from module.
Definition at line 3999 of file structural_objects.cpp.
References module::copy().
find_isomorphic()
structural_objectRef component_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Reimplemented from module.
Definition at line 4004 of file structural_objects.cpp.
References module::find_isomorphic().
find_member()
structural_objectRef component_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Reimplemented from module.
Definition at line 3994 of file structural_objects.cpp.
References module::find_member().
print()
void component_o::print (std::ostream & os) const [override], [virtual]
Print the component (for debug purpose)
Parameters
os is an output stream
Reimplemented from module.
Definition at line 4027 of file structural_objects.cpp.
References module::print().
xload()
void component_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
Implements module.
Definition at line 4009 of file structural_objects.cpp.
References module::xload().
xwrite()
void component_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Implements module.
Definition at line 4014 of file structural_objects.cpp.
References xml_child::add_child_element(), structural_object::get_kind_text(), and module::xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp