CdfcGraph Class Reference
Cdfc graph.
#include <cdfc_module_binding.hpp>
Public Member Functions
CdfcGraph (const CdfcGraphsCollectionRef cdfc_graphs_collection, const int selector)
Constructor.
CdfcGraph (const CdfcGraphsCollectionRef cdfc_graphs_collection, const int selector, const CustomUnorderedSet< vertex > &vertices)
Constructor.
~CdfcGraph () override
Destructor.
const CdfcEdgeInfoConstRef CGetCdfcEdgeInfo (const EdgeDescriptor e) const
Returns the info associated with an edge.
void WriteDot (const std::string &file_name, const int detail_level=0) const
Writes this graph in dot format.
Additional Inherited Members
Detailed Description
Cdfc graph.
Definition at line 301 of file cdfc_module_binding.hpp.
Constructor & Destructor Documentation
CdfcGraph() [1/2]
CdfcGraph::CdfcGraph (const CdfcGraphsCollectionRef cdfc_graphs_collection, const int selector)
Constructor.
Parameters
cdfc_graphs_collection is the collections of graph to which this graph belongs
selector is the selector which identifies the edges of this graph
Definition at line 698 of file cdfc_module_binding.cpp.
CdfcGraph() [2/2]
CdfcGraph::CdfcGraph (const CdfcGraphsCollectionRef cdfc_graphs_collection, const int selector, const CustomUnorderedSet< vertex > & vertices)
Constructor.
Parameters
cdfc_graphs_collection is the collections of graph to which this graph belongs
selector is the selector which identifies the edges of this graph
vertices is the set of vertexes on which the graph is filtered.
Definition at line 702 of file cdfc_module_binding.cpp.
References ~CdfcGraph().
 CdfcGraph()
CdfcGraph::~CdfcGraph () [override], [default]
Destructor.
Referenced by CdfcGraph().
Member Function Documentation
CGetCdfcEdgeInfo()
const CdfcEdgeInfoConstRef CdfcGraph::CGetCdfcEdgeInfo (const EdgeDescriptor e) const [inline]
Returns the info associated with an edge.
Definition at line 327 of file cdfc_module_binding.hpp.
References graph::CGetEdgeInfo().
WriteDot()
void CdfcGraph::WriteDot (const std::string & file_name, const int detail_level = 0) const
Writes this graph in dot format.
Parameters
file_name is the file where the graph has to be printed
detail_level is the detail level of the printed graph
Definition at line 708 of file cdfc_module_binding.cpp.
References graph::CGetGraphInfo(), graph::collection, test_panda::full_name, and graphs_collection::parameters.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/cdfc_module_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/cdfc_module_binding.cpp