/home/osboxes/bambu/PandA-bambu/src/algorithms/graph_helpers/cyclic_topological_sort.hpp File Reference
File used to compute the topological sort in a cyclic graph.
#include `boost/graph/depth_first_search.hpp`
Data Structures
struct cyclic_topological_sort_visitor< OutputIterator >
Functions
template<typename VertexListGraph , typename OutputIterator , typename P , typename T , typename R >
void cyclic_topological_sort (VertexListGraph &g, OutputIterator result, const boost::bgl_named_params< P, T, R > &params)
template<typename VertexListGraph , typename OutputIterator >
void cyclic_topological_sort (VertexListGraph &g, OutputIterator result)
Detailed Description
File used to compute the topological sort in a cyclic graph.
File used to compute the topological sort in a cyclic graph
Author
Christian Pilato pilato@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
cyclic_topological_sort() [1/2]
template<typename VertexListGraph , typename OutputIterator , typename P , typename T , typename R >
void cyclic_topological_sort (VertexListGraph & g, OutputIterator result, const boost::bgl_named_params< P, T, R > & params)
Definition at line 68 of file cyclic_topological_sort.hpp.
Referenced by cyclic_topological_sort(), simple_code_motion::InternalExec(), and multi_way_if::InternalExec().
cyclic_topological_sort() [2/2]
template<typename VertexListGraph , typename OutputIterator >
void cyclic_topological_sort (VertexListGraph & g, OutputIterator result)
Definition at line 75 of file cyclic_topological_sort.hpp.
References cyclic_topological_sort().