Wrefcount< T > Struct Template Reference
#include <refcount.hpp>
Public Member Functions
Wrefcount ()
Wrefcount (Wrefcount< T > const &other)
Wrefcount (refcount< T > const &other)
~Wrefcount ()
Wrefcount< T > & operator= (Wrefcount< T > const &other)
Wrefcount< T > & operator= (refcount< T > const &other)
refcount< T > lock () const
Private Attributes
T * ptr
Detailed Description
template<typename T>
struct Wrefcount< T >
Definition at line 77 of file refcount.hpp.
Constructor & Destructor Documentation
Wrefcount() [1/3]
template<typename T>
Wrefcount< T >::Wrefcount () [inline]
Definition at line 188 of file refcount.hpp.
Wrefcount() [2/3]
template<typename T>
Wrefcount< T >::Wrefcount (Wrefcount< T > const & other) [inline]
Definition at line 192 of file refcount.hpp.
Wrefcount() [3/3]
template<typename T>
Wrefcount< T >::Wrefcount (refcount< T > const & other) [inline]
Definition at line 196 of file refcount.hpp.
 Wrefcount()
template<typename T>
Wrefcount< T >::~Wrefcount () [inline]
Definition at line 199 of file refcount.hpp.
Member Function Documentation
lock()
template<typename T>
refcount<T> Wrefcount< T >::lock () const [inline]
Definition at line 212 of file refcount.hpp.
Referenced by Schedule::CanBeMoved(), DesignFlow::CGetDesignFlowStepFactory(), ToDataFileStep::CGetDesignFlowStepFactory(), ParserFlowStep::CGetDesignFlowStepFactory(), TechnologyFlowStep::CGetDesignFlowStepFactory(), CBackend::CGetDesignFlowStepFactory(), HLS_step::CGetDesignFlowStepFactory(), FrontendFlowStep::CGetDesignFlowStepFactory(), SerializeMutualExclusions::ComputeFrontendRelationships(), AggregateDataFlowAnalysis::ComputeFrontendRelationships(), use_counting::ComputeFrontendRelationships(), commutative_expr_restructuring::ComputeFrontendRelationships(), CondExprRestructuring::ComputeFrontendRelationships(), RemoveEndingIf::ComputeFrontendRelationships(), short_circuit_taf::ComputeFrontendRelationships(), CreateAddressTranslation::ComputeFrontendRelationships(), HLSSynthesisFlow::ComputeHLSRelationships(), TestbenchGenerationBaseStep::ComputeHLSRelationships(), HLSBitValue::ComputeRelationships(), CTestbenchExecution::ComputeRelationships(), create_tree_manager::ComputeRelationships(), BitValueIPA::ComputeRelationships(), fun_dominator_allocation::ComputeRelationships(), TasteInterfaceGeneration::ComputeRelationships(), AggregateDataFlowAnalysis::ComputeRelationships(), GenerateFuList::ComputeRelationships(), BambuFrontendFlow::ComputeRelationships(), BasicBlocksProfiling::ComputeRelationships(), use_counting::ComputeRelationships(), BuildVirtualPhi::ComputeRelationships(), TestbenchValuesCGeneration::ComputeRelationships(), FunctionFrontendFlowStep::ComputeRelationships(), HLSFunctionStep::ComputeRelationships(), interface_infer::ComputeRelationships(), CBackend::ComputeRelationships(), TechnologyFlowStep::ComputeRelationships(), lut_transformation::ComputeRelationships(), IR_lowering::ComputeRelationships(), SDCScheduling::ComputeRelationships(), RTLCharacterization::ComputeRelationships(), PhiOpt::ComputeRelationships(), parametric_list_based::ComputeRelationships(), HLS_step::ComputeRelationships(), FrontendFlowStep::ComputeRelationships(), StateTransitionGraph_constructor::connect_state(), StateTransitionGraph_constructor::create_entry_state(), StateTransitionGraph_constructor::create_exit_state(), FrontendFlowStepFactory::CreateApplicationFrontendFlowStep(), CBackendStepFactory::CreateCBackendStep(), DesignFlowFactory::CreateDesignFlow(), ParserFlowStepFactory::CreateFlowStep(), FrontendFlowStepFactory::CreateFunctionFrontendFlowStep(), HLSFlowStepFactory::CreateHLSFlowStep(), ToDataFileStepFactory::CreateStep(), TechnologyFlowStepFactory::CreateTechnologyFlowStep(), Schedule::EvaluateMultiWayIfsMerging(), FrontendFlowStepFactory::GenerateFrontendStep(), StorageValueInformation::get_compatibility_weight(), structural_object::get_owner(), Schedule::GetBBEndingTime(), DesignFlowStep::GetStatus(), HLSFunctionStep::HasToBeExecuted(), dom_post_dom_computation::HasToBeExecuted(), CondExprRestructuring::HasToBeExecuted(), commutative_expr_restructuring::HasToBeExecuted(), simple_code_motion::HasToBeExecuted(), MultipleEntryIfReduction::HasToBeExecuted(), multi_way_if::HasToBeExecuted(), ChainingInformation::Initialize(), operations_cfg_computation::Initialize(), Schedule::Initialize(), Bit_Value::Initialize(), SDCCodeMotion::InternalExec(), BasicBlocksCfgComputation::InternalExec(), HLSFunctionBitValue::InternalExec(), dom_post_dom_computation::InternalExec(), simple_code_motion::InternalExec(), cdfc_module_binding::InternalExec(), StateInfo::print(), and Schedule::UpdateTime().
operator=() [1/2]
template<typename T>
Wrefcount<T>& Wrefcount< T >::operator= (Wrefcount< T > const & other) [inline]
Definition at line 202 of file refcount.hpp.
operator=() [2/2]
template<typename T>
Wrefcount<T>& Wrefcount< T >::operator= (refcount< T > const & other) [inline]
Definition at line 207 of file refcount.hpp.
Field Documentation
ptr
template<typename T>
T* Wrefcount< T >::ptr [private]
Definition at line 185 of file refcount.hpp.
Referenced by Wrefcount< const HLS_manager >::operator=().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/utility/refcount.hpp