time_model Class Reference
#include <time_model.hpp>
Public Types
enum path_t { POST_SYNTHESIS = 1,
POST_LAYOUT = 2
 }
type of the timing path
Public Member Functions
time_model (const ParameterConstRef Param)
Constructor.
virtual ~time_model ()
Destructor.
virtual void xwrite (xml_element *pin_node, const std::string &output_pin)=0
virtual unsigned int xload_timing_path (xml_element *node)
std::vector< std::string > get_critical_path (unsigned int type) const
bool has_max_delay (unsigned int type) const
void set_max_delay (unsigned int type, float value)
float get_max_delay (unsigned int type) const
void set_initiation_time (const ControlStep _initiation_time)
ControlStep get_initiation_time () const
unsigned int get_cycles () const
double get_stage_period () const
void set_stage_period (double st_per)
void set_execution_time (double execution_time, unsigned int cycles)
void set_synthesis_dependent (bool value)
bool get_synthesis_dependent () const
double get_execution_time () const
Static Public Member Functions
static time_modelRef create_model (TargetDevice_Type dv_type, const ParameterConstRef Param)
Data Fields
boost::math::normal statistical_delay
statistical delay for this type of operation on a given functional unit.
std::map< std::string, std::map< std::string, double > > pin_to_pin_delay
map representing the pin-to-pin delay
Static Public Attributes
 Default values associated with the members of the operation class.
static const double execution_time_DEFAULT = 0
Autoheader include.
static const ControlStep initiation_time_DEFAULT = ControlStep(0u)
static const unsigned int cycles_time_DEFAULT = 0
zero means that the operation is not pipelined
static const double stage_period_DEFAULT = 0
zero means that the operation last in ceil(execution_time/clock_period)
Protected Attributes
const ParameterConstRef Param
class containing all the parameters
std::map< unsigned int, std::vector< std::string > > critical_paths
map containing all the information about critical paths
std::map< unsigned int, float > max_delay
ControlStep initiation_time
initiation time, in terms of cycle_units, for this type of operation on a given functional unit.
unsigned int cycles
number of cycles required to complete the computation
bool synthesis_dependent
flag to check if the number of cycles are dependent on the synthesis or not
double stage_period
critical timing execution path, in term of ns, of a potentially pipelined operation.
double execution_time
execution time, in terms of ns, for this type of operation on a given functional unit.
Detailed Description
Definition at line 74 of file time_model.hpp.
Member Enumeration Documentation
path_t
enum time_model::path_t
type of the timing path
Enumerator
POST_SYNTHESIS
POST_LAYOUT
Definition at line 84 of file time_model.hpp.
Constructor & Destructor Documentation
time_model()
time_model::time_model (const ParameterConstRef Param) [explicit]
Constructor.
zero means a non-pipelined operation
Definition at line 70 of file time_model.cpp.
References ~time_model().
 time_model()
time_model::~time_model () [virtual], [default]
Destructor.
Referenced by time_model().
Member Function Documentation
create_model()
time_modelRef time_model::create_model (TargetDevice_Type dv_type, const ParameterConstRef Param) [static]
Definition at line 129 of file time_model.cpp.
References FPGA, and THROW_UNREACHABLE.
Referenced by allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), OmpAllocation::AddPandaPthreadMutex(), RTLCharacterization::AnalyzeCell(), AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), interface_infer::create_resource_array(), interface_infer::create_resource_Read_simple(), interface_infer::create_resource_Write_simple(), FunctionalUnitStep::create_template_instance(), add_library::InternalExec(), DesignCompilerWrapper::parse_time_reports(), XilinxBackendFlow::parse_timing(), operation::xload(), functional_unit::xload(), and XilinxBackendFlow::xparse_timing().
get_critical_path()
std::vector< std::string > time_model::get_critical_path (unsigned int type) const
Definition at line 193 of file time_model.cpp.
References critical_paths, and THROW_ASSERT.
get_cycles()
unsigned int time_model::get_cycles () const
Definition at line 114 of file time_model.cpp.
References cycles.
Referenced by allocation::check_templated_units(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and operation::xwrite().
get_execution_time()
double time_model::get_execution_time () const
Definition at line 99 of file time_model.cpp.
References execution_time.
Referenced by SynthesisEvaluation::InternalExec(), operation::print(), AllocationInformation::time_m_execution_time(), and operation::xwrite().
get_initiation_time()
ControlStep time_model::get_initiation_time () const
Definition at line 109 of file time_model.cpp.
References initiation_time.
Referenced by AllocationInformation::get_correction_time(), operation::print(), and operation::xwrite().
get_max_delay()
float time_model::get_max_delay (unsigned int type) const
Definition at line 209 of file time_model.cpp.
References has_max_delay(), max_delay, and THROW_ASSERT.
get_stage_period()
double time_model::get_stage_period () const
Definition at line 119 of file time_model.cpp.
References stage_period.
Referenced by AllocationInformation::time_m_stage_period(), and operation::xwrite().
get_synthesis_dependent()
bool time_model::get_synthesis_dependent () const
Definition at line 94 of file time_model.cpp.
References synthesis_dependent.
Referenced by operation::xwrite().
has_max_delay()
bool time_model::has_max_delay (unsigned int type) const
Definition at line 199 of file time_model.cpp.
References max_delay.
Referenced by get_max_delay().
set_execution_time()
void time_model::set_execution_time (double execution_time, unsigned int cycles)
Definition at line 83 of file time_model.cpp.
References cycles, and execution_time.
Referenced by RTLCharacterization::AnalyzeCell(), interface_infer::create_resource_array(), interface_infer::create_resource_Read_simple(), interface_infer::create_resource_Write_simple(), FunctionalUnitStep::create_template_instance(), DesignCompilerWrapper::parse_time_reports(), and operation::xload().
set_initiation_time()
void time_model::set_initiation_time (const ControlStep _initiation_time)
Definition at line 104 of file time_model.cpp.
References initiation_time.
Referenced by operation::xload().
set_max_delay()
void time_model::set_max_delay (unsigned int type, float value)
Definition at line 204 of file time_model.cpp.
References max_delay, and test_panda::type.
set_stage_period()
void time_model::set_stage_period (double st_per)
Definition at line 124 of file time_model.cpp.
References stage_period.
Referenced by RTLCharacterization::AnalyzeCell(), and operation::xload().
set_synthesis_dependent()
void time_model::set_synthesis_dependent (bool value)
Definition at line 89 of file time_model.cpp.
References synthesis_dependent.
Referenced by operation::xload().
xload_timing_path()
unsigned int time_model::xload_timing_path (xml_element * node) [virtual]
Definition at line 145 of file time_model.cpp.
References critical_paths, xml_child::get_children(), LOAD_XVM, POST_LAYOUT, POST_SYNTHESIS, THROW_ASSERT, THROW_ERROR, and test_panda::type.
xwrite()
virtual void time_model::xwrite (xml_element * pin_node, const std::string & output_pin) [pure virtual]
Implemented in LUT_model, and liberty_model.
Field Documentation
critical_paths
std::map<unsigned int, std::vector<std::string> > time_model::critical_paths [protected]
map containing all the information about critical paths
Definition at line 95 of file time_model.hpp.
Referenced by get_critical_path(), and xload_timing_path().
cycles
unsigned int time_model::cycles [protected]
number of cycles required to complete the computation
Definition at line 103 of file time_model.hpp.
Referenced by get_cycles(), and set_execution_time().
cycles_time_DEFAULT
const unsigned int time_model::cycles_time_DEFAULT = 0 [static]
zero means that the operation is not pipelined
Definition at line 163 of file time_model.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), operation::xload(), and operation::xwrite().
execution_time
double time_model::execution_time [protected]
execution time, in terms of ns, for this type of operation on a given functional unit.
Definition at line 111 of file time_model.hpp.
Referenced by get_execution_time(), set_execution_time(), and LUT_model::set_timing_value().
execution_time_DEFAULT
const double time_model::execution_time_DEFAULT = 0 [static]
Autoheader include.
HLS/scheduling include
Definition at line 161 of file time_model.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), operation::xload(), and operation::xwrite().
initiation_time
ControlStep time_model::initiation_time [protected]
initiation time, in terms of cycle_units, for this type of operation on a given functional unit.
Definition at line 100 of file time_model.hpp.
Referenced by get_initiation_time(), and set_initiation_time().
initiation_time_DEFAULT
const ControlStep time_model::initiation_time_DEFAULT = ControlStep(0u) [static]
Definition at line 162 of file time_model.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), operation::xload(), and operation::xwrite().
max_delay
std::map<unsigned int, float> time_model::max_delay [protected]
Definition at line 97 of file time_model.hpp.
Referenced by get_max_delay(), has_max_delay(), and set_max_delay().
Param
const ParameterConstRef time_model::Param [protected]
class containing all the parameters
Definition at line 92 of file time_model.hpp.
pin_to_pin_delay
std::map<std::string, std::map<std::string, double> > time_model::pin_to_pin_delay
map representing the pin-to-pin delay
Definition at line 81 of file time_model.hpp.
Referenced by operation::get_pin_to_pin_delay(), and operation::xload().
stage_period
double time_model::stage_period [protected]
critical timing execution path, in term of ns, of a potentially pipelined operation.
Definition at line 108 of file time_model.hpp.
Referenced by get_stage_period(), and set_stage_period().
stage_period_DEFAULT
const double time_model::stage_period_DEFAULT = 0 [static]
zero means that the operation last in ceil(execution_time/clock_period)
Definition at line 164 of file time_model.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), operation::xload(), and operation::xwrite().
statistical_delay
boost::math::normal time_model::statistical_delay
statistical delay for this type of operation on a given functional unit.
Definition at line 78 of file time_model.hpp.
synthesis_dependent
bool time_model::synthesis_dependent [protected]
flag to check if the number of cycles are dependent on the synthesis or not
Definition at line 105 of file time_model.hpp.
Referenced by get_synthesis_dependent(), and set_synthesis_dependent().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/time_model.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/time_model.cpp