FixCharacterization Class Reference
Step which fixes characterization.
#include <fix_characterization.hpp>
Public Member Functions
FixCharacterization (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~FixCharacterization () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
double assignment_execution_time
The execution time of the assignment.
double connection_time
The estimated execution time of connection.
TimeStamp assignment_characterization_timestamp
The timestamp of the assignment.
Additional Inherited Members
Detailed Description
Step which fixes characterization.
Definition at line 57 of file fix_characterization.hpp.
Constructor & Destructor Documentation
FixCharacterization()
FixCharacterization::FixCharacterization (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
TM is the technology manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include STD include STL includes technology include technology/physical_library includes technology/physical_library/models include technology/target_device include
Definition at line 71 of file fix_characterization.cpp.
References DesignFlowStep::debug_level, FIX_CHARACTERIZATION, GET_CLASS, DesignFlowStep::parameters, and ~FixCharacterization().
 FixCharacterization()
FixCharacterization::~FixCharacterization () [override], [default]
Destructor.
Referenced by FixCharacterization().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > FixCharacterization::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 354 of file fix_characterization.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_DEFAULT_TECHNOLOGY, LOAD_DEVICE_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status FixCharacterization::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
assignment
shift ops
vectorize shift ops
conversion
bitwise ops
vectorize bitwise ops
cond expr ops
vectorize cond expr ops
Second iteration of fixing
64 bits plus/minus
Implements DesignFlowStep.
Definition at line 88 of file fix_characterization.cpp.
References assignment_characterization_timestamp, assignment_execution_time, connection_time, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, technology_manager::get_fu(), technology_manager::get_library(), library_manager::get_library_fu(), technology_manager::get_library_list(), technology_manager::get_library_manager(), INDENT_DBG_MEX, SplitString(), STR, SUCCESS, THROW_ASSERT, and TechnologyFlowStep::TM.
Initialize()
void FixCharacterization::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 79 of file fix_characterization.cpp.
References assignment_characterization_timestamp, assignment_execution_time, technology_manager::CGetSetupHoldTime(), technology_manager::CGetSetupHoldTimeStamp(), connection_time, DesignFlowStep::parameters, and TechnologyFlowStep::TM.
Field Documentation
assignment_characterization_timestamp
TimeStamp FixCharacterization::assignment_characterization_timestamp [protected]
The timestamp of the assignment.
Definition at line 67 of file fix_characterization.hpp.
Referenced by Exec(), and Initialize().
assignment_execution_time
double FixCharacterization::assignment_execution_time [protected]
The execution time of the assignment.
Definition at line 61 of file fix_characterization.hpp.
Referenced by Exec(), and Initialize().
connection_time
double FixCharacterization::connection_time [protected]
The estimated execution time of connection.
Definition at line 64 of file fix_characterization.hpp.
Referenced by Exec(), and Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/fix_characterization.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/fix_characterization.cpp