tree_helper Class Reference
This class collects some utility functions used to extract information from tree-based data structures.
#include <tree_helper.hpp>
Public Member Functions
tree_helper ()
Constructor.
~tree_helper ()
Destructor.
Static Public Member Functions
static unsigned int size (const tree_managerConstRef tm, const unsigned int index)
Return the size of a tree object.
static unsigned int Size (const tree_nodeConstRef tn)
Return the size of a tree object.
static std::string name_type (const tree_managerConstRef tm, const unsigned int index)
Return the type name of a signal or a port.
static std::string name_tmpl (const tree_managerConstRef tm, const unsigned int index)
Return the name of template without parameters.
static std::string record_name (const tree_managerConstRef tm, unsigned int index)
Return the name of the class.
static std::string name_function (const tree_managerConstRef tm, const unsigned int index)
Return the name of the function.
static std::tuple< std::string, unsigned int, unsigned int > get_definition (const tree_managerConstRef tm, const unsigned int index, bool &is_system)
Return where a function or a type is defined.
static bool has_function_return (const tree_managerConstRef tm, const unsigned int index)
Return true if the function index returns a not void type, false otherwise.
static std::string getFunctionTypeString (tree_nodeRef FT)
Return a string describing the functino type.
static void get_used_variables (bool first_level_only, const tree_nodeRef t, CustomUnorderedSet< unsigned int > &list_of_variable)
Return the list of tree nodes associated with the variable used by the node t.
static bool look_for_binfo_inheritance (binfo *b, const std::string &bcs)
Look for inheritance of a class.
static tree_nodeRef find_obj_type_ref_function (const tree_nodeRef tn)
Given the tree_node of an obj_type_ref return the tree_node of the called function.
static const CustomUnorderedSet< unsigned int > GetTypesToBeDeclaredBefore (const tree_managerConstRef TM, const unsigned int index, const bool without_transformation)
Return the types to be declared before declaring index type.
static const CustomUnorderedSet< unsigned int > GetTypesToBeDeclaredAfter (const tree_managerConstRef TM, const unsigned int index, const bool without_transformation)
Return the types to be declared after declaring index type.
static unsigned int get_type_index (const tree_managerConstRef TM, const unsigned int index, long long int &vec_size, bool &is_a_pointer, bool &is_a_function)
Return the treenode index of the type of index.
static unsigned int get_type_index (const tree_managerConstRef TM, const unsigned int index)
Same as previous but with two parameters.
static tree_nodeRef GetFunctionReturnType (const tree_nodeRef function)
Return the return type of a function.
static unsigned int get_pointed_type (const tree_managerConstRef TM, const unsigned int index)
Return the tree_node index of the pointed type of a pointer object;.
static const tree_nodeConstRef CGetPointedType (const tree_nodeConstRef pointer)
Return the pointed type of a pointer object.
static unsigned int GetElements (const tree_managerConstRef TM, const unsigned int index)
Given an array or a vector return the element type.
static const tree_nodeConstRef CGetElements (const tree_nodeConstRef type)
Given an array or a vector return the element type.
static std::string get_type_name (const tree_managerConstRef TM, const unsigned int index)
Return name of the type.
static void get_parameter_types (const tree_managerConstRef TM, const unsigned int index, std::list< unsigned int > &params)
Return the tree node of parameter types.
static const std::vector< tree_nodeConstRef > CGetFieldTypes (const tree_nodeConstRef type)
Return the fields type of a variable of type struct.
static unsigned int get_field_idx (const tree_managerConstRef TM, const unsigned int index, unsigned int idx)
Return the idx element of the fields declared in an union or a record type.
static tree_nodeRef get_type_node (const tree_nodeRef &node, unsigned int &return_index=local_return_index)
FIXME to be removed after complete substitution with GetType.
static const tree_nodeConstRef CGetType (const tree_nodeConstRef node)
static bool is_system (const tree_managerConstRef TM, const unsigned int index)
Return true if variable or type is a system one.
static bool is_an_enum (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is an enumeral type.
static bool is_a_struct (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is a record.
static bool is_an_union (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is an union.
static bool is_a_complex (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is a complex.
static bool is_an_array (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is an array or it is equivalent to an array (record recursively having a single field ending into a single arrays)
static bool is_a_pointer (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is a pointer.
static bool is_a_function (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is a function_decl.
static bool is_a_vector (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode index is a vector.
static bool is_a_misaligned_vector (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode index is a a misaligned access to a vector data object.
static bool is_an_addr_expr (const tree_managerConstRef &TM, const unsigned int index)
Return if treenode index is an address expression.
static bool HasToBeDeclared (const tree_managerConstRef &TM, const unsigned int index)
Return true if the type has to be declared.
static bool is_const_type (const tree_managerConstRef &TM, const unsigned int index)
Return if the treenode is of const type.
static bool is_bool (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of bool type.
static bool is_a_void (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of void type.
static bool is_natural (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is a ssa_name greater or equal to zero.
static bool is_int (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of integer type.
static bool is_real (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of real type.
static bool is_unsigned (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of unsigned integer type.
static bool is_a_variable (const tree_managerConstRef &TM, const unsigned int index)
static bool is_static (const tree_managerConstRef &TM, const unsigned int index)
static bool is_extern (const tree_managerConstRef &TM, const unsigned int index)
static bool is_function_type (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of type function type.
static bool is_function_pointer_type (const tree_managerConstRef &TM, const unsigned int index)
Return true if the treenode is of type function pointer type.
static unsigned int get_base_index (const tree_managerConstRef &TM, const unsigned int index)
Retrun the base address of a memory access.
static bool is_fully_resolved (const tree_managerConstRef &TM, const unsigned int index, CustomOrderedSet< unsigned int > &res_set)
static std::string return_qualifier_prefix (const TreeVocabularyTokenTypes_TokenEnum quals)
return the prefix given a qualifier
static std::string return_C_qualifiers (const TreeVocabularyTokenTypes_TokenEnum quals, bool real_const)
return the qualifiers in C format
static bool is_ssa_name (const tree_managerConstRef &TM, const unsigned int index)
Return true in case index is a ssa_name.
static bool is_volatile (const tree_managerConstRef &TM, const unsigned int index)
return true in case the index corresponds to a volatile variable
static bool is_parameter (const tree_managerConstRef &TM, const unsigned int index)
return true in case the index corresponds to a parameter in ssa form or not
static bool is_virtual (const tree_managerConstRef &TM, const unsigned int index)
return true in case the ssa_name is virtual
static long long get_integer_cst_value (const integer_cst *ic)
Convert a integer_cst in a long long value.
static unsigned int get_array_var (const tree_managerConstRef &TM, const unsigned int index, bool is_written, bool &two_dim_p)
Return the tree node index of the array variable written or read.
static unsigned int get_array_data_bitsize (const tree_managerConstRef &TM, const unsigned int index)
Return the size (in bits) of the base element of the array.
static void get_array_dimensions (const tree_managerConstRef &TM, const unsigned int index, std::vector< unsigned int > &dims)
Return the dimension of the array.
static void get_array_dim_and_bitsize (const tree_managerConstRef &TM, const unsigned int index, std::vector< unsigned int > &dims, unsigned int &elts_bitsize)
Return the dimension of the array.
static unsigned int get_array_num_elements (const tree_managerConstRef &TM, const unsigned int index)
Return the total number of elements of the the base type in the array.
static void extract_array_indexes (const tree_managerConstRef &TM, const unsigned int index, std::vector< unsigned int > &indexes, std::vector< unsigned int > &size_indexes, unsigned int &base_object)
Return the indexes of the array_ref.
static bool is_concat_bit_ior_expr (const tree_managerConstRef &TM, const unsigned int index)
check if a given tree node is a concatenation operation
static bool is_simple_pointer_plus_test (const tree_managerConstRef &TM, const unsigned int index)
check if a given tree node is a simple pointer plus expression
static bool is_constant (const tree_managerConstRef &TM, const unsigned int index)
Return if a tree node is a constant object.
static std::string op_symbol (const tree_nodeRef &op)
Function return the symbol related with the operator op passed as parameter.
static std::string op_symbol (const tree_node *op)
Function return the symbol related with the operator op passed as parameter.
static unsigned int GetUnqualified (const tree_managerConstRef &TM, unsigned int type)
Return the unqualified version of a type.
static unsigned int GetRealType (const tree_managerConstRef &TM, unsigned int index)
Return the real type.
static bool IsAligned (const tree_managerConstRef &TM, unsigned int type)
Return true if type has not default alignment.
static unsigned int get_var_alignment (const tree_managerConstRef &TM, unsigned int var)
Return the var alignment.
static std::string normalized_ID (const std::string &id)
Return the normalized the name of types and variables.
static void get_mangled_fname (const function_decl *fd, std::string &fname)
Return the mangled function name.
static std::string print_function_name (const tree_managerConstRef TM, const function_decl *fd)
Return the name of the function in a string.
static std::string print_type (const tree_managerConstRef &TM, unsigned int type, bool global=false, bool print_qualifiers=false, bool print_storage=false, unsigned int var=0, const var_pp_functorConstRef &vppf=var_pp_functorConstRef(), const std::string &prefix=``, const std::string &tail=``)
Print a type and its variable in case var is not zero.
static unsigned int get_formal_ith (const tree_managerConstRef &TM, unsigned int index_obj, unsigned int parm_index)
return the type of the ith formal parameter in case index_obj is a call_expr
static bool is_packed (const tree_managerConstRef &TreeM, unsigned int node_index)
static bool is_packed_access (const tree_managerConstRef &TreeM, unsigned int node_index)
Check if the access is on a packed data structure or not.
static void accessed_greatest_bitsize (const tree_managerConstRef &TreeM, const tree_nodeRef &type_node, unsigned int type_index, unsigned int &bitsize)
return the maximum bitsize associated with the elements accessible through type_node
static void accessed_minimum_bitsize (const tree_managerConstRef &TreeM, const tree_nodeRef &type_node, unsigned int type_index, unsigned int &bitsize)
return the minimum bitsize associated with the elements accessible through type_node
static size_t AllocatedMemorySize (const tree_nodeConstRef &parameter)
Compute the memory (in bytes) to be allocated to store a parameter or a variable.
static size_t CountPointers (const tree_nodeConstRef &)
Computes how many pointers are included in a tree node.
static unsigned int get_multi_way_if_pos (const tree_managerConstRef &TM, unsigned int node_id, unsigned int cond)
return the position of con in the gimple_multi_way_if conditions
static void compute_ssa_uses_rec_ptr (const tree_nodeRef &tn, CustomOrderedSet< ssa_name *> &ssa_uses)
recursively compute the pointers to the ssa_name variables used in a statement
static TreeNodeMap< size_t > ComputeSsaUses (const tree_nodeRef &tn)
recursively compute the references to the ssa_name variables used in a statement
static bool is_a_nop_function_decl (function_decl *fd)
static void get_required_values (const tree_managerConstRef &TM, std::vector< std::tuple< unsigned int, unsigned int >> &required, const tree_nodeRef &tn, unsigned int index)
static bool LastStatement (const tree_nodeConstRef &statement)
Return true if statement must be the last of a basic block.
static size_t GetFunctionSize (const tree_managerConstRef &TM, const unsigned int function_index)
Return the number of statement + the number of phi in the function.
static std::string get_asm_string (const tree_managerConstRef &TM, const unsigned int node_index)
return the string associated with the gimple_asm
static bool IsStore (const tree_managerConstRef &TM, const tree_nodeConstRef &tn, const CustomOrderedSet< unsigned int > &fun_mem_data)
Return true if the tree node is a gimple_assign writing something which will be allocated in memory.
static bool IsLoad (const tree_managerConstRef &TM, const tree_nodeConstRef &tn, const CustomOrderedSet< unsigned int > &fun_mem_data)
Return true if the tree node is a gimple_assign reading something which will be allocated in memory.
static bool IsLut (const tree_managerConstRef &TM, const tree_nodeConstRef &tn)
Return true in case the right operation is a lut_expr.
 SystemC related functions
static bool is_module (const tree_managerConstRef &TM, unsigned int index)
This function test if a given index is a SystemC module.
static bool is_channel (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC channel.
static bool is_builtin_channel (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC builtin channel.
static bool is_signal (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC sc_signal.
static bool is_port (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC port.
static bool is_in_port (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC input port.
static bool is_out_port (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC output port.
static bool is_inout_port (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC in-output port.
static bool is_event (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index is a SystemC event.
static bool is_clock (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index as parm is a SystemC sc_clock.
static bool is_SC_BIND_PROXY_NIL (const tree_managerConstRef &TM, const unsigned int index)
This function test if a given index as parm is a SC_BIND_PROXY_NIL.
Static Public Attributes
static int debug_level = 0
debug level (set by Parameter)
static unsigned int local_return_index = 0
Return the treenode of the type of node.
Static Private Member Functions
static const CustomUnorderedSet< unsigned int > RecursiveGetTypesToBeDeclared (const tree_managerConstRef TM, const unsigned int index, const bool recursive, const bool without_transformation, const bool before)
Return the type to be declared before declaring index type.
static void ComputeSsaUses (const tree_nodeRef, TreeNodeMap< size_t > &uses)
recursively compute the references to the ssa_name variables used in a statement
Static Private Attributes
static const std::set< std::string > SC_tmpl_class = {`sc_signal`, `sc_in`, `sc_out`, `sc_inout`, `sc_port`, `sc_export`}
store the set of SystemC class for which the type correspond to the template parameter
static const std::set< std::string > SC_builtin_scalar_type
store the set of SystemC class for which the template parameter correspond to the bit size of the type
static const std::set< std::string > TLM_SC_builtin_scalar_type
store the set of TLM SystemC class for which the size corresponds to the sum of the size of template parameters
Detailed Description
This class collects some utility functions used to extract information from tree-based data structures.
Definition at line 85 of file tree_helper.hpp.
Constructor & Destructor Documentation
tree_helper()
tree_helper::tree_helper () [default]
Constructor.
 tree_helper()
tree_helper::~tree_helper () [default]
Destructor.
Member Function Documentation
accessed_greatest_bitsize()
void tree_helper::accessed_greatest_bitsize (const tree_managerConstRef & TreeM, const tree_nodeRef & type_node, unsigned int type_index, unsigned int & bitsize) [static]
return the maximum bitsize associated with the elements accessible through type_node
it is composed by two identical parts
Definition at line 6814 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, get_type_node(), tree_node::index, max(), size(), STR, THROW_ERROR, test_panda::type, and type_node.
Referenced by memory_allocation::finalize_memory_allocation(), AllocationInformation::get_correction_time(), mem_dominator_allocation::InternalExec(), fu_binding::specialise_fu(), and HLSCWriter::WriteSimulatorInitMemory().
accessed_minimum_bitsize()
void tree_helper::accessed_minimum_bitsize (const tree_managerConstRef & TreeM, const tree_nodeRef & type_node, unsigned int type_index, unsigned int & bitsize) [static]
return the minimum bitsize associated with the elements accessible through type_node
it is composed by two identical parts
Definition at line 6954 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, get_type_node(), min, size(), THROW_ERROR, test_panda::type, and type_node.
Referenced by mem_dominator_allocation::InternalExec().
AllocatedMemorySize()
size_t tree_helper::AllocatedMemorySize (const tree_nodeConstRef & parameter) [static]
Compute the memory (in bytes) to be allocated to store a parameter or a variable.
Parameters
parameter is the actual parameter
Note that this part can not be transfromed in recursion because size of array ref corresponds to the size of the element itself
This call check if we can perform deep copy of the single element
Round to upper multiple word size
This calls check if we can perform deep copy of the single element
Round to upper multiple word size
Round to upper multiple word size
Definition at line 7090 of file tree_helper.cpp.
References CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, CGetType(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, PointToInformation::default_key, GET_NODE, get_type_node(), INDENT_DBG_MEX, Size(), THROW_ERROR, THROW_UNREACHABLE, and test_panda::type.
CGetElements()
const tree_nodeConstRef tree_helper::CGetElements (const tree_nodeConstRef type) [static]
Given an array or a vector return the element type.
Parameters
type is the type of the array
Returns
the type of the element
Definition at line 2138 of file tree_helper.cpp.
References GET_CONST_NODE, THROW_UNREACHABLE, and test_panda::type.
Referenced by GetElements(), MemoryInitializationWriterBase::GoDown(), and compute_implicit_calls::InternalExec().
CGetFieldTypes()
const std::vector< tree_nodeConstRef > tree_helper::CGetFieldTypes (const tree_nodeConstRef type) [static]
Return the fields type of a variable of type struct.
Parameters
type is the struct type
Definition at line 2236 of file tree_helper.cpp.
References CGetType(), GET_CONST_NODE, THROW_UNREACHABLE, and test_panda::type.
Referenced by MemoryInitializationWriterBase::GoDown(), MemoryInitializationWriterBase::GoNext(), MemoryInitializationWriterBase::GoUp(), RecursiveGetTypesToBeDeclared(), and HLSCWriter::WriteSimulatorInitMemory().
CGetPointedType()
const tree_nodeConstRef tree_helper::CGetPointedType (const tree_nodeConstRef pointer) [static]
Return the pointed type of a pointer object.
Parameters
pointer is the pointer object
Definition at line 2055 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_NODE, and THROW_UNREACHABLE.
Referenced by CreateAddressTranslation::ComputeAddress(), MemoryInitializationWriterBase::GoDown(), and HLSCWriter::WriteExpectedResults().
CGetType()
const tree_nodeConstRef tree_helper::CGetType (const tree_nodeConstRef node) [static]
Definition at line 2444 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_NODE, NODE_NOT_YET_SUPPORTED_EC, THROW_ASSERT, and THROW_ERROR_CODE.
Referenced by AllocatedMemorySize(), Bit_Value::backward(), Bit_Value::backward_transfer(), CGetFieldTypes(), Vectorize::ClassifyTreeNode(), CreateAddressTranslation::ComputeAddress(), CountPointers(), tree_manipulation::create_gimple_call(), short_circuit_taf::create_gimple_cond(), interface_infer::create_Write_function(), tree_manipulation::CreateAddrExpr(), tree_manipulation::CreateCallExpr(), BitValueIPA::Exec(), CreateAddressTranslation::Exec(), Vectorize::FixPhis(), Bit_Value::forward(), Bit_Value::forward_transfer(), CSE::hash_check(), BitLatticeManipulator::inf(), Bit_Value::initialize(), parm_decl_taken_address_fix::InternalExec(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), SerializeMutualExclusions::InternalExec(), FunctionCallTypeCleanup::InternalExec(), compute_implicit_calls::InternalExec(), rebuild_initialization::InternalExec(), hls_div_cg_ext::InternalExec(), CSE::InternalExec(), IR_lowering::InternalExec(), IsLoad(), IsStore(), Bit_Value::manage_forward_binary_operands(), type_casting::operator()(), Bit_Value_opt::optimize(), BehavioralHelper::print_node(), VarComputation::RecursivelyAnalyze(), BitLatticeManipulator::sup(), and Vectorize::Transform().
compute_ssa_uses_rec_ptr()
void tree_helper::compute_ssa_uses_rec_ptr (const tree_nodeRef & tn, CustomOrderedSet< ssa_name *> & ssa_uses) [static]
recursively compute the pointers to the ssa_name variables used in a statement
Parameters
tn is the statement
ssa_uses is the collection of ssa_name tn uses
var decl performs an assignment when init is not null
step and offset are constants
step and offset are constants
Definition at line 7661 of file tree_helper.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_PARANOIC, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, THROW_UNREACHABLE, and tree_node::ToString().
Referenced by Schedule::CanBeMoved(), simple_code_motion::CheckMovable(), Schedule::ComputeCriticalPath(), simple_code_motion::InternalExec(), and Schedule::UpdateTime().
ComputeSsaUses() [1/2]
void tree_helper::ComputeSsaUses (const tree_nodeRef tn, TreeNodeMap< size_t > & uses) [static], [private]
recursively compute the references to the ssa_name variables used in a statement
Parameters
tn is the statement
uses is where the uses will be stored
var decl performs an assignment when init is not null
step and offset are constants
step and offset are constants
Definition at line 8000 of file tree_helper.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_PARANOIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by bloc::AddPhi(), tree_manager::check_ssa_uses(), interface_infer::Computepar2ssa(), ComputeSsaUses(), BitValueIPA::Exec(), AllocationInformation::GetConnectionTime(), NI_SSA_liveness::InternalExec(), MultipleEntryIfReduction::InternalExec(), VcdSignalSelection::PropagateAddrParamToSsa(), bloc::PushAfter(), bloc::PushBack(), bloc::PushBefore(), bloc::PushFront(), tree_manager::RecursiveReplaceTreeNode(), bloc::RemovePhi(), bloc::RemoveStmt(), and bloc::ReorderLUTs().
ComputeSsaUses() [2/2]
TreeNodeMap< size_t > tree_helper::ComputeSsaUses (const tree_nodeRef & tn) [static]
recursively compute the references to the ssa_name variables used in a statement
Parameters
tn is the statement
Returns
the used ssa
Definition at line 7993 of file tree_helper.cpp.
References ComputeSsaUses().
CountPointers()
size_t tree_helper::CountPointers (const tree_nodeConstRef & tn) [static]
Computes how many pointers are included in a tree node.
Parameters
tn is the tree ndoe to be considered
Returns
the number of pointers included in the tree node
Definition at line 7543 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, CGetType(), counter, GET_NODE, and THROW_UNREACHABLE.
extract_array_indexes()
void tree_helper::extract_array_indexes (const tree_managerConstRef & TM, const unsigned int index, std::vector< unsigned int > & indexes, std::vector< unsigned int > & size_indexes, unsigned int & base_object) [static]
Return the indexes of the array_ref.
Parameters
TM is the tree_manager
index is the array_ref object
indexes return the index of the array_ref
size_indexes return the size of each index
base_object is the base referenced object
Definition at line 5253 of file tree_helper.cpp.
References GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), STR, and THROW_ASSERT.
find_obj_type_ref_function()
tree_nodeRef tree_helper::find_obj_type_ref_function (const tree_nodeRef tn) [static]
Given the tree_node of an obj_type_ref return the tree_node of the called function.
Parameters
tn is the tree node of the obj_type_ref.
Returns
the tree_node of the called function
Definition at line 1389 of file tree_helper.cpp.
References GET_INDEX_NODE, GET_NODE, reference_type::refd, THROW_ASSERT, THROW_ERROR, test_panda::type, and decl_node::type.
Referenced by operations_cfg_computation::build_operation_recursive(), call_graph_computation::call_graph_computation_recursive(), get_required_values(), dead_code_elimination::InternalExec(), and BehavioralHelper::print_node().
get_array_data_bitsize()
unsigned int tree_helper::get_array_data_bitsize (const tree_managerConstRef & TM, const unsigned int index) [static]
Return the size (in bits) of the base element of the array.
Parameters
TM is the tree_manager
index is the array object
Definition at line 5114 of file tree_helper.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), get_type_index(), max(), size(), STR, THROW_ASSERT, and test_panda::type.
Referenced by TestbenchMemoryAllocation::AllocTestbenchMemory(), IR_lowering::array_ref_lowering(), mem_dominator_allocation::InternalExec(), TestbenchGenerationBaseStep::print_var_init(), HLSCWriter::WriteExpectedResults(), and HLSCWriter::WriteSimulatorInitMemory().
get_array_dim_and_bitsize()
void tree_helper::get_array_dim_and_bitsize (const tree_managerConstRef & TM, const unsigned int index, std::vector< unsigned int > & dims, unsigned int & elts_bitsize) [static]
Return the dimension of the array.
Parameters
TM is the tree_manager
index is the array object
dims return for each dimension the number of elements
elts_bitsize return the base type bitsize
Definition at line 5147 of file tree_helper.cpp.
References GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), get_type_index(), max(), size(), STR, THROW_ASSERT, and test_panda::type.
Referenced by AllocationInformation::can_be_asynchronous_ram(), BitLatticeManipulator::constructor_bitstring(), fu_binding::fill_array_ref_memory(), rebuild_initialization2::look_for_ROMs(), and fu_binding::write_init().
get_array_dimensions()
void tree_helper::get_array_dimensions (const tree_managerConstRef & TM, const unsigned int index, std::vector< unsigned int > & dims) [static]
Return the dimension of the array.
Parameters
TM is the tree_manager
index is the array object
dims return for each dimension the number of elements
Definition at line 5201 of file tree_helper.cpp.
References GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), STR, THROW_ASSERT, and test_panda::type.
Referenced by IR_lowering::array_ref_lowering(), mux_connection_binding::dynamic_multidimensional_array_handler(), get_array_num_elements(), AllocationInformation::get_correction_time(), and MemoryInitializationWriterBase::GoUp().
get_array_num_elements()
unsigned int tree_helper::get_array_num_elements (const tree_managerConstRef & TM, const unsigned int index) [static]
Return the total number of elements of the the base type in the array.
Parameters
TM is the tree_manager
index is the array object
Definition at line 5238 of file tree_helper.cpp.
References get_array_dimensions().
Referenced by TestbenchGenerationBaseStep::print_var_init(), HLSCWriter::WriteExpectedResults(), and HLSCWriter::WriteSimulatorInitMemory().
get_array_var()
unsigned int tree_helper::get_array_var (const tree_managerConstRef & TM, const unsigned int index, bool is_written, bool & two_dim_p) [static]
Return the tree node index of the array variable written or read.
Parameters
TM is the tree_manager
index is the index of the gimple_assign
is_written is true when the array is written false otherwise
two_dim_p becomes true when the array is two dimensional
Definition at line 4623 of file tree_helper.cpp.
References target_mem_ref::base, target_mem_ref461::base, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), target_mem_ref::symbol, THROW_ASSERT, and THROW_ERROR.
get_asm_string()
std::string tree_helper::get_asm_string (const tree_managerConstRef & TM, const unsigned int node_index) [static]
return the string associated with the gimple_asm
Parameters
TM is the tree manager
node_index is the gimple_asm node id
Returns
the string associated with gimple_asm
Definition at line 8923 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and THROW_ASSERT.
Referenced by BehavioralHelper::get_asm_string().
get_base_index()
unsigned int tree_helper::get_base_index (const tree_managerConstRef & TM, const unsigned int index) [static]
Retrun the base address of a memory access.
Parameters
TM is the tree manager
int is the index of the access
Definition at line 3658 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, check_for_simple_pointer_arithmetic(), GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), index, tree_node::index, NODE_NOT_YET_SUPPORTED_EC, STR, THROW_ASSERT, THROW_ERROR, and THROW_ERROR_CODE.
Referenced by determine_memory_accesses::analyze_node(), vcd_utility::detect_address_mismatch(), mux_connection_binding::determine_connection(), VcdSignalSelection::Exec(), memory_allocation::finalize_memory_allocation(), Bit_Value::initialize(), mem_dominator_allocation::InternalExec(), compute_implicit_calls::InternalExec(), IR_lowering::InternalExec(), allocation::InternalExec(), Bit_Value::pointer_resizing(), and fu_binding::specialise_fu().
get_definition()
std::tuple< std::string, unsigned int, unsigned int > tree_helper::get_definition (const tree_managerConstRef tm, const unsigned int index, bool & is_system) [static]
Return where a function or a type is defined.
Parameters
tm is the tree manager
index is the index
is_system stores if function or type has been already recognized as a system one
Definition at line 976 of file tree_helper.cpp.
References GET_NODE, and tree_manager::get_tree_node_const().
Referenced by BehavioralHelper::get_definition().
get_field_idx()
unsigned int tree_helper::get_field_idx (const tree_managerConstRef TM, const unsigned int index, unsigned int idx) [static]
Return the idx element of the fields declared in an union or a record type.
Parameters
TM is the tree_manager
ind is the index of the record/union type
idx is the index of the field decl
Definition at line 2270 of file tree_helper.cpp.
References GET_INDEX_NODE, tree_manager::get_tree_node_const(), local_return_index, and THROW_ASSERT.
get_formal_ith()
unsigned int tree_helper::get_formal_ith (const tree_managerConstRef & TM, unsigned int index_obj, unsigned int parm_index) [static]
return the type of the ith formal parameter in case index_obj is a call_expr
parameters are not available through function_type but only through function_decl
parameters are not available through function_type but only through function_decl
Definition at line 6327 of file tree_helper.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), get_type_index(), get_type_node(), THROW_ASSERT, and THROW_ERROR.
Referenced by mux_connection_binding::create_connections(), AllocationInformation::GetNodeTypePrec(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), FunctionCallTypeCleanup::InternalExec(), and hls_div_cg_ext::InternalExec().
get_integer_cst_value()
long long tree_helper::get_integer_cst_value (const integer_cst * ic) [static]
Convert a integer_cst in a long long value.
Parameters
ic is the integer costant data.
If high is null or if high is a sign extension or low is enough to express an int (64 bit system)
Definition at line 4607 of file tree_helper.cpp.
References debug_level, DEBUG_LEVEL_PARANOIC, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, result, STR, THROW_ASSERT, test_panda::type, cst_node::type, and integer_cst::value.
Referenced by simple_code_motion::CheckMovable(), Vectorize::ClassifyTreeNode(), CreateAddressTranslation::ComputeAddress(), mux_connection_binding::create_connections(), tree_manipulation::CreateUnsigned(), mux_connection_binding::determine_connection(), IR_lowering::division_by_a_constant(), ipa_point_to_analysis::Exec(), IR_lowering::expand_MC(), IR_lowering::expand_target_mem_ref(), extract_array_indexes(), rebuild_initialization2::extract_var_decl(), rebuild_initialization2::extract_var_decl_ppe(), get_array_dim_and_bitsize(), get_array_dimensions(), get_base_index(), HLS_manager::get_constant_string(), fsm_controller::get_guard_value(), get_required_values(), GimpleWriter::GimpleWriter(), mem_dominator_allocation::InternalExec(), SwitchFix::InternalExec(), LoopsAnalysisBambu::InternalExec(), rebuild_initialization::InternalExec(), simple_code_motion::InternalExec(), IR_lowering::InternalExec(), is_natural(), mux_connection_binding::isZeroObj(), rebuild_initialization2::look_for_ROMs(), name_type(), field_decl::offset(), op_symbol(), Bit_Value_opt::optimize(), BehavioralHelper::print_constant(), BehavioralHelper::print_node(), print_type(), BehavioralHelper::print_type_declaration(), BehavioralHelper::PrintVariable(), Size(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), Vectorize::Transform(), fu_binding::write_init(), and HLSCWriter::WriteParamInMemory().
get_mangled_fname()
void tree_helper::get_mangled_fname (const function_decl * fd, std::string & fname) [static]
Return the mangled function name.
Parameters
fd is the function decl
fname is the returned function name
Definition at line 869 of file tree_helper.cpp.
References function_decl::builtin_flag, GET_NODE, decl_node::mngl, decl_node::name, normalized_ID(), THROW_ASSERT, and THROW_ERROR.
Referenced by minimal_interface::build_wrapper(), interface_infer::classifyArgRecurse(), interface_infer::create_Read_function(), interface_infer::create_Write_function(), parametric_list_based::exec(), memory_allocation::finalize_memory_allocation(), HDLVarDeclFix::InternalExec(), interface_infer::InternalExec(), moduleGenerator::specialize_fu(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteHeader(), HLSCWriter::WriteParamDecl(), and HLSCWriter::WriteParamInitialization().
get_multi_way_if_pos()
unsigned int tree_helper::get_multi_way_if_pos (const tree_managerConstRef & TM, unsigned int node_id, unsigned int cond) [static]
return the position of con in the gimple_multi_way_if conditions
Parameters
TM is the tree manager
node_id is the node id of the gimple_multi_way_if node
cond is the condition index
Returns
the position
Definition at line 7644 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and THROW_ERROR.
Referenced by fsm_controller::get_guard_value().
get_parameter_types()
void tree_helper::get_parameter_types (const tree_managerConstRef TM, const unsigned int index, std::list< unsigned int > & params) [static]
Return the tree node of parameter types.
Parameters
TM is the tree_manager
ind is the index of the function type
params is where parameter types are stored
Definition at line 2185 of file tree_helper.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by RecursiveGetTypesToBeDeclared().
get_pointed_type()
unsigned int tree_helper::get_pointed_type (const tree_managerConstRef TM, const unsigned int index) [static]
Return the tree_node index of the pointed type of a pointer object;.
Parameters
TM is the tree_manager
index is the index of the pointer objectFIXME: to be remove after substitution with GetPointedType/CGetPointedType
Definition at line 1965 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_manager::get_tree_node_const(), pointer_type::ptd, reference_type::refd, function_type::retn, and THROW_ASSERT.
Referenced by minimal_interface::build_wrapper(), BehavioralHelper::get_pointed_type(), ComputeReservedMemory::GetReservedBytes(), interface_infer::InternalExec(), MemoryInitializationWriter::Process(), RecursiveGetTypesToBeDeclared(), structural_type_descriptor::structural_type_descriptor(), MinimalInterfaceTestbench::write_input_signal_declaration(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), and HLSCWriter::WriteParamInitialization().
get_required_values()
void tree_helper::get_required_values (const tree_managerConstRef & TM, std::vector< std::tuple< unsigned int, unsigned int >> & required, const tree_nodeRef & tn, unsigned int index) [static]
this has not to be synthesized
bpos has an offset in bits
Definition at line 8415 of file tree_helper.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, find_obj_type_ref_function(), GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, is_a_nop_function_decl(), is_a_vector(), STR, THROW_ASSERT, THROW_ERROR, and THROW_UNREACHABLE.
Referenced by Bit_Value::forward(), HLS_manager::get_required_values(), and Bit_Value::initialize().
get_type_index() [1/2]
unsigned int tree_helper::get_type_index (const tree_managerConstRef TM, const unsigned int index, long long int & vec_size, bool & is_a_pointer, bool & is_a_function) [static]
Return the treenode index of the type of index.
Parameters
TM is the tree_manager
index is the treenode index
vec_size in case the treenode is a vector return its size
is_a_pointer in case the treenode is a pointer return true
is_a_function in case the treenode is a function_decl return true
Definition at line 1806 of file tree_helper.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), get_type_node(), index, and THROW_ASSERT.
Referenced by fu_binding::add_to_SM(), TestbenchMemoryAllocation::AllocTestbenchMemory(), CBackend::AnalyzeInclude(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), Bit_Value::backward_transfer(), minimal_interface::build_wrapper(), HWCallInjection::buildBuiltinCall(), memory::compute_next_base_address(), CWriter::compute_phi_nodes(), mux_connection_binding::create_connections(), short_circuit_taf::create_gimple_cond(), CWriter::DeclareVariable(), vcd_utility::detect_fixed_address_mismatch(), VcdSignalSelection::DetectInvalidReturns(), mux_connection_binding::determine_connection(), IR_lowering::division_by_a_constant(), TestbenchValuesXMLGeneration::Exec(), VcdSignalSelection::Exec(), IR_lowering::expand_mult_const(), IR_lowering::expand_target_mem_ref(), memory_allocation::finalize_memory_allocation(), get_array_data_bitsize(), get_array_dim_and_bitsize(), HLS_manager::get_constant_string(), AllocationInformation::get_correction_time(), get_formal_ith(), BehavioralHelper::get_type(), get_type_index(), AllocationInformation::GetCondExprTimeLatency(), AllocationInformation::GetNodeTypePrec(), ComputeReservedMemory::GetReservedBytes(), PhiOpt::IdentifyPattern(), BitLatticeManipulator::inf(), VcdSignalSelection::InitialSsaIsAddress(), mem_dominator_allocation::InternalExec(), compute_implicit_calls::InternalExec(), BuildVirtualPhi::InternalExec(), hls_div_cg_ext::InternalExec(), dead_code_elimination::InternalExec(), CondExprRestructuring::InternalExec(), commutative_expr_restructuring::InternalExec(), MultipleEntryIfReduction::InternalExec(), IR_lowering::InternalExec(), allocation::InternalExec(), is_a_function(), is_a_pointer(), dead_code_elimination::kill_uses(), MemoryInitializationWriterBase::MemoryInitializationWriterBase(), mux_connection_binding::object_bitsize(), Bit_Value_opt::optimize(), vcd_utility::print_discrepancy(), BehavioralHelper::print_node(), print_type(), VcdSignalSelection::SelectInitialAddrParam(), VcdSignalSelection::SelectInitialSsa(), fu_binding::specialise_fu(), BitLatticeManipulator::sup(), virtual_phi_nodes_split::virtual_split_phi(), fu_binding::write_init(), MinimalInterfaceTestbench::write_input_signal_declaration(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteParamInMemory(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and HLSCWriter::WriteSimulatorInitMemory().
get_type_index() [2/2]
unsigned int tree_helper::get_type_index (const tree_managerConstRef TM, const unsigned int index) [static]
Same as previous but with two parameters.
Parameters
TM is the tree_manager
index is the treenode
Definition at line 2228 of file tree_helper.cpp.
References get_type_index(), is_a_function(), and is_a_pointer().
get_type_name()
std::string tree_helper::get_type_name (const tree_managerConstRef TM, const unsigned int index) [static]
Return name of the type.
Parameters
TM is the tree manager
index is the index of the type
Returns
the name of the type
Definition at line 2154 of file tree_helper.cpp.
References GET_NODE, tree_manager::get_tree_node_const(), get_type_node(), STR, THROW_ASSERT, and test_panda::type.
Referenced by tree_manager::check_for_decl(), and tree_manager::check_for_type().
get_type_node()
tree_nodeRef tree_helper::get_type_node (const tree_nodeRef & node, unsigned int & return_index = local_return_index) [static]
FIXME to be removed after complete substitution with GetType.
Definition at line 2291 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, NODE_NOT_YET_SUPPORTED_EC, gimple_while::op0, STR, THROW_ASSERT, and THROW_ERROR_CODE.
Referenced by accessed_greatest_bitsize(), accessed_minimum_bitsize(), AllocatedMemorySize(), determine_memory_accesses::analyze_node(), IR_lowering::array_ref_lowering(), operations_cfg_computation::build_operation_recursive(), AllocationInformation::can_be_asynchronous_ram(), CSE::check_loads(), simple_code_motion::CheckMovable(), mux_connection_binding::create_connections(), tree_manipulation::create_phi_node(), mux_connection_binding::determine_connection(), mux_connection_binding::dynamic_multidimensional_array_handler(), fu_binding::fill_array_ref_memory(), memory_allocation::finalize_memory_allocation(), get_formal_ith(), get_parameter_types(), get_type_index(), get_type_name(), GimpleWriter::GimpleWriter(), CSE::hash_check(), compute_implicit_calls::InternalExec(), fanout_opt::InternalExec(), IR_lowering::InternalExec(), allocation::InternalExec(), is_a_complex(), is_a_misaligned_vector(), is_a_struct(), is_a_vector(), is_a_void(), is_an_array(), is_an_enum(), is_an_union(), is_bool(), is_const_type(), is_function_pointer_type(), is_function_type(), is_int(), is_real(), is_unsigned(), is_volatile(), commutative_expr_restructuring::IsCommExprGimple(), IsLoad(), IsStore(), rebuild_initialization2::look_for_ROMs(), BehavioralHelper::print_node(), TestbenchGenerationBaseStep::print_var_init(), hls_div_cg_ext::recursive_examinate(), soft_float_cg_ext::RecursiveExaminate(), VcdSignalSelection::SingleStepPropagateAddrSsa(), moduleGenerator::specialize_fu(), extract_patterns::ternary_plus_expr_extraction(), and fu_binding::write_init().
get_used_variables()
void tree_helper::get_used_variables (bool first_level_only, const tree_nodeRef t, CustomUnorderedSet< unsigned int > & list_of_variable) [static]
Return the list of tree nodes associated with the variable used by the node t.
Parameters
first_level_only tells if we are performing inlining
t is a tree node (usually a function declaration).
list_of_variable list of used variables.
Definition at line 1037 of file tree_helper.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, gimple_while::op0, gimple_for::op1, gimple_for::op2, sl, THROW_ASSERT, and THROW_ERROR.
Referenced by BehavioralHelper::GetInit().
get_var_alignment()
unsigned int tree_helper::get_var_alignment (const tree_managerConstRef & TM, unsigned int var) [static]
Return the var alignment.
Parameters
TM is the tree manager
index is the index of the variable
Returns
the variable alignment
Definition at line 5301 of file tree_helper.cpp.
References tree_manager::get_tree_node_const().
Referenced by memory::add_external_variable(), and memory::add_internal_variable().
GetElements()
unsigned int tree_helper::GetElements (const tree_managerConstRef TM, const unsigned int index) [static]
Given an array or a vector return the element type.
Parameters
TM is the tree_manager
index is the type of the array
Returns
the type of the element
Definition at line 2133 of file tree_helper.cpp.
References CGetElements(), and tree_manager::get_tree_node_const().
Referenced by fu_binding::fill_array_ref_memory(), BehavioralHelper::GetElements(), AllocationInformation::GetNodeTypePrec(), rebuild_initialization::InternalExec(), IR_lowering::InternalExec(), allocation::InternalExec(), is_unsigned(), VcdSignalSelection::IsAddressType(), rebuild_initialization2::look_for_ROMs(), BehavioralHelper::print_node(), RecursiveGetTypesToBeDeclared(), fu_binding::specialise_fu(), structural_type_descriptor::structural_type_descriptor(), and DiscrepancyAnalysisCWriter::writePostInstructionInfo().
GetFunctionReturnType()
tree_nodeRef tree_helper::GetFunctionReturnType (const tree_nodeRef function) [static]
Return the return type of a function.
Parameters
function is the function to be considered
Returns
the tree node of the return type
Definition at line 1852 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, tree_node::get_kind(), GET_NODE, function_type::retn, THROW_ASSERT, THROW_UNREACHABLE, and decl_node::type.
Referenced by BitValueIPA::Exec(), BehavioralHelper::GetFunctionReturnType(), Bit_Value::initialize(), FunctionCallTypeCleanup::InternalExec(), BehavioralHelper::print_node(), and RecursiveGetTypesToBeDeclared().
GetFunctionSize()
size_t tree_helper::GetFunctionSize (const tree_managerConstRef & TM, const unsigned int function_index) [static]
Return the number of statement + the number of phi in the function.
Parameters
TM is the tree manager
function_index is the index of the function to be analyzed
Returns
the size of a function
Definition at line 8907 of file tree_helper.cpp.
References GET_NODE, tree_manager::get_tree_node_const(), sl, and THROW_ASSERT.
getFunctionTypeString()
static std::string tree_helper::getFunctionTypeString (tree_nodeRef FT) [static]
Return a string describing the functino type.
Parameters
Tree node of the function type
GetRealType()
unsigned int tree_helper::GetRealType (const tree_managerConstRef & TM, unsigned int index) [static]
Return the real type.
Parameters
TM is the tree manager
index is the index of the type
Returns
the real type
Definition at line 1786 of file tree_helper.cpp.
References GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), index, type_node::name, and type_node::unql.
Referenced by CWriter::DeclareType(), BehavioralHelper::print_node(), print_type(), and BehavioralHelper::print_type_declaration().
GetTypesToBeDeclaredAfter()
const CustomUnorderedSet< unsigned int > tree_helper::GetTypesToBeDeclaredAfter (const tree_managerConstRef TM, const unsigned int index, const bool without_transformation) [static]
Return the types to be declared after declaring index type.
Parameters
TM is the tree_manager
index is the starting type
without_transformation specifies if we are not restructuring the code
Returns
the types to be declared
Definition at line 1492 of file tree_helper.cpp.
References RecursiveGetTypesToBeDeclared().
Referenced by CBackend::AnalyzeInclude(), and CWriter::DeclareType().
GetTypesToBeDeclaredBefore()
const CustomUnorderedSet< unsigned int > tree_helper::GetTypesToBeDeclaredBefore (const tree_managerConstRef TM, const unsigned int index, const bool without_transformation) [static]
Return the types to be declared before declaring index type.
Parameters
TM is the tree_manager
index is the starting type
without_transformation specifies if we are not restructuring the code
Returns
the types to be declared
Definition at line 1487 of file tree_helper.cpp.
References RecursiveGetTypesToBeDeclared().
Referenced by CBackend::AnalyzeInclude(), and CWriter::DeclareType().
GetUnqualified()
unsigned int tree_helper::GetUnqualified (const tree_managerConstRef & TM, unsigned int type) [static]
Return the unqualified version of a type.
Parameters
TM is the tree_manager
type is the type
Returns
the unqualified version of the type if it exists, 0 otherwise
Definition at line 5283 of file tree_helper.cpp.
References GET_INDEX_NODE, and tree_manager::get_tree_node_const().
Referenced by BehavioralHelper::GetUnqualified().
has_function_return()
static bool tree_helper::has_function_return (const tree_managerConstRef tm, const unsigned int index) [static]
Return true if the function index returns a not void type, false otherwise.
Parameters
index is the treenode_index of the functions
HasToBeDeclared()
bool tree_helper::HasToBeDeclared (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the type has to be declared.
Parameters
TM is the tree_manager
index is the treenode index
Returns
if the type has to be declared
Definition at line 2856 of file tree_helper.cpp.
References tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), name_type(), SplitString(), THROW_ASSERT, and test_panda::type.
Referenced by tree_manager::collapse_into(), and CWriter::DeclareType().
is_a_complex()
bool tree_helper::is_a_complex (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is a complex.
Parameters
TM is the tree_manager
index is the treenode index
Returns
true if treenode index is a complex
Definition at line 2646 of file tree_helper.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by conv_really_needed(), memory_allocation::finalize_memory_allocation(), HLS_manager::get_constant_string(), AllocationInformation::GetNodeTypePrec(), VcdSignalSelection::InitialSsaIsAddress(), mem_dominator_allocation::InternalExec(), allocation::InternalExec(), BehavioralHelper::is_a_complex(), BitLatticeManipulator::is_handled_by_bitvalue(), dead_code_elimination::kill_uses(), Bit_Value_opt::optimize(), VcdSignalSelection::SelectInitialSsa(), VcdSignalSelection::SingleStepPropagateAddrSsa(), and extract_patterns::ternary_plus_expr_extraction().
is_a_function()
bool tree_helper::is_a_function (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is a function_decl.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2794 of file tree_helper.cpp.
References get_type_index(), and is_a_pointer().
Referenced by get_type_index(), is_a_pointer(), and structural_type_descriptor::structural_type_descriptor().
is_a_misaligned_vector()
bool tree_helper::is_a_misaligned_vector (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode index is a a misaligned access to a vector data object.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2821 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), is_a_vector(), Size(), and THROW_ASSERT.
Referenced by memory_allocation::finalize_memory_allocation(), and fu_binding::specialise_fu().
is_a_nop_function_decl()
bool tree_helper::is_a_nop_function_decl (function_decl * fd) [static]
Definition at line 8344 of file tree_helper.cpp.
References function_decl::body, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, GET_NODE, sl, and THROW_ASSERT.
Referenced by operations_cfg_computation::build_operation_recursive(), ipa_point_to_analysis::compute_function_topological_order(), PhiOpt::ComputeFrontendRelationships(), fun_dominator_allocation::Exec(), get_required_values(), and dead_code_elimination::InternalExec().
is_a_pointer()
bool tree_helper::is_a_pointer (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is a pointer.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2785 of file tree_helper.cpp.
References get_type_index(), and is_a_function().
Referenced by TestbenchMemoryAllocation::AllocTestbenchMemory(), determine_memory_accesses::analyze_node(), operations_cfg_computation::build_operation_recursive(), minimal_interface::build_wrapper(), CSE::check_loads(), mux_connection_binding::create_connections(), ipa_point_to_analysis::Exec(), TestbenchValuesXMLGeneration::Exec(), CreateAddressTranslation::Exec(), memory_allocation::finalize_memory_allocation(), get_type_index(), AllocationInformation::GetNodeTypePrec(), TestbenchGenerationBaseStep::initialize_input_signals(), interface_infer::InternalExec(), allocation::InternalExec(), is_a_function(), BehavioralHelper::is_a_pointer(), VcdSignalSelection::IsAddressType(), Bit_Value_opt::optimize(), BehavioralHelper::print_node(), RecursiveGetTypesToBeDeclared(), MinimalInterfaceTestbench::write_input_signal_declaration(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), and HLSCWriter::WriteSimulatorInitMemory().
is_a_struct()
bool tree_helper::is_a_struct (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is a record.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2604 of file tree_helper.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by cannot_have_struct_parameters(), memory_allocation::finalize_memory_allocation(), AllocationInformation::GetNodeTypePrec(), FixStructsPassedByValue::InternalExec(), mem_dominator_allocation::InternalExec(), BehavioralHelper::is_a_struct(), BitLatticeManipulator::is_handled_by_bitvalue(), mux_connection_binding::object_bitsize(), and BehavioralHelper::print_node().
is_a_variable()
bool tree_helper::is_a_variable (const tree_managerConstRef & TM, const unsigned int index) [static]
The following one are not considered as variables, but as operations on the variables
Definition at line 3302 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_node::get_kind(), tree_node::get_kind_text(), tree_manager::get_tree_node_const(), NODE_NOT_YET_SUPPORTED_EC, THROW_ASSERT, and THROW_ERROR_CODE.
is_a_vector()
bool tree_helper::is_a_vector (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode index is a vector.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2803 of file tree_helper.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by determine_memory_accesses::analyze_node(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), operations_cfg_computation::build_operation_recursive(), CSE::check_loads(), short_circuit_taf::create_gimple_cond(), HLS_manager::get_constant_string(), get_required_values(), AllocationInformation::GetNodeTypePrec(), PhiOpt::IdentifyPattern(), compute_implicit_calls::InternalExec(), dead_code_elimination::InternalExec(), IR_lowering::InternalExec(), allocation::InternalExec(), is_a_misaligned_vector(), BehavioralHelper::is_a_vector(), BitLatticeManipulator::is_handled_by_bitvalue(), VcdSignalSelection::IsAddressType(), IsLoad(), dead_code_elimination::kill_uses(), Bit_Value_opt::optimize(), BehavioralHelper::print_node(), VcdSignalSelection::SingleStepPropagateAddrSsa(), fu_binding::specialise_fu(), extract_patterns::ternary_plus_expr_extraction(), HLSCWriter::WriteMainTestbench(), and HLSCWriter::WriteParamDecl().
is_a_void()
bool tree_helper::is_a_void (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of void type.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2956 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
is_an_addr_expr()
bool tree_helper::is_an_addr_expr (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is an address expression.
Parameters
TM is the tree manager
index is the treenode index
Returns
true if treenode index is an address expression
Definition at line 2851 of file tree_helper.cpp.
References tree_node::get_kind(), and tree_manager::get_tree_node_const().
is_an_array()
bool tree_helper::is_an_array (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is an array or it is equivalent to an array (record recursively having a single field ending into a single arrays)
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2736 of file tree_helper.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), get_type_node(), THROW_ASSERT, and test_panda::type.
Referenced by operations_cfg_computation::build_operation_recursive(), CSE::check_loads(), fu_binding::fill_array_ref_memory(), AllocationInformation::get_correction_time(), AllocationInformation::GetNodeTypePrec(), mem_dominator_allocation::InternalExec(), BehavioralHelper::is_an_array(), VcdSignalSelection::IsAddressType(), rebuild_initialization2::look_for_ROMs(), mux_connection_binding::object_bitsize(), and TestbenchGenerationBaseStep::print_var_init().
is_an_enum()
bool tree_helper::is_an_enum (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is an enumeral type.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2586 of file tree_helper.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by allocation::InternalExec(), and BehavioralHelper::is_an_enum().
is_an_union()
bool tree_helper::is_an_union (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if treenode index is an union.
Parameters
TM is the tree_manager
index is the treenode index
Returns
true if treenode index is an union
Definition at line 2625 of file tree_helper.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by cannot_have_struct_parameters(), memory_allocation::finalize_memory_allocation(), AllocationInformation::GetNodeTypePrec(), FixStructsPassedByValue::InternalExec(), mem_dominator_allocation::InternalExec(), BehavioralHelper::is_an_union(), mux_connection_binding::object_bitsize(), and BehavioralHelper::print_node().
is_bool()
bool tree_helper::is_bool (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of bool type.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2927 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), index, name_type(), and THROW_ASSERT.
Referenced by mux_connection_binding::add_conversion(), mux_connection_binding::create_connections(), short_circuit_taf::create_gimple_cond(), Bit_Value::forward_transfer(), AllocationInformation::GetNodeTypePrec(), BitLatticeManipulator::inf(), IR_lowering::InternalExec(), allocation::InternalExec(), BehavioralHelper::is_bool(), Bit_Value_opt::optimize(), structural_type_descriptor::structural_type_descriptor(), and BitLatticeManipulator::sup().
is_builtin_channel()
bool tree_helper::is_builtin_channel (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC builtin channel.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a SystemC builtin channel, false otherwise
Definition at line 3109 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), record_name(), and THROW_ASSERT.
Referenced by is_channel().
is_channel()
bool tree_helper::is_channel (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC channel.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a sc_channel, false otherwise
Definition at line 3116 of file tree_helper.cpp.
References record_type::binf, GET_NODE, tree_manager::get_tree_node_const(), is_builtin_channel(), look_for_binfo_inheritance(), and THROW_ASSERT.
Referenced by structural_type_descriptor::structural_type_descriptor().
is_clock()
bool tree_helper::is_clock (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index as parm is a SystemC sc_clock.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a sc_clock, false otherwise
Definition at line 3166 of file tree_helper.cpp.
References record_type::binf, record_type::get_maybe_name(), GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
is_concat_bit_ior_expr()
bool tree_helper::is_concat_bit_ior_expr (const tree_managerConstRef & TM, const unsigned int index) [static]
check if a given tree node is a concatenation operation
Parameters
TM is the tree_manager
index is the index of the tree_node
Returns
true when index is a bit_ior_expr and the bit values are mutually exclusive.
Definition at line 4766 of file tree_helper.cpp.
References tree_node::get_kind(), GET_NODE, and tree_manager::get_tree_node_const().
Referenced by AllocationInformation::GetNodeTypePrec().
is_const_type()
bool tree_helper::is_const_type (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if the treenode is of const type.
Parameters
TM is the tree_manager
index is the treenode index
Returns
if tree_node is of const type
Definition at line 4520 of file tree_helper.cpp.
References FIRST_TOKEN, tree_manager::get_tree_node_const(), get_type_node(), THROW_ASSERT, TOK_QUAL_C, TOK_QUAL_CV, and TOK_QUAL_CVR.
is_constant()
bool tree_helper::is_constant (const tree_managerConstRef & TM, const unsigned int index) [static]
Return if a tree node is a constant object.
Parameters
TM is the tree_manager
index is the index of the tree_node
Returns
true is the object is constant
Definition at line 4837 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_node::get_kind(), and tree_manager::get_tree_node_const().
Referenced by simple_code_motion::CheckMovable(), AllocationInformation::GetNodeTypePrec(), commutative_expr_restructuring::IsCommExprChain(), and CondExprRestructuring::IsCondExprChain().
is_event()
bool tree_helper::is_event (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC event.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is an event, false otherwise
Definition at line 3286 of file tree_helper.cpp.
References record_type::binf, GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
Referenced by structural_type_descriptor::structural_type_descriptor().
is_extern()
bool tree_helper::is_extern (const tree_managerConstRef & TM, const unsigned int index) [static]
Definition at line 4500 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and THROW_ASSERT.
Referenced by discrepancy_instruction_writer::declareFunction(), BehavioralHelper::is_extern(), DiscrepancyAnalysisCWriter::WriteFunctionDeclaration(), and DiscrepancyAnalysisCWriter::WriteFunctionImplementation().
is_fully_resolved()
bool tree_helper::is_fully_resolved (const tree_managerConstRef & TM, const unsigned int index, CustomOrderedSet< unsigned int > & res_set) [static]
Definition at line 4151 of file tree_helper.cpp.
References CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_TYPE_NODES, check_for_simple_pointer_arithmetic(), GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), tree_manager::get_tree_node_const(), NODE_NOT_YET_SUPPORTED_EC, STR, THROW_ASSERT, and THROW_ERROR_CODE.
Referenced by mem_dominator_allocation::InternalExec().
is_function_pointer_type()
bool tree_helper::is_function_pointer_type (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of type function pointer type.
Parameters
TM is the tree_manager
index is the treenode_index
Definition at line 2902 of file tree_helper.cpp.
References GET_NODE, tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by BehavioralHelper::print_node().
is_function_type()
bool tree_helper::is_function_type (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of type function type.
Parameters
TM is the tree_manager
index is the treenode_index
Definition at line 2885 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
is_in_port()
bool tree_helper::is_in_port (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC input port.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is an input port, false otherwise
Definition at line 3238 of file tree_helper.cpp.
References record_type::binf, GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
is_inout_port()
bool tree_helper::is_inout_port (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC in-output port.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is an inoutput port, false otherwise
Definition at line 3270 of file tree_helper.cpp.
References record_type::binf, GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
is_int()
bool tree_helper::is_int (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of integer type.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2991 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), index, name_type(), and THROW_ASSERT.
Referenced by mux_connection_binding::add_conversion(), StorageValueInformation::are_value_bitsize_compatible(), Bit_Value::backward_transfer(), mux_connection_binding::connect_array_index(), constrainSSA(), BitLatticeManipulator::constructor_bitstring(), mux_connection_binding::create_connections(), interface_infer::create_Write_function(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), AllocationInformation::GetConnectionTime(), AllocationInformation::GetNodeTypePrec(), BitLatticeManipulator::inf(), Bit_Value::initialize(), IR_lowering::InternalExec(), allocation::InternalExec(), BehavioralHelper::is_int(), Bit_Value_opt::optimize(), BitLatticeManipulator::string_cst_bitstring(), structural_type_descriptor::structural_type_descriptor(), BitLatticeManipulator::sup(), and BitLatticeManipulator::update_current().
is_module()
bool tree_helper::is_module (const tree_managerConstRef & TM, unsigned int index) [static]
This function test if a given index is a SystemC module.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a sc_module, false otherwise
Definition at line 3091 of file tree_helper.cpp.
References record_type::binf, GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
Referenced by structural_type_descriptor::structural_type_descriptor().
is_natural()
bool tree_helper::is_natural (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is a ssa_name greater or equal to zero.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 2974 of file tree_helper.cpp.
References get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), index, min, and THROW_ASSERT.
Referenced by Bit_Value::initialize(), and BehavioralHelper::is_natural().
is_out_port()
bool tree_helper::is_out_port (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC output port.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is an output port, false otherwise
Definition at line 3254 of file tree_helper.cpp.
References record_type::binf, GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
is_packed()
bool tree_helper::is_packed (const tree_managerConstRef & TreeM, unsigned int node_index) [static]
Print the contents of the structure
Definition at line 6456 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), decl_node::packed_flag, type_node::packed_flag, THROW_ASSERT, THROW_UNREACHABLE, test_panda::type, and type_node::unql.
Referenced by mem_dominator_allocation::InternalExec().
is_packed_access()
bool tree_helper::is_packed_access (const tree_managerConstRef & TreeM, unsigned int node_index) [static]
Check if the access is on a packed data structure or not.
Parameters
TreeM is the tree manager
node_index is the node id under check
Returns
true in case the access is to a packed data structure or not
Definition at line 6590 of file tree_helper.cpp.
References CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_TYPE_NODES, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), and THROW_ERROR.
Referenced by memory_allocation::finalize_memory_allocation().
is_parameter()
bool tree_helper::is_parameter (const tree_managerConstRef & TM, const unsigned int index) [static]
return true in case the index corresponds to a parameter in ssa form or not
Parameters
TM is the tree manager
index is the id of a potential parameter
Returns
true in case the index is a parameter
Definition at line 4444 of file tree_helper.cpp.
References GET_NODE, tree_manager::get_tree_node_const(), and THROW_ASSERT.
Referenced by mux_connection_binding::connect_to_registers(), StorageValueInformation::Initialize(), cdfc_module_binding::initialize_connection_relation(), FSM_NI_SSA_liveness::InternalExec(), port_swapping::InternalExec(), HLS_manager::is_register_compatible(), and mux_connection_binding::swap_p().
is_port()
bool tree_helper::is_port (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC port.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a port, false otherwise
Definition at line 3221 of file tree_helper.cpp.
References record_type::binf, record_type::get_maybe_name(), GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
is_real()
bool tree_helper::is_real (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of real type.
Parameters
TM is the tree_manager
index is the treenode index
Returns
if index is of real type
Definition at line 3023 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), and THROW_ASSERT.
Referenced by simple_code_motion::CheckMovable(), conv_really_needed(), mux_connection_binding::create_connections(), HLS_manager::get_constant_string(), AllocationInformation::GetNodeTypePrec(), VcdSignalSelection::InitialSsaIsAddress(), IR_lowering::InternalExec(), allocation::InternalExec(), BitLatticeManipulator::is_handled_by_bitvalue(), BehavioralHelper::is_real(), dead_code_elimination::kill_uses(), Bit_Value_opt::optimize(), VcdSignalSelection::SelectInitialSsa(), VcdSignalSelection::SingleStepPropagateAddrSsa(), extract_patterns::ternary_plus_expr_extraction(), MinimalInterfaceTestbench::write_input_signal_declaration(), TestbenchGenerationBaseStep::write_output_checks(), and WishboneInterfaceTestbench::write_signals().
is_SC_BIND_PROXY_NIL()
bool tree_helper::is_SC_BIND_PROXY_NIL (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index as parm is a SC_BIND_PROXY_NIL.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a SC_BIND_PROXY_NIL, false otherwise
Definition at line 3184 of file tree_helper.cpp.
References tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), and THROW_ASSERT.
is_signal()
bool tree_helper::is_signal (const tree_managerConstRef & TM, const unsigned int index) [static]
This function test if a given index is a SystemC sc_signal.
Parameters
TM is the tree_manager
index is the treenode
Returns
true if index is a sc_signal, false otherwise
Definition at line 3147 of file tree_helper.cpp.
References record_type::binf, record_type::get_maybe_name(), GET_NODE, tree_manager::get_tree_node_const(), look_for_binfo_inheritance(), and THROW_ASSERT.
is_simple_pointer_plus_test()
bool tree_helper::is_simple_pointer_plus_test (const tree_managerConstRef & TM, const unsigned int index) [static]
check if a given tree node is a simple pointer plus expression
Parameters
TM is the tree_manager
index is the index of the tree_node
Returns
true when index is a simple pointer plus expression between two constants
Definition at line 4802 of file tree_helper.cpp.
References tree_node::get_kind(), GET_NODE, and tree_manager::get_tree_node_const().
is_ssa_name()
bool tree_helper::is_ssa_name (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true in case index is a ssa_name.
Parameters
TM is the tree manager
index is the index of a possible ssa_name
Returns
true in case of ssa_name
Definition at line 4460 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and THROW_ASSERT.
Referenced by StorageValueInformation::Initialize(), FSM_NI_SSA_liveness::InternalExec(), and HLS_manager::is_register_compatible().
is_static()
bool tree_helper::is_static (const tree_managerConstRef & TM, const unsigned int index) [static]
Definition at line 4480 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and THROW_ASSERT.
Referenced by discrepancy_instruction_writer::declareFunction(), BehavioralHelper::is_static(), print_type(), DiscrepancyAnalysisCWriter::WriteFunctionDeclaration(), and DiscrepancyAnalysisCWriter::WriteFunctionImplementation().
is_system()
bool tree_helper::is_system (const tree_managerConstRef TM, const unsigned int index) [static]
Return true if variable or type is a system one.
Parameters
TM is the tree manager
index is the index of the treenode corresponding to the decl node or to the type node
Returns
true if variable or type is a system one
Definition at line 1457 of file tree_helper.cpp.
References tree_manager::CGetTreeNode(), tree_manager::get_tree_node_const(), and index.
Referenced by CWriter::DeclareVariable(), BehavioralHelper::function_has_to_be_printed(), BehavioralHelper::print_constant(), and DiscrepancyAnalysisCWriter::WriteExtraInitCode().
is_unsigned()
bool tree_helper::is_unsigned (const tree_managerConstRef & TM, const unsigned int index) [static]
Return true if the treenode is of unsigned integer type.
Parameters
TM is the tree_manager
index is the treenode index
Definition at line 3041 of file tree_helper.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::get_tree_node_const(), get_type_node(), GetElements(), INDENT_DBG_MEX, index, name_type(), and THROW_ASSERT.
Referenced by mux_connection_binding::add_conversion(), operations_cfg_computation::build_operation_recursive(), mux_connection_binding::create_connections(), IR_lowering::division_by_a_constant(), IR_lowering::expand_mult_highpart(), AllocationInformation::GetNodeTypePrec(), IR_lowering::InternalExec(), allocation::InternalExec(), BehavioralHelper::is_unsigned(), MemoryInitializationCWriter::Process(), MemoryInitializationWriter::Process(), hls_div_cg_ext::recursive_examinate(), soft_float_cg_ext::RecursiveExaminate(), and structural_type_descriptor::structural_type_descriptor().
is_virtual()
bool tree_helper::is_virtual (const tree_managerConstRef & TM, const unsigned int index) [static]
return true in case the ssa_name is virtual
Parameters
TM is the tree manager
index is the id of a potential ssa_name
Returns
true in case the index is a virtual ssa_name
Definition at line 4468 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and THROW_ASSERT.
Referenced by StorageValueInformation::Initialize(), FSM_NI_SSA_liveness::InternalExec(), NI_SSA_liveness::InternalExec(), and HLS_manager::is_register_compatible().
is_volatile()
bool tree_helper::is_volatile (const tree_managerConstRef & TM, const unsigned int index) [static]
return true in case the index corresponds to a volatile variable
Parameters
TM is the tree manager
index is the id of a variable/ssa_name
Returns
true in case the variable/ssa_name is a volatile object
Definition at line 4429 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), get_type_node(), THROW_ASSERT, TOK_QUAL_CVR, TOK_QUAL_V, and TOK_QUAL_VR.
Referenced by determine_memory_accesses::analyze_node(), memory_allocation::finalize_memory_allocation(), and VarComputation::RecursivelyAnalyze().
IsAligned()
bool tree_helper::IsAligned (const tree_managerConstRef & TM, unsigned int type) [static]
Return true if type has not default alignment.
Definition at line 5293 of file tree_helper.cpp.
References type_node::algn, tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), THROW_ASSERT, and type_node::unql.
Referenced by RecursiveGetTypesToBeDeclared().
IsLoad()
bool tree_helper::IsLoad (const tree_managerConstRef & TM, const tree_nodeConstRef & tn, const CustomOrderedSet< unsigned int > & fun_mem_data) [static]
Return true if the tree node is a gimple_assign reading something which will be allocated in memory.
Parameters
TM is the tree manager
tn is the tree node
fun_mem_data is the set of memory variables of the function
Returns
true if tn operation is a load
check for bit field ref of vector type
Definition at line 8978 of file tree_helper.cpp.
References CGetType(), GET_CONST_NODE, GET_INDEX_NODE, GET_NODE, get_type_node(), and is_a_vector().
Referenced by operations_cfg_computation::build_operation_recursive(), and BehavioralHelper::IsLoad().
IsLut()
bool tree_helper::IsLut (const tree_managerConstRef & TM, const tree_nodeConstRef & tn) [static]
Return true in case the right operation is a lut_expr.
Parameters
TM is the tree manager
tn is the tree node
Returns
if tn operation is a lut_expr
Definition at line 9035 of file tree_helper.cpp.
References GET_CONST_NODE, and GET_NODE.
Referenced by BehavioralHelper::IsLut().
IsStore()
bool tree_helper::IsStore (const tree_managerConstRef & TM, const tree_nodeConstRef & tn, const CustomOrderedSet< unsigned int > & fun_mem_data) [static]
Return true if the tree node is a gimple_assign writing something which will be allocated in memory.
Parameters
TM is the tree manager
tn is the tree node
fun_mem_data is the set of memory variables of the function
Returns
true if tn operation is a store
Definition at line 8931 of file tree_helper.cpp.
References CGetType(), GET_CONST_NODE, GET_INDEX_NODE, GET_NODE, and get_type_node().
Referenced by operations_cfg_computation::build_operation_recursive(), and BehavioralHelper::IsStore().
LastStatement()
bool tree_helper::LastStatement (const tree_nodeConstRef & statement) [static]
Return true if statement must be the last of a basic block.
Parameters
statement is the statement to be analyzed
Returns
true if statement must be the last of a basic block
Definition at line 8829 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_CONST_NODE, and THROW_UNREACHABLE.
Referenced by bloc::PushBack().
look_for_binfo_inheritance()
bool tree_helper::look_for_binfo_inheritance (binfo * b, const std::string & bcs) [static]
Look for inheritance of a class.
Parameters
b is the binfo to explore
bcs is the name of the base class
Returns
true if an inheritance is found
Definition at line 1363 of file tree_helper.cpp.
References binfo::get_base(), binfo::get_baseinfo_size(), GET_NODE, and binfo::type.
Referenced by is_channel(), is_clock(), is_event(), is_in_port(), is_inout_port(), is_module(), is_out_port(), is_port(), and is_signal().
name_function()
std::string tree_helper::name_function (const tree_managerConstRef tm, const unsigned int index) [static]
Return the name of the function.
Parameters
tm is the tree manager
index is the treenode_index of the class (is the index of a function_decl)
Definition at line 854 of file tree_helper.cpp.
References tree_node::get_kind(), tree_node::get_kind_text(), tree_manager::get_tree_node_const(), print_function_name(), and THROW_ERROR.
Referenced by fu_binding::add_to_SM(), memory_allocation::allocate_parameters(), build_bus_interface(), WB4_interface::build_WB4_bus_interface(), WB4_interface::build_WB4_complete_logic(), buildCircuit(), HLSFunctionStep::ComputeRelationships(), HLS_step::ComputeRelationships(), HLS_manager::create_HLS(), HWDiscrepancyAnalysis::Exec(), ipa_point_to_analysis::Exec(), call_graph_computation::Exec(), BehavioralHelper::get_asm_string(), FixStructsPassedByValue::InternalExec(), parm_decl_taken_address_fix::InternalExec(), InitializeHLS::InternalExec(), CallGraphBuiltinCall::InternalExec(), HWCallInjection::isHardwareCall(), CallGraphBuiltinCall::lookForBuiltinCall(), and memory::xwrite().
name_tmpl()
std::string tree_helper::name_tmpl (const tree_managerConstRef tm, const unsigned int index) [static]
Return the name of template without parameters.
Ex: sc_signal<T> --> sc_signal
Parameters
tm is the tree manager
index is the treenode_index of the class template (is the index of a record_type)
Definition at line 807 of file tree_helper.cpp.
References tree_node::get_kind(), GET_NODE, and tree_manager::get_tree_node_const().
name_type()
std::string tree_helper::name_type (const tree_managerConstRef tm, const unsigned int index) [static]
Return the type name of a signal or a port.
Parameters
tm is the tree manager
index is the treenode_index
Definition at line 541 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), index, decl_node::name, type_node::name, normalized_ID(), SC_tmpl_class, STR, identifier_node::strg, THROW_ASSERT, THROW_ERROR, and THROW_UNREACHABLE.
Referenced by CWriter::DeclareType(), HasToBeDeclared(), is_bool(), is_int(), is_unsigned(), BehavioralHelper::print_node(), and structural_type_descriptor::structural_type_descriptor().
normalized_ID()
std::string tree_helper::normalized_ID (const std::string & id) [static]
Return the normalized the name of types and variables.
Parameters
id is the initial ID
Definition at line 5310 of file tree_helper.cpp.
Referenced by conn_binding::add_command_ports(), fu_binding::add_to_SM(), operations_cfg_computation::build_operation_recursive(), BB_based_stg::compute_EPP_edge_increments(), HLSFunctionStep::ComputeRelationships(), HLS_step::ComputeRelationships(), fsm_controller::create_state_machine(), AllocationInformation::get_attribute_of_fu_per_op(), AllocationInformation::get_cycles(), AllocationInformation::get_execution_time(), AllocationInformation::get_initiation_time(), get_mangled_fname(), AllocationInformation::get_stage_period(), AllocationInformation::GetNodeTypePrec(), OmpAllocation::IntegrateTechnologyLibraries(), InitializeHLS::InternalExec(), BB_based_stg::InternalExec(), allocation::InternalExec(), AllocationInformation::is_operation_bounded(), AllocationInformation::is_operation_PI_registered(), name_type(), BB_based_stg::optimize_cycles(), AllocationInformation::print_allocated_resources(), print_function_name(), print_type(), BehavioralHelper::PrintVariable(), VarDeclFix::recursive_examinate(), and DiscrepancyAnalysisCWriter::writePostInstructionInfo().
op_symbol() [1/2]
std::string tree_helper::op_symbol (const tree_nodeRef & op) [static]
Function return the symbol related with the operator op passed as parameter.
Parameters
op is the tree node of the expression
Returns
the string correspoinding to the operator
Definition at line 4881 of file tree_helper.cpp.
References refcount< T >::get().
Referenced by GimpleWriter::GimpleWriter(), and BehavioralHelper::print_node().
op_symbol() [2/2]
std::string tree_helper::op_symbol (const tree_node * op) [static]
Function return the symbol related with the operator op passed as parameter.
Parameters
op is the tree node of the expression
Returns
the string correspoinding to the operator
Definition at line 4886 of file tree_helper.cpp.
References CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_node::index, THROW_ASSERT, and THROW_ERROR.
print_function_name()
std::string tree_helper::print_function_name (const tree_managerConstRef TM, const function_decl * fd) [static]
Return the name of the function in a string.
Parameters
node is the function_decl
Definition at line 893 of file tree_helper.cpp.
References function_decl::body, function_decl::builtin_flag, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::is_CPP(), tree_manager::is_top_function(), attr::list_attr, decl_node::mngl, decl_node::name, normalized_ID(), print_type(), THROW_ERROR, TI_getTokenName(), TOK_ASSIGN, TOK_CONVERSION, TOK_LSHIFT, TOK_MEMBER, TOK_OPERATOR, TOK_PRIVATE, TOK_PROTECTED, TOK_PUBLIC, TOK_RSHIFT, and decl_node::type.
Referenced by determine_memory_accesses::analyze_node(), operations_cfg_computation::build_operation_recursive(), mux_connection_binding::create_connections(), ipa_point_to_analysis::Exec(), parm2ssa::Exec(), tree_manager::function_index(), call_expr_fix::InternalExec(), BehavioralHelper::is_va_start_call(), name_function(), BehavioralHelper::print_constant(), BehavioralHelper::print_init(), BehavioralHelper::print_node(), print_type(), BehavioralHelper::PrintVariable(), and CheckSystemType::recursive_examinate().
print_type()
std::string tree_helper::print_type (const tree_managerConstRef & TM, unsigned int type, bool global = false, bool print_qualifiers = false, bool print_storage = false, unsigned int var = 0, const var_pp_functorConstRef & vppf = var_pp_functorConstRef(), const std::string & prefix = ``, const std::string & tail = ``) [static]
Print a type and its variable in case var is not zero.
Parameters
type is the type of var.
global tells if the variable is global
print_qualifiers tells if the qualifiers (i.e. `const`) have to be printed
print_storage tells if the storage (i.e. `static`) has to be printed
var is the variable.
vppf is the pointer to the functor used to dump the possible variable var
prefix is the string to be appended at the begining of the printing
Returns
the printed string
patch for unsigned char
patch for va_list
Global variables or parameters
Ad hoc management of vector of bool
references are translated as pointer type objects
Compute the dimensions
add alignment
tree_list are used for parameters declaration: in that case void_type has to be removed from the last type parameter
Definition at line 5335 of file tree_helper.cpp.
References type_node::algn, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, array_type::elts, FIRST_TOKEN, GET_CONST_NODE, tree_manager::get_implementation_node(), GET_INDEX_NODE, get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), get_type_index(), GetRealType(), INDENT_DBG_MEX, tree_manager::is_CPP(), is_static(), type_node::name, normalized_ID(), print_function_name(), return_C_qualifiers(), Size(), type_node::size, SplitString(), STR, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, and test_panda::type.
Referenced by CWriter::compute_phi_nodes(), CallGraphBuiltinCall::ExtendCallGraph(), CallGraphBuiltinCall::InternalExec(), BehavioralHelper::print_constant(), BehavioralHelper::print_forward_declaration(), print_function_name(), BehavioralHelper::print_node(), BehavioralHelper::print_type(), BehavioralHelper::print_type_declaration(), BehavioralHelper::PrintVarDeclaration(), BehavioralHelper::PrintVariable(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), and HLSCWriter::WriteTestbenchFunctionCall().
record_name()
std::string tree_helper::record_name (const tree_managerConstRef tm, unsigned int index) [static]
Return the name of the class.
Parameters
tm is the tree manager
index is the treenode_index of the class (is the index of a record_type)
Definition at line 832 of file tree_helper.cpp.
References tree_node::get_kind(), GET_NODE, and tree_manager::get_tree_node_const().
Referenced by is_builtin_channel().
RecursiveGetTypesToBeDeclared()
const CustomUnorderedSet< unsigned int > tree_helper::RecursiveGetTypesToBeDeclared (const tree_managerConstRef TM, const unsigned int index, const bool recursive, const bool without_transformation, const bool before) [static], [private]
Return the type to be declared before declaring index type.
Parameters
TM is the tree_manager
index is the starting type
recursive must be set to true in recursive call
without_transformation specifies if we are not restructuring the code
before is true if we are computing types which must be declared before index
Returns
the types to be declared
Non pointer fields must be declared before structs, pointer fields can be declared after; in some cases they must be declared after (circular dependencies)
Here true is correct
Non pointer fields must be declared before structs, pointer fields can be declared after; in some cases they must be declared after (circular dependencies)
Here true is correct
Definition at line 1497 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, CGetFieldTypes(), tree_manager::CGetTreeNode(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_CONST_NODE, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, get_parameter_types(), get_pointed_type(), tree_manager::get_tree_node_const(), GetElements(), GetFunctionReturnType(), INDENT_DBG_MEX, tree_node::index, is_a_pointer(), IsAligned(), type_node::name, test_panda::parameters, STR, THROW_UNREACHABLE, test_panda::type, and type_node::unql.
Referenced by GetTypesToBeDeclaredAfter(), and GetTypesToBeDeclaredBefore().
return_C_qualifiers()
std::string tree_helper::return_C_qualifiers (const TreeVocabularyTokenTypes_TokenEnum quals, bool real_const) [static]
return the qualifiers in C format
Parameters
quals store the token encoding the qualifiers
real_const is true when we need a real constant (e.g., const is not commented)
Definition at line 4573 of file tree_helper.cpp.
References THROW_UNREACHABLE, TOK_QUAL_C, TOK_QUAL_CR, TOK_QUAL_CV, TOK_QUAL_CVR, TOK_QUAL_R, TOK_QUAL_V, and TOK_QUAL_VR.
Referenced by GimpleWriter::GimpleWriter(), print_type(), and BehavioralHelper::print_type_declaration().
return_qualifier_prefix()
std::string tree_helper::return_qualifier_prefix (const TreeVocabularyTokenTypes_TokenEnum quals) [static]
return the prefix given a qualifier
Parameters
quals store the token encoding the qualifiers
Definition at line 4539 of file tree_helper.cpp.
References STR, THROW_UNREACHABLE, TOK_QUAL_C, TOK_QUAL_CR, TOK_QUAL_CV, TOK_QUAL_CVR, TOK_QUAL_R, TOK_QUAL_V, and TOK_QUAL_VR.
Referenced by tree_manager::check_for_decl(), and tree_manager::check_for_type().
size()
unsigned int tree_helper::size (const tree_managerConstRef tm, const unsigned int index) [static]
Return the size of a tree object.
Parameters
tm is the tree manager
index is the treenode
Definition at line 106 of file tree_helper.cpp.
References tree_manager::get_tree_node_const(), and Size().
Referenced by accessed_greatest_bitsize(), accessed_minimum_bitsize(), memory::add_internal_symbol(), fu_binding::add_to_SM(), mux_connection_binding::address_precision(), memory_allocation::allocate_parameters(), TestbenchMemoryAllocation::AllocTestbenchMemory(), StorageValueInformation::are_value_bitsize_compatible(), Bit_Value::backward_transfer(), operations_cfg_computation::build_operation_recursive(), minimal_interface::build_wrapper(), memory::compute_next_base_address(), constrainSSA(), conv_really_needed(), mux_connection_binding::create_connections(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), vcd_utility::detect_fixed_address_mismatch(), mux_connection_binding::determine_connection(), IR_lowering::division_by_a_constant(), TestbenchValuesXMLGeneration::Exec(), IR_lowering::expand_mult_const(), fu_binding::fill_array_ref_memory(), memory_allocation::finalize_memory_allocation(), get_array_data_bitsize(), get_array_dim_and_bitsize(), HLS_manager::get_constant_string(), memory::get_last_address(), BehavioralHelper::get_size(), AllocationInformation::GetCondExprTimeLatency(), AllocationInformation::GetNodeTypePrec(), AllocationInformation::GetPhiConnectionLatency(), ComputeReservedMemory::GetReservedBytes(), BitLatticeManipulator::inf(), allocation::IntegrateTechnologyLibraries(), mem_dominator_allocation::InternalExec(), dead_code_elimination::InternalExec(), interface_infer::InternalExec(), IR_lowering::InternalExec(), allocation::InternalExec(), mux_connection_binding::object_bitsize(), Bit_Value_opt::optimize(), Bit_Value::pointer_resizing(), vcd_utility::print_discrepancy(), BehavioralHelper::print_node(), TestbenchGenerationBaseStep::print_var_init(), MemoryInitializationCWriter::Process(), MemoryInitializationWriter::Process(), soft_float_cg_ext::RecursiveExaminate(), Size(), constant_flop_wrapper::SoftFloatWriter(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), structural_type_descriptor::structural_type_descriptor(), BitLatticeManipulator::sup(), fu_binding::write_init(), MinimalInterfaceTestbench::write_input_signal_declaration(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), HLSCWriter::WriteParamInitialization(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and HLSCWriter::WriteSimulatorInitMemory().
Size()
unsigned int tree_helper::Size (const tree_nodeConstRef tn) [static]
Return the size of a tree object.
Parameters
tn is the tree object
Returns
the size of the object
It may happen with GCC8 -O0
count leading ONEs
Definition at line 111 of file tree_helper.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, counter, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_CONST_NODE, get_integer_cst_value(), tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, index, max(), enumeral_type::max, integer_type::max, min, enumeral_type::min, integer_type::min, size(), Size(), STR, THROW_ASSERT, THROW_UNREACHABLE, test_panda::type, enumeral_type::unsigned_flag, and integer_type::unsigned_flag.
Referenced by AllocatedMemorySize(), Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), minimal_interface::build_wrapper(), top_entity_parallel_cs::BW_loop_iter(), AllocationInformation::can_be_asynchronous_ram(), AllocationInformation::CanBeMerged(), simple_code_motion::CheckMovable(), CreateAddressTranslation::ComputeAddress(), interface_infer::create_Read_function(), interface_infer::create_Write_function(), IR_lowering::division_by_a_constant(), BitValueIPA::Exec(), IR_lowering::expand_MC(), fu_binding::fill_array_ref_memory(), Bit_Value::forward(), Bit_Value::forward_transfer(), AllocationInformation::GetConnectionTime(), AllocationInformation::GetCycleLatency(), AllocationInformation::GetStatementArea(), AllocationInformation::GetTimeLatency(), CSE::hash_check(), BitLatticeManipulator::inf(), Bit_Value::initialize(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), compute_implicit_calls::InternalExec(), interface_infer::InternalExec(), IR_lowering::InternalExec(), is_a_misaligned_vector(), Bit_Value::manage_forward_binary_operands(), Bit_Value_opt::optimize(), print_type(), hls_div_cg_ext::recursive_examinate(), size(), Size(), BitLatticeManipulator::sup(), extract_patterns::ternary_plus_expr_extraction(), Vectorize::Transform(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteParamInMemory(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and HLSCWriter::WriteSimulatorInitMemory().
Field Documentation
debug_level
int tree_helper::debug_level = 0 [static]
debug level (set by Parameter)
Definition at line 117 of file tree_helper.hpp.
Referenced by AllocatedMemorySize(), BambuParameter::CheckParameters(), compute_ssa_uses_rec_ptr(), ComputeSsaUses(), get_integer_cst_value(), is_unsigned(), print_type(), RecursiveGetTypesToBeDeclared(), and Size().
local_return_index
unsigned int tree_helper::local_return_index = 0 [static]
Return the treenode of the type of node.
Parameters
node is the treenode
Definition at line 311 of file tree_helper.hpp.
Referenced by get_field_idx().
SC_builtin_scalar_type
const std::set< std::string > tree_helper::SC_builtin_scalar_type [static], [private]
Initial value:
= {"sc_int", "sc_uint", "sc_biguint", "sc_bigint", "sc_lv",
                                                                   "sc_in_rv", "sc_out_rv", "sc_inout_rv",
      "sc_bv", "sc_signal_rv"}
store the set of SystemC class for which the template parameter correspond to the bit size of the type
Definition at line 92 of file tree_helper.hpp.
SC_tmpl_class
const std::set< std::string > tree_helper::SC_tmpl_class = {`sc_signal`, `sc_in`, `sc_out`, `sc_inout`, `sc_port`, `sc_export`} [static], [private]
store the set of SystemC class for which the type correspond to the template parameter
Header include.
parser/treegcc include STL include Tree include Utility include built in type without parameter `sc_in_resolved` is not a template and inherits from sc_in<sc_dt::sc_logic> `sc_inout_resolved` is not a template and inherits from sc_inout<sc_dt::sc_logic> `sc_out_resolved` is not a template and inherits from sc_inout_resolved `sc_in_clk` is not a template and is a typedef of sc_in<bool> `sc_out_clk` is not a template and is a typedef of sc_out<bool> `sc_inout_clk` is not a template and is a typedef of sc_inout<bool> builtin types with parameter `sc_lv` is a template, has a parameter (W) `sc_bv` is a template, has a parameter (W) `sc_in_rv` is a template, has a parameter (W) and inherits from sc_in<sc_dt::sc_lv<W> > `sc_out_rv` is a template, has a parameter (W) and inherits from sc_inout_rv<W> `sc_inout_rv` is a template, has a parameter (W) and inherits from sc_inout<sc_dt::sc_lv<W> > `sc_signal_rv` is a template, has a parameter (W) and inherits from sc_signal<sc_dt::sc_lv<W> > `sc_fifo_in` is a template, has a parameter (T) and inherits from sc_port<sc_fifo_in_if<T>,0> `sc_fifo_out` is a template, has a parameter (T) and inherits from sc_port<sc_fifo_out_if<T>,0>
Definition at line 89 of file tree_helper.hpp.
Referenced by name_type().
TLM_SC_builtin_scalar_type
const std::set< std::string > tree_helper::TLM_SC_builtin_scalar_type [static], [private]
Initial value:
= {
    "tlm_blocking_put_if", "tlm_blocking_get_if", "tlm_nonblocking_get_if", "tlm_nonblocking_put_if",
    "tlm_transport_if"
}
store the set of TLM SystemC class for which the size corresponds to the sum of the size of template parameters
Definition at line 95 of file tree_helper.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_helper.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_helper.cpp