top_entity_parallel_cs Class Reference
#include <top_entity_parallel_cs.hpp>
Public Member Functions
top_entity_parallel_cs (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
behavior include
virtual ~top_entity_parallel_cs ()
Destructor.
virtual DesignFlowStep_Status InternalExec ()
Add selector and suspension.
Protected Member Functions
void connect_port_parallel (const structural_objectRef circuit, unsigned loopBW)
connect_port_parallel connect datapath and controller
virtual const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
unsigned BW_loop_iter (const structural_objectRef circuit)
void connect_loop_iter (const structural_objectRef circuit, unsigned loopBW)
void resize_controller_parallel (structural_objectRef controller_circuit, unsigned loopBW)
resize_controller_parallel
Additional Inherited Members
Detailed Description
Definition at line 46 of file top_entity_parallel_cs.hpp.
Constructor & Destructor Documentation
top_entity_parallel_cs()
top_entity_parallel_cs::top_entity_parallel_cs (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
behavior include
STD includes STL includes utility includes
Definition at line 73 of file top_entity_parallel_cs.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 top_entity_parallel_cs()
top_entity_parallel_cs::~top_entity_parallel_cs () [virtual]
Destructor.
Definition at line 79 of file top_entity_parallel_cs.cpp.
Member Function Documentation
BW_loop_iter()
unsigned top_entity_parallel_cs::BW_loop_iter (const structural_objectRef circuit) [protected]
Definition at line 251 of file top_entity_parallel_cs.cpp.
References ceil_log2(), FunctionBehavior::CGetLoops(), component_o_K, structural_object::find_member(), HLSFunctionStep::funId, HLS_step::HLSMgr, tree_helper::Size(), THROW_ASSERT, and THROW_ERROR.
Referenced by InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > top_entity_parallel_cs::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from top_entity.
Definition at line 83 of file top_entity_parallel_cs.cpp.
References DATAPATH_CS_PARALLEL_CREATOR, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
connect_loop_iter()
void top_entity_parallel_cs::connect_loop_iter (const structural_objectRef circuit, unsigned loopBW) [protected]
Definition at line 285 of file top_entity_parallel_cs.cpp.
References structural_manager::add_connection(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetLoops(), component_o_K, structural_object::find_member(), HLSFunctionStep::funId, structural_manager::get_circ(), HLS_step::HLSMgr, DesignFlowStep::parameters, port_o_K, BehavioralHelper::PrintVariable(), structural_object::set_type(), top_entity::SM, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by connect_port_parallel().
connect_port_parallel()
void top_entity_parallel_cs::connect_port_parallel (const structural_objectRef circuit, unsigned loopBW) [protected]
connect_port_parallel connect datapath and controller
Parameters
circuit
Definition at line 345 of file top_entity_parallel_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), structural_manager::add_sign_vector(), component_o_K, connect_loop_iter(), hls::datapath, DONE_PORT_NAME, DONE_REQUEST, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, DesignFlowStep::parameters, port_o_K, port_vector_o_K, top_entity::SM, START_PORT_NAME, STR, and TASKS_POOL_END.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status top_entity_parallel_cs::InternalExec () [virtual]
Add selector and suspension.
Returns
the exit status of this step
function name to be synthesized
Test on previuos steps. They checks if datapath and controller have been created. If they didn't, top circuit cannot be created.
top circuit creation
main circuit type
setting top circuit component
Set some descriptions and legal stuff
creating structural_manager
command signal type descriptor
add clock port
connect to datapath and controller clock
add reset port
connecting global reset port to the datapath one
connecting global reset port to the controller one
start port
check if datapath has a start signal
add done port
add entry in in_port_map between port id and port index
Reimplemented from top_entity.
Definition at line 107 of file top_entity_parallel_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), top_entity::add_ports(), structural_manager::add_sign(), BW_loop_iter(), FunctionBehavior::CGetBehavioralHelper(), CLOCK_PORT_NAME, connect_port_parallel(), hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, structural_object::find_member(), flipflop_AR, flipflop_SR, FSM_CONTROLLER_CREATOR, FSM_CS_CONTROLLER_CREATOR, HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_name(), HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, port_o::IN, LIBRARY_STD, port_o::OUT, DesignFlowStep::parameters, port_o_K, PRINT_DBG_MEX, memory::propagate_memory_parameters(), hls::registered_done_port, RESET_PORT_NAME, resize_controller_parallel(), structural_object::set_black_box(), structural_object::set_owner(), structural_manager::set_top_info(), top_entity::SM, START_PORT_NAME, SUCCESS, THROW_ASSERT, and hls::top.
resize_controller_parallel()
void top_entity_parallel_cs::resize_controller_parallel (structural_objectRef controller_circuit, unsigned loopBW) [protected]
resize_controller_parallel
Parameters
controller_circuit
Definition at line 329 of file top_entity_parallel_cs.cpp.
References DONE_PORT_NAME, DONE_REQUEST, structural_object::find_member(), DesignFlowStep::parameters, port_o_K, port_vector_o_K, START_PORT_NAME, and STR.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/top_entity_parallel_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/top_entity_parallel_cs.cpp