Quartus13Wrapper Class Reference
#include <quartus_13_wrapper.hpp>
Public Member Functions
Quartus13Wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~Quartus13Wrapper () override
Destructor.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Additional Inherited Members
Detailed Description
Definition at line 52 of file quartus_13_wrapper.hpp.
Constructor & Destructor Documentation
Quartus13Wrapper()
Quartus13Wrapper::Quartus13Wrapper (const ParameterConstRef & _Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Header include.
Parameters
Param is the set of parameters
output_dir is the directory where to save all the results
Autoheader include wrapper/synthesis include
Definition at line 52 of file quartus_13_wrapper.cpp.
References ~Quartus13Wrapper().
 Quartus13Wrapper()
Quartus13Wrapper::~Quartus13Wrapper () [override], [default]
Destructor.
Referenced by Quartus13Wrapper().
Member Function Documentation
get_command_line()
std::string Quartus13Wrapper::get_command_line (const DesignParametersRef & dp) const [override], [virtual]
Returns the proper command line.
Implements AlteraWrapper.
Definition at line 57 of file quartus_13_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, AlteraWrapper::toString(), and SynthesisTool::xml_tool_options.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_13_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_13_wrapper.cpp