OpGraph Struct Reference
Class used to describe a particular graph with operations as nodes.
#include <op_graph.hpp>
Public Member Functions
OpGraph (const OpGraphsCollectionRef g, int selector)
Standard constructor.
OpGraph (const OpGraphsCollectionRef g, int selector, const CustomUnorderedSet< boost::graph_traits< OpGraphsCollection >::vertex_descriptor > &sub)
Sub-graph constructor.
~OpGraph () override
Destructor.
void WriteDot (const std::string &file_name, const int detail_level=0) const
Writes this graph in dot format.
OpNodeInfoRef GetOpNodeInfo (const vertex node)
Returns the info associated with a node.
const OpNodeInfoConstRef CGetOpNodeInfo (const vertex node) const
Returns the info associated with a node.
const OpEdgeInfoConstRef CGetOpEdgeInfo (const EdgeDescriptor edge) const
Returns the info associated with an edge.
OpGraphInfoRef GetOpGraphInfo ()
Returns the property associated with the graph.
const OpGraphInfoConstRef CGetOpGraphInfo () const
Returns the property associated with the graph.
OpGraphInfoRef CGetOpGraphInfo ()
Returns the property associated with the graph.
CustomUnorderedMap< vertex, OpVertexSet > GetSrcVertices (const OpVertexSet &toCheck, int edgeType) const
Given a set of vertices, this function computes the edges which have the target in the set and the source outside: these edges are returned in the form vertex,vertex.
const OpVertexSet CGetOperations () const
Return the vertices belonging to the graph.
OpEdgeSet CGetInEdges (const vertex v) const
Return the edge ingoing in a vertex.
OpEdgeSet CGetOutEdges (const vertex v) const
Return the edge outgoing from a vertex.
Friends
class Schedule
Friend declaration of schedule to allow dot writing.
Additional Inherited Members
Detailed Description
Class used to describe a particular graph with operations as nodes.
Definition at line 788 of file op_graph.hpp.
Constructor & Destructor Documentation
OpGraph() [1/2]
OpGraph::OpGraph (const OpGraphsCollectionRef g, int selector)
Standard constructor.
Parameters
g is the bulk graph.
selector is the selector used to filter the bulk graph.
Definition at line 292 of file op_graph.cpp.
OpGraph() [2/2]
OpGraph::OpGraph (const OpGraphsCollectionRef g, int selector, const CustomUnorderedSet< boost::graph_traits< OpGraphsCollection >::vertex_descriptor > & sub)
Sub-graph constructor.
Parameters
g is the bulk graph.
selector is the selector used to filter the bulk graph.
sub is the set of vertices on which the graph is filtered.
Definition at line 296 of file op_graph.cpp.
References ~OpGraph().
 OpGraph()
OpGraph::~OpGraph () [override], [default]
Destructor.
Referenced by OpGraph().
Member Function Documentation
CGetInEdges()
OpEdgeSet OpGraph::CGetInEdges (const vertex v) const
Return the edge ingoing in a vertex.
Parameters
v is the vertex
Definition at line 352 of file op_graph.cpp.
References CGetOutEdges().
Referenced by CGetOperations(), VcdSignalSelection::DetectInvalidReturns(), and cdfc_module_binding::update_slack_starting_time().
CGetOpEdgeInfo()
const OpEdgeInfoConstRef OpGraph::CGetOpEdgeInfo (const EdgeDescriptor edge) const [inline]
Returns the info associated with an edge.
Parameters
edge is the edge to be analyzed
Returns
the associated property
Definition at line 856 of file op_graph.hpp.
References graph::CGetEdgeInfo().
CGetOperations()
const OpVertexSet OpGraph::CGetOperations () const
Return the vertices belonging to the graph.
Definition at line 340 of file op_graph.cpp.
References CGetInEdges(), and graph::collection.
Referenced by easy_module_binding::InternalExec(), and cdfc_module_binding::InternalExec().
CGetOpGraphInfo() [1/2]
const OpGraphInfoConstRef OpGraph::CGetOpGraphInfo () const [inline]
Returns the property associated with the graph.
Returns
the graph property
Definition at line 874 of file op_graph.hpp.
Referenced by CGetOutEdges(), VcdSignalSelection::CrossPropagateAddrSsa(), VcdSignalSelection::DetectInvalidReturns(), HWCallPathCalculator::examine_edge(), parametric_list_based::exec(), OpOrderComputation::InternalExec(), AddOpPhiFlowEdges::InternalExec(), VarComputation::RecursivelyAnalyze(), Schedule::WriteDot(), StateTransitionGraph::WriteDot(), and WriteDot().
CGetOpGraphInfo() [2/2]
OpGraphInfoRef OpGraph::CGetOpGraphInfo () [inline]
Returns the property associated with the graph.
Returns
the graph property
Definition at line 883 of file op_graph.hpp.
CGetOpNodeInfo()
const OpNodeInfoConstRef OpGraph::CGetOpNodeInfo (const vertex node) const [inline]
Returns the info associated with a node.
Parameters
node is the operation to be considered
Returns
the associated property
Definition at line 846 of file op_graph.hpp.
References graph::CGetNodeInfo().
Referenced by conn_binding::add_command_ports(), ASLAP::add_constraints_to_ALAP(), ASLAP::add_constraints_to_ASAP(), fu_binding::add_to_SM(), SDCScheduling::AddDelayConstraints(), mux_connection_binding::address_precision(), fu_binding::bind(), cdfc_module_binding::can_be_clustered(), AllocationInformation::can_implement_set(), Schedule::CanBeMoved(), BB_based_stg::compute_EPP_edge_increments(), parametric_list_based::compute_exec_stage_time(), CWriter::compute_phi_nodes(), parametric_list_based::compute_starting_ending_time_alap(), parametric_list_based::compute_starting_ending_time_asap(), BB_based_stg::compute_use_def(), CBackend::compute_variables(), Schedule::ComputeCriticalPath(), mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), mux_connection_binding::create_single_conn(), fsm_controller::create_state_machine(), VcdSignalSelection::CrossPropagateAddrSsa(), CWriter::declare_cast_types(), VcdSignalSelection::DetectInvalidReturns(), mux_connection_binding::determine_connection(), p_update_check::discover_vertex(), parametric_list_based::do_balanced_scheduling(), parametric_list_based::do_balanced_scheduling1(), parametric_list_based::exec(), fu_binding::get(), fu_binding::get_assign(), AllocationInformation::get_attribute_of_fu_per_op(), CallGraphManager::get_called_by(), StorageValueInformation::get_compatibility_weight(), Schedule::get_cstep(), Schedule::get_cstep_end(), AllocationInformation::get_cycles(), AllocationInformation::get_execution_time(), fsm_controller::get_guard_value(), fu_binding::get_index(), AllocationInformation::get_initiation_time(), prettyPrintVertex::get_internal_vars(), application_manager::get_produced_value(), HLS_manager::get_required_values(), AllocationInformation::get_stage_period(), CWriter::GetLocalVariables(), AllocationInformation::GetNodeTypePrec(), StorageValueInformation::Initialize(), cdfc_module_binding::initialize_connection_relation(), OmpAllocation::IntegrateTechnologyLibraries(), FSM_NI_SSA_liveness::InternalExec(), mem_dominator_allocation::InternalExec(), BB_based_stg::InternalExec(), easy_module_binding::InternalExec(), AddArtificialCallFlowEdges::InternalExec(), AddOpPhiFlowEdges::InternalExec(), AddOpExitFlowEdges::InternalExec(), VarComputation::InternalExec(), port_swapping::InternalExec(), SDCScheduling::InternalExec(), allocation::InternalExec(), cdfc_module_binding::InternalExec(), fu_binding::is_assigned(), BB_based_stg::is_instantaneous_operation(), AllocationInformation::is_operation_bounded(), AllocationInformation::is_operation_PI_registered(), Schedule::is_scheduled(), AllocationInformation::is_vertex_bounded_with(), AllocationInformation::max_number_of_resources(), AllocationInformation::min_number_of_resources(), OpWriter::operator()(), fu_binding::operator[](), BB_based_stg::optimize_cycles(), Schedule::print(), BehavioralHelper::print_vertex(), VcdSignalSelection::PropagateAddrParamToSsa(), VcdSignalSelection::SelectInitialSsa(), VcdSignalSelection::SelectInternalSignals(), Schedule::set_execution(), Schedule::set_execution_end(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), parametric_list_based::store_in_chaining_with_load_in(), parametric_list_based::store_in_chaining_with_load_out(), mux_connection_binding::swap_p(), cdfc_module_binding::weight_computation(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), DiscrepancyAnalysisCWriter::writePreInstructionInfo(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
CGetOutEdges()
OpEdgeSet OpGraph::CGetOutEdges (const vertex v) const
Return the edge outgoing from a vertex.
Parameters
v is the vertex
Definition at line 371 of file op_graph.cpp.
References CGetOpGraphInfo(), graph::collection, test_panda::full_name, BehavioralHelper::get_function_name(), graphs_collection::parameters, and WriteDot().
Referenced by CGetInEdges(), and cdfc_module_binding::update_slack_starting_time().
GetOpGraphInfo()
OpGraphInfoRef OpGraph::GetOpGraphInfo () [inline]
Returns the property associated with the graph.
Returns
the property associated with the graph
Definition at line 865 of file op_graph.hpp.
GetOpNodeInfo()
OpNodeInfoRef OpGraph::GetOpNodeInfo (const vertex node) [inline]
Returns the info associated with a node.
Parameters
node is the operation to be considered
Returns
the associated property
Definition at line 836 of file op_graph.hpp.
References graph::GetNodeInfo().
GetSrcVertices()
CustomUnorderedMap< vertex, OpVertexSet > OpGraph::GetSrcVertices (const OpVertexSet & toCheck, int edgeType) const
Given a set of vertices, this function computes the edges which have the target in the set and the source outside: these edges are returned in the form vertex,vertex.
Actually the map returned is indexed by the source vertex and contains the set of vertices, inside toCheck, which are targets of the edges starting from the vertex key of the map.
Parameters
toCheck is the set of vertices to be considered as taarget
edgeType is the type of edges to be considered
Definition at line 314 of file op_graph.cpp.
References graph::GetSelector().
WriteDot()
void OpGraph::WriteDot (const std::string & file_name, const int detail_level = 0) const
Writes this graph in dot format.
Parameters
file_name is the file where the graph has to be printed
detail_level is the detail level of the printed graph
Definition at line 302 of file op_graph.cpp.
References CGetOpGraphInfo(), graph::collection, test_panda::full_name, BehavioralHelper::get_function_name(), and graphs_collection::parameters.
Referenced by CGetOutEdges(), and SDCScheduling::InternalExec().
Friends And Related Function Documentation
Schedule
friend class Schedule [friend]
Friend declaration of schedule to allow dot writing.
Definition at line 791 of file op_graph.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.cpp