/home/osboxes/bambu/PandA-bambu/src/technology/parse_technology.hpp File Reference
Input and output functions used to read and write the technology data structures.
#include `config_HAVE_BOOLEAN_PARSER_BUILT.hpp`
#include `config_HAVE_EXPERIMENTAL.hpp`
#include `config_HAVE_FROM_LIBERTY.hpp`
#include `config_HAVE_PHYSICAL_LIBRARY_MODELS_BUILT.hpp`
#include `refcount.hpp`
#include `custom_set.hpp`
#include <string>
#include `target_device.hpp`
Functions
void read_technology_File (const std::string &f, const technology_managerRef &TM, const ParameterConstRef &Param, const target_deviceRef &device)
Read an xml file describing the technology data structures.
void read_technology_library (const technology_managerRef &TM, const ParameterConstRef &param, const target_deviceRef &device)
Read and update a library or a set of libraries based on the parameter options.
void write_xml_technology_File (const std::string &f, library_manager *LM, TargetDevice_Type dv_type)
Write an xml file describing a single library.
void write_technology_File (unsigned int type, const std::string &f, const technology_managerRef &TM, TargetDevice_Type dv_type, const CustomOrderedSet< std::string > &libraries=CustomOrderedSet< std::string >())
Write a file describing the technology data structures.
 forward declarations
Autoheader include
CONSTREF_FORWARD_DECL (technology_manager)
RefCount type definition of the technology_manager class structure.
REF_FORWARD_DECL (technology_manager)
CONSTREF_FORWARD_DECL (Parameter)
REF_FORWARD_DECL (target_device)
Detailed Description
Input and output functions used to read and write the technology data structures.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$
Warning
This file is still in a work in progress state
Last modified by $Author$
Function Documentation
CONSTREF_FORWARD_DECL() [1/2]
CONSTREF_FORWARD_DECL (technology_manager)
RefCount type definition of the technology_manager class structure.
CONSTREF_FORWARD_DECL() [2/2]
CONSTREF_FORWARD_DECL (Parameter)
read_technology_File()
void read_technology_File (const std::string & fn, const technology_managerRef & TM, const ParameterConstRef & Param, const target_deviceRef & device)
Read an xml file describing the technology data structures.
Parameters
f the input file name
TM is the initial technology manager.
Returns
the technology manager.
Read an xml file describing the technology data structures.
STL include utility include FIXME: setting paraemeters
Definition at line 88 of file parse_technology.cpp.
References DESIGN, XMLDomParser::Exec(), refcount< T >::get(), XMLDomParser::get_document(), technology_manager::get_library_list(), test_panda::parser, PROXY_LIBRARY, THROW_ERROR, WORK_LIBRARY, and technology_manager::xload().
Referenced by LoadFileTechnology::Exec(), and read_technology_library().
read_technology_library()
void read_technology_library (const technology_managerRef & TM, const ParameterConstRef & param, const target_deviceRef & device)
Read and update a library or a set of libraries based on the parameter options.
Parameters
TM is the technology manager.
Param is the class containing all the parameters
Definition at line 140 of file parse_technology.cpp.
References DEBUG_LEVEL_VERBOSE, fileIO_istream_open(), refcount< T >::get(), technology_manager::get_library_manager(), GetLeafFileName(), technology_manager::is_library_manager(), OUTPUT_LEVEL_MINIMUM, print_cpu_time(), PRINT_DBG_MEX, PRINT_OUT_MEX, read_technology_File(), library_manager::set_info(), SplitString(), START_TIME, STOP_TIME, THROW_ERROR, write_technology_File(), and technology_manager::XML.
Referenced by main().
REF_FORWARD_DECL() [1/2]
REF_FORWARD_DECL (technology_manager)
REF_FORWARD_DECL() [2/2]
REF_FORWARD_DECL (target_device)
write_technology_File()
void write_technology_File (unsigned int type, const std::string & f, const technology_managerRef & TM, TargetDevice_Type dv_type, const CustomOrderedSet< std::string > & libraries = CustomOrderedSet< std::string >())
Write a file describing the technology data structures.
Parameters
f the output file name
TM is the technology manager.
libraries names of the libraries to dump. If empty or not given, it dumps all libraries
Definition at line 334 of file parse_technology.cpp.
References technology_manager::LEF, technology_manager::LIB, THROW_UNREACHABLE, and technology_manager::XML.
Referenced by read_technology_library().
write_xml_technology_File()
void write_xml_technology_File (const std::string & f, library_manager * LM, TargetDevice_Type dv_type)
Write an xml file describing a single library.
Parameters
f the output file name
LM is the pointer to the library to be written
Definition at line 397 of file parse_technology.cpp.
References xml_document::create_root_node(), DESIGN, PROXY_LIBRARY, library_manager::set_info(), THROW_ERROR, THROW_WARNING, WORK_LIBRARY, xml_document::write_to_file_formatted(), write_xml_technology_File(), library_manager::XML, and library_manager::xwrite().
Referenced by library_manager::get_info(), write_technology_File(), and write_xml_technology_File().