type_casting Struct Reference
#include <type_casting.hpp>
Public Member Functions
type_casting (CustomUnorderedSet< unsigned int > &_types)
default constructor
void operator() (const mem_ref *obj, unsigned int &mask) override
Header include.
void operator() (const indirect_ref *obj, unsigned int &mask) override
Private Attributes
CustomUnorderedSet< unsigned int > & types
tree_node visitors
CustomUnorderedSet< unsigned int > visited
already visited
Detailed Description
Definition at line 73 of file type_casting.hpp.
Constructor & Destructor Documentation
type_casting()
type_casting::type_casting (CustomUnorderedSet< unsigned int > & _types) [inline], [explicit]
default constructor
Definition at line 76 of file type_casting.hpp.
References object_visitor::BOOST_PP_SEQ_FOR_EACH(), LOCAL_OBJ_NOT_SPECIALIZED_SEQ, OBJ_SPECIALIZED_SEQ, operator()(), OPERATOR_MACRO_DECLO, and OPERATOR_MACROO.
Member Function Documentation
operator()() [1/2]
void type_casting::operator() (const mem_ref * obj, unsigned int & mask) [override]
Header include.
Tree include
Definition at line 54 of file type_casting.cpp.
References GET_INDEX_NODE, NO_VISIT, types, and visited.
Referenced by operator()(), and type_casting().
operator()() [2/2]
void type_casting::operator() (const indirect_ref * obj, unsigned int & mask) [override]
Definition at line 67 of file type_casting.cpp.
References tree_helper::CGetType(), GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_node::index, NO_VISIT, unary_expr::op, operator()(), expr_node::type, types, and visited.
Field Documentation
types
CustomUnorderedSet<unsigned int>& type_casting::types [private]
tree_node visitors
set of types used in type casting
Definition at line 89 of file type_casting.hpp.
Referenced by operator()().
visited
CustomUnorderedSet<unsigned int> type_casting::visited [private]
already visited
Definition at line 92 of file type_casting.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/type_casting.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/type_casting.cpp