gimple_call Struct Reference
This struct specifies the gimple_call node.
#include <tree_node.hpp>
Public Types
enum { GETID =(gimple_node) = 0,
GETID =(gimple_node) = 0,
GETID =(gimple_node) = 0
 }
visitor enum
Public Member Functions
gimple_call (unsigned int i)
constructor
void AddArg (const tree_nodeRef &arg)
Add an argument to the list of arguments.
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
tree_nodeRef fn
fn is the operand 0 of the call expression: this is the function
std::vector< tree_nodeRef > args
The arguments of the gimple_call.
Additional Inherited Members
Detailed Description
This struct specifies the gimple_call node.
Function call. Operand 0 is the function. Operand 1 is the argument list, a list of expressions made out of a chain of TREE_LIST nodes. Operand 2 is the static chain argument, or NULL. The tree walker structure of this node is: #(TOK_GIMPLE_CALL type fn (args)?)
Definition at line 1966 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
GETID
GETID
Definition at line 1996 of file tree_node.hpp.
Constructor & Destructor Documentation
gimple_call()
gimple_call::gimple_call (unsigned int i) [explicit]
constructor
Definition at line 585 of file tree_node.cpp.
Member Function Documentation
AddArg()
void gimple_call::AddArg (const tree_nodeRef & arg)
Add an argument to the list of arguments.
Parameters
arg is the argument to be added
Definition at line 598 of file tree_node.cpp.
References args.
visit()
void gimple_call::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from gimple_node.
Definition at line 589 of file tree_node.cpp.
References ALL_VISIT, args, fn, SEQ_VISIT_MEMBER, VISIT_MEMBER, and VISIT_SC.
Referenced by case_label_expr::visit(), cast_expr::visit(), complex_cst::visit(), complex_type::visit(), gimple_cond::visit(), const_decl::visit(), constructor::visit(), enumeral_type::visit(), expr_stmt::visit(), and field_decl::visit().
Field Documentation
args
std::vector<tree_nodeRef> gimple_call::args
The arguments of the gimple_call.
Definition at line 1975 of file tree_node.hpp.
Referenced by AddArg(), PragmaAnalysis::get_call_parameter(), GimpleWriter::GimpleWriter(), CallGraphBuiltinCall::lookForBuiltinCall(), hls_div_cg_ext::recursive_examinate(), VarDeclFix::recursive_examinate(), CheckSystemType::recursive_examinate(), soft_float_cg_ext::RecursiveExaminate(), visit(), and raw_writer::write_when_not_null_point_to().
fn
tree_nodeRef gimple_call::fn
fn is the operand 0 of the call expression: this is the function
Definition at line 1972 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), CallGraphBuiltinCall::lookForBuiltinCall(), CheckSystemType::recursive_examinate(), visit(), and raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp