ssa_name Struct Reference
This struct specifies the ssa_name node.
#include <tree_node.hpp>
Public Types
enum {
GETID =(tree_node) = 0,
GETID =(tree_node) = 0,
GETID =(tree_node) = 0,
GETID =(tree_node) = 0,
GETID =(tree_node) = 0,
GETID =(tree_node) = 0,
GETID =(tree_node) = 0
 }
visitor enum
Public Member Functions
ssa_name (unsigned int i)
constructor
void AddUseStmt (const tree_nodeRef &use_stmt)
Add use of this ssa.
const TreeNodeMap< size_t > & CGetUseStmts () const
Return the use stmts.
size_t CGetNumberUses () const
Return the number of uses.
void RemoveUse (const tree_nodeRef &use_stmt)
Remove a use of this ssa.
void SetDefStmt (const tree_nodeRef &def)
Set the def stmt erasing the old definitions.
void AddDefStmt (const tree_nodeRef &def)
Add a def stmt.
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
const tree_nodeRef CGetDefStmt () const
Return the def stmt (checking that is unique)
const TreeNodeSet CGetDefStmts () const
Return the set of definition statements.
Data Fields
tree_nodeRef type
starting from gcc 4.7.2 ssa_name has a type
tree_nodeRef var
var is the variable being referenced (macro SSA_NAME_VAR).
unsigned int vers
vers is the SSA version number of this SSA name.(macro SSA_NAME_VERSION). Note that in tree SSA, version numbers are not per variable and may be recycled
unsigned int orig_vers
original SSA version number from GCC
bool volatile_flag
in case a ssa_name is never defined this boolean member is true
bool virtual_flag
flag for virtual ssa
bool default_flag
Nonzero if this SSA_NAME is the default definition for the underlying symbol.
tree_nodeRef min
minimum values this ssa may reach
tree_nodeRef max
maximum values this ssa may reach
std::string bit_values
for each bit of the ssa variable tells if it is equal to U,X,0,1
PointToSolutionRef use_set
point to solution
const PointToInformationRef point_to_information
PointToInformation associated with this ssa_name if the corresponding variable is a pointer.
Private Attributes
TreeNodeMap< size_t > use_stmts
The uses of this ssa: it is a map since the same ssa can be used multiple times in the same statement Key is the index of the tree node instad of tree node because in this way gimple_node can updated uses of a ssa without using the tree manager to get the tree reindex of itself.
TreeNodeSet def_stmts
in case ssa_name is not volatile the statement which defines it; statements could be more than one because of gimple_phi splitting
Additional Inherited Members
Detailed Description
This struct specifies the ssa_name node.
Variable references for SSA analysis. New SSA names are created every time a variable is assigned a new value. The SSA builder uses SSA_NAME nodes to implement SSA versioning. The tree walker structure of this node is: #(TOK_SSA_NAME var vers)
Definition at line 4506 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
GETID
GETID
GETID
GETID
GETID
GETID
Definition at line 4624 of file tree_node.hpp.
Constructor & Destructor Documentation
ssa_name()
ssa_name::ssa_name (unsigned int i) [explicit]
constructor
Definition at line 1165 of file tree_node.cpp.
Member Function Documentation
AddDefStmt()
void ssa_name::AddDefStmt (const tree_nodeRef & def)
Add a def stmt.
Parameters
def is a def statement.
Definition at line 1210 of file tree_node.cpp.
References def_stmts.
AddUseStmt()
void ssa_name::AddUseStmt (const tree_nodeRef & use_stmt)
Add use of this ssa.
Parameters
statement is the statement which used this ssa
Definition at line 1205 of file tree_node.cpp.
References use_stmts.
CGetDefStmt()
const tree_nodeRef ssa_name::CGetDefStmt () const
Return the def stmt (checking that is unique)
Returns
the definition statement
Definition at line 1182 of file tree_node.cpp.
References def_stmts, STR, THROW_ASSERT, THROW_UNREACHABLE, and tree_node::ToString().
CGetDefStmts()
const TreeNodeSet ssa_name::CGetDefStmts () const
Return the set of definition statements.
Returns
the definition statements
Definition at line 1200 of file tree_node.cpp.
References def_stmts.
Referenced by dead_code_elimination::InternalExec(), simple_code_motion::InternalExec(), and raw_writer::write_when_not_null_point_to().
CGetNumberUses()
size_t ssa_name::CGetNumberUses () const
Return the number of uses.
Returns
the number of uses
Definition at line 1226 of file tree_node.cpp.
References use_stmts.
Referenced by dead_code_elimination::InternalExec().
CGetUseStmts()
const TreeNodeMap< size_t > & ssa_name::CGetUseStmts () const
Return the use stmts.
Returns
the use stmts
Definition at line 1221 of file tree_node.cpp.
References use_stmts.
Referenced by Bit_Value::backward_compute_result_from_uses(), interface_infer::classifyArgRecurse(), dead_code_elimination::InternalExec(), and raw_writer::write_when_not_null_point_to().
RemoveUse()
void ssa_name::RemoveUse (const tree_nodeRef & use_stmt)
Remove a use of this ssa.
Parameters
use_stmt is the statement which uses this ssa
Definition at line 1236 of file tree_node.cpp.
References INDENT_DBG_MEX, STR, THROW_UNREACHABLE, tree_node::ToString(), and use_stmts.
SetDefStmt()
void ssa_name::SetDefStmt (const tree_nodeRef & def)
Set the def stmt erasing the old definitions.
Parameters
a is a def statement.
Definition at line 1215 of file tree_node.cpp.
References def_stmts.
Referenced by HWCallInjection::buildBuiltinCall().
visit()
void ssa_name::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from tree_node.
Definition at line 1169 of file tree_node.cpp.
References ALL_VISIT, def_stmts, max, min, SEQ_VISIT_MEMBER, type, use_set, var, VISIT_MEMBER, and VISIT_SC.
Referenced by GimpleWriter::GimpleWriter(), statement_list::visit(), string_cst::visit(), gimple_switch::visit(), target_expr::visit(), template_decl::visit(), template_parm_index::visit(), tree_list::visit(), tree_vec::visit(), try_block::visit(), type_decl::visit(), union_type::visit(), and lut_expr::visit().
Field Documentation
bit_values
std::string ssa_name::bit_values
for each bit of the ssa variable tells if it is equal to U,X,0,1
Definition at line 4579 of file tree_node.hpp.
Referenced by constrainSSA(), and raw_writer::write_when_not_null_point_to().
def_stmts
TreeNodeSet ssa_name::def_stmts [private]
in case ssa_name is not volatile the statement which defines it; statements could be more than one because of gimple_phi splitting
Definition at line 4515 of file tree_node.hpp.
Referenced by AddDefStmt(), CGetDefStmt(), CGetDefStmts(), SetDefStmt(), and visit().
default_flag
bool ssa_name::default_flag
Nonzero if this SSA_NAME is the default definition for the underlying symbol.
A default SSA name is created for symbol S if the very first reference to S in the function is a read operation. Default definitions are always created by an empty statement and belong to no basic block.
Definition at line 4546 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), and raw_writer::write_when_not_null_point_to().
max
tree_nodeRef ssa_name::max
maximum values this ssa may reach
Definition at line 4576 of file tree_node.hpp.
Referenced by constrainSSA(), visit(), and raw_writer::write_when_not_null_point_to().
min
tree_nodeRef ssa_name::min
minimum values this ssa may reach
Definition at line 4573 of file tree_node.hpp.
Referenced by constrainSSA(), visit(), and raw_writer::write_when_not_null_point_to().
orig_vers
unsigned int ssa_name::orig_vers
original SSA version number from GCC
Definition at line 4531 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), and raw_writer::write_when_not_null_point_to().
point_to_information
const PointToInformationRef ssa_name::point_to_information
PointToInformation associated with this ssa_name if the corresponding variable is a pointer.
Definition at line 4585 of file tree_node.hpp.
type
tree_nodeRef ssa_name::type
starting from gcc 4.7.2 ssa_name has a type
Definition at line 4522 of file tree_node.hpp.
Referenced by constrainSSA(), GimpleWriter::GimpleWriter(), CheckSystemType::recursive_examinate(), visit(), template_parm_index::visit(), and raw_writer::write_when_not_null_point_to().
use_set
PointToSolutionRef ssa_name::use_set
point to solution
Definition at line 4582 of file tree_node.hpp.
Referenced by visit(), and raw_writer::write_when_not_null_point_to().
use_stmts
TreeNodeMap<size_t> ssa_name::use_stmts [private]
The uses of this ssa: it is a map since the same ssa can be used multiple times in the same statement Key is the index of the tree node instad of tree node because in this way gimple_node can updated uses of a ssa without using the tree manager to get the tree reindex of itself.
Definition at line 4512 of file tree_node.hpp.
Referenced by AddUseStmt(), CGetNumberUses(), CGetUseStmts(), and RemoveUse().
var
tree_nodeRef ssa_name::var
var is the variable being referenced (macro SSA_NAME_VAR).
Definition at line 4525 of file tree_node.hpp.
Referenced by interface_infer::classifyArgRecurse(), GimpleWriter::GimpleWriter(), VarDeclFix::recursive_examinate(), CheckSystemType::recursive_examinate(), visit(), and raw_writer::write_when_not_null_point_to().
vers
unsigned int ssa_name::vers
vers is the SSA version number of this SSA name.(macro SSA_NAME_VERSION). Note that in tree SSA, version numbers are not per variable and may be recycled
Definition at line 4528 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), and raw_writer::write_when_not_null_point_to().
virtual_flag
bool ssa_name::virtual_flag
flag for virtual ssa
Definition at line 4537 of file tree_node.hpp.
Referenced by dead_code_elimination::InternalExec(), simple_code_motion::InternalExec(), and raw_writer::write_when_not_null_point_to().
volatile_flag
bool ssa_name::volatile_flag
in case a ssa_name is never defined this boolean member is true
Definition at line 4534 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp