tree_node_index_factory Struct Reference
#include <tree_nodes_merger.hpp>
Public Member Functions
tree_node_index_factory (CustomUnorderedMapUnstable< unsigned int, unsigned int > &_remap, const tree_managerRef _TM)
default constructor
void create_tree_node (const unsigned int node_id, const tree_nodeRef &tn)
tree_node visitors
Private Attributes
CustomUnorderedMapUnstable< unsigned int, unsigned int > & remap
remap old indexes in new indexes
const tree_managerRef TM
tree manager
tree_node * curr_tree_node_ptr
current tree node filled according to the tree_node_schema
bloc * curr_bloc
current basic block pointer
tree_nodeRef source_tn
current tree_node source
blocRef source_bloc
current basic block source
Detailed Description
Definition at line 82 of file tree_nodes_merger.hpp.
Constructor & Destructor Documentation
tree_node_index_factory()
tree_node_index_factory::tree_node_index_factory (CustomUnorderedMapUnstable< unsigned int, unsigned int > & _remap, const tree_managerRef _TM) [inline]
default constructor
Definition at line 85 of file tree_nodes_merger.hpp.
References object_visitor::BOOST_PP_SEQ_FOR_EACH(), OBJ_NOT_SPECIALIZED_SEQ, OBJ_SPECIALIZED_SEQ, OPERATOR_MACRO, and OPERATOR_MACRO_DECL.
Member Function Documentation
create_tree_node()
void tree_node_index_factory::create_tree_node (const unsigned int node_id, const tree_nodeRef & tn)
tree_node visitors
Factory method. It creates a tree_node of type equal to the type of tn where all the fields are remapped according the remap relation passed to the constructor
Parameters
node_id is the node id of the created object.
tn is the starting tree node
special care is reserved for identifier_nodes
Definition at line 880 of file tree_nodes_merger.cpp.
References ATTR_MACRO, ATTR_SEQ, object_visitor::BOOST_PP_SEQ_FOR_EACH(), CREATE_TREE_NODE_CASE_BODY, refcount< T >::get(), tree_node::get_kind(), tree_node::get_kind_text(), template_id_expr(), THROW_ASSERT, THROW_ERROR, tree_node_reached::TM, typename_type(), and using_decl().
Referenced by tree_manager::merge_tree_managers().
Field Documentation
curr_bloc
bloc* tree_node_index_factory::curr_bloc [private]
current basic block pointer
Definition at line 110 of file tree_nodes_merger.hpp.
curr_tree_node_ptr
tree_node* tree_node_index_factory::curr_tree_node_ptr [private]
current tree node filled according to the tree_node_schema
Definition at line 108 of file tree_nodes_merger.hpp.
remap
CustomUnorderedMapUnstable<unsigned int, unsigned int>& tree_node_index_factory::remap [private]
remap old indexes in new indexes
Definition at line 102 of file tree_nodes_merger.hpp.
source_bloc
blocRef tree_node_index_factory::source_bloc [private]
current basic block source
Definition at line 114 of file tree_nodes_merger.hpp.
source_tn
tree_nodeRef tree_node_index_factory::source_tn [private]
current tree_node source
Definition at line 112 of file tree_nodes_merger.hpp.
TM
const tree_managerRef tree_node_index_factory::TM [private]
tree manager
Definition at line 105 of file tree_nodes_merger.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_nodes_merger.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_nodes_merger.cpp