operations_cfg_computation Class Reference
Compute the control flow graph for the operations.
#include <operations_cfg_computation.hpp>
Public Member Functions
operations_cfg_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~operations_cfg_computation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes the operations CFG graph data structure.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
std::string get_first_node (const tree_nodeRef &tn, const std::string &f_name) const
Return the name of the first node given a tree node.
void clean_start_nodes ()
Clean the list of start nodes.
void insert_start_node (const std::string &start_node)
Insert a start node to the list of start nodes.
bool empty_start_nodes () const
Return true if start_node is empty.
void init_start_nodes (const std::string &start_node)
Initialize the list of start nodes.
void connect_start_nodes (const operations_graph_constructorRef ogc, const std::string &next, bool true_edge=false, bool false_edge=false, unsigned int nodeid=0)
Connect start_node with the next node.
void build_operation_recursive (const tree_managerRef TM, const operations_graph_constructorRef ogc, const tree_nodeRef tn, const std::string &f_name, unsigned int bb_index)
Builds recursively the operation for a given tree node.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
unsigned int last_bb_cfg_computation_version
std::map< unsigned int, std::string > label_decl_map
relation between label declaration and first statement id
std::map< unsigned int, std::string > first_statement
relation between basic block and first statement id
std::list< std::string > start_nodes
store the name of the nodes at which the next node should be attached.
std::string actual_name
store the name of the current vertex
Additional Inherited Members
Detailed Description
Compute the control flow graph for the operations.
Definition at line 75 of file operations_cfg_computation.hpp.
Constructor & Destructor Documentation
operations_cfg_computation()
operations_cfg_computation::operations_cfg_computation (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
Header include Behavior include Design Flow include Graph include Parameter include parser/treegcc include Tree include
Definition at line 84 of file operations_cfg_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~operations_cfg_computation().
 operations_cfg_computation()
operations_cfg_computation::~operations_cfg_computation () [override], [default]
Destructor.
Referenced by operations_cfg_computation().
Member Function Documentation
build_operation_recursive()
void operations_cfg_computation::build_operation_recursive (const tree_managerRef TM, const operations_graph_constructorRef ogc, const tree_nodeRef tn, const std::string & f_name, unsigned int bb_index) [private]
Builds recursively the operation for a given tree node.
We assume a one to one mapping between nodeids and vertices
Parameters
TM is the tree manager.
ogc is the operation graph constructor used to add the vertices.
tn is the reference of the tree node we are currently analyzing
f_name is the name of the function which the node we are analyzing belongs to
Definition at line 485 of file operations_cfg_computation.cpp.
References actual_name, ASSIGN, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, connect_start_nodes(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, tree_helper::find_obj_type_ref_function(), FIX_TRUNC_EXPR, FLOAT_EXPR, FunctionFrontendFlowStep::function_behavior, get_first_node(), GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), INDENT_DBG_MEX, tree_node::index, tree_helper::is_a_nop_function_decl(), tree_helper::is_a_pointer(), tree_helper::is_a_vector(), tree_helper::is_an_array(), tree_helper::is_unsigned(), tree_helper::IsLoad(), tree_helper::IsStore(), MEMCPY, MEMSET, MULTI_READ_COND, NODE_NOT_YET_SUPPORTED_EC, NOP, tree_helper::normalized_ID(), unary_expr::op, binary_expr::op0, ternary_expr::op0, quaternary_expr::op0, binary_expr::op1, ternary_expr::op1, quaternary_expr::op1, ternary_expr::op2, quaternary_expr::op2, quaternary_expr::op3, phi, PRINT_DBG_MEX, tree_helper::print_function_name(), READ_COND, tree_helper::size(), STR, SWITCH_COND, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, TYPE_ASSIGN, TYPE_ATOMIC, TYPE_EXTERNAL, TYPE_FOR, TYPE_GENERIC, TYPE_GOTO, TYPE_IF, TYPE_INIT, TYPE_LABEL, TYPE_LAST_OP, TYPE_LOAD, TYPE_MEMCPY, TYPE_MULTIIF, TYPE_NOP, TYPE_OPAQUE, TYPE_PHI, TYPE_PREDICATED, TYPE_RET, TYPE_STORE, TYPE_SWITCH, TYPE_VPHI, TYPE_WAS_GIMPLE_PHI, TYPE_WHILE, and VECT_CONCATENATION.
Referenced by InternalExec().
clean_start_nodes()
void operations_cfg_computation::clean_start_nodes () [private]
Clean the list of start nodes.
Definition at line 442 of file operations_cfg_computation.cpp.
References start_nodes.
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > operations_cfg_computation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 92 of file operations_cfg_computation.cpp.
References BB_FEEDBACK_EDGES_IDENTIFICATION, BUILD_VIRTUAL_PHI, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
connect_start_nodes()
void operations_cfg_computation::connect_start_nodes (const operations_graph_constructorRef ogc, const std::string & next, bool true_edge = false, bool false_edge = false, unsigned int nodeid = 0) [private]
Connect start_node with the next node.
Parameters
ogc is the operation graph constructor used to add the edges.
next is the ending node of the edge that must be added to g.
true_edge when it is true the control edge is the true branch of an if then else statement.
false_edge when it is true the control edge is the false branch of an if then else statement.
nodeid is meaningful only in case true_edge and false_edge are both true and the control edge is associated with a switch statement.
Mark first operation of the application
Definition at line 458 of file operations_cfg_computation.cpp.
References FrontendFlowStep::AppM, CFG_SELECTOR, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, ENTRY, F_COND, FunctionFrontendFlowStep::function_id, INDENT_DBG_MEX, start_nodes, T_COND, and TYPE_FIRST_OP.
Referenced by build_operation_recursive(), and InternalExec().
empty_start_nodes()
bool operations_cfg_computation::empty_start_nodes () const [private]
Return true if start_node is empty.
Returns
true if start node is empty
Definition at line 447 of file operations_cfg_computation.cpp.
References start_nodes.
Referenced by InternalExec().
get_first_node()
std::string operations_cfg_computation::get_first_node (const tree_nodeRef & tn, const std::string & f_name) const [private]
Return the name of the first node given a tree node.
Parameters
tn is the tree node.
f_name is the name of the function of the node we are analyzing
Returns
the name of the first node
Definition at line 380 of file operations_cfg_computation.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, label_decl_map, NODE_NOT_YET_SUPPORTED_EC, THROW_ASSERT, and THROW_ERROR_CODE.
Referenced by build_operation_recursive(), and InternalExec().
init_start_nodes()
void operations_cfg_computation::init_start_nodes (const std::string & start_node) [private]
Initialize the list of start nodes.
Parameters
start_node is the starting node
Definition at line 452 of file operations_cfg_computation.cpp.
References start_nodes.
Referenced by InternalExec().
Initialize()
void operations_cfg_computation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 138 of file operations_cfg_computation.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, FunctionBehavior::BB, FunctionFrontendFlowStep::bb_version, FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, BBGraph::GetBBNodeInfo(), last_bb_cfg_computation_version, Wrefcount< T >::lock(), and THROW_ASSERT.
insert_start_node()
void operations_cfg_computation::insert_start_node (const std::string & start_node) [private]
Insert a start node to the list of start nodes.
Parameters
start_node is the starting node
Definition at line 437 of file operations_cfg_computation.cpp.
References start_nodes.
InternalExec()
DesignFlowStep_Status operations_cfg_computation::InternalExec () [override], [virtual]
Computes the operations CFG graph data structure.
Returns
the exit status of this step
entry and exit computation
first cycle to compute the label_decl_map and the first_statement maps.
second cycle doing the real job
Implements FunctionFrontendFlowStep.
Definition at line 164 of file operations_cfg_computation.cpp.
References actual_name, FrontendFlowStep::AppM, BB_ENTRY, BB_EXIT, build_operation_recursive(), FunctionBehavior::CFG, BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), clean_start_nodes(), connect_start_nodes(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, empty_start_nodes(), ENTRY, EXIT, bloc::EXIT_BLOCK_ID, FunctionBehavior::FBB, first_statement, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, get_first_node(), BehavioralHelper::get_function_name(), GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, init_start_nodes(), label_decl_map, tree_manager::new_tree_node_id(), DesignFlowStep::parameters, phi, start_nodes, STR, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, TOK, TOK_SRCP, tree_node::ToString(), TYPE_ENTRY, TYPE_EXIT, and TYPE_LAST_OP.
Field Documentation
actual_name
std::string operations_cfg_computation::actual_name [private]
store the name of the current vertex
Definition at line 90 of file operations_cfg_computation.hpp.
Referenced by build_operation_recursive(), and InternalExec().
first_statement
std::map<unsigned int, std::string> operations_cfg_computation::first_statement [private]
relation between basic block and first statement id
Definition at line 84 of file operations_cfg_computation.hpp.
Referenced by InternalExec().
label_decl_map
std::map<unsigned int, std::string> operations_cfg_computation::label_decl_map [private]
relation between label declaration and first statement id
Definition at line 81 of file operations_cfg_computation.hpp.
Referenced by get_first_node(), and InternalExec().
last_bb_cfg_computation_version
unsigned int operations_cfg_computation::last_bb_cfg_computation_version [private]
Definition at line 78 of file operations_cfg_computation.hpp.
Referenced by Initialize().
start_nodes
std::list<std::string> operations_cfg_computation::start_nodes [private]
store the name of the nodes at which the next node should be attached.
Definition at line 87 of file operations_cfg_computation.hpp.
Referenced by clean_start_nodes(), connect_start_nodes(), empty_start_nodes(), init_start_nodes(), insert_start_node(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/operations_cfg_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/operations_cfg_computation.cpp