HDLVarDeclFix Class Reference
Pre-analysis step.
#include <hdl_var_decl_fix.hpp>
Public Member Functions
HDLVarDeclFix (const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~HDLVarDeclFix () override
Destructor.
DesignFlowStep_Status InternalExec () override
Fixes the var_decl duplication.
Protected Member Functions
const std::string Normalize (const std::string &identifier) const override
Return the normalized identifier; in this class it is the identifier itself.
Protected Attributes
const HDLWriter_Language hdl_writer_type
The hdl language.
Additional Inherited Members
Detailed Description
Pre-analysis step.
It transforms the raw intermediate representation removing decl duplication (two decl_node with the same name in the same function) and hdl name conflicts (variable or parameters with same name of auxiliary signals
Definition at line 53 of file hdl_var_decl_fix.hpp.
Constructor & Destructor Documentation
HDLVarDeclFix()
HDLVarDeclFix::HDLVarDeclFix (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
fun_id is the function index
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior includes boost include design_flows/backend/ToHDL include HLS includes tree includes utility include
Definition at line 71 of file hdl_var_decl_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~HDLVarDeclFix().
 HDLVarDeclFix()
HDLVarDeclFix::~HDLVarDeclFix () [override], [default]
Destructor.
Referenced by HDLVarDeclFix().
Member Function Documentation
InternalExec()
DesignFlowStep_Status HDLVarDeclFix::InternalExec () [override], [virtual]
Fixes the var_decl duplication.
Returns
the exit status of this step
Preload backend names
a parameter cannot be named `this`
Add function name
Fixing names of parameters
Implements FunctionFrontendFlowStep.
Definition at line 79 of file hdl_var_decl_fix.cpp.
References VarDeclFix::already_examinated_names, FrontendFlowStep::AppM, test_panda::arg, language_writer::create_writer(), FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_mangled_fname(), GET_NODE, tree_manager::GetTreeNode(), hdl_writer_type, VarDeclFix::InternalExec(), Normalize(), DesignFlowStep::parameters, VarDeclFix::recursive_examinate(), SUCCESS, and THROW_ASSERT.
Normalize()
const std::string HDLVarDeclFix::Normalize (const std::string & identifier) const [override], [protected], [virtual]
Return the normalized identifier; in this class it is the identifier itself.
Subclasses can specialize it
Parameters
identifier is the identifier to be normalized
Returns
the normalized identifier
Reimplemented from VarDeclFix.
Definition at line 176 of file hdl_var_decl_fix.cpp.
References hdl_writer_type, and VHDL.
Referenced by InternalExec().
Field Documentation
hdl_writer_type
const HDLWriter_Language HDLVarDeclFix::hdl_writer_type [protected]
The hdl language.
Definition at line 57 of file hdl_var_decl_fix.hpp.
Referenced by InternalExec(), and Normalize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/hdl_var_decl_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/hdl_var_decl_fix.cpp