Parameter Class Reference
#include <Parameter.hpp>
Public Member Functions
Parameter (const std::string &program_name, int argc, char **const argv, int debug_level=0)
Constructor.
Parameter (const Parameter &other)
Copy Constructor.
virtual ~Parameter ()
Destructor.
void load_xml_configuration_file (const std::string &filename)
Loads an XML configuration file.
void write_xml_configuration_file (const std::string &filename)
Write an XML configuration file with the parameters actually stored.
virtual int Exec ()=0
Execute parameter parsing.
virtual void CheckParameters ()=0
Checks the compatibility among the different parameters and determines the implications.
template<typename G >
void getOption (const std::string &name, G &variable) const
Returns the value of an option.
template<typename G >
void getOption (const char *name, G &variable) const
Returns the value of an option.
template<typename G >
G getOption (const std::string &name) const
Returns the value of an option.
template<typename G >
G getOption (const char *name) const
Returns the value of an option.
template<typename G >
G getOption (const enum enum_option name) const
Returns the value of an option.
template<typename G >
void setOption (const std::string &name, const G value)
Sets the value of an option.
template<typename G >
void setOption (const char *name, const G value)
Sets the value of an option.
template<typename G >
void setOption (const enum enum_option name, const G value)
Sets the value of an option.
bool isOption (const std::string &name) const
Tests if an option has been stored.
bool isOption (const char *name) const
Tests if an option has been stored.
bool isOption (const enum enum_option name) const
Tests if an option has been stored.
bool removeOption (const enum enum_option name)
Remove an option.
bool removeOption (const char *name)
Remove an option.
bool removeOption (const std::string &name)
Remove an option.
int get_class_debug_level (const std::string &class_name, int debug_level=-1) const
Return the debug level for a specific class.
int GetFunctionDebugLevel (const std::string &class_name, const std::string &function_name) const
Return the debug_level of a function.
void print (std::ostream &os) const
void add_debug_class (const std::string &class_name)
Add a class to be debugged.
void PrintUsage (std::ostream &os) const
Print the usage of this tool = PrintHeader() + PrintHelp()
std::string PrintVersion () const
This function prints the version of the tool.
virtual void PrintFullHeader (std::ostream &os) const
This function prints the header of the tool = PrintProgramName() + PrintVersion()
void PrintBugReport (std::ostream &os) const
Print the bug report request.
Parameters_FileFormat GetFileFormat (const std::string &file, bool check_cml_root_node=false) const
Return the file format given the file name or the extension.
template<typename G >
G GetParameter (const std::string &name) const
Returns the value of a parameter.
bool IsParameter (const std::string &name) const
Return if a parameter has been set.
const std::vector< std::string > CGetArgv () const
Return argv.
template<>
const CustomSet< std::string > getOption (const enum enum_option name) const
template<>
const std::list< std::string > getOption (const enum enum_option name) const
template<>
Parameters_FileFormat getOption (const enum enum_option name) const
Protected Member Functions
void load_xml_configuration_file_rec (const xml_element *node)
Loads an XML configuration file (recursive method)
bool ManageDefaultOptions (int next_option, char *optarg_param, bool &exit_success)
Manage default options (common to all tools)
void PrintGeneralOptionsUsage (std::ostream &os) const
Print the usage of the general common options.
void PrintOutputOptionsUsage (std::ostream &os) const
Print the usage of the output common options.
virtual void SetDefaults ()=0
Sets the default values with respect to the tool.
void SetCommonDefaults ()
Sets the default values common to all tools.
virtual void PrintProgramName (std::ostream &os) const =0
Print the name of the program to be included in the header.
virtual void PrintHelp (std::ostream &os) const =0
Print the help.
Protected Attributes
int argc
The number of input paramters.
char **const argv
The input parameters;.
OptionMap Options
Map between the name of the option and the related string-form value.
CustomMap< std::string, std::string > panda_parameters
Map between the name of a parameter and the related string-form value.
std::map< enum enum_option, std::string > enum_options
Map between an enum option and the related string-form value.
std::map< enum enum_option, std::string > option_name
Name of the enum options.
CustomUnorderedSet< std::string > debug_classes
Classes to be debugged.
int debug_level
debug level
Friends
std::ostream & operator<< (std::ostream &os, const Parameter &s)
Friend definition of the << operator.
Detailed Description
Definition at line 334 of file Parameter.hpp.
Constructor & Destructor Documentation
Parameter() [1/2]
Parameter::Parameter (const std::string & program_name, int argc, char **const argv, int debug_level = 0)
Constructor.
Parameters
program_name is the name of the executable
argc is the number of arguments
argv is the array of arguments passed to program.
debug_level is the debug level
Definition at line 209 of file Parameter.cpp.
References BAMBU_OPTIONS, BOOST_PP_SEQ_FOR_EACH, EUCALIPTUS_OPTIONS, FRAMEWORK_OPTIONS, GCC_OPTIONS, GECCO_OPTIONS, KOALA_OPTIONS, OPTION_NAME, option_name, SetCommonDefaults(), setOption(), SPIDER_OPTIONS, SYNTHESIS_OPTIONS, TREE_PANDA_GCC_OPTIONS, and ZEBU_OPTIONS.
Parameter() [2/2]
Parameter::Parameter (const Parameter & other)
Copy Constructor.
Parameters
other is copy element
Definition at line 232 of file Parameter.cpp.
 Parameter()
Parameter::~Parameter () [virtual], [default]
Destructor.
Referenced by CheckParameters().
Member Function Documentation
add_debug_class()
void Parameter::add_debug_class (const std::string & class_name)
Add a class to be debugged.
Definition at line 403 of file Parameter.cpp.
References debug_classes.
Referenced by ManageDefaultOptions().
CGetArgv()
const std::vector< std::string > Parameter::CGetArgv () const
Return argv.
Definition at line 1684 of file Parameter.cpp.
References test_panda::arg, argc, argv, and getOption().
CheckParameters()
void Parameter::CheckParameters () [pure virtual]
Checks the compatibility among the different parameters and determines the implications.
Output directory is not removed since it can be the current one
Implemented in BambuParameter, EucalyptusParameter, SpiderParameter, and tree_panda_gcc_parameter.
Definition at line 236 of file Parameter.cpp.
References ~Parameter().
Referenced by tree_panda_gcc_parameter::CheckParameters(), SpiderParameter::CheckParameters(), BambuParameter::CheckParameters(), and EucalyptusParameter::CheckParameters().
Exec()
virtual int Parameter::Exec () [pure virtual]
Execute parameter parsing.
It has to be specialized
Implemented in BambuParameter, EucalyptusParameter, SpiderParameter, and tree_panda_gcc_parameter.
get_class_debug_level()
int Parameter::get_class_debug_level (const std::string & class_name, int debug_level = -1) const
Return the debug level for a specific class.
Parameters
name is the name the class
Returns
the corresponding level
Definition at line 374 of file Parameter.cpp.
References debug_classes, DEBUG_LEVEL_INFINITE, and STR_CST_debug_all.
Referenced by BambuParameter::CheckParameters(), and GetFunctionDebugLevel().
GetFileFormat()
Parameters_FileFormat Parameter::GetFileFormat (const std::string & file, bool check_cml_root_node = false) const
Return the file format given the file name or the extension.
Parameters
file is the file name or the extension
check_cml_root_node tells xml file has to be analyzed
Returns
the type of the file format
Definition at line 1164 of file Parameter.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, XMLDomParser::Exec(), FF_CSV, FF_TEX, FF_UNKNOWN, FF_VERILOG, FF_VHDL, FF_XML, FF_XML_EXPERIMENTAL_SETUP, FF_XML_IP_XACT_COMPONENT, FF_XML_IP_XACT_CONFIG, FF_XML_IP_XACT_DESIGN, FF_XML_IP_XACT_GENERATOR, FF_XML_SKIP_ROW, FF_XML_SYM_SIM, FF_XML_TEX_TABLE, FF_XML_WGT_SYM, fileIO_istream_open(), attribute_sequence::get_attribute(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), xml_attribute::get_value(), GetExtension(), GetLeafFileName(), INDENT_DBG_MEX, test_panda::parser, STOK, STR_XML_constraints_root, STR_XML_experimental_setup_root, STR_XML_latex_table_root, STR_XML_technology_root, STR_XML_technology_target_root, STR_XML_weights_distribution, STR_XML_weights_root, THROW_ASSERT, and TOK_GCC_VERSION.
Referenced by SpiderParameter::CheckParameters(), and BambuParameter::Exec().
GetFunctionDebugLevel()
int Parameter::GetFunctionDebugLevel (const std::string & class_name, const std::string & function_name) const
Return the debug_level of a function.
Parameters
class_name is the name of the class
function_name is the name of the function
Returns
the debug_level
Definition at line 386 of file Parameter.cpp.
References debug_classes, DEBUG_LEVEL_INFINITE, and get_class_debug_level().
getOption() [1/8]
template<typename G >
void Parameter::getOption (const std::string & name, G & variable) const [inline]
Returns the value of an option.
Parameters
name is the name of the option
variable is the variable where the value of the option will be saved
Definition at line 487 of file Parameter.hpp.
References THROW_ASSERT.
Referenced by CGetArgv(), SpiderParameter::CheckParameters(), BambuParameter::CheckParameters(), getOption(), and GetParameter().
getOption() [2/8]
template<typename G >
void Parameter::getOption (const char * name, G & variable) const [inline]
Returns the value of an option.
Parameters
name is the name of the option
variable is the variable where the value of the option will be saved
Definition at line 499 of file Parameter.hpp.
getOption() [3/8]
template<typename G >
G Parameter::getOption (const std::string & name) const [inline]
Returns the value of an option.
Parameters
name is the name of the option
return the value of the option
Definition at line 510 of file Parameter.hpp.
References THROW_ASSERT.
getOption() [4/8]
template<typename G >
G Parameter::getOption (const char * name) const [inline]
Returns the value of an option.
Parameters
name is the name of the option
return the value of the option
Definition at line 522 of file Parameter.hpp.
getOption() [5/8]
template<typename G >
G Parameter::getOption (const enum enum_option name) const [inline]
Returns the value of an option.
Parameters
name is the name of the option
return the value of the option
Definition at line 533 of file Parameter.hpp.
References THROW_ASSERT.
getOption() [6/8]
const CustomSet< std::string > Parameter::getOption (const enum enum_option name) const
Definition at line 1657 of file Parameter.cpp.
References SplitString(), and STR_CST_string_separator.
getOption() [7/8]
const std::list< std::string > Parameter::getOption (const enum enum_option name) const
Definition at line 1671 of file Parameter.cpp.
References SplitString(), and STR_CST_string_separator.
getOption() [8/8]
Parameters_FileFormat Parameter::getOption (const enum enum_option name) const
Definition at line 1723 of file Parameter.cpp.
References enum_options, getOption(), setOption(), SplitString(), STR_CST_average_case, STR_CST_path_based, STR_CST_worst_case, and THROW_ERROR.
GetParameter()
template<typename G >
G Parameter::GetParameter (const std::string & name) const [inline]
Returns the value of a parameter.
Parameters
name is the name of the parameter
return the value of the parameter
Definition at line 696 of file Parameter.hpp.
References getOption(), setOption(), and THROW_ASSERT.
isOption() [1/3]
bool Parameter::isOption (const std::string & name) const [inline]
Tests if an option has been stored.
Parameters
name is the name of the option
Returns
true if the option is in the map, false otherwise
Definition at line 577 of file Parameter.hpp.
Referenced by BambuParameter::add_bambu_library(), BambuParameter::add_experimental_setup_gcc_options(), SpiderParameter::CheckParameters(), BambuParameter::CheckParameters(), EucalyptusParameter::CheckParameters(), tree_panda_gcc_parameter::Exec(), SpiderParameter::Exec(), BambuParameter::Exec(), ManageDefaultOptions(), and BambuParameter::SetDefaults().
isOption() [2/3]
bool Parameter::isOption (const char * name) const [inline]
Tests if an option has been stored.
Parameters
name is the name of the option
Returns
true if the option is in the map, false otherwise
Definition at line 587 of file Parameter.hpp.
isOption() [3/3]
bool Parameter::isOption (const enum enum_option name) const [inline]
Tests if an option has been stored.
Parameters
name is the name of the option
Returns
true if the option is in the map, false otherwise
Definition at line 597 of file Parameter.hpp.
IsParameter()
bool Parameter::IsParameter (const std::string & name) const
Return if a parameter has been set.
Parameters
name is the name of the parameter
Returns
true if the parameter has been set
Definition at line 1882 of file Parameter.cpp.
References panda_parameters.
load_xml_configuration_file()
void Parameter::load_xml_configuration_file (const std::string & filename)
Loads an XML configuration file.
Parameters
filename is the configuration file name to be loaded
general options
Definition at line 280 of file Parameter.cpp.
References CE_XVM, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), GET_NODE_NAME, GET_STRING_VALUE, load_xml_configuration_file_rec(), Options, and test_panda::parser.
Referenced by ManageDefaultOptions().
load_xml_configuration_file_rec()
void Parameter::load_xml_configuration_file_rec (const xml_element * node) [protected]
Loads an XML configuration file (recursive method)
Parameters
node is the starting node for the analysis
general options
Definition at line 263 of file Parameter.cpp.
References CE_XVM, xml_child::get_children(), GET_NODE_NAME, GET_STRING_VALUE, and Options.
Referenced by load_xml_configuration_file().
ManageDefaultOptions()
bool Parameter::ManageDefaultOptions (int next_option, char * optarg_param, bool & exit_success) [protected]
Manage default options (common to all tools)
Parameters
next_option is the index of the option to be analyzed
optarg_param is the optional argument of the option
exit_success is where the exit value is stored
Returns
true if the option has been recognized
If the path is not absolute, make it into absolute
next_option is not a Tool parameter
Definition at line 436 of file Parameter.cpp.
References add_debug_class(), debug_level, error_on_warning, INPUT_OPT_CFG_MAX_TRANSFORMATIONS, INPUT_OPT_COMPILER, INPUT_OPT_COMPUTE_SIZEOF, INPUT_OPT_CONFIGURATION_NAME, INPUT_OPT_CUSTOM_OPTIONS, INPUT_OPT_ERROR_ON_WARNING, INPUT_OPT_GCC_CONFIG, INPUT_OPT_INCLUDE_SYSDIR, INPUT_OPT_NO_CLEAN, INPUT_OPT_PANDA_PARAMETER, INPUT_OPT_PARAM, INPUT_OPT_PRINT_DOT, INPUT_OPT_READ_GCC_XML, INPUT_OPT_SEED, INPUT_OPT_STD, INPUT_OPT_USE_RAW, INPUT_OPT_WRITE_GCC_XML, isOption(), load_xml_configuration_file(), O0, O1, O2, O3, O4, O5, Ofast, Og, OPT_BENCHMARK_FAKE_PARAMETERS, OPT_BENCHMARK_NAME, OPT_DEBUG_CLASSES, OPT_OUTPUT_TEMPORARY_DIRECTORY, OPT_READ_PARAMETERS_XML, OPT_WRITE_PARAMETERS_XML, Os, OUTPUT_LEVEL_NONE, Oz, panda_parameters, test_panda::parameters, PRINT_OUT_MEX, PrintFullHeader(), PrintUsage(), setOption(), SplitString(), STR_CST_string_separator, STR_CST_temporary_directory, STR_OPT_benchmark_fake_parameters, THROW_ASSERT, and THROW_ERROR.
Referenced by tree_panda_gcc_parameter::Exec(), SpiderParameter::Exec(), EucalyptusParameter::Exec(), and BambuParameter::Exec().
print()
void Parameter::print (std::ostream & os) const
Definition at line 359 of file Parameter.cpp.
References enum_options, option_name, and Options.
PrintBugReport()
void Parameter::PrintBugReport (std::ostream & os) const
Print the bug report request.
Parameters
os is the stream where the message has to be printed
Definition at line 1469 of file Parameter.cpp.
PrintFullHeader()
void Parameter::PrintFullHeader (std::ostream & os) const [virtual]
This function prints the header of the tool = PrintProgramName() + PrintVersion()
Definition at line 410 of file Parameter.cpp.
References PrintProgramName(), and PrintVersion().
Referenced by ManageDefaultOptions(), and PrintUsage().
PrintGeneralOptionsUsage()
void Parameter::PrintGeneralOptionsUsage (std::ostream & os) const [protected]
Print the usage of the general common options.
Parameters
os is the stream where to print
Definition at line 1474 of file Parameter.cpp.
Referenced by tree_panda_gcc_parameter::PrintHelp(), SpiderParameter::PrintHelp(), EucalyptusParameter::PrintHelp(), and BambuParameter::PrintHelp().
PrintHelp()
virtual void Parameter::PrintHelp (std::ostream & os) const [protected], [pure virtual]
Print the help.
Parameters
os is the stream on which the help has to be printed
Implemented in BambuParameter, EucalyptusParameter, SpiderParameter, and tree_panda_gcc_parameter.
Referenced by PrintUsage().
PrintOutputOptionsUsage()
void Parameter::PrintOutputOptionsUsage (std::ostream & os) const [protected]
Print the usage of the output common options.
Parameters
os is the stream
Definition at line 1494 of file Parameter.cpp.
References STR_CST_temporary_directory.
Referenced by tree_panda_gcc_parameter::PrintHelp(), SpiderParameter::PrintHelp(), and BambuParameter::PrintHelp().
PrintProgramName()
virtual void Parameter::PrintProgramName (std::ostream & os) const [protected], [pure virtual]
Print the name of the program to be included in the header.
Parameters
os is the stream on which the program name has to be printed
Implemented in BambuParameter, EucalyptusParameter, SpiderParameter, and tree_panda_gcc_parameter.
Referenced by PrintFullHeader().
PrintUsage()
void Parameter::PrintUsage (std::ostream & os) const
Print the usage of this tool = PrintHeader() + PrintHelp()
Parameters
os is the stream where the message has to be printed
Definition at line 430 of file Parameter.cpp.
References PrintFullHeader(), and PrintHelp().
Referenced by tree_panda_gcc_parameter::Exec(), SpiderParameter::Exec(), EucalyptusParameter::Exec(), BambuParameter::Exec(), and ManageDefaultOptions().
PrintVersion()
std::string Parameter::PrintVersion () const
This function prints the version of the tool.
Definition at line 425 of file Parameter.cpp.
Referenced by PrintFullHeader().
removeOption() [1/3]
bool Parameter::removeOption (const enum enum_option name) [inline]
Remove an option.
Parameters
name is the name of the option
Returns
true if the option has been eliminated, false otherwise
Definition at line 607 of file Parameter.hpp.
removeOption() [2/3]
bool Parameter::removeOption (const char * name) [inline]
Remove an option.
Parameters
name is the name of the option
Returns
true if the option has been eliminated, false otherwise
Definition at line 620 of file Parameter.hpp.
removeOption() [3/3]
bool Parameter::removeOption (const std::string & name) [inline]
Remove an option.
Parameters
name is the name of the option
Returns
true if the option has been eliminated, false otherwise
Definition at line 630 of file Parameter.hpp.
SetCommonDefaults()
void Parameter::SetCommonDefaults () [protected]
Sets the default values common to all tools.
Definition at line 339 of file Parameter.cpp.
References branch_name, GetCurrentPath(), max(), revision_hash, setOption(), STR_CST_temporary_directory, and STR_OPT_benchmark_fake_parameters.
Referenced by Parameter().
SetDefaults()
virtual void Parameter::SetDefaults () [protected], [pure virtual]
Sets the default values with respect to the tool.
Implemented in BambuParameter, tree_panda_gcc_parameter, SpiderParameter, and EucalyptusParameter.
setOption() [1/3]
template<typename G >
void Parameter::setOption (const std::string & name, const G value) [inline]
Sets the value of an option.
Parameters
name is the name of the option
value is the value of the option to be saved
Definition at line 545 of file Parameter.hpp.
Referenced by BambuParameter::add_bambu_library(), BambuParameter::add_experimental_setup_gcc_options(), SpiderParameter::CheckParameters(), BambuParameter::CheckParameters(), EucalyptusParameter::CheckParameters(), tree_panda_gcc_parameter::Exec(), SpiderParameter::Exec(), EucalyptusParameter::Exec(), BambuParameter::Exec(), getOption(), GetParameter(), ManageDefaultOptions(), Parameter(), SetCommonDefaults(), EucalyptusParameter::SetDefaults(), SpiderParameter::SetDefaults(), tree_panda_gcc_parameter::SetDefaults(), and BambuParameter::SetDefaults().
setOption() [2/3]
template<typename G >
void Parameter::setOption (const char * name, const G value) [inline]
Sets the value of an option.
Parameters
name is the name of the option
value is the value of the option to be saved
Definition at line 556 of file Parameter.hpp.
setOption() [3/3]
template<typename G >
void Parameter::setOption (const enum enum_option name, const G value) [inline]
Sets the value of an option.
Parameters
name is the name of the option
value is the value of the option to be saved
Definition at line 567 of file Parameter.hpp.
write_xml_configuration_file()
void Parameter::write_xml_configuration_file (const std::string & filename)
Write an XML configuration file with the parameters actually stored.
Parameters
filename is the configuration file name where parameters have to be written
Definition at line 324 of file Parameter.cpp.
References xml_child::add_child_element(), xml_document::create_root_node(), Options, test_panda::parameters, xml_document::write_to_file_formatted(), and WRITE_XNVM2.
Referenced by tree_panda_gcc_parameter::Exec(), and BambuParameter::Exec().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Parameter & s) [friend]
Friend definition of the << operator.
Definition at line 475 of file Parameter.hpp.
Field Documentation
argc
int Parameter::argc [protected]
The number of input paramters.
Definition at line 338 of file Parameter.hpp.
Referenced by CGetArgv(), tree_panda_gcc_parameter::Exec(), SpiderParameter::Exec(), EucalyptusParameter::Exec(), and BambuParameter::Exec().
argv
char** const Parameter::argv [protected]
The input parameters;.
Definition at line 341 of file Parameter.hpp.
Referenced by CGetArgv(), tree_panda_gcc_parameter::Exec(), SpiderParameter::Exec(), EucalyptusParameter::Exec(), and BambuParameter::Exec().
debug_classes
CustomUnorderedSet<std::string> Parameter::debug_classes [protected]
Classes to be debugged.
Definition at line 356 of file Parameter.hpp.
Referenced by add_debug_class(), get_class_debug_level(), and GetFunctionDebugLevel().
debug_level
int Parameter::debug_level [protected]
debug level
Definition at line 359 of file Parameter.hpp.
Referenced by SpiderParameter::CheckParameters(), GetFileFormat(), and ManageDefaultOptions().
enum_options
std::map<enum enum_option, std::string> Parameter::enum_options [protected]
Map between an enum option and the related string-form value.
Definition at line 350 of file Parameter.hpp.
Referenced by getOption(), and print().
option_name
std::map<enum enum_option, std::string> Parameter::option_name [protected]
Name of the enum options.
Definition at line 353 of file Parameter.hpp.
Referenced by Parameter(), and print().
Options
OptionMap Parameter::Options [protected]
Map between the name of the option and the related string-form value.
Definition at line 344 of file Parameter.hpp.
Referenced by load_xml_configuration_file(), load_xml_configuration_file_rec(), print(), and write_xml_configuration_file().
panda_parameters
CustomMap<std::string, std::string> Parameter::panda_parameters [protected]
Map between the name of a parameter and the related string-form value.
Definition at line 347 of file Parameter.hpp.
Referenced by IsParameter(), ManageDefaultOptions(), and BambuParameter::SetDefaults().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/Parameter.hpp
/home/osboxes/bambu/PandA-bambu/src/Parameter.cpp