MemoryInitializationWriter Class Reference
Functor used to write initialization of the memory writer.
#include <memory_initialization_writer.hpp>
Public Member Functions
MemoryInitializationWriter (std::ofstream &output_stream, const tree_managerConstRef TM, const BehavioralHelperConstRef behavioral_helper, const unsigned long int reserved_mem_bytes, const tree_nodeConstRef function_parameter, const TestbenchGeneration_MemoryType testbench_generation_memory_type, const ParameterConstRef parameters)
Constructor.
void Process (const std::string &content) override
Process an element.
Protected Attributes
std::ofstream & output_stream
The stream corresponding to the memory initialization file.
Additional Inherited Members
Detailed Description
Functor used to write initialization of the memory writer.
Definition at line 65 of file memory_initialization_writer.hpp.
Constructor & Destructor Documentation
MemoryInitializationWriter()
MemoryInitializationWriter::MemoryInitializationWriter (std::ofstream & _output_stream, const tree_managerConstRef _TM, const BehavioralHelperConstRef _behavioral_helper, const unsigned long int _reserved_mem_bytes, const tree_nodeConstRef _function_parameter, const TestbenchGeneration_MemoryType _testbench_generation_memory_type, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
output_stream is where memory initialization will be written
TM is the tree manager
behavioral_helper is the behavioral helper
reserved_mem_bytes is the number of bytes to be written
function_parameter is the function parameter whose initialization is being printed
testbench_generation_memory_type is the type of initialization being printed
parameters is the set of input parameters
. include HLS/simulation include STD include STL include tree includes utility include
Definition at line 67 of file memory_initialization_writer.cpp.
References CInitializationParserFunctor::debug_level, and GET_CLASS.
Member Function Documentation
Process()
void MemoryInitializationWriter::Process (const std::string & content) [override], [virtual]
Process an element.
Second, according to the type let's how many elements have to have been processed
Implements CInitializationParserFunctor.
Definition at line 74 of file memory_initialization_writer.cpp.
References MemoryInitializationWriterBase::behavioral_helper, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, ConvertInBinary(), CInitializationParserFunctor::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, MemoryInitializationWriterBase::function_parameter, tree_helper::get_pointed_type(), INDENT_DBG_MEX, INPUT_PARAMETER, tree_helper::is_unsigned(), MEMORY_INITIALIZATION, NODE_NOT_YET_SUPPORTED_EC, OUTPUT_PARAMETER, output_stream, BehavioralHelper::PrintVariable(), RETURN, tree_helper::size(), MemoryInitializationWriterBase::status, STR, MemoryInitializationWriterBase::testbench_generation_memory_type, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, MemoryInitializationWriterBase::TM, and MemoryInitializationWriterBase::written_bytes.
Field Documentation
output_stream
std::ofstream& MemoryInitializationWriter::output_stream [protected]
The stream corresponding to the memory initialization file.
Definition at line 69 of file memory_initialization_writer.hpp.
Referenced by Process().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/memory_initialization_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/memory_initialization_writer.cpp