lattice_flow_wrapper Class Reference
Main class for wrapping lattice_flow tool by Lattice.
#include <lattice_flow_wrapper.hpp>
Public Member Functions
lattice_flow_wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~lattice_flow_wrapper () override
Destructor.
Protected Member Functions
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
Additional Inherited Members
Detailed Description
Main class for wrapping lattice_flow tool by Lattice.
Definition at line 57 of file lattice_flow_wrapper.hpp.
Constructor & Destructor Documentation
lattice_flow_wrapper()
lattice_flow_wrapper::lattice_flow_wrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Header include.
Parameters
Param is the set of parameters
Definition at line 54 of file lattice_flow_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, and ~lattice_flow_wrapper().
 lattice_flow_wrapper()
lattice_flow_wrapper::~lattice_flow_wrapper () [override], [default]
Destructor.
Referenced by lattice_flow_wrapper().
Member Function Documentation
EvaluateVariables()
void lattice_flow_wrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 62 of file lattice_flow_wrapper.cpp.
References DesignParameters::assign(), DesignParameters::component_name, SynthesisTool::output_dir, PARAM_lattice_outdir, PARAM_lattice_report, and DesignParameters::parameter_values.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/lattice/lattice_flow_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/lattice/lattice_flow_wrapper.cpp