datapath_cs Class Reference
#include <datapath_cs.hpp>
Public Member Functions
datapath_cs (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
virtual ~datapath_cs ()
Destructor.
Protected Member Functions
void add_ports ()
Adds the input/output ports of the module.
Additional Inherited Members
Detailed Description
Definition at line 46 of file datapath_cs.hpp.
Constructor & Destructor Documentation
datapath_cs()
datapath_cs::datapath_cs (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
Constructor.
STD include.
Parameters
design_flow_manager is the design flow manager
utility include
Definition at line 57 of file datapath_cs.cpp.
References DesignFlowStep::debug_level, and GET_CLASS.
 datapath_cs()
datapath_cs::~datapath_cs () [virtual]
Destructor.
Definition at line 63 of file datapath_cs.cpp.
Member Function Documentation
add_ports()
void datapath_cs::add_ports () [protected], [virtual]
Adds the input/output ports of the module.
Reimplemented from classic_datapath.
Definition at line 67 of file datapath_cs.cpp.
References classic_datapath::add_ports(), structural_object::AddParameter(), ceil_log2(), hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, DONE_REQUEST, DONE_SCHEDULER, HLSFunctionStep::funId, GET_CLASS, HLSFunctionStep::HLS, HLS_step::HLSMgr, port_o::IN, INDENT_DBG_MEX, port_o::OUT, DesignFlowStep::parameters, SELECTOR_REGISTER_FILE, START_PORT_NAME, STR, SUSPENSION, TASKS_POOL_END, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/datapath_creation/datapath_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/datapath_creation/datapath_cs.cpp