/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Context-Switch/fourth/trinityq4/lubm_trinityq4.c File Reference
#include <stdio.h>
#include `simple_API.h`
Functions
__attribute__ ((noinline))
int test (NodeId var_2, PropertyId p_var_3, PropertyId p_var_4, PropertyId p_var_5, PropertyId p_var_7, PropertyId p_var_9, PropertyId p_var_11)
Function Documentation
__attribute__()
__attribute__ ((noinline))
Definition at line 12 of file lubm_trinityq4.c.
References __attribute__(), counter, getInDegree(), getInEdges(), getOutDegree(), getOutEdges(), N_THREADS, Edge::node, numAnswers, and Edge::property.
test()
int test (NodeId var_2, PropertyId p_var_3, PropertyId p_var_4, PropertyId p_var_5, PropertyId p_var_7, PropertyId p_var_9, PropertyId p_var_11)
Definition at line 106 of file lubm_trinityq4.c.
References loadGraph(), main(), test(), and TheGraph.