BuildVirtualPhi Class Reference
#include <build_virtual_phi.hpp>
Public Member Functions
BuildVirtualPhi (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~BuildVirtualPhi () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Header include.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const tree_managerRef TM
The tree manager.
tree_manipulationRef tree_man
the tree manipulation
BBGraphRef basic_block_graph
The graph of basic blocks.
TreeNodeMap< CustomUnorderedMapStable< vertex, tree_nodeRef > > added_phis
Cache of created phi - first key is the used ssa - second key is the basic block where is created.
TreeNodeMap< CustomUnorderedMapStable< vertex, tree_nodeRef > > reaching_defs
Cache of reaching defs - first key is the used ssa - second key is the basic block to be considered.
Additional Inherited Members
Detailed Description
Definition at line 57 of file build_virtual_phi.hpp.
Constructor & Destructor Documentation
BuildVirtualPhi()
BuildVirtualPhi::BuildVirtualPhi (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 138 of file build_virtual_phi.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~BuildVirtualPhi().
 BuildVirtualPhi()
BuildVirtualPhi::~BuildVirtualPhi () [override], [default]
Destructor.
Referenced by BuildVirtualPhi().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BuildVirtualPhi::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 105 of file build_virtual_phi.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, BB_FEEDBACK_EDGES_IDENTIFICATION, BB_REACHABILITY_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DOM_POST_DOM_COMPUTATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
ComputeRelationships()
void BuildVirtualPhi::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Header include.
. include algorithms/loops_detection include behavior include parser/treegcc include tree includes
Reimplemented from FunctionFrontendFlowStep.
Definition at line 74 of file build_virtual_phi.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::ComputeRelationships(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::GetSignature(), DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), NULL_VERTEX, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SUCCESS, THROW_ASSERT, and THROW_UNREACHABLE.
HasToBeExecuted()
bool BuildVirtualPhi::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 688 of file build_virtual_phi.cpp.
References FunctionFrontendFlowStep::bb_version.
Initialize()
void BuildVirtualPhi::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 681 of file build_virtual_phi.cpp.
References basic_block_graph, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, DesignFlowStep::Initialize(), DesignFlowStep::parameters, TM, and tree_man.
InternalExec()
DesignFlowStep_Status BuildVirtualPhi::InternalExec () [override], [virtual]
Performs the loops analysis.
For each virtual operand its definition
The set of nodes which overwrite a vop
Computing definitions and overwriting
clean not reachable vuses
here we may have a Use-Def or a Def-Use. They are both perfectly fine.
Check uses
The index of the loop to be considered (the most internal loops which contains the definition and all the uses
The depth of the loop to be considered
The set of basic block uses
The set of statement uses
The set of false uses
Check if this use can be ignored because of transitive reduction
Use is in the considered loop
Use is in a more nested loop
Use is in a less nested loop
It is possible that the use is not reachable; this is due to the gcc alias oracle
Build the gimple nop where volatile ssa is defined
Set of basic blocks belonging to the loop
Set of basic blocks to be analyzed
Loop 0 must be managed in a different way
Remove all basic blocks from which no use can be reached
The phi is necessary only if there are different reaching definition
Phi must always be built in header loop if definition is inside the loop
Check if this is a irreducible loop
If loop is irreducible, than we have to consider the definition coming from sp_back_edge since it can be different: different definitions can enter in the loop in the different enter points
If this is the basic block definition or contains a use
Check if phi has to be created because of different definitions coming from outside the loop
Implements FunctionFrontendFlowStep.
Definition at line 146 of file build_virtual_phi.cpp.
References added_phis, basic_block_graph, CFG_SELECTOR, BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, GET_CONST_NODE, GET_NODE, tree_helper::get_type_index(), BBGraph::GetBBNodeInfo(), graph::GetSelector(), INDENT_DBG_MEX, DesignFlowStep::parameters, phi, reaching_defs, STR, SUCCESS, THROW_ASSERT, TM, TOK, TOK_RES, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, and ToString().
Field Documentation
added_phis
TreeNodeMap<CustomUnorderedMapStable<vertex, tree_nodeRef> > BuildVirtualPhi::added_phis [private]
Cache of created phi - first key is the used ssa - second key is the basic block where is created.
Definition at line 70 of file build_virtual_phi.hpp.
Referenced by InternalExec().
basic_block_graph
BBGraphRef BuildVirtualPhi::basic_block_graph [private]
The graph of basic blocks.
Definition at line 67 of file build_virtual_phi.hpp.
Referenced by Initialize(), and InternalExec().
reaching_defs
TreeNodeMap<CustomUnorderedMapStable<vertex, tree_nodeRef> > BuildVirtualPhi::reaching_defs [private]
Cache of reaching defs - first key is the used ssa - second key is the basic block to be considered.
Definition at line 73 of file build_virtual_phi.hpp.
Referenced by InternalExec().
TM
const tree_managerRef BuildVirtualPhi::TM [private]
The tree manager.
Definition at line 61 of file build_virtual_phi.hpp.
Referenced by Initialize(), and InternalExec().
tree_man
tree_manipulationRef BuildVirtualPhi::tree_man [private]
the tree manipulation
Definition at line 64 of file build_virtual_phi.hpp.
Referenced by Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/build_virtual_phi.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/build_virtual_phi.cpp