easy_module_binding Class Reference
superclass include
#include <easy_module_binding.hpp>
Public Member Functions
easy_module_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~easy_module_binding () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Additional Inherited Members
Detailed Description
superclass include
Class managing a partial module binding based on simple conditions
Definition at line 51 of file easy_module_binding.hpp.
Constructor & Destructor Documentation
easy_module_binding()
easy_module_binding::easy_module_binding (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
HLS include.
Parameters
design_flow_manager is the design flow manager
HLS/allocation_information include tree include utility include
Definition at line 83 of file easy_module_binding.cpp.
References DesignFlowStep::debug_level, EASY_MODULE_BINDING, GET_CLASS, and ~easy_module_binding().
 easy_module_binding()
easy_module_binding::~easy_module_binding () [override], [default]
Destructor.
Referenced by easy_module_binding().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > easy_module_binding::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 107 of file easy_module_binding.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::HLSMgr, INITIALIZE_HLS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void easy_module_binding::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 91 of file easy_module_binding.cpp.
References fu_binding::create_fu_binding(), HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), DesignFlowStep::parameters, and hls::Rfu.
InternalExec()
DesignFlowStep_Status easy_module_binding::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
compute unshared resources
check easy binding and compute the list of vertices for which a sharing is possible
Implements HLSFunctionStep.
Definition at line 135 of file easy_module_binding.cpp.
References hls::allocation_information, fu_binding::bind(), FunctionBehavior::CGetBehavioralHelper(), OpGraph::CGetOperations(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), ENTRY_ID, EXIT_ID, HLSFunctionStep::funId, fu_binding::get_assign(), AllocationInformation::get_fu(), AllocationInformation::get_fu_name(), BehavioralHelper::get_function_name(), fu_binding::get_index(), GET_NAME, AllocationInformation::get_number_channels(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_OUT_MEX, index, INFINITE_UINT, AllocationInformation::is_memory_unit(), AllocationInformation::is_one_cycle_direct_access_memory_unit(), AllocationInformation::is_readonly_memory_unit(), AllocationInformation::is_vertex_bounded(), DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, print_cpu_time(), hls::Rfu, FunctionBehavior::SDG, START_TIME, STOP_TIME, STR, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/easy_module_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/easy_module_binding.cpp