FunctionCallTypeCleanup Class Reference
#include <FunctionCallTypeCleanup.hpp>
Public Member Functions
FunctionCallTypeCleanup (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~FunctionCallTypeCleanup () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes the operations CFG graph data structure.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 52 of file FunctionCallTypeCleanup.hpp.
Constructor & Destructor Documentation
FunctionCallTypeCleanup()
FunctionCallTypeCleanup::FunctionCallTypeCleanup (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Definition at line 67 of file FunctionCallTypeCleanup.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~FunctionCallTypeCleanup().
 FunctionCallTypeCleanup()
FunctionCallTypeCleanup::~FunctionCallTypeCleanup () [override], [default]
Destructor.
Referenced by FunctionCallTypeCleanup().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > FunctionCallTypeCleanup::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Workaround: this should be a precedence, but when this is added later for functions added during call graph extension is added as unnecessary and it is not updated before its execution
Implements FrontendFlowStep.
Definition at line 307 of file FunctionCallTypeCleanup.cpp.
References FrontendFlowStep::CALLED_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, MEM_CG_EXT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void FunctionCallTypeCleanup::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 303 of file FunctionCallTypeCleanup.cpp.
InternalExec()
DesignFlowStep_Status FunctionCallTypeCleanup::InternalExec () [override], [virtual]
Computes the operations CFG graph data structure.
Returns
the exit status of this step
required by CLANG/LLVM
required by CLANG/LLVM
It is required to de-share some IR nodes
required by CLANG/LLVM
required by CLANG/LLVM
It is required to de-share some IR nodes
Implements FunctionFrontendFlowStep.
Definition at line 75 of file FunctionCallTypeCleanup.cpp.
References FrontendFlowStep::AppM, tree_manager::CGetTreeReindex(), tree_helper::CGetType(), conv_really_needed(), tree_manipulation::create_ssa_name(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manipulation::CreateNopExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_formal_ith(), GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_helper::GetFunctionReturnType(), INDENT_DBG_MEX, DesignFlowStep::parameters, tree_manager::RecursiveReplaceTreeNode(), tree_manager::ReplaceTreeNode(), sl, STR, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, and ToString().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/FunctionCallTypeCleanup.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/FunctionCallTypeCleanup.cpp