/home/osboxes/bambu/PandA-bambu/src/utility/strong_typedef.hpp File Reference
This class macros for the definition of strong typedef.
#include <boost/functional/hash/hash.hpp>
Macros
#define STRONG_TYPEDEF_FORWARD_DECL(OriginalType, NewType) class NewType
#define STRONG_TYPEDEF(OriginalType, NewType)
This is quite similar to boost strong typedef, but implicit conversion are disabled.
#define UINT_STRONG_TYPEDEF(new_type) STRONG_TYPEDEF(unsigned int, new_type)
#define UINT_STRONG_TYPEDEF_FORWARD_DECL(new_type) STRONG_TYPEDEF_FORWARD_DECL(unsigned int, new_type)
Functions
template<typename Dest , typename Source >
Dest from_strongtype_cast (Source source)
Detailed Description
This class macros for the definition of strong typedef.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Marco Lattuada lattuada@elet.polimi.it
Macro Definition Documentation
STRONG_TYPEDEF
#define STRONG_TYPEDEF(OriginalType, NewType)
This is quite similar to boost strong typedef, but implicit conversion are disabled.
Definition at line 80 of file strong_typedef.hpp.
STRONG_TYPEDEF_FORWARD_DECL
#define STRONG_TYPEDEF_FORWARD_DECL(OriginalType, NewType) class NewType
Definition at line 78 of file strong_typedef.hpp.
UINT_STRONG_TYPEDEF
#define UINT_STRONG_TYPEDEF(new_type) STRONG_TYPEDEF(unsigned int, new_type)
Definition at line 244 of file strong_typedef.hpp.
UINT_STRONG_TYPEDEF_FORWARD_DECL
#define UINT_STRONG_TYPEDEF_FORWARD_DECL(new_type) STRONG_TYPEDEF_FORWARD_DECL(unsigned int, new_type)
Definition at line 245 of file strong_typedef.hpp.
Function Documentation
from_strongtype_cast()
template<typename Dest , typename Source >
Dest from_strongtype_cast (Source source) [inline]
Definition at line 65 of file strong_typedef.hpp.
Referenced by ASLAP::compute_ALAP_fast(), ASLAP::compute_ASAP(), parametric_list_based::compute_exec_stage_time(), parametric_list_based::compute_slack(), parametric_list_based::compute_starting_ending_time_alap(), parametric_list_based::compute_starting_ending_time_asap(), parametric_list_based::do_balanced_scheduling(), parametric_list_based::do_balanced_scheduling1(), parametric_list_based::exec(), AllocationInformation::get_attribute_of_fu_per_op(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), priority_dynamic_mobility::priority_dynamic_mobility(), priority_static_mobility::priority_static_mobility(), parametric_list_based::update_starting_ending_time(), parametric_list_based::update_starting_ending_time_asap(), Schedule::UpdateTime(), operation::xload(), and operation::xwrite().