VHDL_writer Struct Reference
Autoheader include.
#include <VHDL_writer.hpp>
Public Member Functions
std::string get_name () const override
Return the name of the language writer.
std::string get_extension () const override
Return the filename extension associated with the VHDL_writer.
void write_comment (const std::string &comment_string) override
Print a comment.
std::string type_converter (structural_type_descriptorRef Type) override
Return a language based type string given a structural_type_descriptor.
std::string type_converter_size (const structural_objectRef &cir) override
Return a language based type string given a structural_type_descriptor for the range of the array.
std::string may_slice_string (const structural_objectRef &cir)
return the slice in case of a port owned by a port vector
void write_library_declaration (const structural_objectRef &cir) override
Write used library.
void write_module_declaration (const structural_objectRef &cir) override
Write the declaration of the module.
void write_module_internal_declaration (const structural_objectRef &cir) override
Write the declaration of internal objects of the module.
void write_port_declaration (const structural_objectRef &cir, bool last_port_to_analyze) override
Write the port declaration starting from a port object.
void write_component_declaration (const structural_objectRef &cir) override
Write the declaration of a component.
void write_signal_declaration (const structural_objectRef &cir) override
Write the declaration of a signal.
void write_module_definition_begin (const structural_objectRef &cir) override
Write the top constructor declaration.
void write_module_instance_begin (const structural_objectRef &cir, const std::string &module_name, bool write_parametrization) override
Write the initial part of the instance of a module.
void write_module_instance_end (const structural_objectRef &cir) override
Write the ending part of the instance of a module.
void write_port_binding (const structural_objectRef &port, const structural_objectRef &top, bool &first_port_analyzed) override
Write the binding of a port.
void write_vector_port_binding (const structural_objectRef &port, bool &first_port_analyzed) override
void write_module_definition_end (const structural_objectRef &cir) override
Write the end part in a module declaration.
void write_io_signal_post_fix (const structural_objectRef &port, const structural_objectRef &sig) override
Write some code managing primary ports to signals connections.
void write_module_parametrization (const structural_objectRef &cir) override
Module can be parametrized with respect different features.
void write_tail (const structural_objectRef &cir) override
Write the tail part of the file.
void write_state_declaration (const structural_objectRef &cir, const std::list< std::string > &list_of_states, const std::string &reset_port, const std::string &reset_state, bool one_hot) override
write the declaration of all the states of the finite state machine.
void write_present_state_update (const structural_objectRef cir, const std::string &reset_state, const std::string &reset_port, const std::string &clock_port, const std::string &reset_type, bool connect_present_next_state_signals) override
write the present_state update process
void write_transition_output_functions (bool single_proc, unsigned int output_index, const structural_objectRef &cir, const std::string &reset_state, const std::string &reset_port, const std::string &start_port, const std::string &clock_port, std::vector< std::string >::const_iterator &first, std::vector< std::string >::const_iterator &end) override
Write the transition and output functions.
void write_NP_functionalities (const structural_objectRef &cir) override
Write in the proper language the behavioral description of the module described in `Not Parsed` form.
void write_assign (const std::string &op0, const std::string &op1) override
void write_port_decl_header () override
Write the header for port_decl.
void write_port_decl_tail () override
Write the tail for port_decl.
void write_module_parametrization_decl (const structural_objectRef &cir) override
Write the declaration of the module parameters.
VHDL_writer (const technology_managerConstRef TM, const ParameterConstRef parameters)
Constructor.
~VHDL_writer () override
Destructor.
bool has_output_prefix () const override
bool check_keyword (std::string) const override
void WriteBuiltin (const structural_objectConstRef component) override
Write a builtin component.
void write_header () override
Write the header of vhdl file.
Protected Attributes
CustomOrderedSet< std::string > keywords
CustomOrderedSet< std::string > list_of_comp_already_def
const technology_managerConstRef TM
The technology manager.
Static Protected Attributes
static const char * tokenNames []
Autoheader include.
Additional Inherited Members
Detailed Description
Autoheader include.
STD include STL include
Definition at line 60 of file VHDL_writer.hpp.
Constructor & Destructor Documentation
VHDL_writer()
VHDL_writer::VHDL_writer (const technology_managerConstRef TM, const ParameterConstRef parameters)
Constructor.
Parameters
TM is the technology manager
parameters is the set of input parameters
Definition at line 87 of file VHDL_writer.cpp.
References language_writer::debug_level, GET_CLASS, keywords, language_writer::parameters, tokenNames, and ~VHDL_writer().
Referenced by get_extension().
 VHDL_writer()
VHDL_writer::~VHDL_writer () [override], [default]
Destructor.
Referenced by get_extension(), and VHDL_writer().
Member Function Documentation
check_keyword()
bool VHDL_writer::check_keyword (std::string id) const [override], [virtual]
Implements language_writer.
Definition at line 1698 of file VHDL_writer.cpp.
References keywords.
Referenced by has_output_prefix().
get_extension()
std::string VHDL_writer::get_extension () const [inline], [override], [virtual]
Return the filename extension associated with the VHDL_writer.
Implements language_writer.
Definition at line 82 of file VHDL_writer.hpp.
References may_slice_string(), language_writer::parameters, top(), type_converter(), type_converter_size(), VHDL_writer(), write_assign(), write_comment(), write_component_declaration(), write_io_signal_post_fix(), write_library_declaration(), write_module_declaration(), write_module_definition_begin(), write_module_definition_end(), write_module_instance_begin(), write_module_instance_end(), write_module_internal_declaration(), write_module_parametrization(), write_module_parametrization_decl(), write_NP_functionalities(), write_port_binding(), write_port_decl_header(), write_port_decl_tail(), write_port_declaration(), write_present_state_update(), write_signal_declaration(), write_state_declaration(), write_tail(), write_transition_output_functions(), write_vector_port_binding(), and ~VHDL_writer().
get_name()
std::string VHDL_writer::get_name () const [inline], [override], [virtual]
Return the name of the language writer.
Implements language_writer.
Definition at line 75 of file VHDL_writer.hpp.
has_output_prefix()
bool VHDL_writer::has_output_prefix () const [inline], [override], [virtual]
Implements language_writer.
Definition at line 249 of file VHDL_writer.hpp.
References check_keyword(), write_header(), and WriteBuiltin().
may_slice_string()
std::string VHDL_writer::may_slice_string (const structural_objectRef & cir)
return the slice in case of a port owned by a port vector
Parameters
port is the port
Returns
a string in case of a port owned by a port vector
Definition at line 298 of file VHDL_writer.cpp.
References BITSIZE_PREFIX, structural_type_descriptor::BOOL, get_id(), structural_object::get_id(), structural_object::get_kind(), NP_functionality::get_NP_functionality(), structural_object::get_owner(), structural_object::get_typeRef(), structural_type_descriptor::INT, NUM_ELEM_PREFIX, structural_type_descriptor::OTHER, port_vector_o_K, structural_type_descriptor::print(), structural_type_descriptor::REAL, structural_type_descriptor::size, THROW_ERROR, structural_type_descriptor::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), and write_io_signal_post_fix().
type_converter()
std::string VHDL_writer::type_converter (structural_type_descriptorRef Type) [override], [virtual]
Return a language based type string given a structural_type_descriptor.
Parameters
Type is the structural_type_descriptor.
Implements language_writer.
Definition at line 101 of file VHDL_writer.cpp.
References structural_type_descriptor::BOOL, structural_type_descriptor::id_type, structural_type_descriptor::INT, structural_type_descriptor::OTHER, structural_type_descriptor::REAL, THROW_ERROR, THROW_UNREACHABLE, structural_type_descriptor::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), write_port_binding(), write_port_declaration(), and write_signal_declaration().
type_converter_size()
std::string VHDL_writer::type_converter_size (const structural_objectRef & cir) [override], [virtual]
Return a language based type string given a structural_type_descriptor for the range of the array.
In case of scalar type it return an empty string.
Parameters
cir is the object for which the size has been computed.
Implements language_writer.
Definition at line 152 of file VHDL_writer.cpp.
References BITSIZE_PREFIX, structural_type_descriptor::BOOL, HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_id(), structural_object::get_kind(), NP_functionality::get_NP_functionality(), structural_object::get_owner(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), INDENT_DBG_MEX, structural_type_descriptor::INT, NUM_ELEM_PREFIX, structural_type_descriptor::OTHER, port_vector_o_K, PORTSIZE_PREFIX, structural_type_descriptor::REAL, signal_vector_o_K, structural_type_descriptor::size, STR, THROW_ERROR, THROW_UNREACHABLE, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), write_port_declaration(), and write_signal_declaration().
write_assign()
void VHDL_writer::write_assign (const std::string & op0, const std::string & op1) [override], [virtual]
Implements language_writer.
Definition at line 1539 of file VHDL_writer.cpp.
References THROW_ERROR.
Referenced by get_extension().
write_comment()
void VHDL_writer::write_comment (const std::string & comment_string) [override], [virtual]
Print a comment.
Parameters
comment_string is the string to be printed as a comment.
Implements language_writer.
Definition at line 96 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by get_extension(), write_component_declaration(), write_present_state_update(), write_state_declaration(), and write_transition_output_functions().
write_component_declaration()
void VHDL_writer::write_component_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of a component.
Parameters
cir is the component to be declared.
Implements language_writer.
Definition at line 487 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), structural_object::get_kind_text(), HDL_manager::get_mod_typename(), structural_object::get_path(), IndentedOutputStream::Indent(), language_writer::indented_output_stream, list_of_comp_already_def, THROW_ASSERT, write_comment(), write_module_parametrization_decl(), and write_port_declaration().
Referenced by get_extension().
write_header()
void VHDL_writer::write_header () [override], [virtual]
Write the header of vhdl file.
Reimplemented from language_writer.
Definition at line 1768 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by has_output_prefix().
write_io_signal_post_fix()
void VHDL_writer::write_io_signal_post_fix (const structural_objectRef & port, const structural_objectRef & sig) [override], [virtual]
Write some code managing primary ports to signals connections.
Parameters
port is the primary port for which this problem happens.
sig is the attached signal.
Implements language_writer.
Definition at line 829 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), structural_type_descriptor::BOOL, constant_o_K, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), GET_TYPE_SIZE, port_o::IN, language_writer::indented_output_stream, structural_type_descriptor::INT, may_slice_string(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ASSERT, structural_type_descriptor::UINT, and structural_type_descriptor::VECTOR_BOOL.
Referenced by get_extension().
write_library_declaration()
void VHDL_writer::write_library_declaration (const structural_objectRef & cir) [override], [virtual]
Write used library.
Parameters
cir is the component for which the library declarations are written.
Implements language_writer.
Definition at line 408 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), channel_o_K, component_o_K, structural_object::get_kind(), language_writer::indented_output_stream, NP_functionality::IP_LIBRARY, and THROW_ASSERT.
Referenced by get_extension().
write_module_declaration()
void VHDL_writer::write_module_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of the module.
Parameters
cir is the module to be written.
Implements language_writer.
Definition at line 434 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), structural_object::get_kind(), GET_TYPE_NAME, language_writer::indented_output_stream, list_of_comp_already_def, and THROW_ASSERT.
Referenced by get_extension().
write_module_definition_begin()
void VHDL_writer::write_module_definition_begin (const structural_objectRef & cir) [override], [virtual]
Write the top constructor declaration.
Parameters
cir is the top component to be declared.
Implements language_writer.
Definition at line 574 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), IndentedOutputStream::Indent(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_module_definition_end()
void VHDL_writer::write_module_definition_end (const structural_objectRef & cir) [override], [virtual]
Write the end part in a module declaration.
Parameters
cir is the top component to be declared.
Implements language_writer.
Definition at line 596 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), IndentedOutputStream::Deindent(), structural_object::get_kind(), GET_TYPE_NAME, language_writer::indented_output_stream, and THROW_ASSERT.
Referenced by get_extension().
write_module_instance_begin()
void VHDL_writer::write_module_instance_begin (const structural_objectRef & cir, const std::string & module_name, bool write_parametrization) [override], [virtual]
Write the initial part of the instance of a module.
Parameters
module_name is the name of the module to be instanced. It has to be specified since VHDL and verilog can print in different ways
cir is the module to be instanced.
Implements language_writer.
Definition at line 581 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), language_writer::indented_output_stream, THROW_ASSERT, and write_module_parametrization().
Referenced by get_extension().
write_module_instance_end()
void VHDL_writer::write_module_instance_end (const structural_objectRef & cir) [override], [virtual]
Write the ending part of the instance of a module.
Parameters
cir is the module to be instanced.
Implements language_writer.
Definition at line 591 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_module_internal_declaration()
void VHDL_writer::write_module_internal_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of internal objects of the module.
Parameters
cir is the module to be written.
Implements language_writer.
Definition at line 441 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), structural_object::get_kind(), GET_TYPE_NAME, IndentedOutputStream::Indent(), language_writer::indented_output_stream, and THROW_ASSERT.
Referenced by get_extension().
write_module_parametrization()
void VHDL_writer::write_module_parametrization (const structural_objectRef & cir) [override], [virtual]
Module can be parametrized with respect different features.
Port vectors are parametrized with the number of port associated, while ports are parametrized in case the type is a integer with the number of bits. The id of the module is modified by adding the parameters at its end. For example an AND_GATE with a port_vector of 2 will be declared as: AND_GATE_2. Moreover, a multiplier with the first input of four bits, the second input with eight bits and an output of twelve bits will be declared as: MULT_4_8_12. Note that parametrization has a meaning only in case the functionality come from the STD technology library.
Parameters
cir is the component to be declared.
writing memory-related parameters
Generic of owner module
If we reach this point actual parameter of current module is formal parameter of owner module of type memory Since memory parameters are integer and parameter of current module is std_logic_vector conversion has to be added We need to know the size of the generic (name), but this is not possible examining only the current generic At the moment his pattern has been encountered only in constant_value, so we use information about another generic that we know exist int that module
Implements language_writer.
Definition at line 916 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), BITSIZE_PREFIX, structural_type_descriptor::BOOL, channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_kind(), NP_functionality::get_NP_functionality(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), INDENT_DBG_MEX, language_writer::indented_output_stream, structural_type_descriptor::INT, MEMORY_PARAMETER, NUM_ELEM_PREFIX, structural_type_descriptor::OTHER, port_vector_o_K, PORTSIZE_PREFIX, structural_type_descriptor::REAL, structural_type_descriptor::size, STD_GET_SIZE, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, structural_type_descriptor::type, test_panda::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), and write_module_instance_begin().
write_module_parametrization_decl()
void VHDL_writer::write_module_parametrization_decl (const structural_objectRef & cir) [override], [virtual]
Write the declaration of the module parameters.
writing memory-related parameters
in case first_it is false at least one parameter has used.
Implements language_writer.
Definition at line 1583 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), BITSIZE_PREFIX, structural_type_descriptor::BOOL, channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_id(), structural_object::get_kind(), structural_object::get_kind_text(), NP_functionality::get_NP_functionality(), structural_object::get_typeRef(), INDENT_DBG_MEX, language_writer::indented_output_stream, structural_type_descriptor::INT, MEMORY_PARAMETER, NUM_ELEM_PREFIX, NumberToBinaryString(), structural_type_descriptor::OTHER, port_vector_o_K, PORTSIZE_PREFIX, structural_type_descriptor::REAL, THROW_ASSERT, THROW_UNREACHABLE, TM, structural_type_descriptor::type, test_panda::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), and write_component_declaration().
write_NP_functionalities()
void VHDL_writer::write_NP_functionalities (const structural_objectRef & cir) [override], [virtual]
Write in the proper language the behavioral description of the module described in `Not Parsed` form.
Parameters
cir is the component.
manage reset by preprocessing the behavioral description
Implements language_writer.
Definition at line 1544 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), NP_functionality::get_NP_functionality(), GET_TYPE_NAME, language_writer::indented_output_stream, language_writer::parameters, remove_escaped(), RESET_PORT_NAME, THROW_ASSERT, and NP_functionality::VHDL_PROVIDED.
Referenced by get_extension().
write_port_binding()
void VHDL_writer::write_port_binding (const structural_objectRef & port, const structural_objectRef & top, bool & first_port_analyzed) [override], [virtual]
Write the binding of a port.
It follows the name binding style.
Parameters
port is the port to be bounded.
top is the component owner of the component that has the port to be bounded.
This conversion is needed since vector of bool are mapped on VECTOR_UINT
Implements language_writer.
Definition at line 701 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), structural_type_descriptor::BOOL, constant_o_K, HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_id(), structural_object::get_kind(), structural_type_descriptor::get_name(), structural_object::get_owner(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), port_o::IN, INDENT_DBG_MEX, language_writer::indented_output_stream, structural_type_descriptor::INT, port_o_K, port_vector_o_K, structural_type_descriptor::REAL, structural_type_descriptor::size, STR, THROW_ASSERT, THROW_UNREACHABLE, structural_type_descriptor::type, type_converter(), structural_type_descriptor::UINT, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, and structural_type_descriptor::VECTOR_UINT.
Referenced by get_extension().
write_port_decl_header()
void VHDL_writer::write_port_decl_header () [override], [virtual]
Write the header for port_decl.
Implements language_writer.
Definition at line 1571 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Indent(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_port_decl_tail()
void VHDL_writer::write_port_decl_tail () [override], [virtual]
Write the tail for port_decl.
Implements language_writer.
Definition at line 1577 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_port_declaration()
void VHDL_writer::write_port_declaration (const structural_objectRef & cir, bool last_port_to_analyze) [override], [virtual]
Write the port declaration starting from a port object.
Parameters
cir is the port to be written.
Implements language_writer.
Definition at line 450 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), port_o::GEN, structural_object::get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, language_writer::indented_output_stream, port_o::IO, port_o::OUT, port_o_K, port_vector_o_K, THROW_ASSERT, THROW_ERROR, port_o::TLM_IN, port_o::TLM_INOUT, port_o::TLM_OUT, type_converter(), type_converter_size(), and port_o::UNKNOWN.
Referenced by get_extension(), and write_component_declaration().
write_present_state_update()
void VHDL_writer::write_present_state_update (const structural_objectRef cir, const std::string & reset_state, const std::string & reset_port, const std::string & clock_port, const std::string & reset_type, bool connect_present_next_state_signals) [override], [virtual]
write the present_state update process
Parameters
reset_state is the reset state.
reset_port is the reset port.
clock_port is the clock port.
synch_reset when true the FSM will have an synchronous reset
Implements language_writer.
Definition at line 1173 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), IndentedOutputStream::Indent(), language_writer::indented_output_stream, language_writer::parameters, and write_comment().
Referenced by get_extension().
write_signal_declaration()
void VHDL_writer::write_signal_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of a signal.
Parameters
cir is the signal to be declared.
Implements language_writer.
Definition at line 552 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), structural_type_descriptor::BOOL, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_typeRef(), language_writer::indented_output_stream, signal_o_K, signal_vector_o_K, structural_type_descriptor::size, STR, THROW_UNREACHABLE, structural_type_descriptor::type, type_converter(), type_converter_size(), structural_type_descriptor::VECTOR_BOOL, and structural_type_descriptor::vector_size.
Referenced by get_extension().
write_state_declaration()
void VHDL_writer::write_state_declaration (const structural_objectRef & cir, const std::list< std::string > & list_of_states, const std::string & reset_port, const std::string & reset_state, bool one_hot) [override], [virtual]
write the declaration of all the states of the finite state machine.
Parameters
list_of_states is the list of all the states.
adjust in case states are not consecutives
Implements language_writer.
Definition at line 1128 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), language_writer::bitnumber(), language_writer::encode_one_hot(), language_writer::indented_output_stream, max(), NumberToBinaryString(), language_writer::parameters, STATE_NAME_PREFIX, STR, and write_comment().
Referenced by get_extension().
write_tail()
void VHDL_writer::write_tail (const structural_objectRef & cir) [override], [virtual]
Write the tail part of the file.
Write some lines of comments and some debugging code.
Parameters
cir is the top component.
Implements language_writer.
Definition at line 1124 of file VHDL_writer.cpp.
Referenced by get_extension().
write_transition_output_functions()
void VHDL_writer::write_transition_output_functions (bool single_proc, unsigned int output_index, const structural_objectRef & cir, const std::string & reset_state, const std::string & reset_port, const std::string & start_port, const std::string & clock_port, std::vector< std::string >::const_iterator & first, std::vector< std::string >::const_iterator & end) [override], [virtual]
Write the transition and output functions.
Parameters
cir is the component.
reset_port is the reset port.
clock_port is the clock port.
first if the first iterator of the state table.
end if the end iterator of the state table.
n_states is the number of states.
get the default output of the reset state
set the defaults
get the present state
get the current output
check if we can skip this state or transitions
really useful for one-hot encoding
Implements language_writer.
Definition at line 1218 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, IndentedOutputStream::Deindent(), IndentedOutputStream::Indent(), INDENT_DBG_MEX, language_writer::indented_output_stream, NEXT_STATE_PORT_NAME, NumberToBinaryString(), PRESENT_STATE_PORT_NAME, STR, THROW_ASSERT, THROW_ERROR, and write_comment().
Referenced by get_extension().
write_vector_port_binding()
void VHDL_writer::write_vector_port_binding (const structural_objectRef & port, bool & first_port_analyzed) [override], [virtual]
Implements language_writer.
Definition at line 603 of file VHDL_writer.cpp.
References IndentedOutputStream::Append(), structural_type_descriptor::BOOL, constant_o_K, HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), GET_TYPE_SIZE, INDENT_DBG_MEX, language_writer::indented_output_stream, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, STR, THROW_ASSERT, THROW_UNREACHABLE, and structural_type_descriptor::VECTOR_BOOL.
Referenced by get_extension().
WriteBuiltin()
void VHDL_writer::WriteBuiltin (const structural_objectConstRef component) [override], [virtual]
Write a builtin component.
Parameters
component is the component to be printed
Implements language_writer.
Definition at line 1703 of file VHDL_writer.cpp.
References AND_GATE_STD, IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_TYPE_NAME, INDENT_DBG_MEX, language_writer::indented_output_stream, OR_GATE_STD, port_o_K, port_vector_o_K, STR, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by has_output_prefix().
Field Documentation
keywords
CustomOrderedSet<std::string> VHDL_writer::keywords [protected]
Definition at line 64 of file VHDL_writer.hpp.
Referenced by check_keyword(), and VHDL_writer().
list_of_comp_already_def
CustomOrderedSet<std::string> VHDL_writer::list_of_comp_already_def [protected]
Definition at line 66 of file VHDL_writer.hpp.
Referenced by write_component_declaration(), and write_module_declaration().
TM
const technology_managerConstRef VHDL_writer::TM [protected]
The technology manager.
Definition at line 69 of file VHDL_writer.hpp.
Referenced by write_module_parametrization(), and write_module_parametrization_decl().
tokenNames
const char * VHDL_writer::tokenNames [static], [protected]
Initial value:
= {"abs", "access", "after", "alias", "all", "and", "architecture", "array",
      "assert", "attribute", "begin", "block", "body", "buffer", "bus", "case", "component",
                                         "configuration", "constant", "disconnect", "downto", "else", "
      elsif", "end", "entity", "exit", "file", "for", "function", "generate", "generic"
      , "group", "guarded", "if",
                                         "impure", "in", "inertial", "inout", "is", "
      label", "library", "linkage", "literal", "loop", "map", "mod", "nand", "new",
        "next", "nor", "not",
                                         "null", "of", "on", "open", "or", "
      others", "out", "package", "port", "postponed", "procedure", "process", "pure", "range",
        "record", "register", "reject",
                                         "rem", "return", "rol", "ror", "select", "
      severity", "signal", "shared", "sla", "sli", "sra", "srl", "subtype", "then",
        "to", "transport", "type",
                                         "unaffected", "units", "until", "use", "variable", "
      wait", "when", "while", "with", "xnor", "xor"}
Autoheader include.
. include HLS/stg include STL include technology/physical_library include utility include
Definition at line 63 of file VHDL_writer.hpp.
Referenced by VHDL_writer().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/writer/VHDL_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/writer/VHDL_writer.cpp