/home/osboxes/bambu/PandA-bambu/src/HLS/interface/WB4/WB4Intercon_interface.cpp File Reference
Implementation of WB4Intercon_interface.
#include `WB4Intercon_interface.hpp`
#include `Parameter.hpp`
#include `behavioral_helper.hpp`
#include `call_graph_manager.hpp`
#include `copyrights_strings.hpp`
#include `hls.hpp`
#include `hls_manager.hpp`
#include `hls_target.hpp`
#include `memory.hpp`
#include `memory_symbol.hpp`
#include `structural_manager.hpp`
#include `structural_objects.hpp`
#include `technology_manager.hpp`
#include `technology_wishbone.hpp`
#include `tree_helper.hpp`
Functions
static void build_bus_interface (structural_managerRef SM, const hlsRef HLS, const HLS_managerRef HLSMgr)
static void buildCircuit (structural_managerRef SM, structural_objectRef wrappedObj, structural_objectRef interfaceObj, const hlsRef HLS, const HLS_managerRef HLSMgr)
static unsigned int get_data_bus_bitsize (const hlsRef HLS, const HLS_managerRef HLSMgr)
static unsigned int get_addr_bus_bitsize (const HLS_managerRef HLSMgr)
Detailed Description
Implementation of WB4Intercon_interface.
Author
Marco Minutoli mminutoli@gmail.com
Function Documentation
build_bus_interface()
static void build_bus_interface (structural_managerRef SM, const hlsRef HLS, const HLS_managerRef HLSMgr) [static]
Definition at line 128 of file WB4Intercon_interface.cpp.
References memory::add_memory_parameter(), CLOCK_PORT_NAME, WB4_interface::get_addr_bus_bitsize(), WB4_interface::get_data_bus_bitsize(), port_o::IN, tree_helper::name_function(), port_o::OUT, RESET_PORT_NAME, STR, WB_ACKIM_PORT_NAME, WB_ACKOS_PORT_NAME, WB_ADDRIS_PORT_NAME, WB_ADDROM_PORT_NAME, WB_BASE_ADDRESS, WB_CYCIS_PORT_NAME, WB_CYCOM_PORT_NAME, WB_DATIM_PORT_NAME, WB_DATIS_PORT_NAME, WB_DATOM_PORT_NAME, WB_DATOS_PORT_NAME, WB_SELIS_PORT_NAME, WB_SELOM_PORT_NAME, WB_STBIS_PORT_NAME, WB_STBOM_PORT_NAME, WB_WEIS_PORT_NAME, and WB_WEOM_PORT_NAME.
Referenced by WB4Intercon_interface::exec(), and WB4Intercon_interface::WB4Intercon_interface().
buildCircuit()
static void buildCircuit (structural_managerRef SM, structural_objectRef wrappedObj, structural_objectRef interfaceObj, const hlsRef HLS, const HLS_managerRef HLSMgr) [static]
Definition at line 174 of file WB4Intercon_interface.cpp.
References CLOCK_PORT_NAME, structural_object::find_member(), structural_object::get_id(), structural_object::get_typeRef(), tree_helper::name_function(), port_o::OUT, port_o_K, RESET_PORT_NAME, structural_object::set_type(), structural_object::SetParameter(), STR, WB4_INTERCON, WB_BASE_ADDRESS, WB_CYCOM_PORT_NAME, WB_IRQ_PORT_NAME, WBLIBRARY, and WORK_LIBRARY.
Referenced by WB4Intercon_interface::exec(), and WB4Intercon_interface::WB4Intercon_interface().
get_addr_bus_bitsize()
static unsigned int get_addr_bus_bitsize (const HLS_managerRef HLSMgr) [static]
Definition at line 117 of file WB4Intercon_interface.cpp.
References max().
get_data_bus_bitsize()
static unsigned int get_data_bus_bitsize (const hlsRef HLS, const HLS_managerRef HLSMgr) [static]
Definition at line 100 of file WB4Intercon_interface.cpp.
References max(), and DesignFlowStep::parameters.