xml_ite_block_t Class Reference
If/Then/Else block, evaluated at compile-time.
#include <xml_script_command.hpp>
Public Member Functions
xml_ite_block_t (const std::string *_condition)
xml_ite_block_t (const xml_element *element)
std::string get_xml_name () const override
Gets the XML element name of this node type.
xml_nodeRef create_xml_node () const override
Creates an XML node for polixml data structures.
~xml_ite_block_t () override
void clean () override
Cleans object attributes.
bool checkCondition (const DesignParametersRef &dp) const override
If the node has a compile-time condition, this method evaluates it.
Data Fields
std::string condition
std::vector< xml_script_node_tRef > thenNodes
std::vector< xml_script_node_tRef > elseNodes
Additional Inherited Members
Detailed Description
If/Then/Else block, evaluated at compile-time.
Definition at line 280 of file xml_script_command.hpp.
Constructor & Destructor Documentation
xml_ite_block_t() [1/2]
xml_ite_block_t::xml_ite_block_t (const std::string * _condition) [explicit]
Definition at line 739 of file xml_script_command.cpp.
References elseNodes, and thenNodes.
xml_ite_block_t() [2/2]
xml_ite_block_t::xml_ite_block_t (const xml_element * element) [explicit]
Definition at line 745 of file xml_script_command.cpp.
References xml_script_node_t::create(), el, elseNodes, xml_child::get_children(), xml_node::get_name(), thenNodes, and THROW_ERROR.
 xml_ite_block_t()
xml_ite_block_t::~xml_ite_block_t () [override]
Definition at line 803 of file xml_script_command.cpp.
References clean().
Member Function Documentation
checkCondition()
bool xml_ite_block_t::checkCondition (const DesignParametersRef & dp) const [override], [virtual]
If the node has a compile-time condition, this method evaluates it.
Parameters
dp Design parameters, used to check conditions at compile time.
Returns
The condition evaluation if any, otherwise is true by default.
Reimplemented from xml_script_node_t.
Definition at line 836 of file xml_script_command.cpp.
References condition, and xml_script_node_t::evaluate_condition().
clean()
void xml_ite_block_t::clean () [override], [virtual]
Cleans object attributes.
Implements xml_script_node_t.
Definition at line 808 of file xml_script_command.cpp.
References elseNodes, and thenNodes.
Referenced by ~xml_ite_block_t().
create_xml_node()
xml_nodeRef xml_ite_block_t::create_xml_node () const [override], [virtual]
Creates an XML node for polixml data structures.
Implements xml_script_node_t.
Definition at line 819 of file xml_script_command.cpp.
References xml_child::add_child_element(), condition, elseNodes, get_xml_name(), attribute_sequence::set_attribute(), and thenNodes.
get_xml_name()
std::string xml_ite_block_t::get_xml_name () const [override], [virtual]
Gets the XML element name of this node type.
Implements xml_script_node_t.
Definition at line 814 of file xml_script_command.cpp.
References TAG_ITE_BLOCK.
Referenced by create_xml_node().
Field Documentation
condition
std::string xml_ite_block_t::condition
Definition at line 283 of file xml_script_command.hpp.
Referenced by checkCondition(), create_xml_node(), NanoXploreWrapper::toString(), LatticeWrapper::toString(), AlteraWrapper::toString(), and SynopsysWrapper::toString().
elseNodes
std::vector<xml_script_node_tRef> xml_ite_block_t::elseNodes
Definition at line 285 of file xml_script_command.hpp.
Referenced by clean(), create_xml_node(), NanoXploreWrapper::toString(), LatticeWrapper::toString(), AlteraWrapper::toString(), SynopsysWrapper::toString(), and xml_ite_block_t().
thenNodes
std::vector<xml_script_node_tRef> xml_ite_block_t::thenNodes
Definition at line 284 of file xml_script_command.hpp.
Referenced by clean(), create_xml_node(), NanoXploreWrapper::toString(), LatticeWrapper::toString(), AlteraWrapper::toString(), SynopsysWrapper::toString(), and xml_ite_block_t().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xml_script_command.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xml_script_command.cpp