structural_object Class Reference
Base object for all the structural objects.
#include <structural_objects.hpp>
Public Member Functions
structural_object (int debug_level, const structural_objectRef o)
Constructor for the structural_object.
virtual ~structural_object ()
virtual destructor
const structural_objectRef get_owner () const
Return the owner.
void set_owner (const structural_objectRef new_owner)
set the owner of the structural object
void set_treenode (unsigned int n)
Set the treenode id associated with the structural_object.
unsigned int get_treenode () const
Return the treenode id associated with the structural_object.
void set_id (const std::string &s)
Set the identifier associated with the structural_object.
const std::string get_id () const
Return the identifier associated with the structural_object.
void set_type (const structural_type_descriptorRef &s)
Set the type of the structural_object.
const structural_type_descriptorRef & get_typeRef () const
Return the type descriptor of the structural_object.
void type_resize (unsigned int new_bit_size)
Just resize the size of the bits of the object.
void type_resize (unsigned int new_bit_size, unsigned int new_vec_size)
resizing of vector objects
void set_black_box (bool bb)
Set the black box property associated with the structural_object.
bool get_black_box () const
Return the black box property.
void SetParameter (const std::string &name, const std::string &value)
Set a parameter value.
bool ExistsParameter (std::string name) const
Check if a parameter has been specified.
std::string GetParameter (std::string name) const
Get the value associated to parameter if it has been associated; if it has not specified returns the default.
std::string GetDefaultParameter (std::string name) const
Get the value associated to parameter if it has been associate; It throws an exception if it has not been associated.
CustomMap< std::string, std::string > GetParameters ()
return the whole set of parameters
virtual void AddParameter (const std::string &name, const std::string &default_value)
Add a parameter.
const std::string get_path () const
Return a unique identifier of the structural object.
virtual void copy (structural_objectRef dest) const
Perform a copy of the structural object.
virtual structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const =0
Return the object named id of a given type which belongs to or it is associated with the object.
virtual structural_objectRef find_isomorphic (const structural_objectRef key) const =0
Find key in this object.
virtual void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM)
Load a structural_object starting from an xml file.
virtual void xwrite (xml_element *rootnode)
Add a structural_object to an xml tree.
virtual void print (std::ostream &os) const
Print the structural_object (for debug purpose)
virtual std::string get_kind_text () const =0
Virtual function used to get the string name of a structural_object instance.
virtual enum so_kind get_kind () const =0
Virtual function used to find the real type of a structural_object instance.
Protected Member Functions
std::string convert_so_short (so_kind in) const
Convert a so_kind in a short string.
Protected Attributes
int debug_level
debug level for the object
Static Protected Attributes
static simple_indent PP
pretty print functor object used by all print members to indent the output of the print function.
Private Attributes
Wrefcount< structural_object > owner
The owner of the object.
std::string id
Identifier for this component.
structural_type_descriptorRef type
The description of the type.
unsigned int treenode
index of the treenode in the tree_manager associated with the structural object.
bool black_box
True if the structural object is a black box (e.g., a library component).
CustomMap< std::string, std::string > parameters
Map between parameter string and related values of an instance.
CustomMap< std::string, std::string > default_parameters
Map between parameter string and its default value.
Static Private Attributes
 default values associated with the members of the structural_type_descriptor class.
static const unsigned int treenode_DEFAULT = 0
static const bool black_box_DEFAULT = true
Friends
std::ostream & operator<< (std::ostream &os, const structural_objectRef o)
Friend definition of the << operator.
Detailed Description
Base object for all the structural objects.
It provides a common interface for each structural object present in a design.
Definition at line 344 of file structural_objects.hpp.
Constructor & Destructor Documentation
structural_object()
structural_object::structural_object (int debug_level, const structural_objectRef o)
Constructor for the structural_object.
------------- structural object methods --------------------- //
Parameters
o is the owner (null object for the top object).
Definition at line 542 of file structural_objects.cpp.
 structural_object()
virtual structural_object::~structural_object () [inline], [virtual]
virtual destructor
Definition at line 422 of file structural_objects.hpp.
References structural_type_descriptor::copy(), get_id(), structural_type_descriptor::print(), structural_type_descriptor::xload(), and structural_type_descriptor::xwrite().
Member Function Documentation
AddParameter()
void structural_object::AddParameter (const std::string & name, const std::string & default_value) [virtual]
Add a parameter.
Parameters
name is the name of the parameter
default_value is the default of the value
Reimplemented in module.
Definition at line 725 of file structural_objects.cpp.
References default_parameters, and THROW_ASSERT.
Referenced by top_entity_cs::add_context_switch_port_kernel(), memory::add_memory_parameter(), datapath_cs::add_ports(), module::AddParameter(), TasteInterfaceGeneration::InternalExec(), and memory::propagate_memory_parameters().
convert_so_short()
std::string structural_object::convert_so_short (so_kind in) const [inline], [protected]
Convert a so_kind in a short string.
Used in debugging.
Definition at line 374 of file structural_objects.hpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, and THROW_UNREACHABLE.
Referenced by port_o::print(), constant_o::print(), signal_o::print(), channel_o::print(), and bus_connection_o::print().
copy()
void structural_object::copy (structural_objectRef dest) const [virtual]
Perform a copy of the structural object.
Parameters
dest destination object.
the owner has to be already set.
Reimplemented in bus_connection_o, channel_o, component_o, module, signal_o, constant_o, action_o, data_o, event_o, and port_o.
Definition at line 681 of file structural_objects.cpp.
References black_box, structural_type_descriptor::copy(), debug_level, default_parameters, id, parameters, treenode, and type.
Referenced by fu_binding::add_gate(), moduleGenerator::add_port_parameters(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), fu_binding::add_to_SM(), port_o::copy(), event_o::copy(), data_o::copy(), action_o::copy(), constant_o::copy(), signal_o::copy(), module::copy(), bus_connection_o::copy(), and structural_manager::INIT().
ExistsParameter()
bool structural_object::ExistsParameter (std::string name) const
Check if a parameter has been specified.
Parameters
name is parameter name
Definition at line 796 of file structural_objects.cpp.
References default_parameters.
Referenced by memory::add_memory_parameter(), RTLCharacterization::AnalyzeCell(), fu_binding::check_parametrization(), memory::propagate_memory_parameters(), fu_binding_cs::set_atomic_memory_parameter(), fu_binding::specialise_fu(), and TestbenchGenerationBaseStep::write_auxiliary_signal_declaration().
find_isomorphic()
virtual structural_objectRef structural_object::find_isomorphic (const structural_objectRef key) const [pure virtual]
Find key in this object.
Parameters
key is the object searched.
Implemented in bus_connection_o, channel_o, component_o, module, signal_o, constant_o, action_o, data_o, event_o, and port_o.
Referenced by port_o::find_isomorphic(), constant_o::find_isomorphic(), signal_o::find_isomorphic(), and channel_o::find_isomorphic().
find_member()
virtual structural_objectRef structural_object::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [pure virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implemented in bus_connection_o, channel_o, component_o, module, signal_o, constant_o, action_o, data_o, event_o, and port_o.
Referenced by conn_binding::add_command_ports(), top_entity::add_command_signals(), structural_manager::add_connection(), top_entity_cs::add_context_switch_port(), top_entity_cs::add_context_switch_port_kernel(), fu_binding::add_gate(), top_entity_cs::add_input_register(), top_entity::add_input_register(), RTLCharacterization::add_input_register(), RTLCharacterization::add_output_register(), top_entity::add_ports(), classic_datapath::add_ports(), ParallelMemoryConnBinding::add_to_SM(), reg_binding::add_to_SM(), StateTransitionGraphManager::add_to_SM(), fu_binding::add_to_SM(), module_interface::AddConnection(), module_interface::AddConstant(), module_interface::AddSignal(), RTLCharacterization::AnalyzeCell(), WB4_interface::build_WB4_complete_logic(), minimal_interface::build_wrapper(), buildCircuit(), allocation::BuildProxyFunctionVerilog(), allocation::BuildProxyFunctionVHDL(), allocation::BuildProxyWrapper(), top_entity_parallel_cs::BW_loop_iter(), structural_manager::check_object(), fu_binding::check_parametrization(), datapath_parallel_cs::connect_i_module_kernel(), top_entity_parallel_cs::connect_loop_iter(), datapath_parallel_cs::connect_module_kernel(), top_entity_parallel_cs::connect_port_parallel(), fu_binding_cs::connect_selector(), fu_binding_cs::connect_selector_kernel(), WB4_interface::connect_with_signal(), WB4_interface::connect_with_signal_name(), connectClockAndReset(), conn_binding_cs::connectOutOr(), fsm_controller::create_state_machine(), HWDiscrepancyAnalysis::Exec(), TopEntityMemoryMapped::forwardPorts(), TopEntityMemoryMapped::insertMemoryMappedRegister(), TopEntityMemoryMapped::insertStartDoneLogic(), TopEntityMemoryMapped::insertStatusRegister(), fu_binding_cs::instantiate_component_kernel(), datapath_parallel_cs::instantiate_component_parallel(), cs_interface::instantiate_component_parallel(), conn_binding_cs::instantiate_suspension_component(), cs_interface::InternalExec(), TasteInterfaceGeneration::InternalExec(), top_entity_parallel_cs::InternalExec(), classic_datapath::InternalExec(), top_entity::InternalExec(), datapath_parallel_cs::InternalExec(), fu_binding::kill_proxy_memory_units(), fu_binding::manage_extern_global_port(), datapath_parallel_cs::manage_extern_global_port_parallel(), cs_interface::manage_extern_global_port_top(), fu_binding::manage_killing_function_proxies(), fu_binding::manage_killing_memory_proxies(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), fu_binding::manage_memory_ports_chained(), fu_binding::manage_memory_ports_parallel_chained(), ParallelMemoryFuBinding::manage_module_ports(), conn_binding::mux_allocation(), top_entity_parallel_cs::resize_controller_parallel(), StateTransitionGraphManager::specialise_mu(), reg_binding_cs::specialise_reg(), HDL_manager::write_fsm(), and signal_o::xload().
get_black_box()
bool structural_object::get_black_box () const
Return the black box property.
Definition at line 704 of file structural_objects.cpp.
References black_box.
Referenced by module::set_NP_functionality(), HDL_manager::write_module(), and module::xload().
get_id()
const std::string structural_object::get_id () const
Return the identifier associated with the structural_object.
Definition at line 591 of file structural_objects.cpp.
References id.
Referenced by conn_binding::add_command_ports(), top_entity::add_command_signals(), structural_manager::add_connection(), conn_binding::add_datapath_connection(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), fu_binding::add_to_SM(), conn_binding::add_to_SM(), module_interface::AddConnection(), module_interface::AddConstant(), module::AddParameter(), module_interface::AddSignal(), RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::AnalyzeFu(), minimal_interface::build_wrapper(), buildCircuit(), allocation::BuildProxyFunctionVerilog(), allocation::BuildProxyFunctionVHDL(), allocation::BuildProxyWrapper(), module::change_port_direction(), structural_manager::check_structure(), computeResources(), fu_binding_cs::connect_selector_kernel(), WB4_interface::connect_with_signal(), HWDiscrepancyAnalysis::Exec(), WB4Intercon_interface::exec(), GenerateSimulationScripts::Exec(), port_o::find_bounded_object(), port_o::find_isomorphic(), constant_o::find_isomorphic(), signal_o::find_isomorphic(), channel_o::find_isomorphic(), port_o::fix_port_properties(), moduleGenerator::GenerateHDL(), BackendFlow::GenerateSynthesisScripts(), get_path(), get_typeRef(), TestbenchGenerationBaseStep::Initialize(), TestbenchGenerationBaseStep::initialize_input_signals(), conn_binding_cs::instantiate_suspension_component(), cs_interface::InternalExec(), minimal_interface::InternalExec(), TopEntityMemoryMapped::InternalExec(), WB4_interface::InternalExec(), allocation::InternalExec(), fu_binding::kill_proxy_function_units(), fu_binding::manage_killing_function_proxies(), fu_binding::manage_killing_memory_proxies(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), conn_binding::mux_connection(), cg_edge_info::print(), structural_manager::print(), propagateInterface(), module::remove_port(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), TestbenchGenerationBaseStep::write_hdl_testbench(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), VHDL_writer::write_io_signal_post_fix(), verilog_writer::write_io_signal_post_fix(), HDL_manager::write_module(), TestbenchGenerationBaseStep::write_module_begin(), verilog_writer::write_module_instance_begin(), VHDL_writer::write_module_instance_begin(), VHDL_writer::write_module_parametrization_decl(), verilog_writer::write_port_binding(), VHDL_writer::write_port_binding(), verilog_writer::write_port_declaration(), VHDL_writer::write_port_declaration(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), verilog_writer::write_vector_port_binding(), VHDL_writer::write_vector_port_binding(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), port_o::xload(), signal_o::xload(), module::xload(), port_o::xwrite(), and module::xwrite().
get_kind()
virtual enum so_kind structural_object::get_kind () const [pure virtual]
Virtual function used to find the real type of a structural_object instance.
Returns
a so_kind enum identifying the object type.
Implemented in signal_o, and port_o.
Referenced by conn_binding::add_command_ports(), structural_manager::add_connection(), port_o::add_connection(), constant_o::add_connection(), structural_manager::add_constant(), conn_binding::add_datapath_connection(), add_directed_edge(), add_directed_edge_single(), structural_manager::add_NP_functionality(), structural_manager::add_port(), structural_manager::add_port_vector(), top_entity::add_ports(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), structural_manager::add_sign(), structural_manager::add_sign_vector(), fu_binding::add_to_SM(), conn_binding::add_to_SM(), RTLCharacterization::AnalyzeCell(), structural_manager::build_graph(), minimal_interface::build_wrapper(), structural_manager::change_connection(), structural_manager::change_port_direction(), computeResources(), WB4_interface::connect_with_signal_name(), port_o::find_isomorphic(), constant_o::find_isomorphic(), signal_o::find_isomorphic(), port_o::fix_port_properties(), HDL_manager::get_post_order_structural_components(), structural_manager::INIT(), TestbenchGenerationBaseStep::init_extra_signals(), TasteInterfaceGeneration::InternalExec(), HDL_manager::io_signal_fix_ith(), fu_binding::manage_extern_global_port(), datapath_parallel_cs::manage_extern_global_port_parallel(), cs_interface::manage_extern_global_port_top(), fu_binding::manage_killing_function_proxies(), fu_binding::manage_killing_memory_proxies(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), fu_binding::manage_memory_ports_chained(), fu_binding::manage_memory_ports_parallel_chained(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), conn_binding::mux_connection(), cg_edge_info::print(), structural_manager::reconnect_signal_member(), structural_manager::remove_module(), port_o::resize_busport(), port_o::resize_std_port(), TopEntityMemoryMapped::resizing_IO(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), RTLCharacterization::specialize_fu(), port_o::substitute_connection(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), VHDL_writer::write_io_signal_post_fix(), verilog_writer::write_io_signal_post_fix(), VHDL_writer::write_library_declaration(), MinimalInterfaceTestbench::write_memory_handler(), VHDL_writer::write_module_declaration(), VHDL_writer::write_module_definition_end(), verilog_writer::write_module_instance_begin(), VHDL_writer::write_module_instance_begin(), VHDL_writer::write_module_internal_declaration(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), VHDL_writer::write_module_parametrization_decl(), verilog_writer::write_module_parametrization_decl(), verilog_writer::write_port_binding(), VHDL_writer::write_port_binding(), verilog_writer::write_port_declaration(), VHDL_writer::write_port_declaration(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), MinimalInterfaceTestbench::write_signals(), verilog_writer::write_vector_port_binding(), VHDL_writer::write_vector_port_binding(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), and signal_o::xload().
get_kind_text()
virtual std::string structural_object::get_kind_text () const [pure virtual]
Virtual function used to get the string name of a structural_object instance.
Returns
a string identifying the object type.
Implemented in signal_o, and port_o.
Referenced by structural_manager::add_connection(), port_o::add_connection(), constant_o::add_connection(), add_directed_edge(), top_entity::add_ports(), structural_manager::build_graph(), structural_manager::change_connection(), signal_o::find_member(), port_o::fix_port_properties(), cs_interface::manage_extern_global_port_top(), structural_manager::reconnect_signal_member(), VHDL_writer::write_component_declaration(), VHDL_writer::write_module_parametrization_decl(), event_o::xwrite(), data_o::xwrite(), action_o::xwrite(), constant_o::xwrite(), component_o::xwrite(), channel_o::xwrite(), and bus_connection_o::xwrite().
get_owner()
const structural_objectRef structural_object::get_owner () const
Return the owner.
Definition at line 546 of file structural_objects.cpp.
References Wrefcount< T >::lock(), and owner.
Referenced by conn_binding::add_command_ports(), structural_manager::add_connection(), port_o::add_connection(), conn_binding::add_datapath_connection(), add_directed_edge(), add_directed_edge_single(), conn_binding::add_to_SM(), minimal_interface::build_wrapper(), structural_manager::change_connection(), structural_manager::check_structure(), port_o::find_bounded_object(), port_o::find_isomorphic(), constant_o::find_isomorphic(), signal_o::find_isomorphic(), channel_o::find_isomorphic(), port_o::fix_port_properties(), port_o::get_connected_signal(), get_path(), GetParameters(), HDL_manager::io_signal_fix_ith(), signal_o::is_full_connected(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), cg_edge_info::print(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), VHDL_writer::write_io_signal_post_fix(), verilog_writer::write_io_signal_post_fix(), verilog_writer::write_port_binding(), VHDL_writer::write_port_binding(), verilog_writer::write_vector_port_binding(), VHDL_writer::write_vector_port_binding(), and signal_o::xload().
get_path()
const std::string structural_object::get_path () const
Return a unique identifier of the structural object.
It is composed by the identifier of the current structural object and by its owners separated by the HIERARCHY_SEPARATOR. Structural objects are viewed as elements of a standard filesystem.
Definition at line 882 of file structural_objects.cpp.
References get_id(), get_owner(), get_path(), HIERARCHY_SEPARATOR, port_o::port_directionNames, and port_o::port_interfaceNames.
Referenced by conn_binding::add_command_ports(), structural_manager::add_connection(), port_o::add_connection(), structural_manager::add_constant(), conn_binding::add_datapath_connection(), module::add_internal_object(), port_o::add_n_ports(), structural_manager::add_port(), structural_manager::add_port_vector(), structural_manager::add_sign(), structural_manager::add_sign_vector(), conn_binding::add_sparse_logic_dp(), module_interface::AddConnection(), module_interface::AddConstant(), module_interface::AddSignal(), structural_manager::build_graph(), WB4_interface::connect_with_signal_name(), port_o::copy(), signal_o::copy(), module::copy(), structural_manager::create(), HWDiscrepancyAnalysis::Exec(), port_o::find_bounded_object(), module::find_isomorphic(), port_o::fix_port_properties(), port_o::get_connected_signal(), module::get_in_port(), get_path(), port_o::get_port(), port_o::get_ports_size(), signal_o::get_signal(), TasteInterfaceGeneration::InternalExec(), add_library::InternalExec(), cs_interface::manage_extern_global_port_top(), conn_binding::mux_allocation(), conn_binding::mux_connection(), jms_sorter::operator()(), print(), structural_manager::reconnect_signal_member(), port_o::remove_connection(), module::remove_port(), port_o::resize_std_port(), fu_binding::specialise_fu(), StateTransitionGraphManager::specialise_mu(), conn_binding::specialise_mux(), reg_binding::specialise_reg(), port_o::substitute_connection(), VHDL_writer::type_converter_size(), type_resize(), VHDL_writer::write_component_declaration(), HDL_manager::write_module(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), verilog_writer::write_port_binding(), VHDL_writer::write_port_binding(), verilog_writer::write_vector_port_binding(), module::xload(), and xwrite().
get_treenode()
unsigned int structural_object::get_treenode () const
Return the treenode id associated with the structural_object.
Definition at line 581 of file structural_objects.cpp.
References treenode.
get_typeRef()
const structural_type_descriptorRef & structural_object::get_typeRef () const
Return the type descriptor of the structural_object.
Definition at line 601 of file structural_objects.cpp.
References get_id(), THROW_ASSERT, and type.
Referenced by top_entity::add_command_signals(), structural_manager::add_connection(), conn_binding::add_datapath_connection(), top_entity_cs::add_input_register(), top_entity::add_input_register(), RTLCharacterization::add_input_register(), port_o::add_n_ports(), signal_o::add_n_signals(), RTLCharacterization::add_output_register(), cs_interface::add_parameter_port(), moduleGenerator::add_port_parameters(), top_entity::add_ports(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), module_interface::add_sign(), module_interface::add_sign_vector(), ParallelMemoryFuBinding::add_to_SM(), fu_binding::add_to_SM(), conn_binding::add_to_SM(), module_interface::AddSignal(), RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::AnalyzeFu(), structural_manager::build_graph(), WB4_interface::build_WB4_complete_logic(), minimal_interface::build_wrapper(), buildCircuit(), allocation::BuildProxyWrapper(), structural_manager::check_type(), computeResources(), WB4_interface::connect_with_signal_name(), connect_with_signal_name(), module::copy(), AllocationInformation::estimate_call_delay(), WB4Intercon_interface::exec(), port_o::fix_port_properties(), moduleGenerator::GenerateHDL(), module::get_in_port(), port_o::get_port_size(), GetParameter(), GetParameters(), TestbenchGenerationBaseStep::initialize_input_signals(), TopEntityMemoryMapped::insertMemoryMappedRegister(), TopEntityMemoryMapped::insertStatusRegister(), cs_interface::InternalExec(), minimal_interface::InternalExec(), TopEntityMemoryMapped::InternalExec(), top_entity::InternalExec(), WB4_interface::InternalExec(), add_library::InternalExec(), fu_binding::join_merge_split(), fu_binding::manage_extern_global_port(), datapath_parallel_cs::manage_extern_global_port_parallel(), cs_interface::manage_extern_global_port_top(), fu_binding::manage_killing_function_proxies(), fu_binding::manage_killing_memory_proxies(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), fu_binding::manage_memory_ports_chained(), fu_binding::manage_memory_ports_parallel_chained(), ParallelMemoryFuBinding::manage_module_ports(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), conn_binding::mux_allocation(), propagateInterface(), RTLCharacterization::resize_port(), port_o::set_port_size(), SetParameter(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_memory_handler(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), VHDL_writer::write_module_parametrization_decl(), verilog_writer::write_module_parametrization_decl(), TestbenchGenerationBaseStep::write_output_checks(), VHDL_writer::write_port_binding(), verilog_writer::write_port_declaration(), VHDL_writer::write_port_declaration(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), MinimalInterfaceTestbench::write_signals(), verilog_writer::write_timing_specification(), TestbenchGenerationBaseStep::write_verilator_testbench(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), module::xload(), and port_o::xwrite().
GetDefaultParameter()
std::string structural_object::GetDefaultParameter (std::string name) const
Get the value associated to parameter if it has been associate; It throws an exception if it has not been associated.
Parameters
name is parameter name
Returns
parameter value
Definition at line 731 of file structural_objects.cpp.
References default_parameters, and THROW_ASSERT.
GetParameter()
std::string structural_object::GetParameter (std::string name) const
Get the value associated to parameter if it has been associated; if it has not specified returns the default.
Parameters
name is parameter name
Returns
parameter value
Definition at line 715 of file structural_objects.cpp.
References default_parameters, get_typeRef(), structural_type_descriptor::id_type, parameters, and THROW_ASSERT.
Referenced by memory::add_memory_parameter(), memory::propagate_memory_parameters(), fu_binding::specialise_fu(), and TestbenchGenerationBaseStep::write_auxiliary_signal_declaration().
GetParameters()
CustomMap< std::string, std::string > structural_object::GetParameters ()
return the whole set of parameters
Returns
the whole set of parameters
Definition at line 737 of file structural_objects.cpp.
References default_parameters, functional_unit_K, functional_unit_template_K, technology_node::get_kind(), get_owner(), get_typeRef(), structural_type_descriptor::id_type, structural_type_descriptor::INT, structural_type_descriptor::OTHER, parameters, THROW_UNREACHABLE, structural_type_descriptor::UNKNOWN, and structural_type_descriptor::VECTOR_BOOL.
print()
void structural_object::print (std::ostream & os) const [virtual]
Print the structural_object (for debug purpose)
Parameters
os is an output stream
Reimplemented in bus_connection_o, channel_o, component_o, module, signal_o, constant_o, action_o, data_o, event_o, and port_o.
Definition at line 872 of file structural_objects.cpp.
References black_box, get_path(), PP, treenode, and type.
Referenced by conn_binding::mux_connection(), port_o::print(), event_o::print(), data_o::print(), action_o::print(), constant_o::print(), signal_o::print(), module::print(), bus_connection_o::print(), and verilog_writer::write_module_parametrization().
set_black_box()
void structural_object::set_black_box (bool bb)
Set the black box property associated with the structural_object.
Parameters
bb is true when the object is a black box, false otherwise. The black box property has mean only in case of components and channels.
Definition at line 699 of file structural_objects.cpp.
References black_box.
Referenced by module::add_internal_object(), fsm_controller::InternalExec(), TasteInterfaceGeneration::InternalExec(), top_entity_parallel_cs::InternalExec(), classic_datapath::InternalExec(), top_entity::InternalExec(), datapath_parallel_cs::InternalExec(), and module::set_NP_functionality().
set_id()
void structural_object::set_id (const std::string & s)
Set the identifier associated with the structural_object.
Parameters
s is a string identifying the structural_object.
Definition at line 586 of file structural_objects.cpp.
Referenced by fu_binding::add_gate(), port_o::add_n_ports(), signal_o::add_n_signals(), fu_binding::add_to_SM(), allocation::BuildProxyWrapper(), WB4Intercon_interface::exec(), functional_unit::get_operation(), cs_interface::InternalExec(), minimal_interface::InternalExec(), TasteInterfaceGeneration::InternalExec(), TopEntityMemoryMapped::InternalExec(), WB4_interface::InternalExec(), constant_o::xload(), and signal_o::xload().
set_owner()
void structural_object::set_owner (const structural_objectRef new_owner)
set the owner of the structural object
Parameters
new_owner is the owner (null object for the top object).
Definition at line 551 of file structural_objects.cpp.
References owner, and THROW_ASSERT.
Referenced by WB4Intercon_interface::exec(), cs_interface::InternalExec(), minimal_interface::InternalExec(), TasteInterfaceGeneration::InternalExec(), top_entity_parallel_cs::InternalExec(), TopEntityMemoryMapped::InternalExec(), top_entity::InternalExec(), and WB4_interface::InternalExec().
set_treenode()
void structural_object::set_treenode (unsigned int n)
Set the treenode id associated with the structural_object.
Parameters
n is the treenode id.
Definition at line 576 of file structural_objects.cpp.
References treenode.
set_type()
void structural_object::set_type (const structural_type_descriptorRef & s)
Set the type of the structural_object.
Parameters
s is a type descriptor of a structural_object.
Definition at line 596 of file structural_objects.cpp.
References type.
Referenced by port_o::add_n_ports(), signal_o::add_n_signals(), buildCircuit(), top_entity_parallel_cs::connect_loop_iter(), functional_unit::get_operation(), TopEntityMemoryMapped::insertStatusRegister(), conn_binding_cs::instantiate_suspension_component(), and TopEntityMemoryMapped::InternalExec().
SetParameter()
void structural_object::SetParameter (const std::string & name, const std::string & value)
Set a parameter value.
Parameters
name is parameter name
value is parameter value
Definition at line 709 of file structural_objects.cpp.
References default_parameters, get_typeRef(), structural_type_descriptor::id_type, parameters, and THROW_ASSERT.
Referenced by memory::add_memory_parameter(), classic_datapath::add_ports(), fu_binding::add_to_SM(), RTLCharacterization::AnalyzeCell(), WB4_interface::build_WB4_complete_logic(), minimal_interface::build_wrapper(), buildCircuit(), fu_binding::fill_array_ref_memory(), TasteInterfaceGeneration::InternalExec(), memory::propagate_memory_parameters(), fu_binding_cs::set_atomic_memory_parameter(), structural_manager::SetParameter(), and fu_binding::specialise_fu().
type_resize() [1/2]
void structural_object::type_resize (unsigned int new_bit_size)
Just resize the size of the bits of the object.
Definition at line 607 of file structural_objects.cpp.
References structural_type_descriptor::BOOL, get_path(), structural_type_descriptor::id_type, structural_type_descriptor::INT, structural_type_descriptor::OTHER, structural_type_descriptor::REAL, structural_type_descriptor::size, THROW_ASSERT, THROW_ERROR, structural_type_descriptor::type, type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by conn_binding::add_datapath_connection(), classic_datapath::add_ports(), fu_binding::add_to_SM(), minimal_interface::build_wrapper(), fu_binding_cs::connect_selector_kernel(), TasteInterfaceGeneration::InternalExec(), fu_binding::join_merge_split(), port_o::resize_busport(), cs_interface::resize_dimension_bus_port(), datapath_parallel_cs::resize_dimension_bus_port(), fu_binding_cs::resize_dimension_bus_port(), port_o::resize_std_port(), setBusSizes(), and reg_binding_cs::specialise_reg().
type_resize() [2/2]
void structural_object::type_resize (unsigned int new_bit_size, unsigned int new_vec_size)
resizing of vector objects
Definition at line 643 of file structural_objects.cpp.
References structural_type_descriptor::BOOL, get_path(), structural_type_descriptor::id_type, structural_type_descriptor::INT, structural_type_descriptor::OTHER, structural_type_descriptor::REAL, structural_type_descriptor::size, STR, THROW_ERROR, structural_type_descriptor::type, type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
xload()
void structural_object::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
owner not managed by xload
Reimplemented in bus_connection_o, channel_o, component_o, module, signal_o, constant_o, action_o, data_o, event_o, and port_o.
Definition at line 801 of file structural_objects.cpp.
References black_box, CE_XVM, xml_node::convert_escaped(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_parameters, xml_child::get_children(), GET_CLASS_NAME, xml_text_node::get_content(), xml_node::get_line(), LOAD_XVM, PRINT_DBG_MEX, THROW_ASSERT, THROW_ERROR, treenode, type, and structural_type_descriptor::xload().
Referenced by structural_manager::xload(), port_o::xload(), event_o::xload(), data_o::xload(), action_o::xload(), signal_o::xload(), module::xload(), and bus_connection_o::xload().
xwrite()
void structural_object::xwrite (xml_element * rootnode) [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented in bus_connection_o, channel_o, component_o, module, signal_o, constant_o, action_o, data_o, event_o, and port_o.
Definition at line 844 of file structural_objects.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), black_box, black_box_DEFAULT, default_parameters, get_path(), STR, treenode, treenode_DEFAULT, type, WRITE_XNVM2, WRITE_XVM, and structural_type_descriptor::xwrite().
Referenced by structural_manager::xwrite(), port_o::xwrite(), event_o::xwrite(), data_o::xwrite(), action_o::xwrite(), constant_o::xwrite(), signal_o::xwrite(), module::xwrite(), and bus_connection_o::xwrite().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const structural_objectRef o) [friend]
Friend definition of the << operator.
Definition at line 598 of file structural_objects.hpp.
Field Documentation
black_box
bool structural_object::black_box [private]
True if the structural object is a black box (e.g., a library component).
Definition at line 359 of file structural_objects.hpp.
Referenced by copy(), get_black_box(), print(), set_black_box(), xload(), and xwrite().
black_box_DEFAULT
const bool structural_object::black_box_DEFAULT = true [static], [private]
Definition at line 632 of file structural_objects.hpp.
Referenced by xwrite().
debug_level
int structural_object::debug_level [protected]
debug level for the object
Definition at line 369 of file structural_objects.hpp.
Referenced by port_o::add_n_ports(), signal_o::add_n_signals(), copy(), port_o::copy(), action_o::copy(), signal_o::copy(), module::copy(), port_o::resize_std_port(), xload(), and module::xload().
default_parameters
CustomMap<std::string, std::string> structural_object::default_parameters [private]
Map between parameter string and its default value.
Definition at line 365 of file structural_objects.hpp.
Referenced by AddParameter(), copy(), ExistsParameter(), GetDefaultParameter(), GetParameter(), GetParameters(), SetParameter(), xload(), and xwrite().
id
std::string structural_object::id [private]
Identifier for this component.
Definition at line 350 of file structural_objects.hpp.
Referenced by copy(), and get_id().
owner
Wrefcount<structural_object> structural_object::owner [private]
The owner of the object.
Definition at line 347 of file structural_objects.hpp.
Referenced by port_o::fix_port_properties(), get_owner(), and set_owner().
parameters
CustomMap<std::string, std::string> structural_object::parameters [private]
Map between parameter string and related values of an instance.
Definition at line 362 of file structural_objects.hpp.
Referenced by copy(), GetParameter(), GetParameters(), and SetParameter().
PP
simple_indent structural_object::PP [static], [protected]
pretty print functor object used by all print members to indent the output of the print function.
Definition at line 406 of file structural_objects.hpp.
Referenced by structural_type_descriptor::check_type(), print(), port_o::print(), event_o::print(), data_o::print(), action_o::print(), constant_o::print(), signal_o::print(), module::print(), channel_o::print(), and bus_connection_o::print().
treenode
unsigned int structural_object::treenode [private]
index of the treenode in the tree_manager associated with the structural object.
Definition at line 356 of file structural_objects.hpp.
Referenced by copy(), get_treenode(), print(), set_treenode(), xload(), and xwrite().
treenode_DEFAULT
const unsigned int structural_object::treenode_DEFAULT = 0 [static], [private]
Definition at line 631 of file structural_objects.hpp.
Referenced by xwrite().
type
structural_type_descriptorRef structural_object::type [private]
The description of the type.
Definition at line 353 of file structural_objects.hpp.
Referenced by copy(), get_typeRef(), print(), set_type(), type_resize(), xload(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp