tree_node_factory Struct Reference
#include <tree_node_factory.hpp>
Public Member Functions
tree_node_factory (const std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > &_tree_node_schema, tree_manager &_TM)
default constructor
void create_tree_node (const unsigned int node_id, enum kind)
tree_node visitors
Private Attributes
const std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > & tree_node_schema
tree_node_schema expresses the value of the fields of the tree node we would like to create.
tree_manager & TM
tree manager
tree_node * curr_tree_node_ptr
current tree node filled according to the tree_node_schema
Detailed Description
Definition at line 68 of file tree_node_factory.hpp.
Constructor & Destructor Documentation
tree_node_factory()
tree_node_factory::tree_node_factory (const std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > & _tree_node_schema, tree_manager & _TM) [inline]
default constructor
Definition at line 71 of file tree_node_factory.hpp.
References object_visitor::BOOST_PP_SEQ_FOR_EACH(), create_tree_node(), OBJ_NOT_SPECIALIZED_SEQ, OBJ_SPECIALIZED_SEQ, OPERATOR_MACRO, and OPERATOR_MACRO_DECL.
Member Function Documentation
create_tree_node()
void tree_node_factory::create_tree_node (const unsigned int node_id, enum kind tree_node_type)
tree_node visitors
Factory method. It creates a tree_node of type equal tree_node_type by using a relation (tree_node_schema) between tree node fields and their values.
Parameters
node_id is the node id of the created object.
tree_node_type is the type of the node added to the tree_manager For example the following code: std::map<int, std::string> identifier_schema; int identifier_node_id = TM->get_tree_node_n(); identifier_schema[TOK(TOK_STRG)]= `my_identifier`; tree_node_factory TNF(identifier_schema, TM); TNF.create_tree_node(identifier_node_id, TOK(TOK_IDENTIFIER_NODE));
will add an identifier node to the tree_manager TM.
special care is reserved for identifier_nodes
Definition at line 73 of file tree_node_factory.cpp.
References tree_manager::AddTreeNode(), ATTR_MACRO, ATTR_SEQ, object_visitor::BOOST_PP_SEQ_FOR_EACH(), CREATE_TREE_NODE_CASE_BODY, curr_tree_node_ptr, tree_node::get_kind_text(), template_id_expr(), THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, TM, TOK, TOK_OPERATOR, TOK_STRG, tree_node_schema, typename_type(), and using_decl().
Referenced by tree_manager::create_tree_node(), and tree_node_factory().
Field Documentation
curr_tree_node_ptr
tree_node* tree_node_factory::curr_tree_node_ptr [private]
current tree node filled according to the tree_node_schema
Definition at line 99 of file tree_node_factory.hpp.
Referenced by create_tree_node().
TM
tree_manager& tree_node_factory::TM [private]
tree manager
Definition at line 97 of file tree_node_factory.hpp.
Referenced by create_tree_node().
tree_node_schema
const std::map<TreeVocabularyTokenTypes_TokenEnum, std::string>& tree_node_factory::tree_node_schema [private]
tree_node_schema expresses the value of the fields of the tree node we would like to create.
Definition at line 95 of file tree_node_factory.hpp.
Referenced by create_tree_node().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node_factory.cpp