priority_dynamic_mobility Struct Reference
This is a specialization based on mobility.
#include <priority.hpp>
Public Member Functions
priority_dynamic_mobility (const ASLAPRef &aslap, const OpVertexSet &_ready_nodes, unsigned int _ctrl_step_multiplier)
Constructor.
bool update () override
This specialization does update the priorities at the end of the control step only of ready nodes.
Private Attributes
const OpVertexSet & ready_nodes
set of ready vertices.
unsigned int ctrl_step_multiplier
multiplier used to take into account chaining during asap/alap computation
Detailed Description
This is a specialization based on mobility.
The update function does change the priority at the end of the control step analysis only of ready nodes.
Definition at line 128 of file priority.hpp.
Constructor & Destructor Documentation
priority_dynamic_mobility()
priority_dynamic_mobility::priority_dynamic_mobility (const ASLAPRef & aslap, const OpVertexSet & _ready_nodes, unsigned int _ctrl_step_multiplier)
Constructor.
Note that usually high priority in list based means low mobility.
Definition at line 68 of file priority.cpp.
References from_strongtype_cast(), and priority_data< int >::operator[]().
Member Function Documentation
update()
bool priority_dynamic_mobility::update () [override], [virtual]
This specialization does update the priorities at the end of the control step only of ready nodes.
increase priority
Implements priority_data< int >.
Definition at line 83 of file priority.cpp.
References ctrl_step_multiplier, priority_data< int >::operator[](), and ready_nodes.
Field Documentation
ctrl_step_multiplier
unsigned int priority_dynamic_mobility::ctrl_step_multiplier [private]
multiplier used to take into account chaining during asap/alap computation
Definition at line 144 of file priority.hpp.
Referenced by update().
ready_nodes
const OpVertexSet& priority_dynamic_mobility::ready_nodes [private]
set of ready vertices.
Definition at line 142 of file priority.hpp.
Referenced by update().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/priority.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/priority.cpp