std_var_pp_functor Struct Reference
Standard functor that returns the name of a variable.
#include <var_pp_functor.hpp>
Public Member Functions
std_var_pp_functor (const BehavioralHelperConstRef _BH)
Constructor.
~std_var_pp_functor () override=default
Destructor.
std::string operator() (unsigned int var) const override
return the name of the variable.
Private Attributes
const BehavioralHelperConstRef BH
behavioral helper
Detailed Description
Standard functor that returns the name of a variable.
Definition at line 83 of file var_pp_functor.hpp.
Constructor & Destructor Documentation
std_var_pp_functor()
std_var_pp_functor::std_var_pp_functor (const BehavioralHelperConstRef _BH) [inline], [explicit]
Constructor.
Definition at line 91 of file var_pp_functor.hpp.
References var_pp_functor::operator()().
 std_var_pp_functor()
std_var_pp_functor::~std_var_pp_functor () [override], [default]
Destructor.
Member Function Documentation
operator()()
std::string std_var_pp_functor::operator() (unsigned int var) const [override], [virtual]
return the name of the variable.
Parameters
var is the nodeid of the variable.
Implements var_pp_functor.
Definition at line 52 of file var_pp_functor.cpp.
References pointer_var_pp_functor::BH, BehavioralHelper::get_array_ref_array(), BehavioralHelper::get_array_ref_index(), BehavioralHelper::get_component_ref_field(), BehavioralHelper::get_component_ref_record(), BehavioralHelper::get_mem_ref_base(), BehavioralHelper::get_mem_ref_offset(), BehavioralHelper::get_operand_from_unary_expr(), BehavioralHelper::get_type(), index, BehavioralHelper::is_a_component_ref(), BehavioralHelper::is_a_imagpart_expr(), BehavioralHelper::is_a_mem_ref(), BehavioralHelper::is_a_realpart_expr(), BehavioralHelper::is_an_addr_expr(), BehavioralHelper::is_an_array(), BehavioralHelper::is_an_array_ref(), BehavioralHelper::is_an_indirect_ref(), pointer_var_pp_functor::operator()(), BehavioralHelper::print_type(), BehavioralHelper::PrintVariable(), and test_panda::type.
Field Documentation
BH
const BehavioralHelperConstRef std_var_pp_functor::BH [private]
behavioral helper
Definition at line 87 of file var_pp_functor.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.cpp