conn_binding Class Reference
Class managing the interconnection binding.
#include <conn_binding.hpp>
Data Structures
struct ConnectionSorter
definition of the connection implementations
struct ConnectionTarget
definition of target of a connection
Public Types
enum direction_type { IN = 0,
OUT
 }
direction port identifier
enum type_t { STG = 0
 }
type of the datastructure
typedef std::tuple< generic_objRef, generic_objRef, unsigned int, unsigned int > connection
connection between two objects (<src, tgt, tgt_port, tgt_port_index>)
typedef std::map< connection, connection_objRef, ConnectionSorter > conn_implementation_map
typedef std::tuple< std::string, std::string > const_param
definition of the key to deal with constant parameters
typedef std::map< generic_objRef, CustomOrderedSet< data_transfer >, GenericObjSorter > ConnectionSources
definition of sources of a connection
Public Member Functions
conn_binding (const BehavioralHelperConstRef BH, const ParameterConstRef parameters)
Constructor.
virtual ~conn_binding ()
Destructor.
generic_objRef bind_port (unsigned int var, direction_type dir)
Bind variable to a port object.
generic_objRef bind_command_port (const vertex &ver, direction_type dir, unsigned int mode, const OpGraphConstRef g)
Bind vertex to a command port object.
generic_objRef bind_selector_port (direction_type dir, unsigned int mode, const vertex &ver, const OpGraphConstRef data)
generic_objRef bind_selector_port (direction_type dir, unsigned int mode, const generic_objRef elem, unsigned int op)
generic_objRef get_port (unsigned int var, direction_type dir)
Returns reference to generic object associated to a given variable, for a specific port direction.
generic_objRef get_command_port (const vertex &ver, direction_type dir, unsigned int mode)
Returns reference to generic object associated to a given vertex, for a specific port direction.
unsigned int get_to_controller_ports () const
Returns the number of connections from the datapath to the controller.
std::map< std::pair< vertex, unsigned int >, generic_objRef > get_command_input_ports () const
Returns the list of connections from the controller to the datapath.
unsigned int get_from_controller_ports () const
Returns the number of connections from the controller to the datapath.
virtual void print () const
Function that prints the interconnection binding.
void add_data_transfer (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index, data_transfer data)
Adds a data transfer between two objects.
void add_connection (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index, connection_objRef conn)
Creates a connection between two objects.
connection_objRef get_connection (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index) const
Return the current connection between two objects, if any.
bool is_connection (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index) const
Checks if there is a connection between two objects.
const std::map< ConnectionTarget, ConnectionSources > & get_data_transfers () const
Returns the map containing all the data transfers.
unsigned int determine_bit_level_mux () const
Returns the number of bit-level multiplexers.
const conn_implementation_map & get_connection_implementations () const
Returns the map containing all the connection implementations.
void add_command_port (const generic_objRef obj)
Adds a generic command port to proper set.
CustomOrderedSet< generic_objRef > get_command_ports () const
Returns set of generic command ports.
const std::map< unsigned int, Selectors > & GetSelectors () const
unsigned int get_component_num (const std::string &type) const
void add_component (const std::string &type, unsigned int num=1)
void add_sparse_logic (const generic_objRef so)
const std::map< std::string, unsigned int > & get_components () const
virtual void add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM)
Add the interconnection to the structural representation of the datapath.
generic_objRef get_constant_obj (const std::string &value, const std::string &param, unsigned int precision)
std::map< const_param, generic_objRef > get_constant_objs () const
Static Public Member Functions
static conn_bindingRef create_conn_binding (const HLS_managerRef _HLSMgr, const hlsRef _HLS, const BehavioralHelperConstRef _BH, const ParameterConstRef _parameters)
factory method to create the right conn_binding depending on the flow
Protected Types
typedef std::map< std::pair< generic_objRef, unsigned int >, generic_objRef, GenericObjUnsignedIntSorter > Selectors
selector ports
Protected Member Functions
void specialise_mux (const generic_objRef mux, unsigned int bits_tgt) const
Specialise a multiplexer according to the type of the variables crossing it.
unsigned int get_mux_size (const generic_objRef mux) const
Specialise a multiplexer according to the type of the variables crossing it.
void mux_connection (const hlsRef HLS, const structural_managerRef SM)
Add the mux-based interconnection.
void add_sparse_logic_dp (const hlsRef HLS, const structural_managerRef SM, const HLS_managerRef HLSMgr)
Add sparse logic to the datapath.
void add_command_ports (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM)
Add signals from/to controller.
virtual void mux_allocation (const hlsRef HLS, const structural_managerRef SM, structural_objectRef src, structural_objectRef tgt, connection_objRef conn)
Add multiplexers to the structural representation of the datapath.
void add_datapath_connection (const technology_managerRef TM, const structural_managerRef SM, const structural_objectRef conn_out, const structural_objectRef port_tgt, unsigned int conn_type)
Add a data converter, if needed, between two objects of the structural representation of the datapath.
bool check_pv_allconnected (structural_objectRef port_i)
check if a port vector has its port bounded to something
Protected Attributes
const ParameterConstRef parameters
The set of input parameters.
int debug_level
control the verbosity during the debugging
int output_level
control the output verbosity
const BehavioralHelperConstRef BH
reference to the behavioral helper associated with the specification
std::map< vertex, std::map< unsigned int, generic_objRef > > activation_ports
map between a vertex and the corresponding activation signal
std::map< unsigned int, generic_objRef > input_ports
map between input port variable and generic object
std::map< unsigned int, generic_objRef > output_ports
map between output port variable and generic object
std::map< const_param, generic_objRef > constant_values
constant values
std::map< std::string, structural_objectRef > converters
data type converters
std::map< std::pair< vertex, unsigned int >, generic_objRef > command_input_ports
map between command input port (operation vertex and command type) and generic object
std::map< vertex, generic_objRef > command_output_ports
map between output port variable and generic object
std::map< std::pair< std::string, unsigned int >, unsigned int > interconnection_elements
map between interconnection elements and their number
CustomOrderedSet< generic_objRef > command_ports
set of other command ports
std::map< unsigned int, Selectors > selectors
std::map< std::string, unsigned int > component_num
map between a resource name and the corresponding number of instances inside the datapath
CustomOrderedSet< generic_objRef, GenericObjSorter > sparse_logic
set containing all the sparse logic contained into the datapath
std::map< ConnectionTarget, ConnectionSources > conn_variables
map between the input of the unit and the corresponding incoming connections.
conn_implementation_map conn_implementation
map between the connection <src, tgt, tgt_port, tgt_port_index> and the corresponding object
Static Protected Attributes
static unsigned unique_id = 0
Detailed Description
Class managing the interconnection binding.
Definition at line 77 of file conn_binding.hpp.
Member Typedef Documentation
conn_implementation_map
typedef std::map<connection, connection_objRef, ConnectionSorter> conn_binding::conn_implementation_map
Definition at line 113 of file conn_binding.hpp.
connection
typedef std::tuple<generic_objRef, generic_objRef, unsigned int, unsigned int> conn_binding::connection
connection between two objects (<src, tgt, tgt_port, tgt_port_index>)
Definition at line 94 of file conn_binding.hpp.
ConnectionSources
typedef std::map<generic_objRef, CustomOrderedSet<data_transfer>, GenericObjSorter> conn_binding::ConnectionSources
definition of sources of a connection
Definition at line 143 of file conn_binding.hpp.
const_param
typedef std::tuple<std::string, std::string> conn_binding::const_param
definition of the key to deal with constant parameters
Definition at line 117 of file conn_binding.hpp.
Selectors
typedef std::map<std::pair<generic_objRef, unsigned int>, generic_objRef, GenericObjUnsignedIntSorter> conn_binding::Selectors [protected]
selector ports
Definition at line 190 of file conn_binding.hpp.
Member Enumeration Documentation
direction_type
enum conn_binding::direction_type
direction port identifier
Enumerator
IN
OUT
Definition at line 81 of file conn_binding.hpp.
type_t
enum conn_binding::type_t
type of the datastructure
Enumerator
STG
Definition at line 88 of file conn_binding.hpp.
Constructor & Destructor Documentation
conn_binding()
conn_binding::conn_binding (const BehavioralHelperConstRef BH, const ParameterConstRef parameters)
Constructor.
Definition at line 113 of file conn_binding.cpp.
Referenced by create_conn_binding().
 conn_binding()
conn_binding::~conn_binding () [virtual], [default]
Destructor.
Referenced by create_conn_binding().
Member Function Documentation
add_command_port()
void conn_binding::add_command_port (const generic_objRef obj) [inline]
Adds a generic command port to proper set.
Parameters
obj is refcount to generic_obj class associated with port to be added
Definition at line 384 of file conn_binding.hpp.
add_command_ports()
void conn_binding::add_command_ports (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM) [protected]
Add signals from/to controller.
define the type for boolean command signals
check for start port
if elem is a functional unit and has more than one operation, add a selector for each operation (e.g. selector_LOAD_1...)
no port selector means that functional units can implement different operations without using a selector (i.e., it has several alias operation)
output signals to the controller for condition evaluation
Definition at line 927 of file conn_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), structural_manager::add_sign(), hls::allocation_information, BH, bind_selector_port(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), generic_obj::COMMAND_PORT, generic_obj::CONNECTION_ELEMENT, debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::DFG, DONE_PORT_NAME, structural_object::find_member(), generic_obj::FUNCTIONAL_UNIT, hls::functionId, fu_binding::get(), fu_binding::get_assign(), structural_manager::get_circ(), AllocationInformation::get_fu(), structural_object::get_id(), structural_object::get_kind(), technology_manager::get_library(), StateTransitionGraphManager::get_mu_ctrls(), GET_NAME, structural_object::get_owner(), structural_object::get_path(), get_port(), port_o::get_port(), generic_obj::get_string(), generic_obj::get_structural_obj(), generic_obj::get_type(), GET_TYPE, hls::HLS_T, IN, port_o::IN, INDENT_DBG_MEX, index, commandport_obj::MULTI_UNBOUNDED, commandport_obj::MULTIIF, tree_helper::normalized_ID(), hls::operations, OR_GATE_STD, OUT, port_o::OUT, port_o_K, port_vector_o_K, hls::Rconn, generic_obj::REGISTER, hls::Rfu, selectors, START_PORT_NAME, hls::STG, STR, commandport_obj::SWITCH, THROW_ASSERT, THROW_ERROR, top(), TYPE_EXTERNAL, commandport_obj::UNBOUNDED, unique_id, and WENABLE_PORT_NAME.
Referenced by add_to_SM().
add_component()
void conn_binding::add_component (const std::string & type, unsigned int num = 1)
Definition at line 272 of file conn_binding.cpp.
References component_num, and test_panda::type.
Referenced by mux_connection_binding::add_conversion(), mux_connection_binding::connect_array_index(), mux_connection_binding::create_connections(), mux_connection_binding::determine_connection(), mux_connection_binding::dynamic_multidimensional_array_handler(), GetSelectors(), and mux_connection_binding::input_logic().
add_connection()
void conn_binding::add_connection (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index, connection_objRef conn)
Creates a connection between two objects.
Parameters
op1 is reference to first object
op2 is reference to second object
operand is i-th operand for second object, where first one is connected
port_index is i-th port associated with the operand (different from 0 when multi-channels components are considered)
conn is the reference to the implemented connection
Definition at line 172 of file conn_binding.cpp.
References conn_implementation, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, generic_obj::get_string(), INDENT_DBG_MEX, and STR.
Referenced by mux_connection_binding::input_logic().
add_data_transfer()
void conn_binding::add_data_transfer (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index, data_transfer data)
Adds a data transfer between two objects.
Parameters
op1 is reference to first object
op2 is reference to second object
operand is i-th operand for second object, where first one is connected
port_index is i-th port associated with the operand (different from 0 when multi-channels components are considered)
data is the data to be transferred
Definition at line 157 of file conn_binding.cpp.
References conn_variables.
Referenced by mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), and mux_connection_binding::create_single_conn().
add_datapath_connection()
void conn_binding::add_datapath_connection (const technology_managerRef TM, const structural_managerRef SM, const structural_objectRef conn_out, const structural_objectRef port_tgt, unsigned int conn_type) [protected]
Add a data converter, if needed, between two objects of the structural representation of the datapath.
fixing input stuff
fixing output stuff
Definition at line 642 of file conn_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), converters, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FFDATA_CONVERTER_STD, structural_manager::get_circ(), structural_object::get_id(), structural_object::get_kind(), technology_manager::get_library(), structural_type_descriptor::get_name(), structural_object::get_owner(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), IIDATA_CONVERTER_STD, INDENT_DBG_MEX, structural_type_descriptor::INT, IUDATA_CONVERTER_STD, port_o_K, structural_type_descriptor::REAL, structural_type_descriptor::size, STR, THROW_ASSERT, THROW_UNREACHABLE, structural_type_descriptor::type, structural_object::type_resize(), UIDATA_CONVERTER_STD, UUDATA_CONVERTER_STD, and structural_type_descriptor::VECTOR_BOOL.
Referenced by mux_allocation(), and mux_connection().
add_sparse_logic()
void conn_binding::add_sparse_logic (const generic_objRef so) [inline]
Definition at line 407 of file conn_binding.hpp.
References add_to_SM(), create_conn_binding(), get_components(), get_constant_obj(), and get_constant_objs().
Referenced by mux_connection_binding::add_conversion(), mux_connection_binding::connect_array_index(), mux_connection_binding::create_connections(), mux_connection_binding::determine_connection(), and mux_connection_binding::dynamic_multidimensional_array_handler().
add_sparse_logic_dp()
void conn_binding::add_sparse_logic_dp (const hlsRef HLS, const structural_managerRef SM, const HLS_managerRef HLSMgr) [protected]
Add sparse logic to the datapath.
specializing sparse module ports
the multiplier in the resource library is pipelined, so we use the non-pipelined version by setting PIPE_PARAMETER to 0
Definition at line 743 of file conn_binding.cpp.
References generic_obj::ADDER_CONN_OBJ, ASSIGN_REAL_STD, ASSIGN_SIGNED_STD, ASSIGN_UNSIGNED_STD, ASSIGN_VECTOR_BOOL_STD, generic_obj::BITFIELD_OBJ, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, AllocationInformation::extract_bambu_provided_name(), generic_obj::F_ASSIGN_CONN_OBJ, generic_obj::FF_CONV_CONN_OBJ, FFDATA_CONVERTER_STD, structural_manager::get_circ(), structural_object::get_path(), hls::HLS_T, generic_obj::I_ASSIGN_CONN_OBJ, generic_obj::II_CONV_CONN_OBJ, IIDATA_CONVERTER_STD, INDENT_DBG_MEX, generic_obj::IU_CONV_CONN_OBJ, IUDATA_CONVERTER_STD, generic_obj::MULTIPLIER_CONN_OBJ, hls::Param, PIPE_PARAMETER, SIGNED_BITFIELD_FU_STD, sparse_logic, STR, THROW_ERROR, generic_obj::U_ASSIGN_CONN_OBJ, UI_ADDER_STD, UI_ALIGN_ADDER_STD, UI_CONST_MULTIPLIER_STD, generic_obj::UI_CONV_CONN_OBJ, UI_MULTIPLIER_STD, UIDATA_CONVERTER_STD, generic_obj::UU_CONV_CONN_OBJ, UUDATA_CONVERTER_STD, VALUE_PARAMETER, and generic_obj::VB_ASSIGN_CONN_OBJ.
Referenced by add_to_SM().
add_to_SM()
void conn_binding::add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM) [virtual]
Add the interconnection to the structural representation of the datapath.
add command ports
add sparse logic
up to now, circuit is general about interconnections. Now, proper interconnection architecture will be executed
Reimplemented in conn_binding_cs, and ParallelMemoryConnBinding.
Definition at line 315 of file conn_binding.cpp.
References add_command_ports(), structural_manager::add_connection(), structural_manager::add_constant(), structural_manager::add_sign(), add_sparse_logic_dp(), check_pv_allconnected(), debug_level, DEBUG_LEVEL_VERBOSE, structural_manager::get_circ(), get_id(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), get_port(), GET_TYPE_SIZE, structural_object::get_typeRef(), INDENT_DBG_MEX, mux_connection(), MUX_INTERCONNECTION_BINDING, hls::Param, port_o_K, port_vector_o_K, STR, and THROW_ASSERT.
Referenced by add_sparse_logic(), ParallelMemoryConnBinding::add_to_SM(), conn_binding_cs::add_to_SM(), and classic_datapath::InternalExec().
bind_command_port()
generic_objRef conn_binding::bind_command_port (const vertex & ver, conn_binding::direction_type dir, unsigned int mode, const OpGraphConstRef g)
Bind vertex to a command port object.
Parameters
ver is the vertex to be associated to the port
dir is the direction to be associated to the port
mode is command mode (as defined into commandport_obj::command_type)
g is graph where vertex ver is stored
Definition at line 227 of file conn_binding.cpp.
References command_input_ports, command_output_ports, commandport_obj::get_mode_string(), GET_NAME, IN, OUT, and THROW_ERROR.
Referenced by mux_connection_binding::create_connections().
bind_port()
generic_objRef conn_binding::bind_port (unsigned int var, conn_binding::direction_type dir)
Bind variable to a port object.
Parameters
var is the variable to be associated to the port
dir is the direction to be associated to the port
Definition at line 205 of file conn_binding.cpp.
References BH, IN, input_ports, OUT, output_ports, and THROW_ERROR.
Referenced by conn_binding_creator::add_parameter_ports().
bind_selector_port() [1/2]
generic_objRef conn_binding::bind_selector_port (conn_binding::direction_type dir, unsigned int mode, const vertex & ver, const OpGraphConstRef data)
Definition at line 256 of file conn_binding.cpp.
References activation_ports, commandport_obj::get_mode_string(), GET_NAME, IN, and selectors.
Referenced by add_command_ports(), mux_connection_binding::create_connections(), fsm_controller::create_state_machine(), and mux_connection_binding::input_logic().
bind_selector_port() [2/2]
generic_objRef conn_binding::bind_selector_port (conn_binding::direction_type dir, unsigned int mode, const generic_objRef elem, unsigned int op)
Definition at line 249 of file conn_binding.cpp.
References commandport_obj::get_mode_string(), generic_obj::get_string(), IN, selectors, and STR.
check_pv_allconnected()
bool conn_binding::check_pv_allconnected (structural_objectRef port_i) [protected]
check if a port vector has its port bounded to something
Parameters
port_i
Returns
true in case all ports are bounded to something, false otherwise.
Definition at line 302 of file conn_binding.cpp.
References get_port().
Referenced by add_to_SM().
create_conn_binding()
conn_bindingRef conn_binding::create_conn_binding (const HLS_managerRef _HLSMgr, const hlsRef _HLS, const BehavioralHelperConstRef _BH, const ParameterConstRef _parameters) [static]
factory method to create the right conn_binding depending on the flow
Parameters
_HLSMgr
_HLS
_BH
_parameters
Returns
Definition at line 118 of file conn_binding.cpp.
References conn_binding(), hls::functionId, and ~conn_binding().
Referenced by add_sparse_logic(), and mux_connection_binding::create_connections().
determine_bit_level_mux()
unsigned int conn_binding::determine_bit_level_mux () const
Returns the number of bit-level multiplexers.
Definition at line 910 of file conn_binding.cpp.
References conn_implementation.
Referenced by mux_connection_binding::InternalExec().
get_command_input_ports()
std::map< std::pair< vertex, unsigned int >, generic_objRef > conn_binding::get_command_input_ports () const
Returns the list of connections from the controller to the datapath.
Definition at line 292 of file conn_binding.cpp.
References command_input_ports.
get_command_port()
generic_objRef conn_binding::get_command_port (const vertex & ver, conn_binding::direction_type dir, unsigned int mode)
Returns reference to generic object associated to a given vertex, for a specific port direction.
Parameters
ver is vertex associated to desired port
dir is port direction
mode is command mode (OPERATION or CONDITION)
Returns
reference to the generic object of the port associated to given vertex, into given direction
Definition at line 189 of file conn_binding.cpp.
References command_input_ports, command_output_ports, IN, OUT, THROW_ASSERT, and THROW_ERROR.
get_command_ports()
CustomOrderedSet<generic_objRef> conn_binding::get_command_ports () const [inline]
Returns set of generic command ports.
Returns
a set of all refcount to generic_obj's associated to ports
Definition at line 393 of file conn_binding.hpp.
References command_ports.
get_component_num()
unsigned int conn_binding::get_component_num (const std::string & type) const
Definition at line 265 of file conn_binding.cpp.
References component_num.
Referenced by GetSelectors().
get_components()
const std::map< std::string, unsigned int > & conn_binding::get_components () const
Definition at line 282 of file conn_binding.cpp.
References component_num.
Referenced by add_sparse_logic().
get_connection()
connection_objRef conn_binding::get_connection (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index) const
Return the current connection between two objects, if any.
Parameters
op1 is reference to first object
op2 is reference to second object
operand is i-th operand for second object, where first one is connected
port_index is i-th port associated with the operand (different from 0 when multi-channels components are considered)
Returns
conn is the reference to the implemented connection
Definition at line 178 of file conn_binding.cpp.
References conn_implementation, is_connection(), and THROW_ASSERT.
get_connection_implementations()
const conn_binding::conn_implementation_map & conn_binding::get_connection_implementations () const
Returns the map containing all the connection implementations.
Definition at line 167 of file conn_binding.cpp.
References conn_implementation.
get_constant_obj()
generic_objRef conn_binding::get_constant_obj (const std::string & value, const std::string & param, unsigned int precision)
Definition at line 730 of file conn_binding.cpp.
References constant_values, and THROW_ASSERT.
Referenced by add_sparse_logic(), and mux_connection_binding::determine_connection().
get_constant_objs()
std::map< conn_binding::const_param, generic_objRef > conn_binding::get_constant_objs () const
Definition at line 738 of file conn_binding.cpp.
References constant_values.
Referenced by classic_datapath::add_ports(), and add_sparse_logic().
get_data_transfers()
const std::map< conn_binding::ConnectionTarget, conn_binding::ConnectionSources > & conn_binding::get_data_transfers () const
Returns the map containing all the data transfers.
Definition at line 162 of file conn_binding.cpp.
References conn_variables.
Referenced by mux_connection_binding::mux_interconnection().
get_from_controller_ports()
unsigned int conn_binding::get_from_controller_ports () const
Returns the number of connections from the controller to the datapath.
Definition at line 297 of file conn_binding.cpp.
References command_input_ports.
get_mux_size()
unsigned int conn_binding::get_mux_size (const generic_objRef mux) const [protected]
Specialise a multiplexer according to the type of the variables crossing it.
Parameters
mux is the multiplexer
get_port()
generic_objRef conn_binding::get_port (unsigned int var, conn_binding::direction_type dir)
Returns reference to generic object associated to a given variable, for a specific port direction.
Parameters
var is variable associated with the port
dir is port direction
Returns
reference to the generic object of the port associated to given variable, into given direction
Definition at line 141 of file conn_binding.cpp.
References IN, input_ports, OUT, output_ports, THROW_ASSERT, and THROW_ERROR.
Referenced by add_command_ports(), classic_datapath::add_ports(), ParallelMemoryConnBinding::add_to_SM(), fu_binding::add_to_SM(), add_to_SM(), check_pv_allconnected(), conn_binding_cs::instantiate_suspension_component(), and mux_connection().
get_to_controller_ports()
unsigned int conn_binding::get_to_controller_ports () const
Returns the number of connections from the datapath to the controller.
Definition at line 287 of file conn_binding.cpp.
References command_output_ports.
GetSelectors()
const std::map<unsigned int, Selectors>& conn_binding::GetSelectors () const [inline]
Definition at line 398 of file conn_binding.hpp.
References add_component(), get_component_num(), selectors, and test_panda::type.
Referenced by ControllerCreatorBaseStep::add_command_ports(), top_entity::add_command_signals(), and fsm_controller::create_state_machine().
is_connection()
bool conn_binding::is_connection (const generic_objRef op1, const generic_objRef op2, unsigned int operand, unsigned int port_index) const
Checks if there is a connection between two objects.
Parameters
op1 is reference to first object
op2 is reference to second object
operand is i-th operand for second object, where first one is connected
port_index is i-th port associated with the operand (different from 0 when multi-channels components are considered)
Definition at line 184 of file conn_binding.cpp.
References conn_implementation.
Referenced by get_connection().
mux_allocation()
void conn_binding::mux_allocation (const hlsRef HLS, const structural_managerRef SM, structural_objectRef src, structural_objectRef tgt, connection_objRef conn) [protected], [virtual]
Add multiplexers to the structural representation of the datapath.
adding input connection
mux selector in datapath interface
selector in mux object
specializing allocated mux
adding input connection
adding output signal to the multiplexer
Definition at line 550 of file conn_binding.cpp.
References structural_manager::add_connection(), add_datapath_connection(), structural_manager::add_sign(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), structural_object::get_path(), generic_obj::get_structural_obj(), GET_TYPE_SIZE, structural_object::get_typeRef(), hls::HLS_T, INDENT_DBG_MEX, structural_type_descriptor::INT, MUX_GATE_STD, port_o_K, structural_type_descriptor::REAL, structural_type_descriptor::size, specialise_mux(), T_COND, THROW_ASSERT, structural_type_descriptor::type, structural_type_descriptor::UINT, and structural_type_descriptor::VECTOR_BOOL.
Referenced by mux_connection().
mux_connection()
void conn_binding::mux_connection (const hlsRef HLS, const structural_managerRef SM) [protected]
Add the mux-based interconnection.
Definition at line 403 of file conn_binding.cpp.
References structural_manager::add_connection(), add_datapath_connection(), structural_manager::add_sign(), connection_obj::BY_MUX, CLOCK_PORT_NAME, component_o_K, conn_implementation, debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, connection_obj::DIRECT_CONN, DONE_PORT_NAME, structural_manager::get_circ(), structural_object::get_id(), structural_object::get_kind(), generic_obj::get_out_sign(), structural_object::get_path(), get_port(), generic_obj::get_string(), generic_obj::get_structural_obj(), GET_TYPE_SIZE, hls::HLS_T, INDENT_DBG_MEX, structural_type_descriptor::INT, mux_allocation(), port_o_K, port_vector_o_K, generic_obj::print(), structural_object::print(), structural_type_descriptor::REAL, RESET_PORT_NAME, generic_obj::set_out_sign(), START_PORT_NAME, STR, THROW_ASSERT, THROW_ERROR, structural_type_descriptor::UINT, and structural_type_descriptor::VECTOR_BOOL.
Referenced by add_to_SM().
print()
void conn_binding::print () const [virtual]
Function that prints the interconnection binding.
Definition at line 894 of file conn_binding.cpp.
References connection_obj::BY_MUX, conn_implementation, generic_obj::get_string(), INDENT_OUT_MEX, output_level, OUTPUT_LEVEL_VERY_PEDANTIC, and STR.
Referenced by mux_connection_binding::InternalExec().
specialise_mux()
void conn_binding::specialise_mux (const generic_objRef mux, unsigned int bits_tgt) const [protected]
Specialise a multiplexer according to the type of the variables crossing it.
Parameters
mux is the multiplexer
bits_tgt is the bitwidth of the target port
specializing multiplexer ports
Definition at line 535 of file conn_binding.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, module::get_in_port(), module::get_out_port(), structural_object::get_path(), generic_obj::get_structural_obj(), INDENT_DBG_MEX, max(), and STR.
Referenced by mux_allocation().
Field Documentation
activation_ports
std::map<vertex, std::map<unsigned int, generic_objRef> > conn_binding::activation_ports [protected]
map between a vertex and the corresponding activation signal
Definition at line 160 of file conn_binding.hpp.
Referenced by bind_selector_port().
BH
const BehavioralHelperConstRef conn_binding::BH [protected]
reference to the behavioral helper associated with the specification
Definition at line 157 of file conn_binding.hpp.
Referenced by add_command_ports(), and bind_port().
command_input_ports
std::map<std::pair<vertex, unsigned int>, generic_objRef> conn_binding::command_input_ports [protected]
map between command input port (operation vertex and command type) and generic object
Definition at line 175 of file conn_binding.hpp.
Referenced by bind_command_port(), get_command_input_ports(), get_command_port(), and get_from_controller_ports().
command_output_ports
std::map<vertex, generic_objRef> conn_binding::command_output_ports [protected]
map between output port variable and generic object
Definition at line 178 of file conn_binding.hpp.
Referenced by bind_command_port(), get_command_port(), and get_to_controller_ports().
command_ports
CustomOrderedSet<generic_objRef> conn_binding::command_ports [protected]
set of other command ports
Definition at line 184 of file conn_binding.hpp.
Referenced by get_command_ports().
component_num
std::map<std::string, unsigned int> conn_binding::component_num [protected]
map between a resource name and the corresponding number of instances inside the datapath
Definition at line 195 of file conn_binding.hpp.
Referenced by add_component(), get_component_num(), and get_components().
conn_implementation
conn_implementation_map conn_binding::conn_implementation [protected]
map between the connection <src, tgt, tgt_port, tgt_port_index> and the corresponding object
Definition at line 209 of file conn_binding.hpp.
Referenced by add_connection(), determine_bit_level_mux(), get_connection(), get_connection_implementations(), is_connection(), mux_connection(), and print().
conn_variables
std::map<ConnectionTarget, ConnectionSources> conn_binding::conn_variables [protected]
map between the input of the unit and the corresponding incoming connections.
The key <tgt, tgt_port, tgt_port_index> is the target of the connection, while the value is a set of pairs <src, variable>
Definition at line 206 of file conn_binding.hpp.
Referenced by add_data_transfer(), and get_data_transfers().
constant_values
std::map<const_param, generic_objRef> conn_binding::constant_values [protected]
constant values
Definition at line 169 of file conn_binding.hpp.
Referenced by get_constant_obj(), and get_constant_objs().
converters
std::map<std::string, structural_objectRef> conn_binding::converters [protected]
data type converters
Definition at line 172 of file conn_binding.hpp.
Referenced by add_datapath_connection().
debug_level
int conn_binding::debug_level [protected]
control the verbosity during the debugging
Definition at line 151 of file conn_binding.hpp.
Referenced by add_command_ports(), add_connection(), add_datapath_connection(), add_sparse_logic_dp(), add_to_SM(), conn_binding_cs::conn_binding_cs(), conn_binding_cs::connectOutOr(), conn_binding_cs::instantiate_suspension_component(), mux_allocation(), mux_connection(), and specialise_mux().
input_ports
std::map<unsigned int, generic_objRef> conn_binding::input_ports [protected]
map between input port variable and generic object
Definition at line 163 of file conn_binding.hpp.
Referenced by bind_port(), and get_port().
interconnection_elements
std::map<std::pair<std::string, unsigned int>, unsigned int> conn_binding::interconnection_elements [protected]
map between interconnection elements and their number
Definition at line 181 of file conn_binding.hpp.
output_level
int conn_binding::output_level [protected]
control the output verbosity
Definition at line 154 of file conn_binding.hpp.
Referenced by print().
output_ports
std::map<unsigned int, generic_objRef> conn_binding::output_ports [protected]
map between output port variable and generic object
Definition at line 166 of file conn_binding.hpp.
Referenced by bind_port(), and get_port().
parameters
const ParameterConstRef conn_binding::parameters [protected]
The set of input parameters.
Definition at line 148 of file conn_binding.hpp.
Referenced by ParallelMemoryConnBinding::add_to_SM().
selectors
std::map<unsigned int, Selectors> conn_binding::selectors [protected]
Definition at line 192 of file conn_binding.hpp.
Referenced by add_command_ports(), bind_selector_port(), and GetSelectors().
sparse_logic
CustomOrderedSet<generic_objRef, GenericObjSorter> conn_binding::sparse_logic [protected]
set containing all the sparse logic contained into the datapath
Definition at line 201 of file conn_binding.hpp.
Referenced by add_sparse_logic_dp().
unique_id
unsigned conn_binding::unique_id = 0 [static], [protected]
Definition at line 211 of file conn_binding.hpp.
Referenced by add_command_ports().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/conn_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/conn_binding.cpp