FPGA_device Class Reference
#include <FPGA_device.hpp>
Public Member Functions
FPGA_device (const ParameterConstRef &Param, const technology_managerRef &TM)
Constructor.
~FPGA_device () override
Destructor.
void initialize () override
Initializes the target device based on the given parameters.
void xwrite (xml_element *node) override
Method to write an XML node.
void load_devices (const target_deviceRef device) override
load all the data for the given FPGA
Additional Inherited Members
Detailed Description
Definition at line 48 of file FPGA_device.hpp.
Constructor & Destructor Documentation
FPGA_device()
FPGA_device::FPGA_device (const ParameterConstRef & _Param, const technology_managerRef & _TM)
Constructor.
XML includes.
Parameters
Param is the reference to the class that contains all the parameters
TM is the reference to the class containing all the technology libraries
parameters' includes Boost includes creating the datastructure representing the target technology
Definition at line 64 of file FPGA_device.cpp.
References target_technology::create_technology(), target_device::debug_level, target_technology::FPGA, GET_CLASS, target_device::Param, target_device::target, and ~FPGA_device().
 FPGA_device()
FPGA_device::~FPGA_device () [override], [default]
Destructor.
Referenced by FPGA_device().
Member Function Documentation
initialize()
void FPGA_device::initialize () [override], [virtual]
Initializes the target device based on the given parameters.
Implements target_device.
Definition at line 255 of file FPGA_device.cpp.
load_devices()
void FPGA_device::load_devices (const target_deviceRef device) [override], [virtual]
load all the data for the given FPGA
map between the default device string and the corresponding configuration stream
Load default device options
Implements target_device.
Definition at line 73 of file FPGA_device.cpp.
References target_device::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERBOSE, target_device::Param, test_panda::parser, PRINT_OUT_MEX, THROW_ERROR, and target_device::xload().
xwrite()
void FPGA_device::xwrite (xml_element * node) [override], [virtual]
Method to write an XML node.
Parameters
node is the node for writing the information
Implements target_device.
Definition at line 215 of file FPGA_device.cpp.
References xml_child::add_child_element(), target_device::has_parameter(), target_device::parameters, THROW_ASSERT, and WRITE_XNVM2.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/target_device/FPGA/FPGA_device.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/target_device/FPGA/FPGA_device.cpp