RemoveEndingIf Class Reference
STL include.
#include <remove_ending_if.hpp>
Public Member Functions
RemoveEndingIf (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~RemoveEndingIf () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
statement_list * sl
The statement list of the analyzed function.
tree_managerRef TM
The tree manager.
tree_manipulationRef tree_man
The tree manipulation.
ScheduleRef schedule
The scheduling solution.
Additional Inherited Members
Detailed Description
STL include.
Structure the original short circuit
Definition at line 73 of file remove_ending_if.hpp.
Constructor & Destructor Documentation
RemoveEndingIf()
RemoveEndingIf::RemoveEndingIf (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
. include src/algorithms/graph_helpers include behavior includes design_flows include hls includes HLS/module_allocation include parser/treegcc include STD include STL include tree includes Constructor implementation
Definition at line 144 of file remove_ending_if.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~RemoveEndingIf().
 RemoveEndingIf()
RemoveEndingIf::~RemoveEndingIf () [override], [default]
Destructor.
Referenced by RemoveEndingIf().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > RemoveEndingIf::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 152 of file remove_ending_if.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::GetSignature(), DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SUCCESS, SWITCH_FIX, THROW_UNREACHABLE, and USE_COUNTING.
HasToBeExecuted()
bool RemoveEndingIf::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
If no schedule exists, this step has NOT to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 201 of file remove_ending_if.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), and DesignFlowStep::parameters.
Initialize()
void RemoveEndingIf::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 185 of file remove_ending_if.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), DesignFlowStep::parameters, schedule, sl, TM, and tree_man.
InternalExec()
DesignFlowStep_Status RemoveEndingIf::InternalExec () [override], [virtual]
Restructures the unstructured code.
The basic block containing the if must have two successors
Implements FunctionFrontendFlowStep.
Definition at line 214 of file remove_ending_if.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, Schedule::GetEndingTime(), FunctionFrontendFlowStep::GetName(), Schedule::GetStartingTime(), INDENT_DBG_MEX, statement_list::list_of_bloc, max(), min, schedule, sl, SUCCESS, and UNCHANGED.
Field Documentation
schedule
ScheduleRef RemoveEndingIf::schedule [private]
The scheduling solution.
Definition at line 86 of file remove_ending_if.hpp.
Referenced by Initialize(), and InternalExec().
sl
statement_list* RemoveEndingIf::sl [private]
The statement list of the analyzed function.
Definition at line 77 of file remove_ending_if.hpp.
Referenced by Initialize(), and InternalExec().
TM
tree_managerRef RemoveEndingIf::TM [private]
The tree manager.
Definition at line 80 of file remove_ending_if.hpp.
Referenced by Initialize().
tree_man
tree_manipulationRef RemoveEndingIf::tree_man [private]
The tree manipulation.
Definition at line 83 of file remove_ending_if.hpp.
Referenced by Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/remove_ending_if.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/remove_ending_if.cpp