HDLFunctionDeclFix Class Reference
Superclass include.
#include <hdl_function_decl_fix.hpp>
Public Member Functions
HDLFunctionDeclFix (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~HDLFunctionDeclFix () override
Destructor.
DesignFlowStep_Status Exec () override
Fixes the var_decl duplication.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Frontend flow step which changes names of functions with clash with names of auxiliary signals
Definition at line 49 of file hdl_function_decl_fix.hpp.
Constructor & Destructor Documentation
HDLFunctionDeclFix()
HDLFunctionDeclFix::HDLFunctionDeclFix (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior include design_flows/backend/ToHDL include HLS includes parser/treegcc include tree includes
Definition at line 67 of file hdl_function_decl_fix.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~HDLFunctionDeclFix().
 HDLFunctionDeclFix()
HDLFunctionDeclFix::~HDLFunctionDeclFix () [override], [default]
Destructor.
Referenced by HDLFunctionDeclFix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > HDLFunctionDeclFix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 127 of file hdl_function_decl_fix.cpp.
References CREATE_TREE_MANAGER, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status HDLFunctionDeclFix::Exec () [override], [virtual]
Fixes the var_decl duplication.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 75 of file hdl_function_decl_fix.cpp.
References FrontendFlowStep::AppM, tree_manager::create_tree_node(), language_writer::create_writer(), tree_manager::find(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetAllFunctions(), tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, STR, SUCCESS, TOK, TOK_STRG, test_panda::type, UNCHANGED, and VHDL.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/hdl_function_decl_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/hdl_function_decl_fix.cpp