LoadDeviceTechnology Class Reference
Step which loads device dependent technology information.
#include <load_device_technology.hpp>
Public Member Functions
LoadDeviceTechnology (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~LoadDeviceTechnology () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Step which loads device dependent technology information.
Definition at line 56 of file load_device_technology.hpp.
Constructor & Destructor Documentation
LoadDeviceTechnology()
LoadDeviceTechnology::LoadDeviceTechnology (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
TM is the technology manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include parser/polixml include polixml include technology/target_device include utility include
Definition at line 60 of file load_device_technology.cpp.
References LOAD_DEVICE_TECHNOLOGY, and ~LoadDeviceTechnology().
 LoadDeviceTechnology()
LoadDeviceTechnology::~LoadDeviceTechnology () [override], [default]
Destructor.
Referenced by LoadDeviceTechnology().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > LoadDeviceTechnology::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 67 of file load_device_technology.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_DEFAULT_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status LoadDeviceTechnology::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
load specific device information
Implements DesignFlowStep.
Definition at line 97 of file load_device_technology.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_MINIMUM, DEBUG_LEVEL_VERBOSE, XMLDomParser::Exec(), XMLDomParser::get_document(), DesignFlowStep::parameters, test_panda::parser, PRINT_DBG_MEX, SUCCESS, TechnologyFlowStep::target, and THROW_ERROR.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_device_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_device_technology.cpp