TestbenchGenerationBaseStep Class Reference
STD include.
#include <testbench_generation_base_step.hpp>
Public Member Functions
~TestbenchGenerationBaseStep () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Static Public Member Functions
static std::string print_var_init (const tree_managerConstRef TreeM, unsigned int var, const memoryRef mem)
Protected Member Functions
std::string create_HDL_testbench (bool xilinx_isim) const
Creates the HDL testbench file associated with the given component.
void write_hdl_testbench (std::string simulation_values_path, bool generate_vcd_output, bool xilinx_isim, const tree_managerConstRef TreeM) const
Write the hdl testbench.
void write_hdl_testbench_prolog () const
void write_module_begin () const
void write_compute_ulps_functions () const
void write_auxiliary_signal_declaration () const
void write_module_instantiation (bool xilinx_isim) const
void begin_initial_block () const
void open_result_file (const std::string &result_file) const
void initialize_auxiliary_variables () const
void initialize_input_signals (const tree_managerConstRef TreeM) const
void open_value_file (const std::string &input_values_filename) const
void memory_initialization () const
void write_output_checks (const tree_managerConstRef TreeM) const
void end_initial_block () const
void begin_file_reading_operation () const
void reading_base_memory_address_from_file () const
void memory_initialization_from_file () const
void read_input_value_from_file (const std::string &input_name, bool &first_valid_input) const
void end_file_reading_operation () const
void write_max_simulation_time_control () const
void write_clock_process () const
void write_module_end () const
void testbench_controller_machine () const
void write_sim_time_calc () const
void write_underlying_testbench (std::string simulation_values_path, bool generate_vcd_output, bool xilinx_isim, const tree_managerConstRef TreeM) const
void write_initial_block (const std::string &simulation_values_path, bool withMemory, const tree_managerConstRef TreeM, bool generate_vcd_output) const
std::string verilator_testbench () const
Generates and execute the Verilator testbench file associated with the given component.
std::string write_verilator_testbench (const std::string &input_file) const
Write the verilator testbench.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
virtual void write_signals (const tree_managerConstRef TreeM, bool &withMemory, bool &hasMultiIrq) const =0
virtual void write_slave_initializations (bool withMemory) const =0
virtual void write_memory_handler () const =0
virtual void write_interface_handler () const =0
virtual void write_call (bool hasMultiIrq) const =0
virtual void write_file_reading_operations () const =0
virtual void init_extra_signals (bool withMemory) const
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
TestbenchGenerationBaseStep (const ParameterConstRef Param, const HLS_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, std::string c_testbench_basename=`values`)
Constructor.
Protected Attributes
const language_writerRef writer
structural_objectRef cir
const module * mod
double target_period
const std::string output_directory
output directory
const std::string c_testbench_basename
std::string hdl_testbench_basename
testbench basename
bool flag_cpp
true if the c testbench is generated to wrap c++
Additional Inherited Members
Detailed Description
STD include.
STL include TestbenchGenerationBaseStep is a Facade class that hide implementation details of the testbench creation.
Definition at line 83 of file testbench_generation_base_step.hpp.
Constructor & Destructor Documentation
TestbenchGenerationBaseStep()
TestbenchGenerationBaseStep::TestbenchGenerationBaseStep (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type, std::string _c_testbench_basename = `values`) [protected]
Constructor.
Autoheader include.
Declared protected to prevent direct instantiation. Use Create() factory methods instead.
Header include . include behavior include circuit include constants include design_flows include design_flows/backend/ToHDL includes HLS include HLS/binding/module include HLS/memory include technology/physical_library tree include utility include
Definition at line 108 of file testbench_generation_base_step.cpp.
References flag_cpp, output_directory, and ~TestbenchGenerationBaseStep().
 TestbenchGenerationBaseStep()
TestbenchGenerationBaseStep::~TestbenchGenerationBaseStep () [override], [default]
Destructor.
Referenced by TestbenchGenerationBaseStep().
Member Function Documentation
begin_file_reading_operation()
void TestbenchGenerationBaseStep::begin_file_reading_operation () const [protected]
Definition at line 2004 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, START_PORT_NAME, STD_OPENING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
begin_initial_block()
void TestbenchGenerationBaseStep::begin_initial_block () const [protected]
Definition at line 1715 of file testbench_generation_base_step.cpp.
References STD_OPENING_CHAR, STR, and writer.
Referenced by write_initial_block().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > TestbenchGenerationBaseStep::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 124 of file testbench_generation_base_step.cpp.
References HLS_step::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SUCCESS, TEST_VECTOR_PARSER, TESTBENCH_MEMORY_ALLOCATION, TESTBENCH_VALUES_C_GENERATION, TESTBENCH_VALUES_XML_GENERATION, THROW_UNREACHABLE, and TOP_FUNCTION.
create_HDL_testbench()
std::string TestbenchGenerationBaseStep::create_HDL_testbench (bool xilinx_isim) const [protected]
Creates the HDL testbench file associated with the given component.
Definition at line 335 of file testbench_generation_base_step.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, hdl_testbench_basename, HLS_step::HLSMgr, INDENT_DBG_MEX, output_directory, DesignFlowStep::parameters, PRINT_DBG_MEX, STR, STR_CST_testbench_generation_basename, write_hdl_testbench(), and writer.
Referenced by Exec().
end_file_reading_operation()
void TestbenchGenerationBaseStep::end_file_reading_operation () const [protected]
Definition at line 2017 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
end_initial_block()
void TestbenchGenerationBaseStep::end_initial_block () const [protected]
Definition at line 1724 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STR, and writer.
Referenced by write_initial_block().
Exec()
DesignFlowStep_Status TestbenchGenerationBaseStep::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 175 of file testbench_generation_base_step.cpp.
References create_HDL_testbench(), HLS_step::HLSMgr, DesignFlowStep::parameters, SUCCESS, and verilator_testbench().
HasToBeExecuted()
bool TestbenchGenerationBaseStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 2246 of file testbench_generation_base_step.cpp.
init_extra_signals()
void TestbenchGenerationBaseStep::init_extra_signals (bool withMemory) const [protected], [virtual]
Reimplemented in WishboneInterfaceTestbench.
Definition at line 435 of file testbench_generation_base_step.cpp.
References cir, module::find_member(), structural_object::get_kind(), mod, port_o_K, port_vector_o_K, RETURN_PORT_NAME, STR, THROW_ASSERT, and writer.
Referenced by write_initial_block().
Initialize()
void TestbenchGenerationBaseStep::Initialize () [override], [protected], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 162 of file testbench_generation_base_step.cpp.
References cir, structural_object::get_id(), hdl_testbench_basename, HLS_step::HLSMgr, mod, target_period, and THROW_ASSERT.
initialize_auxiliary_variables()
void TestbenchGenerationBaseStep::initialize_auxiliary_variables () const [protected]
Definition at line 1763 of file testbench_generation_base_step.cpp.
References RESET_PORT_NAME, and writer.
Referenced by write_initial_block().
initialize_input_signals()
void TestbenchGenerationBaseStep::initialize_input_signals (const tree_managerConstRef TreeM) const [protected]
Definition at line 1783 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), refcount< T >::get(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), module::get_out_port(), module::get_out_port_size(), structural_object::get_typeRef(), tree_helper::is_a_pointer(), mod, DesignFlowStep::parameters, RESET_PORT_NAME, START_PORT_NAME, structural_type_descriptor::treenode, WB_ACKIM_PORT_NAME, and writer.
Referenced by write_initial_block().
memory_initialization()
void TestbenchGenerationBaseStep::memory_initialization () const [protected]
Definition at line 1908 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_initial_block().
memory_initialization_from_file()
void TestbenchGenerationBaseStep::memory_initialization_from_file () const [protected]
Definition at line 1975 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
open_result_file()
void TestbenchGenerationBaseStep::open_result_file (const std::string & result_file) const [protected]
Definition at line 1746 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_initial_block().
open_value_file()
void TestbenchGenerationBaseStep::open_value_file (const std::string & input_values_filename) const [protected]
Definition at line 1730 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_initial_block().
print_var_init()
std::string TestbenchGenerationBaseStep::print_var_init (const tree_managerConstRef TreeM, unsigned int var, const memoryRef mem) [static]
Definition at line 181 of file testbench_generation_base_step.cpp.
References tree_helper::get_array_data_bitsize(), tree_helper::get_array_num_elements(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_node(), tree_helper::is_an_array(), tree_helper::size(), and fu_binding::write_init().
Referenced by TestbenchMemoryAllocation::AllocTestbenchMemory(), minimal_interface::build_wrapper(), TestbenchValuesXMLGeneration::Exec(), and HLSCWriter::WriteSimulatorInitMemory().
read_input_value_from_file()
void TestbenchGenerationBaseStep::read_input_value_from_file (const std::string & input_name, bool & first_valid_input) const [protected]
write statement for new vectors' check
Definition at line 2049 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, DesignFlowStep::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, RESET_PORT_NAME, START_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by WishboneInterfaceTestbench::write_file_reading_operations(), and MinimalInterfaceTestbench::write_file_reading_operations().
reading_base_memory_address_from_file()
void TestbenchGenerationBaseStep::reading_base_memory_address_from_file () const [protected]
Definition at line 1938 of file testbench_generation_base_step.cpp.
References STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
testbench_controller_machine()
void TestbenchGenerationBaseStep::testbench_controller_machine () const [protected]
Definition at line 1829 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, HLS_step::HLSMgr, DesignFlowStep::parameters, RESET_PORT_NAME, and writer.
Referenced by write_underlying_testbench().
verilator_testbench()
std::string TestbenchGenerationBaseStep::verilator_testbench () const [protected]
Generates and execute the Verilator testbench file associated with the given component.
Definition at line 234 of file testbench_generation_base_step.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_MINIMUM, output_directory, DesignFlowStep::parameters, PRINT_DBG_MEX, STR, STR_CST_testbench_generation_basename, THROW_ERROR, and write_verilator_testbench().
Referenced by Exec().
write_auxiliary_signal_declaration()
void TestbenchGenerationBaseStep::write_auxiliary_signal_declaration () const [protected]
writing memory-related parameters
Definition at line 1628 of file testbench_generation_base_step.cpp.
References cir, HDL_manager::convert_to_identifier(), structural_object::ExistsParameter(), module::find_member(), refcount< T >::get(), structural_object::GetParameter(), HLS_step::HLSMgr, MEMORY_PARAMETER, mod, DesignFlowStep::parameters, port_o_K, STR, THROW_ASSERT, and writer.
Referenced by write_underlying_testbench().
write_call()
virtual void TestbenchGenerationBaseStep::write_call (bool hasMultiIrq) const [protected], [pure virtual]
Implemented in MinimalInterfaceTestbench, and WishboneInterfaceTestbench.
Referenced by write_underlying_testbench().
write_clock_process()
void TestbenchGenerationBaseStep::write_clock_process () const [protected]
write clock switching operation
Definition at line 1525 of file testbench_generation_base_step.cpp.
References writer.
Referenced by write_hdl_testbench().
write_compute_ulps_functions()
void TestbenchGenerationBaseStep::write_compute_ulps_functions () const [protected]
Definition at line 2158 of file testbench_generation_base_step.cpp.
References writer.
Referenced by write_underlying_testbench().
write_file_reading_operations()
virtual void TestbenchGenerationBaseStep::write_file_reading_operations () const [protected], [pure virtual]
Implemented in MinimalInterfaceTestbench, and WishboneInterfaceTestbench.
Referenced by write_underlying_testbench().
write_hdl_testbench()
void TestbenchGenerationBaseStep::write_hdl_testbench (std::string simulation_values_path, bool generate_vcd_output, bool xilinx_isim, const tree_managerConstRef TreeM) const [protected]
Write the hdl testbench.
This function takes care of generating the hdl testbench top component.
Parameters
hdl_file Output stream of the source file of the generated testbench.
writer Language writer.
simulation_values_path Path of the values file.
generate_vcd_output Enable/Disable vcd generation.
xilinx_isim Xilinx isim?
TreeM Tree Manager of the design under test.
Definition at line 358 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, structural_object::get_id(), mod, STR, write_clock_process(), write_underlying_testbench(), and writer.
Referenced by create_HDL_testbench().
write_hdl_testbench_prolog()
void TestbenchGenerationBaseStep::write_hdl_testbench_prolog () const [protected]
Definition at line 1532 of file testbench_generation_base_step.cpp.
References DesignFlowStep::parameters, STR, target_period, THROW_ERROR, and writer.
Referenced by write_underlying_testbench().
write_initial_block()
void TestbenchGenerationBaseStep::write_initial_block (const std::string & simulation_values_path, bool withMemory, const tree_managerConstRef TreeM, bool generate_vcd_output) const [protected]
VCD output generation (optional)
open file with values
open file with results
auxiliary variables initialization
Definition at line 374 of file testbench_generation_base_step.cpp.
References begin_initial_block(), end_initial_block(), HIERARCHY_SEPARATOR, HLS_step::HLSMgr, init_extra_signals(), initialize_auxiliary_variables(), initialize_input_signals(), memory_initialization(), open_result_file(), open_value_file(), output_directory, DesignFlowStep::parameters, STR, VHDL, and writer.
Referenced by write_underlying_testbench().
write_interface_handler()
virtual void TestbenchGenerationBaseStep::write_interface_handler () const [protected], [pure virtual]
Implemented in MinimalInterfaceTestbench, and WishboneInterfaceTestbench.
Referenced by write_underlying_testbench().
write_max_simulation_time_control()
void TestbenchGenerationBaseStep::write_max_simulation_time_control () const [protected]
Definition at line 1918 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
write_memory_handler()
virtual void TestbenchGenerationBaseStep::write_memory_handler () const [protected], [pure virtual]
Implemented in MinimalInterfaceTestbench, and WishboneInterfaceTestbench.
Referenced by write_underlying_testbench().
write_module_begin()
void TestbenchGenerationBaseStep::write_module_begin () const [protected]
Definition at line 1560 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, structural_object::get_id(), mod, STD_OPENING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
write_module_end()
void TestbenchGenerationBaseStep::write_module_end () const [protected]
Definition at line 1567 of file testbench_generation_base_step.cpp.
References DesignFlowStep::parameters, STD_CLOSING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
write_module_instantiation()
void TestbenchGenerationBaseStep::write_module_instantiation (bool xilinx_isim) const [protected]
write module instantiation and ports binding
Definition at line 1578 of file testbench_generation_base_step.cpp.
References cir, CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), language_writer::create_writer(), DONE_PORT_NAME, refcount< T >::get(), module::get_in_port(), module::get_in_port_size(), HDL_manager::get_mod_typename(), module::get_out_port(), module::get_out_port_size(), HLS_step::HLSMgr, mod, DesignFlowStep::parameters, RESET_PORT_NAME, START_PORT_NAME, STR, target_period, VERILOG, VHDL, and writer.
Referenced by write_underlying_testbench().
write_output_checks()
void TestbenchGenerationBaseStep::write_output_checks (const tree_managerConstRef TreeM) const [protected]
Definition at line 455 of file testbench_generation_base_step.cpp.
References cir, CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, module::find_member(), refcount< T >::get(), memory::get_function_parameters(), GET_INDEX_NODE, GET_NODE, tree_helper::get_pointed_type(), tree_manager::get_tree_node_const(), tree_helper::get_type_index(), GET_TYPE_SIZE, structural_object::get_typeRef(), BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, INDENT_DBG_MEX, INFERRED_INTERFACE_GENERATION, INTERFACE_CS_GENERATION, tree_helper::is_a_pointer(), tree_helper::is_real(), MINIMAL_INTERFACE_GENERATION, mod, NODE_NOT_YET_SUPPORTED_EC, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, port_o_K, BehavioralHelper::PrintVariable(), structural_type_descriptor::REAL, resize_to_1_8_16_32_64_128_256_512(), RETURN_PORT_NAME, tree_helper::size(), STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, structural_type_descriptor::type, WB4_INTERFACE_GENERATION, and writer.
Referenced by write_underlying_testbench().
write_signals()
virtual void TestbenchGenerationBaseStep::write_signals (const tree_managerConstRef TreeM, bool & withMemory, bool & hasMultiIrq) const [protected], [pure virtual]
Implemented in MinimalInterfaceTestbench, and WishboneInterfaceTestbench.
Referenced by write_underlying_testbench().
write_sim_time_calc()
void TestbenchGenerationBaseStep::write_sim_time_calc () const [protected]
Definition at line 2027 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and writer.
Referenced by write_underlying_testbench().
write_slave_initializations()
virtual void TestbenchGenerationBaseStep::write_slave_initializations (bool withMemory) const [protected], [pure virtual]
Implemented in MinimalInterfaceTestbench, and WishboneInterfaceTestbench.
Referenced by write_underlying_testbench().
write_underlying_testbench()
void TestbenchGenerationBaseStep::write_underlying_testbench (std::string simulation_values_path, bool generate_vcd_output, bool xilinx_isim, const tree_managerConstRef TreeM) const [protected]
Definition at line 1493 of file testbench_generation_base_step.cpp.
References begin_file_reading_operation(), end_file_reading_operation(), module::get_in_out_port_size(), memory_initialization_from_file(), mod, reading_base_memory_address_from_file(), testbench_controller_machine(), THROW_ERROR, write_auxiliary_signal_declaration(), write_call(), write_compute_ulps_functions(), write_file_reading_operations(), write_hdl_testbench_prolog(), write_initial_block(), write_interface_handler(), write_max_simulation_time_control(), write_memory_handler(), write_module_begin(), write_module_end(), write_module_instantiation(), write_output_checks(), write_signals(), write_sim_time_calc(), and write_slave_initializations().
Referenced by write_hdl_testbench(), and write_verilator_testbench().
write_verilator_testbench()
std::string TestbenchGenerationBaseStep::write_verilator_testbench (const std::string & input_file) const [protected]
Write the verilator testbench.
Parameters
input_file Filename of the stimuli file.
Definition at line 252 of file testbench_generation_base_step.cpp.
References CLOCK_PORT_NAME, structural_object::get_typeRef(), hdl_testbench_basename, HLS_step::HLSMgr, structural_type_descriptor::id_type, mod, output_directory, DesignFlowStep::parameters, STR, target_period, write_underlying_testbench(), and writer.
Referenced by verilator_testbench().
Field Documentation
c_testbench_basename
const std::string TestbenchGenerationBaseStep::c_testbench_basename [protected]
Definition at line 97 of file testbench_generation_base_step.hpp.
cir
structural_objectRef TestbenchGenerationBaseStep::cir [protected]
Definition at line 88 of file testbench_generation_base_step.hpp.
Referenced by init_extra_signals(), Initialize(), write_auxiliary_signal_declaration(), MinimalInterfaceTestbench::write_call(), MinimalInterfaceTestbench::write_file_reading_operations(), MinimalInterfaceTestbench::write_interface_handler(), WishboneInterfaceTestbench::write_memory_handler(), MinimalInterfaceTestbench::write_memory_handler(), write_module_instantiation(), write_output_checks(), and MinimalInterfaceTestbench::write_signals().
flag_cpp
bool TestbenchGenerationBaseStep::flag_cpp [protected]
true if the c testbench is generated to wrap c++
Definition at line 103 of file testbench_generation_base_step.hpp.
Referenced by TestbenchGenerationBaseStep(), MinimalInterfaceTestbench::write_input_signal_declaration(), and WishboneInterfaceTestbench::write_signals().
hdl_testbench_basename
std::string TestbenchGenerationBaseStep::hdl_testbench_basename [protected]
testbench basename
Definition at line 100 of file testbench_generation_base_step.hpp.
Referenced by create_HDL_testbench(), Initialize(), and write_verilator_testbench().
mod
const module* TestbenchGenerationBaseStep::mod [protected]
Definition at line 90 of file testbench_generation_base_step.hpp.
Referenced by init_extra_signals(), Initialize(), initialize_input_signals(), write_auxiliary_signal_declaration(), MinimalInterfaceTestbench::write_call(), MinimalInterfaceTestbench::write_file_reading_operations(), write_hdl_testbench(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), WishboneInterfaceTestbench::write_memory_handler(), MinimalInterfaceTestbench::write_memory_handler(), write_module_begin(), write_module_instantiation(), write_output_checks(), MinimalInterfaceTestbench::write_output_signal_declaration(), MinimalInterfaceTestbench::write_signals(), MinimalInterfaceTestbench::write_slave_initializations(), write_underlying_testbench(), write_verilator_testbench(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), and WishboneInterfaceTestbench::write_wishbone_output_signal_declaration().
output_directory
const std::string TestbenchGenerationBaseStep::output_directory [protected]
output directory
Definition at line 95 of file testbench_generation_base_step.hpp.
Referenced by create_HDL_testbench(), TestbenchGenerationBaseStep(), verilator_testbench(), write_initial_block(), and write_verilator_testbench().
target_period
double TestbenchGenerationBaseStep::target_period [protected]
Definition at line 92 of file testbench_generation_base_step.hpp.
Referenced by Initialize(), write_hdl_testbench_prolog(), write_module_instantiation(), and write_verilator_testbench().
writer
const language_writerRef TestbenchGenerationBaseStep::writer [protected]
Definition at line 86 of file testbench_generation_base_step.hpp.
Referenced by begin_file_reading_operation(), begin_initial_block(), MinimalInterfaceTestbench::cond_load(), create_HDL_testbench(), end_file_reading_operation(), end_initial_block(), init_extra_signals(), initialize_auxiliary_variables(), initialize_input_signals(), memory_initialization(), memory_initialization_from_file(), open_result_file(), open_value_file(), read_input_value_from_file(), MinimalInterfaceTestbench::read_input_value_from_file_RNONE(), reading_base_memory_address_from_file(), testbench_controller_machine(), write_auxiliary_signal_declaration(), WishboneInterfaceTestbench::write_call(), MinimalInterfaceTestbench::write_call(), write_clock_process(), write_compute_ulps_functions(), WishboneInterfaceTestbench::write_file_reading_operations(), MinimalInterfaceTestbench::write_file_reading_operations(), write_hdl_testbench(), write_hdl_testbench_prolog(), write_initial_block(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), write_max_simulation_time_control(), WishboneInterfaceTestbench::write_memory_handler(), MinimalInterfaceTestbench::write_memory_handler(), write_module_begin(), write_module_end(), write_module_instantiation(), write_output_checks(), MinimalInterfaceTestbench::write_output_signal_declaration(), WishboneInterfaceTestbench::write_signals(), MinimalInterfaceTestbench::write_signals(), write_sim_time_calc(), MinimalInterfaceTestbench::write_slave_initializations(), write_verilator_testbench(), WishboneInterfaceTestbench::write_wishbone_callFSM_signal_declaration(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), and WishboneInterfaceTestbench::write_wishbone_output_signal_declaration().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_generation_base_step.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_generation_base_step.cpp