generic_obj Class Reference
Generic class managing all resources into datapath.
#include <generic_obj.hpp>
Public Types
enum resource_type {
FUNCTIONAL_UNIT = 0,
REGISTER,
MULTI_UNBOUNDED_OBJ,
COMMAND_PORT,
DATA_PORT,
CONNECTION_ELEMENT,
MULTIPLIER_CONN_OBJ,
ADDER_CONN_OBJ,
UU_CONV_CONN_OBJ,
UI_CONV_CONN_OBJ,
IU_CONV_CONN_OBJ,
II_CONV_CONN_OBJ,
FF_CONV_CONN_OBJ,
I_ASSIGN_CONN_OBJ,
U_ASSIGN_CONN_OBJ,
VB_ASSIGN_CONN_OBJ,
F_ASSIGN_CONN_OBJ,
BITFIELD_OBJ,
CONSTRUCTOR_CONN_OBJ
 }
Admissible resource types.
Public Member Functions
generic_obj (const resource_type t, std::string _name)
This is the constructor of the object class.
virtual ~generic_obj ()
Destructor.
void print (std::ostream &os) const
Prints elements into given stream.
const std::string get_string () const
Returns the name associated with the element.
unsigned int get_type () const
Return generic_obj type.
void set_structural_obj (const structural_objectRef &SM_)
Sets structural_object associated to this object.
void set_out_sign (const structural_objectRef &out_sign_)
Sets structural_object of output signal associated to this object.
const structural_objectRef & get_structural_obj () const
Gets structural_object associated to this object.
const structural_objectRef & get_out_sign () const
Gets structural_object of output signal associated to this object.
bool operator< (const generic_obj &other) const
Protected Attributes
const resource_type type
type of resource
structural_objectRef SM
structural_object associated to element
structural_objectRef out_sign
output signal associated to element.
std::string name
connection obj id
Friends
std::ostream & operator<< (std::ostream &os, const generic_obj &s)
Friend definition of the << operator.
Detailed Description
Generic class managing all resources into datapath.
Definition at line 66 of file generic_obj.hpp.
Member Enumeration Documentation
resource_type
enum generic_obj::resource_type
Admissible resource types.
Enumerator
FUNCTIONAL_UNIT
REGISTER a functional resource
MULTI_UNBOUNDED_OBJ a register
COMMAND_PORT a multi unbounded controller
DATA_PORT a command port (mainly connections from/to controller)
CONNECTION_ELEMENT a data port (in/out data)
MULTIPLIER_CONN_OBJ an element used for connecting the resources (e.g., muxes)
ADDER_CONN_OBJ a multiplier object used to compute some addresses
UU_CONV_CONN_OBJ an adder object representation used to compute some addresses
UI_CONV_CONN_OBJ a converter from unsigned to unsigned int
IU_CONV_CONN_OBJ a converter from unsigned to signed int
II_CONV_CONN_OBJ a converter from signed to unsigned int
FF_CONV_CONN_OBJ a converter from signed to signed int
I_ASSIGN_CONN_OBJ a converter from real to real int
U_ASSIGN_CONN_OBJ specify the type of a connection object: INT
VB_ASSIGN_CONN_OBJ specify the type of a connection object: UINT
F_ASSIGN_CONN_OBJ specify the type of a connection object: VECTOR_BOOL
BITFIELD_OBJ specify the type of a connection object: REAL
CONSTRUCTOR_CONN_OBJ a connection unit that filters some bits a connection unit when the concatenation of a vector is considered
Definition at line 70 of file generic_obj.hpp.
Constructor & Destructor Documentation
generic_obj()
generic_obj::generic_obj (const resource_type t, std::string _name) [inline]
This is the constructor of the object class.
Definition at line 111 of file generic_obj.hpp.
 generic_obj()
virtual generic_obj::~generic_obj () [inline], [virtual]
Destructor.
Definition at line 118 of file generic_obj.hpp.
Member Function Documentation
get_out_sign()
const structural_objectRef& generic_obj::get_out_sign () const [inline]
Gets structural_object of output signal associated to this object.
Returns
a reference to structural_object of signal associated
Definition at line 193 of file generic_obj.hpp.
References operator<(), and out_sign.
Referenced by conn_binding::mux_connection().
get_string()
const std::string generic_obj::get_string () const [inline]
Returns the name associated with the element.
Returns
the name associated with element.
Definition at line 147 of file generic_obj.hpp.
References name.
Referenced by conn_binding::add_command_ports(), conn_binding::add_connection(), conn_binding::bind_selector_port(), mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), mux_connection_binding::create_single_conn(), mux_connection_binding::input_logic(), conn_binding::mux_connection(), mux_connection_binding::mux_interconnection(), GenericObjSorter::operator()(), operator<(), and conn_binding::print().
get_structural_obj()
const structural_objectRef& generic_obj::get_structural_obj () const [inline]
Gets structural_object associated to this object.
Returns
a reference to structural_object associated
Definition at line 184 of file generic_obj.hpp.
References SM.
Referenced by conn_binding::add_command_ports(), top_entity::add_ports(), conn_binding::mux_allocation(), conn_binding::mux_connection(), and conn_binding::specialise_mux().
get_type()
unsigned int generic_obj::get_type () const [inline]
Return generic_obj type.
See also
generic_obj::resource_type to get more details on meaning of value
Returns
an integer representing resource type
Definition at line 157 of file generic_obj.hpp.
References type.
Referenced by conn_binding::add_command_ports().
operator<()
bool generic_obj::operator< (const generic_obj & other) const
Parameters
other is the second operand
Returns
this < other
Definition at line 77 of file generic_obj.cpp.
References get_string().
Referenced by get_out_sign().
print()
void generic_obj::print (std::ostream & os) const [inline]
Prints elements into given stream.
Parameters
os is the selected stream
Definition at line 126 of file generic_obj.hpp.
References name.
Referenced by conn_binding::mux_connection().
set_out_sign()
void generic_obj::set_out_sign (const structural_objectRef & out_sign_) [inline]
Sets structural_object of output signal associated to this object.
Parameters
SM_ is reference to structural_object of signal to be associated
Definition at line 175 of file generic_obj.hpp.
Referenced by classic_datapath::add_ports(), and conn_binding::mux_connection().
set_structural_obj()
void generic_obj::set_structural_obj (const structural_objectRef & SM_) [inline]
Sets structural_object associated to this object.
Parameters
SM_ is reference to structural_object to be associated
Definition at line 166 of file generic_obj.hpp.
Referenced by classic_datapath::add_ports().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const generic_obj & s) [friend]
Friend definition of the << operator.
Parameters
os is output stream
s is object to be written
Returns
the stream where the object is written
Definition at line 137 of file generic_obj.hpp.
Field Documentation
name
std::string generic_obj::name [protected]
connection obj id
Definition at line 105 of file generic_obj.hpp.
Referenced by get_string(), and print().
out_sign
structural_objectRef generic_obj::out_sign [protected]
output signal associated to element.
It allows to connect multiple elements to output of this object. So broadcast communication is possible
Definition at line 102 of file generic_obj.hpp.
Referenced by get_out_sign().
SM
structural_objectRef generic_obj::SM [protected]
structural_object associated to element
Definition at line 98 of file generic_obj.hpp.
Referenced by get_structural_obj().
type
const resource_type generic_obj::type [protected]
type of resource
Definition at line 95 of file generic_obj.hpp.
Referenced by get_type().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/virtual_components/generic_obj.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/virtual_components/generic_obj.cpp