SwitchFix Class Reference
Superclass include.
#include <switch_fix.hpp>
Public Member Functions
SwitchFix (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~SwitchFix () override
Destructor.
DesignFlowStep_Status InternalExec () override
Updates the tree to have a more compliant CFG.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Restructuring the basic block structures to fix switches
Definition at line 53 of file switch_fix.hpp.
Constructor & Destructor Documentation
SwitchFix()
SwitchFix::SwitchFix (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
parameters set of input parameters
. include behavior include parser/treegcc include tree include
Definition at line 68 of file switch_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~SwitchFix().
 SwitchFix()
SwitchFix::~SwitchFix () [override], [default]
Destructor.
Referenced by SwitchFix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionFrontendFlowStep::FunctionRelationship > > SwitchFix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 76 of file switch_fix.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status SwitchFix::InternalExec () [override], [virtual]
Updates the tree to have a more compliant CFG.
Returns
the exit status of this step
Fix switch statements
The set of basic blocks which contain more than a label; this fix has to be performed before multiple_pred_switch check
Compute the case labels of the switch
First check that the first label is a case
Each label has to be put into a different basic block; first label is threated in a different way since it can have multiple predecessor Create new basic block
Updating successors of the predecessor of the current block when they are not the switch
This is an intermediate label
Create new basic block
Predecessor of current node has to be fixed
Check if this is a case : and not a label : - if so remove this from successor of switch, otherwise add switch to predecessor of this
create the gimple_multi_way_if node
Map between label decl index and corresponding case value
The destination of the default
Building list of conds
Default
Implements FunctionFrontendFlowStep.
Definition at line 102 of file switch_fix.cpp.
References FrontendFlowStep::AppM, tree_manager::CGetTreeNode(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, index, tree_vec::list_of_op, tree_manager::new_tree_node_id(), DesignFlowStep::parameters, phi, FrontendFlowStep::PrintTreeManager(), sl, STR, SUCCESS, THROW_ASSERT, TOK, TOK_ARTIFICIAL, TOK_OP, TOK_SCPE, TOK_SRCP, TOK_TYPE, ToString(), and FunctionFrontendFlowStep::WriteBBGraphDot().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/switch_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/switch_fix.cpp