LUT_model Class Reference
#include <LUT_model.hpp>
Public Types
enum value_t { COMBINATIONAL_DELAY,
MINIMUM_PERIOD_POST_MAP,
MINIMUM_PERIOD_POST_PAR
 }
Public Member Functions
void xwrite (xml_element *pin_node, const std::string &output_pin) override
void set_timing_value (value_t val, double num)
Sets the timing information for the specified type.
bool is_timing_value (value_t val) const
Returns true if the specified timing value has been set, false otherwise.
double get_timing_value (value_t val) const
Returns the timing information for the given type.
 Constructors and destructors.
LUT_model (const ParameterConstRef Param)
Constructor.
~LUT_model () override
Destructor.
Protected Attributes
std::map< value_t, double > timing_results
timing characterization
Additional Inherited Members
Detailed Description
Definition at line 57 of file LUT_model.hpp.
Member Enumeration Documentation
value_t
enum LUT_model::value_t
Enumerator
COMBINATIONAL_DELAY
MINIMUM_PERIOD_POST_MAP
MINIMUM_PERIOD_POST_PAR
Definition at line 60 of file LUT_model.hpp.
Constructor & Destructor Documentation
LUT_model()
LUT_model::LUT_model (const ParameterConstRef Param) [explicit]
Constructor.
Definition at line 47 of file LUT_model.cpp.
References ~LUT_model().
 LUT_model()
LUT_model::~LUT_model () [override], [default]
Destructor.
Referenced by LUT_model().
Member Function Documentation
get_timing_value()
double LUT_model::get_timing_value (value_t val) const
Returns the timing information for the given type.
Definition at line 68 of file LUT_model.cpp.
References is_timing_value(), and timing_results.
is_timing_value()
bool LUT_model::is_timing_value (value_t val) const
Returns true if the specified timing value has been set, false otherwise.
Definition at line 63 of file LUT_model.cpp.
References timing_results.
Referenced by get_timing_value().
set_timing_value()
void LUT_model::set_timing_value (value_t val, double num)
Sets the timing information for the specified type.
Definition at line 57 of file LUT_model.cpp.
References time_model::execution_time, and timing_results.
xwrite()
void LUT_model::xwrite (xml_element * pin_node, const std::string & output_pin) [override], [virtual]
Implements time_model.
Definition at line 53 of file LUT_model.cpp.
Field Documentation
timing_results
std::map<value_t, double> LUT_model::timing_results [protected]
timing characterization
Definition at line 69 of file LUT_model.hpp.
Referenced by get_timing_value(), is_timing_value(), and set_timing_value().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/time/LUT_model.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/time/LUT_model.cpp