xst_wrapper Class Reference
Main class for wrapping ISE tools by Xilinx.
#include <xst_wrapper.hpp>
Public Member Functions
xst_wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~xst_wrapper () override
Destructor.
Protected Member Functions
void GenerateProjectFile (const DesignParametersRef &dp)
Generates project file.
void init_reserved_vars () override
Initializes the reserved variables.
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Additional Inherited Members
Detailed Description
Main class for wrapping ISE tools by Xilinx.
Definition at line 72 of file xst_wrapper.hpp.
Constructor & Destructor Documentation
xst_wrapper()
xst_wrapper::xst_wrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Includes the class definition.
Parameters
Param is the set of parameters
Definition at line 61 of file xst_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, GET_CLASS, PRINT_DBG_MEX, and ~xst_wrapper().
 xst_wrapper()
xst_wrapper::~xst_wrapper () [override], [default]
Destructor.
Referenced by xst_wrapper().
Member Function Documentation
EvaluateVariables()
void xst_wrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 116 of file xst_wrapper.cpp.
References DesignParameters::assign(), GenerateProjectFile(), DesignParameters::get_value(), SynthesisTool::output_dir, PARAM_top_id, PARAM_xst_hdpdir, PARAM_xst_log_file, PARAM_xst_report, and PARAM_xst_tmpdir.
GenerateProjectFile()
void xst_wrapper::GenerateProjectFile (const DesignParametersRef & dp) [protected]
Generates project file.
Definition at line 76 of file xst_wrapper.cpp.
References DesignParameters::assign(), SynthesisTool::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, flopoco::filename, DesignParameters::get_value(), GetExtension(), INDENT_DBG_MEX, PARAM_HDL_files, PARAM_top_id, PARAM_xst_prj_file, PARAM_xst_tmpdir, and THROW_ERROR.
Referenced by EvaluateVariables().
get_command_line()
std::string xst_wrapper::get_command_line (const DesignParametersRef & dp) const [override], [protected], [virtual]
Returns the proper command line.
Implements SynthesisTool.
Definition at line 126 of file xst_wrapper.cpp.
References SynthesisTool::get_tool_exec(), DesignParameters::parameter_values, SynthesisTool::replace_parameters(), SCRIPT_FILENAME, XilinxWrapper::toString(), and SynthesisTool::xml_tool_options.
init_reserved_vars()
void xst_wrapper::init_reserved_vars () [override], [protected], [virtual]
Initializes the reserved variables.
Reimplemented from SynthesisTool.
Definition at line 70 of file xst_wrapper.cpp.
References ADD_RES_VAR, SynthesisTool::init_reserved_vars(), and PARAM_xst_log_file.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/ise/xst_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/ise/xst_wrapper.cpp