functional_unit Struct Reference
This class specifies the characteristic of a particular functional unit.
#include <technology_node.hpp>
Public Types
enum type_t {
UNKNOWN = 0,
COMBINATIONAL,
STATETABLE,
FF,
LATCH,
PHYSICAL
 }
typedef std::vector< technology_nodeRef > operation_vec
Type definition of a vector of functional_unit.
Public Member Functions
functional_unit ()
Constructor.
functional_unit (const xml_nodeRef XML_description)
Constructor.
~functional_unit () override
Destructor.
void add (const technology_nodeRef &curr)
Add the given operation to the current functional_unit.
void set_clock_period (double _clock_period)
Sets the clock period adopted for the synthesis (0 means that it has been generated with unconstrained synthesis) (in ns)
double get_clock_period () const
Returns the clock period adopted for the synthesis (0 means that it has been generated with unconstrained synthesis) (in ns)
void set_clock_period_resource_fraction (double _clock_period_resource_fraction)
Sets the clock period resource fraction adopted for the synthesis.
double get_clock_period_resource_fraction () const
Returns the clock period resource fraction adopted for the synthesis.
const operation_vec & get_operations () const
Return the operations that the functional unit can handle.
size_t get_operations_num () const
Return the number of the operations that the functional unit can handle.
technology_nodeRef get_operation (const std::string &op_name) const
This method returns the operationRef from its name if the functional unit contains an operation of type op_name.
const std::string & get_name () const override
Return the name of the operation.
void xload (const xml_element *node, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) override
Load a functional unit starting from an xml file.
void xwrite (xml_element *rootnode, const technology_nodeRef tn, const ParameterConstRef Param, const TargetDevice_Type type) override
Add a functional unit to an xml tree.
void lib_write (std::ofstream &os, const simple_indentRef PP) override
Append a technology_node to a liberty file.
void lef_write (std::ofstream &os, const simple_indentRef PP) override
Append a technology_node to a LEF file.
void print (std::ostream &os) const override
function that prints the class functional_unit.
Data Fields
type_t logical_type
return the logical type of the cell
std::string functional_unit_name
name of the functional unit.
std::vector< std::string > ordered_attributes
list of attributes associated to the components
std::map< std::string, attributeRef > attributes
map between the attribute keys and the corresponding values
double clock_period
clock period adopted for the synthesis (in ns)
double clock_period_resource_fraction
clock period resource fraction
area_modelRef area_m
This variable stores the resource information of the component.
xml_nodeRef XML_description
pointer to the XML description of the cell
std::string fu_template_name
Name of the template.
std::string fu_template_parameters
Template parameters.
std::string characterizing_constant_value
Value used during the characterization of this instance.
std::string memory_type
Specify the type of memory the functional unit is compliant with.
std::string channels_type
Specify the type of the channel the functional unit is compliant with.
std::string memory_ctrl_type
Specify the type of memory controller the functional unit is compliant with.
std::string bram_load_latency
Specify the bram load latency the functional unit is compliant with.
std::string component_timing_alias
Specify that the functional unit has the same timing per operation it has the one specified by this field.
TimeStamp characterization_timestamp
The timestamp of the characterization of this functional unit.
Private Attributes
std::map< std::string, technology_nodeRef > op_name_to_op
Redefinition of get_kind_text()
operation_vec list_of_operation
At each functional unit can be associate several operations with different performances.
Friends
class technology_manager
Additional Inherited Members
Detailed Description
This class specifies the characteristic of a particular functional unit.
Definition at line 503 of file technology_node.hpp.
Member Typedef Documentation
operation_vec
typedef std::vector<technology_nodeRef> functional_unit::operation_vec
Type definition of a vector of functional_unit.
Definition at line 516 of file technology_node.hpp.
Member Enumeration Documentation
type_t
enum functional_unit::type_t
Enumerator
UNKNOWN
COMBINATIONAL
STATETABLE
FF
LATCH
PHYSICAL
Definition at line 505 of file technology_node.hpp.
Constructor & Destructor Documentation
functional_unit() [1/2]
functional_unit::functional_unit ()
Constructor.
Definition at line 355 of file technology_node.cpp.
functional_unit() [2/2]
functional_unit::functional_unit (const xml_nodeRef XML_description) [explicit]
Constructor.
Definition at line 359 of file technology_node.cpp.
References ~functional_unit().
 functional_unit()
functional_unit::~functional_unit () [override], [default]
Destructor.
Referenced by functional_unit().
Member Function Documentation
add()
void functional_unit::add (const technology_nodeRef & curr) [inline]
Add the given operation to the current functional_unit.
Parameters
curr is the added element
Definition at line 602 of file technology_node.hpp.
Referenced by get_operation(), xload(), and xwrite().
get_clock_period()
double functional_unit::get_clock_period () const [inline]
Returns the clock period adopted for the synthesis (0 means that it has been generated with unconstrained synthesis) (in ns)
Definition at line 622 of file technology_node.hpp.
get_clock_period_resource_fraction()
double functional_unit::get_clock_period_resource_fraction () const [inline]
Returns the clock period resource fraction adopted for the synthesis.
Definition at line 635 of file technology_node.hpp.
get_name()
const std::string& functional_unit::get_name () const [inline], [override], [virtual]
Return the name of the operation.
Implements technology_node.
Definition at line 667 of file technology_node.hpp.
References GET_TEC_KIND, GET_TEC_KIND_TEXT, technology_node::lef_write(), technology_node::lib_write(), technology_node::PP, technology_node::print(), test_panda::type, technology_node::xload(), and technology_node::xwrite().
Referenced by GenerateFuList::AnalyzeCell(), RTLCharacterization::AnalyzeCell(), and FunctionalUnitStep::AnalyzeFu().
get_operation()
technology_nodeRef functional_unit::get_operation (const std::string & op_name) const
This method returns the operationRef from its name if the functional unit contains an operation of type op_name.
Definition at line 408 of file technology_node.cpp.
References add(), module::add_in_port(), module::add_out_port(), COMBINATIONAL, NP_functionality::EQUATION, functional_unit_name, port_o::IN, logical_type, op_name_to_op, port_o::OUT, structural_object::set_id(), structural_object::set_type(), SplitString(), and THROW_ERROR.
Referenced by allocation::get_compliant_pipelined_unit(), AllocationInformation::get_correction_time(), AllocationInformation::InitializeMuxDB(), AllocationInformation::is_operation_bounded(), AllocationInformation::is_operation_PI_registered(), and allocation::is_ram_not_timing_compliant().
get_operations()
const operation_vec& functional_unit::get_operations () const [inline]
Return the operations that the functional unit can handle.
Returns
operations that the functional unit can handle.
Definition at line 644 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), allocation::BuildProxyFunctionVerilog(), allocation::BuildProxyFunctionVHDL(), allocation::BuildProxyWrapper(), and AllocationInformation::get_correction_time().
get_operations_num()
size_t functional_unit::get_operations_num () const [inline]
Return the number of the operations that the functional unit can handle.
Returns
an integer representing the number of operations that the functional unit can handle.
Definition at line 653 of file technology_node.hpp.
Referenced by xload().
lef_write()
void functional_unit::lef_write (std::ofstream & os, const simple_indentRef PP) [override], [virtual]
Append a technology_node to a LEF file.
Implements technology_node.
Definition at line 1302 of file technology_node.cpp.
lib_write()
void functional_unit::lib_write (std::ofstream & os, const simple_indentRef PP) [override], [virtual]
Append a technology_node to a liberty file.
Implements technology_node.
Definition at line 1285 of file technology_node.cpp.
References area_m, functional_unit_name, and area_model::get_area_value().
print()
void functional_unit::print (std::ostream & os) const [override], [virtual]
function that prints the class functional_unit.
Parameters
os is the output stream.
Implements technology_node.
Definition at line 386 of file technology_node.cpp.
References area_m, functional_unit_name, area_model::get_area_value(), list_of_operation, memory_type, and technology_node::PP.
set_clock_period()
void functional_unit::set_clock_period (double _clock_period)
Sets the clock period adopted for the synthesis (0 means that it has been generated with unconstrained synthesis) (in ns)
Definition at line 365 of file technology_node.cpp.
References attributes, clock_period, ordered_attributes, STR, and THROW_ASSERT.
Referenced by InitializeHLS::InternalExec().
set_clock_period_resource_fraction()
void functional_unit::set_clock_period_resource_fraction (double _clock_period_resource_fraction)
Sets the clock period resource fraction adopted for the synthesis.
Definition at line 376 of file technology_node.cpp.
References attributes, clock_period_resource_fraction, ordered_attributes, and STR.
Referenced by InitializeHLS::InternalExec().
xload()
void functional_unit::xload (const xml_element * node, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) [override], [virtual]
Load a functional unit starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
to be analyzed after all the other information
FPGA technology
area stuff
Implements technology_node.
Definition at line 669 of file technology_node.cpp.
References add(), area_m, attributes, clb_model::BRAM, bram_load_latency, CE_XVM, channels_type, characterization_timestamp, characterizing_constant_value, clock_period, clock_period_resource_fraction, COMBINATIONAL, component_timing_alias, xml_node::convert_escaped(), area_model::create_model(), time_model::create_model(), DEBUG_LEVEL_VERY_PEDANTIC, clb_model::DSP, NP_functionality::EQUATION, FF, FPGA, fu_template_name, fu_template_parameters, functional_unit_name, port_o::GEN, xml_child::get_children(), GET_CLASS, GET_CLASS_NAME, xml_text_node::get_content(), xml_node::get_name(), get_operations_num(), target_device::get_type(), port_o::IN, LATCH, list_of_operation, LOAD_XVM, logical_type, clb_model::LUT_FF_PAIRS, memory_ctrl_type, memory_type, ordered_attributes, port_o::OUT, PHYSICAL, PRINT_DBG_MEX, clb_model::REGISTERS, area_model::set_area_value(), clb_model::SLICE, clb_model::SLICE_LUTS, STATETABLE, THROW_ASSERT, THROW_ERROR, test_panda::type, UNKNOWN, NP_functionality::VERILOG_PROVIDED, and attribute::xload().
xwrite()
void functional_unit::xwrite (xml_element * rootnode, const technology_nodeRef tn, const ParameterConstRef Param, const TargetDevice_Type type) [override], [virtual]
Add a functional unit to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the functional unit is attached.
functional unit name
add the operation related to the unit name if there is not anything else
area attributes
FPGA
dumping of attributes
writing logical type
template stuff
operation stuff
circuit stuff
Implements technology_node.
Definition at line 1156 of file technology_node.cpp.
References add(), xml_child::add_child_element(), xml_child::add_child_text(), area_m, attributes, clb_model::BRAM, bram_load_latency, channels_type, characterization_timestamp, characterizing_constant_value, component_timing_alias, clb_model::DSP, FF, attribute::FLOAT64, fu_template_name, fu_template_parameters, functional_unit_name, area_model::get_area_value(), GET_CLASS_NAME, LATCH, list_of_operation, logical_type, clb_model::LUT_FF_PAIRS, memory_ctrl_type, memory_type, ordered_attributes, clb_model::REGISTERS, clb_model::SLICE_LUTS, STATETABLE, STR, and WRITE_XNVM2.
Friends And Related Function Documentation
technology_manager
friend class technology_manager [friend]
Definition at line 727 of file technology_node.hpp.
Field Documentation
area_m
area_modelRef functional_unit::area_m
This variable stores the resource information of the component.
Definition at line 537 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), AllocationInformation::InitializeMuxDB(), lib_write(), print(), xload(), and xwrite().
attributes
std::map<std::string, attributeRef> functional_unit::attributes
map between the attribute keys and the corresponding values
Definition at line 528 of file technology_node.hpp.
Referenced by set_clock_period(), set_clock_period_resource_fraction(), xload(), and xwrite().
bram_load_latency
std::string functional_unit::bram_load_latency
Specify the bram load latency the functional unit is compliant with.
non-null only in case the functional unit is a memory or a memory controller.
Definition at line 574 of file technology_node.hpp.
Referenced by xload(), and xwrite().
channels_type
std::string functional_unit::channels_type
Specify the type of the channel the functional unit is compliant with.
Definition at line 566 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), xload(), and xwrite().
characterization_timestamp
TimeStamp functional_unit::characterization_timestamp
The timestamp of the characterization of this functional unit.
Definition at line 581 of file technology_node.hpp.
Referenced by technology_manager::CGetSetupHoldTimeStamp(), xload(), and xwrite().
characterizing_constant_value
std::string functional_unit::characterizing_constant_value
Value used during the characterization of this instance.
Definition at line 559 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), xload(), and xwrite().
clock_period
double functional_unit::clock_period
clock period adopted for the synthesis (in ns)
Definition at line 531 of file technology_node.hpp.
Referenced by set_clock_period(), and xload().
clock_period_resource_fraction
double functional_unit::clock_period_resource_fraction
clock period resource fraction
Definition at line 534 of file technology_node.hpp.
Referenced by set_clock_period_resource_fraction(), and xload().
component_timing_alias
std::string functional_unit::component_timing_alias
Specify that the functional unit has the same timing per operation it has the one specified by this field.
Definition at line 578 of file technology_node.hpp.
Referenced by xload(), and xwrite().
fu_template_name
std::string functional_unit::fu_template_name
Name of the template.
Definition at line 553 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), xload(), and xwrite().
fu_template_parameters
std::string functional_unit::fu_template_parameters
Template parameters.
Definition at line 556 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::AnalyzeFu(), xload(), and xwrite().
functional_unit_name
std::string functional_unit::functional_unit_name
name of the functional unit.
Definition at line 522 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::create_template_instance(), get_operation(), lib_write(), print(), xload(), and xwrite().
list_of_operation
operation_vec functional_unit::list_of_operation [private]
At each functional unit can be associate several operations with different performances.
Definition at line 725 of file technology_node.hpp.
Referenced by print(), xload(), and xwrite().
logical_type
type_t functional_unit::logical_type
return the logical type of the cell
Definition at line 519 of file technology_node.hpp.
Referenced by get_operation(), xload(), and xwrite().
memory_ctrl_type
std::string functional_unit::memory_ctrl_type
Specify the type of memory controller the functional unit is compliant with.
non-null only in case the functional unit is a memory controller.
Definition at line 570 of file technology_node.hpp.
Referenced by xload(), and xwrite().
memory_type
std::string functional_unit::memory_type
Specify the type of memory the functional unit is compliant with.
non-null only in case the functional unit is a memory.
Definition at line 563 of file technology_node.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), print(), xload(), and xwrite().
op_name_to_op
std::map<std::string, technology_nodeRef> functional_unit::op_name_to_op [private]
Redefinition of get_kind_text()
Redefinition of get_kind()This varibale maps the name of the op with its reference.
Definition at line 722 of file technology_node.hpp.
Referenced by get_operation().
ordered_attributes
std::vector<std::string> functional_unit::ordered_attributes
list of attributes associated to the components
Definition at line 525 of file technology_node.hpp.
Referenced by set_clock_period(), set_clock_period_resource_fraction(), xload(), and xwrite().
XML_description
xml_nodeRef functional_unit::XML_description
pointer to the XML description of the cell
Definition at line 550 of file technology_node.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.cpp