TS_based_clique_covering< vertex_type > Class Template Reference
#include <clique_covering.hpp>
Public Member Functions
TS_based_clique_covering (bool _all_edges)
constructor
void do_clique_covering (const cc_compatibility_graphRef CG, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > &ds, CustomUnorderedSet< C_vertex > &support, const CustomUnorderedSet< C_vertex > &all_vertices, const filter_clique< vertex_type > &fc) override
Private Types
typedef boost::graph_traits< cc_compatibility_graph >::edge_descriptor edge_descriptor
Private Member Functions
bool is_non_compliant (C_vertex src, C_vertex tgt, const cc_compatibility_graph &subgraph, const CustomUnorderedSet< C_vertex > &all_vertices, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > &ds, const filter_clique< vertex_type > &fc)
bool select_edge_start (C_vertex source, C_vertex &tgt, const cc_compatibility_graph &subgraph, const CustomUnorderedSet< C_vertex > &all_vertices, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > &ds, const filter_clique< vertex_type > &fc)
bool select_edge (C_vertex &src, C_vertex &tgt, const cc_compatibility_graph &subgraph, const CustomUnorderedSet< C_vertex > &all_vertices, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > &ds, const filter_clique< vertex_type > &fc)
Compute the heuristics and return the best matching edge.
Additional Inherited Members
Detailed Description
template<typename vertex_type>
class TS_based_clique_covering< vertex_type >
Definition at line 1149 of file clique_covering.hpp.
Member Typedef Documentation
edge_descriptor
template<typename vertex_type >
typedef boost::graph_traits<cc_compatibility_graph>::edge_descriptor TS_based_clique_covering< vertex_type >::edge_descriptor [private]
Definition at line 1151 of file clique_covering.hpp.
Constructor & Destructor Documentation
TS_based_clique_covering()
template<typename vertex_type >
TS_based_clique_covering< vertex_type >::TS_based_clique_covering (bool _all_edges) [inline], [explicit]
constructor
Definition at line 1254 of file clique_covering.hpp.
Member Function Documentation
do_clique_covering()
template<typename vertex_type >
void TS_based_clique_covering< vertex_type >::do_clique_covering (const cc_compatibility_graphRef CG, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > & ds, CustomUnorderedSet< C_vertex > & support, const CustomUnorderedSet< C_vertex > & all_vertices, const filter_clique< vertex_type > & fc) [inline], [override], [virtual]
build the clique seed
remove non conformant edges
check trivial cases
Reimplemented from coloring_based_clique_covering< vertex_type >.
Definition at line 1258 of file clique_covering.hpp.
References THROW_ASSERT.
is_non_compliant()
template<typename vertex_type >
bool TS_based_clique_covering< vertex_type >::is_non_compliant (C_vertex src, C_vertex tgt, const cc_compatibility_graph & subgraph, const CustomUnorderedSet< C_vertex > & all_vertices, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > & ds, const filter_clique< vertex_type > & fc) [inline], [private]
Definition at line 1153 of file clique_covering.hpp.
References filter_clique< vertex_type >::select_candidate_to_remove().
select_edge()
template<typename vertex_type >
bool TS_based_clique_covering< vertex_type >::select_edge (C_vertex & src, C_vertex & tgt, const cc_compatibility_graph & subgraph, const CustomUnorderedSet< C_vertex > & all_vertices, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > & ds, const filter_clique< vertex_type > & fc) [inline], [private]
Compute the heuristics and return the best matching edge.
Definition at line 1208 of file clique_covering.hpp.
References max(), and unordered_set_intersection().
select_edge_start()
template<typename vertex_type >
bool TS_based_clique_covering< vertex_type >::select_edge_start (C_vertex source, C_vertex & tgt, const cc_compatibility_graph & subgraph, const CustomUnorderedSet< C_vertex > & all_vertices, typename boost::disjoint_sets< rank_pmap_type, pred_pmap_type > & ds, const filter_clique< vertex_type > & fc) [inline], [private]
Definition at line 1167 of file clique_covering.hpp.
References max(), and unordered_set_intersection().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/clique_covering.hpp