XilinxBackendFlow Class Reference
#include <XilinxBackendFlow.hpp>
Public Member Functions
XilinxBackendFlow (const ParameterConstRef Param, const std::string &flow_name, const target_managerRef manager)
Constructor.
~XilinxBackendFlow () override
Destructor.
void InitDesignParameters () override
Initializes the parameters.
void ExecuteSynthesis () override
Checks if the execution can be performed and, in case, performs the synthesis.
Protected Member Functions
virtual void create_cf (const DesignParametersRef dp, bool xst)
Creates the UCF file.
void WriteFlowConfiguration (std::ostream &script) override
Writes the proper flow configuration in the output script.
void CheckSynthesisResults () override
Checks the synthesis results and fills the corresponding datastructures.
void xparse_xst_utilization (const std::string &fn)
Parses the utilization file in XML format.
void parse_DSPs (const std::string &log_file)
retrieve the number of DSPs from the xst log
void xparse_map_utilization (const std::string &fn)
Parses the utilization file in XML format.
void vivado_xparse_utilization (const std::string &fn)
parse vivado results
void xparse_timing (const std::string &fn, bool post)
Fixed the parsing of timing results from trce.
void parse_timing (const std::string &fn)
Fixed the parsing of timing results from xst.
Protected Attributes
std::map< std::string, double > design_values
results from the synthesis
Additional Inherited Members
Detailed Description
Definition at line 61 of file XilinxBackendFlow.hpp.
Constructor & Destructor Documentation
XilinxBackendFlow()
XilinxBackendFlow::XilinxBackendFlow (const ParameterConstRef Param, const std::string & flow_name, const target_managerRef manager)
Constructor.
Definition at line 91 of file XilinxBackendFlow.cpp.
References BackendFlow::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, BackendFlow::default_data, GET_CLASS, target_device::get_parameter(), target_device::has_parameter(), INDENT_DBG_MEX, INDENT_OUT_MEX, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, BackendFlow::Param, BackendFlow::parse_flow(), test_panda::parser, BackendFlow::target, THROW_ERROR, UCF_SUBDIR, and ~XilinxBackendFlow().
 XilinxBackendFlow()
XilinxBackendFlow::~XilinxBackendFlow () [override], [default]
Destructor.
Referenced by XilinxBackendFlow().
Member Function Documentation
CheckSynthesisResults()
void XilinxBackendFlow::CheckSynthesisResults () [override], [protected], [virtual]
Checks the synthesis results and fills the corresponding datastructures.
Implements BackendFlow.
Definition at line 577 of file XilinxBackendFlow.cpp.
References BackendFlow::actual_parameters, BackendFlow::area_m, clb_model::BRAM, LUT_model::COMBINATIONAL_DELAY, CopyFile(), CopyStdout(), area_model::create_model(), time_model::create_model(), design_values, clb_model::DSP, ExistFile(), BackendFlow::flow_name, FPGA, target_device::get_parameter(), clb_model::LUT_FF_PAIRS, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, OUTPUT_LEVEL_VERY_PEDANTIC, BackendFlow::Param, PARAM_map_report, PARAM_trce_report_post, PARAM_trce_report_pre, PARAM_vivado_report, PARAM_vivado_timing_report, PARAM_xst_log_file, PARAM_xst_report, DesignParameters::parameter_values, parse_DSPs(), parse_timing(), PRINT_OUT_MEX, clb_model::REGISTERS, area_model::set_area_value(), clb_model::SLICE, clb_model::SLICE_LUTS, STR_CST_synthesis_timing_violation_report, BackendFlow::target, THROW_ERROR, BackendFlow::time_m, VIVADO_XILINX_BLOCK_RAMFIFO, VIVADO_XILINX_DESIGN_DELAY, VIVADO_XILINX_DSPS, VIVADO_XILINX_LUT_FLIP_FLOP_PAIRS_USED, VIVADO_XILINX_SLICE, VIVADO_XILINX_SLICE_LUTS, VIVADO_XILINX_SLICE_REGISTERS, vivado_xparse_utilization(), xparse_map_utilization(), xparse_timing(), and xparse_xst_utilization().
create_cf()
void XilinxBackendFlow::create_cf (const DesignParametersRef dp, bool xst) [protected], [virtual]
Creates the UCF file.
Reimplemented in XilinxTasteBackendFlow.
Definition at line 862 of file XilinxBackendFlow.cpp.
References DesignParameters::component_name, BackendFlow::Param, PARAM_clk_name, PARAM_clk_period, PARAM_is_combinational, PARAM_ucf_file, PARAM_xcf_file, DesignParameters::parameter_values, THROW_ASSERT, THROW_ERROR, and UCF_SUBDIR.
Referenced by InitDesignParameters().
ExecuteSynthesis()
void XilinxBackendFlow::ExecuteSynthesis () [override], [virtual]
Checks if the execution can be performed and, in case, performs the synthesis.
Reimplemented from BackendFlow.
Definition at line 757 of file XilinxBackendFlow.cpp.
References BackendFlow::ExecuteSynthesis(), and THROW_ERROR.
InitDesignParameters()
void XilinxBackendFlow::InitDesignParameters () [override], [virtual]
Initializes the parameters.
determine if power optimization has to be performed
Vivado section
additional constraints have to be manage at this level
Reimplemented from BackendFlow.
Definition at line 766 of file XilinxBackendFlow.cpp.
References BackendFlow::actual_parameters, create_cf(), BackendFlow::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, target_device::get_parameter(), GetExtension(), INDENT_DBG_MEX, INTSTYLE_ISE, INTSTYLE_SILENT, BackendFlow::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, BackendFlow::Param, PARAM_HDL_files, PARAM_ise_style, PARAM_power_optimization, PARAM_target_device, PARAM_vivado_sources_macro_list, PARAM_yosys_vivado_sources_macro_list, DesignParameters::parameter_values, BackendFlow::steps, STR, BackendFlow::target, and THROW_ERROR.
Referenced by XilinxTasteBackendFlow::GenerateSynthesisScripts().
parse_DSPs()
void XilinxBackendFlow::parse_DSPs (const std::string & log_file) [protected]
retrieve the number of DSPs from the xst log
Definition at line 464 of file XilinxBackendFlow.cpp.
References BackendFlow::area_m, clb_model::DSP, and THROW_ASSERT.
Referenced by CheckSynthesisResults().
parse_timing()
void XilinxBackendFlow::parse_timing (const std::string & fn) [protected]
Fixed the parsing of timing results from xst.
Definition at line 420 of file XilinxBackendFlow.cpp.
References BackendFlow::actual_parameters, LUT_model::COMBINATIONAL_DELAY, DesignParameters::component_name, CopyFile(), time_model::create_model(), BackendFlow::flow_name, FPGA, BackendFlow::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, BackendFlow::Param, PRINT_OUT_MEX, STR_CST_synthesis_timing_violation_report, THROW_WARNING, and BackendFlow::time_m.
Referenced by CheckSynthesisResults().
vivado_xparse_utilization()
void XilinxBackendFlow::vivado_xparse_utilization (const std::string & fn) [protected]
parse vivado results
Parameters
fn si the file where the synthesis results are written
Definition at line 656 of file XilinxBackendFlow.cpp.
References CE_XVM, design_values, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), LOAD_XVM, test_panda::parser, THROW_ASSERT, and THROW_ERROR.
Referenced by CheckSynthesisResults().
WriteFlowConfiguration()
void XilinxBackendFlow::WriteFlowConfiguration (std::ostream & script) [override], [protected], [virtual]
Writes the proper flow configuration in the output script.
Implements BackendFlow.
Definition at line 736 of file XilinxBackendFlow.cpp.
References target_device::get_parameter(), STR, and BackendFlow::target.
xparse_map_utilization()
void XilinxBackendFlow::xparse_map_utilization (const std::string & fn) [protected]
Parses the utilization file in XML format.
Definition at line 163 of file XilinxBackendFlow.cpp.
References BackendFlow::area_m, clb_model::BRAM, area_model::create_model(), clb_model::DSP, FPGA, clb_model::LUT_FF_PAIRS, BackendFlow::Param, clb_model::REGISTERS, clb_model::SLICE, and clb_model::SLICE_LUTS.
Referenced by CheckSynthesisResults().
xparse_timing()
void XilinxBackendFlow::xparse_timing (const std::string & fn, bool post) [protected]
Fixed the parsing of timing results from trce.
Definition at line 487 of file XilinxBackendFlow.cpp.
References abs(), time_model::create_model(), XMLDomParser::Exec(), BackendFlow::flow_name, FPGA, xml_child::get_children(), xml_text_node::get_content(), XMLDomParser::get_document(), xml_node::get_name(), LUT_model::MINIMUM_PERIOD_POST_MAP, LUT_model::MINIMUM_PERIOD_POST_PAR, BackendFlow::Param, test_panda::parser, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, and BackendFlow::time_m.
Referenced by CheckSynthesisResults().
xparse_xst_utilization()
void XilinxBackendFlow::xparse_xst_utilization (const std::string & fn) [protected]
Parses the utilization file in XML format.
setting the global area occupation as the number of LUT/FF pairs when possible
Definition at line 320 of file XilinxBackendFlow.cpp.
References BackendFlow::area_m, clb_model::BRAM, CE_XVM, area_model::create_model(), design_values, XMLDomParser::Exec(), FPGA, xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), LOAD_XVM, clb_model::LUT_FF_PAIRS, BackendFlow::Param, test_panda::parser, clb_model::REGISTERS, clb_model::SLICE_LUTS, THROW_ASSERT, THROW_ERROR, XST_NUMBER_OF_BLOCK_RAMFIFO, XST_NUMBER_OF_LUT_FLIP_FLOP_PAIRS_USED, XST_NUMBER_OF_SLICE_LUTS, and XST_NUMBER_OF_SLICE_REGISTERS.
Referenced by CheckSynthesisResults().
Field Documentation
design_values
std::map<std::string, double> XilinxBackendFlow::design_values [protected]
results from the synthesis
Definition at line 65 of file XilinxBackendFlow.hpp.
Referenced by CheckSynthesisResults(), vivado_xparse_utilization(), and xparse_xst_utilization().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/XilinxBackendFlow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/XilinxBackendFlow.cpp