MinimalInterfaceTestbench Class Reference
Superclass include.
#include <minimal_interface_testbench.hpp>
Public Member Functions
MinimalInterfaceTestbench (const ParameterConstRef _Param, const HLS_managerRef _AppM, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~MinimalInterfaceTestbench () override
Destructor.
Protected Member Functions
std::string memory_aggregate_slices (unsigned int i, long long int bitsize, long long int Mout_addr_ram_bitsize) const
void cond_load (long long int Mout_addr_ram_bitsize, std::string post_slice1, const std::string &post_slice2, const std::string &res_string, unsigned int i, const std::string &in_else, const std::string &mem_aggregate) const
void write_call (bool hasMultiIrq) const override
void write_memory_handler () const override
void write_interface_handler () const override
void write_signals (const tree_managerConstRef TreeM, bool &withMemory, bool &hasMultiIrq) const override
void write_slave_initializations (bool withMemory) const override
void read_input_value_from_file_RNONE (const std::string &input_name, bool &first_valid_input, unsigned bitsize) const
specialize read_input_value_from_file for interface PI_RNONE
void write_file_reading_operations () const override
void write_input_signal_declaration (const tree_managerConstRef TreeM, bool &with_memory) const
void write_output_signal_declaration () const
Additional Inherited Members
Detailed Description
Superclass include.
Definition at line 52 of file minimal_interface_testbench.hpp.
Constructor & Destructor Documentation
MinimalInterfaceTestbench()
MinimalInterfaceTestbench::MinimalInterfaceTestbench (const ParameterConstRef _parameters, const HLS_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
. include circuit include design_flows/backend/ToHDL include HLS include HLS/memory includes STD include tree include
Definition at line 85 of file minimal_interface_testbench.cpp.
References DesignFlowStep::debug_level, GET_CLASS, MINIMAL_TESTBENCH_GENERATION, and ~MinimalInterfaceTestbench().
 MinimalInterfaceTestbench()
MinimalInterfaceTestbench::~MinimalInterfaceTestbench () [override], [default]
Destructor.
Referenced by MinimalInterfaceTestbench().
Member Function Documentation
cond_load()
void MinimalInterfaceTestbench::cond_load (long long int Mout_addr_ram_bitsize, std::string post_slice1, const std::string & post_slice2, const std::string & res_string, unsigned int i, const std::string & in_else, const std::string & mem_aggregate) const [protected]
Definition at line 93 of file minimal_interface_testbench.cpp.
References TestbenchGenerationBaseStep::writer.
Referenced by write_memory_handler().
memory_aggregate_slices()
std::string MinimalInterfaceTestbench::memory_aggregate_slices (unsigned int i, long long int bitsize, long long int Mout_addr_ram_bitsize) const [protected]
Definition at line 896 of file minimal_interface_testbench.cpp.
References STR.
Referenced by write_memory_handler().
read_input_value_from_file_RNONE()
void MinimalInterfaceTestbench::read_input_value_from_file_RNONE (const std::string & input_name, bool & first_valid_input, unsigned bitsize) const [protected]
specialize read_input_value_from_file for interface PI_RNONE
write statement for new vectors' check
Definition at line 719 of file minimal_interface_testbench.cpp.
References CLOCK_PORT_NAME, DesignFlowStep::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, RESET_PORT_NAME, START_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and TestbenchGenerationBaseStep::writer.
Referenced by write_file_reading_operations().
write_call()
void MinimalInterfaceTestbench::write_call (bool hasMultiIrq) const [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 99 of file minimal_interface_testbench.cpp.
References TestbenchGenerationBaseStep::cir, CLOCK_PORT_NAME, module::find_member(), TestbenchGenerationBaseStep::mod, port_o_K, RETURN_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, and TestbenchGenerationBaseStep::writer.
write_file_reading_operations()
void MinimalInterfaceTestbench::write_file_reading_operations () const [override], [protected], [virtual]
file reading operations
iterate over all interface ports
Implements TestbenchGenerationBaseStep.
Definition at line 835 of file minimal_interface_testbench.cpp.
References TestbenchGenerationBaseStep::cir, HDL_manager::convert_to_identifier(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, module::find_member(), refcount< T >::get(), HLS_step::HLSMgr, INDENT_DBG_MEX, TestbenchGenerationBaseStep::mod, port_o_K, TestbenchGenerationBaseStep::read_input_value_from_file(), read_input_value_from_file_RNONE(), resize_to_1_8_16_32_64_128_256_512(), THROW_ASSERT, THROW_ERROR, and TestbenchGenerationBaseStep::writer.
write_input_signal_declaration()
void MinimalInterfaceTestbench::write_input_signal_declaration (const tree_managerConstRef TreeM, bool & with_memory) const [protected]
write input signals declaration
FIXME: real numbers at the moment have to be considered diffently because of computation of ulp; c++ code is still managed in the old way
Definition at line 597 of file minimal_interface_testbench.cpp.
References CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), TestbenchGenerationBaseStep::flag_cpp, refcount< T >::get(), get_id(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), GET_INDEX_NODE, GET_NODE, tree_helper::get_pointed_type(), tree_manager::get_tree_node_const(), tree_helper::get_type_index(), structural_object::get_typeRef(), tree_helper::is_a_pointer(), tree_helper::is_real(), TestbenchGenerationBaseStep::mod, DesignFlowStep::parameters, RESET_PORT_NAME, tree_helper::size(), START_PORT_NAME, STR, structural_type_descriptor::treenode, and TestbenchGenerationBaseStep::writer.
Referenced by write_signals().
write_interface_handler()
void MinimalInterfaceTestbench::write_interface_handler () const [override], [protected], [virtual]
check if you have both _vld and _ack
Implements TestbenchGenerationBaseStep.
Definition at line 439 of file minimal_interface_testbench.cpp.
References TestbenchGenerationBaseStep::cir, CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), module::find_member(), refcount< T >::get(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), TestbenchGenerationBaseStep::mod, port_o_K, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, THROW_ERROR, and TestbenchGenerationBaseStep::writer.
write_memory_handler()
void MinimalInterfaceTestbench::write_memory_handler () const [override], [protected], [virtual]
Master inputs set up
Slave inputs connections
Implements TestbenchGenerationBaseStep.
Definition at line 119 of file minimal_interface_testbench.cpp.
References ALL_BRAM, TestbenchGenerationBaseStep::cir, CLOCK_PORT_NAME, cond_load(), EXT_PIPELINED_BRAM, module::find_member(), structural_object::get_kind(), structural_object::get_typeRef(), memory_aggregate_slices(), TestbenchGenerationBaseStep::mod, DesignFlowStep::parameters, port_o_K, port_vector_o_K, structural_type_descriptor::size, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, THROW_ASSERT, structural_type_descriptor::vector_size, and TestbenchGenerationBaseStep::writer.
write_output_signal_declaration()
void MinimalInterfaceTestbench::write_output_signal_declaration () const [protected]
write output signals declaration
Definition at line 660 of file minimal_interface_testbench.cpp.
References HDL_manager::convert_to_identifier(), DONE_PORT_NAME, refcount< T >::get(), module::get_out_port(), module::get_out_port_size(), TestbenchGenerationBaseStep::mod, DesignFlowStep::parameters, RETURN_PORT_NAME, and TestbenchGenerationBaseStep::writer.
Referenced by write_signals().
write_signals()
void MinimalInterfaceTestbench::write_signals (const tree_managerConstRef TreeM, bool & withMemory, bool & hasMultiIrq) const [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 698 of file minimal_interface_testbench.cpp.
References ALL_BRAM, TestbenchGenerationBaseStep::cir, EXT_PIPELINED_BRAM, module::find_member(), structural_object::get_kind(), structural_object::get_typeRef(), TestbenchGenerationBaseStep::mod, DesignFlowStep::parameters, port_o_K, port_vector_o_K, structural_type_descriptor::size, STR, structural_type_descriptor::vector_size, write_input_signal_declaration(), write_output_signal_declaration(), and TestbenchGenerationBaseStep::writer.
write_slave_initializations()
void MinimalInterfaceTestbench::write_slave_initializations (bool withMemory) const [override], [protected], [virtual]
write slave signals initialization
Implements TestbenchGenerationBaseStep.
Definition at line 568 of file minimal_interface_testbench.cpp.
References HDL_manager::convert_to_identifier(), refcount< T >::get(), get_id(), module::get_in_port(), module::get_in_port_size(), TestbenchGenerationBaseStep::mod, and TestbenchGenerationBaseStep::writer.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/minimal_interface_testbench.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/minimal_interface_testbench.cpp