xml_node Class Reference
#include <xml_node.hpp>
Public Types
typedef std::list< xml_nodeRef > node_list
type for list of xml nodes
Public Member Functions
xml_node (std::string _name)
constructor
virtual ~xml_node ()
destructor
virtual void print (std::ostream &os, bool formatted, simple_indent *pp) const =0
Print the class.
std::string get_name () const
Get the name of this node.
void set_name (const std::string &_name)
Set the name of this node.
int get_line () const
Discover at what line number this node occurs in the XML file.
void set_line (int _line)
Set the line this node occurs in the XML file.
Static Public Member Functions
static void convert_unescaped (std::string &ioString)
Convert unescaped characters.
static void convert_escaped (std::string &ioString)
Convert escaped characters.
Private Attributes
std::string name
name of the node
int line
The line number in the XML file (not unsigned because lineno function of the lexer returns an int)
Friends
std::ostream & operator<< (std::ostream &os, const xml_node &s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const xml_node *s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const xml_nodeRef &s)
Friend definition of the << operator.
Detailed Description
Definition at line 70 of file xml_node.hpp.
Member Typedef Documentation
node_list
typedef std::list<xml_nodeRef> xml_node::node_list
type for list of xml nodes
Definition at line 92 of file xml_node.hpp.
Constructor & Destructor Documentation
xml_node()
xml_node::xml_node (std::string _name) [inline], [explicit]
constructor
Definition at line 83 of file xml_node.hpp.
 xml_node()
virtual xml_node::~xml_node () [inline], [virtual]
destructor
Definition at line 87 of file xml_node.hpp.
Member Function Documentation
convert_escaped()
static void xml_node::convert_escaped (std::string & ioString) [inline], [static]
Convert escaped characters.
Return a reference to the converted string. Supported characters are '&', '<', '>', `'`, and '`'. Managed even strings with '
' character
Parameters
ioString is the converted string.
Definition at line 199 of file xml_node.hpp.
Referenced by attribute::attribute(), interface_infer::InternalExec(), structural_object::xload(), functional_unit::xload(), functional_unit_template::xload(), and module::xload().
convert_unescaped()
static void xml_node::convert_unescaped (std::string & ioString) [inline], [static]
Convert unescaped characters.
Return a reference to the converted string. Supported characters are '&', '<', '>', `'`, and '`'.
Parameters
ioString is the converted string.
Definition at line 164 of file xml_node.hpp.
Referenced by xml_text_node::print(), xml_comment_node::print(), and xml_attribute::print().
get_line()
int xml_node::get_line () const
Discover at what line number this node occurs in the XML file.
Returns
The line number.
Definition at line 101 of file xml_node.cpp.
References line.
Referenced by set_name(), and structural_object::xload().
get_name()
std::string xml_node::get_name () const [inline]
Get the name of this node.
Returns
The node's name.
Definition at line 134 of file xml_node.hpp.
References name.
Referenced by xml_script_node_t::create(), BackendFlow::create_xml_scripts(), xml_script_node_t::find_type(), xml_comment_node::get_content(), xml_text_node::get_content(), Parameter::GetFileFormat(), DataXmlParser::Parse(), mem_xml_allocation::parse_external_allocation(), BackendFlow::parse_flow(), mem_xml_allocation::parse_internal_allocation(), mem_xml_allocation::parse_xml_allocation(), xml_text_node::print(), xml_comment_node::print(), xml_att_decl_node::print(), xml_element::print(), xml_attribute::print(), Translator::read_column_formats(), XilinxBackendFlow::vivado_xparse_utilization(), BackendFlow::xload(), SynthesisTool::xload(), functional_unit::xload(), xml_command_t::xml_command_t(), xml_ite_block_t::xml_ite_block_t(), xml_parameter_t::xml_parameter_t(), xml_set_variable_t::xml_set_variable_t(), xml_shell_t::xml_shell_t(), XilinxBackendFlow::xparse_timing(), LatticeBackendFlow::xparse_utilization(), AlteraBackendFlow::xparse_utilization(), NanoXploreBackendFlow::xparse_utilization(), and XilinxBackendFlow::xparse_xst_utilization().
print()
virtual void xml_node::print (std::ostream & os, bool formatted, simple_indent * pp) const [pure virtual]
Print the class.
Parameters
os is the stream.
formatted when true the xml is formatted in human readable way.
pp is the pretty print helper.
Implemented in xml_child, xml_attribute, xml_document, xml_element, xml_att_decl_node, xml_comment_node, and xml_text_node.
set_line()
void xml_node::set_line (int _line)
Set the line this node occurs in the XML file.
Parameters
_line The line number.
Definition at line 96 of file xml_node.cpp.
References line.
Referenced by set_name().
set_name()
void xml_node::set_name (const std::string & _name) [inline]
Set the name of this node.
Parameters
_name The new name for the node.
Definition at line 143 of file xml_node.hpp.
References get_line(), and set_line().
Referenced by BackendFlow::create_xml_scripts(), xml_comment_node::set_content(), and xml_text_node::set_content().
Friends And Related Function Documentation
operator<< [1/3]
std::ostream& operator<< (std::ostream & os, const xml_node & s) [friend]
Friend definition of the << operator.
Reference version
Definition at line 105 of file xml_node.hpp.
operator<< [2/3]
std::ostream& operator<< (std::ostream & os, const xml_node * s) [friend]
Friend definition of the << operator.
Pointer version
Definition at line 114 of file xml_node.hpp.
operator<< [3/3]
std::ostream& operator<< (std::ostream & os, const xml_nodeRef & s) [friend]
Friend definition of the << operator.
Refcount version
Definition at line 123 of file xml_node.hpp.
Field Documentation
line
int xml_node::line [private]
The line number in the XML file (not unsigned because lineno function of the lexer returns an int)
Definition at line 77 of file xml_node.hpp.
Referenced by get_line(), and set_line().
name
std::string xml_node::name [private]
name of the node
Definition at line 74 of file xml_node.hpp.
Referenced by get_name(), xml_child::print(), and attribute_sequence::set_attribute().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_node.hpp
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_node.cpp