commandport_obj Class Reference
This class manages command ports into datapath.
#include <commandport_obj.hpp>
Public Types
enum command_type {
OPERATION = 0,
CONDITION,
SWITCH,
MULTIIF,
SELECTOR,
ALUSELECTOR,
UNBOUNDED,
MULTI_UNBOUNDED,
WRENABLE
 }
Available command types.
typedef std::pair< unsigned int, vertex > data_operation_pair
typedef std::tuple< vertex, vertex, data_operation_pair > transition
describe a transition from a source state to the target state plus the tree_node of the data transferred and the operation vertex where the computation is performed
Public Member Functions
commandport_obj (const vertex &signal_, unsigned int _mode, const std::string &_name)
This is the constructor of the commandport_obj class.
commandport_obj (generic_objRef _elem, unsigned int _mode, const std::string &_name)
~commandport_obj () override=default
Destructor.
const vertex & get_vertex () const
Gets the vertex associated with port.
unsigned int get_command_type () const
Gets command type.
const CustomOrderedSet< transition > & get_activations () const
void add_activation (const transition &act)
void set_controller_obj (const structural_objectRef &_SM)
Sets structural_object associated to this object.
const structural_objectRef & get_controller_obj () const
Gets structural_object associated to this object.
const generic_objRef & get_elem () const
void set_phi_write_enable ()
bool get_phi_write_enable ()
Static Public Member Functions
static const std::string get_mode_string (unsigned int _mode)
Private Attributes
vertex signal
TODO: substitute with a functor operation vertex associated with the command port signal (if type is condition or operation) or state vertex associated with the command port signal.
generic_objRef elem
unsigned int mode
It's command type for the port.
bool is_a_phi_write_enable
CustomOrderedSet< transition > activations
structural_objectRef controller_SM
structural_object associated with the element inside the controller
Additional Inherited Members
Detailed Description
This class manages command ports into datapath.
It contains information about operation vertex giving command if it is operation or a condition. It also contains information about port direction. All these command ports are connected to controller.
Definition at line 70 of file commandport_obj.hpp.
Member Typedef Documentation
data_operation_pair
typedef std::pair<unsigned int, vertex> commandport_obj::data_operation_pair
Definition at line 87 of file commandport_obj.hpp.
transition
typedef std::tuple<vertex, vertex, data_operation_pair> commandport_obj::transition
describe a transition from a source state to the target state plus the tree_node of the data transferred and the operation vertex where the computation is performed
Definition at line 89 of file commandport_obj.hpp.
Member Enumeration Documentation
command_type
enum commandport_obj::command_type
Available command types.
Enumerator
OPERATION
CONDITION operation enable
SWITCH conditional value. it represents a readcond if it goes to the controller or a condition if it goes to the datapath
MULTIIF switch value, it represents the value of the switch statement
SELECTOR represents the multi conditions
ALUSELECTOR mux selector
UNBOUNDED ALU selector.
MULTI_UNBOUNDED signal representing a communication for an unbounded object (function call)
WRENABLE signal representing when a multi unbounded call ends enable for register writing
Definition at line 74 of file commandport_obj.hpp.
Constructor & Destructor Documentation
commandport_obj() [1/2]
commandport_obj::commandport_obj (const vertex & signal_, unsigned int _mode, const std::string & _name) [inline]
This is the constructor of the commandport_obj class.
It initializes type for generic_obj superclass
Parameters
signal_ is vertex associated to port
mode is command type
Definition at line 115 of file commandport_obj.hpp.
References CONDITION, MULTIIF, OPERATION, SWITCH, THROW_ASSERT, and UNBOUNDED.
commandport_obj() [2/2]
commandport_obj::commandport_obj (generic_objRef _elem, unsigned int _mode, const std::string & _name) [inline]
Definition at line 120 of file commandport_obj.hpp.
References ALUSELECTOR, MULTI_UNBOUNDED, SELECTOR, THROW_ASSERT, WRENABLE, and ~commandport_obj().
 commandport_obj()
commandport_obj::~commandport_obj () [override], [default]
Destructor.
Referenced by commandport_obj().
Member Function Documentation
add_activation()
void commandport_obj::add_activation (const transition & act) [inline]
Definition at line 154 of file commandport_obj.hpp.
get_activations()
const CustomOrderedSet<transition>& commandport_obj::get_activations () const [inline]
Definition at line 149 of file commandport_obj.hpp.
References activations.
get_command_type()
unsigned int commandport_obj::get_command_type () const [inline]
Gets command type.
Returns
an integer associated with command type
Definition at line 144 of file commandport_obj.hpp.
References mode.
get_controller_obj()
const structural_objectRef& commandport_obj::get_controller_obj () const [inline]
Gets structural_object associated to this object.
Returns
a reference to structural_object associated
Definition at line 172 of file commandport_obj.hpp.
References controller_SM.
get_elem()
const generic_objRef& commandport_obj::get_elem () const [inline]
Definition at line 177 of file commandport_obj.hpp.
References ALUSELECTOR, elem, MULTI_UNBOUNDED, SELECTOR, THROW_ASSERT, and WRENABLE.
get_mode_string()
static const std::string commandport_obj::get_mode_string (unsigned int _mode) [inline], [static]
Definition at line 183 of file commandport_obj.hpp.
References CONDITION, MULTI_UNBOUNDED, MULTIIF, OPERATION, SELECTOR, SWITCH, THROW_ERROR, UNBOUNDED, and WRENABLE.
Referenced by conn_binding::bind_command_port(), and conn_binding::bind_selector_port().
get_phi_write_enable()
bool commandport_obj::get_phi_write_enable () [inline]
Definition at line 214 of file commandport_obj.hpp.
References is_a_phi_write_enable.
get_vertex()
const vertex& commandport_obj::get_vertex () const [inline]
Gets the vertex associated with port.
Returns
reference to vertex
Definition at line 134 of file commandport_obj.hpp.
References CONDITION, MULTIIF, OPERATION, signal, SWITCH, THROW_ASSERT, and UNBOUNDED.
set_controller_obj()
void commandport_obj::set_controller_obj (const structural_objectRef & _SM) [inline]
Sets structural_object associated to this object.
Parameters
_SM is reference to structural_object to be associated
Definition at line 163 of file commandport_obj.hpp.
set_phi_write_enable()
void commandport_obj::set_phi_write_enable () [inline]
Definition at line 209 of file commandport_obj.hpp.
Field Documentation
activations
CustomOrderedSet<transition> commandport_obj::activations [private]
Definition at line 104 of file commandport_obj.hpp.
Referenced by get_activations().
controller_SM
structural_objectRef commandport_obj::controller_SM [private]
structural_object associated with the element inside the controller
Definition at line 107 of file commandport_obj.hpp.
Referenced by get_controller_obj().
elem
generic_objRef commandport_obj::elem [private]
Definition at line 97 of file commandport_obj.hpp.
Referenced by get_elem().
is_a_phi_write_enable
bool commandport_obj::is_a_phi_write_enable [private]
Definition at line 102 of file commandport_obj.hpp.
Referenced by get_phi_write_enable().
mode
unsigned int commandport_obj::mode [private]
It's command type for the port.
Definition at line 100 of file commandport_obj.hpp.
Referenced by get_command_type().
signal
vertex commandport_obj::signal [private]
TODO: substitute with a functor operation vertex associated with the command port signal (if type is condition or operation) or state vertex associated with the command port signal.
Definition at line 95 of file commandport_obj.hpp.
Referenced by get_vertex().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/HLS/virtual_components/commandport_obj.hpp