WriteHLSSummary Class Reference
Superclass include.
#include <write_hls_summary.hpp>
Public Member Functions
WriteHLSSummary (const ParameterConstRef parameters, const HLS_managerRef hls_mgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~WriteHLSSummary () override
Destructor.
DesignFlowStep_Status Exec () override
Execute this step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Definition at line 46 of file write_hls_summary.hpp.
Constructor & Destructor Documentation
WriteHLSSummary()
WriteHLSSummary::WriteHLSSummary (const ParameterConstRef _parameters, const HLS_managerRef _hls_mgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
parameters is the set of input parameters
hls_mgr is the HLS manager
design_flow_manager is the design flow manager
. include behavior include HLS include
Definition at line 54 of file write_hls_summary.cpp.
References WRITE_HLS_SUMMARY, and ~WriteHLSSummary().
 WriteHLSSummary()
WriteHLSSummary::~WriteHLSSummary () [override], [default]
Destructor.
Referenced by WriteHLSSummary().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > WriteHLSSummary::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 60 of file write_hls_summary.cpp.
References ALL_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLS_SYNTHESIS_FLOW, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status WriteHLSSummary::Exec () [override], [virtual]
Execute this step.
Implements DesignFlowStep.
Definition at line 84 of file write_hls_summary.cpp.
References HLS_step::HLSMgr, hls::PrintResources(), and UNCHANGED.
HasToBeExecuted()
bool WriteHLSSummary::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 105 of file write_hls_summary.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow/write_hls_summary.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow/write_hls_summary.cpp