Translator Class Reference
Class to translate data from a format to another one.
#include <translator.hpp>
Data Structures
class LatexColumnFormat
Class describing the characteristic of a column of latex table.
Public Member Functions
Translator (const ParameterConstRef Param)
Constructor.
void write_to_csv (const std::map< std::string, CustomOrderedSet< std::string >> &tags, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> &results, const std::string &file_name) const
Write rtl data in csv format.
void write_to_csv (const std::map< std::string, CustomMap< std::string, std::string >> &results, const std::string &file_name) const
Write text data in csv format.
void write_to_pa (const std::map< std::string, CustomOrderedSet< std::string >> &tags, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> &results, const std::string &file_name) const
Write profiling analysis to pa.
void write_to_latex (std::map< std::string, CustomMap< std::string, std::string >> &results, const Parameters_FileFormat input_format, const std::string &file_name) const
Write data in latex table format.
void merge_pa (const std::map< std::string, CustomOrderedSet< std::string >> &tags, const CustomUnorderedMap< std::string, CustomOrderedSet< std::string >> &keys, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> &input_data, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> &merge_data, CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> &output_data) const
Merget profiling analysis.
Static Public Member Functions
static void AggregateAndClean (std::map< std::string, std::map< std::string, long double >> &data, CustomOrderedSet< std::string > &column_names, const ParameterConstRef param)
Collapse columns of data considering super classes and remove selected rows.
Private Member Functions
void get_normalization (CustomUnorderedMap< std::string, long double > &normalization) const
Read normalization file.
std::string get_exponential_notation (const std::string &input) const
Return a number in latex exponential notation.
void read_column_formats (const XMLDomParserRef parser, std::list< LatexColumnFormat > &latex_column_formats, size_t &max_column_width) const
Read latex column format from xml.
Static Private Member Functions
static void replace_underscore (std::string &ioString)
Replace '_' with ' '.
Private Attributes
const ParameterConstRef Param
the set of parameters
int debug_level
the debug level
Detailed Description
Class to translate data from a format to another one.
Definition at line 91 of file translator.hpp.
Constructor & Destructor Documentation
Translator()
Translator::Translator (const ParameterConstRef Param) [explicit]
Constructor.
Parameters
Param is the set of the parameters
Definition at line 190 of file translator.cpp.
References xml_child::add_child_element(), BOOST_PP_SEQ_FOR_EACH, xml_document::create_root_node(), debug_level, DEBUG_LEVEL_PARANOIC, DEBUG_LEVEL_VERY_PEDANTIC, get_normalization(), Param, PRINT_DBG_MEX, SKIPPED_COLUMN, SKIPPING_MACRO, STR, STR_XML_weights_cycles, STR_XML_weights_mode, STR_XML_weights_root, STR_XML_weights_rtl, STR_XML_weights_rtx, THROW_ASSERT, THROW_ERROR, write_to_csv(), xml_document::write_to_file_formatted(), and WRITE_XNVM2.
Member Function Documentation
AggregateAndClean()
static void Translator::AggregateAndClean (std::map< std::string, std::map< std::string, long double >> & data, CustomOrderedSet< std::string > & column_names, const ParameterConstRef param) [static]
Collapse columns of data considering super classes and remove selected rows.
Parameters
data are the data to be collapsed
column_names are the names of the column
Param is the set of input parameters
get_exponential_notation()
std::string Translator::get_exponential_notation (const std::string & input) const [private]
Return a number in latex exponential notation.
Parameters
input is the number to be translated
Returns
the string in exponential notation
Definition at line 1354 of file translator.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, Param, PRINT_DBG_MEX, and result.
Referenced by write_to_latex().
get_normalization()
void Translator::get_normalization (CustomUnorderedMap< std::string, long double > & normalization) const [private]
Read normalization file.
Parameters
normalization is where normalize data will be stored
Definition at line 1294 of file translator.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), LOAD_XVM, Param, test_panda::parser, PRINT_DBG_MEX, STR, and THROW_ERROR.
Referenced by Translator().
merge_pa()
void Translator::merge_pa (const std::map< std::string, CustomOrderedSet< std::string >> & tags, const CustomUnorderedMap< std::string, CustomOrderedSet< std::string >> & keys, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> & input_data, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> & merge_data, CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> & output_data) const
Merget profiling analysis.
Parameters
tags is the column to be written
keys is the column to be written
input_data are the data of the first profiling analysis
merge_data are the data to be merged with the first profiling analysis
output_data is where data will be stored
Definition at line 1248 of file translator.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, and PRINT_DBG_MEX.
read_column_formats()
void Translator::read_column_formats (const XMLDomParserRef parser, std::list< LatexColumnFormat > & latex_column_formats, size_t & max_column_width) const [private]
Read latex column format from xml.
Parameters
parser is the parser used to parse the stream
latex_column_formats is where read data will be put
max_column_width is where maximum column width will be stored
Definition at line 1379 of file translator.cpp.
References CE_XVM, Translator::LatexColumnFormat::column_name, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, xml_child::get_children(), Translator::LatexColumnFormat::get_CO(), xml_node::get_name(), Translator::LatexColumnFormat::get_TF(), Translator::LatexColumnFormat::GetTotalFormat(), INDENT_DBG_MEX, LOAD_XVM, SplitString(), STR, STR_XML_latex_table_alignment, STR_XML_latex_table_column, STR_XML_latex_table_column_name, STR_XML_latex_table_comparison, STR_XML_latex_table_operator, STR_XML_latex_table_precision, STR_XML_latex_table_root, STR_XML_latex_table_source_name, STR_XML_latex_table_text_format, STR_XML_latex_table_total, STR_XML_latex_table_value, THROW_ASSERT, and THROW_ERROR.
Referenced by write_to_latex().
replace_underscore()
void Translator::replace_underscore (std::string & ioString) [static], [private]
Replace '_' with ' '.
Parameters
ioString is the string to be converted
Definition at line 1349 of file translator.cpp.
write_to_csv() [1/2]
void Translator::write_to_csv (const std::map< std::string, CustomOrderedSet< std::string >> & tags, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> & results, const std::string & file_name) const
Write rtl data in csv format.
Parameters
tags is the column to be written
data is the data to be written
file_name is the name of the file where data will be written
Referenced by Translator().
write_to_csv() [2/2]
void Translator::write_to_csv (const std::map< std::string, CustomMap< std::string, std::string >> & results, const std::string & file_name) const
Write text data in csv format.
Parameters
results is the data to be written
file_name is the name of the file
Definition at line 625 of file translator.cpp.
References STR, and THROW_ASSERT.
write_to_latex()
void Translator::write_to_latex (std::map< std::string, CustomMap< std::string, std::string >> & results, const Parameters_FileFormat input_format, const std::string & file_name) const
Write data in latex table format.
Parameters
results is the data to be written
file_name is the name of the files
The maximum width of a column
The bold cells
The bambu version
The timestamp
The bambu arguments
The list of benchmarks
The stream
Computing total when necessary
Adjusting precision
Checking if we have to use exponetial notation
Recomputing column width
Checking if we have to print average line
Definition at line 689 of file translator.cpp.
References add_escape(), Translator::LatexColumnFormat::Compare(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_latex_format_stat, EXACT, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), get_exponential_notation(), INDENT_DBG_MEX, NUM_CST_latex_table_max_column_width, Param, test_panda::parser, PRINT_DBG_MEX, read_column_formats(), STR, STR_XML_experimental_setup_bambu_arguments, STR_XML_experimental_setup_bambu_version, STR_XML_experimental_setup_benchmarks, STR_XML_experimental_setup_timestamp, STR_XML_experimental_setup_value, THROW_ASSERT, THROW_ERROR, and THROW_UNREACHABLE.
write_to_pa()
void Translator::write_to_pa (const std::map< std::string, CustomOrderedSet< std::string >> & tags, const CustomUnorderedMap< std::string, CustomUnorderedMapStable< std::string, CustomUnorderedMapStable< std::string, long double >>> & results, const std::string & file_name) const
Write profiling analysis to pa.
Parameters
tags is the column to be written
data is the data to be written
file_name is the name of the file where data will be written
Definition at line 655 of file translator.cpp.
References THROW_ASSERT.
Field Documentation
debug_level
int Translator::debug_level [private]
the debug level
Definition at line 98 of file translator.hpp.
Referenced by get_exponential_notation(), get_normalization(), merge_pa(), read_column_formats(), Translator(), and write_to_latex().
Param
const ParameterConstRef Translator::Param [private]
the set of parameters
Definition at line 95 of file translator.hpp.
Referenced by get_exponential_notation(), get_normalization(), Translator(), and write_to_latex().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/translator.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/translator.cpp