/home/osboxes/bambu/PandA-bambu/src/parser/treegcc/parse_tree.hpp File Reference
Specification of the tree (GCC raw) parsing interface function.
#include `refcount.hpp`
Functions
tree_managerRef ParseTreeFile (const ParameterConstRef &Param, const std::string &f)
Function that parse the dump of the patched GCC.
 forward declarations
Utility include
CONSTREF_FORWARD_DECL (Parameter)
REF_FORWARD_DECL (tree_manager)
Detailed Description
Specification of the tree (GCC raw) parsing interface function.
Declaration of the function that parse a tree from a file.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$
Warning
This file is still in a work in progress state
Last modified by $Author$
Function Documentation
CONSTREF_FORWARD_DECL()
CONSTREF_FORWARD_DECL (Parameter)
ParseTreeFile()
tree_managerRef ParseTreeFile (const ParameterConstRef & Param, const std::string & f)
Function that parse the dump of the patched GCC.
Parameters
Param is the set of input parameters
f the input file name
debug_level is the the debug_level
Returns
the tree manager associated to the raw file.
Definition at line 67 of file parse_tree.cpp.
References exit_code, and THROW_ERROR_CODE.
Referenced by create_tree_manager::Exec(), GccWrapper::FillTreeManager(), and main().
REF_FORWARD_DECL()
REF_FORWARD_DECL (tree_manager)