GenerateFuList Class Reference
#include <generate_fu_list.hpp>
Public Member Functions
GenerateFuList (const target_managerRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
The constructor.
DesignFlowStep_Status Exec () override
Execute the step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
const std::string GetSignature () const override
Return a unified identifier of this design step.
const std::string GetName () const override
Return the name of this design step.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
void AnalyzeCell (functional_unit *fu, const unsigned int prec, const std::vector< std::string > &portsize_parameters, const size_t portsize_index, const std::vector< std::string > &pipe_parameters, const size_t stage_index, const unsigned int constPort, const bool is_commutative, size_t max_lut_size) override
Analyze the single cell.
Private Attributes
CustomOrderedSet< std::string > cells
The set of list of cells.
CustomOrderedSet< std::string > components_to_be_characterized
The list of components to be added to the list; if the list is empty, all the components will be added.
std::string component
The current functional unit.
std::string current_list
The current entry for list of functional units.
Additional Inherited Members
Detailed Description
Definition at line 52 of file generate_fu_list.hpp.
Constructor & Destructor Documentation
GenerateFuList()
GenerateFuList::GenerateFuList (const target_managerRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
The constructor.
Header include.
Parameters
target is the target manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include circuit includes design_flows includes design_flows/technology includes STD include STL include technology include technology/physical_library includes utility include
Definition at line 75 of file generate_fu_list.cpp.
References components_to_be_characterized, DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and SplitString().
Member Function Documentation
AnalyzeCell()
void GenerateFuList::AnalyzeCell (functional_unit * fu, const unsigned int prec, const std::vector< std::string > & portsize_parameters, const size_t portsize_index, const std::vector< std::string > & pipe_parameters, const size_t stage_index, const unsigned int constPort, const bool is_commutative, size_t max_lut_size) [override], [virtual]
Analyze the single cell.
Parameters
fu is the cell
prec is the precision
portsize_parameters is the size of parameters
portsize_index
pipe_parameters
stage_index
constPort is the index of the constant port
Implements FunctionalUnitStep.
Definition at line 184 of file generate_fu_list.cpp.
References cells, component, current_list, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, functional_unit::get_name(), FunctionalUnitStep::has_first_synthesis_id, and INDENT_DBG_MEX.
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef GenerateFuList::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 179 of file generate_fu_list.cpp.
References ToDataFileStep::CGetDesignFlowStepFactory().
ComputeRelationships()
void GenerateFuList::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements ToDataFileStep.
Definition at line 119 of file generate_fu_list.cpp.
References TechnologyFlowStep::ComputeSignature(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_DEVICE_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and WRITE_TECHNOLOGY.
Exec()
DesignFlowStep_Status GenerateFuList::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 90 of file generate_fu_list.cpp.
References FunctionalUnitStep::AnalyzeFu(), cells, component, components_to_be_characterized, current_list, library_manager::get_library_fu(), technology_manager::get_library_list(), technology_manager::get_library_manager(), DesignFlowStep::parameters, SUCCESS, and FunctionalUnitStep::TM.
GetName()
const std::string GenerateFuList::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 174 of file generate_fu_list.cpp.
References ToDataFileStep::GetName().
GetSignature()
const std::string GenerateFuList::GetSignature () const [override], [virtual]
Return a unified identifier of this design step.
Returns
the signature of the design step
Implements DesignFlowStep.
Definition at line 169 of file generate_fu_list.cpp.
References ToDataFileStep::GetSignature().
HasToBeExecuted()
bool GenerateFuList::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 164 of file generate_fu_list.cpp.
References ToDataFileStep::HasToBeExecuted().
Field Documentation
cells
CustomOrderedSet<std::string> GenerateFuList::cells [private]
The set of list of cells.
Definition at line 56 of file generate_fu_list.hpp.
Referenced by AnalyzeCell(), and Exec().
component
std::string GenerateFuList::component [private]
The current functional unit.
Definition at line 62 of file generate_fu_list.hpp.
Referenced by AnalyzeCell(), and Exec().
components_to_be_characterized
CustomOrderedSet<std::string> GenerateFuList::components_to_be_characterized [private]
The list of components to be added to the list; if the list is empty, all the components will be added.
Definition at line 59 of file generate_fu_list.hpp.
Referenced by Exec(), and GenerateFuList().
current_list
std::string GenerateFuList::current_list [private]
The current entry for list of functional units.
Definition at line 65 of file generate_fu_list.hpp.
Referenced by AnalyzeCell(), and Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/generate_fu_list.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/generate_fu_list.cpp