RTLCharacterization Class Reference
#include <RTL_characterization.hpp>
Public Member Functions
RTLCharacterization (const target_managerRef target, const std::string &component, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~RTLCharacterization ()
Destructor.
DesignFlowStep_Status Exec ()
Perform RTL characterization of the modules with respect to the target device.
virtual bool HasToBeExecuted () const
Check if this step has actually to be executed.
virtual const std::string GetSignature () const
Return a unified identifier of this design step.
virtual const std::string GetName () const
Return the name of this design step.
virtual void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type)
Compute the relationships of a step with other steps.
virtual const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const
Return the factory to create this type of steps.
virtual void Initialize ()
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
void characterize_fu (const technology_nodeRef functional_unit)
Characterize the given functional unit with respect to the target device.
void resize_port (const structural_objectRef &port, unsigned int prec)
resize the port w.r.t a given precision
void specialize_fu (const module *mod, unsigned int prec, unsigned int bus_data_bitsize, unsigned int bus_addr_bitsize, unsigned int bus_size_bitsize, unsigned int bus_tag_bitsize, size_t portsize_value)
Performing the specialization of the given object.
void xwrite_device_file (const target_deviceRef device)
Generate the output file.
void xwrite_characterization (const target_deviceRef device, xml_element *nodeRoot)
Add the characterization to the output file.
void fix_execution_time_std ()
Fix the execution time by removing set/hold/pad timings.
void fix_proxies_execution_time_std ()
Fix execution/stage period value for proxies and bounded memory controllers.
void fix_muxes ()
fix the estimation of mux timing
void add_input_register (structural_objectRef port_in, const std::string &register_library, const std::string &port_prefix, structural_objectRef reset_port, structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef e_port, structural_managerRef SM)
void add_output_register (structural_managerRef SM, structural_objectRef e_port, structural_objectRef circuit, structural_objectRef reset_port, structural_objectRef port_out, const std::string &port_prefix, structural_objectRef clock_port, const std::string &register_library)
const std::string ComputeComponent (const std::string &input) const
Extract the component name from list of cells.
const CustomSet< std::string > ComputeCells (const std::string &input) const
Extract the cell lists.
virtual void AnalyzeCell (functional_unit *fu, const unsigned int prec, const std::vector< std::string > &portsize_parameters, const size_t portsize_index, const std::vector< std::string > &pipe_parameters, const size_t stage_index, const unsigned int constPort, const bool is_commutative, size_t max_lut_size)
Analyze the single cell.
Private Attributes
library_managerRef LM
Library manager.
const std::string component
The component to be characterized.
const CustomSet< std::string > cells
The cells to be characterized.
area_modelRef prev_area_characterization
The area model of the last characterization.
time_modelRef prev_timing_characterization
The time model of the last characterization.
const bool dummy_synthesis
True if we are performing dummy synthesis.
CustomOrderedSet< std::string > completed
set of units completed with success
Additional Inherited Members
Detailed Description
Definition at line 73 of file RTL_characterization.hpp.
Constructor & Destructor Documentation
RTLCharacterization()
RTLCharacterization::RTLCharacterization (const target_managerRef target, const std::string & component, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
target is the target
component is the component to be characterized
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 105 of file RTL_characterization.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~RTLCharacterization().
 RTLCharacterization()
RTLCharacterization::~RTLCharacterization () [default]
Destructor.
Referenced by RTLCharacterization().
Member Function Documentation
add_input_register()
void RTLCharacterization::add_input_register (structural_objectRef port_in, const std::string & register_library, const std::string & port_prefix, structural_objectRef reset_port, structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef e_port, structural_managerRef SM) [private]
Definition at line 560 of file RTL_characterization.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), CLOCK_PORT_NAME, structural_object::find_member(), GET_TYPE_SIZE, structural_object::get_typeRef(), structural_type_descriptor::INT, port_o_K, structural_type_descriptor::REAL, register_AR_NORETIME, register_AR_NORETIME_INT, register_AR_NORETIME_REAL, register_AR_NORETIME_UINT, RESET_PORT_NAME, FunctionalUnitStep::TM, structural_type_descriptor::type, and structural_type_descriptor::UINT.
Referenced by AnalyzeCell().
add_output_register()
void RTLCharacterization::add_output_register (structural_managerRef SM, structural_objectRef e_port, structural_objectRef circuit, structural_objectRef reset_port, structural_objectRef port_out, const std::string & port_prefix, structural_objectRef clock_port, const std::string & register_library) [private]
Definition at line 592 of file RTL_characterization.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), CLOCK_PORT_NAME, structural_object::find_member(), GET_TYPE_SIZE, structural_object::get_typeRef(), structural_type_descriptor::INT, port_o_K, structural_type_descriptor::REAL, register_AR_NORETIME, register_AR_NORETIME_INT, register_AR_NORETIME_REAL, register_AR_NORETIME_UINT, RESET_PORT_NAME, FunctionalUnitStep::TM, structural_type_descriptor::type, and structural_type_descriptor::UINT.
Referenced by AnalyzeCell().
AnalyzeCell()
void RTLCharacterization::AnalyzeCell (functional_unit * fu, const unsigned int prec, const std::vector< std::string > & portsize_parameters, const size_t portsize_index, const std::vector< std::string > & pipe_parameters, const size_t stage_index, const unsigned int constPort, const bool is_commutative, size_t max_lut_size) [private], [virtual]
Analyze the single cell.
Parameters
fu is the cell
prec is the precision
portsize_parameters is the size of parameters
portsize_index
pipe_parameters
constPort is the index of the constant port
is_commutative is true if all the operations are commutative
some modules has to be characterized with respect to a different constant value
main circuit type
setting top circuit component
add further specializations for this module
add clock and reset
add register on inputs
add register on outputs
generate the synthesis scripts
the synthesis has been successfully completed setting the used resources
setting the timing values for each operation
Implements FunctionalUnitStep.
Definition at line 671 of file RTL_characterization.cpp.
References structural_manager::add_connection(), structural_manager::add_constant(), add_input_register(), add_output_register(), structural_manager::add_port(), structural_manager::add_port_vector(), functional_unit::area_m, cells, functional_unit::channels_type, CHANNELS_TYPE_MEM_ACC_11, CHANNELS_TYPE_MEM_ACC_N1, CHANNELS_TYPE_MEM_ACC_NN, functional_unit::characterizing_constant_value, CLOCK_PORT_NAME, completed, counter, area_model::create_model(), time_model::create_model(), BackendFlow::CreateFlow(), time_model::cycles_time_DEFAULT, dummy_synthesis, BackendFlow::ExecuteSynthesis(), time_model::execution_time_DEFAULT, NP_functionality::exist_NP_functionality(), structural_object::ExistsParameter(), structural_object::find_member(), NP_functionality::FLOPOCO_PROVIDED, functional_unit::fu_template_name, functional_unit::fu_template_parameters, functional_unit::functional_unit_name, BackendFlow::GenerateSynthesisScripts(), structural_manager::get_circ(), get_id(), structural_object::get_id(), structural_object::get_kind(), technology_manager::get_library(), library_manager::get_library_name(), NP_functionality::get_library_parameters(), functional_unit::get_name(), functional_unit::get_operations(), target_device::get_parameter(), BackendFlow::get_timing_results(), target_device::get_type(), structural_object::get_typeRef(), BackendFlow::get_used_resources(), FunctionalUnitStep::has_first_synthesis_id, port_o::IN, time_model::initiation_time_DEFAULT, LM, LUT_EXPR_STD, max(), MEMLOAD_STD, functional_unit::memory_type, MEMORY_TYPE_ASYNCHRONOUS, MEMORY_TYPE_SYNCHRONOUS_SDS, MEMORY_TYPE_SYNCHRONOUS_SDS_BUS, MEMORY_TYPE_SYNCHRONOUS_UNALIGNED, MEMSTORE_STD, port_o::OUT, DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, PIPE_PARAMETER, port_o_K, PORT_VECTOR_N_PORTS, port_vector_o_K, prev_area_characterization, prev_timing_characterization, PRINT_OUT_MEX, register_AR_NORETIME, RESET_PORT_NAME, resize_port(), time_model::set_execution_time(), time_model::set_stage_period(), structural_manager::set_top_info(), structural_object::SetParameter(), specialize_fu(), time_model::stage_period_DEFAULT, START_PORT_NAME, STR, NP_functionality::SYSTEM_VERILOG_PROVIDED, FunctionalUnitStep::target, THROW_ASSERT, FunctionalUnitStep::TM, NP_functionality::VERILOG_PROVIDED, and NP_functionality::VHDL_PROVIDED.
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef RTLCharacterization::CGetDesignFlowStepFactory () const [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 665 of file RTL_characterization.cpp.
References THROW_UNREACHABLE.
characterize_fu()
void RTLCharacterization::characterize_fu (const technology_nodeRef functional_unit) [private]
Characterize the given functional unit with respect to the target device.
ComputeCells()
const CustomSet< std::string > RTLCharacterization::ComputeCells (const std::string & input) const [private]
Extract the cell lists.
Parameters
input is the input string
Definition at line 1118 of file RTL_characterization.cpp.
References component, SplitString(), and THROW_ASSERT.
ComputeComponent()
const std::string RTLCharacterization::ComputeComponent (const std::string & input) const [private]
Extract the component name from list of cells.
Parameters
input is the input string
Definition at line 1109 of file RTL_characterization.cpp.
References SplitString(), and THROW_ASSERT.
ComputeRelationships()
void RTLCharacterization::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 638 of file RTL_characterization.cpp.
References TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status RTLCharacterization::Exec () [virtual]
Perform RTL characterization of the modules with respect to the target device.
Implements DesignFlowStep.
Definition at line 128 of file RTL_characterization.cpp.
References FunctionalUnitStep::AnalyzeFu(), component, fix_proxies_execution_time_std(), library_manager::get_fu(), LM, SUCCESS, FunctionalUnitStep::target, and xwrite_device_file().
fix_execution_time_std()
void RTLCharacterization::fix_execution_time_std () [private]
Fix the execution time by removing set/hold/pad timings.
Definition at line 189 of file RTL_characterization.cpp.
References ASSIGN, ASSIGN_VECTOR_BOOL_STD, completed, component, technology_manager::get_fu(), library_manager::get_fu(), library_manager::get_library_name(), LIBRARY_PC, LIBRARY_STD, LIBRARY_STD_FU, LM, DesignFlowStep::parameters, and FunctionalUnitStep::TM.
fix_muxes()
void RTLCharacterization::fix_muxes () [private]
fix the estimation of mux timing
Definition at line 141 of file RTL_characterization.cpp.
References ASSIGN, ASSIGN_VECTOR_BOOL_STD, technology_manager::get_fu(), LIBRARY_STD_FU, MULTIPLIER_STD, MUX_GATE_STD, STR, TEST_MUL_MUX_8, and FunctionalUnitStep::TM.
fix_proxies_execution_time_std()
void RTLCharacterization::fix_proxies_execution_time_std () [private]
Fix execution/stage period value for proxies and bounded memory controllers.
Definition at line 220 of file RTL_characterization.cpp.
References ARRAY_1D_STD_BRAM, ARRAY_1D_STD_BRAM_NN, BMEMORY_STD, BMEMORY_STDN, completed, component, technology_manager::get_fu(), library_manager::get_fu(), library_manager::get_library_name(), LIBRARY_PC, LIBRARY_STD, LIBRARY_STD_FU, LM, MEMORY_CTRL_TYPE_DPROXY, MEMORY_CTRL_TYPE_DPROXYN, MEMORY_CTRL_TYPE_PROXY, MEMORY_CTRL_TYPE_PROXYN, DesignFlowStep::parameters, and FunctionalUnitStep::TM.
Referenced by Exec().
GetName()
const std::string RTLCharacterization::GetName () const [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 633 of file RTL_characterization.cpp.
GetSignature()
const std::string RTLCharacterization::GetSignature () const [virtual]
Return a unified identifier of this design step.
Returns
the signature of the design step
Implements DesignFlowStep.
Definition at line 628 of file RTL_characterization.cpp.
HasToBeExecuted()
bool RTLCharacterization::HasToBeExecuted () const [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 623 of file RTL_characterization.cpp.
Initialize()
void RTLCharacterization::Initialize () [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from FunctionalUnitStep.
Definition at line 120 of file RTL_characterization.cpp.
References component, technology_manager::get_library(), technology_manager::get_library_manager(), FunctionalUnitStep::Initialize(), LM, prev_area_characterization, prev_timing_characterization, and FunctionalUnitStep::TM.
resize_port()
void RTLCharacterization::resize_port (const structural_objectRef & port, unsigned int prec) [private]
resize the port w.r.t a given precision
Parameters
port
Definition at line 486 of file RTL_characterization.cpp.
References structural_type_descriptor::BOOL, structural_object::get_typeRef(), port_o::resize_std_port(), structural_type_descriptor::type, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, and structural_type_descriptor::VECTOR_UINT.
Referenced by AnalyzeCell(), and specialize_fu().
specialize_fu()
void RTLCharacterization::specialize_fu (const module * mod, unsigned int prec, unsigned int bus_data_bitsize, unsigned int bus_addr_bitsize, unsigned int bus_size_bitsize, unsigned int bus_tag_bitsize, size_t portsize_value) [private]
Performing the specialization of the given object.
Definition at line 510 of file RTL_characterization.cpp.
References module::get_in_port(), module::get_in_port_size(), structural_object::get_kind(), module::get_out_port(), module::get_out_port_size(), port_vector_o_K, port_o::resize_busport(), and resize_port().
Referenced by AnalyzeCell().
xwrite_characterization()
void RTLCharacterization::xwrite_characterization (const target_deviceRef device, xml_element * nodeRoot) [private]
Add the characterization to the output file.
set to the default value
Definition at line 349 of file RTL_characterization.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), clb_model::BRAM, cells, completed, area_model::create_model(), clb_model::DSP, GET_CLASS_NAME, library_manager::get_library_fu(), library_manager::get_library_name(), target_device::get_type(), TimeStamp::GetCurrentTimeStamp(), LM, clb_model::LUT_FF_PAIRS, DesignFlowStep::parameters, clb_model::REGISTERS, clb_model::SLICE, clb_model::SLICE_LUTS, STR, THROW_ERROR, and WRITE_XNVM2.
Referenced by xwrite_device_file().
xwrite_device_file()
void RTLCharacterization::xwrite_device_file (const target_deviceRef device) [private]
Generate the output file.
Definition at line 317 of file RTL_characterization.cpp.
References xml_document::create_root_node(), THROW_ERROR, xml_document::write_to_file_formatted(), target_device::xwrite(), and xwrite_characterization().
Referenced by Exec().
Field Documentation
cells
const CustomSet<std::string> RTLCharacterization::cells [private]
The cells to be characterized.
Definition at line 83 of file RTL_characterization.hpp.
Referenced by AnalyzeCell(), and xwrite_characterization().
completed
CustomOrderedSet<std::string> RTLCharacterization::completed [private]
set of units completed with success
Definition at line 122 of file RTL_characterization.hpp.
Referenced by AnalyzeCell(), fix_execution_time_std(), fix_proxies_execution_time_std(), and xwrite_characterization().
component
const std::string RTLCharacterization::component [private]
The component to be characterized.
Definition at line 80 of file RTL_characterization.hpp.
Referenced by ComputeCells(), Exec(), fix_execution_time_std(), fix_proxies_execution_time_std(), and Initialize().
dummy_synthesis
const bool RTLCharacterization::dummy_synthesis [private]
True if we are performing dummy synthesis.
Definition at line 93 of file RTL_characterization.hpp.
Referenced by AnalyzeCell().
LM
library_managerRef RTLCharacterization::LM [private]
Library manager.
Definition at line 77 of file RTL_characterization.hpp.
Referenced by AnalyzeCell(), Exec(), fix_execution_time_std(), fix_proxies_execution_time_std(), Initialize(), and xwrite_characterization().
prev_area_characterization
area_modelRef RTLCharacterization::prev_area_characterization [private]
The area model of the last characterization.
Definition at line 86 of file RTL_characterization.hpp.
Referenced by AnalyzeCell(), and Initialize().
prev_timing_characterization
time_modelRef RTLCharacterization::prev_timing_characterization [private]
The time model of the last characterization.
Definition at line 89 of file RTL_characterization.hpp.
Referenced by AnalyzeCell(), and Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/characterization/RTL_characterization.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/characterization/RTL_characterization.cpp