SDCScheduling Class Reference
#include <sdc_scheduling.hpp>
Public Member Functions
SDCScheduling (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
Constructor.
~SDCScheduling () override
Destructor.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
DesignFlowStep_Status InternalExec () override
Execute the step.
Data Fields
std::list< std::vector< unsigned int > > movements_list
Result of SPECULATIVE_LOOP: the list of movement to be performed (first element is the operation, second element is the old basic block, third element is the new basic block) Movements have to be performed in order.
Protected Member Functions
void ExecLoop ()
Execute the SDCScheduling_Algorithm::SPECULATIVE_LOOP version of the algorithm.
void Initialize () override
Initialize the step.
void AddDelayConstraints (const meilp_solverRef solver, const OpGraphConstRef filtered_op_graph, const OpGraphConstRef debug_filtered_op_graph, const std::set< vertex, bb_vertex_order_by_map > &loop_bbs)
Add constraints to force execution in different steps of operations which cannot be chained.
void AddDependenceConstraint (const meilp_solverRef solver, const vertex first_operation, const vertex second_operation, const bool simultaneous) const
Add constraints to force consecutive execution of dependent operations.
void AddStageConstraints (const meilp_solverRef solver, const vertex operation) const
Add constraints to force consecutive execution of different pipeline stages.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Protected Attributes
OpGraphConstRef op_graph
The operation graph used to perform scheduling.
BBGraphConstRef basic_block_graph
The basic block cfg graph.
OpGraphConstRef feedback_op_graph
The operation graph with feedback used to perform scheduling.
BehavioralHelperConstRef behavioral_helper
The behavioral helper.
AllocationInformationConstRef allocation_information
The allocation.
fu_bindingRef res_binding
The binding.
double clock_period
The clock period.
double margin
The margin which has to be introduced with respect to clock period.
CustomMap< std::pair< vertex, unsigned int >, unsigned int > operation_to_varindex
Map operation-stage to variable index.
CustomSet< vertex > unbounded_operations
The set of unbounded operations.
CustomMap< unsigned int, CustomSet< vertex > > sharing_operations
For each shared resource, the operations mapped on it.
CustomMap< vertex, CustomSet< vertex > > full_reachability_map
Set of reachable operations (in scheduling graph)
CustomSet< unsigned int > limited_resources
The set of limited resources.
CustomSet< EdgeDescriptor > temp_edges
The set of temporary flow edges added to the op_graph.
Additional Inherited Members
Detailed Description
Definition at line 63 of file sdc_scheduling.hpp.
Constructor & Destructor Documentation
SDCScheduling()
SDCScheduling::SDCScheduling (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
Constructor.
Parameters
parameters is the set of input parameters
HLSmgr is the HLS manager
function_id is the function index of the function
design_flow_manager is the hls design flow
hls_flow_step_specialization specifies how specialize this step
Definition at line 233 of file sdc_scheduling.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~SDCScheduling().
 SDCScheduling()
SDCScheduling::~SDCScheduling () [override], [default]
Destructor.
Referenced by SDCScheduling().
Member Function Documentation
AddDelayConstraints()
void SDCScheduling::AddDelayConstraints (const meilp_solverRef solver, const OpGraphConstRef filtered_op_graph, const OpGraphConstRef debug_filtered_op_graph, const std::set< vertex, bb_vertex_order_by_map > & loop_bbs) [protected]
Add constraints to force execution in different steps of operations which cannot be chained.
Parameters
solver is the solver to which constraints have to be added
op_graph is the operation graph
operation is the first operation to be considered
The asap starting and ending time
Reverse reachability
For each vertex the set of `live` operations; an operation is live if its distance is less than the clock period
For each vertex the operation for which a constraint has to be added
The execution time of the current operation - for the current operation we must consider last stage NOTE:: Chaining after unbound operation is not allowed
Stage period of first cycle of operations with registered inputs is 0
Computing starting time
Operations cannot be chained if the chain is longer than clock period
Another predecessor (source2) has already a constraint with (other), so we can skip this constraint
Definition at line 241 of file sdc_scheduling.cpp.
References allocation_information, hls::allocation_information, basic_block_graph, behavioral_helper, AllocationInformation::CanBeChained(), CDG_SELECTOR, BBGraph::CGetBBNodeInfo(), OpGraph::CGetOpNodeInfo(), clock_period, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DEBUG_SELECTOR, graph::ExistsEdge(), HLSFunctionStep::funId, AllocationInformation::get_initiation_time(), GET_NAME, GET_TYPE, AllocationInformation::GetCondExprTimeLatency(), AllocationInformation::GetConnectionTime(), AllocationInformation::GetCycleLatency(), AllocationInformation::GetFuType(), graph::GetSelector(), AllocationInformation::GetTimeLatency(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, AllocationInformation::is_operation_bounded(), AllocationInformation::is_operation_PI_registered(), meilp_solver::L, margin, FunctionBehavior::ogc, op_graph, operation_to_varindex, STR, temp_edges, THROW_UNREACHABLE, graph::TopologicalSort(), TYPE_PHI, TYPE_STORE, AbsControlStep::UNKNOWN, and fu_binding::UNKNOWN.
Referenced by InternalExec().
AddDependenceConstraint()
void SDCScheduling::AddDependenceConstraint (const meilp_solverRef solver, const vertex first_operation, const vertex second_operation, const bool simultaneous) const [protected]
Add constraints to force consecutive execution of dependent operations.
Parameters
solver is the solver to which constraints have to be added
source is the first operation
target is the second operation
simultaneous tells if the two operations can be executed in the same clock cycle (chained) or not
Definition at line 450 of file sdc_scheduling.cpp.
References allocation_information, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NAME, AllocationInformation::GetCycleLatency(), INDENT_DBG_MEX, meilp_solver::L, op_graph, and operation_to_varindex.
Referenced by InternalExec().
AddStageConstraints()
void SDCScheduling::AddStageConstraints (const meilp_solverRef solver, const vertex operation) const [protected]
Add constraints to force consecutive execution of different pipeline stages.
Parameters
solver is the solver to which constraints have to be added
operation is the pipelined operation
Definition at line 461 of file sdc_scheduling.cpp.
References allocation_information, meilp_solver::E, GET_NAME, AllocationInformation::GetCycleLatency(), op_graph, operation_to_varindex, and STR.
Referenced by InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > SDCScheduling::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from Scheduling.
Definition at line 503 of file sdc_scheduling.cpp.
References ALLOCATION, CALLED_FUNCTIONS, Scheduling::ComputeHLSRelationships(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
ComputeRelationships()
void SDCScheduling::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from HLSFunctionStep.
Definition at line 474 of file sdc_scheduling.cpp.
References HLSFunctionStep::ComputeRelationships(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, HLSFunctionStep::funId, DesignFlowStep::GetStatus(), HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), NULL_VERTEX, DesignFlowStep::parameters, and SUCCESS.
ExecLoop()
void SDCScheduling::ExecLoop () [protected]
Execute the SDCScheduling_Algorithm::SPECULATIVE_LOOP version of the algorithm.
HasToBeExecuted()
bool SDCScheduling::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from HLSFunctionStep.
Definition at line 536 of file sdc_scheduling.cpp.
References HLSFunctionStep::bb_version, and HLSFunctionStep::HasToBeExecuted().
Initialize()
void SDCScheduling::Initialize () [override], [protected], [virtual]
Initialize the step.
Build the full reachability map
For the limited resource, the operations assigned to it
If number of resources is limited but larger than number of operations
Removing not actually limited resources
Reimplemented from Scheduling.
Definition at line 1409 of file sdc_scheduling.cpp.
References allocation_information, hls::allocation_information, basic_block_graph, FunctionBehavior::BB, behavioral_helper, FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), clock_period, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, feedback_op_graph, FunctionBehavior::FFLSAODG, FunctionBehavior::FLSAODG, full_reachability_map, HLSFunctionStep::funId, AllocationInformation::get_fu_name(), GET_NAME, AllocationInformation::get_number_fu(), AllocationInformation::get_number_fu_types(), AllocationInformation::GetClockPeriodMargin(), AllocationInformation::GetFuType(), HLSFunctionStep::HLS, hls::HLS_C, HLS_step::HLSMgr, INDENT_DBG_MEX, Scheduling::Initialize(), AllocationInformation::is_operation_bounded(), limited_resources, margin, op_graph, hls::operations, res_binding, graph::ReverseTopologicalSort(), hls::Rfu, sharing_operations, STR, and unbounded_operations.
InternalExec()
DesignFlowStep_Status SDCScheduling::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Vertices not yet added to any tree
FIXME: for the moment the considered graph contains control dependence edges
Create the solver
Compute variables Map real operation-stage to variable index
Create the variables representing the ending of a path Map tree leaf to variable index
next_var_index has been incremented but the + 1 is the makespan
Set integer variables and lower bound
Add consecutive stages constraints
Add dependence constraints: target can start in the same clock cycle in which source ends
Not control dependence
Non speculable operation
Add timing constraints: target can start in the same clock cycle in which source ends only with chaining
For each basic block, the set of unbounded operations found on the paths to it
For each basic block, the set of pipelined operations found on the paths to it
For each basic block, for each functional unit fu, the list of the last n operations executed (n is the number of resource of type fu) - Value is a set since there can be different paths reaching current basic block
NOTE: unbounded operation can start during last stage of multi cycle operation
NOTE: unbounded operation can start during last stage of multi cycle operation
NOTE: unbounded operation can start during last stage of multi cycle operation
Resource constraints
Adding last operation constraint: return must be executed after all the other operations.
last cannot be scheduleded with unbounded operations
Setting path end to be the real end
Setting objective function
set the binding information
Check which statements have to be moved For each statement the basic blocks above which it cannot be moved. Phi cannot be moved Operations which depend from the phi cannot be moved before the phi and so on
Set of operations which cannot be moved (at the moment) because of dependencies from gimple phi
IF is not a barrier for controlled operations
Loads which do not have resource limitation can be moved but not speculated; speculation should be prevented by control edges
Computing bb barrier starting from bb barrier of predecesso
Update dominator
If the current is in the barrier, do not check for the candidate
Implements HLSFunctionStep.
Definition at line 544 of file sdc_scheduling.cpp.
References AddDelayConstraints(), AddDependenceConstraint(), AddStageConstraints(), ASLAP::ALAP_fast, allocation_information, basic_block_graph, behavioral_helper, fu_binding::bind(), CDG_SELECTOR, FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetLoops(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), FunctionBehavior::CheckReachability(), meilp_solver::create_solver(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DEBUG_SELECTOR, FunctionBehavior::DOM_TREE, graph::ExistsEdge(), FunctionBehavior::FLSAODDG, FunctionBehavior::FLSAODG, HLSFunctionStep::funId, meilp_solver::G, FunctionBehavior::get_bb_map_levels(), Schedule::get_cstep(), AllocationInformation::get_fu_name(), BehavioralHelper::get_function_name(), GET_NAME, AllocationInformation::get_number_fu(), GET_TYPE, AllocationInformation::GetCycleLatency(), AllocationInformation::GetFuType(), graph::GetSelector(), HLSFunctionStep::HLS, hls::HLS_C, HLS_step::HLSMgr, INDENT_DBG_MEX, AllocationInformation::is_operation_bounded(), limited_resources, meilp_solver::min, movements_list, FunctionBehavior::ogc, op_graph, operation_to_varindex, DesignFlowStep::parameters, res_binding, hls::Rsch, Schedule::set_csteps(), Schedule::set_execution(), Schedule::set_execution_end(), Scheduling::speculation, STR, SUCCESS, temp_edges, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, TYPE_EXTERNAL, TYPE_IF, TYPE_LABEL, TYPE_LAST_OP, TYPE_LOAD, TYPE_MULTIIF, TYPE_PHI, TYPE_RET, TYPE_STORE, TYPE_SWITCH, TYPE_VPHI, Schedule::UpdateTime(), and OpGraph::WriteDot().
Field Documentation
allocation_information
AllocationInformationConstRef SDCScheduling::allocation_information [protected]
The allocation.
Definition at line 79 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), AddDependenceConstraint(), AddStageConstraints(), Initialize(), and InternalExec().
basic_block_graph
BBGraphConstRef SDCScheduling::basic_block_graph [protected]
The basic block cfg graph.
Definition at line 70 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), Initialize(), and InternalExec().
behavioral_helper
BehavioralHelperConstRef SDCScheduling::behavioral_helper [protected]
The behavioral helper.
Definition at line 76 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), Initialize(), and InternalExec().
clock_period
double SDCScheduling::clock_period [protected]
The clock period.
Definition at line 85 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), and Initialize().
feedback_op_graph
OpGraphConstRef SDCScheduling::feedback_op_graph [protected]
The operation graph with feedback used to perform scheduling.
Definition at line 73 of file sdc_scheduling.hpp.
Referenced by Initialize().
full_reachability_map
CustomMap<vertex, CustomSet<vertex> > SDCScheduling::full_reachability_map [protected]
Set of reachable operations (in scheduling graph)
Definition at line 100 of file sdc_scheduling.hpp.
Referenced by Initialize().
limited_resources
CustomSet<unsigned int> SDCScheduling::limited_resources [protected]
The set of limited resources.
Definition at line 103 of file sdc_scheduling.hpp.
Referenced by Initialize(), and InternalExec().
margin
double SDCScheduling::margin [protected]
The margin which has to be introduced with respect to clock period.
Definition at line 88 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), and Initialize().
movements_list
std::list<std::vector<unsigned int> > SDCScheduling::movements_list
Result of SPECULATIVE_LOOP: the list of movement to be performed (first element is the operation, second element is the old basic block, third element is the new basic block) Movements have to be performed in order.
Definition at line 158 of file sdc_scheduling.hpp.
Referenced by InternalExec().
op_graph
OpGraphConstRef SDCScheduling::op_graph [protected]
The operation graph used to perform scheduling.
Definition at line 67 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), AddDependenceConstraint(), AddStageConstraints(), Initialize(), and InternalExec().
operation_to_varindex
CustomMap<std::pair<vertex, unsigned int>, unsigned int> SDCScheduling::operation_to_varindex [protected]
Map operation-stage to variable index.
Definition at line 91 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), AddDependenceConstraint(), AddStageConstraints(), and InternalExec().
res_binding
fu_bindingRef SDCScheduling::res_binding [protected]
The binding.
Definition at line 82 of file sdc_scheduling.hpp.
Referenced by Initialize(), and InternalExec().
sharing_operations
CustomMap<unsigned int, CustomSet<vertex> > SDCScheduling::sharing_operations [protected]
For each shared resource, the operations mapped on it.
Definition at line 97 of file sdc_scheduling.hpp.
Referenced by Initialize().
temp_edges
CustomSet<EdgeDescriptor> SDCScheduling::temp_edges [protected]
The set of temporary flow edges added to the op_graph.
Definition at line 107 of file sdc_scheduling.hpp.
Referenced by AddDelayConstraints(), and InternalExec().
unbounded_operations
CustomSet<vertex> SDCScheduling::unbounded_operations [protected]
The set of unbounded operations.
Definition at line 94 of file sdc_scheduling.hpp.
Referenced by Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/sdc_scheduling.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/sdc_scheduling.cpp