parm2ssa Class Reference
Pre-analysis step.
#include <parm2ssa.hpp>
Public Member Functions
parm2ssa (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~parm2ssa () override
Destructor.
DesignFlowStep_Status Exec () override
Fixes the var_decl duplication.
Protected Member Functions
void recursive_analysis (tree_nodeRef &tn, const std::string &srcp)
Recursive tree node analysis.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
CustomUnorderedSet< unsigned int > already_visited_ae
Already visited address expression (used to avoid infinite recursion)
Additional Inherited Members
Detailed Description
Pre-analysis step.
computing the relation between parm_decl and the associated ssa_name.
Definition at line 67 of file parm2ssa.hpp.
Constructor & Destructor Documentation
parm2ssa()
parm2ssa::parm2ssa (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
Behavior include Graph include Parameter include STD include STL include Tree include Utility include
Definition at line 79 of file parm2ssa.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~parm2ssa().
 parm2ssa()
parm2ssa::~parm2ssa () [override], [default]
Destructor.
Referenced by parm2ssa().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > parm2ssa::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 86 of file parm2ssa.cpp.
References FrontendFlowStep::ALL_FUNCTIONS, COMPLETE_CALL_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status parm2ssa::Exec () [override], [virtual]
Fixes the var_decl duplication.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 113 of file parm2ssa.cpp.
References FrontendFlowStep::AppM, test_panda::arg, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, tree_manager::GetTreeNode(), INDENT_DBG_MEX, phi, tree_helper::print_function_name(), recursive_analysis(), sl, STR, and SUCCESS.
recursive_analysis()
void parm2ssa::recursive_analysis (tree_nodeRef & tn, const std::string & srcp) [protected]
Recursive tree node analysis.
Definition at line 151 of file parm2ssa.cpp.
References already_visited_ae, FrontendFlowStep::AppM, test_panda::arg, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, NODE_NOT_YET_SUPPORTED_EC, STR, THROW_ASSERT, THROW_ERROR_CODE, THROW_UNREACHABLE, and tree_node::ToString().
Referenced by Exec().
Field Documentation
already_visited_ae
CustomUnorderedSet<unsigned int> parm2ssa::already_visited_ae [protected]
Already visited address expression (used to avoid infinite recursion)
Definition at line 71 of file parm2ssa.hpp.
Referenced by recursive_analysis().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/parm2ssa.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/parm2ssa.cpp