pragma_manager Class Reference
This class is used to manage the pragma directives found in the source code.
#include <pragma_manager.hpp>
Public Types
enum OmpPragmaType {
OMP_ATOMIC = 0,
OMP_BARRIER,
OMP_CRITICAL,
OMP_DECLARE_SIMD,
OMP_FOR,
OMP_PARALLEL_FOR,
OMP_PARALLEL_SECTIONS,
OMP_PARALLEL,
OMP_SECTIONS,
OMP_SECTION,
OMP_SIMD,
OMP_TARGET,
OMP_TASK,
OMP_UNKNOWN
 }
The possible openmp pragmas Note that sections has to go before section but after parallel sections otherwise recognition would be wrong.
Public Member Functions
pragma_manager (const application_managerRef application_manager, const ParameterConstRef param)
Constructor.
virtual ~pragma_manager ()
Destructor.
bool checkCompliant () const
Check if the datastructure information are compliant with the pragma reference manual.
bool isBlackBox (const std::string &name) const
const std::list< std::string > GetFunctionDefinitionPragmas (const std::string &function_name) const
Return the pragmas associated with a function definition.
CustomUnorderedSet< std::string > getFunctionCallPragmas (const std::string &Name) const
void AddFunctionDefinitionPragmas (const std::string &name, const CustomUnorderedSet< std::string > &pragmas)
Add a set of definition pragmas to a function.
void addFunctionCallPragmas (const std::string &Name, const CustomUnorderedSet< std::string > &Pragmas)
unsigned int addBlackBoxPragma (const std::string &function_name)
void setGenericPragma (unsigned int number, const std::string &line)
std::string getGenericPragma (unsigned int number) const
unsigned int AddOmpSimdPragma (const std::string &line) const
Create a simd openmp pragma starting from the line containing it.
bool CheckOmpFor (const application_managerConstRef app_man, const unsigned int function_index, const vertex bb_operation_vertex) const
Check if a omp for pragma is associated with the loop.
void CheckAddOmpFor (const unsigned int function_index, const vertex bb_operation_vertex)
Check if a omp for pragma is associated with the loop; if yes, add the gimple_for.
void CheckAddOmpSimd (const unsigned int function_index, const vertex bb_operation_vertex)
Check if a omp simd pragma is associated with the loop; if yes, add information to the loop.
std::string get_mapping (const std::string &function_name) const
Get mapping of a function given by the pragma.
CustomUnorderedMapUnstable< std::string, std::string > ExtractClauses (const std::string &clauses_list) const
Extract clauses associated with a pragma.
Static Public Member Functions
static OmpPragmaType GetOmpPragmaType (const std::string &directive)
Returns the identifier corresponding to an openmp directive.
Static Public Attributes
static const std::string omp_directive_keywords [OMP_UNKNOWN]
The list of omp directive keywords.
Protected Attributes
const application_managerRef application_manager
The application manager NOTE: this is equivalente to a weakrefcount since deleter should be null.
const tree_managerRef TM
CustomOrderedSet< std::string > BlackBoxFunctions
std::map< std::string, CustomUnorderedSet< std::string > > FunctionCallPragmas
std::map< std::string, std::list< std::string > > function_definition_pragmas
Function defintion pragmas.
std::map< unsigned int, std::string > GenericPragmas
const ParameterConstRef param
Set of input parameters.
int debug_level
The debug level.
Detailed Description
This class is used to manage the pragma directives found in the source code.
Definition at line 82 of file pragma_manager.hpp.
Member Enumeration Documentation
OmpPragmaType
enum pragma_manager::OmpPragmaType
The possible openmp pragmas Note that sections has to go before section but after parallel sections otherwise recognition would be wrong.
Enumerator
OMP_ATOMIC
OMP_BARRIER
OMP_CRITICAL
OMP_DECLARE_SIMD
OMP_FOR
OMP_PARALLEL_FOR
OMP_PARALLEL_SECTIONS
OMP_PARALLEL
OMP_SECTIONS
OMP_SECTION
OMP_SIMD
OMP_TARGET
OMP_TASK
OMP_UNKNOWN
Definition at line 111 of file pragma_manager.hpp.
Constructor & Destructor Documentation
pragma_manager()
pragma_manager::pragma_manager (const application_managerRef application_manager, const ParameterConstRef param)
Constructor.
Parameters
application_manager is the application manager
param is the set of the input parameters
Definition at line 134 of file pragma_manager.cpp.
References addBlackBoxPragma(), BlackBoxFunctions, OUTPUT_LEVEL_VERBOSE, param, PRINT_OUT_MEX, and ~pragma_manager().
 pragma_manager()
pragma_manager::~pragma_manager () [virtual], [default]
Destructor.
Referenced by pragma_manager().
Member Function Documentation
addBlackBoxPragma()
unsigned int pragma_manager::addBlackBoxPragma (const std::string & function_name)
Definition at line 252 of file pragma_manager.cpp.
References BlackBoxFunctions, TM, TOK, TOK_IS_BLOCK, TOK_OPEN, TOK_PRAGMA_DIRECTIVE, TOK_PRAGMA_SCOPE, and TOK_SRCP.
Referenced by pragma_manager().
addFunctionCallPragmas()
void pragma_manager::addFunctionCallPragmas (const std::string & Name, const CustomUnorderedSet< std::string > & Pragmas)
Definition at line 243 of file pragma_manager.cpp.
References FunctionCallPragmas.
AddFunctionDefinitionPragmas()
void pragma_manager::AddFunctionDefinitionPragmas (const std::string & name, const CustomUnorderedSet< std::string > & pragmas)
Add a set of definition pragmas to a function.
Parameters
function_name is the name of the function
is the set of pragmas to be added
Definition at line 182 of file pragma_manager.cpp.
References application_manager, function_definition_pragmas, param, SplitString(), STR_CST_pragma_keyword_call_hw, THROW_ASSERT, and THROW_ERROR.
AddOmpSimdPragma()
unsigned int pragma_manager::AddOmpSimdPragma (const std::string & line) const
Create a simd openmp pragma starting from the line containing it.
Parameters
line is the string containing the pragma
Returns
the index of the created pragma node
Definition at line 275 of file pragma_manager.cpp.
References ExtractClauses(), TM, TOK, TOK_BB_INDEX, TOK_IS_BLOCK, TOK_OPEN, TOK_PRAGMA_DIRECTIVE, TOK_PRAGMA_SCOPE, and TOK_SRCP.
CheckAddOmpFor()
void pragma_manager::CheckAddOmpFor (const unsigned int function_index, const vertex bb_operation_vertex)
Check if a omp for pragma is associated with the loop; if yes, add the gimple_for.
Parameters
function_index is the index of the function
bb_vertex is the basic block to which for operation belongs
Definition at line 390 of file pragma_manager.cpp.
References FunctionBehavior::BB, FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBNodeInfo(), application_manager::CGetFunctionBehavior(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DOALL_LOOP, GET_NODE, application_manager::GetFunctionBehavior(), INDENT_DBG_MEX, and STR.
CheckAddOmpSimd()
void pragma_manager::CheckAddOmpSimd (const unsigned int function_index, const vertex bb_operation_vertex)
Check if a omp simd pragma is associated with the loop; if yes, add information to the loop.
Parameters
function_index is the index of the function
bb_vertex is the basic block to which for operation belongs
Definition at line 425 of file pragma_manager.cpp.
References FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DOALL_LOOP, GET_NODE, BBGraph::GetBBNodeInfo(), application_manager::GetFunctionBehavior(), INDENT_DBG_MEX, and STR.
checkCompliant()
bool pragma_manager::checkCompliant () const
Check if the datastructure information are compliant with the pragma reference manual.
Returns
true if the datastructure is compliant, false otherwise
Definition at line 151 of file pragma_manager.cpp.
References debug_level, DEBUG_LEVEL_MINIMUM, and PRINT_DBG_MEX.
CheckOmpFor()
bool pragma_manager::CheckOmpFor (const application_managerConstRef app_man, const unsigned int function_index, const vertex bb_operation_vertex) const
Check if a omp for pragma is associated with the loop.
Parameters
app_man is the application manager
function_index is the index of the function
bb_vertex is the basic block to which for operation belongs
Returns
true if there is an associated pragma
Definition at line 359 of file pragma_manager.cpp.
References FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, and INDENT_DBG_MEX.
ExtractClauses()
CustomUnorderedMapUnstable< std::string, std::string > pragma_manager::ExtractClauses (const std::string & clauses_list) const
Extract clauses associated with a pragma.
Parameters
clauses_list is the string containing the clauses
Returns
the extracted clauses
Trim blanks inside parentheses
Definition at line 298 of file pragma_manager.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, index, and SplitString().
Referenced by AddOmpSimdPragma().
get_mapping()
std::string pragma_manager::get_mapping (const std::string & function_name) const
Get mapping of a function given by the pragma.
Parameters
function_name is the name of the function
getFunctionCallPragmas()
CustomUnorderedSet< std::string > pragma_manager::getFunctionCallPragmas (const std::string & Name) const
Definition at line 174 of file pragma_manager.cpp.
References FunctionCallPragmas.
GetFunctionDefinitionPragmas()
const std::list< std::string > pragma_manager::GetFunctionDefinitionPragmas (const std::string & function_name) const
Return the pragmas associated with a function definition.
Parameters
function_name is the name of the function to be considered
Definition at line 165 of file pragma_manager.cpp.
References function_definition_pragmas.
getGenericPragma()
std::string pragma_manager::getGenericPragma (unsigned int number) const
Definition at line 353 of file pragma_manager.cpp.
References GenericPragmas, and THROW_ASSERT.
GetOmpPragmaType()
pragma_manager::OmpPragmaType pragma_manager::GetOmpPragmaType (const std::string & directive) [static]
Returns the identifier corresponding to an openmp directive.
Parameters
directive is the string to be considered
Returns
the corresponding identifier
Definition at line 480 of file pragma_manager.cpp.
References index, omp_directive_keywords, and OMP_UNKNOWN.
Referenced by PragmaAnalysis::create_omp_pragma(), and PragmaParser::recognize_omp_pragma().
isBlackBox()
bool pragma_manager::isBlackBox (const std::string & name) const
Definition at line 160 of file pragma_manager.cpp.
References BlackBoxFunctions.
setGenericPragma()
void pragma_manager::setGenericPragma (unsigned int number, const std::string & line)
Definition at line 348 of file pragma_manager.cpp.
References GenericPragmas.
Field Documentation
application_manager
const application_managerRef pragma_manager::application_manager [protected]
The application manager NOTE: this is equivalente to a weakrefcount since deleter should be null.
Definition at line 87 of file pragma_manager.hpp.
Referenced by AddFunctionDefinitionPragmas().
BlackBoxFunctions
CustomOrderedSet<std::string> pragma_manager::BlackBoxFunctions [protected]
Definition at line 91 of file pragma_manager.hpp.
Referenced by addBlackBoxPragma(), isBlackBox(), and pragma_manager().
debug_level
int pragma_manager::debug_level [protected]
The debug level.
Definition at line 104 of file pragma_manager.hpp.
Referenced by CheckAddOmpFor(), CheckAddOmpSimd(), checkCompliant(), CheckOmpFor(), and ExtractClauses().
function_definition_pragmas
std::map<std::string, std::list<std::string> > pragma_manager::function_definition_pragmas [protected]
Function defintion pragmas.
Definition at line 96 of file pragma_manager.hpp.
Referenced by AddFunctionDefinitionPragmas(), and GetFunctionDefinitionPragmas().
FunctionCallPragmas
std::map<std::string, CustomUnorderedSet<std::string> > pragma_manager::FunctionCallPragmas [protected]
Definition at line 93 of file pragma_manager.hpp.
Referenced by addFunctionCallPragmas(), and getFunctionCallPragmas().
GenericPragmas
std::map<unsigned int, std::string> pragma_manager::GenericPragmas [protected]
Definition at line 98 of file pragma_manager.hpp.
Referenced by getGenericPragma(), and setGenericPragma().
omp_directive_keywords
const std::string pragma_manager::omp_directive_keywords [static]
Initial value:
= {
    "atomic", "barrier", "critical", "declare simd", "for", "parallel for", "parallel sections", "parallel"
      , "sections", "section", "simd", "target", "task",
}
The list of omp directive keywords.
Autoheader include.
Header include design_flows/codesing/partitioning/graph_partitioning/ include Behavior include Constants include Graph include Machine include Parameter include parser/pragma include parser/treegcc include STD include STL includes Task graph include Tree include Utility include
Definition at line 130 of file pragma_manager.hpp.
Referenced by PragmaAnalysis::create_omp_pragma(), GetOmpPragmaType(), and PragmaParser::recognize_omp_pragma().
param
const ParameterConstRef pragma_manager::param [protected]
Set of input parameters.
Definition at line 101 of file pragma_manager.hpp.
Referenced by AddFunctionDefinitionPragmas(), and pragma_manager().
TM
const tree_managerRef pragma_manager::TM [protected]
Definition at line 89 of file pragma_manager.hpp.
Referenced by addBlackBoxPragma(), and AddOmpSimdPragma().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/pragma/pragma_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/pragma/pragma_manager.cpp