IndentedOutputStream Class Reference
Class to print indented code.
#include <indented_output_stream.hpp>
Public Member Functions
IndentedOutputStream (char o='{', char c='}', unsigned int d=3)
constructor
~IndentedOutputStream ()
destructor
void Append (const std::string &message)
Append a string to the output.
void Indent ()
Manually increase the indenting of the code.
void Deindent ()
Manually reduce the indenting of the code.
const std::string WriteString ()
Write the indented output on a string.
void WriteFile (const std::string &file_name)
Write the indented output on a file.
Private Member Functions
void AppendIndent ()
Append the indent spaces.
void AppendChar (const char &c)
Append the current char.
Private Attributes
std::ostringstream output_stream
The actual stream.
unsigned int indent_spaces
number of spaces used to indent after a new line print
char opening_char
char that increments the indent space by a delta
char closing_char
char that increments the indent space by a delta
unsigned int delta
delta indent space
bool is_line_start
Detailed Description
Class to print indented code.
Definition at line 61 of file indented_output_stream.hpp.
Constructor & Destructor Documentation
IndentedOutputStream()
IndentedOutputStream::IndentedOutputStream (char o = '{', char c = '}', unsigned int d = 3)
constructor
Parameters
o is the opening character used by simple_indent.
c is the closing character used by simple_indent.
d is the number of characters used to indent the code.
Definition at line 56 of file indented_output_stream.cpp.
 IndentedOutputStream()
IndentedOutputStream::~IndentedOutputStream ()
destructor
This corresponds to a THROW_ASSERT, however it is against C++ rules throw an errror inside a destructor
Definition at line 60 of file indented_output_stream.cpp.
References indent_spaces, and indentation.
Member Function Documentation
Append()
void IndentedOutputStream::Append (const std::string & message)
Append a string to the output.
Parameters
message is the string to be printed
Specified whether the first character of the string we are going to write must be indented or not
Definition at line 71 of file indented_output_stream.cpp.
References AppendChar(), AppendIndent(), closing_char, Deindent(), delta, indent_spaces, is_line_start, opening_char, output_stream, STD_CLOSING_CHAR, STD_OPENING_CHAR, THROW_UNREACHABLE, and WriteFile().
Referenced by CWriter::compute_phi_nodes(), CreateAddressTranslation::ComputeAddress(), HLSInstructionWriter::declareFunction(), InstructionWriter::declareFunction(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), CWriter::DeclareType(), CWriter::DeclareVariable(), CWriter::EndFunctionBody(), CreateAddressTranslation::Exec(), CBackend::Exec(), BasicBlocksProfilingCWriter::print_edge(), MemoryInitializationCWriter::Process(), CWriter::StartFunctionBody(), InstructionWriter::write(), language_writer::write(), verilog_writer::write_assign(), verilog_writer::write_comment(), VHDL_writer::write_comment(), VHDL_writer::write_component_declaration(), verilog_writer::write_header(), VHDL_writer::write_header(), VHDL_writer::write_io_signal_post_fix(), verilog_writer::write_io_signal_post_fix(), VHDL_writer::write_library_declaration(), verilog_writer::write_module_declaration(), VHDL_writer::write_module_declaration(), verilog_writer::write_module_definition_begin(), VHDL_writer::write_module_definition_begin(), verilog_writer::write_module_definition_end(), VHDL_writer::write_module_definition_end(), verilog_writer::write_module_instance_begin(), VHDL_writer::write_module_instance_begin(), verilog_writer::write_module_instance_end(), VHDL_writer::write_module_instance_end(), VHDL_writer::write_module_internal_declaration(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), VHDL_writer::write_module_parametrization_decl(), verilog_writer::write_module_parametrization_decl(), system_verilog_writer::write_NP_functionalities(), VHDL_writer::write_NP_functionalities(), verilog_writer::write_NP_functionalities(), verilog_writer::write_port_binding(), VHDL_writer::write_port_binding(), VHDL_writer::write_port_decl_header(), VHDL_writer::write_port_decl_tail(), verilog_writer::write_port_declaration(), VHDL_writer::write_port_declaration(), VHDL_writer::write_present_state_update(), verilog_writer::write_present_state_update(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), VHDL_writer::write_state_declaration(), verilog_writer::write_state_declaration(), verilog_writer::write_timing_specification(), VHDL_writer::write_transition_output_functions(), verilog_writer::write_transition_output_functions(), verilog_writer::write_vector_port_binding(), VHDL_writer::write_vector_port_binding(), DiscrepancyAnalysisCWriter::WriteBBHeader(), HLSCWriter::WriteBinaryMemoryInit(), VHDL_writer::WriteBuiltin(), verilog_writer::WriteBuiltin(), CWriter::WriteBuiltinWaitCall(), InstructionWriter::WriteComment(), HLSCWriter::WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraCodeBeforeEveryMainCall(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), CWriter::WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteGlobalDeclarations(), BasicBlocksProfilingCWriter::WriteGlobalDeclarations(), CBackend::WriteGlobalDeclarations(), CWriter::WriteGlobalDeclarations(), CWriter::WriteHashTableImplementation(), EdgeCWriter::WriteHeader(), HLSCWriter::WriteHeader(), CWriter::WriteHeader(), CWriter::writeInclude(), HLSCWriter::WriteMainTestbench(), HLSCWriter::WriteParamDecl(), HLSCWriter::WriteParamInitialization(), HLSCWriter::WriteParamInMemory(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), DiscrepancyAnalysisCWriter::writePreInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), CWriter::writeRoutineInstructions_rec(), HLSCWriter::WriteSimulatorInitMemory(), HLSCWriter::WriteTestbenchFunctionCall(), HLSCWriter::WriteTestbenchGlobalVars(), HLSCWriter::WriteTestbenchHelperFunctions(), and HLSCWriter::WriteZeroedBytes().
AppendChar()
void IndentedOutputStream::AppendChar (const char & c) [private]
Append the current char.
Definition at line 156 of file indented_output_stream.cpp.
References output_stream.
Referenced by Append().
AppendIndent()
void IndentedOutputStream::AppendIndent () [private]
Append the indent spaces.
Definition at line 148 of file indented_output_stream.cpp.
References indent_spaces, and output_stream.
Referenced by Append().
Deindent()
void IndentedOutputStream::Deindent ()
Manually reduce the indenting of the code.
Definition at line 166 of file indented_output_stream.cpp.
References delta, indent_spaces, and THROW_ASSERT.
Referenced by Append(), VHDL_writer::write_component_declaration(), VHDL_writer::write_module_definition_begin(), verilog_writer::write_module_definition_end(), VHDL_writer::write_module_definition_end(), VHDL_writer::write_port_decl_tail(), VHDL_writer::write_present_state_update(), verilog_writer::write_present_state_update(), verilog_writer::write_state_declaration(), verilog_writer::write_timing_specification(), and VHDL_writer::write_transition_output_functions().
Indent()
void IndentedOutputStream::Indent ()
Manually increase the indenting of the code.
Definition at line 161 of file indented_output_stream.cpp.
References delta, and indent_spaces.
Referenced by VHDL_writer::write_component_declaration(), verilog_writer::write_module_declaration(), VHDL_writer::write_module_definition_begin(), VHDL_writer::write_module_internal_declaration(), VHDL_writer::write_port_decl_header(), VHDL_writer::write_present_state_update(), verilog_writer::write_present_state_update(), verilog_writer::write_state_declaration(), verilog_writer::write_timing_specification(), and VHDL_writer::write_transition_output_functions().
WriteFile()
void IndentedOutputStream::WriteFile (const std::string & file_name)
Write the indented output on a file.
Parameters
file_name is the name of the file
Definition at line 179 of file indented_output_stream.cpp.
References output_stream.
Referenced by Append(), CreateAddressTranslation::Exec(), HLSCWriter::WriteFile(), language_writer::WriteFile(), and CWriter::WriteFile().
WriteString()
const std::string IndentedOutputStream::WriteString ()
Write the indented output on a string.
Definition at line 172 of file indented_output_stream.cpp.
References output_stream.
Referenced by language_writer::WriteString().
Field Documentation
closing_char
char IndentedOutputStream::closing_char [private]
char that increments the indent space by a delta
Definition at line 74 of file indented_output_stream.hpp.
Referenced by Append().
delta
unsigned int IndentedOutputStream::delta [private]
delta indent space
Definition at line 77 of file indented_output_stream.hpp.
Referenced by Append(), Deindent(), and Indent().
indent_spaces
unsigned int IndentedOutputStream::indent_spaces [private]
number of spaces used to indent after a new line print
Definition at line 68 of file indented_output_stream.hpp.
Referenced by Append(), AppendIndent(), Deindent(), Indent(), and ~IndentedOutputStream().
is_line_start
bool IndentedOutputStream::is_line_start [private]
Definition at line 79 of file indented_output_stream.hpp.
Referenced by Append().
opening_char
char IndentedOutputStream::opening_char [private]
char that increments the indent space by a delta
Definition at line 71 of file indented_output_stream.hpp.
Referenced by Append().
output_stream
std::ostringstream IndentedOutputStream::output_stream [private]
The actual stream.
Definition at line 65 of file indented_output_stream.hpp.
Referenced by Append(), AppendChar(), AppendIndent(), WriteFile(), and WriteString().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/utility/indented_output_stream.hpp
/home/osboxes/bambu/PandA-bambu/src/utility/indented_output_stream.cpp