GimpleWriter Struct Reference
#include <gimple_writer.hpp>
Public Member Functions
GimpleWriter (std::ostream &_os, const bool _use_uid)
default constructor
Private Attributes
std::ostream & os
tree_node visitors
bool use_uid
If true gcc uid instead of tree node index.
unsigned int current_node_index
The index of the currently visited node.
Detailed Description
Definition at line 52 of file gimple_writer.hpp.
Constructor & Destructor Documentation
GimpleWriter()
GimpleWriter::GimpleWriter (std::ostream & _os, const bool _use_uid)
default constructor
Header include.
Parameters
_os is the stream
_use_uid is true if uid have to be used;
Behavior include parser/treegcc include Tree include
Definition at line 69 of file gimple_writer.cpp.
References test_panda::arg, type_pack_expansion::arg, expr_pack_expansion::arg, type_argument_pack::arg, nontype_argument_pack::arg, test_panda::args, call_expr::args, gimple_call::args, target_mem_ref461::base, BB_ENTRY, BB_EXIT, function_decl::body, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, gimple_phi::CGetDefEdgesList(), tree_list::chan, omp_target_pragma::clauses, omp_task_pragma::clauses, omp_critical_pragma::clauses, omp_for_pragma::clauses, omp_simd_pragma::clauses, omp_declare_simd_pragma::clauses, target_expr::clnp, gimple_assign::clobber, template_parm_index::constant_flag, aggr_init_expr::ctor, current_node_index, target_expr::decl, template_parm_index::decl, case_label_expr::default_flag, ssa_name::default_flag, gimple_pragma::directive, array_type::elts, vector_type::elts, FIRST_TOKEN, call_expr::fn, gimple_call::fn, GET_CONST_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), case_label_expr::got, target_mem_ref::idx, target_mem_ref461::idx, template_parm_index::idx, target_mem_ref461::idx2, tree_node::index, target_expr::init, template_parm_index::level, function_decl::list_of_args, statement_list::list_of_bloc, gimple_multi_way_if::list_of_cond, tree_vec::list_of_op, vector_cst::list_of_valu, decl_node::name, type_node::name, NO_VISIT, target_mem_ref::offset, target_mem_ref461::offset, unary_expr::op, cast_expr::op, type_pack_expansion::op, expr_pack_expansion::op, gimple_label::op, gimple_return::op, gimple_while::op0, binary_expr::op0, ternary_expr::op0, quaternary_expr::op0, case_label_expr::op0, gimple_cond::op0, gimple_assign::op0, gimple_switch::op0, lut_expr::op0, gimple_for::op1, binary_expr::op1, ternary_expr::op1, quaternary_expr::op1, case_label_expr::op1, gimple_assign::op1, gimple_switch::op1, lut_expr::op1, gimple_for::op2, ternary_expr::op2, lut_expr::op2, lut_expr::op3, lut_expr::op4, lut_expr::op5, lut_expr::op6, lut_expr::op7, lut_expr::op8, tree_helper::op_symbol(), template_parm_index::orig_level, ssa_name::orig_vers, os, type_pack_expansion::param_packs, expr_pack_expansion::param_packs, phi, gimple_assign::predicate, pointer_type::ptd, type_node::qual, template_parm_index::readonly_flag, gimple_phi::res, tree_helper::return_C_qualifiers(), gimple_pragma::scope, type_node::size, aggr_init_expr::slot, target_mem_ref::step, target_mem_ref461::step, identifier_node::strg, string_cst::strg, target_mem_ref::symbol, gimple_assign::temporary_address, THROW_ASSERT, THROW_UNREACHABLE, decl_node::type, expr_node::type, cst_node::type, ssa_name::type, template_parm_index::type, decl_node::uid, type_node::unql, use_uid, real_cst::valr, tree_list::valu, ssa_name::var, ssa_name::vers, tree_node::visit(), and ssa_name::visit().
Field Documentation
current_node_index
unsigned int GimpleWriter::current_node_index [private]
The index of the currently visited node.
Definition at line 73 of file gimple_writer.hpp.
Referenced by GimpleWriter().
os
std::ostream& GimpleWriter::os [private]
tree_node visitors
output stream
Definition at line 67 of file gimple_writer.hpp.
Referenced by GimpleWriter().
use_uid
bool GimpleWriter::use_uid [private]
If true gcc uid instead of tree node index.
Definition at line 70 of file gimple_writer.hpp.
Referenced by GimpleWriter().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/gimple_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/gimple_writer.cpp