ASICBackendFlow Class Reference
superclass include
#include <ASICBackendFlow.hpp>
Public Member Functions
ASICBackendFlow (const ParameterConstRef Param, const std::string &flow_name, const target_managerRef target)
Constructor.
~ASICBackendFlow () override
Destructor.
Private Member Functions
void WriteFlowConfiguration (std::ostream &script) override
Writes the proper flow configuration in the output script.
void CheckSynthesisResults () override
Checks the synthesis results and fills the corresponding datastructures.
void InitDesignParameters () override
Evaluates design variables.
void create_sdc (const DesignParametersRef dp)
Creates the constraint file.
Additional Inherited Members
Detailed Description
superclass include
Definition at line 50 of file ASICBackendFlow.hpp.
Constructor & Destructor Documentation
ASICBackendFlow()
ASICBackendFlow::ASICBackendFlow (const ParameterConstRef Param, const std::string & flow_name, const target_managerRef target)
Constructor.
Header include.
Definition at line 60 of file ASICBackendFlow.cpp.
References BackendFlow::default_data, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, BackendFlow::Param, BackendFlow::parse_flow(), test_panda::parser, PRINT_OUT_MEX, THROW_ERROR, and ~ASICBackendFlow().
 ASICBackendFlow()
ASICBackendFlow::~ASICBackendFlow () [override], [default]
Destructor.
Referenced by ASICBackendFlow().
Member Function Documentation
CheckSynthesisResults()
void ASICBackendFlow::CheckSynthesisResults () [override], [private], [virtual]
Checks the synthesis results and fills the corresponding datastructures.
Implements BackendFlow.
Definition at line 112 of file ASICBackendFlow.cpp.
References BackendFlow::area_m, DESIGN_COMPILER_TOOL_ID, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, PRINT_OUT_MEX, BackendFlow::steps, and BackendFlow::time_m.
create_sdc()
void ASICBackendFlow::create_sdc (const DesignParametersRef dp) [private]
Creates the constraint file.
Definition at line 87 of file ASICBackendFlow.cpp.
References DesignParameters::component_name, BackendFlow::out_dir, BackendFlow::Param, PARAM_clk_name, PARAM_clk_period, PARAM_is_combinational, PARAM_sdc_file, and DesignParameters::parameter_values.
Referenced by InitDesignParameters().
InitDesignParameters()
void ASICBackendFlow::InitDesignParameters () [override], [private], [virtual]
Evaluates design variables.
Reimplemented from BackendFlow.
Definition at line 102 of file ASICBackendFlow.cpp.
References BackendFlow::actual_parameters, create_sdc(), and BackendFlow::steps.
WriteFlowConfiguration()
void ASICBackendFlow::WriteFlowConfiguration (std::ostream & script) [override], [private], [virtual]
Writes the proper flow configuration in the output script.
nothing to do
Implements BackendFlow.
Definition at line 130 of file ASICBackendFlow.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/ASICBackendFlow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/ASICBackendFlow.cpp