ParallelMemoryConnBinding Class Reference
Superclass include.
#include <parallel_memory_conn_binding.hpp>
Public Member Functions
ParallelMemoryConnBinding (const BehavioralHelperConstRef BH, const ParameterConstRef parameters)
Constructor.
virtual ~ParallelMemoryConnBinding ()
Destructor.
void add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM)
Add the interconnection to the structural representation of the datapath.
Additional Inherited Members
Detailed Description
Superclass include.
Definition at line 46 of file parallel_memory_conn_binding.hpp.
Constructor & Destructor Documentation
ParallelMemoryConnBinding()
ParallelMemoryConnBinding::ParallelMemoryConnBinding (const BehavioralHelperConstRef _behavioral_helper, const ParameterConstRef _parameters)
Constructor.
Header include.
. include circuit includes HLS includes HLS/binding/module HLS/functions
Definition at line 61 of file parallel_memory_conn_binding.cpp.
 ParallelMemoryConnBinding()
ParallelMemoryConnBinding::~ParallelMemoryConnBinding () [virtual]
Destructor.
Definition at line 65 of file parallel_memory_conn_binding.cpp.
Member Function Documentation
add_to_SM()
void ParallelMemoryConnBinding::add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM) [virtual]
Add the interconnection to the structural representation of the datapath.
Reimplemented from conn_binding.
Definition at line 69 of file parallel_memory_conn_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_sign_vector(), conn_binding::add_to_SM(), DONE_PORT_NAME, structural_object::find_member(), structural_manager::get_circ(), conn_binding::get_port(), conn_binding::parameters, port_o_K, hls::Rfu, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/parallel_memory_conn_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/parallel_memory_conn_binding.cpp