boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container > Class Template Reference
#include <maxclique_dsatur_coloring.hpp>
Public Member Functions
maxclique_dsatur_coloring_helper (const VertexListGraph &_G, ColorMap &_CM, const size_type _num_node, size_type &_lb)
~maxclique_dsatur_coloring_helper ()
maxclique_dsatur_coloring_helper (const maxclique_dsatur_coloring_helper &inst)=delete
maxclique_dsatur_coloring_helper & operator= (const maxclique_dsatur_coloring_helper &inst)=delete
size_type MaxCliqueGreedy ()
size_type MaxCliqueRec (size_type ub)
void save_colors ()
void AssignColor (size_type node, size_type color)
void RemoveColor (size_type node, size_type color)
size_type SeqColorRec (size_type i, size_type current_color)
Private Types
typedef graph_traits< VertexListGraph > GraphTraits
typedef GraphTraits::vertex_descriptor Vertex
typedef filtered_graph< VertexListGraph, keep_all, select_vertex< SET_container > > Induced_Graph
typedef graph_traits< Induced_Graph > IG_GraphTraits
typedef IG_GraphTraits::vertex_descriptor IG_Vertex
Private Attributes
const size_type num_node
size_type BestColoring
std::vector< size_type > ColorClass
std::vector< bool > valid
boost::numeric::ublas::matrix< size_type > ColorAdj
std::vector< size_type > ColorCount
std::vector< size_type > DegreeCount
size_type & lb
const VertexListGraph & G
ColorMap & CM
size_type * heap_container
heap_compare_functor< size_type > HCF
const unsigned int clique_size
select_vertex< SET_container > filter
SET_container support
SET_container C
SET_container BestClique
Induced_Graph FG
Detailed Description
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
class boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >
Definition at line 199 of file maxclique_dsatur_coloring.hpp.
Member Typedef Documentation
GraphTraits
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
typedef graph_traits<VertexListGraph> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::GraphTraits [private]
Definition at line 202 of file maxclique_dsatur_coloring.hpp.
IG_GraphTraits
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
typedef graph_traits<Induced_Graph> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::IG_GraphTraits [private]
Definition at line 224 of file maxclique_dsatur_coloring.hpp.
IG_Vertex
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
typedef IG_GraphTraits::vertex_descriptor boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::IG_Vertex [private]
Definition at line 225 of file maxclique_dsatur_coloring.hpp.
Induced_Graph
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
typedef filtered_graph<VertexListGraph, keep_all, select_vertex<SET_container> > boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::Induced_Graph [private]
Definition at line 222 of file maxclique_dsatur_coloring.hpp.
Vertex
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
typedef GraphTraits::vertex_descriptor boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::Vertex [private]
Definition at line 203 of file maxclique_dsatur_coloring.hpp.
Constructor & Destructor Documentation
maxclique_dsatur_coloring_helper() [1/2]
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::maxclique_dsatur_coloring_helper (const VertexListGraph & _G, ColorMap & _CM, const size_type _num_node, size_type & _lb) [inline]
Definition at line 228 of file maxclique_dsatur_coloring.hpp.
 maxclique_dsatur_coloring_helper()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::~maxclique_dsatur_coloring_helper () [inline]
Definition at line 256 of file maxclique_dsatur_coloring.hpp.
maxclique_dsatur_coloring_helper() [2/2]
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::maxclique_dsatur_coloring_helper (const maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container > & inst) [delete]
Member Function Documentation
AssignColor()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
void boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::AssignColor (size_type node, size_type color) [inline]
Definition at line 391 of file maxclique_dsatur_coloring.hpp.
MaxCliqueGreedy()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
size_type boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::MaxCliqueGreedy () [inline]
Definition at line 263 of file maxclique_dsatur_coloring.hpp.
Referenced by boost::maxclique_dsatur_coloring().
MaxCliqueRec()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
size_type boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::MaxCliqueRec (size_type ub) [inline]
if C is empty and k is good save the coloring
look for the vertex with maximum degree
check a) condition
check for the minimum degree condition
create the support for the the induced graph N{selected}
Definition at line 303 of file maxclique_dsatur_coloring.hpp.
References boost::unsorted_coloring().
Referenced by boost::maxclique_dsatur_coloring().
operator=()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
maxclique_dsatur_coloring_helper& boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::operator= (const maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container > & inst) [delete]
RemoveColor()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
void boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::RemoveColor (size_type node, size_type color) [inline]
Definition at line 408 of file maxclique_dsatur_coloring.hpp.
save_colors()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
void boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::save_colors () [inline]
Definition at line 383 of file maxclique_dsatur_coloring.hpp.
SeqColorRec()
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
size_type boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::SeqColorRec (size_type i, size_type current_color) [inline]
Definition at line 424 of file maxclique_dsatur_coloring.hpp.
Referenced by boost::maxclique_dsatur_coloring().
Field Documentation
BestClique
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
SET_container boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::BestClique [private]
Definition at line 221 of file maxclique_dsatur_coloring.hpp.
BestColoring
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
size_type boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::BestColoring [private]
Definition at line 205 of file maxclique_dsatur_coloring.hpp.
C
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
SET_container boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::C [private]
Definition at line 220 of file maxclique_dsatur_coloring.hpp.
clique_size
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
const unsigned int boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::clique_size [private]
Definition at line 217 of file maxclique_dsatur_coloring.hpp.
CM
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
ColorMap& boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::CM [private]
Definition at line 214 of file maxclique_dsatur_coloring.hpp.
ColorAdj
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
boost::numeric::ublas::matrix<size_type> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::ColorAdj [private]
Definition at line 209 of file maxclique_dsatur_coloring.hpp.
ColorClass
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
std::vector<size_type> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::ColorClass [private]
Definition at line 206 of file maxclique_dsatur_coloring.hpp.
ColorCount
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
std::vector<size_type> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::ColorCount [private]
Definition at line 210 of file maxclique_dsatur_coloring.hpp.
DegreeCount
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
std::vector<size_type> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::DegreeCount [private]
Definition at line 211 of file maxclique_dsatur_coloring.hpp.
FG
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
Induced_Graph boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::FG [private]
Definition at line 223 of file maxclique_dsatur_coloring.hpp.
filter
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
select_vertex<SET_container> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::filter [private]
Definition at line 218 of file maxclique_dsatur_coloring.hpp.
G
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
const VertexListGraph& boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::G [private]
Definition at line 213 of file maxclique_dsatur_coloring.hpp.
HCF
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
heap_compare_functor<size_type> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::HCF [private]
Definition at line 216 of file maxclique_dsatur_coloring.hpp.
heap_container
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
size_type* boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::heap_container [private]
Definition at line 215 of file maxclique_dsatur_coloring.hpp.
lb
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
size_type& boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::lb [private]
Definition at line 212 of file maxclique_dsatur_coloring.hpp.
num_node
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
const size_type boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::num_node [private]
Definition at line 204 of file maxclique_dsatur_coloring.hpp.
support
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
SET_container boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::support [private]
Definition at line 219 of file maxclique_dsatur_coloring.hpp.
valid
template<typename VertexListGraph, typename ColorMap, typename size_type, typename SET_container>
std::vector<bool> boost::maxclique_dsatur_coloring_helper< VertexListGraph, ColorMap, size_type, SET_container >::valid [private]
Definition at line 207 of file maxclique_dsatur_coloring.hpp.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/maxclique_dsatur_coloring.hpp