StateTransitionGraph Struct Reference
Class used to describe a state transition graph.
#include <state_transition_graph.hpp>
Public Member Functions
StateTransitionGraph (const StateTransitionGraphsCollectionRef state_transition_graphs_collection, int selector)
Standard constructor.
StateTransitionGraph (const StateTransitionGraphsCollectionRef state_transition_graphs_collection, int selector, CustomUnorderedSet< vertex > &sub)
Sub-graph constructor.
~StateTransitionGraph () override
Destructor.
StateInfoRef GetStateInfo (const vertex state)
Return the info associated with a state.
const StateInfoConstRef CGetStateInfo (const vertex state) const
Return the info associated with a state.
const StateInfoConstRef CGetStateInfo (unsigned int state_id) const
Return the info associated with a state, given its ID is the ID of the state to be considered.
vertex GetVertex (unsigned int state_id) const
Return the state vertex corresponding to the given id.
TransitionInfoRef GetTransitionInfo (const EdgeDescriptor transition)
Return the info associated with a transition.
const TransitionInfoConstRef CGetTransitionInfo (const EdgeDescriptor transition) const
Return the info associated with a transition.
StateTransitionGraphInfoRef GetStateTransitionGraphInfo ()
Return the info associated with the graph.
const StateTransitionGraphInfoConstRef CGetStateTransitionGraphInfo () const
Return the info associated with the graph.
void WriteDot (const std::string &file_name, const int detail_level=0) const
Writes this graph in dot format.
Additional Inherited Members
Detailed Description
Class used to describe a state transition graph.
Definition at line 317 of file state_transition_graph.hpp.
Constructor & Destructor Documentation
StateTransitionGraph() [1/2]
StateTransitionGraph::StateTransitionGraph (const StateTransitionGraphsCollectionRef state_transition_graphs_collection, int selector)
Standard constructor.
Parameters
state_transition_graphs_collection is the bulk graph.
selector is the selector used to filter the bulk graph.
Definition at line 307 of file state_transition_graph.cpp.
StateTransitionGraph() [2/2]
StateTransitionGraph::StateTransitionGraph (const StateTransitionGraphsCollectionRef state_transition_graphs_collection, int selector, CustomUnorderedSet< vertex > & sub)
Sub-graph constructor.
Parameters
state_transition_graphs_collection is the bulk graph.
selector is the selector used to filter the bulk graph.
sub is the set of vertices on which the graph is filtered.
Definition at line 311 of file state_transition_graph.cpp.
References ~StateTransitionGraph().
 StateTransitionGraph()
StateTransitionGraph::~StateTransitionGraph () [override], [default]
Destructor.
Referenced by StateTransitionGraph().
Member Function Documentation
CGetStateInfo() [1/2]
const StateInfoConstRef StateTransitionGraph::CGetStateInfo (const vertex state) const [inline]
Return the info associated with a state.
Parameters
state is the state to be considered
Definition at line 353 of file state_transition_graph.hpp.
References graph::CGetNodeInfo().
Referenced by WriteDot().
CGetStateInfo() [2/2]
const StateInfoConstRef StateTransitionGraph::CGetStateInfo (unsigned int state_id) const [inline]
Return the info associated with a state, given its ID is the ID of the state to be considered.
Definition at line 362 of file state_transition_graph.hpp.
CGetStateTransitionGraphInfo()
const StateTransitionGraphInfoConstRef StateTransitionGraph::CGetStateTransitionGraphInfo () const [inline]
Return the info associated with the graph.
Returns
the info associated with the graph
Definition at line 407 of file state_transition_graph.hpp.
References graph::CGetGraphInfo().
Referenced by WriteDot().
CGetTransitionInfo()
const TransitionInfoConstRef StateTransitionGraph::CGetTransitionInfo (const EdgeDescriptor transition) const [inline]
Return the info associated with a transition.
Parameters
transition is the transition to be considered
Definition at line 389 of file state_transition_graph.hpp.
References graph::CGetEdgeInfo().
GetStateInfo()
StateInfoRef StateTransitionGraph::GetStateInfo (const vertex state) [inline]
Return the info associated with a state.
Parameters
state is the state to be considered
Definition at line 344 of file state_transition_graph.hpp.
References graph::GetNodeInfo().
GetStateTransitionGraphInfo()
StateTransitionGraphInfoRef StateTransitionGraph::GetStateTransitionGraphInfo () [inline]
Return the info associated with the graph.
Returns
the info associated with the graph
Definition at line 398 of file state_transition_graph.hpp.
References graph::GetGraphInfo().
GetTransitionInfo()
TransitionInfoRef StateTransitionGraph::GetTransitionInfo (const EdgeDescriptor transition) [inline]
Return the info associated with a transition.
Parameters
transition is the transition to be considered
Definition at line 380 of file state_transition_graph.hpp.
References graph::GetEdgeInfo().
GetVertex()
vertex StateTransitionGraph::GetVertex (unsigned int state_id) const [inline]
Return the state vertex corresponding to the given id.
Definition at line 370 of file state_transition_graph.hpp.
References STR, and THROW_ASSERT.
WriteDot()
void StateTransitionGraph::WriteDot (const std::string & file_name, const int detail_level = 0) const
Writes this graph in dot format.
Parameters
file_name is the file where the graph has to be printed
detail_level is the detail level of the printed graph
Definition at line 317 of file state_transition_graph.cpp.
References OpGraph::CGetOpGraphInfo(), CGetStateInfo(), CGetStateTransitionGraphInfo(), graph::collection, FunctionBehavior::DFG, and graphs_collection::parameters.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/state_transition_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/state_transition_graph.cpp