vertex_coloring_register Class Reference
#include <vertex_coloring_register.hpp>
Public Member Functions
vertex_coloring_register (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor of the class.
~vertex_coloring_register () override
Destructor of the class.
DesignFlowStep_Status InternalExec () override
Execute the step.
Additional Inherited Members
Detailed Description
Definition at line 48 of file vertex_coloring_register.hpp.
Constructor & Destructor Documentation
vertex_coloring_register()
vertex_coloring_register::vertex_coloring_register (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor of the class.
HLS/binding/storage_value_insertion includes.
Parameters
design_flow_manager is the design flow manager
tree include utility include
Definition at line 68 of file vertex_coloring_register.cpp.
References COLORING_REGISTER_BINDING, and ~vertex_coloring_register().
 vertex_coloring_register()
vertex_coloring_register::~vertex_coloring_register () [override], [default]
Destructor of the class.
Referenced by vertex_coloring_register().
Member Function Documentation
InternalExec()
DesignFlowStep_Status vertex_coloring_register::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
coloring based on DSATUR 2 heuristic
finalize
Implements HLSFunctionStep.
Definition at line 75 of file vertex_coloring_register.cpp.
References reg_binding::bind(), conflict_based_register::cg, conflict_based_register::color, conflict_based_register::create_conflict_graph(), boost::dsatur2_coloring(), HLSFunctionStep::funId, liveness::get_live_in(), StorageValueInformation::get_storage_value_index(), liveness::get_support(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, variable2obj< data_obj >::print(), print_cpu_time(), reg_binding_creator::register_lower_bound, hls::Rliv, hls::Rreg, reg_binding::set_used_regs(), START_TIME, STOP_TIME, hls::storage_value_information, STR, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/vertex_coloring_register.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/vertex_coloring_register.cpp