signal_o Class Reference
This class describes a simple logic/RTL signal.
#include <structural_objects.hpp>
Public Member Functions
signal_o (int debug_level, const structural_objectRef o, so_kind _signal_type)
Constructor.
~signal_o () override=default
Destructor.
void add_port (structural_objectRef p)
Bind the connection object with a port.
void remove_port (structural_objectRef s)
remove the connection of this signal with a port
bool is_connected (structural_objectRef s) const
void substitute_port (structural_objectRef old_port, structural_objectRef new_port)
void set_critical ()
set the signal as critical with respect to the timing path
bool get_critical () const
return if the component is critical or not
const structural_objectRef get_port (unsigned int n) const
Return the ith port bounded to the connection.
structural_objectRef get_port (unsigned int n)
Return the ith port bounded to the connection.
unsigned int get_connected_objects_size () const
Return the number of ports associated with the connection.
bool is_full_connected () const
Return if signal has both input and output.
void add_n_signals (unsigned int n_signals, structural_objectRef owner)
Specify the number of ports of a generic port_vector object and add its corresponding ports.
const structural_objectRef get_signal (unsigned int n) const
Return the ith port of the vector.
const structural_objectRef get_positional_signal (unsigned int n) const
Return the ith port of the vector with respect to lsb.
unsigned int get_signals_size () const
Return the number of ports.
unsigned int get_lsb () const
return the index of the least significant port
void copy (structural_objectRef dest) const override
Perform a copy of the signal.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the signal (for debug purpose)
std::string get_kind_text () const override
return the name of the class as a string.
enum so_kind get_kind () const override
return the type of the class
Static Public Attributes
static const unsigned int PARAMETRIC_SIGNAL = static_cast<unsigned int>(-1)
Private Attributes
std::vector< structural_objectRef > connected_objects
List of ports bound to the signal object.
bool is_critical
when true the signal is involved into the critical path of the netlist
std::vector< structural_objectRef > signals_
The list of signals associated with the vector of signals.
unsigned int lsb
so_kind signal_type
port type
Additional Inherited Members
Detailed Description
This class describes a simple logic/RTL signal.
A signal can be an array of bit but it cannot be sliced or partially accessed. In case of partial access or slicing the bus_connection_o object should be used.
Definition at line 1612 of file structural_objects.hpp.
Constructor & Destructor Documentation
signal_o()
signal_o::signal_o (int debug_level, const structural_objectRef o, so_kind _signal_type)
Constructor.
Parameters
o is the owner of the port
Definition at line 2077 of file structural_objects.cpp.
Referenced by add_n_signals(), copy(), and xload().
 signal_o()
signal_o::~signal_o () [override], [default]
Destructor.
Member Function Documentation
add_n_signals()
void signal_o::add_n_signals (unsigned int n_signals, structural_objectRef owner)
Specify the number of ports of a generic port_vector object and add its corresponding ports.
It can be done only on port_vectors not yet specialized. The type of the port is equal to the type descriptor of the port_vector.
Parameters
n_signals is the number of signals.
owner is the reference version of `this`.
Definition at line 2397 of file structural_objects.cpp.
References structural_object::debug_level, refcount< T >::get(), structural_object::get_typeRef(), PARAMETRIC_SIGNAL, structural_object::set_id(), structural_object::set_type(), signal_o(), signal_o_K, signal_type, signal_vector_o_K, signals_, and THROW_ASSERT.
add_port()
void signal_o::add_port (structural_objectRef p)
Bind the connection object with a port.
Parameters
p is the port
Definition at line 2091 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
Referenced by xload().
copy()
void signal_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the signal.
Parameters
dest destination object.
someone has to take care of connected_objects
Reimplemented from structural_object.
Definition at line 2245 of file structural_objects.cpp.
References structural_object::copy(), structural_object::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_path(), is_critical, lsb, PRINT_DBG_MEX, set_critical(), signal_o(), signal_o_K, and signals_.
find_isomorphic()
structural_objectRef signal_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Please pay attention to this: connected_objects are not built in this moment! check first the if key is part of a port vector
port_vector at the same level
primary ports
simple port at the same level
search key in the owner
search the owner of the key and then the key
Implements structural_object.
Definition at line 2262 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, structural_object::find_isomorphic(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, signals_, THROW_ASSERT, and THROW_ERROR.
find_member()
structural_objectRef signal_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 2212 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, connected_objects, constant_o_K, data_o_K, event_o_K, structural_object::get_kind_text(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, signals_, and THROW_ERROR.
get_connected_objects_size()
unsigned int signal_o::get_connected_objects_size () const
Return the number of ports associated with the connection.
Definition at line 2151 of file structural_objects.cpp.
References connected_objects.
get_critical()
bool signal_o::get_critical () const
return if the component is critical or not
Definition at line 2086 of file structural_objects.cpp.
References is_critical.
get_kind()
enum so_kind signal_o::get_kind () const [inline], [override], [virtual]
return the type of the class
Implements structural_object.
Definition at line 1762 of file structural_objects.hpp.
get_kind_text()
std::string signal_o::get_kind_text () const [inline], [override], [virtual]
return the name of the class as a string.
Implements structural_object.
Definition at line 1752 of file structural_objects.hpp.
References signal_vector_o_K.
Referenced by xwrite().
get_lsb()
unsigned int signal_o::get_lsb () const [inline]
return the index of the least significant port
Definition at line 1704 of file structural_objects.hpp.
References structural_type_descriptor::copy(), structural_type_descriptor::print(), structural_type_descriptor::type, structural_type_descriptor::xload(), and structural_type_descriptor::xwrite().
get_port() [1/2]
const structural_objectRef signal_o::get_port (unsigned int n) const
Return the ith port bounded to the connection.
Parameters
n is the index of the port.
Definition at line 2099 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
get_port() [2/2]
structural_objectRef signal_o::get_port (unsigned int n)
Return the ith port bounded to the connection.
Parameters
n is the index of the port.
Definition at line 2105 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
get_positional_signal()
const structural_objectRef signal_o::get_positional_signal (unsigned int n) const
Return the ith port of the vector with respect to lsb.
It also checks if the port exists
Parameters
n is the index of the port
Definition at line 2422 of file structural_objects.cpp.
References lsb, signals_, and THROW_ASSERT.
get_signal()
const structural_objectRef signal_o::get_signal (unsigned int n) const
Return the ith port of the vector.
It checks that a port exists at position n.
Parameters
n is the index of the port
Definition at line 2415 of file structural_objects.cpp.
References structural_object::get_path(), signals_, STR, and THROW_ASSERT.
get_signals_size()
unsigned int signal_o::get_signals_size () const
Return the number of ports.
When the port_vector has not yet specialized 0 is returned.
Definition at line 2428 of file structural_objects.cpp.
References signals_, and THROW_ASSERT.
is_connected()
bool signal_o::is_connected (structural_objectRef s) const
Definition at line 2120 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
is_full_connected()
bool signal_o::is_full_connected () const
Return if signal has both input and output.
Returns
true if signal has both input and output
Definition at line 2156 of file structural_objects.cpp.
References connected_objects, structural_object::get_owner(), port_o::IN, port_o::IO, and port_o::OUT.
print()
void signal_o::print (std::ostream & os) const [override], [virtual]
Print the signal (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Definition at line 2378 of file structural_objects.cpp.
References connected_objects, structural_object::convert_so_short(), structural_object::PP, structural_object::print(), and signals_.
remove_port()
void signal_o::remove_port (structural_objectRef s)
remove the connection of this signal with a port
Parameters
s is the connection
Definition at line 2111 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
set_critical()
void signal_o::set_critical ()
set the signal as critical with respect to the timing path
Definition at line 2081 of file structural_objects.cpp.
References is_critical.
Referenced by copy().
substitute_port()
void signal_o::substitute_port (structural_objectRef old_port, structural_objectRef new_port)
Definition at line 2128 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
xload()
void signal_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
someone has to take care of the connected_objects
Reimplemented from structural_object.
Definition at line 2313 of file structural_objects.cpp.
References add_port(), component_o_K, structural_object::find_member(), xml_child::get_children(), GET_CLASS_NAME, structural_manager::get_debug_level(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), legalize(), lsb, min, port_o_K, port_vector_o_K, structural_object::set_id(), signal_o(), signal_o_K, signal_type, signal_vector_o_K, signals_, THROW_ASSERT, and structural_object::xload().
xwrite()
void signal_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Definition at line 2367 of file structural_objects.cpp.
References xml_child::add_child_element(), connected_objects, get_kind_text(), signals_, WRITE_XNVM2, and structural_object::xwrite().
Field Documentation
connected_objects
std::vector<structural_objectRef> signal_o::connected_objects [private]
List of ports bound to the signal object.
Definition at line 1769 of file structural_objects.hpp.
Referenced by add_port(), find_member(), get_connected_objects_size(), get_port(), is_connected(), is_full_connected(), print(), remove_port(), substitute_port(), and xwrite().
is_critical
bool signal_o::is_critical [private]
when true the signal is involved into the critical path of the netlist
Definition at line 1772 of file structural_objects.hpp.
Referenced by copy(), get_critical(), and set_critical().
lsb
unsigned int signal_o::lsb [private]
Definition at line 1777 of file structural_objects.hpp.
Referenced by copy(), get_positional_signal(), and xload().
PARAMETRIC_SIGNAL
const unsigned int signal_o::PARAMETRIC_SIGNAL = static_cast<unsigned int>(-1) [static]
Definition at line 1615 of file structural_objects.hpp.
Referenced by add_n_signals(), and structural_manager::add_sign_vector().
signal_type
so_kind signal_o::signal_type [private]
port type
Definition at line 1780 of file structural_objects.hpp.
Referenced by add_n_signals(), and xload().
signals_
std::vector<structural_objectRef> signal_o::signals_ [private]
The list of signals associated with the vector of signals.
Definition at line 1775 of file structural_objects.hpp.
Referenced by add_n_signals(), copy(), find_isomorphic(), find_member(), get_positional_signal(), get_signal(), get_signals_size(), print(), xload(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp