CInitializationParser Class Reference
#include <c_initialization_parser.hpp>
Public Member Functions
CInitializationParser (const ParameterConstRef parameters)
Constructor.
void Parse (const CInitializationParserFunctorRef c_initialization_parser_functor, const std::string &initialization_string) const
Parse a string to generate the corresponding memory initialization.
Private Member Functions
void YYParse (const CInitializationParserFunctorRef c_initialization_parser_functor, const CInitializationFlexLexerRef lexer) const
Wrapper to yyparse.
Private Attributes
const ParameterConstRef parameters
The set of input parameters.
int debug_level
The debug level.
Detailed Description
Definition at line 53 of file c_initialization_parser.hpp.
Constructor & Destructor Documentation
CInitializationParser()
CInitializationParser::CInitializationParser (const ParameterConstRef parameters)
Constructor.
utility include
Parameters
parameters is the set of input parameters
Definition at line 56 of file c_initialization_parser.cpp.
References debug_level, GET_CLASS, and parameters.
Member Function Documentation
Parse()
void CInitializationParser::Parse (const CInitializationParserFunctorRef c_initialization_parser_functor, const std::string & initialization_string) const
Parse a string to generate the corresponding memory initialization.
Parameters
c_initialization_parser_functor is the functor used during parsing
initialization_string is the C initialization string of a variable
Definition at line 61 of file c_initialization_parser.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, fileIO_istream_open_from_string(), refcount< T >::get(), INDENT_DBG_MEX, parameters, and YYParse().
YYParse()
void CInitializationParser::YYParse (const CInitializationParserFunctorRef c_initialization_parser_functor, const CInitializationFlexLexerRef lexer) const [private]
Wrapper to yyparse.
Parameters
c_initialization_parser_functor is the functor used during the parsing
lexer is the lexer used to process the initiation string
Referenced by Parse().
Field Documentation
debug_level
int CInitializationParser::debug_level [private]
The debug level.
Definition at line 60 of file c_initialization_parser.hpp.
Referenced by CInitializationParser(), and Parse().
parameters
const ParameterConstRef CInitializationParser::parameters [private]
The set of input parameters.
Definition at line 57 of file c_initialization_parser.hpp.
Referenced by CInitializationParser(), and Parse().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/c_initialization_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/c_initialization_parser.cpp