CdfgEdgeInfo Struct Reference
Information associated with an operation or basic block graph.
#include <cdfg_edge_info.hpp>
Public Member Functions
CdfgEdgeInfo ()=default
Constructor.
bool CdgEdgeT () const
Function returning true when the edge is a then control dependence edge.
bool CdgEdgeF () const
Function returning true when the edge is an else control dependence edge.
bool CfgEdgeT () const
Function returning true when the edge is a then control flow edge.
bool CfgEdgeF () const
Function returning true when the edge is an else control flow edge.
bool Switch () const
Return true if it is an edge associated with a switch.
void add_nodeID (unsigned int nodeID, const int type)
Add a nodeID of type type to this edge_info.
const CustomOrderedSet< unsigned int > & get_nodeID (const int type) const
Return the nodeID of type type associated with this edge information.
const std::string PrintLabels (const int type, const BehavioralHelperConstRef BH) const
Return the string of the labels associated with the edge.
Protected Attributes
std::map< int, CustomOrderedSet< unsigned int > > labels
edge labels; key is the selector
Detailed Description
Information associated with an operation or basic block graph.
Definition at line 91 of file cdfg_edge_info.hpp.
Constructor & Destructor Documentation
CdfgEdgeInfo()
CdfgEdgeInfo::CdfgEdgeInfo () [default]
Constructor.
Member Function Documentation
add_nodeID()
void CdfgEdgeInfo::add_nodeID (unsigned int nodeID, const int type)
Add a nodeID of type type to this edge_info.
Parameters
nodeID is the nodeID
type is the type
Definition at line 111 of file cdfg_edge_info.cpp.
References labels, and test_panda::type.
CdgEdgeF()
bool CdfgEdgeInfo::CdgEdgeF () const
Function returning true when the edge is an else control dependence edge.
Definition at line 54 of file cdfg_edge_info.cpp.
References CDG_SELECTOR, F_COND, and labels.
Referenced by Switch().
CdgEdgeT()
bool CdfgEdgeInfo::CdgEdgeT () const
Function returning true when the edge is a then control dependence edge.
Definition at line 47 of file cdfg_edge_info.cpp.
References CDG_SELECTOR, labels, and T_COND.
Referenced by Switch().
CfgEdgeF()
bool CdfgEdgeInfo::CfgEdgeF () const
Function returning true when the edge is an else control flow edge.
Definition at line 68 of file cdfg_edge_info.cpp.
References CFG_SELECTOR, F_COND, and labels.
Referenced by Switch().
CfgEdgeT()
bool CdfgEdgeInfo::CfgEdgeT () const
Function returning true when the edge is a then control flow edge.
Definition at line 61 of file cdfg_edge_info.cpp.
References CFG_SELECTOR, labels, and T_COND.
Referenced by Switch().
get_nodeID()
const CustomOrderedSet< unsigned int > & CdfgEdgeInfo::get_nodeID (const int type) const
Return the nodeID of type type associated with this edge information.
Parameters
type is the type
Returns
the nodeID of type type
Definition at line 116 of file cdfg_edge_info.cpp.
References labels.
PrintLabels()
const std::string CdfgEdgeInfo::PrintLabels (const int type, const BehavioralHelperConstRef BH) const
Return the string of the labels associated with the edge.
Parameters
type is the type of labels to be printed
BH is the helper used to print the labels
Definition at line 80 of file cdfg_edge_info.cpp.
References default_COND, F_COND, labels, BehavioralHelper::PrintVariable(), and T_COND.
Switch()
bool CdfgEdgeInfo::Switch () const
Return true if it is an edge associated with a switch.
Definition at line 75 of file cdfg_edge_info.cpp.
References CDG_SELECTOR, CdgEdgeF(), CdgEdgeT(), CFG_SELECTOR, CfgEdgeF(), CfgEdgeT(), and labels.
Field Documentation
labels
std::map<int, CustomOrderedSet<unsigned int> > CdfgEdgeInfo::labels [protected]
edge labels; key is the selector
Definition at line 95 of file cdfg_edge_info.hpp.
Referenced by add_nodeID(), CdgEdgeF(), CdgEdgeT(), CfgEdgeF(), CfgEdgeT(), OpEdgeInfo::FlgEdgeF(), OpEdgeInfo::FlgEdgeT(), get_nodeID(), PrintLabels(), and Switch().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/cdfg_edge_info.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/cdfg_edge_info.cpp