LatticeBackendFlow Class Reference
superclass include
#include <LatticeBackendFlow.hpp>
Public Member Functions
LatticeBackendFlow (const ParameterConstRef Param, const std::string &flow_name, const target_managerRef target)
Constructor.
~LatticeBackendFlow () override
Destructor.
void InitDesignParameters () override
Initializes the parameters.
void ExecuteSynthesis () override
Checks if the execution can be performed and, in case, performs the synthesis.
Private Member Functions
void WriteFlowConfiguration (std::ostream &script) override
Writes the proper flow configuration in the output script.
void xparse_utilization (const std::string &fn)
Parses device utilization.
void CheckSynthesisResults () override
Checks the synthesis results and fills the corresponding datastructures.
void create_sdc (const DesignParametersRef dp)
Creates the constraint file.
Private Attributes
std::map< std::string, double > design_values
design values reported by the tools
Additional Inherited Members
Detailed Description
superclass include
Definition at line 50 of file LatticeBackendFlow.hpp.
Constructor & Destructor Documentation
LatticeBackendFlow()
LatticeBackendFlow::LatticeBackendFlow (const ParameterConstRef Param, const std::string & flow_name, const target_managerRef target)
Constructor.
Definition at line 75 of file LatticeBackendFlow.cpp.
References BackendFlow::debug_level, DEBUG_LEVEL_VERBOSE, BackendFlow::default_data, target_device::get_parameter(), target_device::has_parameter(), INDENT_DBG_MEX, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, BackendFlow::Param, BackendFlow::parse_flow(), test_panda::parser, PRINT_OUT_MEX, BackendFlow::target, THROW_ERROR, and ~LatticeBackendFlow().
 LatticeBackendFlow()
LatticeBackendFlow::~LatticeBackendFlow () [override], [default]
Destructor.
Referenced by LatticeBackendFlow().
Member Function Documentation
CheckSynthesisResults()
void LatticeBackendFlow::CheckSynthesisResults () [override], [private], [virtual]
Checks the synthesis results and fills the corresponding datastructures.
Implements BackendFlow.
Definition at line 189 of file LatticeBackendFlow.cpp.
References BackendFlow::actual_parameters, BackendFlow::area_m, clb_model::BRAM, LUT_model::COMBINATIONAL_DELAY, area_model::create_model(), time_model::create_model(), design_values, clb_model::DSP, FPGA, LATTICE_DELAY, LATTICE_DSP, LATTICE_MEM, LATTICE_REGISTERS, LATTICE_SLICE, clb_model::LUT_FF_PAIRS, BackendFlow::output_level, OUTPUT_LEVEL_MINIMUM, BackendFlow::Param, PARAM_lattice_report, DesignParameters::parameter_values, PRINT_OUT_MEX, clb_model::REGISTERS, THROW_ASSERT, BackendFlow::time_m, and xparse_utilization().
create_sdc()
void LatticeBackendFlow::create_sdc (const DesignParametersRef dp) [private]
Creates the constraint file.
Definition at line 227 of file LatticeBackendFlow.cpp.
References DesignParameters::component_name, BackendFlow::out_dir, BackendFlow::Param, PARAM_clk_name, PARAM_clk_period, PARAM_connect_iob, PARAM_is_combinational, PARAM_sdc_file, and DesignParameters::parameter_values.
Referenced by InitDesignParameters().
ExecuteSynthesis()
void LatticeBackendFlow::ExecuteSynthesis () [override], [virtual]
Checks if the execution can be performed and, in case, performs the synthesis.
Reimplemented from BackendFlow.
Definition at line 293 of file LatticeBackendFlow.cpp.
References BackendFlow::ExecuteSynthesis(), and THROW_ERROR.
InitDesignParameters()
void LatticeBackendFlow::InitDesignParameters () [override], [virtual]
Initializes the parameters.
Reimplemented from BackendFlow.
Definition at line 248 of file LatticeBackendFlow.cpp.
References BackendFlow::actual_parameters, create_sdc(), target_device::get_parameter(), GetExtension(), BackendFlow::Param, PARAM_HDL_files, PARAM_sources_macro_list, PARAM_target_device, PARAM_target_family, DesignParameters::parameter_values, BackendFlow::steps, BackendFlow::target, and THROW_ERROR.
WriteFlowConfiguration()
void LatticeBackendFlow::WriteFlowConfiguration (std::ostream & script) [override], [private], [virtual]
Writes the proper flow configuration in the output script.
Implements BackendFlow.
Definition at line 213 of file LatticeBackendFlow.cpp.
References STR.
xparse_utilization()
void LatticeBackendFlow::xparse_utilization (const std::string & fn) [private]
Parses device utilization.
Definition at line 109 of file LatticeBackendFlow.cpp.
References CE_XVM, design_values, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), LOAD_XVM, test_panda::parser, THROW_ASSERT, and THROW_ERROR.
Referenced by CheckSynthesisResults().
Field Documentation
design_values
std::map<std::string, double> LatticeBackendFlow::design_values [private]
design values reported by the tools
Definition at line 53 of file LatticeBackendFlow.hpp.
Referenced by CheckSynthesisResults(), and xparse_utilization().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/lattice/LatticeBackendFlow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/lattice/LatticeBackendFlow.cpp