HLSIR Class Reference
#include <hls_ir.hpp>
Public Member Functions
HLSIR (const HLS_managerRef &hls_manager, const ParameterConstRef &parameters)
Constructor.
~HLSIR () override
Destructor.
void Initialize () override=0
Initialize all the data structure.
void Clear () override=0
Clear all the data structure.
Protected Attributes
const HLS_managerRef hls_manager
The HLS manager.
Detailed Description
Definition at line 51 of file hls_ir.hpp.
Constructor & Destructor Documentation
HLSIR()
HLSIR::HLSIR (const HLS_managerRef & hls_manager, const ParameterConstRef & parameters)
Constructor.
Header include.
Parameters
hls_manager is the HLS manager
parameters is the set of input parameters
Definition at line 43 of file hls_ir.cpp.
References ~HLSIR().
 HLSIR()
HLSIR::~HLSIR () [override], [default]
Destructor.
Referenced by HLSIR().
Member Function Documentation
Clear()
void HLSIR::Clear () [override], [pure virtual]
Clear all the data structure.
Implements IntermediateRepresentation.
Implemented in AllocationInformation.
Definition at line 54 of file hls_ir.cpp.
References IntermediateRepresentation::Clear().
Referenced by AllocationInformation::Clear().
Initialize()
void HLSIR::Initialize () [override], [pure virtual]
Initialize all the data structure.
Implements IntermediateRepresentation.
Implemented in AllocationInformation.
Definition at line 49 of file hls_ir.cpp.
References IntermediateRepresentation::Initialize().
Referenced by AllocationInformation::Initialize().
Field Documentation
hls_manager
const HLS_managerRef HLSIR::hls_manager [protected]
The HLS manager.
Definition at line 55 of file hls_ir.hpp.
Referenced by AllocationInformation::GetNodeTypePrec(), AllocationInformation::InitializeDSPDB(), and AllocationInformation::InitializeMuxDB().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/hls/hls_ir.hpp
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/hls/hls_ir.cpp