address_var_pp_functor Struct Reference
Address version functor that returns the name of a variable with `&` in front.
#include <var_pp_functor.hpp>
Public Member Functions
address_var_pp_functor (const BehavioralHelperConstRef _BH, const CustomSet< unsigned int > vars, const CustomSet< unsigned int > pointer_vars)
Constructor.
~address_var_pp_functor () override=default
Destructor.
std::string operator() (unsigned int var) const override
return the name of the variable with a star as a prefix.
Private Attributes
const CustomSet< unsigned int > addr_based_variables
reference to the set of variable that has to have a star in front when returned by operator()
const CustomSet< unsigned int > pointer_based_variables
reference to the set of variable that has to have a star in front when returned by operator()
const BehavioralHelperConstRef BH
behavioral helper
Detailed Description
Address version functor that returns the name of a variable with `&` in front.
Definition at line 146 of file var_pp_functor.hpp.
Constructor & Destructor Documentation
address_var_pp_functor()
address_var_pp_functor::address_var_pp_functor (const BehavioralHelperConstRef _BH, const CustomSet< unsigned int > vars, const CustomSet< unsigned int > pointer_vars)
Constructor.
Parameters
BH is the behavioral helper.
vars is the reference to the set of variables for which a star should be returned along with their name.
Definition at line 192 of file var_pp_functor.cpp.
 address_var_pp_functor()
address_var_pp_functor::~address_var_pp_functor () [override], [default]
Destructor.
Member Function Documentation
operator()()
std::string address_var_pp_functor::operator() (unsigned int var) const [override], [virtual]
return the name of the variable with a star as a prefix.
Parameters
var is the nodeid of the variable.
pointer_based_variables are the I/O parameters of the function addr_based_variables are the I/O parameters of the called task
Implements var_pp_functor.
Definition at line 196 of file var_pp_functor.cpp.
References addr_based_variables, BH, BehavioralHelper::is_an_array(), pointer_based_variables, and BehavioralHelper::PrintVariable().
Referenced by isolated_var_pp_functor::operator()().
Field Documentation
addr_based_variables
const CustomSet<unsigned int> address_var_pp_functor::addr_based_variables [private]
reference to the set of variable that has to have a star in front when returned by operator()
Definition at line 167 of file var_pp_functor.hpp.
Referenced by operator()().
BH
const BehavioralHelperConstRef address_var_pp_functor::BH [private]
behavioral helper
Definition at line 173 of file var_pp_functor.hpp.
Referenced by operator()(), and isolated_var_pp_functor::operator()().
pointer_based_variables
const CustomSet<unsigned int> address_var_pp_functor::pointer_based_variables [private]
reference to the set of variable that has to have a star in front when returned by operator()
Definition at line 170 of file var_pp_functor.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.cpp