xml_foreach_t Class Reference
Foreach block, where the set of script nodes is applied to each parameter.
#include <xml_script_command.hpp>
Public Member Functions
xml_foreach_t (std::string _variable)
xml_foreach_t (const xml_element *element)
std::string get_xml_name () const override
Gets the XML element name of this node type.
xml_nodeRef create_xml_node () const override
Creates an XML node for polixml data structures.
~xml_foreach_t () override
void clean () override
Cleans object attributes.
Data Fields
std::string variable
std::vector< xml_script_node_tRef > Nodes
Additional Inherited Members
Detailed Description
Foreach block, where the set of script nodes is applied to each parameter.
Definition at line 304 of file xml_script_command.hpp.
Constructor & Destructor Documentation
xml_foreach_t() [1/2]
xml_foreach_t::xml_foreach_t (std::string _variable) [explicit]
Definition at line 841 of file xml_script_command.cpp.
xml_foreach_t() [2/2]
xml_foreach_t::xml_foreach_t (const xml_element * element) [explicit]
Definition at line 845 of file xml_script_command.cpp.
References xml_script_node_t::create(), el, attribute_sequence::get_attribute(), xml_child::get_children(), xml_attribute::get_value(), Nodes, THROW_ASSERT, and variable.
 xml_foreach_t()
xml_foreach_t::~xml_foreach_t () [override]
Definition at line 877 of file xml_script_command.cpp.
References clean().
Member Function Documentation
clean()
void xml_foreach_t::clean () [override], [virtual]
Cleans object attributes.
Implements xml_script_node_t.
Definition at line 882 of file xml_script_command.cpp.
References Nodes.
Referenced by ~xml_foreach_t().
create_xml_node()
xml_nodeRef xml_foreach_t::create_xml_node () const [override], [virtual]
Creates an XML node for polixml data structures.
Implements xml_script_node_t.
Definition at line 892 of file xml_script_command.cpp.
References get_xml_name(), and NOT_YET_IMPLEMENTED.
get_xml_name()
std::string xml_foreach_t::get_xml_name () const [override], [virtual]
Gets the XML element name of this node type.
Implements xml_script_node_t.
Definition at line 887 of file xml_script_command.cpp.
References TAG_FOREACH.
Referenced by create_xml_node().
Field Documentation
Nodes
std::vector<xml_script_node_tRef> xml_foreach_t::Nodes
Definition at line 308 of file xml_script_command.hpp.
Referenced by clean(), and xml_foreach_t().
variable
std::string xml_foreach_t::variable
Definition at line 307 of file xml_script_command.hpp.
Referenced by xml_foreach_t().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xml_script_command.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xml_script_command.cpp