gimple_predict Struct Reference
This struct specifies a hint for branch prediction.
#include <tree_node.hpp>
Public Types
enum { GETID =(gimple_node) = 0
 }
visitor enum
Public Member Functions
gimple_predict (unsigned int index)
Constructor.
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Additional Inherited Members
Detailed Description
This struct specifies a hint for branch prediction.
PREDICT is one of the predictors from predict.def. OUTCOME is NOT_TAKEN or TAKEN.
Definition at line 3829 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 3847 of file tree_node.hpp.
Constructor & Destructor Documentation
gimple_predict()
gimple_predict::gimple_predict (unsigned int index) [explicit]
Constructor.
Definition at line 1020 of file tree_node.cpp.
Member Function Documentation
visit()
void gimple_predict::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from gimple_node.
Definition at line 1024 of file tree_node.cpp.
References ALL_VISIT, and VISIT_SC.
Referenced by pointer_type::visit(), real_cst::visit(), real_type::visit(), record_type::visit(), reference_type::visit(), result_decl::visit(), gimple_resx::visit(), gimple_return::visit(), return_stmt::visit(), and scope_ref::visit().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp