technology_node Struct Reference
Abstract pure class for the technology structure.
#include <technology_node.hpp>
Public Member Functions
technology_node ()
Constructor.
virtual ~technology_node ()
Destructor.
virtual const std::string & get_name () const =0
Return the name of the technology node.
virtual void xload (const xml_element *Enode, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device)=0
Load a technology_node starting from an xml file.
virtual void xwrite (xml_element *rootnode, const technology_nodeRef tn, const ParameterConstRef Param, TargetDevice_Type type)=0
Add a technology_node to an xml tree.
virtual void lib_write (std::ofstream &os, const simple_indentRef PP)=0
Append a technology_node to a liberty file.
virtual void lef_write (std::ofstream &os, const simple_indentRef PP)=0
Append a technology_node to a LEF file.
virtual void print (std::ostream &os) const =0
Virtual function that prints the class.
virtual std::string get_kind_text () const =0
Virtual function used to get the string name of a technology_node instance.
virtual enum tec_kind get_kind () const =0
Virtual function used to find the real type of a technology_nodeinstance.
Static Protected Attributes
static simple_indent PP
pretty print functor object used by all print members to indent the output of the print function.
Friends
std::ostream & operator<< (std::ostream &os, const technology_nodeRef &s)
Friend definition of the << operator.
Detailed Description
Abstract pure class for the technology structure.
This node and in particular its refCount type will be used to describe all nodes used to build a technology description.
Definition at line 285 of file technology_node.hpp.
Constructor & Destructor Documentation
technology_node()
technology_node::technology_node () [default]
Constructor.
 technology_node()
technology_node::~technology_node () [virtual], [default]
Destructor.
Member Function Documentation
get_kind()
virtual enum tec_kind technology_node::get_kind () const [pure virtual]
Virtual function used to find the real type of a technology_nodeinstance.
Returns
a tec_kind enum identifying the object type.
Referenced by HDL_manager::get_post_order_structural_components(), structural_object::GetParameters(), and HDL_manager::write_module().
get_kind_text()
virtual std::string technology_node::get_kind_text () const [pure virtual]
Virtual function used to get the string name of a technology_node instance.
Returns
a string identifying the object type.
Referenced by operation::xwrite().
get_name()
virtual const std::string& technology_node::get_name () const [pure virtual]
Return the name of the technology node.
Implemented in storage_unit, functional_unit_template, functional_unit, and operation.
Referenced by library_manager::add(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), allocation::add_tech_constraint(), FunctionalUnitStep::AnalyzeFu(), functional_unit_template::get_name(), allocation::IntegrateTechnologyLibraries(), allocation::InternalExec(), library_manager::update(), library_manager::xload(), and operation::xload().
lef_write()
virtual void technology_node::lef_write (std::ofstream & os, const simple_indentRef PP) [pure virtual]
Append a technology_node to a LEF file.
Implemented in storage_unit, functional_unit_template, functional_unit, and operation.
Referenced by operation::get_name(), functional_unit::get_name(), and functional_unit_template::get_name().
lib_write()
virtual void technology_node::lib_write (std::ofstream & os, const simple_indentRef PP) [pure virtual]
Append a technology_node to a liberty file.
Implemented in storage_unit, functional_unit_template, functional_unit, and operation.
Referenced by operation::get_name(), functional_unit::get_name(), and functional_unit_template::get_name().
print()
virtual void technology_node::print (std::ostream & os) const [pure virtual]
Virtual function that prints the class.
Parameters
os is the output stream
Implemented in storage_unit, functional_unit_template, functional_unit, and operation.
Referenced by functional_unit::get_name(), functional_unit_template::get_name(), operation::is_primary_inputs_registered(), and functional_unit_template::print().
xload()
virtual void technology_node::xload (const xml_element * Enode, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) [pure virtual]
Load a technology_node starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
TM is the technology manager.
Implemented in storage_unit, functional_unit_template, functional_unit, and operation.
Referenced by operation::get_name(), functional_unit::get_name(), functional_unit_template::get_name(), library_manager::xload(), and functional_unit_template::xload().
xwrite()
virtual void technology_node::xwrite (xml_element * rootnode, const technology_nodeRef tn, const ParameterConstRef Param, TargetDevice_Type type) [pure virtual]
Add a technology_node to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the technology node is attached.
Implemented in storage_unit, functional_unit_template, functional_unit, and operation.
Referenced by operation::get_name(), functional_unit::get_name(), functional_unit_template::get_name(), and functional_unit_template::xwrite().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const technology_nodeRef & s) [friend]
Friend definition of the << operator.
Pointer version.
Definition at line 349 of file technology_node.hpp.
Field Documentation
PP
simple_indent technology_node::PP [static], [protected]
pretty print functor object used by all print members to indent the output of the print function.
Autoheader include.
STL include utility include
Definition at line 358 of file technology_node.hpp.
Referenced by operation::get_name(), functional_unit::get_name(), functional_unit_template::get_name(), and functional_unit::print().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.cpp