DataXmlParser Class Reference
This class collects information about generic data.
#include <data_xml_parser.hpp>
Public Member Functions
DataXmlParser (const ParameterConstRef &parameters)
Constructor.
~DataXmlParser ()
Destructor.
void Parse (const CustomSet< std::string > &file_names, std::map< std::string, CustomMap< std::string, std::string >> &output) const
Parse xml file.
Private Attributes
const ParameterConstRef parameters
The set of input paraemeters.
const int debug_level
The debug level.
Detailed Description
This class collects information about generic data.
Definition at line 58 of file data_xml_parser.hpp.
Constructor & Destructor Documentation
DataXmlParser()
DataXmlParser::DataXmlParser (const ParameterConstRef & Param) [explicit]
Constructor.
Header include.
Parameters
parameters is the set of input parameters
Parameter include Constants includes Utility include XML include
Definition at line 63 of file data_xml_parser.cpp.
References ~DataXmlParser().
 DataXmlParser()
DataXmlParser::~DataXmlParser () [default]
Destructor.
Referenced by DataXmlParser().
Member Function Documentation
Parse()
void DataXmlParser::Parse (const CustomSet< std::string > & file_names, std::map< std::string, CustomMap< std::string, std::string >> & output) const
Parse xml file.
Parameters
file_names is the input file
output is where data will be saved: first key is the benchmark name (sorted by name thanks to map), second key is the characteristic, value is the actual value
Definition at line 69 of file data_xml_parser.cpp.
References test_panda::benchmark_name, CE_XVM, XMLDomParser::Exec(), attribute_sequence::get_attribute(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), xml_attribute::get_value(), test_panda::parser, STR_XML_data_xml_benchmark_name, STR_XML_data_xml_value, STR_XML_experimental_setup_root, STR_XML_latex_table_root, and THROW_ERROR.
Field Documentation
debug_level
const int DataXmlParser::debug_level [private]
The debug level.
Definition at line 65 of file data_xml_parser.hpp.
parameters
const ParameterConstRef DataXmlParser::parameters [private]
The set of input paraemeters.
Definition at line 62 of file data_xml_parser.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/data_xml/data_xml_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/data_xml/data_xml_parser.cpp