XilinxWrapper Class Reference
#include <XilinxWrapper.hpp>
Public Member Functions
XilinxWrapper (const ParameterConstRef &Param, const std::string &tool_exec, const target_deviceRef &device, const std::string &out_dir, const std::string &default_out_dir)
Constructor.
~XilinxWrapper () override
Destructor.
void generate_synthesis_script (const DesignParametersRef &dp, const std::string &file_name) override
Creates the proper configuration script.
std::string toString (const xml_script_node_tRef node, const DesignParametersRef dp) const override
Returns the string-based representation of the XML element.
std::string getStringValue (const xml_script_node_tRef node, const DesignParametersRef &dp) const override
Returns the string-based representation of the XML element.
Additional Inherited Members
Detailed Description
Definition at line 77 of file XilinxWrapper.hpp.
Constructor & Destructor Documentation
XilinxWrapper()
XilinxWrapper::XilinxWrapper (const ParameterConstRef & Param, const std::string & tool_exec, const target_deviceRef & device, const std::string & out_dir, const std::string & default_out_dir)
Constructor.
Header include.
Parameters
Param is the set of parameters
tool_exec is the name of the executable
out_dir is the directory where to save all the results
default_out_dir is the default output directory
Definition at line 60 of file XilinxWrapper.cpp.
References ~XilinxWrapper().
 XilinxWrapper()
XilinxWrapper::~XilinxWrapper () [override], [default]
Destructor.
Referenced by XilinxWrapper().
Member Function Documentation
generate_synthesis_script()
void XilinxWrapper::generate_synthesis_script (const DesignParametersRef & dp, const std::string & file_name) [override], [virtual]
Creates the proper configuration script.
replace some of the escape sequences
Implements SynthesisTool.
Definition at line 67 of file XilinxWrapper.cpp.
References DesignParameters::assign(), SynthesisTool::generate_bare_script(), getStringValue(), DesignParameters::parameter_values, remove_escaped(), SynthesisTool::replace_parameters(), SCRIPT_FILENAME, SynthesisTool::script_name, SynthesisTool::xml_reserved_vars, and SynthesisTool::xml_script_nodes.
getStringValue()
std::string XilinxWrapper::getStringValue (const xml_script_node_tRef node, const DesignParametersRef & dp) const [override], [virtual]
Returns the string-based representation of the XML element.
Implements SynthesisTool.
Definition at line 104 of file XilinxWrapper.cpp.
References xml_set_variable_t::multiValues, NODE_COMMAND, NODE_ENTRY, NODE_FOREACH, NODE_ITE_BLOCK, NODE_PARAMETER, NODE_SHELL, NODE_UNKNOWN, NODE_VARIABLE, result, xml_set_variable_t::singleValue, STR, THROW_ERROR, and toString().
Referenced by generate_synthesis_script(), and toString().
toString()
std::string XilinxWrapper::toString (const xml_script_node_tRef node, const DesignParametersRef dp) const [override], [virtual]
Returns the string-based representation of the XML element.
Implements SynthesisTool.
Definition at line 149 of file XilinxWrapper.cpp.
References xml_parameter_t::condition, xml_script_node_t::evaluate_condition(), getStringValue(), xml_parameter_t::multiValues, xml_set_variable_t::name, xml_parameter_t::name, xml_command_t::name, NODE_COMMAND, NODE_ENTRY, NODE_FOREACH, NODE_ITE_BLOCK, NODE_PARAMETER, NODE_SHELL, NODE_UNKNOWN, NODE_VARIABLE, NOT_YET_IMPLEMENTED, xml_command_t::output, xml_command_t::parameters, result, xml_parameter_t::separator, xml_parameter_t::singleValue, STR, THROW_ERROR, and xml_set_entry_t::value.
Referenced by vivado_flow_wrapper::get_command_line(), ngdbuild_wrapper::get_command_line(), par_wrapper::get_command_line(), map_wrapper::get_command_line(), trce_wrapper::get_command_line(), xst_wrapper::get_command_line(), and getStringValue().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/XilinxWrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/XilinxWrapper.cpp