LoadBuiltinTechnology Class Reference
Technology steps which loads builtin components.
#include <load_builtin_technology.hpp>
Public Member Functions
LoadBuiltinTechnology (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~LoadBuiltinTechnology () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Technology steps which loads builtin components.
Definition at line 55 of file load_builtin_technology.hpp.
Constructor & Destructor Documentation
LoadBuiltinTechnology()
LoadBuiltinTechnology::LoadBuiltinTechnology (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
TM is the technology manager
target is the target device
design_flow_manager is the design flow manager
parameters is the set of input parameters
Header include circuit include parser/polixml include polixml include technology includes utility include
Definition at line 65 of file load_builtin_technology.cpp.
References ~LoadBuiltinTechnology().
 LoadBuiltinTechnology()
LoadBuiltinTechnology::~LoadBuiltinTechnology () [override], [default]
Destructor.
Referenced by LoadBuiltinTechnology().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > LoadBuiltinTechnology::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 72 of file load_builtin_technology.cpp.
Exec()
DesignFlowStep_Status LoadBuiltinTechnology::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 77 of file load_builtin_technology.cpp.
References structural_manager::add_NP_functionality(), structural_manager::add_port(), structural_manager::add_port_vector(), AND_GATE_STD, BUFF_GATE_STD, DFF_GATE_STD, NP_functionality::EQUATION, FPGA_LIBRARY, structural_manager::get_circ(), IBUF_GATE_STD, port_o::IN, NP_functionality::LIBRARY, LIBRARY_STD, LUT_GATE_STD, NAND_GATE_STD, NOR_GATE_STD, NOT_GATE_STD, OBUF_GATE_STD, OR_GATE_STD, port_o::OUT, DesignFlowStep::parameters, port_o::PARAMETRIC_PORT, structural_manager::set_top_info(), SUCCESS, TechnologyFlowStep::TM, top(), XNOR_GATE_STD, and XOR_GATE_STD.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_builtin_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_builtin_technology.cpp