ExtractOmpFor Class Reference
Superclass include.
#include <extract_omp_for.hpp>
Public Member Functions
ExtractOmpFor (const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~ExtractOmpFor ()
Destructor.
DesignFlowStep_Status InternalExec ()
Restructures the unstructured code.
virtual void Initialize ()
Initialize the step (i.e., like a constructor, but executed just before exec.
virtual bool HasToBeExecuted () const
Check if this step has actually to be executed.
Protected Member Functions
virtual const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Extract openmp for in a separate function
Definition at line 51 of file extract_omp_for.hpp.
Constructor & Destructor Documentation
ExtractOmpFor()
ExtractOmpFor::ExtractOmpFor (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Param is the set of the parameters
. include algorithms/loops_detection includes behavior include design_flows include STL include tree includes utility _Nonnull
Definition at line 76 of file extract_omp_for.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and DesignFlowStep::parameters.
 ExtractOmpFor()
ExtractOmpFor::~ExtractOmpFor ()
Destructor.
Definition at line 82 of file extract_omp_for.cpp.
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > ExtractOmpFor::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 86 of file extract_omp_for.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
HasToBeExecuted()
bool ExtractOmpFor::HasToBeExecuted () const [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 117 of file extract_omp_for.cpp.
References FunctionFrontendFlowStep::bb_version.
Initialize()
void ExtractOmpFor::Initialize () [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 113 of file extract_omp_for.cpp.
InternalExec()
DesignFlowStep_Status ExtractOmpFor::InternalExec () [virtual]
Restructures the unstructured code.
Implements FunctionFrontendFlowStep.
Definition at line 122 of file extract_omp_for.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DOALL_LOOP, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, FunctionFrontendFlowStep::GetName(), INDENT_DBG_MEX, DesignFlowStep::parameters, FrontendFlowStep::PrintTreeManager(), STR, SUCCESS, THROW_ASSERT, THROW_ERROR, UNCHANGED, and FunctionFrontendFlowStep::WriteBBGraphDot().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/extract_omp_for.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/extract_omp_for.cpp