nxpython_flow_wrapper Class Reference
Main class for wrapping nxpython_flow tool by NANOXPLORE.
#include <nxpython_flow_wrapper.hpp>
Public Member Functions
nxpython_flow_wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~nxpython_flow_wrapper () override
Destructor.
Protected Member Functions
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Additional Inherited Members
Detailed Description
Main class for wrapping nxpython_flow tool by NANOXPLORE.
Definition at line 54 of file nxpython_flow_wrapper.hpp.
Constructor & Destructor Documentation
nxpython_flow_wrapper()
nxpython_flow_wrapper::nxpython_flow_wrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Parameters
Param is the set of parameters
Definition at line 57 of file nxpython_flow_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, and ~nxpython_flow_wrapper().
 nxpython_flow_wrapper()
nxpython_flow_wrapper::~nxpython_flow_wrapper () [override], [default]
Destructor.
Referenced by nxpython_flow_wrapper().
Member Function Documentation
EvaluateVariables()
void nxpython_flow_wrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 65 of file nxpython_flow_wrapper.cpp.
References DesignParameters::assign(), DesignParameters::component_name, SynthesisTool::output_dir, PARAM_nxpython_outdir, PARAM_nxpython_report, PARAM_nxpython_timing_report, and DesignParameters::parameter_values.
get_command_line()
std::string nxpython_flow_wrapper::get_command_line (const DesignParametersRef & dp) const [override], [protected], [virtual]
Returns the proper command line.
Implements NanoXploreWrapper.
Definition at line 73 of file nxpython_flow_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, NanoXploreWrapper::toString(), and SynthesisTool::xml_tool_options.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/nanoxplore/nxpython_flow_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/nanoxplore/nxpython_flow_wrapper.cpp