ControlFlowChecker Class Reference
#include <control_flow_checker.hpp>
Public Member Functions
ControlFlowChecker (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
virtual ~ControlFlowChecker ()
Destructor.
virtual DesignFlowStep_Status InternalExec ()
Execute the step.
Protected Member Functions
virtual const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
void add_clock_reset (structural_objectRef circuit)
void add_done_port (structural_objectRef circuit)
void add_start_port (structural_objectRef circuit)
void add_present_state (structural_objectRef circuit, unsigned int state_bitsize)
void add_notifiers (structural_objectRef circuit)
void add_common_ports (structural_objectRef circuit, unsigned int state_bitsize)
Additional Inherited Members
Detailed Description
Definition at line 53 of file control_flow_checker.hpp.
Constructor & Destructor Documentation
ControlFlowChecker()
ControlFlowChecker::ControlFlowChecker (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Author
Pietro Fezzardi pietrofezzardi@gmail.comSTD include
Definition at line 75 of file control_flow_checker.cpp.
References CONTROL_FLOW_CHECKER, DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 ControlFlowChecker()
ControlFlowChecker::~ControlFlowChecker () [virtual]
Destructor.
Definition at line 81 of file control_flow_checker.cpp.
Member Function Documentation
add_clock_reset()
void ControlFlowChecker::add_clock_reset (structural_objectRef circuit) [protected]
define boolean type for the clock and reset signals
add clock port
add entry in in_port_map between port id and port index
add reset port
Definition at line 590 of file control_flow_checker.cpp.
References structural_manager::add_port(), CLOCK_PORT_NAME, hls::control_flow_checker, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, HLSFunctionStep::HLS, port_o::IN, PRINT_DBG_MEX, and RESET_PORT_NAME.
Referenced by add_common_ports().
add_common_ports()
void ControlFlowChecker::add_common_ports (structural_objectRef circuit, unsigned int state_bitsize) [protected]
Definition at line 658 of file control_flow_checker.cpp.
References add_clock_reset(), add_done_port(), add_notifiers(), add_present_state(), add_start_port(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, and PRINT_DBG_MEX.
Referenced by InternalExec().
add_done_port()
void ControlFlowChecker::add_done_port (structural_objectRef circuit) [protected]
define boolean type for the done port
add done port
Definition at line 609 of file control_flow_checker.cpp.
References structural_manager::add_port(), hls::control_flow_checker, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, HLSFunctionStep::HLS, port_o::IN, and PRINT_DBG_MEX.
Referenced by add_common_ports().
add_notifiers()
void ControlFlowChecker::add_notifiers (structural_objectRef circuit) [protected]
define boolean type for the start port
add the notifiers
Definition at line 643 of file control_flow_checker.cpp.
References structural_manager::add_port(), hls::control_flow_checker, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, HLSFunctionStep::HLS, NOTIFIER_PORT_MISMATCH, NOTIFIER_PORT_MISMATCH_ID, NOTIFIER_PORT_MISMATCH_OFFSET, port_o::OUT, and PRINT_DBG_MEX.
Referenced by add_common_ports().
add_present_state()
void ControlFlowChecker::add_present_state (structural_objectRef circuit, unsigned int state_bitsize) [protected]
define boolean type for the start port
add the present/next state
Definition at line 631 of file control_flow_checker.cpp.
References structural_manager::add_port(), hls::control_flow_checker, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, HLSFunctionStep::HLS, port_o::IN, NEXT_STATE_PORT_NAME, PRESENT_STATE_PORT_NAME, and PRINT_DBG_MEX.
Referenced by add_common_ports().
add_start_port()
void ControlFlowChecker::add_start_port (structural_objectRef circuit) [protected]
define boolean type for the start port
add the start port
Definition at line 620 of file control_flow_checker.cpp.
References structural_manager::add_port(), hls::control_flow_checker, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, HLSFunctionStep::HLS, port_o::IN, PRINT_DBG_MEX, and START_PORT_NAME.
Referenced by add_common_ports().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ControlFlowChecker::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 85 of file control_flow_checker.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status ControlFlowChecker::InternalExec () [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 676 of file control_flow_checker.cpp.
References add_common_ports(), add_escape(), structural_manager::add_NP_functionality(), FunctionBehavior::CGetBehavioralHelper(), StateTransitionGraphManager::CGetStg(), comp_state_bitsize(), hls::control_flow_checker, create_control_flow_checker(), DesignFlowStep::debug_level, HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_name(), HLSFunctionStep::HLS, is_one_hot(), NP_functionality::LIBRARY, max(), hls::Param, structural_manager::set_top_info(), hls::STG, STR, SUCCESS, and NP_functionality::VERILOG_PROVIDED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/control_flow_checker.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/control_flow_checker.cpp