CheckSystemType Class Reference
Class which system_flag to tree_node of variables and types when necessary.
#include <check_system_type.hpp>
Public Member Functions
CheckSystemType (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~CheckSystemType () override
Destructor.
DesignFlowStep_Status InternalExec () override
Adds the system_flag to the tree_node's of variables and types when necessary.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
void recursive_examinate (const tree_nodeRef &tn)
Examinate recursively the tree to detect system types and system variables.
void recursive_examinate (const tree_nodeRef &curr_tn, const unsigned int index)
Examinate recursively the tree to detect system types and system variables.
bool is_system_include (std::string include) const
Check if an header is a system header.
void build_include_structures ()
Build the include map, the function rename map and library system sets.
void getRealInclName (const std::string &include, std::string &real_name) const
Given the string stored in a srcp of the raw return the correct include name.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const BehavioralHelperConstRef behavioral_helper
The helper associated with the current function.
const tree_managerRef TM
The tree manager.
CustomUnorderedSet< unsigned int > already_visited
Already visited tree node (used to avoid infinite recursion)
bool already_executed
Already executed.
Static Private Attributes
static std::vector< std::string > systemIncPath
Contains the list of the folders containining the system header files.
static CustomUnorderedMapUnstable< std::string, std::string > inclNameToPath
Associates to each system header file its full path.
static CustomUnorderedMapUnstable< std::string, std::string > rename_function
Associates a function to its original name.
static CustomUnorderedMapUnstable< std::string, std::string > rename_types
Associates a type to its original name.
static CustomUnorderedSet< std::string > library_system_functions
The set of functions which have to be considered library_system.
static CustomUnorderedSet< std::string > library_system_includes
The set of headers which contains function which have to be considered library_system.
static CustomUnorderedMapUnstable< std::string, std::string > undefined_library_function_include
Map undefined library function to corresponding header.
Additional Inherited Members
Detailed Description
Class which system_flag to tree_node of variables and types when necessary.
Definition at line 68 of file check_system_type.hpp.
Constructor & Destructor Documentation
CheckSystemType()
CheckSystemType::CheckSystemType (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the index of the function
design_flow_manager is the design flow manager
Definition at line 98 of file check_system_type.cpp.
References build_include_structures(), DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, inclNameToPath, DesignFlowStep::parameters, and ~CheckSystemType().
 CheckSystemType()
CheckSystemType::~CheckSystemType () [override], [default]
Destructor.
Referenced by CheckSystemType().
Member Function Documentation
build_include_structures()
void CheckSystemType::build_include_structures () [private]
Build the include map, the function rename map and library system sets.
libbambu/libm
libbambu/soft-fp
replace z:/mingw at the beginning of the string
Building the rename function map
Building the rename type map
Building library system function
Definition at line 809 of file check_system_type.cpp.
References CT_NO_GCC, FILENAME_NORM, inclNameToPath, library_system_functions, library_system_includes, O0, DesignFlowStep::parameters, rename_function, rename_types, systemIncPath, and undefined_library_function_include.
Referenced by CheckSystemType().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > CheckSystemType::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 108 of file check_system_type.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
getRealInclName()
void CheckSystemType::getRealInclName (const std::string & include, std::string & real_name) const [private]
Given the string stored in a srcp of the raw return the correct include name.
Parameters
include is the string of srcp to be checked
real_name is the string fixed
Definition at line 927 of file check_system_type.cpp.
References FILENAME_NORM, inclNameToPath, and systemIncPath.
Referenced by recursive_examinate().
HasToBeExecuted()
bool CheckSystemType::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 953 of file check_system_type.cpp.
References already_executed.
InternalExec()
DesignFlowStep_Status CheckSystemType::InternalExec () [override], [virtual]
Adds the system_flag to the tree_node's of variables and types when necessary.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 134 of file check_system_type.cpp.
References already_executed, FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeNode(), recursive_examinate(), sl, SUCCESS, and TM.
is_system_include()
bool CheckSystemType::is_system_include (std::string include) const [private]
Check if an header is a system header.
Parameters
include is the header file
Definition at line 792 of file check_system_type.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FILENAME_NORM, INDENT_DBG_MEX, and systemIncPath.
Referenced by recursive_examinate().
recursive_examinate() [1/2]
void CheckSystemType::recursive_examinate (const tree_nodeRef & tn) [private]
Examinate recursively the tree to detect system types and system variables.
Parameters
tn is the root of the subtree to be examinated; it must be a tree_reindex
Definition at line 164 of file check_system_type.cpp.
References GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, and THROW_ASSERT.
Referenced by InternalExec(), and recursive_examinate().
recursive_examinate() [2/2]
void CheckSystemType::recursive_examinate (const tree_nodeRef & curr_tn, const unsigned int index) [private]
Examinate recursively the tree to detect system types and system variables.
Parameters
curr_tn is the root of the subtree to be examinated; it must not be a tree_reindex
index is the index of the tree_node
Definition at line 170 of file check_system_type.cpp.
References already_visited, test_panda::arg, test_panda::args, call_expr::args, gimple_call::args, target_mem_ref::base, target_mem_ref461::base, behavioral_helper, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, method_type::clas, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, array_type::elts, vector_type::elts, call_expr::fn, gimple_call::fn, GET_CONST_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, getRealInclName(), target_mem_ref::idx, target_mem_ref461::idx, target_mem_ref461::idx2, INDENT_DBG_MEX, is_system_include(), library_system_functions, library_system_includes, constructor::list_of_idx_valu, NODE_NOT_YET_SUPPORTED_EC, unary_expr::op, cast_expr::op, gimple_goto::op, gimple_return::op, gimple_while::op0, binary_expr::op0, ternary_expr::op0, quaternary_expr::op0, gimple_cond::op0, gimple_assign::op0, gimple_switch::op0, gimple_for::op1, binary_expr::op1, ternary_expr::op1, quaternary_expr::op1, gimple_assign::op1, gimple_for::op2, ternary_expr::op2, quaternary_expr::op2, quaternary_expr::op3, DesignFlowStep::parameters, gimple_assign::predicate, PRINT_DBG_MEX, tree_helper::print_function_name(), function_type::prms, pointer_type::ptd, recursive_examinate(), reference_type::refd, rename_function, rename_types, function_type::retn, STR, target_mem_ref::symbol, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, TM, expr_node::type, constructor::type, ssa_name::type, typename_type(), undefined_library_function_include, and ssa_name::var.
Field Documentation
already_executed
bool CheckSystemType::already_executed [private]
Already executed.
Definition at line 107 of file check_system_type.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
already_visited
CustomUnorderedSet<unsigned int> CheckSystemType::already_visited [private]
Already visited tree node (used to avoid infinite recursion)
Definition at line 78 of file check_system_type.hpp.
Referenced by recursive_examinate().
behavioral_helper
const BehavioralHelperConstRef CheckSystemType::behavioral_helper [private]
The helper associated with the current function.
Definition at line 72 of file check_system_type.hpp.
Referenced by recursive_examinate().
inclNameToPath
CustomUnorderedMapUnstable< std::string, std::string > CheckSystemType::inclNameToPath [static], [private]
Associates to each system header file its full path.
Definition at line 84 of file check_system_type.hpp.
Referenced by build_include_structures(), CheckSystemType(), and getRealInclName().
library_system_functions
CustomUnorderedSet< std::string > CheckSystemType::library_system_functions [static], [private]
The set of functions which have to be considered library_system.
Definition at line 93 of file check_system_type.hpp.
Referenced by build_include_structures(), and recursive_examinate().
library_system_includes
CustomUnorderedSet< std::string > CheckSystemType::library_system_includes [static], [private]
The set of headers which contains function which have to be considered library_system.
Definition at line 96 of file check_system_type.hpp.
Referenced by build_include_structures(), and recursive_examinate().
rename_function
CustomUnorderedMapUnstable< std::string, std::string > CheckSystemType::rename_function [static], [private]
Associates a function to its original name.
Definition at line 87 of file check_system_type.hpp.
Referenced by build_include_structures(), and recursive_examinate().
rename_types
CustomUnorderedMapUnstable< std::string, std::string > CheckSystemType::rename_types [static], [private]
Associates a type to its original name.
Definition at line 90 of file check_system_type.hpp.
Referenced by build_include_structures(), and recursive_examinate().
systemIncPath
std::vector< std::string > CheckSystemType::systemIncPath [static], [private]
Contains the list of the folders containining the system header files.
Definition at line 81 of file check_system_type.hpp.
Referenced by build_include_structures(), getRealInclName(), and is_system_include().
TM
const tree_managerRef CheckSystemType::TM [private]
The tree manager.
Definition at line 75 of file check_system_type.hpp.
Referenced by InternalExec(), and recursive_examinate().
undefined_library_function_include
CustomUnorderedMapUnstable< std::string, std::string > CheckSystemType::undefined_library_function_include [static], [private]
Map undefined library function to corresponding header.
Definition at line 104 of file check_system_type.hpp.
Referenced by build_include_structures(), and recursive_examinate().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/check_system_type.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/check_system_type.cpp