conflict_based_register Class Reference
#include <conflict_based_register.hpp>
Public Member Functions
conflict_based_register (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor of the class.
~conflict_based_register () override
Destructor of the class.
void create_conflict_graph ()
Create the conflict graph.
Protected Types
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > conflict_graph
typedef boost::graph_traits< conflict_graph >::vertex_descriptor cg_vertex_descriptor
typedef boost::graph_traits< conflict_graph >::vertices_size_type cg_vertices_size_type
typedef boost::property_map< conflict_graph, boost::vertex_index_t >::const_type cg_vertex_index_map
Protected Attributes
conflict_graph cg
conflict graph
boost::iterator_property_map< cg_vertices_size_type *, cg_vertex_index_map, cg_vertices_size_type, cg_vertices_size_type & > color
Private Attributes
std::vector< cg_vertices_size_type > color_vec
Additional Inherited Members
Detailed Description
Definition at line 50 of file conflict_based_register.hpp.
Member Typedef Documentation
cg_vertex_descriptor
typedef boost::graph_traits<conflict_graph>::vertex_descriptor conflict_based_register::cg_vertex_descriptor [protected]
Definition at line 54 of file conflict_based_register.hpp.
cg_vertex_index_map
typedef boost::property_map<conflict_graph, boost::vertex_index_t>::const_type conflict_based_register::cg_vertex_index_map [protected]
Definition at line 56 of file conflict_based_register.hpp.
cg_vertices_size_type
typedef boost::graph_traits<conflict_graph>::vertices_size_type conflict_based_register::cg_vertices_size_type [protected]
Definition at line 55 of file conflict_based_register.hpp.
conflict_graph
typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS> conflict_based_register::conflict_graph [protected]
Definition at line 53 of file conflict_based_register.hpp.
Constructor & Destructor Documentation
conflict_based_register()
conflict_based_register::conflict_based_register (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor of the class.
HLS/binding/storage_value_insertion includes.
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the register binding algorithm
Definition at line 60 of file conflict_based_register.cpp.
References ~conflict_based_register().
 conflict_based_register()
conflict_based_register::~conflict_based_register () [override], [default]
Destructor of the class.
Referenced by conflict_based_register().
Member Function Documentation
create_conflict_graph()
void conflict_based_register::create_conflict_graph ()
Create the conflict graph.
conflict graph creation
variables of different size are in conflict
Definition at line 67 of file conflict_based_register.cpp.
References StorageValueInformation::are_value_bitsize_compatible(), cg, color, color_vec, liveness::get_live_in(), StorageValueInformation::get_number_of_storage_values(), StorageValueInformation::get_storage_value_index(), liveness::get_support(), HLSFunctionStep::HLS, max(), reg_binding_creator::register_lower_bound, hls::Rliv, hls::storage_value_information, and THROW_ASSERT.
Referenced by vertex_coloring_register::InternalExec(), and chordal_coloring_register::InternalExec().
Field Documentation
cg
conflict_graph conflict_based_register::cg [protected]
conflict graph
Definition at line 59 of file conflict_based_register.hpp.
Referenced by create_conflict_graph(), vertex_coloring_register::InternalExec(), and chordal_coloring_register::InternalExec().
color
boost::iterator_property_map<cg_vertices_size_type*, cg_vertex_index_map, cg_vertices_size_type, cg_vertices_size_type&> conflict_based_register::color [protected]
Definition at line 61 of file conflict_based_register.hpp.
Referenced by create_conflict_graph(), vertex_coloring_register::InternalExec(), and chordal_coloring_register::InternalExec().
color_vec
std::vector<cg_vertices_size_type> conflict_based_register::color_vec [private]
Definition at line 64 of file conflict_based_register.hpp.
Referenced by create_conflict_graph().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/conflict_based_register.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/conflict_based_register.cpp