Bit_Value_opt Class Reference
Class performing some optimizations on the GCC IR exploiting Bit Value analysis.
#include <Bit_Value_opt.hpp>
Public Member Functions
Bit_Value_opt (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~Bit_Value_opt () override
Destructor.
DesignFlowStep_Status InternalExec () override
Extract patterns from the GCC IR.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void optimize (statement_list *sl, tree_managerRef TM)
do bit value based optimization such as:
Private Attributes
tree_manipulationRef IRman
the tree manipulation
bool modified
when true IR has been modified
bool restart_dead_code
True if dead code must be restarted.
Additional Inherited Members
Detailed Description
Class performing some optimizations on the GCC IR exploiting Bit Value analysis.
Definition at line 64 of file Bit_Value_opt.hpp.
Constructor & Destructor Documentation
Bit_Value_opt()
Bit_Value_opt::Bit_Value_opt (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
_Param is the set of the parameters
_AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
HLS/vcd include
Definition at line 86 of file Bit_Value_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~Bit_Value_opt().
 Bit_Value_opt()
Bit_Value_opt::~Bit_Value_opt () [override], [default]
Destructor.
Referenced by Bit_Value_opt().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > Bit_Value_opt::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Following precedence is to reduce invalidation; BIT_VALUE_OPT of called can invalidate DEAD_CODE_ELIMINATION of called and so this
Implements FrontendFlowStep.
Definition at line 94 of file Bit_Value_opt.cpp.
References ABORTED, FrontendFlowStep::CALLED_FUNCTIONS, COMPLETE_CALL_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, NONEXISTENT, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, restart_dead_code, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, UNNECESSARY, and FrontendFlowStep::WHOLE_APPLICATION.
HasToBeExecuted()
bool Bit_Value_opt::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 2559 of file Bit_Value_opt.cpp.
References FunctionFrontendFlowStep::bitvalue_version, FunctionFrontendFlowStep::function_behavior, and FunctionFrontendFlowStep::HasToBeExecuted().
Initialize()
void Bit_Value_opt::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 2564 of file Bit_Value_opt.cpp.
References FrontendFlowStep::AppM, IRman, and DesignFlowStep::parameters.
InternalExec()
DesignFlowStep_Status Bit_Value_opt::InternalExec () [override], [virtual]
Extract patterns from the GCC IR.
Returns
the exit status of this step
for each basic block B in CFG do > Consider all blocks successively
Implements FunctionFrontendFlowStep.
Definition at line 2540 of file Bit_Value_opt.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), modified, optimize(), PRINT_DBG_MEX, restart_dead_code, sl, SUCCESS, THROW_ASSERT, and UNCHANGED.
optimize()
void Bit_Value_opt::optimize (statement_list * sl, tree_managerRef TM) [private]
do bit value based optimization such as:
constant propagation
Parameters
sl is the statement list
TM is the tree manager
in case do sign extension
this prevent an infinite loop with CSE
first check if we have to change a mult_expr in a widen_mult_expr
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
set uses of stmt
set the bit_values to the ssa var
set the bit_values to the ssa var
try to fix cond_expr condition
set the bit_values to the ssa var
set the bit_values to the ssa var
set the bit_values to the ssa var
second argument is null since we cannot add the new statement at the end of the current BB
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
replaced with redundant code to restart lut_transformation
Definition at line 175 of file Bit_Value_opt.cpp.
References FrontendFlowStep::AppM, tree_manager::CGetTreeReindex(), tree_helper::CGetType(), constrainSSA(), convert_to_binary(), tree_manipulation::create_binary_operation(), tree_manipulation::create_boolean_type(), tree_manipulation::create_extract_bit_expr(), tree_manipulation::create_lut_expr(), tree_manipulation::create_ssa_name(), tree_manipulation::create_ternary_operation(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateDefaultUnsignedLongLongInt(), tree_manipulation::CreateGimpleAssign(), tree_manipulation::CreateNopExpr(), tree_manipulation::CreateNotExpr(), tree_manipulation::CreateRealCst(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_helper::get_type_index(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, INDENT_OUT_MEX, index, tree_node::index, IRman, tree_helper::is_a_complex(), tree_helper::is_a_pointer(), tree_helper::is_a_vector(), tree_helper::is_bool(), tree_helper::is_int(), tree_helper::is_real(), statement_list::list_of_bloc, max(), min, modified, tree_manager::new_tree_node_id(), DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, PRINT_DBG_MEX, tree_manager::ReplaceTreeNode(), resize_to_1_8_16_32_64_128_256_512(), restart_dead_code, tree_helper::size(), tree_helper::Size(), STR, THROW_ASSERT, THROW_ERROR, ToString(), and tree_node::ToString().
Referenced by InternalExec().
Field Documentation
IRman
tree_manipulationRef Bit_Value_opt::IRman [private]
the tree manipulation
Definition at line 68 of file Bit_Value_opt.hpp.
Referenced by Initialize(), and optimize().
modified
bool Bit_Value_opt::modified [private]
when true IR has been modified
Definition at line 71 of file Bit_Value_opt.hpp.
Referenced by InternalExec(), and optimize().
restart_dead_code
bool Bit_Value_opt::restart_dead_code [private]
True if dead code must be restarted.
Definition at line 74 of file Bit_Value_opt.hpp.
Referenced by ComputeFrontendRelationships(), InternalExec(), and optimize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value_opt.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value_opt.cpp