isolated_var_pp_functor Struct Reference
#include <var_pp_functor.hpp>
Public Member Functions
isolated_var_pp_functor (const BehavioralHelperConstRef _BH, unsigned int _repl_var, std::string _var_string)
Constructor.
~isolated_var_pp_functor () override=default
Destructor.
std::string operator() (unsigned int var) const override
return the name of the variable.
Private Attributes
const BehavioralHelperConstRef BH
behavioral helper
unsigned int repl_var
std::string var_string
Detailed Description
Definition at line 176 of file var_pp_functor.hpp.
Constructor & Destructor Documentation
isolated_var_pp_functor()
isolated_var_pp_functor::isolated_var_pp_functor (const BehavioralHelperConstRef _BH, unsigned int _repl_var, std::string _var_string) [inline]
Constructor.
Definition at line 186 of file var_pp_functor.hpp.
References var_pp_functor::operator()().
 isolated_var_pp_functor()
isolated_var_pp_functor::~isolated_var_pp_functor () [override], [default]
Destructor.
Member Function Documentation
operator()()
std::string isolated_var_pp_functor::operator() (unsigned int var) const [override], [virtual]
return the name of the variable.
Parameters
var is the nodeid of the variable.
Implements var_pp_functor.
Definition at line 229 of file var_pp_functor.cpp.
References address_var_pp_functor::BH, BehavioralHelper::get_array_ref_array(), BehavioralHelper::get_array_ref_index(), BehavioralHelper::get_component_ref_field(), BehavioralHelper::get_component_ref_record(), BehavioralHelper::get_mem_ref_base(), BehavioralHelper::get_mem_ref_offset(), BehavioralHelper::get_operand_from_unary_expr(), BehavioralHelper::get_type(), index, BehavioralHelper::is_a_component_ref(), BehavioralHelper::is_a_imagpart_expr(), BehavioralHelper::is_a_mem_ref(), BehavioralHelper::is_a_realpart_expr(), BehavioralHelper::is_an_addr_expr(), BehavioralHelper::is_an_array(), BehavioralHelper::is_an_array_ref(), BehavioralHelper::is_an_indirect_ref(), address_var_pp_functor::operator()(), BehavioralHelper::print_type(), BehavioralHelper::PrintVariable(), and test_panda::type.
Field Documentation
BH
const BehavioralHelperConstRef isolated_var_pp_functor::BH [private]
behavioral helper
Definition at line 180 of file var_pp_functor.hpp.
repl_var
unsigned int isolated_var_pp_functor::repl_var [private]
Definition at line 181 of file var_pp_functor.hpp.
var_string
std::string isolated_var_pp_functor::var_string [private]
Definition at line 182 of file var_pp_functor.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.cpp