dead_code_elimination Class Reference
#include <dead_code_elimination.hpp>
Public Member Functions
dead_code_elimination (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~dead_code_elimination () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs dead code elimination.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void kill_uses (const tree_managerRef TM, tree_nodeRef op0) const
void kill_vdef (const tree_managerRef TM, tree_nodeRef vdef)
unsigned move2emptyBB (const tree_managerRef TM, statement_list *sl, unsigned pred, blocRef bb_pred, unsigned cand_bb_dest, unsigned bb_dest) const
void add_gimple_nop (gimple_node *gc, const tree_managerRef TM, tree_nodeRef cur_stmt, blocRef bb)
Private Attributes
std::map< unsigned int, bool > last_writing_memory
std::map< unsigned int, bool > last_reading_memory
Additional Inherited Members
Detailed Description
Definition at line 71 of file dead_code_elimination.hpp.
Constructor & Destructor Documentation
dead_code_elimination()
dead_code_elimination::dead_code_elimination (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
header include
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the index of the function
design_flow_manager is the design flow manager
STD includes
Definition at line 74 of file dead_code_elimination.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~dead_code_elimination().
 dead_code_elimination()
dead_code_elimination::~dead_code_elimination () [override], [default]
Destructor.
Referenced by dead_code_elimination().
Member Function Documentation
add_gimple_nop()
void dead_code_elimination::add_gimple_nop (gimple_node * gc, const tree_managerRef TM, tree_nodeRef cur_stmt, blocRef bb) [private]
Definition at line 239 of file dead_code_elimination.cpp.
References srcp::column_number, tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, tree_manager::GetTreeReindex(), srcp::include_name, INDENT_DBG_MEX, srcp::line_number, tree_manager::new_tree_node_id(), STR, THROW_ASSERT, TOK, TOK_SRCP, and ToString().
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > dead_code_elimination::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 82 of file dead_code_elimination.cpp.
References FrontendFlowStep::CALLED_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, MEM_CG_EXT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and USE_COUNTING.
HasToBeExecuted()
bool dead_code_elimination::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 111 of file dead_code_elimination.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), last_reading_memory, and last_writing_memory.
InternalExec()
DesignFlowStep_Status dead_code_elimination::InternalExec () [override], [virtual]
Performs dead code elimination.
single sweep analysis, block by block, from the bottom to up.
Returns
the exit status of this step
Each ssa which is used zero times is eliminated and the uses of the variables used in the assignment are recomputed multi-way and two way IFs simplified when conditions are constants gimple_call without side effects are removed store-load pairs checked for simplification dead stores removed Retrieve the list of block
find out if it is a gimple_assign
in case of virtual uses it is better not perform the elimination
op0 is the left side of the assignment, op1 is the right side
very strict condition for the elimination
conservative analysis
very strict condition for the elimination
check if this load is killed by a following vover
remove same conditions
Fix PHIs
fix vdef/memdef
all vovers become vuse
fix vdef
fix memdef
all vovers become vuse
fix vdef
fix memdef
update function memory write flag
conservative analysis
more conservative than really needed
Implements FunctionFrontendFlowStep.
Definition at line 289 of file dead_code_elimination.cpp.
References add_gimple_nop(), FrontendFlowStep::AppM, function_decl::body, ssa_name::CGetDefStmts(), ssa_name::CGetNumberUses(), ssa_name::CGetUseStmts(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, tree_helper::find_obj_type_ref_function(), FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_index(), FunctionFrontendFlowStep::GetName(), FunctionFrontendFlowStep::GetSignature(), tree_node::GetString(), tree_manager::GetTreeNode(), INDENT_DBG_MEX, tree_helper::is_a_nop_function_decl(), tree_helper::is_a_vector(), kill_uses(), kill_vdef(), last_reading_memory, last_writing_memory, move2emptyBB(), DesignFlowStep::parameters, phi, function_decl::reading_memory, tree_manager::ReplaceTreeNode(), resize_to_1_8_16_32_64_128_256_512(), tree_helper::size(), sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, UNCHANGED, ssa_name::virtual_flag, and function_decl::writing_memory.
kill_uses()
void dead_code_elimination::kill_uses (const tree_managerRef TM, tree_nodeRef op0) const [private]
Definition at line 128 of file dead_code_elimination.cpp.
References tree_manipulation::create_default_unsigned_integer_type(), tree_manager::create_tree_node(), tree_manipulation::CreateRealCst(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_index(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_helper::is_a_complex(), tree_helper::is_a_vector(), tree_helper::is_real(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), STR, THROW_ASSERT, TOK, TOK_OP, TOK_SRCP, and TOK_TYPE.
Referenced by InternalExec().
kill_vdef()
void dead_code_elimination::kill_vdef (const tree_managerRef TM, tree_nodeRef vdef) [private]
Definition at line 174 of file dead_code_elimination.cpp.
References tree_manager::create_tree_node(), GET_NODE, tree_manager::GetTreeReindex(), tree_manager::new_tree_node_id(), TOK, and TOK_SRCP.
Referenced by InternalExec().
move2emptyBB()
unsigned dead_code_elimination::move2emptyBB (const tree_managerRef TM, statement_list * sl, unsigned pred, blocRef bb_pred, unsigned cand_bb_dest, unsigned bb_dest) const [private]
Create empty basic block
Fix PHIs
Definition at line 183 of file dead_code_elimination.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, INDENT_DBG_MEX, statement_list::list_of_bloc, phi, and STR.
Referenced by InternalExec().
Field Documentation
last_reading_memory
std::map<unsigned int, bool> dead_code_elimination::last_reading_memory [private]
Definition at line 76 of file dead_code_elimination.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
last_writing_memory
std::map<unsigned int, bool> dead_code_elimination::last_writing_memory [private]
Definition at line 74 of file dead_code_elimination.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/dead_code_elimination.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/dead_code_elimination.cpp