VcdSignalSelection Class Reference
#include <VcdSignalSelection.hpp>
Public Member Functions
VcdSignalSelection (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~VcdSignalSelection () override
Destructor.
DesignFlowStep_Status Exec () override
Executes the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void SelectInitialAddrParam (const CustomOrderedSet< unsigned int > &reached_body_fun_ids, CustomUnorderedMap< unsigned int, TreeNodeSet > &address_parameters)
Selects the initial set of function parameters to skip, iterating on the reached functions with a body and inserting the parm_decl tree_nodes in param_to_skip.
void InitialSsaIsAddress (const tree_nodeConstRef &tn, const CustomUnorderedSet< unsigned int > &addr_fun_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> &call_id_to_called_id)
Determines if the tree_node tn assigns an ssa_name representing an address.
void InitialPhiResIsAddress (const tree_nodeConstRef &tn)
Determines if the tree_node tn assigns an ssa_name representing an address.
void SelectInitialSsa (const CustomOrderedSet< unsigned int > &reached_body_fun_ids, const CustomUnorderedSet< unsigned int > &addr_fun_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> &call_id_to_called_id)
Selects the initial set of ssa to skip, iterating on the reached functions with a body and inserting the ssa tree_nodes in ssa_to_skip.
void SingleStepPropagateParamToSsa (const TreeNodeMap< size_t > &used_ssa, const TreeNodeSet &address_parameters)
Single step used in the loop of PropagateAddrParamToSsa()
void PropagateAddrParamToSsa (const CustomUnorderedMap< unsigned int, TreeNodeSet > &address_parameters, const CustomOrderedSet< unsigned int > &reached_body_fun_ids)
Propagates the information on the ssa to skip to all the ssa in the functions with body.
void SingleStepPropagateAddrSsa (const tree_nodeRef &curr_tn)
Single step used in the loop of PropagateAddrSsa()
void PropagateAddrSsa ()
Propagates the information on the ssa representing addresses across all the ssa in the functions with body.
void DetectInvalidReturns (const CustomOrderedSet< unsigned int > &reached_body_functions, CustomUnorderedSet< unsigned int > &addr_fun_ids)
Detects return statements resulting in values to be skipped in the discrepancy analysis.
void InProcedurePropagateAddr (const CustomUnorderedMap< unsigned int, TreeNodeSet > &address_parameters, const CustomOrderedSet< unsigned int > &reached_body_functions, CustomUnorderedSet< unsigned int > &addr_fun_ids)
Propagates the information on the ssa to skip to all the ssa in the functions with body.
void CrossPropagateAddrSsa (CustomUnorderedMap< unsigned int, TreeNodeSet > &address_parameters, const CustomOrderedSet< unsigned int > &reached_body_functions, const CustomUnorderedSet< unsigned int > &addr_fun_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> &fu_id_to_call_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> &call_id_to_called_id)
Propagates the information on the parameters to skip across function calls.
void SelectAddrSsa (const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> &fu_id_to_call_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> &call_id_to_called_id)
Compute the ssa representing address values.
bool IsAddressType (const unsigned int type_index) const
Checks if type_index represents an address type.
void SelectInternalSignals (CustomUnorderedMap< unsigned int, UnorderedSetStdStable< std::string >> &fun_id_to_sig_names) const
Protected Attributes
const tree_managerRef TM
const DiscrepancyRef Discr
std::string present_state_name
The name of the present state signal.
Additional Inherited Members
Detailed Description
Definition at line 45 of file VcdSignalSelection.hpp.
Constructor & Destructor Documentation
VcdSignalSelection()
VcdSignalSelection::VcdSignalSelection (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Definition at line 94 of file VcdSignalSelection.cpp.
References DesignFlowStep::debug_level, GET_CLASS, HLS_step::HLSMgr, DesignFlowStep::parameters, STR, THROW_ASSERT, VERILOG, and ~VcdSignalSelection().
 VcdSignalSelection()
VcdSignalSelection::~VcdSignalSelection () [override], [default]
Destructor.
Referenced by VcdSignalSelection().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > VcdSignalSelection::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Reimplemented from HLS_step.
Definition at line 112 of file VcdSignalSelection.cpp.
References CALL_GRAPH_UNFOLDING, DesignFlowStep::DEPENDENCE_RELATIONSHIP, HW_PATH_COMPUTATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and TOP_FUNCTION.
CrossPropagateAddrSsa()
void VcdSignalSelection::CrossPropagateAddrSsa (CustomUnorderedMap< unsigned int, TreeNodeSet > & address_parameters, const CustomOrderedSet< unsigned int > & reached_body_functions, const CustomUnorderedSet< unsigned int > & addr_fun_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> & fu_id_to_call_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> & call_id_to_called_id) [protected]
Propagates the information on the parameters to skip across function calls.
If a function is called with a parameter which is a ssa marked to skip, then the parm_decl associated to that paramter must be marked to skip. This propagation is based on the ssa names already marked to be skipped
Parameters
in,out address_parameters Set of parm_decl tree_nodes of the parameters to skip
in reached_body_functions List of the ids of the reached functions with body
in addr_fun_ids List of ids of the reached functions that return an address value
in fu_id_to_call_ids Maps a function id to the set of ids of operations where it calls other functions
in call_id_to_called_id Maps the id of a call operation to the id of the called function
Definition at line 486 of file VcdSignalSelection.cpp.
References BUILTIN_WAIT_CALL, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpGraphInfo(), OpGraph::CGetOpNodeInfo(), Discr, FunctionBehavior::FCFG, BehavioralHelper::function_has_to_be_printed(), BehavioralHelper::get_function_name(), tree_node::get_kind(), GET_NODE, BehavioralHelper::has_implementation(), HLS_step::HLSMgr, BehavioralHelper::is_operating_system_function(), BehavioralHelper::is_var_args(), STR, THROW_ASSERT, THROW_WARNING, and TM.
Referenced by SelectAddrSsa().
DetectInvalidReturns()
void VcdSignalSelection::DetectInvalidReturns (const CustomOrderedSet< unsigned int > & reached_body_functions, CustomUnorderedSet< unsigned int > & addr_fun_ids) [protected]
Detects return statements resulting in values to be skipped in the discrepancy analysis.
Parameters
in reached_body_functions List of the ids of the reached functions with body
in,out addr_fun_ids List of ids of the reached functions that return an address value
Definition at line 449 of file VcdSignalSelection.cpp.
References OpGraph::CGetInEdges(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpGraphInfo(), OpGraph::CGetOpNodeInfo(), Discr, ENTRY_ID, EXIT_ID, FunctionBehavior::FCFG, GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), HLS_step::HLSMgr, IsAddressType(), and TM.
Referenced by InProcedurePropagateAddr().
Exec()
DesignFlowStep_Status VcdSignalSelection::Exec () [override], [virtual]
Executes the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 821 of file VcdSignalSelection.cpp.
References CLOCK_PORT_NAME, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, Discr, DONE_PORT_NAME, tree_helper::get_base_index(), tree_helper::get_type_index(), HIERARCHY_SEPARATOR, HLS_step::HLSMgr, INDENT_OUT_MEX, IsAddressType(), DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, present_state_name, PRINT_DBG_MEX, SelectAddrSsa(), SelectInternalSignals(), START_PORT_NAME, STR, SUCCESS, THROW_ASSERT, and TM.
HasToBeExecuted()
bool VcdSignalSelection::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 913 of file VcdSignalSelection.cpp.
InitialPhiResIsAddress()
void VcdSignalSelection::InitialPhiResIsAddress (const tree_nodeConstRef & tn) [protected]
Determines if the tree_node tn assigns an ssa_name representing an address.
Parameters
in tn The node to analyze
Definition at line 233 of file VcdSignalSelection.cpp.
References gimple_phi::CGetDefEdgesList(), Discr, GET_NODE, tree_node::GetString(), phi, gimple_phi::res, STR, and THROW_ASSERT.
Referenced by SelectInitialSsa().
InitialSsaIsAddress()
void VcdSignalSelection::InitialSsaIsAddress (const tree_nodeConstRef & tn, const CustomUnorderedSet< unsigned int > & addr_fun_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> & call_id_to_called_id) [protected]
Determines if the tree_node tn assigns an ssa_name representing an address.
The ssa to be skipped at the beginning are
variables representing addresses (pointers, arrays, vectors)
integer variables resulting from pointers casted to integer
ssa_name referred to a function's parameter marked as to skip
ssa_name to which is assigned the return value of a function to skip If curr_tn must be skipped it is added to ssa_to_skip.
Parameters
in tn The node to analyze
in addr_fun_ids List of ids of the reached functions that return an address value
in call_id_to_called_id Map the id of a call to the id of the called function
Definition at line 154 of file VcdSignalSelection.cpp.
References Discr, GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), tree_node::GetString(), tree_helper::is_a_complex(), tree_helper::is_real(), IsAddressType(), DesignFlowStep::parameters, STR, THROW_ASSERT, and TM.
Referenced by SelectInitialSsa().
InProcedurePropagateAddr()
void VcdSignalSelection::InProcedurePropagateAddr (const CustomUnorderedMap< unsigned int, TreeNodeSet > & address_parameters, const CustomOrderedSet< unsigned int > & reached_body_functions, CustomUnorderedSet< unsigned int > & addr_fun_ids) [protected]
Propagates the information on the ssa to skip to all the ssa in the functions with body.
This propagation is based on the ssa_name and param_decl already marked to skip.
Parameters
in address_parameters Set of parm_decl tree_nodes of the parameters to skip
in reached_body_functions List of the ids of the reached functions with body
in,out addr_fun_ids List of ids of the reached functions that return an address value
Definition at line 478 of file VcdSignalSelection.cpp.
References DetectInvalidReturns(), PropagateAddrParamToSsa(), and PropagateAddrSsa().
Referenced by SelectAddrSsa().
IsAddressType()
bool VcdSignalSelection::IsAddressType (const unsigned int type_index) const [protected]
Checks if type_index represents an address type.
Definition at line 107 of file VcdSignalSelection.cpp.
References tree_helper::GetElements(), tree_helper::is_a_pointer(), tree_helper::is_a_vector(), tree_helper::is_an_array(), and TM.
Referenced by DetectInvalidReturns(), Exec(), InitialSsaIsAddress(), SelectAddrSsa(), SelectInitialAddrParam(), and SelectInitialSsa().
PropagateAddrParamToSsa()
void VcdSignalSelection::PropagateAddrParamToSsa (const CustomUnorderedMap< unsigned int, TreeNodeSet > & address_parameters, const CustomOrderedSet< unsigned int > & reached_body_fun_ids) [protected]
Propagates the information on the ssa to skip to all the ssa in the functions with body.
This propagation mark to skip all the ssa_name tree_nodes wich are referred to a param_decl already marked to be skipped. The propagation is intra procedural.
Parameters
in address_parameters Set of parm_decl tree_nodes of the parameters to skip
in reached_body_functions List of the ids of the reached functions with body
Definition at line 335 of file VcdSignalSelection.cpp.
References FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), tree_helper::ComputeSsaUses(), ENTRY_ID, EXIT_ID, FunctionBehavior::FCFG, HLS_step::HLSMgr, SingleStepPropagateParamToSsa(), THROW_ASSERT, and TM.
Referenced by InProcedurePropagateAddr().
PropagateAddrSsa()
void VcdSignalSelection::PropagateAddrSsa () [protected]
Propagates the information on the ssa representing addresses across all the ssa in the functions with body.
The propagation is intra procedural.
Definition at line 433 of file VcdSignalSelection.cpp.
References Discr, tree_node::GetString(), SingleStepPropagateAddrSsa(), and THROW_ASSERT.
Referenced by InProcedurePropagateAddr().
SelectAddrSsa()
void VcdSignalSelection::SelectAddrSsa (const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> & fu_id_to_call_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> & call_id_to_called_id) [protected]
Compute the ssa representing address values.
They must be manipulated in a different way by the discrepancy analysis
Parameters
in fu_id_to_call_ids Maps a function id to the set of ids of operations where it calls other functions
in call_id_to_called_id Maps the id of a call operation to the id of the called function
Definition at line 666 of file VcdSignalSelection.cpp.
References FunctionBehavior::CGetBehavioralHelper(), CrossPropagateAddrSsa(), Discr, BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, InProcedurePropagateAddr(), IsAddressType(), SelectInitialAddrParam(), and SelectInitialSsa().
Referenced by Exec().
SelectInitialAddrParam()
void VcdSignalSelection::SelectInitialAddrParam (const CustomOrderedSet< unsigned int > & reached_body_fun_ids, CustomUnorderedMap< unsigned int, TreeNodeSet > & address_parameters) [protected]
Selects the initial set of function parameters to skip, iterating on the reached functions with a body and inserting the parm_decl tree_nodes in param_to_skip.
Parameters
in reached_body_fun_ids List of ids of the reached functions with body
out address_parameters The set of parm_decl tree_nodes representing addresses
Definition at line 137 of file VcdSignalSelection.cpp.
References GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), tree_node::GetString(), IsAddressType(), THROW_ASSERT, and TM.
Referenced by SelectAddrSsa().
SelectInitialSsa()
void VcdSignalSelection::SelectInitialSsa (const CustomOrderedSet< unsigned int > & reached_body_fun_ids, const CustomUnorderedSet< unsigned int > & addr_fun_ids, const CustomUnorderedMap< unsigned int, UnorderedSetStdStable< unsigned int >> & call_id_to_called_id) [protected]
Selects the initial set of ssa to skip, iterating on the reached functions with a body and inserting the ssa tree_nodes in ssa_to_skip.
Parameters
in reached_body_fun_ids List of ids of the reached functions with body
in addr_fun_ids List of ids of the reached functions that return an address value
in call_id_to_called_id Map the id of a call to the id of the called function
Definition at line 248 of file VcdSignalSelection.cpp.
References FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), Discr, ENTRY_ID, EXIT_ID, FunctionBehavior::FCFG, tree_node::get_kind(), tree_helper::get_type_index(), HLS_step::HLSMgr, InitialPhiResIsAddress(), InitialSsaIsAddress(), tree_helper::is_a_complex(), tree_helper::is_real(), IsAddressType(), THROW_ASSERT, and TM.
Referenced by SelectAddrSsa().
SelectInternalSignals()
void VcdSignalSelection::SelectInternalSignals (CustomUnorderedMap< unsigned int, UnorderedSetStdStable< std::string >> & fun_id_to_sig_names) const [protected]
Definition at line 725 of file VcdSignalSelection.cpp.
References FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), Discr, ENTRY_ID, EXIT_ID, FunctionBehavior::FCFG, BehavioralHelper::function_has_to_be_printed(), reg_binding::get(), AllocationInformation::get_fu_name(), tree_node::get_kind(), AllocationInformation::get_memory_var(), GET_NAME, AllocationInformation::get_number_channels(), reg_binding::get_register(), StorageValueInformation::get_storage_value_index(), BehavioralHelper::has_implementation(), HLS_step::HLSMgr, StorageValueInformation::is_a_storage_value(), AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_direct_proxy_memory_unit(), AllocationInformation::is_indirect_access_memory_unit(), AllocationInformation::is_memory_unit(), AllocationInformation::is_proxy_memory_unit(), AllocationInformation::is_proxy_wrapped_unit(), phi, STR, THROW_ASSERT, TM, and WRAPPED_PROXY_PREFIX.
Referenced by Exec().
SingleStepPropagateAddrSsa()
void VcdSignalSelection::SingleStepPropagateAddrSsa (const tree_nodeRef & curr_tn) [protected]
Single step used in the loop of PropagateAddrSsa()
Definition at line 371 of file VcdSignalSelection.cpp.
References gimple_phi::CGetDefEdgesList(), Discr, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_node(), tree_node::GetString(), tree_helper::is_a_complex(), tree_helper::is_a_vector(), tree_helper::is_real(), phi, gimple_phi::res, STR, THROW_ASSERT, TM, and tree_node::ToString().
Referenced by PropagateAddrSsa().
SingleStepPropagateParamToSsa()
void VcdSignalSelection::SingleStepPropagateParamToSsa (const TreeNodeMap< size_t > & used_ssa, const TreeNodeSet & address_parameters) [protected]
Single step used in the loop of PropagateAddrParamToSsa()
Definition at line 309 of file VcdSignalSelection.cpp.
References Discr, GET_NODE, tree_node::GetString(), THROW_ASSERT, and tree_node::ToString().
Referenced by PropagateAddrParamToSsa().
Field Documentation
Discr
const DiscrepancyRef VcdSignalSelection::Discr [protected]
Definition at line 50 of file VcdSignalSelection.hpp.
Referenced by CrossPropagateAddrSsa(), DetectInvalidReturns(), Exec(), InitialPhiResIsAddress(), InitialSsaIsAddress(), PropagateAddrSsa(), SelectAddrSsa(), SelectInitialSsa(), SelectInternalSignals(), SingleStepPropagateAddrSsa(), and SingleStepPropagateParamToSsa().
present_state_name
std::string VcdSignalSelection::present_state_name [protected]
The name of the present state signal.
Definition at line 53 of file VcdSignalSelection.hpp.
Referenced by Exec().
TM
const tree_managerRef VcdSignalSelection::TM [protected]
Definition at line 48 of file VcdSignalSelection.hpp.
Referenced by CrossPropagateAddrSsa(), DetectInvalidReturns(), Exec(), InitialSsaIsAddress(), IsAddressType(), PropagateAddrParamToSsa(), SelectInitialAddrParam(), SelectInitialSsa(), SelectInternalSignals(), and SingleStepPropagateAddrSsa().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/VcdSignalSelection.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/VcdSignalSelection.cpp