NanoXploreWrapper Class Reference
#include <NanoXploreWrapper.hpp>
Public Member Functions
NanoXploreWrapper (const ParameterConstRef &Param, const std::string &tool_exec, const target_deviceRef &device, const std::string &output_dir, const std::string &default_output_dir)
Constructor.
~NanoXploreWrapper () override
Destructor.
void generate_synthesis_script (const DesignParametersRef &dp, const std::string &file_name) override
Creates the proper configuration script.
std::string toString (const xml_script_node_tRef node, const DesignParametersRef dp) const override
Returns the string-based representation of the XML element.
std::string getStringValue (const xml_script_node_tRef node, const DesignParametersRef &dp) const override
Returns the string-based representation of the XML element.
std::string get_command_line (const DesignParametersRef &dp) const override=0
Returns the proper command line.
Additional Inherited Members
Detailed Description
Definition at line 51 of file NanoXploreWrapper.hpp.
Constructor & Destructor Documentation
NanoXploreWrapper()
NanoXploreWrapper::NanoXploreWrapper (const ParameterConstRef & Param, const std::string & tool_exec, const target_deviceRef & device, const std::string & output_dir, const std::string & default_output_dir)
Constructor.
Header include.
Parameters
Param is the set of parameters
tool_exec is the name of the executable
output_dir is the directory where to save all the results
default_output_dir is the default output directory
Definition at line 58 of file NanoXploreWrapper.cpp.
References ~NanoXploreWrapper().
 NanoXploreWrapper()
NanoXploreWrapper::~NanoXploreWrapper () [override], [default]
Destructor.
Referenced by NanoXploreWrapper().
Member Function Documentation
generate_synthesis_script()
void NanoXploreWrapper::generate_synthesis_script (const DesignParametersRef & dp, const std::string & file_name) [override], [virtual]
Creates the proper configuration script.
replace some of the escape sequences
Implements SynthesisTool.
Definition at line 65 of file NanoXploreWrapper.cpp.
References DesignParameters::assign(), SynthesisTool::generate_bare_script(), getStringValue(), remove_escaped(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, SynthesisTool::xml_reserved_vars, and SynthesisTool::xml_script_nodes.
get_command_line()
std::string NanoXploreWrapper::get_command_line (const DesignParametersRef & dp) const [override], [pure virtual]
Returns the proper command line.
Implements SynthesisTool.
Implemented in nxpython_flow_wrapper.
getStringValue()
std::string NanoXploreWrapper::getStringValue (const xml_script_node_tRef node, const DesignParametersRef & dp) const [override], [virtual]
Returns the string-based representation of the XML element.
this point should never be reached
Implements SynthesisTool.
Definition at line 98 of file NanoXploreWrapper.cpp.
References xml_set_variable_t::multiValues, NODE_COMMAND, NODE_ENTRY, NODE_FOREACH, NODE_ITE_BLOCK, NODE_PARAMETER, NODE_SHELL, NODE_UNKNOWN, NODE_VARIABLE, result, xml_set_variable_t::singleValue, STR, THROW_ERROR, and toString().
Referenced by generate_synthesis_script(), and toString().
toString()
std::string NanoXploreWrapper::toString (const xml_script_node_tRef node, const DesignParametersRef dp) const [override], [virtual]
Returns the string-based representation of the XML element.
this point should never be reached
Implements SynthesisTool.
Definition at line 144 of file NanoXploreWrapper.cpp.
References xml_ite_block_t::condition, xml_parameter_t::curlyBrackets, xml_ite_block_t::elseNodes, xml_script_node_t::evaluate_condition(), getStringValue(), xml_parameter_t::multiValues, xml_set_variable_t::name, xml_parameter_t::name, xml_command_t::name, xml_shell_t::name, NODE_COMMAND, NODE_ENTRY, NODE_FOREACH, NODE_ITE_BLOCK, NODE_PARAMETER, NODE_SHELL, NODE_UNKNOWN, NODE_VARIABLE, xml_command_t::output, xml_shell_t::output, xml_command_t::parameters, xml_shell_t::parameters, result, xml_parameter_t::separator, sh, xml_parameter_t::singleValue, STR, xml_ite_block_t::thenNodes, THROW_ERROR, xml_set_entry_t::value, xml_command_t::value, and xml_shell_t::value.
Referenced by nxpython_flow_wrapper::get_command_line(), and getStringValue().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/nanoxplore/NanoXploreWrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/nanoxplore/NanoXploreWrapper.cpp