IR_lowering Class Reference
Compute the control flow graph for the operations.
#include <IR_lowering.hpp>
Public Member Functions
IR_lowering (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~IR_lowering () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes the operations CFG graph data structure.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Member Functions
tree_nodeRef expand_mult_const (tree_nodeRef op0, unsigned long long int val, const struct algorithm &alg, enum mult_variant &variant, const tree_nodeRef stmt, const blocRef block, tree_nodeRef &type, const std::string &srcp_default)
A subroutine of expand_mult, used for constant multiplications.
tree_nodeRef expand_smod_pow2 (tree_nodeRef op0, unsigned long long int d, const tree_nodeRef stmt, const blocRef block, tree_nodeRef &type, const std::string &srcp_default)
Expand signed modulus of OP0 by a power of two D in mode MODE.
tree_nodeRef expand_sdiv_pow2 (tree_nodeRef op0, unsigned long long int d, const tree_nodeRef stmt, const blocRef block, tree_nodeRef &type, const std::string &srcp_default)
Expand signed division of OP0 by a power of two D in mode MODE.
tree_nodeRef expand_MC (tree_nodeRef op0, integer_cst *ic_node, tree_nodeRef old_target, const tree_nodeRef stmt, const blocRef block, tree_nodeRef &type_expr, const std::string &srcp_default)
bool expand_target_mem_ref (target_mem_ref461 *tmr, const tree_nodeRef stmt, const blocRef block, const std::string &srcp_default, bool temp_addr)
tree_nodeRef expand_mult_highpart (tree_nodeRef op0, unsigned long long int ml, tree_nodeRef type_expr, int data_bitsize, const std::list< tree_nodeRef >::const_iterator it_los, const blocRef block, const std::string &srcp_default)
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
tree_nodeRef array_ref_lowering (array_ref *AR, const std::string &srcp_default, std::pair< unsigned int, blocRef > block, std::list< tree_nodeRef >::const_iterator it_los, bool temp_addr)
bool reached_max_transformation_limit (tree_nodeRef stmt)
check if the max transformation limit has been reached
void division_by_a_constant (const std::pair< unsigned int, blocRef > &block, std::list< tree_nodeRef >::const_iterator &it_los, gimple_assign *ga, tree_nodeRef op1, enum kind code1, bool &restart_analysis, const std::string &srcp_default, const std::string &step_name)
Private Attributes
tree_managerRef TM
The tree manager.
tree_manipulationRef tree_man
The IR manipulation.
Additional Inherited Members
Detailed Description
Compute the control flow graph for the operations.
Definition at line 84 of file IR_lowering.hpp.
Constructor & Destructor Documentation
IR_lowering()
IR_lowering::IR_lowering (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Definition at line 83 of file IR_lowering.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 IR_lowering()
IR_lowering::~IR_lowering () [override], [default]
Destructor.
Referenced by ComputeFrontendRelationships().
Member Function Documentation
array_ref_lowering()
tree_nodeRef IR_lowering::array_ref_lowering (array_ref * AR, const std::string & srcp_default, std::pair< unsigned int, blocRef > block, std::list< tree_nodeRef >::const_iterator it_los, bool temp_addr) [private]
Definition at line 1497 of file IR_lowering.cpp.
References compute_n_bytes(), tree_manipulation::create_binary_operation(), tree_manipulation::create_pointer_type(), tree_manipulation::create_size_type(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_helper::get_array_data_bitsize(), tree_helper::get_array_dimensions(), GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_node(), INDENT_DBG_MEX, STR, THROW_ASSERT, TM, ToString(), tree_man, and test_panda::type.
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > IR_lowering::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 89 of file IR_lowering.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SWITCH_FIX, THROW_UNREACHABLE, and ~IR_lowering().
ComputeRelationships()
void IR_lowering::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 126 of file IR_lowering.cpp.
References FunctionFrontendFlowStep::ComputeRelationships(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
division_by_a_constant()
void IR_lowering::division_by_a_constant (const std::pair< unsigned int, blocRef > & block, std::list< tree_nodeRef >::const_iterator & it_los, gimple_assign * ga, tree_nodeRef op1, enum kind code1, bool & restart_analysis, const std::string & srcp_default, const std::string & step_name) [private]
very special case op1 == 1
Find a suitable multiplier and right shift count instead of multiplying with D.
restrict if needed the input bit-widths
We have computed OP0 / abs(OP1). If OP1 is negative, negate the quotient.
Definition at line 378 of file IR_lowering_exec.cpp.
References FrontendFlowStep::AppM, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, ceil_log2(), choose_multiplier(), tree_manipulation::create_binary_operation(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, EXACT_POWER_OF_2_OR_ZERO_P, expand_mult_highpart(), expand_sdiv_pow2(), expand_smod_pow2(), floor_log2(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_helper::get_type_index(), INDENT_DBG_MEX, INDENT_OUT_MEX, invert_mod2n(), tree_helper::is_unsigned(), max(), min, gimple_assign::op0, gimple_assign::op1, DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, tree_helper::size(), tree_helper::Size(), STR, THROW_ASSERT, THROW_ERROR, TM, tree_man, and test_panda::type.
Referenced by InternalExec().
expand_MC()
tree_nodeRef IR_lowering::expand_MC (tree_nodeRef op0, integer_cst * ic_node, tree_nodeRef old_target, const tree_nodeRef stmt, const blocRef block, tree_nodeRef & type_expr, const std::string & srcp_default) [private]
very special case op1 == 0
very special case op1 == 1
very special case op1 == -1
keep the old assign
keep the old assign
Definition at line 1052 of file IR_lowering.cpp.
References ADDER_STD, FrontendFlowStep::AppM, choose_mult_variant(), tree_manipulation::create_binary_operation(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), EXACT_POWER_OF_2_OR_ZERO_P, expand_mult_const(), floor_log2(), technology_manager::get_fu(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, target_manager::get_technology_manager(), LIBRARY_STD_FU, MULTIPLIER_STD, resize_to_1_8_16_32_64_128_256_512(), tree_helper::Size(), STR, TM, and tree_man.
Referenced by expand_target_mem_ref(), and InternalExec().
expand_mult_const()
tree_nodeRef IR_lowering::expand_mult_const (tree_nodeRef op0, unsigned long long int val, const struct algorithm & alg, enum mult_variant & variant, const tree_nodeRef stmt, const blocRef block, tree_nodeRef & type, const std::string & srcp_default) [private]
A subroutine of expand_mult, used for constant multiplications.
Multiply OP0 by VAL in mode MODE, storing the result in TARGET if convenient. Use the shift/add sequence described by ALG and apply the final fixup specified by VARIANT. Compare only the bits of val and val_so_far that are significant in the result mode, to avoid sign-/zero-extension confusion.
Definition at line 735 of file IR_lowering.cpp.
References add_variant, alg_add_factor, alg_add_t2_m, alg_add_t_m2, alg_impossible, alg_m, alg_shift, alg_sub_factor, alg_sub_t2_m, alg_sub_t_m2, alg_unknown, alg_zero, tree_manipulation::create_binary_operation(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), INDENT_DBG_MEX, algorithm::log, negate_variant, algorithm::op, algorithm::ops, tree_helper::size(), THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, TM, tree_node::ToString(), and tree_man.
Referenced by expand_MC().
expand_mult_highpart()
tree_nodeRef IR_lowering::expand_mult_highpart (tree_nodeRef op0, unsigned long long int ml, tree_nodeRef type_expr, int data_bitsize, const std::list< tree_nodeRef >::const_iterator it_los, const blocRef block, const std::string & srcp_default) [private]
long long int u0, v0, u1, v1, u0v0, u0v0h, u1v0, u0v0hu1v0, u0v1, u0v0hu1v0u0v1, u0v0hu1v0u0v1h, u1v1; u0 = u & ((1LL<<32)-1); u1 = u >>32; v0 = v & ((1LL<<32)-1); v1 = v >>32; u0v0 = u0 * v0; u0v0h = u0v0>>32; u0v0hU = u0v0h & ((1LL<<32)-1);///only for signed computation u1v0 = u1 * v0; u0v0hu1v0 = u0v0hU + u1v0; w1 = u0v0hu1v0 & ((1LL<<32)-1); w2 = u0v0hu1v0 >>32; u0v1 = u0 * v1; w1u0v1 = w1+u0v1; w1u0v1h = w1u0v1 >> 32; u1v1 = u1 * v1; w1u0v1hw2 = w1u0v1h + w2; return w1u0v1hw2 + u1v1;
Definition at line 1293 of file IR_lowering.cpp.
References tree_manipulation::create_binary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), GET_INDEX_NODE, GET_NODE, tree_helper::is_unsigned(), THROW_ASSERT, TM, and tree_man.
Referenced by division_by_a_constant().
expand_sdiv_pow2()
tree_nodeRef IR_lowering::expand_sdiv_pow2 (tree_nodeRef op0, unsigned long long int d, const tree_nodeRef stmt, const blocRef block, tree_nodeRef & type, const std::string & srcp_default) [private]
Expand signed division of OP0 by a power of two D in mode MODE.
This routine is only called for positive values of D.
Definition at line 1003 of file IR_lowering.cpp.
References tree_manipulation::create_binary_operation(), tree_manipulation::create_boolean_type(), tree_manipulation::create_ternary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), floor_log2(), GET_INDEX_NODE, GET_NODE, tree_node::index, TM, and tree_man.
Referenced by division_by_a_constant().
expand_smod_pow2()
tree_nodeRef IR_lowering::expand_smod_pow2 (tree_nodeRef op0, unsigned long long int d, const tree_nodeRef stmt, const blocRef block, tree_nodeRef & type, const std::string & srcp_default) [private]
Expand signed modulus of OP0 by a power of two D in mode MODE.
Definition at line 946 of file IR_lowering.cpp.
References FrontendFlowStep::AppM, tree_manipulation::create_binary_operation(), tree_manipulation::create_boolean_type(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), floor_log2(), GET_INDEX_NODE, GET_NODE, FunctionFrontendFlowStep::GetName(), tree_node::index, THROW_ERROR, TM, and tree_man.
Referenced by division_by_a_constant().
expand_target_mem_ref()
bool IR_lowering::expand_target_mem_ref (target_mem_ref461 * tmr, const tree_nodeRef stmt, const blocRef block, const std::string & srcp_default, bool temp_addr) [private]
nothing to optimize
It is required to de-share some IR nodes
Definition at line 1148 of file IR_lowering.cpp.
References target_mem_ref461::base, tree_manipulation::create_binary_operation(), tree_manipulation::create_pointer_type(), tree_manipulation::create_size_type(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, expand_MC(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_helper::get_type_index(), target_mem_ref461::idx, target_mem_ref461::idx2, INDENT_DBG_MEX, target_mem_ref461::offset, target_mem_ref461::step, TM, ToString(), tree_man, test_panda::type, and target_mem_ref461::type.
Referenced by InternalExec().
Initialize()
void IR_lowering::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 120 of file IR_lowering.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::parameters, TM, and tree_man.
InternalExec()
DesignFlowStep_Status IR_lowering::InternalExec () [override], [virtual]
Computes the operations CFG graph data structure.
Returns
the exit status of this step
first analyze phis
It is required to de-share some IR nodes
for each basic block B in CFG do > Consider all blocks successively
found a a clobber assignment do nothing
required by the CLANG/LLVM plugin
It is required to de-share some IR nodes
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
It is required to de-share some IR nodes
normalize op0
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
expose some part of the target_mem_ref statement
check missing cast
split the target_mem_ref in a address computation statement and in a load statement
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
check if there is a misaligned access
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
required by CLANG/LLVM plugin
required by CLANG/LLVM plugin
if the previous transformation still give a multiplication let's check if this multiplication is actually widen_mult_expr
check if a mult_expr may become a widen_mult_expr
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
check if there is a misaligned access
check if the mem_ref corresponds to an implicit memset and then it will be lowered to simple loop initializing the variable
split the target_mem_ref in a address computation statement and in a store statement
manage something as binary operand
It is required to de-share some IR nodes
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
optimize less than 0 or greater than or equal than 0
It is required to de-share some IR nodes
required by the CLANG/LLVM plugin
required by the CLANG/LLVM plugin
Implements FunctionFrontendFlowStep.
Definition at line 907 of file IR_lowering_exec.cpp.
References ALGN_POINTER, FrontendFlowStep::AppM, test_panda::arg, array_ref_lowering(), tree_manager::CGetTreeReindex(), tree_helper::CGetType(), tree_manipulation::create_binary_operation(), tree_manipulation::create_boolean_type(), tree_manipulation::create_integer_type_with_prec(), tree_manipulation::create_pointer_type(), tree_manipulation::create_size_type(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateAddrExpr(), tree_manipulation::CreateGimpleAssign(), tree_manipulation::CreateNopExpr(), tree_manager::CreateUniqueIntegerCst(), tree_manipulation::CreateUnsigned(), tree_manipulation::CreateVectorBooleanType(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, division_by_a_constant(), expand_MC(), expand_target_mem_ref(), FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_base_index(), GET_CONST_NODE, GET_INDEX_CONST_NODE, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_helper::get_type_node(), tree_helper::GetElements(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, tree_helper::is_a_vector(), tree_helper::is_bool(), tree_helper::is_int(), tree_helper::is_real(), tree_helper::is_unsigned(), max(), DesignFlowStep::parameters, phi, reached_max_transformation_limit(), resize_to_1_8_16_32_64_128_256_512(), tree_helper::size(), tree_helper::Size(), sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, THROW_WARNING, TM, ToString(), tree_man, and test_panda::type.
reached_max_transformation_limit()
bool IR_lowering::reached_max_transformation_limit (tree_nodeRef stmt) [private]
check if the max transformation limit has been reached
Parameters
stmt is the current statement
Returns
true in case all the next transformations have to be skipped
Definition at line 1552 of file IR_lowering.cpp.
References FrontendFlowStep::AppM, GET_CONST_NODE, and tree_node::get_kind().
Referenced by InternalExec().
Field Documentation
TM
tree_managerRef IR_lowering::TM [private]
The tree manager.
Definition at line 88 of file IR_lowering.hpp.
Referenced by array_ref_lowering(), division_by_a_constant(), expand_MC(), expand_mult_const(), expand_mult_highpart(), expand_sdiv_pow2(), expand_smod_pow2(), expand_target_mem_ref(), Initialize(), and InternalExec().
tree_man
tree_manipulationRef IR_lowering::tree_man [private]
The IR manipulation.
Definition at line 91 of file IR_lowering.hpp.
Referenced by array_ref_lowering(), division_by_a_constant(), expand_MC(), expand_mult_const(), expand_mult_highpart(), expand_sdiv_pow2(), expand_smod_pow2(), expand_target_mem_ref(), Initialize(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/IR_lowering.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/IR_lowering.cpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/IR_lowering_exec.cpp