/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp File Reference
This class represents a base circuit object.
#include `structural_objects.hpp`
#include `config_HAVE_ASSERTS.hpp`
#include `config_HAVE_BAMBU_BUILT.hpp`
#include `config_HAVE_TECHNOLOGY_BUILT.hpp`
#include `config_HAVE_TUCANO_BUILT.hpp`
#include `config_RELEASE.hpp`
#include `HDL_manager.hpp`
#include `NP_functionality.hpp`
#include `custom_set.hpp`
#include <algorithm>
#include <boost/algorithm/string/replace.hpp>
#include <boost/iterator/iterator_facade.hpp>
#include <boost/iterator/iterator_traits.hpp>
#include <boost/lexical_cast.hpp>
#include <climits>
#include <iostream>
#include <list>
#include <memory>
#include <utility>
#include `dbgPrintHelper.hpp`
#include `exceptions.hpp`
#include `library_manager.hpp`
#include `simple_indent.hpp`
#include `structural_manager.hpp`
#include `technology_manager.hpp`
#include `technology_node.hpp`
#include `utility.hpp`
#include `xml_attribute.hpp`
#include `xml_element.hpp`
#include `xml_helper.hpp`
#include `xml_node.hpp`
#include `xml_text_node.hpp`
#include `string_manipulation.hpp`
Functions
std::string legalize (std::string &id)
utility include
std::vector< std::string > get_connections (const xml_element *node)
Detailed Description
This class represents a base circuit object.
Author
Matteo Barbati mbarbati@gmail.com
Christian Pilato pilato@elet.polimi.it
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Function Documentation
get_connections()
std::vector<std::string> get_connections (const xml_element * node)
Definition at line 3364 of file structural_objects.cpp.
References xml_child::get_children().
Referenced by module::xload().
legalize()
std::string legalize (std::string & id) [inline]
utility include
Definition at line 87 of file structural_objects.cpp.
References structural_type_descriptor::s_typeNames.
Referenced by signal_o::xload().