xml_document Class Reference
#include <xml_document.hpp>
Public Member Functions
xml_document (std::string _version=`1.0`)
constructor
void print (std::ostream &os, bool formatted, simple_indent *pp) const override
Print the class.
xml_element * get_root_node () const
Return the root node.
xml_element * create_root_node (const std::string &_name)
Creates the root node.
void write_to_file (const std::string &filename)
Write the document to a file.
void write_to_file_formatted (const std::string &filename)
Write the document to a file.
std::string get_encoding () const
void set_encoding (const std::string &_encoding)
Private Attributes
xml_element * root_node
std::string version
std::string encoding
Additional Inherited Members
Detailed Description
Definition at line 58 of file xml_document.hpp.
Constructor & Destructor Documentation
xml_document()
xml_document::xml_document (std::string _version = `1.0`) [inline], [explicit]
constructor
Definition at line 67 of file xml_document.hpp.
Member Function Documentation
create_root_node()
xml_element* xml_document::create_root_node (const std::string & _name) [inline]
Creates the root node.
Parameters
name The node's name.
Returns
A pointer to the new root node
Definition at line 99 of file xml_document.hpp.
References xml_child::add_child_element(), and root_node.
Referenced by WriteTechnology::Exec(), Evaluation::Exec(), parametric_list_based::InternalExec(), TestVectorParser::ParseXMLFile(), Translator::Translator(), HLS_constraints::write_HLS_constraints_File(), write_structural_File(), DesignCompilerWrapper::write_timing_paths(), Parameter::write_xml_configuration_file(), write_xml_technology_File(), GccWrapper::WriteXml(), HLS_manager::xwrite(), technology_manager::xwrite(), and RTLCharacterization::xwrite_device_file().
get_encoding()
std::string xml_document::get_encoding () const [inline]
Returns
The encoding used in the source from which the document has been loaded.
Definition at line 129 of file xml_document.hpp.
References encoding.
get_root_node()
xml_element* xml_document::get_root_node () const [inline]
Return the root node.
This function does not create a default root node if it doesn't exist.
Returns
A pointer to the root node if it exists, 0 otherwise.
Definition at line 90 of file xml_document.hpp.
References root_node.
print()
void xml_document::print (std::ostream & os, bool formatted, simple_indent * pp) const [inline], [override], [virtual]
Print the class.
Implements xml_node.
Definition at line 74 of file xml_document.hpp.
References xml_child::print().
Referenced by write_to_file(), and write_to_file_formatted().
set_encoding()
void xml_document::set_encoding (const std::string & _encoding) [inline]
Returns
The encoding used in the source from which the document has been loaded.
Definition at line 136 of file xml_document.hpp.
Referenced by BackendFlow::create_xml_scripts().
write_to_file()
void xml_document::write_to_file (const std::string & filename) [inline]
Write the document to a file.
Parameters
filename
Definition at line 108 of file xml_document.hpp.
References print(), and THROW_UNREACHABLE.
write_to_file_formatted()
void xml_document::write_to_file_formatted (const std::string & filename) [inline]
Write the document to a file.
The output is formatted by inserting whitespaces, which is easier to read for a human, but may insert unwanted significant whitespaces. Use with care !
Parameters
filename
Definition at line 120 of file xml_document.hpp.
References print(), STD_CLOSING_CHAR, STD_OPENING_CHAR, and XML_TAB_SIZE.
Referenced by BackendFlow::create_xml_scripts(), WriteTechnology::Exec(), Evaluation::Exec(), parametric_list_based::InternalExec(), TestVectorParser::ParseXMLFile(), Translator::Translator(), HLS_constraints::write_HLS_constraints_File(), write_structural_File(), DesignCompilerWrapper::write_timing_paths(), Parameter::write_xml_configuration_file(), write_xml_technology_File(), GccWrapper::WriteXml(), HLS_manager::xwrite(), technology_manager::xwrite(), and RTLCharacterization::xwrite_device_file().
Field Documentation
encoding
std::string xml_document::encoding [private]
Definition at line 62 of file xml_document.hpp.
Referenced by get_encoding().
root_node
xml_element* xml_document::root_node [private]
Definition at line 60 of file xml_document.hpp.
Referenced by create_root_node(), and get_root_node().
version
std::string xml_document::version [private]
Definition at line 61 of file xml_document.hpp.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_document.hpp