port_swapping Class Reference
superclass include
#include <port_swapping.hpp>
Data Structures
struct PSMultiStart
struct PSVSet
Public Member Functions
port_swapping (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~port_swapping () override
Destructor.
void vertex_levels (std::vector< PSE > &spt_edges, PSVertex root, size_t num_vertices_g, std::vector< PSVSet > &vset)
This function calculates the levels of all te vertices starting from root.
int vertex_distance (std::vector< PSE > &spt_edges, PSVertex root, PSVertex dest, std::vector< PSVSet > &vset)
This function calculates the distances between two vertices in a spanning tree.
PSVertex find_max_degree (CustomOrderedSet< std::pair< PSVertex, unsigned int >> &dSet)
This function finds the maximum degree (out_edges) of a vertex.
void update_degree (PSGraph g2, CustomOrderedSet< std::pair< PSVertex, unsigned int >> &dSet)
This function updates the degree of all the vertices.
PSVertex get_co_tree_vertex (PSVertex vertex, std::vector< PSE > &edges)
This function selects the right vertex from the co_tree_edges vector.
void port_swapping_algorithm (PSGraph g, std::vector< PSMultiStart > &vector_sets, size_t num_vertices_g, PSVertex root)
This function computes the port_swapping.
std::vector< std::pair< PSVertex, unsigned int > > p_swap (PSGraph g)
This function is the wrapper that executes port_swapping_algorithms and extracts the best solution.
bool is_commutative_op (const std::string &operation)
This function checks if an operation is commutative or not.
unsigned int get_results (PSVertex operand, std::vector< std::pair< PSVertex, unsigned int >> results)
This function returns the belonging set of a given vertex.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Private Types
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::no_property, boost::property< boost::edge_color_t, boost::default_color_type > > PSGraph
typedef boost::graph_traits< PSGraph >::edge_descriptor PSEdge
typedef boost::graph_traits< PSGraph >::vertex_descriptor PSVertex
typedef std::pair< unsigned int, unsigned int > PSE
Additional Inherited Members
Detailed Description
superclass include
Class managing a partial module binding based on simple conditions
Definition at line 52 of file port_swapping.hpp.
Member Typedef Documentation
PSE
typedef std::pair<unsigned int, unsigned int> port_swapping::PSE [private]
Definition at line 58 of file port_swapping.hpp.
PSEdge
typedef boost::graph_traits<PSGraph>::edge_descriptor port_swapping::PSEdge [private]
Definition at line 56 of file port_swapping.hpp.
PSGraph
typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, boost::no_property, boost::property<boost::edge_color_t, boost::default_color_type> > port_swapping::PSGraph [private]
Definition at line 55 of file port_swapping.hpp.
PSVertex
typedef boost::graph_traits<PSGraph>::vertex_descriptor port_swapping::PSVertex [private]
Definition at line 57 of file port_swapping.hpp.
Constructor & Destructor Documentation
port_swapping()
port_swapping::port_swapping (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
design_flow_manager is the design flow manager
Definition at line 75 of file port_swapping.cpp.
References DesignFlowStep::debug_level, GET_CLASS, PORT_SWAPPING, and ~port_swapping().
 port_swapping()
port_swapping::~port_swapping () [override], [default]
Destructor.
Referenced by port_swapping().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > port_swapping::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 83 of file port_swapping.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
find_max_degree()
port_swapping::PSVertex port_swapping::find_max_degree (CustomOrderedSet< std::pair< PSVertex, unsigned int >> & dSet)
This function finds the maximum degree (out_edges) of a vertex.
Parameters
dSet structure with all the vertices and relative degrees
Returns
Vertex which has the max degree
Definition at line 209 of file port_swapping.cpp.
References max().
Referenced by port_swapping_algorithm().
get_co_tree_vertex()
port_swapping::PSVertex port_swapping::get_co_tree_vertex (PSVertex vertex, std::vector< PSE > & edges)
This function selects the right vertex from the co_tree_edges vector.
Parameters
vertex
edges vector of edges from which is taken the right one and from that the right vertex
Returns
chosen vertex
Definition at line 229 of file port_swapping.cpp.
Referenced by port_swapping_algorithm().
get_results()
unsigned int port_swapping::get_results (PSVertex operand, std::vector< std::pair< PSVertex, unsigned int >> results)
This function returns the belonging set of a given vertex.
Parameters
operand which represents a vertex in the graph
results vector containing all the vertices and relative belonging sets
Returns
belonging set of the operand
Definition at line 412 of file port_swapping.cpp.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status port_swapping::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
no more than one running state could be considered
TOBEFIXED
Implements HLSFunctionStep.
Definition at line 422 of file port_swapping.cpp.
References hls::allocation_information, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FDFG, hls::functionId, HLSFunctionStep::funId, fu_binding::get_assign(), fu_binding::get_index(), GET_NAME, liveness::get_op_where_defined(), reg_binding::get_register(), get_results(), liveness::get_state_where_end(), liveness::get_state_where_run(), StorageValueInformation::get_storage_value_index(), AllocationInformation::get_string_name(), GET_TYPE, liveness::has_op_where_defined(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, INFINITE_UINT, StorageValueInformation::is_a_storage_value(), is_commutative_op(), tree_helper::is_parameter(), DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, p_swap(), BehavioralHelper::PrintVariable(), hls::Rfu, hls::Rliv, hls::Rreg, SET_A, SET_AB, SET_B, fu_binding::set_ports_are_swapped(), hls::storage_value_information, STR, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, TYPE_PHI, and UNCHANGED.
is_commutative_op()
bool port_swapping::is_commutative_op (const std::string & operation)
This function checks if an operation is commutative or not.
Parameters
operation name
Returns
true if it is a commutative binary operation, false otherwise
Definition at line 406 of file port_swapping.cpp.
References STOK, TOK_BIT_AND_EXPR, TOK_BIT_IOR_EXPR, TOK_BIT_XOR_EXPR, TOK_EQ_EXPR, TOK_MULT_EXPR, TOK_NE_EXPR, TOK_PLUS_EXPR, TOK_POINTER_PLUS_EXPR, TOK_WIDEN_MULT_EXPR, and TOK_WIDEN_SUM_EXPR.
Referenced by InternalExec().
p_swap()
std::vector< std::pair< port_swapping::PSVertex, unsigned int > > port_swapping::p_swap (PSGraph g)
This function is the wrapper that executes port_swapping_algorithms and extracts the best solution.
Parameters
g starting graph
Returns
vector of vertices and relative results. Each vertex will contain the belonging set (A, B, AB)
Definition at line 380 of file port_swapping.cpp.
References port_swapping::PSMultiStart::cardinality, max(), port_swapping_algorithm(), and port_swapping::PSMultiStart::vset.
Referenced by InternalExec().
port_swapping_algorithm()
void port_swapping::port_swapping_algorithm (PSGraph g, std::vector< PSMultiStart > & vector_sets, size_t num_vertices_g, PSVertex root)
This function computes the port_swapping.
Parameters
g graph on which the algorithm is computed
vector_sets vector that will contain all the runs of the algorithm. It will contain the best solution
num_vertices_g number of vertices in the graph
root vertex from which the spanning tree is calculated
Definition at line 239 of file port_swapping.cpp.
References port_swapping::PSVSet::belongs, port_swapping::PSMultiStart::cardinality, port_swapping::PSMultiStart::co_tree_vector_edges, find_max_degree(), get_co_tree_vertex(), port_swapping::PSVSet::level, port_swapping::PSMultiStart::odd_co_tree_vector_edges, DesignFlowStep::parameters, SET_AB, port_swapping::PSMultiStart::spt_vector_edges, update_degree(), port_swapping::PSVSet::v, vertex_distance(), vertex_levels(), and port_swapping::PSMultiStart::vset.
Referenced by p_swap().
update_degree()
void port_swapping::update_degree (PSGraph g2, CustomOrderedSet< std::pair< PSVertex, unsigned int >> & dSet)
This function updates the degree of all the vertices.
Parameters
g2 graph on which the degree of the vertices must be calculated
dSet set to be updated with all the vertices and relative degree
Definition at line 222 of file port_swapping.cpp.
Referenced by port_swapping_algorithm().
vertex_distance()
int port_swapping::vertex_distance (std::vector< PSE > & spt_edges, PSVertex root, PSVertex dest, std::vector< PSVSet > & vset)
This function calculates the distances between two vertices in a spanning tree.
Parameters
spt_edges edges of the spanning tree
root starting vertex
num_vertices_g number of vertices in the graph
vset structure that contains the vertices and the relative level and the belongings
Definition at line 156 of file port_swapping.cpp.
References THROW_ASSERT, and port_swapping::PSVSet::v.
Referenced by port_swapping_algorithm().
vertex_levels()
void port_swapping::vertex_levels (std::vector< PSE > & spt_edges, PSVertex root, size_t num_vertices_g, std::vector< PSVSet > & vset)
This function calculates the levels of all te vertices starting from root.
Parameters
spt_edges edges of the spanning tree
root starting vertex
num_vertices_g number of vertices in the graph
vset structure that contains the vertices and the relative level and the belongings
Definition at line 114 of file port_swapping.cpp.
References test_panda::level, SET_A, SET_B, and port_swapping::PSVSet::v.
Referenced by port_swapping_algorithm().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/port_swapping.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/port_swapping.cpp