liberty_model Class Reference
#include <liberty_model.hpp>
Public Member Functions
void xwrite (xml_element *pin_node, const std::string &output_pin) override
void add_timing_group (const std::string &output, const CustomOrderedSet< std::string > &inputs, const timing_groupRef &tg)
std::map< std::string, std::map< CustomOrderedSet< std::string >, timing_groupRef > > get_timing_groups () const
void set_timing_groups (const std::map< std::string, std::map< CustomOrderedSet< std::string >, timing_groupRef >> &timing_groups_)
bool has_timing_groups () const
void set_drive_strength (double value)
double get_drive_strength () const
void set_skew_value (double value)
double get_skew_value () const
 Constructors and destructors.
liberty_model (const ParameterConstRef Param)
Constructor.
~liberty_model () override
Destructor.
Private Attributes
double drive_strength
double skew
std::map< std::string, std::map< CustomOrderedSet< std::string >, timing_groupRef > > timing_groups
Additional Inherited Members
Detailed Description
Definition at line 52 of file liberty_model.hpp.
Constructor & Destructor Documentation
liberty_model()
liberty_model::liberty_model (const ParameterConstRef Param) [explicit]
Constructor.
Definition at line 48 of file liberty_model.cpp.
References ~liberty_model().
 liberty_model()
liberty_model::~liberty_model () [override], [default]
Destructor.
Referenced by liberty_model().
Member Function Documentation
add_timing_group()
void liberty_model::add_timing_group (const std::string & output, const CustomOrderedSet< std::string > & inputs, const timing_groupRef & tg)
Definition at line 66 of file liberty_model.cpp.
References timing_groups.
get_drive_strength()
double liberty_model::get_drive_strength () const
Definition at line 76 of file liberty_model.cpp.
References drive_strength.
Referenced by has_timing_groups().
get_skew_value()
double liberty_model::get_skew_value () const
Definition at line 86 of file liberty_model.cpp.
References skew.
Referenced by has_timing_groups().
get_timing_groups()
std::map<std::string, std::map<CustomOrderedSet<std::string>, timing_groupRef> > liberty_model::get_timing_groups () const [inline]
Definition at line 80 of file liberty_model.hpp.
References set_timing_groups(), and timing_groups.
has_timing_groups()
bool liberty_model::has_timing_groups () const [inline]
Definition at line 87 of file liberty_model.hpp.
References get_drive_strength(), get_skew_value(), set_drive_strength(), and set_skew_value().
set_drive_strength()
void liberty_model::set_drive_strength (double value)
Definition at line 71 of file liberty_model.cpp.
References drive_strength.
Referenced by has_timing_groups().
set_skew_value()
void liberty_model::set_skew_value (double value)
Definition at line 81 of file liberty_model.cpp.
References skew.
Referenced by has_timing_groups().
set_timing_groups()
void liberty_model::set_timing_groups (const std::map< std::string, std::map< CustomOrderedSet< std::string >, timing_groupRef >> & timing_groups_)
Definition at line 91 of file liberty_model.cpp.
References timing_groups.
Referenced by get_timing_groups().
xwrite()
void liberty_model::xwrite (xml_element * pin_node, const std::string & output_pin) [override], [virtual]
Implements time_model.
Definition at line 54 of file liberty_model.cpp.
References xml_child::add_child_element(), and timing_groups.
Field Documentation
drive_strength
double liberty_model::drive_strength [private]
Definition at line 54 of file liberty_model.hpp.
Referenced by get_drive_strength(), and set_drive_strength().
skew
double liberty_model::skew [private]
Definition at line 56 of file liberty_model.hpp.
Referenced by get_skew_value(), and set_skew_value().
timing_groups
std::map<std::string, std::map<CustomOrderedSet<std::string>, timing_groupRef> > liberty_model::timing_groups [private]
Definition at line 58 of file liberty_model.hpp.
Referenced by add_timing_group(), get_timing_groups(), set_timing_groups(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/time/liberty_model.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/time/liberty_model.cpp