BBGraph Struct Reference
Class used to describe a particular graph with basic blocks as nodes.
#include <basic_block.hpp>
Public Member Functions
BBGraph (const BBGraphsCollectionRef bb_graphs_collection, int selector)
Standard constructor.
BBGraph (const BBGraphsCollectionRef bb_graphs_collection, int selector, CustomUnorderedSet< vertex > &sub)
Sub-graph constructor.
virtual ~BBGraph () override=default
Destructor.
void WriteDot (const std::string &file_name, const int detail_level=0) const
Writes this graph in dot format.
void WriteDot (const std::string &file_name, const CustomUnorderedSet< vertex > &annotated, const int detail_level=0) const
Write this graph in dot format with some basic blocks highlightened.
size_t num_bblocks () const
Returns the number of basic blocks contained into the graph.
BBNodeInfoRef GetBBNodeInfo (const vertex node)
Return the info associated with a basic block.
const BBNodeInfoConstRef CGetBBNodeInfo (const vertex node) const
Return the info associated with a basic block.
BBEdgeInfoRef GetBBEdgeInfo (const EdgeDescriptor e)
Returns the info associated with an edge.
const BBEdgeInfoConstRef CGetBBEdgeInfo (const EdgeDescriptor e) const
Returns the info associated with an edge.
BBGraphInfoRef GetBBGraphInfo ()
Returns the property associated with the graph.
const BBGraphInfoConstRef CGetBBGraphInfo () const
Returns the property associated with the graph.
Additional Inherited Members
Detailed Description
Class used to describe a particular graph with basic blocks as nodes.
Definition at line 320 of file basic_block.hpp.
Constructor & Destructor Documentation
BBGraph() [1/2]
BBGraph::BBGraph (const BBGraphsCollectionRef bb_graphs_collection, int selector)
Standard constructor.
Parameters
BBGraphsCollection is the bulk graph.
selector is the selector used to filter the bulk graph.
Definition at line 142 of file basic_block.cpp.
BBGraph() [2/2]
BBGraph::BBGraph (const BBGraphsCollectionRef bb_graphs_collection, int selector, CustomUnorderedSet< vertex > & sub)
Sub-graph constructor.
Parameters
bb_graphs_collection is the bulk graph.
selector is the selector used to filter the bulk graph.
sub is the set of vertices on which the graph is filtered.
Definition at line 146 of file basic_block.cpp.
 BBGraph()
virtual BBGraph::~BBGraph () [override], [virtual], [default]
Destructor.
Member Function Documentation
CGetBBEdgeInfo()
const BBEdgeInfoConstRef BBGraph::CGetBBEdgeInfo (const EdgeDescriptor e) const [inline]
Returns the info associated with an edge.
Definition at line 394 of file basic_block.hpp.
References graph::CGetEdgeInfo().
Referenced by BB_based_stg::InternalExec(), BBCdgComputation::InternalExec(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
CGetBBGraphInfo()
const BBGraphInfoConstRef BBGraph::CGetBBGraphInfo () const [inline]
Returns the property associated with the graph.
Returns
the proprty associated with the graph
Definition at line 412 of file basic_block.hpp.
References graph::CGetGraphInfo().
Referenced by liveness::are_in_conflict(), Loops::BuildZeroLoop(), Vectorize::ClassifyTreeNode(), CWriter::compute_phi_nodes(), Loops::DetectLoops(), FSM_NI_SSA_liveness::InternalExec(), BB_based_stg::InternalExec(), dom_post_dom_computation::InternalExec(), BuildVirtualPhi::InternalExec(), MultipleEntryIfReduction::InternalExec(), operations_cfg_computation::InternalExec(), SDCScheduling::InternalExec(), BB_based_stg::optimize_cycles(), Vectorize::Transform(), WriteDot(), EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
CGetBBNodeInfo()
const BBNodeInfoConstRef BBGraph::CGetBBNodeInfo (const vertex node) const [inline]
Return the info associated with a basic block.
Parameters
node is the basic block vertex to be considered
Returns
the info associated with a basic block
Definition at line 378 of file basic_block.hpp.
References graph::CGetNodeInfo().
Referenced by SDCScheduling::AddDelayConstraints(), liveness::are_in_conflict(), pragma_manager::CheckAddOmpFor(), pragma_manager::CheckAddOmpSimd(), pragma_manager::CheckOmpFor(), Vectorize::ClassifyTreeNode(), Loops::DetectIrreducibleLoop(), Loops::DetectLoops(), DataDependenceComputation::do_dependence_reduction(), Loop::GetRecursivelyOps(), SDCScheduling::Initialize(), FSM_NI_SSA_liveness::InternalExec(), BB_based_stg::InternalExec(), AddArtificialCallFlowEdges::InternalExec(), BBReachabilityComputation::InternalExec(), LoopsAnalysisBambu::InternalExec(), AddOpLoopFlowEdges::InternalExec(), bb_feedback_edges_computation::InternalExec(), op_feedback_edges_computation::InternalExec(), AddBbEcfgEdges::InternalExec(), BuildVirtualPhi::InternalExec(), CSE::InternalExec(), MultipleEntryIfReduction::InternalExec(), operations_cfg_computation::InternalExec(), Vectorize::InternalExec(), SDCScheduling::InternalExec(), parametric_list_based::InternalExec(), Loop::Loop(), liveness::non_in_parallel(), BBVertexSorter::operator()(), BB_based_stg::optimize_cycles(), BasicBlocksProfilingCWriter::print_edge(), CWriter::schedule_copies(), SDCSorter::SDCSorter(), Loops::tarjan_scc(), Vectorize::Transform(), Loops::WriteDot(), EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), CWriter::writeRoutineInstructions_rec(), and ProfilingInformation::WriteToXml().
GetBBEdgeInfo()
BBEdgeInfoRef BBGraph::GetBBEdgeInfo (const EdgeDescriptor e) [inline]
Returns the info associated with an edge.
Definition at line 386 of file basic_block.hpp.
References graph::GetEdgeInfo().
GetBBGraphInfo()
BBGraphInfoRef BBGraph::GetBBGraphInfo () [inline]
Returns the property associated with the graph.
Returns
the property associated with the graph
Definition at line 403 of file basic_block.hpp.
References graph::GetGraphInfo().
GetBBNodeInfo()
BBNodeInfoRef BBGraph::GetBBNodeInfo (const vertex node) [inline]
Return the info associated with a basic block.
Parameters
node is the basic block vertex to be considered
Returns
the info associated with a basic block
Definition at line 368 of file basic_block.hpp.
References graph::GetNodeInfo().
Referenced by pragma_manager::CheckAddOmpSimd(), operations_cfg_computation::Initialize(), BBCdgComputation::InternalExec(), loops_computation::InternalExec(), BuildVirtualPhi::InternalExec(), MultipleEntryIfReduction::InternalExec(), multi_way_if::InternalExec(), and Vectorize::Transform().
num_bblocks()
size_t BBGraph::num_bblocks () const
Returns the number of basic blocks contained into the graph.
Definition at line 169 of file basic_block.cpp.
WriteDot() [1/2]
void BBGraph::WriteDot (const std::string & file_name, const int detail_level = 0) const
Writes this graph in dot format.
Parameters
file_name is the file where the graph has to be printed
detail_level is the detail level of the printed graph
Definition at line 150 of file basic_block.cpp.
Referenced by Loops::DetectLoops(), simple_code_motion::InternalExec(), and FunctionFrontendFlowStep::WriteBBGraphDot().
WriteDot() [2/2]
void BBGraph::WriteDot (const std::string & file_name, const CustomUnorderedSet< vertex > & annotated, const int detail_level = 0) const
Write this graph in dot format with some basic blocks highlightened.
Parameters
file_name is the name of the file
detail_level is the detail level of the printed graph
annotated is the set of the vertices to be annotated
Definition at line 156 of file basic_block.cpp.
References CGetBBGraphInfo(), graph::collection, test_panda::full_name, and graphs_collection::parameters.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/basic_block.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/basic_block.cpp