/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/bit_lattice.hpp File Reference
#include `frontend_flow_step.hpp`
#include <string>
#include `custom_map.hpp`
#include `custom_set.hpp`
#include <deque>
#include `refcount.hpp`
Data Structures
class BitLatticeManipulator
Enumerations
enum bit_lattice { bit_lattice::U,
bit_lattice::ZERO,
bit_lattice::ONE,
bit_lattice::X
 }
Functions
CONSTREF_FORWARD_DECL (Parameter)
Header include.
CONSTREF_FORWARD_DECL (tree_manager)
REF_FORWARD_DECL (tree_node)
std::deque< bit_lattice > create_u_bitstring (size_t lenght)
Creates a bitstring containing bits initialized at <U>
std::deque< bit_lattice > create_x_bitstring (unsigned int lenght)
Create a bitstring containing bits initialized at <X>
std::deque< bit_lattice > create_bitstring_from_constant (long long int value_int, unsigned int length, bool signed_value)
Creates a bitstring from a constant input.
std::string bitstring_to_string (const std::deque< bit_lattice > &bitstring)
Translates a bitstring (expressed as an std::deque of bit_lattice) into a string of characters.
std::deque< bit_lattice > string_to_bitstring (const std::string &s)
inverse of bitstring_to_string
bool bitstring_constant (const std::deque< bit_lattice > &a)
Checks if a bitstring is constant.
Detailed Description
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Enumeration Type Documentation
bit_lattice
enum bit_lattice [strong]
Enumerator
U
ZERO
ONE
X
Definition at line 61 of file bit_lattice.hpp.
Function Documentation
bitstring_constant()
bool bitstring_constant (const std::deque< bit_lattice > & a)
Checks if a bitstring is constant.
Parameters
a the bitstring to be checked
Returns
TRUE if the bitstring contains only 1, 0 or X but not U values
Definition at line 568 of file bit_lattice.cpp.
References U, and X.
Referenced by Bit_Value::backward().
bitstring_to_string()
std::string bitstring_to_string (const std::deque< bit_lattice > & bitstring)
Translates a bitstring (expressed as an std::deque of bit_lattice) into a string of characters.
Definition at line 514 of file bit_lattice.cpp.
References ONE, THROW_ERROR, U, X, and ZERO.
Referenced by Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), Bit_Value::initialize(), Bit_Value::manage_forward_binary_operands(), BitLatticeManipulator::mix(), Bit_Value::print_bitstring_map(), and Bit_Value::update_IR().
CONSTREF_FORWARD_DECL() [1/2]
CONSTREF_FORWARD_DECL (Parameter)
Header include.
STD include STL includes
CONSTREF_FORWARD_DECL() [2/2]
CONSTREF_FORWARD_DECL (tree_manager)
create_bitstring_from_constant()
std::deque<bit_lattice> create_bitstring_from_constant (long long int value_int, unsigned int length, bool signed_value)
Creates a bitstring from a constant input.
Parameters
value_int integer constant
length the length of the bitstring to be generated
signed_value specified if this bitstring can have negative values
Returns
bitstring generated from the integer constant
Definition at line 486 of file bit_lattice.cpp.
References ONE, and ZERO.
Referenced by BitLatticeManipulator::constructor_bitstring(), BitValueIPA::Exec(), Bit_Value::initialize(), and BitLatticeManipulator::string_cst_bitstring().
create_u_bitstring()
std::deque<bit_lattice> create_u_bitstring (size_t lenght)
Creates a bitstring containing bits initialized at <U>
Parameters
lenght the lenght of the bitstring
Returns
a bitstring of the specified length containing <U> values.
Definition at line 476 of file bit_lattice.cpp.
References U.
Referenced by Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), BitLatticeManipulator::constructor_bitstring(), BitValueIPA::Exec(), Bit_Value::forward(), Bit_Value::forward_transfer(), Bit_Value::initialize(), and Bit_Value::manage_forward_binary_operands().
create_x_bitstring()
std::deque<bit_lattice> create_x_bitstring (unsigned int lenght)
Create a bitstring containing bits initialized at <X>
Parameters
lenght the lenght of the bitstring
Returns
a bitstring of the specified length containing <X> values.
Definition at line 481 of file bit_lattice.cpp.
References X.
Referenced by Bit_Value::backward_compute_result_from_uses(), BitValueIPA::Exec(), and Bit_Value::forward().
REF_FORWARD_DECL()
REF_FORWARD_DECL (tree_node)
string_to_bitstring()
std::deque<bit_lattice> string_to_bitstring (const std::string & s)
inverse of bitstring_to_string
Definition at line 541 of file bit_lattice.cpp.
References ONE, THROW_ERROR, U, X, and ZERO.
Referenced by Bit_Value::backward_compute_result_from_uses(), Bit_Value::backward_transfer(), BitValueIPA::Exec(), Bit_Value::forward_transfer(), and Bit_Value::initialize().