TestbenchValuesCGeneration Class Reference
TestbenchValuesCGeneration is the step which generates values.txt exploiting values.c.
#include <testbench_values_c_generation.hpp>
Public Member Functions
TestbenchValuesCGeneration (const ParameterConstRef parameters, const HLS_managerRef hls_manager, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
virtual ~TestbenchValuesCGeneration ()
Destructor.
DesignFlowStep_Status Exec ()
Execute the step.
bool HasToBeExecuted () const
Check if this step has actually to be executed.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type)
Compute the relationships of this step with other steps.
Protected Member Functions
virtual void Initialize ()
Initialize the step (i.e., like a constructor, but executed just before exec.
virtual const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Compute the relationship of this step.
Protected Attributes
const std::string output_directory
output directory
Additional Inherited Members
Detailed Description
TestbenchValuesCGeneration is the step which generates values.txt exploiting values.c.
Definition at line 62 of file testbench_values_c_generation.hpp.
Constructor & Destructor Documentation
TestbenchValuesCGeneration()
TestbenchValuesCGeneration::TestbenchValuesCGeneration (const ParameterConstRef parameters, const HLS_managerRef hls_manager, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
parameters is the set of the input parameters
hls_manager is the HLS manager
design_flow_manager is the design flow manager
Definition at line 95 of file testbench_values_c_generation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, output_directory, and DesignFlowStep::parameters.
 TestbenchValuesCGeneration()
TestbenchValuesCGeneration::~TestbenchValuesCGeneration () [virtual]
Destructor.
Definition at line 103 of file testbench_values_c_generation.cpp.
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > TestbenchValuesCGeneration::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 107 of file testbench_values_c_generation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TEST_VECTOR_PARSER, THROW_UNREACHABLE, and TOP_FUNCTION.
ComputeRelationships()
void TestbenchValuesCGeneration::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [virtual]
Compute the relationships of this step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from HLS_step.
Definition at line 286 of file testbench_values_c_generation.cpp.
References CBackend::CB_SEQUENTIAL, HLS_step::ComputeRelationships(), CBackend::ComputeSignature(), CBackendStepFactory::CreateCBackendStep(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), output_directory, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, STR, STR_CST_testbench_generation_basename, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status TestbenchValuesCGeneration::Exec () [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 131 of file testbench_values_c_generation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_MINIMUM, HLS_step::HLSMgr, INDENT_DBG_MEX, IsError(), O0, output_directory, PandaSystem(), DesignFlowStep::parameters, STR, STR_CST_testbench_generation_basename, SUCCESS, THROW_ASSERT, and THROW_ERROR.
HasToBeExecuted()
bool TestbenchValuesCGeneration::HasToBeExecuted () const [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 281 of file testbench_values_c_generation.cpp.
Initialize()
void TestbenchValuesCGeneration::Initialize () [protected], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Header include.
Autoheader includes . include behavior includes constants include design_flows includes design_flows/backend/ToC/progModels include design_flows/backend/ToC include HLS include tree include utility includes wrapper/treegcc include
Reimplemented from DesignFlowStep.
Definition at line 91 of file testbench_values_c_generation.cpp.
Field Documentation
output_directory
const std::string TestbenchValuesCGeneration::output_directory [protected]
output directory
Definition at line 66 of file testbench_values_c_generation.hpp.
Referenced by ComputeRelationships(), Exec(), and TestbenchValuesCGeneration().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_values_c_generation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_values_c_generation.cpp