FunctionalUnitStep Class Reference
Step which loads device dependent technology information.
#include <functional_unit_step.hpp>
Public Member Functions
FunctionalUnitStep (const target_managerRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~FunctionalUnitStep () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
virtual void AnalyzeCell (functional_unit *fu, const unsigned int prec, const std::vector< std::string > &portsize_parameters, const size_t portsize_index, const std::vector< std::string > &pipe_parameters, const size_t stage_index, const unsigned int constPort, const bool is_commutative, size_t max_lut_size)=0
Analyze the single cell.
virtual void AnalyzeFu (const technology_nodeRef fu)
Analyze all the cells built starting from a template.
technology_nodeRef create_template_instance (const technology_nodeRef &fu_template, std::string &name, const target_deviceRef &device, unsigned int prec)
Create a template instance to be specialized.
Protected Attributes
const technology_managerRef TM
Technology manager.
const target_managerRef target
target information
unsigned int has_first_synthesis_id
The id of the first analyzed cell of a sequence of cells which differ for the position of the constant.
CustomMap< unsigned int, unsigned int > DSP_y_to_DSP_x
The sizes of available DSPs.
Additional Inherited Members
Detailed Description
Step which loads device dependent technology information.
Definition at line 61 of file functional_unit_step.hpp.
Constructor & Destructor Documentation
FunctionalUnitStep()
FunctionalUnitStep::FunctionalUnitStep (const target_managerRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
target is the target
design_flow_manager is the design flow manager
parameters is the set of input parameters
Header class circuit include HLS/module_allocation HLS/scheduling include STD include STL includes technology include technology/physical_library include technology/physical_library/models includes technology/target_device include utility include
Definition at line 87 of file functional_unit_step.cpp.
References ~FunctionalUnitStep().
 FunctionalUnitStep()
FunctionalUnitStep::~FunctionalUnitStep () [override], [default]
Destructor.
Referenced by FunctionalUnitStep().
Member Function Documentation
AnalyzeCell()
virtual void FunctionalUnitStep::AnalyzeCell (functional_unit * fu, const unsigned int prec, const std::vector< std::string > & portsize_parameters, const size_t portsize_index, const std::vector< std::string > & pipe_parameters, const size_t stage_index, const unsigned int constPort, const bool is_commutative, size_t max_lut_size) [protected], [pure virtual]
Analyze the single cell.
Parameters
fu is the cell
prec is the precision
portsize_parameters is the size of parameters
portsize_index
pipe_parameters
stage_index
constPort is the index of the constant port
Implemented in RTLCharacterization, and GenerateFuList.
Referenced by AnalyzeFu().
AnalyzeFu()
void FunctionalUnitStep::AnalyzeFu (const technology_nodeRef fu) [protected], [virtual]
Analyze all the cells built starting from a template.
Parameters
fu is the corresponding functional unit
previous characterization is not considered
check for a single port
check if the resource can be pipelined
Definition at line 94 of file functional_unit_step.cpp.
References library_manager::add(), AnalyzeCell(), AND_GATE_STD, structural_type_descriptor::BOOL, CLOCK_PORT_NAME, CONSTANT_STD, create_template_instance(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DEMUX_GATE_STD, DONE_PORT_NAME, DSP_y_to_DSP_x, NP_functionality::exist_NP_functionality(), NP_functionality::FLOPOCO_PROVIDED, functional_unit::fu_template_parameters, technology_manager::get_fu(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), technology_manager::get_library(), technology_manager::get_library_manager(), technology_node::get_name(), functional_unit::get_name(), module::get_out_port(), module::get_out_port_size(), target_device::get_parameter(), structural_object::get_typeRef(), has_first_synthesis_id, target_device::has_parameter(), INDENT_DBG_MEX, LUT_GATE_STD, MUX_GATE_STD, NAND_GATE_STD, NOR_GATE_STD, OR_GATE_STD, READ_COND_STD, RESET_PORT_NAME, resize_to_1_8_16_32_64_128_256_512(), SplitString(), START_PORT_NAME, STR, NP_functionality::SYSTEM_VERILOG_PROVIDED, target, THROW_ASSERT, THROW_ERROR, TM, structural_type_descriptor::type, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::VECTOR_UINT, NP_functionality::VERILOG_PROVIDED, NP_functionality::VHDL_PROVIDED, XNOR_GATE_STD, and XOR_GATE_STD.
Referenced by GenerateFuList::Exec(), and RTLCharacterization::Exec().
create_template_instance()
technology_nodeRef FunctionalUnitStep::create_template_instance (const technology_nodeRef & fu_template, std::string & name, const target_deviceRef & device, unsigned int prec) [protected]
Create a template instance to be specialized.
Definition at line 473 of file functional_unit_step.cpp.
References area_model::create_model(), time_model::create_model(), functional_unit::functional_unit_name, target_device::get_type(), operation::operation_name, DesignFlowStep::parameters, time_model::set_execution_time(), and THROW_ASSERT.
Referenced by AnalyzeFu().
Initialize()
void FunctionalUnitStep::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Reimplemented in RTLCharacterization.
Definition at line 454 of file functional_unit_step.cpp.
References DSP_y_to_DSP_x, target_device::get_parameter(), target_device::has_parameter(), SplitString(), target, and THROW_ASSERT.
Referenced by RTLCharacterization::Initialize().
Field Documentation
DSP_y_to_DSP_x
CustomMap<unsigned int, unsigned int> FunctionalUnitStep::DSP_y_to_DSP_x [protected]
The sizes of available DSPs.
Definition at line 74 of file functional_unit_step.hpp.
Referenced by AnalyzeFu(), and Initialize().
has_first_synthesis_id
unsigned int FunctionalUnitStep::has_first_synthesis_id [protected]
The id of the first analyzed cell of a sequence of cells which differ for the position of the constant.
Definition at line 71 of file functional_unit_step.hpp.
Referenced by GenerateFuList::AnalyzeCell(), RTLCharacterization::AnalyzeCell(), and AnalyzeFu().
target
const target_managerRef FunctionalUnitStep::target [protected]
target information
Definition at line 68 of file functional_unit_step.hpp.
Referenced by RTLCharacterization::AnalyzeCell(), AnalyzeFu(), RTLCharacterization::Exec(), and Initialize().
TM
const technology_managerRef FunctionalUnitStep::TM [protected]
Technology manager.
Definition at line 65 of file functional_unit_step.hpp.
Referenced by RTLCharacterization::add_input_register(), RTLCharacterization::add_output_register(), RTLCharacterization::AnalyzeCell(), AnalyzeFu(), GenerateFuList::Exec(), RTLCharacterization::fix_execution_time_std(), RTLCharacterization::fix_muxes(), RTLCharacterization::fix_proxies_execution_time_std(), and RTLCharacterization::Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/functional_unit_step.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/functional_unit_step.cpp