tree_panda_gcc_parameter Class Reference
Superclass include.
#include <tree-panda-gcc-Parameter.hpp>
Public Member Functions
tree_panda_gcc_parameter (const std::string &program_name, int argc, char **const argv)
Constructor.
~tree_panda_gcc_parameter () override
Destructor.
int Exec () override
Execute parameter parsing.
void SetDefaults () override
Sets the default values for the Zebu tool.
Private Member Functions
void CheckParameters () override
Checks parameter values to set implicit one.
void PrintHelp (std::ostream &os) const override
Print the usage of this tool.
void PrintProgramName (std::ostream &os) const override
Print the name of the program to be included in the header.
Additional Inherited Members
Detailed Description
Superclass include.
Utility include
Definition at line 51 of file tree-panda-gcc-Parameter.hpp.
Constructor & Destructor Documentation
tree_panda_gcc_parameter()
tree_panda_gcc_parameter::tree_panda_gcc_parameter (const std::string & program_name, int argc, char **const argv)
Constructor.
Parameters
program_name is the name of the executable
argc is the number of arguments
argv is the array of arguments passed to program.
Definition at line 109 of file tree-panda-gcc-Parameter.cpp.
References SetDefaults(), and ~tree_panda_gcc_parameter().
 tree_panda_gcc_parameter()
tree_panda_gcc_parameter::~tree_panda_gcc_parameter () [override], [default]
Destructor.
Referenced by tree_panda_gcc_parameter().
Member Function Documentation
CheckParameters()
void tree_panda_gcc_parameter::CheckParameters () [override], [private], [virtual]
Checks parameter values to set implicit one.
Implements Parameter.
Definition at line 361 of file tree-panda-gcc-Parameter.cpp.
References Parameter::CheckParameters().
Referenced by Exec().
Exec()
int tree_panda_gcc_parameter::Exec () [override], [virtual]
Execute parameter parsing.
variable used into option parsing
the default of tree-panda-gcc is the silent mode so nothing has to be done
do nothing passed to tree-panda-gcc when it work as ld
Implements Parameter.
Definition at line 116 of file tree-panda-gcc-Parameter.cpp.
References Parameter::argc, Parameter::argv, CheckParameters(), COMMON_LONG_OPTIONS, COMMON_SHORT_OPTIONS_STRING, CT_NO_GCC, exit_code, GCC_LONG_OPTIONS, GCC_SHORT_OPTIONS_STRING, GetExtension(), Parameter::isOption(), Parameter::ManageDefaultOptions(), OPT_END_GROUP, OPT_GC_SECTIONS, OPT_IPLUGINDIR, OPT_MF, OPT_MINUS_INCLUDE, OPT_MINUS_MAP, OPT_MQ, OPT_MT, OPT_PRINT_FILE_NAME, OPT_START_GROUP, PARAMETER_NOTPARSED, PARAMETER_PARSED, Parameter::PrintUsage(), Parameter::setOption(), STR_CST_string_separator, THROW_ERROR, and Parameter::write_xml_configuration_file().
PrintHelp()
void tree_panda_gcc_parameter::PrintHelp (std::ostream & os) const [override], [private], [virtual]
Print the usage of this tool.
Parameters
os is the stream where the message has to be printed
Implements Parameter.
Definition at line 366 of file tree-panda-gcc-Parameter.cpp.
References Parameter::PrintGeneralOptionsUsage(), and Parameter::PrintOutputOptionsUsage().
PrintProgramName()
void tree_panda_gcc_parameter::PrintProgramName (std::ostream & os) const [override], [private], [virtual]
Print the name of the program to be included in the header.
Parameters
os is the stream on which the program name has to be printed
Implements Parameter.
Definition at line 381 of file tree-panda-gcc-Parameter.cpp.
SetDefaults()
void tree_panda_gcc_parameter::SetDefaults () [override], [virtual]
Sets the default values for the Zebu tool.
Debugging level
Output level
---------- frontend analysis ----------//
Implements Parameter.
Definition at line 393 of file tree-panda-gcc-Parameter.cpp.
References DEBUG_LEVEL_NONE, MINIMAL_INTERFACE_GENERATION, O0, OUTPUT_LEVEL_NONE, Parameter::setOption(), and THROW_ERROR.
Referenced by tree_panda_gcc_parameter().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree-panda-gcc-Parameter.hpp
/home/osboxes/bambu/PandA-bambu/src/tree-panda-gcc-Parameter.cpp