vcd_utility Class Reference
#include <vcd_utility.hpp>
Public Member Functions
vcd_utility (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~vcd_utility () override=default
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
unsigned long long GetClockPeriod (const vcd_parser::vcd_trace_t &vcd_trace) const
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
bool detect_mismatch (const vcd_trace_head &t, const uint64_t c_context, const std::string &c_val)
bool detect_regular_mismatch (const vcd_trace_head &t, const std::string &c_val, const std::string &vcd_val) const
bool detect_binary_float_mismatch (const std::string &c_val, const std::string &resized_vcd_val) const
bool detect_binary_double_mismatch (const std::string &c_val, const std::string &resized_vcd_val) const
bool detect_address_mismatch (const DiscrepancyOpInfo &op_info, const uint64_t c_context, const std::string &c_val, const std::string &vcd_val, unsigned int &base_index)
bool detect_fixed_address_mismatch (const DiscrepancyOpInfo &op_info, const uint64_t c_context, const std::string &c_val, const std::string &vcd_val, const unsigned int base_index) const
bool detect_mismatch_element (const vcd_trace_head &t, const uint64_t c_context, const std::string &c_val, const unsigned int el_idx)
bool detect_mismatch_simple (const vcd_trace_head &t, const uint64_t c_context, const std::string &c_val, const unsigned int el_idx, const std::string::size_type first_c_bit, const std::string::size_type c_size)
void update_discr_list (const vcd_trace_head &t, const uint64_t c_context, const std::string &c_val, const unsigned int el_idx, const std::string::size_type first_c_bit, const std::string::size_type c_size, const unsigned int base_index)
void print_failed_vcd_head (const vcd_trace_head &t, bool one_hot_encoding, const int verbosity) const
void print_discrepancy (const DiscrepancyLog &l, bool one_hot_encoding, const int verbosity) const
std::string compute_fsm_state_from_vcd_string (const std::string &vcd_state_string, bool one_hot_encoding) const
Protected Attributes
const tree_managerRef TM
const DiscrepancyRef Discr
unsigned long long possibly_lost_address {0}
unsigned long long mismatched_integers {0}
bool allow_uninitialized
std::list< DiscrepancyLog > discr_list
std::list< DiscrepancyLog > soft_discr_list
std::string present_state_name
The name of the present state signal.
Additional Inherited Members
Detailed Description
Definition at line 94 of file vcd_utility.hpp.
Constructor & Destructor Documentation
vcd_utility()
vcd_utility::vcd_utility (const ParameterConstRef parameters, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Definition at line 132 of file vcd_utility.cpp.
References DesignFlowStep::debug_level, GET_CLASS, HLS_step::HLSMgr, DesignFlowStep::parameters, STR, and THROW_ASSERT.
 vcd_utility()
vcd_utility::~vcd_utility () [override], [default]
Member Function Documentation
compute_fsm_state_from_vcd_string()
std::string vcd_utility::compute_fsm_state_from_vcd_string (const std::string & vcd_state_string, bool one_hot_encoding) const [protected]
Definition at line 1151 of file vcd_utility.cpp.
References STR.
Referenced by print_discrepancy(), and print_failed_vcd_head().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > vcd_utility::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 144 of file vcd_utility.cpp.
References C_TESTBENCH_EXECUTION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TESTBENCH_GENERATION, THROW_UNREACHABLE, and TOP_FUNCTION.
detect_address_mismatch()
bool vcd_utility::detect_address_mismatch (const DiscrepancyOpInfo & op_info, const uint64_t c_context, const std::string & c_val, const std::string & vcd_val, unsigned int & base_index) [protected]
Definition at line 866 of file vcd_utility.cpp.
References detect_fixed_address_mismatch(), Discr, tree_helper::get_base_index(), GET_INDEX_NODE, HLS_step::HLSMgr, DiscrepancyOpInfo::op_id, possibly_lost_address, DiscrepancyOpInfo::ssa_name_node_id, STR, THROW_ASSERT, and TM.
Referenced by detect_mismatch_simple().
detect_binary_double_mismatch()
bool vcd_utility::detect_binary_double_mismatch (const std::string & c_val, const std::string & resized_vcd_val) const [protected]
Definition at line 778 of file vcd_utility.cpp.
References DesignFlowStep::parameters, STR, and THROW_ASSERT.
Referenced by detect_regular_mismatch().
detect_binary_float_mismatch()
bool vcd_utility::detect_binary_float_mismatch (const std::string & c_val, const std::string & resized_vcd_val) const [protected]
Definition at line 733 of file vcd_utility.cpp.
References DesignFlowStep::parameters, STR, and THROW_ASSERT.
Referenced by detect_regular_mismatch().
detect_fixed_address_mismatch()
bool vcd_utility::detect_fixed_address_mismatch (const DiscrepancyOpInfo & op_info, const uint64_t c_context, const std::string & c_val, const std::string & vcd_val, const unsigned int base_index) const [protected]
Definition at line 823 of file vcd_utility.cpp.
References Discr, tree_helper::get_type_index(), HLS_step::HLSMgr, max(), tree_helper::size(), DiscrepancyOpInfo::stg_fun_id, STR, THROW_ASSERT, and TM.
Referenced by detect_address_mismatch().
detect_mismatch()
bool vcd_utility::detect_mismatch (const vcd_trace_head & t, const uint64_t c_context, const std::string & c_val) [protected]
Definition at line 509 of file vcd_utility.cpp.
References detect_mismatch_element(), DISCR_VECTOR, vcd_trace_head::fullsigname, vcd_trace_head::op_info, vcd_trace_head::out_var_it, DesignFlowStep::parameters, DiscrepancyOpInfo::ssa_name, DiscrepancyOpInfo::ssa_name_node_id, STR, THROW_ASSERT, DiscrepancyOpInfo::type, update_discr_list(), and DiscrepancyOpInfo::vec_base_bitsize.
Referenced by Exec().
detect_mismatch_element()
bool vcd_utility::detect_mismatch_element (const vcd_trace_head & t, const uint64_t c_context, const std::string & c_val, const unsigned int el_idx) [protected]
Definition at line 566 of file vcd_utility.cpp.
References detect_mismatch_simple(), DISCR_COMPLEX, vcd_trace_head::fullsigname, vcd_trace_head::op_info, vcd_trace_head::out_var_it, DiscrepancyOpInfo::ssa_name, DiscrepancyOpInfo::ssa_name_node_id, STR, THROW_ASSERT, DiscrepancyOpInfo::type, and DiscrepancyOpInfo::vec_base_bitsize.
Referenced by detect_mismatch().
detect_mismatch_simple()
bool vcd_utility::detect_mismatch_simple (const vcd_trace_head & t, const uint64_t c_context, const std::string & c_val, const unsigned int el_idx, const std::string::size_type first_c_bit, const std::string::size_type c_size) [protected]
Definition at line 639 of file vcd_utility.cpp.
References detect_address_mismatch(), detect_regular_mismatch(), DISCR_ADDR, DISCR_COMPLEX, DISCR_REAL, DISCR_VECTOR, vcd_trace_head::discrepancy_found, mismatched_integers, DiscrepancyOpInfo::op_id, vcd_trace_head::op_info, vcd_trace_head::out_var_it, DiscrepancyOpInfo::ssa_name, STR, THROW_ASSERT, DiscrepancyOpInfo::type, and update_discr_list().
Referenced by detect_mismatch_element().
detect_regular_mismatch()
bool vcd_utility::detect_regular_mismatch (const vcd_trace_head & t, const std::string & c_val, const std::string & vcd_val) const [protected]
Definition at line 926 of file vcd_utility.cpp.
References allow_uninitialized, detect_binary_double_mismatch(), detect_binary_float_mismatch(), DISCR_REAL, vcd_trace_head::fullsigname, GET_NODE, vcd_trace_head::op_info, DiscrepancyOpInfo::ssa_name, DiscrepancyOpInfo::ssa_name_node_id, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, and DiscrepancyOpInfo::type.
Referenced by detect_mismatch_simple().
Exec()
DesignFlowStep_Status vcd_utility::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 206 of file vcd_utility.cpp.
References vcd_trace_head::advance(), vcd_trace_head::after_discrepancy, vcd_trace_head::checked, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, detect_mismatch(), Discr, discr_list, vcd_trace_head::discrepancy_found, vcd_trace_head::ends_after(), vcd_trace_head::exec_times_in_current_state, get_signal_variations(), GetClockPeriod(), HIERARCHY_SEPARATOR, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, vcd_trace_head::init_fail, vcd_trace_head::initialized, max(), mismatched_integers, vcd_trace_head::more_executions_in_this_hw_state(), DiscrepancyOpInfo::op_id, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_NONE, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, parse_discrepancy(), vcd_parser::parse_vcd(), possibly_lost_address, present_state_name, print_cpu_time(), print_discrepancy(), print_failed_vcd_head(), vcd_trace_head::running, soft_discr_list, START_PORT_NAME, START_TIME, vcd_trace_head::state, DiscrepancyOpInfo::stg_fun_id, STOP_TIME, STR, SUCCESS, vcd_trace_head::suspended, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, THROW_WARNING, TM, and vcd_trace_head::uninitialized.
GetClockPeriod()
unsigned long long vcd_utility::GetClockPeriod (const vcd_parser::vcd_trace_t & vcd_trace) const [protected]
Definition at line 188 of file vcd_utility.cpp.
References CLOCK_PORT_NAME, Discr, get_signal_variations(), HIERARCHY_SEPARATOR, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by Exec().
HasToBeExecuted()
bool vcd_utility::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 504 of file vcd_utility.cpp.
print_discrepancy()
void vcd_utility::print_discrepancy (const DiscrepancyLog & l, bool one_hot_encoding, const int verbosity) const [protected]
Definition at line 984 of file vcd_utility.cpp.
References DiscrepancyLog::base_index, DiscrepancyLog::bitsize, DiscrepancyLog::c_val, compute_fsm_state_from_vcd_string(), DiscrepancyLog::context, Discr, DISCR_ADDR, DISCR_COMPLEX, DISCR_VECTOR, DiscrepancyLog::fu_name, DiscrepancyLog::fullsigname, DiscrepancyLog::fun_id, GET_NODE, tree_helper::get_type_index(), HLS_step::HLSMgr, INDENT_OUT_MEX, max(), DiscrepancyLog::op_end_time, DiscrepancyLog::op_id, DiscrepancyLog::op_start_state, DiscrepancyLog::op_start_time, DesignFlowStep::output_level, tree_helper::size(), DiscrepancyLog::ssa_id, DiscrepancyLog::stmt_string, STR, THROW_ASSERT, TM, DiscrepancyLog::type, and DiscrepancyLog::vcd_val.
Referenced by Exec().
print_failed_vcd_head()
void vcd_utility::print_failed_vcd_head (const vcd_trace_head & t, bool one_hot_encoding, const int verbosity) const [protected]
Definition at line 1094 of file vcd_utility.cpp.
References compute_fsm_state_from_vcd_string(), vcd_trace_head::fail_none, vcd_trace_head::failed, vcd_trace_head::fsm_ss_it, vcd_trace_head::fullsigname, vcd_trace_head::function_does_not_start, INDENT_OUT_MEX, vcd_trace_head::no_end_state, vcd_trace_head::no_start_state, vcd_trace_head::op_end_time, DiscrepancyOpInfo::op_id, vcd_trace_head::op_info, vcd_trace_head::op_start_time, DesignFlowStep::output_level, DiscrepancyOpInfo::stg_fun_id, STR, and THROW_UNREACHABLE.
Referenced by Exec().
update_discr_list()
void vcd_utility::update_discr_list (const vcd_trace_head & t, const uint64_t c_context, const std::string & c_val, const unsigned int el_idx, const std::string::size_type first_c_bit, const std::string::size_type c_size, const unsigned int base_index) [protected]
Definition at line 678 of file vcd_utility.cpp.
References DISCR_ADDR, discr_list, HLS_step::HLSMgr, vcd_trace_head::op_end_time, vcd_trace_head::op_info, DesignFlowStep::parameters, soft_discr_list, and DiscrepancyOpInfo::type.
Referenced by detect_mismatch(), and detect_mismatch_simple().
Field Documentation
allow_uninitialized
bool vcd_utility::allow_uninitialized [protected]
Definition at line 122 of file vcd_utility.hpp.
Referenced by detect_regular_mismatch().
Discr
const DiscrepancyRef vcd_utility::Discr [protected]
Definition at line 116 of file vcd_utility.hpp.
Referenced by detect_address_mismatch(), detect_fixed_address_mismatch(), Exec(), GetClockPeriod(), and print_discrepancy().
discr_list
std::list<DiscrepancyLog> vcd_utility::discr_list [protected]
Definition at line 124 of file vcd_utility.hpp.
Referenced by Exec(), and update_discr_list().
mismatched_integers
unsigned long long vcd_utility::mismatched_integers {0} [protected]
Definition at line 120 of file vcd_utility.hpp.
Referenced by detect_mismatch_simple(), and Exec().
possibly_lost_address
unsigned long long vcd_utility::possibly_lost_address {0} [protected]
Definition at line 118 of file vcd_utility.hpp.
Referenced by detect_address_mismatch(), and Exec().
present_state_name
std::string vcd_utility::present_state_name [protected]
The name of the present state signal.
Definition at line 129 of file vcd_utility.hpp.
Referenced by Exec().
soft_discr_list
std::list<DiscrepancyLog> vcd_utility::soft_discr_list [protected]
Definition at line 126 of file vcd_utility.hpp.
Referenced by Exec(), and update_discr_list().
TM
const tree_managerRef vcd_utility::TM [protected]
Definition at line 114 of file vcd_utility.hpp.
Referenced by detect_address_mismatch(), detect_fixed_address_mismatch(), detect_regular_mismatch(), Exec(), and print_discrepancy().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/vcd_utility.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/vcd_utility.cpp