action_o Class Reference
This class describes a generic systemC action.
#include <structural_objects.hpp>
Public Types
enum process_type {
THREAD = 0,
CTHREAD,
METHOD,
SERVICE,
UNKNOWN
 }
Define the possible types of a process.
Public Member Functions
action_o (int debug_level, const structural_objectRef o)
Constructor.
~action_o () override=default
destructor
void add_parameter (structural_objectRef d)
Add a procedure paramenter.
const structural_objectRef get_parameter (unsigned int n) const
Return the ith input parameter.
unsigned int get_parameters_size () const
Return the number of the parameters.
void set_fun_id (unsigned int id)
Function that set the function with the action.
unsigned int get_fun_id () const
Return the function id.
void set_action_type (process_type at)
Set the type of the action.
process_type get_action_type () const
Return the type of the action.
void add_event_to_sensitivity (structural_objectRef e)
Add an event to the sensitivity list of the action.
unsigned int get_sensitivity_size () const
Return tha size of the sensitivity list.
const structural_objectRef get_sensitivity (unsigned int n) const
Return a specific event of the sensitivity list.
void set_scope (const std::string &sc)
Set the scope of the action.
const std::string & get_scope () const
Return the scope of the action.
bool get_process_nservice () const
Return the type of the action: process (true) or services (false).
void copy (structural_objectRef dest) const override
Perform a copy of the action.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the action (for debug purpose)
Private Attributes
std::vector< structural_objectRef > parameters
The method procedure parameter.
unsigned int function_id
The index of the function which represents the behavior.
process_type action_type
The type of the action.
std::vector< structural_objectRef > action_sensitivity
Sensitivity list.
std::string scope
Used to identify the scope of the action (public, private or protected)
Static Private Attributes
static const char * process_typeNames [] = {`THREAD`, `CTHREAD`, `METHOD`, `SERVICE`, `UNKNOWN`}
Redefinition of get_kind_text()
Additional Inherited Members
Detailed Description
This class describes a generic systemC action.
An action can be a SystemC process or a standard service (aka a member function of a class).
Definition at line 1333 of file structural_objects.hpp.
Member Enumeration Documentation
process_type
enum action_o::process_type
Define the possible types of a process.
Enumerator
THREAD
CTHREAD
METHOD
SERVICE
UNKNOWN
Definition at line 1339 of file structural_objects.hpp.
Constructor & Destructor Documentation
action_o()
action_o::action_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the action.
Definition at line 1717 of file structural_objects.cpp.
 action_o()
action_o::~action_o () [override], [default]
destructor
Member Function Documentation
add_event_to_sensitivity()
void action_o::add_event_to_sensitivity (structural_objectRef e)
Add an event to the sensitivity list of the action.
Parameters
e is an event.
Definition at line 1758 of file structural_objects.cpp.
References action_sensitivity, and THROW_ASSERT.
Referenced by copy(), and xload().
add_parameter()
void action_o::add_parameter (structural_objectRef d)
Add a procedure paramenter.
Parameters
d is the paramenter.
Definition at line 1721 of file structural_objects.cpp.
References parameters, and THROW_ASSERT.
Referenced by structural_manager::add_constant(), copy(), and xload().
copy()
void action_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the action.
Parameters
dest destination object.
Reimplemented from structural_object.
Definition at line 1790 of file structural_objects.cpp.
References action_sensitivity, action_type, add_event_to_sensitivity(), add_parameter(), structural_object::copy(), structural_object::debug_level, function_id, parameters, and scope.
find_isomorphic()
structural_objectRef action_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Definition at line 1811 of file structural_objects.cpp.
References THROW_ERROR.
find_member()
structural_objectRef action_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 1817 of file structural_objects.cpp.
References action_o_K, action_sensitivity, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, parameters, port_o_K, port_vector_o_K, process_typeNames, signal_o_K, signal_vector_o_K, and THROW_ERROR.
get_action_type()
action_o::process_type action_o::get_action_type () const
Return the type of the action.
Definition at line 1753 of file structural_objects.cpp.
References action_type.
get_fun_id()
unsigned int action_o::get_fun_id () const
Return the function id.
Returns
the index of the function associated with the action
Definition at line 1743 of file structural_objects.cpp.
References function_id.
get_parameter()
const structural_objectRef action_o::get_parameter (unsigned int n) const
Return the ith input parameter.
Parameters
n is the index of the input parameter.
Definition at line 1727 of file structural_objects.cpp.
References parameters, and THROW_ASSERT.
get_parameters_size()
unsigned int action_o::get_parameters_size () const
Return the number of the parameters.
Definition at line 1733 of file structural_objects.cpp.
References parameters.
get_process_nservice()
bool action_o::get_process_nservice () const
Return the type of the action: process (true) or services (false).
Definition at line 1785 of file structural_objects.cpp.
References action_type, and SERVICE.
get_scope()
const std::string & action_o::get_scope () const
Return the scope of the action.
Definition at line 1780 of file structural_objects.cpp.
References scope.
get_sensitivity()
const structural_objectRef action_o::get_sensitivity (unsigned int n) const
Return a specific event of the sensitivity list.
Parameters
n is the index of the event.
Definition at line 1769 of file structural_objects.cpp.
References action_sensitivity, and THROW_ASSERT.
get_sensitivity_size()
unsigned int action_o::get_sensitivity_size () const
Return tha size of the sensitivity list.
Definition at line 1764 of file structural_objects.cpp.
References action_sensitivity.
print()
void action_o::print (std::ostream & os) const [override], [virtual]
Print the action (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Definition at line 1909 of file structural_objects.cpp.
References action_sensitivity, action_type, parameters, structural_object::PP, structural_object::print(), process_typeNames, scope, and SERVICE.
set_action_type()
void action_o::set_action_type (process_type at)
Set the type of the action.
Parameters
at is the type of the action.
Definition at line 1748 of file structural_objects.cpp.
References action_type.
Referenced by structural_manager::add_constant().
set_fun_id()
void action_o::set_fun_id (unsigned int id)
Function that set the function with the action.
Parameters
id is the index of the function
Definition at line 1738 of file structural_objects.cpp.
References function_id.
set_scope()
void action_o::set_scope (const std::string & sc)
Set the scope of the action.
Parameters
sc is the actual scope.
Definition at line 1775 of file structural_objects.cpp.
References scope.
Referenced by structural_manager::add_constant().
xload()
void action_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
someone has to take care of GM
Reimplemented from structural_object.
Definition at line 1852 of file structural_objects.cpp.
References action_type, add_event_to_sensitivity(), add_parameter(), CE_XVM, xml_child::get_children(), GET_CLASS_NAME, structural_manager::get_debug_level(), LOAD_XVFM, LOAD_XVM, process_typeNames, scope, UNKNOWN, and structural_object::xload().
xwrite()
void action_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
someone has to take care of GM
Reimplemented from structural_object.
Definition at line 1890 of file structural_objects.cpp.
References action_sensitivity, action_type, xml_child::add_child_element(), structural_object::get_kind_text(), parameters, process_typeNames, scope, WRITE_XNVM, WRITE_XVM, and structural_object::xwrite().
Field Documentation
action_sensitivity
std::vector<structural_objectRef> action_o::action_sensitivity [private]
Sensitivity list.
Definition at line 1359 of file structural_objects.hpp.
Referenced by add_event_to_sensitivity(), copy(), find_member(), get_sensitivity(), get_sensitivity_size(), print(), and xwrite().
action_type
process_type action_o::action_type [private]
The type of the action.
Definition at line 1356 of file structural_objects.hpp.
Referenced by copy(), get_action_type(), get_process_nservice(), print(), set_action_type(), xload(), and xwrite().
function_id
unsigned int action_o::function_id [private]
The index of the function which represents the behavior.
Definition at line 1353 of file structural_objects.hpp.
Referenced by copy(), get_fun_id(), and set_fun_id().
parameters
std::vector<structural_objectRef> action_o::parameters [private]
The method procedure parameter.
Definition at line 1350 of file structural_objects.hpp.
Referenced by add_parameter(), copy(), find_member(), get_parameter(), get_parameters_size(), print(), and xwrite().
process_typeNames
const char * action_o::process_typeNames = {`THREAD`, `CTHREAD`, `METHOD`, `SERVICE`, `UNKNOWN`} [static], [private]
Redefinition of get_kind_text()
Redefinition of get_kind()store the names of the enumerative process_type.
Definition at line 1498 of file structural_objects.hpp.
Referenced by find_member(), print(), xload(), and xwrite().
scope
std::string action_o::scope [private]
Used to identify the scope of the action (public, private or protected)
Definition at line 1362 of file structural_objects.hpp.
Referenced by copy(), get_scope(), print(), set_scope(), xload(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp