DataDependenceComputation Class Reference
#include <data_dependence_computation.hpp>
Public Member Functions
DataDependenceComputation (const application_managerRef _AppM, unsigned int function_id, const FrontendFlowStepType frontend_flow_step_type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~DataDependenceComputation () override
Destructor.
DesignFlowStep_Status InternalExec ()
Cleans the fake data dependencies.
void Initialize () override=0
Initialize the step (i.e., like a constructor, but executed just before exec.
template<>
CustomSet< unsigned int > GetVariables (const vertex statement, const FunctionBehavior_VariableAccessType variable_access_type) const
Protected Member Functions
template<typename type >
DesignFlowStep_Status Computedependencies (const int dfg_selector, const int fb_dfg_selector, const int adg_selector, const int fb_adg_selector)
Compute the dependencies.
template<typename type >
CustomSet< type > GetVariables (const vertex statement, const FunctionBehavior_VariableAccessType variable_access_type) const
Return the variables accessed in a node It is specialized in the different subclasses of this.
Private Member Functions
void do_dependence_reduction ()
Additional Inherited Members
Detailed Description
Definition at line 55 of file data_dependence_computation.hpp.
Constructor & Destructor Documentation
DataDependenceComputation()
DataDependenceComputation::DataDependenceComputation (const application_managerRef _AppM, unsigned int _function_id, const FrontendFlowStepType _frontend_flow_step_type, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
frontend_flow_step_type is the type of data flow analysis
design_flow_manager is the design flow manager
parameters is the set of input parameters
Header include . include behavior include tree include
Definition at line 67 of file data_dependence_computation.cpp.
References ~DataDependenceComputation().
 DataDependenceComputation()
DataDependenceComputation::~DataDependenceComputation () [override], [default]
Destructor.
Referenced by DataDependenceComputation().
Member Function Documentation
Computedependencies()
template<typename type >
DesignFlowStep_Status DataDependenceComputation::Computedependencies (const int dfg_selector, const int fb_dfg_selector, const int adg_selector, const int fb_adg_selector) [protected]
Compute the dependencies.
Parameters
dfg_selector is the selector to be used for DFG dependence
fb_dfg_selector is the selector to be used for DFG feedback dependence
adg_selector is the selector to be used for ADG dependence
fb_adg_selector is the selector to be used for ADG feedback dependence
NOTE: label associated with forward selector also on feedback edge
NOTE: label associated with forward selector also on feedback edge
NOTE: label associated with forward selector also on feedback edge
Definition at line 202 of file data_dependence_computation.cpp.
References FunctionBehavior::ADG, ADG_SELECTOR, FrontendFlowStep::AppM, FunctionBehavior::CFG, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DEFINITION, FunctionBehavior::DFG, DFG_SELECTOR, FunctionBehavior::FADG, FB_ODG_AGG_SELECTOR, FunctionBehavior::FDFG, FunctionBehavior::FODG, FunctionFrontendFlowStep::function_behavior, BehavioralHelper::get_function_name(), GET_NAME, INDENT_DBG_MEX, FunctionBehavior::ODG, ODG_AGG_SELECTOR, ODG_SELECTOR, OVER, DesignFlowStep::parameters, FunctionBehavior::SAODG, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, and USE.
do_dependence_reduction()
void DataDependenceComputation::do_dependence_reduction () [private]
Definition at line 126 of file data_dependence_computation.cpp.
References ADG_AGG_SELECTOR, FunctionBehavior::AGG_VIRTUALG, FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DFG_AGG_SELECTOR, FunctionBehavior::FFLSAODG, FunctionFrontendFlowStep::function_behavior, GET_NAME, INDENT_DBG_MEX, ordered_dfs(), DesignFlowStep::parameters, and STR.
Referenced by InternalExec().
GetVariables() [1/2]
template<typename type >
CustomSet<type> DataDependenceComputation::GetVariables (const vertex statement, const FunctionBehavior_VariableAccessType variable_access_type) const [protected]
Return the variables accessed in a node It is specialized in the different subclasses of this.
Parameters
statement is the statement to be considered
variable_access_type is the type of accesses to be considered
Referenced by GetVariables().
GetVariables() [2/2]
template<>
CustomSet<unsigned int> DataDependenceComputation::GetVariables (const vertex statement, const FunctionBehavior_VariableAccessType variable_access_type) const
Definition at line 376 of file data_dependence_computation.cpp.
References FunctionBehavior::CFG, FrontendFlowStep::frontend_flow_step_type, FunctionFrontendFlowStep::function_behavior, GetVariables(), MEMORY, MEMORY_DATA_FLOW_ANALYSIS, SCALAR, SCALAR_SSA_DATA_FLOW_ANALYSIS, THROW_ASSERT, THROW_UNREACHABLE, UNKNOWN, VIRTUAL, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
Initialize()
void DataDependenceComputation::Initialize () [override], [pure virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Implemented in MemoryDataFlowAnalysis, ScalarSsaDataDependenceComputation, and VirtualAggregateDataFlowAnalysis.
InternalExec()
DesignFlowStep_Status DataDependenceComputation::InternalExec () [virtual]
Cleans the fake data dependencies.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 75 of file data_dependence_computation.cpp.
References ABORTED, ADG_AGG_SELECTOR, ADG_SCA_SELECTOR, DFG_AGG_SELECTOR, DFG_SCA_SELECTOR, do_dependence_reduction(), FB_ADG_AGG_SELECTOR, FB_ADG_SCA_SELECTOR, FB_DFG_AGG_SELECTOR, FB_DFG_SCA_SELECTOR, FrontendFlowStep::frontend_flow_step_type, MEMORY_DATA_FLOW_ANALYSIS, SCALAR_SSA_DATA_FLOW_ANALYSIS, THROW_UNREACHABLE, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/data_dependence_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/data_dependence_computation.cpp