HLS_target Class Reference
#include <hls_target.hpp>
Public Member Functions
HLS_target (const ParameterConstRef &Param, const technology_managerRef &TM, const target_deviceRef &_target)
Constructor.
~HLS_target () override
Destructor.
Static Public Member Functions
static HLS_targetRef create_target (const ParameterRef &Param)
Factory method from XML file.
Additional Inherited Members
Detailed Description
Definition at line 62 of file hls_target.hpp.
Constructor & Destructor Documentation
HLS_target()
HLS_target::HLS_target (const ParameterConstRef & _Param, const technology_managerRef & _TM, const target_deviceRef & _target)
Constructor.
Header include.
----------- Resource Library ----------- /// Resource Library Datastructure ----------- Target Device ----------- ///
Definition at line 60 of file hls_target.cpp.
References target_manager::device, target_technology::get_string_type(), OUTPUT_LEVEL_MINIMUM, target_manager::Param, PRINT_OUT_MEX, target_device::set_parameter(), target_manager::target, and ~HLS_target().
Referenced by create_target().
 HLS_target()
HLS_target::~HLS_target () [override], [default]
Destructor.
Referenced by HLS_target().
Member Function Documentation
create_target()
HLS_targetRef HLS_target::create_target (const ParameterRef & Param) [static]
Factory method from XML file.
Definition at line 73 of file hls_target.cpp.
References CE_XVM, target_device::create_device(), FPGA, xml_child::get_children(), HLS_target(), LOAD_XVM, test_panda::parser, target_manager::target, THROW_ERROR, target_manager::TM, test_panda::type, and target_device::xload().
Referenced by main().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_target.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_target.cpp