top_entity_cs Class Reference
#include <top_entity_cs.hpp>
Public Member Functions
top_entity_cs (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type=HLSFlowStep_Type::TOP_ENTITY_CS_CREATION)
Header include.
virtual ~top_entity_cs ()
Destructor.
virtual DesignFlowStep_Status InternalExec ()
Add selector and suspension.
Protected Member Functions
void add_input_register (structural_objectRef port_in, const std::string &port_prefix, structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef reset_port, structural_objectRef e_port)
Add the register file to store input parameters.
void add_context_switch_port ()
void add_context_switch_port_kernel ()
Additional Inherited Members
Detailed Description
Definition at line 44 of file top_entity_cs.hpp.
Constructor & Destructor Documentation
top_entity_cs()
top_entity_cs::top_entity_cs (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::TOP_ENTITY_CS_CREATION)
Header include.
.include circuit include HLS includes HLS/functions_allocation STD include technology include utility includes
Definition at line 69 of file top_entity_cs.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 top_entity_cs()
top_entity_cs::~top_entity_cs () [virtual]
Destructor.
Definition at line 75 of file top_entity_cs.cpp.
Member Function Documentation
add_context_switch_port()
void top_entity_cs::add_context_switch_port () [protected]
Definition at line 108 of file top_entity_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), ceil_log2(), hls::controller, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, port_o::IN, INDENT_DBG_MEX, port_o::OUT, DesignFlowStep::parameters, port_o_K, SELECTOR_REGISTER_FILE, top_entity::SM, STR, and SUSPENSION.
Referenced by InternalExec().
add_context_switch_port_kernel()
void top_entity_cs::add_context_switch_port_kernel () [protected]
Definition at line 133 of file top_entity_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_NP_functionality(), structural_manager::add_port(), structural_manager::add_sign(), structural_object::AddParameter(), ceil_log2(), hls::controller, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DONE_REQUEST, DONE_SCHEDULER, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, port_o::IN, INDENT_DBG_MEX, NP_functionality::LIBRARY, port_o::OUT, DesignFlowStep::parameters, port_o_K, SELECTOR_REGISTER_FILE, signal_o_K, top_entity::SM, START_PORT_NAME, STR, and TASKS_POOL_END.
Referenced by InternalExec().
add_input_register()
void top_entity_cs::add_input_register (structural_objectRef port_in, const std::string & port_prefix, structural_objectRef circuit, structural_objectRef clock_port, structural_objectRef reset_port, structural_objectRef e_port) [protected], [virtual]
Add the register file to store input parameters.
Parameters
port_in is the input parameter port of the datapath
port_prefix is the prefix of the port name
circuit is the circuit of the top entity
clock_port is the port of the clock signal
reset_port is the port of the reset signal
e_port is the input parameter port of the top entity
Resizing input port
Resizing output port
Add clock
Connect write port to start port
Connect selector of register file
Add signal from external port
Add signal to datapath
Reimplemented from top_entity.
Definition at line 185 of file top_entity_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), ceil_log2(), CLOCK_PORT_NAME, hls::controller, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), GET_TYPE_SIZE, structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_T, INDENT_DBG_MEX, hls::Param, port_o_K, SELECTOR_REGISTER_FILE, signal_o_K, top_entity::SM, START_PORT_NAME, and STR.
InternalExec()
DesignFlowStep_Status top_entity_cs::InternalExec () [virtual]
Add selector and suspension.
Returns
the exit status of this step
Register input because of context switch
Reimplemented from top_entity.
Definition at line 79 of file top_entity_cs.cpp.
References add_context_switch_port(), add_context_switch_port_kernel(), HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, top_entity::InternalExec(), hls::registered_inputs, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/top_entity_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/top_entity_cs.cpp