HWCallInjection Class Reference
#include <HWCallInjection.hpp>
Public Member Functions
HWCallInjection (const ParameterConstRef Param, const application_managerRef AppM, unsigned int funId, const DesignFlowManagerConstRef DFM)
~HWCallInjection () override
DesignFlowStep_Status InternalExec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType RT) const override
Return the set of analyses in relationship with this design step.
bool isHardwareCall (tree_nodeRef FD)
void buildBuiltinCall (const blocRef block, const tree_nodeRef stmt)
Private Attributes
bool already_executed
True if already executed.
Static Private Attributes
static unsigned int builtinWaitCallDeclIdx = 0
parser/treegcc include
Additional Inherited Members
Detailed Description
Definition at line 46 of file HWCallInjection.hpp.
Constructor & Destructor Documentation
HWCallInjection()
HWCallInjection::HWCallInjection (const ParameterConstRef Param, const application_managerRef AppM, unsigned int funId, const DesignFlowManagerConstRef DFM)
Definition at line 60 of file HWCallInjection.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~HWCallInjection().
 HWCallInjection()
HWCallInjection::~HWCallInjection () [override], [default]
Referenced by HWCallInjection().
Member Function Documentation
buildBuiltinCall()
void HWCallInjection::buildBuiltinCall (const blocRef block, const tree_nodeRef stmt) [private]
Definition at line 168 of file HWCallInjection.cpp.
References ALGN_POINTER, FrontendFlowStep::AppM, BUILTIN_WAIT_CALL, builtinWaitCallDeclIdx, tree_manipulation::create_default_integer_type(), tree_manipulation::create_identifier_node(), tree_manipulation::create_pointer_type(), tree_manager::create_tree_node(), tree_manipulation::create_void_type(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), tree_manager::GetTreeNode(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_manager::new_tree_node_id(), DesignFlowStep::parameters, ssa_name::SetDefStmt(), STR, THROW_ASSERT, THROW_UNREACHABLE, TOK, TOK_ALGN, TOK_ALIGNED, TOK_ARTIFICIAL, TOK_EXTERN, TOK_FN, TOK_NAME, TOK_OP, TOK_PRMS, TOK_REGISTER, TOK_RETN, TOK_SCPE, TOK_SIZE, TOK_SRCP, TOK_STATIC, TOK_STATIC_STATIC, TOK_TYPE, TOK_USE_TMPL, TOK_USED, TOK_VALU, TOK_VALUE, TOK_VARARGS, and tree_node::ToString().
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > HWCallInjection::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 93 of file HWCallInjection.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
HasToBeExecuted()
bool HWCallInjection::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 403 of file HWCallInjection.cpp.
References already_executed.
InternalExec()
DesignFlowStep_Status HWCallInjection::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 67 of file HWCallInjection.cpp.
References already_executed, FrontendFlowStep::AppM, buildBuiltinCall(), FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), isHardwareCall(), sl, SUCCESS, and THROW_ASSERT.
isHardwareCall()
bool HWCallInjection::isHardwareCall (tree_nodeRef FD) [private]
Definition at line 118 of file HWCallInjection.cpp.
References FrontendFlowStep::AppM, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::name_function(), result, and SplitString().
Referenced by InternalExec().
Field Documentation
already_executed
bool HWCallInjection::already_executed [private]
True if already executed.
Definition at line 52 of file HWCallInjection.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
builtinWaitCallDeclIdx
unsigned int HWCallInjection::builtinWaitCallDeclIdx = 0 [static], [private]
parser/treegcc include
STD include STL includes
Definition at line 49 of file HWCallInjection.hpp.
Referenced by buildBuiltinCall().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/HWCallInjection.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/HWCallInjection.cpp