conn_binding_cs Class Reference
#include <conn_binding_cs.hpp>
Public Member Functions
conn_binding_cs (const BehavioralHelperConstRef BH, const ParameterConstRef parameters)
virtual ~conn_binding_cs ()
Destructor.
void add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM)
add_to_SM
Protected Member Functions
void instantiate_suspension_component (const HLS_managerRef HLSMgr, const hlsRef HLS)
connect_suspension_component
void connectOutOr (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef port_out_or)
connectOutOr depending if module is kernel or another connect out
Additional Inherited Members
Detailed Description
Definition at line 45 of file conn_binding_cs.hpp.
Constructor & Destructor Documentation
conn_binding_cs()
conn_binding_cs::conn_binding_cs (const BehavioralHelperConstRef _BH, const ParameterConstRef _parameters)
STD include.
utility include
Definition at line 59 of file conn_binding_cs.cpp.
References conn_binding::debug_level, and GET_CLASS.
 conn_binding_cs()
conn_binding_cs::~conn_binding_cs () [virtual]
Destructor.
Definition at line 64 of file conn_binding_cs.cpp.
Member Function Documentation
add_to_SM()
void conn_binding_cs::add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM) [virtual]
add_to_SM
Parameters
HLSMgr
HLS
SM
Reimplemented from conn_binding.
Definition at line 68 of file conn_binding_cs.cpp.
References conn_binding::add_to_SM(), and instantiate_suspension_component().
connectOutOr()
void conn_binding_cs::connectOutOr (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef port_out_or) [protected]
connectOutOr depending if module is kernel or another connect out
Parameters
HLSMgr
HLS
port_out_or
Definition at line 217 of file conn_binding_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), component_o_K, hls::datapath, conn_binding::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), hls::functionId, structural_manager::get_circ(), port_o_K, PRINT_DBG_MEX, STR, and SUSPENSION.
Referenced by instantiate_suspension_component().
instantiate_suspension_component()
void conn_binding_cs::instantiate_suspension_component (const HLS_managerRef HLSMgr, const hlsRef HLS) [protected]
connect_suspension_component
Parameters
HLSMgr
HLS
Definition at line 74 of file conn_binding_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), AND_GATE_STD, connectOutOr(), hls::datapath, conn_binding::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), get_id(), structural_object::get_id(), conn_binding::get_port(), GET_TYPE_NAME, hls::HLS_T, OR_GATE_STD, port_o_K, port_vector_o_K, PRINT_DBG_MEX, structural_object::set_type(), START_PORT_NAME, STR, SUSPENSION, THROW_ASSERT, and THROW_ERROR.
Referenced by add_to_SM().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/conn_binding_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/conn_binding_cs.cpp