pointer_var_pp_functor Struct Reference
Pointer version functor that returns the name of a variable with a star in front.
#include <var_pp_functor.hpp>
Public Member Functions
pointer_var_pp_functor (const BehavioralHelperConstRef _BH, const CustomSet< unsigned int > vars, bool _add_restrict=false)
Constructor.
~pointer_var_pp_functor () override=default
Destructor.
std::string operator() (unsigned int var) const override
return the name of the variable with a star as a prefix.
Private Attributes
const CustomSet< unsigned int > pointer_based_variables
reference to the set of variable that has to have a star in front when returned by operator()
const BehavioralHelperConstRef BH
behavioral helper
const std_var_pp_functor std_functor
standard functor used for print array variable
bool add_restrict
it controls the addition to the parameters declarations of the restrict keyword.
Detailed Description
Pointer version functor that returns the name of a variable with a star in front.
Definition at line 108 of file var_pp_functor.hpp.
Constructor & Destructor Documentation
pointer_var_pp_functor()
pointer_var_pp_functor::pointer_var_pp_functor (const BehavioralHelperConstRef _BH, const CustomSet< unsigned int > vars, bool _add_restrict = false)
Constructor.
Header include.
Parameters
BH is the behavioral helper.
vars is the reference to the set of variables for which a star should be returned along with their name.
add_restrict controls the addition to the parameters declarations of the restrict keyword.
Definition at line 48 of file var_pp_functor.cpp.
 pointer_var_pp_functor()
pointer_var_pp_functor::~pointer_var_pp_functor () [override], [default]
Destructor.
Member Function Documentation
operator()()
std::string pointer_var_pp_functor::operator() (unsigned int var) const [override], [virtual]
return the name of the variable with a star as a prefix.
Parameters
var is the nodeid of the variable.
Implements var_pp_functor.
Definition at line 130 of file var_pp_functor.cpp.
References add_restrict, BH, BehavioralHelper::get_array_ref_array(), BehavioralHelper::get_array_ref_index(), BehavioralHelper::get_component_ref_field(), BehavioralHelper::get_component_ref_record(), BehavioralHelper::get_indirect_ref_var(), BehavioralHelper::get_operand_from_unary_expr(), BehavioralHelper::GetVarFromSsa(), index, BehavioralHelper::is_a_component_ref(), BehavioralHelper::is_a_imagpart_expr(), BehavioralHelper::is_a_realpart_expr(), BehavioralHelper::is_an_addr_expr(), BehavioralHelper::is_an_array(), BehavioralHelper::is_an_array_ref(), BehavioralHelper::is_an_indirect_ref(), BehavioralHelper::IsDefaultSsaName(), pointer_based_variables, BehavioralHelper::PrintVariable(), and std_functor.
Referenced by std_var_pp_functor::operator()().
Field Documentation
add_restrict
bool pointer_var_pp_functor::add_restrict [private]
it controls the addition to the parameters declarations of the restrict keyword.
Definition at line 140 of file var_pp_functor.hpp.
Referenced by operator()().
BH
const BehavioralHelperConstRef pointer_var_pp_functor::BH [private]
behavioral helper
Definition at line 134 of file var_pp_functor.hpp.
Referenced by std_var_pp_functor::operator()(), and operator()().
pointer_based_variables
const CustomSet<unsigned int> pointer_var_pp_functor::pointer_based_variables [private]
reference to the set of variable that has to have a star in front when returned by operator()
Definition at line 131 of file var_pp_functor.hpp.
Referenced by operator()().
std_functor
const std_var_pp_functor pointer_var_pp_functor::std_functor [private]
standard functor used for print array variable
Definition at line 137 of file var_pp_functor.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.cpp