hls_div_cg_ext Class Reference
Add to the call graph the function calls associated with the integer division and modulus operations.
#include <hls_div_cg_ext.hpp>
Public Member Functions
hls_div_cg_ext (const ParameterConstRef Param, const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~hls_div_cg_ext () override
Destructor.
DesignFlowStep_Status InternalExec () override
Fixes the var_decl duplication.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
void recursive_examinate (const tree_nodeRef &current_tree_node, const tree_nodeRef &current_statement)
Recursive examinate tree node.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
const tree_managerRef TreeM
const tree_manipulationRef tree_man
bool already_executed
True if already executed.
bool changed_call_graph
bool fix_nop
bool use64bitMul
Additional Inherited Members
Detailed Description
Add to the call graph the function calls associated with the integer division and modulus operations.
Definition at line 63 of file hls_div_cg_ext.hpp.
Constructor & Destructor Documentation
hls_div_cg_ext()
hls_div_cg_ext::hls_div_cg_ext (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
fun_id is the function index
design_flow_manager is the design flow manager
design_flows include frontend_analysis Behavior include Graph include Parameter include STD include STL include Tree include Utility include
Definition at line 91 of file hls_div_cg_ext.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and DesignFlowStep::parameters.
 hls_div_cg_ext()
hls_div_cg_ext::~hls_div_cg_ext () [override], [default]
Destructor.
Referenced by Initialize().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > hls_div_cg_ext::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 111 of file hls_div_cg_ext.cpp.
References ABORTED, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, MEM_CG_EXT, NONEXISTENT, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, UNNECESSARY, and USE_COUNTING.
HasToBeExecuted()
bool hls_div_cg_ext::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 643 of file hls_div_cg_ext.cpp.
References already_executed.
Initialize()
void hls_div_cg_ext::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 103 of file hls_div_cg_ext.cpp.
References changed_call_graph, fix_nop, and ~hls_div_cg_ext().
InternalExec()
DesignFlowStep_Status hls_div_cg_ext::InternalExec () [override], [virtual]
Fixes the var_decl duplication.
Implements FunctionFrontendFlowStep.
Definition at line 162 of file hls_div_cg_ext.cpp.
References already_executed, FrontendFlowStep::AppM, tree_helper::CGetType(), changed_call_graph, tree_manipulation::CreateGimpleAssign(), tree_manipulation::CreateNopExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, fix_nop, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_formal_ith(), GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), INDENT_DBG_MEX, tree_node::index, recursive_examinate(), sl, STR, SUCCESS, THROW_ASSERT, ToString(), tree_man, TreeM, UNCHANGED, and use64bitMul.
recursive_examinate()
void hls_div_cg_ext::recursive_examinate (const tree_nodeRef & current_tree_node, const tree_nodeRef & current_statement) [protected]
Recursive examinate tree node.
Definition at line 261 of file hls_div_cg_ext.cpp.
References FrontendFlowStep::AppM, test_panda::arg, test_panda::args, call_expr::args, gimple_call::args, target_mem_ref::base, target_mem_ref461::base, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, changed_call_graph, tree_manipulation::CreateCallExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, fix_nop, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), target_mem_ref::idx, target_mem_ref461::idx, target_mem_ref461::idx2, INDENT_DBG_MEX, tree_node::index, tree_helper::is_unsigned(), constructor::list_of_idx_valu, max(), NODE_NOT_YET_SUPPORTED_EC, unary_expr::op, gimple_return::op, gimple_while::op0, binary_expr::op0, ternary_expr::op0, quaternary_expr::op0, gimple_cond::op0, gimple_switch::op0, binary_expr::op1, ternary_expr::op1, quaternary_expr::op1, ternary_expr::op2, quaternary_expr::op2, quaternary_expr::op3, resize_to_1_8_16_32_64_128_256_512(), tree_helper::Size(), STR, target_mem_ref::symbol, THROW_ASSERT, THROW_ERROR_CODE, THROW_UNREACHABLE, TOK, TOK_OP, TOK_SRCP, TOK_TYPE, ToString(), tree_man, TreeM, and use64bitMul.
Referenced by InternalExec().
Field Documentation
already_executed
bool hls_div_cg_ext::already_executed [protected]
True if already executed.
Definition at line 71 of file hls_div_cg_ext.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
changed_call_graph
bool hls_div_cg_ext::changed_call_graph [protected]
Definition at line 73 of file hls_div_cg_ext.hpp.
Referenced by Initialize(), InternalExec(), and recursive_examinate().
fix_nop
bool hls_div_cg_ext::fix_nop [protected]
Definition at line 75 of file hls_div_cg_ext.hpp.
Referenced by Initialize(), InternalExec(), and recursive_examinate().
tree_man
const tree_manipulationRef hls_div_cg_ext::tree_man [protected]
Definition at line 68 of file hls_div_cg_ext.hpp.
Referenced by InternalExec(), and recursive_examinate().
TreeM
const tree_managerRef hls_div_cg_ext::TreeM [protected]
Definition at line 66 of file hls_div_cg_ext.hpp.
Referenced by InternalExec(), and recursive_examinate().
use64bitMul
bool hls_div_cg_ext::use64bitMul [protected]
Definition at line 77 of file hls_div_cg_ext.hpp.
Referenced by InternalExec(), and recursive_examinate().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/hls_div_cg_ext.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/hls_div_cg_ext.cpp