/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.cpp File Reference
Data structures used in operations graph.
#include `op_graph.hpp`
#include `Parameter.hpp`
#include `behavioral_helper.hpp`
#include `behavioral_writer_helper.hpp`
#include `exceptions.hpp`
#include `tree_manager.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
#include <boost/filesystem/operations.hpp>
#include <boost/tuple/tuple.hpp>
#include <fstream>
#include <utility>
Functions
void PrintVariablesList (std::ostream &stream, const std::string &name, const CustomSet< unsigned int > variables, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format)
void PrintMemoriesList (std::ostream &stream, const std::string &name, const CustomSet< MemoryAddress > variables, const BehavioralHelperConstRef, const bool dotty_format)
void PrintVariablesLists (std::ostream &stream, const std::string &name, const CustomMap< FunctionBehavior_VariableAccessType, CustomSet< unsigned int >> variables, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format)
void PrintMemoriesLists (std::ostream &stream, const std::string &name, const CustomMap< FunctionBehavior_VariableAccessType, CustomSet< MemoryAddress >> variables, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format)
Detailed Description
Data structures used in operations graph.
Author
Marco Lattuada lattuada@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
PrintMemoriesList()
void PrintMemoriesList (std::ostream & stream, const std::string & name, const CustomSet< MemoryAddress > variables, const BehavioralHelperConstRef , const bool dotty_format)
Definition at line 161 of file op_graph.cpp.
Referenced by PrintMemoriesLists().
PrintMemoriesLists()
void PrintMemoriesLists (std::ostream & stream, const std::string & name, const CustomMap< FunctionBehavior_VariableAccessType, CustomSet< MemoryAddress >> variables, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format)
Definition at line 185 of file op_graph.cpp.
References DEFINITION, OVER, PrintMemoriesList(), USE, and OpNodeInfo::variables.
Referenced by OpNodeInfo::Print().
PrintVariablesList()
void PrintVariablesList (std::ostream & stream, const std::string & name, const CustomSet< unsigned int > variables, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format)
Definition at line 152 of file op_graph.cpp.
Referenced by OpNodeInfo::Print(), and PrintVariablesLists().
PrintVariablesLists()
void PrintVariablesLists (std::ostream & stream, const std::string & name, const CustomMap< FunctionBehavior_VariableAccessType, CustomSet< unsigned int >> variables, const BehavioralHelperConstRef behavioral_helper, const bool dotty_format)
Definition at line 169 of file op_graph.cpp.
References ADDRESS, DEFINITION, OVER, PrintVariablesList(), USE, and OpNodeInfo::variables.
Referenced by OpNodeInfo::Print().