fu_binding_creator Class Reference
Generic class managing module binding algorithms.
#include <fu_binding_creator.hpp>
Public Member Functions
fu_binding_creator (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization=HLSFlowStepSpecializationConstRef())
Constructor.
~fu_binding_creator () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Additional Inherited Members
Detailed Description
Generic class managing module binding algorithms.
Definition at line 54 of file fu_binding_creator.hpp.
Constructor & Destructor Documentation
fu_binding_creator()
fu_binding_creator::fu_binding_creator (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type, const HLSFlowStepSpecializationConstRef _hls_flow_step_specialization = HLSFlowStepSpecializationConstRef())
Constructor.
implemented algorithms
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the type of function binding algorithm
HLS/module_allocation include
Definition at line 63 of file fu_binding_creator.cpp.
References ~fu_binding_creator().
 fu_binding_creator()
fu_binding_creator::~fu_binding_creator () [override], [default]
Destructor.
Referenced by fu_binding_creator().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > fu_binding_creator::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 87 of file fu_binding_creator.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, EASY_MODULE_BINDING, HLSFunctionStep::funId, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void fu_binding_creator::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 71 of file fu_binding_creator.cpp.
References fu_binding::create_fu_binding(), HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), DesignFlowStep::parameters, and hls::Rfu.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/fu_binding_creator.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/fu_binding_creator.cpp