soft_float_cg_ext Class Reference
Add to the call graph the function calls associated with the floating point primitive operations.
#include <soft_float_cg_ext.hpp>
Public Member Functions
soft_float_cg_ext (const ParameterConstRef Param, const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~soft_float_cg_ext () override
Destructor.
DesignFlowStep_Status InternalExec () override
Fixes the var_decl duplication.
Protected Member Functions
void RecursiveExaminate (const tree_nodeRef current_statement, const tree_nodeRef current_tree_node)
Recursive examinate tree node.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
const tree_managerRef TreeM
Tree manager.
const tree_manipulationRef tree_man
tree manipulation
bool modified
when true IR has been modified
Additional Inherited Members
Detailed Description
Add to the call graph the function calls associated with the floating point primitive operations.
Definition at line 63 of file soft_float_cg_ext.hpp.
Constructor & Destructor Documentation
soft_float_cg_ext()
soft_float_cg_ext::soft_float_cg_ext (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
fun_id is the function index
design_flow_manager is the design flow manager
design_flows include frontend_analysis Behavior include Graph include Parameter include STD include STL include Tree include Utility include
Definition at line 87 of file soft_float_cg_ext.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~soft_float_cg_ext().
 soft_float_cg_ext()
soft_float_cg_ext::~soft_float_cg_ext () [override], [default]
Destructor.
Referenced by soft_float_cg_ext().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > soft_float_cg_ext::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 95 of file soft_float_cg_ext.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status soft_float_cg_ext::InternalExec () [override], [virtual]
Fixes the var_decl duplication.
Implements FunctionFrontendFlowStep.
Definition at line 122 of file soft_float_cg_ext.cpp.
References FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, modified, RecursiveExaminate(), sl, SUCCESS, TreeM, and UNCHANGED.
RecursiveExaminate()
void soft_float_cg_ext::RecursiveExaminate (const tree_nodeRef current_statement, const tree_nodeRef current_tree_node) [protected]
Recursive examinate tree node.
Parameters
current_statement is the current analyzed statement
current_tree_node is the current tree node
Definition at line 141 of file soft_float_cg_ext.cpp.
References FrontendFlowStep::AppM, test_panda::arg, test_panda::args, call_expr::args, gimple_call::args, target_mem_ref::base, target_mem_ref461::base, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_manipulation::CreateCallExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), target_mem_ref::idx, target_mem_ref461::idx, target_mem_ref461::idx2, INDENT_DBG_MEX, tree_node::index, tree_helper::is_unsigned(), constructor::list_of_idx_valu, modified, NODE_NOT_YET_SUPPORTED_EC, unary_expr::op, gimple_return::op, gimple_while::op0, binary_expr::op0, ternary_expr::op0, quaternary_expr::op0, gimple_cond::op0, gimple_switch::op0, binary_expr::op1, ternary_expr::op1, quaternary_expr::op1, ternary_expr::op2, quaternary_expr::op2, quaternary_expr::op3, DesignFlowStep::parameters, tree_helper::size(), STR, target_mem_ref::symbol, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, tree_man, TreeM, and expr_node::type.
Referenced by InternalExec().
Field Documentation
modified
bool soft_float_cg_ext::modified [protected]
when true IR has been modified
Definition at line 73 of file soft_float_cg_ext.hpp.
Referenced by InternalExec(), and RecursiveExaminate().
tree_man
const tree_manipulationRef soft_float_cg_ext::tree_man [protected]
tree manipulation
Definition at line 70 of file soft_float_cg_ext.hpp.
Referenced by RecursiveExaminate().
TreeM
const tree_managerRef soft_float_cg_ext::TreeM [protected]
Tree manager.
Definition at line 67 of file soft_float_cg_ext.hpp.
Referenced by InternalExec(), and RecursiveExaminate().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/soft_float_cg_ext.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/soft_float_cg_ext.cpp