tree_rehashed_heap< _Type > Struct Template Reference
Class used to represent a tree of priority queues.
#include <rehashed_heap.hpp>
Public Member Functions
std::vector< rehashed_heap< _Type > >::iterator top (const CustomUnorderedMap< vertex, CustomOrderedSet< unsigned int >> &curren_black_list, const priority_data< _Type > &priority_functor, vertex &controlling_vertex, unsigned int &b_tag, bool &found)
Return the vertex with the highest priority.
void rehash ()
Rehash all the heaps in the map.
Detailed Description
template<class _Type>
struct tree_rehashed_heap< _Type >
Class used to represent a tree of priority queues.
Definition at line 101 of file rehashed_heap.hpp.
Member Function Documentation
rehash()
template<class _Type >
void tree_rehashed_heap< _Type >::rehash () [inline]
Rehash all the heaps in the map.
Definition at line 147 of file rehashed_heap.hpp.
References rehashed_heap< _Type >::begin(), and rehashed_heap< _Type >::end().
top()
template<class _Type >
std::vector<rehashed_heap<_Type> >::iterator tree_rehashed_heap< _Type >::top (const CustomUnorderedMap< vertex, CustomOrderedSet< unsigned int >> & curren_black_list, const priority_data< _Type > & priority_functor, vertex & controlling_vertex, unsigned int & b_tag, bool & found) [inline]
Return the vertex with the highest priority.
Precondition: empty() is false.
Parameters
curren_black_list is the black list, that is the set of queues not usable.
priority_functor is the priority functor.
controlling_vertex filled with the controlling vertex in case found is true.
b_tag filled with the branch tag when found is true.
found is true when there exists a queue with candidate vertices.
Definition at line 111 of file rehashed_heap.hpp.
References rehashed_heap< _Type >::begin(), and rehashed_heap< _Type >::end().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/rehashed_heap.hpp