HLSSynthesisFlow Class Reference
#include <hls_synthesis_flow.hpp>
Public Member Functions
HLSSynthesisFlow (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~HLSSynthesisFlow () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 45 of file hls_synthesis_flow.hpp.
Constructor & Destructor Documentation
HLSSynthesisFlow()
HLSSynthesisFlow::HLSSynthesisFlow (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
. include behavior include HLS include STL include tree include
Definition at line 61 of file hls_synthesis_flow.cpp.
References DesignFlowStep::composed, HLS_SYNTHESIS_FLOW, and ~HLSSynthesisFlow().
 HLSSynthesisFlow()
HLSSynthesisFlow::~HLSSynthesisFlow () [override], [default]
Destructor.
Referenced by HLSSynthesisFlow().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > HLSSynthesisFlow::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 69 of file hls_synthesis_flow.cpp.
References HLS_step::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, HLSFunctionStep::funId, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), OMP_BODY_LOOP_SYNTHESIS_FLOW, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, SUCCESS, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status HLSSynthesisFlow::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 128 of file hls_synthesis_flow.cpp.
References EMPTY.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow/synthesis/hls_synthesis_flow.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow/synthesis/hls_synthesis_flow.cpp