remove_clobber_ga Class Reference
Superclass include.
#include <remove_clobber_ga.hpp>
Public Member Functions
remove_clobber_ga (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~remove_clobber_ga () override
Destructor.
DesignFlowStep_Status InternalExec () override
Updates the tree to have a more compliant CFG.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Static Private Attributes
static bool tree_dumped
flag to check if initial tree has been dumped
Additional Inherited Members
Detailed Description
Superclass include.
Restructure the tree control flow graph
Definition at line 52 of file remove_clobber_ga.hpp.
Constructor & Destructor Documentation
remove_clobber_ga()
remove_clobber_ga::remove_clobber_ga (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
header include
Parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior includes STD include tree includes utility include
Definition at line 69 of file remove_clobber_ga.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~remove_clobber_ga().
 remove_clobber_ga()
remove_clobber_ga::~remove_clobber_ga () [override], [default]
Destructor.
Referenced by remove_clobber_ga().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionFrontendFlowStep::FunctionRelationship > > remove_clobber_ga::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 77 of file remove_clobber_ga.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SWITCH_FIX, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status remove_clobber_ga::InternalExec () [override], [virtual]
Updates the tree to have a more compliant CFG.
skip all non-clobber gimple_assign
perform the substitution
consider only gimple statements using virtual operands
now remove the clobber gimple_assign
Implements FunctionFrontendFlowStep.
Definition at line 101 of file remove_clobber_ga.cpp.
References FrontendFlowStep::AppM, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), phi, sl, SUCCESS, and THROW_ASSERT.
Field Documentation
tree_dumped
bool remove_clobber_ga::tree_dumped [static], [private]
flag to check if initial tree has been dumped
Definition at line 56 of file remove_clobber_ga.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/remove_clobber_ga.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/remove_clobber_ga.cpp