AlteraBackendFlow Class Reference
superclass include
#include <AlteraBackendFlow.hpp>
Public Member Functions
AlteraBackendFlow (const ParameterConstRef Param, const std::string &flow_name, const target_managerRef target)
Constructor.
~AlteraBackendFlow () override
Destructor.
void InitDesignParameters () override
Initializes the parameters.
void ExecuteSynthesis () override
Checks if the execution can be performed and, in case, performs the synthesis.
Private Member Functions
void WriteFlowConfiguration (std::ostream &script) override
Writes the proper flow configuration in the output script.
void xparse_utilization (const std::string &fn)
Parses device utilization.
void CheckSynthesisResults () override
Checks the synthesis results and fills the corresponding datastructures.
void create_sdc (const DesignParametersRef dp)
Creates the constraint file.
Private Attributes
std::map< std::string, double > design_values
design values reported by the tools
Additional Inherited Members
Detailed Description
superclass include
Definition at line 50 of file AlteraBackendFlow.hpp.
Constructor & Destructor Documentation
AlteraBackendFlow()
AlteraBackendFlow::AlteraBackendFlow (const ParameterConstRef Param, const std::string & flow_name, const target_managerRef target)
Constructor.
Definition at line 86 of file AlteraBackendFlow.cpp.
References BackendFlow::debug_level, DEBUG_LEVEL_VERBOSE, BackendFlow::default_data, GET_CLASS, target_device::get_parameter(), target_device::has_parameter(), INDENT_DBG_MEX, BackendFlow::output_level, OUTPUT_LEVEL_VERBOSE, BackendFlow::Param, BackendFlow::parse_flow(), test_panda::parser, PRINT_OUT_MEX, BackendFlow::target, THROW_ERROR, and ~AlteraBackendFlow().
 AlteraBackendFlow()
AlteraBackendFlow::~AlteraBackendFlow () [override], [default]
Destructor.
Referenced by AlteraBackendFlow().
Member Function Documentation
CheckSynthesisResults()
void AlteraBackendFlow::CheckSynthesisResults () [override], [private], [virtual]
Checks the synthesis results and fills the corresponding datastructures.
Implements BackendFlow.
Definition at line 215 of file AlteraBackendFlow.cpp.
References BackendFlow::actual_parameters, clb_model::ALMS, ALTERA_ALM, ALTERA_DSP, ALTERA_FMAX, ALTERA_LE, ALTERA_MEM, ALTERA_REGISTERS, BackendFlow::area_m, clb_model::BRAM, LUT_model::COMBINATIONAL_DELAY, CopyFile(), area_model::create_model(), time_model::create_model(), design_values, clb_model::DSP, BackendFlow::flow_name, FPGA, clb_model::LOGIC_ELEMENTS, BackendFlow::output_level, OUTPUT_LEVEL_MINIMUM, BackendFlow::Param, PARAM_quartus_report, PARAM_top_id, DesignParameters::parameter_values, PRINT_OUT_MEX, clb_model::REGISTERS, STR_CST_synthesis_timing_violation_report, THROW_ASSERT, BackendFlow::time_m, and xparse_utilization().
create_sdc()
void AlteraBackendFlow::create_sdc (const DesignParametersRef dp) [private]
Creates the constraint file.
Definition at line 279 of file AlteraBackendFlow.cpp.
References DesignParameters::component_name, BackendFlow::get_flow_name(), BackendFlow::out_dir, BackendFlow::Param, PARAM_clk_name, PARAM_clk_period, PARAM_connect_iob, PARAM_is_combinational, PARAM_sdc_file, and DesignParameters::parameter_values.
Referenced by InitDesignParameters().
ExecuteSynthesis()
void AlteraBackendFlow::ExecuteSynthesis () [override], [virtual]
Checks if the execution can be performed and, in case, performs the synthesis.
Reimplemented from BackendFlow.
Definition at line 341 of file AlteraBackendFlow.cpp.
References BackendFlow::ExecuteSynthesis(), and THROW_ERROR.
InitDesignParameters()
void AlteraBackendFlow::InitDesignParameters () [override], [virtual]
Initializes the parameters.
Reimplemented from BackendFlow.
Definition at line 308 of file AlteraBackendFlow.cpp.
References BackendFlow::actual_parameters, create_sdc(), target_device::get_parameter(), BackendFlow::Param, PARAM_HDL_files, PARAM_sources_macro_list, PARAM_target_device, PARAM_target_family, DesignParameters::parameter_values, BackendFlow::steps, and BackendFlow::target.
WriteFlowConfiguration()
void AlteraBackendFlow::WriteFlowConfiguration (std::ostream & script) [override], [private], [virtual]
Writes the proper flow configuration in the output script.
Implements BackendFlow.
Definition at line 254 of file AlteraBackendFlow.cpp.
References BackendFlow::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, BackendFlow::Param, and STR.
xparse_utilization()
void AlteraBackendFlow::xparse_utilization (const std::string & fn) [private]
Parses device utilization.
Definition at line 135 of file AlteraBackendFlow.cpp.
References CE_XVM, design_values, XMLDomParser::Exec(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), LOAD_XVM, test_panda::parser, THROW_ASSERT, and THROW_ERROR.
Referenced by CheckSynthesisResults().
Field Documentation
design_values
std::map<std::string, double> AlteraBackendFlow::design_values [private]
design values reported by the tools
Definition at line 53 of file AlteraBackendFlow.hpp.
Referenced by CheckSynthesisResults(), and xparse_utilization().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/AlteraBackendFlow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/AlteraBackendFlow.cpp