MultipleEntryIfReduction Class Reference
Class performing some optimizations exploiting the reduction of BB with n inputs and m outputs.
#include <multiple_entry_if_reduction.hpp>
Public Member Functions
MultipleEntryIfReduction (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~MultipleEntryIfReduction () override
Destructor.
DesignFlowStep_Status InternalExec () override
Extract patterns from the GCC IR.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
double GetAreaCost (const std::list< tree_nodeRef > &list_of_stmt) const
Estimate the area cost of the statements of a basic block.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
tree_managerRef TM
The tree manager.
tree_manipulationRef tree_man
The tree manipulation.
statement_list * sl {nullptr}
The statement list.
bool bb_modified {false}
Modified file.
ScheduleRef schedule
The scheduling solution.
AllocationInformationConstRef allocation_information
The allocation information.
Additional Inherited Members
Detailed Description
Class performing some optimizations exploiting the reduction of BB with n inputs and m outputs.
The block have to contain only phi or conditional statements (such as if and multi way if)
Definition at line 101 of file multiple_entry_if_reduction.hpp.
Constructor & Destructor Documentation
MultipleEntryIfReduction()
MultipleEntryIfReduction::MultipleEntryIfReduction (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
_Param is the set of the parameters
_AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
Definition at line 118 of file multiple_entry_if_reduction.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and DesignFlowStep::parameters.
 MultipleEntryIfReduction()
MultipleEntryIfReduction::~MultipleEntryIfReduction () [override], [default]
Destructor.
Referenced by Initialize().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > MultipleEntryIfReduction::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 140 of file multiple_entry_if_reduction.cpp.
References ABORTED, BB_FEEDBACK_EDGES_IDENTIFICATION, BUILD_VIRTUAL_PHI, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, NONEXISTENT, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, and UNNECESSARY.
GetAreaCost()
double MultipleEntryIfReduction::GetAreaCost (const std::list< tree_nodeRef > & list_of_stmt) const [private]
Estimate the area cost of the statements of a basic block.
Definition at line 960 of file multiple_entry_if_reduction.cpp.
References allocation_information, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, AllocationInformation::GetStatementArea(), INDENT_DBG_MEX, and STR.
Referenced by InternalExec().
HasToBeExecuted()
bool MultipleEntryIfReduction::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 972 of file multiple_entry_if_reduction.cpp.
References FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_id, Wrefcount< T >::lock(), and DesignFlowStep::parameters.
Initialize()
void MultipleEntryIfReduction::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 124 of file multiple_entry_if_reduction.cpp.
References allocation_information, FrontendFlowStep::AppM, bb_modified, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), DesignFlowStep::parameters, sl, TM, tree_man, and ~MultipleEntryIfReduction().
InternalExec()
DesignFlowStep_Status MultipleEntryIfReduction::InternalExec () [override], [virtual]
Extract patterns from the GCC IR.
Returns
the exit status of this step
if the operation had been done
list to save the block to eliminate after the reduction
The basic block graphs
Analyze if a basic block is a possible candidate
We skip basic block containing gimple_call since it would require modification of the call graph
Skip headers
The index of the loop to be considered (the most internal loops which contains the definition and all the uses
The depth of the loop to be considered
Create the copies
Fixing phi: duplicating def_edge of ssa name which are not defined in the current bb
Build list of phis + gimple_nodes
The ssa defined by the statement (left part of gimple assignment and vdef)
The set of basic block uses
The set of statement uses
The set of reaching definition
Cache of created phi - first key is the used ssa - second key is the basic block where is created
Duplicating statement
Defined in a different basic block
The old ssa
Management of vuses for overwrite
Use is in the considered loop
Use is in a more nested loop
Use is in a less nested loop
Set of basic blocks belonging to the loop
Check if there a use of the ssa in the header; if not basic blocks after uses can be removed
Remove all basic blocks from which no use can be reached
Set of basic blocks to be analyzed
True if different definitions reach this bb from all the bbs
If this is the basic block contains a use
If the basic block is the source of a feedback edge, fix the phi in the header
endfor-list_of_bloc
eliminate the blocks (remove them from the tree)
Implements FunctionFrontendFlowStep.
Definition at line 191 of file multiple_entry_if_reduction.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, BB_EXIT, BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), tree_manager::CGetTreeNode(), tree_helper::ComputeSsaUses(), tree_manipulation::create_ssa_name(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), GetAreaCost(), BBGraph::GetBBNodeInfo(), FunctionFrontendFlowStep::GetName(), graph::GetSelector(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, statement_list::list_of_bloc, max(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, phi, tree_manager::ReplaceTreeNode(), sl, STR, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_RES, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, tree_man, and UNCHANGED.
Field Documentation
allocation_information
AllocationInformationConstRef MultipleEntryIfReduction::allocation_information [private]
The allocation information.
Definition at line 120 of file multiple_entry_if_reduction.hpp.
Referenced by GetAreaCost(), and Initialize().
bb_modified
bool MultipleEntryIfReduction::bb_modified {false} [private]
Modified file.
Definition at line 114 of file multiple_entry_if_reduction.hpp.
Referenced by Initialize().
schedule
ScheduleRef MultipleEntryIfReduction::schedule [private]
The scheduling solution.
Definition at line 117 of file multiple_entry_if_reduction.hpp.
sl
statement_list* MultipleEntryIfReduction::sl {nullptr} [private]
The statement list.
Definition at line 111 of file multiple_entry_if_reduction.hpp.
Referenced by Initialize(), and InternalExec().
TM
tree_managerRef MultipleEntryIfReduction::TM [private]
The tree manager.
Definition at line 105 of file multiple_entry_if_reduction.hpp.
Referenced by Initialize(), and InternalExec().
tree_man
tree_manipulationRef MultipleEntryIfReduction::tree_man [private]
The tree manipulation.
Definition at line 108 of file multiple_entry_if_reduction.hpp.
Referenced by Initialize(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/multiple_entry_if_reduction.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/multiple_entry_if_reduction.cpp