classic_datapath Class Reference
#include <classic_datapath.hpp>
Public Member Functions
classic_datapath (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::CLASSIC_DATAPATH_CREATOR)
Constructor.
~classic_datapath () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
void add_clock_reset (structural_objectRef &clock_sign, structural_objectRef &reset_sign)
Adds the clock and reset ports to the structural description of the circuit.
virtual void add_ports ()
Adds the input/output ports of the module.
Additional Inherited Members
Detailed Description
Definition at line 53 of file classic_datapath.hpp.
Constructor & Destructor Documentation
classic_datapath()
classic_datapath::classic_datapath (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::CLASSIC_DATAPATH_CREATOR)
Constructor.
STD includes.
Parameters
design_flow_manager is the design flow manager
STL includes technology/physical_library include utility includes
Definition at line 95 of file classic_datapath.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~classic_datapath().
 classic_datapath()
classic_datapath::~classic_datapath () [override], [default]
Destructor.
Referenced by classic_datapath().
Member Function Documentation
add_clock_reset()
void classic_datapath::add_clock_reset (structural_objectRef & clock_sign, structural_objectRef & reset_sign) [protected]
Adds the clock and reset ports to the structural description of the circuit.
Parameters
clock_sign is the object representing the clock signal
reset_sign is the object representing the reset signal
define boolean type for clock and reset signal
add clock port
add reset port
Definition at line 183 of file classic_datapath.cpp.
References structural_manager::add_port(), CLOCK_PORT_NAME, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, structural_manager::get_circ(), HLSFunctionStep::HLS, port_o::IN, PRINT_DBG_MEX, and RESET_PORT_NAME.
Referenced by InternalExec(), and datapath_parallel_cs::InternalExec().
add_ports()
void classic_datapath::add_ports () [protected], [virtual]
Adds the input/output ports of the module.
add start and done when needed
Reimplemented in datapath_parallel_cs, and datapath_cs.
Definition at line 205 of file classic_datapath.cpp.
References structural_manager::add_connection(), memory::add_memory_parameter(), structural_manager::add_port(), structural_manager::add_sign(), FunctionBehavior::CGetBehavioralHelper(), CONSTANT_STD, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, structural_object::find_member(), hls::functionId, HLSFunctionStep::funId, structural_manager::get_circ(), conn_binding::get_constant_objs(), BehavioralHelper::get_function_index(), structural_type_descriptor::get_name(), BehavioralHelper::get_parameters(), conn_binding::get_port(), BehavioralHelper::GetFunctionReturnType(), HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, conn_binding::IN, port_o::IN, INDENT_DBG_MEX, LIBRARY_STD, conn_binding::OUT, port_o::OUT, port_o_K, PRINT_DBG_STRING, BehavioralHelper::print_type(), BehavioralHelper::PrintVariable(), hls::Rconn, RETURN_PORT_NAME, generic_obj::set_out_sign(), generic_obj::set_structural_obj(), structural_object::SetParameter(), START_PORT_NAME, STR, and structural_object::type_resize().
Referenced by datapath_cs::add_ports(), datapath_parallel_cs::add_ports(), and InternalExec().
InternalExec()
DesignFlowStep_Status classic_datapath::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Test on previous steps. They checks if schedule and connection binding have been performed. If they didn't, circuit cannot be created.
Test on memory allocation
main circuit type
top circuit creation
Set some descriptions and legal stuff
add clock and reset to circuit. It increments in_port number and update in_port_map
add all input ports
add registers, connecting them to clock and reset ports
allocate functional units
allocate interconnections
circuit is now complete. circuit manager can be initialized and dot representation can be created
Implements HLSFunctionStep.
Reimplemented in datapath_parallel_cs.
Definition at line 103 of file classic_datapath.cpp.
References add_clock_reset(), structural_manager::add_connection(), add_ports(), reg_binding::add_to_SM(), StateTransitionGraphManager::add_to_SM(), fu_binding::add_to_SM(), conn_binding::add_to_SM(), FunctionBehavior::CGetBehavioralHelper(), CLOCK_PORT_NAME, structural_manager::COMPLETE_G, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, structural_object::find_member(), flipflop_SR, HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_name(), HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, INDENT_DBG_MEX, structural_manager::INIT(), LIBRARY_STD, hls::Param, DesignFlowStep::parameters, port_o_K, hls::Rconn, reset(), RESET_PORT_NAME, hls::Rfu, hls::Rreg, structural_object::set_black_box(), structural_manager::set_top_info(), hls::STG, SUCCESS, THROW_ASSERT, and structural_manager::WriteDot().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/datapath_creation/classic_datapath.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/datapath_creation/classic_datapath.cpp