call_expr_fix Class Reference
Restructure the tree control flow graph.
#include <call_expr_fix.hpp>
Public Member Functions
call_expr_fix (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~call_expr_fix () override
Destructor.
DesignFlowStep_Status InternalExec () override
Updates the tree to have a more compliant IR.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Restructure the tree control flow graph.
Definition at line 61 of file call_expr_fix.hpp.
Constructor & Destructor Documentation
call_expr_fix()
call_expr_fix::call_expr_fix (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
header include
Parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior includes STD include tree includes utility include
Definition at line 68 of file call_expr_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~call_expr_fix().
 call_expr_fix()
call_expr_fix::~call_expr_fix () [override], [default]
Destructor.
Referenced by call_expr_fix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionFrontendFlowStep::FunctionRelationship > > call_expr_fix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 76 of file call_expr_fix.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status call_expr_fix::InternalExec () [override], [virtual]
Updates the tree to have a more compliant IR.
Returns
the exit status of this step
Checking if there are gimple_call or call_expr for which the fix apply
check if fun_type there is only one parameter and it is equal to void
check if fun_type there is only one parameter and it is equal to void
Implements FunctionFrontendFlowStep.
Definition at line 101 of file call_expr_fix.cpp.
References FrontendFlowStep::AppM, test_panda::args, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, tree_helper::print_function_name(), sl, SUCCESS, ToString(), and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/call_expr_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/call_expr_fix.cpp