ParallelMemoryFuBinding Class Reference
Superclass include.
#include <parallel_memory_fu_binding.hpp>
Public Member Functions
ParallelMemoryFuBinding (const HLS_managerConstRef HLS_mgr, const unsigned int function_id, const ParameterConstRef parameters)
Constructor.
virtual void add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port)
Instance the functional unit inside the structural representation of the datapath.
Data Fields
CustomMap< structural_objectRef, structural_objectRef > component_to_allow_mem_access
For each component, the corresponding ALLOW_MEM_ACCESS_FU.
Protected Member Functions
virtual bool manage_module_ports (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, const structural_objectRef curr_gate, unsigned int num)
Protected Attributes
CustomSet< structural_objectRef > access_allowed_killeds
Internal objects for which access_allowed was killed.
Additional Inherited Members
Detailed Description
Superclass include.
utility include
Definition at line 50 of file parallel_memory_fu_binding.hpp.
Constructor & Destructor Documentation
ParallelMemoryFuBinding()
ParallelMemoryFuBinding::ParallelMemoryFuBinding (const HLS_managerConstRef _HLS_mgr, const unsigned int _function_id, const ParameterConstRef _parameters)
Constructor.
Header class.
Parameters
HLS_mgr is the HLS manager
function_id is the index of the function
parameters is the set of input parameters
. include circuit include HLS includes HLS/functions include HLS/module_allocation include HLS/virtual_components STD include STL include technology includes tree includes utility include
Definition at line 80 of file parallel_memory_fu_binding.cpp.
References fu_binding::debug_level, GET_CLASS, and fu_binding::parameters.
Member Function Documentation
add_to_SM()
void ParallelMemoryFuBinding::add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port) [virtual]
Instance the functional unit inside the structural representation of the datapath.
Collecting memory enabled signals which have to be put in and
Considering atomic operations
Check if there is at least a memory enabled to be connected
Collecting ports of internal objects
Reimplemented from fu_binding.
Definition at line 85 of file parallel_memory_fu_binding.cpp.
References fu_binding::add_to_SM(), fu_binding::allocation_information, CHANNELS_TYPE_MEM_ACC_P1N, CLOCK_PORT_NAME, component_to_allow_mem_access, hls::datapath, fu_binding::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, hls::functionId, fu_binding::get_allocation_list(), AllocationInformation::get_fu(), GET_TYPE, structural_object::get_typeRef(), hls::HLS_T, port_o::IN, INDENT_DBG_MEX, LIBRARY_PC, fu_binding::manage_extern_global_port(), fu_binding::op_graph, port_o::OUT, fu_binding::parameters, port_o_K, reset(), RESET_PORT_NAME, hls::Rfu, STR, THROW_ASSERT, THROW_UNREACHABLE, and TYPE_ATOMIC.
manage_module_ports()
bool ParallelMemoryFuBinding::manage_module_ports (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, const structural_objectRef curr_gate, unsigned int num) [protected], [virtual]
Reimplemented from fu_binding.
Definition at line 358 of file parallel_memory_fu_binding.cpp.
References access_allowed_killeds, structural_object::find_member(), hls::functionId, structural_object::get_typeRef(), structural_type_descriptor::id_type, fu_binding::manage_module_ports(), and port_o_K.
Field Documentation
access_allowed_killeds
CustomSet<structural_objectRef> ParallelMemoryFuBinding::access_allowed_killeds [protected]
Internal objects for which access_allowed was killed.
Definition at line 54 of file parallel_memory_fu_binding.hpp.
Referenced by manage_module_ports().
component_to_allow_mem_access
CustomMap<structural_objectRef, structural_objectRef> ParallelMemoryFuBinding::component_to_allow_mem_access
For each component, the corresponding ALLOW_MEM_ACCESS_FU.
Definition at line 62 of file parallel_memory_fu_binding.hpp.
Referenced by add_to_SM().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/parallel_memory_fu_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/parallel_memory_fu_binding.cpp