NP_functionality Class Reference
Not parsed functionality descriptor of a module.
#include <NP_functionality.hpp>
Public Types
enum NP_functionaly_type {
TABLE = 0,
EQUATION,
PORT_LIST,
LIBRARY,
GRAPH,
FSM,
FSM_CS,
SC_PROVIDED,
VHDL_PROVIDED,
VERILOG_PROVIDED,
SYSTEM_VERILOG_PROVIDED,
VERILOG_GENERATOR,
VHDL_GENERATOR,
FLOPOCO_PROVIDED,
BAMBU_PROVIDED,
BLIF_DESCRIPTION,
AIGER_DESCRIPTION,
IP_COMPONENT,
IP_LIBRARY,
VERILOG_FILE_PROVIDED,
VHDL_FILE_PROVIDED,
UNKNOWN
 }
functionality type descriptors.
Public Member Functions
NP_functionality ()=default
Constructor.
NP_functionality (const NP_functionalityRef &obj)
Constructor.
~NP_functionality ()=default
Destructor.
void add_NP_functionality (NP_functionaly_type type, const std::string &functionality_description)
Add a non SystemC based description.
std::string get_NP_functionality (NP_functionaly_type type) const
Return the description provided the type.
bool exist_NP_functionality (NP_functionaly_type type) const
Return true in case there exist a functionaly of the given type.
std::string get_library_name () const
return the name of the library in case it there exists a LIBRARY based description.
void get_library_parameters (std::vector< std::string > &parameters) const
fill a vector with the library parameters in case it there exists a LIBRARY based description.
void get_port_list (std::map< unsigned int, std::map< std::string, std::string >> &InPortMap, std::map< unsigned int, std::map< std::string, std::string >> &OutPortMap) const
void xload (const xml_element *Enode)
Load a NP_functionality starting from an xml file.
void xwrite (xml_element *rootnode)
Add a NP_functionality to an xml tree.
void print (std::ostream &os) const
Print the Non-SystemC based functionality description (for debug purpose).
std::string get_kind_text () const
Definition of get_kind_text()
Private Member Functions
NP_functionaly_type to_NP_functionaly_type (const std::string &val)
Convert a string into the corresponding NP_functionaly_type enumerative type.
Private Attributes
std::map< NP_functionaly_type, std::string > descriptions
Store the description of the functionality.
Static Private Attributes
static const char * NP_functionaly_typeNames []
store the names of the enumerative NSC_functionaly_type.
Detailed Description
Not parsed functionality descriptor of a module.
Usually a behavior is parsed through the C/C++/SystemC front-end. This class is used in all cases where an alternative description is provided:
true tables
library based descriptions
graph based descriptions(e.g. NFA)
SystemC provided descriptions (not parsed)
VHDL provided descriptions
Verilog provided descriptions Library based descriptions (e.g., LIBRARY) are based on a string containing the name of the library, a list of port names for which a parameters has to be specified. Port vectors are parametrized with the number of port associated, while ports are parametrized in case the type is a integer with the number of bits.
Definition at line 85 of file NP_functionality.hpp.
Member Enumeration Documentation
NP_functionaly_type
enum NP_functionality::NP_functionaly_type
functionality type descriptors.
Currently, it is foreseen six type of descriptions:
True Tables
Library based descriptions
Graph based descriptions like Non deterministic finite automata (NFA)
Finite state machine description of Moore/Mealy machine
SystemC provided descriptions (not parsed)
VHDL provided descriptions
Verilog provided descriptions
System Verilog provided descriptions
Enumerator
TABLE
EQUATION
PORT_LIST
LIBRARY
GRAPH
FSM
FSM_CS
SC_PROVIDED
VHDL_PROVIDED
VERILOG_PROVIDED
SYSTEM_VERILOG_PROVIDED
VERILOG_GENERATOR
VHDL_GENERATOR
FLOPOCO_PROVIDED
BAMBU_PROVIDED
BLIF_DESCRIPTION
AIGER_DESCRIPTION
IP_COMPONENT
IP_LIBRARY
VERILOG_FILE_PROVIDED
VHDL_FILE_PROVIDED
UNKNOWN
Definition at line 98 of file NP_functionality.hpp.
Constructor & Destructor Documentation
NP_functionality() [1/2]
NP_functionality::NP_functionality () [default]
Constructor.
NP_functionality() [2/2]
NP_functionality::NP_functionality (const NP_functionalityRef & obj) [explicit]
Constructor.
Definition at line 207 of file NP_functionality.cpp.
References descriptions, get_NP_functionality(), and UNKNOWN.
 NP_functionality()
NP_functionality::~NP_functionality () [default]
Destructor.
Member Function Documentation
add_NP_functionality()
void NP_functionality::add_NP_functionality (NP_functionaly_type type, const std::string & functionality_description)
Add a non SystemC based description.
Definition at line 99 of file NP_functionality.cpp.
References descriptions, and test_panda::type.
Referenced by structural_manager::add_NP_functionality().
exist_NP_functionality()
bool NP_functionality::exist_NP_functionality (NP_functionaly_type type) const
Return true in case there exist a functionaly of the given type.
Definition at line 144 of file NP_functionality.cpp.
References descriptions.
Referenced by RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::AnalyzeFu(), HDL_manager::get_post_order_structural_components(), HDL_manager::is_fsm(), module::set_NP_functionality(), fu_binding::specialise_fu(), HDL_manager::write_components(), HDL_manager::write_module(), verilog_writer::write_timing_specification(), and verilog_writer::write_transition_output_functions().
get_kind_text()
std::string NP_functionality::get_kind_text () const [inline]
Definition of get_kind_text()
Definition at line 194 of file NP_functionality.hpp.
Referenced by xwrite().
get_library_name()
std::string NP_functionality::get_library_name () const
return the name of the library in case it there exists a LIBRARY based description.
Definition at line 149 of file NP_functionality.cpp.
References get_NP_functionality(), LIBRARY, and test_panda::tokens.
get_library_parameters()
void NP_functionality::get_library_parameters (std::vector< std::string > & parameters) const
fill a vector with the library parameters in case it there exists a LIBRARY based description.
Parameters
parameters is the filled vector.
Definition at line 162 of file NP_functionality.cpp.
References get_NP_functionality(), LIBRARY, and test_panda::tokens.
Referenced by RTLCharacterization::AnalyzeCell(), module::get_NP_library_parameters(), and fu_binding::specialise_fu().
get_NP_functionality()
std::string NP_functionality::get_NP_functionality (NP_functionaly_type type) const
Return the description provided the type.
Definition at line 132 of file NP_functionality.cpp.
References descriptions.
Referenced by structural_manager::add_port(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), allocation::check_generated_bambu_flopoco(), fu_binding::check_parametrization(), port_o::fix_port_properties(), allocation::get_compliant_pipelined_unit(), get_library_name(), get_library_parameters(), HDL_manager::get_mod_typename(), get_port_list(), HDL_manager::get_post_order_structural_components(), HDL_manager::is_fsm(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), NP_functionality(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), HDL_manager::write_components(), HDL_manager::write_module(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), VHDL_writer::write_module_parametrization_decl(), verilog_writer::write_module_parametrization_decl(), system_verilog_writer::write_NP_functionalities(), VHDL_writer::write_NP_functionalities(), verilog_writer::write_NP_functionalities(), and verilog_writer::write_transition_output_functions().
get_port_list()
void NP_functionality::get_port_list (std::map< unsigned int, std::map< std::string, std::string >> & InPortMap, std::map< unsigned int, std::map< std::string, std::string >> & OutPortMap) const
Definition at line 180 of file NP_functionality.cpp.
References get_NP_functionality(), PORT_LIST, SplitString(), and THROW_ASSERT.
print()
void NP_functionality::print (std::ostream & os) const
Print the Non-SystemC based functionality description (for debug purpose).
Parameters
os is the output stream
Definition at line 123 of file NP_functionality.cpp.
References descriptions, and NP_functionaly_typeNames.
Referenced by module::print().
to_NP_functionaly_type()
NP_functionality::NP_functionaly_type NP_functionality::to_NP_functionaly_type (const std::string & val) [private]
Convert a string into the corresponding NP_functionaly_type enumerative type.
STD include.
Parameters
val is the string version of the enum.
utility include
Definition at line 62 of file NP_functionality.cpp.
References NP_functionaly_typeNames, THROW_ASSERT, and UNKNOWN.
Referenced by xload().
xload()
void NP_functionality::xload (const xml_element * Enode)
Load a NP_functionality starting from an xml file.
Parameters
node is a node of the xml tree.
Definition at line 104 of file NP_functionality.cpp.
References descriptions, attribute_sequence::get_attributes(), and to_NP_functionaly_type().
Referenced by module::xload().
xwrite()
void NP_functionality::xwrite (xml_element * rootnode)
Add a NP_functionality to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the non SystemC based description is attached.
Definition at line 113 of file NP_functionality.cpp.
References xml_child::add_child_element(), descriptions, get_kind_text(), NP_functionaly_typeNames, and WRITE_XNVM2.
Referenced by module::xwrite().
Field Documentation
descriptions
std::map<NP_functionaly_type, std::string> NP_functionality::descriptions [private]
Store the description of the functionality.
Definition at line 126 of file NP_functionality.hpp.
Referenced by add_NP_functionality(), exist_NP_functionality(), get_NP_functionality(), NP_functionality(), print(), xload(), and xwrite().
NP_functionaly_typeNames
const char * NP_functionality::NP_functionaly_typeNames [static], [private]
Initial value:
= {"TABLE",
                                                            "EQUATION",
                                                            "PORT_LIST",
                                                            "LIBRARY",
                                                            "GRAPH",
                                                            "FSM",
                                                            "FSM_CS",
                                                            "SC_PROVIDED",
                                                            "VHDL_PROVIDED",
                                                            "VERILOG_PROVIDED",
                                                            "SYSTEM_VERILOG_PROVIDED",
                                                            "VERILOG_GENERATOR",
                                                            "VHDL_GENERATOR",
                                                            "FLOPOCO_PROVIDED",
                                                            "BAMBU_PROVIDED",
                                                            "BLIF_DESCRIPTION",
                                                            "AIGER_DESCRIPTION",
                                                            "IP_COMPONENT",
                                                            "IP_LIBRARY",
                                                            "VERILOG_FILE_PROVIDED",
                                                            "VHDL_FILE_PROVIDED",
                                                            "UNKNOWN"}
store the names of the enumerative NSC_functionaly_type.
Definition at line 128 of file NP_functionality.hpp.
Referenced by print(), to_NP_functionaly_type(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/NP_functionality.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/NP_functionality.cpp