WriteTechnology Class Reference
Step which write technology information.
#include <write_technology.hpp>
Public Member Functions
WriteTechnology (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~WriteTechnology () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Step which write technology information.
Definition at line 56 of file write_technology.hpp.
Constructor & Destructor Documentation
WriteTechnology()
WriteTechnology::WriteTechnology (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
TM is the technology manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include constants include polixml include technology include technology/physical_library include technology/target_device include
Definition at line 63 of file write_technology.cpp.
References WRITE_TECHNOLOGY, and ~WriteTechnology().
 WriteTechnology()
WriteTechnology::~WriteTechnology () [override], [default]
Destructor.
Referenced by WriteTechnology().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > WriteTechnology::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 109 of file write_technology.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, FIX_CHARACTERIZATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_DEFAULT_TECHNOLOGY, LOAD_DEVICE_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status WriteTechnology::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 70 of file write_technology.cpp.
References xml_child::add_child_element(), xml_document::create_root_node(), technology_manager::get_library_list(), technology_manager::get_library_manager(), INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, PRINT_OUT_MEX, library_manager::set_info(), SUCCESS, TechnologyFlowStep::target, TechnologyFlowStep::TM, xml_document::write_to_file_formatted(), library_manager::XML, and technology_manager::xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/write_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/write_technology.cpp