AddBbEcfgEdges Class Reference
Class to extend basic block cfg.
#include <add_bb_ecfg_edges.hpp>
Public Member Functions
AddBbEcfgEdges (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~AddBbEcfgEdges () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the adding of flow edges.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Class to extend basic block cfg.
Definition at line 62 of file add_bb_ecfg_edges.hpp.
Constructor & Destructor Documentation
AddBbEcfgEdges()
AddBbEcfgEdges::AddBbEcfgEdges (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manage
parameters is the set of the parameters
Behavior include Graph include Parameter include STL include Utility include
Definition at line 73 of file add_bb_ecfg_edges.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~AddBbEcfgEdges().
 AddBbEcfgEdges()
AddBbEcfgEdges::~AddBbEcfgEdges () [override], [default]
Destructor.
Referenced by AddBbEcfgEdges().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > AddBbEcfgEdges::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 81 of file add_bb_ecfg_edges.cpp.
References BB_FEEDBACK_EDGES_IDENTIFICATION, BB_ORDER_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status AddBbEcfgEdges::InternalExec () [override], [virtual]
Performs the adding of flow edges.
Returns
the exit status of this step
The behavioral helper
The function name
The control flow graph with feedback of basic blocks
The loop structure
Adding edges in basic block graphs from sources of feedback edges to landing pads
add Extended edges to manage in/out dependencies when we have multi-entries in a loop (aka irreducible loop)
Sources of feedback loop
The targets of the flow edges they can be different from landing_pads of this loop if the edge which connects a block of the loop to a landing_pads is the feedback edge of an external loop. In this case the block must be connected to the landing pads of the external loop
compute sources
Check if the target belongs to the current loop
Landing pads
While at least one landing pad of the current loop or of one of its ancestor is reached with a feedback edge
Implements FunctionFrontendFlowStep.
Definition at line 105 of file add_bb_ecfg_edges.cpp.
References BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::EBB, ECFG_SELECTOR, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, BehavioralHelper::get_function_name(), graph::GetSelector(), INDENT_DBG_MEX, DesignFlowStep::parameters, STR, SUCCESS, THROW_UNREACHABLE, and graph::TopologicalSort().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_bb_ecfg_edges.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/add_bb_ecfg_edges.cpp