ExtractOmpAtomic Class Reference
Superclass include.
#include <extract_omp_atomic.hpp>
Public Member Functions
ExtractOmpAtomic (const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~ExtractOmpAtomic ()
Destructor.
DesignFlowStep_Status InternalExec ()
Restructures the unstructured code.
virtual void Initialize ()
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
virtual const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Extract openmp atomic in a separate function
Definition at line 51 of file extract_omp_atomic.hpp.
Constructor & Destructor Documentation
ExtractOmpAtomic()
ExtractOmpAtomic::ExtractOmpAtomic (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Param is the set of the parameters
. include behavior includes parser/treegcc include STL include tree includes utility include
Definition at line 70 of file extract_omp_atomic.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and DesignFlowStep::parameters.
 ExtractOmpAtomic()
ExtractOmpAtomic::~ExtractOmpAtomic ()
Destructor.
Definition at line 76 of file extract_omp_atomic.cpp.
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > ExtractOmpAtomic::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 80 of file extract_omp_atomic.cpp.
References FrontendFlowStep::AppM, BASIC_BLOCKS_CFG_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void ExtractOmpAtomic::Initialize () [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 107 of file extract_omp_atomic.cpp.
InternalExec()
DesignFlowStep_Status ExtractOmpAtomic::InternalExec () [virtual]
Restructures the unstructured code.
Implements FunctionFrontendFlowStep.
Definition at line 111 of file extract_omp_atomic.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, BB_ENTRY, block::block(), counter, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, FunctionFrontendFlowStep::GetName(), INDENT_DBG_MEX, FrontendFlowStep::PrintTreeManager(), SUCCESS, THROW_ERROR, UNCHANGED, and FunctionFrontendFlowStep::WriteBBGraphDot().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/extract_omp_atomic.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/extract_omp_atomic.cpp