/home/osboxes/bambu/PandA-bambu/src/spider.cpp File Reference
Parser for deep profiling information.
#include `config_HAVE_CMOS_BUILT.hpp`
#include `config_HAVE_EXPERIMENTAL.hpp`
#include `config_HAVE_FROM_ARCH_BUILT.hpp`
#include `config_HAVE_FROM_CSV_BUILT.hpp`
#include `config_HAVE_FROM_LIBERTY.hpp`
#include `config_HAVE_FROM_PROFILING_ANALYIS_BUILT.hpp`
#include `config_HAVE_R.hpp`
#include `SpiderParameter.hpp`
#include <boost/algorithm/string/replace.hpp>
#include <boost/filesystem/operations.hpp>
#include `design_flow_graph.hpp`
#include `design_flow_manager.hpp`
#include `translator.hpp`
#include `data_xml_parser.hpp`
#include <fstream>
#include <iosfwd>
#include <string>
#include `custom_map.hpp`
#include `custom_set.hpp`
#include `dbgPrintHelper.hpp`
#include `exceptions.hpp`
#include `string_manipulation.hpp`
Macros
#define MAX_LENGTH 10000
Autoheader include.
#define INIT(x, y) x.push_back(std::string(y))
Functions
int main (int argc, char *argv[])
Detailed Description
Parser for deep profiling information.
Author
Daniele Loiacono loiacono@elet.polimi.it
Macro Definition Documentation
INIT
#define INIT(x, y) x.push_back(std::string(y))
Definition at line 151 of file spider.cpp.
MAX_LENGTH
#define MAX_LENGTH 10000
Autoheader include.
. includes boost include constants include design_flows include design_flows/backend/ToDataFile includes parser/data_xml include STD include utility includes
Definition at line 149 of file spider.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 153 of file spider.cpp.
References ToDataFileStep::ComputeSignature(), TechnologyFlowStep::ComputeSignature(), target_device::create_device(), DEBUG_LEVEL_MINIMUM, DEBUG_LEVEL_VERY_PEDANTIC, exit_code, FF_CSV, FF_TEX, FF_TGFF, FF_UNKNOWN, FF_VERILOG, FF_VHDL, FF_XML, FF_XML_EXPERIMENTAL_SETUP, FF_XML_IP_XACT_COMPONENT, FF_XML_IP_XACT_CONFIG, FF_XML_IP_XACT_DESIGN, FF_XML_IP_XACT_GENERATOR, FF_XML_SKIP_ROW, FF_XML_SYM_SIM, FF_XML_TEX_TABLE, FF_XML_WGT_GM, FF_XML_WGT_SYM, FIX_CHARACTERIZATION, FPGA, INDENT_DBG_MEX, INDENT_OUT_MEX, INFINITE_LONG_DOUBLE, LOAD_DEVICE_TECHNOLOGY, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_NONE, OUTPUT_LEVEL_VERBOSE, PARAMETER_NOTPARSED, PARAMETER_PARSED, test_panda::parameters, PRINT_DBG_MEX, PRINT_OUT_MEX, read_technology_library(), SplitString(), STR, THROW_ASSERT, THROW_ERROR, and WRITE_TECHNOLOGY.