StateTransitionGraphManager Class Reference
Class used to manage a graph into finite state machine representation; it contains methods to build the graph, to add nodes, edges...
#include <state_transition_graph_manager.hpp>
Public Member Functions
StateTransitionGraphManager (const HLS_managerConstRef HLSMgr, hlsRef HLS, const ParameterConstRef parameters)
Constructor of the class.
~StateTransitionGraphManager ()
Destructor.
CustomOrderedSet< vertex > get_execution_states (const vertex &op) const
CustomOrderedSet< vertex > get_ending_states (const vertex &op) const
CustomOrderedSet< vertex > get_starting_states (const vertex &op) const
void compute_min_max ()
compute the minimum and maximum number of cycles when possible
StateTransitionGraphRef GetStg ()
Returns pointer to state transition graph created.
StateTransitionGraphRef GetEPPStg ()
Returns pointer to acyclic STG with additional edges for Efficient Path Profiling.
const StateTransitionGraphConstRef CGetEPPStg () const
Returns pointer to acyclic STG with additional edges for Efficient Path Profiling.
const StateTransitionGraphConstRef CGetStg () const
Returns pointer to state transition graph created.
StateTransitionGraphRef GetAstg ()
Returns pointer to state transition graph created.
const StateTransitionGraphConstRef CGetAstg () const
Returns pointer to state transition graph created.
void print_statistics () const
vertex get_entry_state () const
Gets vertex that represents state that contains entry node.
std::string get_state_name (vertex state) const
Get the name of a state.
vertex get_exit_state () const
Gets vertex that represents state that contains exit node.
unsigned int get_number_of_states () const
void add_multi_unbounded_obj (vertex s, const CustomOrderedSet< vertex > &ops)
void specialise_mu (structural_objectRef &mu_mod, generic_objRef mu) const
const std::map< vertex, generic_objRef > & get_mu_ctrls () const
void add_to_SM (structural_objectRef clock_port, structural_objectRef reset_port)
Add components to the datapath required by the FSM.
Data Fields
const StateTransitionGraph_constructorRef STG_builder
reference to the class for building the graph
Private Types
enum StateTypes { EXECUTING,
STARTING,
ENDING
 }
Private Member Functions
CustomOrderedSet< vertex > get_states (const vertex &op, StateTypes statetypes) const
Private Attributes
const StateTransitionGraphsCollectionRef state_transition_graphs_collection
The bulk graph.
const StateTransitionGraphRef ACYCLIC_STG_graph
The acyclic version of the STG.
const StateTransitionGraphRef STG_graph
The complete version of the STG.
const StateTransitionGraphRef EPP_STG_graph
The acyclic version of stg with additional edges necessary for Efficient Path Profiling.
const OpGraphConstRef op_function_graph
reference to operation graph
const ParameterConstRef Param
class containing all the parameters
int output_level
verbosity level
int debug_level
debugging level
hlsRef HLS
HLS data-structure.
std::map< vertex, generic_objRef > multi_unbounded_table
map between state and multi-unbounded controllers
Detailed Description
Class used to manage a graph into finite state machine representation; it contains methods to build the graph, to add nodes, edges...
and also to write the dotty representation of the graph. Two different graphs have been stored: the finite state machine and the related acyclic version (without any feedback edges)
Definition at line 70 of file state_transition_graph_manager.hpp.
Member Enumeration Documentation
StateTypes
enum StateTransitionGraphManager::StateTypes [private]
Enumerator
EXECUTING
STARTING
ENDING
Definition at line 98 of file state_transition_graph_manager.hpp.
Constructor & Destructor Documentation
StateTransitionGraphManager()
StateTransitionGraphManager::StateTransitionGraphManager (const HLS_managerConstRef _HLSMgr, hlsRef _HLS, const ParameterConstRef _Param)
Constructor of the class.
Header include.
It creates a new empty graph and it sets reference to hls class
Parameters
HLS is the HLS data structure
Behavior include hls include Parameter include State transition graph include Tree include Utility include
Definition at line 84 of file state_transition_graph_manager.cpp.
References STG_builder, and ~StateTransitionGraphManager().
 StateTransitionGraphManager()
StateTransitionGraphManager::~StateTransitionGraphManager () [default]
Destructor.
Referenced by StateTransitionGraphManager().
Member Function Documentation
add_multi_unbounded_obj()
void StateTransitionGraphManager::add_multi_unbounded_obj (vertex s, const CustomOrderedSet< vertex > & ops)
Definition at line 249 of file state_transition_graph_manager.cpp.
References multi_unbounded_table, and STG_graph.
Referenced by BB_based_stg::InternalExec().
add_to_SM()
void StateTransitionGraphManager::add_to_SM (structural_objectRef clock_port, structural_objectRef reset_port)
Add components to the datapath required by the FSM.
Definition at line 269 of file state_transition_graph_manager.cpp.
References CLOCK_PORT_NAME, hls::datapath, debug_level, DEBUG_LEVEL_VERBOSE, structural_object::find_member(), structural_manager::get_circ(), HLS, hls::HLS_T, INDENT_DBG_MEX, multi_unbounded_table, port_o_K, RESET_PORT_NAME, SIMPLEJOIN_STD, and specialise_mu().
Referenced by get_mu_ctrls(), and classic_datapath::InternalExec().
CGetAstg()
const StateTransitionGraphConstRef StateTransitionGraphManager::CGetAstg () const
Returns pointer to state transition graph created.
Returns
reference to a graph that contains information about operations to be executed and control edges
Definition at line 103 of file state_transition_graph_manager.cpp.
References ACYCLIC_STG_graph.
Referenced by create_control_flow_checker(), fsm_controller::create_state_machine(), and FSM_NI_SSA_liveness::InternalExec().
CGetEPPStg()
const StateTransitionGraphConstRef StateTransitionGraphManager::CGetEPPStg () const
Returns pointer to acyclic STG with additional edges for Efficient Path Profiling.
Definition at line 113 of file state_transition_graph_manager.cpp.
References EPP_STG_graph.
Referenced by BB_based_stg::compute_EPP_edge_increments(), and create_control_flow_checker().
CGetStg()
const StateTransitionGraphConstRef StateTransitionGraphManager::CGetStg () const
Returns pointer to state transition graph created.
Returns
reference to a graph that contains information about operations to be executed and control edges
Definition at line 108 of file state_transition_graph_manager.cpp.
References STG_graph.
Referenced by BB_based_stg::compute_EPP_edge_increments(), create_control_flow_checker(), fsm_controller::create_state_machine(), FSM_NI_SSA_liveness::InternalExec(), BB_based_stg::InternalExec(), ControlFlowChecker::InternalExec(), add_library::InternalExec(), BB_based_stg::optimize_cycles(), and BB_based_stg::res_const_operation().
compute_min_max()
void StateTransitionGraphManager::compute_min_max ()
compute the minimum and maximum number of cycles when possible
Definition at line 118 of file state_transition_graph_manager.cpp.
References ACYCLIC_STG_graph, max(), min, STG_graph, and THROW_ASSERT.
Referenced by BB_based_stg::InternalExec().
get_ending_states()
CustomOrderedSet< vertex > StateTransitionGraphManager::get_ending_states (const vertex & op) const
Definition at line 193 of file state_transition_graph_manager.cpp.
References get_states().
get_entry_state()
vertex StateTransitionGraphManager::get_entry_state () const
Gets vertex that represents state that contains entry node.
Returns
the vertex of state associated to entry node
Definition at line 151 of file state_transition_graph_manager.cpp.
References STG_graph.
Referenced by add_EPP_edges(), fsm_controller::create_state_machine(), FSM_NI_SSA_liveness::InternalExec(), and BB_based_stg::InternalExec().
get_execution_states()
CustomOrderedSet< vertex > StateTransitionGraphManager::get_execution_states (const vertex & op) const
Definition at line 203 of file state_transition_graph_manager.cpp.
References get_states().
get_exit_state()
vertex StateTransitionGraphManager::get_exit_state () const
Gets vertex that represents state that contains exit node.
Returns
the vertex of state associated to exit node
Definition at line 208 of file state_transition_graph_manager.cpp.
References STG_graph.
Referenced by add_EPP_edges(), fsm_controller::create_state_machine(), FSM_NI_SSA_liveness::InternalExec(), and BB_based_stg::InternalExec().
get_mu_ctrls()
const std::map<vertex, generic_objRef>& StateTransitionGraphManager::get_mu_ctrls () const [inline]
Definition at line 201 of file state_transition_graph_manager.hpp.
References add_to_SM(), and multi_unbounded_table.
Referenced by conn_binding::add_command_ports().
get_number_of_states()
unsigned int StateTransitionGraphManager::get_number_of_states () const
Returns
the number of states of the FSM
Definition at line 233 of file state_transition_graph_manager.cpp.
References state_transition_graphs_collection.
Referenced by AllocationInformation::EstimateControllerDelay(), and print_statistics().
get_starting_states()
CustomOrderedSet< vertex > StateTransitionGraphManager::get_starting_states (const vertex & op) const
Definition at line 198 of file state_transition_graph_manager.cpp.
References get_states().
get_state_name()
std::string StateTransitionGraphManager::get_state_name (vertex state) const
Get the name of a state.
Parameters
state is the state
Returns
the name of the state
Definition at line 213 of file state_transition_graph_manager.cpp.
References STG_graph.
Referenced by FSM_NI_SSA_liveness::InternalExec(), BB_based_stg::InternalExec(), and BB_based_stg::move_without_duplication().
get_states()
CustomOrderedSet< vertex > StateTransitionGraphManager::get_states (const vertex & op, StateTypes statetypes) const [private]
Definition at line 156 of file state_transition_graph_manager.cpp.
References ENDING, EXECUTING, GET_NAME, op_function_graph, STARTING, STG_graph, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by get_ending_states(), get_execution_states(), and get_starting_states().
GetAstg()
StateTransitionGraphRef StateTransitionGraphManager::GetAstg ()
Returns pointer to state transition graph created.
Returns
reference to a graph that contains information about operations to be executed and control edges
Definition at line 218 of file state_transition_graph_manager.cpp.
References ACYCLIC_STG_graph.
GetEPPStg()
StateTransitionGraphRef StateTransitionGraphManager::GetEPPStg ()
Returns pointer to acyclic STG with additional edges for Efficient Path Profiling.
Definition at line 228 of file state_transition_graph_manager.cpp.
References EPP_STG_graph.
Referenced by compute_edge_increments().
GetStg()
StateTransitionGraphRef StateTransitionGraphManager::GetStg ()
Returns pointer to state transition graph created.
Returns
reference to a graph that contains information about operations to be executed and control edges
Definition at line 223 of file state_transition_graph_manager.cpp.
References STG_graph.
Referenced by add_EPP_edges(), mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), mux_connection_binding::create_single_conn(), BB_based_stg::InternalExec(), BB_based_stg::move_with_duplication(), BB_based_stg::move_without_duplication(), BB_based_stg::optimize_cycles(), and BB_based_stg::res_const_operation().
print_statistics()
void StateTransitionGraphManager::print_statistics () const
Definition at line 238 of file state_transition_graph_manager.cpp.
References get_number_of_states(), INDENT_OUT_MEX, output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERY_PEDANTIC, STG_graph, and STR.
Referenced by BB_based_stg::InternalExec().
specialise_mu()
void StateTransitionGraphManager::specialise_mu (structural_objectRef & mu_mod, generic_objRef mu) const
Definition at line 257 of file state_transition_graph_manager.cpp.
References port_o::add_n_ports(), hls::debug_level, DEBUG_LEVEL_VERBOSE, structural_object::find_member(), structural_object::get_path(), HLS, INDENT_DBG_MEX, port_vector_o_K, and THROW_ASSERT.
Referenced by add_to_SM().
Field Documentation
ACYCLIC_STG_graph
const StateTransitionGraphRef StateTransitionGraphManager::ACYCLIC_STG_graph [private]
The acyclic version of the STG.
Definition at line 77 of file state_transition_graph_manager.hpp.
Referenced by CGetAstg(), compute_min_max(), and GetAstg().
debug_level
int StateTransitionGraphManager::debug_level [private]
debugging level
Definition at line 95 of file state_transition_graph_manager.hpp.
Referenced by add_to_SM().
EPP_STG_graph
const StateTransitionGraphRef StateTransitionGraphManager::EPP_STG_graph [private]
The acyclic version of stg with additional edges necessary for Efficient Path Profiling.
Definition at line 83 of file state_transition_graph_manager.hpp.
Referenced by CGetEPPStg(), and GetEPPStg().
HLS
hlsRef StateTransitionGraphManager::HLS [private]
HLS data-structure.
Definition at line 109 of file state_transition_graph_manager.hpp.
Referenced by add_to_SM(), and specialise_mu().
multi_unbounded_table
std::map<vertex, generic_objRef> StateTransitionGraphManager::multi_unbounded_table [private]
map between state and multi-unbounded controllers
Definition at line 112 of file state_transition_graph_manager.hpp.
Referenced by add_multi_unbounded_obj(), add_to_SM(), and get_mu_ctrls().
op_function_graph
const OpGraphConstRef StateTransitionGraphManager::op_function_graph [private]
reference to operation graph
Definition at line 86 of file state_transition_graph_manager.hpp.
Referenced by get_states().
output_level
int StateTransitionGraphManager::output_level [private]
verbosity level
Definition at line 92 of file state_transition_graph_manager.hpp.
Referenced by print_statistics().
Param
const ParameterConstRef StateTransitionGraphManager::Param [private]
class containing all the parameters
Definition at line 89 of file state_transition_graph_manager.hpp.
state_transition_graphs_collection
const StateTransitionGraphsCollectionRef StateTransitionGraphManager::state_transition_graphs_collection [private]
The bulk graph.
Definition at line 74 of file state_transition_graph_manager.hpp.
Referenced by get_number_of_states().
STG_builder
const StateTransitionGraph_constructorRef StateTransitionGraphManager::STG_builder
reference to the class for building the graph
Definition at line 116 of file state_transition_graph_manager.hpp.
Referenced by add_EPP_edges(), BB_based_stg::InternalExec(), BB_based_stg::move_with_duplication(), BB_based_stg::move_without_duplication(), BB_based_stg::optimize_cycles(), and StateTransitionGraphManager().
STG_graph
const StateTransitionGraphRef StateTransitionGraphManager::STG_graph [private]
The complete version of the STG.
Definition at line 80 of file state_transition_graph_manager.hpp.
Referenced by add_multi_unbounded_obj(), CGetStg(), compute_min_max(), get_entry_state(), get_exit_state(), get_state_name(), get_states(), GetStg(), and print_statistics().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/state_transition_graph_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/state_transition_graph_manager.cpp