verilog_writer Class Reference
STD include.
#include <verilog_writer.hpp>
Public Member Functions
std::string get_name () const override
Return the name of the language writer.
std::string get_extension () const override
Return the filename extension associated with the verilog_writer.
void write_comment (const std::string &comment_string) override
Print a comment.
std::string type_converter (structural_type_descriptorRef Type) override
Return a language based type string given a structural_type_descriptor.
std::string type_converter_size (const structural_objectRef &cir) override
Return a language based type string given a structural_type_descriptor for the range of the array.
std::string may_slice_string (const structural_objectRef &port)
return the slice in case of a port owned by a port vector
void write_library_declaration (const structural_objectRef &cir) override
Write the #include for each used library.
void write_module_declaration (const structural_objectRef &cir) override
Write the declaration of the module.
void write_module_internal_declaration (const structural_objectRef &cir) override
Write the declaration of internal objects of the module.
void write_port_declaration (const structural_objectRef &cir, bool last_port_to_analyze) override
Write the port declaration starting from a port object.
void write_component_declaration (const structural_objectRef &cir) override
Write the declaration of a component.
void write_signal_declaration (const structural_objectRef &cir) override
Write the declaration of a signal.
void write_module_definition_begin (const structural_objectRef &cir) override
Write the top constructor declaration.
void write_module_instance_begin (const structural_objectRef &cir, const std::string &component_name, bool write_parametrization) override
Write the initial part of the instance of a module.
void write_module_instance_end (const structural_objectRef &cir) override
Write the ending part of the instance of a module.
void write_port_binding (const structural_objectRef &port, const structural_objectRef &top, bool &first_port_analyzed) override
Write the binding of a port.
void write_vector_port_binding (const structural_objectRef &port, bool &first_port_analyzed) override
void write_module_definition_end (const structural_objectRef &cir) override
Write the end part in a module declaration.
void write_io_signal_post_fix (const structural_objectRef &port, const structural_objectRef &sig) override
Write some code managing primary ports to signals connections.
void write_module_parametrization (const structural_objectRef &cir) override
Module can be parameterized with respect different features.
void write_tail (const structural_objectRef &cir) override
Write the tail part of the file.
void write_state_declaration (const structural_objectRef &cir, const std::list< std::string > &list_of_states, const std::string &reset_port, const std::string &reset_state, bool one_hot) override
write the declaration of all the states of the finite state machine.
void write_present_state_update (const structural_objectRef cir, const std::string &reset_state, const std::string &reset_port, const std::string &clock_port, const std::string &reset_type, bool connect_present_next_state_signals) override
write the present_state update process
void write_transition_output_functions (bool single_proc, unsigned int output_index, const structural_objectRef &cir, const std::string &reset_state, const std::string &reset_port, const std::string &start_port, const std::string &clock_port, std::vector< std::string >::const_iterator &first, std::vector< std::string >::const_iterator &end) override
Write the transition and output functions.
void write_NP_functionalities (const structural_objectRef &cir) override
Write in the proper language the behavioral description of the module described in `Not Parsed` form.
void write_port_decl_header () override
Write the header for port_decl.
void write_port_decl_tail () override
Write the tail for port_decl.
void write_module_parametrization_decl (const structural_objectRef &cir) override
Write the declaration of the module parameters.
verilog_writer (const ParameterConstRef parameters)
Constructor.
~verilog_writer () override
Destructor.
void write_assign (const std::string &op0, const std::string &op1) override
bool has_output_prefix () const override
bool check_keyword (std::string id) const override
void write_timing_specification (const technology_managerConstRef TM, const structural_objectRef &cir) override
void write_header () override
Writes the header part of the file.
void WriteBuiltin (const structural_objectConstRef component) override
Write a builtin component.
Protected Attributes
CustomOrderedSet< std::string > keywords
Static Protected Attributes
static const char * tokenNames []
static const std::map< std::string, std::string > builtin_to_verilog_keyword
map putting into relation standard gates with the corresponding built-in Verilog statements.
Additional Inherited Members
Detailed Description
STD include.
STL include
Definition at line 58 of file verilog_writer.hpp.
Constructor & Destructor Documentation
verilog_writer()
verilog_writer::verilog_writer (const ParameterConstRef parameters) [explicit]
Constructor.
Definition at line 1640 of file verilog_writer.cpp.
References language_writer::debug_level, GET_CLASS, keywords, language_writer::parameters, tokenNames, and ~verilog_writer().
Referenced by get_extension().
 verilog_writer()
verilog_writer::~verilog_writer () [override], [default]
Destructor.
Referenced by get_extension(), and verilog_writer().
Member Function Documentation
check_keyword()
bool verilog_writer::check_keyword (std::string id) const [override], [virtual]
Implements language_writer.
Definition at line 1649 of file verilog_writer.cpp.
References keywords.
Referenced by has_output_prefix().
get_extension()
std::string verilog_writer::get_extension () const [inline], [override], [virtual]
Return the filename extension associated with the verilog_writer.
Implements language_writer.
Definition at line 78 of file verilog_writer.hpp.
References may_slice_string(), language_writer::parameters, top(), type_converter(), type_converter_size(), verilog_writer(), write_assign(), write_comment(), write_component_declaration(), write_io_signal_post_fix(), write_library_declaration(), write_module_declaration(), write_module_definition_begin(), write_module_definition_end(), write_module_instance_begin(), write_module_instance_end(), write_module_internal_declaration(), write_module_parametrization(), write_module_parametrization_decl(), write_NP_functionalities(), write_port_binding(), write_port_decl_header(), write_port_decl_tail(), write_port_declaration(), write_present_state_update(), write_signal_declaration(), write_state_declaration(), write_tail(), write_transition_output_functions(), write_vector_port_binding(), and ~verilog_writer().
get_name()
std::string verilog_writer::get_name () const [inline], [override], [virtual]
Return the name of the language writer.
Implements language_writer.
Definition at line 71 of file verilog_writer.hpp.
has_output_prefix()
bool verilog_writer::has_output_prefix () const [inline], [override], [virtual]
Implements language_writer.
Definition at line 254 of file verilog_writer.hpp.
References check_keyword(), write_header(), write_timing_specification(), and WriteBuiltin().
may_slice_string()
std::string verilog_writer::may_slice_string (const structural_objectRef & port)
return the slice in case of a port owned by a port vector
Parameters
port is the port
Returns
a string in case of a port owned by a port vector
Definition at line 326 of file verilog_writer.cpp.
References BITSIZE_PREFIX, structural_type_descriptor::BOOL, get_id(), structural_object::get_id(), structural_object::get_kind(), NP_functionality::get_NP_functionality(), structural_object::get_owner(), structural_object::get_typeRef(), structural_type_descriptor::INT, NUM_ELEM_PREFIX, structural_type_descriptor::OTHER, port_vector_o_K, structural_type_descriptor::print(), structural_type_descriptor::REAL, structural_type_descriptor::size, THROW_ERROR, structural_type_descriptor::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), and write_io_signal_post_fix().
type_converter()
std::string verilog_writer::type_converter (structural_type_descriptorRef Type) [override], [virtual]
Return a language based type string given a structural_type_descriptor.
In case of arrays the range of the array is print by the type_converter_size function.
Parameters
Type is the structural_type_descriptor.
Implements language_writer.
Definition at line 120 of file verilog_writer.cpp.
References structural_type_descriptor::BOOL, structural_type_descriptor::id_type, structural_type_descriptor::INT, structural_type_descriptor::OTHER, structural_type_descriptor::REAL, THROW_ERROR, structural_type_descriptor::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), write_port_declaration(), and write_signal_declaration().
type_converter_size()
std::string verilog_writer::type_converter_size (const structural_objectRef & cir) [override], [virtual]
Return a language based type string given a structural_type_descriptor for the range of the array.
In case of scalar type it return an empty string.
Parameters
cir is the object for which the size has been computed.
Implements language_writer.
Definition at line 177 of file verilog_writer.cpp.
References BITSIZE_PREFIX, structural_type_descriptor::BOOL, structural_object::get_id(), structural_object::get_kind(), NP_functionality::get_NP_functionality(), structural_object::get_owner(), GET_TYPE_SIZE, structural_object::get_typeRef(), structural_type_descriptor::id_type, structural_type_descriptor::INT, NUM_ELEM_PREFIX, structural_type_descriptor::OTHER, port_vector_o_K, PORTSIZE_PREFIX, structural_type_descriptor::print(), structural_type_descriptor::REAL, signal_vector_o_K, structural_type_descriptor::size, STR, THROW_ERROR, THROW_UNREACHABLE, structural_type_descriptor::type, structural_type_descriptor::UINT, structural_type_descriptor::UNKNOWN, structural_type_descriptor::USER, structural_type_descriptor::VECTOR_BOOL, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, structural_type_descriptor::VECTOR_UINT, and structural_type_descriptor::VECTOR_USER.
Referenced by get_extension(), write_port_binding(), write_port_declaration(), and write_signal_declaration().
write_assign()
void verilog_writer::write_assign (const std::string & op0, const std::string & op1) [override], [virtual]
Implements language_writer.
Definition at line 471 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_comment()
void verilog_writer::write_comment (const std::string & comment_string) [override], [virtual]
Print a comment.
Parameters
comment_string is the string to be printed as a comment.
Implements language_writer.
Definition at line 115 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by get_extension(), and write_timing_specification().
write_component_declaration()
void verilog_writer::write_component_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of a component.
Parameters
cir is the component to be declared.
Implements language_writer.
Definition at line 516 of file verilog_writer.cpp.
Referenced by get_extension().
write_header()
void verilog_writer::write_header () [override], [virtual]
Writes the header part of the file.
Write some lines of comments and possibly global libraries.
Reimplemented from language_writer.
Definition at line 1707 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by has_output_prefix().
write_io_signal_post_fix()
void verilog_writer::write_io_signal_post_fix (const structural_objectRef & port, const structural_objectRef & sig) [override], [virtual]
Write some code managing primary ports to signals connections.
Loop signals are present for example in this bench circuit: INPUT(X) OUTPUT(Z) Y = DFF(Z) Z = AND(X,Y). The circuit builder adds an internal signal Z_sign allowing the write and read of the Z values. In verilog, this problem has been solved in this way: ???;
Parameters
port is the primary port for which this problem happens.
sig is the attached signal.
Implements language_writer.
Definition at line 855 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), constant_o_K, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), GET_TYPE_SIZE, port_o::IN, language_writer::indented_output_stream, may_slice_string(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, STR, and THROW_ASSERT.
Referenced by get_extension().
write_library_declaration()
void verilog_writer::write_library_declaration (const structural_objectRef & cir) [override], [virtual]
Write the #include for each used library.
Parameters
cir is the component for which the library declarations are written.
Implements language_writer.
Definition at line 436 of file verilog_writer.cpp.
Referenced by get_extension().
write_module_declaration()
void verilog_writer::write_module_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of the module.
Parameters
cir is the module to be written.
write IO port declarations respecting the position
Implements language_writer.
Definition at line 440 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), GET_TYPE_NAME, IndentedOutputStream::Indent(), language_writer::indented_output_stream, register_AR_NORETIME, register_AR_NORETIME_INT, register_AR_NORETIME_REAL, register_AR_NORETIME_UINT, and THROW_ASSERT.
Referenced by get_extension().
write_module_definition_begin()
void verilog_writer::write_module_definition_begin (const structural_objectRef & cir) [override], [virtual]
Write the top constructor declaration.
Parameters
cir is the top component to be declared.
Implements language_writer.
Definition at line 537 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_module_definition_end()
void verilog_writer::write_module_definition_end (const structural_objectRef & cir) [override], [virtual]
Write the end part in a module declaration.
Parameters
cir is the top component to be declared.
Implements language_writer.
Definition at line 614 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_module_instance_begin()
void verilog_writer::write_module_instance_begin (const structural_objectRef & cir, const std::string & component_name, bool write_parametrization) [override], [virtual]
Write the initial part of the instance of a module.
Parameters
cir is the module to be instanced.
component_name is the name of the module to be instanced. It has to be specified since VHDL and verilog can print in different ways
write_parametrization specified if parameters have to be written
check possible module parametrization
Implements language_writer.
Definition at line 592 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), channel_o_K, component_o_K, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), language_writer::indented_output_stream, THROW_ASSERT, and write_module_parametrization().
Referenced by get_extension().
write_module_instance_end()
void verilog_writer::write_module_instance_end (const structural_objectRef & cir) [override], [virtual]
Write the ending part of the instance of a module.
Parameters
cir is the module to be instanced.
Implements language_writer.
Definition at line 609 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), and language_writer::indented_output_stream.
Referenced by get_extension().
write_module_internal_declaration()
void verilog_writer::write_module_internal_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of internal objects of the module.
Parameters
cir is the module to be written.
Implements language_writer.
Definition at line 467 of file verilog_writer.cpp.
Referenced by get_extension().
write_module_parametrization()
void verilog_writer::write_module_parametrization (const structural_objectRef & cir) [override], [virtual]
Module can be parameterized with respect different features.
Port vectors areparameterizedd with the number of port associated, while ports are parameterized in case the type is a integer with the number of bits. The id of the module is modified by adding the parameters at its end. For example an AND_GATE with a port_vector of 2 will be declared as: AND_GATE_2. Moreover, a multiplier with the first input of four bits, the second input with eight bits and an output of twelve bits will be declared as: MULT_4_8_12. Note that parametrization has a meaning only in case the functionality come from the STD technology library.
Parameters
cir is the component to be declared.
writing memory-related parameters
Implements language_writer.
Definition at line 888 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), BITSIZE_PREFIX, channel_o_K, component_o_K, language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_kind(), NP_functionality::get_NP_functionality(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), INDENT_DBG_MEX, language_writer::indented_output_stream, MEMORY_PARAMETER, NUM_ELEM_PREFIX, port_vector_o_K, PORTSIZE_PREFIX, structural_object::print(), structural_type_descriptor::size, THROW_ASSERT, THROW_ERROR, structural_type_descriptor::type, test_panda::type, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, and structural_type_descriptor::VECTOR_UINT.
Referenced by get_extension(), and write_module_instance_begin().
write_module_parametrization_decl()
void verilog_writer::write_module_parametrization_decl (const structural_objectRef & cir) [override], [virtual]
Write the declaration of the module parameters.
writing memory-related parameters
FIXME: this is workaround due to the fact that the default value of MEMORY_PARAMETER is ``
writing other library parameters
if at least one parameter is used, first_it is true.
Implements language_writer.
Definition at line 1537 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), BITSIZE_PREFIX, channel_o_K, component_o_K, language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_kind(), NP_functionality::get_NP_functionality(), GET_TYPE_SIZE, structural_object::get_typeRef(), INDENT_DBG_MEX, language_writer::indented_output_stream, MEMORY_PARAMETER, NUM_ELEM_PREFIX, port_vector_o_K, PORTSIZE_PREFIX, PRINT_DBG_MEX, structural_type_descriptor::size, THROW_ASSERT, structural_type_descriptor::type, test_panda::type, structural_type_descriptor::VECTOR_INT, structural_type_descriptor::VECTOR_REAL, structural_type_descriptor::vector_size, and structural_type_descriptor::VECTOR_UINT.
Referenced by get_extension().
write_NP_functionalities()
void verilog_writer::write_NP_functionalities (const structural_objectRef & cir) [override], [virtual]
Write in the proper language the behavioral description of the module described in `Not Parsed` form.
Parameters
cir is the component.
manage reset by preprocessing the behavioral description
Implements language_writer.
Definition at line 1494 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), NP_functionality::get_NP_functionality(), GET_TYPE_NAME, language_writer::indented_output_stream, language_writer::parameters, remove_escaped(), RESET_PORT_NAME, THROW_ASSERT, and NP_functionality::VERILOG_PROVIDED.
Referenced by get_extension().
write_port_binding()
void verilog_writer::write_port_binding (const structural_objectRef & port, const structural_objectRef & top, bool & first_port_analyzed) [override], [virtual]
Write the binding of a port.
It follows the name binding style.
Parameters
port is the port to be bounded.
top is the component owner of the component that has the port to be bounded.
Implements language_writer.
Definition at line 810 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), constant_o_K, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), structural_object::get_path(), GET_TYPE_SIZE, language_writer::indented_output_stream, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, STR, THROW_ASSERT, and type_converter_size().
Referenced by get_extension().
write_port_decl_header()
void verilog_writer::write_port_decl_header () [override], [virtual]
Write the header for port_decl.
do nothing
Implements language_writer.
Definition at line 1527 of file verilog_writer.cpp.
Referenced by get_extension().
write_port_decl_tail()
void verilog_writer::write_port_decl_tail () [override], [virtual]
Write the tail for port_decl.
do nothing
Implements language_writer.
Definition at line 1532 of file verilog_writer.cpp.
Referenced by get_extension().
write_port_declaration()
void verilog_writer::write_port_declaration (const structural_objectRef & cir, bool last_port_to_analyze) [override], [virtual]
Write the port declaration starting from a port object.
Parameters
cir is the port to be written.
Implements language_writer.
Definition at line 477 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), port_o::GEN, structural_object::get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, language_writer::indented_output_stream, port_o::IO, port_o::OUT, port_o_K, port_vector_o_K, THROW_ASSERT, THROW_ERROR, port_o::TLM_IN, port_o::TLM_INOUT, port_o::TLM_OUT, type_converter(), type_converter_size(), and port_o::UNKNOWN.
Referenced by get_extension().
write_present_state_update()
void verilog_writer::write_present_state_update (const structural_objectRef cir, const std::string & reset_state, const std::string & reset_port, const std::string & clock_port, const std::string & reset_type, bool connect_present_next_state_signals) [override], [virtual]
write the present_state update process
Parameters
reset_state is the reset state.
reset_port is the reset port.
clock_port is the clock port.
reset_type specify the type of the reset
reset is needed even in case of reset_type == `no`
Implements language_writer.
Definition at line 1104 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), NP_functionality::FSM_CS, module::get_NP_functionality(), IndentedOutputStream::Indent(), language_writer::indented_output_stream, NEXT_STATE_PORT_NAME, language_writer::parameters, PRESENT_STATE_PORT_NAME, SELECTOR_REGISTER_FILE, and STR.
Referenced by get_extension().
write_signal_declaration()
void verilog_writer::write_signal_declaration (const structural_objectRef & cir) [override], [virtual]
Write the declaration of a signal.
Parameters
cir is the signal to be declared.
Implements language_writer.
Definition at line 520 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), structural_type_descriptor::BOOL, HDL_manager::convert_to_identifier(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_typeRef(), language_writer::indented_output_stream, signal_o_K, signal_vector_o_K, structural_type_descriptor::size, THROW_ASSERT, structural_type_descriptor::type, type_converter(), type_converter_size(), and structural_type_descriptor::vector_size.
Referenced by get_extension().
write_state_declaration()
void verilog_writer::write_state_declaration (const structural_objectRef & cir, const std::list< std::string > & list_of_states, const std::string & reset_port, const std::string & reset_state, bool one_hot) [override], [virtual]
write the declaration of all the states of the finite state machine.
Parameters
list_of_states is the list of all the states.
adjust in case states are not consecutive
enable buffers
Implements language_writer.
Definition at line 1008 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), language_writer::bitnumber(), HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERBOSE, IndentedOutputStream::Deindent(), language_writer::encode_one_hot(), NP_functionality::FSM_CS, module::get_NP_functionality(), module::get_out_port(), module::get_out_port_size(), IndentedOutputStream::Indent(), language_writer::indented_output_stream, max(), NEXT_STATE_PORT_NAME, language_writer::parameters, PRESENT_STATE_PORT_NAME, PRINT_DBG_MEX, STATE_NAME_PREFIX, STR, and THROW_ASSERT.
Referenced by get_extension().
write_tail()
void verilog_writer::write_tail (const structural_objectRef & cir) [override], [virtual]
Write the tail part of the file.
Write some lines of comments and some debugging code.
Parameters
cir is the top component.
Implements language_writer.
Definition at line 1004 of file verilog_writer.cpp.
Referenced by get_extension().
write_timing_specification()
void verilog_writer::write_timing_specification (const technology_managerConstRef TM, const structural_objectRef & cir) [override], [virtual]
Reimplemented from language_writer.
Definition at line 1654 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), IndentedOutputStream::Deindent(), NP_functionality::exist_NP_functionality(), NP_functionality::FSM, NP_functionality::FSM_CS, module::get_in_port(), module::get_in_port_size(), module::get_internal_objects_size(), module::get_NP_functionality(), module::get_out_port(), module::get_out_port_size(), structural_object::get_typeRef(), structural_type_descriptor::id_type, IndentedOutputStream::Indent(), language_writer::indented_output_stream, STR, THROW_ASSERT, and write_comment().
Referenced by has_output_prefix().
write_transition_output_functions()
void verilog_writer::write_transition_output_functions (bool single_proc, unsigned int output_index, const structural_objectRef & cir, const std::string & reset_state, const std::string & reset_port, const std::string & start_port, const std::string & clock_port, std::vector< std::string >::const_iterator & first, std::vector< std::string >::const_iterator & end) [override], [virtual]
Write the transition and output functions.
Parameters
cir is the component.
reset_port is the reset port.
clock_port is the clock port.
first if the first iterator of the state table.
end if the end iterator of the state table.
n_states is the number of states.
state transitions description
compute the default output
get the present state
get the current output
check if we can skip this state
Implements language_writer.
Definition at line 1137 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, NP_functionality::exist_NP_functionality(), NP_functionality::FSM_CS, NP_functionality::get_NP_functionality(), INDENT_DBG_MEX, language_writer::indented_output_stream, NEXT_STATE_PORT_NAME, PRESENT_STATE_PORT_NAME, SELECTOR_REGISTER_FILE, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by get_extension().
write_vector_port_binding()
void verilog_writer::write_vector_port_binding (const structural_objectRef & port, bool & first_port_analyzed) [override], [virtual]
Implements language_writer.
Definition at line 620 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), constant_o_K, HDL_manager::convert_to_identifier(), language_writer::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), structural_object::get_path(), GET_TYPE_SIZE, INDENT_DBG_MEX, language_writer::indented_output_stream, index, max(), port_vector_o_K, signal_vector_o_K, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by get_extension().
WriteBuiltin()
void verilog_writer::WriteBuiltin (const structural_objectConstRef component) [override], [virtual]
Write a builtin component.
Parameters
component is the component to be printed
Implements language_writer.
Definition at line 542 of file verilog_writer.cpp.
References IndentedOutputStream::Append(), builtin_to_verilog_keyword, HDL_manager::convert_to_identifier(), GET_TYPE_NAME, language_writer::indented_output_stream, port_o_K, port_vector_o_K, STR, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by has_output_prefix().
Field Documentation
builtin_to_verilog_keyword
const std::map< std::string, std::string > verilog_writer::builtin_to_verilog_keyword [static], [protected]
Initial value:
= {
    {AND_GATE_STD, "and"}, {NAND_GATE_STD, "nand"}, {
      OR_GATE_STD, "or"}, {NOR_GATE_STD, "nor"}, {XOR_GATE_STD, "xor"}, {
      XNOR_GATE_STD, "xnor"}, {NOT_GATE_STD, "not"}, {
      DFF_GATE_STD, "dff"}, {BUFF_GATE_STD, "buf"},
}
map putting into relation standard gates with the corresponding built-in Verilog statements.
Definition at line 63 of file verilog_writer.hpp.
Referenced by WriteBuiltin().
keywords
CustomOrderedSet<std::string> verilog_writer::keywords [protected]
Definition at line 65 of file verilog_writer.hpp.
Referenced by check_keyword(), and verilog_writer().
tokenNames
const char * verilog_writer::tokenNames [static], [protected]
Initial value:
= {
    "abs", "abstol", "access", "acos", "acosh", "always", "analog", "and", "asin", "asinh", "assign", "atan
      ", "atan2", "atanh", "automatic", "begin", "bool", "buf", "bufif0", "bufif1", "case", "casex", "casez", "
      ceil", "cell", "cmos", "config",
    "continuous", "cos", "cosh", "ddt_nature", "deassign", "default", "defparam", "design", "disable", "
      discipline", "discrete", "domain", "edge", "else", "end", "endcase", "endconfig", "enddiscipline", "endfunction
      ", "endgenerate", "endmodule",
    "endnature", "endprimitive", "endspecify", "endtable", "endtask", "event", "exclude", "exp", "floor", "
      flow", "for", "force", "forever", "fork", "from", "function", "generate", "genvar", "ground", "highz0", "
      highz1", "hypot", "idt_nature", "if",
    "ifnone", "incdir", "include", "inf", "initial", "inout", "input", "instance", "integer", "join", "
      large", "liblist", "library", "ln", "localparam", "log", "macromodule", "max", "medium", "min", "module", "nand"
      , "nature", "negedge", "nmos", "nor",
    "noshowcancelled", "not", "notif0", "notif1", "or", "output", "parameter", "pmos", "posedge", "
      potential", "pow", "primitive", "pull0", "pull1", "pulldown", "pullup", "pulsestyle_onevent", "pulsestyle_ondetect",
       "rcmos", "real", "realtime", "reg",
    "release", "repeat", "rnmos", "rpmos", "rtran", "rtranif0", "rtranif1", "scalared", "showcancelled", "
      signed", "sin", "sinh", "small", "specify", "specparam", "sqrt", "strong0", "strong1", "supply0", "supply1",
      "table", "tan", "tanh", "task", "time",
    "tran", "tranif0", "tranif1", "tri", "tri0", "tri1", "triand", "trior", "trireg", "units", "unsigned",
      "use", "uwire", "vectored", "wait", "wand", "weak0", "weak1", "while", "wire", "wone", "wor", "xnor", "xor",
    
    "alias", "always_comb", "always_ff", "always_latch", "assert", "assume", "before", "bind", "bins", "
      binsof", "bit", "break", "byte", "chandle", "class", "clocking", "const", "constraint", "context", "continue",
      "cover", "covergroup", "coverpoint",
    "cross", "dist", "do", "endclass", "endgroup",
    "endsequence"
    "endclocking",
    "endpackage", "endinterface", "endprogram", "endproperty", "enum", "expect", "export", "extends", "
      extern", "final", "first_match", "foreach", "forkjoin", "iff", "ignore_bins", "illegal_bins", "import", "
      intersect", "inside", "interface", "int",
    "join_any", "join_none", "local", "logic", "longint", "matches", "modport", "new", "null", "package", "
      packed", "priority", "program", "property", "protected", "pure", "rand", "randc", "randcase", "randomize", "
      randsequence", "ref", "return",
    "sequence", "shortint", "shortreal", "solve", "static", "string", "struct", "super", "tagged", "this",
      "throughout", "timeprecision", "timeunit", "type", "typedef", "unique", "var", "virtual", "void", "
      wait_order", "wildcard", "with", "within",
    
    "accept_on", "checker", "endchecker", "eventually", "global", "implies", "let", "nexttime", "reject_on"
      , "restrict", "s_always", "s_eventually", "s_nexttime", "s_until", "s_until_with", "strong", "sync_accept_on
      ", "sync_reject_on", "unique0", "until",
    "until_with", "untyped", "weak",
    
    "implements", "interconnect", "nettype", "soft"}
Definition at line 61 of file verilog_writer.hpp.
Referenced by verilog_writer().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/writer/verilog_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/writer/verilog_writer.cpp