module_interface Class Reference
#include <module_interface.hpp>
Public Member Functions
module_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
~module_interface () override
Destructor.
Protected Member Functions
void add_sign (const structural_managerRef SM, const structural_objectRef sig1, const structural_objectRef sig2, const std::string &sig_name)
Connects two ports by adding a signal (i.e., wire)
void AddSignal (const structural_managerRef SM, const structural_objectRef component1, const std::string &port1, const structural_objectRef component2, const std::string &port2, const std::string &signal_name)
Connects two ports by adding a signal.
void AddConnection (const structural_managerRef SM, const structural_objectRef component1, const std::string &port1, const structural_objectRef component2, const std::string &port2)
Connects two ports by adding a signal.
void AddConstant (const structural_managerRef SM, const structural_objectRef component, const std::string &port, const std::string &constant, const unsigned int size)
Connects a constant to a port.
void add_sign_vector (const structural_managerRef SM, const structural_objectRef sig1, const structural_objectRef sig2, const std::string &sig_name)
Connects two ports by adding a vector signal (i.e., wire)
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 53 of file module_interface.hpp.
Constructor & Destructor Documentation
module_interface()
module_interface::module_interface (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
Constructor.
HLS/module_allocation includes.
STL includes utility include
Definition at line 77 of file module_interface.cpp.
References THROW_ASSERT, and ~module_interface().
 module_interface()
module_interface::~module_interface () [override], [default]
Destructor.
Referenced by module_interface().
Member Function Documentation
add_sign()
void module_interface::add_sign (const structural_managerRef SM, const structural_objectRef sig1, const structural_objectRef sig2, const std::string & sig_name) [protected]
Connects two ports by adding a signal (i.e., wire)
Definition at line 143 of file module_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), structural_manager::get_circ(), and structural_object::get_typeRef().
add_sign_vector()
void module_interface::add_sign_vector (const structural_managerRef SM, const structural_objectRef sig1, const structural_objectRef sig2, const std::string & sig_name) [protected]
Connects two ports by adding a vector signal (i.e., wire)
Definition at line 150 of file module_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_sign_vector(), structural_manager::get_circ(), structural_object::get_typeRef(), and THROW_ASSERT.
Referenced by TasteInterfaceGeneration::InternalExec().
AddConnection()
void module_interface::AddConnection (const structural_managerRef SM, const structural_objectRef component1, const std::string & port1, const structural_objectRef component2, const std::string & port2) [protected]
Connects two ports by adding a signal.
Parameters
SM is the circuit
component1 is the first component
port1 is the name of the first port
component2 is the second component
port2 is the name of the second port
Definition at line 216 of file module_interface.cpp.
References structural_manager::add_connection(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_object::get_id(), structural_object::get_path(), GET_TYPE_SIZE, INDENT_DBG_MEX, port_o_K, STR, and THROW_ASSERT.
Referenced by TasteInterfaceGeneration::InternalExec().
AddConstant()
void module_interface::AddConstant (const structural_managerRef SM, const structural_objectRef component, const std::string & port, const std::string & constant, const unsigned int size) [protected]
Connects a constant to a port.
Parameters
SM is the circuit
component is the component to which the port belongs
port_name is the name of the port
constant is the value of the constant
size is the size of the port
Definition at line 264 of file module_interface.cpp.
References structural_manager::add_connection(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), structural_object::get_id(), structural_object::get_path(), INDENT_DBG_MEX, max(), DesignFlowStep::parameters, port_o_K, and THROW_ASSERT.
Referenced by TasteInterfaceGeneration::InternalExec().
AddSignal()
void module_interface::AddSignal (const structural_managerRef SM, const structural_objectRef component1, const std::string & port1, const structural_objectRef component2, const std::string & port2, const std::string & signal_name) [protected]
Connects two ports by adding a signal.
Parameters
SM is the circuit
component1 is the first component
port1 is the name of the first port
component2 is the second component
port2 is the name of the second port
sig_name is the name of the signal to be added
Definition at line 158 of file module_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), structural_object::get_id(), structural_object::get_path(), GET_TYPE_SIZE, structural_object::get_typeRef(), INDENT_DBG_MEX, port_o_K, STR, and THROW_ASSERT.
Referenced by TasteInterfaceGeneration::InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > module_interface::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Reimplemented in TasteInterfaceGeneration.
Definition at line 85 of file module_interface.cpp.
References ADD_LIBRARY, DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::hls_flow_step_type, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, THROW_ASSERT, THROW_UNREACHABLE, TOP_ENTITY_CREATION, TOP_ENTITY_CS_CREATION, TOP_ENTITY_MEMORY_MAPPED_CREATION, and WB4_INTERFACE_GENERATION.
Referenced by TasteInterfaceGeneration::ComputeHLSRelationships().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/module_interface.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/module_interface.cpp