SynopsysWrapper Class Reference
superclass include
#include <SynopsysWrapper.hpp>
Public Types
enum wrapper_t { UNDEFINED = 0,
DESIGN_COMPILER
 }
implemented wrappers
Public Member Functions
SynopsysWrapper (const ParameterConstRef &Param, const std::string &tool_exec, const target_deviceRef &device, const std::string &output_dir, const std::string &default_output_dir)
Constructor.
~SynopsysWrapper () override
Destructor.
void generate_synthesis_script (const DesignParametersRef &dp, const std::string &file_name) override
Creates the proper configuration script.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the tool command line.
std::string toString (const xml_script_node_tRef node, const DesignParametersRef dp) const override
Returns the string-based representation of the XML element.
std::string getStringValue (const xml_script_node_tRef node, const DesignParametersRef &dp) const override
Returns the string-based representation of the XML element.
Static Public Member Functions
static SynthesisToolRef CreateWrapper (wrapper_t type, const ParameterConstRef &Param, const target_deviceRef &_device, const std::string &output_dir)
Factory method.
Additional Inherited Members
Detailed Description
superclass include
Definition at line 50 of file SynopsysWrapper.hpp.
Member Enumeration Documentation
wrapper_t
enum SynopsysWrapper::wrapper_t
implemented wrappers
Enumerator
UNDEFINED
DESIGN_COMPILER
Definition at line 54 of file SynopsysWrapper.hpp.
Constructor & Destructor Documentation
SynopsysWrapper()
SynopsysWrapper::SynopsysWrapper (const ParameterConstRef & Param, const std::string & tool_exec, const target_deviceRef & device, const std::string & output_dir, const std::string & default_output_dir)
Constructor.
Header include.
Parameters
Param is the set of parameters
tool_exec is the name of the executable
output_dir is the directory where to save all the results
default_output_dir is the default output directory
Definition at line 61 of file SynopsysWrapper.cpp.
References ~SynopsysWrapper().
 SynopsysWrapper()
SynopsysWrapper::~SynopsysWrapper () [override], [default]
Destructor.
Referenced by SynopsysWrapper().
Member Function Documentation
CreateWrapper()
SynthesisToolRef SynopsysWrapper::CreateWrapper (wrapper_t type, const ParameterConstRef & Param, const target_deviceRef & _device, const std::string & output_dir) [static]
Factory method.
this point should neven be reached
Definition at line 68 of file SynopsysWrapper.cpp.
References DESIGN_COMPILER, THROW_ERROR, and UNDEFINED.
generate_synthesis_script()
void SynopsysWrapper::generate_synthesis_script (const DesignParametersRef & dp, const std::string & file_name) [override], [virtual]
Creates the proper configuration script.
Implements SynthesisTool.
Definition at line 96 of file SynopsysWrapper.cpp.
References DesignParameters::assign(), SynthesisTool::generate_bare_script(), getStringValue(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, SynthesisTool::xml_reserved_vars, and SynthesisTool::xml_script_nodes.
get_command_line()
std::string SynopsysWrapper::get_command_line (const DesignParametersRef & dp) const [override], [virtual]
Returns the tool command line.
Implements SynthesisTool.
Definition at line 127 of file SynopsysWrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::script_name, toString(), and SynthesisTool::xml_tool_options.
getStringValue()
std::string SynopsysWrapper::getStringValue (const xml_script_node_tRef node, const DesignParametersRef & dp) const [override], [virtual]
Returns the string-based representation of the XML element.
this point should never be reached
Implements SynthesisTool.
Definition at line 141 of file SynopsysWrapper.cpp.
References xml_set_variable_t::multiValues, NODE_COMMAND, NODE_ENTRY, NODE_FOREACH, NODE_ITE_BLOCK, NODE_PARAMETER, NODE_SHELL, NODE_UNKNOWN, NODE_VARIABLE, result, xml_set_variable_t::singleValue, STR, THROW_ERROR, and toString().
Referenced by generate_synthesis_script(), and toString().
toString()
std::string SynopsysWrapper::toString (const xml_script_node_tRef node, const DesignParametersRef dp) const [override], [virtual]
Returns the string-based representation of the XML element.
this point should never be reached
Implements SynthesisTool.
Definition at line 187 of file SynopsysWrapper.cpp.
References xml_ite_block_t::condition, xml_parameter_t::curlyBrackets, xml_ite_block_t::elseNodes, xml_script_node_t::evaluate_condition(), getStringValue(), xml_parameter_t::multiValues, xml_set_variable_t::name, xml_parameter_t::name, xml_command_t::name, xml_shell_t::name, NODE_COMMAND, NODE_ENTRY, NODE_FOREACH, NODE_ITE_BLOCK, NODE_PARAMETER, NODE_SHELL, NODE_UNKNOWN, NODE_VARIABLE, xml_command_t::output, xml_shell_t::output, xml_command_t::parameters, xml_shell_t::parameters, result, xml_parameter_t::separator, sh, xml_parameter_t::singleValue, STR, xml_ite_block_t::thenNodes, THROW_ERROR, xml_set_entry_t::value, xml_command_t::value, and xml_shell_t::value.
Referenced by get_command_line(), and getStringValue().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/synopsys/SynopsysWrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/synopsys/SynopsysWrapper.cpp