FrontendFlowStepFactory Class Reference
#include <frontend_flow_step_factory.hpp>
Public Member Functions
FrontendFlowStepFactory (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~FrontendFlowStepFactory () override
Destructor.
const DesignFlowStepSet GenerateFrontendSteps (const CustomUnorderedSet< FrontendFlowStepType > &frontend_flow_step_types) const
Create the frontend design flow steps.
const DesignFlowStepRef GenerateFrontendStep (FrontendFlowStepType frontend_flow_step_type) const
Create the frontend design flow step.
const DesignFlowStepRef CreateApplicationFrontendFlowStep (const FrontendFlowStepType design_flow_step_type) const
Create an application frontend flow step.
const DesignFlowStepRef CreateFunctionFrontendFlowStep (const FrontendFlowStepType design_flow_step_type, const unsigned int function_id) const
Create a function frontend flow step.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
Protected Attributes
const application_managerRef AppM
The application manager.
Detailed Description
Definition at line 62 of file frontend_flow_step_factory.hpp.
Constructor & Destructor Documentation
FrontendFlowStepFactory()
FrontendFlowStepFactory::FrontendFlowStepFactory (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
_Param is the set of the parameters
Autoheader include Passes includes
Definition at line 322 of file frontend_flow_step_factory.cpp.
References ~FrontendFlowStepFactory().
 FrontendFlowStepFactory()
FrontendFlowStepFactory::~FrontendFlowStepFactory () [override], [default]
Destructor.
Referenced by FrontendFlowStepFactory().
Member Function Documentation
CreateApplicationFrontendFlowStep()
const DesignFlowStepRef FrontendFlowStepFactory::CreateApplicationFrontendFlowStep (const FrontendFlowStepType design_flow_step_type) const
Create an application frontend flow step.
Parameters
design_flow manager is the design flow manager
design_flow_step is the type of step to be created
parameters is the set of input parameters
Definition at line 625 of file frontend_flow_step_factory.cpp.
References ADD_BB_ECFG_EDGES, ADD_OP_EXIT_FLOW_EDGES, ADD_OP_LOOP_FLOW_EDGES, AGGREGATE_DATA_FLOW_ANALYSIS, AppM, BASIC_BLOCKS_CFG_COMPUTATION, BB_CONTROL_DEPENDENCE_COMPUTATION, BB_FEEDBACK_EDGES_IDENTIFICATION, BB_ORDER_COMPUTATION, BB_REACHABILITY_COMPUTATION, BLOCK_FIX, BUILD_VIRTUAL_PHI, CALL_EXPR_FIX, CHECK_SYSTEM_TYPE, CLEAN_VIRTUAL_PHI, COMPLETE_BB_GRAPH, COMPLETE_CALL_GRAPH, CREATE_TREE_MANAGER, DesignFlowStepFactory::design_flow_manager, DOM_POST_DOM_COMPUTATION, FrontendFlowStep::EnumToKindText(), FUNCTION_ANALYSIS, Wrefcount< T >::lock(), LOOP_COMPUTATION, LOOPS_COMPUTATION, MEM_CG_EXT, MEMORY_DATA_FLOW_ANALYSIS, OP_CONTROL_DEPENDENCE_COMPUTATION, OP_FEEDBACK_EDGES_IDENTIFICATION, OP_ORDER_COMPUTATION, OP_REACHABILITY_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStepFactory::parameters, PARM2SSA, SCALAR_SSA_DATA_FLOW_ANALYSIS, STRING_CST_FIX, SWITCH_FIX, SYMBOLIC_APPLICATION_FRONTEND_FLOW_STEP, THROW_UNREACHABLE, USE_COUNTING, VAR_ANALYSIS, VAR_DECL_FIX, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
Referenced by CTestbenchExecution::ComputeRelationships(), CBackend::ComputeRelationships(), and GenerateFrontendStep().
CreateFunctionFrontendFlowStep()
const DesignFlowStepRef FrontendFlowStepFactory::CreateFunctionFrontendFlowStep (const FrontendFlowStepType design_flow_step_type, const unsigned int function_id) const
Create a function frontend flow step.
Parameters
design_flow_step is the type of step to be created
function_id is the index of the function
Definition at line 971 of file frontend_flow_step_factory.cpp.
References ADD_BB_ECFG_EDGES, ADD_OP_EXIT_FLOW_EDGES, ADD_OP_LOOP_FLOW_EDGES, AGGREGATE_DATA_FLOW_ANALYSIS, AppM, BASIC_BLOCKS_CFG_COMPUTATION, BB_CONTROL_DEPENDENCE_COMPUTATION, BB_FEEDBACK_EDGES_IDENTIFICATION, BB_ORDER_COMPUTATION, BB_REACHABILITY_COMPUTATION, BLOCK_FIX, BUILD_VIRTUAL_PHI, CALL_EXPR_FIX, CHECK_SYSTEM_TYPE, CLEAN_VIRTUAL_PHI, COMPLETE_BB_GRAPH, COMPLETE_CALL_GRAPH, CREATE_TREE_MANAGER, DesignFlowStepFactory::design_flow_manager, DOM_POST_DOM_COMPUTATION, FrontendFlowStep::EnumToKindText(), FUNCTION_ANALYSIS, Wrefcount< T >::lock(), LOOP_COMPUTATION, LOOPS_COMPUTATION, MEM_CG_EXT, MEMORY_DATA_FLOW_ANALYSIS, OP_CONTROL_DEPENDENCE_COMPUTATION, OP_FEEDBACK_EDGES_IDENTIFICATION, OP_ORDER_COMPUTATION, OP_REACHABILITY_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStepFactory::parameters, PARM2SSA, SCALAR_SSA_DATA_FLOW_ANALYSIS, STRING_CST_FIX, SWITCH_FIX, SYMBOLIC_APPLICATION_FRONTEND_FLOW_STEP, THROW_UNREACHABLE, USE_COUNTING, VAR_ANALYSIS, VAR_DECL_FIX, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
Referenced by BambuFrontendFlow::ComputeRelationships().
GenerateFrontendStep()
const DesignFlowStepRef FrontendFlowStepFactory::GenerateFrontendStep (FrontendFlowStepType frontend_flow_step_type) const
Create the frontend design flow step.
Parameters
frontend_flow_step_type is the frontend flow to be considered
Definition at line 339 of file frontend_flow_step_factory.cpp.
References ADD_BB_ECFG_EDGES, ADD_OP_EXIT_FLOW_EDGES, ADD_OP_LOOP_FLOW_EDGES, AGGREGATE_DATA_FLOW_ANALYSIS, AppM, BASIC_BLOCKS_CFG_COMPUTATION, BB_CONTROL_DEPENDENCE_COMPUTATION, BB_FEEDBACK_EDGES_IDENTIFICATION, BB_ORDER_COMPUTATION, BB_REACHABILITY_COMPUTATION, BLOCK_FIX, BUILD_VIRTUAL_PHI, CALL_EXPR_FIX, CHECK_SYSTEM_TYPE, CLEAN_VIRTUAL_PHI, COMPLETE_BB_GRAPH, COMPLETE_CALL_GRAPH, CREATE_TREE_MANAGER, CreateApplicationFrontendFlowStep(), DesignFlowStepFactory::design_flow_manager, DOM_POST_DOM_COMPUTATION, FUNCTION_ANALYSIS, Wrefcount< T >::lock(), LOOP_COMPUTATION, LOOPS_COMPUTATION, MEM_CG_EXT, MEMORY_DATA_FLOW_ANALYSIS, OP_CONTROL_DEPENDENCE_COMPUTATION, OP_FEEDBACK_EDGES_IDENTIFICATION, OP_ORDER_COMPUTATION, OP_REACHABILITY_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStepFactory::parameters, PARM2SSA, SCALAR_SSA_DATA_FLOW_ANALYSIS, STRING_CST_FIX, SWITCH_FIX, SYMBOLIC_APPLICATION_FRONTEND_FLOW_STEP, THROW_UNREACHABLE, USE_COUNTING, VAR_ANALYSIS, VAR_DECL_FIX, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
Referenced by GenerateFrontendSteps().
GenerateFrontendSteps()
const DesignFlowStepSet FrontendFlowStepFactory::GenerateFrontendSteps (const CustomUnorderedSet< FrontendFlowStepType > & frontend_flow_step_types) const
Create the frontend design flow steps.
Parameters
frontend_flow_step_types is the set of frontend flow transformation to be considered
Definition at line 328 of file frontend_flow_step_factory.cpp.
References GenerateFrontendStep().
GetPrefix()
const std::string FrontendFlowStepFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 1584 of file frontend_flow_step_factory.cpp.
Field Documentation
AppM
const application_managerRef FrontendFlowStepFactory::AppM [protected]
The application manager.
Definition at line 66 of file frontend_flow_step_factory.hpp.
Referenced by CreateApplicationFrontendFlowStep(), CreateFunctionFrontendFlowStep(), and GenerateFrontendStep().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/frontend_flow_step_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/frontend_flow_step_factory.cpp