identifier_node Struct Reference
struct definition of the function_decl tree node.
#include <tree_node.hpp>
Public Types
enum { GETID =(tree_node) = 0
 }
visitor enum
Public Member Functions
identifier_node (unsigned int node_id, std::string _strg, tree_manager *TM)
constructors
identifier_node (unsigned int node_id, bool _operator_flag, tree_manager *TM)
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
const bool operator_flag
Store true if the identifier_node is an operator.
std::string strg
Store the identifier string associated with the identifier_node.
Additional Inherited Members
Detailed Description
struct definition of the function_decl tree node.
The tree walker structure of this node is: #(TOK_IDENTIFIER_NODE ((strg lngt) | TOK_OPERATOR));
Definition at line 3162 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 3187 of file tree_node.hpp.
Constructor & Destructor Documentation
identifier_node() [1/2]
identifier_node::identifier_node (unsigned int node_id, std::string _strg, tree_manager * TM)
constructors
Referenced by handler::visit().
identifier_node() [2/2]
identifier_node::identifier_node (unsigned int node_id, bool _operator_flag, tree_manager * TM)
Definition at line 841 of file tree_node.cpp.
Member Function Documentation
visit()
void identifier_node::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from tree_node.
Definition at line 846 of file tree_node.cpp.
References ALL_VISIT, and VISIT_SC.
Referenced by integer_cst::visit(), integer_type::visit(), gimple_label::visit(), method_type::visit(), namespace_decl::visit(), and overload::visit().
Field Documentation
operator_flag
const bool identifier_node::operator_flag
Store true if the identifier_node is an operator.
Definition at line 3169 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
strg
std::string identifier_node::strg
Store the identifier string associated with the identifier_node.
Definition at line 3172 of file tree_node.hpp.
Referenced by record_type::get_maybe_name(), GimpleWriter::GimpleWriter(), constant_flop_wrapper::InternalExec(), tree_helper::name_type(), and raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp