/home/osboxes/bambu/PandA-bambu/src/parser/treegcc/parse_tree.cpp File Reference
Implementation of the tree parsing interface function.
#include `parse_tree.hpp`
#include `Parameter.hpp`
#include <fstream>
#include <iostream>
#include <string>
#include `tree_manager.hpp`
#include `refcount.hpp`
Functions
tree_managerRef ParseTreeFile (const ParameterConstRef &Param, const std::string &f)
Function that parse the dump of the patched GCC.
Variables
int exit_code
Header include.
Detailed Description
Implementation of the tree parsing interface function.
Implementation of the function that parse a tree from a file.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$
Warning
This file is still in a work in progress state
Last modified by $Author$
Function Documentation
ParseTreeFile()
tree_managerRef ParseTreeFile (const ParameterConstRef & Param, const std::string & f)
Function that parse the dump of the patched GCC.
Parameters
Param is the set of input parameters
f the input file name
debug_level is the the debug_level
Returns
the tree manager associated to the raw file.
Definition at line 67 of file parse_tree.cpp.
References exit_code, and THROW_ERROR_CODE.
Referenced by create_tree_manager::Exec(), GccWrapper::FillTreeManager(), and main().
Variable Documentation
exit_code
int exit_code
Header include.
Parameter include STD include tree include Utility include
Header include.
utility include
STD include Exit code
Definition at line 51 of file global_variables.cpp.
Referenced by ParseTreeFile().