cdfc_module_binding Class Reference
Class managing the module allocation.
#include <cdfc_module_binding.hpp>
Public Member Functions
cdfc_module_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
This is the constructor of the class.
~cdfc_module_binding () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Protected Member Functions
bool false_loop_search (cdfc_vertex start, unsigned k, const cdfc_graphConstRef &cdfc, const cdfc_graphConstRef &cg, std::deque< cdfc_edge > &candidate_edges)
bool false_loop_search_cdfc_1 (cdfc_vertex src, unsigned int level, unsigned k, cdfc_vertex start, const cdfc_graphConstRef &cdfc, const cdfc_graphConstRef &cg, std::deque< cdfc_edge > &candidate_edges, std::vector< bool > &visited, std::vector< bool > &cg_visited, std::vector< bool > &cdfc_visited)
bool false_loop_search_cdfc_more (cdfc_vertex src, unsigned int level, unsigned k, cdfc_vertex start, const cdfc_graphConstRef &cdfc, const cdfc_graphConstRef &cg, std::deque< cdfc_edge > &candidate_edges, std::vector< bool > &visited, std::vector< bool > &cg_visited, std::vector< bool > &cdfc_visited)
bool can_be_clustered (vertex v, OpGraphConstRef fdfg, const fu_bindingConstRef fu, const CustomUnorderedMap< vertex, double > &slack_time, const double mux_time)
int weight_computation (bool cond1, bool cond2, vertex v1, vertex v2, const double mux_time, const OpGraphConstRef fdfg, const fu_bindingConstRef fu, const CustomUnorderedMap< vertex, double > &slack_time, CustomUnorderedMap< vertex, double > &starting_time, connection_relation &con_rel, double controller_delay, unsigned int prec)
void update_slack_starting_time (const OpGraphConstRef sdg, OpVertexSet &sorted_vertices, CustomUnorderedMap< vertex, double > &slack_time, CustomUnorderedMap< vertex, double > &starting_time, bool update_starting_time, bool only_backward, bool only_forward)
void initialize_connection_relation (connection_relation &con_rel, OpVertexSet &all_candidate_vertices)
Protected Attributes
const double small_normalized_resource_area
Threshold used in sharing of functional units.
CustomUnorderedMap< vertex, bool > can_be_clustered_table
record if a vertex has to be clustered or not
CustomUnorderedMapUnstable< std::pair< vertex, unsigned int >, bool > is_complex
Static Protected Attributes
static const int CD_EDGE = 1
static const int COMPATIBILITY_EDGE = 2
Additional Inherited Members
Detailed Description
Class managing the module allocation.
Definition at line 366 of file cdfc_module_binding.hpp.
Constructor & Destructor Documentation
cdfc_module_binding()
cdfc_module_binding::cdfc_module_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
This is the constructor of the class.
Definition at line 721 of file cdfc_module_binding.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and ~cdfc_module_binding().
 cdfc_module_binding()
cdfc_module_binding::~cdfc_module_binding () [override], [default]
Destructor.
Referenced by cdfc_module_binding().
Member Function Documentation
can_be_clustered()
bool cdfc_module_binding::can_be_clustered (vertex v, OpGraphConstRef fdfg, const fu_bindingConstRef fu, const CustomUnorderedMap< vertex, double > & slack_time, const double mux_time) [protected]
Definition at line 2053 of file cdfc_module_binding.cpp.
References hls::allocation_information, can_be_clustered_table, OpGraph::CGetOpNodeInfo(), AllocationInformation::compute_normalized_area(), hls::functionId, AllocationInformation::get_correction_time(), GET_TYPE, AllocationInformation::get_worst_execution_time(), HLSFunctionStep::HLS, SCALAR, TYPE_ENTRY, TYPE_EXIT, TYPE_EXTERNAL, TYPE_GOTO, TYPE_IF, TYPE_LABEL, TYPE_MULTIIF, TYPE_PHI, TYPE_RET, TYPE_SWITCH, TYPE_VPHI, and USE.
Referenced by InternalExec(), and weight_computation().
false_loop_search()
bool cdfc_module_binding::false_loop_search (cdfc_vertex start, unsigned k, const cdfc_graphConstRef & cdfc, const cdfc_graphConstRef & cg, std::deque< cdfc_edge > & candidate_edges) [protected]
Definition at line 1970 of file cdfc_module_binding.cpp.
References false_loop_search_cdfc_1().
Referenced by InternalExec().
false_loop_search_cdfc_1()
bool cdfc_module_binding::false_loop_search_cdfc_1 (cdfc_vertex src, unsigned int level, unsigned k, cdfc_vertex start, const cdfc_graphConstRef & cdfc, const cdfc_graphConstRef & cg, std::deque< cdfc_edge > & candidate_edges, std::vector< bool > & visited, std::vector< bool > & cg_visited, std::vector< bool > & cdfc_visited) [protected]
Definition at line 1991 of file cdfc_module_binding.cpp.
References false_loop_search_cdfc_more().
Referenced by false_loop_search(), and false_loop_search_cdfc_more().
false_loop_search_cdfc_more()
bool cdfc_module_binding::false_loop_search_cdfc_more (cdfc_vertex src, unsigned int level, unsigned k, cdfc_vertex start, const cdfc_graphConstRef & cdfc, const cdfc_graphConstRef & cg, std::deque< cdfc_edge > & candidate_edges, std::vector< bool > & visited, std::vector< bool > & cg_visited, std::vector< bool > & cdfc_visited) [protected]
Definition at line 2017 of file cdfc_module_binding.cpp.
References COMPATIBILITY_EDGE, and false_loop_search_cdfc_1().
Referenced by false_loop_search_cdfc_1().
initialize_connection_relation()
void cdfc_module_binding::initialize_connection_relation (connection_relation & con_rel, OpVertexSet & all_candidate_vertices) [protected]
Definition at line 255 of file cdfc_module_binding.cpp.
References FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), tree_manager::CGetTreeNode(), DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FDFG, GET_NAME, GET_TYPE, INDENT_DBG_MEX, tree_helper::is_parameter(), no_def, no_phi_chained, no_phi_no_chained, NULL_VERTEX, phi, STR, THROW_ASSERT, THROW_UNREACHABLE, and TYPE_PHI.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status cdfc_module_binding::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
compute non-shared resources
check easy binding and compute the list of vertices for which a sharing is possible
in case no vertices was left we have done
check for PHIs attached to the ouput. They may require one or more muxes.
rank property map definition
parent property map definition
merge easy bound vertices
add the vertices to the cdfc graph
add the control dependencies edges and the chained edges to the cdfc graph
only the chained operations are relevant
pipelined operations break false loops
add compatibility edge with computed weight on both the directions
compute levels
topologically sort vertex of CD_EDGE based graph
remove all cycles from the cdfc graph
remove the loop
remove both the compatibility edges
search another loop
partition vertices for clique covering or bind the easy functional units
check easy binding
solve the binding problem for all the partitions
build the clique covering solver
add vertex to the clique covering solver
add the edges
only one edge is needed to build the undirected compatibility graph
Specify the minimum number of resources in case we have to use all the memory ports. That is relevant for memories attached to the bus Private memories should use the minimum number of ports to minimize the total area.
performing clique covering
only one edge is needed to build the undirected compatibility graph
Specify the minimum number of resources in case we have to use all the memory ports. That is relevant for memories attached to the bus Private memories should use the minimum number of ports to minimize the total area.
retrieve the solution
compute maximum starting time
storing new binding results
Implements HLSFunctionStep.
Definition at line 832 of file cdfc_module_binding.cpp.
References abs(), hls::allocation_information, liveness::are_in_conflict(), fu_binding::bind(), BIPARTITE_MATCHING, can_be_clustered(), CD_EDGE, FunctionBehavior::CGetBehavioralHelper(), OpGraph::CGetOperations(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), hls::chaining_information, CLOCK_MARGIN, COMPATIBILITY_EDGE, compute_condition1(), compute_condition2(), AllocationInformation::compute_normalized_area(), fu_binding::create_fu_binding(), clique_covering< VertexType >::create_solver(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStep::design_flow_manager, FunctionBehavior::DFG, DFG_SCA_SELECTOR, AllocationInformation::estimate_mux_area(), AllocationInformation::estimate_mux_time(), AllocationInformation::EstimateControllerDelay(), false_loop_search(), FunctionBehavior::FDFG, from_strongtype_cast(), FunctionBehavior::FSDG, hls::functionId, HLSFunctionStep::funId, AllocationInformation::get_area(), fu_binding::get_assign(), Schedule::get_cstep(), Schedule::get_cstep_end(), AllocationInformation::get_cycles(), AllocationInformation::get_DSPs(), Schedule::get_fo_correction(), AllocationInformation::get_fu_name(), BehavioralHelper::get_function_name(), fu_binding::get_index(), AllocationInformation::get_initiation_time(), AllocationInformation::get_memory_var(), GET_NAME, AllocationInformation::get_number_channels(), AllocationInformation::get_number_fu(), AllocationInformation::get_prec(), AllocationInformation::get_proxy_memory_var(), ChainingInformation::get_representative_in(), AllocationInformation::get_setup_hold_time(), liveness::get_state_where_run(), AllocationInformation::get_string_name(), tree_manager::get_tree_node_const(), GET_TYPE, Schedule::GetEndingTime(), graph::GetSelector(), Schedule::GetStartingTime(), HLSFunctionStep::HLS, hls::HLS_C, HLS_step::hls_flow_step_specialization, hls::HLS_T, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, index, INFINITE_UINT, initialize_connection_relation(), AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_memory_unit(), AllocationInformation::is_one_cycle_direct_access_memory_unit(), AllocationInformation::is_proxy_unit(), AllocationInformation::is_readonly_memory_unit(), AllocationInformation::is_vertex_bounded(), Wrefcount< T >::lock(), max(), ChainingInformation::may_be_chained_ops(), min, MODULE_BINDING_MUX_MARGIN, NULL_VERTEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERBOSE, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, print_cpu_time(), PRINT_DBG_MEX, PROXY_LIBRARY, test_panda::restart, hls::Rfu, hls::Rliv, hls::Rsch, FunctionBehavior::SDG, small_normalized_resource_area, START_TIME, STOP_TIME, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, topological_based_sorting(), graph::TopologicalSort(), tree_node::ToString(), TS_WEIGHTED_CLIQUE_COVERING, TYPE_ENTRY, TYPE_EXIT, TYPE_GOTO, TYPE_LABEL, TYPE_PHI, TYPE_RET, TYPE_SWITCH, TYPE_VPHI, update_slack_starting_time(), weight_computation(), WEIGHTED_CLIQUE_REGISTER_BINDING, and WORK_LIBRARY.
update_slack_starting_time()
void cdfc_module_binding::update_slack_starting_time (const OpGraphConstRef sdg, OpVertexSet & sorted_vertices, CustomUnorderedMap< vertex, double > & slack_time, CustomUnorderedMap< vertex, double > & starting_time, bool update_starting_time, bool only_backward, bool only_forward) [protected]
Definition at line 731 of file cdfc_module_binding.cpp.
References OpGraph::CGetInEdges(), OpGraph::CGetOutEdges(), hls::chaining_information, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DFG_SCA_SELECTOR, GET_NAME, ChainingInformation::get_representative_in(), graph::GetSelector(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, ChainingInformation::may_be_chained_ops(), NULL_VERTEX, and STR.
Referenced by InternalExec().
weight_computation()
int cdfc_module_binding::weight_computation (bool cond1, bool cond2, vertex v1, vertex v2, const double mux_time, const OpGraphConstRef fdfg, const fu_bindingConstRef fu, const CustomUnorderedMap< vertex, double > & slack_time, CustomUnorderedMap< vertex, double > & starting_time, connection_relation & con_rel, double controller_delay, unsigned int prec) [protected]
Definition at line 2133 of file cdfc_module_binding.cpp.
References can_be_clustered(), OpGraph::CGetOpNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NAME, HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, max(), and STR.
Referenced by InternalExec().
Field Documentation
can_be_clustered_table
CustomUnorderedMap<vertex, bool> cdfc_module_binding::can_be_clustered_table [protected]
record if a vertex has to be clustered or not
Definition at line 394 of file cdfc_module_binding.hpp.
Referenced by can_be_clustered().
CD_EDGE
const int cdfc_module_binding::CD_EDGE = 1 [static], [protected]
Definition at line 390 of file cdfc_module_binding.hpp.
Referenced by InternalExec().
COMPATIBILITY_EDGE
const int cdfc_module_binding::COMPATIBILITY_EDGE = 2 [static], [protected]
Definition at line 391 of file cdfc_module_binding.hpp.
Referenced by false_loop_search_cdfc_more(), and InternalExec().
is_complex
CustomUnorderedMapUnstable<std::pair<vertex, unsigned int>, bool> cdfc_module_binding::is_complex [protected]
Definition at line 395 of file cdfc_module_binding.hpp.
small_normalized_resource_area
const double cdfc_module_binding::small_normalized_resource_area [protected]
Threshold used in sharing of functional units.
Definition at line 370 of file cdfc_module_binding.hpp.
Referenced by compute_condition2(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/cdfc_module_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/cdfc_module_binding.cpp