use_counting Class Reference
Update ssa_name with information about how many times it is used.
#include <use_counting.hpp>
Public Member Functions
use_counting (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~use_counting () override
Destructor.
DesignFlowStep_Status InternalExec () override
Counts how many time a ssa_name is read.
Private Member Functions
void analyze_node (tree_nodeRef &tn, CustomOrderedSet< tree_nodeRef > &ssa_uses)
Update counters with information concerning tree_node tn.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Attributes
std::map< unsigned int, unsigned int > counter
Counters.
Additional Inherited Members
Detailed Description
Update ssa_name with information about how many times it is used.
Definition at line 69 of file use_counting.hpp.
Constructor & Destructor Documentation
use_counting()
use_counting::use_counting (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
Header include Behavior include design_flow_manager includes design_flows/technology includes Parameter include HLS includes STL includes tree include
Definition at line 79 of file use_counting.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~use_counting().
 use_counting()
use_counting::~use_counting () [override], [default]
Destructor.
Referenced by use_counting().
Member Function Documentation
analyze_node()
void use_counting::analyze_node (tree_nodeRef & tn, CustomOrderedSet< tree_nodeRef > & ssa_uses) [private]
Update counters with information concerning tree_node tn.
Parameters
tn is the tree_node to be analyzed
ssa_uses is the vector containing the ssa_nodes `used` by the tree_node tn
var decl performs an assignment when init is not null
step and offset are constants
step and offset are constants
Definition at line 199 of file use_counting.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, counter, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, THROW_ASSERT, THROW_UNREACHABLE, and tree_node::ToString().
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > use_counting::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
We can check if single_write_memory is true only after technology was loaded
Implements FrontendFlowStep.
Definition at line 87 of file use_counting.cpp.
References FrontendFlowStep::AppM, CLEAN_VIRTUAL_PHI, TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, EMPTY, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SWITCH_FIX, and THROW_UNREACHABLE.
ComputeRelationships()
void use_counting::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [private], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 128 of file use_counting.cpp.
References FunctionFrontendFlowStep::ComputeRelationships(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status use_counting::InternalExec () [override], [virtual]
Counts how many time a ssa_name is read.
Returns
the exit status of this step
[breadshe] This set contains the ssa_name nodes `used` by the statement
[breadshe] Add current statement to the use_stmts corresponding to the ssa_name nodes contained in ssa_uses
Implements FunctionFrontendFlowStep.
Definition at line 159 of file use_counting.cpp.
References analyze_node(), FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), sl, and SUCCESS.
Field Documentation
counter
std::map<unsigned int, unsigned int> use_counting::counter [private]
Counters.
Definition at line 73 of file use_counting.hpp.
Referenced by analyze_node().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/use_counting.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/use_counting.cpp