IcarusWrapper Class Reference
Main class for wrapping the Icarus verilog compiler.
#include <IcarusWrapper.hpp>
Public Member Functions
IcarusWrapper (const ParameterConstRef &Param, std::string suffix)
Constructor.
~IcarusWrapper () override
Destructor.
void CheckExecution () override
Checks if the current specification can be executed or not.
Private Member Functions
void GenerateScript (std::ostringstream &script, const std::string &top_filename, const std::list< std::string > &file_list) override
Generates the proper simulation script.
Private Attributes
std::string suffix
suffix added to the SIM dir
Additional Inherited Members
Detailed Description
Main class for wrapping the Icarus verilog compiler.
Definition at line 59 of file IcarusWrapper.hpp.
Constructor & Destructor Documentation
IcarusWrapper()
IcarusWrapper::IcarusWrapper (const ParameterConstRef & Param, std::string suffix)
Constructor.
Parameters
Param is the set of parameters
Definition at line 86 of file IcarusWrapper.cpp.
References SimulationTool::debug_level, DEBUG_LEVEL_VERBOSE, PRINT_DBG_MEX, SIM_SUBDIR, suffix, and ~IcarusWrapper().
 IcarusWrapper()
IcarusWrapper::~IcarusWrapper () [override], [default]
Destructor.
Referenced by IcarusWrapper().
Member Function Documentation
CheckExecution()
void IcarusWrapper::CheckExecution () [override], [virtual]
Checks if the current specification can be executed or not.
Reimplemented from SimulationTool.
Definition at line 95 of file IcarusWrapper.cpp.
References THROW_ERROR.
GenerateScript()
void IcarusWrapper::GenerateScript (std::ostringstream & script, const std::string & top_filename, const std::list< std::string > & file_list) [override], [private], [virtual]
Generates the proper simulation script.
Implements SimulationTool.
Definition at line 102 of file IcarusWrapper.cpp.
References test_panda::command, CopyStdout(), SimulationTool::debug_level, DEBUG_LEVEL_VERBOSE, IVERILOG, IVL, SimulationTool::log_file, SimulationTool::output_level, OUTPUT_LEVEL_VERBOSE, PandaSystem(), SimulationTool::Param, PRINT_DBG_MEX, PRINT_OUT_MEX, SIM_SUBDIR, SplitString(), STR_CST_file_IO_shell_output_file, suffix, THROW_ERROR, and VVP.
Field Documentation
suffix
std::string IcarusWrapper::suffix [private]
suffix added to the SIM dir
Definition at line 62 of file IcarusWrapper.hpp.
Referenced by GenerateScript(), and IcarusWrapper().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/icarus/IcarusWrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/simulation/icarus/IcarusWrapper.cpp