channel_o Class Reference
This class describes a generic channel.
#include <structural_objects.hpp>
Public Member Functions
channel_o (int debug_level, const structural_objectRef o)
Constructor.
~channel_o () override=default
Destructor.
void add_interface (unsigned int t, const std::string &_interface)
Add an interface to the object.
const std::string & get_interface (unsigned int t) const
Return the interface with a given treenode.
void add_port (structural_objectRef p)
Bind the connection object with a port.
const structural_objectRef get_port (unsigned int n) const
Return the ith port bounded to the connection.
unsigned int get_connected_objects_size () const
Return the number of ports associated with the connection.
void copy (structural_objectRef dest) const override
Perform a copy of the channel.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the channel (for debug purpose)
Private Attributes
std::map< unsigned int, std::string > impl_interfaces
List of the interfaces associated with the channel.
std::vector< structural_objectRef > connected_objects
List of ports bounded by the channel object.
Additional Inherited Members
Detailed Description
This class describes a generic channel.
Definition at line 2344 of file structural_objects.hpp.
Constructor & Destructor Documentation
channel_o()
channel_o::channel_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the channel.
Definition at line 4033 of file structural_objects.cpp.
 channel_o()
channel_o::~channel_o () [override], [default]
Destructor.
Member Function Documentation
add_interface()
void channel_o::add_interface (unsigned int t, const std::string & _interface)
Add an interface to the object.
Definition at line 4037 of file structural_objects.cpp.
References impl_interfaces.
Referenced by structural_manager::add_constant(), and copy().
add_port()
void channel_o::add_port (structural_objectRef p)
Bind the connection object with a port.
Parameters
p is the port
Definition at line 4047 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
copy()
void channel_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the channel.
Parameters
dest destination object.
someone has to take care of connected_objects
Reimplemented from module.
Definition at line 4095 of file structural_objects.cpp.
References add_interface(), module::copy(), and impl_interfaces.
find_isomorphic()
structural_objectRef channel_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
to be completed
Please pay attention to this: connected_objects are not built in this moment!
object at the same level
search key in the owner
search the owner of the key and then the key
Reimplemented from module.
Definition at line 4106 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, structural_object::find_isomorphic(), module::find_isomorphic(), structural_object::get_id(), structural_object::get_owner(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, and THROW_ERROR.
find_member()
structural_objectRef channel_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Reimplemented from module.
Definition at line 4065 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, connected_objects, constant_o_K, data_o_K, event_o_K, module::find_member(), port_o_K, port_vector_o_K, signal_o_K, and signal_vector_o_K.
get_connected_objects_size()
unsigned int channel_o::get_connected_objects_size () const
Return the number of ports associated with the connection.
Definition at line 4060 of file structural_objects.cpp.
References connected_objects.
get_interface()
const std::string & channel_o::get_interface (unsigned int t) const
Return the interface with a given treenode.
Parameters
n is the treenode of the interface
Definition at line 4042 of file structural_objects.cpp.
References impl_interfaces.
get_port()
const structural_objectRef channel_o::get_port (unsigned int n) const
Return the ith port bounded to the connection.
Parameters
n is the index of the port.
Definition at line 4054 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
print()
void channel_o::print (std::ostream & os) const [override], [virtual]
Print the channel (for debug purpose)
Parameters
os is an output stream
Reimplemented from module.
Definition at line 4189 of file structural_objects.cpp.
References connected_objects, structural_object::convert_so_short(), impl_interfaces, structural_object::PP, and module::print().
xload()
void channel_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
Implements module.
Definition at line 4145 of file structural_objects.cpp.
References xml_child::get_children(), impl_interfaces, and module::xload().
xwrite()
void channel_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Implements module.
Definition at line 4167 of file structural_objects.cpp.
References xml_child::add_child_element(), connected_objects, structural_object::get_kind_text(), impl_interfaces, WRITE_XNVM2, and module::xwrite().
Field Documentation
connected_objects
std::vector<structural_objectRef> channel_o::connected_objects [private]
List of ports bounded by the channel object.
Definition at line 2350 of file structural_objects.hpp.
Referenced by add_port(), find_member(), get_connected_objects_size(), get_port(), print(), and xwrite().
impl_interfaces
std::map<unsigned int, std::string> channel_o::impl_interfaces [private]
List of the interfaces associated with the channel.
Definition at line 2347 of file structural_objects.hpp.
Referenced by add_interface(), copy(), get_interface(), print(), xload(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp