storage_value_insertion Class Reference
#include <storage_value_insertion.hpp>
Public Member Functions
storage_value_insertion (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
~storage_value_insertion () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Additional Inherited Members
Detailed Description
Definition at line 54 of file storage_value_insertion.hpp.
Constructor & Destructor Documentation
storage_value_insertion()
storage_value_insertion::storage_value_insertion (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the type of storage value insertion algorithm
. include HLS includes HLS/binding/storage_value_insertion include
Definition at line 59 of file storage_value_insertion.cpp.
References ~storage_value_insertion().
 storage_value_insertion()
storage_value_insertion::~storage_value_insertion () [override], [default]
Destructor.
Referenced by storage_value_insertion().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > storage_value_insertion::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 66 of file storage_value_insertion.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::HLSMgr, INITIALIZE_HLS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void storage_value_insertion::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Reimplemented in values_scheme.
Definition at line 94 of file storage_value_insertion.cpp.
References HLSFunctionStep::HLS, HLSFunctionStep::Initialize(), StorageValueInformation::Initialize(), and hls::storage_value_information.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/storage_value_insertion/storage_value_insertion.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/storage_value_insertion/storage_value_insertion.cpp