HLS_manager Class Reference
#include <hls_manager.hpp>
Public Types
typedef std::tuple< unsigned int, unsigned int > io_binding_type
tuple set used to represent the required values or the constant default value associated with the inputs of a node
Public Member Functions
HLS_manager (const ParameterConstRef Param, const HLS_targetRef HLS_T)
Constructor.
~HLS_manager () override
Destructor.
hlsRef get_HLS (unsigned int funId) const
Returns the HLS datastructure associated with a specific function.
HLS_targetRef get_HLS_target () const
Returns the datastructure associated with the HLS target.
const BackendFlowRef get_backend_flow ()
Returns the backend flow.
std::string get_constant_string (unsigned int node, unsigned int precision)
Return the specified constant in string format.
void xwrite (const std::string &filename)
Writes the current HLS project into an XML file.
std::vector< io_binding_type > get_required_values (unsigned int fun_id, const vertex &v) const
Returns the values required by a vertex.
bool is_register_compatible (unsigned int var) const
helper function that return true in case the variable is register compatible
bool is_reading_writing_function (unsigned funID) const
is_reading_writing_function
CustomOrderedSet< hlsRef > GetAllImplementations () const
Returns all the implementations resulting from the synthesis.
bool IsSingleWriteMemory () const
Return if single write memory is exploited.
unsigned int GetMemVersion () const
Return the version of the memory intermediate representation.
unsigned int UpdateMemVersion ()
Update the version of the memory intermediate representation.
Static Public Member Functions
static hlsRef create_HLS (const HLS_managerRef HLSMgr, unsigned int functionId)
Creates the HLS flow starting from the given specification.
Data Fields
unsigned int base_address
base address for memory space addressing
long HLS_execution_time
HLS execution time.
functionsRef Rfuns
information about function allocation
memoryRef Rmem
information about memory allocation
SimulationInformationRef RSim
information about the simulation
CustomMap< std::string, std::vector< double > > evaluations
Evaluations.
std::list< std::string > aux_files
The auxiliary files.
std::list< std::string > hdl_files
The HDL files.
std::map< std::string, std::map< std::string, std::string > > design_interface
store the design interface directives coming from an xml file: function_name->parameter_name->interface_type
std::map< std::string, std::map< std::string, std::string > > design_interface_arraysize
store the design interface array size coming from an xml file: function_name->parameter_name->interface_arraysize
std::map< std::string, std::map< std::string, std::string > > design_interface_typename
store the design interface typenames coming from an xml file: function_name->parameter_name->interface_typename
std::map< std::string, std::vector< std::string > > design_interface_typename_signature
store the design interface signature coming from an xml file: function_name->typename_signature
std::map< std::string, std::map< std::string, std::string > > design_interface_typenameinclude
store the design interface typename includes coming from an xml file: function_name->parameter_name->interface_typenameinclude
std::map< std::string, std::map< unsigned, std::map< std::string, std::list< unsigned > > > > design_interface_loads
store the design interface read references of parameters: function_name->bb_index->parameter_name->list_of_loads
std::map< std::string, std::map< unsigned, std::map< std::string, std::list< unsigned > > > > design_interface_stores
store the design interface write references of parameters: function_name->bb_index->parameter_name->list_of_stores
std::map< unsigned, std::map< std::string, std::map< std::string, unsigned int > > > design_interface_constraints
store the constraints on resources added to manage the I/O interfaces: function_id->library_name->resource_function_name->number of resources
std::map< std::pair< std::string, std::string >, unsigned > global_resource_constraints
global resource constraints
Private Attributes
HLS_targetRef HLS_T
information about the target device/technology for the synthesis
std::map< unsigned int, hlsRef > hlsMap
map between the function id and the corresponding HLS datastructure
BackendFlowRef back_flow
reference to the datastructure implementing the backend flow
unsigned int memory_version
The version of memory representation on which this step was applied.
Additional Inherited Members
Detailed Description
Definition at line 64 of file hls_manager.hpp.
Member Typedef Documentation
io_binding_type
typedef std::tuple<unsigned int, unsigned int> HLS_manager::io_binding_type
tuple set used to represent the required values or the constant default value associated with the inputs of a node
Definition at line 68 of file hls_manager.hpp.
Constructor & Destructor Documentation
HLS_manager()
HLS_manager::HLS_manager (const ParameterConstRef _Param, const HLS_targetRef _HLS_T)
Constructor.
Header include.
. include behavior include
Definition at line 81 of file hls_manager.cpp.
References functions, application_manager::Param, Rfuns, and ~HLS_manager().
 HLS_manager()
HLS_manager::~HLS_manager () [override], [default]
Destructor.
Referenced by HLS_manager().
Member Function Documentation
create_HLS()
hlsRef HLS_manager::create_HLS (const HLS_managerRef HLSMgr, unsigned int functionId) [static]
Creates the HLS flow starting from the given specification.
creates the new HLS data structure associated with the function
Definition at line 116 of file hls_manager.cpp.
References FunctionBehavior::CFG, INFINITE_UINT, tree_helper::name_function(), and THROW_ASSERT.
Referenced by InitializeHLS::InternalExec().
get_backend_flow()
const BackendFlowRef HLS_manager::get_backend_flow ()
Returns the backend flow.
Definition at line 217 of file hls_manager.cpp.
References back_flow, BackendFlow::CreateFlow(), HLS_T, and application_manager::Param.
get_constant_string()
std::string HLS_manager::get_constant_string (unsigned int node, unsigned int precision)
Return the specified constant in string format.
Definition at line 146 of file hls_manager.cpp.
References convert_fp_to_string(), convert_to_binary(), get_constant_string(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), tree_helper::is_a_complex(), tree_helper::is_a_vector(), tree_helper::is_real(), tree_helper::size(), THROW_ASSERT, and application_manager::TM.
Referenced by get_constant_string().
get_HLS()
hlsRef HLS_manager::get_HLS (unsigned int funId) const
Returns the HLS datastructure associated with a specific function.
Definition at line 102 of file hls_manager.cpp.
References hlsMap.
get_HLS_target()
HLS_targetRef HLS_manager::get_HLS_target () const
Returns the datastructure associated with the HLS target.
Definition at line 111 of file hls_manager.cpp.
References HLS_T.
Referenced by IsSingleWriteMemory().
get_required_values()
std::vector< HLS_manager::io_binding_type > HLS_manager::get_required_values (unsigned int fun_id, const vertex & v) const
Returns the values required by a vertex.
Definition at line 256 of file hls_manager.cpp.
References FunctionBehavior::CFG, application_manager::CGetFunctionBehavior(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), ENTRY_ID, EXIT_ID, tree_helper::get_required_values(), tree_manager::get_tree_node_const(), and application_manager::TM.
GetAllImplementations()
CustomOrderedSet<hlsRef> HLS_manager::GetAllImplementations () const
Returns all the implementations resulting from the synthesis.
GetMemVersion()
unsigned int HLS_manager::GetMemVersion () const
Return the version of the memory intermediate representation.
Returns
bb_version
Definition at line 288 of file hls_manager.cpp.
References memory_version.
is_reading_writing_function()
bool HLS_manager::is_reading_writing_function (unsigned funID) const
is_reading_writing_function
Parameters
funID is the function identifier
Returns
true in case the function performs at least a load or a store
Definition at line 273 of file hls_manager.cpp.
References tree_manager::get_tree_node_const(), THROW_ASSERT, and application_manager::TM.
is_register_compatible()
bool HLS_manager::is_register_compatible (unsigned int var) const
helper function that return true in case the variable is register compatible
Parameters
var is the variable
Returns
true in case var is register compatible
Definition at line 266 of file hls_manager.cpp.
References memory::has_base_address(), tree_helper::is_parameter(), tree_helper::is_ssa_name(), tree_helper::is_virtual(), Rmem, and application_manager::TM.
IsSingleWriteMemory()
bool HLS_manager::IsSingleWriteMemory () const
Return if single write memory is exploited.
Definition at line 281 of file hls_manager.cpp.
References get_HLS_target(), target_device::get_parameter(), target_manager::get_target_device(), target_device::has_parameter(), and application_manager::Param.
UpdateMemVersion()
unsigned int HLS_manager::UpdateMemVersion ()
Update the version of the memory intermediate representation.
Returns
the new version
Definition at line 293 of file hls_manager.cpp.
References memory_version.
xwrite()
void HLS_manager::xwrite (const std::string & filename)
Writes the current HLS project into an XML file.
Definition at line 224 of file hls_manager.cpp.
References application_manager::call_graph_manager, application_manager::CGetFunctionBehavior(), xml_document::create_root_node(), FunctionBehavior::FDFG, hlsMap, Rmem, xml_document::write_to_file_formatted(), hls::xwrite(), and memory::xwrite().
Field Documentation
aux_files
std::list<std::string> HLS_manager::aux_files
The auxiliary files.
Definition at line 103 of file hls_manager.hpp.
back_flow
BackendFlowRef HLS_manager::back_flow [private]
reference to the datastructure implementing the backend flow
Definition at line 78 of file hls_manager.hpp.
Referenced by get_backend_flow().
base_address
unsigned int HLS_manager::base_address
base address for memory space addressing
Definition at line 85 of file hls_manager.hpp.
design_interface
std::map<std::string, std::map<std::string, std::string> > HLS_manager::design_interface
store the design interface directives coming from an xml file: function_name->parameter_name->interface_type
Definition at line 114 of file hls_manager.hpp.
design_interface_arraysize
std::map<std::string, std::map<std::string, std::string> > HLS_manager::design_interface_arraysize
store the design interface array size coming from an xml file: function_name->parameter_name->interface_arraysize
Definition at line 116 of file hls_manager.hpp.
design_interface_constraints
std::map<unsigned, std::map<std::string, std::map<std::string, unsigned int> > > HLS_manager::design_interface_constraints
store the constraints on resources added to manage the I/O interfaces: function_id->library_name->resource_function_name->number of resources
Definition at line 129 of file hls_manager.hpp.
design_interface_loads
std::map<std::string, std::map<unsigned, std::map<std::string, std::list<unsigned> > > > HLS_manager::design_interface_loads
store the design interface read references of parameters: function_name->bb_index->parameter_name->list_of_loads
Definition at line 124 of file hls_manager.hpp.
design_interface_stores
std::map<std::string, std::map<unsigned, std::map<std::string, std::list<unsigned> > > > HLS_manager::design_interface_stores
store the design interface write references of parameters: function_name->bb_index->parameter_name->list_of_stores
Definition at line 126 of file hls_manager.hpp.
design_interface_typename
std::map<std::string, std::map<std::string, std::string> > HLS_manager::design_interface_typename
store the design interface typenames coming from an xml file: function_name->parameter_name->interface_typename
Definition at line 118 of file hls_manager.hpp.
design_interface_typename_signature
std::map<std::string, std::vector<std::string> > HLS_manager::design_interface_typename_signature
store the design interface signature coming from an xml file: function_name->typename_signature
Definition at line 120 of file hls_manager.hpp.
design_interface_typenameinclude
std::map<std::string, std::map<std::string, std::string> > HLS_manager::design_interface_typenameinclude
store the design interface typename includes coming from an xml file: function_name->parameter_name->interface_typenameinclude
Definition at line 122 of file hls_manager.hpp.
evaluations
CustomMap<std::string, std::vector<double> > HLS_manager::evaluations
Evaluations.
Definition at line 100 of file hls_manager.hpp.
global_resource_constraints
std::map<std::pair<std::string, std::string>, unsigned> HLS_manager::global_resource_constraints
global resource constraints
Definition at line 132 of file hls_manager.hpp.
hdl_files
std::list<std::string> HLS_manager::hdl_files
The HDL files.
Definition at line 106 of file hls_manager.hpp.
HLS_execution_time
long HLS_manager::HLS_execution_time
HLS execution time.
Definition at line 88 of file hls_manager.hpp.
HLS_T
HLS_targetRef HLS_manager::HLS_T [private]
information about the target device/technology for the synthesis
Definition at line 72 of file hls_manager.hpp.
Referenced by get_backend_flow(), and get_HLS_target().
hlsMap
std::map<unsigned int, hlsRef> HLS_manager::hlsMap [private]
map between the function id and the corresponding HLS datastructure
Definition at line 75 of file hls_manager.hpp.
Referenced by get_HLS(), and xwrite().
memory_version
unsigned int HLS_manager::memory_version [private]
The version of memory representation on which this step was applied.
Definition at line 81 of file hls_manager.hpp.
Referenced by GetMemVersion(), and UpdateMemVersion().
Rfuns
functionsRef HLS_manager::Rfuns
information about function allocation
Definition at line 91 of file hls_manager.hpp.
Referenced by HLS_manager().
Rmem
memoryRef HLS_manager::Rmem
information about memory allocation
Definition at line 94 of file hls_manager.hpp.
Referenced by is_register_compatible(), and xwrite().
RSim
SimulationInformationRef HLS_manager::RSim
information about the simulation
Definition at line 97 of file hls_manager.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_manager.cpp