GccWrapper Class Reference
Main class for wrapping the GCC compiler.
#include <gcc_wrapper.hpp>
Data Structures
class Compiler
Class storing information of a compiler.
Public Member Functions
GccWrapper (const ParameterConstRef Param, const GccWrapper_CompilerTarget compiler, const GccWrapper_OptimizationSet OS)
Constructor.
~GccWrapper ()
Destructor.
void FillTreeManager (const tree_managerRef TM, std::map< std::string, std::string > &input_files)
This function fills the tree manager with the nodes created from a set of source files.
void GetSystemIncludes (std::vector< std::string > &includes) const
Return the list of gcc system include.
void GetGccConfig () const
Dump the gcc configuration.
void QueryGccConfig (const std::string &gcc_option) const
Function that print of stdout some useful information passing the given option.
void CreateExecutable (const std::list< std::string > &file_names, const std::string &executable_name, const std::string &extra_gcc_options) const
Create an executable starting from source code.
void CreateExecutable (const CustomSet< std::string > &file_names, const std::string &executable_name, const std::string &extra_gcc_options) const
Create an executable starting from source code.
void ReadXml (const std::string &file_name)
Read gcc configuration from file.
void WriteXml (const std::string &file_name) const
Write gcc configuration on file.
Static Public Member Functions
static size_t GetSourceCodeLines (const ParameterConstRef Param)
Return the total number of lines of the benchmark.
static std::string WriteOptimizationLevel (const GccWrapper_OptimizationSet optimiation_level)
Writes the optimization level as a string.
static void CheckGccCompatibleVersion (const std::string &gcc_version, const std::string &plugin_version)
Check if the combination gcc-plugin is supported; if not it throws error.
static size_t CGetPointerSize (const ParameterConstRef parameters)
Return the size of the pointer in bit.
Static Public Attributes
static std::string current_gcc_version
The version of the gcc.
static std::string current_plugin_version
The version of the plugin.
Private Member Functions
void CompileFile (const std::string &original_file_name, std::string &real_file_name, const std::string &parameters_line, GccWrapper_CompilerMode cm=GccWrapper_CompilerMode::CM_STD)
Invoke gcc to compile file(s)
Compiler GetCompiler () const
Return the compiler for a given target.
void InitializeGccParameters ()
Initialize the gcc parameters line.
std::string WriteOptimizationsString ()
Write the string containing gcc optimization options.
const std::string AddSourceCodeIncludes (const std::list< std::string > &source_files) const
Add includes of source file directories.
std::string clang_recipes (const GccWrapper_OptimizationSet optimization_level, const GccWrapper_CompilerTarget compiler_target, const std::string &expandMemOps_plugin_obj, const std::string &expandMemOps_plugin_name, const std::string &GepiCanon_plugin_obj, const std::string &GepiCanon_plugin_name, const std::string &CSROA_plugin_obj, const std::string &CSROA_plugin_name, const std::string &fname)
Static Private Member Functions
static size_t ConvertVersion (const std::string &version)
Convert a string version to a number.
Private Attributes
const ParameterConstRef Param
The set of input parameters.
const GccWrapper_CompilerTarget compiler_target
The target compiler to be used.
const GccWrapper_OptimizationSet OS
The set of optimizations to be applied.
std::string gcc_compiling_parameters
The gcc parameters line for compiling a file.
std::string gcc_linking_parameters
The gcc parameters line for creating an executable.
CustomSet< std::string > already_processed_files
The set of files for which tree manager has already been computed.
int output_level
debug level
int debug_level
debug level
std::map< std::string, int > parameter_values
The values of optimizations parameters.
std::map< std::string, bool > optimization_flags
The set of activated optimizations.
std::map< std::string, int > optimization_values
The value of parametric activate optimizations.
Detailed Description
Main class for wrapping the GCC compiler.
It allows an XML configuration file to be specified where the parameters and the related values are stored.
Definition at line 180 of file gcc_wrapper.hpp.
Constructor & Destructor Documentation
GccWrapper()
GccWrapper::GccWrapper (const ParameterConstRef Param, const GccWrapper_CompilerTarget compiler, const GccWrapper_OptimizationSet OS)
Constructor.
Parameters
Param is the set of parameters
compiler is the compiler to be used
OS is the optimization set
Definition at line 267 of file gcc_wrapper.cpp.
References InitializeGccParameters(), Param, WriteXml(), and ~GccWrapper().
 GccWrapper()
GccWrapper::~GccWrapper () [default]
Destructor.
Referenced by GccWrapper().
Member Function Documentation
AddSourceCodeIncludes()
const std::string GccWrapper::AddSourceCodeIncludes (const std::list< std::string > & source_files) const [private]
Add includes of source file directories.
Parameters
source_files are the source files to be considered
Returns
the string to be passed to gcc
Adding includes of original source code files
Definition at line 2735 of file gcc_wrapper.cpp.
References gcc_compiling_parameters.
Referenced by CompileFile(), and CreateExecutable().
CGetPointerSize()
size_t GccWrapper::CGetPointerSize (const ParameterConstRef parameters) [static]
Return the size of the pointer in bit.
Parameters
parameters is the set of input parameters
Returns
the size of pointers in bit
Definition at line 3130 of file gcc_wrapper.cpp.
References THROW_ERROR.
Referenced by Bit_Value::pointer_resizing().
CheckGccCompatibleVersion()
void GccWrapper::CheckGccCompatibleVersion (const std::string & gcc_version, const std::string & plugin_version) [static]
Check if the combination gcc-plugin is supported; if not it throws error.
Parameters
gcc_version is the gcc version in form x.x.x
plugin_version is the plugin version in form x.x
Definition at line 3108 of file gcc_wrapper.cpp.
References ConvertVersion(), current_gcc_version, current_plugin_version, STR_CST_gcc_first_not_supported, STR_CST_gcc_max_plugin_version, STR_CST_gcc_min_plugin_version, STR_CST_gcc_supported_versions, THROW_ERROR, and THROW_WARNING.
clang_recipes()
std::string GccWrapper::clang_recipes (const GccWrapper_OptimizationSet optimization_level, const GccWrapper_CompilerTarget compiler_target, const std::string & expandMemOps_plugin_obj, const std::string & expandMemOps_plugin_name, const std::string & GepiCanon_plugin_obj, const std::string & GepiCanon_plugin_name, const std::string & CSROA_plugin_obj, const std::string & CSROA_plugin_name, const std::string & fname) [private]
Definition at line 2765 of file gcc_wrapper.cpp.
References O0, O2, O3, Param, STR, THROW_ERROR, and WriteOptimizationLevel().
Referenced by FillTreeManager().
CompileFile()
void GccWrapper::CompileFile (const std::string & original_file_name, std::string & real_file_name, const std::string & parameters_line, GccWrapper_CompilerMode cm = GccWrapper_CompilerMode::CM_STD) [private]
Invoke gcc to compile file(s)
Parameters
original_file_name is the original file passed through command line; this information is necessary to retrieve include directory
real_rile_name stores the source code file which is actually compiled; the function can modified it in case of empty file
parameters_line are the parameters to be passed to gcc
empty_file tells if .001.tu tree has to be produced
enable Analyzer plugin.
The gcc output
needed to avoid problem with glibc inlines
needed to avoid problem with iostream
Adding source code includes
remove some extra option not compatible with clang
manage optimization level
assembler files are not allowed so in some cases we pass a C file renamed with extension .S
Definition at line 280 of file gcc_wrapper.cpp.
References AddSourceCodeIncludes(), CM_ANALYZER, CM_EMPTY, CM_LTO, CM_STD, test_panda::command, COMPILING_EC, CopyFile(), CopyStdout(), debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, dump_exec_time(), GetBaseName(), GetCompiler(), GetExtension(), INDENT_DBG_MEX, IsError(), output_level, OUTPUT_LEVEL_NONE, OUTPUT_LEVEL_VERBOSE, PandaSystem(), Param, PRINT_OUT_MEX, START_TIME, STOP_TIME, STR, STR_CST_gcc_obj_file, STR_CST_gcc_output, STR_CST_panda_sizeof, STR_CST_string_sizeof, THROW_ERROR, and THROW_ERROR_CODE.
Referenced by FillTreeManager().
ConvertVersion()
size_t GccWrapper::ConvertVersion (const std::string & version) [static], [private]
Convert a string version to a number.
Parameters
version is the version to be converted
Returns
the corresponding number
Definition at line 2752 of file gcc_wrapper.cpp.
References index, and SplitString().
Referenced by CheckGccCompatibleVersion().
CreateExecutable() [1/2]
void GccWrapper::CreateExecutable (const std::list< std::string > & file_names, const std::string & executable_name, const std::string & extra_gcc_options) const
Create an executable starting from source code.
Parameters
file_names is the list of string; it must be a list since in some cases the order matters
executable_name is the name of the executable
extra_gcc_options is extra options to be used only for this compilation
needed to avoid problem with glibc inlines
Definition at line 2320 of file gcc_wrapper.cpp.
References AddSourceCodeIncludes(), test_panda::command, COMPILING_EC, CopyStdout(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GccWrapper::Compiler::extra_options, GccWrapper::Compiler::gcc, gcc_compiling_parameters, gcc_linking_parameters, GetCompiler(), INDENT_DBG_MEX, IsError(), optimization_flags, output_level, OUTPUT_LEVEL_VERBOSE, PandaSystem(), Param, parameter_values, test_panda::parameters, STR_CST_gcc_output, THROW_ASSERT, THROW_ERROR, and THROW_ERROR_CODE.
Referenced by CreateExecutable().
CreateExecutable() [2/2]
void GccWrapper::CreateExecutable (const CustomSet< std::string > & file_names, const std::string & executable_name, const std::string & extra_gcc_options) const
Create an executable starting from source code.
Parameters
file_names is the set of filename
executable_name is the name of the executable
extra_gcc_options is extra options to be used only for this compilation
Definition at line 2313 of file gcc_wrapper.cpp.
References CreateExecutable().
FillTreeManager()
void GccWrapper::FillTreeManager (const tree_managerRef TM, std::map< std::string, std::string > & input_files)
This function fills the tree manager with the nodes created from a set of source files.
Parameters
TM is where tree_manager will be stored
source_files are the source files to be compiled; key is the original source code file, value is the transformed source code file
check for aligned option
create obj
Recomputing leaf_name since source_file.second should be modified in the previous call
Definition at line 523 of file gcc_wrapper.cpp.
References already_processed_files, clang_recipes(), CM_ANALYZER, CM_EMPTY, CM_LTO, CM_STD, test_panda::command, CompileFile(), COMPILING_EC, CopyStdout(), GccWrapper::Compiler::CSROA_plugin_name, GccWrapper::Compiler::CSROA_plugin_obj, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, dump_exec_time(), GccWrapper::Compiler::expandMemOps_plugin_name, GccWrapper::Compiler::expandMemOps_plugin_obj, gcc_compiling_parameters, GccWrapper::Compiler::GepiCanon_plugin_name, GccWrapper::Compiler::GepiCanon_plugin_obj, GetBaseName(), GetCompiler(), GetLeafFileName(), INDENT_DBG_MEX, INFERRED_INTERFACE_GENERATION, GccWrapper::Compiler::is_clang, IsError(), GccWrapper::Compiler::llvm_link, GccWrapper::Compiler::llvm_opt, tree_manager::merge_tree_managers(), O3, O4, O5, optimization_flags, output_level, OUTPUT_LEVEL_NONE, OUTPUT_LEVEL_VERBOSE, PandaSystem(), Param, ParseTreeFile(), PRINT_OUT_MEX, rename_file(), GccWrapper::Compiler::ssa_plugin_name, GccWrapper::Compiler::ssa_plugin_obj, START_TIME, STOP_TIME, STR_CST_gcc_empty_suffix, STR_CST_gcc_output, STR_CST_gcc_rtl_suffix, STR_CST_gcc_tree_suffix, STR_CST_llvm_obj_file, THROW_ERROR, THROW_ERROR_CODE, THROW_WARNING, GccWrapper::Compiler::topfname_plugin_name, and GccWrapper::Compiler::topfname_plugin_obj.
GetCompiler()
GccWrapper::Compiler GccWrapper::GetCompiler () const [private]
Return the compiler for a given target.
Returns
a structure containing information about compiler
Definition at line 1604 of file gcc_wrapper.cpp.
References GccWrapper::Compiler::ASTAnalyzer_plugin_name, GccWrapper::Compiler::ASTAnalyzer_plugin_obj, compiler_target, GccWrapper::Compiler::cpp, GccWrapper::Compiler::CSROA_plugin_name, GccWrapper::Compiler::CSROA_plugin_obj, CT_NO_GCC, GccWrapper::Compiler::empty_plugin_name, GccWrapper::Compiler::empty_plugin_obj, GccWrapper::Compiler::expandMemOps_plugin_name, GccWrapper::Compiler::expandMemOps_plugin_obj, GccWrapper::Compiler::extra_options, GccWrapper::Compiler::gcc, GccWrapper::Compiler::GepiCanon_plugin_name, GccWrapper::Compiler::GepiCanon_plugin_obj, GccWrapper::Compiler::is_clang, GccWrapper::Compiler::llvm_link, GccWrapper::Compiler::llvm_opt, optimization_flags, Param, GccWrapper::Compiler::ssa_plugin_name, GccWrapper::Compiler::ssa_plugin_obj, STR, THROW_ASSERT, THROW_ERROR, GccWrapper::Compiler::topfname_plugin_name, and GccWrapper::Compiler::topfname_plugin_obj.
Referenced by CompileFile(), CreateExecutable(), FillTreeManager(), GetSystemIncludes(), and QueryGccConfig().
GetGccConfig()
void GccWrapper::GetGccConfig () const
Dump the gcc configuration.
Definition at line 2256 of file gcc_wrapper.cpp.
References QueryGccConfig().
GetSourceCodeLines()
size_t GccWrapper::GetSourceCodeLines (const ParameterConstRef Param) [static]
Return the total number of lines of the benchmark.
Parameters
Param is the set of input parameters
Returns
the total number of lines of the benchmark
The output file
Definition at line 2274 of file gcc_wrapper.cpp.
References test_panda::command, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, IsError(), PandaSystem(), STR_CST_file_IO_shell_output_file, and THROW_ERROR.
GetSystemIncludes()
void GccWrapper::GetSystemIncludes (std::vector< std::string > & includes) const
Return the list of gcc system include.
Parameters
includes is where result will be stored
This string contains the path and name of the compiler to be invoked
Definition at line 2216 of file gcc_wrapper.cpp.
References test_panda::command, GccWrapper::Compiler::cpp, GetCompiler(), IsError(), output_level, OUTPUT_LEVEL_PEDANTIC, PandaSystem(), Param, PRINT_OUT_MEX, SplitString(), STR_CST_gcc_include, THROW_ERROR, and util_print_cpu_stats().
InitializeGccParameters()
void GccWrapper::InitializeGccParameters () [private]
Initialize the gcc parameters line.
Parameters
OS is the optimizations set to be considered
Returns
the string with the parameters
If we are compiling with sparc-elf-gcc
Filling optimizations map
Adding standard
Adding defines
Adding undefines
Adding warnings
Adding includes
Adding libraries
Adding library directories
Adding no parse
Definition at line 825 of file gcc_wrapper.cpp.
References compiler_target, CT_NO_GCC, debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, gcc_compiling_parameters, gcc_linking_parameters, INDENT_DBG_MEX, O0, O1, O2, O3, O4, O5, Ofast, Og, optimization_flags, Os, OS, Oz, Param, parameter_values, ReadXml(), THROW_UNREACHABLE, WriteOptimizationLevel(), and WriteOptimizationsString().
Referenced by GccWrapper().
QueryGccConfig()
void GccWrapper::QueryGccConfig (const std::string & gcc_option) const
Function that print of stdout some useful information passing the given option.
Definition at line 2261 of file gcc_wrapper.cpp.
References test_panda::command, CopyStdout(), GccWrapper::Compiler::gcc, GetCompiler(), IsError(), PandaSystem(), Param, STR_CST_file_IO_shell_output_file, and THROW_ERROR.
Referenced by GetGccConfig().
ReadXml()
void GccWrapper::ReadXml (const std::string & file_name)
Read gcc configuration from file.
Parameters
file_name is the name of the file
Definition at line 2500 of file gcc_wrapper.cpp.
References XMLDomParser::Exec(), gcc_compiling_parameters, gcc_linking_parameters, attribute_sequence::get_attribute(), xml_child::get_children(), XMLDomParser::get_document(), xml_attribute::get_value(), optimization_flags, optimization_values, parameter_values, test_panda::parser, STR_XML_gcc_defines, STR_XML_gcc_includes, STR_XML_gcc_libraries, STR_XML_gcc_library_directories, STR_XML_gcc_name, STR_XML_gcc_optimization_flags, STR_XML_gcc_optimization_values, STR_XML_gcc_optimizations, STR_XML_gcc_parameter_values, STR_XML_gcc_standard, STR_XML_gcc_undefines, STR_XML_gcc_value, STR_XML_gcc_warnings, THROW_ERROR, and WriteOptimizationsString().
Referenced by InitializeGccParameters().
WriteOptimizationLevel()
std::string GccWrapper::WriteOptimizationLevel (const GccWrapper_OptimizationSet optimiation_level) [static]
Writes the optimization level as a string.
Parameters
optimization_level is the optimization level to be printed
Returns
the optimization level in string format
Definition at line 2415 of file gcc_wrapper.cpp.
References O0, O1, O2, O3, O4, O5, Ofast, Og, Os, Oz, and THROW_UNREACHABLE.
Referenced by clang_recipes(), and InitializeGccParameters().
WriteOptimizationsString()
std::string GccWrapper::WriteOptimizationsString () [private]
Write the string containing gcc optimization options.
Returns
the string with optimization options to be passed to the gcc
Preparing optimizations string
Definition at line 2461 of file gcc_wrapper.cpp.
References optimization_flags, optimization_values, parameter_values, and THROW_ASSERT.
Referenced by InitializeGccParameters(), and ReadXml().
WriteXml()
void GccWrapper::WriteXml (const std::string & file_name) const
Write gcc configuration on file.
Parameters
file_name is the name of the file
Definition at line 2703 of file gcc_wrapper.cpp.
References xml_child::add_child_element(), xml_document::create_root_node(), optimization_flags, optimization_values, parameter_values, attribute_sequence::set_attribute(), STR_XML_gcc_name, STR_XML_gcc_optimization_flag, STR_XML_gcc_optimization_value, STR_XML_gcc_optimizations, STR_XML_gcc_parameter_value, STR_XML_gcc_parameter_values, STR_XML_gcc_root, STR_XML_gcc_value, and xml_document::write_to_file_formatted().
Referenced by GccWrapper().
Field Documentation
already_processed_files
CustomSet<std::string> GccWrapper::already_processed_files [private]
The set of files for which tree manager has already been computed.
Definition at line 257 of file gcc_wrapper.hpp.
Referenced by FillTreeManager().
compiler_target
const GccWrapper_CompilerTarget GccWrapper::compiler_target [private]
The target compiler to be used.
Definition at line 245 of file gcc_wrapper.hpp.
Referenced by GetCompiler(), and InitializeGccParameters().
current_gcc_version
std::string GccWrapper::current_gcc_version [static]
The version of the gcc.
Autoheader include.
Header include Behavior include Constants include Frontend include HLS include RTL include STD include STL include Tree includes Utility include XML includes used for writing and reading the configuration file
Definition at line 349 of file gcc_wrapper.hpp.
Referenced by CheckGccCompatibleVersion(), and tree_manager::print().
current_plugin_version
std::string GccWrapper::current_plugin_version [static]
The version of the plugin.
Definition at line 352 of file gcc_wrapper.hpp.
Referenced by CheckGccCompatibleVersion(), and tree_manager::print().
debug_level
int GccWrapper::debug_level [private]
debug level
Definition at line 263 of file gcc_wrapper.hpp.
Referenced by CompileFile(), CreateExecutable(), FillTreeManager(), GetSourceCodeLines(), and InitializeGccParameters().
gcc_compiling_parameters
std::string GccWrapper::gcc_compiling_parameters [private]
The gcc parameters line for compiling a file.
Definition at line 251 of file gcc_wrapper.hpp.
Referenced by AddSourceCodeIncludes(), CreateExecutable(), FillTreeManager(), InitializeGccParameters(), and ReadXml().
gcc_linking_parameters
std::string GccWrapper::gcc_linking_parameters [private]
The gcc parameters line for creating an executable.
Definition at line 254 of file gcc_wrapper.hpp.
Referenced by CreateExecutable(), InitializeGccParameters(), and ReadXml().
optimization_flags
std::map<std::string, bool> GccWrapper::optimization_flags [private]
The set of activated optimizations.
Definition at line 269 of file gcc_wrapper.hpp.
Referenced by CreateExecutable(), FillTreeManager(), GetCompiler(), InitializeGccParameters(), ReadXml(), WriteOptimizationsString(), and WriteXml().
optimization_values
std::map<std::string, int> GccWrapper::optimization_values [private]
The value of parametric activate optimizations.
Definition at line 272 of file gcc_wrapper.hpp.
Referenced by ReadXml(), WriteOptimizationsString(), and WriteXml().
OS
const GccWrapper_OptimizationSet GccWrapper::OS [private]
The set of optimizations to be applied.
Definition at line 248 of file gcc_wrapper.hpp.
Referenced by InitializeGccParameters().
output_level
int GccWrapper::output_level [private]
debug level
Definition at line 260 of file gcc_wrapper.hpp.
Referenced by CompileFile(), CreateExecutable(), FillTreeManager(), and GetSystemIncludes().
Param
const ParameterConstRef GccWrapper::Param [private]
The set of input parameters.
Definition at line 242 of file gcc_wrapper.hpp.
Referenced by clang_recipes(), CompileFile(), CreateExecutable(), FillTreeManager(), GccWrapper(), GetCompiler(), GetSystemIncludes(), InitializeGccParameters(), and QueryGccConfig().
parameter_values
std::map<std::string, int> GccWrapper::parameter_values [private]
The values of optimizations parameters.
Definition at line 266 of file gcc_wrapper.hpp.
Referenced by CreateExecutable(), InitializeGccParameters(), ReadXml(), WriteOptimizationsString(), and WriteXml().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/treegcc/gcc_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/treegcc/gcc_wrapper.cpp