WishboneInterfaceTestbench Class Reference
Superclass include.
#include <wishbone_interface_testbench.hpp>
Public Member Functions
WishboneInterfaceTestbench (const ParameterConstRef _Param, const HLS_managerRef _AppM, const DesignFlowManagerConstRef design_flow_manager)
Header include.
~WishboneInterfaceTestbench () override
Destructor.
Protected Member Functions
void write_wishbone_input_signal_declaration (const tree_managerConstRef TreeM) const
void write_wishbone_callFSM_signal_declaration () const
void write_call (bool hasMultiIrq) const override
void write_memory_handler () const override
void write_interface_handler () const override
void write_signals (const tree_managerConstRef TreeM, bool &withMemory, bool &hasMultiIrq) const override
void write_slave_initializations (bool withMemory) const override
void init_extra_signals (bool withMemory) const override
void write_file_reading_operations () const override
void write_wishbone_output_signal_declaration (bool &withMemory, bool &hasMultiIrq) const
Additional Inherited Members
Detailed Description
Superclass include.
Definition at line 46 of file wishbone_interface_testbench.hpp.
Constructor & Destructor Documentation
WishboneInterfaceTestbench()
WishboneInterfaceTestbench::WishboneInterfaceTestbench (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Header include.
. include behavior include circuit include design_flows/backend/ToHDL include HLS include HLS/memory includes STD include STL includes technology/physical_library include tree include
Definition at line 90 of file wishbone_interface_testbench.cpp.
References WB4_TESTBENCH_GENERATION, and ~WishboneInterfaceTestbench().
Referenced by write_interface_handler().
 WishboneInterfaceTestbench()
WishboneInterfaceTestbench::~WishboneInterfaceTestbench () [override], [default]
Destructor.
Referenced by WishboneInterfaceTestbench(), and write_interface_handler().
Member Function Documentation
init_extra_signals()
void WishboneInterfaceTestbench::init_extra_signals (bool withMemory) const [override], [protected], [virtual]
Reimplemented from TestbenchGenerationBaseStep.
Definition at line 618 of file wishbone_interface_testbench.cpp.
Referenced by write_interface_handler().
write_call()
void WishboneInterfaceTestbench::write_call (bool hasMultiIrq) const [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 153 of file wishbone_interface_testbench.cpp.
References CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), refcount< T >::get(), memory::get_function_parameters(), BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, DesignFlowStep::parameters, BehavioralHelper::PrintVariable(), RESET_PORT_NAME, RETURN_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, THROW_ASSERT, and TestbenchGenerationBaseStep::writer.
write_file_reading_operations()
void WishboneInterfaceTestbench::write_file_reading_operations () const [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 588 of file wishbone_interface_testbench.cpp.
References HDL_manager::convert_to_identifier(), refcount< T >::get(), memory::get_function_parameters(), BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, BehavioralHelper::PrintVariable(), TestbenchGenerationBaseStep::read_input_value_from_file(), RETURN_PORT_NAME, THROW_ASSERT, and TestbenchGenerationBaseStep::writer.
Referenced by write_interface_handler().
write_interface_handler()
void WishboneInterfaceTestbench::write_interface_handler () const [inline], [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 57 of file wishbone_interface_testbench.hpp.
References DesignFlowStep::design_flow_manager, init_extra_signals(), WishboneInterfaceTestbench(), write_file_reading_operations(), write_signals(), write_slave_initializations(), write_wishbone_output_signal_declaration(), and ~WishboneInterfaceTestbench().
write_memory_handler()
void WishboneInterfaceTestbench::write_memory_handler () const [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 395 of file wishbone_interface_testbench.cpp.
References TestbenchGenerationBaseStep::cir, CLOCK_PORT_NAME, module::find_member(), GET_TYPE_SIZE, TestbenchGenerationBaseStep::mod, DesignFlowStep::parameters, port_o_K, RESET_PORT_NAME, STD_CLOSING_CHAR, STD_OPENING_CHAR, STR, U, WB_DATOM_PORT_NAME, and TestbenchGenerationBaseStep::writer.
write_signals()
void WishboneInterfaceTestbench::write_signals (const tree_managerConstRef TreeM, bool & withMemory, bool & hasMultiIrq) const [override], [protected], [virtual]
FIXME: real numbers at the moment have to be considered differently because of computation of ulp; c++ code is still managed in the old way
Implements TestbenchGenerationBaseStep.
Definition at line 516 of file wishbone_interface_testbench.cpp.
References HDL_manager::convert_to_identifier(), TestbenchGenerationBaseStep::flag_cpp, refcount< T >::get(), memory::get_function_parameters(), GET_INDEX_NODE, GET_NODE, memory::get_parameter_base_address(), tree_helper::get_pointed_type(), tree_manager::get_tree_node_const(), tree_helper::get_type_index(), BehavioralHelper::GetFunctionReturnType(), HLS_step::HLSMgr, tree_helper::is_a_pointer(), tree_helper::is_real(), BehavioralHelper::PrintVariable(), RETURN_PORT_NAME, tree_helper::size(), START_PORT_NAME, STR, THROW_ASSERT, write_wishbone_callFSM_signal_declaration(), write_wishbone_input_signal_declaration(), write_wishbone_output_signal_declaration(), and TestbenchGenerationBaseStep::writer.
Referenced by write_interface_handler().
write_slave_initializations()
void WishboneInterfaceTestbench::write_slave_initializations (bool withMemory) const [override], [protected], [virtual]
Implements TestbenchGenerationBaseStep.
Definition at line 583 of file wishbone_interface_testbench.cpp.
Referenced by write_interface_handler().
write_wishbone_callFSM_signal_declaration()
void WishboneInterfaceTestbench::write_wishbone_callFSM_signal_declaration () const [protected]
Definition at line 140 of file wishbone_interface_testbench.cpp.
References TestbenchGenerationBaseStep::writer.
Referenced by write_signals().
write_wishbone_input_signal_declaration()
void WishboneInterfaceTestbench::write_wishbone_input_signal_declaration (const tree_managerConstRef TreeM) const [protected]
write input signals declaration
Definition at line 97 of file wishbone_interface_testbench.cpp.
References CLOCK_PORT_NAME, HDL_manager::convert_to_identifier(), refcount< T >::get(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), GET_INDEX_NODE, structural_object::get_kind(), GET_NODE, tree_helper::get_pointed_type(), tree_manager::get_tree_node_const(), tree_helper::get_type_index(), structural_object::get_typeRef(), tree_helper::is_a_pointer(), TestbenchGenerationBaseStep::mod, port_o_K, tree_helper::size(), STR, structural_type_descriptor::treenode, structural_type_descriptor::type, structural_type_descriptor::VECTOR_BOOL, WB_ACKIM_PORT_NAME, and TestbenchGenerationBaseStep::writer.
Referenced by write_signals().
write_wishbone_output_signal_declaration()
void WishboneInterfaceTestbench::write_wishbone_output_signal_declaration (bool & withMemory, bool & hasMultiIrq) const [protected]
write output signals declaration
Definition at line 489 of file wishbone_interface_testbench.cpp.
References HDL_manager::convert_to_identifier(), refcount< T >::get(), module::get_out_port(), module::get_out_port_size(), TestbenchGenerationBaseStep::mod, port_o_K, port_vector_o_K, STR, structural_type_descriptor::VECTOR_BOOL, WB_CYCOM_PORT_NAME, WB_STBOM_PORT_NAME, and TestbenchGenerationBaseStep::writer.
Referenced by write_interface_handler(), and write_signals().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/wishbone_interface_testbench.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/wishbone_interface_testbench.cpp