operations_graph_constructor Class Reference
class providing methods to manage an operations graph.
#include <operations_graph_constructor.hpp>
Public Member Functions
vertex getIndex (const std::string &source)
Return the vertex index given the id of the vertex node.
vertex CgetIndex (const std::string &source) const
Return the vertex index given the id of the vertex node.
EdgeDescriptor AddEdge (const vertex source, const vertex dest, int selector)
add an edge between vertex source and vertex dest
void RemoveEdge (const vertex source, const vertex dest, int selector)
remove a selector between two vertices
void RemoveSelector (const EdgeDescriptor edge, const int selector)
set the selector of an edge between vertex source and vertex dest
void CompressEdges ()
Remove all redundant edges.
void Clear ()
Remove all vertices and edges.
void add_edge_info (const vertex src, const vertex tgt, const int selector, unsigned int NodeID)
Add edge info to the graph.
void AddOperation (const tree_managerRef TM, const std::string &source, const std::string &oper, unsigned int bb_index, const unsigned int node_id)
Add the operation associated with a vertex.
void add_type (const std::string &source, unsigned int type)
Add the type associated with a vertex.
operations_graph_constructor (OpGraphsCollectionRef _og)
Constructor.
~operations_graph_constructor ()
Destructor.
void AddVariable (const vertex op_vertex, const unsigned int variable, const FunctionBehavior_VariableType variable_type, const FunctionBehavior_VariableAccessType access_type)
Adds an access to a variable to an operation vertex.
void AddSourceCodeVariable (const vertex &Ver, unsigned int Vargc)
Adds a (ssa-)variable to the set of variables referred by the operation vertex.
void add_parameter (const vertex &Ver, unsigned int Vargc)
Adds a parameter to the vertex.
void add_called_function (const std::string &source, unsigned int called_function)
Adds a call to the vertex.
Private Attributes
const OpGraphsCollectionRef og
reference to the bulk operations graph
const OpGraphRef op_graph
The graph with all the edges.
std::map< std::string, vertex > index_map
Mapping between id to index.
Detailed Description
class providing methods to manage an operations graph.
Definition at line 72 of file operations_graph_constructor.hpp.
Constructor & Destructor Documentation
operations_graph_constructor()
operations_graph_constructor::operations_graph_constructor (OpGraphsCollectionRef _og) [explicit]
Constructor.
Header include.
Parameters
og is the collection of operations graph
Definition at line 60 of file operations_graph_constructor.cpp.
References ~operations_graph_constructor().
 operations_graph_constructor()
operations_graph_constructor::~operations_graph_constructor () [default]
Destructor.
Referenced by operations_graph_constructor().
Member Function Documentation
add_called_function()
void operations_graph_constructor::add_called_function (const std::string & source, unsigned int called_function)
Adds a call to the vertex.
Parameters
source is the vertex name at which the type is associated.
called is the called function
Definition at line 180 of file operations_graph_constructor.cpp.
References getIndex(), and op_graph.
add_edge_info()
void operations_graph_constructor::add_edge_info (const vertex src, const vertex tgt, const int selector, unsigned int NodeID)
Add edge info to the graph.
Parameters
src is an unique id representing the source node.
tgt is an unique id representing the target node.
ef is the family of the edge. See cdfg_edge_info class for details.
NodeID is the NodeID of the variable carrying the data through the edge.
Definition at line 109 of file operations_graph_constructor.cpp.
References GET_NAME, og, and THROW_ASSERT.
add_parameter()
void operations_graph_constructor::add_parameter (const vertex & Ver, unsigned int Vargc)
Adds a parameter to the vertex.
Parameters
Ver is the operation vertex
Var is the node id associated to the variable referred by the operation vertex
Definition at line 175 of file operations_graph_constructor.cpp.
References op_graph.
add_type()
void operations_graph_constructor::add_type (const std::string & source, unsigned int type)
Add the type associated with a vertex.
Parameters
source is the vertex name at which the type is associated.
type is an unsigned int representing the type associated with source.
Definition at line 152 of file operations_graph_constructor.cpp.
References GET_NODE_INFO, getIndex(), og, THROW_ASSERT, and TYPE_GENERIC.
AddEdge()
EdgeDescriptor operations_graph_constructor::AddEdge (const vertex source, const vertex dest, int selector)
add an edge between vertex source and vertex dest
Parameters
source is the source vertex
dest is the dest vertexes
selector is the type of the edge
Definition at line 89 of file operations_graph_constructor.cpp.
References og.
AddOperation()
void operations_graph_constructor::AddOperation (const tree_managerRef TM, const std::string & source, const std::string & oper, unsigned int bb_index, const unsigned int node_id)
Add the operation associated with a vertex.
Parameters
TM is the tree manager
source is the vertex name at which the operation is associated.
oper is a string representing the operation associated with source.
bb_index is the basic block index associated with the operation.
node_id is the index of the tree node
Definition at line 118 of file operations_graph_constructor.cpp.
References ENTRY, ENTRY_ID, EXIT, EXIT_ID, GET_NODE_INFO, tree_manager::get_tree_node_const(), getIndex(), tree_manager::GetTreeReindex(), og, op_graph, and THROW_ASSERT.
AddSourceCodeVariable()
void operations_graph_constructor::AddSourceCodeVariable (const vertex & Ver, unsigned int Vargc)
Adds a (ssa-)variable to the set of variables referred by the operation vertex.
Parameters
Ver is the operation vertex
Var is the node id associated to the variable referred by the operation vertex
Definition at line 185 of file operations_graph_constructor.cpp.
References op_graph.
AddVariable()
void operations_graph_constructor::AddVariable (const vertex op_vertex, const unsigned int variable, const FunctionBehavior_VariableType variable_type, const FunctionBehavior_VariableAccessType access_type)
Adds an access to a variable to an operation vertex.
Parameters
op_vertex is the operation to be considered
variable is the index of the variable
type is the type of the variable
access_type is the type of the access
Definition at line 163 of file operations_graph_constructor.cpp.
References op_graph.
CgetIndex()
vertex operations_graph_constructor::CgetIndex (const std::string & source) const
Return the vertex index given the id of the vertex node.
Parameters
source is the name of the vertex.
Returns
the index associated with the source.
Definition at line 83 of file operations_graph_constructor.cpp.
References index_map, and THROW_ASSERT.
Clear()
void operations_graph_constructor::Clear ()
Remove all vertices and edges.
Definition at line 66 of file operations_graph_constructor.cpp.
References index_map, and og.
CompressEdges()
void operations_graph_constructor::CompressEdges ()
Remove all redundant edges.
Definition at line 104 of file operations_graph_constructor.cpp.
References og.
getIndex()
vertex operations_graph_constructor::getIndex (const std::string & source)
Return the vertex index given the id of the vertex node.
Parameters
source is the name of the vertex.
Returns
the index associated with the source.
Definition at line 72 of file operations_graph_constructor.cpp.
References index_map, and og.
Referenced by add_called_function(), add_type(), and AddOperation().
RemoveEdge()
void operations_graph_constructor::RemoveEdge (const vertex source, const vertex dest, int selector)
remove a selector between two vertices
Parameters
source is the source vertex
dest is the dest vertexes
selector is the type of the edge
Definition at line 94 of file operations_graph_constructor.cpp.
References og.
RemoveSelector()
void operations_graph_constructor::RemoveSelector (const EdgeDescriptor edge, const int selector)
set the selector of an edge between vertex source and vertex dest
Parameters
edge is the edge descriptor from which the selector has to be removed
selector is the selector to be removed
Definition at line 99 of file operations_graph_constructor.cpp.
References og.
Field Documentation
index_map
std::map<std::string, vertex> operations_graph_constructor::index_map [private]
Mapping between id to index.
Definition at line 82 of file operations_graph_constructor.hpp.
Referenced by CgetIndex(), Clear(), and getIndex().
og
const OpGraphsCollectionRef operations_graph_constructor::og [private]
reference to the bulk operations graph
Definition at line 76 of file operations_graph_constructor.hpp.
Referenced by add_edge_info(), add_type(), AddEdge(), AddOperation(), Clear(), CompressEdges(), getIndex(), RemoveEdge(), and RemoveSelector().
op_graph
const OpGraphRef operations_graph_constructor::op_graph [private]
The graph with all the edges.
Definition at line 79 of file operations_graph_constructor.hpp.
Referenced by add_called_function(), add_parameter(), AddOperation(), AddSourceCodeVariable(), and AddVariable().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/operations_graph_constructor.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/operations_graph_constructor.cpp