rebuild_initialization Class Reference
Rebuild initialization function flow front-end step.
#include <rebuild_initializations.hpp>
Public Member Functions
rebuild_initialization (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~rebuild_initialization () override
Destructor.
DesignFlowStep_Status InternalExec () override
Rebuild initialization function flow front-end step.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Rebuild initialization function flow front-end step.
Definition at line 66 of file rebuild_initializations.hpp.
Constructor & Destructor Documentation
rebuild_initialization()
rebuild_initialization::rebuild_initialization (const ParameterConstRef Param, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
STD include
Definition at line 68 of file rebuild_initializations.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, and GET_CLASS.
 rebuild_initialization()
rebuild_initialization::~rebuild_initialization () [override], [default]
Destructor.
Referenced by ComputeFrontendRelationships().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > rebuild_initialization::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 74 of file rebuild_initializations.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and ~rebuild_initialization().
InternalExec()
DesignFlowStep_Status rebuild_initialization::InternalExec () [override], [virtual]
Rebuild initialization function flow front-end step.
Returns
the exit status of this step
for each basic block B in CFG do > Consider all blocks successively
NOTE: the check has to be performed on the type of the elements of the array and not on the constant in the right part to avoid rebuilding of array of pointers
Implements FunctionFrontendFlowStep.
Definition at line 93 of file rebuild_initializations.cpp.
References FrontendFlowStep::AppM, tree_manager::CGetTreeNode(), tree_helper::CGetType(), tree_manipulation::create_default_integer_type(), tree_manager::create_tree_node(), tree_manipulation::CreateIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::GetElements(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, index, tree_manager::new_tree_node_id(), DesignFlowStep::parameters, PRINT_DBG_MEX, sl, STR, SUCCESS, THROW_ASSERT, TOK, TOK_SRCP, and TOK_TYPE.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/rebuild_initializations.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/rebuild_initializations.cpp