FSM_NI_SSA_liveness Class Reference
#include <FSM_NI_SSA_liveness.hpp>
Public Member Functions
FSM_NI_SSA_liveness (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~FSM_NI_SSA_liveness () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Additional Inherited Members
Detailed Description
Definition at line 50 of file FSM_NI_SSA_liveness.hpp.
Constructor & Destructor Documentation
FSM_NI_SSA_liveness()
FSM_NI_SSA_liveness::FSM_NI_SSA_liveness (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
design_flow_manager is the design flow manager
. include behavior includes hls includes HLS/liveness include hls/memory include hls/stg includes tree includes utility include
Definition at line 84 of file FSM_NI_SSA_liveness.cpp.
References DesignFlowStep::debug_level, FSM_NI_SSA_LIVENESS, GET_CLASS, DesignFlowStep::parameters, and ~FSM_NI_SSA_liveness().
 FSM_NI_SSA_liveness()
FSM_NI_SSA_liveness::~FSM_NI_SSA_liveness () [override], [default]
Destructor.
Referenced by FSM_NI_SSA_liveness().
Member Function Documentation
Initialize()
void FSM_NI_SSA_liveness::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from HLSFunctionStep.
Definition at line 92 of file FSM_NI_SSA_liveness.cpp.
References HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), DesignFlowStep::parameters, and hls::Rliv.
InternalExec()
DesignFlowStep_Status FSM_NI_SSA_liveness::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Map between basic block node index and vertices
compute which operation defines a variable (add_op_definition) compute in which states an operation complete the computation (add_state_for_ending_op) compute the set of supporting states compute the set of dummy states
compute live_out
compute the live in of a state by traversing the state list in topological order
fix the live in/out of dummy states
add all the uses of ds to src_state
extend the lifetime of used variable to reduce the critical path
compute in which state an operation is in execution compute state in relation: on which transition a variable is live in compute state out relation: on which transition a variable is live out
now we look for the last state with operations belonging to basic block bb_index
print the analysis result
Implements HLSFunctionStep.
Definition at line 144 of file FSM_NI_SSA_liveness.cpp.
References liveness::add_dummy_state(), liveness::add_name(), liveness::add_op_definition(), liveness::add_state_for_ending_op(), liveness::add_state_for_running_op(), liveness::add_state_in_for_var(), liveness::add_state_out_for_var(), liveness::add_support_state(), StateTransitionGraphManager::CGetAstg(), FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), StateTransitionGraphManager::CGetStg(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DEFINITION, FunctionBehavior::DFG, FunctionBehavior::FBB, hls::functionId, HLSFunctionStep::funId, get_bb_index_from_state_info(), StateTransitionGraphManager::get_entry_state(), StateTransitionGraphManager::get_exit_state(), BehavioralHelper::get_function_name(), liveness::get_live_in(), liveness::get_live_out(), GET_NAME, StateTransitionGraphManager::get_state_name(), GET_TYPE, HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, tree_helper::is_parameter(), tree_helper::is_ssa_name(), tree_helper::is_virtual(), NULL_VERTEX, PRINT_DBG_MEX, PRINT_DBG_STRING, BehavioralHelper::PrintVariable(), hls::Rliv, SCALAR, liveness::set_live_in(), liveness::set_live_out(), hls::STG, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, TYPE_NOP, TYPE_PHI, update_liveout_with_prev(), and USE.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/liveness/FSM_NI_SSA_liveness.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/liveness/FSM_NI_SSA_liveness.cpp