bloc Struct Reference
This struct specifies the field bloc (basic block).
#include <tree_basic_block.hpp>
Public Types
enum { GETID =(list_of_phi) = 0
 }
visitor enum
Public Member Functions
bloc (unsigned int _number)
constructor
virtual ~bloc ()
Destructor.
void add_pred (const unsigned int &a)
Add a value to list of pred.
void add_succ (const unsigned int &a)
Add a value to list of succ.
void AddPhi (const tree_nodeRef a)
Add a value to list of phi node.
void PushFront (const tree_nodeRef statement)
Add a statement in front of list of statements.
void PushBack (const tree_nodeRef statement)
Add a statement as last non controllong statement.
void Replace (const tree_nodeRef old_stmt, const tree_nodeRef new_stmt, const bool move_virtuals)
Replace a statement with another one.
void PushBefore (const tree_nodeRef new_stmt, const tree_nodeRef existing_stmt)
Add a statement before a specified one.
void PushAfter (const tree_nodeRef new_stmt, const tree_nodeRef existing_stmt)
Add a statement after a specified one.
void ReorderLUTs ()
ReorderLUTs reorders the LUT statements to fix the def-use relations.
void RemoveStmt (const tree_nodeRef statement)
Remove a statement.
void RemovePhi (const tree_nodeRef phi)
Remove a phi.
void SetSSAUsesComputed ()
Set that uses of ssa have been computed.
const std::list< tree_nodeRef > & CGetPhiList () const
Return the list of phi.
const std::list< tree_nodeRef > & CGetStmtList () const
Return the list of stmt.
size_t CGetNumberRemovedPhi () const
Return the number of removed phi.
virtual void visit (tree_node_visitor *const v) const
virtual function used to traverse the tree_node data structure.
Data Fields
std::vector< unsigned int > list_of_pred
list_of_pred is the list of predecessors.
std::vector< unsigned int > list_of_succ
list_of_succ is the list of successors.
const unsigned int number
number is the index of the basic block.
unsigned int loop_id
loop identifier coming from GCC
CustomOrderedSet< unsigned int > live_in
Live_In of the basic block.
CustomOrderedSet< unsigned int > live_out
Live_Out of the basic block.
unsigned int hpl
store the relation between the phi defs inserted in the live_out set and phi uses
unsigned int true_edge
in case the last statement is a gimple_cond associated with an if statement this member contains the basic block reference to the then statements.
unsigned int false_edge
in case the last statement is a gimple_cond associated with an if statement this member contains the basic block reference to the else statements.
Static Public Attributes
static const unsigned int ENTRY_BLOCK_ID = 0
constant identifying the entry basic block
static const unsigned int EXIT_BLOCK_ID = 1
constant identifying the exit basic block
Private Attributes
std::list< tree_nodeRef > list_of_phi
list_of_phi is a list of eventual phi node presents in the basic block.
std::list< tree_nodeRef > list_of_stmt
list_of_stmt is the list of statements stored in the basic block.
size_t removed_phi
Number of removed phi.
bool updated_ssa_uses
consistency of ssa uses
Friends
class use_counting
Detailed Description
This struct specifies the field bloc (basic block).
The tree walker structure of this node is: #(TOK_BLOC TOK_NUMBER (pred)+ (succ)+ (phi)* (stmt)*)
Definition at line 89 of file tree_basic_block.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 259 of file tree_basic_block.hpp.
Constructor & Destructor Documentation
bloc()
bloc::bloc (unsigned int _number) [explicit]
constructor
Definition at line 62 of file tree_basic_block.cpp.
References ~bloc().
 bloc()
bloc::~bloc () [virtual], [default]
Destructor.
Referenced by bloc().
Member Function Documentation
add_pred()
void bloc::add_pred (const unsigned int & a) [inline]
Add a value to list of pred.
Parameters
a is a pred.
Definition at line 156 of file tree_basic_block.hpp.
add_succ()
void bloc::add_succ (const unsigned int & a) [inline]
Add a value to list of succ.
Parameters
a is a succ.
Definition at line 165 of file tree_basic_block.hpp.
References AddPhi(), CGetNumberRemovedPhi(), CGetPhiList(), CGetStmtList(), phi, PushAfter(), PushBack(), PushBefore(), PushFront(), RemovePhi(), RemoveStmt(), ReorderLUTs(), Replace(), and SetSSAUsesComputed().
AddPhi()
void bloc::AddPhi (const tree_nodeRef a)
Add a value to list of phi node.
Parameters
a is a NODE_ID.
This check is necessary since during parsing of statement list statement has not yet been filled
Definition at line 413 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, GET_NODE, tree_node::index, list_of_phi, number, and updated_ssa_uses.
Referenced by add_succ().
CGetNumberRemovedPhi()
size_t bloc::CGetNumberRemovedPhi () const
Return the number of removed phi.
Definition at line 514 of file tree_basic_block.cpp.
References removed_phi.
Referenced by add_succ().
CGetPhiList()
const std::list< tree_nodeRef > & bloc::CGetPhiList () const
Return the list of phi.
Definition at line 447 of file tree_basic_block.cpp.
References list_of_phi.
Referenced by add_succ(), and raw_writer::write_when_not_null_point_to().
CGetStmtList()
const std::list< tree_nodeRef > & bloc::CGetStmtList () const
Return the list of stmt.
Definition at line 452 of file tree_basic_block.cpp.
References list_of_stmt.
Referenced by add_succ(), and raw_writer::write_when_not_null_point_to().
PushAfter()
void bloc::PushAfter (const tree_nodeRef new_stmt, const tree_nodeRef existing_stmt)
Add a statement after a specified one.
Parameters
new_stmt is the statement to be added
existing_stmt is the statement after which new_stmt has to be added
Definition at line 293 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, ENTRY_BLOCK_ID, GET_NODE, tree_node::index, list_of_stmt, number, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by add_succ().
PushBack()
void bloc::PushBack (const tree_nodeRef statement)
Add a statement as last non controllong statement.
Parameters
statement is the statement to be added
This check is necessary since during parsing of statement list statement has not yet been filled
Definition at line 126 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, GET_NODE, tree_node::index, tree_helper::LastStatement(), list_of_stmt, number, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by add_succ(), and Replace().
PushBefore()
void bloc::PushBefore (const tree_nodeRef new_stmt, const tree_nodeRef existing_stmt)
Add a statement before a specified one.
Parameters
new_stmt is the statement to be added
existing_stmt is the statement before which new_stmt has to be added
Definition at line 243 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, ENTRY_BLOCK_ID, GET_NODE, tree_node::index, list_of_stmt, number, STR, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by add_succ(), and Replace().
PushFront()
void bloc::PushFront (const tree_nodeRef statement)
Add a statement in front of list of statements.
Parameters
statement is the statement to be added
This check is necessary since during parsing of statement list statement has not yet been filled
Definition at line 77 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, GET_NODE, tree_node::index, list_of_stmt, number, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by add_succ().
RemovePhi()
void bloc::RemovePhi (const tree_nodeRef phi)
Remove a phi.
Parameters
phi is the phi to be removed
Definition at line 485 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, GET_NODE, tree_node::index, list_of_phi, removed_phi, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by add_succ().
RemoveStmt()
void bloc::RemoveStmt (const tree_nodeRef statement)
Remove a statement.
Parameters
statement is the statement to be removed
Definition at line 457 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), counter, GET_NODE, tree_node::index, list_of_stmt, number, STR, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by add_succ(), and Replace().
ReorderLUTs()
void bloc::ReorderLUTs ()
ReorderLUTs reorders the LUT statements to fix the def-use relations.
add back
Definition at line 328 of file tree_basic_block.cpp.
References tree_helper::ComputeSsaUses(), GET_NODE, list_of_phi, list_of_stmt, number, and phi.
Referenced by add_succ().
Replace()
void bloc::Replace (const tree_nodeRef old_stmt, const tree_nodeRef new_stmt, const bool move_virtuals)
Replace a statement with another one.
Parameters
old_stmt is the old statement to be removed
new_stmt is the new statement to be added
move_virtuals specifies if memdef and vdef have to be transferred
Definition at line 184 of file tree_basic_block.cpp.
References GET_NODE, tree_node::index, list_of_stmt, PushBack(), PushBefore(), RemoveStmt(), STR, and THROW_ASSERT.
Referenced by add_succ().
SetSSAUsesComputed()
void bloc::SetSSAUsesComputed ()
Set that uses of ssa have been computed.
Definition at line 519 of file tree_basic_block.cpp.
References THROW_ASSERT, and updated_ssa_uses.
Referenced by add_succ().
visit()
void bloc::visit (tree_node_visitor *const v) const [virtual]
virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
live in and out not visited by design
Definition at line 68 of file tree_basic_block.cpp.
References ALL_VISIT, list_of_phi, list_of_stmt, and SEQ_VISIT_MEMBER.
Friends And Related Function Documentation
use_counting
friend class use_counting [friend]
Definition at line 92 of file tree_basic_block.hpp.
Field Documentation
ENTRY_BLOCK_ID
const unsigned int bloc::ENTRY_BLOCK_ID = 0 [static]
constant identifying the entry basic block
Header include.
tree includes
Definition at line 247 of file tree_basic_block.hpp.
Referenced by short_circuit_taf::check_merging_candidate(), interface_infer::classifyArg(), PhiOpt::IdentifyPattern(), BasicBlocksCfgComputation::InternalExec(), remove_clobber_ga::InternalExec(), dead_code_elimination::InternalExec(), interface_infer::InternalExec(), simple_code_motion::InternalExec(), short_circuit_taf::InternalExec(), CSE::InternalExec(), multi_way_if::InternalExec(), PhiOpt::InternalExec(), tree_helper::is_a_nop_function_decl(), rebuild_initialization2::look_for_ROMs(), PushAfter(), PushBefore(), virtual_phi_nodes_split::virtual_split_phi(), raw_writer::write_when_not_null_point_to(), and FunctionFrontendFlowStep::WriteBBGraphDot().
EXIT_BLOCK_ID
const unsigned int bloc::EXIT_BLOCK_ID = 1 [static]
constant identifying the exit basic block
Definition at line 250 of file tree_basic_block.hpp.
Referenced by PhiOpt::ChainOptimization(), interface_infer::classifyArg(), PhiOpt::IdentifyPattern(), BasicBlocksCfgComputation::InternalExec(), remove_clobber_ga::InternalExec(), dead_code_elimination::InternalExec(), interface_infer::InternalExec(), RemoveEndingIf::InternalExec(), simple_code_motion::InternalExec(), short_circuit_taf::InternalExec(), CSE::InternalExec(), multi_way_if::InternalExec(), operations_cfg_computation::InternalExec(), PhiOpt::InternalExec(), tree_helper::is_a_nop_function_decl(), rebuild_initialization2::look_for_ROMs(), raw_writer::write_when_not_null_point_to(), FunctionFrontendFlowStep::WriteBBGraphDot(), EdgeCWriter::writeRoutineInstructions(), and CWriter::writeRoutineInstructions().
false_edge
unsigned int bloc::false_edge
in case the last statement is a gimple_cond associated with an if statement this member contains the basic block reference to the else statements.
Definition at line 135 of file tree_basic_block.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
hpl
unsigned int bloc::hpl
store the relation between the phi defs inserted in the live_out set and phi uses
flag for header of reducible parallelizable loop
Definition at line 129 of file tree_basic_block.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
list_of_phi
std::list<tree_nodeRef> bloc::list_of_phi [private]
list_of_phi is a list of eventual phi node presents in the basic block.
Definition at line 95 of file tree_basic_block.hpp.
Referenced by AddPhi(), CGetPhiList(), RemovePhi(), ReorderLUTs(), and visit().
list_of_pred
std::vector<unsigned int> bloc::list_of_pred
list_of_pred is the list of predecessors.
Definition at line 108 of file tree_basic_block.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
list_of_stmt
std::list<tree_nodeRef> bloc::list_of_stmt [private]
list_of_stmt is the list of statements stored in the basic block.
Definition at line 98 of file tree_basic_block.hpp.
Referenced by CGetStmtList(), PushAfter(), PushBack(), PushBefore(), PushFront(), RemoveStmt(), ReorderLUTs(), Replace(), and visit().
list_of_succ
std::vector<unsigned int> bloc::list_of_succ
list_of_succ is the list of successors.
Definition at line 111 of file tree_basic_block.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
live_in
CustomOrderedSet<unsigned int> bloc::live_in
Live_In of the basic block.
Definition at line 120 of file tree_basic_block.hpp.
live_out
CustomOrderedSet<unsigned int> bloc::live_out
Live_Out of the basic block.
Definition at line 123 of file tree_basic_block.hpp.
loop_id
unsigned int bloc::loop_id
loop identifier coming from GCC
Definition at line 117 of file tree_basic_block.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
number
const unsigned int bloc::number
number is the index of the basic block.
Definition at line 114 of file tree_basic_block.hpp.
Referenced by AddPhi(), PushAfter(), PushBack(), PushBefore(), PushFront(), RemoveStmt(), ReorderLUTs(), and raw_writer::write_when_not_null_point_to().
removed_phi
size_t bloc::removed_phi [private]
Number of removed phi.
Definition at line 101 of file tree_basic_block.hpp.
Referenced by CGetNumberRemovedPhi(), and RemovePhi().
true_edge
unsigned int bloc::true_edge
in case the last statement is a gimple_cond associated with an if statement this member contains the basic block reference to the then statements.
Definition at line 132 of file tree_basic_block.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
updated_ssa_uses
bool bloc::updated_ssa_uses [private]
consistency of ssa uses
Definition at line 104 of file tree_basic_block.hpp.
Referenced by AddPhi(), PushAfter(), PushBack(), PushBefore(), PushFront(), RemovePhi(), RemoveStmt(), and SetSSAUsesComputed().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_basic_block.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_basic_block.cpp