target_technology Class Reference
#include <target_technology.hpp>
Public Types
enum target_t { FPGA = 1
 }
target technologies currently implemented
Public Member Functions
target_technology (const ParameterConstRef &param)
Constructor.
virtual ~target_technology ()
Destructor.
virtual void initialize ()=0
Initializes the target technology based on the given parameters.
target_t get_type () const
Returns the type of the technology currently implemented.
virtual std::string get_string_type () const =0
Returns the type of the technology currently implemented in a string format.
template<typename G >
G get_parameter (const std::string &key) const
Returns the value of the specified parameter, if any.
template<typename G >
void set_parameter (const std::string &key, G value)
Sets the value of the specified parameter.
bool is_parameter (const std::string &key) const
Returns true if there is a value associated with the specified string identifier, false otherwise.
Static Public Member Functions
static target_technologyRef create_technology (const target_t type, const ParameterConstRef &param)
Factory method.
Protected Member Functions
void xload (const xml_element *node)
Method to read an XML file and identify the section containing technology-related parameters.
void xload_technology_parameters (const xml_element *tech_xml)
Method to read the part of the XML file related to technology parameters.
Protected Attributes
const ParameterConstRef Param
Class containing all the parameters.
target_t type
Technology type.
std::map< std::string, std::string > parameters
Map containing all the parameters of the technology. All the values are stored as strings and they have correctly converted through the get_parameter template.
Detailed Description
Definition at line 61 of file target_technology.hpp.
Member Enumeration Documentation
target_t
enum target_technology::target_t
target technologies currently implemented
Enumerator
FPGA
Definition at line 65 of file target_technology.hpp.
Constructor & Destructor Documentation
target_technology()
target_technology::target_technology (const ParameterConstRef & param) [explicit]
Constructor.
Autoheader include.
Definition at line 65 of file target_technology.cpp.
References FPGA, and ~target_technology().
 target_technology()
target_technology::~target_technology () [virtual], [default]
Destructor.
Referenced by target_technology().
Member Function Documentation
create_technology()
target_technologyRef target_technology::create_technology (const target_t type, const ParameterConstRef & param) [static]
Factory method.
Creates the datastructure of the given type
Parameters
type is the type of the target technology to be created
param is the datastructure containing all the parameters
Returns
a reference to the specialization of the target technology datastructure
this point should never be reached
Definition at line 71 of file target_technology.cpp.
References FPGA, and THROW_ERROR.
Referenced by FPGA_device::FPGA_device(), and IC_device::load_devices().
get_parameter()
template<typename G >
G target_technology::get_parameter (const std::string & key) const [inline]
Returns the value of the specified parameter, if any.
Otherwise, it throws an exception.
Parameters
key it is the string identifier of the parameter to be returned
Definition at line 136 of file target_technology.hpp.
References THROW_ERROR.
Referenced by IC_device::set_dimension().
get_string_type()
virtual std::string target_technology::get_string_type () const [pure virtual]
Returns the type of the technology currently implemented in a string format.
Returns
a string representing the type of the technology
Implemented in CMOS_technology, and FPGA_technology.
Referenced by HLS_target::HLS_target().
get_type()
target_technology::target_t target_technology::get_type () const
Returns the type of the technology currently implemented.
Returns
the type of the technology
Definition at line 88 of file target_technology.cpp.
References type.
initialize()
virtual void target_technology::initialize () [pure virtual]
Initializes the target technology based on the given parameters.
Implemented in FPGA_technology, and CMOS_technology.
is_parameter()
bool target_technology::is_parameter (const std::string & key) const [inline]
Returns true if there is a value associated with the specified string identifier, false otherwise.
Parameters
key it is the string identifier of the parameter to be searched
Definition at line 156 of file target_technology.hpp.
set_parameter()
template<typename G >
void target_technology::set_parameter (const std::string & key, G value) [inline]
Sets the value of the specified parameter.
Definition at line 147 of file target_technology.hpp.
Referenced by CMOS_technology::initialize().
xload()
void target_technology::xload (const xml_element * node) [protected]
Method to read an XML file and identify the section containing technology-related parameters.
Parameters
node is the root node for the analysis
Definition at line 93 of file target_technology.cpp.
References xml_child::get_children(), and xload_technology_parameters().
Referenced by CMOS_technology::CMOS_technology().
xload_technology_parameters()
void target_technology::xload_technology_parameters (const xml_element * tech_xml) [protected]
Method to read the part of the XML file related to technology parameters.
Parameters
tech_xml is the node where the analysis will be performed
Definition at line 107 of file target_technology.cpp.
References xml_child::get_children(), LOAD_XVM, and parameters.
Referenced by xload().
Field Documentation
Param
const ParameterConstRef target_technology::Param [protected]
Class containing all the parameters.
Definition at line 75 of file target_technology.hpp.
Referenced by CMOS_technology::CMOS_technology(), and CMOS_technology::initialize().
parameters
std::map<std::string, std::string> target_technology::parameters [protected]
Map containing all the parameters of the technology. All the values are stored as strings and they have correctly converted through the get_parameter template.
Definition at line 81 of file target_technology.hpp.
Referenced by xload_technology_parameters().
type
target_t target_technology::type [protected]
Technology type.
Definition at line 78 of file target_technology.hpp.
Referenced by CMOS_technology::CMOS_technology(), FPGA_technology::FPGA_technology(), and get_type().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/target_technology/target_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/target_technology/target_technology.cpp