fu_binding Class Reference
Class managing the functional-unit binding.
#include <fu_binding.hpp>
Public Member Functions
fu_binding (const HLS_managerConstRef HLS_mgr, const unsigned int function_id, const ParameterConstRef parameters)
Constructor.
fu_binding (const fu_binding &original)
fu_binding & operator= (const fu_binding &)=delete
virtual ~fu_binding ()
Destructor.
void bind (const vertex &v, unsigned int id, unsigned int index=INFINITE_UINT)
Binds an operation vertex to a functional unit.
unsigned int get_assign (const vertex &v) const
Returns the functional unit assigned to the vertex.
unsigned int get_assign (const unsigned int statement_index) const
Returns the functional unit assigned to the operation.
unsigned int get_index (const vertex &v) const
Returns the index of functional unit assigned to the vertex.
std::string get_fu_name (vertex const &v) const
Returns the name of the functional unit.
unsigned int get_number (unsigned int unit) const
Returns number of functional unit allocated.
const funit_obj & operator[] (const vertex &v)
Redefinition of the [] operator.
generic_objRef get (const vertex v) const
Returns reference to funit object associated with this vertex.
generic_objRef get (unsigned int name, unsigned int index)
std::list< unsigned int > get_allocation_list () const
Returns the set of allocated unit.
bool is_assigned (const vertex &v) const
return true in case the vertex has been previously assigned
bool is_assigned (const unsigned int statement_index) const
return true in case the operation has been previously assigned
virtual void add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port)
Instance the functional unit inside the structural representation of the datapath.
virtual void manage_extern_global_port (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, structural_objectRef port_in, unsigned int dir, structural_objectRef circuit, unsigned int num)
virtual void manage_memory_ports_parallel_chained (const HLS_managerRef HLSMgr, const structural_managerRef SM, const std::list< structural_objectRef > &memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int &unique_id)
OpVertexSet get_operations (unsigned int unit, unsigned int index) const
Return the operations that are executed by the given functional unit.
void specialise_fu (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef fu_obj, unsigned int fu, const OpVertexSet &operations, unsigned int ar)
Specialize the functional unit based on variables associated with the corresponding operations.
void specialize_memory_unit (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef fu_obj, unsigned int ar, std::string &base_address, unsigned int rangesize, bool is_doubled, bool is_memory_splitted, bool is_sparse_memory, bool is_sds)
Specialize a memory unit.
virtual bool manage_module_ports (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, const structural_objectRef curr_gate, unsigned int num)
virtual void join_merge_split (const structural_managerRef SM, const hlsRef HLS, std::map< structural_objectRef, std::list< structural_objectRef >, jms_sorter > &primary_outs, const structural_objectRef circuit, unsigned int &unique_id)
void set_ports_are_swapped (vertex v, bool condition)
specify if vertex v have or not its ports swapped
bool get_ports_are_swapped (vertex v) const
Check if vertex v has its ports swapped or not.
bool has_resource_sharing () const
return true in case at least one resource is shared
Static Public Member Functions
static fu_bindingRef create_fu_binding (const HLS_managerConstRef _HLSMgr, const unsigned int _function_id, const ParameterConstRef _parameters)
create_fu_binding: factory method for fu_binding
static void manage_memory_ports_chained (const structural_managerRef SM, const std::list< structural_objectRef > &memory_modules, const structural_objectRef circuit)
Manage the connections between memory ports.
static void write_init (const tree_managerConstRef TreeM, tree_nodeRef var_node, tree_nodeRef init_node, std::vector< std::string > &init_file, const memoryRef mem, unsigned int element_precision)
Static Public Attributes
static const unsigned int UNKNOWN = std::numeric_limits<unsigned int>::max()
The value used to identified unknown functional unit.
Protected Member Functions
void update_allocation (unsigned int unit, unsigned int number)
Update number of allocated units.
void fill_array_ref_memory (std::ostream &init_file_a, std::ostream &init_file_b, unsigned int ar, long long int &vec_size, unsigned int &elts_size, const memoryRef mem, unsigned int bram_bitsize, bool is_memory_splitted, bool is_sds, module *fu_module)
fill the memory of the array ref
structural_objectRef add_gate (const HLS_managerRef HLSMgr, const hlsRef HLS, const technology_nodeRef fu, const std::string &name, const OpVertexSet &operations, structural_objectRef clock_port, structural_objectRef reset_port)
Add an instance of the current port.
void check_parametrization (structural_objectRef curr_gate)
check the module parametrization
void kill_proxy_memory_units (std::map< unsigned int, unsigned int > &memory_units, structural_objectRef curr_gate, std::map< unsigned int, std::list< structural_objectRef >> &var_call_sites_rel, std::map< unsigned int, unsigned int > &reverse_memory_units)
fix port properties for proxy memory ports
void kill_proxy_function_units (std::map< unsigned int, std::string > &wrapped_units, structural_objectRef curr_gate, std::map< std::string, std::list< structural_objectRef >> &fun_call_sites_rel, std::map< std::string, unsigned int > &reverse_wrapped_units)
void manage_killing_memory_proxies (std::map< unsigned int, structural_objectRef > &mem_obj, std::map< unsigned int, unsigned int > &reverse_memory_units, std::map< unsigned int, std::list< structural_objectRef >> &var_call_sites_rel, const structural_managerRef SM, const hlsRef HLS, unsigned int &_unique_id)
connect proxies with storage components
void manage_killing_function_proxies (std::map< unsigned int, structural_objectRef > &fun_obj, std::map< std::string, unsigned int > &reverse_function_units, std::map< std::string, std::list< structural_objectRef >> &fun_call_sites_rel, const structural_managerRef SM, const hlsRef HLS, unsigned int &_unique_id)
Protected Attributes
std::map< unsigned int, unsigned int > allocation_map
map between functional unit id and number of units allocated
std::map< std::pair< unsigned int, unsigned int >, generic_objRef > unique_table
map between unit and allocated objects
std::map< std::pair< unsigned int, unsigned int >, OpVertexSet > operations
reverse map that associated each functional unit with the set of operations that are executed
std::map< unsigned int, generic_objRef > op_binding
operation binding
AllocationInformationRef allocation_information
allocation manager. Used to retrieve the string name of the functional units.
const tree_managerConstRef TreeM
information about the tree datastructure
const OpGraphConstRef op_graph
The operation graph.
CustomOrderedSet< vertex > ports_are_swapped
port assignment: ports are swapped predicate
const ParameterConstRef parameters
The set of input parameters.
int debug_level
The debug level.
bool has_resource_sharing_p
useful to know for automatic pipelining
Detailed Description
Class managing the functional-unit binding.
It stores the functional-unit binding, that is, the mapping of operations in the behavioral description onto the set of allocated functional units.
Definition at line 90 of file fu_binding.hpp.
Constructor & Destructor Documentation
fu_binding() [1/2]
fu_binding::fu_binding (const HLS_managerConstRef HLS_mgr, const unsigned int function_id, const ParameterConstRef parameters)
Constructor.
Parameters
HLS_mgr is the HLS manager
function_id is the index of the function
parameters is the set of input parameters
Definition at line 110 of file fu_binding.cpp.
Referenced by create_fu_binding().
fu_binding() [2/2]
fu_binding::fu_binding (const fu_binding & original)
Definition at line 120 of file fu_binding.cpp.
References ~fu_binding().
 fu_binding()
fu_binding::~fu_binding () [virtual], [default]
Destructor.
Referenced by fu_binding().
Member Function Documentation
add_gate()
structural_objectRef fu_binding::add_gate (const HLS_managerRef HLSMgr, const hlsRef HLS, const technology_nodeRef fu, const std::string & name, const OpVertexSet & operations, structural_objectRef clock_port, structural_objectRef reset_port) [protected]
Add an instance of the current port.
creating structural_manager starting from technology_node
connecting clock and reset ports, if any
Definition at line 242 of file fu_binding.cpp.
References structural_manager::add_connection(), FunctionBehavior::CFG, FunctionBehavior::CGetOpGraph(), CLOCK_PORT_NAME, structural_object::copy(), hls::datapath, debug_level, structural_object::find_member(), hls::functionId, structural_manager::get_circ(), GET_NAME, hls::HLS_T, port_o_K, RESET_PORT_NAME, structural_object::set_id(), and THROW_ASSERT.
Referenced by add_to_SM().
add_to_SM()
void fu_binding::add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port) [virtual]
Instance the functional unit inside the structural representation of the datapath.
unique id identifier
initialize resource sharing to false
add the MEMCPY_STD component when parameters has to be copied into the local store
component specialization
propagate memory parameters if contained into the module to be instantiated
rename proxy ports
propagate memory parameters if contained into the module to be instantiated
rename back all the memory proxies ports
rename back all the function proxies ports
Reimplemented in ParallelMemoryFuBinding, and fu_binding_cs.
Definition at line 492 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_constant(), add_gate(), memory::add_memory_parameter(), structural_manager::add_port(), structural_manager::add_sign(), allocation_information, BUILTIN_WAIT_CALL, FunctionBehavior::CGetBehavioralHelper(), OpGraph::CGetOpNodeInfo(), CHANNELS_TYPE_MEM_ACC_N1, CHANNELS_TYPE_MEM_ACC_NN, check_parametrization(), CLOCK_PORT_NAME, CONSTANT_STD, hls::control_flow_checker, structural_object::copy(), hls::datapath, debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, DONE_PORT_NAME_CFC, structural_object::find_member(), flipflop_AR, flipflop_SR, hls::functionId, get_allocation_list(), structural_manager::get_circ(), AllocationInformation::get_fu(), AllocationInformation::get_fu_name(), structural_object::get_id(), structural_object::get_kind(), AllocationInformation::get_memory_units(), get_number(), AllocationInformation::get_number_channels(), get_operations(), BehavioralHelper::get_parameters(), conn_binding::get_port(), AllocationInformation::get_proxy_function_units(), AllocationInformation::get_proxy_memory_units(), AllocationInformation::get_proxy_memory_var(), AllocationInformation::get_proxy_wrapped_units(), AllocationInformation::get_string_name(), tree_helper::get_type_index(), structural_object::get_typeRef(), has_resource_sharing_p, AllocationInformation::has_to_be_synthetized(), hls::HLS_T, conn_binding::IN, port_o::IN, INDENT_DBG_MEX, INDENT_OUT_MEX, reg_binding::is_all_regs_without_enable(), AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_direct_proxy_memory_unit(), AllocationInformation::is_indirect_access_memory_unit(), AllocationInformation::is_memory_unit(), AllocationInformation::is_proxy_memory_unit(), AllocationInformation::is_return(), kill_proxy_function_units(), kill_proxy_memory_units(), LIBRARY_STD, LIBRARY_STD_FU, manage_killing_function_proxies(), manage_killing_memory_proxies(), manage_memory_ports_chained(), manage_memory_ports_parallel_chained(), manage_module_ports(), max(), MEM_ACC_NN, MEMCPY_STD, MEMORY_TYPE_ASYNCHRONOUS, MEMORY_TYPE_SYNCHRONOUS_SDS, MEMORY_TYPE_SYNCHRONOUS_SDS_BUS, MEMORY_TYPE_SYNCHRONOUS_UNALIGNED, MEMSTORE_STD, MEMSTORE_STDN, tree_helper::name_function(), NEXT_STATE_PORT_NAME, tree_helper::normalized_ID(), NumberToBinaryString(), op_graph, operations, hls::output_level, OUTPUT_LEVEL_MINIMUM, hls::Param, parameters, port_o_K, port_vector_o_K, PRESENT_STATE_PORT_NAME, PRINT_DBG_MEX, memory::propagate_memory_parameters(), PROXY_PREFIX, hls::Rconn, hls::registered_inputs, RESET_PORT_NAME, port_o::resize_busport(), RETURN_PORT_NAME, hls::Rfu, hls::Rreg, structural_object::set_id(), structural_object::SetParameter(), tree_helper::size(), specialise_fu(), specialize_memory_unit(), START_PORT_NAME, START_PORT_NAME_CFC, STD_GET_SIZE, STR, THROW_ASSERT, THROW_ERROR, TreeM, structural_object::type_resize(), VHDL, and WORK_LIBRARY.
Referenced by fu_binding_cs::add_to_SM(), ParallelMemoryFuBinding::add_to_SM(), and classic_datapath::InternalExec().
bind()
void fu_binding::bind (const vertex & v, unsigned int id, unsigned int index = INFINITE_UINT)
Binds an operation vertex to a functional unit.
The functional unit is identified by an id and its index
Parameters
v is operation vertex
id is the identifier of the functional unit
index is the functional unit index
Definition at line 158 of file fu_binding.cpp.
References allocation_information, OpGraph::CGetOpNodeInfo(), AllocationInformation::get_string_name(), index, INFINITE_UINT, op_binding, op_graph, operations, STR, unique_table, and update_allocation().
Referenced by parametric_list_based::exec(), unique_binding::InternalExec(), easy_module_binding::InternalExec(), SDCScheduling::InternalExec(), cdfc_module_binding::InternalExec(), and hls::xload().
check_parametrization()
void fu_binding::check_parametrization (structural_objectRef curr_gate) [protected]
check the module parametrization
Definition at line 1078 of file fu_binding.cpp.
References structural_object::ExistsParameter(), structural_object::find_member(), NP_functionality::get_NP_functionality(), GET_TYPE_NAME, port_o_K, port_vector_o_K, and THROW_ASSERT.
Referenced by add_to_SM().
create_fu_binding()
fu_bindingRef fu_binding::create_fu_binding (const HLS_managerConstRef _HLSMgr, const unsigned int _function_id, const ParameterConstRef _parameters) [static]
create_fu_binding: factory method for fu_binding
Parameters
_HLSMgr
_function_id
_parameters
Returns
the correct class of fu_binding
Definition at line 135 of file fu_binding.cpp.
References fu_binding().
Referenced by fu_binding_creator::Initialize(), easy_module_binding::Initialize(), Scheduling::Initialize(), and cdfc_module_binding::InternalExec().
fill_array_ref_memory()
void fu_binding::fill_array_ref_memory (std::ostream & init_file_a, std::ostream & init_file_b, unsigned int ar, long long int & vec_size, unsigned int & elts_size, const memoryRef mem, unsigned int bram_bitsize, bool is_memory_splitted, bool is_sds, module * fu_module) [protected]
fill the memory of the array ref
Parameters
TreeM is the tree_manager
init_file_a is the file where the data is written (all data stored in this file in case is_memory_splitted is false
initi_file_b is the file where the data is written (only the odd elements are store in this file and only if is_memory_splitted is true
ar is the array ref variable declaration
vec_size is the number of the element of the array
elts_size is the element size in bits
bram_bitsise is value of BRAM_BITSIZE parameter
is_memory_splitted is true when the allocated memory is splitted into two sets of BRAMs
Definition at line 1961 of file fu_binding.cpp.
References counter, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_helper::get_array_dim_and_bitsize(), memory::get_bram_bitsize(), memory::get_bus_data_bitsize(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), tree_helper::GetElements(), INDENT_DBG_MEX, tree_helper::is_an_array(), memory::is_private_memory(), parameters, structural_object::SetParameter(), tree_helper::size(), tree_helper::Size(), STR, THROW_ASSERT, THROW_ERROR, TreeM, and write_init().
Referenced by specialize_memory_unit().
get() [1/2]
generic_objRef fu_binding::get (const vertex v) const
Returns reference to funit object associated with this vertex.
Parameters
v is the given vertex
Returns
the associated reference
Definition at line 2893 of file fu_binding.cpp.
References OpGraph::CGetOpNodeInfo(), op_binding, and op_graph.
Referenced by conn_binding::add_command_ports(), mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), and fsm_controller::create_state_machine().
get() [2/2]
generic_objRef fu_binding::get (unsigned int name, unsigned int index) [inline]
Definition at line 277 of file fu_binding.hpp.
References index.
get_allocation_list()
std::list< unsigned int > fu_binding::get_allocation_list () const
Returns the set of allocated unit.
Returns
the set of allocated unit
Definition at line 201 of file fu_binding.cpp.
References allocation_map.
Referenced by ParallelMemoryFuBinding::add_to_SM(), add_to_SM(), and mux_connection_binding::create_connections().
get_assign() [1/2]
unsigned int fu_binding::get_assign (const vertex & v) const
Returns the functional unit assigned to the vertex.
Parameters
v is the considered vertex.
Returns
the functional unit assigned with the vertex.
Definition at line 218 of file fu_binding.cpp.
References OpGraph::CGetOpNodeInfo(), and op_graph.
Referenced by conn_binding::add_command_ports(), mux_connection_binding::address_precision(), Scheduling::anticipate_operations(), parametric_list_based::check_direct_operation_chaining(), parametric_list_based::check_non_direct_operation_chaining(), BB_based_stg::compute_EPP_edge_increments(), parametric_list_based::compute_starting_ending_time_alap(), parametric_list_based::compute_starting_ending_time_asap(), mux_connection_binding::create_connections(), fsm_controller::create_state_machine(), parametric_list_based::do_balanced_scheduling(), parametric_list_based::do_balanced_scheduling1(), estimate_muxes(), parametric_list_based::exec(), get_fu_name(), module_binding_check< vertex_type >::initialize_structures(), unique_binding::InternalExec(), BB_based_stg::InternalExec(), easy_module_binding::InternalExec(), port_swapping::InternalExec(), cdfc_module_binding::InternalExec(), BB_based_stg::optimize_cycles(), BB_based_stg::res_const_operation(), mux_connection_binding::swap_p(), parametric_list_based::update_starting_ending_time(), parametric_list_based::update_starting_ending_time_asap(), and hls::xwrite().
get_assign() [2/2]
unsigned int fu_binding::get_assign (const unsigned int statement_index) const
Returns the functional unit assigned to the operation.
Parameters
statement_index is the considered operation.
Returns
the functional unit assigned to the operation
Definition at line 224 of file fu_binding.cpp.
References op_binding, THROW_ASSERT, and TreeM.
get_fu_name()
std::string fu_binding::get_fu_name (vertex const & v) const
Returns the name of the functional unit.
Parameters
v is the considered vertex.
Returns
the name of the functional unit assigned to the vertex.
Definition at line 231 of file fu_binding.cpp.
References allocation_information, get_assign(), and AllocationInformation::get_string_name().
Referenced by Schedule::print().
get_index()
unsigned int fu_binding::get_index (const vertex & v) const
Returns the index of functional unit assigned to the vertex.
Parameters
v is the considered vertex.
Returns
the index of the functional unit assigned to the vertex.
Definition at line 236 of file fu_binding.cpp.
References OpGraph::CGetOpNodeInfo(), op_binding, and op_graph.
Referenced by mux_connection_binding::create_connections(), estimate_muxes(), module_binding_check< vertex_type >::initialize_structures(), unique_binding::InternalExec(), easy_module_binding::InternalExec(), port_swapping::InternalExec(), cdfc_module_binding::InternalExec(), mux_connection_binding::swap_p(), and hls::xwrite().
get_number()
unsigned int fu_binding::get_number (unsigned int unit) const [inline]
Returns number of functional unit allocated.
Parameters
unit is the identifier associated to functional unit
Returns
the number of functional units allocated.
Definition at line 251 of file fu_binding.hpp.
Referenced by add_to_SM(), and mux_connection_binding::create_connections().
get_operations()
OpVertexSet fu_binding::get_operations (unsigned int unit, unsigned int index) const
Return the operations that are executed by the given functional unit.
Definition at line 174 of file fu_binding.cpp.
References op_graph, and operations.
Referenced by add_to_SM().
get_ports_are_swapped()
bool fu_binding::get_ports_are_swapped (vertex v) const [inline]
Check if vertex v has its ports swapped or not.
Parameters
v is the vertex
Returns
true when ports of v are swapped, false otherwise
Definition at line 348 of file fu_binding.hpp.
Referenced by mux_connection_binding::create_connections(), and estimate_muxes().
has_resource_sharing()
bool fu_binding::has_resource_sharing () const [inline]
return true in case at least one resource is shared
Definition at line 354 of file fu_binding.hpp.
is_assigned() [1/2]
bool fu_binding::is_assigned (const vertex & v) const
return true in case the vertex has been previously assigned
Parameters
v
Returns
true in case v has been previously assigned
Definition at line 190 of file fu_binding.cpp.
References OpGraph::CGetOpNodeInfo(), and op_graph.
Referenced by module_binding_check< vertex_type >::initialize_structures().
is_assigned() [2/2]
bool fu_binding::is_assigned (const unsigned int statement_index) const
return true in case the operation has been previously assigned
Parameters
statement_index
Returns
true in case operation has been previously assigned
Definition at line 196 of file fu_binding.cpp.
References op_binding.
join_merge_split()
void fu_binding::join_merge_split (const structural_managerRef SM, const hlsRef HLS, std::map< structural_objectRef, std::list< structural_objectRef >, jms_sorter > & primary_outs, const structural_objectRef circuit, unsigned int & unique_id) [virtual]
Definition at line 1194 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), structural_manager::add_sign_vector(), structural_type_descriptor::BOOL, structural_type_descriptor::copy(), structural_object::get_typeRef(), hls::HLS_T, port_vector_o_K, port_o::resize_std_port(), STD_GET_SIZE, STR, structural_type_descriptor::type, structural_object::type_resize(), and structural_type_descriptor::VECTOR_BOOL.
Referenced by manage_killing_function_proxies(), manage_killing_memory_proxies(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), and manage_memory_ports_parallel_chained().
kill_proxy_function_units()
void fu_binding::kill_proxy_function_units (std::map< unsigned int, std::string > & wrapped_units, structural_objectRef curr_gate, std::map< std::string, std::list< structural_objectRef >> & fun_call_sites_rel, std::map< std::string, unsigned int > & reverse_wrapped_units) [protected]
compute the set of killing functions
Definition at line 318 of file fu_binding.cpp.
References structural_object::get_id(), and PROXY_PREFIX.
Referenced by add_to_SM().
kill_proxy_memory_units()
void fu_binding::kill_proxy_memory_units (std::map< unsigned int, unsigned int > & memory_units, structural_objectRef curr_gate, std::map< unsigned int, std::list< structural_objectRef >> & var_call_sites_rel, std::map< unsigned int, unsigned int > & reverse_memory_units) [protected]
fix port properties for proxy memory ports
Parameters
memory_units is the list o memory ports
curr_gate is the current gate
var_call_sites_rel put into relation proxied variables and modules referring to such variables
compute the set of killing vars
Definition at line 286 of file fu_binding.cpp.
References structural_object::find_member(), port_o_K, and STR.
Referenced by add_to_SM().
manage_extern_global_port()
void fu_binding::manage_extern_global_port (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, structural_objectRef port_in, unsigned int dir, structural_objectRef circuit, unsigned int num) [virtual]
Reimplemented in fu_binding_cs.
Definition at line 1363 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), structural_manager::add_port_vector(), structural_manager::change_port_direction(), structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_typeRef(), getFunctionType(), port_vector_o_K, port_o::resize_std_port(), STD_GET_SIZE, and THROW_ASSERT.
Referenced by ParallelMemoryFuBinding::add_to_SM(), fu_binding_cs::manage_extern_global_port(), and manage_module_ports().
manage_killing_function_proxies()
void fu_binding::manage_killing_function_proxies (std::map< unsigned int, structural_objectRef > & fun_obj, std::map< std::string, unsigned int > & reverse_function_units, std::map< std::string, std::list< structural_objectRef >> & fun_call_sites_rel, const structural_managerRef SM, const hlsRef HLS, unsigned int & _unique_id) [protected]
Definition at line 430 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), structural_manager::add_sign_vector(), structural_object::find_member(), fun(), structural_manager::get_circ(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_typeRef(), join_merge_split(), port_o_K, port_vector_o_K, PROXY_PREFIX, and THROW_ASSERT.
Referenced by add_to_SM().
manage_killing_memory_proxies()
void fu_binding::manage_killing_memory_proxies (std::map< unsigned int, structural_objectRef > & mem_obj, std::map< unsigned int, unsigned int > & reverse_memory_units, std::map< unsigned int, std::list< structural_objectRef >> & var_call_sites_rel, const structural_managerRef SM, const hlsRef HLS, unsigned int & _unique_id) [protected]
connect proxies with storage components
Parameters
mem_obj is the relation between fu_id and structural objects
reverse_memory_units is the relation between var and functional units
var_call_sites_rel is the relation between var and call sites having a proxy as module parameter
SM is the structural manager
Definition at line 367 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), structural_manager::add_sign_vector(), structural_object::find_member(), structural_manager::get_circ(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_typeRef(), join_merge_split(), port_o_K, port_vector_o_K, STR, and THROW_ASSERT.
Referenced by add_to_SM().
manage_memory_ports_chained()
void fu_binding::manage_memory_ports_chained (const structural_managerRef SM, const std::list< structural_objectRef > & memory_modules, const structural_objectRef circuit) [static]
Manage the connections between memory ports.
trimmed away the `?in_`prefix
trimmed away the `?out_`prefix
Definition at line 1121 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), structural_manager::add_port_vector(), structural_manager::add_sign(), structural_manager::add_sign_vector(), structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, port_o::OUT, port_vector_o_K, and THROW_ASSERT.
Referenced by add_to_SM().
manage_memory_ports_parallel_chained()
void fu_binding::manage_memory_ports_parallel_chained (const HLS_managerRef HLSMgr, const structural_managerRef SM, const std::list< structural_objectRef > & memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int & unique_id) [virtual]
Reimplemented in fu_binding_cs.
Definition at line 1310 of file fu_binding.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), structural_manager::add_port_vector(), structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, join_merge_split(), port_o::OUT, port_vector_o_K, and THROW_ASSERT.
Referenced by add_to_SM(), TopEntityMemoryMapped::InternalExec(), and fu_binding_cs::manage_memory_ports_parallel_chained().
manage_module_ports()
bool fu_binding::manage_module_ports (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, const structural_objectRef curr_gate, unsigned int num) [virtual]
creating extern IN port on datapath starting from extern ports on module
creating extern OUT port on datapath starting from extern ports on module
creating extern IO port on datapath starting from extern ports on module
Reimplemented in ParallelMemoryFuBinding.
Definition at line 1092 of file fu_binding.cpp.
References structural_manager::get_circ(), port_o::IN, port_o::IO, manage_extern_global_port(), and port_o::OUT.
Referenced by add_to_SM(), TopEntityMemoryMapped::insertMemoryMappedRegister(), TopEntityMemoryMapped::insertStartDoneLogic(), TopEntityMemoryMapped::insertStatusRegister(), TopEntityMemoryMapped::InternalExec(), and ParallelMemoryFuBinding::manage_module_ports().
operator=()
fu_binding& fu_binding::operator= (const fu_binding &) [delete]
operator[]()
const funit_obj & fu_binding::operator[] (const vertex & v)
Redefinition of the [] operator.
It is necessary because segfaults happen when the vertex is not into the map and so the object has not been created yet. This operator can be used only to read information since it returns a constant object. It's necessary because a direct manipulation of the object can create non-consistent data objects.
Parameters
v is the vertex you want to get the object
Returns
the constant object related to vertex
Definition at line 183 of file fu_binding.cpp.
References OpGraph::CGetOpNodeInfo(), op_binding, op_graph, and THROW_ASSERT.
set_ports_are_swapped()
void fu_binding::set_ports_are_swapped (vertex v, bool condition)
specify if vertex v have or not its ports swapped
Parameters
v is the vertex
condition is true when ports are swapped, false otherwise
Definition at line 2885 of file fu_binding.cpp.
References ports_are_swapped.
Referenced by port_swapping::InternalExec().
specialise_fu()
void fu_binding::specialise_fu (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef fu_obj, unsigned int fu, const OpVertexSet & operations, unsigned int ar)
Specialize the functional unit based on variables associated with the corresponding operations.
Round up to the next highest power of 2
specializing MEMORY_STD ports
check for precision parameter
Definition at line 1439 of file fu_binding.cpp.
References tree_helper::accessed_greatest_bitsize(), ALL_BRAM, allocation_information, test_panda::args, structural_type_descriptor::BOOL, BUILTIN_WAIT_CALL, FunctionBehavior::CFG, FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), CLOCK_PORT_NAME, convert_to_binary(), debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, NP_functionality::exist_NP_functionality(), structural_object::ExistsParameter(), EXT_PIPELINED_BRAM, FLOAT_EXPR, NP_functionality::FLOPOCO_PROVIDED, hls::functionId, tree_helper::get_base_index(), AllocationInformation::get_fu(), AllocationInformation::get_fu_name(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), structural_object::get_kind(), NP_functionality::get_library_parameters(), GET_NAME, GET_NODE, module::get_NP_functionality(), AllocationInformation::get_number_channels(), module::get_out_port(), module::get_out_port_size(), structural_object::get_path(), GET_TYPE, tree_helper::get_type_index(), GET_TYPE_NAME, structural_object::get_typeRef(), tree_helper::GetElements(), getFunctionType(), structural_object::GetParameter(), hls::HLS_T, INDENT_DBG_MEX, index, INTERN_UNALIGNED, tree_helper::is_a_misaligned_vector(), tree_helper::is_a_vector(), AllocationInformation::is_direct_access_memory_unit(), FunctionBehavior::is_variable_mem(), max(), min, MULTI_READ_COND_STD, gimple_assign::op1, hls::Param, parameters, PIPE_PARAMETER, port_vector_o_K, PRINT_DBG_MEX, PROXY_LIBRARY, RESET_PORT_NAME, port_o::resize_busport(), port_o::resize_std_port(), structural_object::SetParameter(), tree_helper::size(), START_PORT_NAME, STR, THROW_ASSERT, THROW_ERROR, ToString(), TreeM, structural_type_descriptor::type, TYPE_LOAD, TYPE_STORE, integer_cst::value, and WORK_LIBRARY.
Referenced by add_to_SM().
specialize_memory_unit()
void fu_binding::specialize_memory_unit (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef fu_obj, unsigned int ar, std::string & base_address, unsigned int rangesize, bool is_doubled, bool is_memory_splitted, bool is_sparse_memory, bool is_sds)
Specialize a memory unit.
base address specialization
array ref initialization
specialize the number of elements in the array
Definition at line 1906 of file fu_binding.cpp.
References memory::add_memory_parameter(), hls::datapath, fill_array_ref_memory(), hls::functionId, parameters, STR, and THROW_ASSERT.
Referenced by add_to_SM().
update_allocation()
void fu_binding::update_allocation (unsigned int unit, unsigned int number) [protected]
Update number of allocated units.
It takes effect only if new number is greather than stored one
Parameters
unit is the identifier associated to functional unit
number is the new number of allocated units
Definition at line 212 of file fu_binding.cpp.
References allocation_map.
Referenced by bind().
write_init()
void fu_binding::write_init (const tree_managerConstRef TreeM, tree_nodeRef var_node, tree_nodeRef init_node, std::vector< std::string > & init_file, const memoryRef mem, unsigned int element_precision) [static]
check if designated initializers are really used
check if padding is needed
add padding
check if padding is needed
add padding
check if padding is needed
add padding
Definition at line 2185 of file fu_binding.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, convert_fp_to_string(), tree_helper::get_array_dim_and_bitsize(), memory::get_base_address(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_index(), tree_helper::get_type_node(), memory::has_base_address(), index, tree_node::index, max(), min, tree_helper::size(), STR, THROW_ASSERT, THROW_ERROR, and tree_node::ToString().
Referenced by fill_array_ref_memory(), and TestbenchGenerationBaseStep::print_var_init().
Field Documentation
allocation_information
AllocationInformationRef fu_binding::allocation_information [protected]
allocation manager. Used to retrieve the string name of the functional units.
Definition at line 106 of file fu_binding.hpp.
Referenced by ParallelMemoryFuBinding::add_to_SM(), add_to_SM(), bind(), get_fu_name(), and specialise_fu().
allocation_map
std::map<unsigned int, unsigned int> fu_binding::allocation_map [protected]
map between functional unit id and number of units allocated
Definition at line 94 of file fu_binding.hpp.
Referenced by get_allocation_list(), and update_allocation().
debug_level
int fu_binding::debug_level [protected]
The debug level.
Definition at line 121 of file fu_binding.hpp.
Referenced by add_gate(), ParallelMemoryFuBinding::add_to_SM(), add_to_SM(), fu_binding_cs::connect_selector_kernel(), fill_array_ref_memory(), fu_binding_cs::fu_binding_cs(), fu_binding_cs::instantiate_component_kernel(), fu_binding_cs::manage_memory_port_hierarchical(), fu_binding_cs::manage_memory_port_kernel(), ParallelMemoryFuBinding::ParallelMemoryFuBinding(), and specialise_fu().
has_resource_sharing_p
bool fu_binding::has_resource_sharing_p [protected]
useful to know for automatic pipelining
Definition at line 124 of file fu_binding.hpp.
Referenced by add_to_SM().
op_binding
std::map<unsigned int, generic_objRef> fu_binding::op_binding [protected]
operation binding
Definition at line 103 of file fu_binding.hpp.
Referenced by bind(), get(), get_assign(), get_index(), is_assigned(), and operator[]().
op_graph
const OpGraphConstRef fu_binding::op_graph [protected]
The operation graph.
Definition at line 112 of file fu_binding.hpp.
Referenced by ParallelMemoryFuBinding::add_to_SM(), add_to_SM(), bind(), get(), get_assign(), get_index(), get_operations(), is_assigned(), and operator[]().
operations
std::map<std::pair<unsigned int, unsigned int>, OpVertexSet> fu_binding::operations [protected]
reverse map that associated each functional unit with the set of operations that are executed
Definition at line 100 of file fu_binding.hpp.
Referenced by add_to_SM(), bind(), and get_operations().
parameters
const ParameterConstRef fu_binding::parameters [protected]
The set of input parameters.
Definition at line 118 of file fu_binding.hpp.
Referenced by ParallelMemoryFuBinding::add_to_SM(), add_to_SM(), fu_binding_cs::connect_selector_kernel(), fill_array_ref_memory(), fu_binding_cs::instantiate_component_kernel(), fu_binding_cs::manage_memory_port_hierarchical(), ParallelMemoryFuBinding::ParallelMemoryFuBinding(), fu_binding_cs::set_atomic_memory_parameter(), specialise_fu(), and specialize_memory_unit().
ports_are_swapped
CustomOrderedSet<vertex> fu_binding::ports_are_swapped [protected]
port assignment: ports are swapped predicate
Definition at line 115 of file fu_binding.hpp.
Referenced by set_ports_are_swapped().
TreeM
const tree_managerConstRef fu_binding::TreeM [protected]
information about the tree datastructure
Definition at line 109 of file fu_binding.hpp.
Referenced by add_to_SM(), fill_array_ref_memory(), get_assign(), and specialise_fu().
unique_table
std::map<std::pair<unsigned int, unsigned int>, generic_objRef> fu_binding::unique_table [protected]
map between unit and allocated objects
Definition at line 97 of file fu_binding.hpp.
Referenced by bind().
UNKNOWN
const unsigned int fu_binding::UNKNOWN = std::numeric_limits<unsigned int>::max() [static]
The value used to identified unknown functional unit.
. include
design_flows/backend/ToHDL include HLS/module_allocation STD include STL includes utility include
Definition at line 181 of file fu_binding.hpp.
Referenced by SDCScheduling::AddDelayConstraints(), AllocationInformation::CanBeChained(), AllocationInformation::CanBeMerged(), Schedule::CanBeMoved(), Schedule::ComputeCriticalPath(), Schedule::EvaluateCondsMerging(), Schedule::EvaluateMultiWayIfsMerging(), AllocationInformation::GetConnectionTime(), AllocationInformation::GetTimeLatency(), AllocationInformation::GetZeroDistanceOperations(), CondExprRestructuring::InternalExec(), commutative_expr_restructuring::InternalExec(), and Schedule::UpdateTime().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/fu_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/fu_binding.cpp