VarDeclFix Class Reference
Pre-analysis step.
#include <var_decl_fix.hpp>
Public Member Functions
VarDeclFix (const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters, const FrontendFlowStepType frontend_flow_step_type=VAR_DECL_FIX)
Constructor.
~VarDeclFix () override
Destructor.
DesignFlowStep_Status InternalExec () override
Fixes the var_decl duplication.
Protected Member Functions
virtual const std::string Normalize (const std::string &identifier) const
Return the normalized identifier; in this class it is the identifier itself.
void recursive_examinate (const tree_nodeRef &tn)
Recursive examinate tree node.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
CustomUnorderedSet< unsigned int > already_examinated_decls
Already considered decl_node.
CustomUnorderedSet< std::string > already_examinated_names
Already found variable and parameter names.
CustomUnorderedSet< std::string > already_examinated_type_names
Already found type names.
CustomUnorderedSet< unsigned int > already_visited_ae
Already visited address expression (used to avoid infite recursion)
Additional Inherited Members
Detailed Description
Pre-analysis step.
It transforms the raw intermediate representation removing var_decl duplication: two var_decls with the same variable name in the same function.
Definition at line 65 of file var_decl_fix.hpp.
Constructor & Destructor Documentation
VarDeclFix()
VarDeclFix::VarDeclFix (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters, const FrontendFlowStepType _frontend_flow_step_type = VAR_DECL_FIX)
Constructor.
Autoheader include.
Parameters
AppM is the application manager
fun_id is the function index
design_flow_manager is the design flow manager
parameters is the set of input parameters
frontend_flow_step_type is the type of step; it is different for subclasses
Header include Behavior include Parameter include parser/treegcc include STD include STL include Tree include Utility include
Definition at line 82 of file var_decl_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~VarDeclFix().
 VarDeclFix()
VarDeclFix::~VarDeclFix () [override], [default]
Destructor.
Referenced by VarDeclFix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > VarDeclFix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 90 of file var_decl_fix.cpp.
References CHECK_SYSTEM_TYPE, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status VarDeclFix::InternalExec () [override], [virtual]
Fixes the var_decl duplication.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 120 of file var_decl_fix.cpp.
References FrontendFlowStep::AppM, test_panda::arg, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::GetTreeNode(), recursive_examinate(), sl, and SUCCESS.
Referenced by HDLVarDeclFix::InternalExec().
Normalize()
const std::string VarDeclFix::Normalize (const std::string & identifier) const [protected], [virtual]
Return the normalized identifier; in this class it is the identifier itself.
Subclasses can specialize it
Parameters
identifier is the identifier to be normalized
Returns
the normalized identifier
Reimplemented in HDLVarDeclFix.
Definition at line 507 of file var_decl_fix.cpp.
Referenced by recursive_examinate().
recursive_examinate()
void VarDeclFix::recursive_examinate (const tree_nodeRef & tn) [protected]
Recursive examinate tree node.
create a new identifier_node tree node
create a new identifier_node tree node
create a new identifier_node tree node
Definition at line 144 of file var_decl_fix.cpp.
References already_examinated_decls, already_examinated_names, already_examinated_type_names, already_visited_ae, FrontendFlowStep::AppM, test_panda::arg, test_panda::args, call_expr::args, gimple_call::args, target_mem_ref::base, target_mem_ref461::base, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, target_mem_ref::idx, target_mem_ref461::idx, target_mem_ref461::idx2, INDENT_DBG_MEX, constructor::list_of_idx_valu, NODE_NOT_YET_SUPPORTED_EC, Normalize(), tree_helper::normalized_ID(), unary_expr::op, gimple_return::op, gimple_while::op0, binary_expr::op0, ternary_expr::op0, quaternary_expr::op0, gimple_cond::op0, gimple_switch::op0, gimple_for::op1, binary_expr::op1, ternary_expr::op1, quaternary_expr::op1, gimple_for::op2, ternary_expr::op2, quaternary_expr::op2, quaternary_expr::op3, PRINT_DBG_MEX, STR, target_mem_ref::symbol, THROW_ASSERT, THROW_ERROR_CODE, THROW_UNREACHABLE, TOK, TOK_STRG, tree_node::ToString(), and ssa_name::var.
Referenced by HDLVarDeclFix::InternalExec(), and InternalExec().
Field Documentation
already_examinated_decls
CustomUnorderedSet<unsigned int> VarDeclFix::already_examinated_decls [protected]
Already considered decl_node.
Definition at line 69 of file var_decl_fix.hpp.
Referenced by recursive_examinate().
already_examinated_names
CustomUnorderedSet<std::string> VarDeclFix::already_examinated_names [protected]
Already found variable and parameter names.
Definition at line 72 of file var_decl_fix.hpp.
Referenced by HDLVarDeclFix::InternalExec(), and recursive_examinate().
already_examinated_type_names
CustomUnorderedSet<std::string> VarDeclFix::already_examinated_type_names [protected]
Already found type names.
Definition at line 75 of file var_decl_fix.hpp.
Referenced by recursive_examinate().
already_visited_ae
CustomUnorderedSet<unsigned int> VarDeclFix::already_visited_ae [protected]
Already visited address expression (used to avoid infite recursion)
Definition at line 78 of file var_decl_fix.hpp.
Referenced by recursive_examinate().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/var_decl_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/var_decl_fix.cpp