vcd_parser Class Reference
#include <vcd_parser.hpp>
Public Types
typedef UnorderedMapStd< std::string, UnorderedSetStdStable< std::string > > vcd_filter_t
this is the type used to select which signals have to be filtered during parsing.
typedef UnorderedMapStd< std::string, CustomUnorderedMapStable< std::string, std::list< sig_variation > > > vcd_trace_t
this type is the result of a parse.
Public Member Functions
vcd_parser (const ParameterConstRef &params)
constructor
vcd_trace_t parse_vcd (const std::string &vcd_file_to_parse, const vcd_parser::vcd_filter_t &selected_signals)
parses a file selecting only a predefined set of signals.
Private Member Functions
int vcd_parse_sim ()
Parses all lines that occur in the simulation portion of the VCD file.
int vcd_parse_def ()
int vcd_parse_skip_to_end ()
Parses specified file until $end keyword is seen, ignoring all text inbetween.
int vcd_parse_def_var (const std::string &scope)
Parses definition $var keyword line until $end keyword is seen.
void vcd_push_def_scope (std::stack< std::string > &scope)
Parses definition $scope keyword line until $end keyword is seen.
void vcd_pop_def_scope (std::stack< std::string > &scope)
int vcd_parse_sim_vector (char *value, unsigned long timestamp)
Reads the next token from the file and calls the appropriate fuction.
int vcd_parse_sim_real (char *value, unsigned long timestamp)
Reads the next token from the file and calls the appropriate function.
bool check_filter_list (const std::string &scope_str, const std::string &name)
Checks if a signal is to be monitored.
void vcd_add_signal (const std::string &scope, const std::string &name, const std::string &vcd_id, const std::string &type, const bool isvect, const unsigned int msb, const unsigned int lsb)
insert a signal in the maps needed for selecting the vcd data and for relating it back to HDL and C variables
bool check_signals () const
check if the port vectors declarations are consistent
void init_variations ()
void add_variation (const std::string &id, const std::string &value, unsigned long long ts)
Private Attributes
const int debug_level
Debug Level.
std::string vcd_filename
name of the vcd file to parse
FILE * vcd_fp
file pointer to the vcd file to parse
unsigned long sig_n
total number of signals in the vcd file
vcd_filter_t filtered_signals
set of signals to select from the vcd file.
vcd_trace_t parse_result
holds the parsed vcd trace during the parsing
std::map< std::pair< std::string, std::string >, vcd_sig_info > scope_and_name_to_sig_info
maps every pair (scope, signal name) to the corresponding sig_info
std::map< std::string, CustomUnorderedSet< std::pair< std::string, std::string > > > vcd_id_to_scope_and_name
maps every signal id in the vcd to the set of the corresponding pairs (scope, hdl signal name)
Detailed Description
Definition at line 84 of file vcd_parser.hpp.
Member Typedef Documentation
vcd_filter_t
typedef UnorderedMapStd<std::string, UnorderedSetStdStable<std::string> > vcd_parser::vcd_filter_t
this is the type used to select which signals have to be filtered during parsing.
the key of the map is a std::string representing a scope. the value type is a UnorderedSetStd containing all the names of the signal that have to be selected in that scope
Definition at line 100 of file vcd_parser.hpp.
vcd_trace_t
typedef UnorderedMapStd<std::string, CustomUnorderedMapStable<std::string, std::list<sig_variation> > > vcd_parser::vcd_trace_t
this type is the result of a parse.
the primary key is the scope. the secondary key is the name of the signal. the value type is std::list of sig_variation representing the waveform
Definition at line 108 of file vcd_parser.hpp.
Constructor & Destructor Documentation
vcd_parser()
vcd_parser::vcd_parser (const ParameterConstRef & param) [explicit]
constructor
Parameters
in params is the class holding bambu parameters
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Definition at line 48 of file vcd_parser.cpp.
Member Function Documentation
add_variation()
void vcd_parser::add_variation (const std::string & id, const std::string & value, unsigned long long ts) [private]
Definition at line 581 of file vcd_parser.cpp.
References HIERARCHY_SEPARATOR, vcd_sig_info::lsb, vcd_sig_info::msb, parse_result, scope_and_name_to_sig_info, STR, THROW_ASSERT, vcd_sig_info::vcd_id_to_bit, and vcd_id_to_scope_and_name.
Referenced by vcd_parse_sim(), vcd_parse_sim_real(), and vcd_parse_sim_vector().
check_filter_list()
bool vcd_parser::check_filter_list (const std::string & scope_str, const std::string & name) [private]
Checks if a signal is to be monitored.
Returns
: true if the signal has to be monitored, false if not.
Parameters
in name is the name of the signal to be monitored.
in,out scope_str in input this is the signal scope in the vcd; if the signal has to be monitored the string referenced by this parameter is modified, trimming the initial part of the scope to avoid simulator-dependent path names. After this change the remaining part of the path starts from the top functional unit
Definition at line 507 of file vcd_parser.cpp.
References filtered_signals.
Referenced by vcd_parse_def_var().
check_signals()
bool vcd_parser::check_signals () const [private]
check if the port vectors declarations are consistent
Definition at line 551 of file vcd_parser.cpp.
References DEBUG_LEVEL_NONE, vcd_sig_info::is_vec, vcd_sig_info::lsb, vcd_sig_info::msb, PRINT_OUT_MEX, scope_and_name_to_sig_info, and vcd_sig_info::vcd_id_to_bit.
Referenced by vcd_parse_def().
init_variations()
void vcd_parser::init_variations () [private]
Definition at line 568 of file vcd_parser.cpp.
References vcd_sig_info::lsb, vcd_sig_info::msb, parse_result, scope_and_name_to_sig_info, and vcd_id_to_scope_and_name.
Referenced by vcd_parse_sim().
parse_vcd()
vcd_parser::vcd_trace_t vcd_parser::parse_vcd (const std::string & vcd_file_to_parse, const vcd_parser::vcd_filter_t & selected_signals)
parses a file selecting only a predefined set of signals.
Parameters
in vcd_file_to_parse name of the file to parse
in selected_signals signals to be selected. all signals are selected if this parameter is empty
Returns
: the traces of the selected vcd signals
Definition at line 52 of file vcd_parser.cpp.
References debug_level, DEBUG_LEVEL_VERBOSE, filtered_signals, INDENT_DBG_MEX, parse_result, scope_and_name_to_sig_info, sig_n, STR, THROW_ERROR, vcd_filename, vcd_fp, vcd_id_to_scope_and_name, vcd_parse_def(), and vcd_parse_sim().
Referenced by vcd_utility::Exec().
vcd_add_signal()
void vcd_parser::vcd_add_signal (const std::string & scope, const std::string & name, const std::string & vcd_id, const std::string & type, const bool isvect, const unsigned int msb, const unsigned int lsb) [private]
insert a signal in the maps needed for selecting the vcd data and for relating it back to HDL and C variables
Parameters
in scope is the string representing the scope in the parsed vcd
in name the signal name in the parsed vcd
in vcd_id a string used as unique identifier for the signal in the vcd
in type string describing the signal type
in isvect true if the signal is a bit vector
in msb most significant bit of the signal
in lsb less significant bit of the signal
Definition at line 522 of file vcd_parser.cpp.
References vcd_sig_info::is_vec, vcd_sig_info::lsb, max(), min, vcd_sig_info::msb, parse_result, scope_and_name_to_sig_info, THROW_ASSERT, THROW_ERROR, vcd_sig_info::type, and vcd_id_to_scope_and_name.
Referenced by vcd_parse_def_var().
vcd_parse_def()
int vcd_parser::vcd_parse_def () [private]
Definition at line 318 of file vcd_parser.cpp.
References check_signals(), STR, THROW_ERROR, vcd_filename, vcd_fp, vcd_parse_def_var(), vcd_parse_skip_to_end(), vcd_pop_def_scope(), and vcd_push_def_scope().
Referenced by parse_vcd().
vcd_parse_def_var()
int vcd_parser::vcd_parse_def_var (const std::string & scope) [private]
Parses definition $var keyword line until $end keyword is seen.
Definition at line 142 of file vcd_parser.cpp.
References check_filter_list(), debug_level, DEBUG_LEVEL_VERBOSE, PRINT_DBG_MEX, sig_n, THROW_ERROR, test_panda::type, vcd_add_signal(), and vcd_fp.
Referenced by vcd_parse_def().
vcd_parse_sim()
int vcd_parser::vcd_parse_sim () [private]
Parses all lines that occur in the simulation portion of the VCD file.
Definition at line 440 of file vcd_parser.cpp.
References add_variation(), init_variations(), STR, THROW_ERROR, vcd_filename, vcd_fp, vcd_parse_sim_real(), vcd_parse_sim_vector(), and vcd_parse_skip_to_end().
Referenced by parse_vcd().
vcd_parse_sim_real()
int vcd_parser::vcd_parse_sim_real (char * value, unsigned long timestamp) [private]
Reads the next token from the file and calls the appropriate function.
Definition at line 415 of file vcd_parser.cpp.
References add_variation(), THROW_ERROR, and vcd_fp.
Referenced by vcd_parse_sim().
vcd_parse_sim_vector()
int vcd_parser::vcd_parse_sim_vector (char * value, unsigned long timestamp) [private]
Reads the next token from the file and calls the appropriate fuction.
Definition at line 389 of file vcd_parser.cpp.
References add_variation(), THROW_ERROR, and vcd_fp.
Referenced by vcd_parse_sim().
vcd_parse_skip_to_end()
int vcd_parser::vcd_parse_skip_to_end () [private]
Parses specified file until $end keyword is seen, ignoring all text inbetween.
Definition at line 112 of file vcd_parser.cpp.
References THROW_ERROR, and vcd_fp.
Referenced by vcd_parse_def(), and vcd_parse_sim().
vcd_pop_def_scope()
void vcd_parser::vcd_pop_def_scope (std::stack< std::string > & scope) [private]
Definition at line 289 of file vcd_parser.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, PRINT_DBG_MEX, THROW_ERROR, and vcd_fp.
Referenced by vcd_parse_def().
vcd_push_def_scope()
void vcd_parser::vcd_push_def_scope (std::stack< std::string > & scope) [private]
Parses definition $scope keyword line until $end keyword is seen.
Definition at line 268 of file vcd_parser.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, HIERARCHY_SEPARATOR, PRINT_DBG_MEX, STR, THROW_ERROR, and vcd_fp.
Referenced by vcd_parse_def().
Field Documentation
debug_level
const int vcd_parser::debug_level [private]
Debug Level.
Definition at line 123 of file vcd_parser.hpp.
Referenced by parse_vcd(), vcd_parse_def_var(), vcd_pop_def_scope(), and vcd_push_def_scope().
filtered_signals
vcd_filter_t vcd_parser::filtered_signals [private]
set of signals to select from the vcd file.
if it's empty all the signals will be selected, otherwise the data about uninteresting signals are discarded to save memory
Definition at line 147 of file vcd_parser.hpp.
Referenced by check_filter_list(), and parse_vcd().
parse_result
vcd_trace_t vcd_parser::parse_result [private]
holds the parsed vcd trace during the parsing
Definition at line 154 of file vcd_parser.hpp.
Referenced by add_variation(), init_variations(), parse_vcd(), and vcd_add_signal().
scope_and_name_to_sig_info
std::map<std::pair<std::string, std::string>, vcd_sig_info> vcd_parser::scope_and_name_to_sig_info [private]
maps every pair (scope, signal name) to the corresponding sig_info
Definition at line 159 of file vcd_parser.hpp.
Referenced by add_variation(), check_signals(), init_variations(), parse_vcd(), and vcd_add_signal().
sig_n
unsigned long vcd_parser::sig_n [private]
total number of signals in the vcd file
Definition at line 140 of file vcd_parser.hpp.
Referenced by parse_vcd(), and vcd_parse_def_var().
vcd_filename
std::string vcd_parser::vcd_filename [private]
name of the vcd file to parse
Definition at line 130 of file vcd_parser.hpp.
Referenced by parse_vcd(), vcd_parse_def(), and vcd_parse_sim().
vcd_fp
FILE* vcd_parser::vcd_fp [private]
file pointer to the vcd file to parse
Definition at line 135 of file vcd_parser.hpp.
Referenced by parse_vcd(), vcd_parse_def(), vcd_parse_def_var(), vcd_parse_sim(), vcd_parse_sim_real(), vcd_parse_sim_vector(), vcd_parse_skip_to_end(), vcd_pop_def_scope(), and vcd_push_def_scope().
vcd_id_to_scope_and_name
std::map<std::string, CustomUnorderedSet<std::pair<std::string, std::string> > > vcd_parser::vcd_id_to_scope_and_name [private]
maps every signal id in the vcd to the set of the corresponding pairs (scope, hdl signal name)
Definition at line 164 of file vcd_parser.hpp.
Referenced by add_variation(), init_variations(), parse_vcd(), and vcd_add_signal().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/vcd/vcd_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/vcd/vcd_parser.cpp