rebuild_initialization2 Class Reference
Rebuild initialization function flow front-end step done after IR_lowering.
#include <rebuild_initializations.hpp>
Public Member Functions
rebuild_initialization2 (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~rebuild_initialization2 () override
Destructor.
DesignFlowStep_Status InternalExec () override
Rebuild initialization function flow front-end step.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
bool extract_var_decl_ppe (tree_nodeRef addr_assign_op1, unsigned &vd_index, tree_nodeRef &vd_node)
extract_var_decl_ppe
bool extract_var_decl (const mem_ref *me, unsigned &vd_index, tree_nodeRef &vd_node, tree_nodeRef &addr_assign_op1)
extract_var_decl return the variable decl referred by the mem_ref given it is resolvable
bool look_for_ROMs ()
look_for_ROMs transforms the IR by looking for an initial sequence of writes followed by read only instructions.
Additional Inherited Members
Detailed Description
Rebuild initialization function flow front-end step done after IR_lowering.
Definition at line 100 of file rebuild_initializations.hpp.
Constructor & Destructor Documentation
rebuild_initialization2()
rebuild_initialization2::rebuild_initialization2 (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Definition at line 202 of file rebuild_initializations.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, and GET_CLASS.
 rebuild_initialization2()
rebuild_initialization2::~rebuild_initialization2 () [override], [default]
Destructor.
Referenced by ComputeFrontendRelationships().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > rebuild_initialization2::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 208 of file rebuild_initializations.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and ~rebuild_initialization2().
extract_var_decl()
bool rebuild_initialization2::extract_var_decl (const mem_ref * me, unsigned & vd_index, tree_nodeRef & vd_node, tree_nodeRef & addr_assign_op1) [private]
extract_var_decl return the variable decl referred by the mem_ref given it is resolvable
Parameters
me is the memory reference node
vd_index is the variable decl index
vd_node is the variable decl tree re-index node
addr_assign_op1 is the pointer expression used by the mem_ref
Returns
true in case it is possible to compute the variable decl referred, false otherwise
Definition at line 414 of file rebuild_initializations.cpp.
References extract_var_decl_ppe(), extractOp1(), tree_helper::get_integer_cst_value(), tree_node::get_kind(), GET_NODE, THROW_ASSERT, unexpetedPattern(), and varFound().
Referenced by look_for_ROMs().
extract_var_decl_ppe()
bool rebuild_initialization2::extract_var_decl_ppe (tree_nodeRef addr_assign_op1, unsigned & vd_index, tree_nodeRef & vd_node) [private]
extract_var_decl_ppe
Parameters
vd_index is the variable decl index
vd_node is the variable decl tree re-index node
starting from this condition offset is not anymore null
Definition at line 268 of file rebuild_initializations.cpp.
References extractOp1(), tree_helper::get_integer_cst_value(), GET_NODE, unexpetedPattern(), and varFound().
Referenced by extract_var_decl().
InternalExec()
DesignFlowStep_Status rebuild_initialization2::InternalExec () [override], [virtual]
Rebuild initialization function flow front-end step.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 1136 of file rebuild_initializations.cpp.
References FunctionFrontendFlowStep::function_behavior, look_for_ROMs(), SUCCESS, and UNCHANGED.
look_for_ROMs()
bool rebuild_initialization2::look_for_ROMs () [private]
look_for_ROMs transforms the IR by looking for an initial sequence of writes followed by read only instructions.
In case the writes have constant offset and the written values are constants a constant array may be defined. for each basic block B in CFG compute constantVars candidates
are we writing a constant value
first check if the variable is initialized
then we check if the variable is an array
then in case we are fine we classify as good candidate for being a constant var
if it is still a good candidate
check if the offset is constant
index is constant
index is constant
else do nothing
compute the CFG
add vertices
add edges
add a connection between entry and exit thus avoiding problems with non terminating code
check if reads are consistent with writes: writes are always dominating the following reads
list all constant variables found
Definition at line 549 of file rebuild_initializations.cpp.
References FrontendFlowStep::AppM, CFG_SELECTOR, tree_manager::CGetTreeNode(), tree_manager::CGetTreeReindex(), tree_manipulation::create_default_integer_type(), tree_manager::create_tree_node(), tree_manipulation::CreateIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, extract_var_decl(), foundNonConstant, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_array_dim_and_bitsize(), tree_helper::get_integer_cst_value(), tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_node(), getAssign(), tree_helper::GetElements(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, index, tree_helper::is_an_array(), graph::IsReachable(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, sl, STR, THROW_ASSERT, TOK, TOK_SRCP, TOK_TYPE, ToString(), tree_node::ToString(), and unexpetedPattern2.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/rebuild_initializations.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/rebuild_initializations.cpp