system_verilog_writer Class Reference
#include <sv_writer.hpp>
Public Member Functions
std::string get_name () const override
Return the name of the language writer.
std::string get_extension () const override
Return the filename extension associted with the verilog_writer.
void write_NP_functionalities (const structural_objectRef &cir) override
Write in the proper language the behavioral description of the module described in `Not Parsed` form.
system_verilog_writer (const ParameterConstRef parameters)
Constructor.
~system_verilog_writer () override
Destructor.
Additional Inherited Members
Detailed Description
Definition at line 48 of file sv_writer.hpp.
Constructor & Destructor Documentation
system_verilog_writer()
system_verilog_writer::system_verilog_writer (const ParameterConstRef parameters) [explicit]
Constructor.
Definition at line 95 of file sv_writer.cpp.
References language_writer::debug_level, GET_CLASS, language_writer::parameters, and ~system_verilog_writer().
Referenced by get_extension().
 system_verilog_writer()
system_verilog_writer::~system_verilog_writer () [override], [default]
Destructor.
Referenced by get_extension(), and system_verilog_writer().
Member Function Documentation
get_extension()
std::string system_verilog_writer::get_extension () const [inline], [override], [virtual]
Return the filename extension associted with the verilog_writer.
Implements language_writer.
Definition at line 61 of file sv_writer.hpp.
References language_writer::parameters, system_verilog_writer(), write_NP_functionalities(), and ~system_verilog_writer().
get_name()
std::string system_verilog_writer::get_name () const [inline], [override], [virtual]
Return the name of the language writer.
Implements language_writer.
Definition at line 54 of file sv_writer.hpp.
write_NP_functionalities()
void system_verilog_writer::write_NP_functionalities (const structural_objectRef & cir) [override], [virtual]
Write in the proper language the behavioral description of the module described in `Not Parsed` form.
. include
Parameters
cir is the component.
Utility include manage reset by preprocessing the behavioral description
Implements language_writer.
Definition at line 62 of file sv_writer.cpp.
References IndentedOutputStream::Append(), HDL_manager::convert_to_identifier(), NP_functionality::get_NP_functionality(), GET_TYPE_NAME, language_writer::indented_output_stream, language_writer::parameters, remove_escaped(), RESET_PORT_NAME, NP_functionality::SYSTEM_VERILOG_PROVIDED, and THROW_ASSERT.
Referenced by get_extension().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/writer/sv_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToHDL/writer/sv_writer.cpp