constant_o Class Reference
This class describes a constant value.
#include <structural_objects.hpp>
Public Member Functions
constant_o (int debug_level, const structural_objectRef o)
Constructor.
constant_o (int debug_level, const structural_objectRef o, std::string value)
Constructor.
~constant_o () override=default
Destructor.
void add_connection (structural_objectRef p)
Bind the element object with a port/signal.
structural_objectRef get_connection (unsigned int n) const
Return the ith element bounded to the connection.
unsigned int get_connected_objects_size () const
Return the number of ports associated with the connection.
unsigned int get_size () const
Return the size associated with this element (in bits)
std::string get_value () const
Return the (integer) value associated with this element.
void copy (structural_objectRef dest) const override
Perform a copy of the value.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the constant value (for debug purpose)
Private Attributes
std::string value
Value of this element.
std::vector< Wrefcount< structural_object > > connected_objects
List of ports bounded by the constant object.
Additional Inherited Members
Detailed Description
This class describes a constant value.
The value is defined by a size and a value
Definition at line 1505 of file structural_objects.hpp.
Constructor & Destructor Documentation
constant_o() [1/2]
constant_o::constant_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the value
Definition at line 1930 of file structural_objects.cpp.
constant_o() [2/2]
constant_o::constant_o (int debug_level, const structural_objectRef o, std::string value)
Constructor.
Parameters
o is the owner of the value
value is the constant value
Definition at line 1934 of file structural_objects.cpp.
 constant_o()
constant_o::~constant_o () [override], [default]
Destructor.
Member Function Documentation
add_connection()
void constant_o::add_connection (structural_objectRef p)
Bind the element object with a port/signal.
Parameters
p is the port
check if the object is already into the list
Definition at line 1949 of file structural_objects.cpp.
References connected_objects, structural_object::get_kind(), structural_object::get_kind_text(), port_o_K, signal_o_K, and THROW_ASSERT.
copy()
void constant_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the value.
Parameters
dest destination object.
the field connected_objects has to be updated outside!!!
Reimplemented from structural_object.
Definition at line 1960 of file structural_objects.cpp.
References structural_object::copy(), THROW_ASSERT, and value.
find_isomorphic()
structural_objectRef constant_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Definition at line 2005 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, structural_object::find_isomorphic(), structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_ERROR.
find_member()
structural_objectRef constant_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 1978 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, connected_objects, constant_o_K, data_o_K, event_o_K, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, and THROW_ERROR.
get_connected_objects_size()
unsigned int constant_o::get_connected_objects_size () const
Return the number of ports associated with the connection.
Definition at line 1938 of file structural_objects.cpp.
References connected_objects.
get_connection()
structural_objectRef constant_o::get_connection (unsigned int n) const
Return the ith element bounded to the connection.
Parameters
n is the index of the port.
Definition at line 1943 of file structural_objects.cpp.
References connected_objects, and THROW_ASSERT.
get_size()
unsigned int constant_o::get_size () const
Return the size associated with this element (in bits)
Definition at line 1968 of file structural_objects.cpp.
References GET_TYPE_SIZE.
get_value()
std::string constant_o::get_value () const
Return the (integer) value associated with this element.
Definition at line 1973 of file structural_objects.cpp.
References value.
print()
void constant_o::print (std::ostream & os) const [override], [virtual]
Print the constant value (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Definition at line 2062 of file structural_objects.cpp.
References connected_objects, structural_object::convert_so_short(), structural_object::PP, structural_object::print(), and value.
xload()
void constant_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
the field connected_objects has to be updated outside!!!
Reimplemented from structural_object.
Definition at line 2039 of file structural_objects.cpp.
References CE_XVM, LOAD_XVFM, LOAD_XVM, structural_object::set_id(), and value.
xwrite()
void constant_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Definition at line 2052 of file structural_objects.cpp.
References xml_child::add_child_element(), connected_objects, structural_object::get_kind_text(), value, WRITE_XNVM2, WRITE_XVM, and structural_object::xwrite().
Field Documentation
connected_objects
std::vector<Wrefcount<structural_object> > constant_o::connected_objects [private]
List of ports bounded by the constant object.
Definition at line 1511 of file structural_objects.hpp.
Referenced by add_connection(), find_member(), get_connected_objects_size(), get_connection(), print(), and xwrite().
value
std::string constant_o::value [private]
Value of this element.
Definition at line 1508 of file structural_objects.hpp.
Referenced by copy(), get_value(), print(), xload(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp