tree_node_dup Struct Reference
#include <tree_node_dup.hpp>
Public Member Functions
tree_node_dup (CustomUnorderedMapStable< unsigned int, unsigned int > &_remap, const tree_managerRef _TM)
default constructor
unsigned int create_tree_node (const tree_nodeRef &tn)
tree_node visitors
Private Attributes
CustomUnorderedMapStable< unsigned int, unsigned int > & remap
remap old indexes in new indexes
const tree_managerRef TM
tree manager
tree_node * curr_tree_node_ptr
current tree node filled according to the source tree_node
bloc * curr_bloc
current basic block pointer
tree_nodeRef source_tn
current tree_node source
blocRef source_bloc
current basic block source
Detailed Description
Definition at line 61 of file tree_node_dup.hpp.
Constructor & Destructor Documentation
tree_node_dup()
tree_node_dup::tree_node_dup (CustomUnorderedMapStable< unsigned int, unsigned int > & _remap, const tree_managerRef _TM) [inline]
default constructor
Definition at line 64 of file tree_node_dup.hpp.
References object_visitor::BOOST_PP_SEQ_FOR_EACH(), create_tree_node(), OBJ_NOT_SPECIALIZED_SEQ, OBJ_SPECIALIZED_SEQ, OPERATOR_MACRO, and OPERATOR_MACRO_DECL.
Member Function Documentation
create_tree_node()
unsigned int tree_node_dup::create_tree_node (const tree_nodeRef & tn)
tree_node visitors
Factory method. It duplicates a tree_node when needed according to the source node tn
Parameters
tn is the source tree node
Returns
the node_id of the created object or of tn.
Definition at line 94 of file tree_node_dup.cpp.
References ATTR_MACRO, ATTR_SEQ, object_visitor::BOOST_PP_SEQ_FOR_EACH(), CASE_FAKE_NODES, CREATE_TREE_NODE_CASE_BODY, curr_tree_node_ptr, tree_node::get_kind(), tree_node::get_kind_text(), RET_NODE_ID_CASE_BODY, template_id_expr(), THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, typename_type(), and using_decl().
Referenced by Vectorize::DuplicateIncrement(), and tree_node_dup().
Field Documentation
curr_bloc
bloc* tree_node_dup::curr_bloc [private]
current basic block pointer
Definition at line 87 of file tree_node_dup.hpp.
curr_tree_node_ptr
tree_node* tree_node_dup::curr_tree_node_ptr [private]
current tree node filled according to the source tree_node
Definition at line 85 of file tree_node_dup.hpp.
Referenced by create_tree_node().
remap
CustomUnorderedMapStable<unsigned int, unsigned int>& tree_node_dup::remap [private]
remap old indexes in new indexes
Definition at line 81 of file tree_node_dup.hpp.
source_bloc
blocRef tree_node_dup::source_bloc [private]
current basic block source
Definition at line 91 of file tree_node_dup.hpp.
source_tn
tree_nodeRef tree_node_dup::source_tn [private]
current tree_node source
Definition at line 89 of file tree_node_dup.hpp.
TM
const tree_managerRef tree_node_dup::TM [private]
tree manager
Definition at line 83 of file tree_node_dup.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node_dup.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node_dup.cpp