UpdateSchedule Class Reference
Update schedule of all the instructions.
#include <update_schedule.hpp>
Public Member Functions
UpdateSchedule (const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~UpdateSchedule () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
ScheduleRef schedule
The scheduling solution.
Additional Inherited Members
Detailed Description
Update schedule of all the instructions.
Definition at line 53 of file update_schedule.hpp.
Constructor & Destructor Documentation
UpdateSchedule()
UpdateSchedule::UpdateSchedule (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
Param is the set of the parameters
behavior includes . include HLS includes HLS/scheduling include tree includes
Definition at line 66 of file update_schedule.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~UpdateSchedule().
 UpdateSchedule()
UpdateSchedule::~UpdateSchedule () [override], [default]
Destructor.
Referenced by UpdateSchedule().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > UpdateSchedule::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 74 of file update_schedule.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
HasToBeExecuted()
bool UpdateSchedule::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 115 of file update_schedule.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), and DesignFlowStep::parameters.
Initialize()
void UpdateSchedule::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Set reference to schedule in basic blocks
Reimplemented from DesignFlowStep.
Definition at line 100 of file update_schedule.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, and schedule.
InternalExec()
DesignFlowStep_Status UpdateSchedule::InternalExec () [override], [virtual]
Restructures the unstructured code.
Implements FunctionFrontendFlowStep.
Definition at line 130 of file update_schedule.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_id, GET_NODE, INDENT_DBG_MEX, phi, schedule, sl, STR, SUCCESS, and Schedule::UpdateTime().
Field Documentation
schedule
ScheduleRef UpdateSchedule::schedule [protected]
The scheduling solution.
Definition at line 57 of file update_schedule.hpp.
Referenced by Initialize(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/update_schedule.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/update_schedule.cpp