CallSitesCollectorVisitor Class Reference
#include <CallSitesCollectorVisitor.hpp>
Public Member Functions
CallSitesCollectorVisitor (const HLS_managerRef &_HLSMgr)
Constructor.
~CallSitesCollectorVisitor ()
Destructor.
void start_vertex (const vertex &, const CallGraph &)
void back_edge (const EdgeDescriptor &, const CallGraph &)
void examine_edge (const EdgeDescriptor &, const CallGraph &)
void discover_vertex (const vertex &v, const CallGraph &)
Private Attributes
const HLS_managerRef HLSMgr
A refcount to the HLSMgr.
const CallGraphManagerConstRef CGMan
A refcount to the call graph manager.
Detailed Description
Definition at line 51 of file CallSitesCollectorVisitor.hpp.
Constructor & Destructor Documentation
CallSitesCollectorVisitor()
CallSitesCollectorVisitor::CallSitesCollectorVisitor (const HLS_managerRef & _HLSMgr)
Constructor.
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Definition at line 47 of file CallSitesCollectorVisitor.cpp.
References ~CallSitesCollectorVisitor().
 CallSitesCollectorVisitor()
CallSitesCollectorVisitor::~CallSitesCollectorVisitor () [default]
Destructor.
Referenced by CallSitesCollectorVisitor().
Member Function Documentation
back_edge()
void CallSitesCollectorVisitor::back_edge (const EdgeDescriptor & , const CallGraph &)
Definition at line 64 of file CallSitesCollectorVisitor.cpp.
References THROW_ERROR.
discover_vertex()
void CallSitesCollectorVisitor::discover_vertex (const vertex & v, const CallGraph &)
Definition at line 58 of file CallSitesCollectorVisitor.cpp.
References CGMan, and HLSMgr.
examine_edge()
void CallSitesCollectorVisitor::examine_edge (const EdgeDescriptor & e, const CallGraph & g)
Definition at line 69 of file CallSitesCollectorVisitor.cpp.
References CallGraph::CGetFunctionEdgeInfo(), CGMan, HLSMgr, STR, and THROW_ASSERT.
start_vertex()
void CallSitesCollectorVisitor::start_vertex (const vertex & , const CallGraph &)
Definition at line 53 of file CallSitesCollectorVisitor.cpp.
References HLSMgr, and THROW_ASSERT.
Field Documentation
CGMan
const CallGraphManagerConstRef CallSitesCollectorVisitor::CGMan [private]
A refcount to the call graph manager.
Definition at line 58 of file CallSitesCollectorVisitor.hpp.
Referenced by discover_vertex(), and examine_edge().
HLSMgr
const HLS_managerRef CallSitesCollectorVisitor::HLSMgr [private]
A refcount to the HLSMgr.
Definition at line 55 of file CallSitesCollectorVisitor.hpp.
Referenced by discover_vertex(), examine_edge(), and start_vertex().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/CallSitesCollectorVisitor.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/CallSitesCollectorVisitor.cpp