AuxDesignFlowStep Class Reference
Class describing auxiliary steps in design flow.
#include <design_flow_aux_step.hpp>
Public Member Functions
AuxDesignFlowStep (std::string name, const AuxDesignFlowStepType type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~AuxDesignFlowStep () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
const std::string GetSignature () const override
Return a unified identifier of this design step.
const std::string GetName () const override
Return the name of this design step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
void WriteDot (std::ostream &out) const override
Write the label for a dot graph.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
Static Public Member Functions
static const std::string ComputeSignature (const std::string &name, const AuxDesignFlowStepType type)
Compute the signature of a sdf design flow step.
Private Attributes
const AuxDesignFlowStepType type
The type of this auxiliary design flow step.
const std::string name
The name of this auxiliary design flow step.
Additional Inherited Members
Detailed Description
Class describing auxiliary steps in design flow.
Definition at line 60 of file design_flow_aux_step.hpp.
Constructor & Destructor Documentation
AuxDesignFlowStep()
AuxDesignFlowStep::AuxDesignFlowStep (std::string name, const AuxDesignFlowStepType type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
name is the name of the step
type is the type of the step
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 50 of file design_flow_aux_step.cpp.
References ~AuxDesignFlowStep().
 AuxDesignFlowStep()
AuxDesignFlowStep::~AuxDesignFlowStep () [override], [default]
Destructor.
Referenced by AuxDesignFlowStep().
Member Function Documentation
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef AuxDesignFlowStep::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 86 of file design_flow_aux_step.cpp.
References THROW_UNREACHABLE.
ComputeRelationships()
void AuxDesignFlowStep::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
design_flow is the design flow graph
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 57 of file design_flow_aux_step.cpp.
ComputeSignature()
const std::string AuxDesignFlowStep::ComputeSignature (const std::string & name, const AuxDesignFlowStepType type) [static]
Compute the signature of a sdf design flow step.
Parameters
name is the name of the step
type is the type of auxiliary step
Returns
the signature corresponding to the analysis/transformation
Definition at line 61 of file design_flow_aux_step.cpp.
References type.
Referenced by GetSignature().
Exec()
DesignFlowStep_Status AuxDesignFlowStep::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 66 of file design_flow_aux_step.cpp.
References EMPTY.
GetName()
const std::string AuxDesignFlowStep::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 71 of file design_flow_aux_step.cpp.
References name.
GetSignature()
const std::string AuxDesignFlowStep::GetSignature () const [override], [virtual]
Return a unified identifier of this design step.
Returns
the signature of the design step
Implements DesignFlowStep.
Definition at line 76 of file design_flow_aux_step.cpp.
References ComputeSignature(), name, and type.
HasToBeExecuted()
bool AuxDesignFlowStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 92 of file design_flow_aux_step.cpp.
WriteDot()
void AuxDesignFlowStep::WriteDot (std::ostream & out) const [override], [virtual]
Write the label for a dot graph.
Parameters
out is the stream where label has to be printed
Reimplemented from DesignFlowStep.
Definition at line 81 of file design_flow_aux_step.cpp.
References name.
Field Documentation
name
const std::string AuxDesignFlowStep::name [private]
The name of this auxiliary design flow step.
Definition at line 67 of file design_flow_aux_step.hpp.
Referenced by GetName(), GetSignature(), and WriteDot().
type
const AuxDesignFlowStepType AuxDesignFlowStep::type [private]
The type of this auxiliary design flow step.
Definition at line 64 of file design_flow_aux_step.hpp.
Referenced by ComputeSignature(), and GetSignature().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow_aux_step.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow_aux_step.cpp