attribute Struct Reference
#include <library_manager.hpp>
Public Types
enum value_t { FLOAT64 = 0,
BOOLEAN,
INT32,
STRING
 }
Public Member Functions
attribute (const value_t _value_type, std::string _content)
attribute (const std::string &_value_type, std::string _content)
attribute (const std::vector< attributeRef > &_content)
Autoheader include.
std::string get_value_type_str () const
std::string get_content_str () const
bool has_list () const
unsigned int get_value_type () const
template<class G >
G get_content () const
const std::vector< attributeRef > & get_content_list () const
void xwrite (xml_element *xml_node, const std::string &name)
Static Public Member Functions
static void xload (const xml_element *node, std::vector< std::string > &ordered_attributes, std::map< std::string, attributeRef > &attributes)
Private Attributes
std::string content
value_t value_type {FLOAT64}
std::vector< attributeRef > content_list
Detailed Description
Definition at line 76 of file library_manager.hpp.
Member Enumeration Documentation
value_t
enum attribute::value_t
Enumerator
FLOAT64
BOOLEAN
INT32
STRING
Definition at line 79 of file library_manager.hpp.
Constructor & Destructor Documentation
attribute() [1/3]
attribute::attribute (const value_t _value_type, std::string _content)
Definition at line 103 of file library_manager.cpp.
References content, xml_node::convert_escaped(), and value_type.
Referenced by library_manager::set_default_attributes(), and xload().
attribute() [2/3]
attribute::attribute (const std::string & _value_type, std::string _content)
Definition at line 78 of file library_manager.cpp.
References BOOLEAN, content, xml_node::convert_escaped(), FLOAT64, INT32, STRING, THROW_ERROR, and value_type.
attribute() [3/3]
attribute::attribute (const std::vector< attributeRef > & _content) [explicit]
Autoheader include.
Definition at line 73 of file library_manager.cpp.
References content_list.
Member Function Documentation
get_content()
template<class G >
G attribute::get_content () const [inline]
Definition at line 110 of file library_manager.hpp.
References content.
get_content_list()
const std::vector<attributeRef>& attribute::get_content_list () const [inline]
Definition at line 115 of file library_manager.hpp.
References content_list, xload(), and xwrite().
get_content_str()
std::string attribute::get_content_str () const
fix for content_list
Definition at line 134 of file library_manager.cpp.
References content.
Referenced by xwrite().
get_value_type()
unsigned int attribute::get_value_type () const
Definition at line 145 of file library_manager.cpp.
References value_type.
get_value_type_str()
std::string attribute::get_value_type_str () const
Definition at line 109 of file library_manager.cpp.
References BOOLEAN, FLOAT64, INT32, STRING, THROW_ERROR, and value_type.
Referenced by xwrite().
has_list()
bool attribute::has_list () const
Definition at line 140 of file library_manager.cpp.
References content_list.
Referenced by xwrite().
xload()
void attribute::xload (const xml_element * node, std::vector< std::string > & ordered_attributes, std::map< std::string, attributeRef > & attributes) [static]
Definition at line 150 of file library_manager.cpp.
References attribute(), attribute_sequence::get_attribute(), xml_child::get_child_text(), xml_child::get_children(), xml_text_node::get_content(), and xml_attribute::get_value().
Referenced by get_content_list(), library_manager::xload(), and functional_unit::xload().
xwrite()
void attribute::xwrite (xml_element * xml_node, const std::string & name)
Definition at line 181 of file library_manager.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), content_list, el, get_content_str(), get_value_type_str(), has_list(), and attribute_sequence::set_attribute().
Referenced by get_content_list().
Field Documentation
content
std::string attribute::content [private]
Definition at line 88 of file library_manager.hpp.
Referenced by attribute(), get_content(), get_content_str(), and library_manager::set_default_attributes().
content_list
std::vector<attributeRef> attribute::content_list [private]
Definition at line 92 of file library_manager.hpp.
Referenced by attribute(), get_content_list(), has_list(), and xwrite().
value_type
value_t attribute::value_type {FLOAT64} [private]
Definition at line 90 of file library_manager.hpp.
Referenced by attribute(), get_value_type(), and get_value_type_str().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/library_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/library_manager.cpp