datapath_parallel_cs Class Reference
#include <datapath_parallel_cs.hpp>
Public Member Functions
datapath_parallel_cs (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
virtual ~datapath_parallel_cs ()
Destructor.
DesignFlowStep_Status InternalExec ()
InternalExec.
Protected Member Functions
void instantiate_component_parallel (structural_objectRef clock_port, structural_objectRef reset_port)
instantiate memory_parallel
void manage_extern_global_port_parallel (const structural_managerRef SM, const CustomOrderedSet< structural_objectRef > &memory_modules, const structural_objectRef circuit)
connect mem_parallel with datapath and kernels
void connect_module_kernel (structural_objectRef kernel, unsigned int num_kernel)
connect datapath with each kernel
void connect_i_module_kernel (structural_objectRef kernel)
connect datapath with each kernel
virtual void add_ports ()
Adds the input/output ports of the module.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
ComputeHLSRelationships datapath need kernel in order to be created.
void resize_dimension_bus_port (unsigned int vector_size, structural_objectRef port)
for each port resize it depending on the type of bus port
void resize_ctrl_parallel_ports (structural_objectRef mem_par_mod)
for each port decide the vector size
Additional Inherited Members
Detailed Description
Definition at line 49 of file datapath_parallel_cs.hpp.
Constructor & Destructor Documentation
datapath_parallel_cs()
datapath_parallel_cs::datapath_parallel_cs (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
Constructor.
HLS/function_allocation include.
Parameters
design_flow_manager is the design flow manager
STD include utility includes
Definition at line 71 of file datapath_parallel_cs.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 datapath_parallel_cs()
datapath_parallel_cs::~datapath_parallel_cs () [virtual]
Destructor.
Definition at line 79 of file datapath_parallel_cs.cpp.
Member Function Documentation
add_ports()
void datapath_parallel_cs::add_ports () [protected], [virtual]
Adds the input/output ports of the module.
Reimplemented from classic_datapath.
Definition at line 180 of file datapath_parallel_cs.cpp.
References structural_manager::add_port(), structural_manager::add_port_vector(), classic_datapath::add_ports(), hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, DONE_REQUEST, structural_manager::get_circ(), HLSFunctionStep::HLS, port_o::IN, port_o::OUT, DesignFlowStep::parameters, PRINT_DBG_MEX, START_PORT_NAME, STR, and TASKS_POOL_END.
Referenced by InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > datapath_parallel_cs::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
ComputeHLSRelationships datapath need kernel in order to be created.
Parameters
relationship_type
Returns
Reimplemented from datapath_creator.
Definition at line 83 of file datapath_parallel_cs.cpp.
References CALLED_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, INITIALIZE_HLS, DesignFlowStep::INVALIDATION_RELATIONSHIP, OMP_BODY_LOOP_SYNTHESIS_FLOW, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
connect_i_module_kernel()
void datapath_parallel_cs::connect_i_module_kernel (structural_objectRef kernel) [protected]
connect datapath with each kernel
Parameters
kernel
Definition at line 255 of file datapath_parallel_cs.cpp.
References structural_manager::add_connection(), hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, port_o_K, and PRINT_DBG_MEX.
Referenced by InternalExec().
connect_module_kernel()
void datapath_parallel_cs::connect_module_kernel (structural_objectRef kernel, unsigned int num_kernel) [protected]
connect datapath with each kernel
Parameters
kernel
num_kernel
Definition at line 199 of file datapath_parallel_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), FunctionBehavior::CGetBehavioralHelper(), CLOCK_PORT_NAME, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, DONE_REQUEST, structural_object::find_member(), HLSFunctionStep::funId, structural_manager::get_circ(), BehavioralHelper::get_parameters(), HLSFunctionStep::HLS, HLS_step::HLSMgr, port_o::IN, port_o_K, port_vector_o_K, PRINT_DBG_MEX, BehavioralHelper::PrintVariable(), RESET_PORT_NAME, START_PORT_NAME, STR, and TASKS_POOL_END.
Referenced by InternalExec().
instantiate_component_parallel()
void datapath_parallel_cs::instantiate_component_parallel (structural_objectRef clock_port, structural_objectRef reset_port) [protected]
instantiate memory_parallel
Parameters
HLS
clock_port
reset_port
Definition at line 273 of file datapath_parallel_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), ceil_log2(), CLOCK_PORT_NAME, hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, hls::HLS_T, DesignFlowStep::parameters, port_o_K, PRINT_DBG_MEX, RESET_PORT_NAME, resize_ctrl_parallel_ports(), and STR.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status datapath_parallel_cs::InternalExec () [virtual]
InternalExec.
Returns
main circuit type
top circuit creation
Set some descriptions and legal stuff
add clock and reset to circuit. It increments in_port number and update in_port_map
add all input ports
Reimplemented from classic_datapath.
Definition at line 108 of file datapath_parallel_cs.cpp.
References classic_datapath::add_clock_reset(), add_ports(), ceil_log2(), FunctionBehavior::CGetBehavioralHelper(), component_o_K, connect_i_module_kernel(), connect_module_kernel(), hls::datapath, DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, DEBUG_LEVEL_VERBOSE, structural_object::find_member(), HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_name(), HLSFunctionStep::HLS, hls::HLS_T, HLS_step::HLSMgr, INDENT_DBG_MEX, instantiate_component_parallel(), manage_extern_global_port_parallel(), hls::Param, DesignFlowStep::parameters, memory::propagate_memory_parameters(), reset(), structural_object::set_black_box(), structural_manager::set_top_info(), STR, SUCCESS, THROW_ASSERT, and THROW_UNREACHABLE.
manage_extern_global_port_parallel()
void datapath_parallel_cs::manage_extern_global_port_parallel (const structural_managerRef SM, const CustomOrderedSet< structural_objectRef > & memory_modules, const structural_objectRef circuit) [protected]
connect mem_parallel with datapath and kernels
Parameters
SM
memory_modules
circuit
Definition at line 360 of file datapath_parallel_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_port_vector(), structural_manager::add_sign(), component_o_K, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, INDENT_DBG_MEX, port_o::OUT, port_vector_o_K, STR, and THROW_ASSERT.
Referenced by InternalExec().
resize_ctrl_parallel_ports()
void datapath_parallel_cs::resize_ctrl_parallel_ports (structural_objectRef mem_par_mod) [protected]
for each port decide the vector size
Parameters
mem_par_mod
Definition at line 311 of file datapath_parallel_cs.cpp.
References get_id(), DesignFlowStep::parameters, and resize_dimension_bus_port().
Referenced by instantiate_component_parallel().
resize_dimension_bus_port()
void datapath_parallel_cs::resize_dimension_bus_port (unsigned int vector_size, structural_objectRef port) [protected]
for each port resize it depending on the type of bus port
Parameters
vector_size
port
Definition at line 341 of file datapath_parallel_cs.cpp.
References HLS_step::HLSMgr, and structural_object::type_resize().
Referenced by resize_ctrl_parallel_ports().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/datapath_creation/datapath_parallel_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/datapath_creation/datapath_parallel_cs.cpp