functions Class Reference
#include <functions.hpp>
Public Member Functions
functions ()
Constructor.
virtual ~functions ()
Destructor.
void map_shared_function (unsigned int funID_scope, const std::string &fun)
allocate a shared function in a specified function.
const CustomOrderedSet< std::string > & get_shared_functions (unsigned int funID_scope) const
return the set of shared functions allocated in a given function.
bool has_shared_functions (unsigned int funID_scope) const
return true in case there are shared functions allocated in a given function.
bool is_a_shared_function (unsigned int funID_scope, const std::string &fun) const
return true if a given function is a shared function allocated in a givend function scope
void add_shared_function_proxy (unsigned int funID_scope, const std::string &fun)
allocate a proxy for the function referred within a given function
const CustomOrderedSet< std::string > & get_proxied_shared_functions (unsigned int funID_scope) const
return the proxied internal functions associated with the function
bool has_proxied_shared_functions (unsigned int funID_scope) const
check if the function has proxied shared functions
bool is_a_proxied_shared_function (unsigned int funID_scope, const std::string &fun) const
return true if a given function is a shared function allocated in a givend function scope
bool is_a_proxied_function (const std::string &fun) const
return true if the function is a proxied function
unsigned int get_proxy_mapping (const std::string &fun) const
in case the function is a proxy function, it returns where the function is actually instantiated
Private Attributes
std::map< unsigned int, CustomOrderedSet< std::string > > shared_function_proxy
set of function proxies called by a function
std::map< std::string, unsigned int > proxied_functions
define where the proxied functions are mapped
std::map< unsigned int, CustomOrderedSet< std::string > > shared_functions
map where shared functions are allocated
Detailed Description
Definition at line 52 of file functions.hpp.
Constructor & Destructor Documentation
functions()
functions::functions () [default]
Constructor.
 functions()
functions::~functions () [virtual], [default]
Destructor.
Member Function Documentation
add_shared_function_proxy()
void functions::add_shared_function_proxy (unsigned int funID_scope, const std::string & fun)
allocate a proxy for the function referred within a given function
Parameters
funID_scope is the function id
fun is the proxy function
Definition at line 74 of file functions.cpp.
References shared_function_proxy.
get_proxied_shared_functions()
const CustomOrderedSet< std::string > & functions::get_proxied_shared_functions (unsigned int funID_scope) const
return the proxied internal functions associated with the function
Parameters
funID_scope is the function id
Returns
the set of functions proxied in funID_scope
Definition at line 79 of file functions.cpp.
References has_proxied_shared_functions(), shared_function_proxy, STR, and THROW_ASSERT.
get_proxy_mapping()
unsigned int functions::get_proxy_mapping (const std::string & fun) const
in case the function is a proxy function, it returns where the function is actually instantiated
Parameters
fun is the proxy function
Returns
the function ID of the function having the instance of proxy function fun
Definition at line 100 of file functions.cpp.
References proxied_functions, and THROW_ASSERT.
get_shared_functions()
const CustomOrderedSet< std::string > & functions::get_shared_functions (unsigned int funID_scope) const
return the set of shared functions allocated in a given function.
Parameters
funID_scope is the function where the shared functions have been allocated
Returns
the set of shared functions allocated in funID_scope
Definition at line 59 of file functions.cpp.
References shared_functions.
has_proxied_shared_functions()
bool functions::has_proxied_shared_functions (unsigned int funID_scope) const
check if the function has proxied shared functions
Parameters
funID_scope is the function id
Returns
true when there are proxied shared functions, false otherwise
Definition at line 85 of file functions.cpp.
References shared_function_proxy.
Referenced by get_proxied_shared_functions(), and is_a_proxied_shared_function().
has_shared_functions()
bool functions::has_shared_functions (unsigned int funID_scope) const
return true in case there are shared functions allocated in a given function.
Parameters
funID_scope is the function id
Returns
true when there are shared functions in funID_scope
Definition at line 64 of file functions.cpp.
References shared_functions.
Referenced by is_a_shared_function().
is_a_proxied_function()
bool functions::is_a_proxied_function (const std::string & fun) const
return true if the function is a proxied function
Parameters
fun is the id of the function
Returns
true when fun is a proxied functions
Definition at line 95 of file functions.cpp.
References proxied_functions.
is_a_proxied_shared_function()
bool functions::is_a_proxied_shared_function (unsigned int funID_scope, const std::string & fun) const
return true if a given function is a shared function allocated in a givend function scope
Parameters
funID_scope is the function scope
fun is the proxied shared function
Returns
true when fun is a proxied shared in funID_scope, false otherwise
Definition at line 90 of file functions.cpp.
References has_proxied_shared_functions(), and shared_function_proxy.
is_a_shared_function()
bool functions::is_a_shared_function (unsigned int funID_scope, const std::string & fun) const
return true if a given function is a shared function allocated in a givend function scope
Parameters
funID_scope is the function scope
fun is the shared function
Returns
true when fun is a shared function in funID_scope, false otherwise
Definition at line 69 of file functions.cpp.
References has_shared_functions(), and shared_functions.
map_shared_function()
void functions::map_shared_function (unsigned int funID_scope, const std::string & fun)
allocate a shared function in a specified function.
Parameters
funID_scope if the function id where the shared function is allocated
fun is the shared function
Definition at line 52 of file functions.cpp.
References fun(), proxied_functions, shared_functions, STR, and THROW_ASSERT.
Field Documentation
proxied_functions
std::map<std::string, unsigned int> functions::proxied_functions [private]
define where the proxied functions are mapped
Definition at line 58 of file functions.hpp.
Referenced by get_proxy_mapping(), is_a_proxied_function(), and map_shared_function().
shared_function_proxy
std::map<unsigned int, CustomOrderedSet<std::string> > functions::shared_function_proxy [private]
set of function proxies called by a function
Definition at line 55 of file functions.hpp.
Referenced by add_shared_function_proxy(), get_proxied_shared_functions(), has_proxied_shared_functions(), and is_a_proxied_shared_function().
shared_functions
std::map<unsigned int, CustomOrderedSet<std::string> > functions::shared_functions [private]
map where shared functions are allocated
Definition at line 61 of file functions.hpp.
Referenced by get_shared_functions(), has_shared_functions(), is_a_shared_function(), and map_shared_function().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/function_allocation/functions.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/function_allocation/functions.cpp