chaining Class Reference
#include <chaining.hpp>
Public Member Functions
chaining (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
~chaining () override
Destructor.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Additional Inherited Members
Detailed Description
Definition at line 54 of file chaining.hpp.
Constructor & Destructor Documentation
chaining()
chaining::chaining (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type)
Constructor.
STD include.
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type HLS/chaining
Definition at line 63 of file chaining.cpp.
 chaining()
chaining::~chaining () [override], [default]
Destructor.
Referenced by Initialize().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > chaining::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 68 of file chaining.cpp.
References BB_STG_CREATOR, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void chaining::Initialize () [override], [protected], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Reimplemented in sched_based_chaining_computation.
Definition at line 93 of file chaining.cpp.
References hls::chaining_information, HLSFunctionStep::HLS, ChainingInformation::Initialize(), HLSFunctionStep::Initialize(), and ~chaining().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/chaining/chaining.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/chaining/chaining.cpp