cell_model Class Reference
#include <cell_model.hpp>
Public Member Functions
cell_model (const ParameterConstRef &Param)
Constructor.
cell_model (const ParameterConstRef &Param, const double &_area_)
Constructor with initial area value.
~cell_model () override
Destructor.
void print (std::ostream &os) const override
Print method.
void set_area_value (const double &_area_) override
Sets the nominal value for the area of the component.
double get_area_value () const override
Returns the nominal value for the area of the component.
bool is_characterization (unsigned int characterization_type) const override
Checks if there is a characterization for the given type.
bool has_element_characterization (unsigned int characterization_type, unsigned int element_type) const
Checks if the given element has a characterization.
double get_characterization (unsigned int characterization_type, unsigned int element_type) const
Returns the characterization for the given element.
void set_characterization (unsigned int characterization_type, unsigned int element_type, double value)
Sets the value of the characterization for the given element.
Protected Member Functions
void determine_shape ()
Determines the shape of the component, given the available information.
Protected Attributes
double area
a double value representing the area of the component
std::map< unsigned int, std::map< unsigned int, double > > characterization
values of the available characterizations
Additional Inherited Members
Detailed Description
Definition at line 58 of file cell_model.hpp.
Constructor & Destructor Documentation
cell_model() [1/2]
cell_model::cell_model (const ParameterConstRef & Param) [explicit]
Constructor.
Definition at line 55 of file cell_model.cpp.
cell_model() [2/2]
cell_model::cell_model (const ParameterConstRef & Param, const double & _area_)
Constructor with initial area value.
Definition at line 59 of file cell_model.cpp.
References ~cell_model().
 cell_model()
cell_model::~cell_model () [override], [default]
Destructor.
Referenced by cell_model().
Member Function Documentation
determine_shape()
void cell_model::determine_shape () [protected]
Determines the shape of the component, given the available information.
get_area_value()
double cell_model::get_area_value () const [override], [virtual]
Returns the nominal value for the area of the component.
Implements area_model.
Definition at line 70 of file cell_model.cpp.
References area.
get_characterization()
double cell_model::get_characterization (unsigned int characterization_type, unsigned int element_type) const
Returns the characterization for the given element.
Definition at line 90 of file cell_model.cpp.
References characterization, has_element_characterization(), is_characterization(), and THROW_ASSERT.
has_element_characterization()
bool cell_model::has_element_characterization (unsigned int characterization_type, unsigned int element_type) const
Checks if the given element has a characterization.
Definition at line 85 of file cell_model.cpp.
References characterization, and is_characterization().
Referenced by get_characterization().
is_characterization()
bool cell_model::is_characterization (unsigned int characterization_type) const [override], [virtual]
Checks if there is a characterization for the given type.
Implements area_model.
Definition at line 80 of file cell_model.cpp.
References characterization.
Referenced by get_characterization(), and has_element_characterization().
print()
void cell_model::print (std::ostream & os) const [override], [virtual]
Print method.
Implements area_model.
Definition at line 65 of file cell_model.cpp.
References area.
set_area_value()
void cell_model::set_area_value (const double & _area_) [override], [virtual]
Sets the nominal value for the area of the component.
Implements area_model.
Definition at line 75 of file cell_model.cpp.
References area.
set_characterization()
void cell_model::set_characterization (unsigned int characterization_type, unsigned int element_type, double value)
Sets the value of the characterization for the given element.
Definition at line 97 of file cell_model.cpp.
References characterization.
Field Documentation
area
double cell_model::area [protected]
a double value representing the area of the component
Definition at line 62 of file cell_model.hpp.
Referenced by get_area_value(), print(), and set_area_value().
characterization
std::map<unsigned int, std::map<unsigned int, double> > cell_model::characterization [protected]
values of the available characterizations
Definition at line 65 of file cell_model.hpp.
Referenced by get_characterization(), has_element_characterization(), is_characterization(), and set_characterization().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/area/cell_model.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/models/area/cell_model.cpp