BasicBlocksProfiling Class Reference
Superclass include.
#include <basic_blocks_profiling.hpp>
Public Member Functions
BasicBlocksProfiling (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~BasicBlocksProfiling () override
Destructor.
DesignFlowStep_Status Exec () override
Performs the profiling step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
const std::string profiling_source_file
The instrumented source code.
Additional Inherited Members
Detailed Description
Superclass include.
Class to perform profiling
Definition at line 49 of file basic_blocks_profiling.hpp.
Constructor & Destructor Documentation
BasicBlocksProfiling()
BasicBlocksProfiling::BasicBlocksProfiling (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of the parameters
STD include
Definition at line 65 of file basic_blocks_profiling.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~BasicBlocksProfiling().
 BasicBlocksProfiling()
BasicBlocksProfiling::~BasicBlocksProfiling () [override], [default]
Destructor.
Referenced by BasicBlocksProfiling().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BasicBlocksProfiling::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 73 of file basic_blocks_profiling.cpp.
ComputeRelationships()
void BasicBlocksProfiling::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 179 of file basic_blocks_profiling.cpp.
References FrontendFlowStep::ComputeRelationships(), CBackend::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, Wrefcount< T >::lock(), NULL_VERTEX, and profiling_source_file.
Exec()
DesignFlowStep_Status BasicBlocksProfiling::Exec () [override], [virtual]
Performs the profiling step.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 79 of file basic_blocks_profiling.cpp.
References FrontendFlowStep::AppM, BBGraphInfo::bb_index_map, test_panda::command, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FBB, INDENT_DBG_MEX, INDENT_OUT_MEX, IsError(), O1, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, PandaSystem(), DesignFlowStep::parameters, PROFILING_EC, profiling_source_file, SplitString(), STR_CST_host_profiling_data, STR_CST_host_profiling_output, SUCCESS, THROW_ASSERT, and THROW_ERROR_CODE.
Initialize()
void BasicBlocksProfiling::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 170 of file basic_blocks_profiling.cpp.
References FrontendFlowStep::AppM.
Field Documentation
profiling_source_file
const std::string BasicBlocksProfiling::profiling_source_file [protected]
The instrumented source code.
Definition at line 53 of file basic_blocks_profiling.hpp.
Referenced by ComputeRelationships(), and Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/basic_blocks_profiling.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/basic_blocks_profiling.cpp