PragmaParser Class Reference
Main class for parsing: contains the context associated with a parsing action and the methods to retrieve all the information.
#include <PragmaParser.hpp>
Public Member Functions
PragmaParser (const pragma_managerRef PM, const ParameterConstRef Param)
Constructor.
~PragmaParser ()
Destructor.
std::string substitutePragmas (const std::string &OldFile)
Substitute the pragmas with proper functions.
Private Member Functions
bool analyze_pragma (std::string &Line)
Retrieve information about a pragma directive when the token `#pragma` has been found.
bool recognize_omp_pragma (std::string &Line)
Retrieve information about a pragma directive when a OpenMP (parallelism) pragma has been found.
bool recognize_mapping_pragma (std::string &Line)
Retrieve information about a pragma directive when a mapping pragma has been found.
bool recognize_call_point_hw_pragma (std::string &line) const
Retrieve information about a pragma directive of type pragma map call_point_hw.
bool recognize_issue_pragma (std::string &Line)
Retrieve information about a pragma directive when an issue pragma has been found.
bool recognize_profiling_pragma (std::string &Line)
Retrieve information about a pragma directive when a profiling pragma has been found.
bool recognize_generic_pragma (std::string &Line)
Retrieve information about a generic pragma directive (i.e., none of the known ones has been detected)
Private Attributes
const pragma_managerRef PM
pointer to the pragma manager datastructure
const int debug_level
current debugging level
const ParameterConstRef Param
reference to the parameter datastructure
unsigned int level
counter for nesting level
std::list< std::string > FloatingPragmas
CustomUnorderedSet< std::string > FunctionPragmas
std::map< unsigned int, std::list< std::string > > OpenPragmas
bool search_function
std::string name_function
Static Private Attributes
static unsigned int number = 0
counter of generic pragma
static unsigned int file_counter = 0
Counter of examined files.
Detailed Description
Main class for parsing: contains the context associated with a parsing action and the methods to retrieve all the information.
Definition at line 68 of file PragmaParser.hpp.
Constructor & Destructor Documentation
PragmaParser()
PragmaParser::PragmaParser (const pragma_managerRef PM, const ParameterConstRef Param)
Constructor.
Parameters
PM is the pragma manager
Param is the set of input parameters
Definition at line 78 of file PragmaParser.cpp.
References PM, THROW_ASSERT, and ~PragmaParser().
 PragmaParser()
PragmaParser::~PragmaParser () [default]
Destructor.
Referenced by PragmaParser().
Member Function Documentation
analyze_pragma()
bool PragmaParser::analyze_pragma (std::string & Line) [private]
Retrieve information about a pragma directive when the token `#pragma` has been found.
parallelism pragmas
mapping pragmas
call_point_hw pragmas
issue pragmas
profiling pragmas
generate_hw pragmas
generic pragmas
Definition at line 193 of file PragmaParser.cpp.
References Param, recognize_call_point_hw_pragma(), recognize_generic_pragma(), recognize_issue_pragma(), recognize_mapping_pragma(), recognize_omp_pragma(), recognize_profiling_pragma(), and STR_CST_pragma_keyword_omp.
Referenced by substitutePragmas().
recognize_call_point_hw_pragma()
bool PragmaParser::recognize_call_point_hw_pragma (std::string & line) const [private]
Retrieve information about a pragma directive of type pragma map call_point_hw.
Parameters
line is the line containing the pragma; it will be replaced con a function call
Definition at line 310 of file PragmaParser.cpp.
References SplitString(), STR_CST_pragma_function_single_line_two_arguments, STR_CST_pragma_keyword_call_point_hw, STR_CST_pragma_keyword_map, and THROW_ASSERT.
Referenced by analyze_pragma().
recognize_generic_pragma()
bool PragmaParser::recognize_generic_pragma (std::string & Line) [private]
Retrieve information about a generic pragma directive (i.e., none of the known ones has been detected)
Definition at line 358 of file PragmaParser.cpp.
References FunctionPragmas, level, number, PM, and search_function.
Referenced by analyze_pragma().
recognize_issue_pragma()
bool PragmaParser::recognize_issue_pragma (std::string & Line) [private]
Retrieve information about a pragma directive when an issue pragma has been found.
Definition at line 344 of file PragmaParser.cpp.
References FunctionPragmas, and search_function.
Referenced by analyze_pragma().
recognize_mapping_pragma()
bool PragmaParser::recognize_mapping_pragma (std::string & Line) [private]
Retrieve information about a pragma directive when a mapping pragma has been found.
Definition at line 327 of file PragmaParser.cpp.
References FunctionPragmas, level, number, PM, and search_function.
Referenced by analyze_pragma().
recognize_omp_pragma()
bool PragmaParser::recognize_omp_pragma (std::string & Line) [private]
Retrieve information about a pragma directive when a OpenMP (parallelism) pragma has been found.
Definition at line 244 of file PragmaParser.cpp.
References debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FloatingPragmas, FunctionPragmas, pragma_manager::GetOmpPragmaType(), INDENT_DBG_MEX, pragma_manager::OMP_ATOMIC, pragma_manager::OMP_BARRIER, pragma_manager::OMP_CRITICAL, pragma_manager::OMP_DECLARE_SIMD, pragma_manager::omp_directive_keywords, pragma_manager::OMP_FOR, pragma_manager::OMP_PARALLEL, pragma_manager::OMP_PARALLEL_FOR, pragma_manager::OMP_PARALLEL_SECTIONS, pragma_manager::OMP_SECTION, pragma_manager::OMP_SECTIONS, pragma_manager::OMP_SIMD, pragma_manager::OMP_TARGET, pragma_manager::OMP_TASK, pragma_manager::OMP_UNKNOWN, search_function, STR_CST_pragma_function_single_line_one_argument, STR_CST_pragma_function_start, STR_CST_pragma_keyword_omp, THROW_ERROR, and THROW_UNREACHABLE.
Referenced by analyze_pragma().
recognize_profiling_pragma()
bool PragmaParser::recognize_profiling_pragma (std::string & Line) [private]
Retrieve information about a pragma directive when a profiling pragma has been found.
Definition at line 351 of file PragmaParser.cpp.
References FunctionPragmas, and search_function.
Referenced by analyze_pragma().
substitutePragmas()
std::string PragmaParser::substitutePragmas (const std::string & OldFile)
Substitute the pragmas with proper functions.
Parameters
OldFile is the name of the file to be analyzed and substituted
Returns
the name of the new file coming from the substitution
search for function name
Pragma associated with called are added by pragma_analysis
print out the new pragma line
manage nesting levels
increment line number
Definition at line 86 of file PragmaParser.cpp.
References analyze_pragma(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, file_counter, FloatingPragmas, FunctionPragmas, GetLeafFileName(), INDENT_DBG_MEX, level, name_function, OpenPragmas, Param, PM, search_function, STR_CST_pragma_function_end, STR_CST_pragma_prefix, and THROW_ASSERT.
Field Documentation
debug_level
const int PragmaParser::debug_level [private]
current debugging level
Definition at line 78 of file PragmaParser.hpp.
Referenced by recognize_omp_pragma(), and substitutePragmas().
file_counter
unsigned int PragmaParser::file_counter = 0 [static], [private]
Counter of examined files.
Definition at line 133 of file PragmaParser.hpp.
Referenced by substitutePragmas().
FloatingPragmas
std::list<std::string> PragmaParser::FloatingPragmas [private]
Definition at line 122 of file PragmaParser.hpp.
Referenced by recognize_omp_pragma(), and substitutePragmas().
FunctionPragmas
CustomUnorderedSet<std::string> PragmaParser::FunctionPragmas [private]
Definition at line 124 of file PragmaParser.hpp.
Referenced by recognize_generic_pragma(), recognize_issue_pragma(), recognize_mapping_pragma(), recognize_omp_pragma(), recognize_profiling_pragma(), and substitutePragmas().
level
unsigned int PragmaParser::level [private]
counter for nesting level
Definition at line 120 of file PragmaParser.hpp.
Referenced by recognize_generic_pragma(), recognize_mapping_pragma(), and substitutePragmas().
name_function
std::string PragmaParser::name_function [private]
Definition at line 130 of file PragmaParser.hpp.
Referenced by substitutePragmas().
number
unsigned int PragmaParser::number = 0 [static], [private]
counter of generic pragma
Autoheader include.
Header include Constants include Parameter include Pragma include Utility include
Definition at line 72 of file PragmaParser.hpp.
Referenced by recognize_generic_pragma(), and recognize_mapping_pragma().
OpenPragmas
std::map<unsigned int, std::list<std::string> > PragmaParser::OpenPragmas [private]
Definition at line 126 of file PragmaParser.hpp.
Referenced by substitutePragmas().
Param
const ParameterConstRef PragmaParser::Param [private]
reference to the parameter datastructure
Definition at line 81 of file PragmaParser.hpp.
Referenced by analyze_pragma(), and substitutePragmas().
PM
const pragma_managerRef PragmaParser::PM [private]
pointer to the pragma manager datastructure
Definition at line 75 of file PragmaParser.hpp.
Referenced by PragmaParser(), recognize_generic_pragma(), recognize_mapping_pragma(), and substitutePragmas().
search_function
bool PragmaParser::search_function [private]
Definition at line 128 of file PragmaParser.hpp.
Referenced by recognize_generic_pragma(), recognize_issue_pragma(), recognize_mapping_pragma(), recognize_omp_pragma(), recognize_profiling_pragma(), and substitutePragmas().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/pragma/PragmaParser.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/pragma/PragmaParser.cpp