ControllerCreatorBaseStep Class Reference
Generic class managing controller creation algorithms.
#include <controller_creator_base_step.hpp>
Public Member Functions
ControllerCreatorBaseStep (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
~ControllerCreatorBaseStep () override
Destructor.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
virtual void add_common_ports (structural_objectRef circuit)
This member function adds the standard ports (clock, reset, done and command ones) to a circuit.
Protected Attributes
structural_managerRef SM
structural representation of the resulting controller circuit
std::map< generic_objRef, unsigned int > out_ports
This contains all the ports that go from the controller to the datapath, used to enable the registers and to control muxes in the datapath.
std::map< generic_objRef, unsigned int > in_ports
These are the lines that go from the datapath to the controller containing results of conditions of constructs such as for, if etc.
std::map< vertex, unsigned int > cond_ports
This is the same as in_ports except that the first element is of type vertex.
std::map< vertex, unsigned int > mu_ports
This map put into relation fsm states and alldone multi_unbounded ports.
std::map< vertex, generic_objRef > cond_obj
Map between the operation vertex and the corresponding control port.
unsigned int out_num
Initialized after add_common_ports is called.
unsigned int in_num
Initialized after add_common_ports is called.
Private Member Functions
void add_clock_reset (structural_objectRef circuit)
Adds the clock and reset ports to a circuit.
void add_done_port (structural_objectRef circuit)
Adds the done port to a circuit.
void add_start_port (structural_objectRef circuit)
Adds the start port to a circuit.
void add_command_ports (structural_objectRef circuit)
Adds the command ports to a circuit.
Additional Inherited Members
Detailed Description
Generic class managing controller creation algorithms.
Definition at line 78 of file controller_creator_base_step.hpp.
Constructor & Destructor Documentation
ControllerCreatorBaseStep()
ControllerCreatorBaseStep::ControllerCreatorBaseStep (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
implemented controllers
Definition at line 69 of file controller_creator_base_step.cpp.
References ~ControllerCreatorBaseStep().
 ControllerCreatorBaseStep()
ControllerCreatorBaseStep::~ControllerCreatorBaseStep () [override], [default]
Destructor.
Referenced by ControllerCreatorBaseStep().
Member Function Documentation
add_clock_reset()
void ControllerCreatorBaseStep::add_clock_reset (structural_objectRef circuit) [private]
Adds the clock and reset ports to a circuit.
Called by add_common_ports
Parameters
circuit the circuit where to add the clock and reset ports
define boolean type for the clock and reset signals
add clock port
add entry in in_port_map between port id and port index
add reset port
Definition at line 134 of file controller_creator_base_step.cpp.
References structural_manager::add_port(), CLOCK_PORT_NAME, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, port_o::IN, PRINT_DBG_MEX, RESET_PORT_NAME, and SM.
Referenced by add_common_ports().
add_command_ports()
void ControllerCreatorBaseStep::add_command_ports (structural_objectRef circuit) [private]
Adds the command ports to a circuit.
Called by add_common_ports Command ports are of three types:
Selectors to enable functional units in the datapath, these go from the controller to the datapath
Selectors of mux in the datapath, these go from the controller to the datapath
Conditions, used to modify instruction flow in constructs such as for, if, while, these go in the opposite direction, from the datapath to the controller
Parameters
circuit the circuit where to add the command ports
define boolean type for command signals
connections from controller to datapath
operations signals have not to be added at this point
they represent commands to multiplexers or write enables to registers
connections from datapath to controller
operation modifying the control flow (e.g., if, switch, ...)
multi bit selector representing the evaluation of a switch
single bit selector representing the evaluation of a condition
Definition at line 172 of file controller_creator_base_step.cpp.
References structural_manager::add_port(), FunctionBehavior::CGetBehavioralHelper(), cond_obj, cond_ports, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, hls::functionId, HLSFunctionStep::funId, conn_binding::GetSelectors(), HLSFunctionStep::HLS, HLS_step::HLSMgr, conn_binding::IN, port_o::IN, in_num, in_ports, INDENT_DBG_MEX, mu_ports, commandport_obj::MULTI_UNBOUNDED, commandport_obj::MULTIIF, commandport_obj::OPERATION, conn_binding::OUT, port_o::OUT, out_num, out_ports, hls::Rconn, SM, commandport_obj::SWITCH, and THROW_ASSERT.
Referenced by add_common_ports().
add_common_ports()
void ControllerCreatorBaseStep::add_common_ports (structural_objectRef circuit) [protected], [virtual]
This member function adds the standard ports (clock, reset, done and command ones) to a circuit.
Parameters
circuit it is the datastructure of the component where to add these ports
Reimplemented in controller_cs.
Definition at line 120 of file controller_creator_base_step.cpp.
References add_clock_reset(), add_command_ports(), add_done_port(), add_start_port(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, and PRINT_DBG_MEX.
Referenced by controller_cs::add_common_ports(), and fsm_controller::InternalExec().
add_done_port()
void ControllerCreatorBaseStep::add_done_port (structural_objectRef circuit) [private]
Adds the done port to a circuit.
Called by add_common_ports The done port appears to go high once all the calculation of a function are completed
Parameters
circuit the circuit where to add the done port
define boolean type for the done port
add done port
Definition at line 152 of file controller_creator_base_step.cpp.
References structural_manager::add_port(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, DONE_PORT_NAME, port_o::OUT, PRINT_DBG_MEX, and SM.
Referenced by add_common_ports().
add_start_port()
void ControllerCreatorBaseStep::add_start_port (structural_objectRef circuit) [private]
Adds the start port to a circuit.
Called by add_common_ports
Parameters
circuit the circuit where to add the start port
define boolean type for the start port
add the start port
Definition at line 162 of file controller_creator_base_step.cpp.
References structural_manager::add_port(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, port_o::IN, PRINT_DBG_MEX, SM, and START_PORT_NAME.
Referenced by add_common_ports().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ControllerCreatorBaseStep::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 76 of file controller_creator_base_step.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void ControllerCreatorBaseStep::Initialize () [override], [protected], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Test on previuos steps. They check if schedule, register and connection binding have been performed. Otherwise, the circuit cannot be created.
Reimplemented from DesignFlowStep.
Definition at line 100 of file controller_creator_base_step.cpp.
References cond_obj, cond_ports, hls::controller, HLSFunctionStep::HLS, in_num, in_ports, HLSFunctionStep::Initialize(), out_num, out_ports, hls::Param, hls::Rconn, hls::Rreg, hls::Rsch, SM, and THROW_ASSERT.
Field Documentation
cond_obj
std::map<vertex, generic_objRef> ControllerCreatorBaseStep::cond_obj [protected]
Map between the operation vertex and the corresponding control port.
Definition at line 135 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), and Initialize().
cond_ports
std::map<vertex, unsigned int> ControllerCreatorBaseStep::cond_ports [protected]
This is the same as in_ports except that the first element is of type vertex.
Each element is obtained by calling GetPointer<commandport_obj>(j->second)->get_vertex() to the elements into in_ports. The second element is the same number of the generic_objRef into in_ports to which get_vertex() was called Initialized after add_common_ports is called
Definition at line 131 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), fsm_controller::create_state_machine(), and Initialize().
in_num
unsigned int ControllerCreatorBaseStep::in_num [protected]
Initialized after add_common_ports is called.
It represents the current number of input ports (in_num==in_ports.size()==cond_ports.size())
Definition at line 143 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), fsm_controller::create_state_machine(), and Initialize().
in_ports
std::map<generic_objRef, unsigned int> ControllerCreatorBaseStep::in_ports [protected]
These are the lines that go from the datapath to the controller containing results of conditions of constructs such as for, if etc.
The key is the object representing the port, while the value is the integer value associated with the port. Initialized only after add_common_ports is called
Definition at line 125 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), and Initialize().
mu_ports
std::map<vertex, unsigned int> ControllerCreatorBaseStep::mu_ports [protected]
This map put into relation fsm states and alldone multi_unbounded ports.
Definition at line 133 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), and fsm_controller::create_state_machine().
out_num
unsigned int ControllerCreatorBaseStep::out_num [protected]
Initialized after add_common_ports is called.
It represents the current number of output ports (out_num==out_ports.size())
Definition at line 139 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), fsm_controller::create_state_machine(), and Initialize().
out_ports
std::map<generic_objRef, unsigned int> ControllerCreatorBaseStep::out_ports [protected]
This contains all the ports that go from the controller to the datapath, used to enable the registers and to control muxes in the datapath.
The first element in the map is the port object. Despite its type is generic_objRef it appears that this map contains only objects of type commandport_obj. This is suggested by the dynamic cast hidden behind a GetPointer call in controller::add_command_ports(). The second element of the map is the integer identifier of the port Initialized only after add_common_ports is called
Definition at line 119 of file controller_creator_base_step.hpp.
Referenced by add_command_ports(), fsm_controller::create_state_machine(), and Initialize().
SM
structural_managerRef ControllerCreatorBaseStep::SM [protected]
structural representation of the resulting controller circuit
Definition at line 111 of file controller_creator_base_step.hpp.
Referenced by add_clock_reset(), add_command_ports(), controller_cs::add_correct_transition_memory(), fsm_controller::add_correct_transition_memory(), add_done_port(), controller_cs::add_selector_register_file_port(), add_start_port(), Initialize(), and fsm_controller::InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/controller_creator_base_step.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/controller_creator_base_step.cpp