EdgeCWriter Class Reference
Class use to write the C code with instrumented edges.
#include <edge_c_writer.hpp>
Public Member Functions
EdgeCWriter (const application_managerConstRef _AppM, const InstructionWriterRef instruction_writer, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef Param, bool verbose=true)
Constructor of the class.
~EdgeCWriter () override
Destructor.
const std::map< unsigned int, std::map< unsigned int, unsigned int > > & CGetFunctionLoopToId () const
Returns the map which associates to each loop a unique id.
void Initialize () override
Initialize data structure.
void WriteHeader () override
Writes the header of the file.
Protected Member Functions
virtual void print_edge (EdgeDescriptor e, unsigned int index)
Dump operation requested for instrument an edges.
virtual void print_end_path (unsigned int fun_id, unsigned int loop_id)
Print operations needed to store into symbol table information about last path.
virtual void print_loop_switching (EdgeDescriptor e)
Print operation requested for record information about a path which exit from a loop and immediately enter in another.
void writeRoutineInstructions_rec (vertex current_vertex, bool bracket)
Write recursively instructions belonging to a basic block of task or of a function.
void writeRoutineInstructions (const unsigned int function_index, const OpVertexSet &instructions, const var_pp_functorConstRef variableFunctor, vertex bb_start=NULL_VERTEX, CustomOrderedSet< vertex > bb_end=CustomOrderedSet< vertex >()) override
Writes the instructions of the current routine, being it a task or a function of the original program.
virtual void print_loop_ending (EdgeDescriptor e)
Dump operations requested for record information about a loop path which ends.
virtual void print_loop_escaping (EdgeDescriptor e)
Dump operations requested for record information about a path which exit from a loop.
virtual void print_loop_starting (EdgeDescriptor e)
Dump initializations of variable for recording a loop path.
Protected Attributes
std::map< vertex, EdgeDescriptor > local_inc
Increment which should be added before the label in a basic block.
std::set< EdgeDescriptor, ltedge< BBGraph > > dumped_edges
Set of already dumped edges.
std::map< unsigned int, std::map< unsigned int, unsigned int > > fun_loop_to_index
Map a pair function - loop to an unique index.
unsigned int counter
The size of fun_loop_to_index.
BBGraphConstRef support_cfg
Special control flow graphs.
unsigned int fun_id
Index of the current function.
Additional Inherited Members
Detailed Description
Class use to write the C code with instrumented edges.
Definition at line 73 of file edge_c_writer.hpp.
Constructor & Destructor Documentation
EdgeCWriter()
EdgeCWriter::EdgeCWriter (const application_managerConstRef _AppM, const InstructionWriterRef _instruction_writer, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _Param, bool _verbose = true)
Constructor of the class.
Header include.
Parameters
AppM is the application manager
instruction_writer is the instruction writer to use to print the single instruction
indented_output_stream is the output stream
Param is the set of parameters
verbose tells if annotations
algorithms/dominance include Backend include Behavior include Graph include Parameter include tree includes STL include utility include
Definition at line 78 of file edge_c_writer.cpp.
References CWriter::debug_level, GET_CLASS, CWriter::Param, and ~EdgeCWriter().
 EdgeCWriter()
EdgeCWriter::~EdgeCWriter () [override], [default]
Destructor.
Referenced by EdgeCWriter().
Member Function Documentation
CGetFunctionLoopToId()
const std::map< unsigned int, std::map< unsigned int, unsigned int > > & EdgeCWriter::CGetFunctionLoopToId () const
Returns the map which associates to each loop a unique id.
Returns
the map which associates to each loop a unique id
Definition at line 1314 of file edge_c_writer.cpp.
References fun_loop_to_index.
Initialize()
void EdgeCWriter::Initialize () [override], [virtual]
Initialize data structure.
Reimplemented from CWriter.
Definition at line 86 of file edge_c_writer.cpp.
References CWriter::AppM, FunctionBehavior::CGetLoops(), counter, fun_loop_to_index, and CWriter::Initialize().
print_edge()
void EdgeCWriter::print_edge (EdgeDescriptor e, unsigned int index) [protected], [virtual]
Dump operation requested for instrument an edges.
Parameters
e is the edge
index is the index of the variable to be incremented
Reimplemented in BasicBlocksProfilingCWriter.
Definition at line 105 of file edge_c_writer.cpp.
References dumped_edges.
Referenced by writeRoutineInstructions_rec().
print_end_path()
void EdgeCWriter::print_end_path (unsigned int fun_id, unsigned int loop_id) [protected], [virtual]
Print operations needed to store into symbol table information about last path.
Parameters
fun_id is the index of the function
loop_id is the index of the loop
Definition at line 110 of file edge_c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
print_loop_ending()
void EdgeCWriter::print_loop_ending (EdgeDescriptor e) [protected], [virtual]
Dump operations requested for record information about a loop path which ends.
Parameters
e is the feedback or outgoing edge
Reimplemented in BasicBlocksProfilingCWriter.
Definition at line 114 of file edge_c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
print_loop_escaping()
void EdgeCWriter::print_loop_escaping (EdgeDescriptor e) [protected], [virtual]
Dump operations requested for record information about a path which exit from a loop.
Parameters
e is the feedback or outgoing edge
Reimplemented in BasicBlocksProfilingCWriter.
Definition at line 118 of file edge_c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
print_loop_starting()
void EdgeCWriter::print_loop_starting (EdgeDescriptor e) [protected], [virtual]
Dump initializations of variable for recording a loop path.
Parameters
e is the incoming edged
Reimplemented in BasicBlocksProfilingCWriter.
Definition at line 122 of file edge_c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
print_loop_switching()
void EdgeCWriter::print_loop_switching (EdgeDescriptor e) [protected], [virtual]
Print operation requested for record information about a path which exit from a loop and immediately enter in another.
Parameters
e is the edge
Reimplemented in BasicBlocksProfilingCWriter.
Definition at line 126 of file edge_c_writer.cpp.
Referenced by writeRoutineInstructions_rec().
WriteHeader()
void EdgeCWriter::WriteHeader () [override], [virtual]
Writes the header of the file.
Reimplemented from CWriter.
Definition at line 1319 of file edge_c_writer.cpp.
References IndentedOutputStream::Append(), and CWriter::indented_output_stream.
writeRoutineInstructions()
void EdgeCWriter::writeRoutineInstructions (const unsigned int function_index, const OpVertexSet & instructions, const var_pp_functorConstRef variableFunctor, vertex bb_start = NULL_VERTEX, CustomOrderedSet< vertex > bb_end = CustomOrderedSet<vertex>()) [override], [protected], [virtual]
Writes the instructions of the current routine, being it a task or a function of the original program.
Parameters
function_index is the index of the function
instructions is the instructions which have to be printed
var_pp_functor is the variable functor
bb_start is the first basic block to be printed
bb_end is the set of first basic block not to be printed
Then I compute all the labels associated with a basic block with more than one entering edge.
set of basic block already analyzed
store for which basic block the goto has been used
basic block frontier over which writeRoutineInstructions_rec cannot go.
some statements can be in entry
Reimplemented from CWriter.
Definition at line 1191 of file edge_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, CWriter::basic_blocks_labels, CWriter::bb_analyzed, CWriter::bb_frontier, CWriter::bb_label_counter, FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), CWriter::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, CWriter::dominators, FunctionBehavior::dominators, dumped_edges, bloc::EXIT_BLOCK_ID, FunctionBehavior::FBB, FunctionBehavior::FCFG, fun_id, refcount< T >::get(), BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), BehavioralHelper::get_label_name(), GET_TYPE, CWriter::goto_list, INDENT_DBG_MEX, CWriter::indented_output_stream, local_inc, CWriter::local_rec_function_behavior, CWriter::local_rec_instructions, CWriter::local_rec_variableFunctor, CWriter::post_dominators, FunctionBehavior::post_dominators, FunctionBehavior::PPG, PROFILING_EC, BehavioralHelper::start_with_a_label(), support_cfg, THROW_ERROR_CODE, TYPE_ENTRY, CWriter::WriteFile(), and writeRoutineInstructions_rec().
writeRoutineInstructions_rec()
void EdgeCWriter::writeRoutineInstructions_rec (vertex current_vertex, bool bracket) [protected]
Write recursively instructions belonging to a basic block of task or of a function.
Parameters
function_behavior is the function to which instructions belong
current_vertex is the basic block which is being printed
instructions are the instructions which belongs to this task/function
bracket tells if bracket should be added before and after this basic block
the entry vertex
the exit vertex
get immediate post-dominator
compute the last statement
check the feasibility
check for basic block label
print each instruction
fill the renamin table in case is needed
We can print results of split of phi nodes if they have not yet been printed and if label has already been printed (or there was not any label to be printed)
If there is not any label to be printed, label_has_to_be_printed is already false, otherwise the label will be printed during this loop iteration
in case we have phi nodes we check if some assignments should be printed
Feedback edge on the false path of an if
Target is not a while or a for
now we can analyze the following basic blocks
then adjust post dominator
now we can analyze the following basic blocks
added a fake indent
in case we have phi nodes we check if some assignments should be printed
Last basic block of a while/for loop
added a fake indent
added a fake indent
Definition at line 130 of file edge_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, CWriter::basic_block_prefix, CWriter::basic_block_tail, CWriter::basic_blocks_labels, CWriter::bb_analyzed, CWriter::bb_frontier, CFG_SELECTOR, BBGraph::CGetBBEdgeInfo(), FunctionBehavior::CGetBBGraph(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetLoops(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), BehavioralHelper::clear_renaming_table(), CWriter::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, DOALL_LOOP, CWriter::dominators, BehavioralHelper::end_with_a_cond_or_goto(), FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionBehavior::FCFG, fun_id, fun_loop_to_index, BehavioralHelper::get_function_index(), dominance< GraphObj >::get_immediate_dominator(), GET_INDEX_NODE, tree_node::get_kind(), GET_NAME, GET_TYPE, graph::GetSelector(), CWriter::goto_list, INDENT_DBG_MEX, CWriter::indented_output_stream, CWriter::instrWriter, local_inc, CWriter::local_rec_function_behavior, CWriter::local_rec_instructions, CWriter::local_rec_variableFunctor, NULL_VERTEX, CWriter::post_dominators, BehavioralHelper::print_constant(), print_edge(), print_end_path(), print_loop_ending(), print_loop_escaping(), print_loop_starting(), print_loop_switching(), BehavioralHelper::PrintVariable(), PROFILING_EC, BehavioralHelper::rename_a_variable(), CWriter::renaming_table, BehavioralHelper::start_with_a_label(), STR, support_cfg, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, CWriter::TM, TYPE_FOR, TYPE_IF, TYPE_INIT, TYPE_LABEL, TYPE_LAST_OP, TYPE_MULTIIF, TYPE_RET, TYPE_SWITCH, TYPE_VPHI, TYPE_WHILE, and CWriter::verbose.
Referenced by writeRoutineInstructions().
Field Documentation
counter
unsigned int EdgeCWriter::counter [protected]
The size of fun_loop_to_index.
Definition at line 126 of file edge_c_writer.hpp.
Referenced by Initialize().
dumped_edges
std::set<EdgeDescriptor, ltedge<BBGraph> > EdgeCWriter::dumped_edges [protected]
Set of already dumped edges.
Definition at line 120 of file edge_c_writer.hpp.
Referenced by BasicBlocksProfilingCWriter::print_edge(), print_edge(), and writeRoutineInstructions().
fun_id
unsigned int EdgeCWriter::fun_id [protected]
Index of the current function.
Definition at line 132 of file edge_c_writer.hpp.
Referenced by BasicBlocksProfilingCWriter::print_edge(), writeRoutineInstructions(), and writeRoutineInstructions_rec().
fun_loop_to_index
std::map<unsigned int, std::map<unsigned int, unsigned int> > EdgeCWriter::fun_loop_to_index [protected]
Map a pair function - loop to an unique index.
Definition at line 123 of file edge_c_writer.hpp.
Referenced by CGetFunctionLoopToId(), Initialize(), and writeRoutineInstructions_rec().
local_inc
std::map<vertex, EdgeDescriptor> EdgeCWriter::local_inc [protected]
Increment which should be added before the label in a basic block.
Definition at line 117 of file edge_c_writer.hpp.
Referenced by writeRoutineInstructions(), and writeRoutineInstructions_rec().
support_cfg
BBGraphConstRef EdgeCWriter::support_cfg [protected]
Special control flow graphs.
Definition at line 129 of file edge_c_writer.hpp.
Referenced by BasicBlocksProfilingCWriter::print_edge(), writeRoutineInstructions(), and writeRoutineInstructions_rec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/edge_c_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/edge_c_writer.cpp