StateInfo Struct Reference
Structure holding information about a node into graph.
#include <state_transition_graph.hpp>
Public Member Functions
void print (std::ostream &os, const int detail_level) const override
Implementation of print method for this kind of node.
StateInfo ()
Constructor.
Data Fields
Wrefcount< const HLS_manager > HLSMgr
Weak Reference to function behavior.
unsigned int funId
function identifier of the function from which the state has been derived
std::string name
string used to give a label to the state
std::list< vertex > executing_operations
set of operation vertices which require inputs in this state
std::list< vertex > starting_operations
set of operation vertices which starts in this state
std::list< vertex > ending_operations
set of operation vertices completing their execution in this state
std::list< vertex > onfly_operations
set of operation vertices already in execution at the beginning of this state
CustomOrderedSet< unsigned int > BB_ids
set of BB ids associated with the state
bool is_dummy
flag to check if the state is dummy or not
bool is_duplicated
flag to check if the state is duplicated or not
unsigned int sourceBb
ID of the bb edge associated with the phi operation.
bool isOriginalState
flag to check if the state is duplicated and the original one
vertex clonedState
pointer to the cloned state
bool all_paths
this state is duplicated but manage of path incoming in the phis
CustomOrderedSet< unsigned int > moved_op_def_set
set of ssa vars defined in the state by the moved operations
CustomOrderedSet< unsigned int > moved_op_use_set
set of ssa vars used in the state by the moved operations
std::list< vertex > moved_exec_op
set of moved operations in execution
std::list< vertex > moved_ending_op
set of moved operations ending in this state
Detailed Description
Structure holding information about a node into graph.
A node represent an execution state of the machine. It contains operations to be started when execution will reach this state.
Definition at line 81 of file state_transition_graph.hpp.
Constructor & Destructor Documentation
StateInfo()
StateInfo::StateInfo () [inline]
Constructor.
Definition at line 147 of file state_transition_graph.hpp.
Member Function Documentation
print()
void StateInfo::print (std::ostream & os, const int detail_level) const [override], [virtual]
Implementation of print method for this kind of node.
. include
It simply prints the list of operations contained into this state
Parameters
os is the stream reference where you want to print
behavior includes hls include hls/scheduling tree include utility include
Reimplemented from NodeInfo.
Definition at line 75 of file state_transition_graph.cpp.
References FunctionBehavior::BB, BB_ids, FunctionBehavior::CFG, ending_operations, executing_operations, funId, GET_NAME, GET_TYPE, HLSMgr, Wrefcount< T >::lock(), name, NumberToString(), BehavioralHelper::print_vertex(), STR, TYPE_ENTRY, TYPE_EXIT, and TYPE_STORE.
Field Documentation
all_paths
bool StateInfo::all_paths
this state is duplicated but manage of path incoming in the phis
Definition at line 123 of file state_transition_graph.hpp.
BB_ids
CustomOrderedSet<unsigned int> StateInfo::BB_ids
set of BB ids associated with the state
Definition at line 105 of file state_transition_graph.hpp.
Referenced by print().
clonedState
vertex StateInfo::clonedState
pointer to the cloned state
Definition at line 120 of file state_transition_graph.hpp.
ending_operations
std::list<vertex> StateInfo::ending_operations
set of operation vertices completing their execution in this state
Definition at line 99 of file state_transition_graph.hpp.
Referenced by print().
executing_operations
std::list<vertex> StateInfo::executing_operations
set of operation vertices which require inputs in this state
Definition at line 93 of file state_transition_graph.hpp.
Referenced by print().
funId
unsigned int StateInfo::funId
function identifier of the function from which the state has been derived
Definition at line 87 of file state_transition_graph.hpp.
Referenced by print().
HLSMgr
Wrefcount<const HLS_manager> StateInfo::HLSMgr
Weak Reference to function behavior.
Definition at line 84 of file state_transition_graph.hpp.
Referenced by print().
is_dummy
bool StateInfo::is_dummy
flag to check if the state is dummy or not
Definition at line 108 of file state_transition_graph.hpp.
is_duplicated
bool StateInfo::is_duplicated
flag to check if the state is duplicated or not
Definition at line 111 of file state_transition_graph.hpp.
isOriginalState
bool StateInfo::isOriginalState
flag to check if the state is duplicated and the original one
Definition at line 117 of file state_transition_graph.hpp.
moved_ending_op
std::list<vertex> StateInfo::moved_ending_op
set of moved operations ending in this state
Definition at line 135 of file state_transition_graph.hpp.
moved_exec_op
std::list<vertex> StateInfo::moved_exec_op
set of moved operations in execution
Definition at line 132 of file state_transition_graph.hpp.
moved_op_def_set
CustomOrderedSet<unsigned int> StateInfo::moved_op_def_set
set of ssa vars defined in the state by the moved operations
Definition at line 126 of file state_transition_graph.hpp.
moved_op_use_set
CustomOrderedSet<unsigned int> StateInfo::moved_op_use_set
set of ssa vars used in the state by the moved operations
Definition at line 129 of file state_transition_graph.hpp.
name
std::string StateInfo::name
string used to give a label to the state
Definition at line 90 of file state_transition_graph.hpp.
Referenced by print().
onfly_operations
std::list<vertex> StateInfo::onfly_operations
set of operation vertices already in execution at the beginning of this state
Definition at line 102 of file state_transition_graph.hpp.
sourceBb
unsigned int StateInfo::sourceBb
ID of the bb edge associated with the phi operation.
Definition at line 114 of file state_transition_graph.hpp.
starting_operations
std::list<vertex> StateInfo::starting_operations
set of operation vertices which starts in this state
Definition at line 96 of file state_transition_graph.hpp.
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/state_transition_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/state_transition_graph.cpp