BlockFix Class Reference
Restructure the tree control flow graph.
#include <block_fix.hpp>
Public Member Functions
BlockFix (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~BlockFix () override
Destructor.
DesignFlowStep_Status InternalExec () override
Updates the tree to have a more compliant CFG.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Static Private Attributes
static bool tree_dumped
flag to check if initial tree has been dumped
Additional Inherited Members
Detailed Description
Restructure the tree control flow graph.
Definition at line 66 of file block_fix.hpp.
Constructor & Destructor Documentation
BlockFix()
BlockFix::BlockFix (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
header include
Parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior includes STD include tree includes utility include
Definition at line 69 of file block_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~BlockFix().
 BlockFix()
BlockFix::~BlockFix () [override], [default]
Destructor.
Referenced by BlockFix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionFrontendFlowStep::FunctionRelationship > > BlockFix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 77 of file block_fix.cpp.
References CALL_EXPR_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status BlockFix::InternalExec () [override], [virtual]
Updates the tree to have a more compliant CFG.
Returns
the exit status of this step
set of predecessor of exit is missing! TO BE CHECK
Checking if there are gimple_labels which can be removed Computing reachable labels
Implements FunctionFrontendFlowStep.
Definition at line 103 of file block_fix.cpp.
References FrontendFlowStep::AppM, BB_ENTRY, BB_EXIT, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, sl, SUCCESS, and THROW_ASSERT.
Field Documentation
tree_dumped
bool BlockFix::tree_dumped [static], [private]
flag to check if initial tree has been dumped
Definition at line 70 of file block_fix.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/block_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/block_fix.cpp