CalledFunctionsVisitor Struct Reference
Visitor to identify the list of called functions.
#include <call_graph_manager.hpp>
Public Member Functions
CalledFunctionsVisitor (const bool allow_recursive_functions, const CallGraphManager *call_graph_manager, CustomOrderedSet< unsigned int > &body_functions, CustomOrderedSet< unsigned int > &library_functions)
Constructor.
void back_edge (const EdgeDescriptor &edge, const CallGraph &call_graph)
void finish_vertex (const vertex &u, const CallGraph &call_graph)
Function called when a vertex has been finished.
Private Attributes
const bool allow_recursive_functions
True if recursive calls are allowed.
const CallGraphManager * call_graph_manager
The call graph manager.
CustomOrderedSet< unsigned int > & body_functions
The list of encountered body functions.
CustomOrderedSet< unsigned int > & library_functions
The list of encountered library functions.
Detailed Description
Visitor to identify the list of called functions.
Definition at line 288 of file call_graph_manager.hpp.
Constructor & Destructor Documentation
CalledFunctionsVisitor()
CalledFunctionsVisitor::CalledFunctionsVisitor (const bool allow_recursive_functions, const CallGraphManager * call_graph_manager, CustomOrderedSet< unsigned int > & body_functions, CustomOrderedSet< unsigned int > & library_functions)
Constructor.
Parameters
allow_recursive_functions tells if recursive functions are allowed
call_graph_manager is the call graph manager
body_functions is where results will be stored
library_functions is where results will be stored
Definition at line 536 of file call_graph_manager.cpp.
Member Function Documentation
back_edge()
void CalledFunctionsVisitor::back_edge (const EdgeDescriptor & edge, const CallGraph & call_graph)
Definition at line 541 of file call_graph_manager.cpp.
References allow_recursive_functions, call_graph_manager, CallGraph::CGetCallGraphInfo(), CallGraphManager::get_function(), and THROW_ERROR.
finish_vertex()
void CalledFunctionsVisitor::finish_vertex (const vertex & u, const CallGraph & call_graph)
Function called when a vertex has been finished.
Parameters
u is the vertex
call_graph is the call graph
Definition at line 553 of file call_graph_manager.cpp.
References body_functions, CallGraph::CGetCallGraphInfo(), and library_functions.
Field Documentation
allow_recursive_functions
const bool CalledFunctionsVisitor::allow_recursive_functions [private]
True if recursive calls are allowed.
Definition at line 292 of file call_graph_manager.hpp.
Referenced by back_edge().
body_functions
CustomOrderedSet<unsigned int>& CalledFunctionsVisitor::body_functions [private]
The list of encountered body functions.
Definition at line 298 of file call_graph_manager.hpp.
Referenced by finish_vertex().
call_graph_manager
const CallGraphManager* CalledFunctionsVisitor::call_graph_manager [private]
The call graph manager.
Definition at line 295 of file call_graph_manager.hpp.
Referenced by back_edge().
library_functions
CustomOrderedSet<unsigned int>& CalledFunctionsVisitor::library_functions [private]
The list of encountered library functions.
Definition at line 301 of file call_graph_manager.hpp.
Referenced by finish_vertex().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph_manager.cpp