InitializeHLS Class Reference
#include <initialize_hls.hpp>
Public Member Functions
InitializeHLS (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~InitializeHLS () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Additional Inherited Members
Detailed Description
Definition at line 45 of file initialize_hls.hpp.
Constructor & Destructor Documentation
InitializeHLS()
InitializeHLS::InitializeHLS (const ParameterConstRef _parameters, const HLS_managerRef _HLS_mgr, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
DesignFlowManagerConstRef is the design flow manager
. include circuit include HLS include technology include technology/physical_library include tree include
Definition at line 69 of file initialize_hls.cpp.
References INITIALIZE_HLS, and ~InitializeHLS().
 InitializeHLS()
InitializeHLS::~InitializeHLS () [override], [default]
Destructor.
Referenced by InitializeHLS().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > InitializeHLS::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 76 of file initialize_hls.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and WHOLE_APPLICATION.
Initialize()
void InitializeHLS::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
NOTE: this overrides HLSFunctionStep::Initialize which cannot be invoked since HLS has not yet been set
Reimplemented from DesignFlowStep.
Definition at line 104 of file initialize_hls.cpp.
InternalExec()
DesignFlowStep_Status InitializeHLS::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 109 of file initialize_hls.cpp.
References technology_manager::add_operation(), HLS_manager::create_HLS(), HLSFunctionStep::funId, technology_manager::get_fu(), HLSFunctionStep::HLS, HLS_step::HLSMgr, tree_helper::name_function(), tree_helper::normalized_ID(), DesignFlowStep::parameters, functional_unit::set_clock_period(), functional_unit::set_clock_period_resource_fraction(), SUCCESS, and WORK_LIBRARY.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow/initialize_hls.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/hls_flow/initialize_hls.cpp