data_o Class Reference
This class describes a generic data declaration object.
#include <structural_objects.hpp>
Public Member Functions
data_o (int debug_level, const structural_objectRef o)
Constructor.
~data_o () override=default
destructor
void copy (structural_objectRef dest) const override
Perform a copy of the data.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the data declaration object (for debug purpose).
Additional Inherited Members
Detailed Description
This class describes a generic data declaration object.
Definition at line 1266 of file structural_objects.hpp.
Constructor & Destructor Documentation
data_o()
data_o::data_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the data declaration object.
Definition at line 1678 of file structural_objects.cpp.
 data_o()
data_o::~data_o () [override], [default]
destructor
Member Function Documentation
copy()
void data_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the data.
Parameters
dest destination object.
Reimplemented from structural_object.
Definition at line 1688 of file structural_objects.cpp.
References structural_object::copy().
find_isomorphic()
structural_objectRef data_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Definition at line 1693 of file structural_objects.cpp.
References THROW_ERROR.
find_member()
structural_objectRef data_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
This method throw and error since does not have associated any structural object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 1682 of file structural_objects.cpp.
References THROW_ERROR.
print()
void data_o::print (std::ostream & os) const [override], [virtual]
Print the data declaration object (for debug purpose).
Parameters
os is an output stream.
Reimplemented from structural_object.
Definition at line 1710 of file structural_objects.cpp.
References structural_object::PP, and structural_object::print().
xload()
void data_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
Reimplemented from structural_object.
Definition at line 1699 of file structural_objects.cpp.
References structural_object::xload().
xwrite()
void data_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Definition at line 1704 of file structural_objects.cpp.
References xml_child::add_child_element(), structural_object::get_kind_text(), and structural_object::xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp