RawGraph Struct Reference
#include <graph.hpp>
Public Member Functions
RawGraph (GraphInfoRef g_info)
Constructor.
~RawGraph ()=default
Destructor.
boost::graph_traits< boost_raw_graph >::vertex_descriptor AddVertex (const NodeInfoRef v_info)
void RemoveVertex (boost::graph_traits< boost_raw_graph >::vertex_descriptor v)
boost::graph_traits< boost_raw_graph >::edge_descriptor AddEdge (boost::graph_traits< boost_raw_graph >::vertex_descriptor src, boost::graph_traits< boost_raw_graph >::vertex_descriptor tgt, const EdgeInfoRef e_info)
void RemoveEdge (boost::graph_traits< boost_raw_graph >::edge_descriptor e)
void RemoveEdge (boost::graph_traits< boost_raw_graph >::vertex_descriptor src, boost::graph_traits< boost_raw_graph >::vertex_descriptor tgt)
Detailed Description
Definition at line 89 of file graph.hpp.
Constructor & Destructor Documentation
RawGraph()
RawGraph::RawGraph (GraphInfoRef g_info) [inline], [explicit]
Constructor.
Parameters
g_info is the property associated with the graph
Definition at line 96 of file graph.hpp.
References ~RawGraph().
 RawGraph()
RawGraph::~RawGraph () [default]
Destructor.
Referenced by RawGraph().
Member Function Documentation
AddEdge()
boost::graph_traits<boost_raw_graph>::edge_descriptor RawGraph::AddEdge (boost::graph_traits< boost_raw_graph >::vertex_descriptor src, boost::graph_traits< boost_raw_graph >::vertex_descriptor tgt, const EdgeInfoRef e_info) [inline]
Definition at line 128 of file graph.hpp.
References THROW_ASSERT.
Referenced by RecursivelyUnfold().
AddVertex()
boost::graph_traits<boost_raw_graph>::vertex_descriptor RawGraph::AddVertex (const NodeInfoRef v_info) [inline]
Definition at line 106 of file graph.hpp.
References index, and test_panda::type.
Referenced by graphs_collection::GetSelector(), and RecursivelyUnfold().
RemoveEdge() [1/2]
void RawGraph::RemoveEdge (boost::graph_traits< boost_raw_graph >::edge_descriptor e) [inline]
Definition at line 139 of file graph.hpp.
RemoveEdge() [2/2]
void RawGraph::RemoveEdge (boost::graph_traits< boost_raw_graph >::vertex_descriptor src, boost::graph_traits< boost_raw_graph >::vertex_descriptor tgt) [inline]
Definition at line 144 of file graph.hpp.
References THROW_ASSERT.
RemoveVertex()
void RawGraph::RemoveVertex (boost::graph_traits< boost_raw_graph >::vertex_descriptor v) [inline]
Definition at line 116 of file graph.hpp.
References index, and test_panda::type.
Referenced by graphs_collection::InternalAddEdge().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/graph/graph.hpp