allocation Class Reference
This wrapper collects all the methods used by the High-level synthesis classes to retrieve information about the functional units.
#include <allocation.hpp>
Public Member Functions
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void PrintInitialIR () const override
Dump the initial intermediate representation.
 Constructors and destructors.
allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type=HLSFlowStep_Type::ALLOCATION)
Constructor.
~allocation () override
Destructor.
Protected Member Functions
technology_nodeRef get_fu (const std::string &fu_name)
Returns the technology_node associated with the given operation.
std::string get_compliant_pipelined_unit (double clock, const std::string &pipe_parameter, const technology_nodeRef current_fu, const std::string &curr_op, const std::string &library_name, const std::string &template_suffix, unsigned int module_prec)
In case the current functional unit has pipelined operations then it return an id identifying the most compliant functional unit given the current clock period.
technology_nodeRef extract_bambu_provided (const std::string &library_name, operation *curr_op, const std::string &bambu_provided_resource)
void set_number_channels (unsigned int fu_name, unsigned int n_ports)
set the number of ports associated with the functional unit
double get_execution_time_dsp_modified (const unsigned int fu_name, const technology_nodeRef &node_op) const
double get_stage_period_dsp_modified (const unsigned int fu_name, const technology_nodeRef &node_op) const
void add_proxy_function_module (const HLS_constraintsRef HLS_C, technology_nodeRef techNode_obj, const std::string &orig_fun_name)
Add a proxy function to the WORK library.
void add_proxy_function_wrapper (const std::string &library_name, technology_nodeRef techNode_obj, const std::string &orig_fun_name)
Add a proxy wrapper to the WORK library.
void BuildProxyWrapper (functional_unit *current_fu, const std::string &orig_fun_name, const std::string &orig_library_name)
Build the proxy wrapper.
void BuildProxyFunctionVerilog (functional_unit *orig_fu)
Build the proxy function in Verilog.
void BuildProxyFunctionVHDL (functional_unit *orig_fu)
Build the proxy function in VHDL.
void BuildProxyFunction (functional_unit *orig_fu)
Build the proxy function.
void add_tech_constraint (technology_nodeRef cur_fu, unsigned int tech_constrain_value, unsigned int pos, bool proxy_constrained)
void add_resource_to_fu_list (std::string channels_type, const OpGraphConstRef g, technology_nodeRef current_fu, CustomOrderedSet< vertex > vertex_analysed, node_kind_prec_infoRef node_info, unsigned int current_id, CustomOrderedSet< vertex >::const_iterator vert, const std::vector< std::string > &libraries, bool isMemory, std::string bambu_provided_resource, operation *curr_op, std::string specialized_fuName, bool predicate_2, std::string current_op, HLS_manager::io_binding_type constant_id, bool varargs_fu, unsigned int l, std::string memory_ctrl_type, std::map< std::string, technology_nodeRef > new_fu, unsigned int tech_constrain_value)
bool check_templated_units (double clock_period, node_kind_prec_infoRef node_info, const library_managerRef library, technology_nodeRef current_fu, operation *curr_op)
bool check_for_memory_compliancy (bool Has_extern_allocated_data, technology_nodeRef current_fu, const std::string &memory_ctrl_type, std::string channels_type)
bool check_type_and_precision (operation *curr_op, node_kind_prec_infoRef node_info)
bool check_proxies (const library_managerRef library, std::string fu_name)
bool check_generated_bambu_flopoco (bool skip_softfloat_resources, structural_managerRef structManager_obj, std::string &bambu_provided_resource, bool skip_flopoco_resources, technology_nodeRef current_fu)
bool is_ram_not_timing_compliant (const HLS_constraintsRef HLS_C, unsigned int var, technology_nodeRef current_fu)
std::string get_synch_ram_latency (const std::string &ram_template, const std::string &latency_postfix, const HLS_constraintsRef HLS_C, unsigned int var)
virtual void IntegrateTechnologyLibraries ()
Integrate technology libraries with special functional units.
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
std::map< unsigned int, unsigned int > last_bb_ver
AllocationInformationRef allocation_information
The allocation solution.
std::map< std::string, std::string > precomputed_pipeline_unit
store the precomputed pipeline unit: given a functional unit it return the pipeline id compliant
std::map< technology_nodeRef, std::map< unsigned int, std::map< HLS_manager::io_binding_type, unsigned int > > > fu_list
HLS_targetRef HLS_T
The HLS target.
technology_managerRef TM
The technology manager.
Friends
struct updatecopy_HLS_constraints_functor
Additional Inherited Members
Detailed Description
This wrapper collects all the methods used by the High-level synthesis classes to retrieve information about the functional units.
Definition at line 102 of file allocation.hpp.
Constructor & Destructor Documentation
allocation()
allocation::allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type = HLSFlowStep_Type::ALLOCATION)
Constructor.
Parameters
design_flow_manager is the design flow manager
Definition at line 130 of file allocation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and ~allocation().
 allocation()
allocation::~allocation () [override], [default]
Destructor.
Referenced by allocation().
Member Function Documentation
add_proxy_function_module()
void allocation::add_proxy_function_module (const HLS_constraintsRef HLS_C, technology_nodeRef techNode_obj, const std::string & orig_fun_name) [protected]
Add a proxy function to the WORK library.
add description and license
add a fictitious operation to allow bus merging
automatically build proxy description
Definition at line 696 of file allocation.cpp.
References structural_manager::add_NP_functionality(), technology_manager::add_operation(), structural_manager::add_port(), structural_manager::add_port_vector(), BuildProxyFunction(), CLOCK_PORT_NAME, structural_object::copy(), time_model::create_model(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, ENCODE_FU_LIB, structural_manager::get_circ(), technology_manager::get_fu(), structural_object::get_id(), structural_object::get_kind(), technology_node::get_name(), NP_functionality::get_NP_functionality(), target_manager::get_target_device(), target_device::get_type(), structural_object::get_typeRef(), HLS_T, port_o::IN, is_other_port(), NP_functionality::LIBRARY, port_o::OUT, DesignFlowStep::parameters, port_o::PARAMETRIC_PORT, port_vector_o_K, PRINT_DBG_MEX, PROXY_LIBRARY, PROXY_PREFIX, RESET_PORT_NAME, structural_manager::set_top_info(), TM, and top().
Referenced by IntegrateTechnologyLibraries().
add_proxy_function_wrapper()
void allocation::add_proxy_function_wrapper (const std::string & library_name, technology_nodeRef techNode_obj, const std::string & orig_fun_name) [protected]
Add a proxy wrapper to the WORK library.
add description and license
add a fictitious operation to allow bus merging
automatically build proxy wrapper HDL description
Definition at line 411 of file allocation.cpp.
References structural_manager::add_NP_functionality(), technology_manager::add_operation(), structural_manager::add_port(), structural_manager::add_port_vector(), BuildProxyWrapper(), CLOCK_PORT_NAME, structural_object::copy(), time_model::create_model(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_manager::get_circ(), technology_manager::get_fu(), structural_object::get_id(), structural_object::get_kind(), technology_node::get_name(), NP_functionality::get_NP_functionality(), target_manager::get_target_device(), target_device::get_type(), structural_object::get_typeRef(), HLS_T, port_o::IN, is_other_port(), NP_functionality::LIBRARY, MEMORY_PARAMETER, port_o::OUT, DesignFlowStep::parameters, port_o::PARAMETRIC_PORT, port_vector_o_K, PRINT_DBG_MEX, PROXY_LIBRARY, PROXY_PREFIX, RESET_PORT_NAME, structural_manager::set_top_info(), TM, and WRAPPED_PROXY_PREFIX.
Referenced by IntegrateTechnologyLibraries().
add_resource_to_fu_list()
void allocation::add_resource_to_fu_list (std::string channels_type, const OpGraphConstRef g, technology_nodeRef current_fu, CustomOrderedSet< vertex > vertex_analysed, node_kind_prec_infoRef node_info, unsigned int current_id, CustomOrderedSet< vertex >::const_iterator vert, const std::vector< std::string > & libraries, bool isMemory, std::string bambu_provided_resource, operation * curr_op, std::string specialized_fuName, bool predicate_2, std::string current_op, HLS_manager::io_binding_type constant_id, bool varargs_fu, unsigned int l, std::string memory_ctrl_type, std::map< std::string, technology_nodeRef > new_fu, unsigned int tech_constrain_value) [protected]
add_tech_constraint()
void allocation::add_tech_constraint (technology_nodeRef cur_fu, unsigned int tech_constrain_value, unsigned int pos, bool proxy_constrained) [protected]
check resource constraints for indirect memory accesses
Definition at line 884 of file allocation.cpp.
References allocation_information, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, technology_node::get_name(), AllocationInformation::get_number_channels(), INDENT_DBG_MEX, AllocationInformation::is_indirect_access_memory_unit(), AllocationInformation::list_of_FU, PRINT_DBG_MEX, STR, and AllocationInformation::tech_constraints.
Referenced by InternalExec().
BuildProxyFunction()
void allocation::BuildProxyFunction (functional_unit * orig_fu) [protected]
Build the proxy function.
Definition at line 670 of file allocation.cpp.
References BuildProxyFunctionVerilog(), BuildProxyFunctionVHDL(), DesignFlowStep::parameters, SYSTEM_VERILOG, THROW_UNREACHABLE, VERILOG, and VHDL.
Referenced by add_proxy_function_module(), and extract_bambu_provided().
BuildProxyFunctionVerilog()
void allocation::BuildProxyFunctionVerilog (functional_unit * orig_fu) [protected]
Build the proxy function in Verilog.
Definition at line 545 of file allocation.cpp.
References add_escape(), structural_manager::add_NP_functionality(), structural_manager::add_port(), CLOCK_PORT_NAME, language_writer::create_writer(), structural_object::find_member(), fix_identifier(), structural_manager::get_circ(), structural_object::get_id(), functional_unit::get_operations(), HLS_step::HLSMgr, port_o::IN, is_other_port(), DesignFlowStep::parameters, port_o_K, PROXY_PREFIX, RESET_PORT_NAME, START_PORT_NAME, top(), VERILOG, and NP_functionality::VERILOG_PROVIDED.
Referenced by BuildProxyFunction().
BuildProxyFunctionVHDL()
void allocation::BuildProxyFunctionVHDL (functional_unit * orig_fu) [protected]
Build the proxy function in VHDL.
Definition at line 606 of file allocation.cpp.
References add_escape(), structural_manager::add_NP_functionality(), structural_manager::add_port(), CLOCK_PORT_NAME, language_writer::create_writer(), structural_object::find_member(), fix_identifier(), structural_manager::get_circ(), structural_object::get_id(), functional_unit::get_operations(), GET_TYPE_SIZE, HLS_step::HLSMgr, port_o::IN, is_other_port(), DesignFlowStep::parameters, port_o_K, PROXY_PREFIX, RESET_PORT_NAME, START_PORT_NAME, top(), VHDL, and NP_functionality::VHDL_PROVIDED.
Referenced by BuildProxyFunction().
BuildProxyWrapper()
void allocation::BuildProxyWrapper (functional_unit * current_fu, const std::string & orig_fun_name, const std::string & orig_library_name) [protected]
Build the proxy wrapper.
Definition at line 282 of file allocation.cpp.
References CLOCK_PORT_NAME, connectClockAndReset(), structural_object::find_member(), structural_manager::get_circ(), library_manager::get_fu(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), technology_manager::get_library_manager(), functional_unit::get_operations(), module::get_out_port(), module::get_out_port_size(), structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_T, port_o::IN, library_manager::is_fu(), is_other_port(), MUX_GATE_STD, OR_GATE_STD, port_o_K, port_vector_o_K, memory::propagate_memory_parameters(), PROXY_PREFIX, RESET_PORT_NAME, structural_object::set_id(), STD_GET_SIZE, THROW_ASSERT, TM, and WRAPPED_PROXY_PREFIX.
Referenced by add_proxy_function_wrapper(), and extract_bambu_provided().
check_for_memory_compliancy()
bool allocation::check_for_memory_compliancy (bool Has_extern_allocated_data, technology_nodeRef current_fu, const std::string & memory_ctrl_type, std::string channels_type) [protected]
LOAD/STORE operations allocated on memories have been already allocated
LOAD/STORE operations on proxys have been already managed
Definition at line 965 of file allocation.cpp.
References CHANNELS_TYPE_MEM_ACC_CS, CHANNELS_TYPE_MEM_ACC_NN, CHANNELS_TYPE_MEM_ACC_P1N, MEM_ACC_11, MEM_ACC_CS, MEM_ACC_N1, MEM_ACC_NN, MEM_ACC_P1N, MEMORY_CTRL_TYPE_DPROXY, MEMORY_CTRL_TYPE_DPROXYN, MEMORY_CTRL_TYPE_PROXY, MEMORY_CTRL_TYPE_PROXYN, DesignFlowStep::parameters, THROW_ERROR, and THROW_UNREACHABLE.
Referenced by InternalExec().
check_generated_bambu_flopoco()
bool allocation::check_generated_bambu_flopoco (bool skip_softfloat_resources, structural_managerRef structManager_obj, std::string & bambu_provided_resource, bool skip_flopoco_resources, technology_nodeRef current_fu) [protected]
generated cannot be directly considered for allocation
Definition at line 1099 of file allocation.cpp.
References NP_functionality::BAMBU_PROVIDED, NP_functionality::FLOPOCO_PROVIDED, structural_manager::get_circ(), get_fu(), and NP_functionality::get_NP_functionality().
Referenced by InternalExec().
check_proxies()
bool allocation::check_proxies (const library_managerRef library, std::string fu_name) [protected]
Definition at line 1076 of file allocation.cpp.
References HLSFunctionStep::funId, library_manager::get_library_name(), HLS_step::HLSMgr, PROXY_LIBRARY, PROXY_PREFIX, THROW_ASSERT, and WRAPPED_PROXY_PREFIX.
Referenced by InternalExec().
check_templated_units()
bool allocation::check_templated_units (double clock_period, node_kind_prec_infoRef node_info, const library_managerRef library, technology_nodeRef current_fu, operation * curr_op) [protected]
Definition at line 906 of file allocation.cpp.
References allocation_information, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, get_compliant_pipelined_unit(), time_model::get_cycles(), library_manager::get_library_name(), operation::get_name(), INDENT_DBG_MEX, operation::pipe_parameters, PRINT_DBG_MEX, STR, THROW_WARNING, operation::time_m, and AllocationInformation::time_m_execution_time().
Referenced by InternalExec().
check_type_and_precision()
bool allocation::check_type_and_precision (operation * curr_op, node_kind_prec_infoRef node_info) [protected]
Definition at line 1060 of file allocation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, and operation::is_type_supported().
Referenced by InternalExec().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > allocation::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 156 of file allocation.cpp.
References CALLED_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLS_BIT_VALUE, HLS_SYNTHESIS_FLOW, INITIALIZE_HLS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, THROW_UNREACHABLE, and WHOLE_APPLICATION.
extract_bambu_provided()
technology_nodeRef allocation::extract_bambu_provided (const std::string & library_name, operation * curr_op, const std::string & bambu_provided_resource) [protected]
Definition at line 185 of file allocation.cpp.
References BuildProxyFunction(), BuildProxyWrapper(), operation::commutative, HLSFunctionStep::funId, technology_manager::get_fu(), library_manager::get_fu(), technology_manager::get_library_manager(), operation::get_name(), HLS_step::HLSMgr, library_manager::is_fu(), operation::pipe_parameters, PROXY_PREFIX, operation::supported_types, THROW_ASSERT, TM, WORK_LIBRARY, and WRAPPED_PROXY_PREFIX.
Referenced by InternalExec().
get_compliant_pipelined_unit()
std::string allocation::get_compliant_pipelined_unit (double clock, const std::string & pipe_parameter, const technology_nodeRef current_fu, const std::string & curr_op, const std::string & library_name, const std::string & template_suffix, unsigned int module_prec) [protected]
In case the current functional unit has pipelined operations then it return an id identifying the most compliant functional unit given the current clock period.
in case no pipelined version exist it returns the one not pipelined
in case clock is not compatible with any of the pipelined version it returns the fastest pipelined version available
Definition at line 1973 of file allocation.cpp.
References allocation_information, clb_model::DSP, AllocationInformation::DSP_allocation_coefficient, AllocationInformation::DSP_y_db, AllocationInformation::DSPs_margin, AllocationInformation::DSPs_margin_stage, NP_functionality::FLOPOCO_PROVIDED, functional_unit_template::FU, structural_manager::get_circ(), technology_manager::get_fu(), NP_functionality::get_NP_functionality(), functional_unit::get_operation(), target_manager::get_technology_manager(), HLS_T, is_a_skip_operation(), max(), DesignFlowStep::parameters, precomputed_pipeline_unit, SplitString(), STR, THROW_ASSERT, THROW_WARNING, AllocationInformation::time_m_execution_time(), and AllocationInformation::time_m_stage_period().
Referenced by check_templated_units().
get_execution_time_dsp_modified()
double allocation::get_execution_time_dsp_modified (const unsigned int fu_name, const technology_nodeRef & node_op) const [protected]
get_fu()
technology_nodeRef allocation::get_fu (const std::string & fu_name) [protected]
Returns the technology_node associated with the given operation.
Parameters
fu_name is the string representing the name of the unit
Definition at line 2105 of file allocation.cpp.
References technology_manager::get_fu(), technology_manager::get_library(), target_manager::get_technology_manager(), and HLS_T.
Referenced by check_generated_bambu_flopoco(), get_synch_ram_latency(), IntegrateTechnologyLibraries(), and InternalExec().
get_stage_period_dsp_modified()
double allocation::get_stage_period_dsp_modified (const unsigned int fu_name, const technology_nodeRef & node_op) const [protected]
get_synch_ram_latency()
std::string allocation::get_synch_ram_latency (const std::string & ram_template, const std::string & latency_postfix, const HLS_constraintsRef HLS_C, unsigned int var) [protected]
Definition at line 2131 of file allocation.cpp.
References allocation_information, get_fu(), AllocationInformation::get_latency_string(), is_ram_not_timing_compliant(), and AllocationInformation::sync_ram_var_latency.
Referenced by IntegrateTechnologyLibraries().
HasToBeExecuted()
bool allocation::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from HLSFunctionStep.
Definition at line 2424 of file allocation.cpp.
References HLSFunctionStep::funId, FunctionBehavior::GetBBVersion(), HLSFunctionStep::HasToBeExecuted(), HLS_step::HLSMgr, and last_bb_ver.
Initialize()
void allocation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from HLSFunctionStep.
Definition at line 138 of file allocation.cpp.
References allocation_information, hls::allocation_information, AllocationInformation::Clear(), fu_list, HLSFunctionStep::funId, target_manager::get_technology_manager(), HLSFunctionStep::HLS, HLS_T, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), AllocationInformation::Initialize(), DesignFlowStep::parameters, and TM.
IntegrateTechnologyLibraries()
void allocation::IntegrateTechnologyLibraries () [protected], [virtual]
Integrate technology libraries with special functional units.
check clock constraints compatibility
allocate proxies
add shared functions to the technology manager
allocate it
add shared function proxies to the technology manager
Reimplemented in OmpAllocation.
Definition at line 2150 of file allocation.cpp.
References add_proxy_function_module(), add_proxy_function_wrapper(), allocation_information, ARRAY_1D_STD_BRAM, ARRAY_1D_STD_BRAM_N1, ARRAY_1D_STD_BRAM_N1_SDS, ARRAY_1D_STD_BRAM_N1_SDS_BUS, ARRAY_1D_STD_BRAM_NN, ARRAY_1D_STD_BRAM_NN_SDS, ARRAY_1D_STD_BRAM_NN_SDS_BUS, ARRAY_1D_STD_BRAM_SDS, ARRAY_1D_STD_BRAM_SDS_BUS, ARRAY_1D_STD_DISTRAM_N1_SDS, ARRAY_1D_STD_DISTRAM_NN_SDS, ARRAY_1D_STD_DISTRAM_SDS, AllocationInformation::can_be_asynchronous_ram(), FunctionBehavior::CGetBehavioralHelper(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DPROXY_CTRL, DPROXY_CTRLN, ENCODE_FU_LIB, fu_list, HLSFunctionStep::funId, AllocationInformation::get_correction_time(), get_fu(), technology_manager::get_fu(), library_manager::get_fu(), AllocationInformation::get_latency_string(), technology_manager::get_library(), technology_manager::get_library_manager(), technology_node::get_name(), AllocationInformation::get_number_fu_types(), AllocationInformation::get_setup_hold_time(), get_synch_ram_latency(), HLSFunctionStep::HLS, hls::HLS_C, HLS_step::HLSMgr, AllocationInformation::id_to_fu_names, INFINITE_UINT, is_ram_not_timing_compliant(), AllocationInformation::list_of_FU, MEM_ACC_11, MEM_ACC_N1, MEM_ACC_NN, MEM_ACC_P1N, AllocationInformation::memory_units, AllocationInformation::memory_units_sizes, DesignFlowStep::parameters, AllocationInformation::precision_map, PRINT_DBG_MEX, BehavioralHelper::PrintVariable(), PROXY_CTRL, PROXY_CTRLN, PROXY_LIBRARY, AllocationInformation::proxy_memory_units, PROXY_PREFIX, AllocationInformation::proxy_wrapped_units, set_number_channels(), tree_helper::size(), STR, AllocationInformation::tech_constraints, THROW_ASSERT, THROW_ERROR, AllocationInformation::time_m_execution_time(), TM, AllocationInformation::vars_to_memory_units, and WRAPPED_PROXY_PREFIX.
Referenced by OmpAllocation::IntegrateTechnologyLibraries(), and InternalExec().
InternalExec()
DesignFlowStep_Status allocation::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
skip library of internal components
check proxy functions
check for generated module and bambu/flopoco resources
Check for correct type and precision
in case the operation is pipelined check the clock period
These data structure are filled only once
Implements HLSFunctionStep.
Definition at line 1143 of file allocation.cpp.
References technology_manager::add(), add_tech_constraint(), ADDR_EXPR, ADDR_EXPR_STD, ALL_BRAM, allocation_information, ASSERT_EXPR, ASSERT_EXPR_REAL_STD, ASSERT_EXPR_SIGNED_STD, ASSERT_EXPR_UNSIGNED_STD, ASSIGN, ASSIGN_REAL_STD, ASSIGN_SIGNED_STD, ASSIGN_UNSIGNED_STD, ASSIGN_VEC_SIGNED_STD, ASSIGN_VEC_UNSIGNED_STD, ASSIGN_VECTOR_BOOL_STD, HLSFunctionStep::bb_version, AllocationInformation::binding, BIVECTOR_CONVERTER_STD, BUVECTOR_CONVERTER_STD, FunctionBehavior::CFG, FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), tree_manager::CGetTreeNode(), CHANNELS_TYPE_MEM_ACC_NN, CHANNELS_TYPE_MEM_ACC_P1N, check_for_memory_compliancy(), check_generated_bambu_flopoco(), check_proxies(), check_templated_units(), check_type_and_precision(), CLOCK_PORT_NAME, CONVERT_EXPR, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, ENCODE_FU_LIB, encode_op_type(), encode_op_type_prec(), ENTRY, ENTRY_ID, ENTRY_STD, EXIT, EXIT_ID, EXIT_STD, EXT_PIPELINED_BRAM, extract_bambu_provided(), AllocationInformation::extract_bambu_provided_name(), EXTRACT_BIT_EXPR, EXTRACT_BIT_EXPR_SIGNED_STD, EXTRACT_BIT_EXPR_UNSIGNED_STD, FFDATA_CONVERTER_STD, fu_list, functional_unit_K, hls::functionId, HLSFunctionStep::funId, AllocationInformation::fus_to_node_id, tree_helper::get_base_index(), structural_manager::get_circ(), AllocationInformation::get_DSPs(), get_fu(), technology_manager::get_fu(), library_manager::get_fu(), AllocationInformation::get_fu_name(), structural_object::get_id(), GET_INDEX_NODE, technology_manager::get_library(), library_manager::get_library_fu(), technology_manager::get_library_list(), technology_manager::get_library_manager(), GET_NAME, technology_node::get_name(), GET_NODE, AllocationInformation::get_number_fu_types(), target_manager::get_target_device(), tree_manager::get_tree_node_const(), GET_TYPE, target_device::get_type(), tree_helper::get_type_index(), tree_helper::get_type_node(), FunctionBehavior::GetBBVersion(), tree_helper::GetElements(), AllocationInformation::GetNodeTypePrec(), GIMPLE_ASM, GIMPLE_GOTO, GIMPLE_GOTO_STD, GIMPLE_LABEL, GIMPLE_LABEL_STD, GIMPLE_NOP, GIMPLE_NOP_STD, GIMPLE_PHI, GIMPLE_PHI_STD, GIMPLE_PRAGMA, GIMPLE_PRAGMA_STD, GIMPLE_RETURN, GIMPLE_RETURN_STD, HLSFunctionStep::HLS, hls::HLS_C, HLS_T, HLS_step::HLSMgr, AllocationInformation::id_to_fu_names, IICONVERTER_EXPR_STD, IIDATA_CONVERTER_STD, INDENT_DBG_MEX, INDENT_OUT_MEX, INFINITE_UINT, insert(), IntegrateTechnologyLibraries(), INTERFACE_LIBRARY, INTERN_UNALIGNED, tree_helper::is_a_complex(), tree_helper::is_a_pointer(), tree_helper::is_a_vector(), tree_helper::is_an_enum(), tree_helper::is_bool(), tree_helper::is_int(), tree_helper::is_real(), tree_helper::is_unsigned(), AllocationInformation::is_vertex_bounded_rel, IUCONVERTER_EXPR_STD, IUDATA_CONVERTER_STD, last_bb_ver, AllocationInformation::list_of_FU, LUT_EXPR, LUT_EXPR_STD, AllocationInformation::memory_units, MULTI_READ_COND, MULTI_READ_COND_STD, AllocationInformation::n_complex_operations, AllocationInformation::node_id_to_fus, NOP, NOP_EXPR, NOP_STD, tree_helper::normalized_ID(), hls::operations, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, DesignFlowStep::parameters, AllocationInformation::precision_map, AllocationInformation::print_allocated_resources(), print_cpu_time(), PRINT_DBG_MEX, AllocationInformation::proxy_function_units, PROXY_LIBRARY, AllocationInformation::proxy_memory_units, PROXY_PREFIX, AllocationInformation::proxy_wrapped_units, READ_COND, READ_COND_STD, RESET_PORT_NAME, set_number_channels(), AllocationInformation::simple_pointer_plus_expr, AllocationInformation::single_bool_test_cond_expr_units, tree_helper::size(), START_PORT_NAME, START_TIME, STOP_TIME, STR, SUCCESS, SWITCH_COND, SWITCH_COND_STD, AllocationInformation::tech_constraints, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, AllocationInformation::time_m_stage_period(), TM, tree_node::ToString(), TYPE_LOAD, TYPE_MEMCPY, TYPE_STORE, UICONVERTER_EXPR_STD, UIDATA_CONVERTER_STD, UUCONVERTER_EXPR_STD, UUDATA_CONVERTER_STD, AllocationInformation::vars_to_memory_units, VIEW_CONVERT_EXPR, VIEW_CONVERT_STD_INT, VIEW_CONVERT_STD_REAL, VIEW_CONVERT_STD_UINT, WORK_LIBRARY, and WRAPPED_PROXY_PREFIX.
is_ram_not_timing_compliant()
bool allocation::is_ram_not_timing_compliant (const HLS_constraintsRef HLS_C, unsigned int var, technology_nodeRef current_fu) [protected]
Definition at line 2113 of file allocation.cpp.
References allocation_information, AllocationInformation::estimate_muxNto1_delay(), functional_unit::get_operation(), AllocationInformation::get_setup_hold_time(), HLS_step::HLSMgr, DesignFlowStep::parameters, and AllocationInformation::time_m_execution_time().
Referenced by get_synch_ram_latency(), and IntegrateTechnologyLibraries().
PrintInitialIR()
void allocation::PrintInitialIR () const [override], [virtual]
Dump the initial intermediate representation.
Reimplemented from DesignFlowStep.
Definition at line 2447 of file allocation.cpp.
References HLSFunctionStep::GetName(), DesignFlowStep::parameters, technology_manager::print(), and TM.
set_number_channels()
void allocation::set_number_channels (unsigned int fu_name, unsigned int n_ports) [protected]
set the number of ports associated with the functional unit
Parameters
fu_name is the functional unit id
n_ports is the number of ports
Definition at line 2100 of file allocation.cpp.
References allocation_information, and AllocationInformation::nports_map.
Referenced by IntegrateTechnologyLibraries(), and InternalExec().
Friends And Related Function Documentation
updatecopy_HLS_constraints_functor
friend struct updatecopy_HLS_constraints_functor [friend]
Definition at line 109 of file allocation.hpp.
Field Documentation
allocation_information
AllocationInformationRef allocation::allocation_information [protected]
The allocation solution.
Definition at line 108 of file allocation.hpp.
Referenced by add_tech_constraint(), check_templated_units(), get_compliant_pipelined_unit(), get_synch_ram_latency(), Initialize(), IntegrateTechnologyLibraries(), InternalExec(), is_ram_not_timing_compliant(), and set_number_channels().
fu_list
std::map<technology_nodeRef, std::map<unsigned int, std::map<HLS_manager::io_binding_type, unsigned int> > > allocation::fu_list [protected]
Definition at line 114 of file allocation.hpp.
Referenced by Initialize(), IntegrateTechnologyLibraries(), and InternalExec().
HLS_T
HLS_targetRef allocation::HLS_T [protected]
The HLS target.
Definition at line 117 of file allocation.hpp.
Referenced by add_proxy_function_module(), add_proxy_function_wrapper(), get_compliant_pipelined_unit(), get_fu(), Initialize(), and InternalExec().
last_bb_ver
std::map<unsigned int, unsigned int> allocation::last_bb_ver [protected]
Definition at line 105 of file allocation.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
precomputed_pipeline_unit
std::map<std::string, std::string> allocation::precomputed_pipeline_unit [protected]
store the precomputed pipeline unit: given a functional unit it return the pipeline id compliant
Definition at line 112 of file allocation.hpp.
Referenced by get_compliant_pipelined_unit().
TM
technology_managerRef allocation::TM [protected]
The technology manager.
Definition at line 120 of file allocation.hpp.
Referenced by add_proxy_function_module(), add_proxy_function_wrapper(), OmpAllocation::AddPandaPthreadMutex(), BuildProxyWrapper(), extract_bambu_provided(), Initialize(), OmpAllocation::IntegrateTechnologyLibraries(), IntegrateTechnologyLibraries(), InternalExec(), and PrintInitialIR().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/allocation.cpp