bipartite_matching< CostFunctor > Class Template Reference
#include <bipartite_matching.hpp>
Public Member Functions
bipartite_matching (size_t _num_rows, size_t _num_cols, const CostFunctor &_cost)
constructor
std::vector< size_t > & get_solution ()
void solve_bipartite_matching ()
Private Member Functions
int get_cost (size_t x, size_t y)
this function returns w_{x,y} givent the cost vector and the actual number of columns
void add_to_tree (size_t x, size_t prevx)
void update_labels ()
Private Attributes
const size_t MINUS_ONE
const size_t MINUS_TWO
size_t num_rows
size_t num_cols
size_t nel
std::vector< int > lx
define labels for x and y
std::vector< int > ly
std::vector< size_t > xy
initialize xy and yx
std::vector< size_t > yx
std::vector< int > slack
std::vector< size_t > slackx
std::vector< bool > S
std::vector< bool > T
std::vector< size_t > prev
const CostFunctor & cost
Detailed Description
template<class CostFunctor>
class bipartite_matching< CostFunctor >
Definition at line 77 of file bipartite_matching.hpp.
Constructor & Destructor Documentation
bipartite_matching()
template<class CostFunctor>
bipartite_matching< CostFunctor >::bipartite_matching (size_t _num_rows, size_t _num_cols, const CostFunctor & _cost) [inline]
constructor
initialize lx given the cost matrix we have we just have to iterate over the row
Definition at line 142 of file bipartite_matching.hpp.
Member Function Documentation
add_to_tree()
template<class CostFunctor>
void bipartite_matching< CostFunctor >::add_to_tree (size_t x, size_t prevx) [inline], [private]
Definition at line 109 of file bipartite_matching.hpp.
get_cost()
template<class CostFunctor>
int bipartite_matching< CostFunctor >::get_cost (size_t x, size_t y) [inline], [private]
this function returns w_{x,y} givent the cost vector and the actual number of columns
Definition at line 102 of file bipartite_matching.hpp.
get_solution()
template<class CostFunctor>
std::vector<size_t>& bipartite_matching< CostFunctor >::get_solution () [inline]
Definition at line 164 of file bipartite_matching.hpp.
Referenced by bipartite_matching_clique_covering< vertex_type >::exec().
solve_bipartite_matching()
template<class CostFunctor>
void bipartite_matching< CostFunctor >::solve_bipartite_matching () [inline]
Definition at line 168 of file bipartite_matching.hpp.
Referenced by bipartite_matching_clique_covering< vertex_type >::exec().
update_labels()
template<class CostFunctor>
void bipartite_matching< CostFunctor >::update_labels () [inline], [private]
Definition at line 122 of file bipartite_matching.hpp.
References max(), and min.
Field Documentation
cost
template<class CostFunctor>
const CostFunctor& bipartite_matching< CostFunctor >::cost [private]
Definition at line 99 of file bipartite_matching.hpp.
lx
template<class CostFunctor>
std::vector<int> bipartite_matching< CostFunctor >::lx [private]
define labels for x and y
Definition at line 86 of file bipartite_matching.hpp.
ly
template<class CostFunctor>
std::vector<int> bipartite_matching< CostFunctor >::ly [private]
Definition at line 87 of file bipartite_matching.hpp.
MINUS_ONE
template<class CostFunctor>
const size_t bipartite_matching< CostFunctor >::MINUS_ONE [private]
Definition at line 80 of file bipartite_matching.hpp.
MINUS_TWO
template<class CostFunctor>
const size_t bipartite_matching< CostFunctor >::MINUS_TWO [private]
Definition at line 81 of file bipartite_matching.hpp.
nel
template<class CostFunctor>
size_t bipartite_matching< CostFunctor >::nel [private]
Definition at line 84 of file bipartite_matching.hpp.
num_cols
template<class CostFunctor>
size_t bipartite_matching< CostFunctor >::num_cols [private]
Definition at line 83 of file bipartite_matching.hpp.
num_rows
template<class CostFunctor>
size_t bipartite_matching< CostFunctor >::num_rows [private]
Definition at line 82 of file bipartite_matching.hpp.
prev
template<class CostFunctor>
std::vector<size_t> bipartite_matching< CostFunctor >::prev [private]
Definition at line 97 of file bipartite_matching.hpp.
S
template<class CostFunctor>
std::vector<bool> bipartite_matching< CostFunctor >::S [private]
Definition at line 95 of file bipartite_matching.hpp.
slack
template<class CostFunctor>
std::vector<int> bipartite_matching< CostFunctor >::slack [private]
Definition at line 93 of file bipartite_matching.hpp.
slackx
template<class CostFunctor>
std::vector<size_t> bipartite_matching< CostFunctor >::slackx [private]
Definition at line 94 of file bipartite_matching.hpp.
T
template<class CostFunctor>
std::vector<bool> bipartite_matching< CostFunctor >::T [private]
Definition at line 96 of file bipartite_matching.hpp.
xy
template<class CostFunctor>
std::vector<size_t> bipartite_matching< CostFunctor >::xy [private]
initialize xy and yx
Definition at line 90 of file bipartite_matching.hpp.
yx
template<class CostFunctor>
std::vector<size_t> bipartite_matching< CostFunctor >::yx [private]
Definition at line 91 of file bipartite_matching.hpp.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/bipartite_matching/bipartite_matching.hpp