/home/osboxes/bambu/PandA-bambu/src/HLS/hls.cpp File Reference
Data structure implementation for high-level synthesis flow.
#include `hls.hpp`
#include `config_HAVE_EXPERIMENTAL.hpp`
#include `hls_target.hpp`
#include `technology_manager.hpp`
#include `hls_constraints.hpp`
#include `conn_binding.hpp`
#include `fu_binding.hpp`
#include `reg_binding.hpp`
#include `schedule.hpp`
#include `standard_hls.hpp`
#include `virtual_hls.hpp`
#include `structural_manager.hpp`
#include `BambuParameter.hpp`
#include `exceptions.hpp`
#include `polixml.hpp`
#include `utility.hpp`
#include `xml_helper.hpp`
#include <boost/lexical_cast.hpp>
#include <utility>
#include `op_graph.hpp`
#include `storage_value_information.hpp`
#include `chaining_information.hpp`
#include `allocation_information.hpp`
#include `dbgPrintHelper.hpp`
Functions
static void computeResources (const structural_objectRef circ, const technology_managerRef TM, std::map< std::string, unsigned int > &resources)
Header include.
Detailed Description
Data structure implementation for high-level synthesis flow.
This file contains all the implementations used by hls class to manage the high level synthesis flow
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Christian Pilato pilato@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
computeResources()
static void computeResources (const structural_objectRef circ, const technology_managerRef TM, std::map< std::string, unsigned int > & resources) [static]
Header include.
Autoheader include HLS/binding/storage_value_insertion includes HLS/chaining_information HLS/module_allocation
Definition at line 234 of file hls.cpp.
References component_o_K, structural_object::get_id(), module::get_internal_object(), module::get_internal_objects_size(), structural_object::get_kind(), technology_manager::get_library(), structural_object::get_typeRef(), structural_type_descriptor::id_type, PROXY_LIBRARY, and WORK_LIBRARY.
Referenced by hls::PrintResources(), and hls::xwrite().