object_visitor Class Reference
object visitor template.
#include <visitor.hpp>
Public Member Functions
virtual ~object_visitor ()
destructor
BOOST_PP_SEQ_FOR_EACH (OPERATOR_MACRO, BOOST_PP_EMPTY, VISITED_OBJ_SEQ1)
virtual template object functor
BOOST_PP_SEQ_FOR_EACH (OPERATOR_MACRO, BOOST_PP_EMPTY, VISITED_OBJ_SEQ2)
Detailed Description
object visitor template.
Specializing this class is possible to traverse a complex set of objects.
Definition at line 105 of file visitor.hpp.
Constructor & Destructor Documentation
 object_visitor()
virtual object_visitor::~object_visitor () [inline], [virtual]
destructor
Definition at line 109 of file visitor.hpp.
References BOOST_PP_SEQ_FOR_EACH(), OPERATOR_MACRO, VISITED_OBJ_SEQ1, and VISITED_OBJ_SEQ2.
Member Function Documentation
BOOST_PP_SEQ_FOR_EACH() [1/2]
object_visitor::BOOST_PP_SEQ_FOR_EACH (OPERATOR_MACRO , BOOST_PP_EMPTY , VISITED_OBJ_SEQ1)
virtual template object functor
Parameters
obj is the object visited
mask control the visit of the object members. the next macro will define a set of virtual function starting from VISITED_OBJ_SEQ1 VISITED_OBJ_SEQ2 following the schema:
virtual void operator()(const VISITED_OBJ * obj, unsigned int & mask) {}
where VISITED_OBJ is taken from the sequence VISITED_OBJ_SEQ1 VISITED_OBJ_SEQ2
Referenced by tree_node_dup::create_tree_node(), tree_node_factory::create_tree_node(), tree_node_index_factory::create_tree_node(), function_decl_refs::function_decl_refs(), tree_node_dup::tree_node_dup(), tree_node_factory::tree_node_factory(), tree_node_finder::tree_node_finder(), tree_node_index_factory::tree_node_index_factory(), tree_node_reached::tree_node_reached(), type_casting::type_casting(), and ~object_visitor().
BOOST_PP_SEQ_FOR_EACH() [2/2]
object_visitor::BOOST_PP_SEQ_FOR_EACH (OPERATOR_MACRO , BOOST_PP_EMPTY , VISITED_OBJ_SEQ2)
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/utility/visitor.hpp