BasicBlocksCfgComputation Class Reference
Superclass include.
#include <basic_blocks_cfg_computation.hpp>
Public Member Functions
BasicBlocksCfgComputation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~BasicBlocksCfgComputation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes the basic block graph structure.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Build call graph structures starting from the tree_manager.
Definition at line 52 of file basic_blocks_cfg_computation.hpp.
Constructor & Destructor Documentation
BasicBlocksCfgComputation()
BasicBlocksCfgComputation::BasicBlocksCfgComputation (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
Param is the set of the parameters
AppM is the application manager
fun_id is the function for which basic block control flow graph has to be built
design_flow_manager is the design flow manager
Header include . include behavior includes design_flow includes frontend_analysis/IR_analysis graph include STD include STL include parser/treegcc include tree include utility include
Definition at line 93 of file basic_blocks_cfg_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~BasicBlocksCfgComputation().
 BasicBlocksCfgComputation()
BasicBlocksCfgComputation::~BasicBlocksCfgComputation () [override], [default]
Destructor.
Referenced by BasicBlocksCfgComputation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BasicBlocksCfgComputation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 101 of file basic_blocks_cfg_computation.cpp.
References COMPLETE_BB_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and VAR_DECL_FIX.
Initialize()
void BasicBlocksCfgComputation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 155 of file basic_blocks_cfg_computation.cpp.
References FunctionFrontendFlowStep::bb_version, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status BasicBlocksCfgComputation::InternalExec () [override], [virtual]
Computes the basic block graph structure.
Returns
the exit status of this step
switch statements
computed goto
multi-way if
Implements FunctionFrontendFlowStep.
Definition at line 166 of file basic_blocks_cfg_computation.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, BB_ENTRY, BB_EXIT, FunctionBehavior::CFG, CFG_SELECTOR, FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, DesignFlowStep::design_flow_manager, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, F_COND, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, Wrefcount< T >::lock(), OPERATIONS_CFG_COMPUTATION, DesignFlowStep::parameters, phi, sl, STR, SUCCESS, T_COND, THROW_ASSERT, and ToString().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/basic_blocks_cfg_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/basic_blocks_cfg_computation.cpp