var_pp_functor Struct Reference
Base class functor used by prettyPrintVertex to print variables.
#include <var_pp_functor.hpp>
Public Member Functions
virtual ~var_pp_functor ()
Destructor.
virtual std::string operator() (unsigned int var) const =0
This functor returns a string representing the variable (usually the name of the variable).
Detailed Description
Base class functor used by prettyPrintVertex to print variables.
Definition at line 63 of file var_pp_functor.hpp.
Constructor & Destructor Documentation
 var_pp_functor()
virtual var_pp_functor::~var_pp_functor () [inline], [virtual]
Destructor.
Definition at line 66 of file var_pp_functor.hpp.
References operator()().
Member Function Documentation
operator()()
virtual std::string var_pp_functor::operator() (unsigned int var) const [pure virtual]
This functor returns a string representing the variable (usually the name of the variable).
This can be used both in variable declaration and in variable use. The string returned depends on the type of manipulation performed by the backend layer.
Parameters
var is the nodeid of the variable that should be analyzed.
Implemented in isolated_var_pp_functor, address_var_pp_functor, pointer_var_pp_functor, and std_var_pp_functor.
Referenced by isolated_var_pp_functor::isolated_var_pp_functor(), std_var_pp_functor::std_var_pp_functor(), and ~var_pp_functor().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/tree/var_pp_functor.hpp