simple_code_motion Class Reference
Restructure the tree control flow graph.
#include <simple_code_motion.hpp>
Public Member Functions
simple_code_motion (const ParameterConstRef parameters, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~simple_code_motion () override
Destructor.
DesignFlowStep_Status InternalExec () override
Updates the tree to have a more compliant CFG.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
bool IsScheduleBased () const
Return true if the last run of this step was based on scheduling.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
FunctionFrontendFlowStep_Movable CheckMovable (const unsigned int dest_bb_index, tree_nodeRef tn, bool &zero_delay, const tree_managerRef TM)
Check if a statement can be moved in a basic block.
void loop_pipelined (tree_nodeRef curr_stmt, const tree_managerRef TM, unsigned int curr_bb, unsigned int curr_loop_id, std::list< tree_nodeRef > &to_be_removed, std::list< tree_nodeRef > &to_be_added_back, std::list< tree_nodeRef > &to_be_added_front, std::map< unsigned int, blocRef > &list_of_bloc, std::map< std::pair< unsigned int, blocRef >, std::pair< unsigned int, blocRef >> &dom_diff, unsigned int curr_bb_dom)
Private Attributes
ScheduleRef schedule
The scheduling solution.
bool conservative
True if only zero delay statement can be moved.
Static Private Attributes
static bool tree_dumped
flag to check if initial tree has been dumped
Additional Inherited Members
Detailed Description
Restructure the tree control flow graph.
Definition at line 68 of file simple_code_motion.hpp.
Constructor & Destructor Documentation
simple_code_motion()
simple_code_motion::simple_code_motion (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Skipping warnings due to operator() redefinition.
Parameters
parameters is the set of input parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
header include . include algorithm/dominance include behavior includes design_flows include parser/treegcc include STD include tree includes utility include
Definition at line 99 of file simple_code_motion.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~simple_code_motion().
 simple_code_motion()
simple_code_motion::~simple_code_motion () [override], [default]
Destructor.
Referenced by simple_code_motion().
Member Function Documentation
CheckMovable()
FunctionFrontendFlowStep_Movable simple_code_motion::CheckMovable (const unsigned int dest_bb_index, tree_nodeRef tn, bool & zero_delay, const tree_managerRef TM) [private]
Check if a statement can be moved in a basic block.
Parameters
bb_index is the index of the basic block
gn is the statement to be moved
zero_delay returns if statement has zero delay
TM is the tree manager
Returns
if the statement can be moved
FIXME: already added in master?
If we have the ending time information use it
binary expressions
Definition at line 203 of file simple_code_motion.cpp.
References FrontendFlowStep::AppM, Schedule::CanBeMoved(), CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TYPE_NODES, tree_helper::compute_ssa_uses_rec_ptr(), conservative, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_helper::get_type_node(), INDENT_DBG_MEX, tree_node::index, tree_helper::is_constant(), tree_helper::is_real(), max(), min, gimple_assign::op0, gimple_assign::op1, schedule, tree_helper::Size(), STR, THROW_UNREACHABLE, and tree_node::ToString().
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionFrontendFlowStep::FunctionRelationship > > simple_code_motion::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 138 of file simple_code_motion.cpp.
References ABORTED, BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, NONEXISTENT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, SWITCH_FIX, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, UNNECESSARY, and USE_COUNTING.
HasToBeExecuted()
bool simple_code_motion::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 1238 of file simple_code_motion.cpp.
References FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), Wrefcount< T >::lock(), and DesignFlowStep::parameters.
Initialize()
void simple_code_motion::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 115 of file simple_code_motion.cpp.
References FrontendFlowStep::AppM, function_decl::body, FunctionFrontendFlowStep::function_id, GET_NODE, DesignFlowStep::parameters, schedule, and sl.
InternalExec()
DesignFlowStep_Status simple_code_motion::InternalExec () [override], [virtual]
Updates the tree to have a more compliant CFG.
store the GCC BB graph ala boost::graph
add vertices
add edges
add a connection between entry and exit thus avoiding problems with non terminating code
sort basic block vertices from the entry till the exit
If we are performing simd transformation, look for simd pragma
We must use pointer since we are erasing elements in the list
skip gimple statements defining or using virtual operands
load can be loop pipelined/predicated
only gimple_assign are considered for code motion
compute the SSA variables used by stmt
compute BB where the SSA variables are defined
check for anti-dependencies
allow to move first statements later overwritten in the same BB
skip the statement in case it uses ssa variables defined in the current BB
check if list of pred has a loop_id greater than the loop_id of curr_bb
check if current statement can be loop pipelined
load cannot be code moved
find in which BB can be moved
check the result of the dominator tree analysis
check if the controlling condition of curr_bb is constant
finally we found something of meaningful
check if the current uses in dest_bb_index are due only to phis
check if the statement can be really moved
add predication in case is required
it may happen: two consecutive BBs without conditional jump
create a negated condition
compute default condition
it may happen: two consecutive BBs without conditional jump
Going one step step forward to avoid invalidation of the pointer
Moving statement
Going one step back since pointer is already increment in for loop
Implements FunctionFrontendFlowStep.
Definition at line 618 of file simple_code_motion.cpp.
References FrontendFlowStep::AppM, BUILD_VIRTUAL_PHI, CFG_SELECTOR, FunctionFrontendFlowStep::CGetBBVersion(), ssa_name::CGetDefStmts(), CheckMovable(), tree_helper::compute_ssa_uses_rec_ptr(), FunctionFrontendFlowStep::ComputeSignature(), counter, cyclic_topological_sort(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStep::design_flow_manager, bloc::ENTRY_BLOCK_ID, bloc::EXIT_BLOCK_ID, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), INDENT_DBG_MEX, Wrefcount< T >::lock(), loop_pipelined(), DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, tree_node::ToString(), UNCHANGED, ssa_name::virtual_flag, and BBGraph::WriteDot().
IsScheduleBased()
bool simple_code_motion::IsScheduleBased () const
Return true if the last run of this step was based on scheduling.
Definition at line 1261 of file simple_code_motion.cpp.
References schedule.
loop_pipelined()
void simple_code_motion::loop_pipelined (tree_nodeRef curr_stmt, const tree_managerRef TM, unsigned int curr_bb, unsigned int curr_loop_id, std::list< tree_nodeRef > & to_be_removed, std::list< tree_nodeRef > & to_be_added_back, std::list< tree_nodeRef > & to_be_added_front, std::map< unsigned int, blocRef > & list_of_bloc, std::map< std::pair< unsigned int, blocRef >, std::pair< unsigned int, blocRef >> & dom_diff, unsigned int curr_bb_dom) [private]
Referenced by InternalExec().
Field Documentation
conservative
bool simple_code_motion::conservative [private]
True if only zero delay statement can be moved.
Definition at line 78 of file simple_code_motion.hpp.
Referenced by CheckMovable().
schedule
ScheduleRef simple_code_motion::schedule [private]
The scheduling solution.
Definition at line 72 of file simple_code_motion.hpp.
Referenced by CheckMovable(), Initialize(), and IsScheduleBased().
tree_dumped
bool simple_code_motion::tree_dumped [static], [private]
flag to check if initial tree has been dumped
Definition at line 75 of file simple_code_motion.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/simple_code_motion.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/simple_code_motion.cpp