BasicBlocksProfilingCWriter Class Reference
Super class include.
#include <basic_blocks_profiling_c_writer.hpp>
Public Member Functions
BasicBlocksProfilingCWriter (const application_managerConstRef _AppM, const InstructionWriterRef instruction_writer, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef Param, bool verbose=true)
Constructor of the class.
~BasicBlocksProfilingCWriter () override
Destructor.
void WriteGlobalDeclarations () override
Write global declarations.
Private Member Functions
void print_loop_ending (EdgeDescriptor e) override
Dump operations requested for record information about a loop path which ends.
void print_loop_escaping (EdgeDescriptor e) override
Dump operations requested for record information about a path which exit from a loop.
void print_loop_starting (EdgeDescriptor e) override
Dump initializations of variable for recording a loop path.
void print_edge (EdgeDescriptor e, unsigned int index) override
Dump operation requested for instrument an edges.
void print_loop_switching (EdgeDescriptor e) override
Print operation requested for record information about a path which exit from a loop and immediately enter in another.
Additional Inherited Members
Detailed Description
Super class include.
Class use to write the C code with instruented edges for basic blocks profiling
Definition at line 50 of file basic_blocks_profiling_c_writer.hpp.
Constructor & Destructor Documentation
BasicBlocksProfilingCWriter()
BasicBlocksProfilingCWriter::BasicBlocksProfilingCWriter (const application_managerConstRef _AppM, const InstructionWriterRef _instruction_writer, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _Param, bool _verbose = true)
Constructor of the class.
Header include.
Parameters
_AppM is the application manager
instruction_writer is the instruction writer to use to print the single instruction
indented_output_stream is the output stream
Param is the set of parameters
verbose tells if annotations
. include behavior includes constants include tree includes utility include
Definition at line 66 of file basic_blocks_profiling_c_writer.cpp.
References CWriter::debug_level, GET_CLASS, and ~BasicBlocksProfilingCWriter().
 BasicBlocksProfilingCWriter()
BasicBlocksProfilingCWriter::~BasicBlocksProfilingCWriter () [override], [default]
Destructor.
Referenced by BasicBlocksProfilingCWriter().
Member Function Documentation
print_edge()
void BasicBlocksProfilingCWriter::print_edge (EdgeDescriptor e, unsigned int index) [override], [private], [virtual]
Dump operation requested for instrument an edges.
Parameters
e is the edge
index is the index of the variable to be incremented
Reimplemented from EdgeCWriter.
Definition at line 89 of file basic_blocks_profiling_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, BBGraph::CGetBBNodeInfo(), EdgeCWriter::dumped_edges, EdgeCWriter::fun_id, CWriter::indented_output_stream, STR, and EdgeCWriter::support_cfg.
Referenced by print_loop_ending(), print_loop_escaping(), print_loop_starting(), and print_loop_switching().
print_loop_ending()
void BasicBlocksProfilingCWriter::print_loop_ending (EdgeDescriptor e) [override], [private], [virtual]
Dump operations requested for record information about a loop path which ends.
Parameters
e is the feedback or outgoing edge
Reimplemented from EdgeCWriter.
Definition at line 74 of file basic_blocks_profiling_c_writer.cpp.
References print_edge().
print_loop_escaping()
void BasicBlocksProfilingCWriter::print_loop_escaping (EdgeDescriptor e) [override], [private], [virtual]
Dump operations requested for record information about a path which exit from a loop.
Parameters
e is the feedback or outgoing edge
Reimplemented from EdgeCWriter.
Definition at line 79 of file basic_blocks_profiling_c_writer.cpp.
References print_edge().
print_loop_starting()
void BasicBlocksProfilingCWriter::print_loop_starting (EdgeDescriptor e) [override], [private], [virtual]
Dump initializations of variable for recording a loop path.
Parameters
e is the incoming edged
Reimplemented from EdgeCWriter.
Definition at line 84 of file basic_blocks_profiling_c_writer.cpp.
References print_edge().
print_loop_switching()
void BasicBlocksProfilingCWriter::print_loop_switching (EdgeDescriptor e) [override], [private], [virtual]
Print operation requested for record information about a path which exit from a loop and immediately enter in another.
Parameters
e is the edge
Reimplemented from EdgeCWriter.
Definition at line 97 of file basic_blocks_profiling_c_writer.cpp.
References print_edge().
WriteGlobalDeclarations()
void BasicBlocksProfilingCWriter::WriteGlobalDeclarations () [override], [virtual]
Write global declarations.
Reimplemented from CWriter.
Definition at line 102 of file basic_blocks_profiling_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, GET_CONST_NODE, GET_NODE, CWriter::indented_output_stream, CWriter::Param, sl, STR, STR_CST_host_profiling_data, CWriter::TM, and CWriter::WriteGlobalDeclarations().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/basic_blocks_profiling_c_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/basic_blocks_profiling_c_writer.cpp