/home/osboxes/bambu/PandA-bambu/documentation/tutorial_fpt_2017/debugging/first/operations.c File Reference
Functions
int plus (int x, int y)
int minus (int x, int y)
int times (int x, int y)
int times2 (int x)
int divide (int x, int y)
Function Documentation
divide()
int divide (int x, int y)
Definition at line 5 of file operations.c.
Referenced by compute().
minus()
int minus (int x, int y)
Definition at line 2 of file operations.c.
Referenced by compute().
plus()
int plus (int x, int y)
Definition at line 1 of file operations.c.
Referenced by compute().
times()
int times (int x, int y)
Definition at line 3 of file operations.c.
Referenced by compute(), and p_cpu_time().
times2()
int times2 (int x)
Definition at line 4 of file operations.c.
Referenced by compute().