DesignCompilerWrapper Class Reference
Main class for wrapping Design Compiler by Synopsys.
#include <DesignCompilerWrapper.hpp>
Public Types
enum report_t {
REPORT_AREA = 0,
REPORT_TIME,
REPORT_POWER,
REPORT_CELL,
SYNTHESIS_RESULT,
SYNTHESIS_LOG,
SDC_CONSTRAINTS
 }
enum opt_level_t { MEDIUM = 0,
HIGH,
ULTRA
 }
enum constraint_t { AREA = 0,
TIME,
POWER
 }
Public Member Functions
area_modelRef parse_area_reports ()
parse area reports
time_modelRef parse_time_reports ()
parse time reports
void add_link_library (const std::string &link_library)
Set a link library.
void add_link_library (const std::vector< std::string > &link_library)
Set a vector of link libraries.
void add_target_library (const std::string &target_library)
Set a target library.
void add_target_library (const std::vector< std::string > &target_library)
Set a vector of target libraries.
void add_dont_use_cells (const std::string &top_module, const std::string &dont_use_cells)
Determine the set of cells to be used for each design.
void set_search_path (const std::string &path)
Set the search path.
void set_top_module (const std::string &top)
Sets the top module.
void set_constraint_file (const std::string &path)
Sets the path to the constraint file (SDC)
DesignCompilerWrapper (const ParameterConstRef _Param, const target_deviceRef _device, const std::string &_output_dir)
Constructor.
~DesignCompilerWrapper () override
Destructor.
double get_synthesis_time () const
Return synthesis time.
std::map< unsigned int, double > get_area_values () const
Return area values.
std::vector< double > get_arrival_time () const
Return arrival times.
std::map< unsigned int, double > get_power_values () const
Return synthesis time.
std::vector< std::vector< std::string > > get_critical_cells () const
Return critical cells.
std::map< std::string, unsigned int > get_cell_frequency () const
Return cell frequency.
bool get_synthesis_result () const
Return if the synthesis is completed without errors or not.
std::string get_report_file (unsigned int report_type) const
Return a report file.
Protected Member Functions
void init_reserved_vars () override
Initializes the reserved vars.
void set_link_libraries (const DesignParametersRef dp)
Determine and load the link (i.e., initial) libraries into the synthesis script.
void set_target_libraries (const DesignParametersRef dp)
Determine and load the target libraries into the synthesis script.
void set_constraints (const DesignParametersRef dp)
Determine the synthesis constraints.
void set_search_path (const DesignParametersRef dp)
Determine the search path.
void parse_synthesis_reports ()
parse synthesis reports
void parse_cell_reports ()
parse cell reports
void parse_reports ()
wrapper to parse all reports
std::string write_timing_paths (const std::string &design_name, const std::vector< std::string > &timing_path)
Write the timing path into an XML file.
std::string import_input_design (const DesignParametersRef dp, const std::vector< std::string > &file_list)
Create the piece of script related of the initial design.
void write_reports (const DesignParametersRef dp)
Write the reports about area, time and power.
void save_design (const DesignParametersRef dp, const std::string &target)
Save the resulting netlist.
void perform_optimization (const DesignParametersRef dp)
Perform the synthesis and optimization.
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates variables.
Protected Attributes
std::string top_module
top module
std::string constraint_file
constraint file
std::map< unsigned int, std::string > report_files
map between the type of the reports and the corresponding file generated by Design Compiler's execution
std::vector< std::string > search_path
path where the files have to be searched
std::vector< std::string > link_libs
libraries for linking
std::vector< std::string > target_libs
target libraries for the synthesis process
std::vector< std::string > synthetic_libs
synthetic libraries for the synthesis process
std::vector< std::string > library_list
list of libraries to be considered
double max_area
max area
double max_delay
max area
std::map< std::string, std::string > dont_use_map
map between the name of the benchmark and the dont_use string to be set
std::map< unsigned int, double > area
area values coming out from the synthesis
double synthesis_time {0.0}
synthesis time
bool synthesis_result
results of the synthesis
std::vector< double > arrival_time
arrival time of the different critical paths
std::map< unsigned int, double > power
map for the power values
std::vector< std::vector< std::string > > critical_paths
vector of critical paths
std::vector< std::vector< std::string > > critical_cells
vector of cells in the critical paths
std::map< std::string, unsigned int > cell_frequency
map between the name of the cell and the corresponding frequency
Additional Inherited Members
Detailed Description
Main class for wrapping Design Compiler by Synopsys.
Definition at line 86 of file DesignCompilerWrapper.hpp.
Member Enumeration Documentation
constraint_t
enum DesignCompilerWrapper::constraint_t
Enumerator
AREA
TIME
POWER
Definition at line 107 of file DesignCompilerWrapper.hpp.
opt_level_t
enum DesignCompilerWrapper::opt_level_t
Enumerator
MEDIUM
HIGH
ULTRA
Definition at line 100 of file DesignCompilerWrapper.hpp.
report_t
enum DesignCompilerWrapper::report_t
Enumerator
REPORT_AREA
REPORT_TIME
REPORT_POWER
REPORT_CELL
SYNTHESIS_RESULT
SYNTHESIS_LOG
SDC_CONSTRAINTS
Definition at line 89 of file DesignCompilerWrapper.hpp.
Constructor & Destructor Documentation
DesignCompilerWrapper()
DesignCompilerWrapper::DesignCompilerWrapper (const ParameterConstRef _Param, const target_deviceRef _device, const std::string & _output_dir)
Constructor.
Parameters
Param is the set of parameters
output_dir is the path to the directory where all the results will be stored
Definition at line 111 of file DesignCompilerWrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, GET_CLASS, init_reserved_vars(), link_libs, SynthesisTool::Param, PRINT_DBG_MEX, search_path, and synthetic_libs.
 DesignCompilerWrapper()
DesignCompilerWrapper::~DesignCompilerWrapper () [override]
Destructor.
Definition at line 208 of file DesignCompilerWrapper.cpp.
Member Function Documentation
add_dont_use_cells()
void DesignCompilerWrapper::add_dont_use_cells (const std::string & top_module, const std::string & dont_use_cells)
Determine the set of cells to be used for each design.
Definition at line 236 of file DesignCompilerWrapper.cpp.
References dont_use_map.
add_link_library() [1/2]
void DesignCompilerWrapper::add_link_library (const std::string & link_library)
Set a link library.
Definition at line 218 of file DesignCompilerWrapper.cpp.
References link_libs.
Referenced by add_link_library().
add_link_library() [2/2]
void DesignCompilerWrapper::add_link_library (const std::vector< std::string > & link_library)
Set a vector of link libraries.
Definition at line 212 of file DesignCompilerWrapper.cpp.
References add_link_library().
add_target_library() [1/2]
void DesignCompilerWrapper::add_target_library (const std::string & target_library)
Set a target library.
Definition at line 230 of file DesignCompilerWrapper.cpp.
References target_libs.
Referenced by add_target_library().
add_target_library() [2/2]
void DesignCompilerWrapper::add_target_library (const std::vector< std::string > & target_library)
Set a vector of target libraries.
Definition at line 224 of file DesignCompilerWrapper.cpp.
References add_target_library().
EvaluateVariables()
void DesignCompilerWrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates variables.
Reimplemented from SynthesisTool.
Definition at line 127 of file DesignCompilerWrapper.cpp.
References DesignParameters::component_name, dc_constraint_file, dc_top, SynthesisTool::get_reserved_parameter(), import_input_design(), NODE_COMMAND, PARAM_HDL_files, PARAM_sdc_file, DesignParameters::parameter_values, perform_optimization(), SynthesisTool::replace_parameters(), REPORT_AREA, report_files, REPORT_TIME, save_design(), set_link_libraries(), set_target_libraries(), THROW_ERROR, and SynthesisTool::xml_script_nodes.
get_area_values()
std::map< unsigned int, double > DesignCompilerWrapper::get_area_values () const
Return area values.
Definition at line 799 of file DesignCompilerWrapper.cpp.
References area.
get_arrival_time()
std::vector< double > DesignCompilerWrapper::get_arrival_time () const
Return arrival times.
Definition at line 806 of file DesignCompilerWrapper.cpp.
References arrival_time.
get_cell_frequency()
std::map< std::string, unsigned int > DesignCompilerWrapper::get_cell_frequency () const
Return cell frequency.
Definition at line 827 of file DesignCompilerWrapper.cpp.
References cell_frequency.
get_critical_cells()
std::vector< std::vector< std::string > > DesignCompilerWrapper::get_critical_cells () const
Return critical cells.
Definition at line 820 of file DesignCompilerWrapper.cpp.
References critical_cells.
get_power_values()
std::map< unsigned int, double > DesignCompilerWrapper::get_power_values () const
Return synthesis time.
Definition at line 813 of file DesignCompilerWrapper.cpp.
References power.
get_report_file()
std::string DesignCompilerWrapper::get_report_file (unsigned int report_type) const
Return a report file.
Definition at line 839 of file DesignCompilerWrapper.cpp.
References report_files, and THROW_ASSERT.
get_synthesis_result()
bool DesignCompilerWrapper::get_synthesis_result () const
Return if the synthesis is completed without errors or not.
Definition at line 834 of file DesignCompilerWrapper.cpp.
References synthesis_result.
get_synthesis_time()
double DesignCompilerWrapper::get_synthesis_time () const
Return synthesis time.
Definition at line 794 of file DesignCompilerWrapper.cpp.
References synthesis_time.
import_input_design()
std::string DesignCompilerWrapper::import_input_design (const DesignParametersRef dp, const std::vector< std::string > & file_list) [protected]
Create the piece of script related of the initial design.
Definition at line 285 of file DesignCompilerWrapper.cpp.
References DesignParameters::component_name, dc_HDL_file, dc_top_filetype, SynthesisTool::get_reserved_parameter(), GetLeafFileName(), SynthesisTool::output_dir, THROW_ERROR, top(), VERILOG, and VHDL.
Referenced by EvaluateVariables().
init_reserved_vars()
void DesignCompilerWrapper::init_reserved_vars () [override], [protected], [virtual]
Initializes the reserved vars.
Reimplemented from SynthesisTool.
Definition at line 173 of file DesignCompilerWrapper.cpp.
References ADD_RES_VAR, dc_compile_effort_high, dc_compile_effort_medium, dc_compile_effort_ultra, dc_constraint_file, dc_dont_use, dc_HDL_file, dc_link_library, dc_max_area, dc_max_delay, dc_report_power, dc_search_path, dc_synthesize, dc_target, dc_target_library, dc_top, dc_top_filetype, dc_zero_interconnect_delay, and SynthesisTool::init_reserved_vars().
Referenced by DesignCompilerWrapper().
parse_area_reports()
area_modelRef DesignCompilerWrapper::parse_area_reports ()
parse area reports
saving the value in the area model
Definition at line 636 of file DesignCompilerWrapper.cpp.
References area, area_model::CELL_AREA, area_model::COMBINATIONAL_AREA, area_model::create_model(), SynthesisTool::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, SynthesisTool::device, area_model::INTERCONNECT_AREA, area_model::NONCOMBINATIONAL_AREA, SynthesisTool::output_level, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERBOSE, OUTPUT_LEVEL_VERY_PEDANTIC, SynthesisTool::Param, PRINT_DBG_MEX, PRINT_OUT_MEX, REPORT_AREA, report_files, area_model::set_area_value(), and area_model::TOTAL_AREA.
Referenced by parse_reports().
parse_cell_reports()
void DesignCompilerWrapper::parse_cell_reports () [protected]
parse cell reports
Definition at line 437 of file DesignCompilerWrapper.cpp.
References cell_frequency, SynthesisTool::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, SynthesisTool::output_level, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERBOSE, PRINT_DBG_MEX, PRINT_OUT_MEX, REPORT_CELL, and report_files.
Referenced by parse_reports().
parse_reports()
void DesignCompilerWrapper::parse_reports () [protected]
wrapper to parse all reports
Definition at line 731 of file DesignCompilerWrapper.cpp.
References SynthesisTool::output_level, OUTPUT_LEVEL_VERBOSE, parse_area_reports(), parse_cell_reports(), parse_synthesis_reports(), parse_time_reports(), PRINT_OUT_MEX, and synthesis_result.
parse_synthesis_reports()
void DesignCompilerWrapper::parse_synthesis_reports () [protected]
parse synthesis reports
Definition at line 593 of file DesignCompilerWrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, SynthesisTool::output_level, OUTPUT_LEVEL_VERBOSE, print_cpu_time(), PRINT_DBG_MEX, PRINT_OUT_MEX, report_files, SYNTHESIS_LOG, synthesis_result, and synthesis_time.
Referenced by parse_reports().
parse_time_reports()
time_modelRef DesignCompilerWrapper::parse_time_reports ()
parse time reports
saving the value in the time model
Definition at line 482 of file DesignCompilerWrapper.cpp.
References arrival_time, time_model::create_model(), critical_cells, critical_paths, SynthesisTool::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, SynthesisTool::device, el, SynthesisTool::output_level, OUTPUT_LEVEL_VERBOSE, SynthesisTool::Param, PRINT_DBG_MEX, PRINT_OUT_MEX, report_files, REPORT_TIME, and time_model::set_execution_time().
Referenced by parse_reports().
perform_optimization()
void DesignCompilerWrapper::perform_optimization (const DesignParametersRef dp) [protected]
Perform the synthesis and optimization.
compile the current design
Definition at line 374 of file DesignCompilerWrapper.cpp.
References dc_compile_effort_high, dc_compile_effort_medium, dc_compile_effort_ultra, dc_synthesize, SynthesisTool::get_reserved_parameter(), HIGH, MEDIUM, SynthesisTool::output_level, OUTPUT_LEVEL_MINIMUM, SynthesisTool::Param, PRINT_OUT_MEX, THROW_UNREACHABLE, and ULTRA.
Referenced by EvaluateVariables().
save_design()
void DesignCompilerWrapper::save_design (const DesignParametersRef dp, const std::string & target) [protected]
Save the resulting netlist.
Definition at line 414 of file DesignCompilerWrapper.cpp.
References dc_output_dir, dc_target, SynthesisTool::get_reserved_parameter(), SynthesisTool::output_dir, DesignParameters::parameter_values, report_files, and SYNTHESIS_RESULT.
Referenced by EvaluateVariables().
set_constraint_file()
void DesignCompilerWrapper::set_constraint_file (const std::string & path)
Sets the path to the constraint file (SDC)
Definition at line 202 of file DesignCompilerWrapper.cpp.
References constraint_file.
set_constraints()
void DesignCompilerWrapper::set_constraints (const DesignParametersRef dp) [protected]
Determine the synthesis constraints.
'*' represents a wildcard for all benchmarks
Definition at line 326 of file DesignCompilerWrapper.cpp.
References DesignParameters::component_name, ToolManager::configure(), constraint_file, dc_constraint_file, dc_dont_use, dc_max_area, dc_max_delay, dc_zero_interconnect_delay, DESIGN_COMPILER_TOOL_ID, ToolManager::determine_paths(), dont_use_map, SynthesisTool::get_reserved_parameter(), max_area, max_delay, SynthesisTool::Param, SynthesisTool::tool, top(), and top_module.
set_link_libraries()
void DesignCompilerWrapper::set_link_libraries (const DesignParametersRef dp) [protected]
Determine and load the link (i.e., initial) libraries into the synthesis script.
Definition at line 257 of file DesignCompilerWrapper.cpp.
References dc_link_library, SynthesisTool::get_reserved_parameter(), and link_libs.
Referenced by EvaluateVariables().
set_search_path() [1/2]
void DesignCompilerWrapper::set_search_path (const DesignParametersRef dp) [protected]
Determine the search path.
Definition at line 246 of file DesignCompilerWrapper.cpp.
References dc_search_path, SynthesisTool::get_reserved_parameter(), and search_path.
set_search_path() [2/2]
void DesignCompilerWrapper::set_search_path (const std::string & path)
Set the search path.
Definition at line 241 of file DesignCompilerWrapper.cpp.
References search_path.
set_target_libraries()
void DesignCompilerWrapper::set_target_libraries (const DesignParametersRef dp) [protected]
Determine and load the target libraries into the synthesis script.
Definition at line 268 of file DesignCompilerWrapper.cpp.
References dc_target_library, SynthesisTool::device, SynthesisTool::get_reserved_parameter(), and target_libs.
Referenced by EvaluateVariables().
set_top_module()
void DesignCompilerWrapper::set_top_module (const std::string & top)
Sets the top module.
Definition at line 197 of file DesignCompilerWrapper.cpp.
References top(), and top_module.
write_reports()
void DesignCompilerWrapper::write_reports (const DesignParametersRef dp) [protected]
Write the reports about area, time and power.
Definition at line 425 of file DesignCompilerWrapper.cpp.
References SynthesisTool::Param, REPORT_AREA, REPORT_CELL, report_files, REPORT_POWER, and REPORT_TIME.
write_timing_paths()
std::string DesignCompilerWrapper::write_timing_paths (const std::string & design_name, const std::vector< std::string > & timing_path) [protected]
Write the timing path into an XML file.
Definition at line 746 of file DesignCompilerWrapper.cpp.
References xml_child::add_child_element(), xml_document::create_root_node(), THROW_ASSERT, test_panda::type, xml_document::write_to_file_formatted(), and WRITE_XNVM.
Field Documentation
area
std::map<unsigned int, double> DesignCompilerWrapper::area [protected]
area values coming out from the synthesis
Definition at line 154 of file DesignCompilerWrapper.hpp.
Referenced by get_area_values(), and parse_area_reports().
arrival_time
std::vector<double> DesignCompilerWrapper::arrival_time [protected]
arrival time of the different critical paths
Definition at line 162 of file DesignCompilerWrapper.hpp.
Referenced by get_arrival_time(), and parse_time_reports().
cell_frequency
std::map<std::string, unsigned int> DesignCompilerWrapper::cell_frequency [protected]
map between the name of the cell and the corresponding frequency
Definition at line 173 of file DesignCompilerWrapper.hpp.
Referenced by get_cell_frequency(), and parse_cell_reports().
constraint_file
std::string DesignCompilerWrapper::constraint_file [protected]
constraint file
Definition at line 124 of file DesignCompilerWrapper.hpp.
Referenced by set_constraint_file(), and set_constraints().
critical_cells
std::vector<std::vector<std::string> > DesignCompilerWrapper::critical_cells [protected]
vector of cells in the critical paths
Definition at line 170 of file DesignCompilerWrapper.hpp.
Referenced by get_critical_cells(), and parse_time_reports().
critical_paths
std::vector<std::vector<std::string> > DesignCompilerWrapper::critical_paths [protected]
vector of critical paths
Definition at line 168 of file DesignCompilerWrapper.hpp.
Referenced by parse_time_reports().
dont_use_map
std::map<std::string, std::string> DesignCompilerWrapper::dont_use_map [protected]
map between the name of the benchmark and the dont_use string to be set
Definition at line 151 of file DesignCompilerWrapper.hpp.
Referenced by add_dont_use_cells(), and set_constraints().
library_list
std::vector<std::string> DesignCompilerWrapper::library_list [protected]
list of libraries to be considered
Definition at line 142 of file DesignCompilerWrapper.hpp.
link_libs
std::vector<std::string> DesignCompilerWrapper::link_libs [protected]
libraries for linking
Definition at line 133 of file DesignCompilerWrapper.hpp.
Referenced by add_link_library(), DesignCompilerWrapper(), and set_link_libraries().
max_area
double DesignCompilerWrapper::max_area [protected]
max area
Definition at line 145 of file DesignCompilerWrapper.hpp.
Referenced by set_constraints().
max_delay
double DesignCompilerWrapper::max_delay [protected]
max area
Definition at line 148 of file DesignCompilerWrapper.hpp.
Referenced by set_constraints().
power
std::map<unsigned int, double> DesignCompilerWrapper::power [protected]
map for the power values
Definition at line 165 of file DesignCompilerWrapper.hpp.
Referenced by get_power_values().
report_files
std::map<unsigned int, std::string> DesignCompilerWrapper::report_files [protected]
map between the type of the reports and the corresponding file generated by Design Compiler's execution
Definition at line 127 of file DesignCompilerWrapper.hpp.
Referenced by EvaluateVariables(), get_report_file(), parse_area_reports(), parse_cell_reports(), parse_synthesis_reports(), parse_time_reports(), save_design(), and write_reports().
search_path
std::vector<std::string> DesignCompilerWrapper::search_path [protected]
path where the files have to be searched
Definition at line 130 of file DesignCompilerWrapper.hpp.
Referenced by DesignCompilerWrapper(), and set_search_path().
synthesis_result
bool DesignCompilerWrapper::synthesis_result [protected]
results of the synthesis
Definition at line 159 of file DesignCompilerWrapper.hpp.
Referenced by get_synthesis_result(), parse_reports(), and parse_synthesis_reports().
synthesis_time
double DesignCompilerWrapper::synthesis_time {0.0} [protected]
synthesis time
Definition at line 157 of file DesignCompilerWrapper.hpp.
Referenced by get_synthesis_time(), and parse_synthesis_reports().
synthetic_libs
std::vector<std::string> DesignCompilerWrapper::synthetic_libs [protected]
synthetic libraries for the synthesis process
Definition at line 139 of file DesignCompilerWrapper.hpp.
Referenced by DesignCompilerWrapper().
target_libs
std::vector<std::string> DesignCompilerWrapper::target_libs [protected]
target libraries for the synthesis process
Definition at line 136 of file DesignCompilerWrapper.hpp.
Referenced by add_target_library(), and set_target_libraries().
top_module
std::string DesignCompilerWrapper::top_module [protected]
top module
Definition at line 121 of file DesignCompilerWrapper.hpp.
Referenced by set_constraints(), and set_top_module().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/synopsys/design_compiler/DesignCompilerWrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/synopsys/design_compiler/DesignCompilerWrapper.cpp