tree_manager Class Reference
This class manages the tree structures extracted from the raw file.
#include <tree_manager.hpp>
Public Member Functions
void RecursiveReplaceTreeNode (tree_nodeRef &tn, const tree_nodeRef old_node, const tree_nodeRef &new_node, const tree_nodeRef &stmt, bool definition)
Replace the occurrences of tree node old_node with new_node in statement identified by tn.
tree_manager (const ParameterConstRef &Param)
This is the constructor of the tree_manager which initializes the vector of functions.
~tree_manager ()
unsigned int get_implementation_node (unsigned int decl_node) const
Return the index of function_decl node that implements the declaration node.
void AddTreeNode (const unsigned int i, const tree_nodeRef &curr)
Add to the tree manager the current node.
tree_nodeRef GetTreeReindex (const unsigned int i)
Return a tree_reindex wrapping the i-th tree_node.
const tree_nodeRef CGetTreeReindex (const unsigned int i) const
Return a tree_reindex wrapping the i-th tree_node.
tree_nodeRef GetTreeNode (const unsigned int index) const
Return the index-th tree_node (modifiable version)
const tree_nodeRef get_tree_node_const (unsigned int i) const
Return the reference to the i-th tree_node Constant version of get_tree_node.
const tree_nodeConstRef CGetTreeNode (const unsigned int i) const
bool is_tree_node (unsigned int i) const
Return true if there exists a tree node associated with the given id, false otherwise.
void create_tree_node (const unsigned int node_id, enum kind tree_node_type, std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > &tree_node_schema)
Factory method.
unsigned int find (enum kind tree_node_type, const std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > &tree_node_schema)
if there exist return the node id of a tree node compatible with the tree_node_schema and of type tree_node_type.
unsigned int new_tree_node_id (const unsigned int ask=0)
Return a new node id in the intermediate representation.
unsigned int get_next_available_tree_node_id () const
return the next available tree node id.
void add_function (unsigned int index, tree_nodeRef curr)
Add to the function_decl_nodes the current node.
unsigned long get_function_decl_node_n () const
Return the number of function_decl_node.
const CustomUnorderedSet< unsigned int > GetAllFunctions () const
Returns all the functions in the tree_manager.
unsigned int find_sc_main_node () const
Determine the index node of `sc_main` function in tree_node vector.
unsigned int function_index (const std::string &function_name) const
Return the index of a function given its name.
void print (std::ostream &os) const
Function that prints the class tree_manager.
void PrintGimple (std::ostream &os, const bool use_uid) const
Function that prints the bodies of function in gimple format.
void collapse_into (const unsigned int &funID, CustomUnorderedMapUnstable< unsigned int, unsigned int > &stmt_to_bloc, const tree_nodeRef &tn, CustomUnorderedSet< unsigned int > &removed_nodes)
Collapse operations chains into the examinated node.
void add_parallel_loop ()
increment the number a parallel loop
unsigned int get_n_pl () const
return the number of parallel loops
void merge_tree_managers (const tree_managerRef &TM_source)
merge two tree manager: this with TM_source
void add_goto ()
Increment the number of added gotos.
unsigned int get_added_goto () const
Return the number of added gotos.
void increment_removed_pointer_plus ()
Increment the number of removed pointer plus.
unsigned int get_removed_pointer_plus () const
Return the number of removed pointer plus.
void increment_removable_pointer_plus ()
Increment the number of removable pointer plus.
unsigned int get_removable_pointer_plus () const
Return the number of not removed pointer plus.
void increment_unremoved_pointer_plus ()
Increment the number of not removed pointer plus.
unsigned int get_unremoved_pointer_plus () const
Return the number of not removed pointer plus.
unsigned int find_identifier_nodeID (const std::string &str) const
Return the nodeID of the identifier_node representing string str.
void add_identifier_node (unsigned int nodeID, const std::string &str)
Add an identifier_node to the corresponding unique table.
void add_identifier_node (unsigned int nodeID, const bool &op)
unsigned int get_next_vers ()
Return the next unused version number for ssa variables.
void ReplaceTreeNode (const tree_nodeRef &tn, const tree_nodeRef &old_node, const tree_nodeRef &new_node)
Replace the occurrences of tree node old_node with new_node in statement identified by tn.
tree_nodeRef CreateUniqueIntegerCst (long long int value, unsigned int type_index)
memoization of integer constants
bool is_CPP () const
is_CPP return true in case we have at least one CPP source code
bool is_top_function (const function_decl *fd) const
is_top_function checks if a function is one of the application top functions.
bool check_ssa_uses (unsigned int fun_id) const
check_ssa_uses check if the uses of a ssa are correct
Private Member Functions
bool check_for_decl (const tree_nodeRef &tn, const tree_managerRef &TM, std::string &symbol_name, std::string &symbol_scope, unsigned int node_id, const CustomUnorderedMap< unsigned int, std::string > &global_type_unql_symbol_table)
check for decl_node and return true if not suitable for symbol table or otherwise its symbol_name and symbol_scope.
bool check_for_type (const tree_nodeRef &tn, const tree_managerRef &TM, std::string &symbol_name, std::string &symbol_scope, const CustomUnorderedMapUnstable< std::string, unsigned int > &global_type_symbol_table, unsigned int node_id)
check for type and return true if not suitable for symbol table or otherwise its symbol_name and symbol_scope.
void erase_usage_info (const tree_nodeRef &tn, const tree_nodeRef &stmt)
Erase the information about variable usage (remove stmt from use_stmts attribute) in ssa variables recursively contained in node tn.
void insert_usage_info (const tree_nodeRef &tn, const tree_nodeRef &stmt)
Insert the information about variable usage (insert stmt in use_stmts attribute) in ssa variables recursively contained in node tn.
Private Attributes
CustomUnorderedMap< std::string, enum kind > string_to_kind
map between string and corresponding enum kinds
CustomUnorderedMapUnstable< std::string, unsigned int > find_cache
cache for tree_manager::find
OrderedMapStd< unsigned int, tree_nodeRef > tree_nodes
Variable containing set of tree_nodes.
std::map< unsigned int, tree_nodeRef > function_decl_nodes
Variable containing set of function_declaration with their index node.
std::deque< tree_nodeRef > stack
list of examining statements during collapse_into recursion
CustomUnorderedSet< tree_nodeRef > already_visited
set of already examined addr_expr used to avoid circular recursion
unsigned int n_pl
the number of parallel loops
unsigned int added_goto
the number of added goto
unsigned int removed_pointer_plus
the number of removed pointer_plus
unsigned int removable_pointer_plus
the number of removable pointer_plus
unsigned int unremoved_pointer_plus
the number of unremoved pointer_plus
int debug_level
The debug level.
unsigned int last_node_id
last node_id used
CustomUnorderedMapUnstable< std::string, unsigned int > identifiers_unique_table
this table stores all identifier_nodes with their nodeID.
CustomUnorderedMap< std::pair< long long int, unsigned int >, tree_nodeRef > unique_integer_cst_map
const ParameterConstRef Param
Set of parameters.
CustomUnorderedMap< ssa_name *, tree_nodeRef > uses_erase_temp
Map containing temporary information for ssa_name uses deletion.
unsigned int next_vers
Next version number for ssa variables.
unsigned int collapse_into_counter
Index of current call of collapse_into_counter.
Friends
std::ostream & operator<< (std::ostream &os, tree_manager &s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const tree_managerRef &s)
Friend definition of the << operator.
Detailed Description
This class manages the tree structures extracted from the raw file.
Definition at line 80 of file tree_manager.hpp.
Constructor & Destructor Documentation
tree_manager()
tree_manager::tree_manager (const ParameterConstRef & _Param) [explicit]
This is the constructor of the tree_manager which initializes the vector of functions.
Autoheader include.
Parameters
Param is the set of input parameters
Header include Machine include Parameter include parser/treegcc include Tree include Wrapper include
Definition at line 92 of file tree_manager.cpp.
References ~tree_manager().
 tree_manager()
tree_manager::~tree_manager () [default]
Referenced by tree_manager().
Member Function Documentation
add_function()
void tree_manager::add_function (unsigned int index, tree_nodeRef curr)
Add to the function_decl_nodes the current node.
Parameters
index is the index of the node
curr is the added element
Definition at line 286 of file tree_manager.cpp.
References function_decl_nodes, and index.
add_goto()
void tree_manager::add_goto ()
Increment the number of added gotos.
Definition at line 2532 of file tree_manager.cpp.
References added_goto.
Referenced by tree_manipulation::create_goto().
add_identifier_node() [1/2]
void tree_manager::add_identifier_node (unsigned int nodeID, const std::string & str) [inline]
Add an identifier_node to the corresponding unique table.
Parameters
nodeID is the node id.
str is the string.
Definition at line 422 of file tree_manager.hpp.
References check_ssa_uses(), CreateUniqueIntegerCst(), get_next_vers(), is_CPP(), is_top_function(), and ReplaceTreeNode().
Referenced by find_identifier_nodeID(), and handler::visit().
add_identifier_node() [2/2]
void tree_manager::add_identifier_node (unsigned int nodeID, const bool & op)
add_parallel_loop()
void tree_manager::add_parallel_loop ()
increment the number a parallel loop
Definition at line 1696 of file tree_manager.cpp.
References n_pl.
AddTreeNode()
void tree_manager::AddTreeNode (const unsigned int i, const tree_nodeRef & curr)
Add to the tree manager the current node.
Parameters
i position in the tree_vector. Note that the raw file start from 1
curr is the added element
Definition at line 121 of file tree_manager.cpp.
References last_node_id, STR, THROW_ASSERT, and tree_nodes.
Referenced by tree_node_factory::create_tree_node().
CGetTreeNode()
const tree_nodeConstRef tree_manager::CGetTreeNode (const unsigned int i) const
Definition at line 163 of file tree_manager.cpp.
References last_node_id, STR, THROW_ASSERT, and tree_nodes.
Referenced by Vectorize::AddGuards(), TestbenchMemoryAllocation::AllocTestbenchMemory(), AllocationInformation::can_implement_set(), Schedule::CanBeMoved(), AllocationInformation::CanImplementSetNotEmpty(), Vectorize::ComputeFrontendRelationships(), fsm_controller::create_state_machine(), create_tree_node(), Vectorize::DuplicateIncrement(), Schedule::EvaluateCondsMerging(), TestbenchValuesXMLGeneration::Exec(), CreateAddressTranslation::Exec(), AllocationInformation::get_attribute_of_fu_per_op(), Schedule::get_cstep(), Schedule::get_cstep_end(), Schedule::GetEndingTime(), AllocationInformation::GetNodeTypePrec(), StorageValueInformation::Initialize(), cdfc_module_binding::initialize_connection_relation(), SerializeMutualExclusions::InternalExec(), mem_dominator_allocation::InternalExec(), SDCCodeMotion::InternalExec(), SwitchFix::InternalExec(), compute_implicit_calls::InternalExec(), rebuild_initialization::InternalExec(), CondExprRestructuring::InternalExec(), commutative_expr_restructuring::InternalExec(), VarComputation::InternalExec(), MultipleEntryIfReduction::InternalExec(), allocation::InternalExec(), tree_helper::is_system(), rebuild_initialization2::look_for_ROMs(), tree_helper::RecursiveGetTypesToBeDeclared(), and Schedule::UpdateTime().
CGetTreeReindex()
const tree_nodeRef tree_manager::CGetTreeReindex (const unsigned int i) const
Return a tree_reindex wrapping the i-th tree_node.
Parameters
i is the index of the tree_node.
Returns
the reference to the tree_node.
Definition at line 142 of file tree_manager.cpp.
References last_node_id, STR, THROW_ASSERT, and tree_nodes.
Referenced by tree_manipulation::CreateAddrExpr(), tree_manipulation::CreateGimpleAssignAddrExpr(), getAssign(), FixStructsPassedByValue::InternalExec(), parm_decl_taken_address_fix::InternalExec(), mem_cg_ext::InternalExec(), FunctionCallTypeCleanup::InternalExec(), IR_lowering::InternalExec(), rebuild_initialization2::look_for_ROMs(), and Bit_Value_opt::optimize().
check_for_decl()
bool tree_manager::check_for_decl (const tree_nodeRef & tn, const tree_managerRef & TM, std::string & symbol_name, std::string & symbol_scope, unsigned int node_id, const CustomUnorderedMap< unsigned int, std::string > & global_type_unql_symbol_table) [private]
check for decl_node and return true if not suitable for symbol table or otherwise its symbol_name and symbol_scope.
Parameters
tn is the tree node to be examinated
TM is a refcount to this TODO: could be removed?
symbol_name is where symbol name will be stored
symobl_scope is where symbol scope will be stored
node_id is the index of the tree node
Returns
true if symbol has not to be inserted into symbol table
check for name
check for memory_tag, parm_decl, result_decl
check for scope
declaration with type_node local to a function are not considered
Definition at line 2276 of file tree_manager.cpp.
References function_decl::builtin_flag, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FIRST_TOKEN, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_name(), srcp::include_name, INDENT_DBG_MEX, decl_node::mngl, decl_node::name, tree_helper::return_qualifier_prefix(), decl_node::scpe, function_decl::static_flag, STR, THROW_ASSERT, and test_panda::type.
Referenced by merge_tree_managers().
check_for_type()
bool tree_manager::check_for_type (const tree_nodeRef & tn, const tree_managerRef & TM, std::string & symbol_name, std::string & symbol_scope, const CustomUnorderedMapUnstable< std::string, unsigned int > & global_type_symbol_table, unsigned int node_id) [private]
check for type and return true if not suitable for symbol table or otherwise its symbol_name and symbol_scope.
integer_type and real_type have some duplication
Definition at line 2411 of file tree_manager.cpp.
References debug_level, DEBUG_LEVEL_PARANOIC, FIRST_TOKEN, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_type_name(), PRINT_DBG_MEX, tree_helper::return_qualifier_prefix(), STR, THROW_ASSERT, and test_panda::type.
Referenced by merge_tree_managers().
check_ssa_uses()
bool tree_manager::check_ssa_uses (unsigned int fun_id) const
check_ssa_uses check if the uses of a ssa are correct
Returns
true in case all the ssa uses are correct, false otherwise.
Definition at line 2638 of file tree_manager.cpp.
References tree_helper::ComputeSsaUses(), GET_INDEX_CONST_NODE, tree_node::get_kind(), GET_NODE, get_tree_node_const(), phi, sl, and THROW_ERROR.
Referenced by add_identifier_node().
collapse_into()
void tree_manager::collapse_into (const unsigned int & funID, CustomUnorderedMapUnstable< unsigned int, unsigned int > & stmt_to_bloc, const tree_nodeRef & tn, CustomUnorderedSet< unsigned int > & removed_nodes)
Collapse operations chains into the examinated node.
Parameters
funID is the index of the function
stmt_to_block maps each statement to its bloc
tn is the top tree node of the tree to be collapsed
removed_nodes is the set of nodes removed during collapsing
If there is a conversion to a not built-in type, type has to be declared; but if no variable survives, type will be not declared by the backend
If there is a conversion to a not built-in type, type has to be declared; but if no variable survives, type will be not declared by the backend
FIXME: If right part is a subtree, it should be completly duplicated; For the moment we just stop the collapsing
Update uses of right operand
Definition at line 345 of file tree_manager.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, collapse_into_counter, create_tree_node(), debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, erase_usage_info(), GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), get_next_vers(), GET_NODE, get_tree_node_const(), GetTreeReindex(), tree_helper::HasToBeDeclared(), INDENT_DBG_MEX, insert_usage_info(), new_tree_node_id(), Param, PrintGimple(), RecursiveReplaceTreeNode(), sl, STR, THROW_ASSERT, THROW_ERROR, TOK, TOK_OP0, TOK_OP1, TOK_ORIG, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VOLATILE, top(), and tree_node::ToString().
create_tree_node()
void tree_manager::create_tree_node (const unsigned int node_id, enum kind tree_node_type, std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > & tree_node_schema)
Factory method.
It creates a tree_node of type equal tree_node_type by using a relation (tree_node_schema) between tree node fields and their values.
Parameters
node_id is the node id of the created object.
tree_node_type is the type of the node added to the tree_manager expressed as a treeVocabularyTokenTypes.
tree_node_schema expresses the value of the field of the tree node created. For example the following code: std::map<int, std::string> identifier_schema; int identifier_node_id = TM->get_tree_node_n(); identifier_schema[TOK(TOK_STRG)]= `my_identifier`; TM->create_tree_node(identifier_node_id, TOK(TOK_IDENTIFIER_NODE), identifier_schema); will add an identifier node to the tree_manager TM.
Definition at line 259 of file tree_manager.cpp.
References CGetTreeNode(), tree_node_factory::create_tree_node(), DEBUG_LEVEL_VERY_PEDANTIC, GET_CLASS, INDENT_DBG_MEX, Param, and STR.
Referenced by dead_code_elimination::add_gimple_nop(), interface_infer::addGimpleNOPxVirtual(), Vectorize::AddGuards(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), HWCallInjection::buildBuiltinCall(), collapse_into(), tree_manipulation::create_binary_operation(), tree_manipulation::create_bit_size_type(), tree_manipulation::create_boolean_type(), tree_manipulation::create_default_integer_type(), tree_manipulation::create_default_unsigned_integer_type(), tree_manipulation::create_extract_bit_expr(), tree_manipulation::create_function_decl(), tree_manipulation::create_gimple_call(), short_circuit_taf::create_gimple_cond(), tree_manipulation::create_gimple_cond(), tree_manipulation::create_gimple_modify_stmt(), tree_manipulation::create_gimple_return(), tree_manipulation::create_goto(), tree_manipulation::create_identifier_node(), tree_manipulation::create_integer_type_with_prec(), tree_manipulation::create_label(), tree_manipulation::create_lut_expr(), PragmaAnalysis::create_map_pragma(), PragmaAnalysis::create_omp_pragma(), tree_manipulation::create_parm_decl(), tree_manipulation::create_phi_node(), tree_manipulation::create_pointer_type(), tree_manipulation::create_quaternary_operation(), tree_manipulation::create_result_decl(), create_return_and_fix_cfg(), tree_manipulation::create_size_type(), tree_manipulation::create_ssa_name(), tree_manipulation::create_ternary_operation(), tree_manipulation::create_translation_unit_decl(), tree_manipulation::create_unary_operation(), tree_manipulation::create_var_decl(), tree_manipulation::create_void_type(), tree_manipulation::CreateAddrExpr(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateCallExpr(), tree_manipulation::CreateDefaultUnsignedLongLongInt(), tree_manipulation::CreateEqExpr(), tree_manipulation::CreateIntegerCst(), tree_manipulation::CreateNopExpr(), tree_manipulation::CreateNotExpr(), tree_manipulation::CreateOrExpr(), tree_manipulation::CreateRealCst(), CreateUniqueIntegerCst(), tree_manipulation::CreateUnsigned(), tree_manipulation::CreateVectorBooleanType(), Vectorize::DuplicateIncrement(), HDLFunctionDeclFix::Exec(), PragmaAnalysis::Exec(), Vectorize::FixPhis(), PhiOpt::IdentifyPattern(), SerializeMutualExclusions::InternalExec(), SwitchFix::InternalExec(), rebuild_initialization::InternalExec(), CondExprRestructuring::InternalExec(), commutative_expr_restructuring::InternalExec(), MultipleEntryIfReduction::InternalExec(), operations_cfg_computation::InternalExec(), dead_code_elimination::kill_uses(), dead_code_elimination::kill_vdef(), rebuild_initialization2::look_for_ROMs(), merge_tree_managers(), multi_way_if::MergeCondCond(), multi_way_if::MergeCondMulti(), multi_way_if::MergeMultiCond(), multi_way_if::MergeMultiMulti(), Vectorize::Transform(), and virtual_phi_nodes_split::virtual_split_phi().
CreateUniqueIntegerCst()
tree_nodeRef tree_manager::CreateUniqueIntegerCst (long long int value, unsigned int type_index)
memoization of integer constants
Parameters
value is the integer value
type_index is the type of the integer constant
Returns
a tree reindex node for the integer value with as type type_index
Definition at line 2572 of file tree_manager.cpp.
References create_tree_node(), GetTreeReindex(), new_tree_node_id(), STR, TOK, TOK_TYPE, TOK_VALUE, and unique_integer_cst_map.
Referenced by add_identifier_node(), IR_lowering::array_ref_lowering(), constrainSSA(), tree_manipulation::create_integer_type_with_prec(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateEqExpr(), tree_manipulation::CreateNotExpr(), tree_manipulation::CreateOrExpr(), tree_manipulation::CreateVectorBooleanType(), IR_lowering::division_by_a_constant(), IR_lowering::expand_MC(), IR_lowering::expand_mult_const(), IR_lowering::expand_mult_highpart(), IR_lowering::expand_sdiv_pow2(), IR_lowering::expand_smod_pow2(), tree_manipulation::ExtractCondition(), parm_decl_taken_address_fix::InternalExec(), UnComparisonLowering::InternalExec(), compute_implicit_calls::InternalExec(), CondExprRestructuring::InternalExec(), IR_lowering::InternalExec(), dead_code_elimination::kill_uses(), and Bit_Value_opt::optimize().
erase_usage_info()
void tree_manager::erase_usage_info (const tree_nodeRef & tn, const tree_nodeRef & stmt) [private]
Erase the information about variable usage (remove stmt from use_stmts attribute) in ssa variables recursively contained in node tn.
Parameters
tn is the node from which the recursion begin.
stmt is the statement that is removed from the usage vector of ssa variables.
Definition at line 1277 of file tree_manager.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by collapse_into().
find()
unsigned int tree_manager::find (enum kind tree_node_type, const std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > & tree_node_schema)
if there exist return the node id of a tree node compatible with the tree_node_schema and of type tree_node_type.
Parameters
tree_node_type is the type of the node added to the tree_manager expressed as a treeVocabularyTokenTypes.
tree_node_schema expresses the value of the field of the tree node created.
check if the corresponding tree node has been already created or not
Definition at line 296 of file tree_manager.cpp.
References tree_node_finder::check(), find_cache, find_identifier_nodeID(), tree_node::GetString(), STOK, STOK2, THROW_ERROR, TOK, TOK_OPERATOR, TOK_STRG, and tree_nodes.
Referenced by tree_manipulation::create_bit_size_type(), tree_manipulation::create_boolean_type(), tree_manipulation::create_default_integer_type(), tree_manipulation::create_default_unsigned_integer_type(), tree_manipulation::create_function_decl(), tree_manipulation::create_goto(), tree_manipulation::create_identifier_node(), tree_manipulation::create_integer_type_with_prec(), tree_manipulation::create_label(), tree_manipulation::create_pointer_type(), tree_manipulation::create_size_type(), tree_manipulation::create_translation_unit_decl(), tree_manipulation::create_void_type(), tree_manipulation::CreateDefaultUnsignedLongLongInt(), tree_manipulation::CreateUnsigned(), tree_manipulation::CreateVectorBooleanType(), and HDLFunctionDeclFix::Exec().
find_identifier_nodeID()
unsigned int tree_manager::find_identifier_nodeID (const std::string & str) const
Return the nodeID of the identifier_node representing string str.
In case there is not that identifier_node it returns 0.
Parameters
str is the identifier we are looking for.
Definition at line 2475 of file tree_manager.cpp.
References add_identifier_node(), ASSERT_PARAMETER, identifiers_unique_table, STOK, THROW_ASSERT, and TOK_OPERATOR.
Referenced by find(), and merge_tree_managers().
find_sc_main_node()
unsigned int tree_manager::find_sc_main_node () const
Determine the index node of `sc_main` function in tree_node vector.
Definition at line 177 of file tree_manager.cpp.
References function_index().
function_index()
unsigned int tree_manager::function_index (const std::string & function_name) const
Return the index of a function given its name.
Parameters
tm is the tree_manager
function_name is the name of the function
Returns
the treenode_index of the function_decl
We have already found a function_id corresponding to this name
If this is a clone, return the index of this, otherwise do nothing so that first encountered value is returned
Definition at line 182 of file tree_manager.cpp.
References function_decl_nodes, GET_NODE, and tree_helper::print_function_name().
Referenced by Vectorize::ClassifyTreeNode(), HLS_step::ComputeRelationships(), CallGraphManager::ComputeRootAndReachedFunctions(), tree_manipulation::create_function_decl(), CreateAddressTranslation::Exec(), find_sc_main_node(), FixStructsPassedByValue::InternalExec(), compute_implicit_calls::InternalExec(), and constant_flop_wrapper::InternalExec().
get_added_goto()
unsigned int tree_manager::get_added_goto () const
Return the number of added gotos.
Definition at line 2537 of file tree_manager.cpp.
References added_goto.
get_function_decl_node_n()
unsigned long tree_manager::get_function_decl_node_n () const
Return the number of function_decl_node.
Returns
the number of function decl nodes.
Definition at line 291 of file tree_manager.cpp.
References function_decl_nodes.
get_implementation_node()
unsigned int tree_manager::get_implementation_node (unsigned int decl_node) const
Return the index of function_decl node that implements the declaration node.
Parameters
decl_node is the index of the declaration node
Returns
the index of implementation node
Definition at line 108 of file tree_manager.cpp.
References decl_node, get_tree_node_const(), STR, and THROW_ASSERT.
Referenced by call_graph_computation::call_graph_computation_recursive(), call_graph_computation::Exec(), constant_flop_wrapper::InternalExec(), and tree_helper::print_type().
get_n_pl()
unsigned int tree_manager::get_n_pl () const
return the number of parallel loops
Definition at line 1701 of file tree_manager.cpp.
References n_pl.
get_next_available_tree_node_id()
unsigned int tree_manager::get_next_available_tree_node_id () const
return the next available tree node id.
Definition at line 281 of file tree_manager.cpp.
References last_node_id.
Referenced by CallGraphManager::ComputeRootAndReachedFunctions(), tree_manipulation::create_function_decl(), and merge_tree_managers().
get_next_vers()
unsigned int tree_manager::get_next_vers ()
Return the next unused version number for ssa variables.
Definition at line 2505 of file tree_manager.cpp.
References DEBUG_LEVEL_VERY_PEDANTIC, GET_CLASS, tree_node::get_kind(), INDENT_DBG_MEX, next_vers, Param, STR, and tree_nodes.
Referenced by add_identifier_node(), Vectorize::AddGuards(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyMultiMerge(), collapse_into(), short_circuit_taf::create_gimple_cond(), tree_manipulation::create_ssa_name(), Vectorize::DuplicateIncrement(), Vectorize::FixPhis(), SerializeMutualExclusions::InternalExec(), CondExprRestructuring::InternalExec(), commutative_expr_restructuring::InternalExec(), MultipleEntryIfReduction::InternalExec(), Vectorize::Transform(), and virtual_phi_nodes_split::virtual_split_phi().
get_removable_pointer_plus()
unsigned int tree_manager::get_removable_pointer_plus () const
Return the number of not removed pointer plus.
Definition at line 2557 of file tree_manager.cpp.
References removable_pointer_plus.
get_removed_pointer_plus()
unsigned int tree_manager::get_removed_pointer_plus () const
Return the number of removed pointer plus.
Definition at line 2547 of file tree_manager.cpp.
References removed_pointer_plus.
get_tree_node_const()
const tree_nodeRef tree_manager::get_tree_node_const (unsigned int i) const
Return the reference to the i-th tree_node Constant version of get_tree_node.
Parameters
i is the index of the tree_node of the considered function.
Returns
the reference to the tree_node. FIXME: this should return tree_nodeConstRef
Definition at line 155 of file tree_manager.cpp.
References last_node_id, STR, THROW_ASSERT, and tree_nodes.
Referenced by memory::add_internal_symbol(), Vectorize::AddGuards(), operations_graph_constructor::AddOperation(), mux_connection_binding::address_precision(), TestbenchMemoryAllocation::AllocTestbenchMemory(), determine_memory_accesses::analyze_node(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), AllocationInformation::can_be_asynchronous_ram(), AllocationInformation::can_implement_set(), Schedule::CanBeMoved(), check_ssa_uses(), collapse_into(), memory::compute_next_base_address(), CreateAddressTranslation::ComputeAddress(), Schedule::ComputeCriticalPath(), PhiOpt::ComputeFrontendRelationships(), mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), tree_manipulation::create_function_decl(), tree_manipulation::create_goto(), tree_manipulation::create_label(), PragmaAnalysis::create_map_pragma(), PragmaAnalysis::create_omp_pragma(), mux_connection_binding::create_single_conn(), tree_manipulation::CreateGimpleAssign(), mux_connection_binding::determine_connection(), Vectorize::DuplicateIncrement(), Schedule::EvaluateCondsMerging(), Schedule::EvaluateMultiWayIfsMerging(), HDLFunctionDeclFix::Exec(), TestbenchValuesXMLGeneration::Exec(), PragmaAnalysis::Exec(), call_graph_computation::Exec(), tree_helper::extract_array_indexes(), mux_connection_binding::extract_parm_decl(), Vectorize::FixPhis(), tree_helper::get_array_data_bitsize(), tree_helper::get_array_dim_and_bitsize(), tree_helper::get_array_dimensions(), tree_helper::get_array_var(), tree_helper::get_asm_string(), tree_helper::get_base_index(), PragmaAnalysis::get_call_parameter(), HLS_manager::get_constant_string(), AllocationInformation::get_cycles(), tree_helper::get_definition(), AllocationInformation::get_execution_time(), tree_helper::get_field_idx(), tree_helper::get_formal_ith(), fsm_controller::get_guard_value(), get_implementation_node(), AllocationInformation::get_initiation_time(), tree_helper::get_multi_way_if_pos(), liveness::get_op_where_defined(), tree_helper::get_parameter_types(), tree_helper::get_pointed_type(), application_manager::get_produced_value(), HLS_manager::get_required_values(), AllocationInformation::get_stage_period(), tree_helper::get_type_index(), tree_helper::get_type_name(), tree_helper::get_var_alignment(), Schedule::GetBBEndingTime(), tree_helper::GetElements(), tree_helper::GetFunctionSize(), AllocationInformation::GetNodeTypePrec(), Schedule::GetReadyTime(), tree_helper::GetRealType(), AllocationInformation::GetStatementArea(), tree_helper::GetUnqualified(), tree_helper::HasToBeDeclared(), PhiOpt::IdentifyPattern(), RemoveEndingIf::Initialize(), MultipleEntryIfReduction::Initialize(), multi_way_if::Initialize(), PhiOpt::Initialize(), parm_decl_taken_address_fix::InternalExec(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), HWCallInjection::InternalExec(), SerializeMutualExclusions::InternalExec(), mem_dominator_allocation::InternalExec(), SDCCodeMotion::InternalExec(), BasicBlocksCfgComputation::InternalExec(), FunctionCallTypeCleanup::InternalExec(), SwitchFix::InternalExec(), CallGraphBuiltinCall::InternalExec(), remove_clobber_ga::InternalExec(), call_expr_fix::InternalExec(), compute_implicit_calls::InternalExec(), extract_patterns::InternalExec(), fanout_opt::InternalExec(), rebuild_initialization::InternalExec(), NI_SSA_liveness::InternalExec(), BlockFix::InternalExec(), SplitReturn::InternalExec(), Bit_Value_opt::InternalExec(), determine_memory_accesses::InternalExec(), constant_flop_wrapper::InternalExec(), commutative_expr_restructuring::InternalExec(), CondExprRestructuring::InternalExec(), virtual_phi_nodes_split::InternalExec(), use_counting::InternalExec(), simple_code_motion::InternalExec(), short_circuit_taf::InternalExec(), CSE::InternalExec(), MultipleEntryIfReduction::InternalExec(), lut_transformation::InternalExec(), IR_lowering::InternalExec(), CheckSystemType::InternalExec(), operations_cfg_computation::InternalExec(), Vectorize::InternalExec(), allocation::InternalExec(), cdfc_module_binding::InternalExec(), tree_helper::is_a_complex(), tree_helper::is_a_misaligned_vector(), tree_helper::is_a_struct(), tree_helper::is_a_variable(), tree_helper::is_a_vector(), tree_helper::is_a_void(), tree_helper::is_an_addr_expr(), tree_helper::is_an_array(), tree_helper::is_an_enum(), tree_helper::is_an_union(), tree_helper::is_bool(), tree_helper::is_builtin_channel(), tree_helper::is_channel(), tree_helper::is_clock(), tree_helper::is_concat_bit_ior_expr(), tree_helper::is_const_type(), tree_helper::is_constant(), tree_helper::is_event(), tree_helper::is_extern(), tree_helper::is_fully_resolved(), tree_helper::is_function_pointer_type(), tree_helper::is_function_type(), tree_helper::is_in_port(), tree_helper::is_inout_port(), tree_helper::is_int(), is_large_integer(), tree_helper::is_module(), tree_helper::is_natural(), AllocationInformation::is_operation_bounded(), AllocationInformation::is_operation_PI_registered(), tree_helper::is_out_port(), tree_helper::is_packed(), tree_helper::is_packed_access(), tree_helper::is_parameter(), tree_helper::is_port(), HLS_manager::is_reading_writing_function(), tree_helper::is_real(), tree_helper::is_SC_BIND_PROXY_NIL(), tree_helper::is_signal(), tree_helper::is_simple_pointer_plus_test(), tree_helper::is_ssa_name(), tree_helper::is_static(), tree_helper::is_system(), tree_helper::is_unsigned(), AllocationInformation::is_vertex_bounded_with(), tree_helper::is_virtual(), tree_helper::is_volatile(), tree_helper::IsAligned(), mux_connection_binding::isConstantObj(), mux_connection_binding::isZeroObj(), rebuild_initialization2::look_for_ROMs(), merge_tree_managers(), multi_way_if::MergeCondMulti(), multi_way_if::MergeMultiCond(), multi_way_if::MergeMultiMulti(), tree_helper::name_function(), tree_helper::name_tmpl(), tree_helper::name_type(), tree_helper::print_type(), TestbenchGenerationBaseStep::print_var_init(), tree_helper::record_name(), tree_helper::RecursiveGetTypesToBeDeclared(), tree_helper::size(), moduleGenerator::specialize_fu(), Vectorize::Transform(), vcd_trace_head::update(), Schedule::UpdateTime(), MinimalInterfaceTestbench::write_input_signal_declaration(), TestbenchGenerationBaseStep::write_output_checks(), WishboneInterfaceTestbench::write_signals(), and WishboneInterfaceTestbench::write_wishbone_input_signal_declaration().
get_unremoved_pointer_plus()
unsigned int tree_manager::get_unremoved_pointer_plus () const
Return the number of not removed pointer plus.
Definition at line 2567 of file tree_manager.cpp.
References unremoved_pointer_plus.
GetAllFunctions()
const CustomUnorderedSet< unsigned int > tree_manager::GetAllFunctions () const
Returns all the functions in the tree_manager.
Returns
all the functions
Definition at line 2494 of file tree_manager.cpp.
References function_decl_nodes, and functions.
Referenced by HDLFunctionDeclFix::Exec(), PragmaAnalysis::Exec(), and call_graph_computation::Exec().
GetTreeNode()
tree_nodeRef tree_manager::GetTreeNode (const unsigned int index) const
Return the index-th tree_node (modifiable version)
Parameters
index is the index of the tree node to be returned
Returns
the index-the tree_node
Definition at line 149 of file tree_manager.cpp.
References STR, THROW_ASSERT, and tree_nodes.
Referenced by HWCallInjection::buildBuiltinCall(), parm2ssa::Exec(), string_cst_fix::Exec(), UnComparisonLowering::InternalExec(), CallGraphBuiltinCall::InternalExec(), HDLVarDeclFix::InternalExec(), dead_code_elimination::InternalExec(), constant_flop_wrapper::InternalExec(), VarDeclFix::InternalExec(), CheckSystemType::InternalExec(), and moduleGenerator::specialize_fu().
GetTreeReindex()
tree_nodeRef tree_manager::GetTreeReindex (const unsigned int i)
Return a tree_reindex wrapping the i-th tree_node.
Parameters
i is the index of the tree_node.
Returns
the reference to the tree_node.
Definition at line 132 of file tree_manager.cpp.
References last_node_id, STR, THROW_ASSERT, and tree_nodes.
Referenced by dead_code_elimination::add_gimple_nop(), gimple_phi::AddDefEdge(), interface_infer::addGimpleNOPxVirtual(), Vectorize::AddGuards(), operations_graph_constructor::AddOperation(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), HWCallInjection::buildBuiltinCall(), collapse_into(), tree_manipulation::create_binary_operation(), tree_manipulation::create_bit_size_type(), tree_manipulation::create_boolean_type(), tree_manipulation::create_default_integer_type(), tree_manipulation::create_default_unsigned_integer_type(), tree_manipulation::create_extract_bit_expr(), tree_manipulation::create_function_decl(), tree_manipulation::create_gimple_call(), short_circuit_taf::create_gimple_cond(), tree_manipulation::create_gimple_cond(), tree_manipulation::create_gimple_modify_stmt(), tree_manipulation::create_gimple_return(), tree_manipulation::create_goto(), tree_manipulation::create_identifier_node(), tree_manipulation::create_integer_type_with_prec(), tree_manipulation::create_label(), tree_manipulation::create_lut_expr(), tree_manipulation::create_parm_decl(), tree_manipulation::create_phi_node(), tree_manipulation::create_pointer_type(), tree_manipulation::create_quaternary_operation(), tree_manipulation::create_result_decl(), create_return_and_fix_cfg(), tree_manipulation::create_size_type(), tree_manipulation::create_ssa_name(), tree_manipulation::create_ternary_operation(), tree_manipulation::create_translation_unit_decl(), tree_manipulation::create_unary_operation(), tree_manipulation::create_var_decl(), tree_manipulation::create_void_type(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateCallExpr(), tree_manipulation::CreateDefaultUnsignedLongLongInt(), tree_manipulation::CreateEqExpr(), tree_manipulation::CreateGimpleAssign(), tree_manipulation::CreateIntegerCst(), tree_manipulation::CreateNopExpr(), tree_manipulation::CreateNotExpr(), tree_manipulation::CreateOrExpr(), tree_manipulation::CreateRealCst(), CreateUniqueIntegerCst(), tree_manipulation::CreateUnsigned(), tree_manipulation::CreateVectorBooleanType(), Vectorize::DuplicateIncrement(), Schedule::EvaluateCondsMerging(), HDLFunctionDeclFix::Exec(), tree_manipulation::ExtractCondition(), Vectorize::FixPhis(), SerializeMutualExclusions::InternalExec(), UnComparisonLowering::InternalExec(), SDCCodeMotion::InternalExec(), SwitchFix::InternalExec(), remove_clobber_ga::InternalExec(), compute_implicit_calls::InternalExec(), rebuild_initialization::InternalExec(), constant_flop_wrapper::InternalExec(), commutative_expr_restructuring::InternalExec(), CondExprRestructuring::InternalExec(), CSE::InternalExec(), MultipleEntryIfReduction::InternalExec(), IR_lowering::InternalExec(), operations_cfg_computation::InternalExec(), Vectorize::InternalExec(), dead_code_elimination::kill_uses(), dead_code_elimination::kill_vdef(), rebuild_initialization2::look_for_ROMs(), merge_tree_managers(), multi_way_if::MergeCondCond(), multi_way_if::MergeCondMulti(), multi_way_if::MergeMultiCond(), multi_way_if::MergeMultiMulti(), new_tree_node_id(), Bit_Value_opt::optimize(), gimple_phi::RemoveDefEdge(), gimple_phi::ReplaceDefEdge(), Vectorize::Transform(), and virtual_phi_nodes_split::virtual_split_phi().
increment_removable_pointer_plus()
void tree_manager::increment_removable_pointer_plus ()
Increment the number of removable pointer plus.
Definition at line 2552 of file tree_manager.cpp.
References removable_pointer_plus.
increment_removed_pointer_plus()
void tree_manager::increment_removed_pointer_plus ()
Increment the number of removed pointer plus.
Definition at line 2542 of file tree_manager.cpp.
References removed_pointer_plus.
increment_unremoved_pointer_plus()
void tree_manager::increment_unremoved_pointer_plus ()
Increment the number of not removed pointer plus.
Definition at line 2562 of file tree_manager.cpp.
References unremoved_pointer_plus.
insert_usage_info()
void tree_manager::insert_usage_info (const tree_nodeRef & tn, const tree_nodeRef & stmt) [private]
Insert the information about variable usage (insert stmt in use_stmts attribute) in ssa variables recursively contained in node tn.
Parameters
tn is the node from which the recursion begin.
stmt is the statement that is inserted in the usage vector of ssa variables.
Definition at line 1491 of file tree_manager.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by collapse_into().
is_CPP()
bool tree_manager::is_CPP () const
is_CPP return true in case we have at least one CPP source code
Returns
true when at least one translation unit is written in C++
Definition at line 2593 of file tree_manager.cpp.
References Param.
Referenced by add_identifier_node(), tree_helper::print_function_name(), and tree_helper::print_type().
is_top_function()
bool tree_manager::is_top_function (const function_decl * fd) const
is_top_function checks if a function is one of the application top functions.
Parameters
fd is the function decl
Returns
true in case fd is a top function
Definition at line 2598 of file tree_manager.cpp.
References tree_node::get_kind(), GET_NODE, decl_node::name, and Param.
Referenced by add_identifier_node(), and tree_helper::print_function_name().
is_tree_node()
bool tree_manager::is_tree_node (unsigned int i) const
Return true if there exists a tree node associated with the given id, false otherwise.
Parameters
i is the index of the tree_node to be checked
Definition at line 170 of file tree_manager.cpp.
References tree_nodes.
merge_tree_managers()
void tree_manager::merge_tree_managers (const tree_managerRef & TM_source)
merge two tree manager: this with TM_source
Parameters
TM_source is one of the tree_manager.
a declaration is uniquely identified by the name and by the scope in case the decl_node has a mangle the associated identifier_node is unique a decl_node without name is not added to the symbol table a decl_node local to a function_decl (scpe is a function_decl) is not added to the symbol table a decl_node local to a type_node without name is not added to the symbol table a static decl_node is not added to the symbol table memory_tag, parm_decl, result_decl are not added to the symbol table declaration with type_node local to a function are not considered the key of the declaration symbol table is structured as `name--scope` the value of the declaration symbol table is the nodeID of the tree_node in the tree_manager
a type_node without name is not added to the symbol table a type_node local to a function_decl is not added to the symbol table the key of the type symbol table is structured as `name` the value of the type symbol table is the nodeID of the tree_node in the tree_manager
this table is used to give a name to unqualified record or union
global static variable and function become global so we need some sort of uniquification
build the symbol tables of tree_node inheriting from type_node and then from decl_node; decl_nodes have to be examinated later since they have to be examinated after the record/union types???
give a name to unql where possible
check for decl_node
check for static
check for function_decl undefined
source static function declaration used to correctly rename declaration and definition of a function
the key is the old index while the values is the new index
At the moment the reverse of remap; it is filled only with function_decl without body
For each static function in source_tree_manager the index of the tree node (in source_tree_manager) of its forward declaration
For each static function in TM?source the index of the tree node (in source_tree_manager) of its implementation
set of nodes that will be added to the current tree manager (this)
FIXME: during one of the analysis of the tree nodes of source_tree_manager, new nodes can be inserted; if source_tree_manager->tree_nodes is a undirected_map, the insertion of a new node can invalidate the iterators because of rehash; for this reason we temporary copy the unordered_map in map
remap tree_node from source_tree_manager to this tree_manager first remap the types and then decl
check for decl_node
overwrite gst_it->second
overwrite gst_it->second
overwrite gst_it->second
overwrite gst_it->second
remap tree_node from source_tree_manager to this tree_manager
check for decl_node
check for static
Management of forward declaration of static function
Implementation node
If this is the implementation already remaps so that also forward declaration can be remapped on the same node
If we have already encountered forward declaration, remap it on the same node
Forward declaration
Check if we have already encountered function implementation, remap this on the same node
CHECK: reference to source_tree_manager tree_node in tree_reindex
static function or var_decl with a conflicting name so we fix the name... and we fix in the source tree_manager
CHECK: reference to source_tree_manager tree_node in tree_reindex
The following statements force ti_source.first to overwrite gst_it->second
If the symbol is in reverse_remap, it means that is a function_decl without body coming from other; it has not to be remapped
already performed
tree node visitor
compute the vertexes reached from all function_decl of source_tree_manager
Definition at line 1706 of file tree_manager.cpp.
References check_for_decl(), check_for_type(), counter, tree_node_index_factory::create_tree_node(), create_tree_node(), debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, find_identifier_nodeID(), FIRST_TOKEN, function_decl_nodes, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), get_next_available_tree_node_id(), get_tree_node_const(), GetTreeReindex(), INDENT_DBG_MEX, new_tree_node_id(), Param, STR, THROW_ASSERT, TOK, TOK_STRG, tree_nodes, and tree_node::visit().
Referenced by create_tree_manager::Exec(), GccWrapper::FillTreeManager(), and main().
new_tree_node_id()
unsigned int tree_manager::new_tree_node_id (const unsigned int ask = 0)
Return a new node id in the intermediate representation.
Parameters
ask is the requested id; if it is not used will be returned otherwise a new id
Returns
the new node is
Definition at line 269 of file tree_manager.cpp.
References GetTreeReindex(), last_node_id, and tree_nodes.
Referenced by dead_code_elimination::add_gimple_nop(), interface_infer::addGimpleNOPxVirtual(), Vectorize::AddGuards(), PhiOpt::ApplyIfMerge(), PhiOpt::ApplyIfRemove(), PhiOpt::ApplyMultiMerge(), PhiOpt::ApplyMultiRemove(), HWCallInjection::buildBuiltinCall(), collapse_into(), tree_manipulation::create_binary_operation(), tree_manipulation::create_bit_size_type(), tree_manipulation::create_boolean_type(), tree_manipulation::create_default_integer_type(), tree_manipulation::create_default_unsigned_integer_type(), tree_manipulation::create_extract_bit_expr(), tree_manipulation::create_function_decl(), tree_manipulation::create_gimple_call(), short_circuit_taf::create_gimple_cond(), tree_manipulation::create_gimple_cond(), tree_manipulation::create_gimple_modify_stmt(), tree_manipulation::create_gimple_return(), tree_manipulation::create_goto(), tree_manipulation::create_identifier_node(), tree_manipulation::create_integer_type_with_prec(), tree_manipulation::create_label(), tree_manipulation::create_lut_expr(), PragmaAnalysis::create_map_pragma(), PragmaAnalysis::create_omp_pragma(), tree_manipulation::create_parm_decl(), tree_manipulation::create_phi_node(), tree_manipulation::create_pointer_type(), tree_manipulation::create_quaternary_operation(), interface_infer::create_Read_function(), tree_manipulation::create_result_decl(), create_return_and_fix_cfg(), tree_manipulation::create_size_type(), tree_manipulation::create_ssa_name(), tree_manipulation::create_ternary_operation(), tree_manipulation::create_translation_unit_decl(), tree_manipulation::create_unary_operation(), tree_manipulation::create_var_decl(), tree_manipulation::create_void_type(), interface_infer::create_Write_function(), tree_manipulation::CreateAddrExpr(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateCallExpr(), tree_manipulation::CreateDefaultUnsignedLongLongInt(), tree_manipulation::CreateEqExpr(), tree_manipulation::CreateNopExpr(), tree_manipulation::CreateNotExpr(), tree_manipulation::CreateOrExpr(), CreateUniqueIntegerCst(), tree_manipulation::CreateUnsigned(), tree_manipulation::CreateVectorBooleanType(), Vectorize::DuplicateIncrement(), HDLFunctionDeclFix::Exec(), Vectorize::FixPhis(), PhiOpt::IdentifyPattern(), FixStructsPassedByValue::InternalExec(), mem_cg_ext::InternalExec(), SerializeMutualExclusions::InternalExec(), SwitchFix::InternalExec(), rebuild_initialization::InternalExec(), commutative_expr_restructuring::InternalExec(), CondExprRestructuring::InternalExec(), MultipleEntryIfReduction::InternalExec(), operations_cfg_computation::InternalExec(), dead_code_elimination::kill_uses(), dead_code_elimination::kill_vdef(), rebuild_initialization2::look_for_ROMs(), merge_tree_managers(), multi_way_if::MergeCondCond(), multi_way_if::MergeCondMulti(), multi_way_if::MergeMultiCond(), multi_way_if::MergeMultiMulti(), Bit_Value_opt::optimize(), Vectorize::Transform(), and virtual_phi_nodes_split::virtual_split_phi().
print()
void tree_manager::print (std::ostream & os) const
Function that prints the class tree_manager.
Parameters
Param is the set of the parameter
os is the stream where tree_manager will be printed
Definition at line 219 of file tree_manager.cpp.
References GccWrapper::current_gcc_version, GccWrapper::current_plugin_version, last_node_id, Param, STOK, TOK_GCC_VERSION, TOK_PLUGIN_VERSION, and tree_nodes.
Referenced by FrontendFlowStep::PrintTreeManager().
PrintGimple()
void tree_manager::PrintGimple (std::ostream & os, const bool use_uid) const
Function that prints the bodies of function in gimple format.
Parameters
os is the stream where bodies will be printed
use_uid tells if uid of gimple index has to be used
Definition at line 245 of file tree_manager.cpp.
References function_decl_nodes.
Referenced by collapse_into(), Vectorize::InternalExec(), and FrontendFlowStep::PrintTreeManager().
RecursiveReplaceTreeNode()
void tree_manager::RecursiveReplaceTreeNode (tree_nodeRef & tn, const tree_nodeRef old_node, const tree_nodeRef & new_node, const tree_nodeRef & stmt, bool definition)
Replace the occurrences of tree node old_node with new_node in statement identified by tn.
Operates recursively. NOTE: tn must be a reference since we are replacing the tree_node in other tree_node fields
Parameters
tn is the statement from which the recursion begin. It must be a statement.
old_node is the node whose occurrences have to be replace
new_node is the node that replaces occurrences of old_node
stmt is the statement from which the recursion originates (necessary to update ssa_nodes usage information)
definition is true if old_node is a ssa_name in the left part of a gimple_assign
Check if we need to update uses or definitions
Definition at line 891 of file tree_manager.cpp.
References test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, tree_helper::ComputeSsaUses(), counter, DEBUG_LEVEL_VERY_PEDANTIC, GET_CLASS, GET_CONST_NODE, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, tree_node::index, Param, STR, THROW_ASSERT, THROW_ERROR, and tree_node::ToString().
Referenced by collapse_into(), FunctionCallTypeCleanup::InternalExec(), and ReplaceTreeNode().
ReplaceTreeNode()
void tree_manager::ReplaceTreeNode (const tree_nodeRef & tn, const tree_nodeRef & old_node, const tree_nodeRef & new_node)
Replace the occurrences of tree node old_node with new_node in statement identified by tn.
Operates recursively.
Parameters
tn is the statement from which the recursion begin. It must be a statement.
old_node is the node whose occurrences have to be replace
new_node is thenode that replaces occurrences of old_node
Temporary variable used to pass first argument of RecursiveReplaceTreeNode by reference. Since it is a gimple_node it has not to be replaced
Definition at line 881 of file tree_manager.cpp.
References GET_NODE, RecursiveReplaceTreeNode(), STR, THROW_ASSERT, and tree_node::ToString().
Referenced by add_identifier_node(), interface_infer::create_Read_function(), Vectorize::DuplicateIncrement(), FixStructsPassedByValue::InternalExec(), parm_decl_taken_address_fix::InternalExec(), UnComparisonLowering::InternalExec(), FunctionCallTypeCleanup::InternalExec(), fanout_opt::InternalExec(), dead_code_elimination::InternalExec(), constant_flop_wrapper::InternalExec(), simple_code_motion::InternalExec(), CSE::InternalExec(), MultipleEntryIfReduction::InternalExec(), PhiOpt::InternalExec(), dead_code_elimination::kill_uses(), Bit_Value_opt::optimize(), PhiOpt::RemoveCondExpr(), and PhiOpt::SinglePhiOptimization().
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, tree_manager & s) [friend]
Friend definition of the << operator.
Definition at line 333 of file tree_manager.hpp.
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const tree_managerRef & s) [friend]
Friend definition of the << operator.
Pointer version.
Definition at line 342 of file tree_manager.hpp.
Field Documentation
added_goto
unsigned int tree_manager::added_goto [private]
the number of added goto
Definition at line 112 of file tree_manager.hpp.
Referenced by add_goto(), and get_added_goto().
already_visited
CustomUnorderedSet<tree_nodeRef> tree_manager::already_visited [private]
set of already examined addr_expr used to avoid circular recursion
Definition at line 106 of file tree_manager.hpp.
collapse_into_counter
unsigned int tree_manager::collapse_into_counter [private]
Index of current call of collapse_into_counter.
Definition at line 144 of file tree_manager.hpp.
Referenced by collapse_into().
debug_level
int tree_manager::debug_level [private]
The debug level.
Definition at line 124 of file tree_manager.hpp.
Referenced by check_for_decl(), check_for_type(), collapse_into(), erase_usage_info(), insert_usage_info(), and merge_tree_managers().
find_cache
CustomUnorderedMapUnstable<std::string, unsigned int> tree_manager::find_cache [private]
cache for tree_manager::find
Definition at line 87 of file tree_manager.hpp.
Referenced by find().
function_decl_nodes
std::map<unsigned int, tree_nodeRef> tree_manager::function_decl_nodes [private]
Variable containing set of function_declaration with their index node.
Definition at line 100 of file tree_manager.hpp.
Referenced by add_function(), function_index(), get_function_decl_node_n(), GetAllFunctions(), merge_tree_managers(), and PrintGimple().
identifiers_unique_table
CustomUnorderedMapUnstable<std::string, unsigned int> tree_manager::identifiers_unique_table [private]
this table stores all identifier_nodes with their nodeID.
Definition at line 130 of file tree_manager.hpp.
Referenced by find_identifier_nodeID().
last_node_id
unsigned int tree_manager::last_node_id [private]
last node_id used
Definition at line 127 of file tree_manager.hpp.
Referenced by AddTreeNode(), CGetTreeNode(), CGetTreeReindex(), get_next_available_tree_node_id(), get_tree_node_const(), GetTreeReindex(), new_tree_node_id(), and print().
n_pl
unsigned int tree_manager::n_pl [private]
the number of parallel loops
Definition at line 109 of file tree_manager.hpp.
Referenced by add_parallel_loop(), and get_n_pl().
next_vers
unsigned int tree_manager::next_vers [private]
Next version number for ssa variables.
Definition at line 141 of file tree_manager.hpp.
Referenced by get_next_vers().
Param
const ParameterConstRef tree_manager::Param [private]
Set of parameters.
Definition at line 135 of file tree_manager.hpp.
Referenced by collapse_into(), create_tree_node(), get_next_vers(), is_CPP(), is_top_function(), merge_tree_managers(), print(), and RecursiveReplaceTreeNode().
removable_pointer_plus
unsigned int tree_manager::removable_pointer_plus [private]
the number of removable pointer_plus
Definition at line 118 of file tree_manager.hpp.
Referenced by get_removable_pointer_plus(), and increment_removable_pointer_plus().
removed_pointer_plus
unsigned int tree_manager::removed_pointer_plus [private]
the number of removed pointer_plus
Definition at line 115 of file tree_manager.hpp.
Referenced by get_removed_pointer_plus(), and increment_removed_pointer_plus().
stack
std::deque<tree_nodeRef> tree_manager::stack [private]
list of examining statements during collapse_into recursion
Definition at line 103 of file tree_manager.hpp.
string_to_kind
CustomUnorderedMap<std::string, enum kind> tree_manager::string_to_kind [private]
map between string and corresponding enum kinds
Definition at line 84 of file tree_manager.hpp.
tree_nodes
OrderedMapStd<unsigned int, tree_nodeRef> tree_manager::tree_nodes [private]
Variable containing set of tree_nodes.
Definition at line 95 of file tree_manager.hpp.
Referenced by AddTreeNode(), CGetTreeNode(), CGetTreeReindex(), find(), get_next_vers(), get_tree_node_const(), GetTreeNode(), GetTreeReindex(), is_tree_node(), merge_tree_managers(), new_tree_node_id(), and print().
unique_integer_cst_map
CustomUnorderedMap<std::pair<long long int, unsigned int>, tree_nodeRef> tree_manager::unique_integer_cst_map [private]
Definition at line 132 of file tree_manager.hpp.
Referenced by CreateUniqueIntegerCst().
unremoved_pointer_plus
unsigned int tree_manager::unremoved_pointer_plus [private]
the number of unremoved pointer_plus
Definition at line 121 of file tree_manager.hpp.
Referenced by get_unremoved_pointer_plus(), and increment_unremoved_pointer_plus().
uses_erase_temp
CustomUnorderedMap<ssa_name*, tree_nodeRef> tree_manager::uses_erase_temp [private]
Map containing temporary information for ssa_name uses deletion.
Definition at line 138 of file tree_manager.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_manager.cpp