LoadDefaultTechnology Class Reference
Step which loads default technology libraries.
#include <load_default_technology.hpp>
Public Member Functions
LoadDefaultTechnology (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~LoadDefaultTechnology () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Step which loads default technology libraries.
Definition at line 56 of file load_default_technology.hpp.
Constructor & Destructor Documentation
LoadDefaultTechnology()
LoadDefaultTechnology::LoadDefaultTechnology (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Autoheader include.
Parameters
TM is the technology manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
Header include parser/polixml include polixml include STD include STL include technology include utility include
Definition at line 66 of file load_default_technology.cpp.
References LOAD_DEFAULT_TECHNOLOGY, and ~LoadDefaultTechnology().
 LoadDefaultTechnology()
LoadDefaultTechnology::~LoadDefaultTechnology () [override], [default]
Destructor.
Referenced by LoadDefaultTechnology().
Member Function Documentation
ComputeTechnologyRelationships()
const CustomUnorderedSet< TechnologyFlowStep_Type > LoadDefaultTechnology::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements TechnologyFlowStep.
Definition at line 73 of file load_default_technology.cpp.
Exec()
DesignFlowStep_Status LoadDefaultTechnology::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Load default resources
Implements DesignFlowStep.
Definition at line 78 of file load_default_technology.cpp.
References XMLDomParser::Exec(), XMLDomParser::get_document(), test_panda::parser, STR, SUCCESS, TechnologyFlowStep::target, THROW_ERROR, TechnologyFlowStep::TM, and technology_manager::xload().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_default_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/load_default_technology.cpp