SDCCodeMotion Class Reference
Superclass include.
#include <sdc_code_motion.hpp>
Public Member Functions
SDCCodeMotion (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~SDCCodeMotion () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Utility include Speculation code motion step
Definition at line 52 of file sdc_code_motion.hpp.
Constructor & Destructor Documentation
SDCCodeMotion()
SDCCodeMotion::SDCCodeMotion (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior includes design_flow includes frontend_flow include frontend_flow/IR_analysis include HLS includes HLS/scheduling include tree includes
Definition at line 79 of file sdc_code_motion.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~SDCCodeMotion().
 SDCCodeMotion()
SDCCodeMotion::~SDCCodeMotion () [override], [default]
Destructor.
Referenced by SDCCodeMotion().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > SDCCodeMotion::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 87 of file sdc_code_motion.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
ComputeRelationships()
void SDCCodeMotion::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 160 of file sdc_code_motion.cpp.
References FunctionFrontendFlowStep::ComputeRelationships().
HasToBeExecuted()
bool SDCCodeMotion::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 112 of file sdc_code_motion.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), and DesignFlowStep::parameters.
Initialize()
void SDCCodeMotion::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 118 of file sdc_code_motion.cpp.
InternalExec()
DesignFlowStep_Status SDCCodeMotion::InternalExec () [override], [virtual]
Performs the loops analysis.
Retrieve result of sdc scheduling
Implements FunctionFrontendFlowStep.
Definition at line 122 of file sdc_code_motion.cpp.
References FrontendFlowStep::AppM, tree_manager::CGetTreeNode(), HLSFunctionStep::ComputeSignature(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, Wrefcount< T >::lock(), sl, STR, SUCCESS, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/sdc_code_motion.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/sdc_code_motion.cpp