unique_binding Class Reference
Class managing the module allocation.
#include <unique_binding.hpp>
Public Member Functions
unique_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~unique_binding () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs module binding assigning each operation to a free resource.
Additional Inherited Members
Detailed Description
Class managing the module allocation.
Definition at line 50 of file unique_binding.hpp.
Constructor & Destructor Documentation
unique_binding()
unique_binding::unique_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
HLS/module_allocation include.
Parameters
design_flow_manager is the design flow manager
Definition at line 62 of file unique_binding.cpp.
References UNIQUE_MODULE_BINDING, and ~unique_binding().
 unique_binding()
unique_binding::~unique_binding () [override], [default]
Destructor.
Referenced by unique_binding().
Member Function Documentation
InternalExec()
DesignFlowStep_Status unique_binding::InternalExec () [override], [virtual]
Performs module binding assigning each operation to a free resource.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 69 of file unique_binding.cpp.
References hls::allocation_information, fu_binding::bind(), FunctionBehavior::CFG, FunctionBehavior::CGetOpGraph(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, HLSFunctionStep::funId, fu_binding::get_assign(), fu_binding::get_index(), GET_NAME, HLSFunctionStep::HLS, HLS_step::HLSMgr, INFINITE_UINT, insert(), AllocationInformation::is_memory_unit(), AllocationInformation::is_vertex_bounded(), Schedule::print(), hls::Rfu, hls::Rsch, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/unique_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/unique_binding.cpp