function_allocation Class Reference
Allocation function class.
#include <function_allocation.hpp>
Public Member Functions
function_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
~function_allocation () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Additional Inherited Members
Detailed Description
Allocation function class.
Definition at line 53 of file function_allocation.hpp.
Constructor & Destructor Documentation
function_allocation()
function_allocation::function_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
HLS/function_allocation include.
Definition at line 54 of file function_allocation.cpp.
References ~function_allocation().
 function_allocation()
function_allocation::~function_allocation () [override], [default]
Destructor.
Referenced by function_allocation().
Member Function Documentation
Initialize()
void function_allocation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Reimplemented in OmpFunctionAllocation, and OmpFunctionAllocationCS.
Definition at line 61 of file function_allocation.cpp.
References functions, HLS_step::HLSMgr, and DesignFlowStep::Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/function_allocation/function_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/function_allocation/function_allocation.cpp