XMLDomParser Class Reference
XML DOM parser.
#include <xml_dom_parser.hpp>
Public Member Functions
XMLDomParser (std::string name, std::string string_to_be_parsed)
Constructor from string.
XMLDomParser (const std::string &filename)
Constructor from file.
void Exec ()
Parse an XML document from a file.
operator bool () const
Test whether a document has been parsed.
xml_documentRef get_document ()
Obtain the parsed document.
const xml_documentRef get_document () const
Obtain the parsed document.
Protected Attributes
const std::string name
The name of the parsed file or of the string.
const std::string to_be_parsed
The string to be parsed or the name for the file to be parsed.
xml_documentRef doc
The data structure extracted from the file.
Detailed Description
XML DOM parser.
Definition at line 61 of file xml_dom_parser.hpp.
Constructor & Destructor Documentation
XMLDomParser() [1/2]
XMLDomParser::XMLDomParser (std::string _name, std::string string_to_be_parsed)
Constructor from string.
Header include.
Parameters
name is the name of the string
string_to_be_parsed is the string to be parsed
Utility include
Definition at line 50 of file xml_dom_parser.cpp.
XMLDomParser() [2/2]
XMLDomParser::XMLDomParser (const std::string & filename) [explicit]
Constructor from file.
Parameters
filename is the file to be parsed
Definition at line 55 of file xml_dom_parser.cpp.
Member Function Documentation
Exec()
void XMLDomParser::Exec ()
Parse an XML document from a file.
Parameters
filename The path to the file.
Referenced by HLS_constraints::add_builtin_constraints(), LoadDefaultTechnology::Exec(), LoadDeviceTechnology::Exec(), Translator::get_normalization(), Parameter::GetFileFormat(), HLS_constraints::HLS_constraints(), fixed_scheduling::InternalExec(), interface_infer::InternalExec(), IC_device::load_devices(), Parameter::load_xml_configuration_file(), DataXmlParser::Parse(), mem_xml_allocation::parse_xml_allocation(), TestVectorParser::ParseXMLFile(), HLS_constraints::read_HLS_constraints_File(), read_structural_File(), read_technology_File(), GccWrapper::ReadXml(), XilinxBackendFlow::vivado_xparse_utilization(), Translator::write_to_latex(), XilinxBackendFlow::xparse_timing(), LatticeBackendFlow::xparse_utilization(), AlteraBackendFlow::xparse_utilization(), NanoXploreBackendFlow::xparse_utilization(), and XilinxBackendFlow::xparse_xst_utilization().
get_document() [1/2]
xml_documentRef XMLDomParser::get_document ()
Obtain the parsed document.
Returns
the xml document pointer.
Definition at line 64 of file xml_dom_parser.cpp.
References doc.
Referenced by HLS_constraints::add_builtin_constraints(), LoadDefaultTechnology::Exec(), LoadDeviceTechnology::Exec(), Translator::get_normalization(), Parameter::GetFileFormat(), HLS_constraints::HLS_constraints(), fixed_scheduling::InternalExec(), interface_infer::InternalExec(), IC_device::load_devices(), Parameter::load_xml_configuration_file(), DataXmlParser::Parse(), mem_xml_allocation::parse_xml_allocation(), TestVectorParser::ParseXMLFile(), HLS_constraints::read_HLS_constraints_File(), read_structural_File(), read_technology_File(), GccWrapper::ReadXml(), XilinxBackendFlow::vivado_xparse_utilization(), Translator::write_to_latex(), XilinxBackendFlow::xparse_timing(), LatticeBackendFlow::xparse_utilization(), AlteraBackendFlow::xparse_utilization(), NanoXploreBackendFlow::xparse_utilization(), and XilinxBackendFlow::xparse_xst_utilization().
get_document() [2/2]
const xml_documentRef XMLDomParser::get_document () const
Obtain the parsed document.
Const version.
Returns
the xml document pointer.
Definition at line 69 of file xml_dom_parser.cpp.
References doc.
operator bool()
XMLDomParser::operator bool () const
Test whether a document has been parsed.
Definition at line 59 of file xml_dom_parser.cpp.
References doc.
Field Documentation
doc
xml_documentRef XMLDomParser::doc [protected]
The data structure extracted from the file.
Definition at line 71 of file xml_dom_parser.hpp.
Referenced by get_document(), and operator bool().
name
const std::string XMLDomParser::name [protected]
The name of the parsed file or of the string.
Definition at line 65 of file xml_dom_parser.hpp.
to_be_parsed
const std::string XMLDomParser::to_be_parsed [protected]
The string to be parsed or the name for the file to be parsed.
Definition at line 68 of file xml_dom_parser.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/polixml/xml_dom_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/polixml/xml_dom_parser.cpp