SymbolicApplicationFrontendFlowStep Class Reference
#include <symbolic_application_frontend_flow_step.hpp>
Public Member Functions
SymbolicApplicationFrontendFlowStep (const application_managerRef AppM, const FrontendFlowStepType frontend_flow_step_type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~SymbolicApplicationFrontendFlowStep () override
Destructor.
DesignFlowStep_Status Exec () override
Execute this step.
const std::string GetKindText () const override
Return the type of this step.
const std::string GetSignature () const override
Return the signature of this step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Static Public Member Functions
static const std::string ComputeSignature (const FrontendFlowStepType frontend_flow_step_type)
Compute the signature of a symbolic application frontend flow step.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const FrontendFlowStepType represented_frontend_flow_step_type
The analysis represented by this step.
Additional Inherited Members
Detailed Description
Definition at line 54 of file symbolic_application_frontend_flow_step.hpp.
Constructor & Destructor Documentation
SymbolicApplicationFrontendFlowStep()
SymbolicApplicationFrontendFlowStep::SymbolicApplicationFrontendFlowStep (const application_managerRef AppM, const FrontendFlowStepType frontend_flow_step_type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
frontend_flow_step_type is the type of the step
design_flow_manager is the design flow manager
_Param is the set of the parameters
Definition at line 56 of file symbolic_application_frontend_flow_step.cpp.
References DesignFlowStep::composed, DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~SymbolicApplicationFrontendFlowStep().
 SymbolicApplicationFrontendFlowStep()
SymbolicApplicationFrontendFlowStep::~SymbolicApplicationFrontendFlowStep () [override], [default]
Destructor.
Referenced by SymbolicApplicationFrontendFlowStep().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > SymbolicApplicationFrontendFlowStep::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 66 of file symbolic_application_frontend_flow_step.cpp.
References FrontendFlowStep::ALL_FUNCTIONS, COMPLETE_CALL_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, FUNCTION_ANALYSIS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, represented_frontend_flow_step_type, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
ComputeSignature()
const std::string SymbolicApplicationFrontendFlowStep::ComputeSignature (const FrontendFlowStepType frontend_flow_step_type) [static]
Compute the signature of a symbolic application frontend flow step.
Parameters
frontend_flow_step_type is the type of frontend flow
Returns
the corresponding signature
Definition at line 105 of file symbolic_application_frontend_flow_step.cpp.
References SYMBOLIC_APPLICATION_FRONTEND_FLOW_STEP.
Referenced by FunctionFrontendFlowStep::ComputeRelationships(), ApplicationFrontendFlowStep::ComputeSignature(), and GetSignature().
Exec()
DesignFlowStep_Status SymbolicApplicationFrontendFlowStep::Exec () [override], [virtual]
Execute this step.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 95 of file symbolic_application_frontend_flow_step.cpp.
References EMPTY.
GetKindText()
const std::string SymbolicApplicationFrontendFlowStep::GetKindText () const [override], [virtual]
Return the type of this step.
Reimplemented from FrontendFlowStep.
Definition at line 100 of file symbolic_application_frontend_flow_step.cpp.
References FrontendFlowStep::EnumToKindText(), and represented_frontend_flow_step_type.
GetSignature()
const std::string SymbolicApplicationFrontendFlowStep::GetSignature () const [override], [virtual]
Return the signature of this step.
Reimplemented from ApplicationFrontendFlowStep.
Definition at line 110 of file symbolic_application_frontend_flow_step.cpp.
References ComputeSignature(), and represented_frontend_flow_step_type.
HasToBeExecuted()
bool SymbolicApplicationFrontendFlowStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from ApplicationFrontendFlowStep.
Definition at line 115 of file symbolic_application_frontend_flow_step.cpp.
Field Documentation
represented_frontend_flow_step_type
const FrontendFlowStepType SymbolicApplicationFrontendFlowStep::represented_frontend_flow_step_type [private]
The analysis represented by this step.
Definition at line 58 of file symbolic_application_frontend_flow_step.hpp.
Referenced by ComputeFrontendRelationships(), GetKindText(), and GetSignature().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/symbolic_application_frontend_flow_step.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/symbolic_application_frontend_flow_step.cpp