FunctionBehavior Class Reference
#include <function_behavior.hpp>
Public Types
enum graph_type {
CFG,
ECFG,
FCFG,
CDG,
FCDG,
DFG,
FDFG,
ADG,
FADG,
ODG,
FODG,
FLG,
SDG,
FSDG,
SAODG,
FSAODG,
FLSAODG,
FLSAODDG,
FFLSAODG,
FLAODDG,
FFLAODDG,
SG,
AGG_VIRTUALG
 }
Declaration of enum representing the type of graph.
enum bb_graph_type {
BB,
FBB,
EBB,
CDG_BB,
DOM_TREE,
POST_DOM_TREE,
PPG,
DJ
 }
Declaration of enum representing the type of bb_graph.
Public Member Functions
FunctionBehavior (const application_managerConstRef AppM, const BehavioralHelperRef _helper, const ParameterConstRef parameters)
Constructor.
~FunctionBehavior ()
Destructor.
BehavioralHelperRef GetBehavioralHelper ()
Returns the helper associated with the function.
const BehavioralHelperConstRef CGetBehavioralHelper () const
Returns the helper associated with the function.
CustomOrderedSet< unsigned int > get_local_variables (const application_managerConstRef AppM) const
Returns the set of local variables.
const std::deque< vertex > & get_levels () const
Return the vector of vertex index sorted in topological order.
const std::deque< vertex > & get_bb_levels () const
Return the vector of bb vertex index sorted in topological order.
const std::map< vertex, unsigned int > & get_map_levels () const
Return the map of vertex index sorted in topological order.
const std::map< vertex, unsigned int > & get_bb_map_levels () const
Return the map of bb vertex index sorted in topological order.
OpGraphRef GetOpGraph (FunctionBehavior::graph_type gt)
This method returns the operation graphs.
const OpGraphConstRef CGetOpGraph (FunctionBehavior::graph_type gt) const
This method returns the operation graphs.
const OpGraphConstRef CGetOpGraph (FunctionBehavior::graph_type gt, const OpVertexSet &subset) const
This method returns the operation graph having as vertices the vertices of subset.
BBGraphRef GetBBGraph (FunctionBehavior::bb_graph_type gt=FunctionBehavior::BB)
This method returns the basic block graphs.
const BBGraphConstRef CGetBBGraph (FunctionBehavior::bb_graph_type gt=FunctionBehavior::BB) const
This method returns the basic block graphs.
void print (std::ostream &os) const
Function that prints the class behavioral_manager.
void set_epp (EdgeDescriptor e, unsigned long long value)
Set epp associated with an edges.
const LoopsConstRef CGetLoops () const
Return the loops.
const LoopsRef GetLoops () const
Return the loops.
void add_parm_decl_copied (unsigned int node_id)
Adds an identifier to the set of memory variables.
void add_parm_decl_loaded (unsigned int node_id)
add an actual parameter that has to be loaded into the formal parameter
void add_parm_decl_stored (unsigned int node_id)
add a formal parameter that has to be initialized from the actual value
void add_function_mem (unsigned int node_id)
Adds a memory variable to the function.
void add_dynamic_address (unsigned int node_id)
Add the node_id to the set of object for which a dynamic address computation could be used.
void erase_dynamic_address (unsigned int node_id)
remove a variable from the dynamic address set
void erase_all_dynamic_addresses ()
remove all variables from the dynamic address set
bool is_variable_mem (unsigned int node_id) const
Checks if a variable has been allocated in memory.
const CustomOrderedSet< unsigned int > & get_function_mem () const
Returns the set of memory variables.
const CustomOrderedSet< unsigned int > & get_dynamic_address () const
Returns the set of variables for which a dynamic address computation maybe required.
const CustomOrderedSet< unsigned int > & get_parm_decl_copied () const
Returns the set of parameters to be copied.
const CustomOrderedSet< unsigned int > & get_parm_decl_loaded () const
Returns the set of the actual parameters that has to be loaded into the formal parameter.
const CustomOrderedSet< unsigned int > & get_parm_decl_stored () const
Returns the set of the formal parameters that has to be stored into the formal parameter.
void set_dereference_unknown_addr (bool f)
Set the use of dereferences of unknown address.
bool get_dereference_unknown_addr () const
Return true if the function has dereferences of unknown address.
void set_pointer_type_conversion (bool f)
Set if a pointer conversion happen.
bool get_pointer_type_conversion () const
Return true if a pointer conversion happen.
void set_unaligned_accesses (bool f)
Set if LOADs or STOREs perform unaligned accesses.
bool get_unaligned_accesses () const
Return true if a LOADs or STOREs perform unaligned accesses.
void set_has_globals (bool f)
set if there are or not externally visible global variables
bool get_has_globals () const
helper for global variables property
void set_has_undefined_function_receiveing_pointers (bool f)
set if there are or not undefined functions called and which has pointers passed
bool get_has_undefined_function_receiving_pointers () const
helper for has_undefined_function_receiveing_pointers variables property
void add_state_variable (unsigned int node_id)
Add a state variable: static, global or volatile variable.
bool is_a_state_variable (unsigned int node_id) const
return true if a variable is a state variable or not
void set_packed_vars (bool packed)
update the the packed variables status
bool has_packed_vars () const
bool is_pipelining_enabled () const
void set_pipelining_enabled (bool f)
bool CheckReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from first_operation to second_operation exists in control flow graph (without feedback)
bool CheckBBReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from the first basic block to the second basic block exists in control flow graph (without feedback)
bool CheckFeedbackReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from first_operation to second_operation exists in control flow graph with feedback.
bool CheckBBFeedbackReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from the first basic block to the second basic block exists in control flow graph with feedback.
unsigned int GetBBVersion () const
Return the version of the basic block intermediate representation.
unsigned int UpdateBBVersion ()
Update the version of the basic block intermediate representation.
unsigned int GetBitValueVersion () const
Return the version of the bitvalue information.
unsigned int UpdateBitValueVersion ()
Update the version of the bitvalue information.
Data Fields
CustomUnorderedMapStable< vertex, CustomUnorderedSet< vertex > > bb_reachability
Mutual exclusion between basic blocks (based on control flow graph with flow edges)
CustomUnorderedMapStable< vertex, CustomUnorderedSet< vertex > > feedback_bb_reachability
Reachability between basic blocks based on control flow graph with feedback.
const operations_graph_constructorRef ogc
reference to the operations graph constructor
const BasicBlocksGraphConstructorRef bbgc
reference to the basic block graph constructor
const level_constructorRef lm
reference to the level constructor
const level_constructorRef bb_lm
reference to the level constructor
dominance< BBGraph > * dominators
This class stores dominator information.
dominance< BBGraph > * post_dominators
This class stores post-dominator information.
std::map< unsigned int, memory_accessRef > memory_info
map between node id and the corresponding memory allocation
bool packed_vars
True when there access to packed data.
Private Attributes
const BehavioralHelperRef helper
Behavioral helper associated with this behavioral_graph_manager.
const BBGraphsCollectionRef bb_graphs_collection
Global graph storing CFG, dominators and post-dominators. The nodes of this graph are basic blocks.
const OpGraphsCollectionRef op_graphs_collection
Global graph storing CFG, DFG, FCFG, FDFG, SDG, FSDG, CDG. The nodes of this graph are operations.
const BBGraphRef bb
The basic block CFG.
const BBGraphRef extended_bb
The basic block Control Flow Graph extended with edges that impose that basic block inside a loop are executed before what follows the loop.
const BBGraphRef cdg_bb
The control dependence graph among basic blocks.
const BBGraphRef dj
The dj graph (used for loop computation)
const BBGraphRef dt
The dominator tree of the CFG on basic blocks.
const BBGraphRef fbb
The basic block CFG with feedback.
const BBGraphRef pdt
The post-dominator tree of the CFG on basic blocks.
const BBGraphRef ppg
The support basic block graph for path profiling.
const OpGraphRef cfg
The control flow graph.
const OpGraphRef extended_cfg
The extended control flow graph.
const OpGraphRef fcfg
The control flow graph with feedback.
const OpGraphRef adg
The anti-dependencies graph.
const OpGraphRef fadg
The anti-dependencies graph with feedback.
const OpGraphRef cdg
The control dependence graph.
const OpGraphRef fcdg
The control dependence graph with feedback.
const OpGraphRef dfg
The data flow graph.
const OpGraphRef fdfg
The data flow graph with feedback.
const OpGraphRef flg
The flow edge operation graph.
const OpGraphRef odg
The output-dependencies flow graph.
const OpGraphRef fodg
The output-dependencies flow graph with feedback.
const OpGraphRef flaoddg
The anti-dependence + data dependence + output dependence + flow graph.
const OpGraphRef fflaoddg
The anti-dependence + data dependence + output dependence + flow graph with freedback.
const OpGraphRef flsaodg
The system dependence, antidependence, output dependence and flow graph.
const OpGraphRef flsaoddg
The system dependence, antidependence, output dependence, flow and debug graph.
const OpGraphRef fflsaodg
The system dependence, antidependence, output dependence and flow graph with feedback;.
const OpGraphRef saodg
The system dependence, antidependence and output dependence graph.
const OpGraphRef fsaodg
The system dependence, antidependence and output dependence graph with feedback.
const OpGraphRef sdg
The system dependence graph.
const OpGraphRef fsdg
The system dependence graph with feedback.
const OpGraphRef sg
The speculation graph.
const OpGraphRef agg_virtualg
Anti + Data flow graph on aggregates.
std::map< vertex, unsigned int > map_levels
Map operation vertex to position in topological order in control flow graph; in the sorting then part vertices come before else part ones.
std::map< vertex, unsigned int > bb_map_levels
Map basic block vertex to position in topological order in control flow graph; in the sorting then part vertices come before else part ones.
std::deque< vertex > deque_levels
list of operations vertices sorted by topological order in control flow graph; in the sorting then part vertices come before else part ones
std::deque< vertex > bb_deque_levels
list of operations vertices sorted by topological order in control flow graph; in the sorting then part vertices come before else part ones
LoopsRef loops
Loops of the function.
CustomOrderedSet< unsigned int > mem_nodeID
this set represents the memory variables accessed by the function
CustomOrderedSet< unsigned int > dynamic_address
store memory objects which can be indirectly addressed through a dynamic address computation
CustomOrderedSet< unsigned int > parm_decl_copied
this set represents the parameters that have to be copied from the caller
CustomOrderedSet< unsigned int > parm_decl_loaded
this set represents the actual parameters that has to be loaded into the formal parameter from the actual parameter
CustomOrderedSet< unsigned int > parm_decl_stored
this set represents the formal parameters that has to be stored into the formal parameter from the actual parameter
const ParameterConstRef parameters
The set of input parameters.
bool dereference_unknown_address
the function dereference a pointer initialized with constant address.
bool pointer_type_conversion
true when at least one pointer conversion happen
bool unaligned_accesses
unsigned int bb_version
The version of basic block intermediate representation.
unsigned int bitvalue_version
Version of the bitvalue information.
bool has_globals
when true at least one global variable is used
bool has_undefined_function_receiveing_pointers
function calls undefined function passing pointers
CustomOrderedSet< unsigned int > state_variables
set of global variables
bool pipelining_enabled
when true pipelining has been requested for this function
Friends
std::ostream & operator<< (std::ostream &os, const FunctionBehavior &s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const FunctionBehaviorRef &s)
Friend definition of the << operator.
 some friend classes
class BasicBlocksProfiling
class BBCdgComputation
class OpCdgComputation
class hpp_profiling
class loops_computation
class instr_sequences_detection
struct loop_regions_computation
class LoopsAnalysisZebu
class LoopsProfiling
class probability_path
class HostProfiling
class read_profiling_data
class tp_profiling
class BBOrderComputation
class OpOrderComputation
class BasicBlocksCfgComputation
Detailed Description
Definition at line 184 of file function_behavior.hpp.
Member Enumeration Documentation
bb_graph_type
enum FunctionBehavior::bb_graph_type
Declaration of enum representing the type of bb_graph.
Enumerator
BB Basic block control flow graph.
FBB Basic block control flow graph with feedback.
EBB Basic block control flow graph with edges imposing that basic block inside a loop are executed before what follows the loop.
CDG_BB Basic block control dependence graph.
DOM_TREE Basic block dominator tree.
POST_DOM_TREE Basic block post-dominator tree.
PPG Support basic block for path profiling.
DJ DJ basic block graph (used for loop computation)
Definition at line 469 of file function_behavior.hpp.
graph_type
enum FunctionBehavior::graph_type
Declaration of enum representing the type of graph.
Enumerator
CFG Control flow graph.
ECFG Extended control flow graph.
FCFG Control flow graph with feedback.
CDG Control dependence graph.
FCDG Control dependence graph with feedback.
DFG Data flow graph.
FDFG Data flow graph with feedback.
ADG Anti-dependence graph.
FADG Anti-dependence graph with feedback.
ODG Output dependence graph.
FODG Output dependence graph with feedback.
FLG Flow edges graph.
SDG System dependence graph.
FSDG System dependence graph with feedback.
SAODG System dependence + anti-dependence graph + output dependence graph.
FSAODG System dependence + anti-dependence graph + output dependence graph with feedback.
FLSAODG System dependence + anti-dependence + output dependence graph + flow graph.
FLSAODDG System dependence + anti-dependence + output dependence graph + flow graph + debug graph.
FFLSAODG System dependence + anti-dependence + output dependence graph + flow graph with feedback.
FLAODDG Anti-dependence + data dependence + output dependence + flow graph.
FFLAODDG Anti dependence + data dependence + output dependence + flow graph with feedback.
SG Speculation graph.
AGG_VIRTUALG Anti + Data flow graph dependence between aggregates.
Definition at line 434 of file function_behavior.hpp.
Constructor & Destructor Documentation
FunctionBehavior()
FunctionBehavior::FunctionBehavior (const application_managerConstRef AppM, const BehavioralHelperRef _helper, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
_helper is the helper associated with the function
parameters is the set of input paramters
Definition at line 99 of file function_behavior.cpp.
 FunctionBehavior()
FunctionBehavior::~FunctionBehavior ()
Destructor.
Definition at line 192 of file function_behavior.cpp.
References dominators, and post_dominators.
Member Function Documentation
add_dynamic_address()
void FunctionBehavior::add_dynamic_address (unsigned int node_id)
Add the node_id to the set of object for which a dynamic address computation could be used.
Parameters
node_id is the object stored in memory
the object may be written once you have the address
Definition at line 569 of file function_behavior.cpp.
References dynamic_address.
add_function_mem()
void FunctionBehavior::add_function_mem (unsigned int node_id)
Adds a memory variable to the function.
Definition at line 564 of file function_behavior.cpp.
References mem_nodeID.
add_parm_decl_copied()
void FunctionBehavior::add_parm_decl_copied (unsigned int node_id)
Adds an identifier to the set of memory variables.
Definition at line 591 of file function_behavior.cpp.
References dynamic_address, and parm_decl_copied.
add_parm_decl_loaded()
void FunctionBehavior::add_parm_decl_loaded (unsigned int node_id)
add an actual parameter that has to be loaded into the formal parameter
Definition at line 597 of file function_behavior.cpp.
References dynamic_address, and parm_decl_loaded.
add_parm_decl_stored()
void FunctionBehavior::add_parm_decl_stored (unsigned int node_id)
add a formal parameter that has to be initialized from the actual value
Definition at line 603 of file function_behavior.cpp.
References dynamic_address, and parm_decl_stored.
add_state_variable()
void FunctionBehavior::add_state_variable (unsigned int node_id) [inline]
Add a state variable: static, global or volatile variable.
Definition at line 818 of file function_behavior.hpp.
CGetBBGraph()
const BBGraphConstRef FunctionBehavior::CGetBBGraph (FunctionBehavior::bb_graph_type gt = FunctionBehavior::BB) const
This method returns the basic block graphs.
Parameters
gt is the type of the bb_graph to be returned
Returns
the pointer to the bb_graph.
Definition at line 489 of file function_behavior.cpp.
References bb, BB, cdg_bb, CDG_BB, dj, DJ, DOM_TREE, dt, EBB, extended_bb, fbb, FBB, pdt, POST_DOM_TREE, ppg, PPG, and THROW_UNREACHABLE.
Referenced by liveness::are_in_conflict(), pragma_manager::CheckAddOmpFor(), CWriter::compute_phi_nodes(), SDCScheduling::Initialize(), FSM_NI_SSA_liveness::InternalExec(), SDCScheduling::InternalExec(), parametric_list_based::InternalExec(), EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), and EdgeCWriter::writeRoutineInstructions_rec().
CGetBehavioralHelper()
const BehavioralHelperConstRef FunctionBehavior::CGetBehavioralHelper () const
Returns the helper associated with the function.
Definition at line 329 of file function_behavior.cpp.
References helper.
Referenced by ControllerCreatorBaseStep::add_command_ports(), conn_binding_creator::add_parameter_ports(), top_entity::add_ports(), classic_datapath::add_ports(), fu_binding::add_to_SM(), TopEntityMemoryMapped::allocate_parameters(), memory_allocation::allocate_parameters(), Schedule::CanBeMoved(), CWriter::compute_phi_nodes(), top_entity_parallel_cs::connect_loop_iter(), datapath_parallel_cs::connect_module_kernel(), mux_connection_binding::create_connections(), VcdSignalSelection::CrossPropagateAddrSsa(), CWriter::declare_cast_types(), discrepancy_instruction_writer::declareFunction(), CWriter::DeclareFunctionTypes(), mux_connection_binding::determine_connection(), GenerateSynthesisScripts::Exec(), fun_dominator_allocation::Exec(), Evaluation::Exec(), memory_allocation::finalize_memory_allocation(), TopEntityMemoryMapped::forwardPorts(), WB4_interface::get_data_bus_bitsize(), moduleGenerator::getDataType(), SDCScheduling::Initialize(), Bit_Value::initialize(), TopEntityMemoryMapped::insertMemoryMappedRegister(), allocation::IntegrateTechnologyLibraries(), mem_cg_ext::InternalExec(), FSM_NI_SSA_liveness::InternalExec(), fsm_controller::InternalExec(), minimal_interface::InternalExec(), mem_dominator_allocation::InternalExec(), easy_module_binding::InternalExec(), TasteInterfaceGeneration::InternalExec(), top_entity_parallel_cs::InternalExec(), classic_datapath::InternalExec(), TopEntityMemoryMapped::InternalExec(), ControlFlowChecker::InternalExec(), weighted_clique_register::InternalExec(), top_entity::InternalExec(), add_library::InternalExec(), datapath_parallel_cs::InternalExec(), port_swapping::InternalExec(), SDCScheduling::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), VcdSignalSelection::PropagateAddrParamToSsa(), VcdSignalSelection::SelectAddrSsa(), VcdSignalSelection::SelectInitialSsa(), VcdSignalSelection::SelectInternalSignals(), moduleGenerator::specialize_fu(), InstructionWriter::write(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), CWriter::WriteFunctionBody(), DiscrepancyAnalysisCWriter::WriteFunctionDeclaration(), CWriter::WriteFunctionDeclaration(), DiscrepancyAnalysisCWriter::WriteFunctionImplementation(), CBackend::writeIncludes(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
CGetLoops()
const LoopsConstRef FunctionBehavior::CGetLoops () const
Return the loops.
Definition at line 547 of file function_behavior.cpp.
References loops.
Referenced by liveness::are_in_conflict(), top_entity_parallel_cs::BW_loop_iter(), top_entity_parallel_cs::connect_loop_iter(), EdgeCWriter::Initialize(), SDCScheduling::InternalExec(), EdgeCWriter::writeRoutineInstructions_rec(), and CWriter::writeRoutineInstructions_rec().
CGetOpGraph() [1/2]
const OpGraphConstRef FunctionBehavior::CGetOpGraph (FunctionBehavior::graph_type gt) const
This method returns the operation graphs.
Parameters
gt is the type of the graph to be returned
Returns
the pointer to the graph.
Definition at line 262 of file function_behavior.cpp.
References adg, ADG, agg_virtualg, AGG_VIRTUALG, cdg, CDG, cfg, CFG, dfg, DFG, ECFG, extended_cfg, fadg, FADG, fcdg, FCDG, fcfg, FCFG, fdfg, FDFG, fflaoddg, FFLAODDG, fflsaodg, FFLSAODG, flaoddg, FLAODDG, flg, FLG, flsaoddg, FLSAODDG, flsaodg, FLSAODG, fodg, FODG, fsaodg, FSAODG, fsdg, FSDG, odg, ODG, saodg, SAODG, sdg, SDG, sg, SG, and THROW_UNREACHABLE.
Referenced by conn_binding::add_command_ports(), fu_binding::add_gate(), liveness::are_in_conflict(), CWriter::compute_phi_nodes(), mux_connection_binding::create_connections(), fsm_controller::create_state_machine(), VcdSignalSelection::CrossPropagateAddrSsa(), CWriter::declare_cast_types(), CWriter::DeclareLocalVariables(), VcdSignalSelection::DetectInvalidReturns(), memory_allocation::finalize_memory_allocation(), application_manager::get_produced_value(), HLS_manager::get_required_values(), StorageValueInformation::Initialize(), SDCScheduling::Initialize(), Scheduling::Initialize(), Schedule::Initialize(), parametric_list_based::Initialize(), cdfc_module_binding::initialize_connection_relation(), OmpAllocation::IntegrateTechnologyLibraries(), unique_binding::InternalExec(), FSM_NI_SSA_liveness::InternalExec(), sched_based_chaining_computation::InternalExec(), mem_dominator_allocation::InternalExec(), easy_module_binding::InternalExec(), port_swapping::InternalExec(), SDCScheduling::InternalExec(), allocation::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), VcdSignalSelection::PropagateAddrParamToSsa(), VcdSignalSelection::SelectInitialSsa(), VcdSignalSelection::SelectInternalSignals(), fu_binding::specialise_fu(), moduleGenerator::specialize_fu(), InstructionWriter::write(), CWriter::WriteFunctionBody(), CBackend::writeIncludes(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), DiscrepancyAnalysisCWriter::writePreInstructionInfo(), EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), and EdgeCWriter::writeRoutineInstructions_rec().
CGetOpGraph() [2/2]
const OpGraphConstRef FunctionBehavior::CGetOpGraph (FunctionBehavior::graph_type gt, const OpVertexSet & subset) const
This method returns the operation graph having as vertices the vertices of subset.
optimization in case the subset is equal to the whole set of vertices is possible
Parameters
gt is the type of the graph to be returned
subset is the set of subgraph vertices
Returns
the refcount to the subgraph
This `transformation` is necessary because of graph constructor
Definition at line 335 of file function_behavior.cpp.
References ADG, ADG_AGG_SELECTOR, ADG_SELECTOR, AGG_VIRTUALG, CDG, CDG_SELECTOR, CFG, CFG_SELECTOR, DEBUG_SELECTOR, DFG, DFG_AGG_SELECTOR, DFG_SELECTOR, ECFG, ECFG_SELECTOR, FADG, FADG_SELECTOR, FB_ADG_SELECTOR, FCDG, FCDG_SELECTOR, FCFG, FCFG_SELECTOR, FDFG, FDFG_SELECTOR, FFLAODDG, FFLSAODG, FLAODDG, FLG, FLG_SELECTOR, FLSAODDG, FLSAODG, FODG, FODG_SELECTOR, FSAODG, FSDG, FSDG_SELECTOR, ODG, ODG_SELECTOR, op_graphs_collection, RPDG_SELECTOR, SAODG, SAODG_SELECTOR, SDG, SDG_SELECTOR, SG, SG_SELECTOR, THROW_UNREACHABLE, and test_panda::type.
CheckBBFeedbackReachability()
bool FunctionBehavior::CheckBBFeedbackReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from the first basic block to the second basic block exists in control flow graph with feedback.
Parameters
first_basic_block is the first basic block to be considered
second_basic_block is the second operation to be considered
Returns
true if there is a path from first_basic_block to second_basic_block in flcfg
Definition at line 681 of file function_behavior.cpp.
References CheckBBReachability(), and feedback_bb_reachability.
Referenced by CheckFeedbackReachability().
CheckBBReachability()
bool FunctionBehavior::CheckBBReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from the first basic block to the second basic block exists in control flow graph (without feedback)
Parameters
first_basic_block is the first basic block to be considered
second_basic_block is the second operation to be considered
Returns
true if there is a path from first_basic_block to second_basic_block in flcfg
Definition at line 669 of file function_behavior.cpp.
References bb_reachability.
Referenced by CheckBBFeedbackReachability(), and CheckReachability().
CheckFeedbackReachability()
bool FunctionBehavior::CheckFeedbackReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from first_operation to second_operation exists in control flow graph with feedback.
Parameters
first_operation is the first operation to be considered
second_operation is the second operation to be considered
Returns
true if there is a path from first_operation to second_operation in fcfg
Definition at line 721 of file function_behavior.cpp.
References bb, cfg, and CheckBBFeedbackReachability().
CheckReachability()
bool FunctionBehavior::CheckReachability (const vertex first_operation, const vertex second_operation) const
Check if a path from first_operation to second_operation exists in control flow graph (without feedback)
Parameters
first_operation is the first operation to be considered
second_operation is the second operation to be considered
Returns
true if there is a path from first_operation to second_operation in flcfg
Definition at line 697 of file function_behavior.cpp.
References bb, cfg, CheckBBReachability(), GET_NAME, map_levels, and THROW_ASSERT.
Referenced by liveness::are_in_conflict(), and SDCScheduling::InternalExec().
erase_all_dynamic_addresses()
void FunctionBehavior::erase_all_dynamic_addresses ()
remove all variables from the dynamic address set
Definition at line 581 of file function_behavior.cpp.
References dynamic_address.
erase_dynamic_address()
void FunctionBehavior::erase_dynamic_address (unsigned int node_id)
remove a variable from the dynamic address set
Parameters
node_id is the object stored in memory
Definition at line 576 of file function_behavior.cpp.
References dynamic_address.
get_bb_levels()
const std::deque< vertex > & FunctionBehavior::get_bb_levels () const
Return the vector of bb vertex index sorted in topological order.
Definition at line 527 of file function_behavior.cpp.
References bb_deque_levels.
get_bb_map_levels()
const std::map< vertex, unsigned int > & FunctionBehavior::get_bb_map_levels () const
Return the map of bb vertex index sorted in topological order.
Definition at line 537 of file function_behavior.cpp.
References bb_map_levels.
Referenced by SDCScheduling::InternalExec().
get_dereference_unknown_addr()
bool FunctionBehavior::get_dereference_unknown_addr () const [inline]
Return true if the function has dereferences of unknown address.
Definition at line 742 of file function_behavior.hpp.
Referenced by memory_allocation::finalize_memory_allocation().
get_dynamic_address()
const CustomOrderedSet< unsigned int > & FunctionBehavior::get_dynamic_address () const
Returns the set of variables for which a dynamic address computation maybe required.
Definition at line 614 of file function_behavior.cpp.
References dynamic_address.
Referenced by mem_dominator_allocation::InternalExec().
get_function_mem()
const CustomOrderedSet< unsigned int > & FunctionBehavior::get_function_mem () const
Returns the set of memory variables.
Definition at line 609 of file function_behavior.cpp.
References mem_nodeID.
Referenced by mem_dominator_allocation::InternalExec().
get_has_globals()
bool FunctionBehavior::get_has_globals () const [inline]
helper for global variables property
Returns
true in case there exist at least one externally visible global variable
Definition at line 792 of file function_behavior.hpp.
Referenced by memory_allocation::finalize_memory_allocation().
get_has_undefined_function_receiving_pointers()
bool FunctionBehavior::get_has_undefined_function_receiving_pointers () const [inline]
helper for has_undefined_function_receiveing_pointers variables property
Returns
true in case there are undefined function which receives pointers as a parameter
Definition at line 810 of file function_behavior.hpp.
Referenced by mem_dominator_allocation::InternalExec().
get_levels()
const std::deque< vertex > & FunctionBehavior::get_levels () const
Return the vector of vertex index sorted in topological order.
Definition at line 522 of file function_behavior.cpp.
References deque_levels.
get_local_variables()
CustomOrderedSet< unsigned int > FunctionBehavior::get_local_variables (const application_managerConstRef AppM) const
Returns the set of local variables.
Definition at line 634 of file function_behavior.cpp.
References cfg, and helper.
get_map_levels()
const std::map< vertex, unsigned int > & FunctionBehavior::get_map_levels () const
Return the map of vertex index sorted in topological order.
Definition at line 532 of file function_behavior.cpp.
References map_levels.
get_parm_decl_copied()
const CustomOrderedSet< unsigned int > & FunctionBehavior::get_parm_decl_copied () const
Returns the set of parameters to be copied.
Definition at line 619 of file function_behavior.cpp.
References parm_decl_copied.
Referenced by memory_allocation::setup_memory_allocation().
get_parm_decl_loaded()
const CustomOrderedSet< unsigned int > & FunctionBehavior::get_parm_decl_loaded () const
Returns the set of the actual parameters that has to be loaded into the formal parameter.
Definition at line 624 of file function_behavior.cpp.
References parm_decl_loaded.
Referenced by memory_allocation::setup_memory_allocation().
get_parm_decl_stored()
const CustomOrderedSet< unsigned int > & FunctionBehavior::get_parm_decl_stored () const
Returns the set of the formal parameters that has to be stored into the formal parameter.
Definition at line 629 of file function_behavior.cpp.
References parm_decl_stored.
Referenced by memory_allocation::finalize_memory_allocation(), and memory_allocation::setup_memory_allocation().
get_pointer_type_conversion()
bool FunctionBehavior::get_pointer_type_conversion () const [inline]
Return true if a pointer conversion happen.
Definition at line 758 of file function_behavior.hpp.
Referenced by memory_allocation::finalize_memory_allocation().
get_unaligned_accesses()
bool FunctionBehavior::get_unaligned_accesses () const [inline]
Return true if a LOADs or STOREs perform unaligned accesses.
Definition at line 774 of file function_behavior.hpp.
Referenced by memory_allocation::finalize_memory_allocation().
GetBBGraph()
BBGraphRef FunctionBehavior::GetBBGraph (FunctionBehavior::bb_graph_type gt = FunctionBehavior::BB)
This method returns the basic block graphs.
Parameters
gt is the type of the bb_graph to be returned
Returns
the pointer to the bb_graph.
Definition at line 463 of file function_behavior.cpp.
References bb, BB, cdg_bb, CDG_BB, dj, DJ, DOM_TREE, dt, EBB, extended_bb, fbb, FBB, pdt, POST_DOM_TREE, ppg, PPG, and THROW_UNREACHABLE.
GetBBVersion()
unsigned int FunctionBehavior::GetBBVersion () const
Return the version of the basic block intermediate representation.
Returns
bb_version
Definition at line 731 of file function_behavior.cpp.
References bb_version.
Referenced by BitValueIPA::Exec(), memory_allocation::Exec(), BitValueIPA::HasToBeExecuted(), memory_allocation::HasToBeExecuted(), allocation::HasToBeExecuted(), and allocation::InternalExec().
GetBehavioralHelper()
BehavioralHelperRef FunctionBehavior::GetBehavioralHelper ()
Returns the helper associated with the function.
Definition at line 324 of file function_behavior.cpp.
References helper.
GetBitValueVersion()
unsigned int FunctionBehavior::GetBitValueVersion () const
Return the version of the bitvalue information.
Returns
bitvalue_version
Definition at line 742 of file function_behavior.cpp.
References bitvalue_version.
Referenced by BitValueIPA::Exec(), memory_allocation::Exec(), and BitValueIPA::HasToBeExecuted().
GetLoops()
const LoopsRef FunctionBehavior::GetLoops () const
Return the loops.
Definition at line 552 of file function_behavior.cpp.
References loops.
GetOpGraph()
OpGraphRef FunctionBehavior::GetOpGraph (FunctionBehavior::graph_type gt)
This method returns the operation graphs.
Parameters
gt is the type of the graph to be returned
Returns
the pointer to the graph.
Definition at line 200 of file function_behavior.cpp.
References adg, ADG, agg_virtualg, AGG_VIRTUALG, cdg, CDG, cfg, CFG, dfg, DFG, ECFG, extended_cfg, fadg, FADG, fcdg, FCDG, fcfg, FCFG, fdfg, FDFG, fflaoddg, FFLAODDG, fflsaodg, FFLSAODG, flaoddg, FLAODDG, flg, FLG, flsaoddg, FLSAODDG, flsaodg, FLSAODG, fodg, FODG, fsaodg, FSAODG, fsdg, FSDG, odg, ODG, saodg, SAODG, sdg, SDG, sg, SG, and THROW_UNREACHABLE.
has_packed_vars()
bool FunctionBehavior::has_packed_vars () const [inline]
Returns
true in case packed vars are used
Definition at line 844 of file function_behavior.hpp.
Referenced by memory_allocation::finalize_memory_allocation().
is_a_state_variable()
bool FunctionBehavior::is_a_state_variable (unsigned int node_id) const [inline]
return true if a variable is a state variable or not
Parameters
node_id is the node id of the variable
Definition at line 827 of file function_behavior.hpp.
Referenced by mem_dominator_allocation::InternalExec().
is_pipelining_enabled()
bool FunctionBehavior::is_pipelining_enabled () const [inline]
Definition at line 848 of file function_behavior.hpp.
is_variable_mem()
bool FunctionBehavior::is_variable_mem (unsigned int node_id) const
Checks if a variable has been allocated in memory.
Definition at line 586 of file function_behavior.cpp.
References mem_nodeID.
Referenced by DiscrepancyAnalysisCWriter::DeclareLocalVariables(), mux_connection_binding::determine_connection(), memory_allocation::finalize_memory_allocation(), mem_dominator_allocation::InternalExec(), and fu_binding::specialise_fu().
print()
void FunctionBehavior::print (std::ostream & os) const
Function that prints the class behavioral_manager.
Definition at line 515 of file function_behavior.cpp.
References helper.
set_dereference_unknown_addr()
void FunctionBehavior::set_dereference_unknown_addr (bool f) [inline]
Set the use of dereferences of unknown address.
Definition at line 734 of file function_behavior.hpp.
set_epp()
void FunctionBehavior::set_epp (EdgeDescriptor e, unsigned long long value)
Set epp associated with an edges.
Parameters
e is the edges
value is the value
Definition at line 542 of file function_behavior.cpp.
References ppg.
set_has_globals()
void FunctionBehavior::set_has_globals (bool f) [inline]
set if there are or not externally visible global variables
Parameters
f boolean value specifying if there exist at least one externally visible global variable
Definition at line 783 of file function_behavior.hpp.
set_has_undefined_function_receiveing_pointers()
void FunctionBehavior::set_has_undefined_function_receiveing_pointers (bool f) [inline]
set if there are or not undefined functions called and which has pointers passed
Parameters
f boolean value specifying if there are such functions
Definition at line 801 of file function_behavior.hpp.
set_packed_vars()
void FunctionBehavior::set_packed_vars (bool packed) [inline]
update the the packed variables status
Parameters
packed is true when there is at least one packed variables
Definition at line 836 of file function_behavior.hpp.
set_pipelining_enabled()
void FunctionBehavior::set_pipelining_enabled (bool f) [inline]
Definition at line 853 of file function_behavior.hpp.
set_pointer_type_conversion()
void FunctionBehavior::set_pointer_type_conversion (bool f) [inline]
Set if a pointer conversion happen.
Definition at line 750 of file function_behavior.hpp.
set_unaligned_accesses()
void FunctionBehavior::set_unaligned_accesses (bool f) [inline]
Set if LOADs or STOREs perform unaligned accesses.
Definition at line 766 of file function_behavior.hpp.
UpdateBBVersion()
unsigned int FunctionBehavior::UpdateBBVersion ()
Update the version of the basic block intermediate representation.
Returns
the new version
Definition at line 736 of file function_behavior.cpp.
References bb_version.
UpdateBitValueVersion()
unsigned int FunctionBehavior::UpdateBitValueVersion ()
Update the version of the bitvalue information.
Returns
the new version
Definition at line 747 of file function_behavior.cpp.
References bitvalue_version.
Friends And Related Function Documentation
BasicBlocksCfgComputation
friend class BasicBlocksCfgComputation [friend]
Definition at line 206 of file function_behavior.hpp.
BasicBlocksProfiling
friend class BasicBlocksProfiling [friend]
Definition at line 191 of file function_behavior.hpp.
BBCdgComputation
friend class BBCdgComputation [friend]
Definition at line 192 of file function_behavior.hpp.
BBOrderComputation
friend class BBOrderComputation [friend]
Definition at line 204 of file function_behavior.hpp.
HostProfiling
friend class HostProfiling [friend]
Definition at line 201 of file function_behavior.hpp.
hpp_profiling
friend class hpp_profiling [friend]
Definition at line 194 of file function_behavior.hpp.
instr_sequences_detection
friend class instr_sequences_detection [friend]
Definition at line 196 of file function_behavior.hpp.
loop_regions_computation
friend struct loop_regions_computation [friend]
Definition at line 197 of file function_behavior.hpp.
loops_computation
friend class loops_computation [friend]
Definition at line 195 of file function_behavior.hpp.
LoopsAnalysisZebu
friend class LoopsAnalysisZebu [friend]
Definition at line 198 of file function_behavior.hpp.
LoopsProfiling
friend class LoopsProfiling [friend]
Definition at line 199 of file function_behavior.hpp.
OpCdgComputation
friend class OpCdgComputation [friend]
Definition at line 193 of file function_behavior.hpp.
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, const FunctionBehavior & s) [friend]
Friend definition of the << operator.
Parameters
os is the output stream
Definition at line 629 of file function_behavior.hpp.
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const FunctionBehaviorRef & s) [friend]
Friend definition of the << operator.
Pointer version.
Parameters
os is the output stream
Definition at line 639 of file function_behavior.hpp.
OpOrderComputation
friend class OpOrderComputation [friend]
Definition at line 205 of file function_behavior.hpp.
probability_path
friend class probability_path [friend]
Definition at line 200 of file function_behavior.hpp.
read_profiling_data
friend class read_profiling_data [friend]
Definition at line 202 of file function_behavior.hpp.
tp_profiling
friend class tp_profiling [friend]
Definition at line 203 of file function_behavior.hpp.
Field Documentation
adg
const OpGraphRef FunctionBehavior::adg [private]
The anti-dependencies graph.
Definition at line 252 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
agg_virtualg
const OpGraphRef FunctionBehavior::agg_virtualg [private]
Anti + Data flow graph on aggregates.
Definition at line 351 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
bb
const BBGraphRef FunctionBehavior::bb [private]
The basic block CFG.
Definition at line 219 of file function_behavior.hpp.
Referenced by CGetBBGraph(), CheckFeedbackReachability(), CheckReachability(), and GetBBGraph().
bb_deque_levels
std::deque<vertex> FunctionBehavior::bb_deque_levels [private]
list of operations vertices sorted by topological order in control flow graph; in the sorting then part vertices come before else part ones
Definition at line 368 of file function_behavior.hpp.
Referenced by get_bb_levels().
bb_graphs_collection
const BBGraphsCollectionRef FunctionBehavior::bb_graphs_collection [private]
Global graph storing CFG, dominators and post-dominators. The nodes of this graph are basic blocks.
Definition at line 213 of file function_behavior.hpp.
bb_lm
const level_constructorRef FunctionBehavior::bb_lm
reference to the level constructor
Definition at line 505 of file function_behavior.hpp.
bb_map_levels
std::map<vertex, unsigned int> FunctionBehavior::bb_map_levels [private]
Map basic block vertex to position in topological order in control flow graph; in the sorting then part vertices come before else part ones.
Definition at line 362 of file function_behavior.hpp.
Referenced by get_bb_map_levels().
bb_reachability
CustomUnorderedMapStable<vertex, CustomUnorderedSet<vertex> > FunctionBehavior::bb_reachability
Mutual exclusion between basic blocks (based on control flow graph with flow edges)
Definition at line 482 of file function_behavior.hpp.
Referenced by CheckBBReachability().
bb_version
unsigned int FunctionBehavior::bb_version [private]
The version of basic block intermediate representation.
Definition at line 400 of file function_behavior.hpp.
Referenced by GetBBVersion(), and UpdateBBVersion().
bbgc
const BasicBlocksGraphConstructorRef FunctionBehavior::bbgc
reference to the basic block graph constructor
Definition at line 491 of file function_behavior.hpp.
bitvalue_version
unsigned int FunctionBehavior::bitvalue_version [private]
Version of the bitvalue information.
Definition at line 403 of file function_behavior.hpp.
Referenced by GetBitValueVersion(), and UpdateBitValueVersion().
cdg
const OpGraphRef FunctionBehavior::cdg [private]
The control dependence graph.
Definition at line 258 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
cdg_bb
const BBGraphRef FunctionBehavior::cdg_bb [private]
The control dependence graph among basic blocks.
Definition at line 225 of file function_behavior.hpp.
Referenced by CGetBBGraph(), and GetBBGraph().
cfg
const OpGraphRef FunctionBehavior::cfg [private]
The control flow graph.
Definition at line 243 of file function_behavior.hpp.
Referenced by CGetOpGraph(), CheckFeedbackReachability(), CheckReachability(), get_local_variables(), and GetOpGraph().
deque_levels
std::deque<vertex> FunctionBehavior::deque_levels [private]
list of operations vertices sorted by topological order in control flow graph; in the sorting then part vertices come before else part ones
Definition at line 365 of file function_behavior.hpp.
Referenced by get_levels().
dereference_unknown_address
bool FunctionBehavior::dereference_unknown_address [private]
the function dereference a pointer initialized with constant address.
Definition at line 392 of file function_behavior.hpp.
dfg
const OpGraphRef FunctionBehavior::dfg [private]
The data flow graph.
Definition at line 264 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
dj
const BBGraphRef FunctionBehavior::dj [private]
The dj graph (used for loop computation)
Definition at line 228 of file function_behavior.hpp.
Referenced by CGetBBGraph(), and GetBBGraph().
dominators
dominance<BBGraph>* FunctionBehavior::dominators
This class stores dominator information.
Definition at line 508 of file function_behavior.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), and ~FunctionBehavior().
dt
const BBGraphRef FunctionBehavior::dt [private]
The dominator tree of the CFG on basic blocks.
Definition at line 231 of file function_behavior.hpp.
Referenced by CGetBBGraph(), and GetBBGraph().
dynamic_address
CustomOrderedSet<unsigned int> FunctionBehavior::dynamic_address [private]
store memory objects which can be indirectly addressed through a dynamic address computation
Definition at line 377 of file function_behavior.hpp.
Referenced by add_dynamic_address(), add_parm_decl_copied(), add_parm_decl_loaded(), add_parm_decl_stored(), erase_all_dynamic_addresses(), erase_dynamic_address(), and get_dynamic_address().
extended_bb
const BBGraphRef FunctionBehavior::extended_bb [private]
The basic block Control Flow Graph extended with edges that impose that basic block inside a loop are executed before what follows the loop.
Definition at line 222 of file function_behavior.hpp.
Referenced by CGetBBGraph(), and GetBBGraph().
extended_cfg
const OpGraphRef FunctionBehavior::extended_cfg [private]
The extended control flow graph.
Definition at line 246 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fadg
const OpGraphRef FunctionBehavior::fadg [private]
The anti-dependencies graph with feedback.
Definition at line 255 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fbb
const BBGraphRef FunctionBehavior::fbb [private]
The basic block CFG with feedback.
Definition at line 234 of file function_behavior.hpp.
Referenced by CGetBBGraph(), and GetBBGraph().
fcdg
const OpGraphRef FunctionBehavior::fcdg [private]
The control dependence graph with feedback.
Definition at line 261 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fcfg
const OpGraphRef FunctionBehavior::fcfg [private]
The control flow graph with feedback.
Definition at line 249 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fdfg
const OpGraphRef FunctionBehavior::fdfg [private]
The data flow graph with feedback.
Definition at line 267 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
feedback_bb_reachability
CustomUnorderedMapStable<vertex, CustomUnorderedSet<vertex> > FunctionBehavior::feedback_bb_reachability
Reachability between basic blocks based on control flow graph with feedback.
Definition at line 485 of file function_behavior.hpp.
Referenced by CheckBBFeedbackReachability().
fflaoddg
const OpGraphRef FunctionBehavior::fflaoddg [private]
The anti-dependence + data dependence + output dependence + flow graph with freedback.
Definition at line 282 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fflsaodg
const OpGraphRef FunctionBehavior::fflsaodg [private]
The system dependence, antidependence, output dependence and flow graph with feedback;.
Definition at line 293 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
flaoddg
const OpGraphRef FunctionBehavior::flaoddg [private]
The anti-dependence + data dependence + output dependence + flow graph.
Definition at line 279 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
flg
const OpGraphRef FunctionBehavior::flg [private]
The flow edge operation graph.
Definition at line 270 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
flsaoddg
const OpGraphRef FunctionBehavior::flsaoddg [private]
The system dependence, antidependence, output dependence, flow and debug graph.
Definition at line 289 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
flsaodg
const OpGraphRef FunctionBehavior::flsaodg [private]
The system dependence, antidependence, output dependence and flow graph.
Definition at line 285 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fodg
const OpGraphRef FunctionBehavior::fodg [private]
The output-dependencies flow graph with feedback.
Definition at line 276 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fsaodg
const OpGraphRef FunctionBehavior::fsaodg [private]
The system dependence, antidependence and output dependence graph with feedback.
Definition at line 299 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
fsdg
const OpGraphRef FunctionBehavior::fsdg [private]
The system dependence graph with feedback.
Definition at line 305 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
has_globals
bool FunctionBehavior::has_globals [private]
when true at least one global variable is used
Definition at line 406 of file function_behavior.hpp.
has_undefined_function_receiveing_pointers
bool FunctionBehavior::has_undefined_function_receiveing_pointers [private]
function calls undefined function passing pointers
Definition at line 409 of file function_behavior.hpp.
helper
const BehavioralHelperRef FunctionBehavior::helper [private]
Behavioral helper associated with this behavioral_graph_manager.
Definition at line 210 of file function_behavior.hpp.
Referenced by CGetBehavioralHelper(), get_local_variables(), GetBehavioralHelper(), and print().
lm
const level_constructorRef FunctionBehavior::lm
reference to the level constructor
Definition at line 502 of file function_behavior.hpp.
loops
LoopsRef FunctionBehavior::loops [private]
Loops of the function.
Definition at line 371 of file function_behavior.hpp.
Referenced by CGetLoops(), and GetLoops().
map_levels
std::map<vertex, unsigned int> FunctionBehavior::map_levels [private]
Map operation vertex to position in topological order in control flow graph; in the sorting then part vertices come before else part ones.
Definition at line 359 of file function_behavior.hpp.
Referenced by CheckReachability(), and get_map_levels().
mem_nodeID
CustomOrderedSet<unsigned int> FunctionBehavior::mem_nodeID [private]
this set represents the memory variables accessed by the function
Definition at line 374 of file function_behavior.hpp.
Referenced by add_function_mem(), get_function_mem(), and is_variable_mem().
memory_info
std::map<unsigned int, memory_accessRef> FunctionBehavior::memory_info
map between node id and the corresponding memory allocation
Definition at line 514 of file function_behavior.hpp.
odg
const OpGraphRef FunctionBehavior::odg [private]
The output-dependencies flow graph.
Definition at line 273 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
ogc
const operations_graph_constructorRef FunctionBehavior::ogc
reference to the operations graph constructor
Definition at line 488 of file function_behavior.hpp.
Referenced by SDCScheduling::AddDelayConstraints(), and SDCScheduling::InternalExec().
op_graphs_collection
const OpGraphsCollectionRef FunctionBehavior::op_graphs_collection [private]
Global graph storing CFG, DFG, FCFG, FDFG, SDG, FSDG, CDG. The nodes of this graph are operations.
Definition at line 216 of file function_behavior.hpp.
Referenced by CGetOpGraph().
packed_vars
bool FunctionBehavior::packed_vars
True when there access to packed data.
Definition at line 517 of file function_behavior.hpp.
parameters
const ParameterConstRef FunctionBehavior::parameters [private]
The set of input parameters.
Definition at line 389 of file function_behavior.hpp.
parm_decl_copied
CustomOrderedSet<unsigned int> FunctionBehavior::parm_decl_copied [private]
this set represents the parameters that have to be copied from the caller
Definition at line 380 of file function_behavior.hpp.
Referenced by add_parm_decl_copied(), and get_parm_decl_copied().
parm_decl_loaded
CustomOrderedSet<unsigned int> FunctionBehavior::parm_decl_loaded [private]
this set represents the actual parameters that has to be loaded into the formal parameter from the actual parameter
Definition at line 383 of file function_behavior.hpp.
Referenced by add_parm_decl_loaded(), and get_parm_decl_loaded().
parm_decl_stored
CustomOrderedSet<unsigned int> FunctionBehavior::parm_decl_stored [private]
this set represents the formal parameters that has to be stored into the formal parameter from the actual parameter
Definition at line 386 of file function_behavior.hpp.
Referenced by add_parm_decl_stored(), and get_parm_decl_stored().
pdt
const BBGraphRef FunctionBehavior::pdt [private]
The post-dominator tree of the CFG on basic blocks.
Definition at line 237 of file function_behavior.hpp.
Referenced by CGetBBGraph(), and GetBBGraph().
pipelining_enabled
bool FunctionBehavior::pipelining_enabled [private]
when true pipelining has been requested for this function
Definition at line 415 of file function_behavior.hpp.
pointer_type_conversion
bool FunctionBehavior::pointer_type_conversion [private]
true when at least one pointer conversion happen
Definition at line 395 of file function_behavior.hpp.
post_dominators
dominance<BBGraph>* FunctionBehavior::post_dominators
This class stores post-dominator information.
Definition at line 511 of file function_behavior.hpp.
Referenced by EdgeCWriter::writeRoutineInstructions(), CWriter::writeRoutineInstructions(), and ~FunctionBehavior().
ppg
const BBGraphRef FunctionBehavior::ppg [private]
The support basic block graph for path profiling.
Definition at line 240 of file function_behavior.hpp.
Referenced by CGetBBGraph(), GetBBGraph(), and set_epp().
saodg
const OpGraphRef FunctionBehavior::saodg [private]
The system dependence, antidependence and output dependence graph.
Definition at line 296 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
sdg
const OpGraphRef FunctionBehavior::sdg [private]
The system dependence graph.
Definition at line 302 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
sg
const OpGraphRef FunctionBehavior::sg [private]
The speculation graph.
Definition at line 313 of file function_behavior.hpp.
Referenced by CGetOpGraph(), and GetOpGraph().
state_variables
CustomOrderedSet<unsigned int> FunctionBehavior::state_variables [private]
set of global variables
Definition at line 412 of file function_behavior.hpp.
unaligned_accesses
bool FunctionBehavior::unaligned_accesses [private]
Definition at line 397 of file function_behavior.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/function_behavior.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/function_behavior.cpp