attribute_sequence Struct Reference
#include <xml_attribute.hpp>
Public Types
typedef std::list< xml_attribute * > attribute_list
Public Member Functions
void print_attributes (std::ostream &os) const
Print the class.
xml_attribute * set_attribute (const std::string &name, const std::string &value)
Set the value of the attribute with this name, and optionally with this namespace.
xml_attribute * get_attribute (const std::string &name) const
Obtain the attribute with this name.
attribute_list get_attributes ()
Remove the attribute with this name.
const attribute_list & get_attributes () const
Obtain the list of attributes for this element.
bool has_attributes () const
Private Attributes
attribute_list a_list
std::map< std::string, xml_attributeRef > a_map
Detailed Description
Definition at line 112 of file xml_attribute.hpp.
Member Typedef Documentation
attribute_list
typedef std::list<xml_attribute*> attribute_sequence::attribute_list
Definition at line 114 of file xml_attribute.hpp.
Member Function Documentation
get_attribute()
xml_attribute* attribute_sequence::get_attribute (const std::string & name) const [inline]
Obtain the attribute with this name.
Parameters
name The name of the attribute searched.
Returns
the searched attribute, or 0 if no suitable attribute was found.
Definition at line 159 of file xml_attribute.hpp.
Referenced by BackendFlow::create_xml_scripts(), Parameter::GetFileFormat(), DataXmlParser::Parse(), GccWrapper::ReadXml(), attribute::xload(), xml_command_t::xml_command_t(), xml_foreach_t::xml_foreach_t(), xml_parameter_t::xml_parameter_t(), xml_set_entry_t::xml_set_entry_t(), xml_set_variable_t::xml_set_variable_t(), and xml_shell_t::xml_shell_t().
get_attributes() [1/2]
attribute_list attribute_sequence::get_attributes () [inline]
Remove the attribute with this name.
Parameters
name The name of the attribute to be removed Obtain the list of attributes for this element.
Returns
The list of attributes.
Definition at line 182 of file xml_attribute.hpp.
Referenced by NP_functionality::xload().
get_attributes() [2/2]
const attribute_list& attribute_sequence::get_attributes () const [inline]
Obtain the list of attributes for this element.
Constant version.
Returns
The list of attributes.
Definition at line 190 of file xml_attribute.hpp.
has_attributes()
bool attribute_sequence::has_attributes () const [inline]
Returns
Whether this node has attributes, or is empty.
Definition at line 198 of file xml_attribute.hpp.
Referenced by xml_att_decl_node::print(), and xml_element::print().
print_attributes()
void attribute_sequence::print_attributes (std::ostream & os) const [inline]
Print the class.
Parameters
os is the stream.
Definition at line 119 of file xml_attribute.hpp.
Referenced by xml_att_decl_node::print(), and xml_element::print().
set_attribute()
xml_attribute* attribute_sequence::set_attribute (const std::string & name, const std::string & value) [inline]
Set the value of the attribute with this name, and optionally with this namespace.
A matching attribute will be added if no matching attribute already exists.
Parameters
name The name of the attribute whose value will change.
value The new value for the attribute
Returns
The attribute that was changed or created.
Definition at line 135 of file xml_attribute.hpp.
References xml_node::name, xml_attribute::set_value(), and xml_attribute::xml_attribute().
Referenced by xml_set_entry_t::create_xml_node(), xml_set_variable_t::create_xml_node(), xml_parameter_t::create_xml_node(), xml_command_t::create_xml_node(), xml_shell_t::create_xml_node(), xml_ite_block_t::create_xml_node(), TestVectorParser::ParseXMLFile(), GccWrapper::WriteXml(), attribute::xwrite(), and library_manager::xwrite().
Field Documentation
a_list
attribute_list attribute_sequence::a_list [private]
Definition at line 204 of file xml_attribute.hpp.
a_map
std::map<std::string, xml_attributeRef> attribute_sequence::a_map [private]
Definition at line 205 of file xml_attribute.hpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_attribute.hpp