dom_post_dom_computation Class Reference
loops computation analysis step
#include <dom_post_dom_computation.hpp>
Public Member Functions
dom_post_dom_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~dom_post_dom_computation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the dominators post-dominators computation step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
unsigned int bb_cfg_computation_bb_version
The version of the basic block graph on which dom and post dom trees have been computed.
Additional Inherited Members
Detailed Description
loops computation analysis step
Definition at line 64 of file dom_post_dom_computation.hpp.
Constructor & Destructor Documentation
dom_post_dom_computation()
dom_post_dom_computation::dom_post_dom_computation (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
. include algorithms/dominance include behavior includes design_flows includes graph include tree include utility include
Definition at line 72 of file dom_post_dom_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~dom_post_dom_computation().
 dom_post_dom_computation()
dom_post_dom_computation::~dom_post_dom_computation () [override], [default]
Destructor.
Referenced by dom_post_dom_computation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > dom_post_dom_computation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 80 of file dom_post_dom_computation.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
HasToBeExecuted()
bool dom_post_dom_computation::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 161 of file dom_post_dom_computation.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, bb_cfg_computation_bb_version, FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), Wrefcount< T >::lock(), and THROW_ASSERT.
Initialize()
void dom_post_dom_computation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 103 of file dom_post_dom_computation.cpp.
References FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status dom_post_dom_computation::InternalExec () [override], [virtual]
Performs the dominators post-dominators computation step.
Returns
the exit status of this step
dominators computation
post-dominators computation
Implements FunctionFrontendFlowStep.
Definition at line 109 of file dom_post_dom_computation.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, bb_cfg_computation_bb_version, BBGraph::CGetBBGraphInfo(), FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), D_SELECTOR, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DesignFlowStep::design_flow_manager, FunctionBehavior::DOM_TREE, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, BehavioralHelper::get_function_name(), Wrefcount< T >::lock(), DesignFlowStep::parameters, PD_SELECTOR, FunctionBehavior::POST_DOM_TREE, PRINT_DBG_MEX, SUCCESS, and THROW_ASSERT.
Field Documentation
bb_cfg_computation_bb_version
unsigned int dom_post_dom_computation::bb_cfg_computation_bb_version [private]
The version of the basic block graph on which dom and post dom trees have been computed.
Definition at line 68 of file dom_post_dom_computation.hpp.
Referenced by HasToBeExecuted(), and InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/dom_post_dom_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/dom_post_dom_computation.cpp