AddArtificialCallFlowEdges Class Reference
Superclass include.
#include <AddArtificialCallFlowEdges.hpp>
Public Member Functions
AddArtificialCallFlowEdges (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~AddArtificialCallFlowEdges () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the adding of flow edges to operation graphs.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Utility include Class to perform adding of flow edges to operation graph
Definition at line 52 of file AddArtificialCallFlowEdges.hpp.
Constructor & Destructor Documentation
AddArtificialCallFlowEdges()
AddArtificialCallFlowEdges::AddArtificialCallFlowEdges (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior include boost include tree include
Definition at line 62 of file AddArtificialCallFlowEdges.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~AddArtificialCallFlowEdges().
 AddArtificialCallFlowEdges()
AddArtificialCallFlowEdges::~AddArtificialCallFlowEdges () [override], [default]
Destructor.
Referenced by AddArtificialCallFlowEdges().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > AddArtificialCallFlowEdges::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 70 of file AddArtificialCallFlowEdges.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, OP_REACHABILITY_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status AddArtificialCallFlowEdges::InternalExec () [override], [virtual]
Performs the adding of flow edges to operation graphs.
Returns
the exit status of this step
The control flow graph of basic blocks
The control flow graph of operation
Adding operation to empty return
Implements FunctionFrontendFlowStep.
Definition at line 94 of file AddArtificialCallFlowEdges.cpp.
References FunctionBehavior::BB, FunctionBehavior::CFG, BBGraph::CGetBBNodeInfo(), OpGraph::CGetOpNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FFLSAODG, FunctionBehavior::FLG, FLG_SELECTOR, FunctionFrontendFlowStep::function_behavior, INDENT_DBG_MEX, DesignFlowStep::parameters, STR, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/AddArtificialCallFlowEdges.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/AddArtificialCallFlowEdges.cpp