MemoryInitializationWriterBase Class Reference
Functor used to write initialization of the memory writer.
#include <memory_initialization_writer_base.hpp>
Public Member Functions
MemoryInitializationWriterBase (const tree_managerConstRef TM, const BehavioralHelperConstRef behavioral_helper, const unsigned long int reserved_mem_bytes, const tree_nodeConstRef function_parameter, const TestbenchGeneration_MemoryType testbench_generation_memory_type, const ParameterConstRef parameters)
Constructor.
void CheckEnd () override
Check that all the necessary information was present in the initialization string.
void GoDown () override
Start the initialization of a new aggregated data structure.
void GoNext () override
Consume an element of an aggregated data structure.
void GoUp () override
Ends the initialization of the current aggregated data structure.
Protected Member Functions
const std::string PrintStatus () const
Print the current status.
Protected Attributes
const tree_managerConstRef TM
The tree manager.
const BehavioralHelperConstRef behavioral_helper
The behavioral helper.
const unsigned long int reserved_mem_bytes
The number of bytes to be written.
unsigned long int written_bytes
The number of bytes currently written.
std::vector< std::pair< const tree_nodeConstRef, size_t > > status
The stack representing the current status of the parser; the content is the last dumped element.
const tree_nodeConstRef function_parameter
The variable/parameter being printed.
const TestbenchGeneration_MemoryType testbench_generation_memory_type
The type of initialization being written.
Detailed Description
Functor used to write initialization of the memory writer.
Definition at line 65 of file memory_initialization_writer_base.hpp.
Constructor & Destructor Documentation
MemoryInitializationWriterBase()
MemoryInitializationWriterBase::MemoryInitializationWriterBase (const tree_managerConstRef _TM, const BehavioralHelperConstRef _behavioral_helper, const unsigned long int _reserved_mem_bytes, const tree_nodeConstRef _function_parameter, const TestbenchGeneration_MemoryType _testbench_generation_memory_type, const ParameterConstRef parameters)
Constructor.
Header include.
Parameters
TM is the tree manager
behavioral_helper is the behavioral helper
reserved_mem_bytes is the number of bytes to be written
function_parameter is the function parameter whose initialization is being printed
testbench_generation_memory_type is the type of initialization being printed
parameters is the set of input parameters
. include HLS/simulation include STD include STL include tree includes utility include
Definition at line 67 of file memory_initialization_writer_base.cpp.
References function_parameter, tree_helper::get_type_index(), status, and TM.
Member Function Documentation
CheckEnd()
void MemoryInitializationWriterBase::CheckEnd () [override], [virtual]
Check that all the necessary information was present in the initialization string.
First of all we have to check that there is just one element in the stack
Implements CInitializationParserFunctor.
Definition at line 74 of file memory_initialization_writer_base.cpp.
References PrintStatus(), reserved_mem_bytes, status, STR, THROW_ERROR, and written_bytes.
GoDown()
void MemoryInitializationWriterBase::GoDown () [override], [virtual]
Start the initialization of a new aggregated data structure.
Implements CInitializationParserFunctor.
Definition at line 169 of file memory_initialization_writer_base.cpp.
References tree_helper::CGetElements(), tree_helper::CGetFieldTypes(), tree_helper::CGetPointedType(), CInitializationParserFunctor::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, PrintStatus(), status, STR, THROW_ASSERT, and THROW_ERROR.
GoNext()
void MemoryInitializationWriterBase::GoNext () [override], [virtual]
Consume an element of an aggregated data structure.
We have read a field of record, move to the next field, if any
Check if there is at least another field
Implements CInitializationParserFunctor.
Definition at line 195 of file memory_initialization_writer_base.cpp.
References tree_helper::CGetFieldTypes(), CInitializationParserFunctor::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, PrintStatus(), status, and THROW_ASSERT.
GoUp()
void MemoryInitializationWriterBase::GoUp () [override], [virtual]
Ends the initialization of the current aggregated data structure.
Second, according to the type let's how many elements have to have been processed
parameters cannot have this type, but global variables can
Actually the expected size is unknown
Actual size depends on the pointed type
Implements CInitializationParserFunctor.
Definition at line 85 of file memory_initialization_writer_base.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, tree_helper::CGetFieldTypes(), CInitializationParserFunctor::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_helper::get_array_dimensions(), INDENT_DBG_MEX, NODE_NOT_YET_SUPPORTED_EC, PrintStatus(), status, STR, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, and TM.
PrintStatus()
const std::string MemoryInitializationWriterBase::PrintStatus () const [protected]
Print the current status.
Definition at line 225 of file memory_initialization_writer_base.cpp.
References test_panda::level, status, and STR.
Referenced by CheckEnd(), GoDown(), GoNext(), and GoUp().
Field Documentation
behavioral_helper
const BehavioralHelperConstRef MemoryInitializationWriterBase::behavioral_helper [protected]
The behavioral helper.
Definition at line 72 of file memory_initialization_writer_base.hpp.
Referenced by MemoryInitializationCWriter::Process(), and MemoryInitializationWriter::Process().
function_parameter
const tree_nodeConstRef MemoryInitializationWriterBase::function_parameter [protected]
The variable/parameter being printed.
Definition at line 87 of file memory_initialization_writer_base.hpp.
Referenced by MemoryInitializationWriterBase(), MemoryInitializationCWriter::Process(), and MemoryInitializationWriter::Process().
reserved_mem_bytes
const unsigned long int MemoryInitializationWriterBase::reserved_mem_bytes [protected]
The number of bytes to be written.
Definition at line 75 of file memory_initialization_writer_base.hpp.
Referenced by CheckEnd().
status
std::vector<std::pair<const tree_nodeConstRef, size_t> > MemoryInitializationWriterBase::status [protected]
The stack representing the current status of the parser; the content is the last dumped element.
First element of the pair is the tree node describing the type, the second element of the pair is the number of the field (for struct/union) or of the element (for array) Second element is the number of seen elements (index of the last element + 1) Note that storing last element dumped is equivalent to store next element to be dumped, but this approach make easier check of closes parenthesis
Definition at line 84 of file memory_initialization_writer_base.hpp.
Referenced by CheckEnd(), GoDown(), GoNext(), GoUp(), MemoryInitializationWriterBase(), PrintStatus(), MemoryInitializationCWriter::Process(), and MemoryInitializationWriter::Process().
testbench_generation_memory_type
const TestbenchGeneration_MemoryType MemoryInitializationWriterBase::testbench_generation_memory_type [protected]
The type of initialization being written.
Definition at line 90 of file memory_initialization_writer_base.hpp.
Referenced by MemoryInitializationCWriter::Process(), and MemoryInitializationWriter::Process().
TM
const tree_managerConstRef MemoryInitializationWriterBase::TM [protected]
The tree manager.
Definition at line 69 of file memory_initialization_writer_base.hpp.
Referenced by GoUp(), MemoryInitializationWriterBase(), MemoryInitializationCWriter::Process(), and MemoryInitializationWriter::Process().
written_bytes
unsigned long int MemoryInitializationWriterBase::written_bytes [protected]
The number of bytes currently written.
Definition at line 78 of file memory_initialization_writer_base.hpp.
Referenced by CheckEnd(), MemoryInitializationCWriter::Process(), and MemoryInitializationWriter::Process().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/memory_initialization_writer_base.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/memory_initialization_writer_base.cpp