mem_cg_ext Class Reference
#include <mem_cg_ext.hpp>
Public Member Functions
mem_cg_ext (const application_managerRef AppM, const unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
~mem_cg_ext () override
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 49 of file mem_cg_ext.hpp.
Constructor & Destructor Documentation
mem_cg_ext()
mem_cg_ext::mem_cg_ext (const application_managerRef AppM, const unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Definition at line 67 of file mem_cg_ext.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~mem_cg_ext().
 mem_cg_ext()
mem_cg_ext::~mem_cg_ext () [override], [default]
Referenced by mem_cg_ext().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > mem_cg_ext::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Workaround: this should be a precedence, but when this is added later for functions added during call graph extension is added as unnecessary and it is not updated before its execution
Implements FrontendFlowStep.
Definition at line 75 of file mem_cg_ext.cpp.
References FrontendFlowStep::ALL_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, FUNCTION_ANALYSIS, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, USE_COUNTING, and FrontendFlowStep::WHOLE_APPLICATION.
Initialize()
void mem_cg_ext::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 357 of file mem_cg_ext.cpp.
InternalExec()
DesignFlowStep_Status mem_cg_ext::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 111 of file mem_cg_ext.cpp.
References FrontendFlowStep::AppM, test_panda::args, FunctionBehavior::CGetBehavioralHelper(), tree_manager::CGetTreeReindex(), tree_helper::CGetType(), tree_manipulation::create_gimple_call(), tree_manipulation::create_pointer_type(), tree_manipulation::CreateGimpleAssignAddrExpr(), tree_manipulation::CreateIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_id, tree_helper::get_formal_ith(), BehavioralHelper::get_function_name(), GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, max(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, tree_helper::Size(), sl, STR, SUCCESS, THROW_ASSERT, and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/mem_cg_ext.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/mem_cg_ext.cpp