PragmaAnalysis Class Reference
Restructure the tree control flow graph.
#include <pragma_analysis.hpp>
Public Member Functions
PragmaAnalysis (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~PragmaAnalysis () override
Destructor.
DesignFlowStep_Status Exec () override
Performes the analysis of the pragmas.
Private Member Functions
std::string get_call_parameter (const unsigned int tree_node, const unsigned int param) const
Given the index of a function replacing a pragma, returns a parameter.
void create_map_pragma (const unsigned int tree_node) const
Create a map pragma.
void create_omp_pragma (const unsigned int tree_node) const
Create an omp pragma.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Restructure the tree control flow graph.
Definition at line 63 of file pragma_analysis.hpp.
Constructor & Destructor Documentation
PragmaAnalysis()
PragmaAnalysis::PragmaAnalysis (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
Codesign include Constants include parser/treegcc include Pragma include STL include Tree include Utility include
Definition at line 82 of file pragma_analysis.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~PragmaAnalysis().
 PragmaAnalysis()
PragmaAnalysis::~PragmaAnalysis () [override], [default]
Destructor.
Referenced by PragmaAnalysis().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > PragmaAnalysis::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 89 of file pragma_analysis.cpp.
References CREATE_TREE_MANAGER, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
create_map_pragma()
void PragmaAnalysis::create_map_pragma (const unsigned int tree_node) const [private]
Create a map pragma.
Parameters
index_node is the tree index of the gimple containing the call which will be directly replaced by the pragma
Definition at line 407 of file pragma_analysis.cpp.
References FrontendFlowStep::AppM, tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, get_call_parameter(), GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, tree_manager::new_tree_node_id(), STR_CST_pragma_function_single_line_two_arguments, STR_CST_pragma_keyword_recursive, THROW_ASSERT, THROW_ERROR, TOK, TOK_BB_INDEX, TOK_HW_COMPONENT, TOK_IS_BLOCK, TOK_OPEN, TOK_PRAGMA_DIRECTIVE, TOK_PRAGMA_SCOPE, TOK_RECURSIVE, and TOK_SRCP.
Referenced by Exec().
create_omp_pragma()
void PragmaAnalysis::create_omp_pragma (const unsigned int tree_node) const [private]
Create an omp pragma.
Parameters
index_node is the tree index of the gimple containing the call which will be directly replaced by the pragma
Definition at line 137 of file pragma_analysis.cpp.
References FrontendFlowStep::AppM, tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, get_call_parameter(), GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), pragma_manager::GetOmpPragmaType(), INDENT_DBG_MEX, tree_manager::new_tree_node_id(), pragma_manager::OMP_ATOMIC, pragma_manager::OMP_BARRIER, pragma_manager::OMP_CRITICAL, pragma_manager::OMP_DECLARE_SIMD, pragma_manager::omp_directive_keywords, pragma_manager::OMP_FOR, pragma_manager::OMP_PARALLEL, pragma_manager::OMP_PARALLEL_FOR, pragma_manager::OMP_PARALLEL_SECTIONS, pragma_manager::OMP_SECTION, pragma_manager::OMP_SECTIONS, pragma_manager::OMP_SIMD, pragma_manager::OMP_TARGET, pragma_manager::OMP_TASK, pragma_manager::OMP_UNKNOWN, OpenParallelSections, STR_CST_pragma_function_end, STR_CST_pragma_function_single_line_one_argument, STR_CST_pragma_function_start, THROW_ERROR, THROW_UNREACHABLE, TOK, TOK_BB_INDEX, TOK_IS_BLOCK, TOK_MEMDEF, TOK_MEMUSE, TOK_OP0, TOK_OP1, TOK_OPEN, TOK_PRAGMA_DIRECTIVE, TOK_PRAGMA_OMP_SHORTCUT, TOK_PRAGMA_SCOPE, TOK_SRCP, and tree_node::ToString().
Referenced by Exec().
Exec()
DesignFlowStep_Status PragmaAnalysis::Exec () [override], [virtual]
Performes the analysis of the pragmas.
Returns
the exit status of this step
Erasing first element
Erasing not the first element
No more gimple_node - Finished for this block
Implements ApplicationFrontendFlowStep.
Definition at line 458 of file pragma_analysis.cpp.
References FrontendFlowStep::AppM, create_map_pragma(), create_omp_pragma(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, el, get_call_parameter(), GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetAllFunctions(), INDENT_DBG_MEX, sl, STR, STR_CST_pragma_function_generic, STR_CST_pragma_keyword_map, STR_CST_pragma_keyword_omp, STR_CST_pragma_prefix, SUCCESS, TOK, and TOK_SRCP.
get_call_parameter()
std::string PragmaAnalysis::get_call_parameter (const unsigned int tree_node, const unsigned int param) const [private]
Given the index of a function replacing a pragma, returns a parameter.
Parameters
tree_node is the index of the call
param is the index of the parameter (starting from 1)
Definition at line 117 of file pragma_analysis.cpp.
References FrontendFlowStep::AppM, test_panda::arg, gimple_call::args, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, tree_manager::get_tree_node_const(), INDENT_DBG_MEX, and THROW_ASSERT.
Referenced by create_map_pragma(), create_omp_pragma(), and Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/pragma_analysis.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/pragma_analysis.cpp