xml_comment_node Class Reference
#include <xml_comment_node.hpp>
Public Member Functions
xml_comment_node (const std::string &comment)
constructor
void print (std::ostream &os, bool formatted, simple_indent *pp) const override
Print the class.
std::string get_content () const
Get the text of this content node.
void set_content (const std::string &content)
Set the text of this content node.
Additional Inherited Members
Detailed Description
Definition at line 52 of file xml_comment_node.hpp.
Constructor & Destructor Documentation
xml_comment_node()
xml_comment_node::xml_comment_node (const std::string & comment) [inline], [explicit]
constructor
Definition at line 56 of file xml_comment_node.hpp.
Member Function Documentation
get_content()
std::string xml_comment_node::get_content () const [inline]
Get the text of this content node.
Returns
The text. Note that the 5 predefined entities (&, ", <, &qt, ') are always resolved, so this content will show their human-readable equivalents.
Definition at line 79 of file xml_comment_node.hpp.
References xml_node::get_name().
print()
void xml_comment_node::print (std::ostream & os, bool formatted, simple_indent * pp) const [inline], [override], [virtual]
Print the class.
Parameters
os is the stream.
formatted when true the xml is formatted in human readable way.
pp is the pretty print helper.
Implements xml_node.
Definition at line 66 of file xml_comment_node.hpp.
References xml_node::convert_unescaped(), and xml_node::get_name().
set_content()
void xml_comment_node::set_content (const std::string & content) [inline]
Set the text of this content node.
Parameters
content The text. This must be unescaped, meaning that the predefined entities will be created for you where necessary. See get_content().
Definition at line 88 of file xml_comment_node.hpp.
References xml_node::set_name().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_comment_node.hpp