CallGraphManager Class Reference
This class manages the accesses to the CallGraph.
#include <call_graph_manager.hpp>
Public Member Functions
CallGraphManager (const FunctionExpanderConstRef function_expander, const bool single_root_function, const bool allow_recursive_functions, const tree_managerConstRef tree_manager, const ParameterConstRef Param)
Constructor.
~CallGraphManager ()
Destructor.
CallGraphRef GetCallGraph ()
Return the call graph.
const CallGraphConstRef CGetAcyclicCallGraph () const
Return an acyclic version of the call graph.
const CallGraphConstRef CGetCallGraph () const
Return the call graph.
const CallGraphConstRef CGetCallSubGraph (const CustomUnorderedSet< vertex > &vertices) const
Return a subset of the call graph.
const CustomOrderedSet< unsigned int > get_called_by (unsigned int index) const
Returns the set of functions called by a function.
const CustomUnorderedSet< unsigned int > get_called_by (const OpGraphConstRef cfg, const vertex &caller) const
Returns the set of functions called by an operation vertex.
unsigned int get_function (vertex node) const
Given a vertex of the call graph, this returns the index of the corresponding function.
vertex GetVertex (const unsigned int index) const
Return the vertex given the function id.
const CustomOrderedSet< unsigned int > GetRootFunctions () const
Returns the root functions (i.e., the functions that are not called by any other ones.
CustomOrderedSet< unsigned int > GetReachedBodyFunctions () const
Returns the source code functions called by the root functions.
CustomOrderedSet< unsigned int > GetReachedBodyFunctionsFrom (unsigned int from_f) const
compute the list of reached function starting from a given function
CustomOrderedSet< unsigned int > GetReachedLibraryFunctions () const
Returns the library functions called by the root functions.
bool IsVertex (unsigned int functionID) const
return true in case the vertex has been already created
bool IsCallPoint (unsigned int caller_id, unsigned int called_id, unsigned int call_id, enum FunctionEdgeInfo::CallType call_type) const
Returns true if the call point is present.
void AddFunction (unsigned int new_function_id, const FunctionBehaviorRef fun_behavior)
void AddCallPoint (unsigned int caller_id, unsigned int called_id, unsigned int call_id, enum FunctionEdgeInfo::CallType call_type)
Creates a new call point.
void AddFunctionAndCallPoint (unsigned int caller_id, unsigned int called_id, unsigned int call_id, const FunctionBehaviorRef called_function_behavior, enum FunctionEdgeInfo::CallType call_type)
Creates a new called function and directly adds the call to the call graph.
void RemoveCallPoint (const unsigned int caller_id, const unsigned int called_id, const unsigned int call_id)
Remove a function call, like RemoveCallPoint with a different API.
void RemoveCallPoint (EdgeDescriptor e, const unsigned int call_id)
Removes a call point.
void ReplaceCallPoint (const EdgeDescriptor e, const unsigned int old_call_id, const unsigned int new_call_id)
Replaces a call point.
bool ExistsAddressedFunction () const
Returns true is there is at least a reachable function that is called through a function pointer or its address is taken.
CustomOrderedSet< unsigned int > GetAddressedFunctions () const
Returns a set containing all the reachable addressed_functions.
Data Fields
const FunctionExpanderConstRef function_expander
Functor used to check if the analysis should consider the body of a function.
Private Member Functions
void ComputeRootAndReachedFunctions ()
Compute the root and reached functions, maintaining the internal data structures coherent.
Private Attributes
const CallGraphsCollectionRef call_graphs_collection
const CallGraphRef call_graph
The view of call graph with all the edges.
const tree_managerConstRef tree_manager
The tree manager.
std::map< unsigned int, CustomOrderedSet< unsigned int > > called_by
put into relation function F_i and the list of functions called by F_i
std::map< unsigned int, vertex > functionID_vertex_map
put into relation function F_i and the vertex in the call graph representing it
const bool single_root_function
True if only.
const bool allow_recursive_functions
True if recursive calls are allowed.
CustomOrderedSet< unsigned int > root_functions
Root functions.
CustomOrderedSet< unsigned int > reached_body_functions
source code functions directly or indirectly called by the root functions
CustomOrderedSet< unsigned int > reached_library_functions
library functions directly or indirectly called by the root functions
CustomOrderedSet< unsigned int > addressed_functions
set of functions whose address is taken
const ParameterConstRef Param
set of input parameters
const int debug_level
the debug level
Detailed Description
This class manages the accesses to the CallGraph.
Definition at line 69 of file call_graph_manager.hpp.
Constructor & Destructor Documentation
CallGraphManager()
CallGraphManager::CallGraphManager (const FunctionExpanderConstRef function_expander, const bool single_root_function, const bool allow_recursive_functions, const tree_managerConstRef tree_manager, const ParameterConstRef Param)
Constructor.
The data structure is initialized.
Parameters
function_expander is the functor used to determine if a function has to be considered during construction of call graph
single_root_function specifies if only one root function has to be considered
allow_recursive_functions specifies if recursive functions are allowed
tree_manager is the tree manager
Param is the set of input parameters
Definition at line 85 of file call_graph_manager.cpp.
References ~CallGraphManager().
 CallGraphManager()
CallGraphManager::~CallGraphManager () [default]
Destructor.
Referenced by CallGraphManager().
Member Function Documentation
AddCallPoint()
void CallGraphManager::AddCallPoint (unsigned int caller_id, unsigned int called_id, unsigned int call_id, enum FunctionEdgeInfo::CallType call_type)
Creates a new call point.
Parameters
caller_id is the function id of the caller
called_id is the function id of the called function
call_id is the tree node index of the call statement
call_type is the type of call
Definition at line 120 of file call_graph_manager.cpp.
References addressed_functions, FunctionEdgeInfo::call_any, call_graph, call_graphs_collection, called_by, CGetCallGraph(), ComputeRootAndReachedFunctions(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, FEEDBACK_SELECTOR, FunctionEdgeInfo::function_address, GetVertex(), INDENT_DBG_MEX, FunctionEdgeInfo::indirect_call, IsCallPoint(), IsVertex(), STD_SELECTOR, STR, THROW_ASSERT, THROW_UNREACHABLE, and graph::TopologicalSort().
Referenced by AddFunctionAndCallPoint(), and ReplaceCallPoint().
AddFunction()
void CallGraphManager::AddFunction (unsigned int new_function_id, const FunctionBehaviorRef fun_behavior)
Parameters
new_function_id is the index of the function to add
fun_behavior is the corresponding function behavior
Definition at line 99 of file call_graph_manager.cpp.
References call_graph, call_graphs_collection, called_by, ComputeRootAndReachedFunctions(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, functionID_vertex_map, refcount< T >::get(), GET_NODE_INFO, INDENT_DBG_MEX, IsVertex(), STR, and THROW_ASSERT.
Referenced by AddFunctionAndCallPoint().
AddFunctionAndCallPoint()
void CallGraphManager::AddFunctionAndCallPoint (unsigned int caller_id, unsigned int called_id, unsigned int call_id, const FunctionBehaviorRef called_function_behavior, enum FunctionEdgeInfo::CallType call_type)
Creates a new called function and directly adds the call to the call graph.
Parameters
caller_id is the function id of the caller
called_id is the function id of the called function
call_id is the tree node index of the call statement
called_function_behavior is the FunctionBehavior of the called function
call_type is the type of call
Definition at line 232 of file call_graph_manager.cpp.
References AddCallPoint(), and AddFunction().
CGetAcyclicCallGraph()
const CallGraphConstRef CallGraphManager::CGetAcyclicCallGraph () const
Return an acyclic version of the call graph.
Definition at line 352 of file call_graph_manager.cpp.
References call_graphs_collection, and STD_SELECTOR.
CGetCallGraph()
const CallGraphConstRef CallGraphManager::CGetCallGraph () const
Return the call graph.
Definition at line 357 of file call_graph_manager.cpp.
References call_graph.
Referenced by AddCallPoint(), IsCallPoint(), and RemoveCallPoint().
CGetCallSubGraph()
const CallGraphConstRef CallGraphManager::CGetCallSubGraph (const CustomUnorderedSet< vertex > & vertices) const
Return a subset of the call graph.
Parameters
vertices is the subset of vertices to be considered
Definition at line 362 of file call_graph_manager.cpp.
References call_graphs_collection, FEEDBACK_SELECTOR, and STD_SELECTOR.
ComputeRootAndReachedFunctions()
void CallGraphManager::ComputeRootAndReachedFunctions () [private]
Compute the root and reached functions, maintaining the internal data structures coherent.
If top function option has been passed
If not -c option has been passed we assume that whole program has been passed, so the main must be present
Main not found
Main not found, but call graph not yet built
If there is the main, we return it
Return all the functions not called by any other function
Definition at line 400 of file call_graph_manager.cpp.
References allow_recursive_functions, call_graph, debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::function_index(), get_function(), tree_manager::get_next_available_tree_node_id(), GetVertex(), INDENT_DBG_MEX, IsVertex(), Param, reached_body_functions, reached_library_functions, root_functions, single_root_function, STR, THROW_ASSERT, and THROW_ERROR.
Referenced by AddCallPoint(), AddFunction(), and RemoveCallPoint().
ExistsAddressedFunction()
bool CallGraphManager::ExistsAddressedFunction () const
Returns true is there is at least a reachable function that is called through a function pointer or its address is taken.
Definition at line 337 of file call_graph_manager.cpp.
References addressed_functions, and reached_body_functions.
get_called_by() [1/2]
const CustomOrderedSet< unsigned int > CallGraphManager::get_called_by (unsigned int index) const
Returns the set of functions called by a function.
Parameters
index is the index of the caller function
Definition at line 387 of file call_graph_manager.cpp.
References called_by.
get_called_by() [2/2]
const CustomUnorderedSet< unsigned int > CallGraphManager::get_called_by (const OpGraphConstRef cfg, const vertex & caller) const
Returns the set of functions called by an operation vertex.
Parameters
cfg is the pointer to the graph which the operation belongs to
caller is the caller vertex
Definition at line 395 of file call_graph_manager.cpp.
References OpGraph::CGetOpNodeInfo().
get_function()
unsigned int CallGraphManager::get_function (vertex node) const
Given a vertex of the call graph, this returns the index of the corresponding function.
Parameters
node is the vertex of the function
Returns
the index of the function
Definition at line 378 of file call_graph_manager.cpp.
References functionID_vertex_map.
Referenced by CalledFunctionsVisitor::back_edge(), and ComputeRootAndReachedFunctions().
GetAddressedFunctions()
CustomOrderedSet< unsigned int > CallGraphManager::GetAddressedFunctions () const
Returns a set containing all the reachable addressed_functions.
Definition at line 345 of file call_graph_manager.cpp.
References addressed_functions, and reached_body_functions.
GetCallGraph()
CallGraphRef CallGraphManager::GetCallGraph ()
Return the call graph.
GetReachedBodyFunctions()
CustomOrderedSet< unsigned int > CallGraphManager::GetReachedBodyFunctions () const
Returns the source code functions called by the root functions.
Returns
the set of top function
Definition at line 514 of file call_graph_manager.cpp.
References reached_body_functions.
GetReachedBodyFunctionsFrom()
CustomOrderedSet< unsigned int > CallGraphManager::GetReachedBodyFunctionsFrom (unsigned int from_f) const
compute the list of reached function starting from a given function
Parameters
from_f is the starting function
Returns
the set of top function
Definition at line 519 of file call_graph_manager.cpp.
References allow_recursive_functions, call_graph, and GetVertex().
GetReachedLibraryFunctions()
CustomOrderedSet< unsigned int > CallGraphManager::GetReachedLibraryFunctions () const
Returns the library functions called by the root functions.
Returns
the set of library function (without implementation)
Definition at line 531 of file call_graph_manager.cpp.
References reached_library_functions.
GetRootFunctions()
const CustomOrderedSet< unsigned int > CallGraphManager::GetRootFunctions () const
Returns the root functions (i.e., the functions that are not called by any other ones.
Returns
the set of top function
Definition at line 508 of file call_graph_manager.cpp.
References call_graph, root_functions, and THROW_ASSERT.
GetVertex()
vertex CallGraphManager::GetVertex (const unsigned int index) const
Return the vertex given the function id.
Parameters
index is the function index
Returns
the corresponding vertex in the call graph
Definition at line 367 of file call_graph_manager.cpp.
References functionID_vertex_map, STR, and THROW_ASSERT.
Referenced by AddCallPoint(), ComputeRootAndReachedFunctions(), GetReachedBodyFunctionsFrom(), IsCallPoint(), and RemoveCallPoint().
IsCallPoint()
bool CallGraphManager::IsCallPoint (unsigned int caller_id, unsigned int called_id, unsigned int call_id, enum FunctionEdgeInfo::CallType call_type) const
Returns true if the call point is present.
Parameters
caller_id is the function id of the caller
called_id is the function id of the called function
call_id is the tree node index of the call statement
call_type is the type of call
Definition at line 181 of file call_graph_manager.cpp.
References FunctionEdgeInfo::call_any, call_graph, called_by, CGetCallGraph(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, FunctionEdgeInfo::function_address, GetVertex(), INDENT_DBG_MEX, FunctionEdgeInfo::indirect_call, IsVertex(), STR, THROW_ASSERT, and THROW_UNREACHABLE.
Referenced by AddCallPoint().
IsVertex()
bool CallGraphManager::IsVertex (unsigned int functionID) const
return true in case the vertex has been already created
Parameters
functionID is the function identifier
Definition at line 373 of file call_graph_manager.cpp.
References functionID_vertex_map.
Referenced by AddCallPoint(), AddFunction(), ComputeRootAndReachedFunctions(), and IsCallPoint().
RemoveCallPoint() [1/2]
void CallGraphManager::RemoveCallPoint (const unsigned int caller_id, const unsigned int called_id, const unsigned int call_id)
Remove a function call, like RemoveCallPoint with a different API.
Parameters
caller_id is the index of the calling function
called_id is the index of the called function
call_id is the index of the statement containing the call
Definition at line 295 of file call_graph_manager.cpp.
References CGetCallGraph(), GetVertex(), STR, and THROW_ASSERT.
Referenced by ReplaceCallPoint().
RemoveCallPoint() [2/2]
void CallGraphManager::RemoveCallPoint (EdgeDescriptor e, const unsigned int call_id)
Removes a call point.
The edge is completely removed if necessary
Parameters
e is the edge in the call graph
call_id is the call graph point to remove
Definition at line 238 of file call_graph_manager.cpp.
References addressed_functions, call_graph, call_graphs_collection, called_by, ComputeRootAndReachedFunctions(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, STR, and THROW_ASSERT.
ReplaceCallPoint()
void CallGraphManager::ReplaceCallPoint (const EdgeDescriptor e, const unsigned int old_call_id, const unsigned int new_call_id)
Replaces a call point.
Parameters
e is the edge in the call graph
old_call_id is the old call tree node id
new_call_id is the new call tree node id
Definition at line 306 of file call_graph_manager.cpp.
References AddCallPoint(), call_graph, FunctionEdgeInfo::direct_call, FunctionEdgeInfo::function_address, FunctionEdgeInfo::indirect_call, RemoveCallPoint(), and THROW_ASSERT.
Field Documentation
addressed_functions
CustomOrderedSet<unsigned int> CallGraphManager::addressed_functions [private]
set of functions whose address is taken
Definition at line 102 of file call_graph_manager.hpp.
Referenced by AddCallPoint(), ExistsAddressedFunction(), GetAddressedFunctions(), and RemoveCallPoint().
allow_recursive_functions
const bool CallGraphManager::allow_recursive_functions [private]
True if recursive calls are allowed.
Definition at line 90 of file call_graph_manager.hpp.
Referenced by ComputeRootAndReachedFunctions(), and GetReachedBodyFunctionsFrom().
call_graph
const CallGraphRef CallGraphManager::call_graph [private]
The view of call graph with all the edges.
Definition at line 75 of file call_graph_manager.hpp.
Referenced by AddCallPoint(), AddFunction(), CGetCallGraph(), ComputeRootAndReachedFunctions(), GetReachedBodyFunctionsFrom(), GetRootFunctions(), IsCallPoint(), RemoveCallPoint(), and ReplaceCallPoint().
call_graphs_collection
const CallGraphsCollectionRef CallGraphManager::call_graphs_collection [private]
Definition at line 72 of file call_graph_manager.hpp.
Referenced by AddCallPoint(), AddFunction(), CGetAcyclicCallGraph(), CGetCallSubGraph(), and RemoveCallPoint().
called_by
std::map<unsigned int, CustomOrderedSet<unsigned int> > CallGraphManager::called_by [private]
put into relation function F_i and the list of functions called by F_i
Definition at line 81 of file call_graph_manager.hpp.
Referenced by AddCallPoint(), AddFunction(), get_called_by(), IsCallPoint(), and RemoveCallPoint().
debug_level
const int CallGraphManager::debug_level [private]
the debug level
Definition at line 108 of file call_graph_manager.hpp.
Referenced by AddCallPoint(), AddFunction(), ComputeRootAndReachedFunctions(), IsCallPoint(), and RemoveCallPoint().
function_expander
const FunctionExpanderConstRef CallGraphManager::function_expander
Functor used to check if the analysis should consider the body of a function.
Definition at line 118 of file call_graph_manager.hpp.
functionID_vertex_map
std::map<unsigned int, vertex> CallGraphManager::functionID_vertex_map [private]
put into relation function F_i and the vertex in the call graph representing it
Definition at line 84 of file call_graph_manager.hpp.
Referenced by AddFunction(), get_function(), GetVertex(), and IsVertex().
Param
const ParameterConstRef CallGraphManager::Param [private]
set of input parameters
Definition at line 105 of file call_graph_manager.hpp.
Referenced by ComputeRootAndReachedFunctions().
reached_body_functions
CustomOrderedSet<unsigned int> CallGraphManager::reached_body_functions [private]
source code functions directly or indirectly called by the root functions
Definition at line 96 of file call_graph_manager.hpp.
Referenced by ComputeRootAndReachedFunctions(), ExistsAddressedFunction(), GetAddressedFunctions(), and GetReachedBodyFunctions().
reached_library_functions
CustomOrderedSet<unsigned int> CallGraphManager::reached_library_functions [private]
library functions directly or indirectly called by the root functions
Definition at line 99 of file call_graph_manager.hpp.
Referenced by ComputeRootAndReachedFunctions(), and GetReachedLibraryFunctions().
root_functions
CustomOrderedSet<unsigned int> CallGraphManager::root_functions [private]
Root functions.
Definition at line 93 of file call_graph_manager.hpp.
Referenced by ComputeRootAndReachedFunctions(), and GetRootFunctions().
single_root_function
const bool CallGraphManager::single_root_function [private]
True if only.
Definition at line 87 of file call_graph_manager.hpp.
Referenced by ComputeRootAndReachedFunctions().
tree_manager
const tree_managerConstRef CallGraphManager::tree_manager [private]
The tree manager.
Definition at line 78 of file call_graph_manager.hpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/call_graph_manager.cpp