operation Struct Reference
This class specifies the characteristic of a particular operation working on a given functional unit.
#include <technology_node.hpp>
Public Member Functions
operation ()
Constructor.
~operation () override
Destructor.
const std::string & get_name () const override
Returns the name of the operation.
bool is_type_supported (std::string type_name) const
Checks if the specified type name is supported.
bool is_type_supported (std::string type_name, unsigned int type_prec) const
Checks if the specified type name is supported If the attribute `supported_types` is not defined, it will always return true.
bool is_type_supported (const std::string &type_name, const std::vector< unsigned int > &type_prec, const std::vector< unsigned int > &type_n_element) const
Checks if the specified type name is supported with the max precision in type_prec.
std::string get_type_supported_string () const
Returns the supported type as a string.
void xload (const xml_element *Enode, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) override
Load a operation node starting from an xml file.
void xwrite (xml_element *rootnode, const technology_nodeRef tn, const ParameterConstRef Param, const TargetDevice_Type type) override
Add a operation node to an xml tree.
void lib_write (std::ofstream &os, const simple_indentRef PP) override
Append a technology_node to a liberty file.
void lef_write (std::ofstream &os, const simple_indentRef PP) override
Append a technology_node to a LEF file.
std::map< std::string, std::map< std::string, double > > get_pin_to_pin_delay () const
Return the datastructure containing the pin-to-pin delay for this operation.
bool is_bounded () const
bool is_primary_inputs_registered () const
void print (std::ostream &os) const override
function that prints the class operation.
Data Fields
std::string operation_name
name of the operation mappen on a given functional unit.
time_modelRef time_m
class representing the timing information associated with this operation
bool commutative
property of commutativity
bool bounded
flag to determine if the operation is bounded or not
bool primary_inputs_registered
true when the primary input of the functional unit are registered
std::map< std::string, std::vector< unsigned int > > supported_types
supported types and precision of the operation, in form (name, list_of_prec).
std::string pipe_parameters
comma separated string with the parameter for the different implementation of the pipeline. Empty when the operation is not pipelined
std::string portsize_parameters
comma separed string with the parameter for different portsize values.
Additional Inherited Members
Detailed Description
This class specifies the characteristic of a particular operation working on a given functional unit.
Definition at line 367 of file technology_node.hpp.
Constructor & Destructor Documentation
operation()
operation::operation ()
Constructor.
Definition at line 98 of file technology_node.cpp.
References ~operation().
Referenced by AllocationInformation::GetConnectionTime().
 operation()
operation::~operation () [override], [default]
Destructor.
Referenced by operation().
Member Function Documentation
get_name()
const std::string& operation::get_name () const [inline], [override], [virtual]
Returns the name of the operation.
Implements technology_node.
Definition at line 411 of file technology_node.hpp.
References technology_node::lef_write(), technology_node::lib_write(), technology_node::PP, test_panda::type, technology_node::xload(), and technology_node::xwrite().
Referenced by allocation::check_templated_units(), allocation::extract_bambu_provided(), and DiscrepancyAnalysisCWriter::writePostInstructionInfo().
get_pin_to_pin_delay()
std::map< std::string, std::map< std::string, double > > operation::get_pin_to_pin_delay () const
Return the datastructure containing the pin-to-pin delay for this operation.
Definition at line 349 of file technology_node.cpp.
References operation_name, time_model::pin_to_pin_delay, THROW_ASSERT, and time_m.
get_type_supported_string()
std::string operation::get_type_supported_string () const
Returns the supported type as a string.
Definition at line 336 of file technology_node.cpp.
References result, and supported_types.
is_bounded()
bool operation::is_bounded () const [inline]
Definition at line 473 of file technology_node.hpp.
Referenced by DiscrepancyAnalysisCWriter::writePostInstructionInfo().
is_primary_inputs_registered()
bool operation::is_primary_inputs_registered () const [inline]
Definition at line 478 of file technology_node.hpp.
References GET_TEC_KIND, GET_TEC_KIND_TEXT, and technology_node::print().
is_type_supported() [1/3]
bool operation::is_type_supported (std::string type_name) const
Checks if the specified type name is supported.
If the attribute `supported_types` is not defined, it will always return true.
Parameters
type_name is the name of the type
if there is at least one supported type, the given type has to be in the list
Definition at line 304 of file technology_node.cpp.
References supported_types.
Referenced by allocation::check_type_and_precision(), and is_type_supported().
is_type_supported() [2/3]
bool operation::is_type_supported (std::string type_name, unsigned int type_prec) const
Checks if the specified type name is supported If the attribute `supported_types` is not defined, it will always return true.
Parameters
type_name is the name of the type
type_prec is the type precision
check also for the precision
Definition at line 315 of file technology_node.cpp.
References is_type_supported(), and supported_types.
is_type_supported() [3/3]
bool operation::is_type_supported (const std::string & type_name, const std::vector< unsigned int > & type_prec, const std::vector< unsigned int > & type_n_element) const
Checks if the specified type name is supported with the max precision in type_prec.
If the attribute `supported_types` is not defined, it will always return true.
Parameters
type_name is the name of the type
type_prec is the vector of type precisions
Definition at line 329 of file technology_node.cpp.
References is_type_supported().
lef_write()
void operation::lef_write (std::ofstream & os, const simple_indentRef PP) [override], [virtual]
Append a technology_node to a LEF file.
Implements technology_node.
Definition at line 293 of file technology_node.cpp.
References THROW_UNREACHABLE.
lib_write()
void operation::lib_write (std::ofstream & os, const simple_indentRef PP) [override], [virtual]
Append a technology_node to a liberty file.
Implements technology_node.
Definition at line 288 of file technology_node.cpp.
References THROW_UNREACHABLE.
print()
void operation::print (std::ostream & os) const [override], [virtual]
function that prints the class operation.
Parameters
os is the output stream.
Implements technology_node.
Definition at line 298 of file technology_node.cpp.
References commutative, time_model::get_execution_time(), time_model::get_initiation_time(), operation_name, STR, and time_m.
xload()
void operation::xload (const xml_element * Enode, const technology_nodeRef owner, const ParameterConstRef Param, const target_deviceRef device) [override], [virtual]
Load a operation node starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
TM is the technology manager.
name of the operation
commutative property
parsing of supported types
time characterization
timing path
Implements technology_node.
Definition at line 104 of file technology_node.cpp.
References bounded, CE_XVM, commutative, time_model::create_model(), time_model::cycles_time_DEFAULT, time_model::execution_time_DEFAULT, from_strongtype_cast(), xml_child::get_children(), technology_node::get_name(), target_device::get_type(), time_model::initiation_time_DEFAULT, LOAD_XVFM, LOAD_XVM, max(), operation_name, time_model::pin_to_pin_delay, pipe_parameters, portsize_parameters, primary_inputs_registered, time_model::set_execution_time(), time_model::set_initiation_time(), time_model::set_stage_period(), time_model::set_synthesis_dependent(), SplitString(), time_model::stage_period_DEFAULT, supported_types, THROW_ASSERT, THROW_ERROR, time_m, and test_panda::type.
xwrite()
void operation::xwrite (xml_element * rootnode, const technology_nodeRef tn, const ParameterConstRef Param, const TargetDevice_Type type) [override], [virtual]
Add a operation node to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the operation is attached.
name of the operation
commutative property
supported types
timing characterization, if any
Implements technology_node.
Definition at line 210 of file technology_node.cpp.
References xml_child::add_child_element(), bounded, commutative, time_model::cycles_time_DEFAULT, time_model::execution_time_DEFAULT, from_strongtype_cast(), time_model::get_cycles(), time_model::get_execution_time(), time_model::get_initiation_time(), technology_node::get_kind_text(), time_model::get_stage_period(), time_model::get_synthesis_dependent(), time_model::initiation_time_DEFAULT, operation_name, pipe_parameters, portsize_parameters, primary_inputs_registered, time_model::stage_period_DEFAULT, STR, supported_types, time_m, WRITE_XNVM, and WRITE_XVM.
Field Documentation
bounded
bool operation::bounded
flag to determine if the operation is bounded or not
Definition at line 384 of file technology_node.hpp.
Referenced by library_manager::update(), xload(), and xwrite().
commutative
bool operation::commutative
property of commutativity
Definition at line 381 of file technology_node.hpp.
Referenced by allocation::extract_bambu_provided(), print(), xload(), and xwrite().
operation_name
std::string operation::operation_name
name of the operation mappen on a given functional unit.
Definition at line 370 of file technology_node.hpp.
Referenced by FunctionalUnitStep::create_template_instance(), get_pin_to_pin_delay(), print(), library_manager::update(), xload(), and xwrite().
pipe_parameters
std::string operation::pipe_parameters
comma separated string with the parameter for the different implementation of the pipeline. Empty when the operation is not pipelined
Definition at line 393 of file technology_node.hpp.
Referenced by allocation::check_templated_units(), allocation::extract_bambu_provided(), library_manager::update(), xload(), and xwrite().
portsize_parameters
std::string operation::portsize_parameters
comma separed string with the parameter for different portsize values.
Definition at line 396 of file technology_node.hpp.
Referenced by library_manager::update(), xload(), and xwrite().
primary_inputs_registered
bool operation::primary_inputs_registered
true when the primary input of the functional unit are registered
Definition at line 387 of file technology_node.hpp.
Referenced by xload(), and xwrite().
supported_types
std::map<std::string, std::vector<unsigned int> > operation::supported_types
supported types and precision of the operation, in form (name, list_of_prec).
Definition at line 390 of file technology_node.hpp.
Referenced by allocation::extract_bambu_provided(), get_type_supported_string(), is_type_supported(), xload(), and xwrite().
time_m
time_modelRef operation::time_m
class representing the timing information associated with this operation
Definition at line 373 of file technology_node.hpp.
Referenced by allocation::check_templated_units(), AllocationInformation::get_correction_time(), get_pin_to_pin_delay(), print(), AllocationInformation::time_m_execution_time(), AllocationInformation::time_m_stage_period(), library_manager::update(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), xload(), and xwrite().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/technology_node.cpp