op_feedback_edges_computation Class Reference
Compute the feedback edges of the operations graphs.
#include <op_feedback_edges_computation.hpp>
Public Member Functions
op_feedback_edges_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~op_feedback_edges_computation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Computes the feedback edges for the CFG and the CDG operations graphs.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Compute the feedback edges of the operations graphs.
Definition at line 62 of file op_feedback_edges_computation.hpp.
Constructor & Destructor Documentation
op_feedback_edges_computation()
op_feedback_edges_computation::op_feedback_edges_computation (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the paramters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
Behavior include Graph include Frontend include Tree include
Definition at line 68 of file op_feedback_edges_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~op_feedback_edges_computation().
 op_feedback_edges_computation()
op_feedback_edges_computation::~op_feedback_edges_computation () [override], [default]
Destructor.
Referenced by op_feedback_edges_computation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > op_feedback_edges_computation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 76 of file op_feedback_edges_computation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOOPS_COMPUTATION, OPERATIONS_CFG_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status op_feedback_edges_computation::InternalExec () [override], [virtual]
Computes the feedback edges for the CFG and the CDG operations graphs.
Returns
the exit status of this step
then consider loops
add the feedback control dependence and the feedback control flow graph edges
Implements FunctionFrontendFlowStep.
Definition at line 107 of file op_feedback_edges_computation.cpp.
References FunctionBehavior::CFG, CFG_SELECTOR, BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionBehavior::FCFG, FunctionFrontendFlowStep::function_behavior, INDENT_DBG_MEX, DesignFlowStep::parameters, STR, SUCCESS, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/op_feedback_edges_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/op_feedback_edges_computation.cpp