CMOS_technology Class Reference
#include <CMOS_technology.hpp>
Public Member Functions
CMOS_technology (const ParameterConstRef &param)
Constructor of the class.
~CMOS_technology () override
Destructor of the class.
std::string get_string_type () const override
Returns the type of the technology currently implemented in a string format.
Private Member Functions
void initialize () override
Initialize the target device based on the given parameters.
Additional Inherited Members
Detailed Description
Definition at line 52 of file CMOS_technology.hpp.
Constructor & Destructor Documentation
CMOS_technology()
CMOS_technology::CMOS_technology (const ParameterConstRef & param) [explicit]
Constructor of the class.
Autoheader include.
Definition at line 60 of file CMOS_technology.cpp.
References initialize(), OUTPUT_LEVEL_MINIMUM, target_technology::Param, test_panda::parser, PRINT_OUT_MEX, THROW_ERROR, target_technology::type, target_technology::xload(), and ~CMOS_technology().
 CMOS_technology()
CMOS_technology::~CMOS_technology () [override], [default]
Destructor of the class.
Referenced by CMOS_technology().
Member Function Documentation
get_string_type()
std::string CMOS_technology::get_string_type () const [override], [virtual]
Returns the type of the technology currently implemented in a string format.
Returns
a string representing the type of the technology
Implements target_technology.
Definition at line 163 of file CMOS_technology.cpp.
initialize()
void CMOS_technology::initialize () [override], [private], [virtual]
Initialize the target device based on the given parameters.
it represents the height of the cell based on the manufacturing information
it represents the width of each single cell column based on the manufacturing information
Implements target_technology.
Definition at line 126 of file CMOS_technology.cpp.
References OUTPUT_LEVEL_VERBOSE, target_technology::Param, PRINT_OUT_MEX, and target_technology::set_parameter().
Referenced by CMOS_technology().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/target_technology/CMOS/CMOS_technology.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/target_technology/CMOS/CMOS_technology.cpp