CreateAddressTranslation Class Reference
Class which creates source code of hdl module to translate addresses from pci address space to bambu address space.
#include <create_address_translation.hpp>
Public Member Functions
CreateAddressTranslation (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~CreateAddressTranslation () override
Destructor.
DesignFlowStep_Status Exec () override
Execute this step.
Protected Member Functions
void ComputeAddress (const AsnTypeRef asn_type, const unsigned int tree_parameter_type, unsigned int &bambu_address, unsigned int &taste_address, unsigned int &registers, const bool first_level, const bool little_endianess)
Compute the addresses and add them to the writers.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Attributes
IndentedOutputStreamRef address_translation
The address translation stream.
IndentedOutputStreamRef memory_enabling
The memory enabling stream.
IndentedOutputStreamRef data_size
The data size stream.
IndentedOutputStreamRef endianess_check
The endianess check stream.
tree_managerConstRef TreeM
The tree manager.
const AadlInformationRef aadl_information
The asn information.
bool already_executed {false}
True if it was already executed.
Additional Inherited Members
Detailed Description
Class which creates source code of hdl module to translate addresses from pci address space to bambu address space.
Definition at line 57 of file create_address_translation.hpp.
Constructor & Destructor Documentation
CreateAddressTranslation()
CreateAddressTranslation::CreateAddressTranslation (const application_managerRef _AppM, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
. include behavior include constants includes design_flows include HLS include intermediate_representation/aadl include tree includes utility include
Definition at line 75 of file create_address_translation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~CreateAddressTranslation().
 CreateAddressTranslation()
CreateAddressTranslation::~CreateAddressTranslation () [override], [default]
Destructor.
Referenced by CreateAddressTranslation().
Member Function Documentation
ComputeAddress()
void CreateAddressTranslation::ComputeAddress (const AsnTypeRef asn_type, const unsigned int tree_parameter_type, unsigned int & bambu_address, unsigned int & taste_address, unsigned int & registers, const bool first_level, const bool little_endianess) [protected]
Compute the addresses and add them to the writers.
Parameters
asn_type is the type of the asn parameter
tree_parameter_type is the index of the type
bambu_address is the current starting address for bambu interface
taste_address is the current starting address for taste interface
registers is the number of registers to be allocated for this parameter
first_level is true if we are analyzing a parameter and not something inside a parameter
little_endianess tells if the parameter has little endianess
Definition at line 111 of file create_address_translation.cpp.
References aadl_information, address_translation, IndentedOutputStream::Append(), BOOLEAN, tree_helper::CGetPointedType(), tree_helper::CGetType(), CHOICE, counter, data_size, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, endianess_check, ENUMERATED, tree_helper::get_integer_cst_value(), GET_NODE, tree_manager::get_tree_node_const(), AsnType::GetKind(), INDENT_DBG_MEX, index, INTEGER, memory_enabling, OCTET_STRING, REAL, REDEFINE, SEQUENCE, SEQUENCEOF, SET, SETOF, tree_helper::Size(), STR, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, and TreeM.
Referenced by Exec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > CreateAddressTranslation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 83 of file create_address_translation.cpp.
References CREATE_TREE_MANAGER, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, ApplicationFrontendFlowStep::GetSignature(), DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, SUCCESS, THROW_UNREACHABLE, and FrontendFlowStep::WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status CreateAddressTranslation::Exec () [override], [virtual]
Execute this step.
Returns
the exit status of this step
The taste address of return (if any)
Taste address starts from 4, since first 4 bytes are reserved to status register
Build the map between parameter name and index type
Starting address of the parameter
Storing starting coming from outside
We are running if we receive the start and we were not running or if we were running and we didn't receive done
We ended if (we ended in the past or we just ended) and we were not starting
We are starting if we start and we are not running
Implements ApplicationFrontendFlowStep.
Definition at line 382 of file create_address_translation.cpp.
References aadl_information, address_translation, already_executed, IndentedOutputStream::Append(), FrontendFlowStep::AppM, test_panda::arg, tree_manager::CGetTreeNode(), tree_helper::CGetType(), ComputeAddress(), data_size, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, endianess_check, tree_manager::function_index(), refcount< T >::get(), GET_NODE, INDENT_DBG_MEX, tree_helper::is_a_pointer(), memory_enabling, DesignFlowStep::parameters, STR, STR_CST_string_separator, STR_CST_taste_address_translation, STR_CST_taste_data_size, STR_CST_taste_endianess_check, STR_CST_taste_endianess_inversion, STR_CST_taste_memory_enabling, STR_CST_taste_output_multiplexer, STR_CST_taste_reg_status, SUCCESS, THROW_ASSERT, TreeM, UNCHANGED, and IndentedOutputStream::WriteFile().
HasToBeExecuted()
bool CreateAddressTranslation::HasToBeExecuted () const [override], [protected], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from ApplicationFrontendFlowStep.
Definition at line 579 of file create_address_translation.cpp.
References already_executed.
Initialize()
void CreateAddressTranslation::Initialize () [override], [protected], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 573 of file create_address_translation.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::Initialize(), and TreeM.
Field Documentation
aadl_information
const AadlInformationRef CreateAddressTranslation::aadl_information [protected]
The asn information.
Definition at line 76 of file create_address_translation.hpp.
Referenced by ComputeAddress(), and Exec().
address_translation
IndentedOutputStreamRef CreateAddressTranslation::address_translation [protected]
The address translation stream.
Definition at line 61 of file create_address_translation.hpp.
Referenced by ComputeAddress(), and Exec().
already_executed
bool CreateAddressTranslation::already_executed {false} [protected]
True if it was already executed.
Definition at line 79 of file create_address_translation.hpp.
Referenced by Exec(), and HasToBeExecuted().
data_size
IndentedOutputStreamRef CreateAddressTranslation::data_size [protected]
The data size stream.
Definition at line 67 of file create_address_translation.hpp.
Referenced by ComputeAddress(), and Exec().
endianess_check
IndentedOutputStreamRef CreateAddressTranslation::endianess_check [protected]
The endianess check stream.
Definition at line 70 of file create_address_translation.hpp.
Referenced by ComputeAddress(), and Exec().
memory_enabling
IndentedOutputStreamRef CreateAddressTranslation::memory_enabling [protected]
The memory enabling stream.
Definition at line 64 of file create_address_translation.hpp.
Referenced by ComputeAddress(), and Exec().
TreeM
tree_managerConstRef CreateAddressTranslation::TreeM [protected]
The tree manager.
Definition at line 73 of file create_address_translation.hpp.
Referenced by ComputeAddress(), Exec(), and Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/source_code_manipulation/create_address_translation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/source_code_manipulation/create_address_translation.cpp