constant_flop_wrapper Class Reference
#include <constant_flop_wrapper.hpp>
Public Member Functions
constant_flop_wrapper (const ParameterConstRef Param, const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~constant_flop_wrapper () override
Destructor.
DesignFlowStep_Status InternalExec () override
Fixes the var_decl duplication.
Protected Member Functions
void SoftFloatWriter (CustomSet< std::pair< std::string, tree_nodeConstRef >> functions_to_be_created)
Integrate the tree manager with the soft float functions with a constant parameter.
std::string GenerateFunctionName (const std::string &function_name, const tree_nodeConstRef constant)
Compute the name of a function with implicit constant operand.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Protected Attributes
const tree_managerRef TreeM
Tree manager.
const tree_manipulationRef tree_man
tree manipulation
Static Protected Attributes
static CustomOrderedSet< std::string > operations
The set of already created functions.
Additional Inherited Members
Detailed Description
Definition at line 59 of file constant_flop_wrapper.hpp.
Constructor & Destructor Documentation
constant_flop_wrapper()
constant_flop_wrapper::constant_flop_wrapper (const ParameterConstRef Param, const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
fun_id is the function index
design_flow_manager is the design flow manager
Definition at line 99 of file constant_flop_wrapper.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~constant_flop_wrapper().
 constant_flop_wrapper()
constant_flop_wrapper::~constant_flop_wrapper () [override], [default]
Destructor.
Referenced by constant_flop_wrapper().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > constant_flop_wrapper::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 107 of file constant_flop_wrapper.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
GenerateFunctionName()
std::string constant_flop_wrapper::GenerateFunctionName (const std::string & function_name, const tree_nodeConstRef constant) [protected]
Compute the name of a function with implicit constant operand.
Parameters
function_name is the name of the function
constant is the tree node storing the constant
Definition at line 350 of file constant_flop_wrapper.cpp.
Referenced by InternalExec(), and SoftFloatWriter().
InternalExec()
DesignFlowStep_Status constant_flop_wrapper::InternalExec () [override], [virtual]
Fixes the var_decl duplication.
Implements FunctionFrontendFlowStep.
Definition at line 133 of file constant_flop_wrapper.cpp.
References FrontendFlowStep::AppM, function_decl::body, tree_manipulation::CreateCallExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, fun(), FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_manager::function_index(), GenerateFunctionName(), tree_manager::get_implementation_node(), GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeNode(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, decl_node::name, NESTED_FUNCTIONS_EC, operations, DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), sl, SoftFloatWriter(), STR, identifier_node::strg, SUCCESS, THROW_ASSERT, THROW_ERROR_CODE, tree_man, TreeM, and UNCHANGED.
SoftFloatWriter()
void constant_flop_wrapper::SoftFloatWriter (CustomSet< std::pair< std::string, tree_nodeConstRef >> functions_to_be_created) [protected]
Integrate the tree manager with the soft float functions with a constant parameter.
Parameters
functions_to_be_created is the set of functions to be generated
Definition at line 305 of file constant_flop_wrapper.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_behavior, GenerateFunctionName(), operations, DesignFlowStep::parameters, tree_helper::size(), THROW_UNREACHABLE, and TreeM.
Referenced by InternalExec().
Field Documentation
operations
CustomOrderedSet< std::string > constant_flop_wrapper::operations [static], [protected]
The set of already created functions.
Definition at line 63 of file constant_flop_wrapper.hpp.
Referenced by InternalExec(), and SoftFloatWriter().
tree_man
const tree_manipulationRef constant_flop_wrapper::tree_man [protected]
tree manipulation
Definition at line 69 of file constant_flop_wrapper.hpp.
Referenced by InternalExec().
TreeM
const tree_managerRef constant_flop_wrapper::TreeM [protected]
Tree manager.
Definition at line 66 of file constant_flop_wrapper.hpp.
Referenced by InternalExec(), and SoftFloatWriter().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/constant_flop_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/constant_flop_wrapper.cpp