fsm_controller Class Reference
#include <fsm_controller.hpp>
Public Member Functions
fsm_controller (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::FSM_CONTROLLER_CREATOR)
Constructor.
~fsm_controller () override
Destructor.
Protected Member Functions
virtual void add_correct_transition_memory (std::string state_representation)
Set the correct NP functionality.
Private Member Functions
void create_state_machine (std::string &parse)
Generates the string representation of the FSM.
std::string get_guard_value (const tree_managerRef TM, const unsigned int index, vertex op, const OpGraphConstRef data)
Returns the value of the guard value of a case_label_expr default is not managed.
DesignFlowStep_Status InternalExec () override
Execute the step.
Additional Inherited Members
Detailed Description
Definition at line 52 of file fsm_controller.hpp.
Constructor & Destructor Documentation
fsm_controller()
fsm_controller::fsm_controller (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::FSM_CONTROLLER_CREATOR)
Constructor.
HLS/binding/storage_value_insertion.
Parameters
design_flow_manager is the design flow manager
HLS/liveness include HLS/module_allocation STL includes technology/physical_library include
Definition at line 103 of file fsm_controller.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~fsm_controller().
 fsm_controller()
fsm_controller::~fsm_controller () [override], [default]
Destructor.
Referenced by fsm_controller().
Member Function Documentation
add_correct_transition_memory()
void fsm_controller::add_correct_transition_memory (std::string state_representation) [protected], [virtual]
Set the correct NP functionality.
Parameters
state_representation is the state representation of the FSM
Reimplemented in controller_cs.
Definition at line 587 of file fsm_controller.cpp.
References structural_manager::add_NP_functionality(), NP_functionality::FSM, structural_manager::get_circ(), and ControllerCreatorBaseStep::SM.
Referenced by InternalExec().
create_state_machine()
void fsm_controller::create_state_machine (std::string & parse) [private]
Generates the string representation of the FSM.
Getting first state (initial one). It will be also first state for resetting
adding reset state to machine encoding
analysis for each state to compute the default output
ensure that first_state is the really first one...
do some checks
Definition at line 164 of file fsm_controller.cpp.
References ALL_FINISHED, hls::allocation_information, conn_binding::bind_selector_port(), CASE_COND, FunctionBehavior::CFG, StateTransitionGraphManager::CGetAstg(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), StateTransitionGraphManager::CGetStg(), tree_manager::CGetTreeNode(), CLOCK_PORT_NAME, generic_obj::COMMAND_PORT, ControllerCreatorBaseStep::cond_ports, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, DONE_PORT_NAME, DONTCARE_COND, FALSE_COND, structural_object::find_member(), HLSFunctionStep::funId, fu_binding::get(), fu_binding::get_assign(), structural_manager::get_circ(), StateTransitionGraphManager::get_entry_state(), StateTransitionGraphManager::get_exit_state(), AllocationInformation::get_fu(), get_guard_value(), liveness::get_live_in(), GET_NAME, reg_binding::get_register(), StorageValueInformation::get_storage_value_index(), GET_TYPE, reg_binding::get_used_regs(), conn_binding::GetSelectors(), HLSFunctionStep::HLS, HLS_step::HLSMgr, conn_binding::IN, ControllerCreatorBaseStep::in_num, INDENT_DBG_MEX, input_vector_to_string(), insert(), StorageValueInformation::is_a_storage_value(), ControllerCreatorBaseStep::mu_ports, tree_helper::normalized_ID(), NOT_ALL_FINISHED, NULL_VERTEX, ControllerCreatorBaseStep::out_num, ControllerCreatorBaseStep::out_ports, DesignFlowStep::parameters, port_o_K, PRINT_DBG_STRING, hls::Rconn, hls::registered_done_port, RESET_PORT_NAME, hls::Rfu, hls::Rliv, hls::Rreg, START_PORT_NAME, hls::STG, hls::storage_value_information, STR, THROW_ASSERT, THROW_ERROR, top(), TRUE_COND, TYPE_EXTERNAL, and commandport_obj::UNBOUNDED.
Referenced by InternalExec().
get_guard_value()
std::string fsm_controller::get_guard_value (const tree_managerRef TM, const unsigned int index, vertex op, const OpGraphConstRef data) [private]
Returns the value of the guard value of a case_label_expr default is not managed.
Definition at line 548 of file fsm_controller.cpp.
References OpGraph::CGetOpNodeInfo(), tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_helper::get_multi_way_if_pos(), GET_NAME, GET_NODE, tree_manager::get_tree_node_const(), GET_TYPE, STR, THROW_ASSERT, and TYPE_MULTIIF.
Referenced by create_state_machine().
InternalExec()
DesignFlowStep_Status fsm_controller::InternalExec () [override], [private], [virtual]
Execute the step.
Returns
the exit status of this step
top circuit creation
main circuit type
Set some descriptions and legal stuff
Implements HLSFunctionStep.
Definition at line 111 of file fsm_controller.cpp.
References ControllerCreatorBaseStep::add_common_ports(), add_correct_transition_memory(), FunctionBehavior::CGetBehavioralHelper(), create_state_machine(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_name(), HLSFunctionStep::HLS, HLS_step::HLSMgr, PRINT_DBG_MEX, structural_object::set_black_box(), structural_manager::set_top_info(), ControllerCreatorBaseStep::SM, hls::STG, SUCCESS, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/fsm_controller.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/fsm_controller.cpp