TechnologyFlowStep Class Reference
#include <technology_flow_step.hpp>
Public Member Functions
TechnologyFlowStep (const technology_managerRef _TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const TechnologyFlowStep_Type technology_flow_step_type, const ParameterConstRef parameters)
Constructor.
const std::string GetSignature () const override
Return a unified identifier of this design step.
const std::string GetName () const override
Return the name of this design step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Static Public Member Functions
static const std::string EnumToName (const TechnologyFlowStep_Type technology_flow_step_type)
Given a technology flow step type, return the name of the type.
static const std::string ComputeSignature (const TechnologyFlowStep_Type technology_flow_step_type)
Compute the signature of a technology flow step.
Protected Member Functions
virtual const CustomUnorderedSet< TechnologyFlowStep_Type > ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const =0
Return the set of analyses in relationship with this design step.
Protected Attributes
TechnologyFlowStep_Type technology_flow_step_type
The type of step.
const technology_managerRef TM
The technology manager.
const target_deviceRef target
The target device.
Additional Inherited Members
Detailed Description
Definition at line 90 of file technology_flow_step.hpp.
Constructor & Destructor Documentation
TechnologyFlowStep()
TechnologyFlowStep::TechnologyFlowStep (const technology_managerRef _TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const TechnologyFlowStep_Type technology_flow_step_type, const ParameterConstRef parameters)
Constructor.
Parameters
TM is the technology manager
target is the target device
design_flow_manager is the design flow manager
technology_flow_step_type is the type of this step
parameters is the set of input parameters
Definition at line 111 of file technology_flow_step.cpp.
Member Function Documentation
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef TechnologyFlowStep::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 106 of file technology_flow_step.cpp.
References DesignFlowStep::design_flow_manager, and Wrefcount< T >::lock().
Referenced by ComputeRelationships().
ComputeRelationships()
void TechnologyFlowStep::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 93 of file technology_flow_step.cpp.
References CGetDesignFlowStepFactory(), ComputeSignature(), ComputeTechnologyRelationships(), DesignFlowStep::design_flow_manager, and Wrefcount< T >::lock().
ComputeSignature()
const std::string TechnologyFlowStep::ComputeSignature (const TechnologyFlowStep_Type technology_flow_step_type) [static]
Compute the signature of a technology flow step.
Parameters
technology_flow_step_type is the type of the step
Returns
the corresponding signature
Definition at line 78 of file technology_flow_step.cpp.
References STR.
Referenced by AggregateDataFlowAnalysis::ComputeFrontendRelationships(), use_counting::ComputeFrontendRelationships(), short_circuit_taf::ComputeFrontendRelationships(), fun_dominator_allocation::ComputeRelationships(), AggregateDataFlowAnalysis::ComputeRelationships(), GenerateFuList::ComputeRelationships(), use_counting::ComputeRelationships(), interface_infer::ComputeRelationships(), ComputeRelationships(), lut_transformation::ComputeRelationships(), IR_lowering::ComputeRelationships(), RTLCharacterization::ComputeRelationships(), PhiOpt::ComputeRelationships(), GetSignature(), and main().
ComputeTechnologyRelationships()
virtual const CustomUnorderedSet<TechnologyFlowStep_Type> TechnologyFlowStep::ComputeTechnologyRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [pure virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implemented in FixCharacterization, LoadDefaultTechnology, LoadDeviceTechnology, LoadFileTechnology, LoadTechnology, WriteTechnology, and LoadBuiltinTechnology.
Referenced by ComputeRelationships().
EnumToName()
const std::string TechnologyFlowStep::EnumToName (const TechnologyFlowStep_Type technology_flow_step_type) [static]
Given a technology flow step type, return the name of the type.
Header include.
Parameters
technology_flow_step_type is the type to be considered
Returns
the name of the type
design_flows include design_flows/technology include
Definition at line 52 of file technology_flow_step.cpp.
References FIX_CHARACTERIZATION, LOAD_DEFAULT_TECHNOLOGY, LOAD_DEVICE_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, LOAD_TECHNOLOGY, THROW_UNREACHABLE, and WRITE_TECHNOLOGY.
Referenced by GetName().
GetName()
const std::string TechnologyFlowStep::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 88 of file technology_flow_step.cpp.
References EnumToName(), and technology_flow_step_type.
Referenced by LoadTechnology::PrintFinalIR().
GetSignature()
const std::string TechnologyFlowStep::GetSignature () const [override], [virtual]
Return a unified identifier of this design step.
Returns
the signature of the design step
Implements DesignFlowStep.
Definition at line 83 of file technology_flow_step.cpp.
References ComputeSignature(), and technology_flow_step_type.
HasToBeExecuted()
bool TechnologyFlowStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 116 of file technology_flow_step.cpp.
Field Documentation
target
const target_deviceRef TechnologyFlowStep::target [protected]
The target device.
Definition at line 100 of file technology_flow_step.hpp.
Referenced by LoadDefaultTechnology::Exec(), WriteTechnology::Exec(), LoadFileTechnology::Exec(), and LoadDeviceTechnology::Exec().
technology_flow_step_type
TechnologyFlowStep_Type TechnologyFlowStep::technology_flow_step_type [protected]
The type of step.
Definition at line 94 of file technology_flow_step.hpp.
Referenced by GetName(), and GetSignature().
TM
const technology_managerRef TechnologyFlowStep::TM [protected]
The technology manager.
Definition at line 97 of file technology_flow_step.hpp.
Referenced by LoadBuiltinTechnology::Exec(), LoadDefaultTechnology::Exec(), LoadFileTechnology::Exec(), WriteTechnology::Exec(), FixCharacterization::Exec(), FixCharacterization::Initialize(), and LoadTechnology::PrintFinalIR().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/technology_flow_step.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/technology_flow_step.cpp