CondExprRestructuring Class Reference
#include <cond_expr_restructuring.hpp>
Public Member Functions
CondExprRestructuring (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~CondExprRestructuring () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
bool IsCondExprGimple (const tree_nodeConstRef tn) const
Return true if tree node is a gimple_assign with a cond_expr in the right part.
tree_nodeRef IsCondExprChain (const tree_nodeConstRef tn, const bool first) const
Given a gimple_assign with cond_expr in the right part and one of its operand it checks:
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
ScheduleRef schedule
The schedule.
AllocationInformationRef allocation_information
The allocation information.
tree_managerRef TM
The tree manager.
Additional Inherited Members
Detailed Description
Definition at line 55 of file cond_expr_restructuring.hpp.
Constructor & Destructor Documentation
CondExprRestructuring()
CondExprRestructuring::CondExprRestructuring (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 131 of file cond_expr_restructuring.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~CondExprRestructuring().
 CondExprRestructuring()
CondExprRestructuring::~CondExprRestructuring () [override], [default]
Destructor.
Referenced by CondExprRestructuring().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > CondExprRestructuring::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Not executed
If schedule is not update, do not execute this step and invalidate UpdateSchedule
Implements FrontendFlowStep.
Definition at line 83 of file cond_expr_restructuring.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::CGetBBVersion(), COMPLETE_BB_GRAPH, FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SUCCESS, and THROW_UNREACHABLE.
HasToBeExecuted()
bool CondExprRestructuring::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 495 of file cond_expr_restructuring.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::CGetBBVersion(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, FunctionFrontendFlowStep::HasToBeExecuted(), Wrefcount< T >::lock(), and DesignFlowStep::parameters.
Initialize()
void CondExprRestructuring::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 484 of file cond_expr_restructuring.cpp.
References allocation_information, FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, DesignFlowStep::Initialize(), schedule, and TM.
InternalExec()
DesignFlowStep_Status CondExprRestructuring::InternalExec () [override], [virtual]
Performs the loops analysis.
Check if new ending time would not be larger The time in which last operand is ready
As cond expr time we consider the worst among the existing operation in the chain
Inserting first cond expr after the last one
Create the ssa in the left part
Create the assign
Set the bit value for the intermediate ssa to correctly update execution time
simplified version
we are going to create a LUT
Inserting last cond expr
Create the assign
Check that the second cond expr is actually dead
Remove the intermediate cond_expr
Removing added statements
Adding old statements
Recomputing schedule
Setting pointer to the previous element
Restarting
Implements FunctionFrontendFlowStep.
Definition at line 174 of file cond_expr_restructuring.cpp.
References allocation_information, FrontendFlowStep::AppM, tree_manager::CGetTreeNode(), counter, tree_manipulation::create_boolean_type(), tree_manipulation::create_lut_expr(), tree_manager::create_tree_node(), tree_manipulation::CreateDefaultUnsignedLongLongInt(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, EPSILON, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, Schedule::get_cstep(), GET_INDEX_NODE, tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), AllocationInformation::GetConnectionTime(), Schedule::GetEndingTime(), FunctionFrontendFlowStep::GetName(), AllocationInformation::GetTimeLatency(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_node::index, IsCondExprChain(), IsCondExprGimple(), max(), tree_manager::new_tree_node_id(), DesignFlowStep::parameters, schedule, sl, STR, SUCCESS, THROW_ASSERT, TM, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, UNCHANGED, fu_binding::UNKNOWN, Schedule::UpdateTime(), and FunctionFrontendFlowStep::WriteBBGraphDot().
IsCondExprChain()
tree_nodeRef CondExprRestructuring::IsCondExprChain (const tree_nodeConstRef tn, const bool first) const [private]
Given a gimple_assign with cond_expr in the right part and one of its operand it checks:
if operand is a ssa_name
if operand is defined in the same basic block
if operand is defined in a gimple_assign whose right a part is another cond_expr
if operand is on the relative critical path (i.e., it delays execution of tn
Parameters
tn is the starting gimple_assign
first is true if first operand has to be considered, false if second oeprand has to be considered
Returns
the chained gimple_assignment if all conditions hold
Definition at line 147 of file cond_expr_restructuring.cpp.
References GET_CONST_NODE, Schedule::get_cstep(), Schedule::get_cstep_end(), GET_NODE, Schedule::GetEndingTime(), Schedule::GetStartingTime(), tree_helper::is_constant(), schedule, and TM.
Referenced by InternalExec().
IsCondExprGimple()
bool CondExprRestructuring::IsCondExprGimple (const tree_nodeConstRef tn) const [private]
Return true if tree node is a gimple_assign with a cond_expr in the right part.
Parameters
tn is the tree reindex to be considered
Definition at line 139 of file cond_expr_restructuring.cpp.
References GET_CONST_NODE, and GET_NODE.
Referenced by InternalExec().
Field Documentation
allocation_information
AllocationInformationRef CondExprRestructuring::allocation_information [private]
The allocation information.
Definition at line 62 of file cond_expr_restructuring.hpp.
Referenced by Initialize(), and InternalExec().
schedule
ScheduleRef CondExprRestructuring::schedule [private]
The schedule.
Definition at line 59 of file cond_expr_restructuring.hpp.
Referenced by Initialize(), InternalExec(), and IsCondExprChain().
TM
tree_managerRef CondExprRestructuring::TM [private]
The tree manager.
Definition at line 65 of file cond_expr_restructuring.hpp.
Referenced by Initialize(), InternalExec(), and IsCondExprChain().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/cond_expr_restructuring.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/cond_expr_restructuring.cpp