VarComputation Class Reference
#include <var_computation.hpp>
Public Member Functions
VarComputation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~VarComputation () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Computes the set of read and written variables.
Private Member Functions
void RecursivelyAnalyze (const vertex op_vertex, const tree_nodeConstRef tree_node, const FunctionBehavior_VariableAccessType access_type) const
Recursively analyze a tree_node.
void AnalyzeVops (const vertex op_graph, const gimple_node *vops) const
Analyze virtual operands associated with a gimple node.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const operations_graph_constructorRef ogc
The operation graph constructor.
const OpGraphConstRef cfg
The control flow graph of the function.
const BehavioralHelperRef behavioral_helper
The behavioral helper associated with the function.
Additional Inherited Members
Detailed Description
Definition at line 71 of file var_computation.hpp.
Constructor & Destructor Documentation
VarComputation()
VarComputation::VarComputation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the reference to the application manager
function_id is the index of the function
design_flow_manager is the design flow manager
Definition at line 83 of file var_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~VarComputation().
 VarComputation()
VarComputation::~VarComputation () [override], [default]
Destructor.
Referenced by VarComputation().
Member Function Documentation
AnalyzeVops()
void VarComputation::AnalyzeVops (const vertex op_graph, const gimple_node * vops) const [private]
Analyze virtual operands associated with a gimple node.
Parameters
op_vertex is the vertex to which gimple node belongs
vops is the set of virtual operands to be considered
Definition at line 638 of file var_computation.cpp.
References DEFINITION, GET_INDEX_NODE, gimple_node::memdef, MEMORY, gimple_node::memuse, ogc, OVER, USE, gimple_node::vdef, VIRTUAL, gimple_node::vovers, and gimple_node::vuses.
Referenced by RecursivelyAnalyze().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > VarComputation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 91 of file var_computation.cpp.
References BUILD_VIRTUAL_PHI, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, OPERATIONS_CFG_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void VarComputation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 121 of file var_computation.cpp.
References FunctionFrontendFlowStep::bb_version, FunctionBehavior::CFG, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status VarComputation::InternalExec () [override], [virtual]
Computes the set of read and written variables.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 144 of file var_computation.cpp.
References FrontendFlowStep::AppM, cfg, FunctionBehavior::CFG, OpGraph::CGetOpNodeInfo(), tree_manager::CGetTreeNode(), ENTRY_ID, EXIT_ID, FunctionFrontendFlowStep::function_behavior, GET_TYPE, DesignFlowStep::parameters, RecursivelyAnalyze(), SUCCESS, TYPE_VPHI, and UNKNOWN.
RecursivelyAnalyze()
void VarComputation::RecursivelyAnalyze (const vertex op_vertex, const tree_nodeConstRef tree_node, const FunctionBehavior_VariableAccessType access_type) const [private]
Recursively analyze a tree_node.
Parameters
op_vertex is the vertex to which the statement where tree_node is inclued belongs
tree_node is the tree node to be examined
access_type is the type of the access
Needed to correctly support function pointers
add parameter to the vertex
Needed to correctly support function pointers
add parameter to the vertex
GCC 4.5 plugin does not writer vuse for component ref of volatile variable
Definition at line 188 of file var_computation.cpp.
References ADDRESS, AnalyzeVops(), FrontendFlowStep::AppM, ARG, test_panda::arg, test_panda::args, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, cfg, OpGraph::CGetOpGraphInfo(), tree_helper::CGetType(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DEFINITION, GET_CONST_NODE, GET_NODE, INDENT_DBG_MEX, tree_helper::is_volatile(), ogc, OVER, DesignFlowStep::parameters, SCALAR, THROW_ERROR, THROW_UNREACHABLE, UNKNOWN, USE, and VIRTUAL.
Referenced by InternalExec().
Field Documentation
behavioral_helper
const BehavioralHelperRef VarComputation::behavioral_helper [private]
The behavioral helper associated with the function.
Definition at line 81 of file var_computation.hpp.
cfg
const OpGraphConstRef VarComputation::cfg [private]
The control flow graph of the function.
Definition at line 78 of file var_computation.hpp.
Referenced by InternalExec(), and RecursivelyAnalyze().
ogc
const operations_graph_constructorRef VarComputation::ogc [private]
The operation graph constructor.
Definition at line 75 of file var_computation.hpp.
Referenced by AnalyzeVops(), and RecursivelyAnalyze().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/var_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/var_computation.cpp