Evaluation Class Reference
#include <evaluation.hpp>
Public Member Functions
Evaluation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~Evaluation () override
Destructor.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
DesignFlowStep_Status Exec () override
Execute the step.
Private Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 70 of file evaluation.hpp.
Constructor & Destructor Documentation
Evaluation()
Evaluation::Evaluation (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
. include
Parameters
design_flow_manager is the design flow manager
hls_flow_step_type is the type of evaluation
behavior include constants include hls includes polixml include tree include utility include HLS include behavior include technology/physical_library/models includes wrapper/synthesis include
Definition at line 88 of file evaluation.cpp.
References DesignFlowStep::debug_level, EVALUATION, GET_CLASS, DesignFlowStep::parameters, and ~Evaluation().
 Evaluation()
Evaluation::~Evaluation () [override], [default]
Destructor.
Referenced by Evaluation().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > Evaluation::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 95 of file evaluation.cpp.
References ALL_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DRY_RUN, DRY_RUN_EVALUATION, EXACT, DesignFlowStep::INVALIDATION_RELATIONSHIP, NONE, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_ERROR, THROW_UNREACHABLE, TOP_FUNCTION, and WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status Evaluation::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
get the timing information after the synthesis
get the timing information after the synthesis
get the used resources from the wrapper
get the timing information after the synthesis
get the used resources from the wrapper
Implements DesignFlowStep.
Definition at line 216 of file evaluation.cpp.
References xml_child::add_child_element(), FunctionBehavior::CGetBehavioralHelper(), xml_document::create_root_node(), BehavioralHelper::get_function_name(), TimeStamp::GetCurrentTimeStamp(), HLS_step::HLSMgr, INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, STR, STR_XML_bambu_results_bambu_args, STR_XML_bambu_results_bambu_version, STR_XML_bambu_results_timestamp, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, xml_document::write_to_file_formatted(), and WRITE_XNVM2.
HasToBeExecuted()
bool Evaluation::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 470 of file evaluation.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/evaluation/evaluation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/evaluation/evaluation.cpp