/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/FixStructsPassedByValue.cpp File Reference
#include `FixStructsPassedByValue.hpp`
#include `Parameter.hpp`
#include `application_manager.hpp`
#include `behavioral_helper.hpp`
#include `call_graph_manager.hpp`
#include `dbgPrintHelper.hpp`
#include `function_behavior.hpp`
#include `string_manipulation.hpp`
#include `tree_basic_block.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_manipulation.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
Functions
static bool cannot_have_struct_parameters (const function_decl *const fd, const function_type *const ft, const tree_managerConstRef, const std::string &)
Detailed Description
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Function Documentation
cannot_have_struct_parameters()
static bool cannot_have_struct_parameters (const function_decl *const fd, const function_type *const ft, const tree_managerConstRef , const std::string &) [static]
Definition at line 62 of file FixStructsPassedByValue.cpp.
References GET_CONST_NODE, GET_NODE, tree_helper::is_a_struct(), tree_helper::is_an_union(), function_decl::list_of_args, function_type::prms, STR, and THROW_ASSERT.
Referenced by FixStructsPassedByValue::InternalExec().