FindMaxCFGTransformations Class Reference
Class to find the maximum admissible value of cfg-max-transformations.
#include <find_max_cfg_transformations.hpp>
Public Member Functions
FindMaxCFGTransformations (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~FindMaxCFGTransformations () override
Destructor.
DesignFlowStep_Status Exec () override
Performs the profiling step.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
const std::string ComputeArgString (const size_t cfg_max_transformations) const
Compute the arg list string of bambu.
bool ExecuteBambu (const size_t cfg_max_transformations) const
Execute bambu with cfg-max-transformations.
Additional Inherited Members
Detailed Description
Class to find the maximum admissible value of cfg-max-transformations.
Definition at line 54 of file find_max_cfg_transformations.hpp.
Constructor & Destructor Documentation
FindMaxCFGTransformations()
FindMaxCFGTransformations::FindMaxCFGTransformations (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of the parameters
Definition at line 49 of file find_max_cfg_transformations.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~FindMaxCFGTransformations().
 FindMaxCFGTransformations()
FindMaxCFGTransformations::~FindMaxCFGTransformations () [override], [default]
Destructor.
Referenced by FindMaxCFGTransformations().
Member Function Documentation
ComputeArgString()
const std::string FindMaxCFGTransformations::ComputeArgString (const size_t cfg_max_transformations) const [private]
Compute the arg list string of bambu.
Parameters
cfg_max_transformations is the value to be used in the option
Returns
the argument string
Executable
Definition at line 62 of file find_max_cfg_transformations.cpp.
References test_panda::arg, DesignFlowStep::parameters, STR, and THROW_ASSERT.
Referenced by ExecuteBambu().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > FindMaxCFGTransformations::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 57 of file find_max_cfg_transformations.cpp.
Exec()
DesignFlowStep_Status FindMaxCFGTransformations::Exec () [override], [virtual]
Performs the profiling step.
Returns
the exit status of this step
First check
Implements ApplicationFrontendFlowStep.
Definition at line 109 of file find_max_cfg_transformations.cpp.
References ABORTED, ExecuteBambu(), INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, and STR.
ExecuteBambu()
bool FindMaxCFGTransformations::ExecuteBambu (const size_t cfg_max_transformations) const [private]
Execute bambu with cfg-max-transformations.
Parameters
cfg_max_transformations is the value to be used in the option
Returns
true if the execution was successful, false otherwise
Definition at line 87 of file find_max_cfg_transformations.cpp.
References ComputeArgString(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, INDENT_DBG_MEX, IsError(), PandaSystem(), DesignFlowStep::parameters, and STR.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/find_max_cfg_transformations.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/find_max_cfg_transformations.cpp