/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Introduction/second/module.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
Data Structures
struct stack
struct bin_tree
Macros
#define MAX_NUMBER_OF_NODES 255
Typedefs
typedef struct stack node_stack
typedef struct bin_tree node_tree
Functions
void push_stack_free_list (node_stack **head, node_stack *new_node)
node_stack * pop_stack_free_list (node_stack **head)
void init_stack_free_list ()
void push (node_stack **head, void *t)
_Bool isEmpty (node_stack *head)
void * pop (node_stack **head)
void * top (node_stack *head)
void push_tree_free_list (node_tree **head, node_tree *new_node)
node_tree * pop_tree_free_list (node_tree **head)
void init_tree_free_list ()
void insert (node_tree **tree, int val)
void print_preorder (node_tree *root)
void print_inorder (node_tree *root)
void print_postorder (node_tree *root)
void deltree (node_tree *root)
node_tree * __attribute__ ((noinline))
int main ()
Variables
static node_stack StaticPoolStack [MAX_NUMBER_OF_NODES]
static node_stack * head_stack_free_list
static node_tree StaticPoolTree [MAX_NUMBER_OF_NODES]
static node_tree * head_tree_free_list
Macro Definition Documentation
MAX_NUMBER_OF_NODES
#define MAX_NUMBER_OF_NODES 255
Definition at line 11 of file module.c.
Referenced by init_stack_free_list(), and init_tree_free_list().
Typedef Documentation
node_stack
typedef struct stack node_stack
Definition at line 20 of file module.c.
node_tree
typedef struct bin_tree node_tree
Definition at line 89 of file module.c.
Function Documentation
__attribute__()
node_tree* __attribute__ ((noinline))
Definition at line 251 of file module.c.
References bin_tree::data, bin_tree::left, and bin_tree::right.
deltree()
void deltree (node_tree * root)
Definition at line 224 of file module.c.
References isEmpty(), bin_tree::left, pop(), push(), push_tree_free_list(), bin_tree::right, and top().
init_stack_free_list()
void init_stack_free_list ()
Definition at line 46 of file module.c.
References index, MAX_NUMBER_OF_NODES, and push_stack_free_list().
init_tree_free_list()
void init_tree_free_list ()
Definition at line 116 of file module.c.
References index, MAX_NUMBER_OF_NODES, and push_tree_free_list().
insert()
void insert (node_tree ** tree, int val)
Definition at line 125 of file module.c.
References bin_tree::data, insert(), bin_tree::left, pop_tree_free_list(), and bin_tree::right.
isEmpty()
_Bool isEmpty (node_stack * head)
Definition at line 62 of file module.c.
main()
int main ()
Definition at line 262 of file module.c.
References bin_tree::data, deltree(), init_stack_free_list(), init_tree_free_list(), insert(), print_inorder(), print_postorder(), and print_preorder().
pop()
void* pop (node_stack ** head)
Definition at line 66 of file module.c.
References stack::data, isEmpty(), stack::next, push_stack_free_list(), and top().
pop_stack_free_list()
node_stack* pop_stack_free_list (node_stack ** head)
Definition at line 32 of file module.c.
References stack::next.
pop_tree_free_list()
node_tree* pop_tree_free_list (node_tree ** head)
Definition at line 102 of file module.c.
References bin_tree::left.
print_inorder()
void print_inorder (node_tree * root)
Definition at line 169 of file module.c.
References bin_tree::data, isEmpty(), bin_tree::left, pop(), push(), and bin_tree::right.
print_postorder()
void print_postorder (node_tree * root)
Definition at line 197 of file module.c.
References bin_tree::data, isEmpty(), bin_tree::left, pop(), push(), bin_tree::right, and top().
print_preorder()
void print_preorder (node_tree * root)
Definition at line 147 of file module.c.
References bin_tree::data, isEmpty(), bin_tree::left, pop(), push(), and bin_tree::right.
push()
void push (node_stack ** head, void * t)
Definition at line 54 of file module.c.
References stack::data, stack::next, and pop_stack_free_list().
push_stack_free_list()
void push_stack_free_list (node_stack ** head, node_stack * new_node)
Definition at line 26 of file module.c.
References stack::data, and stack::next.
push_tree_free_list()
void push_tree_free_list (node_tree ** head, node_tree * new_node)
Definition at line 95 of file module.c.
References bin_tree::data, bin_tree::left, and bin_tree::right.
top()
void* top (node_stack * head)
Definition at line 79 of file module.c.
References stack::data, bin_tree::left, and bin_tree::right.
Variable Documentation
head_stack_free_list
node_stack* head_stack_free_list [static]
Definition at line 24 of file module.c.
head_tree_free_list
node_tree* head_tree_free_list [static]
Definition at line 93 of file module.c.
StaticPoolStack
node_stack StaticPoolStack[MAX_NUMBER_OF_NODES] [static]
Definition at line 23 of file module.c.
StaticPoolTree
node_tree StaticPoolTree[MAX_NUMBER_OF_NODES] [static]
Definition at line 92 of file module.c.