BambuFrontendFlow Class Reference
#include <bambu_frontend_flow.hpp>
Public Member Functions
BambuFrontendFlow (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~BambuFrontendFlow () override
Destructor.
DesignFlowStep_Status Exec () override
Execute this step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 48 of file bambu_frontend_flow.hpp.
Constructor & Destructor Documentation
BambuFrontendFlow()
BambuFrontendFlow::BambuFrontendFlow (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
STL include.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 69 of file bambu_frontend_flow.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~BambuFrontendFlow().
 BambuFrontendFlow()
BambuFrontendFlow::~BambuFrontendFlow () [override], [default]
Destructor.
Referenced by BambuFrontendFlow().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BambuFrontendFlow::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 76 of file bambu_frontend_flow.cpp.
References ADD_OP_EXIT_FLOW_EDGES, AGGREGATE_DATA_FLOW_ANALYSIS, BLOCK_FIX, CALL_EXPR_FIX, CHECK_SYSTEM_TYPE, COMPLETE_CALL_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, INFERRED_INTERFACE_GENERATION, DesignFlowStep::INVALIDATION_RELATIONSHIP, OP_CONTROL_DEPENDENCE_COMPUTATION, DesignFlowStep::parameters, PARM2SSA, PM_NONE, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SCALAR_SSA_DATA_FLOW_ANALYSIS, STRING_CST_FIX, SWITCH_FIX, THROW_UNREACHABLE, VHDL, and FrontendFlowStep::WHOLE_APPLICATION.
ComputeRelationships()
void BambuFrontendFlow::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 229 of file bambu_frontend_flow.cpp.
References FrontendFlowStep::AppM, FrontendFlowStep::ComputeRelationships(), FunctionFrontendFlowStep::ComputeSignature(), FrontendFlowStepFactory::CreateFunctionFrontendFlowStep(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, Wrefcount< T >::lock(), and DesignFlowStep::parameters.
Exec()
DesignFlowStep_Status BambuFrontendFlow::Exec () [override], [virtual]
Execute this step.
Returns
the exit status of this step
Implements ApplicationFrontendFlowStep.
Definition at line 213 of file bambu_frontend_flow.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, EMPTY, and DesignFlowStep::parameters.
HasToBeExecuted()
bool BambuFrontendFlow::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from ApplicationFrontendFlowStep.
Definition at line 224 of file bambu_frontend_flow.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/bambu_frontend_flow.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/bambu_frontend_flow.cpp