mux_connection_binding Class Reference
Class managing the connection binding of datapath.
#include <mux_connection_binding.hpp>
Public Member Functions
mux_connection_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Main constructor.
~mux_connection_binding () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
void create_connections ()
Creates the connections inside the architecture.
unsigned int swap_p (const OpGraphConstRef data, vertex op, unsigned int num, std::vector< HLS_manager::io_binding_type > &vars_read, const BehavioralHelperConstRef behavioral_helper, const tree_managerRef TreeM)
check if the port has to be swapped
Private Types
enum cacheType { i_assign = 0,
iu_conv,
ui_conv,
vb_assign
 }
cache connection type
typedef std::pair< unsigned int, unsigned int > resource_id_type
type representing a resource identifier
Private Member Functions
unsigned int mux_interconnection ()
Performs specialization of interconnections using mux architecture.
unsigned int input_logic (const conn_binding::ConnectionSources &src, const generic_objRef tgt, unsigned int op, unsigned int port_index, unsigned int iteration)
Computes logic for inputs.
void determine_connection (const vertex &op, const HLS_manager::io_binding_type &var, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, const OpGraphConstRef data, unsigned int precision, unsigned int alignment=0)
Determine the actual interconnection.
unsigned int object_bitsize (const tree_managerRef TreeM, const HLS_manager::io_binding_type &obj) const
Compute the bitsize given a io_binding type.
generic_objRef dynamic_multidimensional_array_handler (array_ref *ar, const vertex &op, const OpGraphConstRef data, unsigned int &base_address_index_pointer, std::vector< unsigned int > &recursive_indexes_values, std::vector< unsigned int > &dims, generic_objRef &global_adder, const bool is_not_a_phi)
Recursive function which returns the offset of a dynamic multidimensional array call.
void connect_array_index (unsigned int tree_index, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, unsigned int bus_addr_bitsize, const OpGraphConstRef data, const vertex &op)
connect_array_index: connect the index port of an array_ref and convert it in case the source is of int type
void create_single_conn (const OpGraphConstRef data, const vertex &op, generic_objRef fu_obj_src, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, unsigned int tree_var, unsigned int precision, const bool is_not_a_phi)
create the connection object and update the unique table
void connect_to_registers (vertex op, const OpGraphConstRef data, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, unsigned int tree_var, unsigned int precision, const bool is_not_a_phi)
connect the fu_obj with the associated registers.
unsigned int extract_parm_decl (unsigned int tree_var, const tree_managerRef TreeM)
void add_conversion (unsigned int num, unsigned int size_tree_var, VertexIterator op, unsigned int form_par_type, unsigned int port_index, const generic_objRef fu_obj, const OpGraphConstRef data, const tree_managerRef TreeM, unsigned int tree_var, std::vector< HLS_manager::io_binding_type > &var_read, unsigned int size_form_par)
unsigned int address_precision (unsigned int precision, const vertex &op, const OpGraphConstRef data, const tree_managerRef TreeM)
bool isZeroObj (unsigned int tree_index, const tree_managerRef TreeM)
bool isConstantObj (unsigned int tree_index, const tree_managerRef TreeM)
Private Attributes
std::map< resource_id_type, std::map< unsigned int, CustomOrderedSet< unsigned int > > > regs_in
store the registers for each resource and for each port
std::map< resource_id_type, std::map< unsigned int, CustomOrderedSet< unsigned int > > > chained_in
store the chained storage values for each resource and for each port
std::map< resource_id_type, std::map< unsigned int, CustomOrderedSet< resource_id_type > > > module_in
store the resource in IN for each resource and for each port
CustomOrderedSet< vertex > swap_computed_table
store the operations for which a port swapping is beneficial
CustomOrderedSet< vertex > noswap_computed_table
store the operations for which a port swapping is not beneficial
unsigned int id
variable used to assign a unique id to sparse logic
unsigned int cur_phi_tree_var
store the current phi use. Used during the analysis of phi nodes
bool is_PC
std::map< std::tuple< unsigned int, cacheType, const HLS_manager::io_binding_type >, generic_objRef > connCache
connection cache
Additional Inherited Members
Detailed Description
Class managing the connection binding of datapath.
It extends the standard mux_connection_binding class.
This class provides methods to compute interconnections among datapath elements (functional units, registers, ports). Different architectural style have been implemented: mux-based or bus-based. They are implemented as specialization of generic interconnections.
Definition at line 69 of file mux_connection_binding.hpp.
Member Typedef Documentation
resource_id_type
typedef std::pair<unsigned int, unsigned int> mux_connection_binding::resource_id_type [private]
type representing a resource identifier
Definition at line 73 of file mux_connection_binding.hpp.
Member Enumeration Documentation
cacheType
enum mux_connection_binding::cacheType [private]
cache connection type
Enumerator
i_assign
iu_conv
ui_conv
vb_assign
Definition at line 97 of file mux_connection_binding.hpp.
Constructor & Destructor Documentation
mux_connection_binding()
mux_connection_binding::mux_connection_binding (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Main constructor.
Parameters
design_flow_manager is the design flow manager
Definition at line 138 of file mux_connection_binding.cpp.
References DesignFlowStep::debug_level, GET_CLASS, MUX_INTERCONNECTION_BINDING, and ~mux_connection_binding().
 mux_connection_binding()
mux_connection_binding::~mux_connection_binding () [override], [default]
Destructor.
Referenced by mux_connection_binding().
Member Function Documentation
add_conversion()
void mux_connection_binding::add_conversion (unsigned int num, unsigned int size_tree_var, VertexIterator op, unsigned int form_par_type, unsigned int port_index, const generic_objRef fu_obj, const OpGraphConstRef data, const tree_managerRef TreeM, unsigned int tree_var, std::vector< HLS_manager::io_binding_type > & var_read, unsigned int size_form_par) [private]
Definition at line 1590 of file mux_connection_binding.cpp.
References conn_binding::add_component(), conn_binding::add_sparse_logic(), connCache, create_single_conn(), determine_connection(), AllocationInformation::extract_bambu_provided_name(), FFDATA_CONVERTER_STD, HLSFunctionStep::HLS, HLS_step::HLSMgr, tree_helper::is_bool(), tree_helper::is_int(), tree_helper::is_unsigned(), isConstantObj(), isZeroObj(), iu_conv, IUDATA_CONVERTER_STD, object_bitsize(), DesignFlowStep::parameters, hls::Rconn, STR, ui_conv, and UIDATA_CONVERTER_STD.
Referenced by create_connections().
address_precision()
unsigned int mux_connection_binding::address_precision (unsigned int precision, const vertex & op, const OpGraphConstRef data, const tree_managerRef TreeM) [private]
Definition at line 359 of file mux_connection_binding.cpp.
References hls::allocation_information, OpGraph::CGetOpNodeInfo(), hls::functionId, fu_binding::get_assign(), AllocationInformation::get_memory_var(), GET_NODE, AllocationInformation::get_proxy_memory_var(), tree_manager::get_tree_node_const(), GET_TYPE, HLSFunctionStep::HLS, HLS_step::HLSMgr, AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_memory_unit(), hls::Rfu, tree_helper::size(), TYPE_LOAD, and TYPE_STORE.
Referenced by determine_connection(), and dynamic_multidimensional_array_handler().
connect_array_index()
void mux_connection_binding::connect_array_index (unsigned int tree_index, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, unsigned int bus_addr_bitsize, const OpGraphConstRef data, const vertex & op) [private]
connect_array_index: connect the index port of an array_ref and convert it in case the source is of int type
Definition at line 3236 of file mux_connection_binding.cpp.
References conn_binding::add_component(), conn_binding::add_sparse_logic(), connCache, create_single_conn(), determine_connection(), HLSFunctionStep::HLS, HLS_step::HLSMgr, tree_helper::is_int(), isConstantObj(), isZeroObj(), iu_conv, IUDATA_CONVERTER_STD, hls::Rconn, and STR.
Referenced by determine_connection(), and dynamic_multidimensional_array_handler().
connect_to_registers()
void mux_connection_binding::connect_to_registers (vertex op, const OpGraphConstRef data, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, unsigned int tree_var, unsigned int precision, const bool is_not_a_phi) [private]
connect the fu_obj with the associated registers.
Definition at line 1334 of file mux_connection_binding.cpp.
References conn_binding::add_data_transfer(), OpGraph::CGetOpNodeInfo(), cur_phi_tree_var, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, extract_parm_decl(), HLSFunctionStep::funId, reg_binding::get(), fu_binding::get(), GET_NAME, liveness::get_name(), liveness::get_op_where_defined(), reg_binding::get_register(), liveness::get_state_in(), liveness::get_state_where_end(), liveness::get_state_where_run(), StorageValueInformation::get_storage_value_index(), generic_obj::get_string(), tree_manager::get_tree_node_const(), GET_TYPE, StateTransitionGraphManager::GetStg(), liveness::has_state_in(), HLSFunctionStep::HLS, HLS_step::HLSMgr, conn_binding_creator::input_ports, StorageValueInformation::is_a_storage_value(), tree_helper::is_parameter(), is_PC, NULL_VERTEX, PRINT_DBG_MEX, hls::Rconn, hls::Rfu, hls::Rliv, hls::Rreg, hls::STG, hls::storage_value_information, STR, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, and TYPE_PHI.
Referenced by determine_connection().
create_connections()
void mux_connection_binding::create_connections ()
Creates the connections inside the architecture.
add the ports representing the parameters
check for required and produced values
virtual phis are skipped
phis are skipped
adding activation's state of selector related to operation op
MEMORY REFERENCES
bitfield management
phi must be differently managed
if the variable does not belong to the live-out set, it means that it is used inside the state (chaining) and this situation is managed above
Definition at line 1660 of file mux_connection_binding.cpp.
References conn_binding::add_component(), add_conversion(), conn_binding::add_data_transfer(), conn_binding_creator::add_parameter_ports(), conn_binding::add_sparse_logic(), hls::allocation_information, test_panda::arg, test_panda::args, ASSIGN_REAL_STD, ASSIGN_SIGNED_STD, ASSIGN_UNSIGNED_STD, ASSIGN_VECTOR_BOOL_STD, conn_binding::bind_command_port(), conn_binding::bind_selector_port(), CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), commandport_obj::CONDITION, connCache, conn_binding::create_conn_binding(), create_single_conn(), cur_phi_tree_var, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, determine_connection(), FunctionBehavior::FDFG, hls::functionId, HLSFunctionStep::funId, reg_binding::get(), fu_binding::get(), fu_binding::get_allocation_list(), fu_binding::get_assign(), tree_helper::get_formal_ith(), AllocationInformation::get_fu(), AllocationInformation::get_fu_name(), fu_binding::get_index(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), liveness::get_live_in(), GET_NAME, liveness::get_name(), GET_NODE, fu_binding::get_number(), AllocationInformation::get_number_channels(), liveness::get_op_where_defined(), fu_binding::get_ports_are_swapped(), reg_binding::get_register(), liveness::get_state_in(), liveness::get_state_out(), liveness::get_state_where_end(), liveness::get_state_where_run(), StorageValueInformation::get_storage_value_index(), generic_obj::get_string(), AllocationInformation::get_string_name(), liveness::get_support(), tree_manager::get_tree_node_const(), GET_TYPE, tree_helper::get_type_index(), tree_helper::get_type_node(), reg_binding::get_used_regs(), StateTransitionGraphManager::GetStg(), liveness::has_state_in(), liveness::has_state_out(), HLSFunctionStep::HLS, HLS_step::HLSMgr, i_assign, conn_binding::IN, INDENT_DBG_MEX, tree_helper::is_a_pointer(), StorageValueInformation::is_a_storage_value(), tree_helper::is_bool(), AllocationInformation::is_direct_access_memory_unit(), AllocationInformation::is_indirect_access_memory_unit(), tree_helper::is_int(), is_PC, tree_helper::is_real(), tree_helper::is_unsigned(), isConstantObj(), isZeroObj(), iu_conv, IUDATA_CONVERTER_STD, MEMCPY, MEMSET, MULTI_READ_COND, commandport_obj::MULTIIF, NULL_VERTEX, object_bitsize(), commandport_obj::OPERATION, conn_binding::OUT, DesignFlowStep::parameters, PRINT_DBG_MEX, tree_helper::print_function_name(), BehavioralHelper::PrintVariable(), hls::Rconn, hls::Rfu, hls::Rliv, hls::Rreg, commandport_obj::SELECTOR, tree_helper::size(), hls::STG, hls::storage_value_information, STR, commandport_obj::SWITCH, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, ToString(), test_panda::type, TYPE_IF, TYPE_LOAD, TYPE_MULTIIF, TYPE_PHI, TYPE_STORE, TYPE_SWITCH, TYPE_VPHI, vb_assign, and commandport_obj::WRENABLE.
Referenced by InternalExec().
create_single_conn()
void mux_connection_binding::create_single_conn (const OpGraphConstRef data, const vertex & op, generic_objRef fu_obj_src, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, unsigned int tree_var, unsigned int precision, const bool is_not_a_phi) [private]
create the connection object and update the unique table
instead of tree_var we use cur_phi_tree_var when we look into the state in data structure since tree_var can be modified in the mean time
Definition at line 299 of file mux_connection_binding.cpp.
References conn_binding::add_data_transfer(), OpGraph::CGetOpNodeInfo(), cur_phi_tree_var, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, HLSFunctionStep::funId, liveness::get_name(), liveness::get_state_in(), liveness::get_state_where_run(), generic_obj::get_string(), tree_manager::get_tree_node_const(), StateTransitionGraphManager::GetStg(), liveness::has_state_in(), HLSFunctionStep::HLS, HLS_step::HLSMgr, is_PC, NULL_VERTEX, PRINT_DBG_MEX, hls::Rconn, hls::Rliv, hls::STG, STR, and THROW_ASSERT.
Referenced by add_conversion(), connect_array_index(), create_connections(), determine_connection(), and dynamic_multidimensional_array_handler().
determine_connection()
void mux_connection_binding::determine_connection (const vertex & op, const HLS_manager::io_binding_type & var, generic_objRef fu_obj, unsigned int port_num, unsigned int port_index, const OpGraphConstRef data, unsigned int precision, unsigned int alignment = 0) [private]
Determine the actual interconnection.
dynamic multidimensional array case
symbol_index + base_index + idx_index * step_index + offset_index
idx2_index + base_index + idx_index * step_index + offset_index
the first element of a complex object is the realpart so we just need the base_address
else a direct connection is considered since adresses are passed
else a direct connection is considered
check bitsize
create connection with the constant
Definition at line 408 of file mux_connection_binding.cpp.
References conn_binding::add_component(), conn_binding::add_sparse_logic(), address_precision(), align_to_trimmed_bits(), BITFIELD_EC, CASE_CPP_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_TYPE_NODES, FunctionBehavior::CGetBehavioralHelper(), OpGraph::CGetOpNodeInfo(), connect_array_index(), connect_to_registers(), convert_to_binary(), create_single_conn(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, dynamic_multidimensional_array_handler(), hls::functionId, HLSFunctionStep::funId, tree_helper::get_base_index(), conn_binding::get_constant_obj(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, tree_manager::get_tree_node_const(), GET_TYPE, tree_helper::get_type_index(), tree_helper::get_type_node(), HLSFunctionStep::HLS, HLS_step::HLSMgr, BehavioralHelper::is_a_constant(), FunctionBehavior::is_variable_mem(), min, PRINT_DBG_MEX, BehavioralHelper::PrintVariable(), hls::Rconn, resize_to_1_8_16_32_64_128_256_512(), tree_helper::size(), STR, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, test_panda::type, TYPE_PHI, UI_ADDER_STD, UI_ALIGN_ADDER_STD, UI_CONST_MULTIPLIER_STD, and UI_MULTIPLIER_STD.
Referenced by add_conversion(), connect_array_index(), create_connections(), and dynamic_multidimensional_array_handler().
dynamic_multidimensional_array_handler()
generic_objRef mux_connection_binding::dynamic_multidimensional_array_handler (array_ref * ar, const vertex & op, const OpGraphConstRef data, unsigned int & base_address_index_pointer, std::vector< unsigned int > & recursive_indexes_values, std::vector< unsigned int > & dims, generic_objRef & global_adder, const bool is_not_a_phi) [private]
Recursive function which returns the offset of a dynamic multidimensional array call.
generates needed components
updates indexes array and calls recursive function
starts to create basic components directly linked to the offset calculator
Definition at line 191 of file mux_connection_binding.cpp.
References conn_binding::add_component(), conn_binding::add_sparse_logic(), address_precision(), connect_array_index(), create_single_conn(), determine_connection(), tree_helper::get_array_dimensions(), GET_INDEX_NODE, GET_NODE, tree_helper::get_type_node(), HLSFunctionStep::HLS, HLS_step::HLSMgr, hls::Rconn, STR, THROW_ERROR, UI_ADDER_STD, and UI_CONST_MULTIPLIER_STD.
Referenced by determine_connection().
extract_parm_decl()
unsigned int mux_connection_binding::extract_parm_decl (unsigned int tree_var, const tree_managerRef TreeM) [private]
Definition at line 1320 of file mux_connection_binding.cpp.
References GET_INDEX_NODE, and tree_manager::get_tree_node_const().
Referenced by connect_to_registers().
Initialize()
void mux_connection_binding::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 146 of file mux_connection_binding.cpp.
References chained_in, hls::controller_type, cur_phi_tree_var, HLSFunctionStep::HLS, HLSFunctionStep::Initialize(), is_PC, module_in, noswap_computed_table, hls::Rconn, regs_in, and swap_computed_table.
input_logic()
unsigned int mux_connection_binding::input_logic (const conn_binding::ConnectionSources & src, const generic_objRef tgt, unsigned int op, unsigned int port_index, unsigned int iteration) [private]
Computes logic for inputs.
The connection can become directed or by multiplexer. If multiplexers are allocated, then decoding logic is created.
Parameters
src is the set of references to generic_obj, sources of connections
tgt is the reference to connection target
op is i-th operand of target element, where source is attached
port_index is the i-th port index of the given target port.
Returns
number of multiplexer allocated
if it's a one-to-one connection, a directed link can be used
map between the source object and the resulting tree of multiplexers to the current target object
map between a data_transfer and object associated at the moment
map between a generic_obj and list of data_transfer associated with this object
map between a data_transfer and original source object
all the inputs are connected with 2:1 multiplexers. Two inputs are taken at each time.
stuff for the first input
stuff for the second input
specialize connections between sources and target
Definition at line 2720 of file mux_connection_binding.cpp.
References conn_binding::add_component(), conn_binding::add_connection(), conn_binding::bind_selector_port(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, F_COND, HLSFunctionStep::funId, liveness::get_name(), generic_obj::get_string(), HLSFunctionStep::HLS, HLS_step::HLSMgr, conn_binding::IN, INFINITE_UINT, test_panda::level, MUX_GATE_STD, PRINT_DBG_MEX, hls::Rconn, generic_obj::REGISTER, hls::Rliv, commandport_obj::SELECTOR, STR, T_COND, THROW_ASSERT, and THROW_ERROR.
Referenced by mux_interconnection().
InternalExec()
DesignFlowStep_Status mux_connection_binding::InternalExec () [override], [virtual]
Execute the step.
This function is the public one to execute connection binding.
Returns
the exit status of this step
First it computes virtual connection to be implemented and then it allocates them based on chosen architecture
Implements HLSFunctionStep.
Definition at line 164 of file mux_connection_binding.cpp.
References connCache, create_connections(), conn_binding::determine_bit_level_mux(), HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_OUT_MEX, mux_interconnection(), DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, conn_binding::print(), print_cpu_time(), hls::Rconn, START_TIME, STOP_TIME, STR, and SUCCESS.
isConstantObj()
bool mux_connection_binding::isConstantObj (unsigned int tree_index, const tree_managerRef TreeM) [private]
Definition at line 397 of file mux_connection_binding.cpp.
References tree_manager::get_tree_node_const().
Referenced by add_conversion(), connect_array_index(), and create_connections().
isZeroObj()
bool mux_connection_binding::isZeroObj (unsigned int tree_index, const tree_managerRef TreeM) [private]
Definition at line 384 of file mux_connection_binding.cpp.
References tree_helper::get_integer_cst_value(), and tree_manager::get_tree_node_const().
Referenced by add_conversion(), connect_array_index(), and create_connections().
mux_interconnection()
unsigned int mux_connection_binding::mux_interconnection () [private]
Performs specialization of interconnections using mux architecture.
Definition at line 2698 of file mux_connection_binding.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, conn_binding::get_data_transfers(), generic_obj::get_string(), HLSFunctionStep::HLS, input_logic(), PRINT_DBG_MEX, and hls::Rconn.
Referenced by InternalExec().
object_bitsize()
unsigned int mux_connection_binding::object_bitsize (const tree_managerRef TreeM, const HLS_manager::io_binding_type & obj) const [private]
Compute the bitsize given a io_binding type.
Definition at line 2864 of file mux_connection_binding.cpp.
References tree_helper::get_type_index(), HLS_step::HLSMgr, tree_helper::is_a_struct(), tree_helper::is_an_array(), tree_helper::is_an_union(), and tree_helper::size().
Referenced by add_conversion(), and create_connections().
swap_p()
unsigned int mux_connection_binding::swap_p (const OpGraphConstRef data, vertex op, unsigned int num, std::vector< HLS_manager::io_binding_type > & vars_read, const BehavioralHelperConstRef behavioral_helper, const tree_managerRef TreeM)
check if the port has to be swapped
it is not chained but from the mux binding it counts as input to the mux tree
Definition at line 2892 of file mux_connection_binding.cpp.
References OpGraph::CGetOpNodeInfo(), chained_in, fu_binding::get_assign(), fu_binding::get_index(), liveness::get_op_where_defined(), reg_binding::get_register(), liveness::get_state_where_end(), liveness::get_state_where_run(), StorageValueInformation::get_storage_value_index(), GET_TYPE, liveness::has_op_where_defined(), HLSFunctionStep::HLS, INFINITE_UINT, insert(), BehavioralHelper::is_a_constant(), StorageValueInformation::is_a_storage_value(), tree_helper::is_parameter(), module_in, noswap_computed_table, regs_in, hls::Rfu, hls::Rliv, hls::Rreg, STOK, hls::storage_value_information, swap_computed_table, TOK_BIT_AND_EXPR, TOK_BIT_IOR_EXPR, TOK_BIT_XOR_EXPR, TOK_EQ_EXPR, TOK_MULT_EXPR, TOK_NE_EXPR, TOK_PLUS_EXPR, TOK_POINTER_PLUS_EXPR, TOK_WIDEN_MULT_EXPR, TOK_WIDEN_SUM_EXPR, and TYPE_PHI.
Field Documentation
chained_in
std::map<resource_id_type, std::map<unsigned int, CustomOrderedSet<unsigned int> > > mux_connection_binding::chained_in [private]
store the chained storage values for each resource and for each port
Definition at line 78 of file mux_connection_binding.hpp.
Referenced by Initialize(), and swap_p().
connCache
std::map<std::tuple<unsigned int, cacheType, const HLS_manager::io_binding_type>, generic_objRef> mux_connection_binding::connCache [private]
connection cache
Definition at line 105 of file mux_connection_binding.hpp.
Referenced by add_conversion(), connect_array_index(), create_connections(), and InternalExec().
cur_phi_tree_var
unsigned int mux_connection_binding::cur_phi_tree_var [private]
store the current phi use. Used during the analysis of phi nodes
Definition at line 92 of file mux_connection_binding.hpp.
Referenced by connect_to_registers(), create_connections(), create_single_conn(), and Initialize().
id
unsigned int mux_connection_binding::id [private]
variable used to assign a unique id to sparse logic
Definition at line 89 of file mux_connection_binding.hpp.
is_PC
bool mux_connection_binding::is_PC [private]
Definition at line 94 of file mux_connection_binding.hpp.
Referenced by connect_to_registers(), create_connections(), create_single_conn(), and Initialize().
module_in
std::map<resource_id_type, std::map<unsigned int, CustomOrderedSet<resource_id_type> > > mux_connection_binding::module_in [private]
store the resource in IN for each resource and for each port
Definition at line 80 of file mux_connection_binding.hpp.
Referenced by Initialize(), and swap_p().
noswap_computed_table
CustomOrderedSet<vertex> mux_connection_binding::noswap_computed_table [private]
store the operations for which a port swapping is not beneficial
Definition at line 86 of file mux_connection_binding.hpp.
Referenced by Initialize(), and swap_p().
regs_in
std::map<resource_id_type, std::map<unsigned int, CustomOrderedSet<unsigned int> > > mux_connection_binding::regs_in [private]
store the registers for each resource and for each port
Definition at line 76 of file mux_connection_binding.hpp.
Referenced by Initialize(), and swap_p().
swap_computed_table
CustomOrderedSet<vertex> mux_connection_binding::swap_computed_table [private]
store the operations for which a port swapping is beneficial
Definition at line 83 of file mux_connection_binding.hpp.
Referenced by Initialize(), and swap_p().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/mux_connection_binding.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/interconnection/mux_connection_binding.cpp