DesignFlow Class Reference
#include <design_flow.hpp>
Public Member Functions
DesignFlow (const DesignFlowManagerConstRef design_flow_manager, const DesignFlow_Type design_flow_type, const ParameterConstRef parameters)
Constructor.
~DesignFlow () override
Destructor.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
const std::string GetSignature () const override
Return the signature of this step.
const std::string GetName () const override
Return the name of this design step.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Static Public Member Functions
static std::string ComputeSignature (const DesignFlow_Type design_flow_type)
Compute the signature of a step.
static const std::string EnumToKindText (const DesignFlow_Type design_flow_type)
Return the name of the type.
static DesignFlow_Type KindTextToEnum (const std::string &name)
Given the name of design flow, return the enum.
Protected Attributes
const DesignFlow_Type design_flow_type
The type of this design flow.
Additional Inherited Members
Detailed Description
Definition at line 52 of file design_flow.hpp.
Constructor & Destructor Documentation
DesignFlow()
DesignFlow::DesignFlow (const DesignFlowManagerConstRef design_flow_manager, const DesignFlow_Type design_flow_type, const ParameterConstRef parameters)
Constructor.
Parameters
design_flow_manager is the design flow manager
design_flow_type is the type of the flow
parameters is the set of the parameters
Definition at line 46 of file design_flow.cpp.
References ~DesignFlow().
 DesignFlow()
DesignFlow::~DesignFlow () [override], [default]
Destructor.
Referenced by DesignFlow().
Member Function Documentation
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef DesignFlow::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Returns
the factory to create frontend flow step
Implements DesignFlowStep.
Definition at line 79 of file design_flow.cpp.
References DesignFlowStep::design_flow_manager, and Wrefcount< T >::lock().
ComputeRelationships()
void DesignFlow::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
relationship is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 52 of file design_flow.cpp.
ComputeSignature()
std::string DesignFlow::ComputeSignature (const DesignFlow_Type design_flow_type) [static]
Compute the signature of a step.
Parameters
design_flow_type is the type of design flow
Returns
the signature corresponding to the design flow
Definition at line 102 of file design_flow.cpp.
References STR.
Referenced by GetSignature().
EnumToKindText()
const std::string DesignFlow::EnumToKindText (const DesignFlow_Type design_flow_type) [static]
Return the name of the type.
Parameters
design_flow_type is the type of the design flow
Returns
the name
Definition at line 66 of file design_flow.cpp.
References NON_DETERMINISTIC_FLOWS, and THROW_UNREACHABLE.
Referenced by GetName().
GetName()
const std::string DesignFlow::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 61 of file design_flow.cpp.
References design_flow_type, and EnumToKindText().
GetSignature()
const std::string DesignFlow::GetSignature () const [override], [virtual]
Return the signature of this step.
Implements DesignFlowStep.
Definition at line 56 of file design_flow.cpp.
References ComputeSignature(), and design_flow_type.
HasToBeExecuted()
bool DesignFlow::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 97 of file design_flow.cpp.
KindTextToEnum()
DesignFlow_Type DesignFlow::KindTextToEnum (const std::string & name) [static]
Given the name of design flow, return the enum.
Parameters
name is the name of the design flow
Returns
the corresponding enum
Definition at line 84 of file design_flow.cpp.
References NON_DETERMINISTIC_FLOWS, and THROW_UNREACHABLE.
Referenced by DesignFlowFactory::CreateFlowStep().
Field Documentation
design_flow_type
const DesignFlow_Type DesignFlow::design_flow_type [protected]
The type of this design flow.
Definition at line 56 of file design_flow.hpp.
Referenced by GetName(), and GetSignature().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow.cpp