unique_binding_register Class Reference
#include <unique_binding_register.hpp>
Public Member Functions
unique_binding_register (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor of the class.
~unique_binding_register () override
Destructor of the class.
DesignFlowStep_Status InternalExec () override
Unique binding register allocation algorithm execution.
Additional Inherited Members
Detailed Description
Definition at line 51 of file unique_binding_register.hpp.
Constructor & Destructor Documentation
unique_binding_register()
unique_binding_register::unique_binding_register (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor of the class.
HLS/binding/storage_value_insertion includes.
Parameters
design_flow_manager is the design flow manager
tree include utility include
Definition at line 63 of file unique_binding_register.cpp.
References UNIQUE_REGISTER_BINDING, and ~unique_binding_register().
 unique_binding_register()
unique_binding_register::~unique_binding_register () [override], [default]
Destructor of the class.
Referenced by unique_binding_register().
Member Function Documentation
InternalExec()
DesignFlowStep_Status unique_binding_register::InternalExec () [override], [virtual]
Unique binding register allocation algorithm execution.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 70 of file unique_binding_register.cpp.
References reg_binding::bind(), HLSFunctionStep::funId, liveness::get_live_in(), StorageValueInformation::get_number_of_storage_values(), StorageValueInformation::get_storage_value_index(), liveness::get_support(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_OUT_MEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERY_PEDANTIC, variable2obj< data_obj >::print(), print_cpu_time(), hls::Rliv, hls::Rreg, reg_binding::set_used_regs(), START_TIME, STOP_TIME, hls::storage_value_information, SUCCESS, and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/unique_binding_register.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/unique_binding_register.cpp