handler Struct Reference
A HANDLER wraps a catch handler for the HANDLER_TYPE.
#include <tree_node.hpp>
Public Types
enum { GETID =(tree_node) = 0
 }
visitor enum
Public Member Functions
handler (unsigned int i)
constructor
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
int line
line is the line number where the compound_stmt is defined.
tree_nodeRef body
is the body of the handler
Additional Inherited Members
Detailed Description
A HANDLER wraps a catch handler for the HANDLER_TYPE.
If this is CATCH_ALL_TYPE, then the handler catches all types. The declaration of the catch variable is in HANDLER_PARMS, and the body block in HANDLER_BODY.
Definition at line 3124 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
Definition at line 3150 of file tree_node.hpp.
Constructor & Destructor Documentation
handler()
handler::handler (unsigned int i) [inline], [explicit]
constructor
Definition at line 3127 of file tree_node.hpp.
Member Function Documentation
visit()
void handler::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from tree_node.
Definition at line 818 of file tree_node.cpp.
References tree_manager::add_identifier_node(), ALL_VISIT, identifier_node::identifier_node(), tree_node::tree_node(), gimple_assign::visit(), VISIT_MEMBER, and VISIT_SC.
Field Documentation
body
tree_nodeRef handler::body
is the body of the handler
Definition at line 3135 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
line
int handler::line
line is the line number where the compound_stmt is defined.
Definition at line 3132 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp