ToDataFileStep Class Reference
#include <to_data_file_step.hpp>
Public Member Functions
ToDataFileStep (const DesignFlowManagerConstRef design_flow_manager, const ToDataFileStep_Type to_data_file_step, const ParameterConstRef parameters)
Constructor.
const std::string GetSignature () const override
Return a unified identifier of this design step.
const std::string GetName () const override
Return the name of this design step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override=0
Compute the relationships of a step with other steps.
const DesignFlowStepFactoryConstRef CGetDesignFlowStepFactory () const override
Return the factory to create this type of steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Static Public Member Functions
static const std::string EnumToName (const ToDataFileStep_Type to_data_file_step)
Given a to data file step type, return the name of the type.
static ToDataFileStep_Type NameToEnum (const std::string &to_data_file_step)
Given the name of data file step type, return the enum.
static const std::string ComputeSignature (const ToDataFileStep_Type to_data_file_step_type)
Compute the signature of a to data file step.
Protected Attributes
ToDataFileStep_Type to_data_file_step_type
The type of step.
Additional Inherited Members
Detailed Description
Definition at line 63 of file to_data_file_step.hpp.
Constructor & Destructor Documentation
ToDataFileStep()
ToDataFileStep::ToDataFileStep (const DesignFlowManagerConstRef _design_flow_manager, const ToDataFileStep_Type _to_data_file_step_type, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
to_data_file_step is the type of this step
parameters is the set of input parameters
design_flows include
Definition at line 46 of file to_data_file_step.cpp.
Member Function Documentation
CGetDesignFlowStepFactory()
const DesignFlowStepFactoryConstRef ToDataFileStep::CGetDesignFlowStepFactory () const [override], [virtual]
Return the factory to create this type of steps.
Implements DesignFlowStep.
Definition at line 108 of file to_data_file_step.cpp.
References DesignFlowStep::design_flow_manager, and Wrefcount< T >::lock().
Referenced by GenerateFuList::CGetDesignFlowStepFactory().
ComputeRelationships()
void ToDataFileStep::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [pure virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Implemented in GenerateFuList.
ComputeSignature()
const std::string ToDataFileStep::ComputeSignature (const ToDataFileStep_Type to_data_file_step_type) [static]
Compute the signature of a to data file step.
Parameters
to_data_file_step_type is the type of the step
Returns
the corresponding signature
Definition at line 51 of file to_data_file_step.cpp.
References EnumToName().
Referenced by GetSignature(), and main().
EnumToName()
const std::string ToDataFileStep::EnumToName (const ToDataFileStep_Type to_data_file_step) [static]
Given a to data file step type, return the name of the type.
Parameters
to_data_file_step is the type to be considered
Returns
the name of the type
Definition at line 56 of file to_data_file_step.cpp.
References THROW_UNREACHABLE, and UNKNOWN.
Referenced by ComputeSignature(), and GetName().
GetName()
const std::string ToDataFileStep::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 103 of file to_data_file_step.cpp.
References EnumToName(), and to_data_file_step_type.
Referenced by GenerateFuList::GetName().
GetSignature()
const std::string ToDataFileStep::GetSignature () const [override], [virtual]
Return a unified identifier of this design step.
Returns
the signature of the design step
Implements DesignFlowStep.
Definition at line 98 of file to_data_file_step.cpp.
References ComputeSignature(), and to_data_file_step_type.
Referenced by GenerateFuList::GetSignature().
HasToBeExecuted()
bool ToDataFileStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 93 of file to_data_file_step.cpp.
Referenced by GenerateFuList::HasToBeExecuted().
NameToEnum()
ToDataFileStep_Type ToDataFileStep::NameToEnum (const std::string & to_data_file_step) [static]
Given the name of data file step type, return the enum.
Parameters
to_data_file_step_type is the type to be considered
Returns
the name of the type
Definition at line 77 of file to_data_file_step.cpp.
References THROW_UNREACHABLE, and UNKNOWN.
Referenced by ToDataFileStepFactory::CreateStep().
Field Documentation
to_data_file_step_type
ToDataFileStep_Type ToDataFileStep::to_data_file_step_type [protected]
The type of step.
Definition at line 67 of file to_data_file_step.hpp.
Referenced by GetName(), and GetSignature().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/to_data_file_step.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToDataFile/to_data_file_step.cpp