UnComparisonLowering Class Reference
Superclass include.
#include <un_comparison_lowering.hpp>
Public Member Functions
UnComparisonLowering (const application_managerRef AppM, unsigned int fun_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~UnComparisonLowering () override
Destructor.
DesignFlowStep_Status InternalExec () override
Fixes the var_decl duplication.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Replace uneq_expr, ltgt_expr, unge_expr, ungt_expr, unle_expr and unlt_expr
Definition at line 49 of file un_comparison_lowering.hpp.
Constructor & Destructor Documentation
UnComparisonLowering()
UnComparisonLowering::UnComparisonLowering (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
fun_id is the function index
design_flow_manager is the design flow manager
Param is the set of the parameters
. include behavior include tree includes
Definition at line 61 of file un_comparison_lowering.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and DesignFlowStep::parameters.
 UnComparisonLowering()
UnComparisonLowering::~UnComparisonLowering () [override], [default]
Destructor.
Referenced by ComputeFrontendRelationships().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > UnComparisonLowering::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 66 of file un_comparison_lowering.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, USE_COUNTING, and ~UnComparisonLowering().
InternalExec()
DesignFlowStep_Status UnComparisonLowering::InternalExec () [override], [virtual]
Fixes the var_decl duplication.
Implements FunctionFrontendFlowStep.
Definition at line 95 of file un_comparison_lowering.cpp.
References FrontendFlowStep::AppM, tree_manipulation::create_binary_operation(), tree_manipulation::create_boolean_type(), tree_manipulation::create_unary_operation(), tree_manipulation::CreateGimpleAssign(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::GetTreeNode(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), sl, STR, SUCCESS, THROW_UNREACHABLE, and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/un_comparison_lowering.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/un_comparison_lowering.cpp