discrepancy_instruction_writer Class Reference
#include <discrepancy_instruction_writer.hpp>
Public Member Functions
discrepancy_instruction_writer (const application_managerConstRef app_man, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters)
Constructor.
~discrepancy_instruction_writer () override
Destructor.
void declareFunction (const unsigned int function_id) override
Write the declaration of a function.
Additional Inherited Members
Detailed Description
Definition at line 55 of file discrepancy_instruction_writer.hpp.
Constructor & Destructor Documentation
discrepancy_instruction_writer()
discrepancy_instruction_writer::discrepancy_instruction_writer (const application_managerConstRef _app_man, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
app_man is the application manager
indented_output_stream is the output stream on which source code has to be written
parameters is the set of input parameters
behavior include tree include
Definition at line 57 of file discrepancy_instruction_writer.cpp.
References ~discrepancy_instruction_writer().
 discrepancy_instruction_writer()
discrepancy_instruction_writer::~discrepancy_instruction_writer () [override], [default]
Destructor.
Referenced by discrepancy_instruction_writer().
Member Function Documentation
declareFunction()
void discrepancy_instruction_writer::declareFunction (const unsigned int function_id) [override], [virtual]
Write the declaration of a function.
Parameters
function_id is the index of the function
Reimplemented from InstructionWriter.
Definition at line 64 of file discrepancy_instruction_writer.cpp.
References InstructionWriter::AppM, FunctionBehavior::CGetBehavioralHelper(), HLSInstructionWriter::declareFunction(), BehavioralHelper::get_function_name(), tree_helper::is_extern(), tree_helper::is_static(), and THROW_ASSERT.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/discrepancy_instruction_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/discrepancy_instruction_writer.cpp