ProfilingInformation Class Reference
Definition of the profiling information class.
#include <profiling_information.hpp>
Public Member Functions
ProfilingInformation (const BBGraphConstRef bb_graph)
Constructor.
~ProfilingInformation ()
Destructor.
const PathProfilingInformation & GetPathProfiling () const
Return the path profiling information.
unsigned long long int GetBBExecutions (const vertex basic_block) const
Return the absolute number of executions of a basic block.
unsigned long long int GetEdgeExecutions (const EdgeDescriptor edge) const
Return the absolute number of the executions of an edge.
long double GetLoopAvgIterations (const unsigned int loop_id) const
Return number of average iterations of a loop.
unsigned long long int GetLoopMaxIterations (const unsigned int loop_id) const
Return the maximum number of iterations of a loop.
unsigned long long GetLoopAbsIterations (const unsigned int loop_id) const
Return the number of absolute iterations of a loop.
long double GetLoopAvgIterations (const LoopConstRef loop) const
Return number of average iterations of a loop.
unsigned long long int GetLoopMaxIterations (const LoopConstRef loop) const
Return the maximum number of iterations of a loop.
unsigned long long GetLoopAbsIterations (const LoopConstRef loop) const
Return the number of absolute iterations of a loop.
void WriteToXml (xml_element *root, const BBGraphConstRef fcfg) const
Write to xml.
void Clear ()
Clear.
Private Attributes
PathProfilingInformation path_profiling
map that represents, for each execution path of each loop (represented by the set of the executed control equivalent regions), the execution frequency
BBExecutions bb_executions
Absolute number of execution of each basic block.
BBEdgeExecutions edge_executions
Absolute number of running of edges.
AvgIterations avg_iterations
number of average iterations for one loop execution
Iterations abs_iterations
number of absolute execution (different from number of execution of the header); correspond to how many times a feedback edge of a loop is executed
Iterations max_iterations
Maximum number of iterations.
Friends
class BasicBlocksProfiling
Friend defintion of profiling classes.
class hpp_profiling
class LoopsAnalysisZebu
class LoopsProfiling
class probability_path
class HostProfiling
class read_profiling_data
class tp_profiling
Detailed Description
Definition of the profiling information class.
Definition at line 157 of file profiling_information.hpp.
Constructor & Destructor Documentation
ProfilingInformation()
ProfilingInformation::ProfilingInformation (const BBGraphConstRef bb_graph) [explicit]
Constructor.
Parameters
bb_graph is the basic block graph
Definition at line 78 of file profiling_information.cpp.
References ~ProfilingInformation().
 ProfilingInformation()
ProfilingInformation::~ProfilingInformation () [default]
Destructor.
Referenced by ProfilingInformation().
Member Function Documentation
Clear()
void ProfilingInformation::Clear ()
Clear.
Definition at line 230 of file profiling_information.cpp.
References abs_iterations, avg_iterations, bb_executions, edge_executions, max_iterations, and path_profiling.
GetBBExecutions()
unsigned long long int ProfilingInformation::GetBBExecutions (const vertex basic_block) const
Return the absolute number of executions of a basic block.
Parameters
basic_block is the basic block
Returns
the absolute number of executions of a basic block
Definition at line 89 of file profiling_information.cpp.
References bb_executions.
GetEdgeExecutions()
unsigned long long int ProfilingInformation::GetEdgeExecutions (const EdgeDescriptor edge) const
Return the absolute number of the executions of an edge.
Parameters
edge is the edge
Returns
the absolute number of executions of the edge
Definition at line 96 of file profiling_information.cpp.
References edge_executions.
GetLoopAbsIterations() [1/2]
unsigned long long int ProfilingInformation::GetLoopAbsIterations (const unsigned int loop_id) const
Return the number of absolute iterations of a loop.
Parameters
loop_id is the id of the loop
Returns
the number of average iterations of the loop
Definition at line 117 of file profiling_information.cpp.
References abs_iterations.
Referenced by GetLoopAbsIterations().
GetLoopAbsIterations() [2/2]
unsigned long long ProfilingInformation::GetLoopAbsIterations (const LoopConstRef loop) const
Return the number of absolute iterations of a loop.
Parameters
loop is the loop
Returns
the number of average iterations of the loop
Definition at line 134 of file profiling_information.cpp.
References GetLoopAbsIterations().
GetLoopAvgIterations() [1/2]
long double ProfilingInformation::GetLoopAvgIterations (const unsigned int loop_id) const
Return number of average iterations of a loop.
Parameters
loop_id is the id of the loop
Returns
the number of average iterations of the loop
Definition at line 110 of file profiling_information.cpp.
References avg_iterations.
Referenced by GetLoopAvgIterations().
GetLoopAvgIterations() [2/2]
long double ProfilingInformation::GetLoopAvgIterations (const LoopConstRef loop) const
Return number of average iterations of a loop.
Parameters
loop is the loop
Returns
the number of average iterations of the loop
Definition at line 124 of file profiling_information.cpp.
References GetLoopAvgIterations().
GetLoopMaxIterations() [1/2]
unsigned long long int ProfilingInformation::GetLoopMaxIterations (const unsigned int loop_id) const
Return the maximum number of iterations of a loop.
Parameters
loop_id is the of the loop
Returns
the number of maximum iterations of the loop
Definition at line 103 of file profiling_information.cpp.
References max_iterations.
Referenced by GetLoopMaxIterations().
GetLoopMaxIterations() [2/2]
unsigned long long int ProfilingInformation::GetLoopMaxIterations (const LoopConstRef loop) const
Return the maximum number of iterations of a loop.
Parameters
loop is the loop
Returns
the number of maximum iterations of the loop
Definition at line 129 of file profiling_information.cpp.
References GetLoopMaxIterations().
GetPathProfiling()
const PathProfilingInformation & ProfilingInformation::GetPathProfiling () const
Return the path profiling information.
Returns
the path profiling information
Definition at line 84 of file profiling_information.cpp.
References path_profiling.
WriteToXml()
void ProfilingInformation::WriteToXml (xml_element * root, const BBGraphConstRef fcfg) const
Write to xml.
Parameters
root is the root xml node to which append the information contained in this profiling information
fcfg is the basic block graph of the function
Map used to print profiling information in deterministic order
Map used to print profiling information in deterministic order
Definition at line 139 of file profiling_information.cpp.
References abs_iterations, xml_child::add_child_element(), avg_iterations, bb_executions, BBGraph::CGetBBNodeInfo(), edge_executions, max_iterations, path_profiling, STR_XML_host_profiling_abs_iteration, STR_XML_host_profiling_abs_iterations, STR_XML_host_profiling_avg_iteration, STR_XML_host_profiling_avg_iterations, STR_XML_host_profiling_bb_execution, STR_XML_host_profiling_bb_executions, STR_XML_host_profiling_cers, STR_XML_host_profiling_edge_execution, STR_XML_host_profiling_edge_executions, STR_XML_host_profiling_executions, STR_XML_host_profiling_frequency, STR_XML_host_profiling_id, STR_XML_host_profiling_iterations, STR_XML_host_profiling_max_iteration, STR_XML_host_profiling_max_iterations, STR_XML_host_profiling_path, STR_XML_host_profiling_paths, STR_XML_host_profiling_paths_loop, STR_XML_host_profiling_source_id, STR_XML_host_profiling_target_id, and WRITE_XNVM2.
Friends And Related Function Documentation
BasicBlocksProfiling
friend class BasicBlocksProfiling [friend]
Friend defintion of profiling classes.
Definition at line 161 of file profiling_information.hpp.
HostProfiling
friend class HostProfiling [friend]
Definition at line 166 of file profiling_information.hpp.
hpp_profiling
friend class hpp_profiling [friend]
Definition at line 162 of file profiling_information.hpp.
LoopsAnalysisZebu
friend class LoopsAnalysisZebu [friend]
Definition at line 163 of file profiling_information.hpp.
LoopsProfiling
friend class LoopsProfiling [friend]
Definition at line 164 of file profiling_information.hpp.
probability_path
friend class probability_path [friend]
Definition at line 165 of file profiling_information.hpp.
read_profiling_data
friend class read_profiling_data [friend]
Definition at line 167 of file profiling_information.hpp.
tp_profiling
friend class tp_profiling [friend]
Definition at line 168 of file profiling_information.hpp.
Field Documentation
abs_iterations
Iterations ProfilingInformation::abs_iterations [private]
number of absolute execution (different from number of execution of the header); correspond to how many times a feedback edge of a loop is executed
Definition at line 183 of file profiling_information.hpp.
Referenced by Clear(), GetLoopAbsIterations(), and WriteToXml().
avg_iterations
AvgIterations ProfilingInformation::avg_iterations [private]
number of average iterations for one loop execution
Definition at line 180 of file profiling_information.hpp.
Referenced by Clear(), GetLoopAvgIterations(), and WriteToXml().
bb_executions
BBExecutions ProfilingInformation::bb_executions [private]
Absolute number of execution of each basic block.
Definition at line 174 of file profiling_information.hpp.
Referenced by Clear(), GetBBExecutions(), and WriteToXml().
edge_executions
BBEdgeExecutions ProfilingInformation::edge_executions [private]
Absolute number of running of edges.
Definition at line 177 of file profiling_information.hpp.
Referenced by Clear(), GetEdgeExecutions(), and WriteToXml().
max_iterations
Iterations ProfilingInformation::max_iterations [private]
Maximum number of iterations.
Definition at line 186 of file profiling_information.hpp.
Referenced by Clear(), GetLoopMaxIterations(), and WriteToXml().
path_profiling
PathProfilingInformation ProfilingInformation::path_profiling [private]
map that represents, for each execution path of each loop (represented by the set of the executed control equivalent regions), the execution frequency
Definition at line 171 of file profiling_information.hpp.
Referenced by Clear(), GetPathProfiling(), and WriteToXml().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/profiling_information.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/profiling_information.cpp