mem_xml_allocation Class Reference
#include <mem_xml_allocation.hpp>
Public Member Functions
mem_xml_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~mem_xml_allocation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Private Member Functions
bool parse_xml_allocation (const std::string &xml_file)
Imports the memory configuration from XML file.
void parse_external_allocation (const xml_element *node)
Parses the memory allocation related to external variables.
void parse_internal_allocation (const xml_element *node)
Parses the memory allocation related to internal variables.
void finalize_memory_allocation ()
Performs a final analysis of the memory allocation to finalize the datastructure.
Private Attributes
std::map< unsigned int, memory_symbolRef > ext_variables
map of symbols that are externally allocated
std::map< unsigned int, std::map< unsigned int, memory_symbolRef > > int_variables
map of symbols that are internally allocated
std::map< unsigned int, std::map< unsigned int, memory_symbolRef > > param_variables
map of symbols that refer to parameters
Additional Inherited Members
Detailed Description
Definition at line 51 of file mem_xml_allocation.hpp.
Constructor & Destructor Documentation
mem_xml_allocation()
mem_xml_allocation::mem_xml_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
design_flow_manager is the design flow manager
Definition at line 61 of file mem_xml_allocation.cpp.
References XML_MEMORY_ALLOCATOR, and ~mem_xml_allocation().
 mem_xml_allocation()
mem_xml_allocation::~mem_xml_allocation () [override], [default]
Destructor.
Referenced by mem_xml_allocation().
Member Function Documentation
finalize_memory_allocation()
void mem_xml_allocation::finalize_memory_allocation () [private]
Performs a final analysis of the memory allocation to finalize the datastructure.
Definition at line 247 of file mem_xml_allocation.cpp.
References ext_variables, memory_allocation::finalize_memory_allocation(), HLS_step::HLSMgr, int_variables, and param_variables.
Referenced by parse_xml_allocation().
InternalExec()
DesignFlowStep_Status mem_xml_allocation::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
clean proxy library
Implements memory_allocation.
Definition at line 68 of file mem_xml_allocation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERBOSE, HLS_step::HLSMgr, DesignFlowStep::parameters, parse_xml_allocation(), PRINT_DBG_MEX, PROXY_LIBRARY, SUCCESS, THROW_ERROR, UNCHANGED, and WORK_LIBRARY.
parse_external_allocation()
void mem_xml_allocation::parse_external_allocation (const xml_element * node) [private]
Parses the memory allocation related to external variables.
Definition at line 163 of file mem_xml_allocation.cpp.
References CE_XVM, ext_variables, xml_child::get_children(), get_id(), xml_node::get_name(), LOAD_XVFM, and LOAD_XVM.
Referenced by parse_xml_allocation().
parse_internal_allocation()
void mem_xml_allocation::parse_internal_allocation (const xml_element * node) [private]
Parses the memory allocation related to internal variables.
Definition at line 189 of file mem_xml_allocation.cpp.
References CE_XVM, xml_child::get_children(), get_id(), xml_node::get_name(), int_variables, LOAD_XVFM, LOAD_XVM, param_variables, and THROW_ERROR.
Referenced by parse_xml_allocation().
parse_xml_allocation()
bool mem_xml_allocation::parse_xml_allocation (const std::string & xml_file) [private]
Imports the memory configuration from XML file.
Definition at line 96 of file mem_xml_allocation.cpp.
References memory::create_memory(), XMLDomParser::Exec(), finalize_memory_allocation(), xml_child::get_children(), XMLDomParser::get_document(), xml_node::get_name(), target_device::get_parameter(), target_manager::get_target_device(), HLS_step::HLSMgr, LOAD_XVM, max(), DesignFlowStep::parameters, parse_external_allocation(), parse_internal_allocation(), test_panda::parser, memory_allocation::setup_memory_allocation(), and THROW_ERROR.
Referenced by InternalExec().
Field Documentation
ext_variables
std::map<unsigned int, memory_symbolRef> mem_xml_allocation::ext_variables [private]
map of symbols that are externally allocated
Definition at line 74 of file mem_xml_allocation.hpp.
Referenced by finalize_memory_allocation(), and parse_external_allocation().
int_variables
std::map<unsigned int, std::map<unsigned int, memory_symbolRef> > mem_xml_allocation::int_variables [private]
map of symbols that are internally allocated
Definition at line 77 of file mem_xml_allocation.hpp.
Referenced by finalize_memory_allocation(), and parse_internal_allocation().
param_variables
std::map<unsigned int, std::map<unsigned int, memory_symbolRef> > mem_xml_allocation::param_variables [private]
map of symbols that refer to parameters
Definition at line 80 of file mem_xml_allocation.hpp.
Referenced by finalize_memory_allocation(), and parse_internal_allocation().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/mem_xml_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/memory/mem_xml_allocation.cpp