binfo Struct Reference
This struct specifies the binfo node.
#include <tree_node.hpp>
Public Types
enum { GETID =(tree_node) = 0,
GETID =(tree_node) = 0
 }
visitor enum
Public Member Functions
binfo (unsigned int i)
constructor
tree_nodeRef get_base (size_t i) const
return the i-th element of baseinfo
size_t get_baseinfo_size () const
return the size of baseinfo vector
void add_access_binf (const tree_nodeRef &binf, TreeVocabularyTokenTypes_TokenEnum access)
Add a pair <access, binf> to the list of access binf.
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
tree_nodeRef type
type field is the actual data type node being inherited in this basetype.(BINFO_TYPE)
bool virt_flag
virt_flag is true if the node is a virtual declaration (macro TREE_VIA_VIRTUAL)
int bases
The number of basetypes for NODE.
std::vector< std::pair< TreeVocabularyTokenTypes_TokenEnum, tree_nodeRef > > list_of_access_binf
is the list of pair access binf: baseinfo vector.
Additional Inherited Members
Detailed Description
This struct specifies the binfo node.
The tree walker structure of this node is: #(TOK_BINFO (type)? (TOK_VIRT)? (baseinfo)*
Definition at line 1719 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
GETID
Definition at line 1773 of file tree_node.hpp.
Constructor & Destructor Documentation
binfo()
binfo::binfo (unsigned int i) [inline], [explicit]
constructor
Definition at line 1722 of file tree_node.hpp.
Member Function Documentation
add_access_binf()
void binfo::add_access_binf (const tree_nodeRef & binf, TreeVocabularyTokenTypes_TokenEnum access)
Add a pair <access, binf> to the list of access binf.
Parameters
binf is the binf.
access is a token between PROTECTED, PRIVATE and PUBLIC
Definition at line 457 of file tree_node.cpp.
get_base()
tree_nodeRef binfo::get_base (size_t i) const [inline]
return the i-th element of baseinfo
Parameters
i is the index of baseinfo vector
Definition at line 1742 of file tree_node.hpp.
Referenced by tree_helper::look_for_binfo_inheritance().
get_baseinfo_size()
size_t binfo::get_baseinfo_size () const [inline]
return the size of baseinfo vector
Definition at line 1748 of file tree_node.hpp.
References GET_KIND, and GET_KIND_TEXT.
Referenced by tree_helper::look_for_binfo_inheritance().
visit()
void binfo::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from tree_node.
Definition at line 444 of file tree_node.cpp.
References ALL_VISIT, test_panda::type, type_node::visit(), VISIT_MEMBER, VISIT_MEMBER_NAMED, and VISIT_SC.
Field Documentation
bases
int binfo::bases
The number of basetypes for NODE.
Definition at line 1733 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
list_of_access_binf
std::vector<std::pair<TreeVocabularyTokenTypes_TokenEnum, tree_nodeRef> > binfo::list_of_access_binf
is the list of pair access binf: baseinfo vector.
Definition at line 1736 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
type
tree_nodeRef binfo::type
type field is the actual data type node being inherited in this basetype.(BINFO_TYPE)
Definition at line 1727 of file tree_node.hpp.
Referenced by tree_helper::look_for_binfo_inheritance(), and raw_writer::write_when_not_null_point_to().
virt_flag
bool binfo::virt_flag
virt_flag is true if the node is a virtual declaration (macro TREE_VIA_VIRTUAL)
Definition at line 1730 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp