EucalyptusParameter Class Reference
#include <EucalyptusParameter.hpp>
Public Member Functions
EucalyptusParameter (const std::string &program_name, int argc, char **const argv)
Constructor.
~EucalyptusParameter () override=default
Destructor.
int Exec () override
Execute parameter parsing.
Private Member Functions
void CheckParameters () override
Check the compatibility among the different parameters and compute implicated parameters.
void SetDefaults () override
Sets the default values with respect to the tool.
void PrintHelp (std::ostream &os) const override
Print the usage of this tool.
void PrintProgramName (std::ostream &os) const override
Print the name of the program to be included in the header.
Additional Inherited Members
Detailed Description
Definition at line 58 of file EucalyptusParameter.hpp.
Constructor & Destructor Documentation
EucalyptusParameter()
EucalyptusParameter::EucalyptusParameter (const std::string & program_name, int argc, char **const argv)
Constructor.
Parameters
program_name is the name of the executable
argc is the number of arguments
argv is the array of arguments passed to program.
Definition at line 102 of file EucalyptusParameter.cpp.
References SetDefaults().
 EucalyptusParameter()
EucalyptusParameter::~EucalyptusParameter () [override], [default]
Destructor.
Member Function Documentation
CheckParameters()
void EucalyptusParameter::CheckParameters () [override], [private], [virtual]
Check the compatibility among the different parameters and compute implicated parameters.
Implements Parameter.
Definition at line 274 of file EucalyptusParameter.cpp.
References Parameter::CheckParameters(), Parameter::isOption(), Parameter::setOption(), and THROW_ERROR.
Referenced by Exec().
Exec()
int EucalyptusParameter::Exec () [override], [virtual]
Execute parameter parsing.
variable used into option parsing
output options
other options
Implements Parameter.
Definition at line 107 of file EucalyptusParameter.cpp.
References Parameter::argc, Parameter::argv, CheckParameters(), COMMON_LONG_OPTIONS, COMMON_SHORT_OPTIONS_STRING, exit_code, INPUT_OPT_CHARACTERIZE, INPUT_OPT_TARGET_DATAFILE, INPUT_OPT_TARGET_SCRIPTFILE, Parameter::ManageDefaultOptions(), OUTPUT_LEVEL_MINIMUM, PARAMETER_NOTPARSED, PARAMETER_PARSED, Parameter::PrintUsage(), Parameter::setOption(), THROW_ERROR, VERILOG, and VHDL.
PrintHelp()
void EucalyptusParameter::PrintHelp (std::ostream & os) const [override], [private], [virtual]
Print the usage of this tool.
Parameters
os is the stream where the message has to be printed
Implements Parameter.
Definition at line 77 of file EucalyptusParameter.cpp.
References Parameter::PrintGeneralOptionsUsage().
PrintProgramName()
void EucalyptusParameter::PrintProgramName (std::ostream & os) const [override], [private], [virtual]
Print the name of the program to be included in the header.
Parameters
os is the stream on which the program name has to be printed
Implements Parameter.
Definition at line 64 of file EucalyptusParameter.cpp.
SetDefaults()
void EucalyptusParameter::SetDefaults () [override], [private], [virtual]
Sets the default values with respect to the tool.
debugging levels
target device
library estimation
backend HDL
Implements Parameter.
Definition at line 299 of file EucalyptusParameter.cpp.
References DEBUG_LEVEL_MINIMUM, DEBUG_LEVEL_NONE, FPGA, OUTPUT_LEVEL_MINIMUM, Parameter::setOption(), and VERILOG.
Referenced by EucalyptusParameter().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/EucalyptusParameter.hpp
/home/osboxes/bambu/PandA-bambu/src/EucalyptusParameter.cpp