/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/discrepancy_analysis_c_writer.cpp File Reference
#include `discrepancy_analysis_c_writer.hpp`
#include `application_manager.hpp`
#include `call_graph.hpp`
#include `call_graph_manager.hpp`
#include `hls.hpp`
#include `hls_manager.hpp`
#include `fu_binding.hpp`
#include `memory.hpp`
#include `allocation_information.hpp`
#include `state_transition_graph.hpp`
#include `state_transition_graph_manager.hpp`
#include `Discrepancy.hpp`
#include `hls_c_backend_information.hpp`
#include `language_writer.hpp`
#include `technology_node.hpp`
#include `time_model.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_reindex.hpp`
#include `behavioral_helper.hpp`
#include `indented_output_stream.hpp`
#include `math_function.hpp`
#include `utility.hpp`
#include `Parameter.hpp`
Functions
static bool is_large_integer (const unsigned int t_id, const tree_managerConstRef T_M)
Function Documentation
is_large_integer()
static bool is_large_integer (const unsigned int t_id, const tree_managerConstRef T_M) [static]
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Michele Castellana michele.castellana@mail.polimi.it
Definition at line 97 of file discrepancy_analysis_c_writer.cpp.
References tree_node::get_kind(), tree_manager::get_tree_node_const(), STR, and THROW_ASSERT.
Referenced by DiscrepancyAnalysisCWriter::writePostInstructionInfo().