XilinxTasteBackendFlow Class Reference
superclass include
#include <xilinx_taste_backend_flow.hpp>
Public Member Functions
XilinxTasteBackendFlow (const ParameterConstRef &parameters, const std::string &flow_name, const target_managerRef &manager)
Constructor.
std::string GenerateSynthesisScripts (const std::string &fu_name, const structural_managerRef SM, const std::list< std::string > &hdl_files, const std::list< std::string > &aux_files) override
Generates the synthesis scripts for the specified design.
Protected Member Functions
void create_cf (const DesignParametersRef dp, bool xst) override
Creates the UCF file.
Additional Inherited Members
Detailed Description
superclass include
Definition at line 46 of file xilinx_taste_backend_flow.hpp.
Constructor & Destructor Documentation
XilinxTasteBackendFlow()
XilinxTasteBackendFlow::XilinxTasteBackendFlow (const ParameterConstRef & _parameters, const std::string & _flow_name, const target_managerRef & _manager)
Constructor.
Header include.
Parameters
parameters is the set of input parameters
flow_name is the name of the create flow
manager is the target manager
Autoheader include . include technology includes utility include wrapper/synthesis include wrapper/synthesis/xilinx include wrapper/synthesis/xilinx/ise include
Definition at line 69 of file xilinx_taste_backend_flow.cpp.
References BackendFlow::debug_level, and GET_CLASS.
Member Function Documentation
create_cf()
void XilinxTasteBackendFlow::create_cf (const DesignParametersRef dp, bool xst) [override], [protected], [virtual]
Creates the UCF file.
Reimplemented from XilinxBackendFlow.
Definition at line 184 of file xilinx_taste_backend_flow.cpp.
References DesignParameters::component_name, PARAM_ucf_file, PARAM_xcf_file, DesignParameters::parameter_values, and UCF_SUBDIR.
GenerateSynthesisScripts()
std::string XilinxTasteBackendFlow::GenerateSynthesisScripts (const std::string & fu_name, const structural_managerRef SM, const std::list< std::string > & hdl_files, const std::list< std::string > & aux_files) [override], [virtual]
Generates the synthesis scripts for the specified design.
Copying GRLIB
Modifying xst project adding grlib files
Reimplemented from BackendFlow.
Definition at line 74 of file xilinx_taste_backend_flow.cpp.
References BackendFlow::actual_parameters, DesignParameters::chain_name, CLOCK_PORT_NAME, DesignParameters::component_name, BackendFlow::CreateScripts(), BackendFlow::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BackendFlow::flow_name, INDENT_DBG_MEX, XilinxBackendFlow::InitDesignParameters(), IsError(), PandaSystem(), BackendFlow::Param, PARAM_backend_script_extensions, PARAM_clk_name, PARAM_connect_iob, PARAM_has_script_extensions, PARAM_has_VHDL_library, PARAM_HDL_files, PARAM_is_combinational, PARAM_time_constrained, PARAM_top_id, PARAM_VHDL_library, PARAM_xst_prj_file, DesignParameters::parameter_values, STR, BackendFlow::target, and THROW_ERROR.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/xilinx_taste_backend_flow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/xilinx_taste_backend_flow.cpp