minimal_interface Class Reference
Class generating minimal interfaces.
#include <minimal_interface.hpp>
Public Member Functions
minimal_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::MINIMAL_INTERFACE_GENERATION)
Constructor.
void build_wrapper (structural_objectRef wrappedObj, structural_objectRef interfaceObj, structural_managerRef SM_minimal_interface)
~minimal_interface () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Additional Inherited Members
Detailed Description
Class generating minimal interfaces.
Definition at line 54 of file minimal_interface.hpp.
Constructor & Destructor Documentation
minimal_interface()
minimal_interface::minimal_interface (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::MINIMAL_INTERFACE_GENERATION)
Constructor.
STD include.
STL includes utility include
Definition at line 86 of file minimal_interface.cpp.
References HLSFunctionStep::funId, THROW_ASSERT, and ~minimal_interface().
 minimal_interface()
minimal_interface::~minimal_interface () [override], [default]
Destructor.
Referenced by minimal_interface().
Member Function Documentation
build_wrapper()
void minimal_interface::build_wrapper (structural_objectRef wrappedObj, structural_objectRef interfaceObj, structural_managerRef SM_minimal_interface)
list of ports that have to be connected to constant 0
slave INs
slave OUTs
do nothing it may happen with ALL_BRAM memory allocation policy
intern data is not externally visible slave INs
slave OUTs
slave INs connections
master INs connections
slave OUTs skip
master OUTs skip
do nothing
allocate the unique shared memory
data padding
alignment padding
slave INs connections
master INs connections
master OUTs skip
slave INs connections
master INs connections
slave OUTs skip
master OUTs skip
slave INs
slave OUTs
Check if we have an I/O interface
check if we have fifo-in interface
check if we have fifo-out interface
check if we have array single port in interface
check if we have array single port out interface
Definition at line 144 of file minimal_interface.cpp.
References structural_manager::add_connection(), structural_manager::add_constant(), structural_manager::add_port(), structural_manager::add_port_vector(), structural_manager::add_sign(), structural_manager::add_sign_vector(), test_panda::arg, CLOCK_PORT_NAME, compareMemVarsPair(), counter, DONE_PORT_NAME, EXT_PIPELINED_BRAM, structural_object::find_member(), port_o::fix_port_properties(), hls::functionId, HLSFunctionStep::funId, get_id(), structural_object::get_id(), module::get_in_port(), module::get_in_port_size(), GET_INDEX_NODE, structural_object::get_kind(), tree_helper::get_mangled_fname(), GET_NODE, module::get_out_port(), module::get_out_port_size(), structural_object::get_owner(), tree_helper::get_pointed_type(), tree_helper::get_type_index(), GET_TYPE_SIZE, structural_object::get_typeRef(), HLSFunctionStep::HLS, HLS_step::HLSMgr, port_o::IN, structural_type_descriptor::INT, INTERN_UNALIGNED, port_o::IO, tree_helper::is_a_pointer(), LIBRARY_STD, MEM_ACC_11, MEM_ACC_N1, MEM_ACC_P1N, NO_BRAM, port_o::OUT, DesignFlowStep::parameters, port_o_K, port_vector_o_K, TestbenchGenerationBaseStep::print_var_init(), RESET_PORT_NAME, structural_object::SetParameter(), tree_helper::size(), tree_helper::Size(), structural_type_descriptor::size, SplitString(), START_PORT_NAME, STD_BRAM, STD_BRAMN, STR, THROW_ASSERT, THROW_ERROR, structural_type_descriptor::treenode, structural_type_descriptor::type, structural_object::type_resize(), structural_type_descriptor::UINT, VIEW_CONVERT_STD_INT, VIEW_CONVERT_STD_UINT, and WB4_INTERFACE_GENERATION.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status minimal_interface::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Set some descriptions and legal stuff
Implements HLSFunctionStep.
Reimplemented in WB4_interface.
Definition at line 94 of file minimal_interface.cpp.
References build_wrapper(), FunctionBehavior::CGetBehavioralHelper(), HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), structural_object::get_id(), structural_object::get_typeRef(), HLSFunctionStep::HLS, HLS_step::HLSMgr, structural_type_descriptor::id_type, DesignFlowStep::parameters, memory::propagate_memory_parameters(), structural_object::set_id(), structural_object::set_owner(), structural_manager::set_top_info(), SUCCESS, THROW_ERROR, and hls::top.
Referenced by WB4_interface::InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/minimal/minimal_interface.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/minimal/minimal_interface.cpp