IntermediateRepresentation Class Reference
#include <intermediate_representation.hpp>
Public Member Functions
IntermediateRepresentation (const ParameterConstRef &parameters)
Constructor.
virtual ~IntermediateRepresentation ()
Destructor.
virtual void Initialize ()=0
Initialize all the data structure.
virtual void Clear ()=0
Clear all the data structure.
Protected Attributes
const ParameterConstRef parameters
The set of input parameters.
int debug_level
The debug level.
Detailed Description
Definition at line 48 of file intermediate_representation.hpp.
Constructor & Destructor Documentation
IntermediateRepresentation()
IntermediateRepresentation::IntermediateRepresentation (const ParameterConstRef & _parameters) [explicit]
Constructor.
Header include.
Parameters
parameters is the set of input parameters
. include
Definition at line 46 of file intermediate_representation.cpp.
References ~IntermediateRepresentation().
 IntermediateRepresentation()
IntermediateRepresentation::~IntermediateRepresentation () [virtual], [default]
Destructor.
Referenced by IntermediateRepresentation().
Member Function Documentation
Clear()
void IntermediateRepresentation::Clear () [pure virtual]
Clear all the data structure.
Implemented in AllocationInformation, and HLSIR.
Definition at line 56 of file intermediate_representation.cpp.
Referenced by HLSIR::Clear().
Initialize()
void IntermediateRepresentation::Initialize () [pure virtual]
Initialize all the data structure.
Implemented in AllocationInformation, and HLSIR.
Definition at line 52 of file intermediate_representation.cpp.
Referenced by HLSIR::Initialize().
Field Documentation
debug_level
int IntermediateRepresentation::debug_level [protected]
The debug level.
Definition at line 55 of file intermediate_representation.hpp.
Referenced by AllocationInformation::AllocationInformation(), AllocationInformation::get_attribute_of_fu_per_op(), AllocationInformation::get_execution_time(), and AllocationInformation::GetNodeTypePrec().
parameters
const ParameterConstRef IntermediateRepresentation::parameters [protected]
The set of input parameters.
Definition at line 52 of file intermediate_representation.hpp.
Referenced by AllocationInformation::GetNodeTypePrec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/intermediate_representation.hpp
/home/osboxes/bambu/PandA-bambu/src/intermediate_representations/intermediate_representation.cpp