/home/osboxes/bambu/PandA-bambu/src/utility/cpu_time.hpp File Reference
Include a set of utilities used to manage CPU time measures.
#include `config_HAVE_OPENMP.hpp`
#include <boost/lexical_cast.hpp>
#include <sys/times.h>
#include `dbgPrintHelper.hpp`
#include <unistd.h>
Macros
#define TIMES_TICKS_PER_SEC 60
#define START_TIME(time_var) time_var = p_cpu_time()
Macro used to store the start time into time_var.
#define STOP_TIME(time_var) time_var = p_cpu_time() - (time_var)
Macro used to store the elapsed time into time_var.
#define START_WTIME(time_var) time_var = p_cpu_wtime()
Macro used to store the start time into time_var.
#define STOP_WTIME(time_var) time_var = p_cpu_wtime() - (time_var)
Macro used to store the elapsed time into time_var.
Functions
long int p_cpu_time ()
return a long which represents the elapsed processor time in milliseconds since some constant reference
std::string print_cpu_time (long int t)
massage a long which represents a time interval in milliseconds, into a string suitable for output
void dump_exec_time (const std::string &thing, long et)
long int p_cpu_wtime ()
return a long which represents the elapsed wall processor time in milliseconds since some constant reference
Detailed Description
Include a set of utilities used to manage CPU time measures.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$ Last modified by $Author$
Macro Definition Documentation
START_TIME
#define START_TIME(time_var) time_var = p_cpu_time()
Macro used to store the start time into time_var.
Definition at line 129 of file cpu_time.hpp.
Referenced by GccWrapper::CompileFile(), vcd_utility::Exec(), DesignFlowManager::Exec(), GccWrapper::FillTreeManager(), vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), mem_dominator_allocation::InternalExec(), chordal_coloring_register::InternalExec(), BB_based_stg::InternalExec(), easy_module_binding::InternalExec(), values_scheme::InternalExec(), weighted_clique_register::InternalExec(), mux_connection_binding::InternalExec(), allocation::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), main(), and read_technology_library().
START_WTIME
#define START_WTIME(time_var) time_var = p_cpu_wtime()
Macro used to store the start time into time_var.
Definition at line 148 of file cpu_time.hpp.
STOP_TIME
#define STOP_TIME(time_var) time_var = p_cpu_time() - (time_var)
Macro used to store the elapsed time into time_var.
Definition at line 132 of file cpu_time.hpp.
Referenced by GccWrapper::CompileFile(), vcd_utility::Exec(), DesignFlowManager::Exec(), GccWrapper::FillTreeManager(), vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), standard_hls::InternalExec(), mem_dominator_allocation::InternalExec(), chordal_coloring_register::InternalExec(), BB_based_stg::InternalExec(), easy_module_binding::InternalExec(), values_scheme::InternalExec(), weighted_clique_register::InternalExec(), mux_connection_binding::InternalExec(), allocation::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), main(), and read_technology_library().
STOP_WTIME
#define STOP_WTIME(time_var) time_var = p_cpu_wtime() - (time_var)
Macro used to store the elapsed time into time_var.
Definition at line 151 of file cpu_time.hpp.
TIMES_TICKS_PER_SEC
#define TIMES_TICKS_PER_SEC 60
Definition at line 73 of file cpu_time.hpp.
Referenced by p_cpu_time().
Function Documentation
dump_exec_time()
void dump_exec_time (const std::string & thing, long et) [inline]
Definition at line 122 of file cpu_time.hpp.
References INDENT_OUT_MEX, and print_cpu_time().
Referenced by GccWrapper::CompileFile(), GccWrapper::FillTreeManager(), and main().
p_cpu_time()
long int p_cpu_time () [inline]
return a long which represents the elapsed processor time in milliseconds since some constant reference
Definition at line 80 of file cpu_time.hpp.
References times(), and TIMES_TICKS_PER_SEC.
Referenced by p_cpu_wtime().
p_cpu_wtime()
long int p_cpu_wtime () [inline]
return a long which represents the elapsed wall processor time in milliseconds since some constant reference
Definition at line 138 of file cpu_time.hpp.
References p_cpu_time().
print_cpu_time()
std::string print_cpu_time (long int t) [inline]
massage a long which represents a time interval in milliseconds, into a string suitable for output
Definition at line 110 of file cpu_time.hpp.
Referenced by dump_exec_time(), vcd_utility::Exec(), DesignFlowManager::Exec(), vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), mem_dominator_allocation::InternalExec(), chordal_coloring_register::InternalExec(), BB_based_stg::InternalExec(), easy_module_binding::InternalExec(), values_scheme::InternalExec(), weighted_clique_register::InternalExec(), mux_connection_binding::InternalExec(), allocation::InternalExec(), parametric_list_based::InternalExec(), cdfc_module_binding::InternalExec(), main(), DesignCompilerWrapper::parse_synthesis_reports(), and read_technology_library().