SerializeMutualExclusions Class Reference
Superclass include.
#include <serialize_mutual_exclusions.hpp>
Public Member Functions
SerializeMutualExclusions (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~SerializeMutualExclusions () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Definition at line 44 of file serialize_mutual_exclusions.hpp.
Constructor & Destructor Documentation
SerializeMutualExclusions()
SerializeMutualExclusions::SerializeMutualExclusions (const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
parameters is the set of input parameters
. include behavior includes design_flows include parser/treegcc include tree includes utility include
Definition at line 72 of file serialize_mutual_exclusions.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~SerializeMutualExclusions().
 SerializeMutualExclusions()
SerializeMutualExclusions::~SerializeMutualExclusions () [override], [default]
Destructor.
Referenced by SerializeMutualExclusions().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > SerializeMutualExclusions::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 80 of file serialize_mutual_exclusions.cpp.
References BASIC_BLOCKS_CFG_COMPUTATION, BB_CONTROL_DEPENDENCE_COMPUTATION, BB_FEEDBACK_EDGES_IDENTIFICATION, BB_REACHABILITY_COMPUTATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DOM_POST_DOM_COMPUTATION, FunctionFrontendFlowStep::GetSignature(), DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SUCCESS, and THROW_UNREACHABLE.
HasToBeExecuted()
bool SerializeMutualExclusions::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 113 of file serialize_mutual_exclusions.cpp.
InternalExec()
DesignFlowStep_Status SerializeMutualExclusions::InternalExec () [override], [virtual]
Restructures the unstructured code.
Returns
the exit status of this step
Check if the control flow graph is structured
Analyzing basic blocks starting from the leaves
NOTE: here cfg_bb_graph is correct
Fix the phi in end if and create the phi in new block
Implements FunctionFrontendFlowStep.
Definition at line 118 of file serialize_mutual_exclusions.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, FunctionBehavior::CDG_BB, tree_manager::CGetTreeNode(), tree_helper::CGetType(), tree_manager::create_tree_node(), tree_manipulation::CreateIntegerCst(), tree_manipulation::CreateNotExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), INDENT_DBG_MEX, tree_manager::new_tree_node_id(), NULL_VERTEX, DesignFlowStep::parameters, phi, FunctionBehavior::POST_DOM_TREE, sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, TOK, TOK_OP0, TOK_RES, TOK_SCPE, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, test_panda::type, and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/serialize_mutual_exclusions.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_manipulation/serialize_mutual_exclusions.cpp