parm_decl_taken_address_fix Class Reference
#include <parm_decl_taken_address_fix.hpp>
Public Member Functions
parm_decl_taken_address_fix (const ParameterConstRef params, const application_managerRef AM, unsigned int fun_id, const DesignFlowManagerConstRef dfm)
Constructor.
~parm_decl_taken_address_fix () override
Destructor.
Protected Member Functions
DesignFlowStep_Status InternalExec () override
Execute the step.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 45 of file parm_decl_taken_address_fix.hpp.
Constructor & Destructor Documentation
parm_decl_taken_address_fix()
parm_decl_taken_address_fix::parm_decl_taken_address_fix (const ParameterConstRef params, const application_managerRef AM, unsigned int fun_id, const DesignFlowManagerConstRef dfm)
Constructor.
Definition at line 55 of file parm_decl_taken_address_fix.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~parm_decl_taken_address_fix().
 parm_decl_taken_address_fix()
parm_decl_taken_address_fix::~parm_decl_taken_address_fix () [override], [default]
Destructor.
Referenced by parm_decl_taken_address_fix().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > parm_decl_taken_address_fix::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 62 of file parm_decl_taken_address_fix.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status parm_decl_taken_address_fix::InternalExec () [override], [protected], [virtual]
Execute the step.
Returns
the exit status of this step
select the first basic block
Implements FunctionFrontendFlowStep.
Definition at line 90 of file parm_decl_taken_address_fix.cpp.
References FrontendFlowStep::AppM, BB_ENTRY, tree_manager::CGetTreeReindex(), tree_helper::CGetType(), tree_manipulation::create_binary_operation(), tree_manipulation::create_gimple_modify_stmt(), tree_manipulation::create_identifier_node(), tree_manipulation::create_ssa_name(), tree_manipulation::create_var_decl(), tree_manipulation::CreateGimpleAssignAddrExpr(), tree_manager::CreateUniqueIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), srcp::include_name, INDENT_DBG_MEX, tree_helper::name_function(), DesignFlowStep::parameters, tree_manager::ReplaceTreeNode(), sl, STR, SUCCESS, THROW_ASSERT, ToString(), and UNCHANGED.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/parm_decl_taken_address_fix.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/parm_decl_taken_address_fix.cpp