values_scheme Class Reference
#include <values_scheme.hpp>
Public Member Functions
values_scheme (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor of the class.
~values_scheme () override
Destructor of the class.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Additional Inherited Members
Detailed Description
Definition at line 65 of file values_scheme.hpp.
Constructor & Destructor Documentation
values_scheme()
values_scheme::values_scheme (const ParameterConstRef _Param, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor of the class.
Header include.
Parameters
design_flow_manager is the design flow manager
. include HLS includes HLS/binding/storage_value_information includes HLS/liveness include tree includes utility include
Definition at line 62 of file values_scheme.cpp.
References VALUES_SCHEME_STORAGE_VALUE_INSERTION, and ~values_scheme().
 values_scheme()
values_scheme::~values_scheme () [override], [default]
Destructor of the class.
Referenced by values_scheme().
Member Function Documentation
Initialize()
void values_scheme::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from storage_value_insertion.
Definition at line 69 of file values_scheme.cpp.
References HLSFunctionStep::funId, HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), StorageValueInformation::Initialize(), and hls::storage_value_information.
InternalExec()
DesignFlowStep_Status values_scheme::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements HLSFunctionStep.
Definition at line 76 of file values_scheme.cpp.
References HLSFunctionStep::funId, liveness::get_live_in(), liveness::get_support(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_OUT_MEX, StorageValueInformation::number_of_storage_values, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, print_cpu_time(), hls::Rliv, START_TIME, STOP_TIME, StorageValueInformation::storage_index_map, hls::storage_value_information, SUCCESS, THROW_ASSERT, and StorageValueInformation::variable_index_vect.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/storage_value_insertion/values_scheme.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/storage_value_insertion/values_scheme.cpp