flopoco_wrapper Class Reference
Main class for wrapping the FloPoCo code generator.
#include <flopoco_wrapper.hpp>
Public Member Functions
flopoco_wrapper (int _debug_level, const std::string &FU_target)
Constructor.
~flopoco_wrapper ()
Destructor.
flopoco_wrapper (const flopoco_wrapper &inst)=delete
void add_FU (const std::string &FU_type, unsigned int FU_prec_in, unsigned int FU_prec_out, const std::string &FU_name, const std::string &pipe_parameter)
Adds a Functional Unit to the wrapper.
unsigned int get_FUPipelineDepth (const std::string &FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const std::string &pipe_parameter) const
Returns the Functional Unit's Pipeline Depth.
int writeVHDL (const std::string &FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, std::string pipe_parameter, std::string &filename)
Writes the VHDL for a Functional Unit to the default file name, which is `FU_name.vhdl` Returns -1 if some problem occurred, 0 if the file was successfully written, 1 if the FU was already written to a file.
std::string writeVHDLcommon ()
write the common components
const CustomUnorderedSet< std::string > & get_files_written ()
Returns the Functional Units that have been written to a VHDL file.
bool is_unit_written (const std::string &FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const std::string &pipe_parameter) const
Checks if a Functional Unit have been written to a VHDL file.
const std::vector< std::string > get_in_ports (const std::string &FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const unsigned int expected_ports, const std::string &pipe_parameter) const
Return the names of input and output ports (multiple names, thus a vector of strings)
const std::vector< std::string > get_out_ports (const std::string &FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const unsigned int expected_ports, const std::string &pipe_parameter) const
Static Public Member Functions
static void DECODE_BITS (unsigned int FU_prec, unsigned int &n_mant, unsigned int &n_exp)
Retrieve mantissa and exponent for a given precision.
Static Public Attributes
static const double DEFAULT_TARGET_FREQUENCY = 100.0
Private Types
enum port_type { port_in,
port_out,
clk,
rst
 }
Port types.
enum component_type { top,
wrapped,
in_wrap,
out_wrap
 }
Component types.
enum unit_type {
UT_ADD,
UT_SUB,
UT_MULT,
UT_DIV,
UT_FF_CONV,
UT_ADDSUB,
UT_UFIX2FP,
UT_IFIX2FP,
UT_FP2UFIX,
UT_FP2IFIX,
UT_EXP,
UT_SQRT,
UT_compare_expr,
UT_LOG,
UT_POW,
UT_UNKNOWN
 }
unit type
Private Member Functions
flopoco::Operator * get_FU (std::string FU_name_stored) const
Returns one of the generated Functional Units.
const std::vector< std::string > get_ports (const std::string &FU_name_stored, unsigned int expected_ports, port_type type, bool check_ports=true) const
Returns the names of ports, according to the needed port type (port_in or port_out)
const std::string get_port (port_type type) const
Returns the name of a port, according to the needed port type (clock or reset)
int InternalWriteVHDL (const std::string &FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const std::string &FU_file, const std::string &pipe_parameter)
Writes the VHDL for a Functional Unit to the desired file name Returns -1 if some problem occurred, 0 if the file was successfully written, 1 if the FU was already written to a file.
void outputHeaderVHDL (const std::string &FU_name_stored, std::ostream &os) const
Helper methods for automatic VHDL code generation:
void outputWrapVHDL (const std::string &FU_name_stored, std::ostream &os, const std::string &pipe_parameter)
void outputPortDeclaration (const std::string &FU_prefix, const std::string &FU_name_stored, std::ostream &os, component_type type, const std::string &pipe_parameter)
void outputSignals (const std::string &FU_name_stored, std::ostream &os)
void outputPortMap (const std::string &FU_name_stored, std::ostream &os, const std::string &pipe_parameter)
Private Attributes
int debug_level
Current debug level.
CustomUnorderedMap< std::string, flopoco::Operator * > FUs
Generated Functional Units.
CustomUnorderedSet< std::string > FU_files
Set of Functional Units written to a .vhdl file.
CustomUnorderedMap< std::string, std::pair< unsigned int, unsigned int > > FU_to_prec
Maps a Functional Unit to its precision.
simple_indent PP
Pretty print functor object used to indent the generated code.
unit_type type
bool signed_p
std::vector< flopoco::Operator * > oplist
flopoco::Target * target
Detailed Description
Main class for wrapping the FloPoCo code generator.
Definition at line 96 of file flopoco_wrapper.hpp.
Member Enumeration Documentation
component_type
enum flopoco_wrapper::component_type [private]
Component types.
Enumerator
top
wrapped
in_wrap
out_wrap
Definition at line 120 of file flopoco_wrapper.hpp.
port_type
enum flopoco_wrapper::port_type [private]
Port types.
Enumerator
port_in
port_out
clk
rst
Definition at line 112 of file flopoco_wrapper.hpp.
unit_type
enum flopoco_wrapper::unit_type [private]
unit type
Enumerator
UT_ADD
UT_SUB
UT_MULT
UT_DIV
UT_FF_CONV
UT_ADDSUB
UT_UFIX2FP
UT_IFIX2FP
UT_FP2UFIX
UT_FP2IFIX
UT_EXP
UT_SQRT
UT_compare_expr
UT_LOG
UT_POW
UT_UNKNOWN
Definition at line 128 of file flopoco_wrapper.hpp.
Constructor & Destructor Documentation
flopoco_wrapper() [1/2]
flopoco_wrapper::flopoco_wrapper (int _debug_level, const std::string & FU_target)
Constructor.
Parameters
debug is the current debug level
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
does not exist so we use Virtex 6 target
sollya initialization
Definition at line 151 of file flopoco_wrapper.cpp.
References target, THROW_ERROR, and THROW_UNREACHABLE.
 flopoco_wrapper()
flopoco_wrapper::~flopoco_wrapper ()
Destructor.
Definition at line 221 of file flopoco_wrapper.cpp.
flopoco_wrapper() [2/2]
flopoco_wrapper::flopoco_wrapper (const flopoco_wrapper & inst) [delete]
Member Function Documentation
add_FU()
void flopoco_wrapper::add_FU (const std::string & FU_type, unsigned int FU_prec_in, unsigned int FU_prec_out, const std::string & FU_name, const std::string & pipe_parameter)
Adds a Functional Unit to the wrapper.
Parameters
FU_type is a string representing the FU type
FU_prec_in is a number representing the FU input precision
FU_prec_out is a number representing the FU output precision
FU_name is a string representing the FU name
pipe_parameter is a string defining the design frequency, in case is not empty
set the target frequency
Definition at line 226 of file flopoco_wrapper.cpp.
References debug_level, DEBUG_LEVEL_PEDANTIC, DECODE_BITS(), DEFAULT_TARGET_FREQUENCY, ENCODE_NAME, FU_to_prec, FUs, IN_WRAP_PREFIX, OPLIST, OUT_WRAP_PREFIX, PRINT_DBG_MEX, signed_p, STR, target, THROW_ASSERT, THROW_UNREACHABLE, type, UT_ADD, UT_ADDSUB, UT_compare_expr, UT_DIV, UT_EXP, UT_FF_CONV, UT_FP2IFIX, UT_FP2UFIX, UT_IFIX2FP, UT_LOG, UT_MULT, UT_POW, UT_SQRT, UT_SUB, UT_UFIX2FP, UT_UNKNOWN, and WRAPPED_PREFIX.
DECODE_BITS()
void flopoco_wrapper::DECODE_BITS (unsigned int FU_prec, unsigned int & n_mant, unsigned int & n_exp) [static]
Retrieve mantissa and exponent for a given precision.
Parameters
FU_prec is a number representing the FU precision
n_mant is the number of bits for the mantissa
n_exp is the number of bits for the exponent
Intel 80 bit extended precision padded with 16bits
Definition at line 970 of file flopoco_wrapper.cpp.
References THROW_ERROR.
Referenced by add_FU().
get_files_written()
const CustomUnorderedSet<std::string>& flopoco_wrapper::get_files_written () [inline]
Returns the Functional Units that have been written to a VHDL file.
Definition at line 254 of file flopoco_wrapper.hpp.
get_FU()
flopoco::Operator * flopoco_wrapper::get_FU (std::string FU_name_stored) const [private]
Returns one of the generated Functional Units.
Parameters
FU_name_stored is a string representing the stored FU name
Definition at line 492 of file flopoco_wrapper.cpp.
References FUs, and THROW_ASSERT.
Referenced by get_FUPipelineDepth(), and get_ports().
get_FUPipelineDepth()
unsigned int flopoco_wrapper::get_FUPipelineDepth (const std::string & FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const std::string & pipe_parameter) const
Returns the Functional Unit's Pipeline Depth.
Parameters
FU_name is the Functional Unit whose Pipeline Depth is returned
FU_prec_in is a number representing the FU input precision
FU_prec_out is a number representing the FU output precision
Definition at line 481 of file flopoco_wrapper.cpp.
References ENCODE_NAME, get_FU(), IN_WRAP_PREFIX, OUT_WRAP_PREFIX, type, UT_compare_expr, UT_FP2IFIX, UT_FP2UFIX, UT_IFIX2FP, UT_UFIX2FP, and WRAPPED_PREFIX.
get_in_ports()
const std::vector<std::string> flopoco_wrapper::get_in_ports (const std::string & FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const unsigned int expected_ports, const std::string & pipe_parameter) const [inline]
Return the names of input and output ports (multiple names, thus a vector of strings)
Parameters
FU_name is a string representing the FU name
expected_ports is the number of expected ports to be returned
Definition at line 273 of file flopoco_wrapper.hpp.
References ENCODE_NAME, and WRAPPED_PREFIX.
get_out_ports()
const std::vector<std::string> flopoco_wrapper::get_out_ports (const std::string & FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const unsigned int expected_ports, const std::string & pipe_parameter) const [inline]
Definition at line 277 of file flopoco_wrapper.hpp.
References ENCODE_NAME, and WRAPPED_PREFIX.
get_port()
const std::string flopoco_wrapper::get_port (port_type type) const [private]
Returns the name of a port, according to the needed port type (clock or reset)
Parameters
type is the type of the required port
Definition at line 960 of file flopoco_wrapper.cpp.
References clk, rst, and THROW_UNREACHABLE.
Referenced by outputPortDeclaration(), and outputPortMap().
get_ports()
const std::vector< std::string > flopoco_wrapper::get_ports (const std::string & FU_name_stored, unsigned int expected_ports, port_type type, bool check_ports = true) const [private]
Returns the names of ports, according to the needed port type (port_in or port_out)
Parameters
FU_name_stored is a string representing the stored FU name
FU_prec is a number representing the FU precision
expected_ports is the number of expected ports to be returned
type is the type of the required ports
Definition at line 944 of file flopoco_wrapper.cpp.
References get_FU(), port_in, port_out, and THROW_ASSERT.
Referenced by outputPortDeclaration(), outputPortMap(), outputSignals(), and outputWrapVHDL().
InternalWriteVHDL()
int flopoco_wrapper::InternalWriteVHDL (const std::string & FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const std::string & FU_file, const std::string & pipe_parameter) [private]
Writes the VHDL for a Functional Unit to the desired file name Returns -1 if some problem occurred, 0 if the file was successfully written, 1 if the FU was already written to a file.
Parameters
FU_name is the Functional Unit whose code must be output
FU_prec_in_in is a number representing the FU input precision
FU_prec_out is a number representing the FU output precision
FU_file is the name of the file, without extension, where the VHDL code should be put (i.e. `FPAdder`, not `FPAdder.vhdl`)
pipe_parameter is a string defining the design frequency, in case is not empty
Definition at line 874 of file flopoco_wrapper.cpp.
References debug_level, DEBUG_LEVEL_PEDANTIC, ENCODE_NAME, FU_files, OPLIST, outputWrapVHDL(), and PRINT_DBG_MEX.
Referenced by writeVHDL().
is_unit_written()
bool flopoco_wrapper::is_unit_written (const std::string & FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, const std::string & pipe_parameter) const [inline]
Checks if a Functional Unit have been written to a VHDL file.
Parameters
FU_name is the Functional Unit whose existence must be checked
Definition at line 263 of file flopoco_wrapper.hpp.
References ENCODE_NAME, and FILE_EXT.
outputHeaderVHDL()
void flopoco_wrapper::outputHeaderVHDL (const std::string & FU_name_stored, std::ostream & os) const [private]
Helper methods for automatic VHDL code generation:
Parameters
FU_prefix is a string representing the prefix to prepend to FU_name, when needed
FU_name_stored is a string representing the stored FU name
os is the stream where the VHDL code should be put
type is the type of component under examination
Definition at line 864 of file flopoco_wrapper.cpp.
Referenced by outputWrapVHDL().
outputPortDeclaration()
void flopoco_wrapper::outputPortDeclaration (const std::string & FU_prefix, const std::string & FU_name_stored, std::ostream & os, component_type type, const std::string & pipe_parameter) [private]
Definition at line 740 of file flopoco_wrapper.cpp.
References clk, CLOCK_PORT_NAME, DONE_PORT_NAME, FLOPOCO_ADDITIONAL_BITS, FU_to_prec, get_port(), get_ports(), in_wrap, out_wrap, port_in, port_out, PP, RESET_PORT_NAME, rst, START_PORT_NAME, STR, top, type, UT_ADDSUB, UT_compare_expr, UT_EXP, UT_FF_CONV, UT_FP2IFIX, UT_FP2UFIX, UT_IFIX2FP, UT_LOG, UT_POW, UT_SQRT, UT_UFIX2FP, and wrapped.
Referenced by outputWrapVHDL().
outputPortMap()
void flopoco_wrapper::outputPortMap (const std::string & FU_name_stored, std::ostream & os, const std::string & pipe_parameter) [private]
Definition at line 582 of file flopoco_wrapper.cpp.
References clk, CLOCK_PORT_NAME, DONE_PORT_NAME, FU_to_prec, get_port(), get_ports(), IN_WRAP_PREFIX, OUT_WRAP_PREFIX, port_in, port_out, PP, RESET_PORT_NAME, rst, STR, type, UT_ADDSUB, UT_compare_expr, UT_EXP, UT_FP2IFIX, UT_FP2UFIX, UT_IFIX2FP, UT_LOG, UT_POW, UT_SQRT, UT_SUB, UT_UFIX2FP, and WRAPPED_PREFIX.
Referenced by outputWrapVHDL().
outputSignals()
void flopoco_wrapper::outputSignals (const std::string & FU_name_stored, std::ostream & os) [private]
Definition at line 692 of file flopoco_wrapper.cpp.
References FU_to_prec, get_ports(), max(), port_in, port_out, PP, STR, type, UT_ADDSUB, UT_compare_expr, UT_FF_CONV, UT_FP2IFIX, UT_FP2UFIX, UT_IFIX2FP, UT_SUB, UT_UFIX2FP, and WRAPPED_PREFIX.
Referenced by outputWrapVHDL().
outputWrapVHDL()
void flopoco_wrapper::outputWrapVHDL (const std::string & FU_name_stored, std::ostream & os, const std::string & pipe_parameter) [private]
Definition at line 499 of file flopoco_wrapper.cpp.
References simple_indent::deindent(), FU_to_prec, get_ports(), in_wrap, IN_WRAP_PREFIX, simple_indent::indent(), out_wrap, OUT_WRAP_PREFIX, outputHeaderVHDL(), outputPortDeclaration(), outputPortMap(), outputSignals(), port_in, port_out, PP, STR, THROW_UNREACHABLE, top, type, UT_compare_expr, UT_FP2IFIX, UT_FP2UFIX, UT_IFIX2FP, UT_UFIX2FP, wrapped, and WRAPPED_PREFIX.
Referenced by InternalWriteVHDL().
writeVHDL()
int flopoco_wrapper::writeVHDL (const std::string & FU_name, const unsigned int FU_prec_in, const unsigned int FU_prec_out, std::string pipe_parameter, std::string & filename)
Writes the VHDL for a Functional Unit to the default file name, which is `FU_name.vhdl` Returns -1 if some problem occurred, 0 if the file was successfully written, 1 if the FU was already written to a file.
Parameters
FU_name is the Functional Unit whose code must be output
FU_prec_in_in is a number representing the FU input precision
FU_prec_out is a number representing the FU output precision
pipe_parameter is a string defining the design frequency, in case is not empty
filename is where the name of the produced file will be stored
Definition at line 911 of file flopoco_wrapper.cpp.
References ENCODE_NAME, FILE_EXT, and InternalWriteVHDL().
writeVHDLcommon()
std::string flopoco_wrapper::writeVHDLcommon ()
write the common components
Returns
the name of the generated
Definition at line 917 of file flopoco_wrapper.cpp.
References FILE_EXT, flopoco::filename, target, and THROW_UNREACHABLE.
Field Documentation
debug_level
int flopoco_wrapper::debug_level [private]
Current debug level.
Definition at line 101 of file flopoco_wrapper.hpp.
Referenced by add_FU(), and InternalWriteVHDL().
DEFAULT_TARGET_FREQUENCY
const double flopoco_wrapper::DEFAULT_TARGET_FREQUENCY = 100.0 [static]
Definition at line 293 of file flopoco_wrapper.hpp.
Referenced by add_FU().
FU_files
CustomUnorderedSet<std::string> flopoco_wrapper::FU_files [private]
Set of Functional Units written to a .vhdl file.
Definition at line 106 of file flopoco_wrapper.hpp.
Referenced by InternalWriteVHDL().
FU_to_prec
CustomUnorderedMap<std::string, std::pair<unsigned int, unsigned int> > flopoco_wrapper::FU_to_prec [private]
Maps a Functional Unit to its precision.
Definition at line 108 of file flopoco_wrapper.hpp.
Referenced by add_FU(), outputPortDeclaration(), outputPortMap(), outputSignals(), and outputWrapVHDL().
FUs
CustomUnorderedMap<std::string, flopoco::Operator*> flopoco_wrapper::FUs [private]
Generated Functional Units.
Definition at line 104 of file flopoco_wrapper.hpp.
Referenced by add_FU(), and get_FU().
oplist
std::vector<flopoco::Operator*> flopoco_wrapper::oplist [private]
Definition at line 152 of file flopoco_wrapper.hpp.
PP
simple_indent flopoco_wrapper::PP [private]
Pretty print functor object used to indent the generated code.
Definition at line 110 of file flopoco_wrapper.hpp.
Referenced by outputPortDeclaration(), outputPortMap(), outputSignals(), and outputWrapVHDL().
signed_p
bool flopoco_wrapper::signed_p [private]
Definition at line 150 of file flopoco_wrapper.hpp.
Referenced by add_FU().
target
flopoco::Target* flopoco_wrapper::target [private]
Definition at line 154 of file flopoco_wrapper.hpp.
Referenced by add_FU(), flopoco_wrapper(), and writeVHDLcommon().
type
unit_type flopoco_wrapper::type [private]
Definition at line 148 of file flopoco_wrapper.hpp.
Referenced by add_FU(), get_FUPipelineDepth(), outputPortDeclaration(), outputPortMap(), outputSignals(), and outputWrapVHDL().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/flopoco/flopoco_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/flopoco/flopoco_wrapper.cpp