moduleGenerator Class Reference
#include <moduleGenerator.hpp>
Public Member Functions
moduleGenerator (const HLS_managerConstRef HLSMgr, const ParameterConstRef parameters)
Constructor.
virtual ~moduleGenerator ()
Destructor.
structural_type_descriptorRef getDataType (unsigned int variable, const FunctionBehaviorConstRef FB) const
void add_port_parameters (structural_objectRef generated_port, structural_objectRef currentPort)
std::string GenerateHDL (const module *mod, const std::string &hdl_template, std::vector< std::tuple< unsigned int, unsigned int >> &required_variables, const std::string &specializing_string, const FunctionBehaviorConstRef FB, const std::string &path_dynamic_generators, HDLWriter_Language)
std::string get_specialized_name (unsigned int firstIndexToSpecialize, std::vector< std::tuple< unsigned int, unsigned int >> &required_variables, const FunctionBehaviorConstRef FB) const
void specialize_fu (std::string fuName, vertex ve, std::string libraryId, const technology_managerRef TM, const FunctionBehaviorConstRef FB, std::string new_fu_name, std::map< std::string, technology_nodeRef > &new_fu, const TargetDevice_Type dv_type)
Protected Attributes
const HLS_managerConstRef HLSMgr
The HLS manager.
const ParameterConstRef parameters
The set of input parameters.
const int debug_level
The debug level.
Detailed Description
Definition at line 71 of file moduleGenerator.hpp.
Constructor & Destructor Documentation
moduleGenerator()
moduleGenerator::moduleGenerator (const HLS_managerConstRef _HLSMgr, const ParameterConstRef _parameters)
Constructor.
header include
Parameters
HLSMgr is the HLS manager
parameters is the set of input parameters
Autoheader include . include behavior include circuit includes design_flows/backend/ToHDL HLS include HLS/memory include STD includes STL include technology include technology/physical_library includes technology/physical_library/models include tree include utility include
Definition at line 107 of file moduleGenerator.cpp.
References ~moduleGenerator().
 moduleGenerator()
moduleGenerator::~moduleGenerator () [virtual], [default]
Destructor.
Referenced by moduleGenerator().
Member Function Documentation
add_port_parameters()
void moduleGenerator::add_port_parameters (structural_objectRef generated_port, structural_objectRef currentPort)
Definition at line 338 of file moduleGenerator.cpp.
References structural_object::copy(), structural_object::get_typeRef(), structural_type_descriptor::size, and structural_type_descriptor::vector_size.
Referenced by specialize_fu().
GenerateHDL()
std::string moduleGenerator::GenerateHDL (const module * mod, const std::string & hdl_template, std::vector< std::tuple< unsigned int, unsigned int >> & required_variables, const std::string & specializing_string, const FunctionBehaviorConstRef FB, const std::string & path_dynamic_generators, HDLWriter_Language language)
Definition at line 145 of file moduleGenerator.cpp.
References debug_level, DEBUG_LEVEL_VERBOSE, structural_object::get_id(), module::get_in_out_port_size(), module::get_in_port(), module::get_in_port_size(), structural_type_descriptor::get_name(), module::get_out_port(), module::get_out_port_size(), structural_object::get_typeRef(), getDataType(), HLSMgr, IsError(), PandaSystem(), parameters, PRINT_DBG_MEX, resize_to_8_or_greater(), structural_type_descriptor::size, STR, THROW_ERROR, structural_type_descriptor::vector_size, and VERILOG.
Referenced by specialize_fu().
get_specialized_name()
std::string moduleGenerator::get_specialized_name (unsigned int firstIndexToSpecialize, std::vector< std::tuple< unsigned int, unsigned int >> & required_variables, const FunctionBehaviorConstRef FB) const
Definition at line 128 of file moduleGenerator.cpp.
References structural_type_descriptor::get_name(), getDataType(), index, NAMESEPARATOR, resize_to_8_or_greater(), structural_type_descriptor::size, STR, and structural_type_descriptor::vector_size.
getDataType()
structural_type_descriptorRef moduleGenerator::getDataType (unsigned int variable, const FunctionBehaviorConstRef FB) const
Definition at line 115 of file moduleGenerator.cpp.
References FunctionBehavior::CGetBehavioralHelper().
Referenced by GenerateHDL(), get_specialized_name(), and specialize_fu().
specialize_fu()
void moduleGenerator::specialize_fu (std::string fuName, vertex ve, std::string libraryId, const technology_managerRef TM, const FunctionBehaviorConstRef FB, std::string new_fu_name, std::map< std::string, technology_nodeRef > & new_fu, const TargetDevice_Type dv_type)
add description and license
normalize type
default language
Definition at line 345 of file moduleGenerator.cpp.
References structural_manager::add_NP_functionality(), structural_manager::add_port(), add_port_parameters(), structural_manager::add_port_vector(), test_panda::args, BUILTIN_WAIT_CALL, FunctionBehavior::CFG, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), CLOCK_PORT_NAME, area_model::create_model(), debug_level, DEBUG_LEVEL_VERBOSE, GenerateHDL(), BehavioralHelper::get_asm_string(), structural_manager::get_circ(), library_manager::get_fu(), BehavioralHelper::get_function_index(), structural_object::get_id(), GET_INDEX_NODE, tree_helper::get_integer_cst_value(), structural_object::get_kind(), technology_manager::get_library_manager(), tree_helper::get_mangled_fname(), GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_node(), structural_object::get_typeRef(), getDataType(), tree_manager::GetTreeNode(), GIMPLE_ASM, HLSMgr, port_o::IN, NP_functionality::LIBRARY, port_o::OUT, parameters, port_vector_o_K, PRINT_DBG_MEX, RESET_PORT_NAME, resize_to_8_or_greater(), structural_manager::set_top_info(), tree_helper::size(), structural_type_descriptor::size, START_PORT_NAME, STR, STR_CST_interface_parameter_keyword, THROW_ASSERT, THROW_ERROR, top(), structural_type_descriptor::vector_size, VERILOG, NP_functionality::VERILOG_GENERATOR, NP_functionality::VERILOG_PROVIDED, VHDL, NP_functionality::VHDL_GENERATOR, and NP_functionality::VHDL_PROVIDED.
Field Documentation
debug_level
const int moduleGenerator::debug_level [protected]
The debug level.
Definition at line 81 of file moduleGenerator.hpp.
Referenced by GenerateHDL(), and specialize_fu().
HLSMgr
const HLS_managerConstRef moduleGenerator::HLSMgr [protected]
The HLS manager.
Definition at line 75 of file moduleGenerator.hpp.
Referenced by GenerateHDL(), and specialize_fu().
parameters
const ParameterConstRef moduleGenerator::parameters [protected]
The set of input parameters.
Definition at line 78 of file moduleGenerator.hpp.
Referenced by GenerateHDL(), and specialize_fu().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/module_generator/moduleGenerator.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/module_generator/moduleGenerator.cpp