/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/split_return.cpp File Reference
Simple transformations that remove almost empty basic blocks having a single phi and a return statement.
#include `split_return.hpp`
#include `phi_opt.hpp`
#include `application_manager.hpp`
#include `call_graph.hpp`
#include `call_graph_manager.hpp`
#include `Parameter.hpp`
#include `hls.hpp`
#include `hls_manager.hpp`
#include `token_interface.hpp`
#include <fstream>
#include `custom_set.hpp`
#include `dbgPrintHelper.hpp`
#include `ext_tree_node.hpp`
#include `string_manipulation.hpp`
#include `tree_basic_block.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_node.hpp`
#include `tree_reindex.hpp`
Functions
static void create_return_and_fix_cfg (const tree_managerRef TM, std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > &gimple_return_schema, statement_list *sl, blocRef pred_block, blocRef bb_block, int DEBUG_PARAMETER(debug_level))
Detailed Description
Simple transformations that remove almost empty basic blocks having a single phi and a return statement.
The transformation remove this BB by propagating back the return statement.
Author
Hamidreza Hanafi hamidreza.hanafi@mail.polimi.it
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
create_return_and_fix_cfg()
static void create_return_and_fix_cfg (const tree_managerRef TM, std::map< TreeVocabularyTokenTypes_TokenEnum, std::string > & gimple_return_schema, statement_list * sl, blocRef pred_block, blocRef bb_block, int DEBUG_PARAMETERdebug_level) [static]
Add predecessor as pred basic block
Add successor as succ basic block
Fix successor of predecessor
Fix gimple_multi_way_if
Definition at line 138 of file split_return.cpp.
References tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, GET_NODE, tree_manager::GetTreeReindex(), INDENT_DBG_MEX, statement_list::list_of_bloc, tree_manager::new_tree_node_id(), and STR.
Referenced by SplitReturn::InternalExec().