technology_manager Class Reference
This class manages the technology library structures.
#include <technology_manager.hpp>
Public Types
typedef CustomUnorderedMap< std::string, library_managerRef > library_map_type
definition of the type for identifying the libraries
Public Member Functions
double CGetSetupHoldTime () const
Return the setup hold time.
TimeStamp CGetSetupHoldTimeStamp () const
Return the characterization timestamp of the setup hold time.
 Constructors and destructors.
technology_manager (const ParameterConstRef Param)
Constructor.
~technology_manager ()
Destructor.
 Factory functions. Used to build and fill the technology data structures
void add (const technology_nodeRef curr, const std::string &Library)
Add the given functional_unit to the specified library.
void add_operation (const std::string &Library, const std::string &fu_name, const std::string &operation_name)
Add an operation to the specified functional unit.
 Query functions. Used to extract some information from the technology data structure.
const std::vector< std::string > & get_library_list () const
Return the list of the libraries.
bool can_implement (const std::string &fu_name, const std::string &op_name, const std::string &Library) const
Check if an operation can be implemented by a given component in a given library.
technology_nodeRef get_fu (const std::string &fu_name, const std::string &Library) const
Return the reference to a component given its name.
std::string get_library (const std::string &Name) const
Return the higher priority library where the given component is stored.
void erase_library (const std::string &Name)
Release the given library.
bool is_library_manager (const std::string &Name) const
Check if a library is contained into the data structure.
library_managerRef get_library_manager (const std::string &Name) const
Return the library data structure corresponding to the given library id.
ControlStep get_initiation_time (const std::string &fu_name, const std::string &op_name, const std::string &Library) const
Return the initiation time for a given operation type and a given component.
double get_execution_time (const std::string &fu_name, const std::string &op_name, const std::string &Library) const
Return the execution time for a given operation type and a given component.
double get_area (const std::string &fu_name, const std::string &Library) const
Return the area for a given component.
bool IsBuiltin (const std::string &component_name) const
Return true if a component is builtin.
 XML functions.
void xload (const xml_element *node, const target_deviceRef device)
Load a technology manager from an xml file.
void xwrite (xml_element *rootnode, TargetDevice_Type dv_type, const CustomOrderedSet< std::string > &libraries=CustomOrderedSet< std::string >())
add library elements operation node to an xml tree.
Static Public Attributes
 Library output formats
static const unsigned int XML = 1 << 0
Autoheader include.
static const unsigned int LIB
static const unsigned int LEF = 1 << 2
Private Member Functions
const functional_unit * CGetSetupHoldFU () const
Return the functional unit used to compute the setup hold time.
Private Attributes
const ParameterConstRef Param
class containing all the parameters
int debug_level
The debug level for this class.
library_map_type library_map
map between library name and the corresponding data structure
std::vector< std::string > libraries
(reverse) ordered list of libraries; it gives a priority ordering for searching the nodes
CustomSet< std::string > builtins
The builtin components.
Friends
class allocation
friend definition for class allocation
Print functions.
std::ostream & operator<< (std::ostream &os, const technology_manager &s)
Friend definition of the << operator.
std::ostream & operator<< (std::ostream &os, const technology_managerRef &s)
Friend definition of the << operator.
void print (std::ostream &os) const
Function that prints the class technology_manager.
Detailed Description
This class manages the technology library structures.
Definition at line 121 of file technology_manager.hpp.
Member Typedef Documentation
library_map_type
typedef CustomUnorderedMap<std::string, library_managerRef> technology_manager::library_map_type
definition of the type for identifying the libraries
Definition at line 134 of file technology_manager.hpp.
Constructor & Destructor Documentation
technology_manager()
technology_manager::technology_manager (const ParameterConstRef Param) [explicit]
Constructor.
Definition at line 92 of file technology_manager.cpp.
References debug_level, GET_CLASS, Param, and ~technology_manager().
 technology_manager()
technology_manager::~technology_manager () [default]
Destructor.
Referenced by technology_manager().
Member Function Documentation
add()
void technology_manager::add (const technology_nodeRef curr, const std::string & Library)
Add the given functional_unit to the specified library.
Parameters
curr is the added element
Definition at line 207 of file technology_manager.cpp.
References CG_LIBRARY, DESIGN, libraries, library_map, and Param.
Referenced by add_operation(), erase_library(), get_area(), allocation::InternalExec(), and xload().
add_operation()
void technology_manager::add_operation (const std::string & Library, const std::string & fu_name, const std::string & operation_name)
Add an operation to the specified functional unit.
Definition at line 196 of file technology_manager.cpp.
References add(), get_fu(), library_map, and THROW_ASSERT.
Referenced by allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), OmpAllocation::AddPandaPthreadMutex(), InitializeHLS::InternalExec(), and add_library::InternalExec().
can_implement()
bool technology_manager::can_implement (const std::string & fu_name, const std::string & op_name, const std::string & Library) const
Check if an operation can be implemented by a given component in a given library.
Parameters
fu_name is the name of the component.
op_name is the name of the operation.
Library is library name where the unit is stored
Returns
true when the operation can be implemented, false otherwise.
Definition at line 112 of file technology_manager.cpp.
References get_fu().
Referenced by get_library_list().
CGetSetupHoldFU()
const functional_unit * technology_manager::CGetSetupHoldFU () const [private]
Return the functional unit used to compute the setup hold time.
Returns
the functional unit used to compute the setup hold time
Definition at line 518 of file technology_manager.cpp.
References get_fu(), LIBRARY_STD_FU, and THROW_ASSERT.
Referenced by CGetSetupHoldTime(), and CGetSetupHoldTimeStamp().
CGetSetupHoldTime()
double technology_manager::CGetSetupHoldTime () const
Return the setup hold time.
Returns
the setup hold time
Definition at line 525 of file technology_manager.cpp.
References CGetSetupHoldFU(), and THROW_ASSERT.
Referenced by FixCharacterization::Initialize().
CGetSetupHoldTimeStamp()
TimeStamp technology_manager::CGetSetupHoldTimeStamp () const
Return the characterization timestamp of the setup hold time.
Returns
the characterization timestamp of the setup hold time
Definition at line 534 of file technology_manager.cpp.
References CGetSetupHoldFU(), and functional_unit::characterization_timestamp.
Referenced by FixCharacterization::Initialize().
erase_library()
void technology_manager::erase_library (const std::string & Name)
Release the given library.
Parameters
Name is the name of the library to be erased.
Definition at line 490 of file technology_manager.cpp.
References add(), libraries, and library_map.
Referenced by get_library_list(), and mem_dominator_allocation::InternalExec().
get_area()
double technology_manager::get_area (const std::string & fu_name, const std::string & Library) const
Return the area for a given component.
Parameters
fu_name is the name of the component.
Library is library name where the unit is stored
Returns
the area for the library component
Definition at line 148 of file technology_manager.cpp.
References add(), builtins, get_fu(), and THROW_ASSERT.
Referenced by get_library_list().
get_execution_time()
double technology_manager::get_execution_time (const std::string & fu_name, const std::string & op_name, const std::string & Library) const
Return the execution time for a given operation type and a given component.
Parameters
fu_name is the name of the component.
op_name is the name of the operation.
res is true when there is the pair (fu_name, op_name), false otherwise.
Library is library name where the unit is stored
Returns
the execution time for (fu_name, op_name)
Definition at line 138 of file technology_manager.cpp.
References get_fu(), and THROW_ASSERT.
Referenced by get_library_list().
get_fu()
technology_nodeRef technology_manager::get_fu (const std::string & fu_name, const std::string & Library) const
Return the reference to a component given its name.
Parameters
fu_name is the name of the component.
Library is library name where the unit is stored
Returns
the reference to a component
Definition at line 120 of file technology_manager.cpp.
References library_map, and THROW_ASSERT.
Referenced by add_operation(), allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), OmpAllocation::AddPandaPthreadMutex(), FunctionalUnitStep::AnalyzeFu(), can_implement(), CGetSetupHoldFU(), AllocationInformation::EstimateControllerDelay(), FixCharacterization::Exec(), IR_lowering::expand_MC(), allocation::extract_bambu_provided(), RTLCharacterization::fix_execution_time_std(), RTLCharacterization::fix_muxes(), RTLCharacterization::fix_proxies_execution_time_std(), BackendFlow::GenerateSynthesisScripts(), get_area(), allocation::get_compliant_pipelined_unit(), AllocationInformation::get_correction_time(), get_execution_time(), allocation::get_fu(), AllocationInformation::get_fu(), get_initiation_time(), get_library_list(), AllocationInformation::InitializeMuxDB(), OmpAllocation::IntegrateTechnologyLibraries(), allocation::IntegrateTechnologyLibraries(), InitializeHLS::InternalExec(), add_library::InternalExec(), allocation::InternalExec(), AllocationInformation::mux_area_unit_raw(), AllocationInformation::mux_time_unit_raw(), and xload().
get_initiation_time()
ControlStep technology_manager::get_initiation_time (const std::string & fu_name, const std::string & op_name, const std::string & Library) const
Return the initiation time for a given operation type and a given component.
Parameters
fu_name is the name of the component.
op_name is the name of the operation.
res is true when there is the pair (fu_name, op_name), false otherwise.
Library is library name where the unit is stored
Returns
the initiation_time for (fu_name, op_name).
Definition at line 128 of file technology_manager.cpp.
References get_fu(), and THROW_ASSERT.
Referenced by get_library_list().
get_library()
std::string technology_manager::get_library (const std::string & Name) const
Return the higher priority library where the given component is stored.
Parameters
Name is the name of the component.
Returns
the identifier of the library where the unit is contained
empty string. it means that the cell is not contained into any library
Definition at line 455 of file technology_manager.cpp.
References libraries, library_map, and THROW_ASSERT.
Referenced by conn_binding::add_command_ports(), conn_binding::add_datapath_connection(), top_entity::add_input_register(), RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::AnalyzeFu(), computeResources(), fun_dominator_allocation::Exec(), FixCharacterization::Exec(), BackendFlow::GenerateSynthesisScripts(), allocation::get_fu(), AllocationInformation::get_fu(), get_library_list(), RTLCharacterization::Initialize(), allocation::IntegrateTechnologyLibraries(), TasteInterfaceGeneration::InternalExec(), and allocation::InternalExec().
get_library_list()
const std::vector<std::string>& technology_manager::get_library_list () const [inline]
Return the list of the libraries.
Returns
a vector containing the identifiers of the libraries contained into the technology manager
Definition at line 219 of file technology_manager.hpp.
References can_implement(), erase_library(), flopoco::filename, get_area(), get_execution_time(), get_fu(), get_initiation_time(), get_library(), get_library_manager(), is_library_manager(), IsBuiltin(), libraries, print(), xload(), and xwrite().
Referenced by GenerateFuList::Exec(), WriteTechnology::Exec(), FixCharacterization::Exec(), allocation::InternalExec(), and read_technology_File().
get_library_manager()
library_managerRef technology_manager::get_library_manager (const std::string & Name) const
Return the library data structure corresponding to the given library id.
Parameters
Name is the name of the library.
Returns
the reference to the data structure of the library
Definition at line 479 of file technology_manager.cpp.
References library_map, and THROW_ASSERT.
Referenced by FunctionalUnitStep::AnalyzeFu(), allocation::BuildProxyWrapper(), fun_dominator_allocation::Exec(), GenerateFuList::Exec(), WriteTechnology::Exec(), FixCharacterization::Exec(), allocation::extract_bambu_provided(), get_library_list(), RTLCharacterization::Initialize(), allocation::IntegrateTechnologyLibraries(), add_library::InternalExec(), allocation::InternalExec(), read_technology_library(), moduleGenerator::specialize_fu(), and xwrite().
is_library_manager()
bool technology_manager::is_library_manager (const std::string & Name) const
Check if a library is contained into the data structure.
Parameters
Name is the name of the library.
Returns
true if there is a data structure corresponding to the library name, false otherwise
Definition at line 485 of file technology_manager.cpp.
References library_map.
Referenced by get_library_list(), read_technology_library(), and xwrite().
IsBuiltin()
bool technology_manager::IsBuiltin (const std::string & component_name) const
Return true if a component is builtin.
Parameters
component_name is the name of the component
Returns
true if the component is builtin
Definition at line 513 of file technology_manager.cpp.
References builtins.
Referenced by get_library_list().
print()
void technology_manager::print (std::ostream & os) const
Function that prints the class technology_manager.
Definition at line 99 of file technology_manager.cpp.
References library_manager::get_library_fu(), libraries, and library_map.
Referenced by get_library_list(), LoadTechnology::PrintFinalIR(), and allocation::PrintInitialIR().
xload()
void technology_manager::xload (const xml_element * node, const target_deviceRef device)
Load a technology manager from an xml file.
Parameters
node is a node of the xml tree.
First part of the condition is for skip template
Definition at line 222 of file technology_manager.cpp.
References add(), debug_level, DEBUG_LEVEL_VERY_PEDANTIC, xml_child::get_children(), get_fu(), library_manager::get_library_fu(), library_manager::get_library_name(), INDENT_DBG_MEX, libraries, library_map, Param, library_manager::set_info(), SplitString(), STR, library_manager::xload(), and library_manager::XML.
Referenced by LoadDefaultTechnology::Exec(), get_library_list(), read_technology_File(), and target_device::xload().
xwrite()
void technology_manager::xwrite (xml_element * rootnode, TargetDevice_Type dv_type, const CustomOrderedSet< std::string > & libraries = CustomOrderedSet<std::string>())
add library elements operation node to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the operation is attached.
Set of libraries sorted by name
Definition at line 352 of file technology_manager.cpp.
References xml_document::create_root_node(), debug_level, DEBUG_LEVEL_PEDANTIC, flopoco::filename, library_manager::get_library_fu(), get_library_manager(), is_library_manager(), library_map, library_manager::set_info(), xml_document::write_to_file_formatted(), and library_manager::xwrite().
Referenced by WriteTechnology::Exec(), and get_library_list().
Friends And Related Function Documentation
allocation
friend class allocation [friend]
friend definition for class allocation
Definition at line 172 of file technology_manager.hpp.
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, const technology_manager & s) [friend]
Friend definition of the << operator.
Definition at line 365 of file technology_manager.hpp.
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const technology_managerRef & s) [friend]
Friend definition of the << operator.
Pointer version.
Definition at line 373 of file technology_manager.hpp.
Field Documentation
builtins
CustomSet<std::string> technology_manager::builtins [private]
The builtin components.
Definition at line 150 of file technology_manager.hpp.
Referenced by get_area(), and IsBuiltin().
debug_level
int technology_manager::debug_level [private]
The debug level for this class.
Definition at line 141 of file technology_manager.hpp.
Referenced by technology_manager(), xload(), and xwrite().
LEF
const unsigned int technology_manager::LEF = 1 << 2 [static]
Definition at line 130 of file technology_manager.hpp.
Referenced by write_technology_File().
LIB
const unsigned int technology_manager::LIB [static]
Definition at line 129 of file technology_manager.hpp.
Referenced by write_technology_File().
libraries
std::vector<std::string> technology_manager::libraries [private]
(reverse) ordered list of libraries; it gives a priority ordering for searching the nodes
Definition at line 147 of file technology_manager.hpp.
Referenced by add(), erase_library(), get_library(), get_library_list(), print(), and xload().
library_map
library_map_type technology_manager::library_map [private]
map between library name and the corresponding data structure
Definition at line 144 of file technology_manager.hpp.
Referenced by add(), add_operation(), erase_library(), get_fu(), get_library(), get_library_manager(), is_library_manager(), print(), xload(), and xwrite().
Param
const ParameterConstRef technology_manager::Param [private]
class containing all the parameters
Definition at line 138 of file technology_manager.hpp.
Referenced by add(), technology_manager(), and xload().
XML
const unsigned int technology_manager::XML = 1 << 0 [static]
Autoheader include.
STL include
Definition at line 128 of file technology_manager.hpp.
Referenced by read_technology_library(), and write_technology_File().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/technology_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/technology_manager.cpp