AsnParser Class Reference
#include <asn_parser.hpp>
Public Member Functions
AsnParser (const DesignFlowManagerConstRef design_flow_manager, const std::string &file_name, const application_managerRef AppM, const ParameterConstRef parameters)
Constructor.
~AsnParser () override
Destuctor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
void YYParse (const AsnParserDataRef data, const AsnFlexLexerRef lexer) const
Wrapper to yyparse.
Protected Attributes
const application_managerRef AppM
The application manager.
Additional Inherited Members
Detailed Description
Definition at line 72 of file asn_parser.hpp.
Constructor & Destructor Documentation
AsnParser()
AsnParser::AsnParser (const DesignFlowManagerConstRef design_flow_manager, const std::string & file_name, const application_managerRef AppM, const ParameterConstRef parameters)
Constructor.
Parameters
design_flow_manager is the design flow manager
file_name is the file to be parsed
AppM is the application manager
parameters is the set of input parameters
Definition at line 69 of file asn_parser.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and ~AsnParser().
 AsnParser()
AsnParser::~AsnParser () [override], [default]
Destuctor.
Referenced by AsnParser().
Member Function Documentation
Exec()
DesignFlowStep_Status AsnParser::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 77 of file asn_parser.cpp.
References AppM, ParserFlowStep::file_name, fileIO_istream_open(), refcount< T >::get(), DesignFlowStep::parameters, SUCCESS, THROW_ERROR, and YYParse().
YYParse()
void AsnParser::YYParse (const AsnParserDataRef data, const AsnFlexLexerRef lexer) const [protected]
Wrapper to yyparse.
Parameters
data is the data to be passed to the parser
lexer is the lexer
Referenced by Exec().
Field Documentation
AppM
const application_managerRef AsnParser::AppM [protected]
The application manager.
Definition at line 76 of file asn_parser.hpp.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/asn/asn_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/asn/asn_parser.cpp