bus_connection_o Class Reference
This class describes a generic bus connection.
#include <structural_objects.hpp>
Public Member Functions
bus_connection_o (int debug_level, const structural_objectRef o)
Constructor.
~bus_connection_o () override=default
destructor
void add_connection (structural_objectRef c)
Add a connection (e.g.
const structural_objectRef get_connection (unsigned int n) const
Return a connection.
unsigned int get_connections_size () const
Return the number of connections associated with the bus connection object.
void copy (structural_objectRef dest) const override
Perform a copy of the bus_connection_o.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override
Add a structural_object to an xml tree.
void print (std::ostream &os) const override
Print the bus_connection_o (for debug purpose)
Private Attributes
std::vector< structural_objectRef > connections
List of connections associated with the bus.
Additional Inherited Members
Detailed Description
This class describes a generic bus connection.
A bus_connection_o is a a vector of signals or channels [1..n].
Definition at line 2452 of file structural_objects.hpp.
Constructor & Destructor Documentation
bus_connection_o()
bus_connection_o::bus_connection_o (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the bus_connection_o.
Definition at line 4206 of file structural_objects.cpp.
 bus_connection_o()
bus_connection_o::~bus_connection_o () [override], [default]
destructor
Member Function Documentation
add_connection()
void bus_connection_o::add_connection (structural_objectRef c)
Add a connection (e.g.
a signal or a channel) to the bus connection object.
Parameters
c is a signal connection
Definition at line 4210 of file structural_objects.cpp.
References connections, and THROW_ASSERT.
copy()
void bus_connection_o::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the bus_connection_o.
Parameters
dest destination object.
someone has to take care of connections
Reimplemented from structural_object.
Definition at line 4260 of file structural_objects.cpp.
References structural_object::copy().
find_isomorphic()
structural_objectRef bus_connection_o::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Definition at line 4227 of file structural_objects.cpp.
References THROW_ERROR.
find_member()
structural_objectRef bus_connection_o::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Definition at line 4233 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, connections, constant_o_K, data_o_K, event_o_K, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, and THROW_ERROR.
get_connection()
const structural_objectRef bus_connection_o::get_connection (unsigned int n) const
Return a connection.
Parameters
n is the index of the connection
Definition at line 4216 of file structural_objects.cpp.
References connections, and THROW_ASSERT.
Referenced by port_o::fix_port_properties().
get_connections_size()
unsigned int bus_connection_o::get_connections_size () const
Return the number of connections associated with the bus connection object.
Definition at line 4222 of file structural_objects.cpp.
References connections.
Referenced by port_o::fix_port_properties().
print()
void bus_connection_o::print (std::ostream & os) const [override], [virtual]
Print the bus_connection_o (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Definition at line 4277 of file structural_objects.cpp.
References connections, structural_object::convert_so_short(), structural_object::PP, and structural_object::print().
xload()
void bus_connection_o::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
Reimplemented from structural_object.
Definition at line 4266 of file structural_objects.cpp.
References structural_object::xload().
xwrite()
void bus_connection_o::xwrite (xml_element * rootnode) [override], [virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Definition at line 4271 of file structural_objects.cpp.
References xml_child::add_child_element(), structural_object::get_kind_text(), and structural_object::xwrite().
Field Documentation
connections
std::vector<structural_objectRef> bus_connection_o::connections [private]
List of connections associated with the bus.
Definition at line 2455 of file structural_objects.hpp.
Referenced by add_connection(), find_member(), get_connection(), get_connections_size(), and print().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp