map_wrapper Class Reference
Main class for wrapping ISE tools by Xilinx.
#include <map_wrapper.hpp>
Public Member Functions
map_wrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~map_wrapper () override
Destructor.
Protected Member Functions
void init_reserved_vars () override
Initializes the reserved variables.
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Additional Inherited Members
Detailed Description
Main class for wrapping ISE tools by Xilinx.
Definition at line 59 of file map_wrapper.hpp.
Constructor & Destructor Documentation
map_wrapper()
map_wrapper::map_wrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Header include.
Parameters
Param is the set of parameters
Definition at line 58 of file map_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, and ~map_wrapper().
 map_wrapper()
map_wrapper::~map_wrapper () [override], [default]
Destructor.
Referenced by map_wrapper().
Member Function Documentation
EvaluateVariables()
void map_wrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 72 of file map_wrapper.cpp.
References DesignParameters::assign(), SynthesisTool::output_dir, PARAM_map_report, PARAM_map_tmpdir, PARAM_top_id, and DesignParameters::parameter_values.
get_command_line()
std::string map_wrapper::get_command_line (const DesignParametersRef & dp) const [override], [protected], [virtual]
Returns the proper command line.
Implements SynthesisTool.
Definition at line 79 of file map_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), XilinxWrapper::toString(), and SynthesisTool::xml_tool_options.
init_reserved_vars()
void map_wrapper::init_reserved_vars () [override], [protected], [virtual]
Initializes the reserved variables.
Reimplemented from SynthesisTool.
Definition at line 66 of file map_wrapper.cpp.
References ADD_RES_VAR, SynthesisTool::init_reserved_vars(), and PARAM_map_tmpdir.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/ise/map_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/xilinx/ise/map_wrapper.cpp