/home/osboxes/bambu/PandA-bambu/src/utility/math_function.hpp File Reference
mathematical utility function not provided by standard libraries
#include `augmented_vector.hpp`
#include <boost/version.hpp>
#include <boost/math/common_factor_rt.hpp>
Macros
#define EXACT_POWER_OF_2_OR_ZERO_P(x) (((x) & ((x)-1)) == 0)
Test whether a value is zero of a power of two.
Functions
long double get_point_line_distance (const AugmentedVector< long double > &point, AugmentedVector< long double > &line_point1, AugmentedVector< long double > &line_point2)
Utility include.
template<typename Integer >
Integer GreatestCommonDivisor (const Integer first, const Integer second)
Return the greatest common divisor.
template<typename Integer >
Integer LeastCommonMultiple (const Integer first, const Integer second)
Return the least common multiple of two integers.
unsigned int resize_to_1_8_16_32_64_128_256_512 (unsigned int value)
unsigned int compute_n_bytes (unsigned bitsize)
int floor_log2 (unsigned long long int x)
Given X, an unsigned number, return the largest int Y such that 2**Y <= X. If X is 0, return -1.
int exact_log2 (unsigned long long int x)
Return the logarithm of X, base 2, considering X unsigned, if X is a power of 2.
int ceil_log2 (unsigned long long int x)
Return the smallest n such that 2**n >= X.
Detailed Description
mathematical utility function not provided by standard libraries
Author
Marco Lattuada lattuada@elet.polimi.it $Revision$ $Date$ Last modified by $Author$
Macro Definition Documentation
EXACT_POWER_OF_2_OR_ZERO_P
#define EXACT_POWER_OF_2_OR_ZERO_P(x) (((x) & ((x)-1)) == 0)
Test whether a value is zero of a power of two.
Definition at line 122 of file math_function.hpp.
Referenced by IR_lowering::division_by_a_constant(), and IR_lowering::expand_MC().
Function Documentation
ceil_log2()
int ceil_log2 (unsigned long long int x) [inline]
Return the smallest n such that 2**n >= X.
Definition at line 158 of file math_function.hpp.
References floor_log2().
Referenced by top_entity_cs::add_context_switch_port(), top_entity_cs::add_context_switch_port_kernel(), top_entity_cs::add_input_register(), datapath_cs::add_ports(), controller_cs::add_selector_register_file_port(), top_entity_parallel_cs::BW_loop_iter(), choose_multiplier(), fu_binding_cs::connect_selector_kernel(), IR_lowering::division_by_a_constant(), mem_dominator_allocation_cs::Exec(), fu_binding_cs::instantiate_component_kernel(), datapath_parallel_cs::instantiate_component_parallel(), cs_interface::instantiate_component_parallel(), datapath_parallel_cs::InternalExec(), fu_binding_cs::set_atomic_memory_parameter(), and reg_binding_cs::specialise_reg().
compute_n_bytes()
unsigned int compute_n_bytes (unsigned bitsize) [inline]
Definition at line 116 of file math_function.hpp.
Referenced by memory::add_internal_symbol(), IR_lowering::array_ref_lowering(), memory::compute_next_base_address(), DiscrepancyAnalysisCWriter::DeclareLocalVariables(), mem_dominator_allocation::InternalExec(), and DiscrepancyAnalysisCWriter::WriteExtraInitCode().
exact_log2()
int exact_log2 (unsigned long long int x) [inline]
Return the logarithm of X, base 2, considering X unsigned, if X is a power of 2.
Otherwise, returns -1.
Definition at line 150 of file math_function.hpp.
References floor_log2().
Referenced by synth_mult().
floor_log2()
int floor_log2 (unsigned long long int x) [inline]
Given X, an unsigned number, return the largest int Y such that 2**Y <= X. If X is 0, return -1.
Definition at line 125 of file math_function.hpp.
Referenced by ceil_log2(), IR_lowering::division_by_a_constant(), exact_log2(), IR_lowering::expand_MC(), IR_lowering::expand_sdiv_pow2(), IR_lowering::expand_smod_pow2(), and synth_mult().
get_point_line_distance()
long double get_point_line_distance (const AugmentedVector< long double > & point, AugmentedVector< long double > & line_point1, AugmentedVector< long double > & line_point2)
Utility include.
Return the distance between a point and a line (represented as a couple of points) in a n-dimensional space
Header include
Definition at line 57 of file math_function.cpp.
References AugmentedVector< T >::size(), and THROW_ASSERT.
GreatestCommonDivisor()
template<typename Integer >
Integer GreatestCommonDivisor (const Integer first, const Integer second)
Return the greatest common divisor.
Parameters
first is the first operand
second is the second operand
Returns
the greatest common divisor of first and second
Definition at line 68 of file math_function.hpp.
LeastCommonMultiple()
template<typename Integer >
Integer LeastCommonMultiple (const Integer first, const Integer second)
Return the least common multiple of two integers.
Parameters
first is the first operand
second is the second operand
Returns
the least common multiple of first and second
Definition at line 84 of file math_function.hpp.
resize_to_1_8_16_32_64_128_256_512()
unsigned int resize_to_1_8_16_32_64_128_256_512 (unsigned int value) [inline]
Definition at line 93 of file math_function.hpp.
References THROW_ERROR.
Referenced by FunctionalUnitStep::AnalyzeFu(), StorageValueInformation::are_value_bitsize_compatible(), mux_connection_binding::determine_connection(), AllocationInformation::estimate_mux_area(), AllocationInformation::estimate_mux_time(), AllocationInformation::estimate_muxNto1_area(), AllocationInformation::estimate_muxNto1_delay(), IR_lowering::expand_MC(), memory_allocation::finalize_memory_allocation(), AllocationInformation::get_correction_time(), AllocationInformation::GetCondExprTimeLatency(), AllocationInformation::GetCycleLatency(), AllocationInformation::GetNodeTypePrec(), AllocationInformation::GetPhiConnectionLatency(), AllocationInformation::GetStatementArea(), AllocationInformation::GetTimeLatency(), dead_code_elimination::InternalExec(), IR_lowering::InternalExec(), Bit_Value_opt::optimize(), hls_div_cg_ext::recursive_examinate(), resize_to_8_or_greater(), MinimalInterfaceTestbench::write_file_reading_operations(), and TestbenchGenerationBaseStep::write_output_checks().