fun_dominator_allocation Class Reference
#include <fun_dominator_allocation.hpp>
Public Member Functions
fun_dominator_allocation (const ParameterConstRef Param, const HLS_managerRef HLSMgr, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type=HLSFlowStep_Type::DOMINATOR_FUNCTION_ALLOCATION)
Constructor.
~fun_dominator_allocation () override
Destructor.
DesignFlowStep_Status Exec () override
Execute the step.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Protected Attributes
bool already_executed
True if this step has yet been executed.
Additional Inherited Members
Detailed Description
Definition at line 49 of file fun_dominator_allocation.hpp.
Constructor & Destructor Documentation
fun_dominator_allocation()
fun_dominator_allocation::fun_dominator_allocation (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, const DesignFlowManagerConstRef _design_flow_manager, const HLSFlowStep_Type _hls_flow_step_type = HLSFlowStep_Type::DOMINATOR_FUNCTION_ALLOCATION)
Constructor.
Autoheader include.
. include Header include algorithms/domainance include behavior include design_flows include design_flows/codesign include frontend_analysis includes HLS include HLS/function_allocation includes technology include technology/physical_library includes tree include utility include
Definition at line 109 of file fun_dominator_allocation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~fun_dominator_allocation().
 fun_dominator_allocation()
fun_dominator_allocation::~fun_dominator_allocation () [override], [default]
Destructor.
Referenced by fun_dominator_allocation().
Member Function Documentation
ComputeRelationships()
void fun_dominator_allocation::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 117 of file fun_dominator_allocation.cpp.
References HLS_step::ComputeRelationships(), ApplicationFrontendFlowStep::ComputeSignature(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
Exec()
DesignFlowStep_Status fun_dominator_allocation::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
the analysis has to be performed only on the reachable functions
we do not need the exit vertex since the post-dominator graph is not used
compute the number of instances for each function
find the common dominator and decide where to allocate
find the common dominator between two candidates
really allocate
add proxies
Implements DesignFlowStep.
Reimplemented in OmpFunctionAllocation, and OmpFunctionAllocationCS.
Definition at line 165 of file fun_dominator_allocation.cpp.
References already_executed, FunctionBehavior::CGetBehavioralHelper(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, library_manager::get_fu(), BehavioralHelper::get_function_name(), technology_manager::get_library(), technology_manager::get_library_manager(), target_manager::get_technology_manager(), HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, INFINITE_UINT, insert(), tree_helper::is_a_nop_function_decl(), NULL_VERTEX, DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERBOSE, DesignFlowStep::parameters, PRINT_DBG_MEX, PRINT_OUT_MEX, STR, SUCCESS, THROW_ASSERT, UNCHANGED, and WORK_LIBRARY.
Referenced by OmpFunctionAllocation::Exec(), and OmpFunctionAllocationCS::Exec().
HasToBeExecuted()
bool fun_dominator_allocation::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 414 of file fun_dominator_allocation.cpp.
References already_executed.
Field Documentation
already_executed
bool fun_dominator_allocation::already_executed [protected]
True if this step has yet been executed.
Definition at line 53 of file fun_dominator_allocation.hpp.
Referenced by Exec(), and HasToBeExecuted().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/function_allocation/fun_dominator_allocation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/function_allocation/fun_dominator_allocation.cpp