/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/vcd_trace_head.cpp File Reference
#include `vcd_trace_head.hpp`
#include `hls.hpp`
#include `hls_manager.hpp`
#include `storage_value_information.hpp`
#include `state_transition_graph.hpp`
#include `state_transition_graph_manager.hpp`
#include `tree_manager.hpp`
#include `tree_node.hpp`
#include `exceptions.hpp`
#include `string_manipulation.hpp`
#include <functional>
#include <utility>
Functions
static bool is_valid_state_string (const std::string &s, bool one_hot_fsm_encoding)
static size_t compute_state_id (const std::string &s, bool one_hot_fsm_encoding)
static bool is_binary_string_repr (const std::string &s, unsigned int id, bool one_hot_fsm_encoding)
static bool string_represents_one_of_the_states (const std::string &val, const CustomOrderedSet< unsigned int > &state_ids, bool one_hot_fsm_encoding)
static bool is_exec (const sig_variation &state_var, const DiscrepancyOpInfo &i, bool one_hot_fsm_encoding)
static bool is_start (const sig_variation &state_var, const DiscrepancyOpInfo &i, bool one_hot_fsm_encoding)
static bool all_ones (const std::string &s)
static bool var_has_value_ones (const sig_variation &v)
static bool var_is_later_or_equal (const sig_variation &v, const unsigned long long time)
Function Documentation
all_ones()
static bool all_ones (const std::string & s) [static]
Definition at line 140 of file vcd_trace_head.cpp.
Referenced by var_has_value_ones().
compute_state_id()
static size_t compute_state_id (const std::string & s, bool one_hot_fsm_encoding) [static]
Definition at line 88 of file vcd_trace_head.cpp.
References is_valid_state_string(), and THROW_ERROR.
Referenced by is_binary_string_repr(), and vcd_trace_head::update().
is_binary_string_repr()
static bool is_binary_string_repr (const std::string & s, unsigned int id, bool one_hot_fsm_encoding) [static]
Definition at line 104 of file vcd_trace_head.cpp.
References compute_state_id(), is_valid_state_string(), and THROW_ERROR.
Referenced by string_represents_one_of_the_states(), and vcd_trace_head::update().
is_exec()
static bool is_exec (const sig_variation & state_var, const DiscrepancyOpInfo & i, bool one_hot_fsm_encoding) [static]
Definition at line 120 of file vcd_trace_head.cpp.
References DiscrepancyOpInfo::exec_states, DiscrepancyOpInfo::op_id, DiscrepancyOpInfo::stg_fun_id, STR, string_represents_one_of_the_states(), THROW_ASSERT, and sig_variation::value.
Referenced by vcd_trace_head::unbounded_find_end_time().
is_start()
static bool is_start (const sig_variation & state_var, const DiscrepancyOpInfo & i, bool one_hot_fsm_encoding) [static]
Definition at line 126 of file vcd_trace_head.cpp.
References DiscrepancyOpInfo::end_states, DiscrepancyOpInfo::op_id, DiscrepancyOpInfo::start_states, DiscrepancyOpInfo::stg_fun_id, STR, string_represents_one_of_the_states(), THROW_ASSERT, and sig_variation::value.
Referenced by vcd_trace_head::unbounded_find_end_time(), and vcd_trace_head::update().
is_valid_state_string()
static bool is_valid_state_string (const std::string & s, bool one_hot_fsm_encoding) [static]
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Definition at line 62 of file vcd_trace_head.cpp.
Referenced by compute_state_id(), and is_binary_string_repr().
string_represents_one_of_the_states()
static bool string_represents_one_of_the_states (const std::string & val, const CustomOrderedSet< unsigned int > & state_ids, bool one_hot_fsm_encoding) [static]
Definition at line 112 of file vcd_trace_head.cpp.
References is_binary_string_repr().
Referenced by is_exec(), and is_start().
var_has_value_ones()
static bool var_has_value_ones (const sig_variation & v) [static]
Definition at line 145 of file vcd_trace_head.cpp.
References all_ones(), and sig_variation::value.
Referenced by vcd_trace_head::update().
var_is_later_or_equal()
static bool var_is_later_or_equal (const sig_variation & v, const unsigned long long time) [static]
Definition at line 150 of file vcd_trace_head.cpp.
Referenced by vcd_trace_head::advance().