TopEntityMemoryMapped Class Reference
Build a wrapper layer on the top entity implementing the momory mapped interface.
#include <TopEntityMemoryMapped.hpp>
Public Member Functions
TopEntityMemoryMapped (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~TopEntityMemoryMapped () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Private Member Functions
void allocate_parameters () const
Allocates the in/out parameters of the module as internal registers.
void insertMemoryMappedRegister (structural_managerRef SM, structural_objectRef wrappedObj)
void insertStartDoneLogic (structural_managerRef SM, structural_objectRef wrapperObj)
void insertStatusRegister (structural_managerRef SM, structural_objectRef wrappedObj)
void forwardPorts (structural_managerRef SM, structural_objectRef wrappedObj)
void resizing_IO (module *fu_module, unsigned int max_n_ports) const
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Attributes
std::list< std::string > ParametersName
std::list< structural_objectRef > AddedComponents
bool needMemoryMappedRegisters {false}
bool is_root_function {false}
true when the module is a root function
Additional Inherited Members
Detailed Description
Build a wrapper layer on the top entity implementing the momory mapped interface.
This step augment the top entity with the logic necessary to build the memory mapped interface when the top function needs it (i.e. when it will be attached to a wishbone bus).
The top entity is augmented adding:
A memory mapped control register.
A memery mapped register for each function parameters.
A memory mapped register storing the function return value.
If the bus interface is MINIMAL the top function will not contain the memory mapped registers but it will contain the instances of the additional tops.
Definition at line 64 of file TopEntityMemoryMapped.hpp.
Constructor & Destructor Documentation
TopEntityMemoryMapped()
TopEntityMemoryMapped::TopEntityMemoryMapped (const ParameterConstRef _parameters, const HLS_managerRef _HLSMgr, unsigned int _funId, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param The set of parameters.
HLSMgr The HLS manager.
funId The tree index of the synthesized function.
. include behavior include circuit includes HLS include HLS/binding/module include HLS/function_allocation include HLS/memory includes STL include technology include technology/physical_library include tree include
Definition at line 79 of file TopEntityMemoryMapped.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, TOP_ENTITY_MEMORY_MAPPED_CREATION, and ~TopEntityMemoryMapped().
 TopEntityMemoryMapped()
TopEntityMemoryMapped::~TopEntityMemoryMapped () [override], [default]
Destructor.
Referenced by TopEntityMemoryMapped().
Member Function Documentation
allocate_parameters()
void TopEntityMemoryMapped::allocate_parameters () const [private]
Allocates the in/out parameters of the module as internal registers.
Definition at line 201 of file TopEntityMemoryMapped.cpp.
References memory::add_memory_parameter(), FunctionBehavior::CGetBehavioralHelper(), connect_with_signal_name(), connectClockAndReset(), hls::functionId, BehavioralHelper::get_function_index(), BehavioralHelper::get_parameters(), BehavioralHelper::GetFunctionReturnType(), HLSFunctionStep::HLS, HLS_step::HLSMgr, setBusSizes(), STR, and hls::top.
Referenced by InternalExec().
forwardPorts()
void TopEntityMemoryMapped::forwardPorts (structural_managerRef SM, structural_objectRef wrappedObj) [private]
Definition at line 443 of file TopEntityMemoryMapped.cpp.
References structural_manager::add_connection(), FunctionBehavior::CGetBehavioralHelper(), DONE_PORT_NAME, structural_object::find_member(), hls::functionId, HLSFunctionStep::funId, structural_manager::get_circ(), BehavioralHelper::GetFunctionReturnType(), HLSFunctionStep::HLS, ParametersName, port_o_K, RETURN_PORT_NAME, and START_PORT_NAME.
Referenced by InternalExec().
Initialize()
void TopEntityMemoryMapped::Initialize () [override], [private], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 87 of file TopEntityMemoryMapped.cpp.
References AddedComponents, HLSFunctionStep::funId, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), is_root_function, needMemoryMappedRegisters, DesignFlowStep::parameters, and WB4_INTERFACE_GENERATION.
insertMemoryMappedRegister()
void TopEntityMemoryMapped::insertMemoryMappedRegister (structural_managerRef SM, structural_objectRef wrappedObj) [private]
Definition at line 233 of file TopEntityMemoryMapped.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), AddedComponents, FunctionBehavior::CGetBehavioralHelper(), connect_with_signal_name(), connectClockAndReset(), DONE_PORT_NAME, structural_object::find_member(), hls::functionId, HLSFunctionStep::funId, structural_manager::get_circ(), structural_object::get_typeRef(), BehavioralHelper::GetFunctionReturnType(), HLSFunctionStep::HLS, hls::HLS_T, is_root_function, fu_binding::manage_module_ports(), MEM_ACC_NN, MEMORY_MAPPED_REGISTER_FU, MEMORY_MAPPED_REGISTERN_FU, MUX_GATE_STD, DesignFlowStep::parameters, port_o_K, BehavioralHelper::PrintVariable(), resizing_IO(), RETURN_MM_REGISTER_FU, RETURN_MM_REGISTERN_FU, RETURN_PORT_NAME, hls::Rfu, setBusSizes(), signal_o_K, STD_GET_SIZE, and STR.
Referenced by InternalExec().
insertStartDoneLogic()
void TopEntityMemoryMapped::insertStartDoneLogic (structural_managerRef SM, structural_objectRef wrapperObj) [private]
Definition at line 330 of file TopEntityMemoryMapped.cpp.
References structural_manager::add_connection(), AddedComponents, connect_with_signal_name(), connectClockAndReset(), DONE_PORT_NAME, structural_object::find_member(), structural_manager::get_circ(), HLSFunctionStep::HLS, hls::HLS_T, is_root_function, fu_binding::manage_module_ports(), MEM_ACC_NN, NOTYFY_CALLER_MINIMAL_FU, NOTYFY_CALLER_MINIMALN_FU, OR_GATE_STD, DesignFlowStep::parameters, port_o_K, resizing_IO(), hls::Rfu, setBusSizes(), signal_o_K, and START_PORT_NAME.
Referenced by InternalExec().
insertStatusRegister()
void TopEntityMemoryMapped::insertStatusRegister (structural_managerRef SM, structural_objectRef wrappedObj) [private]
Definition at line 379 of file TopEntityMemoryMapped.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), AddedComponents, connectClockAndReset(), DONE_PORT_NAME, structural_object::find_member(), hls::functionId, structural_manager::get_circ(), structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_T, fu_binding::manage_module_ports(), MEM_ACC_NN, DesignFlowStep::parameters, port_o_K, resizing_IO(), hls::Rfu, structural_object::set_type(), setBusSizes(), START_PORT_NAME, STATUS_REGISTER_FU, STATUS_REGISTER_NO_NOTIFIED_FU, STATUS_REGISTER_NO_NOTIFIEDN_FU, and STATUS_REGISTERN_FU.
Referenced by InternalExec().
InternalExec()
DesignFlowStep_Status TopEntityMemoryMapped::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Reimplemented from top_entity.
Definition at line 132 of file TopEntityMemoryMapped.cpp.
References AddedComponents, allocate_parameters(), FunctionBehavior::CGetBehavioralHelper(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, forwardPorts(), HLSFunctionStep::funId, GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), structural_object::get_id(), BehavioralHelper::get_parameters(), structural_object::get_typeRef(), HLSFunctionStep::HLS, HLS_step::HLSMgr, structural_type_descriptor::id_type, INDENT_DBG_MEX, insertMemoryMappedRegister(), insertStartDoneLogic(), insertStatusRegister(), top_entity::InternalExec(), fu_binding::manage_memory_ports_parallel_chained(), fu_binding::manage_module_ports(), needMemoryMappedRegisters, DesignFlowStep::parameters, ParametersName, BehavioralHelper::PrintVariable(), memory::propagate_memory_parameters(), propagateInterface(), hls::Rfu, structural_object::set_id(), structural_object::set_owner(), structural_manager::set_top_info(), structural_object::set_type(), STR, SUCCESS, and hls::top.
resizing_IO()
void TopEntityMemoryMapped::resizing_IO (module * fu_module, unsigned int max_n_ports) const [private]
Definition at line 99 of file TopEntityMemoryMapped.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, module::get_in_port(), module::get_in_port_size(), structural_object::get_kind(), module::get_out_port(), module::get_out_port_size(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, hls::Param, ParametersName, port_vector_o_K, propagateInterface(), port_o::resize_busport(), and top_entity::SM.
Referenced by insertMemoryMappedRegister(), insertStartDoneLogic(), and insertStatusRegister().
Field Documentation
AddedComponents
std::list<structural_objectRef> TopEntityMemoryMapped::AddedComponents [private]
Definition at line 101 of file TopEntityMemoryMapped.hpp.
Referenced by Initialize(), insertMemoryMappedRegister(), insertStartDoneLogic(), insertStatusRegister(), and InternalExec().
is_root_function
bool TopEntityMemoryMapped::is_root_function {false} [private]
true when the module is a root function
Definition at line 105 of file TopEntityMemoryMapped.hpp.
Referenced by Initialize(), insertMemoryMappedRegister(), and insertStartDoneLogic().
needMemoryMappedRegisters
bool TopEntityMemoryMapped::needMemoryMappedRegisters {false} [private]
Definition at line 102 of file TopEntityMemoryMapped.hpp.
Referenced by Initialize(), and InternalExec().
ParametersName
std::list<std::string> TopEntityMemoryMapped::ParametersName [private]
Definition at line 100 of file TopEntityMemoryMapped.hpp.
Referenced by forwardPorts(), InternalExec(), and resizing_IO().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/TopEntityMemoryMapped.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/TopEntityMemoryMapped.cpp