/home/osboxes/bambu/PandA-bambu/documentation/tutorial_fpt_2017/optimizations/third/softfloat.c File Reference
#include `milieu.h`
#include `softfloat.h`
#include `softfloat-macros`
#include `softfloat-specialize`
Functions
INLINE bits64 extractFloat64Frac (float64 a)
INLINE int16 extractFloat64Exp (float64 a)
INLINE flag extractFloat64Sign (float64 a)
static void normalizeFloat64Subnormal (bits64 aSig, int16 *zExpPtr, bits64 *zSigPtr)
INLINE float64 packFloat64 (flag zSign, int16 zExp, bits64 zSig)
static float64 roundAndPackFloat64 (flag zSign, int16 zExp, bits64 zSig)
float64 float64_div (float64 a, float64 b)
Variables
int8 float_rounding_mode = float_round_nearest_even
int8 float_exception_flags = 0
Function Documentation
extractFloat64Exp()
INLINE int16 extractFloat64Exp (float64 a)
Definition at line 94 of file softfloat.c.
References INLINE.
extractFloat64Frac()
INLINE bits64 extractFloat64Frac (float64 a)
Definition at line 82 of file softfloat.c.
References INLINE, and LIT64.
extractFloat64Sign()
INLINE flag extractFloat64Sign (float64 a)
Definition at line 106 of file softfloat.c.
float64_div()
float64 float64_div (float64 a, float64 b)
Definition at line 241 of file softfloat.c.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_divbyzero, float_flag_invalid, LIT64, normalizeFloat64Subnormal(), packFloat64(), and roundAndPackFloat64().
normalizeFloat64Subnormal()
static void normalizeFloat64Subnormal (bits64 aSig, int16 * zExpPtr, bits64 * zSigPtr) [static]
Definition at line 121 of file softfloat.c.
References INLINE.
Referenced by float64_div().
packFloat64()
INLINE float64 packFloat64 (flag zSign, int16 zExp, bits64 zSig)
Definition at line 143 of file softfloat.c.
roundAndPackFloat64()
static float64 roundAndPackFloat64 (flag zSign, int16 zExp, bits64 zSig) [static]
Definition at line 173 of file softfloat.c.
References float_exception_flags, float_flag_inexact, float_flag_overflow, float_flag_underflow, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, float_tininess_before_rounding, LIT64, and packFloat64().
Referenced by float64_div().
Variable Documentation
float_exception_flags
int8 float_exception_flags = 0
Definition at line 58 of file softfloat.c.
float_rounding_mode
int8 float_rounding_mode = float_round_nearest_even
Definition at line 57 of file softfloat.c.