ipa_point_to_analysis Class Reference
#include <ipa_point_to_analysis.hpp>
Public Member Functions
ipa_point_to_analysis (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~ipa_point_to_analysis () override
Destructor.
DesignFlowStep_Status Exec () override
Determines the variables that require a memory access.
Private Member Functions
void compute_function_topological_order (std::list< unsigned int > &sort_list)
compute the topological order of the functions called by the top function
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
const tree_managerConstRef TM
The tree manager.
Additional Inherited Members
Detailed Description
Definition at line 56 of file ipa_point_to_analysis.hpp.
Constructor & Destructor Documentation
ipa_point_to_analysis()
ipa_point_to_analysis::ipa_point_to_analysis (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
design_flow_manager is the design flow manager
parameters is the set of input parameters
Definition at line 132 of file ipa_point_to_analysis.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~ipa_point_to_analysis().
 ipa_point_to_analysis()
ipa_point_to_analysis::~ipa_point_to_analysis () [override], [default]
Destructor.
Referenced by ipa_point_to_analysis().
Member Function Documentation
compute_function_topological_order()
void ipa_point_to_analysis::compute_function_topological_order (std::list< unsigned int > & sort_list) [private]
compute the topological order of the functions called by the top function
check if the root function is an empty function: compiler optimizations may kill everything
the analysis has to be performed only on the reachable functions
Definition at line 88 of file ipa_point_to_analysis.cpp.
References DEBUG_LEVEL_VERBOSE, tree_helper::is_a_nop_function_decl(), OUTPUT_LEVEL_VERBOSE, test_panda::parameters, PRINT_DBG_MEX, THROW_ERROR, and THROW_WARNING.
Referenced by Exec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > ipa_point_to_analysis::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 140 of file ipa_point_to_analysis.cpp.
References FrontendFlowStep::ALL_FUNCTIONS, BUILD_VIRTUAL_PHI, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, MEM_CG_EXT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, THROW_UNREACHABLE, USE_COUNTING, and FrontendFlowStep::WHOLE_APPLICATION.
Exec()
DesignFlowStep_Status ipa_point_to_analysis::Exec () [override], [virtual]
Determines the variables that require a memory access.
array storing the functions for which the address has been taken by some gimple node.
compute ssa variables that may work as a pointer variables first compute seeds
may use pointers
reserve priorities for the function parameters
may use pointers
do nothing
print all ssa vars pointing to something
Implements ApplicationFrontendFlowStep.
Definition at line 225 of file ipa_point_to_analysis.cpp.
References FrontendFlowStep::AppM, compute_function_topological_order(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, functions, GET_INDEX_NODE, tree_helper::get_integer_cst_value(), GET_NODE, INDENT_DBG_MEX, worklist_queue::insert(), tree_helper::is_a_pointer(), tree_helper::name_function(), DesignFlowStep::output_level, OUTPUT_LEVEL_VERBOSE, tree_helper::print_function_name(), sl, STR, SUCCESS, THROW_ASSERT, THROW_ERROR, THROW_WARNING, TM, ToString(), and tree_node::ToString().
Field Documentation
TM
const tree_managerConstRef ipa_point_to_analysis::TM [private]
The tree manager.
Definition at line 60 of file ipa_point_to_analysis.hpp.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/ipa_point_to_analysis.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/ipa_point_to_analysis.cpp