NI_SSA_liveness Class Reference
#include <NI_SSA_liveness.hpp>
Public Member Functions
NI_SSA_liveness (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~NI_SSA_liveness () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performes the liveness analysis.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Private Member Functions
void Up_and_Mark (blocRef B, tree_nodeRef v, statement_list *sl)
Algorithm 5: Explore all paths from a variable’s use to its definition.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 66 of file NI_SSA_liveness.hpp.
Constructor & Destructor Documentation
NI_SSA_liveness()
NI_SSA_liveness::NI_SSA_liveness (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the index of the function
design_flow_manager is the design flow manager
Behavior include Parameter include STD include Tree include
Definition at line 91 of file NI_SSA_liveness.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~NI_SSA_liveness().
 NI_SSA_liveness()
NI_SSA_liveness::~NI_SSA_liveness () [override], [default]
Destructor.
Referenced by NI_SSA_liveness().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > NI_SSA_liveness::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 99 of file NI_SSA_liveness.cpp.
References COMPLETE_BB_GRAPH, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and USE_COUNTING.
Initialize()
void NI_SSA_liveness::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 261 of file NI_SSA_liveness.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::bb_version, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, sl, and THROW_ASSERT.
InternalExec()
DesignFlowStep_Status NI_SSA_liveness::InternalExec () [override], [virtual]
Performes the liveness analysis.
for each basic block B in CFG do > Consider all blocks successively
for each v ∈ PhiUses(B) do > Used in the φ of a successor block
in the original algorithm the live out has all the PhiUses of B, that is: LiveOut(B) = LiveOut(B) ∪ {v}
for each v used in B (φ excluded) do > Traverse B to find all uses
print the analysis result
Implements FunctionFrontendFlowStep.
Definition at line 173 of file NI_SSA_liveness.cpp.
References FrontendFlowStep::AppM, tree_helper::ComputeSsaUses(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionFrontendFlowStep::function_id, BehavioralHelper::get_function_name(), GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_helper::is_virtual(), phi, PRINT_DBG_MEX, PRINT_DBG_STRING, BehavioralHelper::PrintVariable(), sl, STR, SUCCESS, THROW_ASSERT, and Up_and_Mark().
Up_and_Mark()
void NI_SSA_liveness::Up_and_Mark (blocRef B, tree_nodeRef v, statement_list * sl) [private]
Algorithm 5: Explore all paths from a variable’s use to its definition.
if def(v) ∈ B (φ excluded) then return > Killed in the block, stop
if v ∈ LiveIn(B) then return > Propagation already done, stop
LiveIn(B) = LiveIn(B) ∪ {v}
if v ∈ PhiDefs(B) then return > Do not propagate φ definitions
for each P ∈ CFG_preds(B) do > Propagate backward
Definition at line 134 of file NI_SSA_liveness.cpp.
References GET_INDEX_NODE, GET_NODE, statement_list::list_of_bloc, phi, STR, and THROW_ASSERT.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/NI_SSA_liveness.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/NI_SSA_liveness.cpp