BBReachabilityComputation Class Reference
Superclass include.
#include <bb_reachability_computation.hpp>
Public Member Functions
BBReachabilityComputation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~BBReachabilityComputation () override
Destructor.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
DesignFlowStep_Status InternalExec () override
Computes the reachability between operations according to the control flow graph WITHOUT feedback.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Computes reachability between operations according to the extended control flow graph An operation inside a loop reaches all the operation after the loop An operation inside a loop does not reach all the operation inside the loop but which are not reachable without crossing a feedback edge
Definition at line 51 of file bb_reachability_computation.hpp.
Constructor & Destructor Documentation
BBReachabilityComputation()
BBReachabilityComputation::BBReachabilityComputation (const ParameterConstRef _Param, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
. includes algorithms/loops_detection includes behavior includes graph includes tree includes STL includes
Definition at line 71 of file bb_reachability_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, and ~BBReachabilityComputation().
 BBReachabilityComputation()
BBReachabilityComputation::~BBReachabilityComputation () [override], [default]
Destructor.
Referenced by BBReachabilityComputation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BBReachabilityComputation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 88 of file bb_reachability_computation.cpp.
References ADD_BB_ECFG_EDGES, BB_FEEDBACK_EDGES_IDENTIFICATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void BBReachabilityComputation::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 79 of file bb_reachability_computation.cpp.
References FunctionFrontendFlowStep::bb_version, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status BBReachabilityComputation::InternalExec () [override], [virtual]
Computes the reachability between operations according to the control flow graph WITHOUT feedback.
Returns
the exit status of this step
The extended control flow graph of basic block
The reachability among basic blocks
Get first level loops
Implements FunctionFrontendFlowStep.
Definition at line 112 of file bb_reachability_computation.cpp.
References BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::EBB, FunctionFrontendFlowStep::function_behavior, PRINT_DBG_MEX, and SUCCESS.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/bb_reachability_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/bb_reachability_computation.cpp