SpiderParameter Class Reference
Superclass include.
#include <SpiderParameter.hpp>
Public Member Functions
SpiderParameter (const std::string &program_name, int argc, char **const argv)
Constructor.
~SpiderParameter () override=default
Destructor.
int Exec () override
Execute parameter parsing.
Private Member Functions
void CheckParameters () override
Check the compatibility among the different parameters and compute implicated parameters.
void PrintHelp (std::ostream &os) const override
Print the usage of this tool.
void PrintProgramName (std::ostream &os) const override
Print the name of the program to be included in the header.
void SetDefaults () override
Sets the default values for the Zebu tool.
Additional Inherited Members
Detailed Description
Superclass include.
STD include utility include
Definition at line 55 of file SpiderParameter.hpp.
Constructor & Destructor Documentation
SpiderParameter()
SpiderParameter::SpiderParameter (const std::string & program_name, int argc, char **const argv)
Constructor.
Parameters
program_name is the name of the executable
argc is the number of arguments
argv is the array of arguments passed to program.
Definition at line 170 of file SpiderParameter.cpp.
References SetDefaults().
 SpiderParameter()
SpiderParameter::~SpiderParameter () [override], [default]
Destructor.
Member Function Documentation
CheckParameters()
void SpiderParameter::CheckParameters () [override], [private], [virtual]
Check the compatibility among the different parameters and compute implicated parameters.
Implements Parameter.
Definition at line 373 of file SpiderParameter.cpp.
References Parameter::CheckParameters(), Parameter::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FF_CSV, FF_TEX, FF_TGFF, FF_UNKNOWN, FF_VERILOG, FF_VHDL, FF_XML, FF_XML_EXPERIMENTAL_SETUP, FF_XML_IP_XACT_COMPONENT, FF_XML_IP_XACT_CONFIG, FF_XML_IP_XACT_DESIGN, FF_XML_IP_XACT_GENERATOR, FF_XML_SKIP_ROW, FF_XML_SYM_SIM, FF_XML_TEX_TABLE, FF_XML_WGT_GM, FF_XML_WGT_SYM, Parameter::GetFileFormat(), Parameter::getOption(), INDENT_DBG_MEX, Parameter::isOption(), Parameter::setOption(), STR, STR_CST_string_separator, and THROW_ERROR.
Referenced by Exec().
Exec()
int SpiderParameter::Exec () [override], [virtual]
Execute parameter parsing.
variable used into option parsing
Implements Parameter.
Definition at line 175 of file SpiderParameter.cpp.
References Parameter::argc, Parameter::argv, CheckParameters(), COMMON_LONG_OPTIONS, COMMON_SHORT_OPTIONS_STRING, exit_code, INPUT_OPT_ACCURACY, INPUT_OPT_BENCHMARK_BOUNDS, INPUT_OPT_COMPONENTS, INPUT_OPT_CROSS_VALIDATION, INPUT_OPT_MINIMUM_SIGNIFICANCE, INPUT_OPT_NORMALIZATION_SEQUENCES, INPUT_OPT_NORMALIZATION_WEIGHT_FILE, INPUT_OPT_PREDICTION_INTERVAL_VALUE, INPUT_OPT_SEQUENCE_LENGTH, INPUT_OPT_SURVIVING_BENCHMARKS, Parameter::isOption(), Parameter::ManageDefaultOptions(), PARAMETER_NOTPARSED, PARAMETER_PARSED, Parameter::PrintUsage(), Parameter::setOption(), SplitString(), STR_CST_string_separator, THROW_ASSERT, and THROW_ERROR.
PrintHelp()
void SpiderParameter::PrintHelp (std::ostream & os) const [override], [private], [virtual]
Print the usage of this tool.
Parameters
os is the stream where the message has to be printed
Implements Parameter.
Definition at line 90 of file SpiderParameter.cpp.
References Parameter::PrintGeneralOptionsUsage(), and Parameter::PrintOutputOptionsUsage().
PrintProgramName()
void SpiderParameter::PrintProgramName (std::ostream & os) const [override], [private], [virtual]
Print the name of the program to be included in the header.
Parameters
os is the stream on which the program name has to be printed
Implements Parameter.
Definition at line 156 of file SpiderParameter.cpp.
SetDefaults()
void SpiderParameter::SetDefaults () [override], [private], [virtual]
Sets the default values for the Zebu tool.
Debugging level
Output level
Implements Parameter.
Definition at line 335 of file SpiderParameter.cpp.
References DEBUG_LEVEL_MINIMUM, DEBUG_LEVEL_NONE, INFINITE_LONG_DOUBLE, NUM_CST_surviving_benchmarks, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_NONE, and Parameter::setOption().
Referenced by SpiderParameter().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/SpiderParameter.hpp
/home/osboxes/bambu/PandA-bambu/src/SpiderParameter.cpp