MemoryInitializationCWriter Class Reference
Functor used to write initialization of the memory throw C instructions added to values.c.
#include <memory_initialization_c_writer.hpp>
Public Member Functions
MemoryInitializationCWriter (const IndentedOutputStreamRef indented_output_stream, const tree_managerConstRef TM, const BehavioralHelperConstRef behavioral_helper, const unsigned long int reserved_mem_bytes, const tree_nodeConstRef function_parameter, const TestbenchGeneration_MemoryType testbench_generation_memory_type, const ParameterConstRef parameters)
Constructor.
void Process (const std::string &content) override
Process an element.
Protected Attributes
const IndentedOutputStreamRef indented_output_stream
The stream where C code has to be written.
Additional Inherited Members
Detailed Description
Functor used to write initialization of the memory throw C instructions added to values.c.
Definition at line 57 of file memory_initialization_c_writer.hpp.
Constructor & Destructor Documentation
MemoryInitializationCWriter()
MemoryInitializationCWriter::MemoryInitializationCWriter (const IndentedOutputStreamRef _indented_output_stream, const tree_managerConstRef _TM, const BehavioralHelperConstRef _behavioral_helper, const unsigned long int _reserved_mem_bytes, const tree_nodeConstRef _function_parameter, const TestbenchGeneration_MemoryType _testbench_generation_memory_type, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
indented_output_stream is where the C code will be written
TM is the tree manager
behavioral_helper is the behavioral helper
reserved_mem_bytes is the number of bytes to be written
function_parameter is the function parameter whose initialization is being printed
testbench_generation_memory_type is the type of initialization being printed
parameters is the set of input parameters
. include HLS/simulation include tree includes utility includes
Definition at line 54 of file memory_initialization_c_writer.cpp.
References CInitializationParserFunctor::debug_level, and GET_CLASS.
Member Function Documentation
Process()
void MemoryInitializationCWriter::Process (const std::string & content) [override], [virtual]
Process an element.
Parameters
content is the string assocated with the string
Second, according to the type let's how many elements have to have been processed
Implements CInitializationParserFunctor.
Definition at line 72 of file memory_initialization_c_writer.cpp.
References IndentedOutputStream::Append(), MemoryInitializationWriterBase::behavioral_helper, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, ConvertInBinary(), CInitializationParserFunctor::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, MemoryInitializationWriterBase::function_parameter, INDENT_DBG_MEX, indented_output_stream, INPUT_PARAMETER, is_all_8zeros(), tree_helper::is_unsigned(), MEMORY_INITIALIZATION, NODE_NOT_YET_SUPPORTED_EC, OUTPUT_PARAMETER, BehavioralHelper::PrintVariable(), RETURN, tree_helper::size(), MemoryInitializationWriterBase::status, STR, MemoryInitializationWriterBase::testbench_generation_memory_type, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, THROW_UNREACHABLE, MemoryInitializationWriterBase::TM, and MemoryInitializationWriterBase::written_bytes.
Field Documentation
indented_output_stream
const IndentedOutputStreamRef MemoryInitializationCWriter::indented_output_stream [protected]
The stream where C code has to be written.
Definition at line 61 of file memory_initialization_c_writer.hpp.
Referenced by Process().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/memory_initialization_c_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/memory_initialization_c_writer.cpp