DesignFlowGraphsCollection Class Reference
#include <design_flow_graph.hpp>
Public Member Functions
DesignFlowGraphsCollection (const ParameterConstRef parameters)
Constructor.
~DesignFlowGraphsCollection () override
Destructor.
vertex GetDesignFlowStep (const std::string &signature) const
Return the vertex associated with a design step if exists, NULL_VERTEX otherwise.
EdgeDescriptor AddDesignFlowDependence (const vertex source, const vertex target, const int selector)
Add a design flow dependence.
vertex AddDesignFlowStep (const DesignFlowStepRef design_flow_step, const bool unnecessary)
Add a design step.
Protected Attributes
CustomUnorderedMap< std::string, vertex > signature_to_vertex
Map a signature of a step to the corresponding vertex.
Additional Inherited Members
Detailed Description
Definition at line 109 of file design_flow_graph.hpp.
Constructor & Destructor Documentation
DesignFlowGraphsCollection()
DesignFlowGraphsCollection::DesignFlowGraphsCollection (const ParameterConstRef parameters) [explicit]
Constructor.
Definition at line 63 of file design_flow_graph.cpp.
References ~DesignFlowGraphsCollection().
 DesignFlowGraphsCollection()
DesignFlowGraphsCollection::~DesignFlowGraphsCollection () [override], [default]
Destructor.
Referenced by DesignFlowGraphsCollection().
Member Function Documentation
AddDesignFlowDependence()
EdgeDescriptor DesignFlowGraphsCollection::AddDesignFlowDependence (const vertex source, const vertex target, const int selector) [inline]
Add a design flow dependence.
Parameters
source is the source of the dependence
target is the target of the dependence
Definition at line 137 of file design_flow_graph.hpp.
References DesignFlowStepInfo::design_flow_step.
AddDesignFlowStep()
vertex DesignFlowGraphsCollection::AddDesignFlowStep (const DesignFlowStepRef design_flow_step, const bool unnecessary)
Add a design step.
Parameters
design_flow_step is the step to be added
unnecessary specifiy is the step is necessary or not
Definition at line 69 of file design_flow_graph.cpp.
References graphs_collection::AddVertex(), and signature_to_vertex.
GetDesignFlowStep()
vertex DesignFlowGraphsCollection::GetDesignFlowStep (const std::string & signature) const
Return the vertex associated with a design step if exists, NULL_VERTEX otherwise.
Parameters
signature is the signature of the design step
Definition at line 77 of file design_flow_graph.cpp.
References DesignFlowGraph::AUX_SELECTOR, DesignFlowGraph::DEPENDENCE_FEEDBACK_SELECTOR, DesignFlowGraph::DEPENDENCE_SELECTOR, NULL_VERTEX, DesignFlowGraph::PRECEDENCE_SELECTOR, and signature_to_vertex.
Field Documentation
signature_to_vertex
CustomUnorderedMap<std::string, vertex> DesignFlowGraphsCollection::signature_to_vertex [protected]
Map a signature of a step to the corresponding vertex.
Definition at line 113 of file design_flow_graph.hpp.
Referenced by AddDesignFlowStep(), and GetDesignFlowStep().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/design_flow_graph.cpp