ApplicationFrontendFlowStep Class Reference
#include <application_frontend_flow_step.hpp>
Public Member Functions
ApplicationFrontendFlowStep (const application_managerRef AppM, const FrontendFlowStepType frontend_flow_step_type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~ApplicationFrontendFlowStep () override
Destructor.
DesignFlowStep_Status Exec () override=0
Execute this step.
const std::string GetSignature () const override
Return the signature of this step.
const std::string GetName () const override
Return the name of this design step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Static Public Member Functions
static const std::string ComputeSignature (const FrontendFlowStepType frontend_flow_step_type)
Compute the signature of a function frontend flow step.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override=0
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 53 of file application_frontend_flow_step.hpp.
Constructor & Destructor Documentation
ApplicationFrontendFlowStep()
ApplicationFrontendFlowStep::ApplicationFrontendFlowStep (const application_managerRef AppM, const FrontendFlowStepType frontend_flow_step_type, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
frontend_flow_step_type is the type of the step
design_flow_manager is the design flow manager
_Param is the set of the parameters
Definition at line 61 of file application_frontend_flow_step.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~ApplicationFrontendFlowStep().
 ApplicationFrontendFlowStep()
ApplicationFrontendFlowStep::~ApplicationFrontendFlowStep () [override], [default]
Destructor.
Referenced by ApplicationFrontendFlowStep().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet<std::pair<FrontendFlowStepType, FunctionRelationship> > ApplicationFrontendFlowStep::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [pure virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Implemented in CreateAddressTranslation, call_graph_computation, PragmaAnalysis, string_cst_fix, HostProfiling, parm2ssa, BitValueIPA, ipa_point_to_analysis, create_tree_manager, SymbolicApplicationFrontendFlowStep, FindMaxCFGTransformations, PragmaSubstitution, BasicBlocksProfiling, CompleteCallGraph, HDLFunctionDeclFix, and BambuFrontendFlow.
ComputeSignature()
const std::string ApplicationFrontendFlowStep::ComputeSignature (const FrontendFlowStepType frontend_flow_step_type) [static]
Compute the signature of a function frontend flow step.
Parameters
frontend_flow_step_type is the type of frontend flow
Returns
the corresponding signature
Definition at line 69 of file application_frontend_flow_step.cpp.
References ADD_BB_ECFG_EDGES, ADD_OP_EXIT_FLOW_EDGES, ADD_OP_LOOP_FLOW_EDGES, AGGREGATE_DATA_FLOW_ANALYSIS, BASIC_BLOCKS_CFG_COMPUTATION, BB_CONTROL_DEPENDENCE_COMPUTATION, BB_FEEDBACK_EDGES_IDENTIFICATION, BB_ORDER_COMPUTATION, BB_REACHABILITY_COMPUTATION, BLOCK_FIX, BUILD_VIRTUAL_PHI, CALL_EXPR_FIX, CHECK_SYSTEM_TYPE, CLEAN_VIRTUAL_PHI, COMPLETE_BB_GRAPH, COMPLETE_CALL_GRAPH, SymbolicApplicationFrontendFlowStep::ComputeSignature(), CREATE_TREE_MANAGER, DOM_POST_DOM_COMPUTATION, FrontendFlowStep::frontend_flow_step_type, FUNCTION_ANALYSIS, LOOP_COMPUTATION, LOOPS_COMPUTATION, MEM_CG_EXT, MEMORY_DATA_FLOW_ANALYSIS, OP_CONTROL_DEPENDENCE_COMPUTATION, OP_FEEDBACK_EDGES_IDENTIFICATION, OP_ORDER_COMPUTATION, OP_REACHABILITY_COMPUTATION, OPERATIONS_CFG_COMPUTATION, PARM2SSA, SCALAR_SSA_DATA_FLOW_ANALYSIS, STRING_CST_FIX, SWITCH_FIX, SYMBOLIC_APPLICATION_FRONTEND_FLOW_STEP, THROW_UNREACHABLE, USE_COUNTING, VAR_ANALYSIS, VAR_DECL_FIX, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
Referenced by HLSBitValue::ComputeRelationships(), CTestbenchExecution::ComputeRelationships(), fun_dominator_allocation::ComputeRelationships(), CBackend::ComputeRelationships(), HLS_step::ComputeRelationships(), FrontendFlowStep::CreateSteps(), GetSignature(), and Bit_Value::Initialize().
Exec()
DesignFlowStep_Status ApplicationFrontendFlowStep::Exec () [override], [pure virtual]
Execute this step.
Returns
the exit status of this step
Implements DesignFlowStep.
Implemented in CreateAddressTranslation, call_graph_computation, PragmaAnalysis, string_cst_fix, HostProfiling, parm2ssa, FindMaxCFGTransformations, create_tree_manager, ipa_point_to_analysis, BitValueIPA, SymbolicApplicationFrontendFlowStep, PragmaSubstitution, BasicBlocksProfiling, CompleteCallGraph, HDLFunctionDeclFix, and BambuFrontendFlow.
GetName()
const std::string ApplicationFrontendFlowStep::GetName () const [override], [virtual]
Return the name of this design step.
Returns
the name of the pass (for debug purpose)
Implements DesignFlowStep.
Definition at line 361 of file application_frontend_flow_step.cpp.
References FrontendFlowStep::GetKindText().
GetSignature()
const std::string ApplicationFrontendFlowStep::GetSignature () const [override], [virtual]
Return the signature of this step.
Implements DesignFlowStep.
Reimplemented in SymbolicApplicationFrontendFlowStep.
Definition at line 356 of file application_frontend_flow_step.cpp.
References ComputeSignature(), and FrontendFlowStep::frontend_flow_step_type.
Referenced by CreateAddressTranslation::ComputeFrontendRelationships().
HasToBeExecuted()
bool ApplicationFrontendFlowStep::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Reimplemented in CreateAddressTranslation, SymbolicApplicationFrontendFlowStep, create_tree_manager, BitValueIPA, CompleteCallGraph, and BambuFrontendFlow.
Definition at line 366 of file application_frontend_flow_step.cpp.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/application_frontend_flow_step.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/application_frontend_flow_step.cpp