cg_edge_info Struct Reference
Information associated with a circuit graph edge.
#include <cg_node.hpp>
Public Member Functions
void print (std::ostream &os) const
Print the information associated with the current node of the graph.
cg_edge_info ()
Constructor.
Data Fields
structural_objectRef from_port
port from which the edge is generated
structural_objectRef to_port
destination port/channel to the edge is attached
bool is_critical
flag to check if the edge is involved into the critical path
Detailed Description
Information associated with a circuit graph edge.
Definition at line 107 of file cg_node.hpp.
Constructor & Destructor Documentation
cg_edge_info()
cg_edge_info::cg_edge_info () [inline]
Constructor.
Definition at line 122 of file cg_node.hpp.
Member Function Documentation
print()
void cg_edge_info::print (std::ostream & os) const
Print the information associated with the current node of the graph.
Parameters
os is the output stream.
Definition at line 49 of file cg_node.cpp.
References constant_o_K, from_port, structural_object::get_id(), structural_object::get_kind(), structural_object::get_owner(), port_vector_o_K, and to_port.
Field Documentation
from_port
structural_objectRef cg_edge_info::from_port
port from which the edge is generated
Definition at line 110 of file cg_node.hpp.
Referenced by print().
is_critical
bool cg_edge_info::is_critical
flag to check if the edge is involved into the critical path
Definition at line 114 of file cg_node.hpp.
to_port
structural_objectRef cg_edge_info::to_port
destination port/channel to the edge is attached
Definition at line 112 of file cg_node.hpp.
Referenced by print().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/cg_node.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/cg_node.cpp