fanout_opt Class Reference
fanout_opt analysis
#include <fanout_opt.hpp>
Public Member Functions
fanout_opt (const ParameterConstRef Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~fanout_opt () override
Destructor.
DesignFlowStep_Status InternalExec () override
perform fanout_opt analysis
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec)
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
bool is_dest_relevant (tree_nodeRef t, bool is_phi)
return true in case the use is relevant for the fanout optimization
Private Attributes
ScheduleRef schedule
The scheduling solution.
const tree_managerRef TM
tree manager
Additional Inherited Members
Detailed Description
fanout_opt analysis
Definition at line 62 of file fanout_opt.hpp.
Constructor & Destructor Documentation
fanout_opt()
fanout_opt::fanout_opt (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Header include.
Parameters
_Param is the set of the parameters
_AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
. include boost include behavior includes HLS include STD include
Definition at line 82 of file fanout_opt.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~fanout_opt().
 fanout_opt()
fanout_opt::~fanout_opt () [override], [default]
Destructor.
Referenced by fanout_opt().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > fanout_opt::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 90 of file fanout_opt.cpp.
References ABORTED, DesignFlowStep::DEPENDENCE_RELATIONSHIP, EMPTY, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, NONEXISTENT, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, SKIPPED, SUCCESS, THROW_UNREACHABLE, UNCHANGED, UNEXECUTED, and UNNECESSARY.
Initialize()
void fanout_opt::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec)
Reimplemented from DesignFlowStep.
Definition at line 270 of file fanout_opt.cpp.
References FrontendFlowStep::AppM, FunctionFrontendFlowStep::function_id, and schedule.
InternalExec()
DesignFlowStep_Status fanout_opt::InternalExec () [override], [virtual]
perform fanout_opt analysis
Returns
the exit status of this step
fanout duplication may prevent openmp simd detection
Copy the list of def edges
Implements FunctionFrontendFlowStep.
Definition at line 149 of file fanout_opt.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_manager::get_tree_node_const(), tree_helper::get_type_node(), INDENT_DBG_MEX, is_dest_relevant(), DesignFlowStep::parameters, phi, tree_manager::ReplaceTreeNode(), schedule, SKIPPED, sl, STR, SUCCESS, TM, ToString(), tree_node::ToString(), UNCHANGED, and Schedule::UpdateTime().
is_dest_relevant()
bool fanout_opt::is_dest_relevant (tree_nodeRef t, bool is_phi) [private]
return true in case the use is relevant for the fanout optimization
Definition at line 136 of file fanout_opt.cpp.
References tree_node::get_kind(), GET_NODE, and THROW_ASSERT.
Referenced by InternalExec().
Field Documentation
schedule
ScheduleRef fanout_opt::schedule [private]
The scheduling solution.
Definition at line 66 of file fanout_opt.hpp.
Referenced by Initialize(), and InternalExec().
TM
const tree_managerRef fanout_opt::TM [private]
tree manager
Definition at line 69 of file fanout_opt.hpp.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/fanout_opt.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/fanout_opt.cpp