gimple_phi Struct Reference
This struct specifies the gimple_phi node.
#include <tree_node.hpp>
Public Types
enum { GETID =(gimple_node) = 0,
GETID =(gimple_node) = 0
 }
visitor enum
typedef std::pair< tree_nodeRef, unsigned int > DefEdge
The type of the def edge.
typedef std::list< DefEdge > DefEdgeList
The type of the def edge list.
Public Member Functions
gimple_phi (unsigned int i)
Constructor.
const DefEdgeList & CGetDefEdgesList () const
Return the list of def edges.
void RemoveDefEdge (const tree_managerRef &TM, const DefEdge &def_edge)
Remove a defedge.
void AddDefEdge (const tree_managerRef &TM, const DefEdge &def_edge)
Add a defedge.
void ReplaceDefEdge (const tree_managerRef &TM, const DefEdge &old_def_edge, const DefEdge &new_def_edge)
Replace a defedge.
void SetDefEdgeList (const tree_managerRef &TM, DefEdgeList new_list_of_def_edge)
Set the def edge list removing the ond one.
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
void SetSSAUsesComputed ()
Set that uses of ssa have been computed.
Data Fields
tree_nodeRef res
res is the new SSA_NAME node created by the PHI node.
bool virtual_flag
flag for virtual phi
Private Attributes
DefEdgeList list_of_def_edge
store the list pairs: <def, edge>.
bool updated_ssa_uses
True if ssa uses are updated.
Friends
class tree_manager
class string_cst_fix
class parm2ssa
Additional Inherited Members
Detailed Description
This struct specifies the gimple_phi node.
SSA PHI operator. PHI_RESULT is the new node created by the PHI node. PHI_ARG_LENGTH is the number of arguments. PHI_ARG_ELT returns the Ith tuple <def, edge> from the argument list. Each tuple contains the incoming reaching definition (SSA_NAME node) and the edge via which that definition is coming through. The tree walker structure of this node is: #(TOK_GIMPLE_PHI res (tuple)*)
Definition at line 3725 of file tree_node.hpp.
Member Typedef Documentation
DefEdge
typedef std::pair<tree_nodeRef, unsigned int> gimple_phi::DefEdge
The type of the def edge.
Definition at line 3733 of file tree_node.hpp.
DefEdgeList
typedef std::list<DefEdge> gimple_phi::DefEdgeList
The type of the def edge list.
Definition at line 3736 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
GETID
Definition at line 3811 of file tree_node.hpp.
Constructor & Destructor Documentation
gimple_phi()
gimple_phi::gimple_phi (unsigned int i) [explicit]
Constructor.
Parameters
i is the index of the node to be created
Definition at line 916 of file tree_node.cpp.
Member Function Documentation
AddDefEdge()
void gimple_phi::AddDefEdge (const tree_managerRef & TM, const DefEdge & def_edge)
Add a defedge.
Parameters
TM is the tree manager
def_edge is the def edge to be added
update_uses specifies if the uses have to be updated
Definition at line 932 of file tree_node.cpp.
References gimple_node::bb_index, GET_NODE, tree_manager::GetTreeReindex(), tree_node::index, list_of_def_edge, and updated_ssa_uses.
Referenced by SetDefEdgeList().
CGetDefEdgesList()
const gimple_phi::DefEdgeList & gimple_phi::CGetDefEdgesList () const
Return the list of def edges.
Returns
the list of def edges
Definition at line 945 of file tree_node.cpp.
References list_of_def_edge.
Referenced by GimpleWriter::GimpleWriter(), VcdSignalSelection::InitialPhiResIsAddress(), VcdSignalSelection::SingleStepPropagateAddrSsa(), and raw_writer::write_when_not_null_point_to().
RemoveDefEdge()
void gimple_phi::RemoveDefEdge (const tree_managerRef & TM, const DefEdge & def_edge)
Remove a defedge.
Parameters
TM is the tree manager
def_edge is the def edge to be removed
update_uses specifies if the uses have to be updated
Definition at line 990 of file tree_node.cpp.
References gimple_node::bb_index, GET_NODE, tree_manager::GetTreeReindex(), tree_node::index, list_of_def_edge, STR, THROW_ASSERT, tree_node::ToString(), and updated_ssa_uses.
Referenced by SetDefEdgeList().
ReplaceDefEdge()
void gimple_phi::ReplaceDefEdge (const tree_managerRef & TM, const DefEdge & old_def_edge, const DefEdge & new_def_edge)
Replace a defedge.
Parameters
old_def_edge is the def edge to be removed
new_def_edge is the def edge to be added
update_uses specifies if the uses have to be updated
Definition at line 950 of file tree_node.cpp.
References gimple_node::bb_index, GET_NODE, tree_manager::GetTreeReindex(), tree_node::index, list_of_def_edge, and updated_ssa_uses.
SetDefEdgeList()
void gimple_phi::SetDefEdgeList (const tree_managerRef & TM, DefEdgeList new_list_of_def_edge)
Set the def edge list removing the ond one.
Parameters
TM is the tree manager
new_def_edge_list is the new def edge list
update_uses specifies if the uses have to be updated
Definition at line 978 of file tree_node.cpp.
References AddDefEdge(), list_of_def_edge, and RemoveDefEdge().
SetSSAUsesComputed()
void gimple_phi::SetSSAUsesComputed ()
Set that uses of ssa have been computed.
Definition at line 1014 of file tree_node.cpp.
References THROW_ASSERT, and updated_ssa_uses.
visit()
void gimple_phi::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from gimple_node.
Definition at line 920 of file tree_node.cpp.
References ALL_VISIT, list_of_def_edge, res, VISIT_MEMBER, VISIT_MEMBER_NAMED, and VISIT_SC.
Friends And Related Function Documentation
parm2ssa
friend class parm2ssa [friend]
Definition at line 3730 of file tree_node.hpp.
string_cst_fix
friend class string_cst_fix [friend]
Definition at line 3729 of file tree_node.hpp.
tree_manager
friend class tree_manager [friend]
Definition at line 3728 of file tree_node.hpp.
Field Documentation
list_of_def_edge
DefEdgeList gimple_phi::list_of_def_edge [private]
store the list pairs: <def, edge>.
Each tuple contains the incoming reaching definition (SSA_NAME node) and the edge via which that definition is coming through.
Definition at line 3742 of file tree_node.hpp.
Referenced by AddDefEdge(), CGetDefEdgesList(), RemoveDefEdge(), ReplaceDefEdge(), SetDefEdgeList(), and visit().
res
tree_nodeRef gimple_phi::res
res is the new SSA_NAME node created by the PHI node.
Definition at line 3755 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), VcdSignalSelection::InitialPhiResIsAddress(), VcdSignalSelection::SingleStepPropagateAddrSsa(), visit(), and raw_writer::write_when_not_null_point_to().
updated_ssa_uses
bool gimple_phi::updated_ssa_uses [private]
True if ssa uses are updated.
Definition at line 3745 of file tree_node.hpp.
Referenced by AddDefEdge(), RemoveDefEdge(), ReplaceDefEdge(), and SetSSAUsesComputed().
virtual_flag
bool gimple_phi::virtual_flag
flag for virtual phi
Definition at line 3758 of file tree_node.hpp.
Referenced by raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp