virtual_phi_nodes_split Class Reference
#include <virtual_phi_nodes_split.hpp>
Public Member Functions
virtual_phi_nodes_split (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~virtual_phi_nodes_split () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performes the virtual splitting of the phi-nodes.
Private Member Functions
void virtual_split_phi (tree_nodeRef phi, blocRef &bb_block, std::map< unsigned int, blocRef > &list_of_bloc, const tree_managerRef TM)
virtually split a particular phi in two or more assignments
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
blocRef next_entry
Basic block introduced after entry.
std::map< std::pair< unsigned int, unsigned int >, unsigned int > replace
Basic block splitting information: if replace[source, target] exists, then between source and target replace[source, target] has been inserted.
Static Private Attributes
static bool tree_dumped = false
flag to check if initial tree has been dumped
Additional Inherited Members
Detailed Description
Definition at line 68 of file virtual_phi_nodes_split.hpp.
Constructor & Destructor Documentation
virtual_phi_nodes_split()
virtual_phi_nodes_split::virtual_phi_nodes_split (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the index of the function
design_flow_manager is the design flow manager
Definition at line 68 of file virtual_phi_nodes_split.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~virtual_phi_nodes_split().
 virtual_phi_nodes_split()
virtual_phi_nodes_split::~virtual_phi_nodes_split () [override], [default]
Destructor.
Referenced by virtual_phi_nodes_split().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > virtual_phi_nodes_split::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 76 of file virtual_phi_nodes_split.cpp.
References BLOCK_FIX, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status virtual_phi_nodes_split::InternalExec () [override], [virtual]
Performes the virtual splitting of the phi-nodes.
Implements FunctionFrontendFlowStep.
Definition at line 104 of file virtual_phi_nodes_split.cpp.
References FrontendFlowStep::AppM, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_NODE, tree_manager::get_tree_node_const(), DesignFlowStep::parameters, phi, PRINT_DBG_MEX, sl, SUCCESS, tree_dumped, and virtual_split_phi().
virtual_split_phi()
void virtual_phi_nodes_split::virtual_split_phi (tree_nodeRef phi, blocRef & bb_block, std::map< unsigned int, blocRef > & list_of_bloc, const tree_managerRef TM) [private]
virtually split a particular phi in two or more assignments
Parameters
phi is the phi
bb_block is the current basic block
list_of_bloc is basic block of the current function
TM is the tree manager
create the new ssa
substitute the def with the new ssa
update bb_index associated with the statement
Definition at line 144 of file virtual_phi_nodes_split.cpp.
References tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, bloc::ENTRY_BLOCK_ID, GET_INDEX_NODE, tree_manager::get_next_vers(), GET_NODE, tree_helper::get_type_index(), tree_manager::GetTreeReindex(), index, tree_manager::new_tree_node_id(), next_entry, phi, PRINT_DBG_MEX, replace, STR, THROW_ASSERT, TOK, TOK_OP0, TOK_OP1, TOK_ORIG, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, and TOK_VOLATILE.
Referenced by InternalExec().
Field Documentation
next_entry
blocRef virtual_phi_nodes_split::next_entry [private]
Basic block introduced after entry.
Definition at line 75 of file virtual_phi_nodes_split.hpp.
Referenced by virtual_split_phi().
replace
std::map<std::pair<unsigned int, unsigned int>, unsigned int> virtual_phi_nodes_split::replace [private]
Basic block splitting information: if replace[source, target] exists, then between source and target replace[source, target] has been inserted.
Definition at line 78 of file virtual_phi_nodes_split.hpp.
Referenced by virtual_split_phi().
tree_dumped
bool virtual_phi_nodes_split::tree_dumped = false [static], [private]
flag to check if initial tree has been dumped
Header include.
. include behavior includes parser/treegcc include STD include tree include
Definition at line 72 of file virtual_phi_nodes_split.hpp.
Referenced by InternalExec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/virtual_phi_nodes_split.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/virtual_phi_nodes_split.cpp