target_device Class Reference
#include <target_device.hpp>
Public Member Functions
target_device (const ParameterConstRef &Param, const technology_managerRef &TM, const TargetDevice_Type type)
Constructor of the class.
virtual ~target_device ()
Destructor of the class.
void xload (const target_deviceRef &device, const xml_element *node)
Method to read an XML file and identify the section containing device-related parameters.
virtual void xwrite (xml_element *node)=0
Method to write an XML node.
virtual void load_devices (const target_deviceRef device)=0
Load all data specific for a given technology.
template<typename G >
G get_parameter (const std::string &key) const
Returns the value of the specified parameter, if any.
template<typename G >
void set_parameter (const std::string &key, G value)
Sets the value of the specified parameter.
bool has_parameter (const std::string &key) const
Returns true if there is a value associated with the specified string identifier, false otherwise.
double get_core_height () const
Returns the height of the area dedicated for the implementation.
double get_core_width () const
Returns the width of the area dedicated for the implementation.
virtual void initialize ()=0
Initializes the target device based on the given parameters.
target_technologyRef get_target_technology () const
Returns the target technology datastructure.
technology_managerRef get_technology_manager () const
Returns the technology manager.
TargetDevice_Type get_type () const
return the type of target device
Static Public Member Functions
static target_deviceRef create_device (const TargetDevice_Type type, const ParameterConstRef &Param, const technology_managerRef &TM)
Factory method.
Protected Member Functions
void xload_device_parameters (const xml_element *dev_xml)
Method to read the part of the XML file related to technology parameters.
Protected Attributes
TargetDevice_Type device_type
define the type of the target device
const ParameterConstRef Param
class containing all the parameters
const technology_managerRef TM
class containing all the elements of the technology library
target_technologyRef target
Reference to the target technology which will be used in the target device.
std::map< std::string, std::string > parameters
Map containing all the parameters of the technology. All the values are stored as strings and they have correctly converted through the get_parameter template.
double core_height
Height of the core area dedicated for the design (in um).
double core_width
Width of the core area dedicated for the design (in um).
int debug_level
The debug level.
Detailed Description
Definition at line 72 of file target_device.hpp.
Constructor & Destructor Documentation
target_device()
target_device::target_device (const ParameterConstRef & _Param, const technology_managerRef & _TM, const TargetDevice_Type type)
Constructor of the class.
Autoheader include.
Parameters
Param is the reference to the class that contains all the parameters
TM is the reference to the current technology library
target is the reference to the current target technology
XML includes parameters' includes boost includes for file manipulations
Definition at line 69 of file target_device.cpp.
References ~target_device().
 target_device()
target_device::~target_device () [virtual], [default]
Destructor of the class.
Referenced by target_device().
Member Function Documentation
create_device()
target_deviceRef target_device::create_device (const TargetDevice_Type type, const ParameterConstRef & Param, const technology_managerRef & TM) [static]
Factory method.
It creates the proper specialization based on the given type
Parameters
type is the type of the target device that has to be created
Param is the class containing all the parameters
TM is the reference to the current technology library
target is the reference to the current target technology
this point should never be reached
Definition at line 76 of file target_device.cpp.
References FPGA, and THROW_UNREACHABLE.
Referenced by HLS_target::create_target(), and main().
get_core_height()
double target_device::get_core_height () const
Returns the height of the area dedicated for the implementation.
Definition at line 151 of file target_device.cpp.
References core_height.
get_core_width()
double target_device::get_core_width () const
Returns the width of the area dedicated for the implementation.
Definition at line 156 of file target_device.cpp.
References core_width.
get_parameter()
template<typename G >
G target_device::get_parameter (const std::string & key) const [inline]
Returns the value of the specified parameter, if any.
Otherwise, it throws an exception.
Parameters
key it is the string identifier of the parameter to be returned
Definition at line 150 of file target_device.hpp.
References THROW_ERROR.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::AnalyzeFu(), XilinxBackendFlow::CheckSynthesisResults(), BackendFlow::DetermineBackendFlowType(), memory_allocation::finalize_memory_allocation(), AlteraBackendFlow::InitDesignParameters(), LatticeBackendFlow::InitDesignParameters(), NanoXploreBackendFlow::InitDesignParameters(), XilinxBackendFlow::InitDesignParameters(), FunctionalUnitStep::Initialize(), mem_dominator_allocation::InternalExec(), HLS_manager::IsSingleWriteMemory(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), mem_xml_allocation::parse_xml_allocation(), XilinxBackendFlow::WriteFlowConfiguration(), and XilinxBackendFlow::XilinxBackendFlow().
get_target_technology()
target_technologyRef target_device::get_target_technology () const
Returns the target technology datastructure.
Definition at line 161 of file target_device.cpp.
References target.
Referenced by target_manager::set_target_device().
get_technology_manager()
technology_managerRef target_device::get_technology_manager () const
Returns the technology manager.
Definition at line 166 of file target_device.cpp.
References TM.
get_type()
TargetDevice_Type target_device::get_type () const [inline]
return the type of target device
Definition at line 203 of file target_device.hpp.
Referenced by allocation::add_proxy_function_module(), allocation::add_proxy_function_wrapper(), RTLCharacterization::AnalyzeCell(), FunctionalUnitStep::create_template_instance(), add_library::InternalExec(), allocation::InternalExec(), operation::xload(), functional_unit::xload(), and RTLCharacterization::xwrite_characterization().
has_parameter()
bool target_device::has_parameter (const std::string & key) const [inline]
Returns true if there is a value associated with the specified string identifier, false otherwise.
Parameters
key it is the string identifier of the parameter to be searched
Definition at line 170 of file target_device.hpp.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), FunctionalUnitStep::AnalyzeFu(), BackendFlow::DetermineBackendFlowType(), IC_device::IC_device(), IC_device::initialize(), FunctionalUnitStep::Initialize(), HLS_manager::IsSingleWriteMemory(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), XilinxBackendFlow::XilinxBackendFlow(), and FPGA_device::xwrite().
initialize()
virtual void target_device::initialize () [pure virtual]
Initializes the target device based on the given parameters.
Implemented in FPGA_device, and IC_device.
load_devices()
virtual void target_device::load_devices (const target_deviceRef device) [pure virtual]
Load all data specific for a given technology.
Implemented in FPGA_device, and IC_device.
set_parameter()
template<typename G >
void target_device::set_parameter (const std::string & key, G value) [inline]
Sets the value of the specified parameter.
Definition at line 161 of file target_device.hpp.
Referenced by HLS_target::HLS_target().
xload()
void target_device::xload (const target_deviceRef & device, const xml_element * node)
Method to read an XML file and identify the section containing device-related parameters.
Parameters
node is the root node for the analysis
Definition at line 93 of file target_device.cpp.
References xml_child::get_children(), Param, TM, technology_manager::xload(), and xload_device_parameters().
Referenced by HLS_target::create_target(), IC_device::load_devices(), and FPGA_device::load_devices().
xload_device_parameters()
void target_device::xload_device_parameters (const xml_element * dev_xml) [protected]
Method to read the part of the XML file related to technology parameters.
Parameters
dev_xml is the node where the analysis will be performed
Definition at line 116 of file target_device.cpp.
References device_type, FPGA, refcount< T >::get(), xml_child::get_children(), LOAD_XVM, Param, and parameters.
Referenced by xload().
xwrite()
virtual void target_device::xwrite (xml_element * node) [pure virtual]
Method to write an XML node.
Parameters
node is the node for writing the information
Implemented in IC_device, and FPGA_device.
Referenced by RTLCharacterization::xwrite_device_file().
Field Documentation
core_height
double target_device::core_height [protected]
Height of the core area dedicated for the design (in um).
Definition at line 91 of file target_device.hpp.
Referenced by get_core_height(), IC_device::IC_device(), and IC_device::set_dimension().
core_width
double target_device::core_width [protected]
Width of the core area dedicated for the design (in um).
Definition at line 94 of file target_device.hpp.
Referenced by get_core_width(), IC_device::IC_device(), and IC_device::set_dimension().
debug_level
int target_device::debug_level [protected]
The debug level.
Definition at line 97 of file target_device.hpp.
Referenced by FPGA_device::FPGA_device(), IC_device::IC_device(), and FPGA_device::load_devices().
device_type
TargetDevice_Type target_device::device_type [protected]
define the type of the target device
Definition at line 76 of file target_device.hpp.
Referenced by xload_device_parameters().
Param
const ParameterConstRef target_device::Param [protected]
class containing all the parameters
Definition at line 79 of file target_device.hpp.
Referenced by FPGA_device::FPGA_device(), IC_device::IC_device(), IC_device::initialize(), IC_device::load_devices(), FPGA_device::load_devices(), xload(), and xload_device_parameters().
parameters
std::map<std::string, std::string> target_device::parameters [protected]
Map containing all the parameters of the technology. All the values are stored as strings and they have correctly converted through the get_parameter template.
Definition at line 88 of file target_device.hpp.
Referenced by IC_device::initialize(), xload_device_parameters(), FPGA_device::xwrite(), and IC_device::xwrite().
target
target_technologyRef target_device::target [protected]
Reference to the target technology which will be used in the target device.
Definition at line 85 of file target_device.hpp.
Referenced by FPGA_device::FPGA_device(), get_target_technology(), IC_device::load_devices(), and IC_device::set_dimension().
TM
const technology_managerRef target_device::TM [protected]
class containing all the elements of the technology library
Definition at line 82 of file target_device.hpp.
Referenced by get_technology_manager(), and xload().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/target_device/target_device.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/target_device/target_device.cpp