meilp_solver Class Reference
Base class providing several methods to encapsulate the interface to several ilp solver.
#include <meilp_solver.hpp>
Public Types
enum ilp_sign { G,
L,
E
 }
Possible operator in constraints.
enum supported_solvers
List of currently supported solvers.
enum ilp_dir { min,
max
 }
Type of objective function.
Public Member Functions
virtual ~meilp_solver ()
virtual destructor
virtual void make (int nvars)=0
???
virtual int solve ()=0
Solve the linear problem.
virtual int solve_ilp ()=0
Solve the integer linear problem.
virtual void add_row (std::map< int, double > &i_coeffs, double i_rhs, ilp_sign i_sign, const std::string &name)=0
Add a constraint to the ilp formulation.
virtual void objective_add (std::map< int, double > &i_coeffs, ilp_dir dir)=0
Set the objective function.
virtual void set_binary (int i)
Set a variable to have only binary values.
virtual void set_int (int i)=0
Set a variable to have only integer values.
virtual void set_bnds (int var, double lowbo, double upbo)
Set lower and upper bound of a variable.
virtual void set_lowbo (int var, double bound)
Set lower bound of a variable.
virtual void set_upbo (int var, double bound)
Set upper bound of a variable.
virtual void get_vars_solution (std::map< int, double > &vars) const =0
Return the solution of the problem.
virtual int get_number_constraints () const =0
Return the number of constraints.
virtual int get_number_variables () const =0
Return the number of variables.
virtual void set_col_name (int var, const std::string &name)=0
Set name of a variable (column)
virtual std::string get_col_name (int var)=0
Get name of a variable (column)
virtual int add_empty_column ()=0
Add an empty column ???
void setMaximumSeconds (int MAX_t)
???
void set_debug_level (int v)
Set the verbosity (debug_level)
void set_priority (const std::map< int, int > &_priority)
Set the variable priority.
virtual void print_to_file (const std::string &file_name)=0
Print the problem.
Static Public Member Functions
static meilp_solverRef create_solver (supported_solvers solver_type)
Factory static member function.
Protected Member Functions
meilp_solver ()
Constructor.
void resize (size_t count)
virtual void copy (const std::map< int, double > &i_coeffs)
virtual void set_all_bounds ()=0
Set the lower and upper of the variables using lower_bounds and upper_bounds.
virtual void print (std::ostream &os)=0
Print the problem.
Protected Attributes
double * real_buffer
values in the constraint buffer
int * int_buffer
indexes in the constraint buffer
int unique_column_id
unique column identifier
int MAX_time
Time-out value.
int debug_level
debug_level
std::map< int, int > priority
variables priority
CustomUnorderedMap< int, double > lower_bounds
The lower bound of the variables. They will be really set by solve method.
CustomUnorderedMap< int, double > upper_bounds
The upper bound of the variables. They will be really set by solve method.
Private Attributes
size_t nel
number of elements in the constraint buffer
Detailed Description
Base class providing several methods to encapsulate the interface to several ilp solver.
Definition at line 73 of file meilp_solver.hpp.
Member Enumeration Documentation
ilp_dir
enum meilp_solver::ilp_dir
Type of objective function.
Enumerator
min Minimization.
max Maximization.
Definition at line 163 of file meilp_solver.hpp.
ilp_sign
enum meilp_solver::ilp_sign
Possible operator in constraints.
Enumerator
G Greater then.
L Less then.
E Equal to.
Definition at line 79 of file meilp_solver.hpp.
supported_solvers
enum meilp_solver::supported_solvers
List of currently supported solvers.
Definition at line 147 of file meilp_solver.hpp.
Constructor & Destructor Documentation
meilp_solver()
meilp_solver::meilp_solver () [protected]
Constructor.
Definition at line 64 of file meilp_solver.cpp.
 meilp_solver()
meilp_solver::~meilp_solver () [virtual]
virtual destructor
Definition at line 68 of file meilp_solver.cpp.
References int_buffer, nel, and real_buffer.
Member Function Documentation
add_empty_column()
virtual int meilp_solver::add_empty_column () [pure virtual]
Add an empty column ???
Implemented in glpk_solver.
add_row()
virtual void meilp_solver::add_row (std::map< int, double > & i_coeffs, double i_rhs, ilp_sign i_sign, const std::string & name) [pure virtual]
Add a constraint to the ilp formulation.
Parameters
i_coeffs are the coefficients of the variables in the left part
i_rhs is the constant in the right part
i_sign is the operator in the constraints
name is the name of the constraint
Implemented in glpk_solver.
copy()
void meilp_solver::copy (const std::map< int, double > & i_coeffs) [protected], [virtual]
Parameters
i_coeffs
Definition at line 100 of file meilp_solver.cpp.
References index, int_buffer, real_buffer, and resize().
Referenced by glpk_solver::add_row().
create_solver()
meilp_solverRef meilp_solver::create_solver (supported_solvers solver_type) [static]
Factory static member function.
Given the supported enum create a specialization of meilp_solver
Parameters
solver_type is the solver.
Returns
the solver object.
Definition at line 112 of file meilp_solver.cpp.
References THROW_ERROR.
Referenced by SDCScheduling::InternalExec(), and setMaximumSeconds().
get_col_name()
virtual std::string meilp_solver::get_col_name (int var) [pure virtual]
Get name of a variable (column)
Parameters
var is the index of the variables return the name of the variable
Implemented in glpk_solver.
get_number_constraints()
virtual int meilp_solver::get_number_constraints () const [pure virtual]
Return the number of constraints.
Returns
the number of constraints
Implemented in glpk_solver.
get_number_variables()
virtual int meilp_solver::get_number_variables () const [pure virtual]
Return the number of variables.
Returns
the number of variables
Implemented in glpk_solver.
get_vars_solution()
virtual void meilp_solver::get_vars_solution (std::map< int, double > & vars) const [pure virtual]
Return the solution of the problem.
Parameters
vars is where solution are stored
Implemented in glpk_solver.
make()
virtual void meilp_solver::make (int nvars) [pure virtual]
???
Parameters
nvars
Implemented in glpk_solver.
objective_add()
virtual void meilp_solver::objective_add (std::map< int, double > & i_coeffs, ilp_dir dir) [pure virtual]
Set the objective function.
Parameters
I_coeffs are the coefficients of the variables in the objective function
dir is the type of objective function
Implemented in glpk_solver.
print()
virtual void meilp_solver::print (std::ostream & os) [protected], [pure virtual]
Print the problem.
Parameters
os is the stream on which problem has to be printed
Implemented in glpk_solver.
print_to_file()
virtual void meilp_solver::print_to_file (const std::string & file_name) [pure virtual]
Print the problem.
Parameters
file_name is the name of the file to be written
Implemented in glpk_solver.
Referenced by setMaximumSeconds().
resize()
void meilp_solver::resize (size_t count) [protected]
Parameters
count
Definition at line 77 of file meilp_solver.cpp.
References int_buffer, nel, real_buffer, and THROW_ASSERT.
Referenced by copy().
set_all_bounds()
virtual void meilp_solver::set_all_bounds () [protected], [pure virtual]
Set the lower and upper of the variables using lower_bounds and upper_bounds.
Implemented in glpk_solver.
set_binary()
void meilp_solver::set_binary (int i) [virtual]
Set a variable to have only binary values.
Parameters
i is the variable
Definition at line 135 of file meilp_solver.cpp.
References set_bnds(), and set_int().
set_bnds()
void meilp_solver::set_bnds (int var, double lowbo, double upbo) [virtual]
Set lower and upper bound of a variable.
Parameters
var is the variables
lowbo is the lower bound
upbo is the upper bound
Definition at line 141 of file meilp_solver.cpp.
References lower_bounds, and upper_bounds.
Referenced by set_binary().
set_col_name()
virtual void meilp_solver::set_col_name (int var, const std::string & name) [pure virtual]
Set name of a variable (column)
Parameters
var is the index of the variables
name is the name of the variable
Implemented in glpk_solver.
set_debug_level()
void meilp_solver::set_debug_level (int v)
Set the verbosity (debug_level)
Definition at line 90 of file meilp_solver.cpp.
References debug_level, and dl.
Referenced by setMaximumSeconds().
set_int()
virtual void meilp_solver::set_int (int i) [pure virtual]
Set a variable to have only integer values.
Parameters
i is the variables
Implemented in glpk_solver.
Referenced by set_binary().
set_lowbo()
void meilp_solver::set_lowbo (int var, double bound) [virtual]
Set lower bound of a variable.
Parameters
var is the variable
bound is the lower bound
Definition at line 147 of file meilp_solver.cpp.
References lower_bounds.
set_priority()
void meilp_solver::set_priority (const std::map< int, int > & _priority)
Set the variable priority.
Parameters
_priority is mapping between index variable and priority
Definition at line 95 of file meilp_solver.cpp.
References priority.
Referenced by setMaximumSeconds().
set_upbo()
void meilp_solver::set_upbo (int var, double bound) [virtual]
Set upper bound of a variable.
Parameters
var is the variable
bound is the upper bound
Definition at line 152 of file meilp_solver.cpp.
References upper_bounds.
setMaximumSeconds()
void meilp_solver::setMaximumSeconds (int MAX_t) [inline]
???
Definition at line 280 of file meilp_solver.hpp.
References create_solver(), print_to_file(), set_debug_level(), and set_priority().
solve()
virtual int meilp_solver::solve () [pure virtual]
Solve the linear problem.
Implemented in glpk_solver.
solve_ilp()
virtual int meilp_solver::solve_ilp () [pure virtual]
Solve the integer linear problem.
Implemented in glpk_solver.
Field Documentation
debug_level
int meilp_solver::debug_level [protected]
debug_level
Definition at line 104 of file meilp_solver.hpp.
Referenced by glpk_solver::make(), set_debug_level(), glpk_solver::solve(), and glpk_solver::solve_ilp().
int_buffer
int* meilp_solver::int_buffer [protected]
indexes in the constraint buffer
Definition at line 95 of file meilp_solver.hpp.
Referenced by glpk_solver::add_row(), copy(), resize(), and ~meilp_solver().
lower_bounds
CustomUnorderedMap<int, double> meilp_solver::lower_bounds [protected]
The lower bound of the variables. They will be really set by solve method.
Definition at line 110 of file meilp_solver.hpp.
Referenced by glpk_solver::set_all_bounds(), set_bnds(), and set_lowbo().
MAX_time
int meilp_solver::MAX_time [protected]
Time-out value.
Definition at line 101 of file meilp_solver.hpp.
Referenced by glpk_solver::make().
nel
size_t meilp_solver::nel [private]
number of elements in the constraint buffer
Definition at line 88 of file meilp_solver.hpp.
Referenced by resize(), and ~meilp_solver().
priority
std::map<int, int> meilp_solver::priority [protected]
variables priority
Definition at line 107 of file meilp_solver.hpp.
Referenced by set_priority().
real_buffer
double* meilp_solver::real_buffer [protected]
values in the constraint buffer
Definition at line 92 of file meilp_solver.hpp.
Referenced by glpk_solver::add_row(), copy(), resize(), and ~meilp_solver().
unique_column_id
int meilp_solver::unique_column_id [protected]
unique column identifier
Definition at line 98 of file meilp_solver.hpp.
upper_bounds
CustomUnorderedMap<int, double> meilp_solver::upper_bounds [protected]
The upper bound of the variables. They will be really set by solve method.
Definition at line 113 of file meilp_solver.hpp.
Referenced by glpk_solver::set_all_bounds(), set_bnds(), and set_upbo().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/ilp/meilp_solver.hpp
/home/osboxes/bambu/PandA-bambu/src/ilp/meilp_solver.cpp