/home/osboxes/bambu/PandA-bambu/src/eucalyptus.cpp File Reference
Tool for estimation of RTL descriptions.
#include `config_HAVE_ALTERA.hpp`
#include `config_HAVE_DESIGN_COMPILER.hpp`
#include `config_HAVE_EXPERIMENTAL.hpp`
#include `config_HAVE_LATTICE.hpp`
#include `config_HAVE_XILINX.hpp`
#include <boost/filesystem/operations.hpp>
#include `design_flow_graph.hpp`
#include `design_flow_manager.hpp`
#include `design_flow_step.hpp`
#include `technology_flow_step_factory.hpp`
#include `EucalyptusParameter.hpp`
#include `parse_technology.hpp`
#include `target_device.hpp`
#include `target_manager.hpp`
#include `technology_manager.hpp`
#include `cpu_time.hpp`
#include `utility.hpp`
#include `load_builtin_technology.hpp`
#include `load_default_technology.hpp`
Functions
int main (int argc, char *argv[])
Autoheader include.
Detailed Description
Tool for estimation of RTL descriptions.
Author
Christian Pilato pilato@elet.polimi.it
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Marco Lattuada marco.lattuada@polimi.it
Function Documentation
main()
int main (int argc, char * argv[])
Autoheader include.
design_flows include design_flows/technology include technology include eucalyptus does not perform a clock constrained synthesis
creating the datastructure representing the target device
Definition at line 81 of file eucalyptus.cpp.
References TechnologyFlowStep::ComputeSignature(), target_device::create_device(), DEBUG_LEVEL_MINIMUM, exit_code, LOAD_TECHNOLOGY, OUTPUT_LEVEL_MINIMUM, PARAMETER_NOTPARSED, PARAMETER_PARSED, test_panda::parameters, print_cpu_time(), PRINT_MSG, PRINT_OUT_MEX, START_TIME, STOP_TIME, and THROW_ERROR.