structural_type_descriptor Struct Reference
Structure representing the most relevant information about the type of a structural object.
#include <structural_objects.hpp>
Public Types
enum s_type {
OTHER = 0,
BOOL,
INT,
UINT,
REAL,
USER,
VECTOR_BOOL,
VECTOR_INT,
VECTOR_UINT,
VECTOR_REAL,
VECTOR_USER,
UNKNOWN
 }
Define the possible type of a structural object.
Public Member Functions
structural_type_descriptor ()
Constructor.
structural_type_descriptor (const std::string &type_name, unsigned int vector_size)
Object factory.
structural_type_descriptor (std::string module_name)
Object factory for module objects.
~structural_type_descriptor ()=default
Destructor.
void copy (structural_type_descriptorRef dest)
Method that copies the contents of the current structural_type_descriptorRef into another structural_type_descriptor.
const std::string get_name () const
Returns the name of the type descriptor.
void xload (const xml_element *Enode, structural_type_descriptorRef owner)
Load a structural_type_descriptor starting from an xml file.
void xwrite (xml_element *rootnode)
Add a structural_type_descriptor to an xml tree.
void print (std::ostream &os) const
function that prints the class.
std::string get_kind_text () const
Definition of get_kind_text()
Static Public Member Functions
static bool check_type (structural_type_descriptorRef src_type, structural_type_descriptorRef dest_type)
Check if two type descriptors are consistent.
Data Fields
s_type type
The type of the port or the signal.
unsigned int size
The size of the object (in bit). The objects having a size are: ports, signals, channels, data, and actions.
unsigned int vector_size
The number of the elements of a vector.
std::string id_type
Original type id of the structural object.
unsigned int treenode
Treenode id of the type.
Static Private Attributes
static const char * s_typeNames [] = {`OTHER`, `BOOL`, `INT`, `UINT`, `REAL`, `USER`, `VECTOR_BOOL`, `VECTOR_INT`, `VECTOR_UINT`, `VECTOR_REAL`, `VECTOR_USER`, `UNKNOWN`}
store the names of the enumerative s_type.
 default values associated with the members of the structural_type_descriptor class.
static const s_type type_DEFAULT = OTHER
static const unsigned int treenode_DEFAULT = 0
static const unsigned int size_DEFAULT = 0
static const unsigned int vector_size_DEFAULT = 0
Friends
std::ostream & operator<< (std::ostream &os, const structural_type_descriptorRef o)
Friend definition of the << operator.
Detailed Description
Structure representing the most relevant information about the type of a structural object.
In case the structural object is a signal or a port all member has a real meaning, while when the structural object is a channel, component, event, data or an action the only relevant information stored into the descriptor is the id_type and treenode when available. The size member has also a relevant meaning when a channel, data, and an action? is considered.
Definition at line 142 of file structural_objects.hpp.
Member Enumeration Documentation
s_type
enum structural_type_descriptor::s_type
Define the possible type of a structural object.
Enumerator
OTHER
BOOL
INT
UINT
REAL
USER
VECTOR_BOOL
VECTOR_INT
VECTOR_UINT
VECTOR_REAL
VECTOR_USER
UNKNOWN
Definition at line 145 of file structural_objects.hpp.
Constructor & Destructor Documentation
structural_type_descriptor() [1/3]
structural_type_descriptor::structural_type_descriptor () [inline]
Constructor.
Definition at line 179 of file structural_objects.hpp.
Referenced by structural_type_descriptor().
structural_type_descriptor() [2/3]
structural_type_descriptor::structural_type_descriptor (const std::string & type_name, unsigned int vector_size)
Object factory.
Parameters
type_name is the string starting from which the object is built.
vector_size is the size of the the vector. In case vector_size is zero the descriptor type represents a scalar object, otherwise an array.
first set defaults
Definition at line 258 of file structural_objects.cpp.
References BOOL, tree_helper::get_pointed_type(), BehavioralHelper::get_size(), BehavioralHelper::get_type(), tree_helper::GetElements(), BehavioralHelper::GetElements(), BehavioralHelper::GetUnqualified(), id_type, index, INT, BehavioralHelper::is_a_complex(), tree_helper::is_a_function(), BehavioralHelper::is_a_pointer(), BehavioralHelper::is_a_vector(), BehavioralHelper::is_an_array(), BehavioralHelper::is_bool(), tree_helper::is_bool(), tree_helper::is_channel(), tree_helper::is_event(), BehavioralHelper::is_int(), tree_helper::is_int(), tree_helper::is_module(), BehavioralHelper::is_real(), BehavioralHelper::is_unsigned(), tree_helper::is_unsigned(), tree_helper::name_type(), OTHER, BehavioralHelper::print_type(), REAL, tree_helper::size(), size, size_DEFAULT, STR, structural_type_descriptor(), THROW_ERROR, treenode, type, UINT, UNKNOWN, USER, VECTOR_BOOL, VECTOR_INT, VECTOR_REAL, vector_size, vector_size_DEFAULT, VECTOR_UINT, and VECTOR_USER.
structural_type_descriptor() [3/3]
structural_type_descriptor::structural_type_descriptor (std::string module_name) [inline], [explicit]
Object factory for module objects.
Parameters
treenode is the treenode descriptor of the type.
Definition at line 196 of file structural_objects.hpp.
References check_type(), copy(), get_name(), index, print(), structural_type_descriptor(), xload(), xwrite(), and ~structural_type_descriptor().
 structural_type_descriptor()
structural_type_descriptor::~structural_type_descriptor () [default]
Destructor.
Referenced by structural_type_descriptor().
Member Function Documentation
check_type()
bool structural_type_descriptor::check_type (structural_type_descriptorRef src_type, structural_type_descriptorRef dest_type) [static]
Check if two type descriptors are consistent.
Parameters
src_type is the first type descriptor.
dest_type is the second type descriptor.
Returns
true if the two type descriptors are consistent.
Definition at line 511 of file structural_objects.cpp.
References BOOL, INT, structural_object::PP, REAL, THROW_WARNING, treenode_DEFAULT, UINT, UNKNOWN, USER, VECTOR_BOOL, VECTOR_INT, and VECTOR_UINT.
Referenced by WB4_interface::build_WB4_complete_logic(), structural_manager::check_type(), and structural_type_descriptor().
copy()
void structural_type_descriptor::copy (structural_type_descriptorRef dest)
Method that copies the contents of the current structural_type_descriptorRef into another structural_type_descriptor.
Parameters
dest is the reference to the structural_type_descriptor where the contents have to be written
Definition at line 147 of file structural_objects.cpp.
References id_type, size, treenode, type, and vector_size.
Referenced by structural_object::copy(), signal_o::get_lsb(), fu_binding::join_merge_split(), structural_type_descriptor(), and structural_object::~structural_object().
get_kind_text()
std::string structural_type_descriptor::get_kind_text () const [inline]
Definition of get_kind_text()
Definition at line 263 of file structural_objects.hpp.
Referenced by xwrite().
get_name()
const std::string structural_type_descriptor::get_name () const
Returns the name of the type descriptor.
Definition at line 97 of file structural_objects.cpp.
References s_typeNames, type, and UNKNOWN.
Referenced by structural_manager::add_connection(), conn_binding::add_datapath_connection(), classic_datapath::add_ports(), reg_binding::compute_bitsize(), moduleGenerator::GenerateHDL(), moduleGenerator::get_specialized_name(), reg_binding::specialise_reg(), structural_type_descriptor(), and VHDL_writer::write_port_binding().
print()
void structural_type_descriptor::print (std::ostream & os) const
function that prints the class.
Parameters
os is the output stream
Definition at line 156 of file structural_objects.cpp.
References BOOL, id_type, INT, OTHER, REAL, size, STR, THROW_ASSERT, THROW_ERROR, treenode, type, UINT, UNKNOWN, USER, VECTOR_BOOL, VECTOR_INT, VECTOR_REAL, vector_size, VECTOR_UINT, and VECTOR_USER.
Referenced by port_o::get_lsb(), signal_o::get_lsb(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), structural_type_descriptor(), verilog_writer::type_converter_size(), and structural_object::~structural_object().
xload()
void structural_type_descriptor::xload (const xml_element * Enode, structural_type_descriptorRef owner)
Load a structural_type_descriptor starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
Definition at line 105 of file structural_objects.cpp.
References BOOL, CE_XVM, id_type, LOAD_XVFM, LOAD_XVM, s_typeNames, size, THROW_ASSERT, treenode, type, type_DEFAULT, UNKNOWN, and vector_size.
Referenced by signal_o::get_lsb(), structural_type_descriptor(), structural_object::xload(), and structural_object::~structural_object().
xwrite()
void structural_type_descriptor::xwrite (xml_element * rootnode)
Add a structural_type_descriptor to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural type descriptor is attached.
Definition at line 132 of file structural_objects.cpp.
References xml_child::add_child_element(), get_kind_text(), id_type, s_typeNames, size, size_DEFAULT, treenode, treenode_DEFAULT, type, type_DEFAULT, vector_size, WRITE_XNVM, and WRITE_XVM.
Referenced by signal_o::get_lsb(), structural_type_descriptor(), structural_object::xwrite(), and structural_object::~structural_object().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const structural_type_descriptorRef o) [friend]
Friend definition of the << operator.
Definition at line 271 of file structural_objects.hpp.
Field Documentation
id_type
std::string structural_type_descriptor::id_type
Original type id of the structural object.
Definition at line 171 of file structural_objects.hpp.
Referenced by structural_manager::build_graph(), computeResources(), copy(), AllocationInformation::estimate_call_delay(), WB4Intercon_interface::exec(), port_o::fix_port_properties(), module::get_in_port(), structural_object::GetParameter(), structural_object::GetParameters(), cs_interface::InternalExec(), minimal_interface::InternalExec(), TopEntityMemoryMapped::InternalExec(), WB4_interface::InternalExec(), add_library::InternalExec(), ParallelMemoryFuBinding::manage_module_ports(), print(), structural_object::SetParameter(), structural_type_descriptor(), verilog_writer::type_converter(), VHDL_writer::type_converter(), verilog_writer::type_converter_size(), structural_object::type_resize(), verilog_writer::write_timing_specification(), TestbenchGenerationBaseStep::write_verilator_testbench(), xload(), xwrite(), and port_o::xwrite().
s_typeNames
const char * structural_type_descriptor::s_typeNames = {`OTHER`, `BOOL`, `INT`, `UINT`, `REAL`, `USER`, `VECTOR_BOOL`, `VECTOR_INT`, `VECTOR_UINT`, `VECTOR_REAL`, `VECTOR_USER`, `UNKNOWN`} [static], [private]
store the names of the enumerative s_type.
Definition at line 289 of file structural_objects.hpp.
Referenced by get_name(), legalize(), xload(), and xwrite().
size
unsigned int structural_type_descriptor::size
The size of the object (in bit). The objects having a size are: ports, signals, channels, data, and actions.
Definition at line 165 of file structural_objects.hpp.
Referenced by conn_binding::add_datapath_connection(), moduleGenerator::add_port_parameters(), minimal_interface::build_wrapper(), reg_binding::compute_bitsize(), copy(), moduleGenerator::GenerateHDL(), port_o::get_port_size(), moduleGenerator::get_specialized_name(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), conn_binding::mux_allocation(), print(), port_o::set_port_size(), reg_binding::specialise_reg(), moduleGenerator::specialize_fu(), structural_type_descriptor(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), structural_object::type_resize(), MinimalInterfaceTestbench::write_memory_handler(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), verilog_writer::write_module_parametrization_decl(), VHDL_writer::write_port_binding(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), MinimalInterfaceTestbench::write_signals(), xload(), and xwrite().
size_DEFAULT
const unsigned int structural_type_descriptor::size_DEFAULT = 0 [static], [private]
Definition at line 285 of file structural_objects.hpp.
Referenced by structural_type_descriptor(), and xwrite().
treenode
unsigned int structural_type_descriptor::treenode
Treenode id of the type.
Definition at line 174 of file structural_objects.hpp.
Referenced by minimal_interface::build_wrapper(), copy(), TestbenchGenerationBaseStep::initialize_input_signals(), print(), structural_type_descriptor(), MinimalInterfaceTestbench::write_input_signal_declaration(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), xload(), and xwrite().
treenode_DEFAULT
const unsigned int structural_type_descriptor::treenode_DEFAULT = 0 [static], [private]
Definition at line 284 of file structural_objects.hpp.
Referenced by check_type(), and xwrite().
type
s_type structural_type_descriptor::type
The type of the port or the signal.
Definition at line 162 of file structural_objects.hpp.
Referenced by conn_binding::add_datapath_connection(), RTLCharacterization::add_input_register(), RTLCharacterization::add_output_register(), FunctionalUnitStep::AnalyzeFu(), minimal_interface::build_wrapper(), copy(), signal_o::get_lsb(), get_name(), fu_binding::join_merge_split(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), conn_binding::mux_allocation(), print(), RTLCharacterization::resize_port(), fu_binding::specialise_fu(), structural_type_descriptor(), verilog_writer::type_converter(), VHDL_writer::type_converter(), verilog_writer::type_converter_size(), structural_object::type_resize(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), VHDL_writer::write_module_parametrization_decl(), verilog_writer::write_module_parametrization_decl(), TestbenchGenerationBaseStep::write_output_checks(), VHDL_writer::write_port_binding(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), WishboneInterfaceTestbench::write_wishbone_input_signal_declaration(), xload(), and xwrite().
type_DEFAULT
const s_type structural_type_descriptor::type_DEFAULT = OTHER [static], [private]
Definition at line 283 of file structural_objects.hpp.
Referenced by xload(), and xwrite().
vector_size
unsigned int structural_type_descriptor::vector_size
The number of the elements of a vector.
Definition at line 168 of file structural_objects.hpp.
Referenced by moduleGenerator::add_port_parameters(), reg_binding::compute_bitsize(), copy(), moduleGenerator::GenerateHDL(), moduleGenerator::get_specialized_name(), verilog_writer::may_slice_string(), VHDL_writer::may_slice_string(), print(), reg_binding::specialise_reg(), moduleGenerator::specialize_fu(), structural_type_descriptor(), verilog_writer::type_converter_size(), VHDL_writer::type_converter_size(), structural_object::type_resize(), MinimalInterfaceTestbench::write_memory_handler(), VHDL_writer::write_module_parametrization(), verilog_writer::write_module_parametrization(), verilog_writer::write_module_parametrization_decl(), verilog_writer::write_signal_declaration(), VHDL_writer::write_signal_declaration(), MinimalInterfaceTestbench::write_signals(), xload(), and xwrite().
vector_size_DEFAULT
const unsigned int structural_type_descriptor::vector_size_DEFAULT = 0 [static], [private]
Definition at line 286 of file structural_objects.hpp.
Referenced by structural_type_descriptor().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp