fu_binding_cs Class Reference
#include <fu_binding_cs.hpp>
Public Member Functions
fu_binding_cs (const HLS_managerConstRef HLS_mgr, const unsigned int function_id, const ParameterConstRef parameters)
STD include.
virtual ~fu_binding_cs ()
Destructor.
virtual void add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port)
Call different method that instantiate the new component for each function_type.
void manage_memory_ports_parallel_chained (const HLS_managerRef HLSMgr, const structural_managerRef SM, const std::list< structural_objectRef > &memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int &_unique_id)
decide based on function what function to call in order to connect appropriately the datapath memory_signal with the component
void manage_extern_global_port (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, structural_objectRef port_in, unsigned int dir, structural_objectRef circuit, unsigned int num)
manage_extern_global_port based on function attach the input of memory modules
Protected Member Functions
void instantiate_component_kernel (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port)
instantiate_component_kernel
void connectOutOr (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef port_out_or)
connectOutOr connect or with datapath or scheduler depending on function
void connect_scheduler_Datapath (const structural_managerRef SM, const std::list< structural_objectRef > &memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int &_unique_id)
connect scheduler with datapath and other memory modules
void resize_scheduler_ports (const HLS_managerRef HLSMgr, structural_objectRef scheduler_mod)
for each port decide its vector size
void resize_dimension_bus_port (const HLS_managerRef HLSMgr, structural_objectRef port)
for each port resize it using vector size
void manage_memory_port_kernel (const structural_managerRef SM, const std::list< structural_objectRef > &memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int &_unique_id)
manage_memory_port_kernel connect correctly memory port when in kernel function
void manage_memory_port_hierarchical (const structural_managerRef SM, const std::list< structural_objectRef > &memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int &_unique_id)
manage_memory_port_hierarchical connect correctly memory port when in hierarchical function
void connect_selector (const hlsRef HLS)
connect_selector in function not kernel connect selector with all the module that have the right port
void connect_selector_kernel (const hlsRef HLS)
connect_selector_kernel, kernel take selector from scheduler
void set_atomic_memory_parameter (const hlsRef HLS)
set_atomic_memory_parameter need to set in order to have memory operation defined as atomic
Additional Inherited Members
Detailed Description
Definition at line 45 of file fu_binding_cs.hpp.
Constructor & Destructor Documentation
fu_binding_cs()
fu_binding_cs::fu_binding_cs (const HLS_managerConstRef _HLSMgr, const unsigned int _function_id, const ParameterConstRef _parameters)
STD include.
STL include utility include
Definition at line 63 of file fu_binding_cs.cpp.
References fu_binding::debug_level, and GET_CLASS.
 fu_binding_cs()
fu_binding_cs::~fu_binding_cs () [virtual]
Destructor.
Definition at line 68 of file fu_binding_cs.cpp.
Member Function Documentation
add_to_SM()
void fu_binding_cs::add_to_SM (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port) [virtual]
Call different method that instantiate the new component for each function_type.
Reimplemented from fu_binding.
Definition at line 72 of file fu_binding_cs.cpp.
References fu_binding::add_to_SM(), connect_selector(), connect_selector_kernel(), hls::functionId, instantiate_component_kernel(), and set_atomic_memory_parameter().
connect_scheduler_Datapath()
void fu_binding_cs::connect_scheduler_Datapath (const structural_managerRef SM, const std::list< structural_objectRef > & memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int & _unique_id) [protected]
connect scheduler with datapath and other memory modules
Parameters
SM
memory_modules
circuit
HLS
_unique_id
connect_selector()
void fu_binding_cs::connect_selector (const hlsRef HLS) [protected]
connect_selector in function not kernel connect selector with all the module that have the right port
Parameters
HLS
Definition at line 175 of file fu_binding_cs.cpp.
References structural_manager::add_connection(), hls::datapath, structural_object::find_member(), structural_manager::get_circ(), port_o_K, SELECTOR_REGISTER_FILE, and STR.
Referenced by add_to_SM().
connect_selector_kernel()
void fu_binding_cs::connect_selector_kernel (const hlsRef HLS) [protected]
connect_selector_kernel, kernel take selector from scheduler
Parameters
HLS
Definition at line 189 of file fu_binding_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_sign(), ceil_log2(), component_o_K, hls::datapath, fu_binding::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), structural_manager::get_circ(), structural_object::get_id(), fu_binding::parameters, port_o_K, PRINT_DBG_MEX, SELECTOR_REGISTER_FILE, STR, and structural_object::type_resize().
Referenced by add_to_SM().
connectOutOr()
void fu_binding_cs::connectOutOr (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef port_out_or) [protected]
connectOutOr connect or with datapath or scheduler depending on function
Parameters
HLSMgr
HLS
suspensionOr
instantiate_component_kernel()
void fu_binding_cs::instantiate_component_kernel (const HLS_managerRef HLSMgr, const hlsRef HLS, structural_objectRef clock_port, structural_objectRef reset_port) [protected]
instantiate_component_kernel
Parameters
HLSMgr
HLS
clock_port
reset_port
Definition at line 91 of file fu_binding_cs.cpp.
References structural_manager::add_connection(), ceil_log2(), CLOCK_PORT_NAME, hls::datapath, fu_binding::debug_level, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, DONE_REQUEST, DONE_SCHEDULER, structural_object::find_member(), structural_manager::get_circ(), hls::HLS_T, fu_binding::parameters, port_o_K, PRINT_DBG_MEX, RESET_PORT_NAME, resize_scheduler_ports(), START_PORT_NAME, STR, and TASKS_POOL_END.
Referenced by add_to_SM().
manage_extern_global_port()
void fu_binding_cs::manage_extern_global_port (const HLS_managerRef HLSMgr, const hlsRef HLS, const structural_managerRef SM, structural_objectRef port_in, unsigned int dir, structural_objectRef circuit, unsigned int num) [virtual]
manage_extern_global_port based on function attach the input of memory modules
Parameters
HLSMgr
HLS
SM
port_in
dir
circuit
num
Reimplemented from fu_binding.
Definition at line 421 of file fu_binding_cs.cpp.
References hls::functionId, port_o::IO, fu_binding::manage_extern_global_port(), and THROW_ERROR.
manage_memory_port_hierarchical()
void fu_binding_cs::manage_memory_port_hierarchical (const structural_managerRef SM, const std::list< structural_objectRef > & memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int & _unique_id) [protected]
manage_memory_port_hierarchical connect correctly memory port when in hierarchical function
Parameters
SM
memory_modules
circuit
HLS
_unique_id
Definition at line 350 of file fu_binding_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_port_vector(), fu_binding::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, fu_binding::join_merge_split(), port_o::OUT, fu_binding::parameters, port_vector_o_K, PRINT_DBG_MEX, and THROW_ASSERT.
Referenced by manage_memory_ports_parallel_chained().
manage_memory_port_kernel()
void fu_binding_cs::manage_memory_port_kernel (const structural_managerRef SM, const std::list< structural_objectRef > & memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int & _unique_id) [protected]
manage_memory_port_kernel connect correctly memory port when in kernel function
Parameters
SM
memory_modules
circuit
HLS
_unique_id
Definition at line 261 of file fu_binding_cs.cpp.
References structural_manager::add_connection(), structural_manager::add_port(), structural_manager::add_port_vector(), structural_manager::add_sign(), component_o_K, fu_binding::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, structural_object::find_member(), port_o::fix_port_properties(), get_id(), structural_object::get_kind(), structural_object::get_typeRef(), port_o::IN, fu_binding::join_merge_split(), port_o::OUT, port_vector_o_K, PRINT_DBG_MEX, and THROW_ASSERT.
Referenced by manage_memory_ports_parallel_chained().
manage_memory_ports_parallel_chained()
void fu_binding_cs::manage_memory_ports_parallel_chained (const HLS_managerRef HLSMgr, const structural_managerRef SM, const std::list< structural_objectRef > & memory_modules, const structural_objectRef circuit, const hlsRef HLS, unsigned int & _unique_id) [virtual]
decide based on function what function to call in order to connect appropriately the datapath memory_signal with the component
Parameters
HLSMgr
SM
memory_modules
circuit
HLS
_unique_id
Reimplemented from fu_binding.
Definition at line 246 of file fu_binding_cs.cpp.
References hls::functionId, manage_memory_port_hierarchical(), manage_memory_port_kernel(), and fu_binding::manage_memory_ports_parallel_chained().
resize_dimension_bus_port()
void fu_binding_cs::resize_dimension_bus_port (const HLS_managerRef HLSMgr, structural_objectRef port) [protected]
for each port resize it using vector size
Parameters
HLSMgr
port
Definition at line 158 of file fu_binding_cs.cpp.
References structural_object::type_resize().
Referenced by resize_scheduler_ports().
resize_scheduler_ports()
void fu_binding_cs::resize_scheduler_ports (const HLS_managerRef HLSMgr, structural_objectRef scheduler_mod) [protected]
for each port decide its vector size
Parameters
HLSMgr
scheduler_mod
Definition at line 142 of file fu_binding_cs.cpp.
References resize_dimension_bus_port().
Referenced by instantiate_component_kernel().
set_atomic_memory_parameter()
void fu_binding_cs::set_atomic_memory_parameter (const hlsRef HLS) [protected]
set_atomic_memory_parameter need to set in order to have memory operation defined as atomic
Parameters
HLS
Definition at line 221 of file fu_binding_cs.cpp.
References ceil_log2(), hls::datapath, structural_object::ExistsParameter(), structural_manager::get_circ(), fu_binding::parameters, structural_object::SetParameter(), STR, and THROW_ERROR.
Referenced by add_to_SM().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/fu_binding_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/fu_binding_cs.cpp