/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Introduction/fourth/module.c File Reference
Functions
int Upper_Triangular_Solve (float *U, float B[], float x[], int n)
void Unit_Lower_Triangular_Solve (float *L, float B[], float x[], int n)
int Doolittle_LU_Decomposition (float *A, int n)
int Doolittle_LU_Solve (float *LU, float B[], float x[], int n)
int invertMatrix (float *LU, float *invA, float *I)
int fun (float *A, float *invA, float *b, float *x, float *I)
Function Documentation
Doolittle_LU_Decomposition()
int Doolittle_LU_Decomposition (float * A, int n)
Definition at line 153 of file module.c.
Doolittle_LU_Solve()
int Doolittle_LU_Solve (float * LU, float B[], float x[], int n)
Definition at line 219 of file module.c.
References Unit_Lower_Triangular_Solve(), and Upper_Triangular_Solve().
fun()
int fun (float * A, float * invA, float * b, float * x, float * I)
Definition at line 254 of file module.c.
References Doolittle_LU_Decomposition(), Doolittle_LU_Solve(), and invertMatrix().
invertMatrix()
int invertMatrix (float * LU, float * invA, float * I)
Definition at line 233 of file module.c.
References Doolittle_LU_Solve().
Unit_Lower_Triangular_Solve()
void Unit_Lower_Triangular_Solve (float * L, float B[], float x[], int n)
Definition at line 86 of file module.c.
Upper_Triangular_Solve()
int Upper_Triangular_Solve (float * U, float B[], float x[], int n)
Definition at line 36 of file module.c.