AadlParser Class Reference
#include <aadl_parser.hpp>
Public Member Functions
AadlParser (const DesignFlowManagerConstRef design_flow_manager, const std::string &file_name, const application_managerRef AppM, const ParameterConstRef parameters)
Constructor.
~AadlParser () override
Destuctor.
DesignFlowStep_Status Exec () override
Execute the step.
Protected Member Functions
void YYParse (const AadlParserDataRef data, const AadlFlexLexerRef lexer) const
Wrapper to yyparse.
Protected Attributes
const application_managerRef AppM
The application manager.
Additional Inherited Members
Detailed Description
Definition at line 83 of file aadl_parser.hpp.
Constructor & Destructor Documentation
AadlParser()
AadlParser::AadlParser (const DesignFlowManagerConstRef design_flow_manager, const std::string & file_name, const application_managerRef AppM, const ParameterConstRef parameters)
Constructor.
Parameters
design_flow_manager is the design flow manager
file_name is the file to be parsed
AppM is the application manager
parameters is the set of input parameters
Definition at line 97 of file aadl_parser.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and ~AadlParser().
 AadlParser()
AadlParser::~AadlParser () [override], [default]
Destuctor.
Referenced by AadlParser().
Member Function Documentation
Exec()
DesignFlowStep_Status AadlParser::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
Implements DesignFlowStep.
Definition at line 105 of file aadl_parser.cpp.
References AppM, AadlInformation::AadlParameter::asn_type, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, AadlInformation::AadlParameter::direction, AadlInformation::AadlParameter::endianess, AadlInformation::AadlParameter::Endianess(), ParserFlowStep::file_name, fileIO_istream_open(), refcount< T >::get(), AadlInformation::AadlParameter::GetDirection(), GetDirectory(), GetFile(), INDENT_DBG_MEX, AadlInformation::AadlParameter::name, DesignFlowStep::parameters, STR_CST_aadl_data_view, STR_CST_aadl_parameter_direction, STR_CST_aadl_parameter_endianess, STR_CST_aadl_parameter_type, STR_CST_string_separator, SUCCESS, THROW_ASSERT, THROW_ERROR, and YYParse().
YYParse()
void AadlParser::YYParse (const AadlParserDataRef data, const AadlFlexLexerRef lexer) const [protected]
Wrapper to yyparse.
Parameters
data is the data to be passed to the parser
lexer is the lexer
Referenced by Exec().
Field Documentation
AppM
const application_managerRef AadlParser::AppM [protected]
The application manager.
Definition at line 87 of file aadl_parser.hpp.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/aadl/aadl_parser.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/aadl/aadl_parser.cpp