BackendFlow Class Reference
#include <BackendFlow.hpp>
Public Types
enum type_t {
UNKNOWN,
ASIC,
XILINX_FPGA,
ALTERA_FPGA,
LATTICE_FPGA,
NANOXPLORE_FPGA
 }
implemented flow
Public Member Functions
BackendFlow (const ParameterConstRef Param, std::string flow_name, const target_managerRef target)
Constructor.
virtual ~BackendFlow ()
Destructor.
virtual std::string GenerateSynthesisScripts (const std::string &fu_name, const structural_managerRef SM, const std::list< std::string > &hdl_files, const std::list< std::string > &aux_files)
Generates the synthesis scripts for the specified design.
virtual void ExecuteSynthesis ()
Executes the synthesis with the implemented flow.
void Execute (const std::string &top_id, const std::string &top_normalized, const std::string &filestring, const std::string &filename_bench, const std::string &clock, double clk_period, bool syntax_check)
Executes the synthesis with the implemented flow.
std::string CreateScripts (const DesignParametersRef dp)
Creates the scripts for the specified tools in the right order, along with the overall configuration.
virtual void InitDesignParameters ()
Initializes the parameters.
void parse_flow (const XMLDomParserRef parser)
Creates the synthesis flow based on the user's requirements.
void create_xml_scripts (const std::string &xml_file)
Creates the XML script containing all the steps.
void add_backend_step (const BackendStepRef &step)
Adds a backend step to the list of the ones to be performed.
std::string get_flow_name () const
Returns the name of the flow.
void set_initial_parameters (const DesignParametersRef &flow_parameters, const CustomOrderedSet< std::string > &undefined_parameters)
Sets parameters.
void set_parameters (const DesignParametersRef &_flow_parameters)
Sets actual parameters.
area_modelRef get_used_resources () const
Returns the list of used resources.
time_modelRef get_timing_results () const
Returns the timing information.
Static Public Member Functions
static BackendFlowRef CreateFlow (const ParameterConstRef Param, const std::string &flow_name, const target_managerRef target)
Creates the flow specification based on the given parameters.
static type_t DetermineBackendFlowType (const target_deviceRef device, const ParameterConstRef parameters)
Determines the type of the backend flow based on the target device.
Protected Member Functions
void ParseBackendFlow (const std::string &flow_name)
Parses the description of the backend flow given its identifier.
void xload (const xml_element *node)
Loads the backend flow from an XML node.
virtual void WriteFlowConfiguration (std::ostream &script)=0
Writes the proper flow configuration in the output script.
virtual void CheckSynthesisResults ()=0
Checks the synthesis results and fills the corresponding datastructures.
Protected Attributes
const ParameterConstRef Param
class containing all the parameters
int debug_level
debugging level of the class
unsigned int output_level
verbosity level of the class
std::string flow_name
string-based identifier of the flow
std::string out_dir
name of the output directory
std::map< std::string, std::string > default_data
map between the identifiers of the synthesis flows and the corresponding implementations
const target_managerRef target
information about the target device
xml_element * root
root node of the configuration device
area_modelRef area_m
pointer to the datastructure containing information about the resources
time_modelRef time_m
pointer to the datastructure containing timing information
std::vector< BackendStepRef > steps
ordered list of synthesis steps
DesignParametersRef default_flow_parameters
set of design parameters to be set
CustomOrderedSet< std::string > undefined_parameters
list of undefined parameters
DesignParametersRef actual_parameters
set of design parameters with the actual values
std::string generated_synthesis_script
name of the synthesis script
Detailed Description
Definition at line 96 of file BackendFlow.hpp.
Member Enumeration Documentation
type_t
enum BackendFlow::type_t
implemented flow
Enumerator
UNKNOWN
ASIC
XILINX_FPGA
ALTERA_FPGA
LATTICE_FPGA
NANOXPLORE_FPGA
Definition at line 100 of file BackendFlow.hpp.
Constructor & Destructor Documentation
BackendFlow()
BackendFlow::BackendFlow (const ParameterConstRef _Param, std::string _flow_name, const target_managerRef _manager)
Constructor.
Autoheader include.
Parameters
Param is the reference to the class containing all the parameters
flow_name is a string representing the name of the flow
target is the datastructure containing all the information about the target of the synthesis
wrapper/synthesis/altera includes wrapper/synthesis/xilinx includes implemented flows target devices supported synthesis steps
Definition at line 206 of file BackendFlow.cpp.
References GET_CLASS, out_dir, Param, and ~BackendFlow().
Referenced by create_xml_scripts().
 BackendFlow()
BackendFlow::~BackendFlow () [virtual], [default]
Destructor.
Referenced by BackendFlow().
Member Function Documentation
add_backend_step()
void BackendFlow::add_backend_step (const BackendStepRef & step)
Adds a backend step to the list of the ones to be performed.
Parameters
step is the reference to the datastructure containing information about the step
add the step after all the previous ones
Definition at line 586 of file BackendFlow.cpp.
References steps.
Referenced by create_xml_scripts(), and xload().
CheckSynthesisResults()
virtual void BackendFlow::CheckSynthesisResults () [protected], [pure virtual]
Checks the synthesis results and fills the corresponding datastructures.
Implemented in XilinxBackendFlow, NanoXploreBackendFlow, AlteraBackendFlow, LatticeBackendFlow, and ASICBackendFlow.
Referenced by ExecuteSynthesis().
create_xml_scripts()
void BackendFlow::create_xml_scripts (const std::string & xml_file)
Creates the XML script containing all the steps.
Definition at line 686 of file BackendFlow.cpp.
References add_backend_step(), xml_child::add_child_element(), BackendFlow(), DesignParameters::chain_name, SynthesisTool::create_synthesis_tool(), DEBUG_LEVEL_MINIMUM, SynthesisTool::DESIGN_COMPILER, DESIGN_COMPILER_TOOL_ID, fileIO_istream_open(), attribute_sequence::get_attribute(), xml_child::get_child_text(), xml_child::get_children(), xml_text_node::get_content(), xml_node::get_name(), xml_attribute::get_value(), INDENT_DBG_MEX, NOT_YET_IMPLEMENTED, Param, DesignParameters::parameter_values, test_panda::parser, xml_document::set_encoding(), set_initial_parameters(), xml_node::set_name(), steps, STR, THROW_ASSERT, THROW_ERROR, test_panda::type, undefined_parameters, SynthesisTool::UNKNOWN, and xml_document::write_to_file_formatted().
Referenced by CreateScripts().
CreateFlow()
BackendFlowRef BackendFlow::CreateFlow (const ParameterConstRef Param, const std::string & flow_name, const target_managerRef target) [static]
Creates the flow specification based on the given parameters.
Definition at line 264 of file BackendFlow.cpp.
References ALTERA_FPGA, ASIC, DetermineBackendFlowType(), LATTICE_FPGA, NANOXPLORE_FPGA, Param, THROW_UNREACHABLE, test_panda::type, UNKNOWN, and XILINX_FPGA.
Referenced by RTLCharacterization::AnalyzeCell(), and HLS_manager::get_backend_flow().
CreateScripts()
std::string BackendFlow::CreateScripts (const DesignParametersRef dp)
Creates the scripts for the specified tools in the right order, along with the overall configuration.
output directory
script file
Definition at line 592 of file BackendFlow.cpp.
References DesignParameters::chain_name, DesignParameters::clone(), DesignParameters::component_name, ToolManager::configure(), create_xml_scripts(), DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, default_flow_parameters, ToolManager::execute(), generated_synthesis_script, INDENT_DBG_MEX, Param, DesignParameters::parameter_values, test_panda::parameters, PRINT_MSG, steps, STR, THROW_ASSERT, THROW_ERROR, undefined_parameters, and WriteFlowConfiguration().
Referenced by XilinxTasteBackendFlow::GenerateSynthesisScripts(), and GenerateSynthesisScripts().
DetermineBackendFlowType()
BackendFlow::type_t BackendFlow::DetermineBackendFlowType (const target_deviceRef device, const ParameterConstRef parameters) [static]
Determines the type of the backend flow based on the target device.
Definition at line 223 of file BackendFlow.cpp.
References ALTERA_FPGA, ASIC, target_device::get_parameter(), target_device::has_parameter(), LATTICE_FPGA, NANOXPLORE_FPGA, test_panda::parameters, THROW_ERROR, UNKNOWN, and XILINX_FPGA.
Referenced by CreateFlow(), and GenerateSimulationScripts::Exec().
Execute()
void BackendFlow::Execute (const std::string & top_id, const std::string & top_normalized, const std::string & filestring, const std::string & filename_bench, const std::string & clock, double clk_period, bool syntax_check)
Executes the synthesis with the implemented flow.
ExecuteSynthesis()
void BackendFlow::ExecuteSynthesis () [virtual]
Executes the synthesis with the implemented flow.
Reimplemented in XilinxBackendFlow, NanoXploreBackendFlow, AlteraBackendFlow, and LatticeBackendFlow.
Definition at line 380 of file BackendFlow.cpp.
References CheckSynthesisResults(), ToolManager::configure(), DEBUG_LEVEL_VERY_PEDANTIC, ToolManager::execute(), generated_synthesis_script, INDENT_DBG_MEX, Param, test_panda::parameters, and steps.
Referenced by RTLCharacterization::AnalyzeCell(), AlteraBackendFlow::ExecuteSynthesis(), LatticeBackendFlow::ExecuteSynthesis(), NanoXploreBackendFlow::ExecuteSynthesis(), and XilinxBackendFlow::ExecuteSynthesis().
GenerateSynthesisScripts()
std::string BackendFlow::GenerateSynthesisScripts (const std::string & fu_name, const structural_managerRef SM, const std::list< std::string > & hdl_files, const std::list< std::string > & aux_files) [virtual]
Generates the synthesis scripts for the specified design.
Reimplemented in XilinxTasteBackendFlow.
Definition at line 290 of file BackendFlow.cpp.
References actual_parameters, DesignParameters::chain_name, CLOCK_PORT_NAME, functional_unit::COMBINATIONAL, DesignParameters::component_name, CreateScripts(), DEBUG_LEVEL_VERY_PEDANTIC, flow_name, structural_manager::get_circ(), technology_manager::get_fu(), structural_object::get_id(), technology_manager::get_library(), INDENT_DBG_MEX, InitDesignParameters(), Param, PARAM_backend_script_extensions, PARAM_clk_freq, PARAM_clk_name, PARAM_clk_period, PARAM_clk_period_default, PARAM_connect_iob, PARAM_fu, PARAM_has_script_extensions, PARAM_has_VHDL_library, PARAM_HDL_files, PARAM_is_combinational, PARAM_time_constrained, PARAM_top_id, PARAM_VHDL_library, DesignParameters::parameter_values, STR, and target.
Referenced by RTLCharacterization::AnalyzeCell().
get_flow_name()
std::string BackendFlow::get_flow_name () const
Returns the name of the flow.
Definition at line 581 of file BackendFlow.cpp.
References flow_name.
Referenced by AlteraBackendFlow::create_sdc().
get_timing_results()
time_modelRef BackendFlow::get_timing_results () const
Returns the timing information.
Definition at line 403 of file BackendFlow.cpp.
References time_m.
Referenced by RTLCharacterization::AnalyzeCell().
get_used_resources()
area_modelRef BackendFlow::get_used_resources () const
Returns the list of used resources.
Definition at line 398 of file BackendFlow.cpp.
References area_m.
Referenced by RTLCharacterization::AnalyzeCell().
InitDesignParameters()
void BackendFlow::InitDesignParameters () [virtual]
Initializes the parameters.
nothing to do
Reimplemented in XilinxBackendFlow, NanoXploreBackendFlow, AlteraBackendFlow, LatticeBackendFlow, and ASICBackendFlow.
Definition at line 864 of file BackendFlow.cpp.
Referenced by GenerateSynthesisScripts().
parse_flow()
void BackendFlow::parse_flow (const XMLDomParserRef parser)
Creates the synthesis flow based on the user's requirements.
Parameters
xml_file is the XML-based configuration file of the entire flow
Definition at line 408 of file BackendFlow.cpp.
References flow_name, xml_child::get_children(), xml_node::get_name(), LOAD_XVM, root, and xload().
Referenced by AlteraBackendFlow::AlteraBackendFlow(), ASICBackendFlow::ASICBackendFlow(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), and XilinxBackendFlow::XilinxBackendFlow().
ParseBackendFlow()
void BackendFlow::ParseBackendFlow (const std::string & flow_name) [protected]
Parses the description of the backend flow given its identifier.
Parameters
flow_name is the string that represents the identifier of the flow
set_initial_parameters()
void BackendFlow::set_initial_parameters (const DesignParametersRef & flow_parameters, const CustomOrderedSet< std::string > & undefined_parameters)
Sets parameters.
Definition at line 680 of file BackendFlow.cpp.
References default_flow_parameters, and undefined_parameters.
Referenced by create_xml_scripts().
set_parameters()
void BackendFlow::set_parameters (const DesignParametersRef & _flow_parameters)
Sets actual parameters.
WriteFlowConfiguration()
virtual void BackendFlow::WriteFlowConfiguration (std::ostream & script) [protected], [pure virtual]
Writes the proper flow configuration in the output script.
Implemented in XilinxBackendFlow, NanoXploreBackendFlow, AlteraBackendFlow, LatticeBackendFlow, and ASICBackendFlow.
Referenced by CreateScripts().
xload()
void BackendFlow::xload (const xml_element * node) [protected]
Loads the backend flow from an XML node.
list of supported synthesis steps
update with the actual name of the output directory
parse the proper script configuration for the tool in the device configuration XML
Definition at line 427 of file BackendFlow.cpp.
References add_backend_step(), CE_XVM, DesignParameters::chain_name, SynthesisTool::create_synthesis_tool(), default_flow_parameters, SynthesisTool::DESIGN_COMPILER, DESIGN_COMPILER_TOOL_ID, flow_name, xml_child::get_children(), xml_node::get_name(), SynthesisTool::LATTICE_FLOW, LATTICE_FLOW_TOOL_ID, LOAD_XVFM, LOAD_XVM, SynthesisTool::MAP, MAP_TOOL_ID, SynthesisTool::NGDBUILD, NGDBUILD_TOOL_ID, SynthesisTool::NXPYTHON_FLOW, NXPYTHON_FLOW_TOOL_ID, out_dir, SynthesisTool::PAR, PAR_TOOL_ID, Param, SynthesisTool::QUARTUS_13_FLOW, QUARTUS_13_FLOW_TOOL_ID, QUARTUS_13_REPORT_TOOL_ID, SynthesisTool::QUARTUS_13_SETUP, QUARTUS_13_SETUP_TOOL_ID, SynthesisTool::QUARTUS_13_STA, SynthesisTool::QUARTUS_FLOW, QUARTUS_FLOW_TOOL_ID, SynthesisTool::QUARTUS_POW, QUARTUS_POWER_TOOL_ID, QUARTUS_REPORT_TOOL_ID, SynthesisTool::QUARTUS_SETUP, QUARTUS_SETUP_TOOL_ID, SynthesisTool::QUARTUS_STA, root, target, THROW_ASSERT, THROW_ERROR, SynthesisTool::TRCE, TRCE_TOOL_ID, test_panda::type, SynthesisTool::UNKNOWN, SynthesisTool::VIVADO_FLOW, VIVADO_FLOW_TOOL_ID, SynthesisTool::XST, and XST_TOOL_ID.
Referenced by parse_flow().
Field Documentation
actual_parameters
DesignParametersRef BackendFlow::actual_parameters [protected]
set of design parameters with the actual values
Definition at line 154 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), GenerateSynthesisScripts(), ASICBackendFlow::InitDesignParameters(), AlteraBackendFlow::InitDesignParameters(), LatticeBackendFlow::InitDesignParameters(), NanoXploreBackendFlow::InitDesignParameters(), XilinxBackendFlow::InitDesignParameters(), and XilinxBackendFlow::parse_timing().
area_m
area_modelRef BackendFlow::area_m [protected]
pointer to the datastructure containing information about the resources
Definition at line 139 of file BackendFlow.hpp.
Referenced by ASICBackendFlow::CheckSynthesisResults(), AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), get_used_resources(), XilinxBackendFlow::parse_DSPs(), XilinxBackendFlow::xparse_map_utilization(), and XilinxBackendFlow::xparse_xst_utilization().
debug_level
int BackendFlow::debug_level [protected]
debugging level of the class
Definition at line 118 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), NanoXploreBackendFlow::InitDesignParameters(), XilinxBackendFlow::InitDesignParameters(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), AlteraBackendFlow::WriteFlowConfiguration(), NanoXploreBackendFlow::WriteFlowConfiguration(), XilinxBackendFlow::XilinxBackendFlow(), and XilinxTasteBackendFlow::XilinxTasteBackendFlow().
default_data
std::map<std::string, std::string> BackendFlow::default_data [protected]
map between the identifiers of the synthesis flows and the corresponding implementations
Definition at line 130 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), ASICBackendFlow::ASICBackendFlow(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), and XilinxBackendFlow::XilinxBackendFlow().
default_flow_parameters
DesignParametersRef BackendFlow::default_flow_parameters [protected]
set of design parameters to be set
Definition at line 148 of file BackendFlow.hpp.
Referenced by CreateScripts(), set_initial_parameters(), and xload().
flow_name
std::string BackendFlow::flow_name [protected]
string-based identifier of the flow
Definition at line 124 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), GenerateSynthesisScripts(), get_flow_name(), parse_flow(), XilinxBackendFlow::parse_timing(), xload(), and XilinxBackendFlow::xparse_timing().
generated_synthesis_script
std::string BackendFlow::generated_synthesis_script [protected]
name of the synthesis script
Definition at line 157 of file BackendFlow.hpp.
Referenced by CreateScripts(), and ExecuteSynthesis().
out_dir
std::string BackendFlow::out_dir [protected]
name of the output directory
Definition at line 127 of file BackendFlow.hpp.
Referenced by BackendFlow(), ASICBackendFlow::create_sdc(), AlteraBackendFlow::create_sdc(), LatticeBackendFlow::create_sdc(), and xload().
output_level
unsigned int BackendFlow::output_level [protected]
verbosity level of the class
Definition at line 121 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), ASICBackendFlow::ASICBackendFlow(), ASICBackendFlow::CheckSynthesisResults(), AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::InitDesignParameters(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), XilinxBackendFlow::parse_timing(), and XilinxBackendFlow::XilinxBackendFlow().
Param
const ParameterConstRef BackendFlow::Param [protected]
class containing all the parameters
Definition at line 115 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), ASICBackendFlow::ASICBackendFlow(), BackendFlow(), AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::create_cf(), ASICBackendFlow::create_sdc(), AlteraBackendFlow::create_sdc(), LatticeBackendFlow::create_sdc(), create_xml_scripts(), CreateFlow(), CreateScripts(), ExecuteSynthesis(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), GenerateSynthesisScripts(), LatticeBackendFlow::InitDesignParameters(), AlteraBackendFlow::InitDesignParameters(), NanoXploreBackendFlow::InitDesignParameters(), XilinxBackendFlow::InitDesignParameters(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), XilinxBackendFlow::parse_timing(), AlteraBackendFlow::WriteFlowConfiguration(), XilinxBackendFlow::XilinxBackendFlow(), xload(), XilinxBackendFlow::xparse_map_utilization(), XilinxBackendFlow::xparse_timing(), and XilinxBackendFlow::xparse_xst_utilization().
root
xml_element* BackendFlow::root [protected]
root node of the configuration device
Definition at line 136 of file BackendFlow.hpp.
Referenced by parse_flow(), and xload().
steps
std::vector<BackendStepRef> BackendFlow::steps [protected]
ordered list of synthesis steps
Definition at line 145 of file BackendFlow.hpp.
Referenced by add_backend_step(), ASICBackendFlow::CheckSynthesisResults(), create_xml_scripts(), CreateScripts(), ExecuteSynthesis(), ASICBackendFlow::InitDesignParameters(), AlteraBackendFlow::InitDesignParameters(), LatticeBackendFlow::InitDesignParameters(), NanoXploreBackendFlow::InitDesignParameters(), and XilinxBackendFlow::InitDesignParameters().
target
const target_managerRef BackendFlow::target [protected]
information about the target device
Definition at line 133 of file BackendFlow.hpp.
Referenced by AlteraBackendFlow::AlteraBackendFlow(), XilinxBackendFlow::CheckSynthesisResults(), XilinxTasteBackendFlow::GenerateSynthesisScripts(), GenerateSynthesisScripts(), AlteraBackendFlow::InitDesignParameters(), LatticeBackendFlow::InitDesignParameters(), NanoXploreBackendFlow::InitDesignParameters(), XilinxBackendFlow::InitDesignParameters(), LatticeBackendFlow::LatticeBackendFlow(), NanoXploreBackendFlow::NanoXploreBackendFlow(), XilinxBackendFlow::WriteFlowConfiguration(), XilinxBackendFlow::XilinxBackendFlow(), and xload().
time_m
time_modelRef BackendFlow::time_m [protected]
pointer to the datastructure containing timing information
Definition at line 142 of file BackendFlow.hpp.
Referenced by ASICBackendFlow::CheckSynthesisResults(), AlteraBackendFlow::CheckSynthesisResults(), LatticeBackendFlow::CheckSynthesisResults(), NanoXploreBackendFlow::CheckSynthesisResults(), XilinxBackendFlow::CheckSynthesisResults(), get_timing_results(), XilinxBackendFlow::parse_timing(), and XilinxBackendFlow::xparse_timing().
undefined_parameters
CustomOrderedSet<std::string> BackendFlow::undefined_parameters [protected]
list of undefined parameters
Definition at line 151 of file BackendFlow.hpp.
Referenced by create_xml_scripts(), CreateScripts(), and set_initial_parameters().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/BackendFlow.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/BackendFlow.cpp