expr_pack_expansion Struct Reference
Represents an expression that will be expanded into a list of expressions when instantiated with one or more argument packs.
#include <tree_node.hpp>
Public Types
enum { GETID =(expr_node) = 0,
GETID =(expr_node) = 0,
GETID =(expr_node) = 0
 }
visitor enum
Public Member Functions
expr_pack_expansion (unsigned int i)
constructor
void visit (tree_node_visitor *const v) const override
Redefinition of get_kind_text.
Data Fields
tree_nodeRef op
PACK_EXPANSION_PATTERN.
tree_nodeRef param_packs
PACK_EXPANSION_PARAMETER_PACKS.
tree_nodeRef arg
PACK_EXPANSION_EXTRA_ARGS.
Additional Inherited Members
Detailed Description
Represents an expression that will be expanded into a list of expressions when instantiated with one or more argument packs.
EXPR_PACK_EXPANSION plays precisely the same role as TYPE_PACK_EXPANSION, but will be used for expressions.
Definition at line 2193 of file tree_node.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
visitor enum
Enumerator
GETID
GETID
GETID
Definition at line 2222 of file tree_node.hpp.
Constructor & Destructor Documentation
expr_pack_expansion()
expr_pack_expansion::expr_pack_expansion (unsigned int i) [inline], [explicit]
constructor
Definition at line 2196 of file tree_node.hpp.
Member Function Documentation
visit()
void expr_pack_expansion::visit (tree_node_visitor *const v) const [override], [virtual]
Redefinition of get_kind_text.
Redefinition of get_kind. virtual function used to traverse the tree_node data structure.
Parameters
v is a reference to the tree_node visitor class
Reimplemented from expr_node.
Definition at line 1468 of file tree_node.cpp.
References ALL_VISIT, test_panda::arg, tree_node::index, TreeNodeConstSorter::operator()(), TreeNodeSorter::operator()(), TreeNodeConstSet::TreeNodeConstSet(), TreeNodeConstSorter::TreeNodeConstSorter(), TreeNodeSet::TreeNodeSet(), TreeNodeSorter::TreeNodeSorter(), var_decl::visit(), VISIT_MEMBER, and VISIT_SC.
Field Documentation
arg
tree_nodeRef expr_pack_expansion::arg
PACK_EXPANSION_EXTRA_ARGS.
Definition at line 2207 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), and raw_writer::write_when_not_null_point_to().
op
tree_nodeRef expr_pack_expansion::op
PACK_EXPANSION_PATTERN.
Definition at line 2201 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), and raw_writer::write_when_not_null_point_to().
param_packs
tree_nodeRef expr_pack_expansion::param_packs
PACK_EXPANSION_PARAMETER_PACKS.
Definition at line 2204 of file tree_node.hpp.
Referenced by GimpleWriter::GimpleWriter(), and raw_writer::write_when_not_null_point_to().
The documentation for this struct was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.hpp
/home/osboxes/bambu/PandA-bambu/src/tree/tree_node.cpp