xml_attribute Class Reference
#include <xml_attribute.hpp>
Public Member Functions
xml_attribute (const std::string &_name)
constructor
void print (std::ostream &os, bool, simple_indent *) const override
Print the class.
std::string get_value () const
Get the value of this attribute.
void set_value (const std::string &value)
Set the value of this attribute.
Private Attributes
std::string at_value
Additional Inherited Members
Detailed Description
Definition at line 67 of file xml_attribute.hpp.
Constructor & Destructor Documentation
xml_attribute()
xml_attribute::xml_attribute (const std::string & _name) [inline], [explicit]
constructor
Definition at line 73 of file xml_attribute.hpp.
Referenced by attribute_sequence::set_attribute().
Member Function Documentation
get_value()
std::string xml_attribute::get_value () const [inline]
Get the value of this attribute.
Returns
The node's value.
Definition at line 98 of file xml_attribute.hpp.
References at_value.
Referenced by BackendFlow::create_xml_scripts(), Parameter::GetFileFormat(), DataXmlParser::Parse(), GccWrapper::ReadXml(), attribute::xload(), xml_command_t::xml_command_t(), xml_foreach_t::xml_foreach_t(), xml_parameter_t::xml_parameter_t(), xml_set_entry_t::xml_set_entry_t(), xml_set_variable_t::xml_set_variable_t(), and xml_shell_t::xml_shell_t().
print()
void xml_attribute::print (std::ostream & os, bool , simple_indent *) const [inline], [override], [virtual]
Print the class.
Parameters
os is the stream.
formatted when true the xml is formatted in human readable way.
pp is the pretty print helper.
replace '
' character with the escaped version `\\n`
Implements xml_node.
Definition at line 83 of file xml_attribute.hpp.
References xml_node::convert_unescaped(), and xml_node::get_name().
set_value()
void xml_attribute::set_value (const std::string & value) [inline]
Set the value of this attribute.
Parameters
The attribute's value.
Definition at line 106 of file xml_attribute.hpp.
Referenced by attribute_sequence::set_attribute().
Field Documentation
at_value
std::string xml_attribute::at_value [private]
Definition at line 69 of file xml_attribute.hpp.
Referenced by get_value().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_attribute.hpp