ParserFlowStepFactory Class Reference
#include <parser_flow_step_factory.hpp>
Public Member Functions
ParserFlowStepFactory (const DesignFlowManagerConstRef design_flow_manager, const application_managerRef AppM, const ParameterConstRef parameters)
Constructor.
~ParserFlowStepFactory () override
Destructor.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
DesignFlowStepRef CreateFlowStep (const std::string &signature) const override
Return a step given the signature.
Protected Attributes
const application_managerRef AppM
The application manager.
Detailed Description
Definition at line 53 of file parser_flow_step_factory.hpp.
Constructor & Destructor Documentation
ParserFlowStepFactory()
ParserFlowStepFactory::ParserFlowStepFactory (const DesignFlowManagerConstRef _design_flow_manager, const application_managerRef _AppM, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
AppM is the application manager
parameters is the set of input parameters
Autoheader includes parser include
Definition at line 57 of file parser_flow_step_factory.cpp.
References ~ParserFlowStepFactory().
 ParserFlowStepFactory()
ParserFlowStepFactory::~ParserFlowStepFactory () [override], [default]
Destructor.
Referenced by ParserFlowStepFactory().
Member Function Documentation
CreateFlowStep()
DesignFlowStepRef ParserFlowStepFactory::CreateFlowStep (const std::string & signature) const [override], [virtual]
Return a step given the signature.
Parameters
signature is the signature of the step to be created
Returns
the created step
Reimplemented from DesignFlowStepFactory.
Definition at line 68 of file parser_flow_step_factory.cpp.
References AppM, DesignFlowStepFactory::design_flow_manager, GetPrefix(), Wrefcount< T >::lock(), DesignFlowStepFactory::parameters, THROW_ASSERT, and THROW_UNREACHABLE.
GetPrefix()
const std::string ParserFlowStepFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 63 of file parser_flow_step_factory.cpp.
Referenced by CreateFlowStep().
Field Documentation
AppM
const application_managerRef ParserFlowStepFactory::AppM [protected]
The application manager.
Definition at line 57 of file parser_flow_step_factory.hpp.
Referenced by CreateFlowStep().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/parser/parser_flow_step_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/parser/parser_flow_step_factory.cpp