InstructionWriter Class Reference
#include <instruction_writer.hpp>
Public Member Functions
virtual ~InstructionWriter ()
Destructor.
virtual void Initialize ()
Initialize data structure.
virtual void write (const FunctionBehaviorConstRef function_behavior, const vertex statement, const var_pp_functorConstRef varFunctor)
Write a statement.
virtual void declareFunction (const unsigned int function_id)
Write the declaration of a function.
virtual void write_declarations ()
Write code needed for declaration/initialization of auxiliary variables.
void WriteComment (const std::string &comment)
Writes a comment.
Static Public Member Functions
static InstructionWriterRef CreateInstructionWriter (const ActorGraphBackend_Type actor_graph_backend_type, const application_managerConstRef AppM, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters)
Factory method.
Protected Member Functions
InstructionWriter (const application_managerConstRef AppM, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters)
Constructor; it is protected since factory method should be used.
Protected Attributes
const application_managerConstRef AppM
The application manager.
const IndentedOutputStreamRef indented_output_stream
The indented output stream.
const ParameterConstRef parameters
The set of input parameters.
int debug_level
The debug level.
Detailed Description
Definition at line 68 of file instruction_writer.hpp.
Constructor & Destructor Documentation
InstructionWriter()
InstructionWriter::InstructionWriter (const application_managerConstRef _AppM, const IndentedOutputStreamRef _indented_output_stream, const ParameterConstRef _parameters) [protected]
Constructor; it is protected since factory method should be used.
Autoheader include.
Parameters
AppM is the application manager
indented_output_stream is the output stream for source code
parameters is the set of input parameters
Header include behavior include design_flows/backend/ToC/source_code_writers design_flows/codesign/partitioning/graph_partitioningh Backend include Behavior include design_flows/backend/ToC/progmodels include Graph include Parameter include STD include tree includes utility include
Definition at line 103 of file instruction_writer.cpp.
References debug_level, GET_CLASS, and parameters.
Referenced by CreateInstructionWriter().
 InstructionWriter()
InstructionWriter::~InstructionWriter () [virtual], [default]
Destructor.
Referenced by CreateInstructionWriter().
Member Function Documentation
CreateInstructionWriter()
InstructionWriterRef InstructionWriter::CreateInstructionWriter (const ActorGraphBackend_Type actor_graph_backend_type, const application_managerConstRef AppM, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef parameters) [static]
Factory method.
Parameters
actor_graph_backend_type is the type of thread model to be considered in backend
AppM is the application manager
indented_output_stream is the output stream
parameters is the set of input parameters
Definition at line 109 of file instruction_writer.cpp.
References BA_NONE, InstructionWriter(), THROW_UNREACHABLE, and ~InstructionWriter().
Referenced by CWriter::CreateCWriter().
declareFunction()
void InstructionWriter::declareFunction (const unsigned int function_id) [virtual]
Write the declaration of a function.
Parameters
function_id is the index of the function
Reimplemented in HLSInstructionWriter, and discrepancy_instruction_writer.
Definition at line 154 of file instruction_writer.cpp.
References IndentedOutputStream::Append(), AppM, indented_output_stream, and BehavioralHelper::print_type().
Initialize()
void InstructionWriter::Initialize () [virtual]
Initialize data structure.
Definition at line 142 of file instruction_writer.cpp.
write()
void InstructionWriter::write (const FunctionBehaviorConstRef function_behavior, const vertex statement, const var_pp_functorConstRef varFunctor) [virtual]
Write a statement.
Parameters
function_behavior is the function to which the statement belongs
statement is the statement to be printed
varFunctor is the variable functor
Definition at line 146 of file instruction_writer.cpp.
References IndentedOutputStream::Append(), FunctionBehavior::CFG, FunctionBehavior::CGetBehavioralHelper(), FunctionBehavior::CGetOpGraph(), indented_output_stream, and BehavioralHelper::print_vertex().
write_declarations()
void InstructionWriter::write_declarations () [virtual]
Write code needed for declaration/initialization of auxiliary variables.
Definition at line 160 of file instruction_writer.cpp.
WriteComment()
void InstructionWriter::WriteComment (const std::string & comment)
Writes a comment.
Parameters
comment is the string to be printed
Definition at line 164 of file instruction_writer.cpp.
References IndentedOutputStream::Append(), and indented_output_stream.
Field Documentation
AppM
const application_managerConstRef InstructionWriter::AppM [protected]
The application manager.
Definition at line 72 of file instruction_writer.hpp.
Referenced by discrepancy_instruction_writer::declareFunction(), HLSInstructionWriter::declareFunction(), and declareFunction().
debug_level
int InstructionWriter::debug_level [protected]
The debug level.
Definition at line 81 of file instruction_writer.hpp.
Referenced by InstructionWriter().
indented_output_stream
const IndentedOutputStreamRef InstructionWriter::indented_output_stream [protected]
The indented output stream.
Definition at line 75 of file instruction_writer.hpp.
Referenced by HLSInstructionWriter::declareFunction(), declareFunction(), write(), and WriteComment().
parameters
const ParameterConstRef InstructionWriter::parameters [protected]
The set of input parameters.
Definition at line 78 of file instruction_writer.hpp.
Referenced by HLSInstructionWriter::declareFunction(), and InstructionWriter().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/instruction_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/instruction_writer.cpp