check_clique< vertex_type > Struct Template Reference
Autoheader include.
#include <check_clique.hpp>
Public Member Functions
virtual ~check_clique ()
virtual bool check_edge_compatibility (C_vertex &rep, C_vertex &other)=0
virtual bool check_no_mux_needed (C_vertex &rep, C_vertex &other)=0
virtual check_clique * clone () const =0
virtual double cost (size_t clique_count)=0
virtual size_t num_mux ()=0
virtual void update_after_join (C_vertex &, C_vertex &)=0
virtual void initialize_structures (boost_cc_compatibility_graph &, std::map< C_vertex, vertex_type > &)=0
Detailed Description
template<typename vertex_type>
struct check_clique< vertex_type >
Autoheader include.
matrix includes
Definition at line 45 of file check_clique.hpp.
Constructor & Destructor Documentation
 check_clique()
template<typename vertex_type>
virtual check_clique< vertex_type >::~check_clique () [inline], [virtual]
Definition at line 47 of file check_clique.hpp.
References check_clique< vertex_type >::check_edge_compatibility(), check_clique< vertex_type >::check_no_mux_needed(), check_clique< vertex_type >::clone(), check_clique< vertex_type >::cost(), check_clique< vertex_type >::initialize_structures(), check_clique< vertex_type >::num_mux(), and check_clique< vertex_type >::update_after_join().
Member Function Documentation
check_edge_compatibility()
template<typename vertex_type>
virtual bool check_clique< vertex_type >::check_edge_compatibility (C_vertex & rep, C_vertex & other) [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by check_clique< vertex_type >::~check_clique().
check_no_mux_needed()
template<typename vertex_type>
virtual bool check_clique< vertex_type >::check_no_mux_needed (C_vertex & rep, C_vertex & other) [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by check_clique< vertex_type >::~check_clique().
clone()
template<typename vertex_type>
virtual check_clique* check_clique< vertex_type >::clone () const [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by check_clique< vertex_type >::~check_clique().
cost()
template<typename vertex_type>
virtual double check_clique< vertex_type >::cost (size_t clique_count) [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by check_clique< vertex_type >::~check_clique().
initialize_structures()
template<typename vertex_type>
virtual void check_clique< vertex_type >::initialize_structures (boost_cc_compatibility_graph & , std::map< C_vertex, vertex_type > &) [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by bipartite_matching_clique_covering< vertex_type >::max_resources(), and check_clique< vertex_type >::~check_clique().
num_mux()
template<typename vertex_type>
virtual size_t check_clique< vertex_type >::num_mux () [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by check_clique< vertex_type >::~check_clique().
update_after_join()
template<typename vertex_type>
virtual void check_clique< vertex_type >::update_after_join (C_vertex & , C_vertex &) [pure virtual]
Implemented in module_binding_check< vertex_type >, and no_check_clique< vertex_type >.
Referenced by check_clique< vertex_type >::~check_clique().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/clique_covering/check_clique.hpp