TestbenchValuesXMLGeneration Class Reference
TestbenchValuesXMLGeneration is the step which generates values.txt exploiting only values stored in xml (output included)
#include <testbench_values_xml_generation.hpp>
Public Member Functions
TestbenchValuesXMLGeneration (const ParameterConstRef parameters, const HLS_managerRef hls_manager, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
virtual ~TestbenchValuesXMLGeneration ()
Destructor.
DesignFlowStep_Status Exec ()
Execute the step.
bool HasToBeExecuted () const
Check if this step has actually to be executed.
Protected Member Functions
virtual void Initialize ()
Initialize the step (i.e., like a constructor, but executed just before exec.
virtual const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const
Compute the relationship of this step.
Protected Attributes
const tree_managerConstRef TM
The tree manager.
const std::string output_directory
output directory
Additional Inherited Members
Detailed Description
TestbenchValuesXMLGeneration is the step which generates values.txt exploiting only values stored in xml (output included)
Definition at line 58 of file testbench_values_xml_generation.hpp.
Constructor & Destructor Documentation
TestbenchValuesXMLGeneration()
TestbenchValuesXMLGeneration::TestbenchValuesXMLGeneration (const ParameterConstRef parameters, const HLS_managerRef hls_manager, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
parameters is the set of the input parameters
hls_manager is the HLS manager
design_flow_manager is the design flow manager
Definition at line 97 of file testbench_values_xml_generation.cpp.
References DesignFlowStep::debug_level, GET_CLASS, output_directory, and DesignFlowStep::parameters.
 TestbenchValuesXMLGeneration()
TestbenchValuesXMLGeneration::~TestbenchValuesXMLGeneration () [virtual]
Destructor.
Definition at line 105 of file testbench_values_xml_generation.cpp.
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > TestbenchValuesXMLGeneration::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 109 of file testbench_values_xml_generation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, TEST_VECTOR_PARSER, THROW_UNREACHABLE, and TOP_FUNCTION.
Exec()
DesignFlowStep_Status TestbenchValuesXMLGeneration::Exec () [virtual]
Execute the step.
Returns
the exit status of this step
print base address
This is the lis of memory variables and of pointer parameters
Initialization of memory variables which are not pointer parameters
Parameter: read initialization from parsed xml
Retrieve the space to be reserved in memory
Call the parser to translate C initialization to verilog initialization
Implements DesignFlowStep.
Definition at line 133 of file testbench_values_xml_generation.cpp.
References tree_manager::CGetTreeNode(), ConvertInBinary(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, tree_manager::get_tree_node_const(), tree_helper::get_type_index(), HLS_step::HLSMgr, INDENT_DBG_MEX, INPUT_PARAMETER, tree_helper::is_a_pointer(), MEMORY_INITIALIZATION, output_directory, OUTPUT_PARAMETER, DesignFlowStep::parameters, TestbenchGenerationBaseStep::print_var_init(), RETURN, tree_helper::size(), SplitString(), STR, STR_CST_testbench_generation_basename, SUCCESS, THROW_ASSERT, TM, and test_panda::type.
HasToBeExecuted()
bool TestbenchValuesXMLGeneration::HasToBeExecuted () const [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Implements DesignFlowStep.
Definition at line 327 of file testbench_values_xml_generation.cpp.
Initialize()
void TestbenchValuesXMLGeneration::Initialize () [protected], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Header include.
. include behavior includes boost include constants include HLS include HLS/memory includes HLS/simulation includes STD include STL includes tree includes utility includes
Reimplemented from DesignFlowStep.
Definition at line 93 of file testbench_values_xml_generation.cpp.
Field Documentation
output_directory
const std::string TestbenchValuesXMLGeneration::output_directory [protected]
output directory
Definition at line 65 of file testbench_values_xml_generation.hpp.
Referenced by Exec(), and TestbenchValuesXMLGeneration().
TM
const tree_managerConstRef TestbenchValuesXMLGeneration::TM [protected]
The tree manager.
Definition at line 62 of file testbench_values_xml_generation.hpp.
Referenced by Exec().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_values_xml_generation.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/simulation/testbench_values_xml_generation.cpp