LoopsAnalysisBambu Class Reference
loops computation analysis step
#include <loops_analysis_bambu.hpp>
Public Member Functions
LoopsAnalysisBambu (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~LoopsAnalysisBambu () override
Destructor.
DesignFlowStep_Status InternalExec () override
Performs the loops analysis.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
loops computation analysis step
Definition at line 57 of file loops_analysis_bambu.hpp.
Constructor & Destructor Documentation
LoopsAnalysisBambu()
LoopsAnalysisBambu::LoopsAnalysisBambu (const ParameterConstRef _parameters, const application_managerRef _AppM, unsigned int _function_id, const DesignFlowManagerConstRef _design_flow_manager)
Constructor.
Autoheader include.
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the node id of the function analyzed.
design_flow_manager is the design flow manager
Header include . include algorithms/loops_detection include behavior include pragma include tree include
Definition at line 70 of file loops_analysis_bambu.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~LoopsAnalysisBambu().
 LoopsAnalysisBambu()
LoopsAnalysisBambu::~LoopsAnalysisBambu () [override], [default]
Destructor.
Referenced by LoopsAnalysisBambu().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > LoopsAnalysisBambu::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 78 of file loops_analysis_bambu.cpp.
References FrontendFlowStep::AppM, BB_FEEDBACK_EDGES_IDENTIFICATION, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DOM_POST_DOM_COMPUTATION, FunctionFrontendFlowStep::function_id, GET_NODE, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOOPS_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, sl, THROW_ASSERT, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status LoopsAnalysisBambu::InternalExec () [override], [virtual]
Performs the loops analysis.
Returns
the exit status of this step
Get last basic block of the loop
Get exit condition of the loop
We assume that induction variable is the left one; if it is not, analysis will fail
Induction variable must be a ssa name
Look for its definition
Implements FunctionFrontendFlowStep.
Definition at line 130 of file loops_analysis_bambu.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), COUNTABLE_LOOP, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DO_WHILE_LOOP, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, graph::GetSelector(), INDENT_DBG_MEX, tree_node::index, NULL_VERTEX, DesignFlowStep::parameters, FunctionBehavior::POST_DOM_TREE, STR, SUCCESS, tree_node::ToString(), UNCHANGED, and UNKNOWN_LOOP.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/loops_analysis_bambu.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/loops_analysis_bambu.cpp