/home/osboxes/bambu/PandA-bambu/documentation/tutorial_fpl_2017/lab4/materials/4.1/main.c File Reference
#include <stdbool.h>
#include <stdint.h>
#include `checksum.h`
Functions
bool have_same_checksum (uint64_t original1, uint64_t original2, uint64_t reference1, uint64_t reference2)
int test (uint64_t original1, uint64_t original2, uint64_t reference1, uint64_t reference2, bool must_be_equal)
Function Documentation
have_same_checksum()
bool have_same_checksum (uint64_t original1, uint64_t original2, uint64_t reference1, uint64_t reference2)
Definition at line 6 of file main.c.
References checksum().
Referenced by test().
test()
int test (uint64_t original1, uint64_t original2, uint64_t reference1, uint64_t reference2, bool must_be_equal)
Definition at line 12 of file main.c.
References have_same_checksum().