xml_element Class Reference
#include <xml_element.hpp>
Public Member Functions
xml_element (const std::string &_name)
constructor
void print (std::ostream &os, bool formatted, simple_indent *pp) const override
Print the class.
Additional Inherited Members
Detailed Description
Definition at line 60 of file xml_element.hpp.
Constructor & Destructor Documentation
xml_element()
xml_element::xml_element (const std::string & _name) [inline], [explicit]
constructor
Definition at line 66 of file xml_element.hpp.
Member Function Documentation
print()
void xml_element::print (std::ostream & os, bool formatted, simple_indent * pp) const [inline], [override], [virtual]
Print the class.
Implements xml_node.
Definition at line 73 of file xml_element.hpp.
References xml_child::get_child_text(), xml_child::get_children(), xml_node::get_name(), attribute_sequence::has_attributes(), xml_child::has_child(), xml_child::print(), attribute_sequence::print_attributes(), STD_CLOSING_CHAR, STD_OPENING_CHAR, and THROW_ASSERT.
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_element.hpp