library_manager Class Reference
This class manages the specific library structure.
#include <library_manager.hpp>
Public Types
typedef std::map< std::string, technology_nodeRef > fu_map_type
typedef for the identification of the functional units contained into the library
 Library output formats
enum info_t { XML
 }
available information for the library
Public Member Functions
bool is_virtual () const
Check if the library is virtual or not.
void set_dont_use (const std::string &name)
Set a cell to be not used.
void remove_dont_use (const std::string &name)
Set a cell to be used.
CustomOrderedSet< std::string > get_dont_use_cells () const
Return the cells not to be used for the synthesis.
size_t get_dont_use_num () const
void set_info (unsigned int type, const std::string &information)
bool is_info (unsigned int type) const
std::string get_info (const info_t type, const TargetDevice_Type dv_type)
void erase_info ()
void xwrite (xml_element *rootnode, TargetDevice_Type dv_type)
std::string get_library_name () const
void add (const technology_nodeRef &node)
void update (const technology_nodeRef &node)
bool is_fu (const std::string &name) const
technology_nodeRef get_fu (const std::string &name) const
void remove_fu (const std::string &name)
size_t get_gate_count () const
const fu_map_type & get_library_fu () const
Return the list of the resources contained into the given library.
 Constructors and destructors.
library_manager (ParameterConstRef Param, bool std=true)
Constructor.
library_manager (std::string library_name, ParameterConstRef Param, bool std=true)
~library_manager ()
Destructor.
Static Public Member Functions
static void xload (const xml_element *node, const library_managerRef &LM, const ParameterConstRef &Param, const target_deviceRef &device)
Private Member Functions
void set_default_attributes ()
Set the default attributes for the library.
Private Attributes
const ParameterConstRef Param
class containing all the parameters
std::string name
string identifier of the library
fu_map_type fu_map
datastructure to identify the units that are contained into the library
std::vector< std::string > ordered_attributes
std::map< std::string, attributeRef > attributes
attributes of the library
std::map< unsigned int, std::string > info
files that provide information about the library
bool is_std
flag to check if the library is standard (i.e., provided in input) or virtual
CustomOrderedSet< std::string > dont_use
Detailed Description
This class manages the specific library structure.
Definition at line 129 of file library_manager.hpp.
Member Typedef Documentation
fu_map_type
typedef std::map<std::string, technology_nodeRef> library_manager::fu_map_type
typedef for the identification of the functional units contained into the library
Definition at line 133 of file library_manager.hpp.
Member Enumeration Documentation
info_t
enum library_manager::info_t
available information for the library
Enumerator
XML
Definition at line 140 of file library_manager.hpp.
Constructor & Destructor Documentation
library_manager() [1/2]
library_manager::library_manager (ParameterConstRef Param, bool std = true)
Constructor.
Definition at line 232 of file library_manager.cpp.
References set_default_attributes().
library_manager() [2/2]
library_manager::library_manager (std::string library_name, ParameterConstRef Param, bool std = true)
Definition at line 237 of file library_manager.cpp.
References set_default_attributes(), and ~library_manager().
 library_manager()
library_manager::~library_manager () [default]
Destructor.
Referenced by library_manager().
Member Function Documentation
add()
void library_manager::add (const technology_nodeRef & node)
adding a cells invalidates the library view currently stored
Definition at line 394 of file library_manager.cpp.
References erase_info(), fu_map, and technology_node::get_name().
Referenced by FunctionalUnitStep::AnalyzeFu(), and xload().
erase_info()
void library_manager::erase_info ()
Definition at line 519 of file library_manager.cpp.
References info.
Referenced by add(), remove_fu(), and update().
get_dont_use_cells()
CustomOrderedSet< std::string > library_manager::get_dont_use_cells () const
Return the cells not to be used for the synthesis.
Definition at line 601 of file library_manager.cpp.
References dont_use.
get_dont_use_num()
size_t library_manager::get_dont_use_num () const
Definition at line 606 of file library_manager.cpp.
References dont_use.
get_fu()
technology_nodeRef library_manager::get_fu (const std::string & name) const
Definition at line 503 of file library_manager.cpp.
References fu_map, is_fu(), and THROW_ASSERT.
Referenced by allocation::BuildProxyWrapper(), fun_dominator_allocation::Exec(), RTLCharacterization::Exec(), allocation::extract_bambu_provided(), RTLCharacterization::fix_execution_time_std(), RTLCharacterization::fix_proxies_execution_time_std(), allocation::IntegrateTechnologyLibraries(), allocation::InternalExec(), and moduleGenerator::specialize_fu().
get_gate_count()
size_t library_manager::get_gate_count () const
Definition at line 509 of file library_manager.cpp.
References fu_map.
get_info()
std::string library_manager::get_info (const info_t type, const TargetDevice_Type dv_type)
Definition at line 524 of file library_manager.cpp.
References get_library_name(), info, is_info(), name, NOT_YET_IMPLEMENTED, OUTPUT_LEVEL_MINIMUM, Param, PRINT_OUT_MEX, set_info(), THROW_ASSERT, THROW_ERROR, write_xml_technology_File(), and XML.
get_library_fu()
const fu_map_type& library_manager::get_library_fu () const [inline]
Return the list of the resources contained into the given library.
Returns
a datastructure that maps the name of the cells contained into the library with the related technology_node's
Definition at line 250 of file library_manager.hpp.
Referenced by GenerateFuList::Exec(), FixCharacterization::Exec(), allocation::InternalExec(), technology_manager::print(), technology_manager::xload(), technology_manager::xwrite(), and RTLCharacterization::xwrite_characterization().
get_library_name()
std::string library_manager::get_library_name () const
Definition at line 389 of file library_manager.cpp.
References name.
Referenced by RTLCharacterization::AnalyzeCell(), allocation::check_proxies(), allocation::check_templated_units(), RTLCharacterization::fix_execution_time_std(), RTLCharacterization::fix_proxies_execution_time_std(), get_info(), technology_manager::xload(), and RTLCharacterization::xwrite_characterization().
is_fu()
bool library_manager::is_fu (const std::string & name) const
Definition at line 498 of file library_manager.cpp.
References fu_map.
Referenced by allocation::BuildProxyWrapper(), allocation::extract_bambu_provided(), get_fu(), and xload().
is_info()
bool library_manager::is_info (unsigned int type) const
Definition at line 572 of file library_manager.cpp.
References info.
Referenced by get_info().
is_virtual()
bool library_manager::is_virtual () const
Check if the library is virtual or not.
Returns
true if the library is virtual, false otherwise (i.e., it is a standard library or, however, a library already characterized)
Definition at line 577 of file library_manager.cpp.
References is_std.
remove_dont_use()
void library_manager::remove_dont_use (const std::string & name)
Set a cell to be used.
Definition at line 611 of file library_manager.cpp.
References dont_use.
remove_fu()
void library_manager::remove_fu (const std::string & name)
Definition at line 582 of file library_manager.cpp.
References erase_info(), and fu_map.
Referenced by add_library::InternalExec().
set_default_attributes()
void library_manager::set_default_attributes () [private]
Set the default attributes for the library.
Definition at line 200 of file library_manager.cpp.
References attribute::attribute(), attributes, attribute::content, attribute::INT32, ordered_attributes, and attribute::STRING.
Referenced by library_manager().
set_dont_use()
void library_manager::set_dont_use (const std::string & name)
Set a cell to be not used.
Definition at line 592 of file library_manager.cpp.
References dont_use, and fu_map.
set_info()
void library_manager::set_info (unsigned int type, const std::string & information)
Definition at line 514 of file library_manager.cpp.
References info, and test_panda::type.
Referenced by WriteTechnology::Exec(), get_info(), read_technology_library(), write_xml_technology_File(), technology_manager::xload(), and technology_manager::xwrite().
update()
void library_manager::update (const technology_nodeRef & node)
adding a cells invalidates the library view currently stored
Definition at line 402 of file library_manager.cpp.
References attributes, operation::bounded, erase_info(), fu_map, technology_node::get_name(), operation::operation_name, ordered_attributes, operation::pipe_parameters, operation::portsize_parameters, STR, THROW_ASSERT, and operation::time_m.
xload()
void library_manager::xload (const xml_element * node, const library_managerRef & LM, const ParameterConstRef & Param, const target_deviceRef & device) [static]
Check if a more recently characterized version of the same cell already exists in the library
Definition at line 244 of file library_manager.cpp.
References add(), attributes, functional_unit::COMBINATIONAL, DEBUG_LEVEL_VERBOSE, fu_map, xml_child::get_children(), xml_text_node::get_content(), technology_node::get_name(), info, is_fu(), name, ordered_attributes, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_VERBOSE, PRINT_OUT_MEX, THROW_ASSERT, THROW_WARNING, attribute::xload(), and technology_node::xload().
Referenced by technology_manager::xload().
xwrite()
void library_manager::xwrite (xml_element * rootnode, TargetDevice_Type dv_type)
Definition at line 352 of file library_manager.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), attributes, fu_map, info, name, ordered_attributes, Param, and attribute_sequence::set_attribute().
Referenced by write_xml_technology_File(), and technology_manager::xwrite().
Field Documentation
attributes
std::map<std::string, attributeRef> library_manager::attributes [private]
attributes of the library
Definition at line 168 of file library_manager.hpp.
Referenced by set_default_attributes(), update(), xload(), and xwrite().
dont_use
CustomOrderedSet<std::string> library_manager::dont_use [private]
Definition at line 181 of file library_manager.hpp.
Referenced by get_dont_use_cells(), get_dont_use_num(), remove_dont_use(), and set_dont_use().
fu_map
fu_map_type library_manager::fu_map [private]
datastructure to identify the units that are contained into the library
Definition at line 163 of file library_manager.hpp.
Referenced by add(), get_fu(), get_gate_count(), is_fu(), remove_fu(), set_dont_use(), update(), xload(), and xwrite().
info
std::map<unsigned int, std::string> library_manager::info [private]
files that provide information about the library
Definition at line 171 of file library_manager.hpp.
Referenced by erase_info(), get_info(), is_info(), set_info(), xload(), and xwrite().
is_std
bool library_manager::is_std [private]
flag to check if the library is standard (i.e., provided in input) or virtual
Definition at line 174 of file library_manager.hpp.
Referenced by is_virtual().
name
std::string library_manager::name [private]
string identifier of the library
Definition at line 160 of file library_manager.hpp.
Referenced by get_info(), get_library_name(), xload(), and xwrite().
ordered_attributes
std::vector<std::string> library_manager::ordered_attributes [private]
Definition at line 165 of file library_manager.hpp.
Referenced by set_default_attributes(), update(), xload(), and xwrite().
Param
const ParameterConstRef library_manager::Param [private]
class containing all the parameters
Definition at line 157 of file library_manager.hpp.
Referenced by get_info(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/library_manager.hpp
/home/osboxes/bambu/PandA-bambu/src/technology/physical_library/library_manager.cpp