xml_text_node Class Reference
#include <xml_text_node.hpp>
Public Member Functions
xml_text_node (const std::string &content)
void print (std::ostream &os, bool formatted, simple_indent *) const override
Print the class.
std::string get_content () const
Get the text of this content node.
void set_content (const std::string &content)
Set the text of this content node.
Additional Inherited Members
Detailed Description
Definition at line 52 of file xml_text_node.hpp.
Constructor & Destructor Documentation
xml_text_node()
xml_text_node::xml_text_node (const std::string & content) [inline], [explicit]
Definition at line 55 of file xml_text_node.hpp.
Member Function Documentation
get_content()
std::string xml_text_node::get_content () const [inline]
Get the text of this content node.
Returns
The text. Note that the 5 predefined entities (&, ", <, &qt, ') are always resolved, so this content will show their human-readable equivalents.
Definition at line 91 of file xml_text_node.hpp.
References xml_node::get_name().
Referenced by BackendFlow::create_xml_scripts(), attribute::xload(), library_manager::xload(), structural_object::xload(), functional_unit::xload(), functional_unit_template::xload(), module::xload(), and XilinxBackendFlow::xparse_timing().
print()
void xml_text_node::print (std::ostream & os, bool formatted, simple_indent *) const [inline], [override], [virtual]
Print the class.
Parameters
os is the stream.
formatted when true the xml is formatted in human readable way.
pp is the pretty print helper.
Implements xml_node.
Definition at line 65 of file xml_text_node.hpp.
References xml_node::convert_unescaped(), xml_node::get_name(), and index.
set_content()
void xml_text_node::set_content (const std::string & content) [inline]
Set the text of this content node.
Parameters
content The text. This must be unescaped, meaning that the predefined entities will be created for you where necessary. See get_content().
Definition at line 100 of file xml_text_node.hpp.
References xml_node::set_name().
The documentation for this class was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/polixml/xml_text_node.hpp