/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Introduction/third/src/keccak_coproc.c File Reference
#include `Keccak.h`
Functions
void keccak_coproc (UINT64 *A)
Function Documentation
keccak_coproc()
void keccak_coproc (UINT64 * A)
Definition at line 3 of file keccak_coproc.c.
References chi(), iota(), nrRounds, pi(), rho(), and theta().