/home/osboxes/bambu/PandA-bambu/src/tree-panda-gcc.cpp File Reference
panda working as cross compiler targeting tree nodes...
#include `config_RELEASE.hpp`
#include `Parameter.hpp`
#include `tree-panda-gcc-Parameter.hpp`
#include <csignal>
#include <cstdlib>
#include <fstream>
#include <getopt.h>
#include <iosfwd>
#include <string>
#include <boost/filesystem.hpp>
#include <boost/filesystem/convenience.hpp>
#include `parse_tree.hpp`
#include `tree_manager.hpp`
#include `cpu_time.hpp`
#include `exceptions.hpp`
#include `fileIO.hpp`
#include `utility.hpp`
#include <boost/lexical_cast.hpp>
#include `gcc_wrapper.hpp`
Functions
static char * alloc_long_option (char *argv[], int &i, int &dec)
Autoheader include.
static char ** alloc_argv (int &argc, char *argv[])
static void dealloc_argv (int argc, char *argv_copied[])
static void close_everything (int argc, char *argv[], const ParameterRef &Param)
int main (int argc, char *argv_orig[])
Main file used to perform Hardware/Software Codesign starting from C/C++/SystemC specification.
Detailed Description
panda working as cross compiler targeting tree nodes...
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$ Last modified by $Author$
Function Documentation
alloc_argv()
static char** alloc_argv (int & argc, char * argv[]) [static]
Definition at line 90 of file tree-panda-gcc.cpp.
References alloc_long_option().
Referenced by main().
alloc_long_option()
static char* alloc_long_option (char * argv[], int & i, int & dec) [static]
Autoheader include.
Frontend includes STD Include Tree includes Utility includes Wrapper include
Definition at line 76 of file tree-panda-gcc.cpp.
Referenced by alloc_argv().
close_everything()
static void close_everything (int argc, char * argv[], const ParameterRef & Param) [static]
Definition at line 130 of file tree-panda-gcc.cpp.
References dealloc_argv().
Referenced by main().
dealloc_argv()
static void dealloc_argv (int argc, char * argv_copied[]) [static]
Definition at line 121 of file tree-panda-gcc.cpp.
Referenced by close_everything().
main()
int main (int argc, char * argv_orig[])
Main file used to perform Hardware/Software Codesign starting from C/C++/SystemC specification.
Parameters
argc an integer value
argv an array of char pointer
Returns
The main ending status
GCC wrapper to create the raw
creating the tree manager from the data structure
Definition at line 144 of file tree-panda-gcc.cpp.
References alloc_argv(), close_everything(), test_panda::command, DEBUG_LEVEL_MINIMUM, DEBUG_LEVEL_NONE, DEBUG_LEVEL_VERBOSE, DEBUG_LEVEL_VERY_PEDANTIC, dump_exec_time(), exit_code, fileIO_ostream_open(), IsError(), tree_manager::merge_tree_managers(), OUTPUT_LEVEL_MINIMUM, PandaSystem(), PARAMETER_NOTPARSED, PARAMETER_PARSED, ParseTreeFile(), PRINT_DBG_MEX, START_TIME, STOP_TIME, and THROW_ERROR.