OpGraphsCollection Class Reference
This structure defines graphs where nodes are operations.
#include <op_graph.hpp>
Public Member Functions
OpGraphsCollection (const OpGraphInfoRef info, const ParameterConstRef parameters)
Empty Constructror.
~OpGraphsCollection () override
Destructor.
EdgeDescriptor AddEdge (const vertex source, const vertex target, const int selector)
Add an edge with empty information associated.
boost::graph_traits< boost_graphs_collection >::vertex_descriptor AddVertex (const NodeInfoRef info) override
Add a vertex to this graph with a property.
void RemoveVertex (boost::graph_traits< boost_graphs_collection >::vertex_descriptor v) override
Remove a vertex from this graph.
const OpVertexSet CGetOperations () const
Return the vertices belonging to the graph.
void Clear ()
Remove all the edges and vertices from the graph.
Protected Attributes
OpVertexSet operations
The set of operations.
Additional Inherited Members
Detailed Description
This structure defines graphs where nodes are operations.
Definition at line 724 of file op_graph.hpp.
Constructor & Destructor Documentation
OpGraphsCollection()
OpGraphsCollection::OpGraphsCollection (const OpGraphInfoRef info, const ParameterConstRef parameters)
Empty Constructror.
Parameters
info is the info associated with the graph
parameters is the set of input parameters
Definition at line 220 of file op_graph.cpp.
References ~OpGraphsCollection().
 OpGraphsCollection()
OpGraphsCollection::~OpGraphsCollection () [override], [default]
Destructor.
Referenced by OpGraphsCollection().
Member Function Documentation
AddEdge()
EdgeDescriptor OpGraphsCollection::AddEdge (const vertex source, const vertex target, const int selector) [inline]
Add an edge with empty information associated.
Parameters
source is the source of the edge
target is the target of the edge
selector is the selector to be added
Returns
the created edge
Definition at line 750 of file op_graph.hpp.
AddVertex()
boost::graph_traits< boost_graphs_collection >::vertex_descriptor OpGraphsCollection::AddVertex (const NodeInfoRef info) [override], [virtual]
Add a vertex to this graph with a property.
Parameters
info is the property to be associated with the new vertex
Returns
the added vertex
Reimplemented from graphs_collection.
Definition at line 238 of file op_graph.cpp.
References graphs_collection::AddVertex(), and operations.
CGetOperations()
const OpVertexSet OpGraphsCollection::CGetOperations () const
Return the vertices belonging to the graph.
Definition at line 227 of file op_graph.cpp.
References operations.
Clear()
void OpGraphsCollection::Clear ()
Remove all the edges and vertices from the graph.
Definition at line 245 of file op_graph.cpp.
References OpEdgeSet::OpEdgeSet(), operations, and OpVertexSet::OpVertexSet().
RemoveVertex()
void OpGraphsCollection::RemoveVertex (boost::graph_traits< boost_graphs_collection >::vertex_descriptor v) [override], [virtual]
Remove a vertex from this graph.
Parameters
v is the vertex to be removed
Reimplemented from graphs_collection.
Definition at line 232 of file op_graph.cpp.
References operations, and graphs_collection::RemoveVertex().
Field Documentation
operations
OpVertexSet OpGraphsCollection::operations [protected]
The set of operations.
Definition at line 728 of file op_graph.hpp.
Referenced by AddVertex(), CGetOperations(), Clear(), and RemoveVertex().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.hpp
/home/osboxes/bambu/PandA-bambu/src/behavior/op_graph.cpp