HLSCWriter Class Reference
#include <hls_c_writer.hpp>
Public Member Functions
HLSCWriter (const HLSCBackendInformationConstRef hls_c_backend_information, const application_managerConstRef _AppM, const InstructionWriterRef instruction_writer, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef Param, bool verbose=true)
Constructor of the class.
virtual ~HLSCWriter ()
Destructor.
virtual void WriteFile (const std::string &file_name)
Writes the final C file.
virtual void WriteHeader ()
Writes the header of the file.
Protected Member Functions
bool is_all_8zeros (const std::string &str)
Check if a binary string is a sequence of zeros with length multiple of 8.
void WriteZeroedBytes (const size_t n_bytes)
Write printf statements to write n_bytes bytes initialized to 0 for the memory initialization of the HDL simulator.
size_t WriteBinaryMemoryInit (const std::string &binary_string, const size_t data_size, std::string &bits_offset)
Takes a binary string and writes in the C file a series of statements used to print the equivalent memory initialization data for the HDL simulator.
void WriteTestbenchGlobalVars ()
Write global variables needed by the tesbench.
void WriteTestbenchHelperFunctions ()
Write helper functions used by the testbench, like an __exit() helper and some binary conversion functions used to print memory initialization information.
void WriteParamDecl (const BehavioralHelperConstRef behavioral_helper)
Write declaration of the top function parameters.
void WriteParamInitialization (const BehavioralHelperConstRef behavioral_helper, const std::map< std::string, std::string > &curr_test_vector, const unsigned int vector_index)
Initialize the parameters of the function.
void WriteTestbenchFunctionCall (const BehavioralHelperConstRef behavioral_helper)
Writes a call to the top function to be tested, using its parameters.
void WriteExpectedResults (const BehavioralHelperConstRef behavioral_helper, const std::map< std::string, std::string > &curr_test_vector, const unsigned v_idx)
Write some print statements used to dump the results of each call to the tested function.
void WriteSimulatorInitMemory (const unsigned int function_id)
Write some print statements used to dump the values used by the HDL to initialize the memory before the simulation.
virtual void WriteExtraInitCode ()
Write additional initialization code needed by subclasses.
virtual void WriteExtraCodeBeforeEveryMainCall ()
void WriteMainTestbench ()
Writes the main() of the testbench C program.
virtual void WriteGlobalDeclarations ()
Writes the global declarations.
virtual void WriteFunctionImplementation (unsigned int function_index)
Write function implementation.
virtual void WriteBuiltinWaitCall ()
Writes implementation of __builtin_wait_call.
void WriteParamInMemory (const BehavioralHelperConstRef behavioral_helper, const std::string &param, const unsigned int type, const unsigned int nesting_level, bool input)
Write the print to fill values.txt with values for t parameters.
Protected Attributes
bool flag_cpp
True if the input code is c++.
const HLSCBackendInformationConstRef hls_c_backend_information
Backend information.
Additional Inherited Members
Detailed Description
Definition at line 51 of file hls_c_writer.hpp.
Constructor & Destructor Documentation
HLSCWriter()
HLSCWriter::HLSCWriter (const HLSCBackendInformationConstRef hls_c_backend_information, const application_managerConstRef _AppM, const InstructionWriterRef instruction_writer, const IndentedOutputStreamRef indented_output_stream, const ParameterConstRef Param, bool verbose = true)
Constructor of the class.
Parameters
hls_c_backend_information is the information about backend
AppM is the manager of the application
instruction_writer is the instruction writer to use to print the single instruction
indented_output_stream is the stream where code has to be printed
Param is the set of parameters
verbose tells if annotations
include from cpp
Definition at line 102 of file hls_c_writer.cpp.
References CWriter::debug_level, flag_cpp, GET_CLASS, CWriter::Param, CWriter::TM, and ~HLSCWriter().
 HLSCWriter()
HLSCWriter::~HLSCWriter () [virtual], [default]
Destructor.
Referenced by HLSCWriter().
Member Function Documentation
is_all_8zeros()
bool HLSCWriter::is_all_8zeros (const std::string & str) [protected]
Check if a binary string is a sequence of zeros with length multiple of 8.
Definition at line 1230 of file hls_c_writer.cpp.
Referenced by WriteBinaryMemoryInit().
WriteBinaryMemoryInit()
size_t HLSCWriter::WriteBinaryMemoryInit (const std::string & binary_string, const size_t data_size, std::string & bits_offset) [protected]
Takes a binary string and writes in the C file a series of statements used to print the equivalent memory initialization data for the HDL simulator.
Definition at line 1181 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::indented_output_stream, is_all_8zeros(), and WriteZeroedBytes().
Referenced by WriteSimulatorInitMemory().
WriteBuiltinWaitCall()
void HLSCWriter::WriteBuiltinWaitCall () [protected], [virtual]
Writes implementation of __builtin_wait_call.
Do nothing
Reimplemented from CWriter.
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 1246 of file hls_c_writer.cpp.
WriteExpectedResults()
void HLSCWriter::WriteExpectedResults (const BehavioralHelperConstRef behavioral_helper, const std::map< std::string, std::string > & curr_test_vector, const unsigned v_idx) [protected]
Write some print statements used to dump the results of each call to the tested function.
The output is in a format that is recognized by the HDL testbench generation FIXME: for c++ code the old code is still used
Retrieve the space to be reserved in memory
Definition at line 586 of file hls_c_writer.cpp.
References ac_type_bitwidth(), IndentedOutputStream::Append(), tree_helper::CGetPointedType(), CWriter::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, flag_cpp, tree_helper::get_array_data_bitsize(), tree_helper::get_array_num_elements(), BehavioralHelper::get_function_index(), GET_INDEX_NODE, tree_node::get_kind(), tree_helper::get_mangled_fname(), BehavioralHelper::get_parameters(), tree_helper::get_type_index(), BehavioralHelper::GetElements(), BehavioralHelper::GetFunctionReturnType(), hls_c_backend_information, INDENT_DBG_MEX, CWriter::indented_output_stream, INFERRED_INTERFACE_GENERATION, BehavioralHelper::is_a_pointer(), BehavioralHelper::is_a_struct(), BehavioralHelper::is_an_array(), BehavioralHelper::is_an_union(), BehavioralHelper::is_real(), CWriter::output_level, OUTPUT_LEVEL_MINIMUM, CWriter::Param, BehavioralHelper::print_type(), BehavioralHelper::PrintVariable(), RETURN_PORT_NAME, tree_helper::size(), tree_helper::Size(), SplitString(), STR, THROW_ASSERT, THROW_ERROR, CWriter::TM, and WriteParamInMemory().
Referenced by WriteMainTestbench().
WriteExtraCodeBeforeEveryMainCall()
void HLSCWriter::WriteExtraCodeBeforeEveryMainCall () [protected], [virtual]
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 1082 of file hls_c_writer.cpp.
Referenced by WriteMainTestbench().
WriteExtraInitCode()
void HLSCWriter::WriteExtraInitCode () [protected], [virtual]
Write additional initialization code needed by subclasses.
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 1078 of file hls_c_writer.cpp.
Referenced by WriteMainTestbench().
WriteFile()
void HLSCWriter::WriteFile (const std::string & file_name) [virtual]
Writes the final C file.
Parameters
file_name is the name of the file to be generated
Reimplemented from CWriter.
Definition at line 1158 of file hls_c_writer.cpp.
References CWriter::AppM, BehavioralHelper::get_function_name(), INDENT_OUT_MEX, CWriter::indented_output_stream, CWriter::output_level, OUTPUT_LEVEL_VERBOSE, THROW_ASSERT, IndentedOutputStream::WriteFile(), and WriteMainTestbench().
WriteFunctionImplementation()
void HLSCWriter::WriteFunctionImplementation (unsigned int function_index) [protected], [virtual]
Write function implementation.
Parameters
function_id is the index of the function to be written
Do nothing
Reimplemented from CWriter.
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 1241 of file hls_c_writer.cpp.
WriteGlobalDeclarations()
void HLSCWriter::WriteGlobalDeclarations () [protected], [virtual]
Writes the global declarations.
Reimplemented from CWriter.
Reimplemented in DiscrepancyAnalysisCWriter.
Definition at line 155 of file hls_c_writer.cpp.
References CWriter::instrWriter, WriteTestbenchGlobalVars(), and WriteTestbenchHelperFunctions().
WriteHeader()
void HLSCWriter::WriteHeader () [virtual]
Writes the header of the file.
Reimplemented from CWriter.
Definition at line 113 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, flag_cpp, tree_helper::get_mangled_fname(), hls_c_backend_information, CWriter::indented_output_stream, CWriter::Param, THROW_ASSERT, and CWriter::TM.
WriteMainTestbench()
void HLSCWriter::WriteMainTestbench () [protected]
Writes the main() of the testbench C program.
Definition at line 1086 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::AppM, CWriter::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, BehavioralHelper::get_function_name(), BehavioralHelper::GetFunctionReturnType(), hls_c_backend_information, INDENT_DBG_MEX, CWriter::indented_output_stream, tree_helper::is_a_vector(), BehavioralHelper::print_type(), RETURN_PORT_NAME, STR, THROW_ASSERT, THROW_ERROR, CWriter::TM, WriteExpectedResults(), WriteExtraCodeBeforeEveryMainCall(), WriteExtraInitCode(), WriteParamDecl(), WriteParamInitialization(), WriteSimulatorInitMemory(), and WriteTestbenchFunctionCall().
Referenced by WriteFile().
WriteParamDecl()
void HLSCWriter::WriteParamDecl (const BehavioralHelperConstRef behavioral_helper) [protected]
Write declaration of the top function parameters.
Declaration and initialization are separate statements.
Definition at line 295 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), flag_cpp, BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), tree_node::get_kind(), tree_helper::get_mangled_fname(), BehavioralHelper::get_parameters(), BehavioralHelper::get_type(), hls_c_backend_information, CWriter::indented_output_stream, BehavioralHelper::is_a_pointer(), tree_helper::is_a_vector(), BehavioralHelper::print_type(), tree_helper::print_type(), BehavioralHelper::PrintVariable(), THROW_ASSERT, THROW_ERROR, CWriter::TM, and test_panda::type.
Referenced by WriteMainTestbench().
WriteParamInitialization()
void HLSCWriter::WriteParamInitialization (const BehavioralHelperConstRef behavioral_helper, const std::map< std::string, std::string > & curr_test_vector, const unsigned int vector_index) [protected]
Initialize the parameters of the function.
Declaration and initialization are separate statements and the declaration code must be printed before the initialization code.
Parameters
behavioral_helper is the function to which the parameters are referred
curr_test_vector is the test vector used to initialize the parameters
vector_index is the index of the test_vector (this should not be needed here, since it's used to get memory information, it will be removed when tesbench memory allocation and c testbench creation will be executed as separate steps)
Definition at line 385 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), ConvertInBinary(), CWriter::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, flag_cpp, BehavioralHelper::get_function_index(), tree_helper::get_mangled_fname(), BehavioralHelper::get_parameters(), tree_helper::get_pointed_type(), BehavioralHelper::get_type(), tree_helper::get_type_index(), hls_c_backend_information, INDENT_DBG_MEX, CWriter::indented_output_stream, BehavioralHelper::is_a_pointer(), BehavioralHelper::is_real(), BehavioralHelper::is_unsigned(), BehavioralHelper::print_type(), tree_helper::print_type(), BehavioralHelper::PrintVariable(), tree_helper::size(), STR, THROW_ASSERT, THROW_ERROR, CWriter::TM, and test_panda::type.
Referenced by WriteMainTestbench().
WriteParamInMemory()
void HLSCWriter::WriteParamInMemory (const BehavioralHelperConstRef behavioral_helper, const std::string & param, const unsigned int type, const unsigned int nesting_level, bool input) [protected]
Write the print to fill values.txt with values for t parameters.
Parameters
behavioral_helper is the helper used to print field names
param is the string of the parameter currently printed
type is the type of the currently printed piece of parameter
nesting_level is the level of nesting of the currently printed field/element
input specifies if the input syntax must be used
FIXME: real numbers at the moment have to be considered differently because of computation of ulp
Definition at line 1251 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_UNARY_EXPRESSION, GET_CONST_NODE, tree_helper::get_integer_cst_value(), GET_NODE, tree_helper::get_type_index(), CWriter::indented_output_stream, NODE_NOT_YET_SUPPORTED_EC, BehavioralHelper::PrintVariable(), tree_helper::Size(), STR, THROW_ASSERT, THROW_ERROR, THROW_ERROR_CODE, CWriter::TM, and test_panda::type.
Referenced by WriteExpectedResults().
WriteSimulatorInitMemory()
void HLSCWriter::WriteSimulatorInitMemory (const unsigned int function_id) [protected]
Write some print statements used to dump the values used by the HDL to initialize the memory before the simulation.
(This function actually also reserves memory out of the top function to be tested, if needed. This should not be done here, but in a separate memory allocation step, and will be moved soon). Remove leading spaces
Remove trailing spaces
Remove first {
Remove last }
Retrieve the space to be reserved in memory
FIXME: for c++ code the old code is still used
Call the parser to translate C initialization to values.txt initialization
Definition at line 781 of file hls_c_writer.cpp.
References tree_helper::accessed_greatest_bitsize(), IndentedOutputStream::Append(), CWriter::AppM, tree_helper::CGetFieldTypes(), ConvertInBinary(), CWriter::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, flag_cpp, tree_helper::get_array_data_bitsize(), tree_helper::get_array_num_elements(), GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, BehavioralHelper::get_parameters(), tree_helper::get_type_index(), BehavioralHelper::GetElements(), hls_c_backend_information, INDENT_DBG_MEX, CWriter::indented_output_stream, index, BehavioralHelper::is_a_pointer(), tree_helper::is_a_pointer(), BehavioralHelper::is_a_struct(), BehavioralHelper::is_an_array(), BehavioralHelper::is_an_union(), BehavioralHelper::is_real(), BehavioralHelper::is_unsigned(), MEMORY_INITIALIZATION, CWriter::output_level, OUTPUT_LEVEL_MINIMUM, CWriter::Param, test_panda::parameters, TestbenchGenerationBaseStep::print_var_init(), BehavioralHelper::PrintVariable(), tree_helper::size(), tree_helper::Size(), SplitString(), STR, THROW_ASSERT, THROW_ERROR, CWriter::TM, test_panda::type, WriteBinaryMemoryInit(), and WriteZeroedBytes().
Referenced by WriteMainTestbench().
WriteTestbenchFunctionCall()
void HLSCWriter::WriteTestbenchFunctionCall (const BehavioralHelperConstRef behavioral_helper) [protected]
Writes a call to the top function to be tested, using its parameters.
The code for the declaration and initialization of such parameters must be written before a call to obtain meaningful outcome.
Parameters
behavioral_helper refers to the function to be tested
Definition at line 479 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), flag_cpp, BehavioralHelper::get_definition(), BehavioralHelper::get_function_index(), BehavioralHelper::get_function_name(), tree_node::get_kind(), GET_NODE, BehavioralHelper::get_parameters(), BehavioralHelper::get_type(), BehavioralHelper::GetFunctionReturnType(), CWriter::indented_output_stream, BehavioralHelper::is_a_pointer(), BehavioralHelper::is_real(), CWriter::Param, BehavioralHelper::print_type(), tree_helper::print_type(), BehavioralHelper::PrintVariable(), RETURN_PORT_NAME, CWriter::TM, and test_panda::type.
Referenced by WriteMainTestbench().
WriteTestbenchGlobalVars()
void HLSCWriter::WriteTestbenchGlobalVars () [protected]
Write global variables needed by the tesbench.
Definition at line 162 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), and CWriter::indented_output_stream.
Referenced by DiscrepancyAnalysisCWriter::WriteGlobalDeclarations(), and WriteGlobalDeclarations().
WriteTestbenchHelperFunctions()
void HLSCWriter::WriteTestbenchHelperFunctions () [protected]
Write helper functions used by the testbench, like an __exit() helper and some binary conversion functions used to print memory initialization information.
Definition at line 169 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::indented_output_stream, and CWriter::Param.
Referenced by DiscrepancyAnalysisCWriter::WriteGlobalDeclarations(), and WriteGlobalDeclarations().
WriteZeroedBytes()
void HLSCWriter::WriteZeroedBytes (const size_t n_bytes) [inline], [protected]
Write printf statements to write n_bytes bytes initialized to 0 for the memory initialization of the HDL simulator.
Parameters
in n_bytes the number of zeroed bytes to be printed
Definition at line 1172 of file hls_c_writer.cpp.
References IndentedOutputStream::Append(), CWriter::indented_output_stream, and STR.
Referenced by WriteBinaryMemoryInit(), and WriteSimulatorInitMemory().
Field Documentation
flag_cpp
bool HLSCWriter::flag_cpp [protected]
True if the input code is c++.
Definition at line 55 of file hls_c_writer.hpp.
Referenced by HLSCWriter(), WriteExpectedResults(), WriteHeader(), WriteParamDecl(), WriteParamInitialization(), WriteSimulatorInitMemory(), and WriteTestbenchFunctionCall().
hls_c_backend_information
const HLSCBackendInformationConstRef HLSCWriter::hls_c_backend_information [protected]
Backend information.
Definition at line 58 of file hls_c_writer.hpp.
Referenced by DiscrepancyAnalysisCWriter::DeclareLocalVariables(), WriteExpectedResults(), DiscrepancyAnalysisCWriter::WriteExtraInitCode(), WriteHeader(), WriteMainTestbench(), WriteParamDecl(), WriteParamInitialization(), DiscrepancyAnalysisCWriter::writePostInstructionInfo(), and WriteSimulatorInitMemory().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/hls_c_writer.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/backend/ToC/source_code_writers/hls_c_writer.cpp