simple_indent Class Reference
Very simple pretty printer functor.
#include <simple_indent.hpp>
Public Member Functions
void operator() (std::ostream &os, const std::string &str)
pretty print functor
simple_indent (char o, char c, unsigned int d)
constructor
~simple_indent ()
destructor
void indent ()
Manually increase the indenting of the code.
void deindent ()
Manually reduce the indenting of the code.
Private Member Functions
void write_indent (std::ostream &os)
Write the indent spaces.
void write_char (std::ostream &os, const char &c)
Write the current char.
Private Attributes
unsigned int indent_spaces
number of spaces used to indent after a new line print
char opening_char
char that increments the indent space by a delta
char closing_char
char that increments the indent space by a delta
unsigned int delta
delta indent space
bool is_line_start
Detailed Description
Very simple pretty printer functor.
Definition at line 58 of file simple_indent.hpp.
Constructor & Destructor Documentation
simple_indent()
simple_indent::simple_indent (char o, char c, unsigned int d)
constructor
Utility include.
Parameters
o is the opening character used by simple_indent.
c is the closing character used by simple_indent.
d is the number of characters used to indent the code.
Header include
Definition at line 54 of file simple_indent.cpp.
 simple_indent()
simple_indent::~simple_indent ()
destructor
This corresponds to a THROW_ASSERT, however it is against C++ rules throw an error inside a destructor
Definition at line 58 of file simple_indent.cpp.
References indent_spaces, and indentation.
Member Function Documentation
deindent()
void simple_indent::deindent ()
Manually reduce the indenting of the code.
Definition at line 144 of file simple_indent.cpp.
References delta, indent_spaces, and THROW_ASSERT.
Referenced by operator()(), and flopoco_wrapper::outputWrapVHDL().
indent()
void simple_indent::indent ()
Manually increase the indenting of the code.
Definition at line 139 of file simple_indent.cpp.
References delta, and indent_spaces.
Referenced by operator()(), and flopoco_wrapper::outputWrapVHDL().
operator()()
void simple_indent::operator() (std::ostream & os, const std::string & str)
pretty print functor
Parameters
is the output stream
is the string to be printed
Specified whether the first character of the string we are going to write must be indented or not
Definition at line 69 of file simple_indent.cpp.
References closing_char, deindent(), indent(), is_line_start, opening_char, STD_CLOSING_CHAR, STD_OPENING_CHAR, write_char(), and write_indent().
write_char()
void simple_indent::write_char (std::ostream & os, const char & c) [private]
Write the current char.
Definition at line 158 of file simple_indent.cpp.
Referenced by operator()().
write_indent()
void simple_indent::write_indent (std::ostream & os) [private]
Write the indent spaces.
Definition at line 150 of file simple_indent.cpp.
References indent_spaces.
Referenced by operator()().
Field Documentation
closing_char
char simple_indent::closing_char [private]
char that increments the indent space by a delta
Definition at line 68 of file simple_indent.hpp.
Referenced by operator()().
delta
unsigned int simple_indent::delta [private]
delta indent space
Definition at line 71 of file simple_indent.hpp.
Referenced by deindent(), and indent().
indent_spaces
unsigned int simple_indent::indent_spaces [private]
number of spaces used to indent after a new line print
Definition at line 62 of file simple_indent.hpp.
Referenced by deindent(), indent(), write_indent(), and ~simple_indent().
is_line_start
bool simple_indent::is_line_start [private]
Definition at line 73 of file simple_indent.hpp.
Referenced by operator()().
opening_char
char simple_indent::opening_char [private]
char that increments the indent space by a delta
Definition at line 65 of file simple_indent.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/utility/simple_indent.hpp
/home/osboxes/bambu/PandA-bambu/src/utility/simple_indent.cpp