compatibility_based_register Class Reference
#include <compatibility_based_register.hpp>
Data Structures
struct edge_compatibility_property
edge property
Public Member Functions
compatibility_based_register (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization=HLSFlowStepSpecializationConstRef())
Constructor.
~compatibility_based_register () override
Destructor.
void create_compatibility_graph ()
Creates the compatibility graph.
bool is_compatible (unsigned int sv1, unsigned int sv2) const
Checks if two storage values are compatible.
Protected Types
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::no_property, edge_compatibility_property > compatibility_graph
typedef boost::graph_traits< compatibility_graph >::vertex_descriptor CG_vertex_descriptor
typedef boost::graph_traits< compatibility_graph >::vertices_size_type CG_vertices_size_type
Protected Attributes
compatibility_graph CG
compatibility graph
std::vector< CG_vertex_descriptor > verts
ordered vector containing the vertices of the compatibility graph
Additional Inherited Members
Detailed Description
Definition at line 51 of file compatibility_based_register.hpp.
Member Typedef Documentation
CG_vertex_descriptor
typedef boost::graph_traits<compatibility_graph>::vertex_descriptor compatibility_based_register::CG_vertex_descriptor [protected]
Definition at line 70 of file compatibility_based_register.hpp.
CG_vertices_size_type
typedef boost::graph_traits<compatibility_graph>::vertices_size_type compatibility_based_register::CG_vertices_size_type [protected]
Definition at line 71 of file compatibility_based_register.hpp.
compatibility_graph
typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, boost::no_property, edge_compatibility_property> compatibility_based_register::compatibility_graph [protected]
Definition at line 69 of file compatibility_based_register.hpp.
Constructor & Destructor Documentation
compatibility_based_register()
compatibility_based_register::compatibility_based_register (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization = HLSFlowStepSpecializationConstRef())
Constructor.
HLS/binding/storage_value_insertion includes.
Parameters
design_flow_manager is the design flow manager
Definition at line 61 of file compatibility_based_register.cpp.
References ~compatibility_based_register().
 compatibility_based_register()
compatibility_based_register::~compatibility_based_register () [override], [default]
Destructor.
Referenced by compatibility_based_register().
Member Function Documentation
create_compatibility_graph()
void compatibility_based_register::create_compatibility_graph ()
Creates the compatibility graph.
compatibility graph creation
we consider only valuable sharing between registers
Definition at line 69 of file compatibility_based_register.cpp.
References StorageValueInformation::are_value_bitsize_compatible(), CG, StorageValueInformation::get_compatibility_weight(), liveness::get_live_in(), StorageValueInformation::get_number_of_storage_values(), StorageValueInformation::get_storage_value_index(), liveness::get_support(), HLSFunctionStep::HLS, max(), reg_binding_creator::register_lower_bound, hls::Rliv, hls::storage_value_information, THROW_ASSERT, and verts.
Referenced by weighted_clique_register::InternalExec().
is_compatible()
bool compatibility_based_register::is_compatible (unsigned int sv1, unsigned int sv2) const
Checks if two storage values are compatible.
Definition at line 125 of file compatibility_based_register.cpp.
References CG, and verts.
Field Documentation
CG
compatibility_graph compatibility_based_register::CG [protected]
compatibility graph
Definition at line 74 of file compatibility_based_register.hpp.
Referenced by create_compatibility_graph(), weighted_clique_register::InternalExec(), and is_compatible().
verts
std::vector<CG_vertex_descriptor> compatibility_based_register::verts [protected]
ordered vector containing the vertices of the compatibility graph
Definition at line 77 of file compatibility_based_register.hpp.
Referenced by create_compatibility_graph(), weighted_clique_register::InternalExec(), and is_compatible().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/compatibility_based_register.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/register/algorithms/compatibility_based_register.cpp