/home/osboxes/bambu/PandA-bambu/documentation/tutorial_pact_2019/Introduction/sixth/test.c File Reference
#include `aggregate.h`
Typedefs
typedef unsigned int size_t
typedef int(* __compar_d_fn_t) (void *, void *, void *)
Functions
void _quicksort (void *const pbase, size_t total_elems, size_t size, int(*cmp)(const void *, const void *, void *), void *arg)
int less (void *a, void *b, void *notUsed)
void test (float *const pbase, size_t total_elems)
Typedef Documentation
__compar_d_fn_t
typedef int(* __compar_d_fn_t) (void *, void *, void *)
Definition at line 3 of file test.c.
size_t
typedef unsigned int size_t
Definition at line 1 of file test.c.
Function Documentation
_quicksort()
void _quicksort (void *const pbase, size_t total_elems, size_t size, int(*)(const void *, const void *, void *) cmp, void * arg)
Definition at line 87 of file qsort.c.
References MAX_THRESH, min, POP, PUSH, STACK_NOT_EMPTY, STACK_SIZE, SWAP, and top().
less()
int less (void * a, void * b, void * notUsed)
test()
void test (float *const pbase, size_t total_elems)
Definition at line 14 of file test.c.
References _quicksort(), and less().