AggregateDataFlowAnalysis Class Reference
Superclass include.
#include <aggregate_data_flow_analysis.hpp>
Public Member Functions
AggregateDataFlowAnalysis (const application_managerRef AppM, const unsigned int function_index, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~AggregateDataFlowAnalysis () override
Destructor.
DesignFlowStep_Status InternalExec () override
Cleans the fake data dependencies.
void ComputeRelationships (DesignFlowStepSet &relationship, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Superclass include.
Definition at line 51 of file aggregate_data_flow_analysis.hpp.
Constructor & Destructor Documentation
AggregateDataFlowAnalysis()
AggregateDataFlowAnalysis::AggregateDataFlowAnalysis (const application_managerRef _AppM, const unsigned int _function_index, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
AppM is the application manager
function_index is the index of the function
design_flow_manager is the design flow manager
parameters is the set of the parameters
Autoheader include design_flows include frontend_flow includes
Definition at line 71 of file aggregate_data_flow_analysis.cpp.
References DesignFlowStep::composed, DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~AggregateDataFlowAnalysis().
 AggregateDataFlowAnalysis()
AggregateDataFlowAnalysis::~AggregateDataFlowAnalysis () [override], [default]
Destructor.
Referenced by AggregateDataFlowAnalysis().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > AggregateDataFlowAnalysis::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 85 of file aggregate_data_flow_analysis.cpp.
References FrontendFlowStep::AppM, TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, EMPTY, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), MEMORY_DATA_FLOW_ANALYSIS, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and VIRTUAL_AGGREGATE_DATA_FLOW_ANALYSIS.
ComputeRelationships()
void AggregateDataFlowAnalysis::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Implements DesignFlowStep.
Definition at line 132 of file aggregate_data_flow_analysis.cpp.
References FunctionFrontendFlowStep::ComputeRelationships(), TechnologyFlowStep::ComputeSignature(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::design_flow_manager, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStep::PRECEDENCE_RELATIONSHIP, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status AggregateDataFlowAnalysis::InternalExec () [override], [virtual]
Cleans the fake data dependencies.
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 80 of file aggregate_data_flow_analysis.cpp.
References EMPTY.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/aggregate_data_flow_analysis.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/aggregate_data_flow_analysis.cpp