TechnologyFlowStepFactory Class Reference
#include <technology_flow_step_factory.hpp>
Public Member Functions
TechnologyFlowStepFactory (const technology_managerRef TM, const target_deviceRef target, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~TechnologyFlowStepFactory () override
Destructor.
const std::string GetPrefix () const override
Return the prefix of the steps created by the factory.
DesignFlowStepRef CreateTechnologyFlowStep (const TechnologyFlowStep_Type hls_flow_step_type) const
Create a scheduling design flow step.
Protected Attributes
const technology_managerRef TM
The technology manager.
const target_deviceRef target
The target device.
Detailed Description
Definition at line 56 of file technology_flow_step_factory.hpp.
Constructor & Destructor Documentation
TechnologyFlowStepFactory()
TechnologyFlowStepFactory::TechnologyFlowStepFactory (const technology_managerRef _TM, const target_deviceRef _target, const DesignFlowManagerConstRef _design_flow_manager, const ParameterConstRef _parameters)
Constructor.
Header include.
Parameters
TM is the technology manager
target is the target device
design_flow_manager is the design flow manager
parameters is the set of input parameters
technology includes
Definition at line 53 of file technology_flow_step_factory.cpp.
References ~TechnologyFlowStepFactory().
 TechnologyFlowStepFactory()
TechnologyFlowStepFactory::~TechnologyFlowStepFactory () [override], [default]
Destructor.
Referenced by TechnologyFlowStepFactory().
Member Function Documentation
CreateTechnologyFlowStep()
DesignFlowStepRef TechnologyFlowStepFactory::CreateTechnologyFlowStep (const TechnologyFlowStep_Type hls_flow_step_type) const
Create a scheduling design flow step.
Parameters
technology_design_flow_step_type is the type of step to be created
Definition at line 65 of file technology_flow_step_factory.cpp.
References DesignFlowStepFactory::design_flow_manager, FIX_CHARACTERIZATION, LOAD_DEFAULT_TECHNOLOGY, LOAD_DEVICE_TECHNOLOGY, LOAD_FILE_TECHNOLOGY, LOAD_TECHNOLOGY, Wrefcount< T >::lock(), DesignFlowStepFactory::parameters, target, THROW_UNREACHABLE, TM, and WRITE_TECHNOLOGY.
GetPrefix()
const std::string TechnologyFlowStepFactory::GetPrefix () const [override], [virtual]
Return the prefix of the steps created by the factory.
Implements DesignFlowStepFactory.
Definition at line 60 of file technology_flow_step_factory.cpp.
Field Documentation
target
const target_deviceRef TechnologyFlowStepFactory::target [protected]
The target device.
Definition at line 63 of file technology_flow_step_factory.hpp.
Referenced by CreateTechnologyFlowStep().
TM
const technology_managerRef TechnologyFlowStepFactory::TM [protected]
The technology manager.
Definition at line 60 of file technology_flow_step_factory.hpp.
Referenced by CreateTechnologyFlowStep().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/technology_flow_step_factory.hpp
/home/osboxes/bambu/PandA-bambu/src/design_flows/technology/technology_flow_step_factory.cpp