StorageValueInformation Class Reference
#include <storage_value_information.hpp>
Public Member Functions
StorageValueInformation (const HLS_managerConstRef HLS_mgr, const unsigned int function_id)
Constructor.
~StorageValueInformation ()
Destructor.
void Initialize ()
Initialize the step (i.e., like a constructor)
unsigned int get_number_of_storage_values () const
Returns the number of storage values inserted.
bool is_a_storage_value (vertex curr_vertex, unsigned int var_index) const
return true in case a storage value exist for the pair vertex variable
unsigned int get_storage_value_index (vertex curr_vertex, unsigned int var_index) const
Returns the index of the storage value associated with the variable in a given vertex.
unsigned int get_variable_index (unsigned int storage_value_index) const
Returns the index of the variable associated with the storage value in a given vertex.
int get_compatibility_weight (unsigned int storage_value_index1, unsigned int storage_value_index2) const
return a weight that estimate how much two storage values are compatible.
bool are_value_bitsize_compatible (unsigned int storage_value_index1, unsigned int storage_value_index2) const
return the in case the storage values have compatible size
Protected Attributes
unsigned int number_of_storage_values
current number of storage values
CustomUnorderedMapUnstable< unsigned int, unsigned int > storage_index_map
put into relation variables/values with storage values
std::vector< unsigned int > variable_index_vect
put into relation storage value index with variables
CustomUnorderedMap< unsigned int, vertex > vw2vertex
relation between var written and operations
const HLS_managerConstRef HLS_mgr
The HLS manager.
const unsigned int function_id
The index of the function.
OpGraphConstRef data
operation graph used to compute the affinity between storage values
Wrefcount< const fu_binding > fu
functional unit assignments
Friends
class values_scheme
Detailed Description
Definition at line 56 of file storage_value_information.hpp.
Constructor & Destructor Documentation
StorageValueInformation()
StorageValueInformation::StorageValueInformation (const HLS_managerConstRef _HLS_mgr, const unsigned int _function_id)
Constructor.
Header include.
Autoheader include behavior include HLS include HLS/binding/module_binding includes tree includes
Definition at line 63 of file storage_value_information.cpp.
References ~StorageValueInformation().
 StorageValueInformation()
StorageValueInformation::~StorageValueInformation () [default]
Destructor.
Referenced by StorageValueInformation().
Member Function Documentation
are_value_bitsize_compatible()
bool StorageValueInformation::are_value_bitsize_compatible (unsigned int storage_value_index1, unsigned int storage_value_index2) const
return the in case the storage values have compatible size
Parameters
storage_value_index1 is the first storage value
storage_value_index2 is the second storage value
Definition at line 317 of file storage_value_information.cpp.
References get_variable_index(), HLS_mgr, tree_helper::is_int(), resize_to_1_8_16_32_64_128_256_512(), and tree_helper::size().
Referenced by compatibility_based_register::create_compatibility_graph(), and conflict_based_register::create_conflict_graph().
get_compatibility_weight()
int StorageValueInformation::get_compatibility_weight (unsigned int storage_value_index1, unsigned int storage_value_index2) const
return a weight that estimate how much two storage values are compatible.
An high value returned means an high compatibility between the two storage values.
Definition at line 138 of file storage_value_information.cpp.
References OpGraph::CGetOpNodeInfo(), data, DEBUG_LEVEL_VERY_PEDANTIC, fu, GET_NAME, GET_TYPE, get_variable_index(), HLS_mgr, INDENT_DBG_MEX, INFINITE_UINT, Wrefcount< T >::lock(), SCALAR, STR, THROW_ASSERT, THROW_ERROR, TYPE_ENTRY, TYPE_PHI, USE, and vw2vertex.
Referenced by compatibility_based_register::create_compatibility_graph().
get_number_of_storage_values()
unsigned int StorageValueInformation::get_number_of_storage_values () const
Returns the number of storage values inserted.
Definition at line 116 of file storage_value_information.cpp.
References number_of_storage_values.
Referenced by compatibility_based_register::create_compatibility_graph(), conflict_based_register::create_conflict_graph(), unique_binding_register::InternalExec(), and chordal_coloring_register::InternalExec().
get_storage_value_index()
unsigned int StorageValueInformation::get_storage_value_index (vertex curr_vertex, unsigned int var_index) const
Returns the index of the storage value associated with the variable in a given vertex.
Parameters
curr_vertex is the vertex
var_index is the variable
Definition at line 126 of file storage_value_information.cpp.
References storage_index_map, and THROW_ASSERT.
Referenced by mux_connection_binding::connect_to_registers(), compatibility_based_register::create_compatibility_graph(), conflict_based_register::create_conflict_graph(), mux_connection_binding::create_connections(), fsm_controller::create_state_machine(), vertex_coloring_register::InternalExec(), unique_binding_register::InternalExec(), chordal_coloring_register::InternalExec(), weighted_clique_register::InternalExec(), port_swapping::InternalExec(), VcdSignalSelection::SelectInternalSignals(), and mux_connection_binding::swap_p().
get_variable_index()
unsigned int StorageValueInformation::get_variable_index (unsigned int storage_value_index) const
Returns the index of the variable associated with the storage value in a given vertex.
Definition at line 132 of file storage_value_information.cpp.
References THROW_ASSERT, and variable_index_vect.
Referenced by are_value_bitsize_compatible(), get_compatibility_weight(), reg_binding::get_vars(), and reg_binding::print_el().
Initialize()
void StorageValueInformation::Initialize ()
Initialize the step (i.e., like a constructor)
initialize the vw2vertex relation
Definition at line 69 of file storage_value_information.cpp.
References FunctionBehavior::CGetOpGraph(), OpGraph::CGetOpNodeInfo(), tree_manager::CGetTreeNode(), counter, data, DEBUG_LEVEL_NONE, DEFINITION, FunctionBehavior::DFG, fu, function_id, GET_NAME, GET_TYPE, HLS_mgr, INDENT_DBG_MEX, tree_helper::is_parameter(), tree_helper::is_ssa_name(), tree_helper::is_virtual(), hls::Rfu, SCALAR, hls::storage_value_information, STR, THROW_UNREACHABLE, TYPE_ENTRY, and vw2vertex.
Referenced by storage_value_insertion::Initialize(), and values_scheme::Initialize().
is_a_storage_value()
bool StorageValueInformation::is_a_storage_value (vertex curr_vertex, unsigned int var_index) const
return true in case a storage value exist for the pair vertex variable
Parameters
curr_vertex is the vertex
var_index is the variable
Definition at line 121 of file storage_value_information.cpp.
References storage_index_map.
Referenced by mux_connection_binding::connect_to_registers(), mux_connection_binding::create_connections(), fsm_controller::create_state_machine(), port_swapping::InternalExec(), VcdSignalSelection::SelectInternalSignals(), and mux_connection_binding::swap_p().
Friends And Related Function Documentation
values_scheme
friend class values_scheme [friend]
Definition at line 59 of file storage_value_information.hpp.
Field Documentation
data
OpGraphConstRef StorageValueInformation::data [protected]
operation graph used to compute the affinity between storage values
Definition at line 80 of file storage_value_information.hpp.
Referenced by get_compatibility_weight(), and Initialize().
fu
Wrefcount<const fu_binding> StorageValueInformation::fu [protected]
functional unit assignments
Definition at line 83 of file storage_value_information.hpp.
Referenced by get_compatibility_weight(), and Initialize().
function_id
const unsigned int StorageValueInformation::function_id [protected]
The index of the function.
Definition at line 77 of file storage_value_information.hpp.
Referenced by Initialize().
HLS_mgr
const HLS_managerConstRef StorageValueInformation::HLS_mgr [protected]
The HLS manager.
Definition at line 74 of file storage_value_information.hpp.
Referenced by are_value_bitsize_compatible(), get_compatibility_weight(), and Initialize().
number_of_storage_values
unsigned int StorageValueInformation::number_of_storage_values [protected]
current number of storage values
Definition at line 62 of file storage_value_information.hpp.
Referenced by get_number_of_storage_values(), and values_scheme::InternalExec().
storage_index_map
CustomUnorderedMapUnstable<unsigned int, unsigned int> StorageValueInformation::storage_index_map [protected]
put into relation variables/values with storage values
Definition at line 65 of file storage_value_information.hpp.
Referenced by get_storage_value_index(), values_scheme::InternalExec(), and is_a_storage_value().
variable_index_vect
std::vector<unsigned int> StorageValueInformation::variable_index_vect [protected]
put into relation storage value index with variables
Definition at line 68 of file storage_value_information.hpp.
Referenced by get_variable_index(), and values_scheme::InternalExec().
vw2vertex
CustomUnorderedMap<unsigned int, vertex> StorageValueInformation::vw2vertex [protected]
relation between var written and operations
Definition at line 71 of file storage_value_information.hpp.
Referenced by get_compatibility_weight(), and Initialize().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/storage_value_insertion/storage_value_information.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/binding/storage_value_insertion/storage_value_information.cpp