/home/osboxes/bambu/PandA-bambu/src/utility/string_manipulation.cpp File Reference
Auxiliary methods for manipulating string.
#include `string_manipulation.hpp`
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/split.hpp>
#include `exceptions.hpp`
Functions
std::string ConvertInBinary (const std::string &C_value, const unsigned int precision, const bool real_type, const bool unsigned_type)
Header include.
const std::vector< std::string > SplitString (const std::string &input, const std::string &separators)
Function which splits a string into tokens.
Detailed Description
Auxiliary methods for manipulating string.
Author
Marco Lattuada marco.lattuada@polimi.it
Function Documentation
ConvertInBinary()
std::string ConvertInBinary (const std::string & C_value, const unsigned int precision, const bool real_type, const bool unsigned_type)
Header include.
Convert a string storing a number in decimal format into a string in binary format.
Boost includes utility include
Definition at line 51 of file string_manipulation.cpp.
References convert_fp_to_string(), THROW_ASSERT, and THROW_ERROR.
Referenced by TestbenchValuesXMLGeneration::Exec(), MemoryInitializationCWriter::Process(), MemoryInitializationWriter::Process(), HLSCWriter::WriteParamInitialization(), and HLSCWriter::WriteSimulatorInitMemory().
SplitString()
const std::vector<std::string> SplitString (const std::string & input, const std::string & separators)
Function which splits a string into tokens.
Parameters
input is the string to be split
separators is the set of characters to be used to compute the tokens
Returns
the identified tokens
Definition at line 149 of file string_manipulation.cpp.
Referenced by structural_manager::add_port(), pragma_manager::AddFunctionDefinitionPragmas(), TestbenchMemoryAllocation::AllocTestbenchMemory(), FunctionalUnitStep::AnalyzeFu(), minimal_interface::build_wrapper(), xml_child::CGetDescendants(), BambuParameter::CheckParameters(), RTLCharacterization::ComputeCells(), RTLCharacterization::ComputeComponent(), convert_string_to_vector(), GccWrapper::ConvertVersion(), DECODE_FU_LIB(), SimulationTool::DetermineCycles(), BasicBlocksProfiling::Exec(), FixCharacterization::Exec(), SpiderParameter::Exec(), TestbenchValuesXMLGeneration::Exec(), BambuParameter::Exec(), pragma_manager::ExtractClauses(), port_o::fix_port_properties(), GenerateFuList::GenerateFuList(), IcarusWrapper::GenerateScript(), allocation::get_compliant_pipelined_unit(), functional_unit::get_operation(), NP_functionality::get_port_list(), Parameter::getOption(), GccWrapper::GetSystemIncludes(), tree_helper::HasToBeDeclared(), FunctionalUnitStep::Initialize(), AllocationInformation::InitializeDSPDB(), AllocationInformation::InitializeMuxDB(), HWCallInjection::isHardwareCall(), main(), Parameter::ManageDefaultOptions(), TestVectorParser::ParseUserString(), tree_helper::print_type(), Translator::read_column_formats(), read_technology_library(), PragmaParser::recognize_call_point_hw_pragma(), TrimSpaces(), HDL_manager::write_behavioral(), HDL_manager::write_fsm(), HLSCWriter::WriteExpectedResults(), HLSCWriter::WriteSimulatorInitMemory(), technology_manager::xload(), operation::xload(), and module::xload().