Vectorize Class Reference
#include <vectorize.hpp>
Public Member Functions
Vectorize (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
~Vectorize () override
Destructor.
DesignFlowStep_Status InternalExec () override
Restructures the unstructured code.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Types
enum SimdLoop { SIMD_NONE,
SIMD_INNER,
SIMD_OUTER
 }
Enum used to classify the loop according to the required transformation.
Private Member Functions
void ClassifyLoop (const LoopConstRef loop, const size_t parallel_degree)
Classify a loop.
void ClassifyTreeNode (const unsigned int loop_id, const tree_nodeConstRef tree_node)
Classify a statement.
bool LookForScalar (const tree_nodeConstRef tree_node)
Check recursively if at least an ssa operand is defined an operation outside simd outer loop.
unsigned int Transform (const unsigned int tree_node_index, const size_t parallel_degree, const size_t scalar_index, std::list< tree_nodeRef > &created_statements, std::vector< tree_nodeRef > &created_phis)
Transform a tree node.
unsigned int DuplicateIncrement (const unsigned int loop_id, const tree_nodeRef statement)
Duplicate increment statement and update uses of defined variable when necessary.
void AddGuards ()
Add the guards for predicated operations.
void FixPhis ()
Fix the phis to consider implicitly predicated operations.
void SetPredication ()
Set predicate of predicated instructions.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
CustomUnorderedMapUnstable< unsigned int, unsigned int > scalar_to_vector
Map between scalar tree node and vector tree node.
CustomUnorderedMap< unsigned int, CustomUnorderedMapStable< size_t, unsigned int > > scalar_to_scalar
Map between scalar tree node and versioned scalar tree node.
const tree_managerRef TM
The tree manager.
const tree_manipulationRef tree_man
The tree_manipulation.
CustomMap< unsigned int, long long int > iv_increment
THe increment of induction variables; id is the index of the ssa name defined in the init gimple.
CustomMap< unsigned int, unsigned int > gimple_id_to_bb
Map gimple node index to basic block index.
CustomMap< unsigned int, SimdLoop > simd_loop_type
Loop classification.
CustomMap< unsigned int, size_t > loop_parallel_degree
Loop parallel degree.
CustomMap< unsigned int, bool > basic_block_divergence
Basic block classification: if value is true, the basic block can be executed or not in parallel instances.
CustomMap< unsigned int, Transformation > transformations
Statement classification.
CustomMap< unsigned int, tree_nodeRef > guards
The guards for each basic block.
Additional Inherited Members
Detailed Description
Definition at line 67 of file vectorize.hpp.
Member Enumeration Documentation
SimdLoop
enum Vectorize::SimdLoop [private]
Enum used to classify the loop according to the required transformation.
Enumerator
SIMD_NONE
SIMD_INNER No transformation is required.
SIMD_OUTER Loop is nested in a outer simd loop. Loop is a outer simd
Definition at line 86 of file vectorize.hpp.
Constructor & Destructor Documentation
Vectorize()
Vectorize::Vectorize (const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
Constructor.
Parameters
AppM is the application manager
function_id is the identifier of the function
DesignFlowManagerConstRef is the design flow manager
parameters is the set of input parameters
Definition at line 107 of file vectorize.cpp.
References DesignFlowStep::debug_level, GET_CLASS, and ~Vectorize().
 Vectorize()
Vectorize::~Vectorize () [override], [default]
Destructor.
Referenced by Vectorize().
Member Function Documentation
AddGuards()
void Vectorize::AddGuards () [private]
Add the guards for predicated operations.
The guards for combination of basic_block condition
Endif
Header
Create the ssa defined by phi
Create the phi
We cannot use CreateAndExpr to add the created statement since we need to add at the beginning of the current basic block instad of the end
Fix phi
Definition at line 860 of file vectorize.cpp.
References basic_block_divergence, FunctionBehavior::BB, BB_ENTRY, FunctionBehavior::CDG_BB, CDG_SELECTOR, tree_manager::CGetTreeNode(), tree_manipulation::create_boolean_type(), tree_manager::create_tree_node(), tree_manipulation::CreateAndExpr(), tree_manipulation::CreateIntegerCst(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), guards, INDENT_DBG_MEX, tree_manager::new_tree_node_id(), simd_loop_type, SIMD_NONE, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_RES, TOK_SCPE, TOK_SRCP, TOK_TYPE, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, and tree_man.
Referenced by InternalExec().
ClassifyLoop()
void Vectorize::ClassifyLoop (const LoopConstRef loop, const size_t parallel_degree) [private]
Classify a loop.
Parameters
loop is the loop to be analyzed
parallel_degree specifies the degree of parallelism
FIXME: the parallel degree is set to default for doall loop and not read from pragma
The number of iterations can be not multiple of the parallel degree of outer loop
The header cannot diverge
The control condition which enables execution of header
Classify the remaining basic blocks
The control condition which enables execution of header
Classify the remaining basic blocks
If the current parallel degree is different from the parallel loop of the outer loop, this is an outer simd loop
Definition at line 115 of file vectorize.cpp.
References basic_block_divergence, FunctionBehavior::CDG_BB, CDG_SELECTOR, COUNTABLE_LOOP, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DOALL_LOOP, FunctionFrontendFlowStep::function_behavior, INDENT_DBG_MEX, loop_parallel_degree, DesignFlowStep::parameters, SIMD_INNER, simd_loop_type, SIMD_NONE, SIMD_OUTER, STR, and THROW_ASSERT.
Referenced by InternalExec().
ClassifyTreeNode()
void Vectorize::ClassifyTreeNode (const unsigned int loop_id, const tree_nodeConstRef tree_node) [private]
Classify a statement.
Parameters
loop_id is the id of the looop of the statement
tree_node is the tree_node to be classified
Check if the statement is the increment operation of an outer loop
This gimple assign could already be analyzed because of induction variable gimple phi
FIXME: allocation does not support this
FIXME: C backend for vec_lshift_expr is wrong
Check if the phi is the init operation of an outer loop
Check if the phi is in the header of an outer loop
Check if the gimple cond belongs to an exit of the loop
Check that one of the outgoing edge is a feedback edge
Definition at line 253 of file vectorize.cpp.
References basic_block_divergence, FunctionBehavior::BB, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_FAKE_NODES, CASE_PRAGMA_NODES, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), tree_helper::CGetType(), COND_CON, COND_DIV, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, tree_manager::function_index(), GET_CONST_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), GET_NODE, INC, INDENT_DBG_MEX, INIT, iv_increment, NONE, SCALAR, SIMD, simd_loop_type, SIMD_NONE, SIMD_OUTER, STR, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, TM, ToString(), tree_node::ToString(), and transformations.
Referenced by DuplicateIncrement(), and InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > Vectorize::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 1246 of file vectorize.cpp.
References BB_CONTROL_DEPENDENCE_COMPUTATION, BB_ORDER_COMPUTATION, BB_REACHABILITY_COMPUTATION, tree_manager::CGetTreeNode(), DesignFlowStep::DEPENDENCE_RELATIONSHIP, FunctionFrontendFlowStep::function_id, GET_NODE, DesignFlowStep::GetStatus(), DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, sl, SUCCESS, THROW_ASSERT, THROW_UNREACHABLE, and TM.
DuplicateIncrement()
unsigned int Vectorize::DuplicateIncrement (const unsigned int loop_id, const tree_nodeRef statement) [private]
Duplicate increment statement and update uses of defined variable when necessary.
Parameters
loop_id is the id of the loop to which the statement belongs
statement is the statement to be duplicated
Returns
the index of the created statement
First reclassify the original increment as simd
First create the new ssa_name
Duplicate increment
Replace uses
First create the new ssa_name
Duplicate computation of condition
Look for phi computing the guard of header
We create a local variable since first argument of replace_ssa_name is passed by reference. Statement root will not be modified by replace_ssa_name but only their successors
Definition at line 659 of file vectorize.cpp.
References tree_manager::CGetTreeNode(), ClassifyTreeNode(), tree_node_dup::create_tree_node(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, Loop::exit_block_iter_begin(), FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, GET_CONST_NODE, tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), Loop::GetHeader(), tree_manager::GetTreeReindex(), guards, INDENT_DBG_MEX, tree_node::index, Loop::IsReducible(), tree_manager::new_tree_node_id(), Loop::num_exits(), phi, tree_manager::ReplaceTreeNode(), SIMD, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_MAX, TOK_MIN, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, tree_node::ToString(), and transformations.
Referenced by InternalExec().
FixPhis()
void Vectorize::FixPhis () [private]
Fix the phis to consider implicitly predicated operations.
Check if the input basic block diverge
Create the ssa with the new input of the phi
Create the assign
Definition at line 1058 of file vectorize.cpp.
References basic_block_divergence, FunctionBehavior::CDG_BB, tree_helper::CGetType(), tree_manager::create_tree_node(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionBehavior::DOM_TREE, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), tree_manager::GetTreeReindex(), guards, INDENT_DBG_MEX, tree_manager::new_tree_node_id(), phi, simd_loop_type, SIMD_NONE, STR, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_OP0, TOK_OP1, TOK_OP2, TOK_SRCP, TOK_TYPE, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, tree_node::ToString(), and test_panda::type.
Referenced by InternalExec().
HasToBeExecuted()
bool Vectorize::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 2823 of file vectorize.cpp.
References FunctionFrontendFlowStep::bb_version, DOALL_LOOP, and FunctionFrontendFlowStep::function_behavior.
InternalExec()
DesignFlowStep_Status Vectorize::InternalExec () [override], [virtual]
Restructures the unstructured code.
Returns
the exit status of this step
Classify loop
Add the guards
Fix the phi
Predicate instructions which cannot be speculated
Classify statement
Duplicate the increment operation when necessary
Perform the transformation
Remove old statements
Remove old phis
Add new statements
Add new phis
Implements FunctionFrontendFlowStep.
Definition at line 1308 of file vectorize.cpp.
References AddGuards(), FunctionBehavior::BB, BBGraph::CGetBBNodeInfo(), ClassifyLoop(), ClassifyTreeNode(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DuplicateIncrement(), FixPhis(), FunctionFrontendFlowStep::function_behavior, GET_CONST_NODE, GET_NODE, tree_manager::get_tree_node_const(), FunctionFrontendFlowStep::GetName(), tree_manager::GetTreeReindex(), INC, INDENT_DBG_MEX, loop_parallel_degree, DesignFlowStep::parameters, phi, tree_manager::PrintGimple(), SetPredication(), simd_loop_type, SIMD_NONE, STR, SUCCESS, TM, Transform(), transformations, UNCHANGED, and FunctionFrontendFlowStep::WriteBBGraphDot().
LookForScalar()
bool Vectorize::LookForScalar (const tree_nodeConstRef tree_node) [private]
Check recursively if at least an ssa operand is defined an operation outside simd outer loop.
Parameters
tree_node is the root of the tree to be checked
Returns
true if at least a scalar operand is found
Definition at line 796 of file vectorize.cpp.
References CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, and THROW_UNREACHABLE.
SetPredication()
void Vectorize::SetPredication () [private]
Set predicate of predicated instructions.
Definition at line 1214 of file vectorize.cpp.
References basic_block_divergence, FunctionBehavior::BB, DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, GET_NODE, guards, INDENT_DBG_MEX, and STR.
Referenced by InternalExec().
Transform()
unsigned int Vectorize::Transform (const unsigned int tree_node_index, const size_t parallel_degree, const size_t scalar_index, std::list< tree_nodeRef > & created_statements, std::vector< tree_nodeRef > & created_phis) [private]
Transform a tree node.
Parameters
tree_node_index is the tree node to be transformed
parallel_degree is the degree of parallelism
scalar_index is the index of the vector when parallel statements are created as multiple statements
created_statements is the list of statements created during transformation
Returns
the tree node of the transformed node
The current init
Creating scalar from simd
Build bit_field_ref to extract the scalar
vector of boolean types are mapped on vector of unsigned integer
Split of phi node goes to the beginning of the list of statement
Creating scalar from simd
Build bit_field_ref to extract the scalar
vector of boolean types are mapped on vector of integer
Build simd from scalar
Build constructor for right part
Build bit_field_ref to extract the scalar
vector of boolean types are mapped on vector of integer
Workaround due to cycle in the tree between void_type and type_decl
Size of new type
FIXME: check if the function has to parallelized
Build constructor
Creating scalar from simd
Build bit_field_ref to extract the scalar
vector of boolean types are mapped on vector of integer
Split of phi node goes to the beginning of the list of statement
Definition at line 1450 of file vectorize.cpp.
References FrontendFlowStep::AppM, test_panda::arg, FunctionBehavior::BB, CASE_BINARY_EXPRESSION, CASE_CPP_NODES, CASE_CST_NODES, CASE_DECL_NODES, CASE_FAKE_NODES, CASE_GIMPLE_NODES, CASE_PRAGMA_NODES, CASE_QUATERNARY_EXPRESSION, CASE_TERNARY_EXPRESSION, CASE_TYPE_NODES, CASE_UNARY_EXPRESSION, BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), tree_helper::CGetType(), COND_CON, COND_DIV, tree_manipulation::create_default_unsigned_integer_type(), tree_manager::create_tree_node(), tree_manipulation::CreateIntegerCst(), tree_manipulation::CreateOrExpr(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionEdgeInfo::direct_call, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, GET_CONST_NODE, tree_helper::get_integer_cst_value(), tree_node::get_kind(), tree_node::get_kind_text(), tree_manager::get_next_vers(), GET_NODE, tree_manager::get_tree_node_const(), BBGraph::GetBBNodeInfo(), tree_manager::GetTreeReindex(), INC, INDENT_DBG_MEX, index, tree_node::index, INIT, iv_increment, tree_manager::new_tree_node_id(), NONE, FrontendFlowStep::PrintTreeManager(), pointer_type::ptd, SCALAR, scalar_to_scalar, scalar_to_vector, SIMD, tree_helper::Size(), STR, THROW_ASSERT, THROW_UNREACHABLE, TM, TOK, TOK_ADDR, TOK_ALGN, TOK_ARTIFICIAL, TOK_ATTRIBUTES, TOK_BASE, TOK_C, TOK_CHAN, TOK_CLOBBER, TOK_ELTS, TOK_EXTERN, TOK_FN, TOK_IDX, TOK_IDX2, TOK_INIT, TOK_LIBBAMBU, TOK_LIBRARY_SYSTEM, TOK_MAX, TOK_MIN, TOK_MNGL, TOK_NAME, TOK_OFFSET, TOK_OP, TOK_OP0, TOK_OP1, TOK_OP2, TOK_OP3, TOK_OP4, TOK_OP5, TOK_OP6, TOK_OP7, TOK_OP8, TOK_OPERATING_SYSTEM, TOK_OPERATOR, TOK_ORIG, TOK_ORIG_VERS, TOK_PACKED, TOK_PREDICATE, TOK_PTD, TOK_QUAL, TOK_REGISTER, TOK_RES, TOK_SCPE, TOK_SIZE, TOK_SMT_ANN, TOK_SRCP, TOK_STATIC, TOK_STATIC_STATIC, TOK_STEP, TOK_STRG, TOK_SYSTEM, TOK_TMPL_ARGS, TOK_TMPL_PARMS, TOK_TYPE, TOK_UNQL, TOK_USE_TMPL, TOK_USED, TOK_VAR, TOK_VERS, TOK_VIRTUAL, TOK_VOLATILE, ToString(), tree_node::ToString(), transformations, tree_man, and test_panda::type.
Referenced by InternalExec().
Field Documentation
basic_block_divergence
CustomMap<unsigned int, bool> Vectorize::basic_block_divergence [private]
Basic block classification: if value is true, the basic block can be executed or not in parallel instances.
Definition at line 103 of file vectorize.hpp.
Referenced by AddGuards(), ClassifyLoop(), ClassifyTreeNode(), FixPhis(), and SetPredication().
gimple_id_to_bb
CustomMap<unsigned int, unsigned int> Vectorize::gimple_id_to_bb [private]
Map gimple node index to basic block index.
Definition at line 94 of file vectorize.hpp.
guards
CustomMap<unsigned int, tree_nodeRef> Vectorize::guards [private]
The guards for each basic block.
Definition at line 109 of file vectorize.hpp.
Referenced by AddGuards(), DuplicateIncrement(), FixPhis(), and SetPredication().
iv_increment
CustomMap<unsigned int, long long int> Vectorize::iv_increment [private]
THe increment of induction variables; id is the index of the ssa name defined in the init gimple.
Definition at line 83 of file vectorize.hpp.
Referenced by ClassifyTreeNode(), and Transform().
loop_parallel_degree
CustomMap<unsigned int, size_t> Vectorize::loop_parallel_degree [private]
Loop parallel degree.
Definition at line 100 of file vectorize.hpp.
Referenced by ClassifyLoop(), and InternalExec().
scalar_to_scalar
CustomUnorderedMap<unsigned int, CustomUnorderedMapStable<size_t, unsigned int> > Vectorize::scalar_to_scalar [private]
Map between scalar tree node and versioned scalar tree node.
Definition at line 74 of file vectorize.hpp.
Referenced by Transform().
scalar_to_vector
CustomUnorderedMapUnstable<unsigned int, unsigned int> Vectorize::scalar_to_vector [private]
Map between scalar tree node and vector tree node.
Definition at line 71 of file vectorize.hpp.
Referenced by Transform().
simd_loop_type
CustomMap<unsigned int, SimdLoop> Vectorize::simd_loop_type [private]
Loop classification.
Definition at line 97 of file vectorize.hpp.
Referenced by AddGuards(), ClassifyLoop(), ClassifyTreeNode(), FixPhis(), and InternalExec().
TM
const tree_managerRef Vectorize::TM [private]
The tree manager.
Definition at line 77 of file vectorize.hpp.
Referenced by AddGuards(), ClassifyTreeNode(), ComputeFrontendRelationships(), DuplicateIncrement(), FixPhis(), InternalExec(), and Transform().
transformations
CustomMap<unsigned int, Transformation> Vectorize::transformations [private]
Statement classification.
Definition at line 106 of file vectorize.hpp.
Referenced by ClassifyTreeNode(), DuplicateIncrement(), InternalExec(), and Transform().
tree_man
const tree_manipulationRef Vectorize::tree_man [private]
The tree_manipulation.
Definition at line 80 of file vectorize.hpp.
Referenced by AddGuards(), and Transform().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/vectorize.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/vectorize.cpp