Bit_Value Class Reference
Full implementation of Bit Value analysis as described in BitValue Inference: Detecting and Exploiting Narrow Bitwidth Computations Mihai Budiu Seth Copen Goldstein http://www.cs.cmu.edu/~seth/papers/budiu-tr00.pdf.
#include <Bit_Value.hpp>
Public Member Functions
Bit_Value (const ParameterConstRef Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~Bit_Value () override
Destructor.
DesignFlowStep_Status InternalExec () override
perform the bit value analysis
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
Private Member Functions
void print_bitstring_map (const CustomUnorderedMap< unsigned int, std::deque< bit_lattice >> &map) const
Debugging function used to print the contents of the current and best maps.
unsigned int pointer_resizing (unsigned int output_id) const
unsigned int lsb_to_zero (const addr_expr *ae) const
void initialize ()
Initializes best with C type as bitstring, signed_var and arguments using the information taken from the syntax tree given by the application manager.
void clear_current ()
Clears all the entry in the current map, except for the input arguments.
void forward ()
Applies the forward algorithm, as described in the paper, analyzing each assignment statement following the program order, and each phi.
void backward ()
Applies the backward algorithm, as described in the paper, analyzing each assignment statement starting from the output, going up to the inputs, and each phi.
std::deque< bit_lattice > forward_transfer (const gimple_assign *ga) const
Takes a gimple assignment, analyzes the operation performed from the rhs and its input bitstring, and generate a bitstring from the output.
std::deque< bit_lattice > backward_transfer (const gimple_assign *ga, unsigned int output_id) const
Compute the inputs back propagation values, given a gimple assignment and the uid of the output variable.
bool update_IR ()
Updates the bitvalues of the intermediate representation with the values taken from the input map.
bool manage_forward_binary_operands (const binary_expr *operation, unsigned int &arg1_uid, unsigned int &arg2_uid, std::deque< bit_lattice > &arg1_bitstring, std::deque< bit_lattice > &arg2_bitstring) const
Given a binary operation, fetches the uid of the arguments and the relative bitstrings.
std::deque< bit_lattice > backward_compute_result_from_uses (const ssa_name &ssa, const statement_list &sl, unsigned int bb_loop_id) const
Given an ssa_name it computes the resulting bitstring from backward propagation from the places where that ssa is used.
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Private Attributes
bool not_frontend
True if this step is not executed in the frontend.
CustomUnorderedMapUnstable< unsigned int, unsigned int > direct_call_id_to_called_id
Maps the id of a gimple statement to the id of the function called in that statement.
CustomUnorderedSet< unsigned int > arguments
Contains the input parameters of the function that's being analyzed.
Static Private Attributes
static const std::map< bit_lattice, std::map< bit_lattice, std::map< bit_lattice, std::deque< bit_lattice > > > > plus_expr_map
Map storing the implementation of the forward_transfer's plus_expr.
static const std::map< bit_lattice, std::map< bit_lattice, std::map< bit_lattice, std::deque< bit_lattice > > > > minus_expr_map
Map storing the implementation of the forward_transfer's minus_expr.
static const std::map< bit_lattice, std::map< bit_lattice, bit_lattice > > bit_ior_expr_map
Map storing the implementation of the forward_transfer's bit_ior_expr_map.
static const std::map< bit_lattice, std::map< bit_lattice, bit_lattice > > bit_xor_expr_map
Map storing the implementation of the forward_transfer's bit_xor_expr_map.
static const std::map< bit_lattice, std::map< bit_lattice, bit_lattice > > bit_and_expr_map
Map storing the implementation of the forward_transfer's bit_and_expr_map.
Additional Inherited Members
Detailed Description
Full implementation of Bit Value analysis as described in BitValue Inference: Detecting and Exploiting Narrow Bitwidth Computations Mihai Budiu Seth Copen Goldstein http://www.cs.cmu.edu/~seth/papers/budiu-tr00.pdf.
Definition at line 77 of file Bit_Value.hpp.
Constructor & Destructor Documentation
Bit_Value()
Bit_Value::Bit_Value (const ParameterConstRef Param, const application_managerRef _AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Parameters
_Param is the set of the parameters
_AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
Definition at line 888 of file Bit_Value.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~Bit_Value().
 Bit_Value()
Bit_Value::~Bit_Value () [override], [default]
Destructor.
Referenced by Bit_Value().
Member Function Documentation
backward()
void Bit_Value::backward () [private]
Applies the backward algorithm, as described in the paper, analyzing each assignment statement starting from the output, going up to the inputs, and each phi.
Uses the backward_transfer() function to compute the output's bitstring, that stores in current. The algorithm loops until current is modified.
See also
backward_transfer()
Definition at line 202 of file Bit_Value_backward.cpp.
References backward_compute_result_from_uses(), BitLatticeManipulator::best, bitstring_constant(), tree_helper::CGetType(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, INDENT_DBG_MEX, BitLatticeManipulator::is_handled_by_bitvalue(), sl, STR, THROW_ASSERT, BitLatticeManipulator::TM, and BitLatticeManipulator::update_current().
Referenced by InternalExec().
backward_compute_result_from_uses()
std::deque< bit_lattice > Bit_Value::backward_compute_result_from_uses (const ssa_name & ssa, const statement_list & sl, unsigned int bb_loop_id) const [private]
Given an ssa_name it computes the resulting bitstring from backward propagation from the places where that ssa is used.
Parameters
ssa the ssa_name to process
sl is the statment list of the function where ssa is defined
bb_loop_id is the loop_id of the basic block where ssa is defined
Returns
the computed bitstring
Author
Giulio Stramondo
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Pietro Fezzardi pietrofezzardi@gmail.com
Definition at line 59 of file Bit_Value_backward.cpp.
References FrontendFlowStep::AppM, backward_transfer(), BitLatticeManipulator::best, bitstring_to_string(), ssa_name::CGetUseStmts(), create_u_bitstring(), create_x_bitstring(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, direct_call_id_to_called_id, FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, tree_node::index, BitLatticeManipulator::inf(), statement_list::list_of_bloc, tree_helper::Size(), STR, string_to_bitstring(), THROW_ASSERT, and BitLatticeManipulator::TM.
Referenced by backward().
backward_transfer()
std::deque< bit_lattice > Bit_Value::backward_transfer (const gimple_assign * ga, unsigned int output_id) const [private]
Compute the inputs back propagation values, given a gimple assignment and the uid of the output variable.
Parameters
ga gimple assignment that is being analyzed
output_id uid of the output of the given gimple assignment.
Returns
computed backpropagation bitstring
first check if the gimple assign still produces something of relevant and it is not a call_expr
we cannot say anything on abs_expr
Definition at line 295 of file Bit_Value_backward.cpp.
References call_expr::args, BitLatticeManipulator::best, BitLatticeManipulator::bit_inf(), bitstring_to_string(), tree_helper::CGetType(), create_u_bitstring(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, direct_call_id_to_called_id, GET_INDEX_NODE, GET_NODE, tree_helper::get_type_index(), INDENT_DBG_MEX, index, tree_node::index, BitLatticeManipulator::inf(), tree_helper::is_int(), ONE, gimple_assign::op0, gimple_assign::op1, pointer_resizing(), BitLatticeManipulator::sign_extend_bitstring(), tree_helper::size(), tree_helper::Size(), STR, string_to_bitstring(), gimple_assign::temporary_address, THROW_ASSERT, THROW_ERROR, BitLatticeManipulator::TM, tree_node::ToString(), X, and ZERO.
Referenced by backward_compute_result_from_uses().
clear_current()
void Bit_Value::clear_current () [private]
Clears all the entry in the current map, except for the input arguments.
Definition at line 1682 of file Bit_Value.cpp.
References arguments, BitLatticeManipulator::best, BitLatticeManipulator::current, and FunctionFrontendFlowStep::function_id.
Referenced by InternalExec().
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > Bit_Value::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 896 of file Bit_Value.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, THROW_UNREACHABLE, and USE_COUNTING.
forward()
void Bit_Value::forward () [private]
Applies the forward algorithm, as described in the paper, analyzing each assignment statement following the program order, and each phi.
Uses the forward_transfer() function to compute the output's bitstring, that stores in current. The algorithm loops until current is modified.
See also
forward_transfer()
Definition at line 2194 of file Bit_Value_forward.cpp.
References BitLatticeManipulator::best, bitstring_to_string(), tree_helper::CGetType(), create_u_bitstring(), create_x_bitstring(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, forward_transfer(), FunctionFrontendFlowStep::function_id, GET_INDEX_NODE, GET_NODE, tree_helper::get_required_values(), INDENT_DBG_MEX, BitLatticeManipulator::inf(), BitLatticeManipulator::is_handled_by_bitvalue(), tree_helper::is_int(), phi, tree_helper::Size(), sl, STR, THROW_ASSERT, BitLatticeManipulator::TM, and BitLatticeManipulator::update_current().
Referenced by InternalExec().
forward_transfer()
std::deque< bit_lattice > Bit_Value::forward_transfer (const gimple_assign * ga) const [private]
Takes a gimple assignment, analyzes the operation performed from the rhs and its input bitstring, and generate a bitstring from the output.
Parameters
ga assignment to analyze
Returns
output bitstring
Definition at line 107 of file Bit_Value_forward.cpp.
References FrontendFlowStep::AppM, BitLatticeManipulator::best, bit_and_expr_map, bit_ior_expr_map, bit_xor_expr_map, bitstring_to_string(), tree_helper::CGetType(), create_u_bitstring(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, direct_call_id_to_called_id, GET_INDEX_NODE, GET_NODE, INDENT_DBG_MEX, index, tree_node::index, BitLatticeManipulator::inf(), tree_helper::is_bool(), BitLatticeManipulator::is_handled_by_bitvalue(), tree_helper::is_int(), lsb_to_zero(), manage_forward_binary_operands(), max(), min, minus_expr_map, ONE, gimple_assign::op0, gimple_assign::op1, plus_expr_map, BitLatticeManipulator::sign_extend_bitstring(), tree_helper::Size(), STR, string_to_bitstring(), THROW_ASSERT, THROW_UNREACHABLE, BitLatticeManipulator::TM, U, X, and ZERO.
Referenced by forward().
HasToBeExecuted()
bool Bit_Value::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from FunctionFrontendFlowStep.
Definition at line 1746 of file Bit_Value.cpp.
References FunctionFrontendFlowStep::bitvalue_version, FunctionFrontendFlowStep::function_behavior, and FunctionFrontendFlowStep::HasToBeExecuted().
initialize()
void Bit_Value::initialize () [private]
Initializes best with C type as bitstring, signed_var and arguments using the information taken from the syntax tree given by the application manager.
Scan all the gimple assign statements in each bloc if the left hand side is signed this is inserted into the signed_var set (this information is used by the signextension)
for each lhs variable in the gimple_assign instruction and entry is created in the best map the entry in the map is of the type <GET_INDEX_NODE(lhs), bit_string of <U>s of the variable lenght> for each gimple_assign the used variables are checked against the values in the parm set in order to identify the parameters of the function when those are found their ssa index node is added in the best map and in the arguments map (used by the clear() function)
Scans each phi in the bloc (not virtual) res of the phi is added to the signed_var set if it's signed, and to the best map
The edge of each phi are scanned, if the edge is carrying a constant of type integer_cst the index of the integer_cst node is used to identify it, one entry is created for the best table mapping the integer_cst index to its bitstring representation if the value of the constant is negative it's added to the signed_var set
if the edge is carrying a ssa variable it's checked if its a parameter, if it is, it is added to the arguments set and, it is added to the best map check if this assignment is a load from a constant array
and now something for the written variables
check if this assignment is a load from a constant array
Definition at line 1015 of file Bit_Value.cpp.
References FrontendFlowStep::AppM, arguments, BitLatticeManipulator::best, bitstring_to_string(), FunctionBehavior::CGetBehavioralHelper(), tree_helper::CGetType(), BitLatticeManipulator::clear(), BitLatticeManipulator::constructor_bitstring(), create_bitstring_from_constant(), create_u_bitstring(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, direct_call_id_to_called_id, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_base_index(), BehavioralHelper::get_function_name(), GET_INDEX_NODE, tree_node::get_kind(), GET_NODE, tree_helper::get_required_values(), tree_helper::GetFunctionReturnType(), INDENT_DBG_MEX, tree_node::index, BitLatticeManipulator::inf(), BitLatticeManipulator::is_handled_by_bitvalue(), tree_helper::is_int(), tree_helper::is_natural(), OUTPUT_LEVEL_PEDANTIC, phi, print_bitstring_map(), BitLatticeManipulator::sign_extend_bitstring(), BitLatticeManipulator::sign_reduce_bitstring(), BitLatticeManipulator::signed_var, tree_helper::Size(), sl, STR, BitLatticeManipulator::string_cst_bitstring(), string_to_bitstring(), BitLatticeManipulator::sup(), THROW_ASSERT, THROW_UNREACHABLE, BitLatticeManipulator::TM, and ZERO.
Referenced by InternalExec().
Initialize()
void Bit_Value::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 1740 of file Bit_Value.cpp.
References ApplicationFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, EMPTY, Wrefcount< T >::lock(), and not_frontend.
InternalExec()
DesignFlowStep_Status Bit_Value::InternalExec () [override], [virtual]
perform the bit value analysis
Returns
the exit status of this step
Implements FunctionFrontendFlowStep.
Definition at line 1698 of file Bit_Value.cpp.
References arguments, backward(), BitLatticeManipulator::best, FunctionFrontendFlowStep::bitvalue_version, BitLatticeManipulator::clear(), clear_current(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, direct_call_id_to_called_id, forward(), FunctionFrontendFlowStep::function_behavior, INDENT_DBG_MEX, initialize(), BitLatticeManipulator::mix(), print_bitstring_map(), PRINT_DBG_MEX, test_panda::restart, SUCCESS, UNCHANGED, and update_IR().
lsb_to_zero()
unsigned int Bit_Value::lsb_to_zero (const addr_expr * ae) const [private]
Definition at line 870 of file Bit_Value.cpp.
References FrontendFlowStep::AppM, GET_NODE, and index.
Referenced by forward_transfer().
manage_forward_binary_operands()
bool Bit_Value::manage_forward_binary_operands (const binary_expr * operation, unsigned int & arg1_uid, unsigned int & arg2_uid, std::deque< bit_lattice > & arg1_bitstring, std::deque< bit_lattice > & arg2_bitstring) const [private]
Given a binary operation, fetches the uid of the arguments and the relative bitstrings.
Parameters
operation where the inputs are going to be extracted from.
arg1_uid where the uid of the first argument is going to be stored
arg2_uid where the uid of the second argument is going to be stored
arg1_bitstring where the bitstring (taken from best) relative to argument 1 is going to be saved.
arg2_bitstring where the bitstring (taken from best) relative to argument 2 is going to be saved.
Returns
TRUE, if the operation was successful, FALSE otherwise.
Author
Giulio Stramondo
Pietro Fezzardi pietrofezzardi@gmail.com
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it
Definition at line 54 of file Bit_Value_forward.cpp.
References BitLatticeManipulator::best, bitstring_to_string(), tree_helper::CGetType(), create_u_bitstring(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, GET_INDEX_NODE, GET_NODE, INDENT_DBG_MEX, BitLatticeManipulator::is_handled_by_bitvalue(), binary_expr::op0, binary_expr::op1, tree_helper::Size(), STR, and THROW_ASSERT.
Referenced by forward_transfer().
pointer_resizing()
unsigned int Bit_Value::pointer_resizing (unsigned int output_id) const [private]
check if it clash with the alignment:
Definition at line 812 of file Bit_Value.cpp.
References FrontendFlowStep::AppM, GccWrapper::CGetPointerSize(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FunctionFrontendFlowStep::function_behavior, FunctionFrontendFlowStep::function_id, tree_helper::get_base_index(), INDENT_DBG_MEX, index, not_frontend, DesignFlowStep::parameters, tree_helper::size(), STR, and BitLatticeManipulator::TM.
Referenced by backward_transfer().
print_bitstring_map()
void Bit_Value::print_bitstring_map (const CustomUnorderedMap< unsigned int, std::deque< bit_lattice >> & map) const [private]
Debugging function used to print the contents of the current and best maps.
Parameters
map map to be printed
Definition at line 926 of file Bit_Value.cpp.
References FrontendFlowStep::AppM, bitstring_to_string(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionFrontendFlowStep::function_id, INDENT_DBG_MEX, BehavioralHelper::PrintVariable(), and STR.
Referenced by initialize(), and InternalExec().
update_IR()
bool Bit_Value::update_IR () [private]
Updates the bitvalues of the intermediate representation with the values taken from the input map.
Definition at line 941 of file Bit_Value.cpp.
References BitLatticeManipulator::best, bitstring_to_string(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, FunctionFrontendFlowStep::function_id, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, INDENT_DBG_MEX, STR, THROW_ASSERT, THROW_ERROR, and BitLatticeManipulator::TM.
Referenced by InternalExec().
Field Documentation
arguments
CustomUnorderedSet<unsigned int> Bit_Value::arguments [private]
Contains the input parameters of the function that's being analyzed.
Definition at line 118 of file Bit_Value.hpp.
Referenced by clear_current(), initialize(), and InternalExec().
bit_and_expr_map
const std::map< bit_lattice, std::map< bit_lattice, bit_lattice > > Bit_Value::bit_and_expr_map [static], [private]
Map storing the implementation of the forward_transfer's bit_and_expr_map.
Definition at line 103 of file Bit_Value.hpp.
Referenced by forward_transfer().
bit_ior_expr_map
const std::map< bit_lattice, std::map< bit_lattice, bit_lattice > > Bit_Value::bit_ior_expr_map [static], [private]
Map storing the implementation of the forward_transfer's bit_ior_expr_map.
Definition at line 93 of file Bit_Value.hpp.
Referenced by forward_transfer().
bit_xor_expr_map
const std::map< bit_lattice, std::map< bit_lattice, bit_lattice > > Bit_Value::bit_xor_expr_map [static], [private]
Map storing the implementation of the forward_transfer's bit_xor_expr_map.
Definition at line 98 of file Bit_Value.hpp.
Referenced by forward_transfer().
direct_call_id_to_called_id
CustomUnorderedMapUnstable<unsigned int, unsigned int> Bit_Value::direct_call_id_to_called_id [private]
Maps the id of a gimple statement to the id of the function called in that statement.
This relationship is created only for direct calls, because for indirect calls there is not a one-to-one relationship
Definition at line 113 of file Bit_Value.hpp.
Referenced by backward_compute_result_from_uses(), backward_transfer(), forward_transfer(), initialize(), and InternalExec().
minus_expr_map
const std::map< bit_lattice, std::map< bit_lattice, std::map< bit_lattice, std::deque< bit_lattice > > > > Bit_Value::minus_expr_map [static], [private]
Map storing the implementation of the forward_transfer's minus_expr.
Definition at line 88 of file Bit_Value.hpp.
Referenced by forward_transfer().
not_frontend
bool Bit_Value::not_frontend [private]
True if this step is not executed in the frontend.
Definition at line 106 of file Bit_Value.hpp.
Referenced by Initialize(), and pointer_resizing().
plus_expr_map
const std::map< bit_lattice, std::map< bit_lattice, std::map< bit_lattice, std::deque< bit_lattice > > > > Bit_Value::plus_expr_map [static], [private]
Map storing the implementation of the forward_transfer's plus_expr.
Header include.
. include behavior includes design_flows include frontend_analysis HLS include HLS/memory include STD include STL includes tree include wrapper/treegcc include
Definition at line 83 of file Bit_Value.hpp.
Referenced by forward_transfer().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value.cpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value_backward.cpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/Bit_Value_forward.cpp