rehashed_heap< _Type > Struct Template Reference
Class used to represent a priority queue of vertex with rehash.
#include <rehashed_heap.hpp>
Public Member Functions
rehashed_heap (const priority_compare_functor< _Type > &_comp)
Constructor.
void rehash ()
Rehash the heap associated with the priority queue.
std::vector< vertex >::const_iterator begin ()
std::vector< vertex >::const_iterator end ()
Detailed Description
template<class _Type>
struct rehashed_heap< _Type >
Class used to represent a priority queue of vertex with rehash.
Definition at line 69 of file rehashed_heap.hpp.
Constructor & Destructor Documentation
rehashed_heap()
template<class _Type >
rehashed_heap< _Type >::rehashed_heap (const priority_compare_functor< _Type > & _comp) [inline]
Constructor.
Parameters
pri is the priority functor.
Definition at line 75 of file rehashed_heap.hpp.
Member Function Documentation
begin()
template<class _Type >
std::vector<vertex>::const_iterator rehashed_heap< _Type >::begin () [inline]
Definition at line 87 of file rehashed_heap.hpp.
Referenced by tree_rehashed_heap< _Type >::rehash(), and tree_rehashed_heap< _Type >::top().
end()
template<class _Type >
std::vector<vertex>::const_iterator rehashed_heap< _Type >::end () [inline]
Definition at line 91 of file rehashed_heap.hpp.
Referenced by tree_rehashed_heap< _Type >::rehash(), and tree_rehashed_heap< _Type >::top().
rehash()
template<class _Type >
void rehashed_heap< _Type >::rehash () [inline]
Rehash the heap associated with the priority queue.
Definition at line 81 of file rehashed_heap.hpp.
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/HLS/scheduling/rehashed_heap.hpp