controller_cs Class Reference
#include <controller_cs.hpp>
Public Member Functions
controller_cs (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
virtual ~controller_cs ()
Destructor.
Protected Member Functions
void add_common_ports (structural_objectRef circuit)
This member function adds the standard ports (clock, reset, done and command ones) to a circuit.
void add_selector_register_file_port (structural_objectRef circuit)
void add_correct_transition_memory (std::string state_representation)
Set the correct NP functionality.
Additional Inherited Members
Detailed Description
Definition at line 44 of file controller_cs.hpp.
Constructor & Destructor Documentation
controller_cs()
controller_cs::controller_cs (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStep_Type hls_flow_step_type)
Constructor.
utility include
Definition at line 57 of file controller_cs.cpp.
 controller_cs()
controller_cs::~controller_cs () [virtual]
Destructor.
Definition at line 62 of file controller_cs.cpp.
Member Function Documentation
add_common_ports()
void controller_cs::add_common_ports (structural_objectRef circuit) [protected], [virtual]
This member function adds the standard ports (clock, reset, done and command ones) to a circuit.
Parameters
circuit it is the datastructure of the component where to add these ports
Reimplemented from ControllerCreatorBaseStep.
Definition at line 66 of file controller_cs.cpp.
References ControllerCreatorBaseStep::add_common_ports(), add_selector_register_file_port(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, HLSFunctionStep::funId, HLS_step::HLSMgr, and PRINT_DBG_MEX.
add_correct_transition_memory()
void controller_cs::add_correct_transition_memory (std::string state_representation) [protected], [virtual]
Set the correct NP functionality.
Parameters
state_representation is the state representation of the FSM
Reimplemented from fsm_controller.
Definition at line 96 of file controller_cs.cpp.
References structural_manager::add_NP_functionality(), NP_functionality::FSM, NP_functionality::FSM_CS, HLSFunctionStep::funId, structural_manager::get_circ(), HLS_step::HLSMgr, and ControllerCreatorBaseStep::SM.
add_selector_register_file_port()
void controller_cs::add_selector_register_file_port (structural_objectRef circuit) [protected]
add selector port
Definition at line 84 of file controller_cs.cpp.
References structural_manager::add_port(), ceil_log2(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, port_o::IN, DesignFlowStep::parameters, PRINT_DBG_MEX, SELECTOR_REGISTER_FILE, ControllerCreatorBaseStep::SM, and STR.
Referenced by add_common_ports().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/controller_cs.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/architecture_creation/controller_creation/controller_cs.cpp