add_library Class Reference
#include <add_library.hpp>
Public Member Functions
add_library (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
Constructor.
~add_library () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
Private Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Definition at line 81 of file add_library.hpp.
Constructor & Destructor Documentation
add_library()
add_library::add_library (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager, const HLSFlowStepSpecializationConstRef hls_flow_step_specialization)
Constructor.
Parameters
design_flow_manager is the design flow manager
Definition at line 93 of file add_library.cpp.
References DesignFlowStep::debug_level, GET_CLASS, DesignFlowStep::parameters, and ~add_library().
 add_library()
add_library::~add_library () [override], [default]
Destructor.
Referenced by add_library().
Member Function Documentation
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > add_library::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Reimplemented from HLS_step.
Definition at line 101 of file add_library.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, HLSFunctionStep::funId, HLS_step::hls_flow_step_specialization, HLS_step::HLSMgr, DesignFlowStep::INVALIDATION_RELATIONSHIP, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, THROW_ASSERT, THROW_UNREACHABLE, TOP_ENTITY_CREATION, TOP_ENTITY_CS_CREATION, TOP_ENTITY_CS_PARALLEL_CREATION, TOP_ENTITY_MEMORY_MAPPED_CREATION, and WB4_INTERFACE_GENERATION.
InternalExec()
DesignFlowStep_Status add_library::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
First computing if operation is bounded, then computing call_delay; call_delay depends on the value of bounded
functions accessing memory are classified as unbounded
FIXME: identification of pipelined functions is disabled since liveness analysis of parameters have not yet been added
fake number to avoid sharing of functions
Implements HLSFunctionStep.
Definition at line 172 of file add_library.cpp.
References technology_manager::add_operation(), hls::allocation_information, FunctionBehavior::CGetBehavioralHelper(), StateTransitionGraphManager::CGetStg(), functional_unit::COMBINATIONAL, area_model::create_model(), time_model::create_model(), DesignFlowStep::debug_level, DEBUG_LEVEL_MINIMUM, DEBUG_LEVEL_VERY_PEDANTIC, AllocationInformation::estimate_call_delay(), HLSFunctionStep::funId, structural_manager::get_circ(), technology_manager::get_fu(), BehavioralHelper::get_function_name(), technology_manager::get_library_manager(), structural_object::get_path(), target_device::get_type(), structural_object::get_typeRef(), HLSFunctionStep::HLS, hls::HLS_C, HLS_step::hls_flow_step_specialization, hls::HLS_T, HLS_step::HLSMgr, structural_type_descriptor::id_type, INDENT_DBG_MEX, NP_functionality::LIBRARY, DesignFlowStep::parameters, PROXY_LIBRARY, PROXY_PREFIX, hls::registered_inputs, library_manager::remove_fu(), area_model::set_area_value(), hls::STG, STR, SUCCESS, THROW_ASSERT, hls::top, WORK_LIBRARY, and WRAPPED_PROXY_PREFIX.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/add_library.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/module_allocation/add_library.cpp