bb_feedback_edges_computation Class Reference
Compute the feedback edges of the basic block control flow graph.
#include <bb_feedback_edges_computation.hpp>
Public Member Functions
bb_feedback_edges_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~bb_feedback_edges_computation () override
Destructor.
DesignFlowStep_Status InternalExec () override
Compute the feedback edges for the CFG and the CDG operations graphs (at basic block level).
Private Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
Additional Inherited Members
Detailed Description
Compute the feedback edges of the basic block control flow graph.
Definition at line 62 of file bb_feedback_edges_computation.hpp.
Constructor & Destructor Documentation
bb_feedback_edges_computation()
bb_feedback_edges_computation::bb_feedback_edges_computation (const ParameterConstRef Param, const application_managerRef AppM, unsigned int function_id, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
tree include
Parameters
Param is the set of the parameters
AppM is the application manager
function_id is the identifier of the function
design_flow_manager is the design flow manager
Definition at line 63 of file bb_feedback_edges_computation.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~bb_feedback_edges_computation().
 bb_feedback_edges_computation()
bb_feedback_edges_computation::~bb_feedback_edges_computation () [override], [default]
Destructor.
Referenced by bb_feedback_edges_computation().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > bb_feedback_edges_computation::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [private], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements FrontendFlowStep.
Definition at line 71 of file bb_feedback_edges_computation.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LOOPS_COMPUTATION, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
InternalExec()
DesignFlowStep_Status bb_feedback_edges_computation::InternalExec () [override], [virtual]
Compute the feedback edges for the CFG and the CDG operations graphs (at basic block level).
Returns
the exit status of this step
then consider loops
FIXME: check to identify irreducible loops, since Loop::IsReducible does not work
Implements FunctionFrontendFlowStep.
Definition at line 94 of file bb_feedback_edges_computation.cpp.
References FunctionBehavior::BB, CFG_SELECTOR, BBGraph::CGetBBNodeInfo(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, FB_CFG_SELECTOR, FunctionBehavior::FBB, FunctionFrontendFlowStep::function_behavior, BehavioralHelper::get_function_name(), INDENT_DBG_MEX, IRREDUCIBLE_LOOPS_EC, DesignFlowStep::parameters, STR, SUCCESS, THROW_ERROR_CODE, and graph::TopologicalSort().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/bb_feedback_edges_computation.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/behavior_analysis/bb_feedback_edges_computation.cpp