/home/osboxes/bambu/PandA-bambu/src/HLS/vcd/CallGraphUnfolding.cpp File Reference
#include `CallGraphUnfolding.hpp`
#include `Parameter.hpp`
#include `call_graph.hpp`
#include `call_graph_manager.hpp`
#include `op_graph.hpp`
#include `hls_manager.hpp`
#include `CallSitesCollectorVisitor.hpp`
#include `Discrepancy.hpp`
#include `UnfoldedCallGraph.hpp`
#include `UnfoldedCallInfo.hpp`
#include `UnfoldedFunctionInfo.hpp`
#include `dbgPrintHelper.hpp`
#include `string_manipulation.hpp`
Functions
static void RecursivelyUnfold (const UnfoldedVertexDescriptor caller_v, UnfoldedCallGraph &ucg, const CallGraphConstRef &cg, const CallSitesInfoRef &call_sites_info)
static void Unfold (const HLS_managerRef &HLSMgr)
Function Documentation
RecursivelyUnfold()
static void RecursivelyUnfold (const UnfoldedVertexDescriptor caller_v, UnfoldedCallGraph & ucg, const CallGraphConstRef & cg, const CallSitesInfoRef & call_sites_info) [static]
Author
Pietro Fezzardi pietrofezzardi@gmail.com
Definition at line 59 of file CallGraphUnfolding.cpp.
References RawGraph::AddEdge(), RawGraph::AddVertex(), CallSitesInfo::call_id_to_called_id, CallSitesInfo::fu_id_to_call_ids, CallSitesInfo::indirect_calls, and CallSitesInfo::taken_addresses.
Referenced by Unfold().
Unfold()
static void Unfold (const HLS_managerRef & HLSMgr) [static]
Definition at line 86 of file CallGraphUnfolding.cpp.
References FunctionBehavior::FCFG, RecursivelyUnfold(), STR, and THROW_ASSERT.
Referenced by CallGraphUnfolding::Exec().