BitValueIPA Class Reference
Inter-Procedural extension of the Bit Value analysis as described in BitValue Inference: Detecting and Exploiting Narrow Bitwidth Computations Mihai Budiu Seth Copen Goldstein http://www.cs.cmu.edu/~seth/papers/budiu-tr00.pdf.
#include <BitValueIPA.hpp>
Public Member Functions
BitValueIPA (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
STD include.
~BitValueIPA () override
DesignFlowStep_Status Exec () override
Execute the step.
bool HasToBeExecuted () const override
Check if this step has actually to be executed.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FunctionRelationship > > ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Return the set of analyses in relationship with this design step.
void ComputeRelationships (DesignFlowStepSet &relationships, const DesignFlowStep::RelationshipType relationship_type) override
Compute the relationships of a step with other steps.
Protected Attributes
CustomOrderedSet< unsigned int > fun_id_to_restart
stores the function ids of the functions whose Bit_Value intra procedural steps have to be invalidated by this step
std::map< unsigned int, unsigned int > last_bitvalue_ver
std::map< unsigned int, unsigned int > last_bb_ver
Additional Inherited Members
Detailed Description
Inter-Procedural extension of the Bit Value analysis as described in BitValue Inference: Detecting and Exploiting Narrow Bitwidth Computations Mihai Budiu Seth Copen Goldstein http://www.cs.cmu.edu/~seth/papers/budiu-tr00.pdf.
Definition at line 59 of file BitValueIPA.hpp.
Constructor & Destructor Documentation
BitValueIPA()
BitValueIPA::BitValueIPA (const application_managerRef AppM, const DesignFlowManagerConstRef design_flow_manager, const ParameterConstRef parameters)
STD include.
Definition at line 79 of file BitValueIPA.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_NONE, GET_CLASS, DesignFlowStep::parameters, and ~BitValueIPA().
 BitValueIPA()
BitValueIPA::~BitValueIPA () [override], [default]
Referenced by BitValueIPA().
Member Function Documentation
ComputeFrontendRelationships()
const CustomUnorderedSet< std::pair< FrontendFlowStepType, FrontendFlowStep::FunctionRelationship > > BitValueIPA::ComputeFrontendRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Return the set of analyses in relationship with this design step.
Parameters
relationship_type is the type of relationship to be considered
Implements ApplicationFrontendFlowStep.
Definition at line 87 of file BitValueIPA.cpp.
References FrontendFlowStep::ALL_FUNCTIONS, DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, MEM_CG_EXT, DesignFlowStep::PRECEDENCE_RELATIONSHIP, FrontendFlowStep::SAME_FUNCTION, and THROW_UNREACHABLE.
ComputeRelationships()
void BitValueIPA::ComputeRelationships (DesignFlowStepSet & relationship, const DesignFlowStep::RelationshipType relationship_type) [override], [protected], [virtual]
Compute the relationships of a step with other steps.
Parameters
dependencies is where relationships will be stored
relationship_type is the type of relationship to be computed
Reimplemented from FrontendFlowStep.
Definition at line 117 of file BitValueIPA.cpp.
References FrontendFlowStep::AppM, FrontendFlowStep::ComputeRelationships(), FunctionFrontendFlowStep::ComputeSignature(), DesignFlowStep::design_flow_manager, fun_id_to_restart, DesignFlowStep::INVALIDATION_RELATIONSHIP, Wrefcount< T >::lock(), NULL_VERTEX, and THROW_ASSERT.
Exec()
DesignFlowStep_Status BitValueIPA::Exec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
In case of indirect calls (e.g., pointer to function) no Bit Value IPA can be done.
Implements ApplicationFrontendFlowStep.
Definition at line 149 of file BitValueIPA.cpp.
References FrontendFlowStep::AppM, BitLatticeManipulator::best, function_decl::bit_values, bitstring_to_string(), function_decl::body, tree_helper::CGetType(), BitLatticeManipulator::clear(), tree_helper::ComputeSsaUses(), create_bitstring_from_constant(), create_u_bitstring(), create_x_bitstring(), BitLatticeManipulator::current, DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERY_PEDANTIC, fun_id_to_restart, GET_INDEX_NODE, tree_node::get_kind(), tree_node::get_kind_text(), GET_NODE, FunctionBehavior::GetBBVersion(), FunctionBehavior::GetBitValueVersion(), tree_helper::GetFunctionReturnType(), INDENT_DBG_MEX, BitLatticeManipulator::inf(), BitLatticeManipulator::is_handled_by_bitvalue(), tree_helper::is_int(), last_bb_ver, last_bitvalue_ver, function_decl::list_of_args, BitLatticeManipulator::mix(), test_panda::restart, BitLatticeManipulator::signed_var, tree_helper::Size(), sl, STR, string_to_bitstring(), SUCCESS, THROW_ASSERT, THROW_ERROR, THROW_UNREACHABLE, BitLatticeManipulator::TM, UNCHANGED, and BitLatticeManipulator::update_current().
HasToBeExecuted()
bool BitValueIPA::HasToBeExecuted () const [override], [virtual]
Check if this step has actually to be executed.
Returns
true if the step has to be executed
Reimplemented from ApplicationFrontendFlowStep.
Definition at line 135 of file BitValueIPA.cpp.
References FrontendFlowStep::AppM, FunctionBehavior::GetBBVersion(), FunctionBehavior::GetBitValueVersion(), last_bb_ver, and last_bitvalue_ver.
Initialize()
void BitValueIPA::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from DesignFlowStep.
Definition at line 895 of file BitValueIPA.cpp.
Field Documentation
fun_id_to_restart
CustomOrderedSet<unsigned int> BitValueIPA::fun_id_to_restart [protected]
stores the function ids of the functions whose Bit_Value intra procedural steps have to be invalidated by this step
Definition at line 66 of file BitValueIPA.hpp.
Referenced by ComputeRelationships(), and Exec().
last_bb_ver
std::map<unsigned int, unsigned int> BitValueIPA::last_bb_ver [protected]
Definition at line 70 of file BitValueIPA.hpp.
Referenced by Exec(), and HasToBeExecuted().
last_bitvalue_ver
std::map<unsigned int, unsigned int> BitValueIPA::last_bitvalue_ver [protected]
Definition at line 68 of file BitValueIPA.hpp.
Referenced by Exec(), and HasToBeExecuted().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/BitValueIPA.hpp
/home/osboxes/bambu/PandA-bambu/src/frontend_analysis/IR_analysis/BitValueIPA.cpp