BambuParameter Class Reference
#include <BambuParameter.hpp>
Public Member Functions
BambuParameter (const std::string &program_name, int argc, char **const argv)
Constructor.
~BambuParameter () override=default
Destructor.
int Exec () override
Execute parameter parsing.
void SetDefaults () override
Sets default values.
Private Member Functions
void CheckParameters () override
Check the compatibility among the different parameters and compute implicated parameters.
void add_bambu_library (std::string lib)
add the library to the raw to be considered
void PrintHelp (std::ostream &os) const override
Print the usage of this tool.
void PrintProgramName (std::ostream &os) const override
Print the name of the program to be included in the header.
void add_experimental_setup_gcc_options (bool kill_printf)
add the following GCC options: -fwhole-program -fno-ipa-cp -fno-ipa-cp-clone and -D'printf(fmt, ...)='
Additional Inherited Members
Detailed Description
Definition at line 58 of file BambuParameter.hpp.
Constructor & Destructor Documentation
BambuParameter()
BambuParameter::BambuParameter (const std::string & program_name, int argc, char **const argv)
Constructor.
Parameters
program_name is the name of the executable
argc is the number of arguments
argv is the array of arguments passed to program.
Definition at line 1047 of file BambuParameter.cpp.
References SetDefaults().
 BambuParameter()
BambuParameter::~BambuParameter () [override], [default]
Destructor.
Member Function Documentation
add_bambu_library()
void BambuParameter::add_bambu_library (std::string lib) [private]
add the library to the raw to be considered
Parameters
lib is the name of the library.
Definition at line 3849 of file BambuParameter.cpp.
References Parameter::isOption(), Parameter::setOption(), and STR_CST_string_separator.
Referenced by CheckParameters().
add_experimental_setup_gcc_options()
void BambuParameter::add_experimental_setup_gcc_options (bool kill_printf) [private]
add the following GCC options: -fwhole-program -fno-ipa-cp -fno-ipa-cp-clone and -D'printf(fmt, ...)='
Parameters
kill_printf when true the option -D'printf(fmt, ...)=' added otherwise only the `whole` program options are added
Definition at line 2703 of file BambuParameter.cpp.
References Parameter::isOption(), Parameter::setOption(), STR_CST_string_separator, and THROW_ASSERT.
Referenced by CheckParameters().
CheckParameters()
void BambuParameter::CheckParameters () [override], [private], [virtual]
Check the compatibility among the different parameters and compute implicated parameters.
target device options
DSE options
circuit debugging options
controller options
chaining options
evaluation options
add -I <ac_types_dir> and -I <ac_math_dir>
add experimental setup options
GCC SECTION
CLANG SECTION
default for memory allocation policy
base address and initial internal address checks
Checks
Disable proxy when there are multiple top functions
In case copy input files
When simd is enabled bit value analysis and optimization are disabled
Implements Parameter.
Definition at line 2736 of file BambuParameter.cpp.
References add_bambu_library(), add_evaluation_objective_string(), add_experimental_setup_gcc_options(), ALL_BRAM, Parameter::CheckParameters(), test_panda::command, DATAPATH_CS_CREATOR, tree_helper::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DOMINATOR_FUNCTION_ALLOCATION, DOMINATOR_MEMORY_ALLOCATION_CS, DRY_RUN, EXACT, EXT_PIPELINED_BRAM, FSM_CONTROLLER_CREATOR, FSM_CS_CONTROLLER_CREATOR, Parameter::get_class_debug_level(), Parameter::getOption(), INFERRED_INTERFACE_GENERATION, INTERFACE_CS_GENERATION, INTERN_UNALIGNED, is_evaluation_objective_string(), IsError(), Parameter::isOption(), LSS, MEM_ACC_11, MEM_ACC_CS, MEM_ACC_N1, MEM_ACC_NN, NO_BRAM, NONE, O0, O2, O3, Os, PandaSystem(), test_panda::parameters, SCHED_CHAINING, Parameter::setOption(), SplitString(), STR_CST_concat_c_file, STR_CST_string_separator, THROW_ASSERT, THROW_ERROR, THROW_WARNING, VERILOG, VHDL, WB4_INTERFACE_GENERATION, and XML_MEMORY_ALLOCATOR.
Referenced by Exec().
Exec()
int BambuParameter::Exec () [override], [virtual]
Execute parameter parsing.
flag to check if scheduling algorithm has been already chosen
variable used into option parsing
General options
Frontend options
Scheduling options
Finite state machine options
module binding
register allocation
Memory allocation
evaluation options
target options
Output options
general options
scheduling options
binding options
target options
evaluation
output options
scheduling options
other options
Implements Parameter.
Definition at line 1052 of file BambuParameter.cpp.
References add_evaluation_objective_string(), ALL_BRAM, test_panda::arg, Parameter::argc, Parameter::argv, BIPARTITE_MATCHING, CDFC_MODULE_BINDING, CHANNELS_TYPE_MEM_ACC_11, CHANNELS_TYPE_MEM_ACC_N1, CHANNELS_TYPE_MEM_ACC_NN, CheckParameters(), CHORDAL_COLORING_REGISTER_BINDING, COLORING, COLORING_REGISTER_BINDING, COMMON_LONG_OPTIONS, COMMON_SHORT_OPTIONS_STRING, counter, DOMINATOR_MEMORY_ALLOCATION, EXACT, exit_code, EXT_PIPELINED_BRAM, FIXED_SCHEDULING, FIXED_SCHEDULING_OPT, GCC_LONG_OPTIONS, GCC_SHORT_OPTIONS_STRING, Parameter::GetFileFormat(), GSS, INDENT_OUT_MEX, INFERRED_INTERFACE_GENERATION, INPUT_OPT_C_NO_PARSE, INPUT_OPT_C_PYTHON_NO_PARSE, INPUT_OPT_DRY_RUN_EVALUATION, INPUT_OPT_FILE_INPUT_DATA, INPUT_OPT_FIND_MAX_CFG_TRANSFORMATIONS, INPUT_OPT_TEST_MULTIPLE_NON_DETERMINISTIC_FLOWS, INPUT_OPT_TEST_SINGLE_NON_DETERMINISTIC_FLOW, INTERN_UNALIGNED, Parameter::isOption(), LIST_BASED_SCHEDULING, LSS, Parameter::ManageDefaultOptions(), MEM_ACC_11, MEM_ACC_N1, MEM_ACC_NN, MINIMAL_INTERFACE_GENERATION, MUX_INTERCONNECTION_BINDING, NO_BRAM, NONE, OPT_ACCEPT_NONZERO_RETURN, OPT_ACO_FLOW, OPT_ACO_GENERATIONS, OPT_ADDITIONAL_TOP, OPT_ALIGNED_ACCESS_PARAMETER, OPT_AREA_WEIGHT, OPT_BACKEND_SCRIPT_EXTENSIONS_PARAMETER, OPT_BACKEND_SDC_EXTENSIONS_PARAMETER, OPT_BRAM_HIGH_LATENCY, OPT_CLOCK_NAME, OPT_CLOCK_PERIOD_RESOURCE_FRACTION, OPT_DEVICE_NAME, OPT_DISABLE_BITVALUE_IPA, OPT_DISABLE_BOUNDED_FUNCTION, OPT_DISABLE_FUNCTION_PROXY, OPT_DISABLE_IOB, OPT_DISABLE_REG_INIT_VALUE, OPT_DISCREPANCY, OPT_DISCREPANCY_FORCE, OPT_DISCREPANCY_HW, OPT_DISCREPANCY_NO_LOAD_POINTERS, OPT_DISCREPANCY_ONLY, OPT_DISCREPANCY_PERMISSIVE_PTRS, OPT_DISTRAM_THRESHOLD, OPT_DO_NOT_CHAIN_MEMORIES, OPT_DO_NOT_EXPOSE_GLOBALS, OPT_DO_NOT_USE_ASYNCHRONOUS_MEMORIES, OPT_DONE_NAME, OPT_DSE, OPT_DSP_ALLOCATION_COEFFICIENT, OPT_DSP_MARGIN_COMBINATIONAL, OPT_DSP_MARGIN_PIPELINED, OPT_DUMP_CONSTRAINTS, OPT_DYNAMIC_GENERATORS_DIR, OPT_EVALUATION, OPT_EVALUATION_MODE, OPT_EXPERIMENTAL_SETUP, OPT_FIXED_SCHED, OPT_FLOPOCO, OPT_FSM_ENCODING, OPT_GENERATE_VCD, OPT_GENERATION, OPT_HLS_DIV, OPT_HLS_FPDIV, OPT_HOST_PROFILING, OPT_ILP, OPT_ILP_NEWFORM, OPT_ILP_SOLVER, OPT_INPUT_CONTEXT_SWITCH, OPT_INSERT_VERIFICATION_OPERATION, OPT_LEVEL_RESET, OPT_LIBM_STD_ROUNDING, OPT_LIST_BASED, OPT_LOGICAL_OPTIMIZATION, OPT_MAX_EVALUATIONS, OPT_MAX_INHERITANCE, OPT_MAX_SIM_CYCLES, OPT_MAX_ULP, OPT_MEM_DELAY_READ, OPT_MEM_DELAY_WRITE, OPT_MEMORY_BANKS_NUMBER, OPT_MEMORY_MAPPED_TOP, OPT_MIN_INHERITANCE, OPT_MOSA_FLOW, OPT_NO_MIXED_DESIGN, OPT_NUM_ACCELERATORS, OPT_PARALLEL_CONTROLLER, OPT_PERIOD_CLOCK, OPT_POST_RESCHEDULING, OPT_POWER_OPTIMIZATION, OPT_PRAGMA_PARSE, OPT_PRETTY_PRINT, OPT_REGISTER_ALLOCATION, OPT_REGISTERED_INPUTS, OPT_RESET, OPT_RESET_NAME, OPT_ROM_DUPLICATION, OPT_SCHEDULING_MUX_MARGINS, OPT_SERIALIZE_MEMORY_ACCESSES, OPT_SILP, OPT_SIMULATE, OPT_SKIP_PIPE_PARAMETER, OPT_SOFT_FLOAT, OPT_SOFT_FP, OPT_SOFTFLOAT_SUBNORMAL, OPT_SPECULATIVE, OPT_START_NAME, OPT_STG, OPT_TESTBENCH, OPT_TESTBENCH_EXTRA_GCC_FLAGS, OPT_TIME_WEIGHT, OPT_TIMING_MODEL, OPT_TIMING_VIOLATION, OPT_TOP_FNAME, OPT_TOP_RTLDESIGN_NAME, OPT_UNALIGNED_ACCESS_PARAMETER, OPT_USE_ALUS, OPT_VHDL_LIBRARY_PARAMETER, OPT_VISUALIZER, OPT_XML_CONFIG, OUTPUT_LEVEL_MINIMUM, PAR_LIST_BASED_OPT, PARAMETER_NOTPARSED, PARAMETER_PARSED, PM_BBP, PRINT_MSG, Parameter::PrintUsage(), Parameter::setOption(), SplitString(), STR_CST_string_separator, THROW_ERROR, TrimSpaces(), TS_CLIQUE_COVERING, TS_WEIGHTED_CLIQUE_COVERING, TTT_CLIQUE_COVERING, TTT_CLIQUE_COVERING2, TTT_CLIQUE_COVERING_FAST, TTT_CLIQUE_COVERING_FAST2, UNIQUE_MODULE_BINDING, UNIQUE_REGISTER_BINDING, VERILOG, VHDL, WB4_INTERFACE_GENERATION, WEIGHTED_CLIQUE_REGISTER_BINDING, WEIGHTED_COLORING, Parameter::write_xml_configuration_file(), and XML_MEMORY_ALLOCATOR.
PrintHelp()
void BambuParameter::PrintHelp (std::ostream & os) const [override], [private], [virtual]
Print the usage of this tool.
Parameters
os is the stream where the message has to be printed
Implements Parameter.
Definition at line 353 of file BambuParameter.cpp.
References Parameter::PrintGeneralOptionsUsage(), and Parameter::PrintOutputOptionsUsage().
PrintProgramName()
void BambuParameter::PrintProgramName (std::ostream & os) const [override], [private], [virtual]
Print the name of the program to be included in the header.
Parameters
os is the stream on which the program name has to be printed
Implements Parameter.
Definition at line 1032 of file BambuParameter.cpp.
SetDefaults()
void BambuParameter::SetDefaults () [override], [virtual]
Sets default values.
Revision
Debugging level
maximum execution time: 0 means no time limit
pragmas related
---------- frontend analysis ----------//
---------- HLS process options ----------- //
---------- HLS specification reference ----------- //
High-level synthesis contraints dump -- //
-- Scheduling -- // Scheduling algorithm (default is list based one)
ilp solver
speculative execution flag
-- Module binding -- // module binding algorithm
-- Finite state machine -- // flag to check if finite state machine has to be created
state transition graph creation algorithm
-- Dataflow analysis -- //
-- Register allocation -- // register allocation algorithm
storage value insertion algorithm
Function allocation
Enable function proxy by default
Disable memory mapped interface for top function by default
-- Memory allocation -- //
-- Datapath -- // Datapath interconnection architecture
Datapath architecture
-- Controller -- // target architecture for the controller
-- top entity -- // Output file name for top entity
backend HDL
-- Module Interfaces -- //
-- Module Characterization -- //
-- Module Synthesis -- //
the resulting specification will be a RTL description
-- GCC options -- //
Implements Parameter.
Definition at line 3390 of file BambuParameter.cpp.
References BB_STG_CREATOR, CDFC_MODULE_BINDING, CLASSIC_DATAPATH_CREATOR, CLASSICAL_HLS_SYNTHESIS_FLOW, DEBUG_LEVEL_NONE, DOMINATOR_FUNCTION_ALLOCATION, DOMINATOR_MEMORY_ALLOCATION, DYNAMIC_MOBILITY, FPGA, FSM_CONTROLLER_CREATOR, FSM_NI_SSA_LIVENESS, GetCurrentPath(), Parameter::isOption(), LIST_BASED_SCHEDULING, MINIMAL_INTERFACE_GENERATION, MUX_INTERCONNECTION_BINDING, NONE, NUM_CST_allocation_default_allocation_coefficient, OUTPUT_LEVEL_MINIMUM, Parameter::panda_parameters, PM_NONE, Parameter::setOption(), STANDARD_HLS_FLOW, STR_CST_string_separator, THROW_ERROR, TS_WEIGHTED_CLIQUE_COVERING, VALUES_SCHEME_STORAGE_VALUE_INSERTION, VERILOG, and WEIGHTED_CLIQUE_REGISTER_BINDING.
Referenced by BambuParameter().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/BambuParameter.hpp
/home/osboxes/bambu/PandA-bambu/src/BambuParameter.cpp