WB4Intercon_interface Class Reference
Class generating the top WB4 module.
#include <WB4Intercon_interface.hpp>
Public Member Functions
WB4Intercon_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~WB4Intercon_interface () override
Destructor.
virtual void exec ()
Additional Inherited Members
Detailed Description
Class generating the top WB4 module.
Definition at line 46 of file WB4Intercon_interface.hpp.
Constructor & Destructor Documentation
WB4Intercon_interface()
WB4Intercon_interface::WB4Intercon_interface (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Definition at line 55 of file WB4Intercon_interface.cpp.
References build_bus_interface(), buildCircuit(), HLSFunctionStep::HLS, HLS_step::HLSMgr, WB4_INTERCON_INTERFACE_GENERATION, and ~WB4Intercon_interface().
 WB4Intercon_interface()
WB4Intercon_interface::~WB4Intercon_interface () [override], [default]
Destructor.
Referenced by WB4Intercon_interface().
Member Function Documentation
exec()
void WB4Intercon_interface::exec () [virtual]
Set some descriptions and legal stuff
Definition at line 65 of file WB4Intercon_interface.cpp.
References build_bus_interface(), buildCircuit(), GENERATED_COPYRIGHT, GENERATED_LICENSE, structural_manager::get_circ(), structural_object::get_id(), structural_object::get_typeRef(), structural_type_descriptor::id_type, WB4_interface::InternalExec(), DesignFlowStep::parameters, memory::propagate_memory_parameters(), structural_object::set_id(), structural_object::set_owner(), structural_manager::set_top_info(), and hls::top.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/WB4/WB4Intercon_interface.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/interface/WB4/WB4Intercon_interface.cpp