/home/osboxes/bambu/PandA-bambu/src/HLS/binding/module/cdfc_module_binding.cpp File Reference
Class implementation of the module binding algorithm.
#include `cdfc_module_binding.hpp`
#include `config_HAVE_EXPERIMENTAL.hpp`
#include <boost/filesystem/operations.hpp>
#include `Parameter.hpp`
#include `clique_covering.hpp`
#include `behavioral_writer_helper.hpp`
#include `function_behavior.hpp`
#include `op_graph.hpp`
#include <boost/range/adaptor/reversed.hpp>
#include `graph.hpp`
#include `hls.hpp`
#include `hls_constraints.hpp`
#include `hls_manager.hpp`
#include `hls_target.hpp`
#include `mux_connection_binding.hpp`
#include `fu_binding.hpp`
#include `parallel_memory_fu_binding.hpp`
#include `module_binding_check.hpp`
#include `reg_binding.hpp`
#include `weighted_clique_register.hpp`
#include `design_flow_manager.hpp`
#include `design_flow_step.hpp`
#include `hls_flow_step_factory.hpp`
#include `storage_value_information.hpp`
#include `storage_value_insertion.hpp`
#include `chaining_information.hpp`
#include `liveness.hpp`
#include `memory.hpp`
#include `allocation_information.hpp`
#include `schedule.hpp`
#include `state_transition_graph_manager.hpp`
#include <cmath>
#include <iosfwd>
#include <limits>
#include <string>
#include `custom_map.hpp`
#include `custom_set.hpp`
#include <algorithm>
#include <deque>
#include <list>
#include <utility>
#include <vector>
#include `technology_manager.hpp`
#include `technology_node.hpp`
#include `time_model.hpp`
#include `behavioral_helper.hpp`
#include `tree_helper.hpp`
#include `tree_manager.hpp`
#include `tree_node.hpp`
#include `cpu_time.hpp`
#include `dbgPrintHelper.hpp`
#include `hash_helper.hpp`
#include `string_manipulation.hpp`
Data Structures
struct topological_based_sorting_visitor< OutputIterator >
struct cdfc_resource_ordering_functor
Functor used to compare which of two resources has to be considered first during the binding.
struct slack_based_filtering
class CdfcWriter
class CdfcEdgeWriter
Macros
#define TOOSMALL_NORMALIZED_RESOURCE_AREA 0.9
. include
#define DEFAULT_SMALL_NORMALIZED_RESOURCE_AREA 1.0
#define MODULE_BINDING_MUX_MARGIN 1.0
#define DSP_MARGIN 1.0
#define CLOCK_MARGIN 0.97
Functions
template<typename VertexListGraph , typename OutputIterator , typename P , typename T , typename R >
void topological_based_sorting (const VertexListGraph &g, std::vector< vertex > &c2s, const OpGraphConstRef sdg, OutputIterator result, const boost::bgl_named_params< P, T, R > &params)
template<typename VertexListGraph , typename OutputIterator >
void topological_based_sorting (const VertexListGraph &g, std::vector< vertex > &c2s, const OpGraphConstRef sdg, OutputIterator result)
template<bool do_estimation, bool do_conversion, typename vertex_type , class cluster_type , bool IS_DEBUGGING = true>
void estimate_muxes (const connection_relation &con_rel, unsigned int mux_prec, double &tot_mux_delay, double &tot_mux_area, const cluster_type &cluster, unsigned int &total_muxes, unsigned int &n_shared, const typename std::map< vertex_type, vertex > &converter, const HLS_managerRef HLSMgr, const hlsRef HLS, int debug_level)
static bool compute_condition1 (const std::string &lib_name, const AllocationInformationConstRef allocation_information, double local_mux_time, unsigned int fu_s1)
static bool compute_condition2 (bool cond1, unsigned int fu_prec, double resource_area, const double small_normalized_resource_area)
Detailed Description
Class implementation of the module binding algorithm.
Author
Fabrizio Ferrandi fabrizio.ferrandi@polimi.it $Revision$ $Date$ Last modified by $Author$
Macro Definition Documentation
CLOCK_MARGIN
#define CLOCK_MARGIN 0.97
Definition at line 160 of file cdfc_module_binding.cpp.
Referenced by cdfc_module_binding::InternalExec().
DEFAULT_SMALL_NORMALIZED_RESOURCE_AREA
#define DEFAULT_SMALL_NORMALIZED_RESOURCE_AREA 1.0
Definition at line 157 of file cdfc_module_binding.cpp.
DSP_MARGIN
#define DSP_MARGIN 1.0
Definition at line 159 of file cdfc_module_binding.cpp.
MODULE_BINDING_MUX_MARGIN
#define MODULE_BINDING_MUX_MARGIN 1.0
Definition at line 158 of file cdfc_module_binding.cpp.
Referenced by cdfc_module_binding::InternalExec().
TOOSMALL_NORMALIZED_RESOURCE_AREA
#define TOOSMALL_NORMALIZED_RESOURCE_AREA 0.9
. include
algorithms/clique_covering include behavior includes boost include Graph include HLS includes HLS/binding/interconnection HLS/binding/module include HLS/binding/module include HLS/binding/register include HLS/binding/register/algorithms include required by register binding HLS/binding/storage_value_insertion includes HLS/chaining include HLS/liveness include HLS/memory include HLS/module_allocation include HLS/scheduling include HLS/stg include STD includes STL includes technology include technology/physical_library include technology/physical_library/models include tree includes utility include
Definition at line 156 of file cdfc_module_binding.cpp.
Function Documentation
compute_condition1()
static bool compute_condition1 (const std::string & lib_name, const AllocationInformationConstRef allocation_information, double local_mux_time, unsigned int fu_s1) [inline], [static]
Definition at line 817 of file cdfc_module_binding.cpp.
References AllocationInformation::get_number_channels(), AllocationInformation::get_number_fu(), AllocationInformation::get_worst_number_of_cycles(), INFINITE_UINT, PROXY_LIBRARY, and WORK_LIBRARY.
Referenced by cdfc_module_binding::InternalExec().
compute_condition2()
static bool compute_condition2 (bool cond1, unsigned int fu_prec, double resource_area, const double small_normalized_resource_area) [inline], [static]
Definition at line 825 of file cdfc_module_binding.cpp.
References cdfc_module_binding::small_normalized_resource_area.
Referenced by cdfc_module_binding::InternalExec().
estimate_muxes()
template<bool do_estimation, bool do_conversion, typename vertex_type , class cluster_type , bool IS_DEBUGGING = true>
void estimate_muxes (const connection_relation & con_rel, unsigned int mux_prec, double & tot_mux_delay, double & tot_mux_area, const cluster_type & cluster, unsigned int & total_muxes, unsigned int & n_shared, const typename std::map< vertex_type, vertex > & converter, const HLS_managerRef HLSMgr, const hlsRef HLS, int debug_level)
it is not chained but from the mux binding it counts as input to the mux tree
compute the maximum number of mux ins
Definition at line 318 of file cdfc_module_binding.cpp.
References DEBUG_LEVEL_VERY_PEDANTIC, DFG_SCA_SELECTOR, FB_DFG_SCA_SELECTOR, FunctionBehavior::FDFG, fu_binding::get_assign(), fu_binding::get_index(), fu_binding::get_ports_are_swapped(), INDENT_DBG_MEX, INFINITE_UINT, insert(), max(), no_def, no_phi_chained, no_phi_no_chained, phi, STR, THROW_ASSERT, and THROW_ERROR.
topological_based_sorting() [1/2]
template<typename VertexListGraph , typename OutputIterator , typename P , typename T , typename R >
void topological_based_sorting (const VertexListGraph & g, std::vector< vertex > & c2s, const OpGraphConstRef sdg, OutputIterator result, const boost::bgl_named_params< P, T, R > & params)
Definition at line 188 of file cdfc_module_binding.cpp.
Referenced by cdfc_module_binding::InternalExec(), and topological_based_sorting().
topological_based_sorting() [2/2]
template<typename VertexListGraph , typename OutputIterator >
void topological_based_sorting (const VertexListGraph & g, std::vector< vertex > & c2s, const OpGraphConstRef sdg, OutputIterator result)
Definition at line 195 of file cdfc_module_binding.cpp.
References topological_based_sorting().