module Class Reference
This class describes a generic module.
#include <structural_objects.hpp>
Public Member Functions
module (int debug_level, const structural_objectRef o)
Constructor.
~module () override=default
destructor
unsigned int get_num_ports () const
Return the total number of the ports.
structural_objectRef get_positional_port (unsigned int index) const
return a port of the module given its position
void add_in_port (structural_objectRef p)
Add an input port.
const structural_objectRef get_in_port (unsigned int n) const
Return the ith input port.
unsigned int get_in_port_size () const
Return the number of input ports.
void add_out_port (structural_objectRef p)
Add an output port.
const structural_objectRef get_out_port (unsigned int n) const
Return the ith output port.
unsigned int get_out_port_size () const
Return the number of output ports.
void add_in_out_port (structural_objectRef p)
Add an input-output port.
const structural_objectRef get_in_out_port (unsigned int n) const
Return the ith input-output port.
unsigned int get_in_out_port_size () const
Return the number of output ports.
void add_gen_port (structural_objectRef p)
Add a generic port.
const structural_objectRef get_gen_port (unsigned int n) const
Return the ith generic port.
unsigned int get_gen_port_size () const
Return the number of generic ports.
void remove_port (const std::string &id)
remove a port from the module
void add_internal_object (structural_objectRef c)
Add an internal component/channel/signal/bus_connection_o.
void remove_internal_object (structural_objectRef c)
const structural_objectRef get_internal_object (unsigned int n) const
Return the ith internal objects.
unsigned int get_internal_objects_size () const
Return the number of internal objects.
void add_process (structural_objectRef p)
Add a process to the module.
const structural_objectRef get_process (unsigned int n) const
Return the ith process.
unsigned int get_process_size () const
Return the number of internal processes.
void add_service (structural_objectRef p)
Add a service to the module.
const structural_objectRef get_service (unsigned int n) const
Return the ith service.
unsigned int get_service_size () const
Return the number of services.
void add_event (structural_objectRef e)
Add an event to the module.
const structural_objectRef get_event (unsigned int n) const
Return the ith event.
unsigned int get_event_size () const
Return the number of events.
void add_local_data (structural_objectRef d)
Add a local data.
const structural_objectRef get_local_data (unsigned int n) const
Return the ith local data.
unsigned int get_local_data_size () const
Return the number of local data.
void set_NP_functionality (NP_functionalityRef f)
Set the alternative module behavior descriptions (Non SystemC based).
const NP_functionalityRef & get_NP_functionality () const
Return the alternative functionalities.
void get_NP_library_parameters (structural_objectRef owner, std::vector< std::pair< std::string, structural_objectRef >> &parameters) const
Return the list of object that can be parametrized.
void copy (structural_objectRef dest) const override
Perform a copy of the module.
structural_objectRef find_member (const std::string &id, so_kind type, const structural_objectRef owner) const override
Return the object named id of a given type which belongs to or it is associated with the object.
structural_objectRef find_isomorphic (const structural_objectRef key) const override
Find key in this object.
void xload (const xml_element *Enode, structural_objectRef owner, structural_managerRef const &CM) override=0
Load a structural_object starting from an xml file.
void xwrite (xml_element *rootnode) override=0
Add a structural_object to an xml tree.
bool is_var_args () const
True if one of the ports of the module has the attribute is_var_args=true.
void print (std::ostream &os) const override
Print the module (for debug purpose)
void set_critical ()
set the component as critical with respect to the timing path
bool get_critical () const
return if the component is critical or not
void set_generated ()
set the component as generated
bool get_generated () const
return if the component has been generated or not
void set_multi_unit_multiplicity (unsigned int value)
set_multi_unit_multiplicity
unsigned int get_multi_unit_multiplicity () const
get_multi_unit_multiplicity
void change_port_direction (structural_objectRef port, port_o::port_direction pdir)
change the direction of a port
const std::string get_description () const
Return the description associated with the module.
void set_description (const std::string &d)
Set the description associated with the module.
const std::string get_copyright () const
Return the copyright associated with the module.
void set_copyright (const std::string &c)
Set the copyright associated with the module.
const std::string get_authors () const
Return the authors of the functional description of the module.
void set_authors (const std::string &a)
Set the authors associated with the module.
const std::string get_license () const
Return the license of the functional description of the module.
void set_license (const std::string &l)
Set the license associated with the module.
const std::string get_specialized () const
Return a non-empty string when the component has been specialized.
void set_specialized (const std::string &s)
Set the specialization string.
void AddParameter (const std::string &name, const std::string &default_value) override
Add a parameter.
Private Attributes
std::vector< structural_objectRef > in_ports
input port of this module
std::vector< structural_objectRef > out_ports
output ports of this module
std::vector< structural_objectRef > in_out_ports
Input-output ports of this module.
std::vector< structural_objectRef > gen_ports
generic ports of this module
std::vector< structural_objectRef > internal_objects
internal components/channels/signals/bus_connection_os (for structural modules)
std::vector< structural_objectRef > local_data
List of local data associated with the module.
std::vector< structural_objectRef > list_of_event
List of event associated with the module.
std::vector< structural_objectRef > list_of_process
List of processes associated with the module.
std::vector< structural_objectRef > list_of_service
List of services associated with the module.
NP_functionalityRef NP_descriptions
Alternative descriptions of the behavior of the module.
unsigned int last_position_port
store the last index of the positional binding
bool is_critical
when true the component is involved into the critical path of the netlist
bool is_generated
when true the component has been internally generated
std::map< unsigned int, structural_objectRef > positional_map
positional map, given the index return the port in that position
std::map< std::string, structural_objectRef > index_signals
index for signals this table is used to quickly search internal signals used by find_member and find_isomorphic
std::map< std::string, structural_objectRef > index_constants
index for constants this table is used to quickly search internal constants used by find_member and find_isomorphic
std::map< std::string, structural_objectRef > index_components
index for components this table is used to quickly search internal components used by find_member and find_isomorphic
std::map< std::string, structural_objectRef > index_channels
index for channels this table is used to quickly search internal channels used by find_member and find_isomorphic
std::map< std::string, structural_objectRef > index_bus_connections
index for bus_connections this table is used to quickly search internal bus_connections used by find_member and find_isomorphic
std::string description
Store the module description.
std::string copyright
Store the copyright description.
std::string authors
Store the list of authors.
std::string license
Store some tags concerning the license type associated with the functional unit.
std::string specialized
when non empty it defines with respect what module has been specialized
unsigned int multi_unit_multiplicity
multi-unit multiplicity is the number of units implemented by this module all doing the same thing
Additional Inherited Members
Detailed Description
This class describes a generic module.
A module can be further specialized in a channel or in a component. This class should be not instantiated. Only channels and components can be instantiated.
Definition at line 1788 of file structural_objects.hpp.
Constructor & Destructor Documentation
module()
module::module (int debug_level, const structural_objectRef o)
Constructor.
Parameters
o is the owner of the module.
Definition at line 2434 of file structural_objects.cpp.
 module()
module::~module () [override], [default]
destructor
Member Function Documentation
add_event()
void module::add_event (structural_objectRef e)
Add an event to the module.
Parameters
e is the event.
Definition at line 2784 of file structural_objects.cpp.
References event_o_K, refcount< T >::get(), list_of_event, and THROW_ASSERT.
Referenced by structural_manager::add_constant(), and xload().
add_gen_port()
void module::add_gen_port (structural_objectRef p)
Add a generic port.
Parameters
p is the port.
Definition at line 2542 of file structural_objects.cpp.
References port_o::GEN, gen_ports, refcount< T >::get(), last_position_port, positional_map, and THROW_ASSERT.
Referenced by xload().
add_in_out_port()
void module::add_in_out_port (structural_objectRef p)
Add an input-output port.
Parameters
p is the port.
Definition at line 2521 of file structural_objects.cpp.
References refcount< T >::get(), in_out_ports, port_o::IO, last_position_port, positional_map, and THROW_ASSERT.
Referenced by copy(), and xload().
add_in_port()
void module::add_in_port (structural_objectRef p)
Add an input port.
Parameters
p is the port.
Definition at line 2479 of file structural_objects.cpp.
References refcount< T >::get(), port_o::IN, in_ports, last_position_port, positional_map, and THROW_ASSERT.
Referenced by copy(), functional_unit::get_operation(), and xload().
add_internal_object()
void module::add_internal_object (structural_objectRef c)
Add an internal component/channel/signal/bus_connection_o.
Parameters
c can be a component, channel, signal or a bus_connection_o.
Definition at line 2657 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, refcount< T >::get(), structural_object::get_path(), index_bus_connections, index_channels, index_components, index_constants, index_signals, internal_objects, port_o_K, port_vector_o_K, structural_object::set_black_box(), signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_ERROR.
Referenced by copy(), and xload().
add_local_data()
void module::add_local_data (structural_objectRef d)
Add a local data.
Parameters
d is the local data.
Definition at line 2803 of file structural_objects.cpp.
References data_o_K, refcount< T >::get(), local_data, and THROW_ASSERT.
Referenced by structural_manager::add_constant(), and xload().
add_out_port()
void module::add_out_port (structural_objectRef p)
Add an output port.
Parameters
p is the port .
Definition at line 2500 of file structural_objects.cpp.
References refcount< T >::get(), last_position_port, port_o::OUT, out_ports, positional_map, and THROW_ASSERT.
Referenced by copy(), functional_unit::get_operation(), and xload().
add_process()
void module::add_process (structural_objectRef p)
Add a process to the module.
Parameters
p is the process.
Definition at line 2746 of file structural_objects.cpp.
References action_o_K, refcount< T >::get(), list_of_process, and THROW_ASSERT.
Referenced by structural_manager::add_constant(), and xload().
add_service()
void module::add_service (structural_objectRef p)
Add a service to the module.
Parameters
p is the service.
Definition at line 2765 of file structural_objects.cpp.
References action_o_K, refcount< T >::get(), list_of_service, and THROW_ASSERT.
Referenced by structural_manager::add_constant(), and xload().
AddParameter()
void module::AddParameter (const std::string & name, const std::string & default_value) [override], [virtual]
Add a parameter.
Parameters
name is the name of the parameter
default_value is the default of the value
Reimplemented from structural_object.
Definition at line 3976 of file structural_objects.cpp.
References structural_object::AddParameter(), structural_object::get_id(), NP_functionality::LIBRARY, MEMORY_PARAMETER, and NP_descriptions.
change_port_direction()
void module::change_port_direction (structural_objectRef port, port_o::port_direction pdir)
change the direction of a port
Parameters
port is the port to be moved
pdir is the new direction
Definition at line 3895 of file structural_objects.cpp.
References port_o::GEN, gen_ports, structural_object::get_id(), port_o::IN, in_out_ports, in_ports, port_o::IO, port_o::OUT, out_ports, and THROW_ASSERT.
copy()
void module::copy (structural_objectRef dest) const [override], [virtual]
Perform a copy of the module.
Parameters
dest destination object.
copying of the ports of the module: be aware of respecting the initial order of the ports
copy all the internal objects
it is a port
Reimplemented from structural_object.
Reimplemented in channel_o, and component_o.
Definition at line 2947 of file structural_objects.cpp.
References action_o_K, add_in_out_port(), add_in_port(), add_internal_object(), add_out_port(), authors, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, structural_object::copy(), copyright, data_o_K, structural_object::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, description, event_o_K, port_o::GEN, structural_object::get_path(), structural_object::get_typeRef(), port_o::IN, index_bus_connections, index_channels, index_constants, index_signals, internal_objects, port_o::IO, is_critical, is_generated, last_position_port, license, multi_unit_multiplicity, NP_descriptions, port_o::OUT, port_o_K, port_vector_o_K, positional_map, PRINT_DBG_MEX, set_authors(), set_copyright(), set_critical(), set_description(), set_generated(), set_license(), set_multi_unit_multiplicity(), set_NP_functionality(), signal_o_K, signal_vector_o_K, THROW_ASSERT, THROW_ERROR, port_o::TLM_IN, port_o::TLM_INOUT, port_o::TLM_OUT, and port_o::UNKNOWN.
Referenced by component_o::copy(), and channel_o::copy().
find_isomorphic()
structural_objectRef module::find_isomorphic (const structural_objectRef key) const [override], [virtual]
Find key in this object.
Parameters
key is the object searched.
Implements structural_object.
Reimplemented in channel_o, and component_o.
Definition at line 3222 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, port_o::GEN, gen_ports, structural_object::get_path(), port_o::IN, in_out_ports, in_ports, index_bus_connections, index_channels, index_components, index_constants, index_signals, port_o::IO, port_o::OUT, out_ports, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ERROR, port_o::TLM_IN, port_o::TLM_INOUT, port_o::TLM_OUT, and port_o::UNKNOWN.
Referenced by component_o::find_isomorphic(), and channel_o::find_isomorphic().
find_member()
structural_objectRef module::find_member (const std::string & id, so_kind type, const structural_objectRef owner) const [override], [virtual]
Return the object named id of a given type which belongs to or it is associated with the object.
Parameters
id is the identifier of the object we are looking for.
type is the type of the object we are looking for.
owner is the owner of the object named id.
Implements structural_object.
Reimplemented in channel_o, and component_o.
Definition at line 2848 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, gen_ports, in_out_ports, in_ports, index_bus_connections, index_channels, index_components, index_constants, index_signals, list_of_event, list_of_process, list_of_service, local_data, out_ports, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_ERROR.
Referenced by component_o::find_member(), channel_o::find_member(), get_NP_library_parameters(), TestbenchGenerationBaseStep::init_extra_signals(), TestbenchGenerationBaseStep::write_auxiliary_signal_declaration(), MinimalInterfaceTestbench::write_call(), MinimalInterfaceTestbench::write_file_reading_operations(), MinimalInterfaceTestbench::write_interface_handler(), WishboneInterfaceTestbench::write_memory_handler(), MinimalInterfaceTestbench::write_memory_handler(), TestbenchGenerationBaseStep::write_output_checks(), MinimalInterfaceTestbench::write_signals(), and xload().
get_authors()
const std::string module::get_authors () const [inline]
Return the authors of the functional description of the module.
Definition at line 2197 of file structural_objects.hpp.
Referenced by HDL_manager::write_module().
get_copyright()
const std::string module::get_copyright () const [inline]
Return the copyright associated with the module.
Definition at line 2181 of file structural_objects.hpp.
Referenced by HDL_manager::write_module().
get_critical()
bool module::get_critical () const
return if the component is critical or not
Definition at line 2448 of file structural_objects.cpp.
References is_critical.
get_description()
const std::string module::get_description () const [inline]
Return the description associated with the module.
Definition at line 2165 of file structural_objects.hpp.
Referenced by HDL_manager::write_module().
get_event()
const structural_objectRef module::get_event (unsigned int n) const
Return the ith event.
Parameters
n is the index of the event.
Definition at line 2792 of file structural_objects.cpp.
References list_of_event, and THROW_ASSERT.
get_event_size()
unsigned int module::get_event_size () const
Return the number of events.
Definition at line 2798 of file structural_objects.cpp.
References list_of_event.
get_gen_port()
const structural_objectRef module::get_gen_port (unsigned int n) const
Return the ith generic port.
Parameters
n is the index of the port
Definition at line 2552 of file structural_objects.cpp.
References gen_ports, and THROW_ASSERT.
Referenced by HDL_manager::write_module().
get_gen_port_size()
unsigned int module::get_gen_port_size () const
Return the number of generic ports.
Definition at line 2558 of file structural_objects.cpp.
References gen_ports.
Referenced by HDL_manager::write_module().
get_generated()
bool module::get_generated () const
return if the component has been generated or not
Definition at line 2458 of file structural_objects.cpp.
References is_generated.
get_in_out_port()
const structural_objectRef module::get_in_out_port (unsigned int n) const
Return the ith input-output port.
Parameters
n is the index of the port.
Definition at line 2531 of file structural_objects.cpp.
References in_out_ports, and THROW_ASSERT.
Referenced by HDL_manager::write_module().
get_in_out_port_size()
unsigned int module::get_in_out_port_size () const
Return the number of output ports.
Definition at line 2537 of file structural_objects.cpp.
References in_out_ports.
Referenced by moduleGenerator::GenerateHDL(), HDL_manager::write_module(), and TestbenchGenerationBaseStep::write_underlying_testbench().
get_in_port()
const structural_objectRef module::get_in_port (unsigned int n) const
Return the ith input port.
Parameters
n is the index of the port.
Definition at line 2489 of file structural_objects.cpp.
References structural_object::get_path(), structural_object::get_typeRef(), structural_type_descriptor::id_type, in_ports, STR, and THROW_ASSERT.
Referenced by FunctionalUnitStep::AnalyzeFu(), structural_manager::build_graph(), minimal_interface::build_wrapper(), allocation::BuildProxyWrapper(), moduleGenerator::GenerateHDL(), TestbenchGenerationBaseStep::initialize_input_signals(), is_var_args(), TopEntityMemoryMapped::resizing_IO(), fu_binding::specialise_fu(), conn_binding::specialise_mux(), RTLCharacterization::specialize_fu(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), HDL_manager::write_module(), TestbenchGenerationBaseStep::write_module_instantiation(), MinimalInterfaceTestbench::write_slave_initializations(), verilog_writer::write_timing_specification(), and WishboneInterfaceTestbench::write_wishbone_input_signal_declaration().
get_in_port_size()
unsigned int module::get_in_port_size () const
Return the number of input ports.
Definition at line 2495 of file structural_objects.cpp.
References in_ports.
Referenced by FunctionalUnitStep::AnalyzeFu(), structural_manager::build_graph(), minimal_interface::build_wrapper(), allocation::BuildProxyWrapper(), moduleGenerator::GenerateHDL(), TestbenchGenerationBaseStep::initialize_input_signals(), is_var_args(), TopEntityMemoryMapped::resizing_IO(), fu_binding::specialise_fu(), RTLCharacterization::specialize_fu(), MinimalInterfaceTestbench::write_input_signal_declaration(), MinimalInterfaceTestbench::write_interface_handler(), HDL_manager::write_module(), TestbenchGenerationBaseStep::write_module_instantiation(), MinimalInterfaceTestbench::write_slave_initializations(), verilog_writer::write_timing_specification(), and WishboneInterfaceTestbench::write_wishbone_input_signal_declaration().
get_internal_object()
const structural_objectRef module::get_internal_object (unsigned int n) const
Return the ith internal objects.
Parameters
n is the index of the objects.
Definition at line 2735 of file structural_objects.cpp.
References internal_objects, and THROW_ASSERT.
Referenced by structural_manager::build_graph(), computeResources(), and HDL_manager::write_module().
get_internal_objects_size()
unsigned int module::get_internal_objects_size () const
Return the number of internal objects.
Definition at line 2741 of file structural_objects.cpp.
References internal_objects.
Referenced by structural_manager::build_graph(), computeResources(), HDL_manager::write_module(), and verilog_writer::write_timing_specification().
get_license()
const std::string module::get_license () const [inline]
Return the license of the functional description of the module.
Definition at line 2213 of file structural_objects.hpp.
Referenced by HDL_manager::write_module().
get_local_data()
const structural_objectRef module::get_local_data (unsigned int n) const
Return the ith local data.
Parameters
n represent the index of the local data.
Definition at line 2811 of file structural_objects.cpp.
References local_data, and THROW_ASSERT.
get_local_data_size()
unsigned int module::get_local_data_size () const
Return the number of local data.
Definition at line 2817 of file structural_objects.cpp.
References local_data.
get_multi_unit_multiplicity()
unsigned int module::get_multi_unit_multiplicity () const
get_multi_unit_multiplicity
Returns
the number of units implemented by this module
Definition at line 2468 of file structural_objects.cpp.
References multi_unit_multiplicity.
get_NP_functionality()
const NP_functionalityRef & module::get_NP_functionality () const
Return the alternative functionalities.
Definition at line 2831 of file structural_objects.cpp.
References NP_descriptions.
Referenced by fu_binding::specialise_fu(), HDL_manager::write_module(), verilog_writer::write_present_state_update(), verilog_writer::write_state_declaration(), and verilog_writer::write_timing_specification().
get_NP_library_parameters()
void module::get_NP_library_parameters (structural_objectRef owner, std::vector< std::pair< std::string, structural_objectRef >> & parameters) const
Return the list of object that can be parametrized.
This function is usually used by the backend.
Parameters
owner is the refcount version of this.
Definition at line 2836 of file structural_objects.cpp.
References find_member(), NP_functionality::get_library_parameters(), NP_descriptions, and port_vector_o_K.
get_num_ports()
unsigned int module::get_num_ports () const
Return the total number of the ports.
Definition at line 2438 of file structural_objects.cpp.
References last_position_port.
get_out_port()
const structural_objectRef module::get_out_port (unsigned int n) const
Return the ith output port.
Parameters
n is the index of the port
Definition at line 2510 of file structural_objects.cpp.
References out_ports, and THROW_ASSERT.
Referenced by FunctionalUnitStep::AnalyzeFu(), structural_manager::build_graph(), minimal_interface::build_wrapper(), allocation::BuildProxyWrapper(), moduleGenerator::GenerateHDL(), TestbenchGenerationBaseStep::initialize_input_signals(), TopEntityMemoryMapped::resizing_IO(), fu_binding::specialise_fu(), conn_binding::specialise_mux(), RTLCharacterization::specialize_fu(), HDL_manager::write_module(), TestbenchGenerationBaseStep::write_module_instantiation(), MinimalInterfaceTestbench::write_output_signal_declaration(), verilog_writer::write_state_declaration(), verilog_writer::write_timing_specification(), and WishboneInterfaceTestbench::write_wishbone_output_signal_declaration().
get_out_port_size()
unsigned int module::get_out_port_size () const
Return the number of output ports.
Definition at line 2516 of file structural_objects.cpp.
References out_ports.
Referenced by FunctionalUnitStep::AnalyzeFu(), structural_manager::build_graph(), minimal_interface::build_wrapper(), allocation::BuildProxyWrapper(), moduleGenerator::GenerateHDL(), TestbenchGenerationBaseStep::initialize_input_signals(), TopEntityMemoryMapped::resizing_IO(), fu_binding::specialise_fu(), RTLCharacterization::specialize_fu(), HDL_manager::write_module(), TestbenchGenerationBaseStep::write_module_instantiation(), MinimalInterfaceTestbench::write_output_signal_declaration(), verilog_writer::write_state_declaration(), verilog_writer::write_timing_specification(), and WishboneInterfaceTestbench::write_wishbone_output_signal_declaration().
get_positional_port()
structural_objectRef module::get_positional_port (unsigned int index) const
return a port of the module given its position
Parameters
index is the position of the port.
Definition at line 2473 of file structural_objects.cpp.
References index, positional_map, and THROW_ASSERT.
get_process()
const structural_objectRef module::get_process (unsigned int n) const
Return the ith process.
Parameters
n is the index of the process.
Definition at line 2754 of file structural_objects.cpp.
References list_of_process, and THROW_ASSERT.
get_process_size()
unsigned int module::get_process_size () const
Return the number of internal processes.
Definition at line 2760 of file structural_objects.cpp.
References list_of_process.
get_service()
const structural_objectRef module::get_service (unsigned int n) const
Return the ith service.
Parameters
n is the index of the service.
Definition at line 2773 of file structural_objects.cpp.
References list_of_service, and THROW_ASSERT.
get_service_size()
unsigned int module::get_service_size () const
Return the number of services.
Definition at line 2779 of file structural_objects.cpp.
References list_of_service.
get_specialized()
const std::string module::get_specialized () const [inline]
Return a non-empty string when the component has been specialized.
The string identify with respect what the component has been specialized (e.g., target_device, behavior...)
Definition at line 2230 of file structural_objects.hpp.
is_var_args()
bool module::is_var_args () const
True if one of the ports of the module has the attribute is_var_args=true.
Definition at line 2936 of file structural_objects.cpp.
References get_in_port(), and get_in_port_size().
print()
void module::print (std::ostream & os) const [override], [virtual]
Print the module (for debug purpose)
Parameters
os is an output stream
Reimplemented from structural_object.
Reimplemented in channel_o, and component_o.
Definition at line 3828 of file structural_objects.cpp.
References authors, copyright, description, gen_ports, in_out_ports, in_ports, internal_objects, license, list_of_event, list_of_process, list_of_service, local_data, NP_descriptions, out_ports, structural_object::PP, NP_functionality::print(), and structural_object::print().
Referenced by component_o::print(), and channel_o::print().
remove_internal_object()
void module::remove_internal_object (structural_objectRef c)
Definition at line 2701 of file structural_objects.cpp.
References action_o_K, bus_connection_o_K, channel_o_K, component_o_K, constant_o_K, data_o_K, event_o_K, index_bus_connections, index_channels, index_components, index_signals, internal_objects, port_o_K, port_vector_o_K, signal_o_K, signal_vector_o_K, THROW_ASSERT, and THROW_ERROR.
remove_port()
void module::remove_port (const std::string & id)
remove a port from the module
Parameters
id is the name of the port
Definition at line 2563 of file structural_objects.cpp.
References port_o::GEN, gen_ports, structural_object::get_id(), structural_object::get_path(), port_o::IN, in_out_ports, in_ports, port_o::IO, last_position_port, port_o::OUT, out_ports, positional_map, and THROW_ASSERT.
set_authors()
void module::set_authors (const std::string & a) [inline]
Set the authors associated with the module.
Definition at line 2205 of file structural_objects.hpp.
Referenced by copy().
set_copyright()
void module::set_copyright (const std::string & c) [inline]
Set the copyright associated with the module.
Definition at line 2189 of file structural_objects.hpp.
Referenced by copy().
set_critical()
void module::set_critical ()
set the component as critical with respect to the timing path
Definition at line 2443 of file structural_objects.cpp.
References is_critical.
Referenced by copy().
set_description()
void module::set_description (const std::string & d) [inline]
Set the description associated with the module.
Definition at line 2173 of file structural_objects.hpp.
Referenced by copy().
set_generated()
void module::set_generated ()
set the component as generated
Definition at line 2453 of file structural_objects.cpp.
References is_generated.
Referenced by copy().
set_license()
void module::set_license (const std::string & l) [inline]
Set the license associated with the module.
Definition at line 2221 of file structural_objects.hpp.
Referenced by copy().
set_multi_unit_multiplicity()
void module::set_multi_unit_multiplicity (unsigned int value)
set_multi_unit_multiplicity
Parameters
value is the number of units implemented by this module all doing the same thing
Definition at line 2463 of file structural_objects.cpp.
References multi_unit_multiplicity.
Referenced by copy().
set_NP_functionality()
void module::set_NP_functionality (NP_functionalityRef f)
Set the alternative module behavior descriptions (Non SystemC based).
Parameters
f is the alternative functionalities
Definition at line 2822 of file structural_objects.cpp.
References NP_functionality::exist_NP_functionality(), NP_functionality::FLOPOCO_PROVIDED, NP_functionality::FSM, NP_functionality::FSM_CS, structural_object::get_black_box(), NP_descriptions, NP_functionality::SC_PROVIDED, structural_object::set_black_box(), NP_functionality::SYSTEM_VERILOG_PROVIDED, NP_functionality::VERILOG_FILE_PROVIDED, NP_functionality::VERILOG_PROVIDED, NP_functionality::VHDL_FILE_PROVIDED, and NP_functionality::VHDL_PROVIDED.
Referenced by copy().
set_specialized()
void module::set_specialized (const std::string & s) [inline]
Set the specialization string.
Definition at line 2238 of file structural_objects.hpp.
xload()
void module::xload (const xml_element * Enode, structural_objectRef owner, structural_managerRef const & CM) [override], [pure virtual]
Load a structural_object starting from an xml file.
Parameters
node is a node of the xml tree.
owner is the refcount version of this.
CM is the circuit manager.
if the scope is not included, it means that is an external connection. In this case, go on
it can be connected to a primary scalar port or a constant or a signal
it can be connected to a (scalar) port module or a primary vector port element or a vector signal element check if it is a module
it can be connected to an element of a vector port of a module
Reimplemented from structural_object.
Implemented in channel_o, and component_o.
Definition at line 3386 of file structural_objects.cpp.
References add_event(), add_gen_port(), add_in_out_port(), add_in_port(), add_internal_object(), add_local_data(), add_out_port(), add_process(), add_service(), authors, CE_XVM, component_o_K, constant_o_K, xml_node::convert_escaped(), copyright, structural_object::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, description, find_member(), port_o::GEN, structural_object::get_black_box(), xml_child::get_children(), GET_CLASS_NAME, get_connections(), xml_text_node::get_content(), structural_object::get_id(), structural_object::get_path(), structural_object::get_typeRef(), HIERARCHY_SEPARATOR, port_o::IN, port_o::IO, license, LOAD_XVFM, multi_unit_multiplicity, NP_descriptions, port_o::OUT, port_o_K, port_vector_o_K, PRINT_DBG_MEX, signal_o_K, signal_vector_o_K, specialized, SplitString(), THROW_ASSERT, THROW_ERROR, THROW_WARNING, port_o::TLM_IN, port_o::TLM_INOUT, port_o::TLM_OUT, port_o::to_port_direction(), port_o::UNKNOWN, NP_functionality::xload(), and structural_object::xload().
Referenced by component_o::xload(), and channel_o::xload().
xwrite()
void module::xwrite (xml_element * rootnode) [override], [pure virtual]
Add a structural_object to an xml tree.
Parameters
rootnode is the root node at which the xml representation of the structural object is attached.
Reimplemented from structural_object.
Implemented in channel_o, and component_o.
Definition at line 3720 of file structural_objects.cpp.
References xml_child::add_child_element(), xml_child::add_child_text(), authors, copyright, description, gen_ports, structural_object::get_id(), in_out_ports, in_ports, internal_objects, license, list_of_event, list_of_process, list_of_service, local_data, NP_descriptions, out_ports, specialized, NP_functionality::xwrite(), and structural_object::xwrite().
Referenced by component_o::xwrite(), and channel_o::xwrite().
Field Documentation
authors
std::string module::authors [private]
Store the list of authors.
Definition at line 1859 of file structural_objects.hpp.
Referenced by copy(), print(), xload(), and xwrite().
copyright
std::string module::copyright [private]
Store the copyright description.
Definition at line 1856 of file structural_objects.hpp.
Referenced by copy(), print(), xload(), and xwrite().
description
std::string module::description [private]
Store the module description.
Definition at line 1853 of file structural_objects.hpp.
Referenced by copy(), print(), xload(), and xwrite().
gen_ports
std::vector<structural_objectRef> module::gen_ports [private]
generic ports of this module
Definition at line 1800 of file structural_objects.hpp.
Referenced by add_gen_port(), change_port_direction(), find_isomorphic(), find_member(), get_gen_port(), get_gen_port_size(), print(), remove_port(), and xwrite().
in_out_ports
std::vector<structural_objectRef> module::in_out_ports [private]
Input-output ports of this module.
Definition at line 1797 of file structural_objects.hpp.
Referenced by add_in_out_port(), change_port_direction(), find_isomorphic(), find_member(), get_in_out_port(), get_in_out_port_size(), print(), remove_port(), and xwrite().
in_ports
std::vector<structural_objectRef> module::in_ports [private]
input port of this module
Definition at line 1791 of file structural_objects.hpp.
Referenced by add_in_port(), change_port_direction(), find_isomorphic(), find_member(), get_in_port(), get_in_port_size(), print(), remove_port(), and xwrite().
index_bus_connections
std::map<std::string, structural_objectRef> module::index_bus_connections [private]
index for bus_connections this table is used to quickly search internal bus_connections used by find_member and find_isomorphic
Definition at line 1850 of file structural_objects.hpp.
Referenced by add_internal_object(), copy(), find_isomorphic(), find_member(), and remove_internal_object().
index_channels
std::map<std::string, structural_objectRef> module::index_channels [private]
index for channels this table is used to quickly search internal channels used by find_member and find_isomorphic
Definition at line 1846 of file structural_objects.hpp.
Referenced by add_internal_object(), copy(), find_isomorphic(), find_member(), and remove_internal_object().
index_components
std::map<std::string, structural_objectRef> module::index_components [private]
index for components this table is used to quickly search internal components used by find_member and find_isomorphic
Definition at line 1842 of file structural_objects.hpp.
Referenced by add_internal_object(), find_isomorphic(), find_member(), and remove_internal_object().
index_constants
std::map<std::string, structural_objectRef> module::index_constants [private]
index for constants this table is used to quickly search internal constants used by find_member and find_isomorphic
Definition at line 1838 of file structural_objects.hpp.
Referenced by add_internal_object(), copy(), find_isomorphic(), and find_member().
index_signals
std::map<std::string, structural_objectRef> module::index_signals [private]
index for signals this table is used to quickly search internal signals used by find_member and find_isomorphic
Definition at line 1834 of file structural_objects.hpp.
Referenced by add_internal_object(), copy(), find_isomorphic(), find_member(), and remove_internal_object().
internal_objects
std::vector<structural_objectRef> module::internal_objects [private]
internal components/channels/signals/bus_connection_os (for structural modules)
Definition at line 1803 of file structural_objects.hpp.
Referenced by add_internal_object(), copy(), get_internal_object(), get_internal_objects_size(), print(), remove_internal_object(), and xwrite().
is_critical
bool module::is_critical [private]
when true the component is involved into the critical path of the netlist
Definition at line 1824 of file structural_objects.hpp.
Referenced by copy(), get_critical(), and set_critical().
is_generated
bool module::is_generated [private]
when true the component has been internally generated
Definition at line 1827 of file structural_objects.hpp.
Referenced by copy(), get_generated(), and set_generated().
last_position_port
unsigned int module::last_position_port [private]
store the last index of the positional binding
Definition at line 1821 of file structural_objects.hpp.
Referenced by add_gen_port(), add_in_out_port(), add_in_port(), add_out_port(), copy(), get_num_ports(), and remove_port().
license
std::string module::license [private]
Store some tags concerning the license type associated with the functional unit.
Definition at line 1862 of file structural_objects.hpp.
Referenced by copy(), print(), xload(), and xwrite().
list_of_event
std::vector<structural_objectRef> module::list_of_event [private]
List of event associated with the module.
Definition at line 1809 of file structural_objects.hpp.
Referenced by add_event(), find_member(), get_event(), get_event_size(), print(), and xwrite().
list_of_process
std::vector<structural_objectRef> module::list_of_process [private]
List of processes associated with the module.
Definition at line 1812 of file structural_objects.hpp.
Referenced by add_process(), find_member(), get_process(), get_process_size(), print(), and xwrite().
list_of_service
std::vector<structural_objectRef> module::list_of_service [private]
List of services associated with the module.
Definition at line 1815 of file structural_objects.hpp.
Referenced by add_service(), find_member(), get_service(), get_service_size(), print(), and xwrite().
local_data
std::vector<structural_objectRef> module::local_data [private]
List of local data associated with the module.
Definition at line 1806 of file structural_objects.hpp.
Referenced by add_local_data(), find_member(), get_local_data(), get_local_data_size(), print(), and xwrite().
multi_unit_multiplicity
unsigned int module::multi_unit_multiplicity [private]
multi-unit multiplicity is the number of units implemented by this module all doing the same thing
Definition at line 1868 of file structural_objects.hpp.
Referenced by copy(), get_multi_unit_multiplicity(), set_multi_unit_multiplicity(), and xload().
NP_descriptions
NP_functionalityRef module::NP_descriptions [private]
Alternative descriptions of the behavior of the module.
Definition at line 1818 of file structural_objects.hpp.
Referenced by AddParameter(), copy(), get_NP_functionality(), get_NP_library_parameters(), print(), set_NP_functionality(), xload(), and xwrite().
out_ports
std::vector<structural_objectRef> module::out_ports [private]
output ports of this module
Definition at line 1794 of file structural_objects.hpp.
Referenced by add_out_port(), change_port_direction(), find_isomorphic(), find_member(), get_out_port(), get_out_port_size(), print(), remove_port(), and xwrite().
positional_map
std::map<unsigned int, structural_objectRef> module::positional_map [private]
positional map, given the index return the port in that position
Definition at line 1830 of file structural_objects.hpp.
Referenced by add_gen_port(), add_in_out_port(), add_in_port(), add_out_port(), copy(), get_positional_port(), and remove_port().
specialized
std::string module::specialized [private]
when non empty it defines with respect what module has been specialized
Definition at line 1865 of file structural_objects.hpp.
Referenced by xload(), and xwrite().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.hpp
/home/osboxes/bambu/PandA-bambu/src/circuit/structural_objects.cpp