Quartus13ReportWrapper Class Reference
Main class for wrapping quartus_report tool by Altera.
#include <quartus_13_report_wrapper.hpp>
Public Member Functions
Quartus13ReportWrapper (const ParameterConstRef &Param, const std::string &_output_dir, const target_deviceRef &_device)
Constructor.
~Quartus13ReportWrapper () override
Destructor.
std::string get_command_line (const DesignParametersRef &dp) const override
Returns the proper command line.
Protected Member Functions
void EvaluateVariables (const DesignParametersRef dp) override
Evaluates the design variables.
Additional Inherited Members
Detailed Description
Main class for wrapping quartus_report tool by Altera.
Definition at line 55 of file quartus_13_report_wrapper.hpp.
Constructor & Destructor Documentation
Quartus13ReportWrapper()
Quartus13ReportWrapper::Quartus13ReportWrapper (const ParameterConstRef & Param, const std::string & _output_dir, const target_deviceRef & _device)
Constructor.
Parameters
Param is the set of parameters
Definition at line 56 of file quartus_13_report_wrapper.cpp.
References SynthesisTool::debug_level, DEBUG_LEVEL_PEDANTIC, PRINT_DBG_MEX, and ~Quartus13ReportWrapper().
 Quartus13ReportWrapper()
Quartus13ReportWrapper::~Quartus13ReportWrapper () [override], [default]
Destructor.
Referenced by Quartus13ReportWrapper().
Member Function Documentation
EvaluateVariables()
void Quartus13ReportWrapper::EvaluateVariables (const DesignParametersRef dp) [override], [protected], [virtual]
Evaluates the design variables.
Reimplemented from SynthesisTool.
Definition at line 64 of file quartus_13_report_wrapper.cpp.
References DesignParameters::component_name, SynthesisTool::output_dir, PARAM_quartus_report, and DesignParameters::parameter_values.
get_command_line()
std::string Quartus13ReportWrapper::get_command_line (const DesignParametersRef & dp) const [override], [virtual]
Returns the proper command line.
Implements AlteraWrapper.
Definition at line 70 of file quartus_13_report_wrapper.cpp.
References SynthesisTool::get_tool_exec(), SynthesisTool::replace_parameters(), SynthesisTool::script_name, AlteraWrapper::toString(), and SynthesisTool::xml_tool_options.
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_13_report_wrapper.hpp
/home/osboxes/bambu/PandA-bambu/src/wrapper/synthesis/altera/quartus_13_report_wrapper.cpp