BM_cost_functor Struct Reference
Base class functor used bipartite_matching to manage the costs.
#include <bipartite_matching.hpp>
Public Member Functions
virtual ~BM_cost_functor ()
Destructor.
virtual int operator() (size_t x, size_t y) const =0
This functor returns a cost given x and y.
virtual int max_row (size_t x) const =0
return the maximum cost for a given row
Detailed Description
Base class functor used bipartite_matching to manage the costs.
Definition at line 55 of file bipartite_matching.hpp.
Constructor & Destructor Documentation
 BM_cost_functor()
virtual BM_cost_functor::~BM_cost_functor () [inline], [virtual]
Destructor.
Definition at line 58 of file bipartite_matching.hpp.
References max_row(), and operator()().
Member Function Documentation
max_row()
virtual int BM_cost_functor::max_row (size_t x) const [pure virtual]
return the maximum cost for a given row
Parameters
x is the index of the row
Implemented in full_cost_matrix, and y_independent_cost.
Referenced by ~BM_cost_functor().
operator()()
virtual int BM_cost_functor::operator() (size_t x, size_t y) const [pure virtual]
This functor returns a cost given x and y.
Parameters
x is the index of the row
y is the index of the column
Implemented in full_cost_matrix, and y_independent_cost.
Referenced by ~BM_cost_functor().
The documentation for this struct was generated from the following file:
/home/osboxes/bambu/PandA-bambu/src/algorithms/bipartite_matching/bipartite_matching.hpp