/home/osboxes/bambu/PandA-bambu/src/parser/discrepancy/parse_discrepancy.cpp File Reference
#include `config_HAVE_BISON_2_7_OR_GREATER.hpp`
#include `parse_discrepancy.hpp`
#include <iostream>
#include `discrepancyParser.h`
#include `exceptions.hpp`
Functions
REF_FORWARD_DECL (Discrepancy)
void discrepancy_parseY (const std::string &fname, DiscrepancyRef Discrepancy)
void parse_discrepancy (const std::string &c_trace_filename, DiscrepancyRef Discrepancy)
Function Documentation
discrepancy_parseY()
void discrepancy_parseY (const std::string & fname, DiscrepancyRef Discrepancy)
Referenced by parse_discrepancy().
parse_discrepancy()
void parse_discrepancy (const std::string & c_trace_filename, DiscrepancyRef Discrepancy)
Definition at line 55 of file parse_discrepancy.cpp.
References discrepancy_parseY(), and THROW_ERROR.
Referenced by HWDiscrepancyAnalysis::Exec(), and vcd_utility::Exec().
REF_FORWARD_DECL()
REF_FORWARD_DECL (Discrepancy)
Author
Pietro Fezzardi pietrofezzardi@gmail.com