BB_based_stg Class Reference
#include <BB_based_stg.hpp>
Public Member Functions
BB_based_stg (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
~BB_based_stg () override
Destructor.
DesignFlowStep_Status InternalExec () override
Execute the step.
void Initialize () override
Initialize the step (i.e., like a constructor, but executed just before exec.
Protected Member Functions
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const override
Compute the relationship of this step.
Private Member Functions
void optimize_cycles (vertex bbEndingCycle, CustomUnorderedMap< vertex, vertex > &first_state, CustomUnorderedMap< vertex, vertex > &last_state, std::map< vertex, std::list< vertex >> &global_starting_ops, std::map< vertex, std::list< vertex >> &global_ending_ops, std::map< vertex, std::list< vertex >> &global_executing_ops, std::map< vertex, std::list< vertex >> &global_onfly_ops)
Given two bb linked by a forwarding edge, this method tries to move overlap the execution of the last state of the bb ending the cycle with the execution of the first state of the bb that begins the cycle.
bool can_be_moved (std::list< vertex > &lastStateEndingOp, std::list< vertex > &lastStateConditionalOpList, vertex firstStateNextBb, std::map< vertex, std::list< vertex >> &global_starting_ops, std::map< vertex, std::list< vertex >> &global_executing_ops)
Returns true if all the operations in the list can be moved to the state specified.
vertex check_data_dependency (vertex operation, vertex state, std::map< vertex, std::list< vertex >> &global_starting_ops, std::map< vertex, std::list< vertex >> &global_executing_ops)
This method takes as parameters an operation and a state of the STG graph, and returns the operation that needs the output of the given operation in the given state, NULL otherwise.
bool is_instantaneous_operation (vertex operation)
returns true if the operation takes no time
bool res_const_operation (vertex &operation, std::list< vertex > &lastStateExecutingOpList, vertex lastSt)
returns true if the number of fu available prevents us from moving that operation in the next state
void compute_use_def (const std::list< vertex > &opEndingList, const std::list< vertex > &opRuningList, const std::list< vertex > &ignoreList, CustomOrderedSet< unsigned int > &useSet, CustomOrderedSet< unsigned int > &defSet, const OpGraphConstRef data)
computes the variables used and defined in the by the given list of operations, and saves them in the two sets.
void move_without_duplication (const vertex stateToMove, const vertex secondLastState, const vertex dest_first_state, const std::map< vertex, std::list< vertex >> &global_starting_ops, const std::map< vertex, std::list< vertex >> &global_executing_ops, const std::map< vertex, std::list< vertex >> &global_ending_ops, const CustomOrderedSet< unsigned int > &defSet, const CustomOrderedSet< unsigned int > &useSet)
Copies all the operations of the state to move in the following.
void move_with_duplication (const vertex stateToMove, const vertex secondLastState, const vertex dest_first_state, const std::map< vertex, std::list< vertex >> &global_starting_ops, const std::map< vertex, std::list< vertex >> &global_executing_ops, const std::map< vertex, std::list< vertex >> &global_ending_ops, const CustomOrderedSet< unsigned int > &defSet, const CustomOrderedSet< unsigned int > &useSet)
Duplicates the first state of the destination bb and copies all the operations of the state to move in the new state.
void compute_EPP_edge_increments (const std::map< vertex, std::list< vertex >> &starting_ops) const
If hardware discrepancy analysis is activated, use this function to compute the edge increments for the Efficient Path Profiling (EPP) on the STG.
Additional Inherited Members
Detailed Description
Definition at line 50 of file BB_based_stg.hpp.
Constructor & Destructor Documentation
BB_based_stg()
BB_based_stg::BB_based_stg (const ParameterConstRef Param, const HLS_managerRef HLSMgr, unsigned int funId, const DesignFlowManagerConstRef design_flow_manager)
Constructor.
Header include.
Parameters
design_flow_manager is the design flow manager
. include algorithms/loop_detection includes behavior include boost includes HLS includes HLS/binding/module include HLS/function_allocation include HLS/module_allocation include HLS/scheduling include HLS/stg includes HLS/vcd includes STD include technology includes technology/physical_library/models include tree include HLS/module_allocation include utility include
Definition at line 130 of file BB_based_stg.cpp.
References BB_STG_CREATOR, DesignFlowStep::debug_level, GET_CLASS, and ~BB_based_stg().
 BB_based_stg()
BB_based_stg::~BB_based_stg () [override], [default]
Destructor.
Referenced by BB_based_stg().
Member Function Documentation
can_be_moved()
bool BB_based_stg::can_be_moved (std::list< vertex > & lastStateEndingOp, std::list< vertex > & lastStateConditionalOpList, vertex firstStateNextBb, std::map< vertex, std::list< vertex >> & global_starting_ops, std::map< vertex, std::list< vertex >> & global_executing_ops) [private]
Returns true if all the operations in the list can be moved to the state specified.
Operations contained in the vertx list lastStateConditionalOpList will be ignored in the analysis. This method works fine only if the list of operation contains all the operations executed in a state preceding the one passed as a parameter.
Definition at line 1326 of file BB_based_stg.cpp.
References check_data_dependency(), and is_instantaneous_operation().
Referenced by optimize_cycles().
check_data_dependency()
vertex BB_based_stg::check_data_dependency (vertex operation, vertex state, std::map< vertex, std::list< vertex >> & global_starting_ops, std::map< vertex, std::list< vertex >> & global_executing_ops) [private]
This method takes as parameters an operation and a state of the STG graph, and returns the operation that needs the output of the given operation in the given state, NULL otherwise.
This method takes as parameters an operation and a state of the STG graph, and returns the operation that needs the output of the given operation in the given state, nullptr otherwise.
If the result of the given operation is read by a phi operation chained with a second operation, a pointer to that second operation is returned. In case the result of the given operation is read by a phi which is not chained to any other operation, and no other operation needs the output of the given operation, a pointer to the phi itself is returned.
NOTICE that a phi is treated as a weaker dependance, because it can be solved via chaining. A phi is returned only if no stronger data dependency is found.
If the result of the given operation is read by a phi operation chained with a second operation, a pointer to that second operation is returned. In case the result of the given operation is read by a phi which is not chained to any other operation, and no other operation needs the output of the given operation, a pointer to the phi itself is returned.
NOTICE that an instantaneous operation is treated as a weaker dependence, because it can be solved via chaining. An instantaneous operation is returned only if no stronger data dependency is found.
Definition at line 1371 of file BB_based_stg.cpp.
References FunctionBehavior::DFG, HLSFunctionStep::funId, HLS_step::HLSMgr, and is_instantaneous_operation().
Referenced by can_be_moved().
compute_EPP_edge_increments()
void BB_based_stg::compute_EPP_edge_increments (const std::map< vertex, std::list< vertex >> & starting_ops) const [private]
If hardware discrepancy analysis is activated, use this function to compute the edge increments for the Efficient Path Profiling (EPP) on the STG.
Details on EPP and on the algorithm to compute edge increments are here: Thomas Ball and James R. Larus. 1996. Efficient path profiling. In Proceedings of the 29th annual ACM/IEEE international symposium on Microarchitecture (MICRO 29). IEEE Computer Society, Washington, DC, USA, 46-57.
Parameters
starting_ops maps every state to a list of operations starting in that state. They are necessary to compute a set of states when the HW discrepancy analysis has to check the EPP trace, in addition to states before taking feedback edges.
Definition at line 844 of file BB_based_stg.cpp.
References add_EPP_edges(), hls::allocation_information, StateTransitionGraphManager::CGetEPPStg(), OpGraph::CGetOpNodeInfo(), StateTransitionGraphManager::CGetStg(), compute_edge_increments(), DesignFlowStep::debug_level, DEBUG_LEVEL_PEDANTIC, DEBUG_LEVEL_VERBOSE, FunctionBehavior::DFG, HWDiscrepancyInfo::fu_id_control_flow_skip, HWDiscrepancyInfo::fu_id_to_epp_trace_bitsize, HWDiscrepancyInfo::fu_id_to_feedback_states_to_check, HWDiscrepancyInfo::fu_id_to_max_epp_path_val, HWDiscrepancyInfo::fu_id_to_reset_edges, HWDiscrepancyInfo::fu_id_to_states_to_check, HLSFunctionStep::funId, fu_binding::get_assign(), AllocationInformation::get_fu(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, tree_helper::normalized_ID(), DesignFlowStep::parameters, hls::Rfu, hls::STG, STR, and THROW_ASSERT.
Referenced by InternalExec().
compute_use_def()
void BB_based_stg::compute_use_def (const std::list< vertex > & opEndingList, const std::list< vertex > & opRuningList, const std::list< vertex > & ignoreList, CustomOrderedSet< unsigned int > & useSet, CustomOrderedSet< unsigned int > & defSet, const OpGraphConstRef data) [private]
computes the variables used and defined in the by the given list of operations, and saves them in the two sets.
operations included in the ignoreList will not be considered in this analysis.
Definition at line 1481 of file BB_based_stg.cpp.
References OpGraph::CGetOpNodeInfo(), DEFINITION, HLS_step::HLSMgr, SCALAR, and USE.
Referenced by optimize_cycles().
ComputeHLSRelationships()
const CustomUnorderedSet< std::tuple< HLSFlowStep_Type, HLSFlowStepSpecializationConstRef, HLSFlowStep_Relationship > > BB_based_stg::ComputeHLSRelationships (const DesignFlowStep::RelationshipType relationship_type) const [override], [protected], [virtual]
Compute the relationship of this step.
Parameters
relationship_type is the type of relationship to be considered
Returns
the steps in relationship with this
Reimplemented from HLS_step.
Definition at line 160 of file BB_based_stg.cpp.
References DesignFlowStep::DEPENDENCE_RELATIONSHIP, DesignFlowStep::INVALIDATION_RELATIONSHIP, LIST_BASED_SCHEDULING, DesignFlowStep::parameters, DesignFlowStep::PRECEDENCE_RELATIONSHIP, SAME_FUNCTION, and THROW_UNREACHABLE.
Initialize()
void BB_based_stg::Initialize () [override], [virtual]
Initialize the step (i.e., like a constructor, but executed just before exec.
Reimplemented from HLSFunctionStep.
Definition at line 138 of file BB_based_stg.cpp.
References HLSFunctionStep::HLS, HLS_step::HLSMgr, HLSFunctionStep::Initialize(), DesignFlowStep::parameters, and hls::STG.
InternalExec()
DesignFlowStep_Status BB_based_stg::InternalExec () [override], [virtual]
Execute the step.
Returns
the exit status of this step
first state of a basic-block
last state of a basic-block
get entry and exit basic block
contains the list of operations which are executing, starting, ending and `on-fly` in every state of the STG
the analysis has to be performed only on the reachable functions functions to be analyzed
for basic block connected only to entry bb
add an empty state before the current basic block
check if virtual phi can be removed and so its basic block
connect two states belonging to different basic blocks concurrently manage entry and exit state and completely merged basic blocks
removed the edge from entry to exit
compute the controlling vertex
Call optimize_cycles for every cycle in the stg
check for unbounded op executed in the last step this ops creates problems with done port registering
Implements HLSFunctionStep.
Definition at line 193 of file BB_based_stg.cpp.
References add_in_sched_order(), StateTransitionGraphManager::add_multi_unbounded_obj(), ALL_FINISHED, hls::allocation_information, FunctionBehavior::BB, hls::call_sites_number, FunctionBehavior::CFG, CFG_SELECTOR, BBGraph::CGetBBEdgeInfo(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), OpGraph::CGetOpNodeInfo(), StateTransitionGraphManager::CGetStg(), compute_EPP_edge_increments(), StateTransitionGraphManager::compute_min_max(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, default_COND, FunctionBehavior::DFG, AllocationInformation::EstimateControllerDelay(), F_COND, FALSE_COND, FB_CFG_SELECTOR, FunctionBehavior::FBB, HLSFunctionStep::funId, fu_binding::get_assign(), Schedule::get_cstep(), Schedule::get_cstep_end(), StateTransitionGraphManager::get_entry_state(), StateTransitionGraphManager::get_exit_state(), AllocationInformation::get_fu(), AllocationInformation::get_initiation_time(), GET_NAME, StateTransitionGraphManager::get_state_name(), GET_TYPE, AllocationInformation::getMinimumSlack(), graph::GetSelector(), StateTransitionGraphManager::GetStg(), HLSFunctionStep::HLS, HLS_step::HLSMgr, INDENT_DBG_MEX, INDENT_OUT_MEX, max(), min, AllocationInformation::mux_time_unit(), tree_helper::normalized_ID(), NOT_ALL_FINISHED, optimize_cycles(), DesignFlowStep::output_level, OUTPUT_LEVEL_MINIMUM, OUTPUT_LEVEL_PEDANTIC, OUTPUT_LEVEL_VERBOSE, hls::Param, DesignFlowStep::parameters, print_cpu_time(), PRINT_DBG_MEX, StateTransitionGraphManager::print_statistics(), hls::registered_done_port, hls::registered_inputs, hls::Rfu, hls::Rsch, START_TIME, hls::STG, StateTransitionGraphManager::STG_builder, STOP_TIME, STR, SUCCESS, T_COND, THROW_ASSERT, TRUE_COND, TYPE_GOTO, TYPE_PHI, TYPE_VPHI, and WB4_INTERFACE_GENERATION.
is_instantaneous_operation()
bool BB_based_stg::is_instantaneous_operation (vertex operation) [private]
returns true if the operation takes no time
Definition at line 1412 of file BB_based_stg.cpp.
References ASSIGN, OpGraph::CGetOpNodeInfo(), CONVERT_EXPR, FunctionBehavior::DFG, HLSFunctionStep::funId, GET_TYPE, HLS_step::HLSMgr, NOP_EXPR, TYPE_PHI, and VIEW_CONVERT_EXPR.
Referenced by can_be_moved(), and check_data_dependency().
move_with_duplication()
void BB_based_stg::move_with_duplication (const vertex stateToMove, const vertex secondLastState, const vertex stateToClone, const std::map< vertex, std::list< vertex >> & global_starting_ops, const std::map< vertex, std::list< vertex >> & global_executing_ops, const std::map< vertex, std::list< vertex >> & global_ending_ops, const CustomOrderedSet< unsigned int > & defSet, const CustomOrderedSet< unsigned int > & useSet) [private]
Duplicates the first state of the destination bb and copies all the operations of the state to move in the new state.
An edge is created from the second last state to the new state, and outgoing edges are created from the new state to all the states that follows the first state of the destination bb. The state to move, and all the edges to/from it are not modified by this method.
Definition at line 1596 of file BB_based_stg.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, StateTransitionGraphManager::GetStg(), HLSFunctionStep::HLS, INDENT_DBG_MEX, hls::STG, StateTransitionGraphManager::STG_builder, and THROW_ASSERT.
Referenced by optimize_cycles().
move_without_duplication()
void BB_based_stg::move_without_duplication (const vertex stateToMove, const vertex secondLastState, const vertex destinationState, const std::map< vertex, std::list< vertex >> & global_starting_ops, const std::map< vertex, std::list< vertex >> & global_executing_ops, const std::map< vertex, std::list< vertex >> & global_ending_ops, const CustomOrderedSet< unsigned int > & defSet, const CustomOrderedSet< unsigned int > & useSet) [private]
Copies all the operations of the state to move in the following.
An edge is created from the second last state to the destination state. The state to move, and all the edges to/from it are not modified by this method.
Definition at line 1527 of file BB_based_stg.cpp.
References DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, StateTransitionGraphManager::get_state_name(), StateTransitionGraphManager::GetStg(), HLSFunctionStep::HLS, INDENT_DBG_MEX, hls::STG, and StateTransitionGraphManager::STG_builder.
Referenced by optimize_cycles().
optimize_cycles()
void BB_based_stg::optimize_cycles (vertex bbEndingCycle, CustomUnorderedMap< vertex, vertex > & first_state, CustomUnorderedMap< vertex, vertex > & last_state, std::map< vertex, std::list< vertex >> & global_starting_ops, std::map< vertex, std::list< vertex >> & global_ending_ops, std::map< vertex, std::list< vertex >> & global_executing_ops, std::map< vertex, std::list< vertex >> & global_onfly_ops) [private]
Given two bb linked by a forwarding edge, this method tries to move overlap the execution of the last state of the bb ending the cycle with the execution of the first state of the bb that begins the cycle.
If the exit vertex follows the ending bb, I cannot perform any optimization. The same happen for next BBs having a multi way if, load, store or return operations.
Definition at line 949 of file BB_based_stg.cpp.
References hls::allocation_information, can_be_moved(), BBGraph::CGetBBGraphInfo(), BBGraph::CGetBBNodeInfo(), OpGraph::CGetOpNodeInfo(), StateTransitionGraphManager::CGetStg(), compute_use_def(), DesignFlowStep::debug_level, DEBUG_LEVEL_VERY_PEDANTIC, DEFINITION, FunctionBehavior::DFG, FunctionBehavior::FBB, HLSFunctionStep::funId, fu_binding::get_assign(), AllocationInformation::get_fu(), GET_TYPE, StateTransitionGraphManager::GetStg(), HLSFunctionStep::HLS, HLS_step::HLSMgr, move_with_duplication(), move_without_duplication(), tree_helper::normalized_ID(), PRINT_DBG_MEX, res_const_operation(), hls::Rfu, SCALAR, hls::STG, StateTransitionGraphManager::STG_builder, STR, TYPE_EXTERNAL, TYPE_IF, TYPE_LOAD, TYPE_MULTIIF, TYPE_PHI, TYPE_RET, TYPE_STORE, TYPE_SWITCH, and TYPE_VPHI.
Referenced by InternalExec().
res_const_operation()
bool BB_based_stg::res_const_operation (vertex & operation, std::list< vertex > & lastStateExecutingOpList, vertex lastSt) [private]
returns true if the number of fu available prevents us from moving that operation in the next state
Definition at line 1439 of file BB_based_stg.cpp.
References hls::allocation_information, StateTransitionGraphManager::CGetStg(), fu_binding::get_assign(), AllocationInformation::get_number_fu(), StateTransitionGraphManager::GetStg(), HLSFunctionStep::HLS, INFINITE_UINT, hls::Rfu, and hls::STG.
Referenced by optimize_cycles().
The documentation for this class was generated from the following files:
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/BB_based_stg.hpp
/home/osboxes/bambu/PandA-bambu/src/HLS/stg/BB_based_stg.cpp